# -*- coding: utf-8 -*-
"""40-Day devotional maps — Batch 10 (nums 70-75): Money & the Heart.
6 movements aligned to the 6 sessions, 40 days in a 7-7-7-7-7-5 arc."""

MAPS = {
 # ---------------- 70 · The Idol of Money ----------------
 70: [
  {"roman":"I","title":"The Quiet Bid","subtitle":"Money's Claim on the Heart","days":[
   (1,"Money's Quiet Bid","For the heart's throne","Matt 6:24; Col 3:5"),
   (2,"A Subtle Idol","Rarely named as one","Col 3:5; Eph 5:5"),
   (3,"The Heart's True Worship","Where devotion goes","Matt 6:21; Ps 62:10"),
   (4,"Mammon Speaks Softly","Promising security","Matt 6:24; Luke 12:19"),
   (5,"When Money Becomes Master","The slow takeover","Matt 6:24; 1 Tim 6:10"),
   (6,"Whom Do You Serve?","The honest question","Luke 16:13; Josh 24:15"),
   (7,"The Quiet Bid","Money's claim exposed","Matt 6:24; Col 3:5"),
  ]},
  {"roman":"II","title":"Two Masters","subtitle":"Only One Can Reign","days":[
   (8,"No One Can Serve Two","The clear teaching","Matt 6:24; Luke 16:13"),
   (9,"Love One, Hate the Other","Divided loyalty fails","Matt 6:24; 1 Kgs 18:21"),
   (10,"God and Money","The rivalry named","Matt 6:24; Luke 16:13"),
   (11,"You Cannot Serve Both","A choice required","Matt 6:24; Josh 24:15"),
   (12,"Devoted to One","Despising the other","Matt 6:24; Jas 4:4"),
   (13,"The Undivided Heart","Wholly the Lord's","Ps 86:11; Matt 6:24"),
   (14,"Two Masters","Only one can reign","Matt 6:24; Luke 16:13"),
  ]},
  {"roman":"III","title":"The False God's Promise","subtitle":"Exposed as Empty","days":[
   (15,"The Promise of Security","Money's false offer","Prov 18:11; Ps 62:10"),
   (16,"A Fortress in Imagination","The illusion","Prov 18:11; 1 Tim 6:17"),
   (17,"Riches Cannot Save","In the day of wrath","Prov 11:4; Zeph 1:18"),
   (18,"Wealth That Can't Redeem","No ransom for a life","Ps 49:6-9; Mark 8:37"),
   (19,"The Empty Guarantee","Money fails us","Eccl 5:10; Luke 12:20"),
   (20,"Trusting the Untrustworthy","A broken refuge","Prov 11:28; Jer 17:5"),
   (21,"The False God's Promise","Exposed as empty","Ps 62:10; Prov 11:28"),
  ]},
  {"roman":"IV","title":"Spotting the Idol","subtitle":"Naming It Honestly","days":[
   (22,"Examine the Heart","Where is your trust?","Ps 139:23-24; Prov 4:23"),
   (23,"What Keeps You Up?","The anxiety test","Matt 6:25; Luke 12:22-25"),
   (24,"What Do You Boast In?","The pride test","Jer 9:23-24; Ps 49:6"),
   (25,"Where Does Your Mind Go?","The daydream test","Matt 6:21; Col 3:1-2"),
   (26,"What Can't You Give?","The grip test","Luke 18:22-23; Acts 5:1-4"),
   (27,"Greed Is Idolatry","The blunt diagnosis","Col 3:5; Eph 5:5"),
   (28,"Spotting the Idol","Naming it honestly","Col 3:5; Ps 139:23-24"),
  ]},
  {"roman":"V","title":"Dethroning Money","subtitle":"The Idol Toppled","days":[
   (29,"Put Greed to Death","Idolatry slain","Col 3:5; Rom 8:13"),
   (30,"Tear Down the Idol","Off the throne","2 Kgs 23:24; 1 John 5:21"),
   (31,"Give to Break Its Power","Generosity dethrones","Luke 12:33; Acts 20:35"),
   (32,"Set Your Heart Above","Where Christ is","Col 3:1-2; Matt 6:20-21"),
   (33,"Keep From Idols","The closing charge","1 John 5:21; Ex 20:3-4"),
   (34,"Trust the Living God","Not uncertain riches","1 Tim 6:17; Ps 62:10"),
   (35,"Dethroning Money","The idol toppled","Matt 6:24; Col 3:5"),
  ]},
  {"roman":"VI","title":"One Master","subtitle":"God on the Throne","days":[
   (36,"The Lord Alone","One throne, one King","Matt 6:24; Deut 6:4-5"),
   (37,"Free to Serve God","No longer money's slave","Matt 6:24; Rom 6:18"),
   (38,"Money as Servant","Restored to its place","Matt 6:24; Luke 16:9"),
   (39,"An Undivided Heart","Wholly His","Ps 86:11; Matt 6:24"),
   (40,"One Master","God on the throne","Matt 6:24; Luke 16:13"),
  ]},
 ],
 # ---------------- 71 · You Are Not Your Net Worth ----------------
 71: [
  {"roman":"I","title":"The Number That Defines Us","subtitle":"The Lie Examined","days":[
   (1,"The Defining Number","Net worth as identity","1 Sam 16:7; Luke 12:15"),
   (2,"Worth Measured in Dollars?","The culture's lie","Luke 12:15; Ps 49:16-17"),
   (3,"The Tyranny of Comparison","Always measuring","2 Cor 10:12; Gal 6:4"),
   (4,"When the Number Is Low","The shame of less","1 Sam 16:7; Jas 2:5"),
   (5,"When the Number Is High","The pride of more","Jer 9:23; Deut 8:17-18"),
   (6,"More Than a Balance Sheet","You are not a number","1 Sam 16:7; Ps 139:13-14"),
   (7,"The Number That Defines Us","The lie examined","1 Sam 16:7; Luke 12:15"),
  ]},
  {"roman":"II","title":"God Looks at the Heart","subtitle":"The Truer Measure","days":[
   (8,"Man Looks at the Outward","God at the heart","1 Sam 16:7; Luke 16:15"),
   (9,"Not as Mortals See","God's different measure","1 Sam 16:7; Isa 55:8-9"),
   (10,"The Hidden Person of the Heart","What God values","1 Pet 3:3-4; 1 Sam 16:7"),
   (11,"A Gentle and Quiet Spirit","Of great worth","1 Pet 3:4; Ps 51:17"),
   (12,"Rich Toward God","The wealth He sees","Luke 12:21; Jas 2:5"),
   (13,"What Is Highly Valued","May be detestable","Luke 16:15; 1 Sam 16:7"),
   (14,"God Looks at the Heart","The truer measure","1 Sam 16:7; 1 Pet 3:4"),
  ]},
  {"roman":"III","title":"Made in His Image","subtitle":"Worth That's Given","days":[
   (15,"Made in God's Image","Worth from creation","Gen 1:27; Ps 139:13-14"),
   (16,"Fearfully, Wonderfully Made","Known and crafted","Ps 139:13-14; Ps 139:16"),
   (17,"Crowned With Glory","A little lower than angels","Ps 8:5; Heb 2:6-7"),
   (18,"A Chosen People","Belonging to God","1 Pet 2:9; Eph 1:4-5"),
   (19,"Bought With a Price","Christ's costly love","1 Cor 6:20; 1 Pet 1:18-19"),
   (20,"No Longer I, but Christ","Identity in Him","Gal 2:20; Col 3:3"),
   (21,"Made in His Image","Worth that's given","Gen 1:27; Ps 139:14"),
  ]},
  {"roman":"IV","title":"The Rise and Fall","subtitle":"Why the Number Can't Hold","days":[
   (22,"Riches Take Wings","Here today, gone","Prov 23:5; Prov 27:24"),
   (23,"We Brought Nothing In","And take nothing out","1 Tim 6:7; Eccl 5:15"),
   (24,"The Rich Man Will Fade","Like a wildflower","Jas 1:10-11; 1 Pet 1:24"),
   (25,"Do Not Be Overawed","When others grow rich","Ps 49:16-17; Ps 37:7"),
   (26,"Naked I Came","Naked I'll return","Job 1:21; Eccl 5:15"),
   (27,"Built on Shifting Sand","If worth rests on wealth","Matt 7:26-27; Prov 11:28"),
   (28,"The Rise and Fall","Why the number can't hold","Prov 23:5; 1 Tim 6:7"),
  ]},
  {"roman":"V","title":"Cutting the Cord","subtitle":"Worth Detached From Wealth","days":[
   (29,"Untie Worth From Wealth","Cut the cord","1 Sam 16:7; Luke 12:15"),
   (30,"Life Is Not Your Stuff","It doesn't consist in it","Luke 12:15; Eccl 5:10"),
   (31,"Identity in Christ","Secure and unshakable","Gal 2:20; Col 3:3-4"),
   (32,"Approved by God","Not by net worth","Gal 1:10; 2 Cor 10:18"),
   (33,"Freed From the Scoreboard","No more measuring","Gal 6:4; 2 Cor 10:12"),
   (34,"Resting in Belovedness","Who you are to Him","1 John 3:1; Zeph 3:17"),
   (35,"Cutting the Cord","Worth detached from wealth","1 Sam 16:7; Gal 2:20"),
  ]},
  {"roman":"VI","title":"More Than a Number","subtitle":"Your True Worth","days":[
   (36,"More Than a Net Worth","A beloved child","1 John 3:1; 1 Sam 16:7"),
   (37,"Defined by His Love","Not by dollars","Rom 8:38-39; Eph 2:4-5"),
   (38,"Secure in Christ","Whatever the balance","Col 3:3; Phil 4:11-13"),
   (39,"Holding Wealth Loosely","It isn't you","Luke 12:15; 1 Tim 6:7"),
   (40,"More Than a Number","Your true worth","1 Sam 16:7; Ps 139:13-14"),
  ]},
 ],
 # ---------------- 72 · The Love of Money ----------------
 72: [
  {"roman":"I","title":"Not Money, but Love","subtitle":"The Real Problem","days":[
   (1,"The Love, Not the Money","A precise diagnosis","1 Tim 6:10; Eccl 5:10"),
   (2,"Money Itself Is Neutral","The heart is the issue","1 Tim 6:10; Matt 6:21"),
   (3,"A Root, Not the Tree","Where evil starts","1 Tim 6:10; Jas 1:14-15"),
   (4,"The Eager Pursuit","Wandering from faith","1 Tim 6:10; 1 Tim 6:9"),
   (5,"Have Without Loving It","And lack without freedom","1 Tim 6:10; Prov 30:8-9"),
   (6,"Examining the Affection","What do you love?","Matt 6:21; Deut 6:5"),
   (7,"Not Money, but Love","The real problem","1 Tim 6:10; Matt 6:21"),
  ]},
  {"roman":"II","title":"The Root System","subtitle":"Tracing It Down","days":[
   (8,"A Root of All Kinds of Evil","How deep it runs","1 Tim 6:10; Heb 13:5"),
   (9,"The Desire to Be Rich","A trap and a snare","1 Tim 6:9; Prov 28:22"),
   (10,"Harmful Desires","That drown people","1 Tim 6:9; Mark 4:19"),
   (11,"Roots Beneath the Surface","Hidden but powerful","1 Tim 6:10; Luke 16:14-15"),
   (12,"Feeding the Root","What waters greed","Eccl 5:10; Luke 12:15"),
   (13,"Discontent at the Core","Never satisfied","Eccl 5:10; Phil 4:11"),
   (14,"The Root System","Tracing it down","1 Tim 6:10; Eccl 5:10"),
  ]},
  {"roman":"III","title":"What Grows From It","subtitle":"The Fruit Examined","days":[
   (15,"The Bitter Fruit","What it yields","1 Tim 6:10; Prov 15:27"),
   (16,"Pierced With Many Griefs","Self-inflicted sorrow","1 Tim 6:10; Prov 1:19"),
   (17,"Wandering From the Faith","The spiritual cost","1 Tim 6:10; Mark 4:18-19"),
   (18,"Broken Relationships","Greed divides","Prov 15:27; Jas 4:1-2"),
   (19,"The Thorns That Choke","Riches strangle the word","Matt 13:22; Mark 4:19"),
   (20,"A Trap That Plunges","Into ruin","1 Tim 6:9; Prov 28:20"),
   (21,"What Grows From It","The fruit examined","1 Tim 6:10; Matt 13:22"),
  ]},
  {"roman":"IV","title":"Naming It Honestly","subtitle":"The First Step Free","days":[
   (22,"Honest Self-Examination","Search me, O God","Ps 139:23-24; Lam 3:40"),
   (23,"The Anxiety It Breeds","A telling sign","Matt 6:25; Luke 12:22-25"),
   (24,"The Grip You Can't Loosen","What you can't give","Luke 18:22-23; Acts 5:1-4"),
   (25,"Confessing the Love","Bringing it to light","1 John 1:9; Ps 32:5"),
   (26,"No Condemnation","Grace for the greedy heart","Rom 8:1; 1 John 1:9"),
   (27,"Turning From It","Repentance and freedom","Luke 19:8-9; Acts 19:19"),
   (28,"Naming It Honestly","The first step free","1 Tim 6:10; Ps 139:23-24"),
  ]},
  {"roman":"V","title":"Loosening the Grip","subtitle":"The Heart Pried Open","days":[
   (29,"Flee From It","Run the other way","1 Tim 6:11; 2 Tim 2:22"),
   (30,"Pursue Righteousness Instead","A new chase","1 Tim 6:11; Matt 6:33"),
   (31,"Be Content","Godliness with contentment","1 Tim 6:6-8; Heb 13:5"),
   (32,"Give It Away","Generosity breaks the grip","1 Tim 6:18; Luke 12:33"),
   (33,"Set Your Hope on God","Not on wealth","1 Tim 6:17; Ps 62:10"),
   (34,"Keep Free From the Love","Content with what you have","Heb 13:5; Phil 4:11-12"),
   (35,"Loosening the Grip","The heart pried open","1 Tim 6:10-11; Heb 13:5"),
  ]},
  {"roman":"VI","title":"The Freedom Beyond","subtitle":"Life Past the Love of Money","days":[
   (36,"Free at Last","The grip released","1 Tim 6:11; Gal 5:1"),
   (37,"Rich in Good Deeds","The better wealth","1 Tim 6:18-19; Luke 12:21"),
   (38,"Take Hold of True Life","The life that is truly life","1 Tim 6:19; John 10:10"),
   (39,"Content and Free","No longer enslaved","1 Tim 6:6; Heb 13:5"),
   (40,"The Freedom Beyond","Life past the love of money","1 Tim 6:10-11; 1 Tim 6:19"),
  ]},
 ],
 # ---------------- 73 · What Money Can't Buy ----------------
 73: [
  {"roman":"I","title":"The Priceless Things","subtitle":"What Wealth Can't Reach","days":[
   (1,"Beyond Price","What money can't buy","Prov 22:1; Mark 8:36-37"),
   (2,"The Limits of Wealth","What it cannot reach","Eccl 5:10; Ps 49:7-8"),
   (3,"Money's Real Boundaries","Where it stops","Ps 49:6-9; Prov 11:4"),
   (4,"The Best Things Are Free","Given, not bought","Isa 55:1-2; Matt 10:8"),
   (5,"Counting True Riches","What actually matters","Luke 12:15; Matt 6:19-21"),
   (6,"A Higher Currency","Love, peace, conscience","Prov 15:16-17; 1 Tim 6:6"),
   (7,"The Priceless Things","What wealth can't reach","Prov 22:1; Mark 8:36"),
  ]},
  {"roman":"II","title":"A Good Name","subtitle":"The Unbuyable Treasure","days":[
   (8,"A Good Name","More desirable than riches","Prov 22:1; Eccl 7:1"),
   (9,"Esteem Better Than Silver","And gold","Prov 22:1; Prov 3:3-4"),
   (10,"Reputation Built, Not Bought","Earned over time","Prov 22:1; Luke 16:10"),
   (11,"A Name Worth More","Than great wealth","Prov 22:1; Eccl 7:1"),
   (12,"Integrity's Reward","A name that stands","Prov 10:9; Prov 11:3"),
   (13,"Remembered for Character","Not for cash","Prov 10:7; Ps 112:6"),
   (14,"A Good Name","The unbuyable treasure","Prov 22:1; Eccl 7:1"),
  ]},
  {"roman":"III","title":"Love and Peace","subtitle":"Priceless and Given","days":[
   (15,"Love Unpurchasable","Wealth can't buy it","Song 8:7; 1 Cor 13:3"),
   (16,"If One Gave All","It would be scorned","Song 8:7; 1 Cor 13:1-3"),
   (17,"Better a Little With Love","Than a feast with strife","Prov 15:17; Prov 17:1"),
   (18,"Peace Money Can't Buy","The gift of God","John 14:27; Phil 4:7"),
   (19,"A Quiet Home","Better than wealth with turmoil","Prov 17:1; Prov 15:16"),
   (20,"The Peace That Guards","Beyond purchase","Phil 4:7; Isa 26:3"),
   (21,"Love and Peace","Priceless and given","Song 8:7; John 14:27"),
  ]},
  {"roman":"IV","title":"Time and Presence","subtitle":"The Truest Currency","days":[
   (22,"Time Can't Be Bought","The non-renewable gift","Ps 90:12; Eph 5:15-16"),
   (23,"Number Our Days","Spend them wisely","Ps 90:12; Ps 39:4-5"),
   (24,"Presence Over Presents","Being there matters","Eccl 4:9-10; Phil 2:4"),
   (25,"The Gift of Attention","Worth more than money","Phil 2:4; 1 Thess 2:8"),
   (26,"Moments You Can't Rewind","Treasure them now","Eccl 3:1; Ps 90:12"),
   (27,"Redeeming the Time","Making it count","Eph 5:15-16; Col 4:5"),
   (28,"Time and Presence","The truest currency","Ps 90:12; Eph 5:16"),
  ]},
  {"roman":"V","title":"A Clear Conscience","subtitle":"Unbuyable Peace","days":[
   (29,"A Clear Conscience","Better than gold","1 Tim 1:5; Acts 24:16"),
   (30,"Sleep of the Innocent","Peace within","Prov 3:24; Ps 4:8"),
   (31,"Wealth Can't Quiet Guilt","Only grace can","Ps 32:1-5; 1 John 1:9"),
   (32,"Clean Hands, Pure Heart","What money can't give","Ps 24:3-4; Ps 51:10"),
   (33,"Better Poor and Blameless","Than rich and crooked","Prov 19:1; Prov 28:6"),
   (34,"The Peace of Integrity","A priceless rest","Prov 10:9; 1 Pet 3:16"),
   (35,"A Clear Conscience","Unbuyable peace","1 Tim 1:5; Acts 24:16"),
  ]},
  {"roman":"VI","title":"What Money Can't Buy","subtitle":"The Greatest Riches","days":[
   (36,"The Unbuyable List","Name, love, peace, conscience","Prov 22:1; Mark 8:36"),
   (37,"Salvation Not for Sale","The greatest gift","Isa 55:1-2; Acts 8:20"),
   (38,"Seek the Lasting Riches","Beyond money's reach","Matt 6:19-21; Luke 12:21"),
   (39,"Rich in What Counts","The priceless wealth","Luke 12:15; 1 Tim 6:6"),
   (40,"What Money Can't Buy","The greatest riches","Prov 22:1; Mark 8:36-37"),
  ]},
 ],
 # ---------------- 74 · Money and the Soul ----------------
 74: [
  {"roman":"I","title":"More Than Transactions","subtitle":"The Soul at Stake","days":[
   (1,"More Than Transactions","Money shapes the soul","Mark 8:36; Luke 16:10-11"),
   (2,"The Spiritual Side of Money","Never just numbers","Matt 6:21; Luke 16:11"),
   (3,"What Money Reveals","The heart laid bare","Matt 6:21; Luke 12:34"),
   (4,"A Matter of the Soul","Not just the wallet","Mark 8:36; Prov 4:23"),
   (5,"Money as a Mirror","Showing the heart","Luke 12:34; 1 Tim 6:10"),
   (6,"Eternity in the Everyday","Soul-stakes in spending","Mark 8:36; Luke 16:11"),
   (7,"More Than Transactions","The soul at stake","Mark 8:36; Matt 6:21"),
  ]},
  {"roman":"II","title":"Forming or Deforming","subtitle":"Money's Shaping Power","days":[
   (8,"Money Forms Us","For better or worse","Luke 16:10-11; 1 Tim 6:10"),
   (9,"Faithful Habits Shape the Soul","Little by little","Luke 16:10; Gal 6:7-8"),
   (10,"Greed Deforms","Generosity forms","1 Tim 6:10; Prov 11:24-25"),
   (11,"Sowing to the Flesh","Or to the Spirit","Gal 6:7-8; Rom 8:5-6"),
   (12,"Treasure Shapes You","Heart follows treasure","Matt 6:21; Col 3:1-2"),
   (13,"Becoming What We Worship","Idols deform us","Ps 115:4-8; 2 Cor 3:18"),
   (14,"Forming or Deforming","Money's shaping power","Luke 16:10-11; Gal 6:7-8"),
  ]},
  {"roman":"III","title":"Gain the World, Lose the Soul","subtitle":"The Trade Refused","days":[
   (15,"What Good Is It","To gain the world","Mark 8:36; Luke 9:25"),
   (16,"And Lose Your Soul","The fatal trade","Mark 8:36; Matt 16:26"),
   (17,"What Can You Give","In exchange for your soul?","Mark 8:37; Ps 49:7-8"),
   (18,"The Rich Fool's End","Soul required that night","Luke 12:20-21; Ps 39:6"),
   (19,"Storing Up, Missing Out","Rich but not toward God","Luke 12:21; 1 Tim 6:17"),
   (20,"The Worst Bargain","Everything for nothing","Mark 8:36-37; Matt 16:26"),
   (21,"Gain the World, Lose the Soul","The trade refused","Mark 8:36; Luke 9:25"),
  ]},
  {"roman":"IV","title":"The Faithful and the Soul","subtitle":"Money as Proving Ground","days":[
   (22,"Faithful in Little","Reveals the soul","Luke 16:10; Luke 16:11"),
   (23,"Trustworthy With Worldly Wealth","A spiritual test","Luke 16:11; Luke 16:12"),
   (24,"If Not Faithful Here","Who'll trust you with true riches?","Luke 16:11; Matt 25:21"),
   (25,"A Discipleship Test","The heart proven","Luke 16:13; Matt 6:24"),
   (26,"Handling Money Faithfully","Shapes the soul well","Luke 16:10; 1 Cor 4:2"),
   (27,"Stewardship Forms Character","The faithful servant","Matt 25:21; Luke 12:42-44"),
   (28,"The Faithful and the Soul","Money as proving ground","Luke 16:10-11; Matt 25:21"),
  ]},
  {"roman":"V","title":"Guarding the Heart","subtitle":"Protecting the Soul","days":[
   (29,"Guard Your Heart","Above all else","Prov 4:23; Luke 12:15"),
   (30,"The Wellspring of Life","Flows from the heart","Prov 4:23; Matt 12:34"),
   (31,"Watch What You Treasure","It captures the heart","Matt 6:21; Luke 12:34"),
   (32,"Be on Guard Against Greed","The constant vigilance","Luke 12:15; Col 3:5"),
   (33,"Turn My Heart","Toward You, not gain","Ps 119:36; Ps 141:4"),
   (34,"Keep the Heart Free","From money's claim","Heb 13:5; 1 Tim 6:10"),
   (35,"Guarding the Heart","Protecting the soul","Prov 4:23; Luke 12:15"),
  ]},
  {"roman":"VI","title":"Money and the Soul","subtitle":"The Heart Kept for God","days":[
   (36,"Money in Its Place","Servant, not master","Matt 6:24; Luke 16:9"),
   (37,"A Soul Kept Whole","Through faithful stewardship","Mark 8:36; Luke 16:10"),
   (38,"Treasuring the Right Things","Heart set on heaven","Matt 6:20-21; Col 3:1-2"),
   (39,"The Soul Well-Tended","Money handled wisely","Prov 4:23; Mark 8:36"),
   (40,"Money and the Soul","The heart kept for God","Mark 8:36; Matt 6:21"),
  ]},
 ],
 # ---------------- 75 · The Treasure Test ----------------
 75: [
  {"roman":"I","title":"The Diagnostic","subtitle":"Your Treasure Shows Your Heart","days":[
   (1,"Where Your Treasure Is","There your heart will be","Luke 12:34; Matt 6:21"),
   (2,"A Heart Diagnostic","Money reveals it","Luke 12:34; Matt 6:21"),
   (3,"Follow the Heart's Trail","It leads to treasure","Matt 6:21; Luke 12:34"),
   (4,"What Has Your Heart?","The honest question","Matt 6:21; Deut 6:5"),
   (5,"Treasure and Affection","Bound together","Luke 12:34; Col 3:1-2"),
   (6,"The Test Is Revealing","Not condemning","Luke 12:34; Ps 139:23-24"),
   (7,"The Diagnostic","Treasure shows the heart","Luke 12:34; Matt 6:21"),
  ]},
  {"roman":"II","title":"Follow the Money","subtitle":"The Heart's Trail Revealed","days":[
   (8,"Follow the Money","Where does it go?","Luke 12:34; Matt 6:21"),
   (9,"Your Spending, Your Heart","The bank statement sermon","Matt 6:21; Luke 16:13"),
   (10,"First Fruits or Leftovers?","What gets priority","Prov 3:9-10; Matt 6:33"),
   (11,"Where the Surplus Goes","A telling sign","Luke 12:34; 1 Tim 6:18"),
   (12,"Generosity or Accumulation?","The direction of flow","2 Cor 9:7; Luke 12:21"),
   (13,"Money Follows the Heart","And shapes it too","Matt 6:21; Luke 12:34"),
   (14,"Follow the Money","The heart's trail revealed","Luke 12:34; Matt 6:21"),
  ]},
  {"roman":"III","title":"Follow the Calendar","subtitle":"Time Shows the Heart","days":[
   (15,"Follow the Calendar","Where does time go?","Eph 5:15-16; Ps 90:12"),
   (16,"Time Reveals Treasure","As money does","Matt 6:21; Eph 5:16"),
   (17,"What Gets the Hours?","Priorities in the schedule","Ps 90:12; Col 4:5"),
   (18,"Margin for What Matters","Or crowded out","Luke 10:41-42; Eph 5:15-16"),
   (19,"Time With God","On the calendar?","Mark 1:35; Ps 5:3"),
   (20,"Redeeming the Days","Spending time wisely","Eph 5:15-16; Ps 90:12"),
   (21,"Follow the Calendar","Time shows the heart","Eph 5:16; Matt 6:21"),
  ]},
  {"roman":"IV","title":"The Honest Results","subtitle":"Facing What's Found","days":[
   (22,"Reading the Results","What the test shows","Luke 12:34; Ps 139:23-24"),
   (23,"No Hiding From It","The heart laid bare","Heb 4:13; Luke 16:15"),
   (24,"Surprised by the Findings","Treasure misplaced","Matt 6:21; Hag 1:5-7"),
   (25,"Conviction, Not Condemnation","Grace in the mirror","Rom 8:1; 2 Cor 7:10"),
   (26,"Honest Before God","Owning what's revealed","Ps 32:5; 1 John 1:9"),
   (27,"Ready to Change","The results invite it","Lam 3:40; Rom 12:2"),
   (28,"The Honest Results","Facing what's found","Luke 12:34; Ps 139:23-24"),
  ]},
  {"roman":"V","title":"Resetting the Treasure","subtitle":"Heart Re-aimed at God","days":[
   (29,"Store Up in Heaven","Re-aim the treasure","Matt 6:19-20; Luke 12:33"),
   (30,"Set Your Heart Above","Where Christ is","Col 3:1-2; Matt 6:21"),
   (31,"Seek First the Kingdom","Reorder everything","Matt 6:33; Luke 12:31"),
   (32,"Give to Redirect the Heart","Treasure follows giving","Luke 12:33-34; 2 Cor 9:7"),
   (33,"New Priorities","Time and money realigned","Matt 6:33; Eph 5:15-16"),
   (34,"Treasure Where It Lasts","The eternal aim","Matt 6:20; 2 Cor 4:18"),
   (35,"Resetting the Treasure","Heart re-aimed at God","Matt 6:19-21; Luke 12:34"),
  ]},
  {"roman":"VI","title":"The Treasure Test","subtitle":"Where Your Heart Truly Is","days":[
   (36,"Heart Where Treasure Is","The principle settled","Luke 12:34; Matt 6:21"),
   (37,"An Honest Audit","Money and time","Luke 12:34; Hag 1:5"),
   (38,"Treasure in Heaven","Heart following it home","Matt 6:20-21; Col 3:1-2"),
   (39,"A Heart Set on God","The test passed","Matt 6:33; Ps 73:25-26"),
   (40,"The Treasure Test","Where your heart truly is","Luke 12:34; Matt 6:21"),
  ]},
 ],
}
