# -*- coding: utf-8 -*-
# Finances Campaign Catalog — Top 10, campaigns 1-5
# Each "movements" list groups the 40 days into 6 thematic movements.

TOP10_A = [
{
 "num": 1,
 "title": "God Owns It All",
 "tagline": "Living as a Steward, Not an Owner",
 "positioning": "A 40-day journey that resets the single most important question about money — who actually owns it — and rebuilds daily financial life on the freedom of stewardship.",
 "felt_need": "Control, the white-knuckle grip of ownership, and the anxiety of having something to protect.",
 "audience": "All church · Workplace teams · New believers through mature disciples",
 "tier": "Tier 1 — Church & Company",
 "core_ref": "Psalm 24:1 (NIV)",
 "core_text": "The earth is the Lord's, and everything in it, the world, and all who live in it.",
 "marketing": "Most people manage money as owners, and ownership is exhausting. It makes every dollar a weight, every loss a threat, and every decision a private burden carried alone. Scripture begins somewhere completely different: God owns it all, and we are simply stewards of what belongs to Him. This campaign walks a congregation through the ownership transfer that changes everything, moving people from the clenched fist of the owner to the open hand of the steward who has nothing to protect and nothing to prove.",
 "why_matters": "Every other financial issue — fear, debt, generosity, contentment, legacy — flows downstream of the ownership question. Settle this one, and everything else finally becomes possible.",
 "problem": "We carry money as owners, and owners are always anxious, because an owner can always lose what is his.",
 "transformation": "From owner to steward; from grip to open hand; from \"mine to protect\" to \"His to manage.\"",
 "formats": ["4-Session", "6-Session", "21-Day", "30-Day", "40-Day"],
 "sessions": [
   ("Who Really Owns It All?", "The ownership transfer that changes everything"),
   ("The Steward's Job Description", "What God actually asks of a manager"),
   ("Faithful in the Small Things", "Why how you handle a little reveals everything"),
   ("Holding It All Open-Handed", "Releasing the grip that fear creates"),
   ("Spending as Worship", "Every financial decision as a spiritual one"),
   ("The Free Life of a Steward", "Living lighter because nothing is yours to protect"),
 ],
 "scriptures": ["Psalm 24:1", "1 Chronicles 29:11-14", "Luke 16:10-13", "Matthew 25:14-30", "Deuteronomy 8:18", "1 Corinthians 4:2"],
 "movements": [
  {"roman":"I","title":"Who Owns It All","subtitle":"The Ownership Transfer","days":[
    (1,"The Great Transfer","When \"mine\" becomes \"His\"","Ps 24:1; 1 Chr 29:11"),
    (2,"Everything Comes From God","Even the ability to earn","Deut 8:17-18; Jas 1:17"),
    (3,"The Maker's Claim","He owns it because He made it","Ps 50:10-12; Col 1:16"),
    (4,"On Loan, Not Owned","We arrive and leave with nothing","1 Tim 6:7; Job 1:21"),
    (5,"The Heart Behind the Hands","Money reveals what we trust","Matt 6:21,24; Prov 3:5-6"),
    (6,"The Owner's Anxiety","Why ownership never rests","Luke 12:15; Eccl 5:10"),
    (7,"The First Surrender","Praying \"It's all Yours\"","Rom 11:36; Ps 24:1"),
  ]},
  {"roman":"II","title":"The Steward's Calling","subtitle":"A Manager, Not an Owner","days":[
    (8,"The Job Description","Stewards manage another's resources","1 Cor 4:1-2; Gen 1:28"),
    (9,"Trusted With Much","The parable of the talents","Matt 25:14-18; Luke 19:12-13"),
    (10,"Burying the Gift","The cost of playing it safe","Matt 25:24-27; Prov 18:9"),
    (11,"Well Done","The reward of faithfulness","Matt 25:21; Luke 16:10"),
    (12,"Accountable to the Owner","One day we give an account","Rom 14:12; 2 Cor 5:10"),
    (13,"The Shrewd Manager","Using resources wisely now","Luke 16:1-9; Prov 21:5"),
    (14,"Manager of the Mundane","Stewardship in ordinary days","Col 3:23; 1 Cor 10:31"),
  ]},
  {"roman":"III","title":"Faithful in the Small","subtitle":"How You Handle a Little","days":[
    (15,"Very Little, Very Much","Small faithfulness, big trust","Luke 16:10; Matt 25:21"),
    (16,"The Test of a Dollar","What one decision reveals","Luke 16:11; Prov 11:1"),
    (17,"Honest Scales","Integrity in every transaction","Prov 11:1; Lev 19:35-36"),
    (18,"Diligence Over Hurry","Slow and steady stewardship","Prov 21:5; Prov 13:11"),
    (19,"The Faithful Few","Trusted because tested","Luke 16:12; Matt 24:45-47"),
    (20,"Small Leaks, Sunk Ships","Where waste quietly hides","Prov 21:20; Hag 1:6"),
    (21,"Counting the Cost","Planning before spending","Luke 14:28; Prov 24:3-4"),
  ]},
  {"roman":"IV","title":"The Open Hand","subtitle":"Releasing the Grip","days":[
    (22,"The Clenched Fist","What fear does to our hands","Matt 6:25; 1 John 4:18"),
    (23,"Open-Handed Living","Holding everything loosely","1 Tim 6:17-18; Eccl 5:15"),
    (24,"Nothing to Protect","The freedom of the steward","Phil 4:11-12; Heb 13:5"),
    (25,"Letting Go to Receive","The paradox of release","Luke 6:38; Prov 11:24"),
    (26,"Trusting the Owner","He provides for His stewards","Matt 6:31-33; Phil 4:19"),
    (27,"When You Lose Something","Loss when it was never yours","Job 1:21; Ps 62:10"),
    (28,"Hands Free for Others","Generosity flows from release","Acts 20:35; 2 Cor 9:7"),
  ]},
  {"roman":"V","title":"Spending as Worship","subtitle":"Every Decision a Spiritual One","days":[
    (29,"The Spiritual Budget","Money decisions are worship","Rom 12:1; Matt 6:24"),
    (30,"Where Treasure Goes","The heart follows the money","Matt 6:19-21; Luke 12:34"),
    (31,"Two Masters","Why you can't serve both","Matt 6:24; Luke 16:13"),
    (32,"First Things First","Honoring God off the top","Prov 3:9-10; Mal 3:10"),
    (33,"Contentment as Worship","Enough is an act of trust","1 Tim 6:6-8; Phil 4:12"),
    (34,"Generosity as Worship","Giving that pleases God","2 Cor 9:7; Heb 13:16"),
    (35,"The Worship of Wise Saving","Stewarding the future","Prov 21:20; Prov 6:6-8"),
  ]},
  {"roman":"VI","title":"The Free Life","subtitle":"Living Lighter","days":[
    (36,"The Steward's Peace","Rest that owners never know","Matt 11:28-30; Ps 23:1"),
    (37,"Rich Toward God","The only wealth that lasts","Luke 12:21; 1 Tim 6:18-19"),
    (38,"A Life That Lets Go","Holding on to nothing but God","Phil 3:7-8; Matt 6:33"),
    (39,"The Account You'll Give","Living for \"well done\"","Matt 25:21; 2 Tim 4:7"),
    (40,"Steward for Life","A daily, lifelong surrender","Rom 12:1; 1 Chr 29:14"),
  ]},
 ],
},
{
 "num": 2,
 "title": "Free From Financial Fear",
 "tagline": "Trading Money Worry for the Peace of God",
 "positioning": "A 40-day journey for everyone who lies awake worrying about money, leading from the weight of anxiety to the settled peace of a God who promises to provide.",
 "felt_need": "Money stress, sleepless nights, scarcity thinking, and the fear that you will not be okay.",
 "audience": "All church · Workplace teams · Anyone carrying financial anxiety",
 "tier": "Tier 1 — Church & Company",
 "core_ref": "Matthew 6:34 (NIV)",
 "core_text": "Therefore do not worry about tomorrow, for tomorrow will worry about itself. Each day has enough trouble of its own.",
 "marketing": "Money is one of the most common sources of anxiety in any congregation, and it rarely announces itself on Sunday morning. It shows up at 3 a.m., in the pit of the stomach, in the argument that was never really about the credit card. This campaign meets people exactly there. Rooted in Jesus' own teaching on worry in Matthew 6, it walks participants from naming their fear honestly, to meeting the God who provides, to casting their anxiety on Him daily, until a different posture toward money becomes possible: not denial, not false confidence, but real peace.",
 "why_matters": "Financial fear silently shapes decisions, marriages, sleep, and generosity. People do not need a lecture on budgeting first; they need to be released from the fear that keeps them stuck.",
 "problem": "We carry a weight of financial worry we were never designed to bear, and it steals our peace, our rest, and our joy.",
 "transformation": "From anxious to anchored; from scarcity to trust; from sleepless worry to the peace of God that guards the heart.",
 "formats": ["4-Session", "6-Session", "21-Day", "30-Day", "40-Day"],
 "sessions": [
   ("The Weight of Worry", "Naming the financial fear we carry"),
   ("What Worry Can't Do", "Why anxiety never adds a day or a dollar"),
   ("The God Who Provides", "Meeting the Provider behind every provision"),
   ("Casting the Care", "Handing the fear to God, daily"),
   ("Peace That Guards", "The peace of God standing watch over money"),
   ("Living Unafraid", "A new daily posture toward money and the future"),
 ],
 "scriptures": ["Matthew 6:25-34", "Philippians 4:6-7", "1 Peter 5:7", "Psalm 23:1-4", "Isaiah 41:10", "Hebrews 13:5-6"],
 "movements": [
  {"roman":"I","title":"The Weight We Carry","subtitle":"Naming the Fear","days":[
    (1,"The 3 a.m. Worry","The fear money whispers at night","Matt 6:25; Ps 4:8"),
    (2,"The Faces of Fear","Scarcity, comparison, control","Eccl 5:10; Luke 12:15"),
    (3,"Where Fear Comes From","Believing it all depends on me","Prov 3:5-6; Jer 17:7-8"),
    (4,"What Fear Costs","The daily toll of anxiety","Matt 6:27; Prov 12:25"),
    (5,"Fear's Big Lie","\"You will not be okay\"","Isa 41:10; Deut 31:6"),
    (6,"The Idol of Security","When safety becomes a god","Matt 6:24; Ps 20:7"),
    (7,"Fear Into the Light","Being honest before God","Ps 62:8; 1 Pet 5:7"),
  ]},
  {"roman":"II","title":"What Worry Cannot Do","subtitle":"The Limits of Anxiety","days":[
    (8,"Not One Hour","Worry adds nothing at all","Matt 6:27; Luke 12:25"),
    (9,"The Birds and the Lilies","Provision without panic","Matt 6:26-30; Luke 12:24"),
    (10,"Tomorrow's Trouble","One day at a time","Matt 6:34; Lam 3:22-23"),
    (11,"Daily Bread","Asking only for today","Matt 6:11; Exod 16:4"),
    (12,"The Worry Cycle","Breaking the anxious loop","Phil 4:6; Ps 94:19"),
    (13,"Worry vs. Wisdom","Planning is not panicking","Prov 21:5; Prov 6:6-8"),
    (14,"Trading Worry for Trust","A daily exchange","Prov 3:5-6; Isa 26:3"),
  ]},
  {"roman":"III","title":"The God Who Provides","subtitle":"Meeting the Provider","days":[
    (15,"The Lord Will Provide","Jehovah Jireh on the mountain","Gen 22:14; Phil 4:19"),
    (16,"The Shepherd's Provision","I lack nothing","Ps 23:1-3; Ps 34:9-10"),
    (17,"Manna Morning","Enough for the day","Exod 16:14-18; 2 Cor 8:15"),
    (18,"He Knows Your Needs","Before you even ask","Matt 6:8,32; Ps 139:1-4"),
    (19,"The Father's Heart","Good gifts from a good Father","Matt 7:9-11; Jas 1:17"),
    (20,"Provision in the Lean","God in the wilderness season","Deut 8:3-4; 1 Kgs 17:13-16"),
    (21,"Seek First","The promise that reorders all","Matt 6:33; Ps 37:25"),
  ]},
  {"roman":"IV","title":"Casting the Care","subtitle":"Handing Over the Fear","days":[
    (22,"Cast It On Him","Because He cares for you","1 Pet 5:7; Ps 55:22"),
    (23,"The Daily Handoff","Surrender as a habit","Matt 11:28-30; Ps 37:5"),
    (24,"Prayer Instead of Panic","Turning worry into words","Phil 4:6; 1 Thess 5:17"),
    (25,"Thanksgiving in the Middle","Gratitude that disarms fear","Phil 4:6; 1 Thess 5:18"),
    (26,"Remember What He's Done","Past provision, present peace","Ps 77:11; Lam 3:21"),
    (27,"Let Him Carry It","Stop picking it back up","Ps 68:19; Matt 6:34"),
    (28,"The Unclenched Heart","Releasing the grip of fear","1 John 4:18; Ps 56:3"),
  ]},
  {"roman":"V","title":"Peace That Guards","subtitle":"The Peace of God","days":[
    (29,"Peace Beyond Understanding","A guard for the heart","Phil 4:7; John 14:27"),
    (30,"Anchored, Not Anxious","Steady in uncertainty","Heb 6:19; Ps 112:7"),
    (31,"The Mind Stayed on God","Kept in perfect peace","Isa 26:3; Col 3:2"),
    (32,"Contentment's Calm","Learning to be at rest","Phil 4:11-12; 1 Tim 6:6"),
    (33,"Sleeping in the Storm","Rest while the wind howls","Mark 4:38-40; Ps 3:5"),
    (34,"Peace With Less","When circumstances don't change","Hab 3:17-18; Phil 4:12"),
    (35,"Guarded Day by Day","Peace as a daily gift","John 14:27; Ps 29:11"),
  ]},
  {"roman":"VI","title":"Living Unafraid","subtitle":"A New Posture","days":[
    (36,"Do Not Be Afraid","God's most repeated command","Isa 41:10; Josh 1:9"),
    (37,"Generous Because Unafraid","Fear-free giving","2 Cor 9:7-8; Prov 11:25"),
    (38,"Free to Be Faithful","Obedience without anxiety","Matt 6:33; Heb 13:5-6"),
    (39,"The Story You Tell","Trust becomes testimony","Ps 34:4; Ps 23:6"),
    (40,"Unafraid for Life","A daily, durable peace","Phil 4:6-7; 1 Pet 5:7"),
  ]},
 ],
},
{
 "num": 3,
 "title": "Getting Out of Debt",
 "tagline": "A God-Honoring Path From Bondage to Freedom",
 "positioning": "A 40-day journey for the household carrying the weight of debt, combining honest spiritual truth with a practical, hope-filled path toward financial freedom.",
 "felt_need": "The bondage of debt, the shame of owing, and the longing for room to breathe.",
 "audience": "All church · Families and households · Workplace teams",
 "tier": "Tier 1 — Church & Company",
 "core_ref": "Proverbs 22:7 (NIV)",
 "core_text": "The rich rule over the poor, and the borrower is slave to the lender.",
 "marketing": "Debt is one of the heaviest burdens people carry into church, and it is almost always carried in silence. It strains marriages, steals sleep, and quietly closes the door on generosity and calling. This campaign brings debt into the light with grace, naming it honestly without shame, and then walks participants step by step toward freedom: understanding why debt enslaves, building a real plan, finding the discipline and momentum to cut the chains, and discovering the margin, peace, and generosity waiting on the other side.",
 "why_matters": "A congregation in bondage to debt has limited capacity to give, serve, or follow God's leading. Helping people get free unlocks their generosity and their freedom to say yes to God.",
 "problem": "Debt has become a master, ruling over decisions and stealing peace, and most people feel trapped with no way out.",
 "transformation": "From slave to the lender to owing no one anything but love; from white-knuckle bondage to margin and freedom.",
 "formats": ["6-Session", "21-Day", "30-Day", "40-Day"],
 "sessions": [
   ("The Weight of Owing", "Telling the truth about debt"),
   ("Why Debt Enslaves", "The borrower and the lender"),
   ("The Way Out", "Building a God-honoring plan to get free"),
   ("Cutting the Chains", "Discipline, sacrifice, and momentum"),
   ("Staying Free", "Habits that keep debt from coming back"),
   ("The Freedom on the Other Side", "Margin, peace, and generosity"),
 ],
 "scriptures": ["Proverbs 22:7", "Romans 13:8", "Luke 14:28-30", "Proverbs 6:1-5", "Proverbs 21:20", "Galatians 5:1"],
 "movements": [
  {"roman":"I","title":"The Weight of Owing","subtitle":"Telling the Truth","days":[
    (1,"Naming the Number","Honesty about what we owe","Luke 14:28; Ps 32:3-5"),
    (2,"The Borrower's Bondage","Slave to the lender","Prov 22:7; Neh 5:1-5"),
    (3,"How We Got Here","The roots of our debt","Prov 21:17; Luke 15:13-14"),
    (4,"The Shame Spiral","Bringing debt into the light","Ps 38:4; 1 John 1:9"),
    (5,"Presuming on Tomorrow","Borrowing against the unknown","Jas 4:13-15; Prov 27:1"),
    (6,"The Hidden Cost","What interest really takes","Prov 22:7; Hab 2:6-7"),
    (7,"A Different Future","Hope that there is a way out","Jer 29:11; Ps 40:2"),
  ]},
  {"roman":"II","title":"Why Debt Enslaves","subtitle":"Understanding the Trap","days":[
    (8,"Two Masters, One Heart","Debt as a competing lord","Matt 6:24; Rom 6:16"),
    (9,"The Snare of the Snap","Co-signing and impulse","Prov 6:1-5; Prov 17:18"),
    (10,"More Than You Make","Living beyond provision","Prov 21:20; Hag 1:6"),
    (11,"The Comparison Engine","Debt fueled by keeping up","Eccl 4:4; Luke 12:15"),
    (12,"Quick Money, Quick Loss","The get-rich shortcut","Prov 13:11; Prov 28:20"),
    (13,"The Anxiety of Owing","Why debt steals peace","Prov 12:25; Ps 38:4"),
    (14,"Repay What You Owe","The call to make it right","Ps 37:21; Rom 13:7"),
  ]},
  {"roman":"III","title":"The Way Out","subtitle":"Building the Plan","days":[
    (15,"Count the Cost","A plan before the fight","Luke 14:28-30; Prov 24:27"),
    (16,"The Diligent Plan","Steady beats frantic","Prov 21:5; Prov 13:4"),
    (17,"First the Small Stones","Momentum from quick wins","Zech 4:10; Luke 16:10"),
    (18,"Spend Less Than You Earn","The non-negotiable","Prov 21:20; Prov 30:8"),
    (19,"Write the Vision","A plan on paper","Hab 2:2; Prov 16:3"),
    (20,"Wise Counsel","Don't do it alone","Prov 15:22; Prov 11:14"),
    (21,"Cutting Back, Not Corners","Honest sacrifice","Prov 13:11; 2 Thess 3:10"),
  ]},
  {"roman":"IV","title":"Cutting the Chains","subtitle":"Discipline and Sacrifice","days":[
    (22,"Saying No for Now","Delayed gratification","Heb 12:11; Prov 25:28"),
    (23,"Contentment While You Climb","Enough during the grind","1 Tim 6:6-8; Phil 4:11"),
    (24,"The Discipline of Diligence","Hard work pays debt","Prov 10:4; Prov 14:23"),
    (25,"Selling and Simplifying","Releasing what we don't need","Luke 12:33; Prov 21:20"),
    (26,"No More Digging","Avoiding new debt","Prov 22:3; Prov 27:12"),
    (27,"When Progress Stalls","Endurance over discouragement","Gal 6:9; Ps 27:14"),
    (28,"Celebrating Each Win","Gratitude fuels momentum","1 Thess 5:18; Ps 126:3"),
  ]},
  {"roman":"V","title":"Staying Free","subtitle":"Habits That Hold","days":[
    (29,"The Margin Habit","Room to breathe","Prov 21:20; Prov 6:6-8"),
    (30,"Prepared, Not Panicked","An emergency fund","Prov 22:3; Gen 41:35-36"),
    (31,"Generosity Even Now","Giving on the journey","Prov 11:24-25; 2 Cor 8:2-3"),
    (32,"Guarding the Heart","Where overspending starts","Prov 4:23; Luke 12:15"),
    (33,"The Trap of \"Just Once\"","Small cracks, big breaks","Prov 22:3; 1 Cor 10:12"),
    (34,"Living on Less","A simpler standard","1 Tim 6:8; Heb 13:5"),
    (35,"A Plan That Lasts","Sustaining the discipline","Prov 21:5; Gal 6:9"),
  ]},
  {"roman":"VI","title":"Freedom on the Other Side","subtitle":"Life After Debt","days":[
    (36,"Owe Nothing But Love","The freedom of zero","Rom 13:8; Ps 37:21"),
    (37,"Margin for the Master","Free to say yes to God","2 Cor 9:8; Prov 3:9-10"),
    (38,"The Peace of Enough","Rest debt can't give","Phil 4:12; Ps 23:1"),
    (39,"From Borrower to Blessing","Free to be generous","Deut 15:6; Acts 20:35"),
    (40,"Free for Good","Walking in lasting freedom","Gal 5:1; John 8:36"),
  ]},
 ],
},
{
 "num": 4,
 "title": "A Simple Budget That Works",
 "tagline": "From Money Chaos to a Plan You Can Actually Keep",
 "positioning": "A 40-day journey that turns financial overwhelm into order, giving every household a simple, sustainable plan that tells their money where to go.",
 "felt_need": "Feeling out of control with money, having no plan, and the stress of not knowing where it all went.",
 "audience": "All church · Families and households · Workplace teams · Young adults",
 "tier": "Tier 1 — Church & Company",
 "core_ref": "Proverbs 21:5 (NIV)",
 "core_text": "The plans of the diligent lead to profit as surely as haste leads to poverty.",
 "marketing": "For most people, money feels out of control not because they earn too little but because they have no plan. The paycheck arrives, the month happens, and they are left wondering where it all went. This campaign makes budgeting simple, doable, and even freeing. It moves participants from the fog of no plan to clear sight of their numbers, to a one-page budget that gives every dollar a job, to the steady habits that make a plan stick through real life. The result is not restriction but peace, margin, and the freedom that order creates.",
 "why_matters": "A simple plan is the practical doorway to nearly every financial goal: getting out of debt, saving, giving, and ending money stress. Most people simply need a plan they can actually keep.",
 "problem": "Money feels chaotic and out of control, and without a plan, good intentions quietly drift into debt and stress.",
 "transformation": "From overwhelmed to organized; from \"where did it go?\" to a plan that brings margin, peace, and rest.",
 "formats": ["4-Session", "6-Session", "21-Day", "30-Day", "40-Day"],
 "sessions": [
   ("Why Money Feels Out of Control", "The real cost of having no plan"),
   ("Know Your Flocks and Herds", "Seeing clearly where the money goes"),
   ("A Plan on One Page", "Building a simple, doable budget"),
   ("Telling Your Money Where to Go", "Giving every dollar a job"),
   ("When the Plan Meets Real Life", "Adjusting without quitting"),
   ("The Peace of a Plan", "Order, margin, and rest"),
 ],
 "scriptures": ["Proverbs 21:5", "Luke 14:28-30", "Proverbs 27:23-24", "Proverbs 24:3-4", "Habakkuk 2:2", "Proverbs 16:9"],
 "movements": [
  {"roman":"I","title":"Out of Control","subtitle":"The Cost of No Plan","days":[
    (1,"Where Did It All Go?","Money without a map","Hag 1:6; Prov 21:5"),
    (2,"The Fog of No Plan","Confusion and stress","1 Cor 14:33; Prov 13:16"),
    (3,"Drifting Into Debt","What happens by default","Prov 22:3; Prov 21:20"),
    (4,"Impulse and Regret","Spending without thinking","Prov 21:5; Prov 19:2"),
    (5,"The Myth of \"More Income\"","Why a raise won't fix it","Eccl 5:10-11; Hag 1:6"),
    (6,"Order Is God's Idea","From chaos to design","Gen 1:1-3; 1 Cor 14:40"),
    (7,"The First Step: Decide","Choosing to plan","Prov 16:9; Luke 14:28"),
  ]},
  {"roman":"II","title":"Know Your Numbers","subtitle":"Seeing Clearly","days":[
    (8,"Know Your Flocks","Pay attention to what you have","Prov 27:23-24; Luke 16:11"),
    (9,"Track the Truth","Where it actually goes","Prov 27:12; Prov 14:8"),
    (10,"Income, Honestly","What you really earn","Prov 13:11; 2 Thess 3:10"),
    (11,"The Four Walls First","Food, shelter, the basics","1 Tim 6:8; Matt 6:11"),
    (12,"Wants vs. Needs","Telling the difference","Phil 4:11-12; Prov 30:8"),
    (13,"The Leaks You Don't See","Small recurring costs","Prov 21:20; Hag 1:6"),
    (14,"Counting Before Building","The wisdom of the estimate","Luke 14:28-30; Prov 24:27"),
  ]},
  {"roman":"III","title":"A Plan on One Page","subtitle":"Building the Budget","days":[
    (15,"Every Dollar a Job","A purpose for each one","Prov 21:5; 1 Cor 14:40"),
    (16,"God First, Off the Top","The first portion","Prov 3:9-10; Mal 3:10"),
    (17,"Save Before You Spend","Pay your future first","Prov 21:20; Prov 6:6-8"),
    (18,"A Plan for Giving","Generosity on purpose","2 Cor 9:7; 1 Cor 16:2"),
    (19,"Room for Real Life","Margin in the plan","Prov 21:20; Eccl 7:12"),
    (20,"Simple Beats Perfect","A plan you'll actually keep","Prov 16:3; Eccl 11:4"),
    (21,"Write It Down","Make the plan plain","Hab 2:2; Prov 16:9"),
  ]},
  {"roman":"IV","title":"Make It Work","subtitle":"Living the Plan","days":[
    (22,"You Lead, It Follows","Telling money where to go","Prov 21:5; Luke 16:10"),
    (23,"The Weekly Check-In","Small, steady reviews","Prov 27:23; Lam 3:40"),
    (24,"A Clear Conscience","Freedom inside the lines","Rom 14:22; 1 Tim 1:5"),
    (25,"The Discipline of Waiting","Sleep on the purchase","Prov 21:5; Prov 19:2"),
    (26,"Patience Pays","Saying no to yes-later","Heb 12:11; Prov 13:11"),
    (27,"Spend What You Have","Cash, not confusion","Prov 22:7; Rom 13:8"),
    (28,"Guarding Against Drift","Staying on plan","Prov 4:25-27; Heb 2:1"),
  ]},
  {"roman":"V","title":"When Life Happens","subtitle":"Adjusting Without Quitting","days":[
    (29,"The Plan Will Break","And that is okay","Prov 24:16; Phil 3:13-14"),
    (30,"Expect the Unexpected","Build a buffer","Prov 22:3; Gen 41:35-36"),
    (31,"Recalculate, Don't Quit","Adjust and continue","Prov 16:9; Lam 3:22-23"),
    (32,"Seasons Change","A plan that flexes","Eccl 3:1; Prov 27:12"),
    (33,"Grace for the Overspend","No shame, just reset","Rom 8:1; 1 John 1:9"),
    (34,"Counsel When Stuck","Ask for help","Prov 15:22; Prov 11:14"),
    (35,"Progress, Not Perfection","Faithful over flawless","Luke 16:10; Gal 6:9"),
  ]},
  {"roman":"VI","title":"The Peace of a Plan","subtitle":"Order and Rest","days":[
    (36,"Margin Brings Peace","Room to breathe","Prov 21:20; Ps 23:2"),
    (37,"Free to Give","A plan makes generosity possible","2 Cor 9:8; Prov 11:25"),
    (38,"Order as Worship","Stewardship in the details","Col 3:23; 1 Cor 10:31"),
    (39,"Teaching the Next Generation","Passing on the plan","Prov 22:6; Deut 6:6-7"),
    (40,"A Plan for Life","Simple, sustainable, faithful","Prov 21:5; Prov 16:3"),
  ]},
 ],
},
{
 "num": 5,
 "title": "The Generous Life",
 "tagline": "Discovering That the Most Generous Person Is Always the Most Free",
 "positioning": "A 40-day journey out of the scarcity and grip that hold us back, into the surprising joy and freedom of an open-handed, generous life.",
 "felt_need": "A tight grip on money, scarcity thinking, and the longing to give but the fear of not having enough.",
 "audience": "All church · Families · Workplace teams · Givers at every level",
 "tier": "Tier 1 — Church & Company",
 "core_ref": "Acts 20:35 (NIV)",
 "core_text": "...remembering the words the Lord Jesus himself said: 'It is more blessed to give than to receive.'",
 "marketing": "Generosity is one of the great surprises of the Christian life: the people who give most freely are almost always the people who are most at peace. Yet scarcity and fear keep most of us holding on tighter than we want to. This campaign reframes generosity not as an obligation but as a gift, walking participants from the joy of giving, through the move from scarcity to abundance, into a lifestyle of open-handed living that touches money, time, talent, and presence. The result is a congregation that gives more, fears less, and lives lighter.",
 "why_matters": "Generosity is the clearest evidence that someone has been set free from the love of money, and it is the engine of every ministry, mission, and act of mercy a church can do.",
 "problem": "Scarcity and fear keep us gripping what we have, and the joy and freedom God designed generosity to bring stay just out of reach.",
 "transformation": "From scarcity to abundance; from clenched to open-handed; from reluctant giver to joyful, free, generous person.",
 "formats": ["4-Session", "6-Session", "21-Day", "30-Day", "40-Day"],
 "sessions": [
   ("The Surprising Joy of Giving", "Why generosity makes us free"),
   ("From Scarcity to Abundance", "Trusting the God who supplies the seed"),
   ("The Cheerful Giver", "Giving from the heart, not from pressure"),
   ("Generosity Beyond Money", "Open hands with time, talent, and presence"),
   ("The Generosity Ripple", "How giving multiplies far beyond us"),
   ("A Lifestyle of Generosity", "Living open-handed for good"),
 ],
 "scriptures": ["2 Corinthians 9:6-11", "Acts 20:35", "Luke 6:38", "Proverbs 11:24-25", "Malachi 3:10", "1 Timothy 6:18-19"],
 "movements": [
  {"roman":"I","title":"The Joy of Giving","subtitle":"More Blessed to Give","days":[
    (1,"The Backwards Blessing","Giving beats getting","Acts 20:35; Prov 11:25"),
    (2,"The Free-est People","Generosity and freedom","2 Cor 9:7; Luke 12:33-34"),
    (3,"The Grip of Greed","What hoarding does to us","Luke 12:15-21; 1 Tim 6:9-10"),
    (4,"Treasure That Lasts","Investing in eternity","Matt 6:19-21; 1 Tim 6:18-19"),
    (5,"The Widow's Wonder","Big giving from little","Mark 12:41-44; Luke 21:1-4"),
    (6,"Giving as Worship","Generosity unto God","2 Cor 9:11-13; Heb 13:16"),
    (7,"The First Gift","Beginning to give","2 Cor 8:5; Prov 3:9"),
  ]},
  {"roman":"II","title":"Scarcity to Abundance","subtitle":"Trusting the Supplier","days":[
    (8,"The Scarcity Lie","\"There's never enough\"","Eccl 5:10; Matt 6:31-32"),
    (9,"More Than Enough","The God of abundant supply","2 Cor 9:8; Phil 4:19"),
    (10,"The Sower's Math","Sow little, reap little","2 Cor 9:6; Gal 6:7"),
    (11,"He Supplies the Seed","God funds our giving","2 Cor 9:10; Deut 8:18"),
    (12,"Give and It's Given","The overflowing return","Luke 6:38; Prov 19:17"),
    (13,"The Generosity Paradox","Give more, have more","Prov 11:24-25; Mal 3:10"),
    (14,"Test Him in This","The one invitation to test God","Mal 3:10; 2 Chr 31:10"),
  ]},
  {"roman":"III","title":"The Cheerful Giver","subtitle":"From the Heart","days":[
    (15,"Not Reluctantly","God loves a cheerful giver","2 Cor 9:7; Exod 25:2"),
    (16,"Decide in Your Heart","Planned, prayerful giving","2 Cor 9:7; 1 Cor 16:2"),
    (17,"The Macedonian Joy","Joy in giving through hardship","2 Cor 8:1-4; Acts 2:44-45"),
    (18,"Excel in Giving","A grace worth growing in","2 Cor 8:7; Rom 12:8"),
    (19,"First, Not Last","Off the top, not leftovers","Prov 3:9-10; Gen 4:3-4"),
    (20,"The Heart Behind the Gift","Why motive matters","Matt 6:1-4; 1 Cor 13:3"),
    (21,"Sacrificial, Not Surplus","Giving that actually costs","2 Sam 24:24; Mark 12:43-44"),
  ]},
  {"roman":"IV","title":"Beyond Money","subtitle":"Time, Talent, Presence","days":[
    (22,"More Than a Check","Generous with all of life","Rom 12:1; 1 Pet 4:10"),
    (23,"The Gift of Time","Generosity with our hours","Eph 5:15-16; Ps 90:12"),
    (24,"The Gift of Presence","Showing up for others","Rom 12:15; Gal 6:2"),
    (25,"Hospitality's Open Door","Sharing the table","1 Pet 4:9; Rom 12:13"),
    (26,"Gifts to Serve","Stewarding your abilities","1 Pet 4:10-11; Rom 12:6-8"),
    (27,"Generous With Mercy","Forgiveness freely given","Matt 18:21-22; Eph 4:32"),
    (28,"The Generosity of Words","Encouragement freely given","Prov 11:25; Eph 4:29"),
  ]},
  {"roman":"V","title":"The Ripple Effect","subtitle":"How Giving Multiplies","days":[
    (29,"Enriched to Be Generous","Blessed in order to bless","2 Cor 9:11; Gen 12:2"),
    (30,"Meeting Real Needs","Generosity with open eyes","1 John 3:17; Jas 2:15-16"),
    (31,"Thanksgiving Overflows","Giving produces gratitude to God","2 Cor 9:12; Acts 4:34-35"),
    (32,"The Cup That Overflows","Abundance meant to spill","Ps 23:5; John 7:38"),
    (33,"Generosity Is Contagious","Stirring others up","2 Cor 9:2; Heb 10:24"),
    (34,"Lending to the Lord","God repays the generous","Prov 19:17; Matt 25:40"),
    (35,"A Harvest of Righteousness","The long-term fruit","2 Cor 9:10; Hos 10:12"),
  ]},
  {"roman":"VI","title":"A Lifestyle of Generosity","subtitle":"Open-Handed for Good","days":[
    (36,"From Act to Identity","Becoming a generous person","1 Tim 6:18; Acts 9:36"),
    (37,"Rich in Good Deeds","The wealth that truly counts","1 Tim 6:17-19; Titus 3:8"),
    (38,"Generous to the End","A lifelong open hand","Ps 112:9; 2 Cor 9:9"),
    (39,"A Legacy of Generosity","Giving that outlives us","Prov 13:22; Matt 6:20"),
    (40,"The Most Free Life","Living open-handed forever","2 Cor 9:8; Prov 11:25"),
  ]},
 ],
},
]
