# -*- coding: utf-8 -*-
"""40-Day devotional maps — Batch 4 (nums 32-37): Budgeting & Order.
6 movements aligned to the 6 sessions, 40 days in a 7-7-7-7-7-5 arc."""

MAPS = {
 # ---------------- 32 · The One-Page Money Plan ----------------
 32: [
  {"roman":"I","title":"Make It Plain","subtitle":"Write the Vision Down","days":[
   (1,"Write the Vision","Make it plain","Hab 2:2; Prov 21:5"),
   (2,"Plain Enough to Run","Clear at a glance","Hab 2:2; Prov 15:22"),
   (3,"The Power of Written","Out of the head","Hab 2:2; Prov 16:3"),
   (4,"A Plan You Can See","Clarity over chaos","Hab 2:2; 1 Cor 14:40"),
   (5,"Wait for It","The plan unfolds","Hab 2:3; Prov 21:5"),
   (6,"One Page, Not Ten","Simple and usable","Hab 2:2; Eccl 5:2"),
   (7,"Putting It on Paper","The first draft","Hab 2:2; Prov 21:5"),
  ]},
  {"roman":"II","title":"The Whole Picture","subtitle":"Seeing It All at Once","days":[
   (8,"See It All at Once","The full picture","Prov 27:23; Luke 14:28"),
   (9,"Income in View","What comes in","Prov 27:23-24; Prov 13:16"),
   (10,"Outgo in View","What goes out","Luke 14:28; Hag 1:5-6"),
   (11,"No Blind Spots","Nothing hidden","Luke 8:17; Prov 27:23"),
   (12,"The Honest Snapshot","Reality on a page","Prov 27:23; Luke 14:28"),
   (13,"Build With Knowledge","Rooms filled by wisdom","Prov 24:3-4; Prov 13:16"),
   (14,"The Whole Picture","Clear and complete","Prov 27:23-24; Hab 2:2"),
  ]},
  {"roman":"III","title":"The Four Numbers","subtitle":"The Whole Plan in Order","days":[
   (15,"Income","What you earn","Prov 27:23; Deut 8:18"),
   (16,"Giving","What goes first","Prov 3:9-10; 2 Cor 9:7"),
   (17,"Saving","What you keep","Prov 21:20; Prov 6:8"),
   (18,"Spending","What's left to live on","Luke 14:28; Prov 21:5"),
   (19,"Four Simple Numbers","The whole plan","Hab 2:2; Prov 21:5"),
   (20,"In Right Order","First things first","Matt 6:33; Prov 3:9"),
   (21,"The Four in Balance","A plan that works","Prov 21:5; 1 Cor 14:40"),
  ]},
  {"roman":"IV","title":"Seeing It at a Glance","subtitle":"The Dashboard View","days":[
   (22,"At a Glance","The dashboard view","Hab 2:2; Prov 22:3"),
   (23,"Know Where You Stand","Today's position","Prov 27:23; Prov 14:15"),
   (24,"Spotting Trouble Early","The prudent foresee","Prov 22:3; Prov 27:12"),
   (25,"Quick to Adjust","Course corrections","Prov 15:22; Prov 21:5"),
   (26,"One Look, One Plan","Simplicity that sticks","Hab 2:2; 1 Cor 14:40"),
   (27,"Clarity Brings Calm","Order over anxiety","1 Cor 14:33; Phil 4:6-7"),
   (28,"Seen at a Glance","The plan in view","Hab 2:2; Prov 27:23"),
  ]},
  {"roman":"V","title":"Keeping It Current","subtitle":"A Living Plan","days":[
   (29,"Tend It Regularly","Keep the numbers fresh","Prov 27:23-24; Lam 3:23"),
   (30,"A Living Plan","Updated, not framed","Prov 27:23; Prov 21:5"),
   (31,"Riches Don't Endure","So watch them","Prov 27:24; Prov 23:5"),
   (32,"The Weekly Glance","Staying current","Ps 90:12; Prov 27:23"),
   (33,"Adjust as Life Changes","Flexing the plan","Prov 16:9; Prov 15:22"),
   (34,"Faithful Attention","Ongoing care","Luke 16:10; 1 Cor 4:2"),
   (35,"Kept Current","The plan stays true","Prov 27:23-24; Hab 2:2"),
  ]},
  {"roman":"VI","title":"The Plan That Sticks","subtitle":"Clear, Current, Kept","days":[
   (36,"Simple Enough to Keep","Why one page works","Hab 2:2; Eccl 5:2"),
   (37,"Do It in Order","Decently and in order","1 Cor 14:40; Col 2:5"),
   (38,"From Plan to Habit","Living the page","Jas 1:22-25; Prov 21:5"),
   (39,"The Plan That Holds","Sustained over time","Hab 2:2-3; Gal 6:9"),
   (40,"The One-Page Plan","Clear, current, kept","Hab 2:2; Prov 21:5"),
  ]},
 ],
 # ---------------- 33 · Give Every Dollar a Job ----------------
 33: [
  {"roman":"I","title":"Where Did It Go?","subtitle":"Finding the Leaks","days":[
   (1,"The Vanishing Money","Where did it go","Hag 1:6; Prov 27:23"),
   (2,"Leaks in the Purse","Untracked spending","Hag 1:6; Prov 21:20"),
   (3,"The Unwatched Flock","Not knowing your condition","Prov 27:23; Prov 23:5"),
   (4,"Money Without Memory","No record kept","Prov 27:23-24; Luke 16:10"),
   (5,"Surprised at Month's End","The mystery shortfall","Hag 1:6; Prov 21:5"),
   (6,"The Cost of Not Knowing","Drift in the dark","Prov 27:23; Prov 22:3"),
   (7,"Tracking It Down","Finding the leaks","Prov 27:23; Hag 1:7"),
  ]},
  {"roman":"II","title":"Every Dollar Employed","subtitle":"Money on Assignment","days":[
   (8,"Give Each Dollar a Job","Money on assignment","Prov 27:23; Prov 21:5"),
   (9,"No Idle Dollars","All of it working","Prov 21:5; Matt 25:14-18"),
   (10,"Assign Before You Spend","The plan precedes","Luke 14:28; Prov 21:5"),
   (11,"Name Every Use","Purpose for each","Prov 21:5; Hab 2:2"),
   (12,"Down to Zero","Every dollar placed","Prov 27:23-24; Prov 13:16"),
   (13,"Tell Money Where to Go","You direct it","Prov 21:5; Luke 16:11"),
   (14,"Every Dollar Employed","Nothing wasted","Prov 27:23; Prov 21:5"),
  ]},
  {"roman":"III","title":"Know Your Flocks","subtitle":"Faithful Oversight","days":[
   (15,"Know Their Condition","Watch your flocks","Prov 27:23; Prov 24:3-4"),
   (16,"Give Careful Attention","To your herds","Prov 27:23; Luke 14:28"),
   (17,"Riches Don't Last","So pay attention","Prov 27:24; Prov 23:5"),
   (18,"Counting the Categories","Knowing each area","Prov 27:23; Prov 13:16"),
   (19,"The Diligent Knows","Insight into the flow","Prov 13:16; Prov 21:5"),
   (20,"Tend, Don't Neglect","Faithful oversight","Prov 27:23-24; Luke 16:10"),
   (21,"Flocks Well Known","The shepherd's care","Prov 27:23; Prov 24:3-4"),
  ]},
  {"roman":"IV","title":"The Monthly Assignment","subtitle":"Planning Ahead","days":[
   (22,"Before the Month Begins","Plan ahead","Prov 21:5; Luke 14:28"),
   (23,"A Fresh Assignment","Each month anew","Lam 3:23; Prov 21:5"),
   (24,"Anticipate the Bills","Nothing forgotten","Prov 22:3; Prov 27:12"),
   (25,"Plan for the Irregular","The non-monthly costs","Prov 21:5; Prov 6:8"),
   (26,"Build in Margin","Room in the plan","Prov 21:20; Prov 21:5"),
   (27,"The Plan on Paper","Written and ready","Hab 2:2; Prov 21:5"),
   (28,"The Month Assigned","Every dollar placed","Prov 27:23; Prov 21:5"),
  ]},
  {"roman":"V","title":"When Plans Change","subtitle":"Flexible, Not Fragile","days":[
   (29,"Life Interrupts","Plans meet reality","Prov 16:9; Prov 19:21"),
   (30,"Move, Don't Quit","Reassign, don't abandon","Prov 24:16; Prov 21:5"),
   (31,"The Flex of Wisdom","Adjusting the plan","Prov 15:22; Prov 16:9"),
   (32,"Cover the Overage","Shifting between jobs","Prov 21:5; Luke 14:28"),
   (33,"Grace for the Imperfect","Start again","Lam 3:22-23; Phil 3:13-14"),
   (34,"A Plan That Bends","Flexible, not fragile","Prov 16:9; Prov 21:5"),
   (35,"Adjusted and On Track","Plans realigned","Prov 16:9; Prov 27:23"),
  ]},
  {"roman":"VI","title":"Money on Command","subtitle":"Directed, Not Drifting","days":[
   (36,"You Tell It Where","Command over money","Prov 21:5; Luke 16:11"),
   (37,"Master, Not Servant","Money under you","Matt 6:24; Prov 22:7"),
   (38,"Faithful in the Details","Trusted with much","Luke 16:10; Prov 27:23"),
   (39,"Money With a Job","Purpose for every dollar","Prov 27:23; Prov 21:5"),
   (40,"Money on Command","Directed, not drifting","Prov 21:5; Prov 27:23-24"),
  ]},
 ],
 # ---------------- 34 · Order Out of Money Chaos ----------------
 34: [
  {"roman":"I","title":"The Hum of Chaos","subtitle":"The Background Stress","days":[
   (1,"The Background Stress","Money chaos hums","1 Cor 14:33; Prov 22:3"),
   (2,"Scattered and Anxious","No system, much worry","Prov 24:3-4; Matt 6:25"),
   (3,"The Constant Low Roar","Disorder's noise","1 Cor 14:33; Prov 25:28"),
   (4,"Missed and Forgotten","Bills that slip","Prov 27:23; Prov 22:3"),
   (5,"Reacting, Not Planning","Always behind","Prov 21:5; Prov 22:3"),
   (6,"The Toll of Disorder","Peace eroded","1 Cor 14:33; Prov 17:1"),
   (7,"Longing for Order","Ready for calm","1 Cor 14:33; Ps 37:23"),
  ]},
  {"roman":"II","title":"A God of Order","subtitle":"Form Out of the Void","days":[
   (8,"Not a God of Disorder","But of peace","1 Cor 14:33; 1 Cor 14:40"),
   (9,"Order From the Start","He formed and filled","Gen 1:1-2; Gen 1:31"),
   (10,"Form Out of Void","Bringing order to chaos","Gen 1:2; Ps 33:6-9"),
   (11,"He Orders Our Steps","Established by the Lord","Ps 37:23; Prov 16:9"),
   (12,"Decently and in Order","The pattern","1 Cor 14:40; Col 2:5"),
   (13,"Made in His Image","Called to order too","Gen 1:27; 1 Cor 14:33"),
   (14,"A God of Peace","Order brings calm","1 Cor 14:33; Phil 4:9"),
  ]},
  {"roman":"III","title":"Gathering the Scattered","subtitle":"Pulling It Together","days":[
   (15,"Gather What's Scattered","Pulling it together","Prov 24:3-4; Prov 27:23"),
   (16,"One Place to Look","Centralizing the chaos","Prov 27:23; Hab 2:2"),
   (17,"Name Every Account","Knowing what's there","Prov 27:23-24; Luke 14:28"),
   (18,"List the Obligations","All bills in view","Prov 22:3; Prov 27:12"),
   (19,"By Knowledge Filled","Rooms of wisdom","Prov 24:3-4; Prov 13:16"),
   (20,"The Scattered Collected","A clear inventory","Prov 27:23; Prov 24:3-4"),
   (21,"Gathered and Seen","Chaos contained","Prov 24:3-4; Hab 2:2"),
  ]},
  {"roman":"IV","title":"First Structures","subtitle":"Simple Systems First","days":[
   (22,"Build the Framework","Simple systems first","Prov 24:3; 1 Cor 14:40"),
   (23,"A Place for Bills","When and how they're paid","Prov 27:23; Prov 21:5"),
   (24,"A Rhythm for Money","Regular attention","Ps 90:12; Lam 3:23"),
   (25,"Automate the Basics","Order that holds","Prov 21:5; Prov 13:16"),
   (26,"Simple, Not Complex","Structures you'll keep","Eccl 5:2; 1 Cor 14:40"),
   (27,"Built to Last","Established by wisdom","Prov 24:3-4; Matt 7:24"),
   (28,"First Structures Set","The framework stands","1 Cor 14:40; Prov 24:3"),
  ]},
  {"roman":"V","title":"Calm Restored","subtitle":"Order Brings Quiet","days":[
   (29,"Peace Where Chaos Was","Order brings rest","1 Cor 14:33; Phil 4:6-7"),
   (30,"The Quieted Mind","Anxiety lifts","Phil 4:6-7; Isa 26:3"),
   (31,"Knowing Brings Peace","No more dread","Prov 27:23; Ps 112:7"),
   (32,"Steps Made Firm","The Lord establishes","Ps 37:23-24; Prov 16:9"),
   (33,"Rest in Order","Calm in the system","1 Cor 14:33; Ps 23:2-3"),
   (34,"The Roar Silenced","Stress replaced by peace","1 Cor 14:33; Phil 4:9"),
   (35,"Calm Restored","Order brings quiet","1 Cor 14:33; Phil 4:7"),
  ]},
  {"roman":"VI","title":"Keeping the Order","subtitle":"Chaos Held at Bay","days":[
   (36,"Maintain the System","Tend it faithfully","Prov 27:23; Luke 16:10"),
   (37,"A Regular Review","Keeping it current","Ps 90:12; Prov 27:23-24"),
   (38,"Order as a Habit","Sustained over time","1 Cor 14:40; Gal 6:9"),
   (39,"Peace That Remains","Order kept, calm kept","1 Cor 14:33; Phil 4:9"),
   (40,"Keeping the Order","Chaos held at bay","1 Cor 14:33; Prov 24:3-4"),
  ]},
 ],
 # ---------------- 35 · The Spending Plan ----------------
 35: [
  {"roman":"I","title":"Budget vs. Plan","subtitle":"Not a Cage, a Plan","days":[
   (1,"Not a Cage, a Plan","Reframing the budget","Prov 16:9; Prov 21:5"),
   (2,"The Heart Plans","The Lord directs","Prov 16:9; Prov 19:21"),
   (3,"A Tool, Not a Punishment","Freedom, not restriction","Prov 21:5; Gal 5:13"),
   (4,"Tell Money Where to Go","Direction, not denial","Prov 16:9; Luke 16:11"),
   (5,"The Plan Serves You","Money as servant","Prov 21:5; Matt 6:24"),
   (6,"Permission to Spend","A plan includes joy","Eccl 5:19; 1 Tim 6:17"),
   (7,"From Budget to Plan","The mindset shift","Prov 16:9; Prov 21:5"),
  ]},
  {"roman":"II","title":"The Life You Want","subtitle":"Funding What Matters","days":[
   (8,"Begin With the End","What life you're funding","Prov 16:9; Prov 29:18"),
   (9,"Name Your Values","Money follows them","Matt 6:21; Prov 4:23"),
   (10,"Dream, Then Plan","Vision before numbers","Prov 29:18; Hab 2:2"),
   (11,"What Matters Most","Funding first things","Matt 6:33; Prov 3:9"),
   (12,"The Good Life Defined","God's design for it","Eccl 5:18-19; 1 Tim 6:17-19"),
   (13,"Plan Toward It","Aligning the spending","Prov 16:9; Prov 21:5"),
   (14,"The Life in View","A plan with purpose","Prov 16:9; Phil 4:8"),
  ]},
  {"roman":"III","title":"Planning the Course","subtitle":"Marking Out the Path","days":[
   (15,"A Heart That Plans","The human part","Prov 16:9; Prov 21:5"),
   (16,"Steps Directed","The Lord's part","Prov 16:9; Ps 37:23"),
   (17,"Mark Out the Path","Level the course","Prov 4:26; Prov 21:5"),
   (18,"The Diligent Plan","Toward plenty","Prov 21:5; Prov 13:11"),
   (19,"Count Before You Build","Finish what you start","Luke 14:28-30; Prov 24:27"),
   (20,"Plans With Counsel","Wisdom in advice","Prov 15:22; Prov 11:14"),
   (21,"The Course Set","The plan laid out","Prov 16:9; Prov 4:26"),
  ]},
  {"roman":"IV","title":"Saying Yes on Purpose","subtitle":"Intentional Spending","days":[
   (22,"Yes to What Matters","Intentional spending","Prov 16:9; Phil 1:9-10"),
   (23,"Fund the Priorities","First things financed","Matt 6:33; Prov 3:9"),
   (24,"Spend on the Good","Approving the best","Phil 1:9-10; 1 Cor 10:23"),
   (25,"Joy Without Guilt","Enjoying God's gifts","Eccl 5:19; 1 Tim 6:17"),
   (26,"Generous on Purpose","Giving in the plan","2 Cor 9:7; 1 Cor 16:2"),
   (27,"Aligned With Values","Dollars match the heart","Matt 6:21; Prov 21:5"),
   (28,"Yes, on Purpose","Spending with intent","Prov 16:9; Phil 1:9-10"),
  ]},
  {"roman":"V","title":"Guilt-Free Spending","subtitle":"Enjoying God's Gifts","days":[
   (29,"No More Guilt","Spending within the plan","Eccl 5:19; 1 Tim 6:17"),
   (30,"Richly Provided","God gives to enjoy","1 Tim 6:17; Eccl 5:18-19"),
   (31,"Every Good Gift","Received with thanks","Jas 1:17; 1 Tim 4:4-5"),
   (32,"Planned Means Free","Pre-decided spending","Prov 16:9; Prov 21:5"),
   (33,"Enjoy Without Excess","Joy with wisdom","Eccl 5:19; Prov 21:17"),
   (34,"Gratitude in Spending","Thankful, not guilty","1 Tim 6:17; Col 3:17"),
   (35,"Guilt-Free at Last","Freedom in the plan","Eccl 5:19; Prov 16:9"),
  ]},
  {"roman":"VI","title":"A Plan You Love","subtitle":"Spending That Brings Peace","days":[
   (36,"A Plan That Fits","Built for your life","Prov 16:9; Prov 21:5"),
   (37,"Sustainable Joy","A plan you'll keep","Gal 6:9; Eccl 5:19"),
   (38,"The Plan as Freedom","Living on purpose","Gal 5:13; Prov 16:9"),
   (39,"Loving the Plan","Not enduring it","Prov 16:9; Phil 4:8"),
   (40,"A Plan You Love","Spending that brings peace","Prov 16:9; Eccl 5:19"),
  ]},
 ],
 # ---------------- 36 · Money Made Manageable ----------------
 36: [
  {"roman":"I","title":"Why It Feels Hard","subtitle":"Beginning Without Fear","days":[
   (1,"The Overwhelm","Why money feels hard","Prov 6:6; Prov 24:33-34"),
   (2,"Avoidance and Dread","Not looking at it","Prov 22:3; Hag 1:5"),
   (3,"The Tangle","Too complicated to start","Eccl 5:2; 1 Cor 14:40"),
   (4,"Paralyzed by Numbers","Where to even begin","Prov 21:5; Prov 13:16"),
   (5,"Hard, but Not Impossible","Hope for the daunted","Prov 6:6-8; Phil 4:13"),
   (6,"One Small Start","The first manageable step","Luke 16:10; Zech 4:10"),
   (7,"Facing It Gently","Beginning without fear","Prov 6:6; Phil 4:6"),
  ]},
  {"roman":"II","title":"Lessons From the Ant","subtitle":"Diligence That Works","days":[
   (8,"Go to the Ant","Consider its ways","Prov 6:6; Prov 30:24-25"),
   (9,"No Commander Needed","Self-directed diligence","Prov 6:7; Prov 30:25"),
   (10,"Stores in Summer","Preparing in season","Prov 6:8; Prov 30:25"),
   (11,"Little but Wise","Small and effective","Prov 30:24-25; Luke 16:10"),
   (12,"Steady Provision","The ant's quiet work","Prov 6:8; Prov 13:11"),
   (13,"Wisdom in the Small","Big lessons, little teacher","Prov 6:6; Prov 30:24"),
   (14,"The Ant's Way","Diligence that works","Prov 6:6-8; Prov 21:5"),
  ]},
  {"roman":"III","title":"Small Habits, Big Order","subtitle":"Little by Little","days":[
   (15,"Faithful in Little","Small habits matter","Luke 16:10; Prov 13:11"),
   (16,"One Habit at a Time","Building slowly","Prov 21:5; Gal 6:9"),
   (17,"The Daily Glance","A small check-in","Ps 90:12; Prov 27:23"),
   (18,"Little by Little","Order accumulates","Prov 13:11; Luke 16:10"),
   (19,"Small Wins Compound","Progress adds up","Prov 13:11; Gal 6:9"),
   (20,"Tiny, Repeatable Steps","Sustainable change","Luke 16:10; Prov 21:5"),
   (21,"Big Order, Small Habits","The quiet system","Prov 21:5; Prov 6:8"),
  ]},
  {"roman":"IV","title":"Tools You'll Actually Use","subtitle":"Function Over Flash","days":[
   (22,"Simple Tools","Decently and in order","1 Cor 14:40; Prov 13:16"),
   (23,"The Right Fit","What you'll actually keep","Eccl 5:2; Prov 21:5"),
   (24,"Not Fancy, Just Used","Function over flash","Prov 13:16; 1 Cor 14:40"),
   (25,"Automate What You Can","Order that holds itself","Prov 21:5; Prov 6:8"),
   (26,"One System, Not Five","Keep it simple","Eccl 5:2; 1 Cor 14:40"),
   (27,"Tools That Serve","Helping, not hindering","Prov 13:16; Prov 21:5"),
   (28,"Equipped to Manage","The right tools in hand","Prov 13:16; Prov 6:6-8"),
  ]},
  {"roman":"V","title":"Doable, Not Daunting","subtitle":"Progress, Not Perfection","days":[
   (29,"Broken Into Steps","Manageable pieces","Prov 21:5; Luke 14:28"),
   (30,"One Thing Today","Just the next step","Luke 16:10; Phil 4:13"),
   (31,"Progress, Not Perfection","Grace to keep going","Prov 24:16; Phil 3:13-14"),
   (32,"The Doable Plan","Right-sized for you","Prov 21:5; Eccl 5:2"),
   (33,"Celebrate Small Steps","Encouragement along the way","Zech 4:10; Gal 6:9"),
   (34,"Not Weary in Doing","Keeping at it","Gal 6:9; 2 Thess 3:13"),
   (35,"Doable, Day by Day","Daunting no more","Prov 6:6-8; Phil 4:13"),
  ]},
  {"roman":"VI","title":"Steady and Manageable","subtitle":"Money Made Simple","days":[
   (36,"A Manageable Rhythm","Money under control","Prov 6:6-8; Luke 16:10"),
   (37,"Steady Wins","Consistency over intensity","Prov 13:11; Gal 6:9"),
   (38,"The Quiet Confidence","Knowing your money","Prov 27:23; Ps 112:7"),
   (39,"Manageable for Good","A lasting system","Prov 6:6-8; Prov 21:5"),
   (40,"Steady and Manageable","Money made simple","Prov 6:6; Luke 16:10"),
  ]},
 ],
 # ---------------- 37 · The Weekly Money Check-In ----------------
 37: [
  {"roman":"I","title":"The Slow Drift","subtitle":"Off Course Without Noticing","days":[
   (1,"The Quiet Drift","Off course slowly","Ps 90:12; Heb 2:1"),
   (2,"Out of Sight, Off Track","Neglect's cost","Prov 27:23; Hag 1:5-6"),
   (3,"Small Leaks Unwatched","Drift accumulates","Hag 1:6; Prov 21:20"),
   (4,"The Unexamined Month","Surprised again","Prov 27:23; Prov 21:5"),
   (5,"Drifting Without Noticing","The gradual slide","Heb 2:1; Prov 22:3"),
   (6,"Catching the Drift","A regular look","Prov 27:23; Ps 90:12"),
   (7,"Anchoring the Week","The check-in begins","Ps 90:12; Prov 27:23"),
  ]},
  {"roman":"II","title":"Number Your Days","subtitle":"A Heart of Wisdom","days":[
   (8,"Teach Us to Number","Days made to count","Ps 90:12; Eph 5:15-16"),
   (9,"A Heart of Wisdom","The fruit of counting","Ps 90:12; Prov 9:10"),
   (10,"Make the Most of Time","Redeeming the days","Eph 5:15-16; Col 4:5"),
   (11,"Life Is Brief","Steward it well","Ps 90:12; Jas 4:14"),
   (12,"Intentional With Time","And with money","Eph 5:15-16; Prov 21:5"),
   (13,"Counting What Matters","Days and dollars","Ps 90:12; Matt 6:33"),
   (14,"Numbered and Wise","Time stewarded","Ps 90:12; Eph 5:16"),
  ]},
  {"roman":"III","title":"The Fifteen-Minute Check","subtitle":"A Short, Regular Look","days":[
   (15,"Just Fifteen Minutes","A short, regular look","Prov 27:23; Luke 16:10"),
   (16,"Know Your Condition","Where you stand","Prov 27:23-24; Prov 14:15"),
   (17,"Review the Week","What came and went","Prov 27:23; Hag 1:5"),
   (18,"Adjust as Needed","Small corrections","Prov 15:22; Prov 16:9"),
   (19,"Look Ahead","The week to come","Prov 21:5; Prov 22:3"),
   (20,"Quick and Faithful","The simple habit","Luke 16:10; Prov 27:23"),
   (21,"The Check Complete","Fifteen minutes well spent","Prov 27:23; Ps 90:12"),
  ]},
  {"roman":"IV","title":"Tending, Not Overhauling","subtitle":"Gentle Upkeep","days":[
   (22,"Small Adjustments","Tend, don't tear down","Prov 27:23; Prov 15:22"),
   (23,"Course Corrections","Little nudges","Prov 16:9; Prov 21:5"),
   (24,"Faithful Maintenance","Ongoing care","Luke 16:10; 1 Cor 4:2"),
   (25,"Not a Big Overhaul","Just light tending","Prov 27:23-24; Lam 3:23"),
   (26,"Weeding the Garden","Keeping it healthy","Prov 24:30-31; Prov 27:23"),
   (27,"Steady Tending","Consistent care","Prov 27:23; Gal 6:9"),
   (28,"Tended, Not Torn Up","Gentle upkeep","Prov 27:23; Prov 21:5"),
  ]},
  {"roman":"V","title":"Making It a Rhythm","subtitle":"A Habit That Holds","days":[
   (29,"A Set Time","Same day each week","Ps 90:12; Prov 21:5"),
   (30,"New Every Week","Mercies and check-ins","Lam 3:22-23; Ps 90:12"),
   (31,"Rhythm Over Willpower","Habit that holds","Gal 6:9; 1 Cor 9:25"),
   (32,"Protecting the Time","Guarding the habit","Eph 5:15-16; Prov 21:5"),
   (33,"When You Miss a Week","Grace to resume","Prov 24:16; Phil 3:13-14"),
   (34,"The Settled Routine","A rhythm formed","Gal 6:9; Luke 16:10"),
   (35,"Made a Rhythm","The weekly habit","Ps 90:12; Prov 27:23"),
  ]},
  {"roman":"VI","title":"On Track for Good","subtitle":"The Weekly Rhythm Holds","days":[
   (36,"Steady on Course","Drift corrected","Ps 90:12; Heb 2:1"),
   (37,"The Compounding Check","Small habit, big fruit","Gal 6:9; Luke 16:10"),
   (38,"Peace in Knowing","No more dread","Prov 27:23; Ps 112:7"),
   (39,"Faithful Week by Week","Endurance rewarded","Gal 6:9; 1 Cor 15:58"),
   (40,"On Track for Good","The weekly rhythm holds","Ps 90:12; Prov 27:23"),
  ]},
 ],
}
