# -*- coding: utf-8 -*-
"""40-Day devotional maps for non-flagship campaigns — Batch 1 (nums 11-16).
Structure matches the flagship campaigns: 6 movements (aligned to the 6 sessions),
40 days each in a 7-7-7-7-7-5 arc, every day = (n, title, focus, NIV refs)."""

MAPS = {
 # ---------------- 11 · Whose Money Is It? ----------------
 11: [
  {"roman":"I","title":"Owner or Manager","subtitle":"The Two Roles","days":[
   (1,"The Unasked Question","The one we skip","Hag 2:8; Ps 24:1"),
   (2,"Two Ways to Hold","Owning versus managing","Luke 16:1-2; 1 Cor 4:1"),
   (3,"The Owner's Weight","Why owning exhausts","Eccl 5:10-12; Luke 12:15"),
   (4,"The Manager's Ease","A lighter way to carry","Matt 11:28-30; 1 Pet 5:7"),
   (5,"Everything Received","Nothing is self-made","1 Cor 4:7; Jas 1:17"),
   (6,"We Brought Nothing","Empty hands in and out","Job 1:21; 1 Tim 6:7"),
   (7,"Settling It Today","Choosing the manager's role","Josh 24:15; Ps 24:1"),
  ]},
  {"roman":"II","title":"The Owner's Claim","subtitle":"Whose It Really Is","days":[
   (8,"The Earth Is His","All of it belongs to God","Ps 24:1; Ps 50:10-12"),
   (9,"Silver and Gold","Even the money is His","Hag 2:8; Deut 8:18"),
   (10,"Maker of It All","He owns what He made","Col 1:16; Ps 89:11"),
   (11,"Cattle on the Hills","His by right of creation","Ps 50:10-11; Gen 1:1"),
   (12,"Breath and Ability","He gives the power to earn","Acts 17:25; Deut 8:18"),
   (13,"Held Together","Sustained by Him each moment","Col 1:17; Heb 1:3"),
   (14,"No Exceptions","Nothing outside His claim","Rom 11:36; 1 Chr 29:11-12"),
  ]},
  {"roman":"III","title":"The Manager's Job","subtitle":"What We're Entrusted To Do","days":[
   (15,"A Trust to Keep","Faithfulness is required","1 Cor 4:2; Luke 12:42"),
   (16,"Put It to Work","Stewards don't bury it","Matt 25:14-18; Luke 19:13"),
   (17,"Manage His Way","On the Owner's terms","Luke 16:10-12; 1 Pet 4:10"),
   (18,"Watch the Flocks","Attend to what you hold","Prov 27:23-24; Luke 16:11"),
   (19,"First His Portion","Honor the Owner first","Prov 3:9-10; Mal 3:10"),
   (20,"Generous on His Behalf","Releasing what isn't ours","2 Cor 9:7-8; Acts 20:35"),
   (21,"Faithful in Little","Small trust, greater trust","Luke 16:10; Matt 25:21"),
  ]},
  {"roman":"IV","title":"The Weight That Lifts","subtitle":"The Freedom of Managing","days":[
   (22,"Nothing to Protect","The fear loosens","1 Tim 6:17-19; Matt 6:25"),
   (23,"Nothing to Prove","Worth isn't net worth","1 Sam 16:7; Luke 12:15"),
   (24,"Loss Reframed","It was never ours","Job 1:21; Ps 62:10"),
   (25,"Open Hands","Holding it all loosely","1 Tim 6:7; Eccl 5:15"),
   (26,"Anxiety Released","The Owner carries it","1 Pet 5:7; Phil 4:6-7"),
   (27,"Freed to Give","Generosity flows from trust","2 Cor 9:6-8; Prov 11:24-25"),
   (28,"Lighter Already","The manager rests","Matt 11:28-30; Ps 23:1"),
  ]},
  {"roman":"V","title":"The Day of Accounting","subtitle":"Stewards Give a Report","days":[
   (29,"A Coming Reckoning","Managers report back","Rom 14:12; Luke 16:2"),
   (30,"Well Done","The words we long to hear","Matt 25:21; Matt 25:23"),
   (31,"The Wasteful Manager","A warning to heed","Luke 16:1-2; Luke 12:48"),
   (32,"Trusted With More","Faithfulness multiplies","Luke 19:17; Matt 25:29"),
   (33,"Living Ready","Stewarding with the end in view","Luke 12:42-44; 2 Cor 5:10"),
   (34,"What Lasts","Storing where it counts","Matt 6:19-21; 1 Tim 6:18-19"),
   (35,"The Master's Joy","Sharing His happiness","Matt 25:21; Heb 12:2"),
  ]},
  {"roman":"VI","title":"Living the Answer","subtitle":"Walking It Out","days":[
   (36,"A New Posture","Daily life as a steward","Col 3:23-24; 1 Cor 10:31"),
   (37,"Re-deciding Daily","Renewing the choice","Rom 12:1-2; Lam 3:22-23"),
   (38,"In the Small Things","Ownership shows up everywhere","Luke 16:10; Zech 4:10"),
   (39,"Telling the Truth","He owns it; I manage it","Ps 24:1; Hag 2:8"),
   (40,"The Settled Steward","Free, faithful, at rest","1 Tim 6:6-8; Ps 24:1"),
  ]},
 ],
 # ---------------- 12 · The Faithful Steward ----------------
 12: [
  {"roman":"I","title":"Entrusted, Not Owned","subtitle":"The Setup of Every Parable","days":[
   (1,"The Master's Goods","It all belongs to Him","Matt 25:14; Ps 24:1"),
   (2,"A Servant's Role","We manage another's wealth","Luke 16:1; 1 Cor 4:1"),
   (3,"Required: Faithful","The one thing asked","1 Cor 4:2; Luke 12:42"),
   (4,"According to Ability","Entrusted in measure","Matt 25:15; Rom 12:6"),
   (5,"Stewards of Grace","Managing all God gives","1 Pet 4:10; Eph 3:2"),
   (6,"Whose Servant","Daily we choose a master","Matt 6:24; Rom 6:16"),
   (7,"Ready to Manage","Taking up the trust","Luke 12:35-36; Matt 25:14"),
  ]},
  {"roman":"II","title":"The Parable of the Talents","subtitle":"Faithfulness Puts It to Work","days":[
   (8,"Five, Two, One","Each given something","Matt 25:15; Luke 19:13"),
   (9,"At Once to Work","The faithful invest","Matt 25:16; Prov 13:11"),
   (10,"The Buried Talent","Fear that does nothing","Matt 25:18; Matt 25:25"),
   (11,"Good and Faithful","The Master's verdict","Matt 25:21; Matt 25:23"),
   (12,"The Wicked, Lazy Servant","Neglect has a cost","Matt 25:26-27; Prov 18:9"),
   (13,"More to the Faithful","Faithfulness multiplies","Matt 25:29; Luke 19:26"),
   (14,"Using What You Have","No talent too small","1 Pet 4:10; Luke 16:10"),
  ]},
  {"roman":"III","title":"The Shrewd Manager","subtitle":"Wise With What Isn't Yours","days":[
   (15,"Called to Account","The manager's reckoning","Luke 16:2; Rom 14:12"),
   (16,"Shrewd, Not Sinful","Wise use of resources","Luke 16:8; Matt 10:16"),
   (17,"Friends for Eternity","Investing in what lasts","Luke 16:9; Matt 6:20"),
   (18,"Faithful With Little","Proves trust with much","Luke 16:10; Matt 25:21"),
   (19,"Worldly Wealth, Eternal Use","Money in kingdom service","Luke 16:11; 1 Tim 6:18-19"),
   (20,"Cannot Serve Both","God or money","Luke 16:13; Matt 6:24"),
   (21,"Trustworthy With True Riches","Money is the test","Luke 16:11-12; Luke 19:17"),
  ]},
  {"roman":"IV","title":"Faithful in Little","subtitle":"Small Trust, Greater Trust","days":[
   (22,"Very Little Matters","The proving ground","Luke 16:10; Zech 4:10"),
   (23,"The Ordinary Test","Faithfulness in the daily","Col 3:23; 1 Cor 10:31"),
   (24,"Diligent, Not Slack","Tending the trust","Prov 27:23; Prov 12:24"),
   (25,"Hidden Faithfulness","Seen by the Master alone","Matt 6:4; Col 3:23-24"),
   (26,"Little by Little","Quiet faithfulness compounds","Prov 13:11; Luke 16:10"),
   (27,"Steady Over Time","Endurance in stewarding","Gal 6:9; 1 Cor 15:58"),
   (28,"Trusted With More","The reward of faithful little","Luke 19:17; Matt 25:21"),
  ]},
  {"roman":"V","title":"The Master Returns","subtitle":"Living Ready to Give Account","days":[
   (29,"He Will Return","An accounting is coming","Matt 25:19; Luke 19:15"),
   (30,"Found Watching","Ready when He comes","Luke 12:37; Matt 24:46"),
   (31,"Found Working","Busy with the trust","Matt 24:45-46; Luke 12:43"),
   (32,"To Whom Much Given","Greater trust, greater account","Luke 12:48; Jas 3:1"),
   (33,"The Books Opened","Each gives account","Rom 14:12; 2 Cor 5:10"),
   (34,"Treasure That Greets You","Sent on ahead","Matt 6:20; 1 Tim 6:19"),
   (35,"No Wasted Trust","Stewarding to the end","1 Cor 4:2; 2 Tim 4:7"),
  ]},
  {"roman":"VI","title":"Well Done","subtitle":"The Reward of the Faithful","days":[
   (36,"The Words We Long For","Well done, good servant","Matt 25:21; Matt 25:23"),
   (37,"Share the Master's Joy","Beyond the reward","Matt 25:21; Heb 12:2"),
   (38,"Put in Charge of More","Faithfulness enlarges","Matt 25:23; Luke 19:17"),
   (39,"A Crown That Lasts","Running to finish","1 Cor 9:25; 2 Tim 4:8"),
   (40,"Faithful for Good","A steward to the end","1 Cor 4:2; Rev 2:10"),
  ]},
 ],
 # ---------------- 13 · First Things First ----------------
 13: [
  {"roman":"I","title":"The Order of Things","subtitle":"Why First Matters","days":[
   (1,"What Comes First","Order reveals the heart","Matt 6:33; Prov 3:9"),
   (2,"First, Not Most","Priority over amount","Prov 3:9; 2 Cor 8:12"),
   (3,"The Leftovers Trap","God last, bills first","Hag 1:9; Mal 1:8"),
   (4,"Seek First","The kingdom before the rest","Matt 6:33; Luke 12:31"),
   (5,"Honor With Wealth","Putting God at the front","Prov 3:9; 1 Tim 1:17"),
   (6,"Where God Belongs","First place in all things","Col 1:18; Ex 20:3"),
   (7,"Reordering Today","Putting first things first","Matt 6:33; Prov 3:9-10"),
  ]},
  {"roman":"II","title":"The Firstfruits Principle","subtitle":"Off the Top","days":[
   (8,"The First of the Harvest","Given before the rest","Prov 3:9; Ex 23:19"),
   (9,"Cain and Abel","The better offering","Gen 4:3-5; Heb 11:4"),
   (10,"Bring the First","Not what's left over","Ex 34:26; Neh 10:35"),
   (11,"The Best, Not the Rest","Honoring God with quality","Mal 1:8; Lev 22:20"),
   (12,"Barns Overflowing","The promise behind it","Prov 3:10; 2 Cor 9:6"),
   (13,"Test Me in This","God's open invitation","Mal 3:10; 2 Cor 9:8"),
   (14,"First Means Trust","Giving before you see","Prov 3:5; Mal 3:10"),
  ]},
  {"roman":"III","title":"The Trust to Give First","subtitle":"Faith at the Front","days":[
   (15,"Giving First Is Faith","Trusting the rest to God","Prov 3:5-6; 2 Cor 9:8"),
   (16,"The Widow's First","Out of her need","1 Kgs 17:13-14; Luke 21:4"),
   (17,"Fear of Not Enough","The lie that holds back","Matt 6:31-33; Phil 4:19"),
   (18,"God Goes Before","Provision follows obedience","Deut 31:8; Phil 4:19"),
   (19,"Loosening the Grip","First-giving frees the hand","2 Cor 9:7; Acts 20:35"),
   (20,"He Will Provide","The Owner supplies","Gen 22:14; Matt 6:33"),
   (21,"Trusting the Remainder","Enough is left","Phil 4:19; 2 Cor 9:8"),
  ]},
  {"roman":"IV","title":"Tithes and Beginnings","subtitle":"Where Giving Takes Root","days":[
   (22,"Abraham's Tenth","Generosity before the law","Gen 14:20; Heb 7:2"),
   (23,"Jacob's Vow","A tenth of all","Gen 28:22; Deut 14:22"),
   (24,"The Whole Tithe","Bringing it in full","Mal 3:10; Lev 27:30"),
   (25,"More Than a Rule","The heart behind the tithe","Matt 23:23; 2 Cor 9:7"),
   (26,"A Starting Line","Not the finish","Mal 3:10; 2 Cor 8:7"),
   (27,"Giving as Worship","An offering to God","Phil 4:18; Heb 13:16"),
   (28,"Building the Habit","First-giving, every time","1 Cor 16:2; 2 Cor 9:7"),
  ]},
  {"roman":"V","title":"Trusting the Rest","subtitle":"What Comes After","days":[
   (29,"After You Give","God with the remainder","Phil 4:19; Ps 37:25"),
   (30,"Enough and to Spare","His abundance","2 Cor 9:8; Phil 4:19"),
   (31,"Daily Bread Follows","Provision day by day","Matt 6:11; Matt 6:33"),
   (32,"No Good Thing Withheld","God's generous heart","Ps 84:11; Rom 8:32"),
   (33,"Contentment in the Rest","Enough is a gift","1 Tim 6:6-8; Heb 13:5"),
   (34,"The Cheerful Remainder","Joy on both sides","2 Cor 9:7; Prov 11:25"),
   (35,"Provided For","Looking back in trust","Ps 37:25; Deut 2:7"),
  ]},
  {"roman":"VI","title":"A First-Things Life","subtitle":"A Budget That Honors God","days":[
   (36,"First in the Budget","God at the top line","Prov 3:9; Matt 6:33"),
   (37,"First in the Heart","Where it really starts","Matt 6:21; Col 3:1-2"),
   (38,"First in the Week","Giving with intention","1 Cor 16:2; 2 Cor 9:7"),
   (39,"First, Then the Rest","The settled order","Matt 6:33; Prov 3:9-10"),
   (40,"A Life Put First","God honored off the top","Prov 3:9-10; Phil 4:19"),
  ]},
 ],
 # ---------------- 14 · Money on Purpose ----------------
 14: [
  {"roman":"I","title":"The Purse With Holes","subtitle":"Where the Money Goes","days":[
   (1,"Give Careful Thought","Examining the ways","Hag 1:5; Lam 3:40"),
   (2,"A Purse With Holes","Money leaking away","Hag 1:6; Prov 21:5"),
   (3,"Nothing to Show","Spent, but for what","Eccl 2:11; Hag 1:9"),
   (4,"The Quiet Drift","No aim, no direction","Prov 21:5; Eph 5:15-16"),
   (5,"Sowing for the Wind","Effort without harvest","Hos 8:7; Hag 1:6"),
   (6,"The Cost of Drift","Where leaking leads","Prov 13:11; Prov 21:5"),
   (7,"Time to Examine","Looking honestly at it","Hag 1:7; 2 Cor 13:5"),
  ]},
  {"roman":"II","title":"Give Careful Thought","subtitle":"Examining How We Spend","days":[
   (8,"Consider Your Ways","The unexamined purse","Hag 1:5-7; Prov 4:26"),
   (9,"Count the Cost","Knowing before spending","Luke 14:28; Prov 24:27"),
   (10,"The Prudent Plan","Forethought pays off","Prov 21:5; Prov 14:15"),
   (11,"Honest Numbers","Facing the real picture","Prov 27:23; Luke 14:28"),
   (12,"Where It Actually Went","Tracing the leaks","Hag 1:6; Prov 27:23-24"),
   (13,"Make the Most of Time","Redeeming the days","Eph 5:15-16; Ps 90:12"),
   (14,"Ready to Realign","From drift to direction","Prov 4:25-27; Hag 1:7"),
  ]},
  {"roman":"III","title":"Naming What Matters","subtitle":"Values Before Dollars","days":[
   (15,"What Do You Treasure","Money follows the heart","Matt 6:21; Luke 12:34"),
   (16,"First Things Named","Clarifying priorities","Matt 6:33; Prov 3:9"),
   (17,"Commit Your Plans","Offering them to God","Prov 16:3; Ps 37:5"),
   (18,"His Will, Your Mission","Aligning with God's aims","Rom 12:2; Eph 5:17"),
   (19,"People Over Things","What truly counts","Mark 8:36; 1 Tim 6:18"),
   (20,"Eternity in View","Spending for what lasts","2 Cor 4:18; Matt 6:20"),
   (21,"A Clear Aim","Knowing the target","Phil 3:14; Prov 4:25"),
  ]},
  {"roman":"IV","title":"Aligning the Flow","subtitle":"Pointing Money at Priorities","days":[
   (22,"Every Dollar Aimed","Spending on purpose","Prov 21:5; Luke 16:11"),
   (23,"Plans That Hold","The diligent prosper","Prov 21:5; Prov 16:9"),
   (24,"Funding First Things","God, family, mission","Prov 3:9; 1 Tim 5:8"),
   (25,"Generosity on the Plan","Giving by design","2 Cor 9:7; 1 Cor 16:2"),
   (26,"Saving on Purpose","Foresight built in","Prov 21:20; Prov 6:6-8"),
   (27,"Margin by Design","Room left on purpose","Prov 21:20; Luke 14:28"),
   (28,"The Aligned Purse","Money serving the mission","Matt 6:33; Prov 16:3"),
  ]},
  {"roman":"V","title":"Cutting the Drift","subtitle":"Removing What Doesn't Serve","days":[
   (29,"Name the Leaks","Spotting the waste","Hag 1:6; Prov 21:20"),
   (30,"Lay Aside the Weight","Cutting the excess","Heb 12:1; Luke 12:15"),
   (31,"No to the Good","Saying yes to the best","Phil 1:9-10; 1 Cor 10:23"),
   (32,"Tame the Impulse","Slowing the spend","Prov 21:5; Prov 25:28"),
   (33,"Simplicity Restored","Less drift, more aim","Luke 12:15; 1 Tim 6:8"),
   (34,"Redeem the Waste","Reclaiming the dollars","Eph 5:15-16; Hag 1:7"),
   (35,"Lighter and Aimed","Free of the leaks","Heb 12:1; Prov 4:26-27"),
  ]},
  {"roman":"VI","title":"Money With a Mission","subtitle":"Living On Purpose","days":[
   (36,"On Purpose, Daily","Intention every day","Eph 5:15-16; Col 3:23"),
   (37,"Money in Its Place","A tool, not a master","Matt 6:24; 1 Tim 6:10"),
   (38,"Spending That Reflects","Dollars match values","Matt 6:21; 2 Cor 9:7"),
   (39,"Careful Thought, Settled","The examined purse","Hag 1:5; Prov 4:26"),
   (40,"A Mission-Driven Life","Money serving what matters","Matt 6:33; Prov 16:3"),
  ]},
 ],
 # ---------------- 15 · The Heart of Money ----------------
 15: [
  {"roman":"I","title":"Treasure and Heart","subtitle":"The Two Are Tied","days":[
   (1,"Where Your Treasure Is","There the heart goes","Matt 6:21; Luke 12:34"),
   (2,"Heart Follows Money","The trail leads home","Matt 6:21; Luke 16:13"),
   (3,"More Than Math","A heart issue, not a money one","Luke 12:15; 1 Tim 6:10"),
   (4,"What You Love","Money reveals it","Matt 6:24; Eccl 5:10"),
   (5,"The Inner Spring","Out of the heart, life","Prov 4:23; Luke 6:45"),
   (6,"Treasure in Heaven","Aiming the heart higher","Matt 6:20-21; Col 3:1-2"),
   (7,"Listening to Money","What it says about you","Matt 6:21; Luke 12:34"),
  ]},
  {"roman":"II","title":"The Mirror of Money","subtitle":"What Habits Reveal","days":[
   (8,"Money as Mirror","Habits expose the heart","Luke 16:10-11; Matt 6:21"),
   (9,"The Anxious Heart","Worry tells a story","Matt 6:25; Luke 12:22-25"),
   (10,"The Grasping Heart","Greed laid bare","Luke 12:15; Eccl 5:10"),
   (11,"The Fearful Heart","Hoarding reveals distrust","Matt 25:25; 1 John 4:18"),
   (12,"The Generous Heart","Open hands, open soul","2 Cor 9:7; Prov 11:25"),
   (13,"Honest Reflection","Facing what we see","Ps 139:23-24; 2 Cor 13:5"),
   (14,"Beyond the Surface","The heart beneath habits","1 Sam 16:7; Prov 4:23"),
  ]},
  {"roman":"III","title":"Two Masters","subtitle":"Money as a Rival","days":[
   (15,"You Cannot Serve Both","God or money","Matt 6:24; Luke 16:13"),
   (16,"Mammon's Pull","The rival for the throne","Matt 6:24; Col 3:5"),
   (17,"Divided Loyalty","Hating one, loving the other","Matt 6:24; Jas 4:4"),
   (18,"Who Is Master","The honest question","Rom 6:16; 1 Cor 6:12"),
   (19,"Idol on the Throne","Greed as idolatry","Col 3:5; Eph 5:5"),
   (20,"Dethroning Money","Returning God to first","Matt 6:33; Ex 20:3"),
   (21,"One Master Served","Undivided at last","Matt 6:24; Josh 24:15"),
  ]},
  {"roman":"IV","title":"The Root","subtitle":"Understanding the Love of Money","days":[
   (22,"Not Money, but Love","The root Scripture names","1 Tim 6:10; Heb 13:5"),
   (23,"A Root of Evils","What grows from it","1 Tim 6:10; Jas 4:1-2"),
   (24,"Piercing Griefs","The wounds it brings","1 Tim 6:10; Prov 15:27"),
   (25,"How It Takes Hold","The slow grip","1 Tim 6:9; Mark 4:19"),
   (26,"Wandering From Faith","Where money love leads","1 Tim 6:10; Matt 13:22"),
   (27,"Naming the Root","Honest before God","Ps 139:23; 1 John 1:9"),
   (28,"Pulling It Up","Loosening the grip","Heb 13:5; Luke 12:15"),
  ]},
  {"roman":"V","title":"The Never-Enough Ache","subtitle":"Why More Never Satisfies","days":[
   (29,"Never Satisfied","The lover of money","Eccl 5:10; Prov 27:20"),
   (30,"The Hedonic Chase","More that fades","Eccl 2:10-11; Eccl 5:10"),
   (31,"The Empty Promise","Money's broken vow","Eccl 5:10; Ps 62:10"),
   (32,"Bread That Doesn't Satisfy","Spending on the wrong things","Isa 55:2; John 6:35"),
   (33,"The Ache Beneath","A God-shaped hunger","Ps 107:9; Matt 5:6"),
   (34,"Satisfied in Him","Where the ache ends","Ps 16:11; Ps 23:1"),
   (35,"Filled, Not Full","Contentment as gift","Phil 4:11-13; 1 Tim 6:6"),
  ]},
  {"roman":"VI","title":"A Changed Heart","subtitle":"When the Heart Shifts","days":[
   (36,"A New Treasure","The heart re-aimed","Matt 6:20-21; Col 3:2"),
   (37,"Guard the Heart","Tending the spring","Prov 4:23; Phil 4:7"),
   (38,"Rich Toward God","The wealth that counts","Luke 12:21; 1 Tim 6:18-19"),
   (39,"Money Follows","A changed heart, changed habits","Matt 6:21; 2 Cor 9:7"),
   (40,"A Heart Set Free","Money in its place","Matt 6:24; Heb 13:5"),
  ]},
 ],
 # ---------------- 16 · Everyday Stewardship ----------------
 16: [
  {"roman":"I","title":"Faithful in Very Little","subtitle":"Why Small Counts Most","days":[
   (1,"Whoever Is Faithful","Little proves much","Luke 16:10; Matt 25:21"),
   (2,"The Proving Ground","Small things test us","Luke 16:10-12; Zech 4:10"),
   (3,"Trusted With More","Faithfulness opens doors","Luke 16:10; Luke 19:17"),
   (4,"The Everyday Trust","Ordinary stewardship","1 Cor 4:2; 1 Pet 4:10"),
   (5,"Not Despising Small","God's eye on the little","Zech 4:10; Matt 10:42"),
   (6,"The Grocery and the Gas","Stewardship in the mundane","Col 3:17; 1 Cor 10:31"),
   (7,"Faithful Where You Are","Starting with today","Luke 16:10; Col 3:23"),
  ]},
  {"roman":"II","title":"The Unseen Choices","subtitle":"Stewardship Nobody Applauds","days":[
   (8,"Seen by God Alone","Hidden faithfulness","Matt 6:4; Col 3:23-24"),
   (9,"No Applause Needed","Working for the Lord","Col 3:23; Eph 6:7"),
   (10,"The Small Yes","Quiet right choices","Luke 16:10; Prov 11:3"),
   (11,"The Small No","Restraint nobody sees","Prov 25:28; Titus 2:12"),
   (12,"Integrity in Private","The same when alone","Ps 51:6; Prov 10:9"),
   (13,"Faithful in the Dark","Stewardship off-stage","1 Cor 4:2; Luke 12:2-3"),
   (14,"The Unseen Adds Up","Quiet choices shape a life","Luke 16:10; Gal 6:9"),
  ]},
  {"roman":"III","title":"Whatever You Do","subtitle":"Working and Spending as Worship","days":[
   (15,"Whatever You Do","All for the Lord","Col 3:23; 1 Cor 10:31"),
   (16,"To the Glory of God","Even the ordinary","1 Cor 10:31; 1 Cor 6:20"),
   (17,"Work as Worship","Service rendered to Him","Col 3:23-24; Eph 6:7"),
   (18,"Spending as Worship","Money offered to God","Rom 12:1; 2 Cor 9:7"),
   (19,"Wholehearted","Not half-measures","Col 3:23; Eccl 9:10"),
   (20,"As Unto Him","The audience of One","Col 3:23-24; Gal 1:10"),
   (21,"Sacred Ordinary","Everyday made holy","1 Cor 10:31; Rom 12:1"),
  ]},
  {"roman":"IV","title":"The Compounding of Small","subtitle":"How Little Adds Up","days":[
   (22,"Little by Little","Growth over time","Prov 13:11; Luke 16:10"),
   (23,"Faithful Daily","Repetition that shapes","Lam 3:22-23; Gal 6:9"),
   (24,"The Slow Build","Patience in stewarding","Prov 21:5; Prov 13:11"),
   (25,"Habits Become a Life","Small choices, big sum","Prov 4:23; 1 Tim 4:7-8"),
   (26,"Not Weary in Doing","Keeping at the little","Gal 6:9; 2 Thess 3:13"),
   (27,"A Harvest in Time","Reaping what's sown","Gal 6:9; 2 Cor 9:6"),
   (28,"Compounded Faithfulness","Small days, large fruit","Luke 16:10; Matt 25:21"),
  ]},
  {"roman":"V","title":"Despise Not Small Days","subtitle":"God's Heart for the Ordinary","days":[
   (29,"The Day of Small Things","God rejoices in it","Zech 4:10; Matt 13:31-32"),
   (30,"A Cup of Water","Small acts, real reward","Matt 10:42; Mark 9:41"),
   (31,"The Mustard Seed","Little beginnings","Matt 13:31-32; Luke 13:18-19"),
   (32,"The Widow's Mite","Small gift, great worth","Mark 12:43-44; Luke 21:1-4"),
   (33,"Faithful Servants","Honored in the little","Matt 25:23; Luke 19:17"),
   (34,"God Sees It All","Nothing overlooked","Heb 6:10; 1 Cor 15:58"),
   (35,"Small and Significant","Ordinary days matter","Zech 4:10; Col 3:23"),
  ]},
  {"roman":"VI","title":"A Well-Managed Life","subtitle":"The Fruit of Everyday Faithfulness","days":[
   (36,"A Life Stewarded Well","The sum of small days","Luke 16:10; 1 Cor 4:2"),
   (37,"Faithful to the End","Endurance in the ordinary","1 Cor 15:58; Rev 2:10"),
   (38,"Every Area His","Whole-life stewardship","Col 3:17; Rom 12:1"),
   (39,"Ordinary, Offered","Daily life as worship","1 Cor 10:31; Col 3:23"),
   (40,"Well Done in the Little","The faithful steward's joy","Matt 25:21; Luke 16:10"),
  ]},
 ],
}
