# -*- coding: utf-8 -*-
"""40-Day devotional maps — Batch 11 (nums 76-80): Marriage & Family (all Tier 2).
6 movements aligned to the 6 sessions, 40 days in a 7-7-7-7-7-5 arc."""

MAPS = {
 # ---------------- 76 · Raising Money-Smart Kids ----------------
 76: [
  {"roman":"I","title":"Lasting Lessons","subtitle":"Money Wisdom for Life","days":[
   (1,"Train Up a Child","Lessons that last","Prov 22:6; Deut 6:6-7"),
   (2,"The Way They Should Go","Pointing them right","Prov 22:6; Prov 1:8"),
   (3,"When They Are Old","The long view","Prov 22:6; Ps 78:6-7"),
   (4,"More Caught Than Taught","They watch us","Deut 6:6-7; 1 Cor 11:1"),
   (5,"The Cost of Not Teaching","Lessons learned hard","Prov 22:6; Prov 29:15"),
   (6,"Start Now","It's never too early","Deut 6:7; Prov 22:6"),
   (7,"Lasting Lessons","Money wisdom for life","Prov 22:6; Deut 6:6-7"),
  ]},
  {"roman":"II","title":"Start Them Right","subtitle":"A Solid Foundation","days":[
   (8,"Begin Early","The wet cement","Prov 22:6; Eccl 12:1"),
   (9,"Simple First Lessons","Age-appropriate truth","Prov 4:1; Deut 6:7"),
   (10,"Money Is a Tool","Not a treasure","Luke 12:15; Matt 6:24"),
   (11,"God Owns It All","The foundation","Ps 24:1; 1 Chr 29:14"),
   (12,"Needs and Wants","The first distinction","Prov 30:8-9; Phil 4:11-12"),
   (13,"Patience Over Impulse","Teaching self-control","Prov 25:28; Prov 21:5"),
   (14,"Start Them Right","A solid foundation","Prov 22:6; Eccl 12:1"),
  ]},
  {"roman":"III","title":"Teaching Work and Earning","subtitle":"Diligence Instilled","days":[
   (15,"The Value of Work","Earning what they have","Prov 14:23; Gen 2:15"),
   (16,"Go to the Ant","Diligence taught young","Prov 6:6-8; Prov 10:4"),
   (17,"Work Before Reward","Effort then pay","2 Thess 3:10; Prov 12:11"),
   (18,"Chores and Character","Responsibility built","Prov 22:29; Luke 16:10"),
   (19,"Earning Their Own","The dignity of work","Eph 4:28; 1 Thess 4:11-12"),
   (20,"Faithful in Little","The training ground","Luke 16:10; Prov 13:11"),
   (21,"Teaching Work and Earning","Diligence instilled","Prov 14:23; Prov 6:6-8"),
  ]},
  {"roman":"IV","title":"Teaching Saving and Wisdom","subtitle":"Prudence Passed On","days":[
   (22,"Save Before You Spend","The first habit","Prov 21:20; Prov 13:11"),
   (23,"Little by Little","Watching it grow","Prov 13:11; Prov 21:5"),
   (24,"Delayed Gratification","The marshmallow lesson","Prov 25:28; Prov 21:5"),
   (25,"Wise Choices","Counting the cost young","Luke 14:28; Prov 14:15"),
   (26,"Avoiding Debt's Trap","An early warning","Prov 22:7; Rom 13:8"),
   (27,"The Ant's Foresight","Saving for later","Prov 6:6-8; Prov 30:25"),
   (28,"Teaching Saving and Wisdom","Prudence passed on","Prov 21:20; Prov 13:11"),
  ]},
  {"roman":"V","title":"Teaching Generosity","subtitle":"Open-Handed Kids","days":[
   (29,"Give a Portion","The first gift","Prov 3:9-10; 2 Cor 9:7"),
   (30,"The Joy of Giving","Caught, not forced","Acts 20:35; 2 Cor 9:7"),
   (31,"Letting Them Give","Their own offering","Mark 12:43-44; 2 Cor 8:12"),
   (32,"Generous Hearts Formed","Open hands young","Prov 11:24-25; 1 Tim 6:18"),
   (33,"Giving With a Face","Seeing the need","Prov 19:17; Matt 25:40"),
   (34,"More Blessed to Give","The lesson learned","Acts 20:35; Luke 6:38"),
   (35,"Teaching Generosity","Open-handed kids","2 Cor 9:7; Prov 11:25"),
  ]},
  {"roman":"VI","title":"Money-Smart for Life","subtitle":"Children Well-Trained","days":[
   (36,"Wisdom That Sticks","Lessons for a lifetime","Prov 22:6; Prov 4:1-2"),
   (37,"A Legacy of Wisdom","More than money","Prov 13:22; Ps 78:4-7"),
   (38,"Prepared to Launch","Ready for the world","Prov 22:6; Eccl 12:1"),
   (39,"The Next Generation","Equipped and wise","Ps 78:6-7; 2 Tim 1:5"),
   (40,"Money-Smart for Life","Children well-trained","Prov 22:6; Deut 6:6-7"),
  ]},
 ],
 # ---------------- 77 · Talking to Your Kids About Money ----------------
 77: [
  {"roman":"I","title":"The Silent Subject","subtitle":"Time to Speak","days":[
   (1,"The Money Taboo","Why we don't talk","Prov 4:1; Eph 6:4"),
   (2,"Breaking the Silence","Opening the conversation","Prov 4:1-2; Deut 6:7"),
   (3,"They're Already Learning","From somewhere","Deut 6:7; Prov 22:6"),
   (4,"Honest, Age-Wise Talk","Truth they can hold","Prov 4:1; Ps 78:4"),
   (5,"No Shame, No Fear","A safe subject","Eph 6:4; Prov 4:1"),
   (6,"Inviting the Questions","Open doors","Prov 4:1; Deut 6:7"),
   (7,"The Silent Subject","Time to speak","Prov 4:1; Eph 6:4"),
  ]},
  {"roman":"II","title":"A Father's Instruction","subtitle":"Teaching With Love","days":[
   (8,"Listen, My Children","A father's teaching","Prov 4:1; Prov 1:8"),
   (9,"Pay Attention, Gain Insight","The invitation","Prov 4:1; Prov 4:5"),
   (10,"Do Not Exasperate","Instruction with grace","Eph 6:4; Col 3:21"),
   (11,"In the Training of the Lord","Gentle guidance","Eph 6:4; Deut 6:7"),
   (12,"Sound Teaching","Don't forsake it","Prov 4:2; Prov 1:8-9"),
   (13,"Wisdom Handed Down","Parent to child","Prov 4:1-4; Ps 78:5-6"),
   (14,"A Father's Instruction","Teaching with love","Prov 4:1; Eph 6:4"),
  ]},
  {"roman":"III","title":"Little Ones","subtitle":"First Money Lessons","days":[
   (15,"Simple Truths","For young hearts","Deut 6:7; Prov 22:6"),
   (16,"Money Is Earned","The first idea","Prov 14:23; Gen 3:19"),
   (17,"Saving in a Jar","Seeing it grow","Prov 21:20; Prov 13:11"),
   (18,"Giving a Little","The first gift","2 Cor 9:7; Mark 12:43-44"),
   (19,"Wants Can Wait","Patience taught","Prov 25:28; Prov 21:5"),
   (20,"Learning Through Play","Concrete lessons","Prov 22:6; Deut 6:7"),
   (21,"Little Ones","First money lessons","Deut 6:7; Prov 22:6"),
  ]},
  {"roman":"IV","title":"The Middle Years","subtitle":"Deepening Lessons","days":[
   (22,"Growing Understanding","Bigger concepts","Prov 4:1; Prov 9:9"),
   (23,"An Allowance With Purpose","Practice money","Luke 16:10; Prov 21:5"),
   (24,"Save, Give, Spend","The three jars","Prov 21:20; 2 Cor 9:7"),
   (25,"The Cost of Things","Counting before buying","Luke 14:28; Prov 14:15"),
   (26,"Earning Beyond Allowance","Work for extra","Prov 14:23; Eph 4:28"),
   (27,"Wise Choices Practiced","Small decisions","Prov 13:16; Luke 16:10"),
   (28,"The Middle Years","Deepening lessons","Prov 4:1; Prov 9:9"),
  ]},
  {"roman":"V","title":"The Teen Years","subtitle":"Readying for Independence","days":[
   (29,"Preparing to Launch","Real-world readiness","Prov 22:6; Eccl 12:1"),
   (30,"Bigger Money, Bigger Lessons","Jobs and budgets","Luke 16:10; Prov 21:5"),
   (31,"The Danger of Debt","A clear warning","Prov 22:7; Rom 13:8"),
   (32,"Saving for Goals","Long-term thinking","Prov 21:20; Prov 13:11"),
   (33,"Generosity as a Teen","Owning their giving","2 Cor 9:7; 1 Tim 6:18"),
   (34,"Letting Them Decide","And learn","Gal 6:7; Luke 15:13-19"),
   (35,"The Teen Years","Readying for independence","Prov 22:6; Eccl 12:1"),
  ]},
  {"roman":"VI","title":"Always Teaching","subtitle":"The Open Dialogue","days":[
   (36,"Talk Along the Way","Everyday moments","Deut 6:7; Prov 4:1"),
   (37,"Model What You Teach","Words and life","1 Cor 11:1; Eph 6:4"),
   (38,"Never Stop","A lifelong conversation","Prov 4:1; Ps 78:4"),
   (39,"The Conversation Continues","Into adulthood","Prov 4:1-2; Prov 13:22"),
   (40,"Always Teaching","The open dialogue","Prov 4:1; Deut 6:7"),
  ]},
 ],
 # ---------------- 78 · Money Lessons for the Family ----------------
 78: [
  {"roman":"I","title":"Learning Together","subtitle":"The Family Classroom","days":[
   (1,"A Family That Learns","Growing as one","Ps 78:4; Deut 6:6-7"),
   (2,"Not Hiding From Children","Telling the next generation","Ps 78:4; Ps 78:6"),
   (3,"Around the Table","Shared learning","Deut 11:18-19; Ps 78:4"),
   (4,"Faith and Finances Together","Both passed down","2 Tim 1:5; Ps 78:4-7"),
   (5,"Everyone Participates","All ages learning","Deut 11:19; Ps 78:4"),
   (6,"A Household on Mission","Serving the Lord","Josh 24:15; Deut 6:6-7"),
   (7,"Learning Together","The family classroom","Ps 78:4; Deut 6:6-7"),
  ]},
  {"roman":"II","title":"Tell the Next Generation","subtitle":"The Story Continues","days":[
   (8,"Tell the Coming Generation","God's deeds declared","Ps 78:4; Ps 145:4"),
   (9,"What We Have Heard","Passing it on","Ps 78:3-4; Ps 78:5"),
   (10,"So They Set Their Hope","The purpose of telling","Ps 78:6-7; Ps 78:5"),
   (11,"Not Forgetting His Works","Remembering together","Ps 78:7; Deut 6:12"),
   (12,"A Faith Passed Down","Like Timothy's","2 Tim 1:5; 2 Tim 3:15"),
   (13,"Generation to Generation","The relay of wisdom","Ps 78:4-7; Ps 102:18"),
   (14,"Tell the Next Generation","The story continues","Ps 78:4; Ps 145:4"),
  ]},
  {"roman":"III","title":"Stewardship for All Ages","subtitle":"The Whole Family","days":[
   (15,"God Owns It All","The family foundation","Ps 24:1; 1 Chr 29:14"),
   (16,"Stewards, Not Owners","Managing His gifts","1 Pet 4:10; Luke 16:10-11"),
   (17,"Faithful With What We Have","At every age","Luke 16:10; Matt 25:21"),
   (18,"Everyone a Steward","Young and old","1 Pet 4:10; Ps 78:4"),
   (19,"Tending God's Gifts","The family calling","Gen 2:15; Col 3:23"),
   (20,"Accountable to Him","The shared trust","Luke 16:2; Rom 14:12"),
   (21,"Stewardship for All Ages","The whole family","1 Pet 4:10; Luke 16:10"),
  ]},
  {"roman":"IV","title":"Saving as a Family","subtitle":"Foresight Shared","days":[
   (22,"Saving Together","A shared goal","Prov 21:20; Prov 13:11"),
   (23,"The Family Fund","Building it as one","Prov 6:6-8; Prov 21:5"),
   (24,"Patience as a Household","Waiting well","Prov 13:11; Prov 21:5"),
   (25,"A Goal Everyone Shares","Pulling together","Eccl 4:9; Phil 2:2"),
   (26,"Wise With the Surplus","Storing, not gulping","Prov 21:20; Prov 21:17"),
   (27,"Celebrating Milestones","Family wins","Ps 126:3; Luke 15:6"),
   (28,"Saving as a Family","Foresight shared","Prov 21:20; Prov 13:11"),
  ]},
  {"roman":"V","title":"Giving as a Family","subtitle":"Generosity Shared","days":[
   (29,"Giving Together","A family offering","2 Cor 9:7; Ps 96:8"),
   (30,"Choosing a Cause","Generosity with a face","Prov 19:17; Matt 25:40"),
   (31,"Everyone Gives","Each hand open","Mark 12:43-44; 2 Cor 8:12"),
   (32,"The Joy of Family Giving","Glad hearts","Acts 20:35; 2 Cor 9:7"),
   (33,"Serving Together","Hands and money","Gal 5:13; Acts 20:35"),
   (34,"A Generous Household","Open hands at home","Prov 11:25; 1 Tim 6:18"),
   (35,"Giving as a Family","Generosity shared","2 Cor 9:7; Prov 11:25"),
  ]},
  {"roman":"VI","title":"A Shared Story","subtitle":"The Family's Legacy","days":[
   (36,"The Family Story","Money and faith woven","Ps 78:4; Josh 24:15"),
   (37,"A Heritage of Wisdom","Passed to children","Prov 13:22; 2 Tim 1:5"),
   (38,"Serving the Lord Together","The household's aim","Josh 24:15; Col 3:23-24"),
   (39,"Generations Blessed","The ripple forward","Ps 78:6-7; Ps 112:1-2"),
   (40,"A Shared Story","The family's legacy","Ps 78:4; Deut 6:6-7"),
  ]},
 ],
 # ---------------- 79 · The Family Money Meeting ----------------
 79: [
  {"roman":"I","title":"The Money Silence","subtitle":"Ready to Break It","days":[
   (1,"The Unspoken Topic","Money silence at home","Eccl 4:9; Amos 3:3"),
   (2,"Avoidance and Tension","What silence breeds","Prov 15:22; Eph 4:25"),
   (3,"Drifting Apart","Without communication","Amos 3:3; Eccl 4:9-10"),
   (4,"The Cost of Not Talking","Surprises and strife","Prov 13:10; Prov 15:22"),
   (5,"Breaking the Silence","Starting the meeting","Eccl 4:9; Prov 15:22"),
   (6,"A Safe Conversation","Honesty without blame","Eph 4:25; Col 3:19"),
   (7,"The Money Silence","Ready to break it","Eccl 4:9; Amos 3:3"),
  ]},
  {"roman":"II","title":"Two Are Better","subtitle":"The Case for Partnership","days":[
   (8,"Two Are Better Than One","The team principle","Eccl 4:9; Eccl 4:10"),
   (9,"A Good Return for Labor","Working together","Eccl 4:9; Gen 2:18"),
   (10,"If One Falls","The other helps up","Eccl 4:10; Gal 6:2"),
   (11,"A Cord of Three Strands","God in the middle","Eccl 4:12; Matt 18:20"),
   (12,"Walking in Agreement","United on money","Amos 3:3; Phil 2:2"),
   (13,"Stronger Together","The household team","Eccl 4:9-12; Eccl 4:12"),
   (14,"Two Are Better","The case for partnership","Eccl 4:9; Eccl 4:12"),
  ]},
  {"roman":"III","title":"Setting the Table","subtitle":"The Meeting Begins","days":[
   (15,"A Regular Time","Setting the meeting","Eccl 4:9; Prov 21:5"),
   (16,"A Calm Setting","The right atmosphere","Prov 15:1; Col 3:19"),
   (17,"Plans Need Counsel","Talking it through","Prov 15:22; Prov 11:14"),
   (18,"By Wisdom a House Is Built","Through conversation","Prov 24:3-4; Prov 15:22"),
   (19,"No Distractions","Full attention","Prov 4:25; Eccl 4:9"),
   (20,"Both at the Table","Equal partners","Eccl 4:9; Gen 2:24"),
   (21,"Setting the Table","The meeting begins","Eccl 4:9; Prov 24:3-4"),
  ]},
  {"roman":"IV","title":"What to Talk About","subtitle":"The Agenda Set","days":[
   (22,"Where We Stand","The honest numbers","Prov 27:23; Luke 14:28"),
   (23,"The Coming Month","Planning ahead","Prov 21:5; Prov 27:12"),
   (24,"Goals and Dreams","Aiming together","Prov 29:18; Phil 2:2"),
   (25,"Giving and Saving","The priorities","Prov 3:9; Prov 21:20"),
   (26,"Bills and Obligations","Nothing forgotten","Prov 22:3; Rom 13:7"),
   (27,"Wins and Worries","Sharing both","Eccl 4:9-10; 1 Thess 5:11"),
   (28,"What to Talk About","The agenda set","Prov 24:3-4; Prov 15:22"),
  ]},
  {"roman":"V","title":"Keeping It Calm","subtitle":"Peace at the Table","days":[
   (29,"A Gentle Answer","Turning away wrath","Prov 15:1; Jas 1:19"),
   (30,"Quick to Listen","Slow to speak","Jas 1:19; Prov 18:13"),
   (31,"No Blame Games","Grace over accusation","Eph 4:31-32; Col 3:13"),
   (32,"Speaking Truth in Love","Honest and kind","Eph 4:15; Eph 4:25"),
   (33,"When It Gets Tense","Pause and pray","Phil 4:6-7; Prov 15:18"),
   (34,"Unity Over Winning","The shared goal","Phil 2:2-4; Eccl 4:9"),
   (35,"Keeping It Calm","Peace at the table","Prov 15:1; Col 3:19"),
  ]},
  {"roman":"VI","title":"A Household Rhythm","subtitle":"The Meeting That Endures","days":[
   (36,"Make It Regular","A steady rhythm","Eccl 4:9; Prov 21:5"),
   (37,"As for the Lord","Money meetings as service","Col 3:23; Eccl 4:9"),
   (38,"Built Over Time","The habit holds","Gal 6:9; Prov 24:3-4"),
   (39,"A Stronger Household","United and clear","Eccl 4:9-12; Prov 24:3-4"),
   (40,"A Household Rhythm","The meeting that endures","Eccl 4:9; Prov 24:3-4"),
  ]},
 ],
 # ---------------- 80 · Generosity Starts at Home ----------------
 80: [
  {"roman":"I","title":"Generous Kids, Generous Adults","subtitle":"The Home's Fruit","days":[
   (1,"Where Generosity Begins","In the home","Matt 10:8; Deut 6:6-7"),
   (2,"Generous Children Become","Generous adults","Prov 22:6; 2 Cor 9:7"),
   (3,"The Seedbed of Giving","Home as the soil","Deut 6:6-7; Ps 78:4"),
   (4,"Caught at the Table","Generosity modeled","Acts 20:35; 1 Cor 11:1"),
   (5,"A Culture of Open Hands","The family ethos","Prov 11:25; 2 Cor 9:7"),
   (6,"Starting Young","Habits formed early","Prov 22:6; Matt 10:8"),
   (7,"Generous Kids, Generous Adults","The home's fruit","Matt 10:8; Prov 22:6"),
  ]},
  {"roman":"II","title":"Freely Give","subtitle":"The Heart of Generosity","days":[
   (8,"Freely You Received","Freely give","Matt 10:8; 2 Cor 9:15"),
   (9,"All We Have Is a Gift","Received first","1 Cor 4:7; Jas 1:17"),
   (10,"Grace Flows Outward","Given, then giving","2 Cor 8:9; 1 John 4:19"),
   (11,"No Strings Attached","Free generosity","Matt 10:8; Luke 6:35"),
   (12,"Giving as God Gives","Lavishly","John 3:16; Eph 1:7-8"),
   (13,"The Overflow of Grace","Generous because loved","2 Cor 8:1-2; 1 John 4:11"),
   (14,"Freely Give","The heart of generosity","Matt 10:8; 2 Cor 9:7"),
  ]},
  {"roman":"III","title":"Letting Children Give","subtitle":"Young Givers Formed","days":[
   (15,"Let Them Give","Their own gifts","Mark 12:43-44; 2 Cor 8:12"),
   (16,"Small Hands, Real Gifts","God sees the heart","2 Cor 8:12; Mark 12:43"),
   (17,"Their Own Decision","Owning generosity","2 Cor 9:7; Ex 35:5"),
   (18,"Giving What's Theirs","Real sacrifice","2 Sam 24:24; Mark 12:44"),
   (19,"Seeing Where It Goes","Generosity with a face","Prov 19:17; Matt 25:40"),
   (20,"The Joy They Discover","More blessed to give","Acts 20:35; Luke 6:38"),
   (21,"Letting Children Give","Young givers formed","Mark 12:43-44; 2 Cor 9:7"),
  ]},
  {"roman":"IV","title":"Modeling It Ourselves","subtitle":"Generosity Shown","days":[
   (22,"They Watch Us","More caught than taught","1 Cor 11:1; Deut 6:6-7"),
   (23,"Our Open Hands","The first lesson","Acts 20:35; Prov 11:25"),
   (24,"Giving in the Open","Letting them see","Matt 5:16; 2 Cor 9:7"),
   (25,"Cheerful, Not Grudging","The tone they learn","2 Cor 9:7; Deut 15:10"),
   (26,"Generous With Time Too","Not just money","Gal 5:13; Acts 20:35"),
   (27,"Practice What We Preach","Words matching life","Jas 1:22; 1 Cor 11:1"),
   (28,"Modeling It Ourselves","Generosity shown","1 Cor 11:1; Acts 20:35"),
  ]},
  {"roman":"V","title":"Making Giving Joyful","subtitle":"Glad-Hearted Home","days":[
   (29,"God Loves a Cheerful Giver","Joy at the center","2 Cor 9:7; Prov 22:9"),
   (30,"Celebrate the Giving","Make it glad","Acts 20:35; Ps 126:3"),
   (31,"Giving as Adventure","Not obligation","2 Cor 9:7; Luke 6:38"),
   (32,"The Family That Gives Together","Shared joy","2 Cor 9:7; Acts 2:46"),
   (33,"Stories of Impact","Seeing the difference","Prov 19:17; Matt 25:40"),
   (34,"Joy That Multiplies","Generosity is contagious","2 Cor 8:2; 2 Cor 9:11-12"),
   (35,"Making Giving Joyful","Glad-hearted home","2 Cor 9:7; Prov 11:25"),
  ]},
  {"roman":"VI","title":"Open Hands at Home","subtitle":"Where Generosity Starts","days":[
   (36,"A Generous Household","Open hands as habit","Prov 11:25; 1 Tim 6:18"),
   (37,"Generosity Passed On","Generation to generation","Ps 78:4; Prov 13:22"),
   (38,"Rich in Good Deeds","A family marked by giving","1 Tim 6:18; Ps 112:9"),
   (39,"Freely Giving Together","The home's overflow","Matt 10:8; 2 Cor 9:7"),
   (40,"Open Hands at Home","Where generosity starts","Matt 10:8; Prov 11:25"),
  ]},
 ],
}
