# -*- coding: utf-8 -*-
"""Volume 2, Batch 5 (final) — architecture blueprints, Groups 13-14:
Workplace & Marketplace, Signature Short Formats. Completes all 90 non-flagships."""

DEF = ["4-Session", "6-Session", "21-Day", "30-Day", "40-Day"]
T1 = "Tier 1 — Church & Company"

GROUP_DESC = {
    "Workplace & Marketplace":
        "Faith and finances where work happens \u2014 wellness, meaning, integrity, and stewardship for teams, leaders, and the marketplace.",
    "Signature Short Formats":
        "Short, focused, high-energy campaigns \u2014 resets, peace journeys, and giving challenges built to move a church or team fast.",
}

ARCH = [
 # ---------------- WORKPLACE & MARKETPLACE ----------------
 {
  "num": 91, "group": "Workplace & Marketplace",
  "title": "Faith & Finances at Work",
  "tagline": "Faith-Friendly Financial Wellness for Your Team",
  "tier": T1, "audience": "Company Teams \u00b7 Workplace Groups \u00b7 Employee Wellness",
  "core_ref": "3 John 1:2 (NIV)",
  "core_text": "I pray that all may go well with you, even as your soul is getting along well.",
  "marketing": "Financial stress follows people to work \u2014 and quietly costs focus, morale, and peace. This workplace-ready series brings faith-friendly financial wellness to a team, pairing practical money help with timeless principles, so people thrive not just at their desks but in every area money touches.",
  "felt_need": "Carrying money stress into work, where it quietly drains focus and peace.",
  "why_matters": "Scripture wants it to go well with us in every area, as our souls prosper too.",
  "problem": "Financial stress shows up at work, but workplaces rarely offer real help for it.",
  "transformation": "From money stress weighing on the team to genuine, faith-friendly wellness.",
  "formats": DEF,
  "sessions": [
   ("Stress Comes to Work", "How money follows us in"),
   ("Wellness That's Whole", "Finances and the soul together"),
   ("Practical Money Help", "Tools the team can use"),
   ("Principles That Last", "Timeless wisdom at work"),
   ("A Healthier Team", "When money stress lifts"),
   ("Thriving at Work", "Faith-friendly financial wellness"),
  ],
  "scriptures": ["3 John 1:2", "Colossians 3:23-24", "Proverbs 3:9-10", "1 Timothy 6:17-19", "Philippians 4:19"],
 },
 {
  "num": 92, "group": "Workplace & Marketplace",
  "title": "Money, Work, and Meaning",
  "tagline": "Connecting Your Finances to Deeper Purpose",
  "tier": T1, "audience": "Company Teams \u00b7 Working Professionals \u00b7 Workplace Groups",
  "core_ref": "Ecclesiastes 2:24 (NIV)",
  "core_text": "A person can find satisfaction in their toil. This too is from the hand of God.",
  "marketing": "For many professionals, work and money run on autopilot, disconnected from any deeper why. This study reconnects the three \u2014 money, work, and meaning \u2014 helping people find genuine satisfaction in their labor as a gift from God, and see their earning as part of a purpose larger than the next paycheck.",
  "felt_need": "Earning and working on autopilot, disconnected from any deeper purpose.",
  "why_matters": "Scripture says satisfaction in our work is a gift from the hand of God.",
  "problem": "We separate money and meaning, so work becomes a grind with no larger why.",
  "transformation": "From autopilot earning to work and money connected to real purpose.",
  "formats": DEF,
  "sessions": [
   ("Work on Autopilot", "Losing the why"),
   ("Satisfaction as Gift", "Meaning in the toil"),
   ("Why Do I Earn?", "Money in service of purpose"),
   ("Work That Matters", "Reconnecting labor and meaning"),
   ("Commit Your Work", "Offering it to God"),
   ("Money, Work, and Meaning", "Earning with purpose"),
  ],
  "scriptures": ["Ecclesiastes 2:24", "Ecclesiastes 3:12-13", "Colossians 3:23-24", "Ecclesiastes 5:18-19", "Proverbs 16:3"],
 },
 {
  "num": 93, "group": "Workplace & Marketplace",
  "title": "The Generous Workplace",
  "tagline": "Cultivating a Culture of Generosity Across a Team",
  "tier": T1, "audience": "Company Teams \u00b7 Workplace Groups \u00b7 Team Leaders",
  "core_ref": "2 Corinthians 9:11 (NIV)",
  "core_text": "You will be enriched in every way so that you can be generous on every occasion.",
  "marketing": "Generosity isn't only personal \u2014 it can become a culture. This study helps teams cultivate open-handedness together, where people are enriched to be generous on every occasion. It reimagines a workplace not just as a place to earn, but as a community that gives.",
  "felt_need": "Wanting our team to be marked by generosity, not just productivity.",
  "why_matters": "Scripture says we're enriched in every way so we can be generous on every occasion.",
  "problem": "Workplaces optimize for output and rarely cultivate a culture of giving.",
  "transformation": "From a team focused only on earning to a culture of shared generosity.",
  "formats": DEF,
  "sessions": [
   ("Beyond the Personal", "Generosity as culture"),
   ("Enriched to Give", "Why God supplies generosity"),
   ("The Generous Team", "Open hands together"),
   ("Giving on Every Occasion", "Generosity as a habit"),
   ("A Community That Gives", "More than a place to earn"),
   ("The Generous Workplace", "Cultivating the culture"),
  ],
  "scriptures": ["2 Corinthians 9:11", "Acts 4:32-35", "Proverbs 11:25", "2 Corinthians 9:6-8", "Galatians 6:9-10"],
 },
 {
  "num": 94, "group": "Workplace & Marketplace",
  "title": "Integrity in the Marketplace",
  "tagline": "Honest Dealing and Clean Hands in Business",
  "tier": T1, "audience": "Company Teams \u00b7 Business & Sales \u00b7 Marketplace Christians",
  "core_ref": "Proverbs 11:3 (NIV)",
  "core_text": "The integrity of the upright guides them, but the unfaithful are destroyed by their duplicity.",
  "marketing": "The marketplace tests character daily \u2014 with pressure to bend, spin, and cut corners for the deal. This study calls for integrity that guides every transaction, the kind that walks securely because it has nothing to hide, proving that honest dealing and lasting success are not enemies.",
  "felt_need": "Pressure to bend the truth or cut corners to win in business.",
  "why_matters": "Scripture says the integrity of the upright guides them through every dealing.",
  "problem": "Marketplace pressure tempts us to compromise integrity for the deal.",
  "transformation": "From bending under pressure to integrity that guides every transaction.",
  "formats": DEF,
  "sessions": [
   ("The Daily Test", "Where character is pressured"),
   ("Integrity as Guide", "Letting it steer decisions"),
   ("Honest Dealing", "Truth in every transaction"),
   ("The Long View", "Why integrity outlasts shortcuts"),
   ("Nothing to Hide", "Walking securely in business"),
   ("Integrity in the Marketplace", "Clean hands, clear path"),
  ],
  "scriptures": ["Proverbs 11:3", "Proverbs 16:11", "Proverbs 20:23", "Luke 16:10-11", "Proverbs 28:6"],
 },
 {
  "num": 95, "group": "Workplace & Marketplace",
  "title": "Stewardship for Leaders",
  "tagline": "Stewarding Resources, People, and Influence With Wisdom",
  "tier": T1, "audience": "Company Leaders \u00b7 Managers & Executives \u00b7 Ministry Leaders",
  "core_ref": "Luke 12:48 (NIV)",
  "core_text": "From everyone who has been given much, much will be demanded.",
  "marketing": "Leaders are entrusted with more than money \u2014 with people, influence, and decisions that ripple outward. This study equips leaders to steward it all with wisdom, remembering that to whom much is given, much is required, and that the best leaders manage what they hold for the good of those they serve.",
  "felt_need": "Leading with significant resources and influence, and feeling the weight of it.",
  "why_matters": "Scripture says from everyone given much, much will be demanded.",
  "problem": "Leaders can wield resources and influence without stewarding them faithfully.",
  "transformation": "From leading by default to stewarding resources, people, and influence wisely.",
  "formats": DEF,
  "sessions": [
   ("Entrusted With Much", "The leader's larger charge"),
   ("To Whom Much Is Given", "The weight of responsibility"),
   ("Stewarding Resources", "Managing what you hold"),
   ("Stewarding People", "Leading for their good"),
   ("Stewarding Influence", "Using a platform well"),
   ("Stewardship for Leaders", "Faithful with all of it"),
  ],
  "scriptures": ["Luke 12:48", "1 Peter 5:2-3", "Luke 16:10-12", "Proverbs 27:23-24", "1 Corinthians 4:1-2"],
 },
 {
  "num": 96, "group": "Workplace & Marketplace",
  "title": "The Ethics of Money at Work",
  "tagline": "Navigating the Real Financial Tensions of Work",
  "tier": T1, "audience": "Company Teams \u00b7 Working Professionals \u00b7 Workplace Groups",
  "core_ref": "Proverbs 10:9 (NIV)",
  "core_text": "Whoever walks in integrity walks securely, but whoever takes crooked paths will be found out.",
  "marketing": "Professional life is full of money tensions the textbooks skip \u2014 the expense report, the conflict of interest, the quiet pressure to look the other way. This study walks through the real ethical gray areas of work, showing how those who walk in integrity walk securely while crooked paths are eventually found out.",
  "felt_need": "Facing financial gray areas at work with no clear sense of the right call.",
  "why_matters": "Scripture says whoever walks in integrity walks securely; crooked paths get found out.",
  "problem": "Work brings ethical tensions we're rarely equipped to navigate wisely.",
  "transformation": "From fumbling money ethics at work to walking securely in integrity.",
  "formats": DEF,
  "sessions": [
   ("The Gray Areas", "Tensions the textbooks skip"),
   ("Walking Securely", "Why integrity is safe ground"),
   ("The Expense and the Edge", "Everyday ethical tests"),
   ("Conflicts of Interest", "When loyalties collide"),
   ("Found Out", "The cost of crooked paths"),
   ("Ethics That Hold", "Integrity under pressure"),
  ],
  "scriptures": ["Proverbs 10:9", "Daniel 6:4", "1 Peter 3:16", "Proverbs 11:1", "Colossians 3:23-25"],
 },
 {
  "num": 97, "group": "Workplace & Marketplace",
  "title": "Wise Money for Working Professionals",
  "tagline": "Practical Financial Wisdom for a Demanding Career",
  "tier": T1, "audience": "Company Teams \u00b7 Working Professionals \u00b7 High Earners",
  "core_ref": "Ephesians 5:15-16 (NIV)",
  "core_text": "Be very careful how you live... making the most of every opportunity.",
  "marketing": "A demanding career brings real money complexity \u2014 higher income, less time, lifestyle creep, and decisions that won't wait. This study offers practical financial wisdom tailored to that reality, helping busy professionals make the most of every opportunity and steward a fuller income with foresight rather than drift.",
  "felt_need": "A demanding career, a fuller income, and no time to manage it wisely.",
  "why_matters": "Scripture says to live carefully, making the most of every opportunity.",
  "problem": "Busy professionals let income and lifestyle drift for lack of time to steer them.",
  "transformation": "From drifting on a busy income to stewarding it with foresight and wisdom.",
  "formats": DEF,
  "sessions": [
   ("The Professional's Squeeze", "Income up, time down"),
   ("Making the Most of It", "Redeeming opportunity"),
   ("Taming Lifestyle Creep", "When more earns less peace"),
   ("Decisions That Won't Wait", "Wisdom on the clock"),
   ("Foresight Over Drift", "Steering a fuller income"),
   ("Wise and Working", "Stewarding a demanding career"),
  ],
  "scriptures": ["Ephesians 5:15-16", "Proverbs 21:5", "Proverbs 24:3-4", "Luke 14:28", "Proverbs 13:11"],
 },
 # ---------------- SIGNATURE SHORT FORMATS ----------------
 {
  "num": 98, "group": "Signature Short Formats",
  "title": "The Money Reset",
  "tagline": "A Focused 21-Day Reset for Your Financial Life",
  "tier": T1, "audience": "All Church \u00b7 Workplace Teams \u00b7 21-Day Challenge",
  "core_ref": "2 Corinthians 5:17 (NIV)",
  "core_text": "If anyone is in Christ, the new creation has come: the old has gone, the new is here!",
  "marketing": "Sometimes finances need less of a tune-up and more of a reset. This focused 21-day journey clears the clutter and rebuilds money life on God's design from the ground up \u2014 a short, intense, fresh-start sprint for anyone ready to declare the old gone and the new here.",
  "felt_need": "My money life feels cluttered and off-track, and I want a clean fresh start.",
  "why_matters": "In Christ the old is gone and the new has come \u2014 a reset is always possible.",
  "problem": "Small fixes don't cut it when the whole financial picture needs a reset.",
  "transformation": "From cluttered and off-track to a fresh financial start on God's design.",
  "formats": ["6-Session", "21-Day"],
  "sessions": [
   ("Time to Reset", "When a tune-up isn't enough"),
   ("The Old Is Gone", "Clearing the clutter"),
   ("Back to God's Design", "Rebuilding the foundation"),
   ("The 21-Day Sprint", "Focused, daily reset steps"),
   ("New Habits, New Start", "Setting the new normal"),
   ("The Money Reset", "A financial life made new"),
  ],
  "scriptures": ["2 Corinthians 5:17", "Lamentations 3:22-23", "Isaiah 43:18-19", "Philippians 3:13-14", "Proverbs 21:5"],
 },
 {
  "num": 99, "group": "Signature Short Formats",
  "title": "21 Days to Financial Peace",
  "tagline": "Three Weeks of Daily Steps to Settled Peace",
  "tier": T1, "audience": "All Church \u00b7 Workplace Teams \u00b7 21-Day Challenge",
  "core_ref": "Isaiah 26:3 (NIV)",
  "core_text": "You will keep in perfect peace those whose minds are steadfast, because they trust in you.",
  "marketing": "Peace with money rarely arrives all at once \u2014 it's built day by day. This 21-day journey walks people from money anxiety to a settled, grounded peace through three weeks of small daily steps, anchored in the promise that God keeps in perfect peace those whose minds stay fixed on Him.",
  "felt_need": "Money anxiety I want to trade for a settled, grounded peace \u2014 step by step.",
  "why_matters": "God keeps in perfect peace those whose minds are steadfast and trusting.",
  "problem": "Money peace feels out of reach when anxiety is addressed only all at once.",
  "transformation": "From daily money anxiety to a settled peace built one day at a time.",
  "formats": ["6-Session", "21-Day"],
  "sessions": [
   ("Peace, Day by Day", "Built, not switched on"),
   ("The Steadfast Mind", "Where perfect peace rests"),
   ("Week One: Surrender", "Handing money fears to God"),
   ("Week Two: Trust", "Leaning on His provision"),
   ("Week Three: Rest", "Settling into peace"),
   ("21 Days to Peace", "A settled, grounded heart"),
  ],
  "scriptures": ["Isaiah 26:3", "Philippians 4:6-7", "Matthew 6:34", "Psalm 4:8", "John 14:27"],
 },
 {
  "num": 100, "group": "Signature Short Formats",
  "title": "The Generosity Challenge",
  "tagline": "A High-Energy Challenge Toward Joyful, Contagious Giving",
  "tier": T1, "audience": "All Church \u00b7 Whole Congregation \u00b7 Giving Challenge",
  "core_ref": "1 Chronicles 29:9 (NIV)",
  "core_text": "The people rejoiced... for they had given freely and wholeheartedly to the Lord.",
  "marketing": "Generosity is contagious \u2014 and sometimes a church just needs a spark. This high-energy short campaign challenges a congregation to give freely and wholeheartedly together, turning ordinary people into joyful, contagious givers and igniting a wave of generosity the whole community can feel.",
  "felt_need": "Wanting to ignite real, joyful generosity across the whole congregation.",
  "why_matters": "Scripture describes a people who rejoiced to give freely and wholeheartedly to God.",
  "problem": "Generosity can stay quiet and individual when it's meant to be joyful and shared.",
  "transformation": "From scattered, private giving to a contagious wave of joyful generosity.",
  "formats": ["21-Day", "30-Day"],
  "sessions": [
   ("The Spark", "Why generosity needs igniting"),
   ("Freely and Wholeheartedly", "A people who rejoiced to give"),
   ("The Challenge Begins", "Stepping out together"),
   ("Contagious Giving", "How generosity spreads"),
   ("The Joy of the Wave", "Celebrating together"),
   ("A Generous People", "Generosity that lasts"),
  ],
  "scriptures": ["1 Chronicles 29:9", "2 Corinthians 9:6-7", "Malachi 3:10", "Luke 6:38", "Acts 20:35"],
 },
]
