# -*- coding: utf-8 -*-
"""40-Day devotional maps — Batch 9 (nums 63-69): Work, Income & Calling.
6 movements aligned to the 6 sessions, 40 days in a 7-7-7-7-7-5 arc."""

MAPS = {
 # ---------------- 63 · Working as Worship ----------------
 63: [
  {"roman":"I","title":"The Sacred-Secular Divide","subtitle":"A Myth Dispelled","days":[
   (1,"The False Divide","Sacred work vs secular","Col 3:23; 1 Cor 10:31"),
   (2,"All of Life Is His","No secular zone","1 Cor 10:31; Ps 24:1"),
   (3,"Work Before the Fall","Good from the start","Gen 2:15; Gen 1:28"),
   (4,"The Dignity of Labor","Made to work","Gen 2:15; Ps 8:6"),
   (5,"Monday Matters to God","Not just Sunday","Col 3:23; Rom 12:1"),
   (6,"Tearing Down the Wall","One integrated life","1 Cor 10:31; Col 3:17"),
   (7,"The Sacred-Secular Divide","A myth dispelled","Col 3:23; 1 Cor 10:31"),
  ]},
  {"roman":"II","title":"As Working for the Lord","subtitle":"An Audience of One","days":[
   (8,"Whatever You Do","Work at it heartily","Col 3:23; Eccl 9:10"),
   (9,"As for the Lord","Not for human masters","Col 3:23; Eph 6:7"),
   (10,"The Lord You Serve","Christ is your boss","Col 3:24; Eph 6:5-8"),
   (11,"With All Your Heart","Wholehearted labor","Col 3:23; Deut 6:5"),
   (12,"Serving Wholeheartedly","As to the Lord","Eph 6:7; Col 3:23"),
   (13,"An Audience of One","Working before Him","Col 3:23-24; Gal 1:10"),
   (14,"Working for the Lord","The reframe complete","Col 3:23; Eph 6:7"),
  ]},
  {"roman":"III","title":"Worship at the Desk","subtitle":"Labor Becomes Liturgy","days":[
   (15,"Worship in the Work","Daily labor as praise","Rom 12:1; Col 3:23"),
   (16,"To the Glory of God","Even ordinary tasks","1 Cor 10:31; Col 3:17"),
   (17,"Offering Your Hands","The body as worship","Rom 12:1; 1 Cor 6:20"),
   (18,"The Sacred in the Mundane","Holy routine","Col 3:17; 1 Cor 10:31"),
   (19,"Doing It Unto Him","Every task an offering","Col 3:23; Eph 6:7"),
   (20,"Prayer at Work","Inviting Him in","1 Thess 5:17; Col 4:2"),
   (21,"Worship at the Desk","Labor becomes liturgy","Col 3:23; Rom 12:1"),
  ]},
  {"roman":"IV","title":"The Paycheck as Provision","subtitle":"God's Gift Through Labor","days":[
   (22,"The Fruit of Labor","Earned by work","Ps 128:2; Prov 14:23"),
   (23,"God Behind the Paycheck","He gives the ability","Deut 8:17-18; Ps 128:2"),
   (24,"Not by My Power","Remember the Giver","Deut 8:17-18; Jas 1:17"),
   (25,"Daily Bread Through Work","The ordinary means","2 Thess 3:10; Ps 128:2"),
   (26,"Grateful for Provision","Thanks for the wage","1 Thess 5:18; Ps 128:2"),
   (27,"A Channel of His Care","Work as conduit","Deut 8:18; Phil 4:19"),
   (28,"The Paycheck as Provision","God's gift through labor","Ps 128:2; Deut 8:18"),
  ]},
  {"roman":"V","title":"Excellence as Offering","subtitle":"Good Work Given to God","days":[
   (29,"Do It Well","Excellence honors God","Col 3:23; Eccl 9:10"),
   (30,"Skilled Hands Before Kings","Diligence noticed","Prov 22:29; Dan 6:3"),
   (31,"Whatever Your Hand Finds","Do it with might","Eccl 9:10; Col 3:23"),
   (32,"Quality as Worship","Caring about the craft","1 Cor 10:31; Col 3:17"),
   (33,"Not Slacking","Diligent, not lazy","Rom 12:11; Prov 18:9"),
   (34,"Your Labor Is Not in Vain","It matters to God","1 Cor 15:58; Gal 6:9"),
   (35,"Excellence as Offering","Good work given to God","Col 3:23; 1 Cor 15:58"),
  ]},
  {"roman":"VI","title":"Working as Worship","subtitle":"Labor Offered to God","days":[
   (36,"Every Task Sacred","The integrated life","Col 3:23; 1 Cor 10:31"),
   (37,"Steady and Immovable","Always abounding","1 Cor 15:58; Col 3:23"),
   (38,"The Joy of Good Work","Satisfaction in labor","Eccl 2:24; Eccl 3:13"),
   (39,"For His Glory","The aim of it all","1 Cor 10:31; Col 3:17"),
   (40,"Working as Worship","Labor offered to God","Col 3:23-24; 1 Cor 10:31"),
  ]},
 ],
 # ---------------- 64 · Faith on the Job ----------------
 64: [
  {"roman":"I","title":"Your Daily Mission Field","subtitle":"Where God Has Placed You","days":[
   (1,"The Mission Field at Work","Where you spend your days","Matt 5:16; 1 Pet 2:12"),
   (2,"Placed on Purpose","God put you here","Acts 17:26; 1 Cor 7:17"),
   (3,"People Who Are Watching","Coworkers observe","1 Pet 2:12; Matt 5:16"),
   (4,"Salt and Light","Your daily influence","Matt 5:13-14; Phil 2:15"),
   (5,"Not Hiding the Faith","Visible, not loud","Matt 5:15; 1 Pet 3:15"),
   (6,"Ambassadors at Work","Representing Christ","2 Cor 5:20; Col 4:5"),
   (7,"Your Daily Mission Field","Right where you are","Matt 5:16; 1 Cor 7:17"),
  ]},
  {"roman":"II","title":"Let Your Light Shine","subtitle":"That They May See","days":[
   (8,"Let Your Light Shine","Before others","Matt 5:16; Phil 2:15"),
   (9,"Good Deeds Seen","They point to God","Matt 5:16; 1 Pet 2:12"),
   (10,"Glory to the Father","The aim of the light","Matt 5:16; 1 Cor 10:31"),
   (11,"A City on a Hill","Not hidden away","Matt 5:14; Phil 2:15"),
   (12,"Shining Without Words","Conduct that speaks","1 Pet 3:1-2; Matt 5:16"),
   (13,"Lights in a Dark World","Standing out","Phil 2:15; Eph 5:8"),
   (14,"Let Your Light Shine","That they may see","Matt 5:16; 1 Pet 2:12"),
  ]},
  {"roman":"III","title":"Integrity Under Pressure","subtitle":"Standing Firm","days":[
   (15,"Pressure to Compromise","The daily test","Dan 6:4; Prov 10:9"),
   (16,"Blameless and Above Reproach","Nothing to hide","Dan 6:4; Titus 2:7-8"),
   (17,"Integrity Holds","When tested","Prov 10:9; Job 27:5-6"),
   (18,"The Cost of Honesty","Worth paying","Prov 19:1; Ps 15:4"),
   (19,"Walking Securely","The blameless path","Prov 10:9; Prov 28:18"),
   (20,"Refusing to Bend","Faithful under fire","Dan 3:17-18; Dan 6:10"),
   (21,"Integrity Under Pressure","Standing firm","Dan 6:4; Prov 10:9"),
  ]},
  {"roman":"IV","title":"Words and Conduct","subtitle":"Adorning the Gospel","days":[
   (22,"Conversation With Grace","Seasoned with salt","Col 4:6; Eph 4:29"),
   (23,"Wise Toward Outsiders","Making the most of it","Col 4:5; Eph 5:15-16"),
   (24,"Adorn the Teaching","Make the gospel attractive","Titus 2:9-10; Titus 2:7"),
   (25,"Trustworthy in All","Fully reliable","Titus 2:10; Luke 16:10"),
   (26,"Words That Build Up","Not tearing down","Eph 4:29; Prov 16:24"),
   (27,"Practice What You Preach","Conduct matching words","1 Pet 2:12; Jas 1:22"),
   (28,"Words and Conduct","Adorning the gospel","Titus 2:9-10; Col 4:6"),
  ]},
  {"roman":"V","title":"The Daniel Standard","subtitle":"Excellent and Faithful","days":[
   (29,"An Excellent Spirit","Daniel stood out","Dan 6:3; Dan 5:12"),
   (30,"No Corruption Found","Trustworthy through and through","Dan 6:4; Prov 11:3"),
   (31,"Faithful in His Work","Neither corrupt nor negligent","Dan 6:4; Col 3:23"),
   (32,"Praying Anyway","Faithful when it cost him","Dan 6:10; Acts 5:29"),
   (33,"God Honored His Stand","Delivered and promoted","Dan 6:22-23; Dan 6:28"),
   (34,"Excellence and Faith Together","The Daniel pattern","Dan 6:3-4; Col 3:23"),
   (35,"The Daniel Standard","Excellent and faithful","Dan 6:3-4; Prov 22:29"),
  ]},
  {"roman":"VI","title":"Faith on the Job","subtitle":"Living It Out","days":[
   (36,"Faith That Works","Lived, not just believed","Jas 2:17; Matt 5:16"),
   (37,"Consistent and Quiet","Steady witness","1 Pet 2:12; Col 4:5-6"),
   (38,"Ready to Give an Answer","With gentleness and respect","1 Pet 3:15; Col 4:6"),
   (39,"Light That Lasts","A long obedience","Matt 5:16; Gal 6:9"),
   (40,"Faith on the Job","Living it out","Matt 5:16; 1 Pet 2:12"),
  ]},
 ],
 # ---------------- 65 · Your Work, God's Provision ----------------
 65: [
  {"roman":"I","title":"The Fruit of Your Labor","subtitle":"Eating From Your Work","days":[
   (1,"You Will Eat the Fruit","Of your labor","Ps 128:2; Prov 14:23"),
   (2,"Blessings and Prosperity","The worker's portion","Ps 128:2; Ps 128:1"),
   (3,"Hard Work Profits","All labor brings gain","Prov 14:23; Prov 12:11"),
   (4,"By the Sweat of Your Brow","Work since Eden's gate","Gen 3:19; Gen 2:15"),
   (5,"The Worker Is Worthy","Of his wages","Luke 10:7; 1 Tim 5:18"),
   (6,"Provision Through Effort","God's ordinary way","2 Thess 3:10; Ps 128:2"),
   (7,"The Fruit of Your Labor","Eating from your work","Ps 128:2; Prov 14:23"),
  ]},
  {"roman":"II","title":"Dignity in Work","subtitle":"Made to Labor","days":[
   (8,"Work Is a Gift","Not a curse","Gen 2:15; Eccl 5:18-19"),
   (9,"Made to Work","From the beginning","Gen 2:15; Gen 1:28"),
   (10,"The Honor of Labor","Every honest job","Prov 14:23; 1 Thess 4:11-12"),
   (11,"Working With Your Hands","A quiet dignity","1 Thess 4:11; Eph 4:28"),
   (12,"No Shame in Honest Work","Whatever the task","Eccl 9:10; Col 3:23"),
   (13,"Provide for Your Own","A worker's duty","1 Tim 5:8; 2 Thess 3:12"),
   (14,"Dignity in Work","Made to labor","Gen 2:15; Prov 14:23"),
  ]},
  {"roman":"III","title":"Not the Source, the Channel","subtitle":"Work Is the Means, Not the Maker","days":[
   (15,"Work Is the Channel","Not the source","Deut 8:17-18; Ps 127:1-2"),
   (16,"My Power Got Me This?","The subtle lie","Deut 8:17; Hos 2:8"),
   (17,"He Gives the Ability","To produce wealth","Deut 8:18; Jas 1:17"),
   (18,"Unless the Lord Builds","Labor is in vain","Ps 127:1-2; 1 Cor 3:7"),
   (19,"The Hand Behind the Hand","God's quiet provision","Deut 8:18; Phil 4:19"),
   (20,"Trust Beyond the Job","The Provider, not the paycheck","Matt 6:33; Ps 62:10"),
   (21,"Not the Source, the Channel","Work as the means","Deut 8:18; Ps 127:1-2"),
  ]},
  {"roman":"IV","title":"Remember Who Gives","subtitle":"Guarding Against Forgetting","days":[
   (22,"Remember the Lord","Lest you forget","Deut 8:18; Deut 8:11"),
   (23,"The Danger of Plenty","Forgetting in abundance","Deut 8:12-14; Prov 30:8-9"),
   (24,"Every Good Gift","Comes from above","Jas 1:17; 1 Chr 29:14"),
   (25,"What Do You Have","That you didn't receive?","1 Cor 4:7; John 3:27"),
   (26,"Acknowledge Him","In all your ways","Prov 3:6; Deut 8:18"),
   (27,"From Him and Through Him","All things","Rom 11:36; 1 Chr 29:11-12"),
   (28,"Remember Who Gives","Guarding against forgetting","Deut 8:18; Jas 1:17"),
  ]},
  {"roman":"V","title":"Gratitude for Daily Work","subtitle":"Thanks for the Labor Itself","days":[
   (29,"Thankful for Work","The gift of labor","Eccl 5:18-19; 1 Thess 5:18"),
   (30,"Satisfaction in Toil","A gift from God","Eccl 5:19; Eccl 2:24"),
   (31,"Find Joy in Your Work","Accept your lot","Eccl 5:18-20; Eccl 3:22"),
   (32,"Gratitude for the Wage","Provision received","1 Thess 5:18; Ps 128:2"),
   (33,"Content in Calling","Wherever assigned","1 Cor 7:17; Phil 4:11"),
   (34,"Working With Gladness","Joy in the doing","Eccl 9:10; Ps 90:17"),
   (35,"Gratitude for Daily Work","Thanks for the labor itself","Eccl 5:18-19; 1 Thess 5:18"),
  ]},
  {"roman":"VI","title":"Your Work, His Provision","subtitle":"Labor and the Provider Together","days":[
   (36,"Diligent and Dependent","Both at once","Prov 10:4; Deut 8:18"),
   (37,"Establish the Work of Our Hands","The prayer","Ps 90:17; Ps 127:1"),
   (38,"He Provides Through Labor","The wise balance","Ps 128:2; Phil 4:19"),
   (39,"Grateful and Trusting","Work held rightly","1 Thess 5:18; Matt 6:33"),
   (40,"Your Work, His Provision","Labor and the Provider together","Ps 128:2; Deut 8:18"),
  ]},
 ],
 # ---------------- 66 · The Side Hustle and the Soul ----------------
 66: [
  {"roman":"I","title":"The Promise of More","subtitle":"What the Hustle Offers","days":[
   (1,"The Promise of More","What extra work offers","Eccl 4:6; Eccl 4:8"),
   (2,"The Lure of Extra Income","More money, more dreams","Eccl 5:10; Prov 13:11"),
   (3,"Always One More Thing","The endless add-on","Eccl 4:8; Eccl 2:22-23"),
   (4,"Good Gift or Greedy Grab?","Examining the why","Luke 12:15; 1 Tim 6:9"),
   (5,"Counting the Real Cost","More than time / money","Mark 8:36; Eccl 4:6"),
   (6,"Whose Kingdom Am I Building?","The honest question","Matt 6:33; Luke 12:15"),
   (7,"The Promise of More","Weighing what it offers","Eccl 4:6; Mark 8:36"),
  ]},
  {"roman":"II","title":"Two Handfuls and Toil","subtitle":"Better One Handful With Rest","days":[
   (8,"Better One Handful","With tranquility","Eccl 4:6; Prov 15:16-17"),
   (9,"Than Two With Toil","Chasing the wind","Eccl 4:6; Eccl 4:4"),
   (10,"Toiling for Whom?","No one to enjoy it","Eccl 4:8; Eccl 2:18-19"),
   (11,"Wealth Without Rest","A meaningless gain","Eccl 4:8; Eccl 5:12"),
   (12,"The Sweet Sleep of the Laborer","Versus the rich man's worry","Eccl 5:12; Ps 127:2"),
   (13,"Enough With Peace","Better than more with stress","Prov 15:16; 1 Tim 6:6"),
   (14,"Two Handfuls and Toil","Better one with rest","Eccl 4:6; Prov 15:16-17"),
  ]},
  {"roman":"III","title":"What It's Quietly Taking","subtitle":"The Hidden Toll","days":[
   (15,"The Hidden Cost","What hustle quietly takes","Mark 8:36; Eccl 4:6"),
   (16,"Time With Family","Slipping away","Eph 5:15-16; Ps 90:12"),
   (17,"Rest and Health","Quietly eroded","Eccl 5:12; Mark 6:31"),
   (18,"The Soul Crowded Out","No room to breathe","Mark 8:36; Luke 10:41-42"),
   (19,"Margin for God","Squeezed thin","Luke 10:41-42; Ps 46:10"),
   (20,"What Profit Is It?","To gain and lose your soul","Mark 8:36-37; Luke 9:25"),
   (21,"What It's Quietly Taking","The hidden toll","Mark 8:36; Eccl 4:6"),
  ]},
  {"roman":"IV","title":"Guarding the Soul","subtitle":"Protecting What Matters Most","days":[
   (22,"Watch Over Your Soul","Guard the heart","Prov 4:23; Mark 8:36"),
   (23,"Be on Guard Against Greed","The quiet motive","Luke 12:15; Col 3:5"),
   (24,"Set Limits","Boundaries that protect","Prov 25:28; Eccl 4:6"),
   (25,"Seek First the Kingdom","Keep the priority","Matt 6:33; Luke 12:31"),
   (26,"Don't Wear Yourself Out","For riches","Prov 23:4; Eccl 4:8"),
   (27,"Keep the Heart Free","From the love of money","Heb 13:5; 1 Tim 6:10"),
   (28,"Guarding the Soul","Protecting what matters most","Prov 4:23; Mark 8:36"),
  ]},
  {"roman":"V","title":"Rest as Resistance","subtitle":"The Defiant Sabbath","days":[
   (29,"Come and Rest","The invitation","Matt 11:28; Mark 6:31"),
   (30,"Rest as Trust","Stopping says God provides","Ex 20:8-10; Ps 127:2"),
   (31,"He Gives to His Beloved Sleep","Provision while we rest","Ps 127:2; Ps 3:5"),
   (32,"The Sabbath Principle","Built-in stopping","Ex 20:8-11; Mark 2:27"),
   (33,"Be Still","And know He is God","Ps 46:10; Ex 14:14"),
   (34,"Rest Restores the Soul","Green pastures","Ps 23:2-3; Matt 11:29"),
   (35,"Rest as Resistance","The defiant sabbath","Matt 11:28-30; Ps 127:2"),
  ]},
  {"roman":"VI","title":"Hustle in Its Place","subtitle":"Work Without Losing the Soul","days":[
   (36,"Work, Rightly Ordered","In its proper place","Eccl 4:6; Matt 6:33"),
   (37,"Diligent, Not Driven","Free from compulsion","Prov 10:4; Heb 13:5"),
   (38,"Enough Is Enough","Knowing when to stop","1 Tim 6:6-8; Eccl 4:6"),
   (39,"Soul Intact","The real win","Mark 8:36; Prov 4:23"),
   (40,"Hustle in Its Place","Work without losing the soul","Eccl 4:6; Mark 8:36"),
  ]},
 ],
 # ---------------- 67 · Earning With Integrity ----------------
 67: [
  {"roman":"I","title":"How We Earn Matters","subtitle":"The Means, Not Just the Amount","days":[
   (1,"How, Not Just How Much","The means matter","Prov 11:1; Prov 16:8"),
   (2,"Honest Gain","Better than much wrong","Prov 16:8; Prov 15:16"),
   (3,"The Lord Detests Dishonesty","A weighty truth","Prov 11:1; Prov 20:23"),
   (4,"Wealth With a Clear Conscience","Worth more","Prov 19:1; Ps 15:2"),
   (5,"Ill-Gotten Gain","Profits nothing lasting","Prov 10:2; Prov 13:11"),
   (6,"Earning God's Way","Righteousness over riches","Prov 16:8; Matt 6:33"),
   (7,"How We Earn Matters","The means, not just the amount","Prov 11:1; Prov 16:8"),
  ]},
  {"roman":"II","title":"Honest Scales","subtitle":"Accurate Weights Delight Him","days":[
   (8,"Honest Scales","The Lord's delight","Prov 11:1; Prov 16:11"),
   (9,"Accurate Weights","His concern for fairness","Prov 16:11; Lev 19:35-36"),
   (10,"No Differing Weights","Detestable to Him","Prov 20:10; Prov 20:23"),
   (11,"Just Balances","Required by God","Lev 19:36; Deut 25:13-15"),
   (12,"Fair in Every Deal","Honesty in trade","Prov 11:1; Mic 6:11"),
   (13,"God Cares About Commerce","Even the scales","Prov 16:11; Amos 8:5-6"),
   (14,"Honest Scales","Accurate weights delight Him","Prov 11:1; Prov 16:11"),
  ]},
  {"roman":"III","title":"The Small Compromises","subtitle":"Where Integrity Erodes","days":[
   (15,"The Little Cheats","Small compromises add up","Luke 16:10; Song 2:15"),
   (16,"Faithful in Little","Or unfaithful in little","Luke 16:10; Luke 16:11"),
   (17,"The Padded Expense","Cutting the corner","Prov 11:1; Prov 10:9"),
   (18,"The Slack Hour","Stealing time","Eph 6:5-7; Col 3:22-23"),
   (19,"Half-Truths in the Sale","Honesty slipping","Prov 12:22; Eph 4:25"),
   (20,"Integrity in the Unseen","When no one's looking","Prov 10:9; Heb 4:13"),
   (21,"The Small Compromises","Where integrity erodes","Luke 16:10; Prov 11:1"),
  ]},
  {"roman":"IV","title":"Clean Hands at Work","subtitle":"Walking Securely","days":[
   (22,"Clean Hands, Pure Heart","Who may stand","Ps 24:3-4; Ps 15:1-2"),
   (23,"Walking in Integrity","Securely, not anxiously","Prov 10:9; Prov 28:18"),
   (24,"Above Reproach","Nothing to hide","Titus 2:7-8; 1 Tim 3:7"),
   (25,"Doing What Is Right","In God's eyes","Prov 21:3; Mic 6:8"),
   (26,"Truthful in Speech","No deceit on the lips","Ps 15:2-3; Eph 4:25"),
   (27,"The Blameless Path","A clear way forward","Prov 11:3; Prov 13:6"),
   (28,"Clean Hands at Work","Walking securely","Ps 24:3-4; Prov 10:9"),
  ]},
  {"roman":"V","title":"Trustworthy With Money","subtitle":"Faithful With True Riches","days":[
   (29,"Trustworthy in Little","Then trusted with much","Luke 16:10; Matt 25:21"),
   (30,"Worldly Wealth a Test","Of faithfulness","Luke 16:11; Luke 16:12"),
   (31,"Required of Stewards","To be found faithful","1 Cor 4:2; Luke 12:42"),
   (32,"Handling Others' Money Well","A sacred trust","Luke 16:12; Rom 13:7"),
   (33,"Repaying What's Owed","The righteous way","Ps 37:21; Rom 13:8"),
   (34,"A Good Reputation","Built on trust","Prov 22:1; Eccl 7:1"),
   (35,"Trustworthy With Money","Faithful with true riches","Luke 16:10-11; 1 Cor 4:2"),
  ]},
  {"roman":"VI","title":"Earning With Integrity","subtitle":"A Life Above Reproach","days":[
   (36,"Integrity as a Way of Life","Not a one-time choice","Prov 11:3; Prov 10:9"),
   (37,"Honest in All Things","Consistent and clean","2 Cor 8:21; Heb 13:18"),
   (38,"The Long Game of Trust","Reputation built slowly","Prov 22:1; Luke 16:10"),
   (39,"Blessed, Not Just Rich","God's favor on integrity","Prov 10:22; Ps 112:1-3"),
   (40,"Earning With Integrity","A life above reproach","Prov 11:1; Prov 10:9"),
  ]},
 ],
 # ---------------- 68 · Called to Your Career ----------------
 68: [
  {"roman":"I","title":"Job or Calling?","subtitle":"More Than a Paycheck","days":[
   (1,"Just a Job?","Or something more","Eph 2:10; Col 3:23-24"),
   (2,"More Than a Paycheck","Purpose in the work","Col 3:23-24; Eccl 9:10"),
   (3,"The Restless Question","Is this all there is?","Eccl 1:3; Eccl 2:24"),
   (4,"Work With Meaning","Beyond the wage","Eph 2:10; Col 3:23"),
   (5,"Calling in the Ordinary","Not just for pastors","1 Cor 7:17; 1 Cor 10:31"),
   (6,"Seeing the Bigger Story","Your part in it","Eph 2:10; Phil 2:13"),
   (7,"Job or Calling?","More than a paycheck","Eph 2:10; Col 3:23-24"),
  ]},
  {"roman":"II","title":"God's Handiwork","subtitle":"Created for Good Works","days":[
   (8,"We Are His Handiwork","Crafted by God","Eph 2:10; Ps 139:14"),
   (9,"Created in Christ Jesus","A new creation working","Eph 2:10; 2 Cor 5:17"),
   (10,"Designed With Purpose","Made for a reason","Eph 2:10; Ps 139:13-16"),
   (11,"Your Gifts Are Given","To be used","Rom 12:6-8; 1 Pet 4:10"),
   (12,"Fearfully Made to Contribute","Each one needed","Ps 139:14; 1 Cor 12:18"),
   (13,"His Workmanship at Work","Living the design","Eph 2:10; Phil 1:6"),
   (14,"God's Handiwork","Created for good works","Eph 2:10; 1 Pet 4:10"),
  ]},
  {"roman":"III","title":"Works Prepared in Advance","subtitle":"The Path Already Laid","days":[
   (15,"Prepared in Advance","Works waiting for you","Eph 2:10; Ps 139:16"),
   (16,"For Us to Walk In","The path laid out","Eph 2:10; Prov 16:9"),
   (17,"Ordained Days","Written before one came to be","Ps 139:16; Jer 1:5"),
   (18,"He Works in You","To will and to act","Phil 2:13; Heb 13:21"),
   (19,"Good Works to Do","Right where you are","Eph 2:10; Gal 6:10"),
   (20,"Following the Prepared Path","Step by step","Prov 16:9; Eph 2:10"),
   (21,"Works Prepared in Advance","The path already laid","Eph 2:10; Ps 139:16"),
  ]},
  {"roman":"IV","title":"Where You Are","subtitle":"Faithful in Your Place","days":[
   (22,"Bloom Where Planted","Your current assignment","1 Cor 7:17; 1 Cor 7:20"),
   (23,"The Place God Assigned","Content and faithful","1 Cor 7:17; Acts 17:26"),
   (24,"Faithful Where You Stand","Today's calling","Luke 16:10; Col 3:23"),
   (25,"Not Despising Small Beginnings","Every season counts","Zech 4:10; Luke 16:10"),
   (26,"Serving Here and Now","Present, not waiting","Eccl 9:10; Gal 6:9"),
   (27,"God Uses This Place","Nothing wasted","Rom 8:28; Gen 50:20"),
   (28,"Where You Are","Faithful in your place","1 Cor 7:17; Col 3:23"),
  ]},
  {"roman":"V","title":"Meaning in the Mundane","subtitle":"Sacred in the Routine","days":[
   (29,"The Holy Ordinary","Meaning in routine","Col 3:17; 1 Cor 10:31"),
   (30,"Whatever You Do","Do it all for God","1 Cor 10:31; Col 3:23"),
   (31,"Small Tasks, Sacred Work","No job too lowly","Eccl 9:10; Col 3:23"),
   (32,"Faithful in the Repetitive","Day after day","Lam 3:22-23; Gal 6:9"),
   (33,"God in the Details","Present in the daily","Col 3:17; Zech 4:10"),
   (34,"Purpose in the Plain","Eternal weight in the ordinary","2 Cor 4:17-18; 1 Cor 15:58"),
   (35,"Meaning in the Mundane","Sacred in the routine","Col 3:17; 1 Cor 10:31"),
  ]},
  {"roman":"VI","title":"Called to Your Career","subtitle":"Living Your Design","days":[
   (36,"A Sense of Calling","Purpose in the work","Eph 2:10; 1 Cor 7:17"),
   (37,"Serving God Through Work","An act of worship","Col 3:23-24; Rom 12:1"),
   (38,"Your Labor Matters","To God and others","1 Cor 15:58; Gal 6:9-10"),
   (39,"Fulfilling the Design","Walking in good works","Eph 2:10; Phil 1:6"),
   (40,"Called to Your Career","Living your design","Eph 2:10; Col 3:23-24"),
  ]},
 ],
 # ---------------- 69 · The Diligent Hand ----------------
 69: [
  {"roman":"I","title":"Two Kinds of Hands","subtitle":"Diligent or Slack","days":[
   (1,"Lazy or Diligent","Two kinds of hands","Prov 10:4; Prov 12:24"),
   (2,"Slack Hands Bring Poverty","The cost of laziness","Prov 10:4; Prov 6:10-11"),
   (3,"Diligent Hands Bring Wealth","The fruit of effort","Prov 10:4; Prov 13:4"),
   (4,"The Sluggard's Excuses","A lion in the road","Prov 22:13; Prov 26:13"),
   (5,"Cravings Without Work","The lazy go hungry","Prov 13:4; Prov 21:25"),
   (6,"Which Hand Is Yours?","An honest look","Prov 10:4; Prov 13:4"),
   (7,"Two Kinds of Hands","Diligent or slack","Prov 10:4; Prov 12:24"),
  ]},
  {"roman":"II","title":"The Cost of Neglect","subtitle":"Where Laziness Leads","days":[
   (8,"The Field of the Sluggard","Overgrown and broken","Prov 24:30-31; Prov 24:34"),
   (9,"A Little Sleep","Poverty creeps in","Prov 24:33-34; Prov 6:10-11"),
   (10,"Chasing Fantasies","Instead of working","Prov 28:19; Prov 12:11"),
   (11,"The Door on Its Hinges","The sluggard turns in bed","Prov 26:14; Prov 19:15"),
   (12,"Hunger as Teacher","The lazy appetite unmet","Prov 16:26; Prov 19:15"),
   (13,"Neglect Compounds","Small slips, big losses","Prov 18:9; Eccl 10:18"),
   (14,"The Cost of Neglect","Where laziness leads","Prov 24:30-34; Prov 10:4"),
  ]},
  {"roman":"III","title":"Diligence and Provision","subtitle":"Effort God Honors","days":[
   (15,"Diligent Hands Will Rule","The reward of effort","Prov 12:24; Prov 22:29"),
   (16,"Plans of the Diligent","Lead to profit","Prov 21:5; Prov 14:23"),
   (17,"The Soul of the Diligent","Fully satisfied","Prov 13:4; Prov 13:25"),
   (18,"Working the Land","Abundant food","Prov 12:11; Prov 28:19"),
   (19,"Skilled and Diligent","Standing before kings","Prov 22:29; Dan 6:3"),
   (20,"God Honors Effort","Provision through work","Prov 10:4; 2 Thess 3:10"),
   (21,"Diligence and Provision","Effort God honors","Prov 10:4; Prov 13:4"),
  ]},
  {"roman":"IV","title":"Faithful in the Work","subtitle":"Steady and Reliable","days":[
   (22,"Faithful in Little","Trusted with much","Luke 16:10; Matt 25:21"),
   (23,"Work With Your Hands","As we instructed","1 Thess 4:11; 2 Thess 3:10-12"),
   (24,"Earning Your Bread","Quietly and faithfully","2 Thess 3:12; 1 Thess 4:11-12"),
   (25,"Not Idle or Disruptive","Settling down to work","2 Thess 3:11-12; Prov 18:9"),
   (26,"Faithful Day by Day","Consistency over flash","Lam 3:22-23; Gal 6:9"),
   (27,"Whatever Your Hand Finds","Do it with all your might","Eccl 9:10; Col 3:23"),
   (28,"Faithful in the Work","Steady and reliable","Luke 16:10; 2 Thess 3:10-12"),
  ]},
  {"roman":"V","title":"When Diligence Feels Vain","subtitle":"Keeping On","days":[
   (29,"When Work Feels Pointless","The honest struggle","Eccl 2:22-23; Eccl 1:3"),
   (30,"Not in Vain in the Lord","Your labor counts","1 Cor 15:58; Gal 6:9"),
   (31,"Sow in the Morning","And evening too","Eccl 11:6; Gal 6:9"),
   (32,"Do Not Grow Weary","The harvest will come","Gal 6:9; 2 Thess 3:13"),
   (33,"Working for the Lord","Not for human reward","Col 3:23-24; Eph 6:7-8"),
   (34,"Trusting the Outcome","To God's hands","Ps 127:1-2; 1 Cor 3:7"),
   (35,"When Diligence Feels Vain","Keeping on","1 Cor 15:58; Gal 6:9"),
  ]},
  {"roman":"VI","title":"The Diligent Hand","subtitle":"Faithful Work Rewarded","days":[
   (36,"Steady Effort","The diligent way","Prov 10:4; Prov 21:5"),
   (37,"Diligent and Trusting","Effort plus dependence","Prov 10:4; Ps 127:1"),
   (38,"Honored by God","Faithful work seen","Prov 22:29; Col 3:23-24"),
   (39,"The Reward of Labor","Provision and satisfaction","Prov 13:4; Ps 128:2"),
   (40,"The Diligent Hand","Faithful work rewarded","Prov 10:4; Prov 13:4"),
  ]},
 ],
}
