# -*- coding: utf-8 -*-
"""40-Day devotional maps — Batch 14 (nums 91-97): Workplace & Marketplace.
6 movements aligned to the 6 sessions, 40 days in a 7-7-7-7-7-5 arc."""

MAPS = {
 # ---------------- 91 · Faith & Finances at Work ----------------
 91: [
  {"roman":"I","title":"Stress Comes to Work","subtitle":"Naming the Burden","days":[
   (1,"Stress Follows Us In","Money worry at work","3 John 1:2; Matt 6:34"),
   (2,"The Weight We Carry","Financial pressure","Prov 12:25; 1 Pet 5:7"),
   (3,"Distracted and Drained","Worry steals focus","Matt 6:25-27; Phil 4:6"),
   (4,"Whole-Person Pressure","Body, mind, soul","3 John 1:2; Ps 38:9-10"),
   (5,"Bringing It to God","Casting our cares","1 Pet 5:7; Phil 4:6-7"),
   (6,"You're Not Alone in It","A common struggle","Eccl 4:9-10; Gal 6:2"),
   (7,"Stress Comes to Work","Naming the burden","3 John 1:2; Matt 6:34"),
  ]},
  {"roman":"II","title":"Wellness That's Whole","subtitle":"Flourishing Fully","days":[
   (8,"Soul and Body Together","Whole wellness","3 John 1:2; 1 Thess 5:23"),
   (9,"That You May Prosper","In every way","3 John 1:2; Ps 1:3"),
   (10,"As Your Soul Prospers","Inside-out health","3 John 1:2; Prov 4:23"),
   (11,"Peace That Guards","Mind and heart","Phil 4:7; Isa 26:3"),
   (12,"Rest for the Weary","He restores","Matt 11:28-29; Ps 23:2-3"),
   (13,"Cares Exchanged for Peace","The good trade","1 Pet 5:7; Phil 4:6-7"),
   (14,"Wellness That's Whole","Flourishing fully","3 John 1:2; 1 Thess 5:23"),
  ]},
  {"roman":"III","title":"Practical Money Help","subtitle":"Steps That Steady","days":[
   (15,"Honor God First","With your income","Prov 3:9-10; Mal 3:10"),
   (16,"A Simple Plan","Order over chaos","Prov 21:5; Luke 14:28"),
   (17,"Live Below Your Means","The freeing habit","Prov 21:20; Prov 13:11"),
   (18,"Save for the Unexpected","Wise foresight","Prov 6:6-8; Prov 27:12"),
   (19,"Steady, Not Anxious","Diligence with peace","Prov 21:5; Phil 4:6"),
   (20,"Content With Enough","The settled heart","1 Tim 6:6-8; Heb 13:5"),
   (21,"Practical Money Help","Steps that steady","Prov 3:9-10; Prov 21:5"),
  ]},
  {"roman":"IV","title":"Principles That Last","subtitle":"Truth That Holds","days":[
   (22,"God Owns It All","The first principle","Ps 24:1; 1 Chr 29:14"),
   (23,"Work as for the Lord","Meaning in labor","Col 3:23-24; Eph 6:7"),
   (24,"Command the Rich","To do good","1 Tim 6:17-18; Luke 12:15"),
   (25,"Hope in God, Not Wealth","The secure anchor","1 Tim 6:17; Ps 62:10"),
   (26,"My God Will Supply","Every need met","Phil 4:19; Matt 6:33"),
   (27,"Rich Toward God","The lasting aim","Luke 12:21; 1 Tim 6:18-19"),
   (28,"Principles That Last","Truth that holds","1 Tim 6:17-19; Col 3:23-24"),
  ]},
  {"roman":"V","title":"A Healthier Team","subtitle":"Whole-Person Culture","days":[
   (29,"Carrying One Another","Burdens shared","Gal 6:2; Eccl 4:9-10"),
   (30,"A Culture of Care","Looking out for each other","Phil 2:4; Rom 12:10"),
   (31,"Encouraging One Another","Daily strength","1 Thess 5:11; Heb 3:13"),
   (32,"Doing Good to All","Especially the household","Gal 6:9-10; Heb 13:16"),
   (33,"Peace Among Us","A healthier climate","Rom 12:18; Col 3:15"),
   (34,"Thriving Together","Mutual flourishing","3 John 1:2; Phil 2:1-2"),
   (35,"A Healthier Team","Whole-person culture","3 John 1:2; Gal 6:9-10"),
  ]},
  {"roman":"VI","title":"Thriving at Work","subtitle":"Prospering in Soul","days":[
   (36,"Flourishing in Every Way","Body and soul","3 John 1:2; Ps 1:3"),
   (37,"Work Without the Worry","Peace at the desk","Phil 4:6-7; Matt 6:34"),
   (38,"Steady and Secure","Anchored in God","1 Tim 6:17; Ps 62:6-7"),
   (39,"Healthy, Whole, and Wise","The full picture","3 John 1:2; Prov 4:23"),
   (40,"Thriving at Work","Prospering in soul","3 John 1:2; Col 3:23-24"),
  ]},
 ],
 # ---------------- 92 · Money, Work, and Meaning ----------------
 92: [
  {"roman":"I","title":"Work on Autopilot","subtitle":"Ready for More","days":[
   (1,"The Daily Grind","Work on autopilot","Eccl 2:22-23; Eccl 1:3"),
   (2,"Going Through the Motions","Meaning gone missing","Eccl 2:17; Eccl 4:8"),
   (3,"What's It All For?","The honest question","Eccl 1:2-3; Eccl 2:11"),
   (4,"Toiling Without Joy","The empty treadmill","Eccl 2:22-23; Eccl 4:8"),
   (5,"More Than a Paycheck","Longing for purpose","Eccl 2:24; Mark 8:36"),
   (6,"Waking Up to Meaning","Beyond the routine","Eccl 2:24-25; Col 3:23"),
   (7,"Work on Autopilot","Ready for more","Eccl 2:22-24; Eccl 1:3"),
  ]},
  {"roman":"II","title":"Satisfaction as Gift","subtitle":"Joy From His Hand","days":[
   (8,"Eat, Drink, Find Satisfaction","A gift from God","Eccl 2:24; Eccl 3:13"),
   (9,"From the Hand of God","Joy in work given","Eccl 2:24-25; Eccl 5:19"),
   (10,"The Gift of God","Enjoying your labor","Eccl 3:13; Eccl 5:18-19"),
   (11,"Nothing Better Than This","Satisfaction in toil","Eccl 3:22; Eccl 2:24"),
   (12,"Receiving, Not Grasping","Joy as grace","Eccl 5:19; Jas 1:17"),
   (13,"Gratitude in the Work","Thankful for it","1 Thess 5:18; Eccl 3:13"),
   (14,"Satisfaction as Gift","Joy from His hand","Eccl 2:24; Eccl 3:13"),
  ]},
  {"roman":"III","title":"Why Do I Earn?","subtitle":"The Purpose Clarified","days":[
   (15,"Examining the Why","Motives matter","Eccl 2:24; Prov 16:2"),
   (16,"Earning to Hoard?","The empty barn","Luke 12:18-21; Eccl 5:10"),
   (17,"Earning to Spend?","Chasing the wind","Eccl 2:1-11; Eccl 5:10"),
   (18,"Earning to Give","A higher purpose","Eph 4:28; 2 Cor 9:11"),
   (19,"Earning to Provide","A worthy aim","1 Tim 5:8; 2 Thess 3:12"),
   (20,"Earning for His Glory","The deepest why","1 Cor 10:31; Col 3:23-24"),
   (21,"Why Do I Earn?","The purpose clarified","Eccl 2:24; 1 Cor 10:31"),
  ]},
  {"roman":"IV","title":"Work That Matters","subtitle":"Significance in Labor","days":[
   (22,"Labor With Purpose","Work that counts","Col 3:23-24; 1 Cor 15:58"),
   (23,"Working for the Lord","The real boss","Col 3:23-24; Eph 6:7"),
   (24,"Your Labor Not in Vain","It matters to God","1 Cor 15:58; Gal 6:9"),
   (25,"Serving Others Through Work","A daily ministry","Gal 5:13; 1 Pet 4:10"),
   (26,"Eternal Weight in Daily Tasks","Meaning multiplied","2 Cor 4:17-18; Col 3:17"),
   (27,"Faithful Where Placed","Purpose in position","1 Cor 7:17; Col 3:23"),
   (28,"Work That Matters","Significance in labor","Col 3:23-24; 1 Cor 15:58"),
  ]},
  {"roman":"V","title":"Commit Your Work","subtitle":"Given to the Lord","days":[
   (29,"Commit Your Work to the Lord","Plans established","Prov 16:3; Ps 37:5"),
   (30,"In All Your Ways","Acknowledge Him","Prov 3:6; Prov 16:9"),
   (31,"Plans Established","When committed to God","Prov 16:3; Prov 19:21"),
   (32,"Whatever You Do","Do it for Him","Col 3:17; 1 Cor 10:31"),
   (33,"Working Before God's Face","An audience of One","Col 3:23-24; Gal 1:10"),
   (34,"Surrendered Labor","Offered up daily","Rom 12:1; Prov 16:3"),
   (35,"Commit Your Work","Given to the Lord","Prov 16:3; Col 3:23-24"),
  ]},
  {"roman":"VI","title":"Money, Work, and Meaning","subtitle":"Labor With Purpose","days":[
   (36,"Purpose Restored","Meaning recovered","Eccl 2:24; Col 3:23-24"),
   (37,"Joy in the Doing","Satisfaction as gift","Eccl 3:13; Eccl 5:18-19"),
   (38,"Eternity in View","The big picture","2 Cor 4:17-18; 1 Cor 15:58"),
   (39,"Committed and Content","Work surrendered","Prov 16:3; Phil 4:11-12"),
   (40,"Money, Work, and Meaning","Labor with purpose","Eccl 2:24; Prov 16:3"),
  ]},
 ],
 # ---------------- 93 · The Generous Workplace ----------------
 93: [
  {"roman":"I","title":"Beyond the Personal","subtitle":"Generosity Together","days":[
   (1,"Generosity Goes Public","Beyond the personal","2 Cor 9:11; Acts 4:32"),
   (2,"More Than My Own Wallet","A shared culture","Acts 4:32-35; 2 Cor 8:1-2"),
   (3,"A Team That Gives","Corporate generosity","2 Cor 9:11; Gal 6:10"),
   (4,"The Ripple of Open Hands","Generosity spreads","Prov 11:25; 2 Cor 9:13"),
   (5,"Enriched to Be Generous","The purpose of plenty","2 Cor 9:11; 2 Cor 9:8"),
   (6,"Generous on Every Occasion","A way of working","2 Cor 9:11; Gal 6:9-10"),
   (7,"Beyond the Personal","Generosity together","2 Cor 9:11; Acts 4:32"),
  ]},
  {"roman":"II","title":"Enriched to Give","subtitle":"Blessed to Bless","days":[
   (8,"Made Rich in Every Way","To be generous","2 Cor 9:11; 2 Cor 9:8"),
   (9,"So You Can Be Generous","The reason for increase","2 Cor 9:11; Eph 4:28"),
   (10,"Generosity Produces Thanksgiving","Overflow to God","2 Cor 9:11-12; 2 Cor 9:13"),
   (11,"God Loves a Cheerful Giver","The glad heart","2 Cor 9:7; Prov 22:9"),
   (12,"Sow Generously, Reap Generously","The principle","2 Cor 9:6; Luke 6:38"),
   (13,"Able to Do Abundantly","God supplies the seed","2 Cor 9:8-10; Phil 4:19"),
   (14,"Enriched to Give","Blessed to bless","2 Cor 9:11; 2 Cor 9:8"),
  ]},
  {"roman":"III","title":"The Generous Team","subtitle":"Open-Handed as One","days":[
   (15,"All Things in Common","The early church model","Acts 4:32; Acts 2:44-45"),
   (16,"No One in Need","Generosity meets needs","Acts 4:34-35; 2 Cor 8:14"),
   (17,"One Heart and Mind","Unity in giving","Acts 4:32; Phil 2:2"),
   (18,"Sharing With the Team","Bearing burdens","Gal 6:2; Rom 12:13"),
   (19,"Looking to Others' Interests","Not just our own","Phil 2:4; 1 Cor 10:24"),
   (20,"Doing Good Together","The shared good","Gal 6:9-10; Heb 13:16"),
   (21,"The Generous Team","Open-handed as one","2 Cor 9:11; Acts 4:32"),
  ]},
  {"roman":"IV","title":"Giving on Every Occasion","subtitle":"Generosity as Habit","days":[
   (22,"Generous on Every Occasion","A constant posture","2 Cor 9:11; Prov 11:25"),
   (23,"As We Have Opportunity","Doing good to all","Gal 6:10; Eccl 11:6"),
   (24,"Ready to Share","Rich in good deeds","1 Tim 6:18; Heb 13:16"),
   (25,"Generous to Outsiders","Beyond our own","Gal 6:10; Luke 6:35"),
   (26,"Spontaneous Generosity","Seizing the moment","Prov 3:27-28; 2 Cor 9:7"),
   (27,"A Lifestyle, Not an Event","Always giving","2 Cor 9:11; Prov 11:24-25"),
   (28,"Giving on Every Occasion","Generosity as habit","2 Cor 9:11; Gal 6:10"),
  ]},
  {"roman":"V","title":"A Community That Gives","subtitle":"Generosity Shared","days":[
   (29,"A Giving Culture","Built together","2 Cor 9:11; Acts 4:32"),
   (30,"Encouraging Generosity","Spurring one another","Heb 10:24; 2 Cor 9:2"),
   (31,"The Refreshed Refresh Others","The cycle","Prov 11:25; 2 Cor 9:12"),
   (32,"Not Growing Weary","In doing good","Gal 6:9; 2 Thess 3:13"),
   (33,"Generosity Multiplied","The contagious effect","2 Cor 8:1-5; 2 Cor 9:13"),
   (34,"Glory to God","The end of generosity","2 Cor 9:12-13; Matt 5:16"),
   (35,"A Community That Gives","Generosity shared","2 Cor 9:11; Acts 4:32"),
  ]},
  {"roman":"VI","title":"The Generous Workplace","subtitle":"Open-Handed Together","days":[
   (36,"A Workplace of Open Hands","The culture formed","2 Cor 9:11; Gal 6:10"),
   (37,"Enriched and Generous","Blessed to bless","2 Cor 9:11; 2 Cor 9:8"),
   (38,"Thanksgiving to God","Generosity's overflow","2 Cor 9:11-12; 2 Cor 9:13"),
   (39,"Reaping What Is Sown","Generously","2 Cor 9:6; Luke 6:38"),
   (40,"The Generous Workplace","Open-handed together","2 Cor 9:11; Gal 6:9-10"),
  ]},
 ],
 # ---------------- 94 · Integrity in the Marketplace ----------------
 94: [
  {"roman":"I","title":"The Daily Test","subtitle":"Integrity Tried","days":[
   (1,"The Marketplace Test","Integrity tried daily","Prov 11:3; Prov 10:9"),
   (2,"Pressures to Bend","The constant pull","Prov 11:3; Dan 6:4"),
   (3,"Small Choices, Big Character","Integrity in the details","Luke 16:10; Prov 20:23"),
   (4,"Who You Are Unseen","Character revealed","Prov 10:9; Heb 4:13"),
   (5,"The Cost of Cutting Corners","A losing bargain","Prov 11:1; Prov 13:11"),
   (6,"Integrity Over Advantage","The harder right","Prov 11:3; Prov 16:8"),
   (7,"The Daily Test","Integrity tried","Prov 11:3; Prov 10:9"),
  ]},
  {"roman":"II","title":"Integrity as Guide","subtitle":"The Trustworthy Compass","days":[
   (8,"Integrity Guides the Upright","A trustworthy compass","Prov 11:3; Prov 11:5"),
   (9,"Duplicity Destroys","The crooked fall","Prov 11:3; Prov 28:18"),
   (10,"A Clear Path","The blameless way","Prov 11:5; Prov 10:9"),
   (11,"Walking Securely","Nothing to fear","Prov 10:9; Prov 28:18"),
   (12,"Led by Honesty","Decisions made clean","Prov 11:3; Prov 2:7-8"),
   (13,"The Upright Are Guided","By their integrity","Prov 11:3; Ps 25:21"),
   (14,"Integrity as Guide","The trustworthy compass","Prov 11:3; Prov 11:5"),
  ]},
  {"roman":"III","title":"Honest Dealing","subtitle":"Fair and True","days":[
   (15,"Honest Scales","Accurate and fair","Prov 16:11; Prov 11:1"),
   (16,"Differing Weights Detested","No double standards","Prov 20:23; Prov 20:10"),
   (17,"Fair in Every Transaction","Square dealing","Prov 11:1; Lev 19:35-36"),
   (18,"Truthful in Business","No deception","Prov 12:22; Eph 4:25"),
   (19,"Keeping Your Word","Even when it costs","Ps 15:4; Matt 5:37"),
   (20,"Doing Right by Others","The golden rule","Matt 7:12; Phil 2:4"),
   (21,"Honest Dealing","Fair and true","Prov 16:11; Prov 11:1"),
  ]},
  {"roman":"IV","title":"The Long View","subtitle":"Integrity's Lasting Reward","days":[
   (22,"Wealth Built Slowly","Grows over time","Prov 13:11; Prov 21:5"),
   (23,"Dishonest Gain Dwindles","The short-lived profit","Prov 13:11; Prov 10:2"),
   (24,"A Good Name Endures","Better than riches","Prov 22:1; Eccl 7:1"),
   (25,"Trust Compounds","Faithful over years","Luke 16:10; Prov 3:3-4"),
   (26,"Better Poor and Honest","Than rich and crooked","Prov 28:6; Prov 19:1"),
   (27,"Sowing Integrity","Reaping trust","Gal 6:7-9; Prov 11:18"),
   (28,"The Long View","Integrity's lasting reward","Prov 13:11; Prov 22:1"),
  ]},
  {"roman":"V","title":"Nothing to Hide","subtitle":"Integrity in the Open","days":[
   (29,"Clean Hands at Work","Nothing concealed","Ps 24:3-4; Prov 10:9"),
   (30,"Above Reproach","No accusation sticks","1 Tim 3:7; Titus 2:7-8"),
   (31,"Living in the Light","Open to scrutiny","John 3:21; 1 Pet 3:16"),
   (32,"No Corruption Found","Like Daniel","Dan 6:4; Prov 11:3"),
   (33,"A Clear Conscience","Before God and people","Acts 24:16; 1 Pet 3:16"),
   (34,"Transparent and True","Honest through and through","2 Cor 8:21; Prov 11:3"),
   (35,"Nothing to Hide","Integrity in the open","Prov 10:9; Dan 6:4"),
  ]},
  {"roman":"VI","title":"Integrity in the Marketplace","subtitle":"Upright in Business","days":[
   (36,"Character That Holds","Under any pressure","Prov 11:3; Prov 10:9"),
   (37,"Trusted and Respected","The fruit of integrity","Prov 22:1; Luke 16:10"),
   (38,"Honest in All Things","A consistent life","2 Cor 8:21; Heb 13:18"),
   (39,"Blessed in the Doing","God honors integrity","Prov 10:9; Ps 112:1-3"),
   (40,"Integrity in the Marketplace","Upright in business","Prov 11:3; Prov 10:9"),
  ]},
 ],
 # ---------------- 95 · Stewardship for Leaders ----------------
 95: [
  {"roman":"I","title":"Entrusted With Much","subtitle":"The Leader's Calling","days":[
   (1,"The Trust of Leadership","Entrusted with much","Luke 12:48; 1 Cor 4:1-2"),
   (2,"Managers, Not Owners","Stewards of it all","1 Cor 4:1-2; 1 Pet 4:10"),
   (3,"Given to Be Used","Resources, people, influence","Luke 12:48; Matt 25:14-15"),
   (4,"The Weight of Responsibility","Much required","Luke 12:48; Jas 3:1"),
   (5,"Faithful, Not Flashy","What's asked of stewards","1 Cor 4:2; Luke 16:10"),
   (6,"A Sacred Trust","Leadership as stewardship","1 Pet 5:2-3; Luke 12:48"),
   (7,"Entrusted With Much","The leader's calling","Luke 12:48; 1 Cor 4:1-2"),
  ]},
  {"roman":"II","title":"To Whom Much Is Given","subtitle":"The Leader's Account","days":[
   (8,"Much Given, Much Required","The principle","Luke 12:48; Luke 12:47"),
   (9,"Greater Trust, Greater Account","The weightier charge","Luke 12:48; Jas 3:1"),
   (10,"Privilege Is Responsibility","Not entitlement","Luke 12:48; 1 Cor 4:7"),
   (11,"Stewarding the Position","Power held humbly","1 Pet 5:2-3; Mark 10:42-45"),
   (12,"Accountable to the Master","The reckoning","Luke 16:2; Rom 14:12"),
   (13,"Faithful With More","As with little","Luke 16:10-12; Matt 25:21"),
   (14,"To Whom Much Is Given","The leader's account","Luke 12:48; 1 Cor 4:2"),
  ]},
  {"roman":"III","title":"Stewarding Resources","subtitle":"Faithful With the Funds","days":[
   (15,"Know Your Flocks and Herds","Mind the resources","Prov 27:23-24; Luke 16:11"),
   (16,"Wise With the Budget","Faithful management","Luke 16:10-11; Prov 21:5"),
   (17,"Riches Don't Last Forever","Steward them well","Prov 27:24; 1 Tim 6:17"),
   (18,"Not Wasting What's Entrusted","Accountable use","Luke 16:1-2; Matt 25:26-27"),
   (19,"Investing for Return","The faithful servant","Matt 25:20-23; Luke 19:13-17"),
   (20,"Generous With Resources","Open-handed leadership","1 Tim 6:18; 2 Cor 9:11"),
   (21,"Stewarding Resources","Faithful with the funds","Prov 27:23-24; Luke 16:11"),
  ]},
  {"roman":"IV","title":"Stewarding People","subtitle":"The Flock Entrusted","days":[
   (22,"People Are the Trust","Not just numbers","1 Pet 5:2-3; Phil 2:4"),
   (23,"Shepherd, Don't Lord","Servant leadership","1 Pet 5:2-3; Mark 10:42-45"),
   (24,"Eager to Serve","Not for gain","1 Pet 5:2; Acts 20:33-35"),
   (25,"Examples to the Flock","Leading by living","1 Pet 5:3; 1 Cor 11:1"),
   (26,"Caring for the Team","Their good in view","Phil 2:4; Prov 27:23"),
   (27,"Developing Others","Multiplying faithfulness","2 Tim 2:2; Eph 4:11-12"),
   (28,"Stewarding People","The flock entrusted","1 Pet 5:2-3; Phil 2:4"),
  ]},
  {"roman":"V","title":"Stewarding Influence","subtitle":"Reach Used Rightly","days":[
   (29,"Influence as a Trust","Given to steward","Luke 12:48; Prov 3:27"),
   (30,"Setting the Tone","Culture flows down","1 Cor 11:1; 1 Pet 5:3"),
   (31,"Using Power to Serve","Not to be served","Mark 10:42-45; Phil 2:5-7"),
   (32,"A Platform for Good","Doing right with reach","Gal 6:9-10; Prov 31:8-9"),
   (33,"Integrity at the Top","Watched and followed","Prov 11:3; Titus 2:7"),
   (34,"Pointing Beyond Yourself","To the Master","Matt 5:16; 1 Cor 10:31"),
   (35,"Stewarding Influence","Reach used rightly","Luke 12:48; Mark 10:43-45"),
  ]},
  {"roman":"VI","title":"Stewardship for Leaders","subtitle":"Faithful With Much","days":[
   (36,"The Faithful Leader","Steward of it all","1 Cor 4:1-2; Luke 12:48"),
   (37,"Resources, People, Influence","All held in trust","Luke 12:48; 1 Pet 5:2-3"),
   (38,"Servant at the Helm","Leading like Christ","Mark 10:42-45; Phil 2:5-7"),
   (39,"Well Done, Good Steward","The aim of it all","Matt 25:21; Luke 19:17"),
   (40,"Stewardship for Leaders","Faithful with much","Luke 12:48; 1 Cor 4:2"),
  ]},
 ],
 # ---------------- 96 · The Ethics of Money at Work ----------------
 96: [
  {"roman":"I","title":"The Gray Areas","subtitle":"Bringing Light to Them","days":[
   (1,"The Gray Areas","Where ethics get murky","Prov 10:9; Prov 11:3"),
   (2,"Not Always Black and White","The hard calls","Prov 2:6-9; Jas 1:5"),
   (3,"Small Compromises","The slippery slope","Luke 16:10; Song 2:15"),
   (4,"Everybody Does It","The crowd's excuse","Ex 23:2; Prov 1:10-15"),
   (5,"When No One Would Know","The true test","Prov 10:9; Heb 4:13"),
   (6,"Asking the Hard Question","Is this right?","Mic 6:8; Prov 3:7"),
   (7,"The Gray Areas","Bringing light to them","Prov 10:9; Jas 1:5"),
  ]},
  {"roman":"II","title":"Walking Securely","subtitle":"The Integrity Dividend","days":[
   (8,"Walking in Integrity","Walking securely","Prov 10:9; Ps 25:21"),
   (9,"The Crooked Path Found Out","No hiding place","Prov 10:9; Num 32:23"),
   (10,"Security in Honesty","Nothing to fear","Prov 10:9; Prov 28:1"),
   (11,"A Conscience at Rest","Sleeping soundly","Prov 3:24; Ps 4:8"),
   (12,"The Blameless Kept Safe","Guarded by integrity","Prov 2:7-8; Prov 11:3"),
   (13,"Steady Footing","On the honest road","Prov 10:9; Ps 26:1"),
   (14,"Walking Securely","The integrity dividend","Prov 10:9; Ps 25:21"),
  ]},
  {"roman":"III","title":"The Expense and the Edge","subtitle":"Honest in the Details","days":[
   (15,"The Padded Expense","A common temptation","Luke 16:10; Prov 11:1"),
   (16,"Faithful in Little","Or unfaithful in little","Luke 16:10; Luke 16:11"),
   (17,"The Honest Report","Truth in the details","Prov 12:22; Eph 4:25"),
   (18,"Stealing by Inches","Time and resources","Eph 6:5-7; Titus 2:10"),
   (19,"The Small Edge","Not worth the soul","Mark 8:36; Prov 11:1"),
   (20,"Trustworthy With Money","In the small things","Luke 16:10-11; Prov 20:23"),
   (21,"The Expense and the Edge","Honest in the details","Luke 16:10; Prov 11:1"),
  ]},
  {"roman":"IV","title":"Conflicts of Interest","subtitle":"Loyalties Kept Clean","days":[
   (22,"Two Masters at Work","Divided loyalties","Matt 6:24; Luke 16:13"),
   (23,"Whose Interest Comes First?","The honest question","Phil 2:4; 1 Cor 10:24"),
   (24,"The Gift That Obligates","Bribes and favors","Prov 17:23; Ex 23:8"),
   (25,"Serving the Right Master","Undivided","Col 3:23-24; Matt 6:24"),
   (26,"No Hidden Agendas","Transparent dealings","2 Cor 4:2; 2 Cor 8:21"),
   (27,"Doing Right by All","Fair to every party","Mic 6:8; Rom 13:7-8"),
   (28,"Conflicts of Interest","Loyalties kept clean","Matt 6:24; Phil 2:4"),
  ]},
  {"roman":"V","title":"Found Out","subtitle":"Why Honesty Is Wisdom","days":[
   (29,"Be Sure It Finds You","The hidden surfaces","Num 32:23; Luke 12:2-3"),
   (30,"Nothing Concealed","Will not be revealed","Luke 12:2-3; Mark 4:22"),
   (31,"The God Who Sees","All is laid bare","Heb 4:13; Prov 15:3"),
   (32,"Caught Clean, Not Dirty","The better way","Prov 10:9; 1 Pet 3:16"),
   (33,"No Fear of Exposure","The honest freedom","Prov 28:1; Ps 32:1-2"),
   (34,"Integrity Vindicated","In time, it shows","Ps 37:5-6; 1 Pet 2:12"),
   (35,"Found Out","Why honesty is wisdom","Num 32:23; Luke 12:2-3"),
  ]},
  {"roman":"VI","title":"Ethics That Hold","subtitle":"Integrity That Lasts","days":[
   (36,"Ethics Under Pressure","Holding the line","Prov 10:9; Dan 6:4"),
   (37,"A Reputation for Right","Trusted and clean","Prov 22:1; 1 Pet 3:16"),
   (38,"Working as for the Lord","The highest standard","Col 3:23-25; Eph 6:7"),
   (39,"Clean Hands, Clear Conscience","The settled soul","Ps 24:3-4; Acts 24:16"),
   (40,"Ethics That Hold","Integrity that lasts","Prov 10:9; Col 3:23-25"),
  ]},
 ],
 # ---------------- 97 · Wise Money for Working Professionals ----------------
 97: [
  {"roman":"I","title":"The Professional's Squeeze","subtitle":"Naming the Bind","days":[
   (1,"The Professional's Squeeze","Busy and stretched","Eph 5:15-16; Ps 90:12"),
   (2,"Time-Poor, Cash-Stressed","The modern bind","Eccl 2:22-23; Mark 4:19"),
   (3,"Drifting Without a Plan","Money on autopilot","Prov 21:5; Hag 1:5-6"),
   (4,"The Cost of Busyness","No time to steward","Luke 10:41-42; Eph 5:15-16"),
   (5,"Earning Well, Saving Poorly","The leaky bucket","Hag 1:6; Prov 21:20"),
   (6,"Time to Be Intentional","Wise, not careless","Eph 5:15; Prov 14:8"),
   (7,"The Professional's Squeeze","Naming the bind","Eph 5:15-16; Ps 90:12"),
  ]},
  {"roman":"II","title":"Making the Most of It","subtitle":"Time and Money Redeemed","days":[
   (8,"Make the Most of Every Opportunity","Time redeemed","Eph 5:16; Col 4:5"),
   (9,"Be Very Careful How You Live","Wise, not unwise","Eph 5:15; Prov 14:8"),
   (10,"Number Your Days","Steward the hours","Ps 90:12; Eph 5:16"),
   (11,"The Days Are Evil","Use them well","Eph 5:16; Eccl 9:10"),
   (12,"Wise Use of Resources","Time and money","Eph 5:15-16; Luke 16:10"),
   (13,"Intentional, Not Accidental","On purpose","Prov 21:5; Prov 14:8"),
   (14,"Making the Most of It","Time and money redeemed","Eph 5:15-16; Col 4:5"),
  ]},
  {"roman":"III","title":"Taming Lifestyle Creep","subtitle":"Spending Held in Check","days":[
   (15,"As Income Rises","So does spending","Eccl 5:10-11; Prov 21:17"),
   (16,"The Upgrade Trap","More never satisfies","Eccl 5:10; 1 Tim 6:8"),
   (17,"When Goods Increase","So do the consumers","Eccl 5:11; Luke 12:15"),
   (18,"Holding the Line","Lifestyle held steady","Prov 21:20; Heb 13:5"),
   (19,"Content at Any Income","The learned secret","Phil 4:11-12; 1 Tim 6:6"),
   (20,"Growing the Gap","Save the raise","Prov 21:20; Prov 13:11"),
   (21,"Taming Lifestyle Creep","Spending held in check","Eccl 5:10-11; Prov 21:20"),
  ]},
  {"roman":"IV","title":"Decisions That Won't Wait","subtitle":"Made With Wisdom","days":[
   (22,"Counting the Cost","Before committing","Luke 14:28; Prov 21:5"),
   (23,"Big Decisions, Wise Counsel","Many advisers","Prov 15:22; Prov 11:14"),
   (24,"By Wisdom a House Is Built","Sound choices","Prov 24:3-4; Prov 14:1"),
   (25,"Plans of the Diligent","Lead to profit","Prov 21:5; Prov 14:23"),
   (26,"Not Deciding by Default","Choosing on purpose","Prov 14:8; Jas 4:13-15"),
   (27,"Committing Plans to God","His direction","Prov 16:3; Prov 16:9"),
   (28,"Decisions That Won't Wait","Made with wisdom","Luke 14:28; Prov 21:5"),
  ]},
  {"roman":"V","title":"Foresight Over Drift","subtitle":"Intentional and Prepared","days":[
   (29,"Look Well to Your Ways","Foresight, not drift","Prov 14:8; Hag 1:5"),
   (30,"The Prudent See Ahead","And prepare","Prov 22:3; Prov 27:12"),
   (31,"Saving for Tomorrow","The ant's wisdom","Prov 6:6-8; Prov 21:20"),
   (32,"Steady Plans, Sure Progress","Diligence pays","Prov 21:5; Prov 13:11"),
   (33,"An Emergency Cushion","Wise margin","Prov 27:12; Prov 22:3"),
   (34,"Planning for the Long Haul","The future in view","Prov 13:11; Prov 24:27"),
   (35,"Foresight Over Drift","Intentional and prepared","Prov 14:8; Prov 21:5"),
  ]},
  {"roman":"VI","title":"Wise and Working","subtitle":"The Intentional Professional","days":[
   (36,"Living Wisely","Careful and intentional","Eph 5:15-16; Prov 14:8"),
   (37,"Time and Money Stewarded","Both redeemed","Eph 5:16; Luke 16:10"),
   (38,"Content and Foresighted","Steady at any income","Phil 4:11-12; Prov 21:20"),
   (39,"Making It Count","Every day, every dollar","Eph 5:15-16; Ps 90:12"),
   (40,"Wise and Working","The intentional professional","Eph 5:15-16; Prov 21:5"),
  ]},
 ],
}
