# -*- coding: utf-8 -*-
"""40-Day devotional maps — Batch 13 (nums 86-90): Seasons & Life Stages (part 2).
Includes tender topics (loss, financial crisis, hard times) handled gently.
6 movements aligned to the 6 sessions, 40 days in a 7-7-7-7-7-5 arc."""

MAPS = {
 # ---------------- 86 · Finishing the Race Financially ----------------
 86: [
  {"roman":"I","title":"The Final Lap","subtitle":"Running It Well","days":[
   (1,"The Home Stretch","The final lap of life","2 Tim 4:7; Phil 3:14"),
   (2,"Running to the End","Finishing, not coasting","1 Cor 9:24-25; Heb 12:1"),
   (3,"The Goal Ahead","Pressing on","Phil 3:13-14; 2 Tim 4:7"),
   (4,"Stewarding the Last Stretch","Faithful to the finish","Luke 16:10; Matt 25:21"),
   (5,"No Coasting Now","Diligent to the end","Gal 6:9; Eccl 9:10"),
   (6,"Eyes on the Prize","The finish line","Phil 3:14; Heb 12:1-2"),
   (7,"The Final Lap","Running it well","2 Tim 4:7; Phil 3:14"),
  ]},
  {"roman":"II","title":"Finished the Race","subtitle":"The Aim of It All","days":[
   (8,"I Have Finished the Race","Paul's testimony","2 Tim 4:7; Acts 20:24"),
   (9,"Fought the Good Fight","A life well spent","2 Tim 4:7; 1 Tim 6:12"),
   (10,"Kept the Faith","Faithful throughout","2 Tim 4:7; 2 Tim 4:8"),
   (11,"The Crown Awaits","The reward ahead","2 Tim 4:8; 1 Cor 9:25"),
   (12,"Well Done, Good Servant","The words we long to hear","Matt 25:21; Matt 25:23"),
   (13,"A Life Poured Out","Like a drink offering","2 Tim 4:6; Phil 2:17"),
   (14,"Finished the Race","The aim of it all","2 Tim 4:7; Matt 25:21"),
  ]},
  {"roman":"III","title":"Stewarding to the End","subtitle":"Faithful With the Last","days":[
   (15,"Faithful to the Last","Stewarding every day","Luke 16:10; 1 Cor 4:2"),
   (16,"Wise With What Remains","The final stewardship","Prov 21:20; Luke 16:11"),
   (17,"Setting Affairs in Order","Wisdom for the end","2 Kgs 20:1; Prov 21:5"),
   (18,"A Plan for What's Left","Thoughtful provision","Prov 13:22; Prov 21:5"),
   (19,"Not Hoarding to the Grave","Holding loosely","Luke 12:20-21; Eccl 5:15"),
   (20,"Tending the Trust","To the very end","Matt 25:21; 1 Pet 4:10"),
   (21,"Stewarding to the End","Faithful with the last","Luke 16:10; Prov 21:20"),
  ]},
  {"roman":"IV","title":"Generous at the Finish","subtitle":"Open-Handed to the End","days":[
   (22,"Generous to the Last","Open hands at the end","1 Tim 6:18-19; 2 Cor 9:7"),
   (23,"Storing Treasure in Heaven","Sending it ahead","Matt 6:20-21; Luke 12:33"),
   (24,"Blessing the Next Generation","Giving forward","Prov 13:22; Ps 112:1-3"),
   (25,"Final Gifts of Love","Generosity that outlives","2 Cor 9:6; Prov 11:25"),
   (26,"Rich Toward God","At the finish","Luke 12:21; 1 Tim 6:18"),
   (27,"A Legacy of Giving","The lasting mark","Ps 112:9; 2 Cor 9:9"),
   (28,"Generous at the Finish","Open-handed to the end","1 Tim 6:18-19; Luke 6:38"),
  ]},
  {"roman":"V","title":"Leaving It Well","subtitle":"A Blessing Handed On","days":[
   (29,"A Good Inheritance","For children's children","Prov 13:22; Ps 112:2"),
   (30,"More Than Money","A heritage of faith","2 Tim 1:5; Ps 78:4-7"),
   (31,"Wisdom in the Will","Thoughtful provision","Prov 13:22; Prov 21:5"),
   (32,"Blessing, Not Burden","Leaving freedom, not strife","Prov 13:22; Prov 17:1"),
   (33,"The Legacy That Lasts","Character and faith","Prov 22:1; Ps 112:6"),
   (34,"Naked I Came","What truly transfers","Job 1:21; 1 Tim 6:7"),
   (35,"Leaving It Well","A blessing handed on","Prov 13:22; 2 Tim 1:5"),
  ]},
  {"roman":"VI","title":"Finishing Faithful","subtitle":"The Race Run Well","days":[
   (36,"Faithful to the Finish","The whole-life aim","2 Tim 4:7; Matt 25:21"),
   (37,"The Crown of Righteousness","Awaiting the faithful","2 Tim 4:8; 1 Cor 9:25"),
   (38,"Well Done","The Master's welcome","Matt 25:21; Matt 25:23"),
   (39,"Hope Beyond the Finish","Eternity ahead","Phil 3:14; 2 Cor 4:17-18"),
   (40,"Finishing Faithful","The race run well","2 Tim 4:7; Phil 3:14"),
  ]},
 ],
 # ---------------- 87 · Single and Stewarding Well ----------------
 87: [
  {"roman":"I","title":"The Single Steward","subtitle":"A Full and Good Life","days":[
   (1,"Single and Whole","A full stewardship","1 Cor 7:35; 1 Cor 7:7"),
   (2,"Not Lesser, Just Different","A good calling","1 Cor 7:7-8; 1 Cor 7:17"),
   (3,"Your Own Stewardship","Fully yours","1 Pet 4:10; Luke 16:10"),
   (4,"Free to Steward Well","Unique opportunities","1 Cor 7:32-34; 1 Cor 7:35"),
   (5,"Content in This Season","Whatever it holds","Phil 4:11-12; 1 Tim 6:6"),
   (6,"God's Good Gift","Singleness honored","1 Cor 7:7; Ps 16:5-6"),
   (7,"The Single Steward","A full and good life","1 Cor 7:35; 1 Pet 4:10"),
  ]},
  {"roman":"II","title":"Undivided Devotion","subtitle":"Living It Fully","days":[
   (8,"Undivided Devotion","The single's gift","1 Cor 7:35; 1 Cor 7:32"),
   (9,"The Lord's Affairs","A focused life","1 Cor 7:32; 1 Cor 7:34"),
   (10,"Freedom to Serve","Time and energy given","1 Cor 7:35; Gal 5:13"),
   (11,"Seeking First the Kingdom","Wholehearted","Matt 6:33; Luke 12:31"),
   (12,"Generous With Availability","A unique offering","Rom 12:1; 1 Cor 7:35"),
   (13,"Devotion Without Distraction","The single advantage","1 Cor 7:35; Ps 27:4"),
   (14,"Undivided Devotion","Living it fully","1 Cor 7:35; 1 Cor 7:32"),
  ]},
  {"roman":"III","title":"Decisions of One","subtitle":"Made in Wisdom","days":[
   (15,"Choosing Alone","Decisions of one","Jas 1:5; Prov 3:5-6"),
   (16,"Wisdom for the Solo Call","Asking God","Jas 1:5; Prov 2:6"),
   (17,"Seeking Wise Counsel","Not deciding in a vacuum","Prov 15:22; Prov 11:14"),
   (18,"The Freedom to Decide","And the responsibility","1 Cor 7:37; Gal 6:5"),
   (19,"Planning for One","Thoughtful and clear","Prov 21:5; Luke 14:28"),
   (20,"Committing the Way","To the Lord","Ps 37:5; Prov 16:3"),
   (21,"Decisions of One","Made in wisdom","Jas 1:5; Prov 15:22"),
  ]},
  {"roman":"IV","title":"Building Your Community","subtitle":"Woven Into Others","days":[
   (22,"Not Meant to Be Alone","Community matters","Eccl 4:9-10; Gen 2:18"),
   (23,"Two Are Better Than One","Even when single","Eccl 4:9; Eccl 4:12"),
   (24,"If One Falls","Friends help up","Eccl 4:10; Gal 6:2"),
   (25,"The Family of God","Belonging deeply","Ps 68:6; Mark 3:34-35"),
   (26,"Bearing One Another's Burdens","Mutual support","Gal 6:2; Rom 12:13"),
   (27,"Generous in Community","Sharing life and resources","Acts 2:44-45; Heb 13:16"),
   (28,"Building Your Community","Woven into others","Eccl 4:9-12; Ps 68:6"),
  ]},
  {"roman":"V","title":"Safety Nets and Wisdom","subtitle":"Prepared and Trusting","days":[
   (29,"Prudent Provision","Wise safety nets","Prov 21:20; Prov 22:3"),
   (30,"An Emergency Fund","The single's cushion","Prov 6:6-8; Prov 27:12"),
   (31,"The Prudent See Danger","And prepare","Prov 22:3; Prov 27:12"),
   (32,"A House Built by Wisdom","Practical planning","Prov 24:3-4; Luke 14:28"),
   (33,"Planning for the Future","Thoughtful foresight","Prov 13:11; Prov 21:5"),
   (34,"Trusting While Preparing","Faith and wisdom","Prov 3:5-6; Matt 6:33"),
   (35,"Safety Nets and Wisdom","Prepared and trusting","Prov 21:20; Prov 22:3"),
  ]},
  {"roman":"VI","title":"Stewarding Well, Single","subtitle":"A Full and Faithful Life","days":[
   (36,"A Faithful Single Steward","Living it well","1 Cor 7:35; Luke 16:10"),
   (37,"Content and Devoted","The settled heart","Phil 4:11-12; 1 Cor 7:32"),
   (38,"Generous and Free","Open-handed living","2 Cor 9:7; 1 Cor 7:35"),
   (39,"Whole in This Season","Lacking nothing","Ps 23:1; Phil 4:19"),
   (40,"Stewarding Well, Single","A full and faithful life","1 Cor 7:35; 1 Pet 4:10"),
  ]},
 ],
 # ---------------- 88 · Money After Loss ----------------
 88: [
  {"roman":"I","title":"Grief and Money","subtitle":"A Tender Beginning","days":[
   (1,"When Grief and Money Meet","A heavy season","Ps 68:5; Ps 31:9-10"),
   (2,"The Weight You Carry","More than finances","Ps 34:18; Ps 142:1-3"),
   (3,"Decisions in the Fog","Hard to think clearly","Ps 68:5; Eccl 3:4"),
   (4,"It's Okay to Grieve","Tears are welcome","Ps 56:8; John 11:35"),
   (5,"You Don't Face It Alone","God draws near","Ps 34:18; Ps 23:4"),
   (6,"He Carries the Brokenhearted","Held in sorrow","Ps 147:3; Isa 40:11"),
   (7,"Grief and Money","A tender beginning","Ps 68:5; Ps 34:18"),
  ]},
  {"roman":"II","title":"Close to the Brokenhearted","subtitle":"Never Abandoned","days":[
   (8,"Close to the Brokenhearted","God is near","Ps 34:18; Ps 147:3"),
   (9,"He Saves the Crushed in Spirit","Tender care","Ps 34:18; Ps 73:26"),
   (10,"A Father to the Fatherless","Defender of the widow","Ps 68:5; Ps 146:9"),
   (11,"He Heals the Brokenhearted","Binding up wounds","Ps 147:3; Isa 61:1"),
   (12,"The God of All Comfort","Comfort in affliction","2 Cor 1:3-4; Ps 23:4"),
   (13,"He Keeps Your Tears","Not one is lost","Ps 56:8; Ps 30:5"),
   (14,"Close to the Brokenhearted","Never abandoned","Ps 34:18; Ps 68:5"),
  ]},
  {"roman":"III","title":"First, Be Gentle","subtitle":"Tenderness With Yourself","days":[
   (15,"Be Gentle With Yourself","No need to rush","Eccl 3:1; Ps 23:2-3"),
   (16,"No Big Decisions Yet","Wait where you can","Prov 19:2; Ps 27:14"),
   (17,"One Day at a Time","Today's grace for today","Matt 6:34; Lam 3:22-23"),
   (18,"Rest in the Grieving","He gives rest","Matt 11:28; Ps 23:2"),
   (19,"Grace for the Hard Days","His mercy is new","Lam 3:22-23; 2 Cor 12:9"),
   (20,"Permission to Go Slow","Healing takes time","Eccl 3:1-4; Ps 30:5"),
   (21,"First, Be Gentle","Tenderness with yourself","Ps 23:2-3; Lam 3:22-23"),
  ]},
  {"roman":"IV","title":"The Necessary Steps","subtitle":"Taken Gently, in Time","days":[
   (22,"When You're Ready","The practical matters","Prov 21:5; Eccl 3:1"),
   (23,"One Step at a Time","Small and manageable","Luke 16:10; Ps 119:105"),
   (24,"Asking for Help","You needn't know it all","Jas 1:5; Prov 15:22"),
   (25,"Trusted Guidance","Wise counsel matters","Prov 11:14; Prov 15:22"),
   (26,"Simple, Not Overwhelming","Just the next thing","Matt 6:34; Prov 21:5"),
   (27,"He Gives Wisdom","For each decision","Jas 1:5; Ps 32:8"),
   (28,"The Necessary Steps","Taken gently, in time","Prov 21:5; Jas 1:5"),
  ]},
  {"roman":"V","title":"Leaning on Others","subtitle":"Carried by Community","days":[
   (29,"Not Made to Carry Alone","Lean on others","Gal 6:2; Eccl 4:9-10"),
   (30,"Bear One Another's Burdens","Let them help","Gal 6:2; Rom 12:15"),
   (31,"The Family of God","Surrounding you","Ps 68:6; Mark 3:34-35"),
   (32,"Mourn With Those Who Mourn","Community in grief","Rom 12:15; Job 2:11-13"),
   (33,"Receiving Care","Letting others give","Acts 20:35; 2 Cor 1:4"),
   (34,"Held by the Body","Not facing it solo","1 Cor 12:26; Gal 6:2"),
   (35,"Leaning on Others","Carried by community","Gal 6:2; Ps 68:6"),
  ]},
  {"roman":"VI","title":"Tended Through Loss","subtitle":"Held by the God of Comfort","days":[
   (36,"Tended in the Valley","God's faithful care","Ps 23:4; Ps 34:18"),
   (37,"Where You Go, He Goes","Never alone","Ruth 1:16-17; Heb 13:5"),
   (38,"Morning Will Come","Joy returns in time","Ps 30:5; Ps 126:5"),
   (39,"He Will Sustain You","Through and beyond","Ps 55:22; Isa 46:4"),
   (40,"Tended Through Loss","Held by the God of comfort","Ps 68:5; 2 Cor 1:3-4"),
  ]},
 ],
 # ---------------- 89 · Rebuilding After Financial Crisis ----------------
 89: [
  {"roman":"I","title":"After the Collapse","subtitle":"Beginning Again","days":[
   (1,"When It All Falls Apart","The aftermath","Joel 2:25; Ps 40:1-2"),
   (2,"The Rubble of a Crisis","Surveying the loss","Lam 3:19-20; Ps 31:9-10"),
   (3,"You Are Still Here","Hope remains","Lam 3:21-22; Ps 42:11"),
   (4,"Not the End of the Story","God isn't finished","Joel 2:25; Phil 1:6"),
   (5,"He Lifts From the Pit","The rescuing God","Ps 40:1-2; Ps 113:7"),
   (6,"A God Who Restores","Hope of rebuilding","Joel 2:25; Job 42:10"),
   (7,"After the Collapse","Beginning again","Joel 2:25; Ps 40:1-2"),
  ]},
  {"roman":"II","title":"Restoring the Years","subtitle":"The Promise of Renewal","days":[
   (8,"I Will Restore the Years","The locusts' damage undone","Joel 2:25; Joel 2:26"),
   (9,"The Lord Restored Job","After his trouble","Job 42:10; Job 42:12"),
   (10,"Beauty for Ashes","The great exchange","Isa 61:3; Isa 61:1"),
   (11,"He Restores My Soul","More than finances","Ps 23:3; Ps 51:12"),
   (12,"New Mercies Each Morning","Fresh starts","Lam 3:22-23; Ps 30:5"),
   (13,"Hope of Restoration","God can rebuild","Joel 2:25-26; Jer 29:11"),
   (14,"Restoring the Years","The promise of renewal","Joel 2:25; Job 42:10"),
  ]},
  {"roman":"III","title":"Releasing the Shame","subtitle":"Free to Move Forward","days":[
   (15,"Lay Down the Shame","It isn't yours to carry","Rom 8:1; Ps 34:5"),
   (16,"No Condemnation","In Christ Jesus","Rom 8:1; Isa 54:4"),
   (17,"Those Who Look to Him","Are never ashamed","Ps 34:5; Rom 10:11"),
   (18,"Forgetting What Is Behind","Pressing forward","Phil 3:13-14; Isa 43:18-19"),
   (19,"His Mercy, Not Your Failure","Grace defines you","Lam 3:22-23; Eph 2:4-5"),
   (20,"Lifting the Head","He restores dignity","Ps 3:3; Ps 27:6"),
   (21,"Releasing the Shame","Free to move forward","Rom 8:1; Ps 34:5"),
  ]},
  {"roman":"IV","title":"The First Steps Back","subtitle":"The Climb Begins","days":[
   (22,"One Step at a Time","Small beginnings","Zech 4:10; Luke 16:10"),
   (23,"Do Not Despise Small Things","Every step counts","Zech 4:10; Prov 13:11"),
   (24,"A Plan to Rebuild","Wisdom for the climb","Prov 21:5; Prov 24:3-4"),
   (25,"Faithful in Little","The foundation of more","Luke 16:10; Matt 25:21"),
   (26,"Asking for Help","Wisdom in counsel","Prov 15:22; Gal 6:2"),
   (27,"Diligent Hands","Rebuilding steadily","Prov 10:4; Prov 13:4"),
   (28,"The First Steps Back","The climb begins","Zech 4:10; Prov 21:5"),
  ]},
  {"roman":"V","title":"Steady Progress","subtitle":"Faithful, Day by Day","days":[
   (29,"Little by Little","Rebuilding takes time","Prov 13:11; Prov 21:5"),
   (30,"Not Weary in Doing Good","Keep going","Gal 6:9; 2 Thess 3:13"),
   (31,"Brick by Brick","Steady reconstruction","Neh 4:6; Prov 24:27"),
   (32,"Patience in the Process","The slow climb","Jas 5:7-8; Rom 5:3-4"),
   (33,"Celebrating Small Wins","Progress noticed","Zech 4:10; Ps 126:3"),
   (34,"Trusting the Rebuilder","God in the work","Ps 127:1; Phil 1:6"),
   (35,"Steady Progress","Faithful, day by day","Prov 13:11; Gal 6:9"),
  ]},
  {"roman":"VI","title":"Hope Restored","subtitle":"Rebuilt by Grace","days":[
   (36,"Plans to Give Hope","A future ahead","Jer 29:11; Rom 8:28"),
   (37,"He Will Complete It","The good work finished","Phil 1:6; 1 Thess 5:24"),
   (38,"Restored and Stronger","Refined by fire","1 Pet 1:6-7; Jas 1:2-4"),
   (39,"A Future and a Hope","Beyond the crisis","Jer 29:11; Ps 40:1-3"),
   (40,"Hope Restored","Rebuilt by grace","Joel 2:25; Jer 29:11"),
  ]},
 ],
 # ---------------- 90 · Money in Hard Times ----------------
 90: [
  {"roman":"I","title":"When Times Are Hard","subtitle":"Bringing It to God","days":[
   (1,"When Times Are Hard","Facing the lean season","Hab 3:17; Ps 37:18-19"),
   (2,"The Pinch of Scarcity","Doing more with less","Phil 4:12; Prov 30:8"),
   (3,"Fear at the Door","The temptation to panic","Matt 6:31-32; Ps 56:3"),
   (4,"God in the Hard Times","Still on the throne","Ps 46:1-3; Nah 1:7"),
   (5,"Not Forsaken in Famine","He provides","Ps 37:18-19; Ps 33:18-19"),
   (6,"Hard, but Not Hopeless","Faith in scarcity","Hab 3:17-18; Rom 5:3-4"),
   (7,"When Times Are Hard","Bringing it to God","Hab 3:17-18; Phil 4:6"),
  ]},
  {"roman":"II","title":"Though the Fig Tree","subtitle":"Rejoicing Without the Harvest","days":[
   (8,"Though the Fig Tree Doesn't Bud","Faith when there's nothing","Hab 3:17; Job 13:15"),
   (9,"No Grapes, No Olives","The barren season","Hab 3:17; Joel 1:10-12"),
   (10,"The Fields Produce No Food","Empty stalls","Hab 3:17; Ps 37:19"),
   (11,"Yet I Will Rejoice","The defiant choice","Hab 3:18; Phil 4:4"),
   (12,"Joy in God My Savior","Not in circumstances","Hab 3:18; Ps 43:4"),
   (13,"The Lord My Strength","He enables","Hab 3:19; Ps 18:32-33"),
   (14,"Though the Fig Tree","Rejoicing without the harvest","Hab 3:17-18; Phil 4:4"),
  ]},
  {"roman":"III","title":"The Secret of Content","subtitle":"Peace in Scarcity","days":[
   (15,"The Learned Secret","Content in want","Phil 4:11-12; 1 Tim 6:6"),
   (16,"In Plenty and in Need","Both seasons held","Phil 4:12; Phil 4:11"),
   (17,"I Can Do All This","Through Him who strengthens","Phil 4:13; 2 Cor 12:9"),
   (18,"Godliness With Contentment","Great gain","1 Tim 6:6; Ps 37:16"),
   (19,"Daily Bread Is Enough","Today's portion","Matt 6:11; Prov 30:8"),
   (20,"Never Will I Forsake You","The anchor","Heb 13:5; Deut 31:6"),
   (21,"The Secret of Content","Peace in scarcity","Phil 4:11-13; 1 Tim 6:6"),
  ]},
  {"roman":"IV","title":"Practical Wisdom","subtitle":"Stewardship in Scarcity","days":[
   (22,"Wise in Lean Times","Practical steps","Prov 21:5; Prov 6:6-8"),
   (23,"Trim and Simplify","Cutting back wisely","Prov 21:20; Luke 14:28"),
   (24,"The Ant in Hard Times","Foresight pays","Prov 6:6-8; Gen 41:35-36"),
   (25,"Prioritize the Essential","Needs over wants","Prov 30:8; Matt 6:31-33"),
   (26,"Seek First the Kingdom","Even in want","Matt 6:33; Luke 12:31"),
   (27,"Diligent and Trusting","Both at once","Prov 10:4; Ps 37:3"),
   (28,"Practical Wisdom","Stewardship in scarcity","Prov 21:5; Prov 6:6-8"),
  ]},
  {"roman":"V","title":"Rejoicing Anyway","subtitle":"Joy Beyond Circumstance","days":[
   (29,"Consider It Joy","In trials of many kinds","Jas 1:2-3; Rom 5:3-4"),
   (30,"Perseverance at Work","Trials produce it","Jas 1:3-4; Rom 5:3-4"),
   (31,"Rejoice in the Lord Always","A repeated call","Phil 4:4; 1 Thess 5:16"),
   (32,"The Joy of the Lord","Our strength","Neh 8:10; Ps 28:7"),
   (33,"Giving Thanks Anyway","Gratitude in hardship","1 Thess 5:18; Ps 34:1"),
   (34,"Hope That Holds","Sustained in trial","Rom 5:3-5; Ps 42:11"),
   (35,"Rejoicing Anyway","Joy beyond circumstance","Hab 3:18; Phil 4:4"),
  ]},
  {"roman":"VI","title":"Enduring Hard Times","subtitle":"Faithful and Rejoicing","days":[
   (36,"Endurance for the Lean","Steady through it","Jas 1:2-4; Rom 5:3-4"),
   (37,"In Famine, Plenty","God's strange provision","Ps 37:18-19; Ps 33:19"),
   (38,"This Too Will Pass","A season, not forever","Eccl 3:1; 2 Cor 4:17"),
   (39,"Refined, Not Ruined","Stronger through fire","1 Pet 1:6-7; Jas 1:3-4"),
   (40,"Enduring Hard Times","Faithful and rejoicing","Hab 3:17-18; Phil 4:11-13"),
  ]},
 ],
}
