# -*- coding: utf-8 -*-
"""Volume 2, Batch 3 — architecture blueprints, Groups 7-9:
Provision & Trust, Wisdom/Saving/Investing, Work/Income/Calling."""

DEF = ["4-Session", "6-Session", "21-Day", "30-Day", "40-Day"]
T1 = "Tier 1 — Church & Company"

GROUP_DESC = {
    "Provision & Trust":
        "Faith for the uncertain seasons \u2014 meeting the God who has fed His people through every famine, drought, and dry brook.",
    "Wisdom, Saving & Investing":
        "Scripture's deep well of financial wisdom \u2014 saving, investing, deciding, and avoiding the traps, with an eye on what lasts.",
    "Work, Income & Calling":
        "Where provision and purpose meet \u2014 daily work as worship, calling, and the honest, diligent earning of daily bread.",
}

ARCH = [
 # ---------------- PROVISION & TRUST ----------------
 {
  "num": 51, "group": "Provision & Trust",
  "title": "Daily Bread",
  "tagline": "Receiving God's Provision One Day at a Time",
  "tier": T1, "audience": "All Church \u00b7 Workplace Teams \u00b7 Daily Devotional",
  "core_ref": "Matthew 6:11 (NIV)",
  "core_text": "Give us today our daily bread.",
  "marketing": "We want the whole future secured today; God tends to provide one day at a time. This study returns to the manna in the wilderness and the prayer for daily bread, teaching the freeing rhythm of daily dependence \u2014 trusting God for today and letting tomorrow's bread come tomorrow.",
  "felt_need": "Anxiety about the long-term future when God seems to provide only for today.",
  "why_matters": "Jesus taught us to pray for daily bread \u2014 provision often comes one day at a time.",
  "problem": "We want years of security at once and resent the pace of daily dependence.",
  "transformation": "From demanding the whole future to receiving each day's bread with trust.",
  "formats": DEF,
  "sessions": [
   ("Manna in the Morning", "How God fed them daily"),
   ("Give Us This Day", "The prayer for daily bread"),
   ("Why Only Today?", "The purpose of daily dependence"),
   ("Tomorrow's Bread", "Leaving the future to God"),
   ("Gathering Enough", "Trusting there will be more"),
   ("A Daily Trust", "Living on daily provision"),
  ],
  "scriptures": ["Matthew 6:11", "Exodus 16:4", "Lamentations 3:22-23", "Matthew 6:34", "Proverbs 30:8"],
 },
 {
  "num": 52, "group": "Provision & Trust",
  "title": "The God Who Provides",
  "tagline": "Meeting Jehovah Jireh, the Lord Who Provides",
  "tier": T1, "audience": "All Church \u00b7 Small Groups \u00b7 Workplace Teams",
  "core_ref": "Genesis 22:14 (NIV)",
  "core_text": "So Abraham called that place The Lord Will Provide.",
  "marketing": "Long before there was a paycheck, there was a Provider. This study walks through the Bible's great stories of unexpected provision \u2014 the ram in the thicket, ravens at the brook, loaves multiplied \u2014 to introduce God by one of His oldest names: Jehovah Jireh, the Lord who provides.",
  "felt_need": "Knowing about God's provision in theory but not knowing Him as my Provider.",
  "why_matters": "Abraham named God \u201cThe Lord Will Provide\u201d \u2014 provision is part of who He is.",
  "problem": "We trust our income as provider and never come to know the real one.",
  "transformation": "From trusting the paycheck to knowing God as Jehovah Jireh.",
  "formats": DEF,
  "sessions": [
   ("The Ram in the Thicket", "Where the name was given"),
   ("Jehovah Jireh", "The Lord who provides"),
   ("Ravens and a Widow", "Provision in the dry season"),
   ("Loaves and Fish", "When little becomes enough"),
   ("The Provider's Character", "Why He delights to give"),
   ("Knowing Him as Provider", "Trusting the One who provides"),
  ],
  "scriptures": ["Genesis 22:13-14", "Philippians 4:19", "1 Kings 17:2-6", "Matthew 14:13-21", "Psalm 34:9-10"],
 },
 {
  "num": 53, "group": "Provision & Trust",
  "title": "When the Paycheck Stops",
  "tagline": "Faith and Practical Steps When Income Stops",
  "tier": T1, "audience": "All Church \u00b7 Those Facing Lost Income",
  "core_ref": "Psalm 37:25 (NIV)",
  "core_text": "I have never seen the righteous forsaken or their children begging bread.",
  "marketing": "Few seasons are as disorienting as the one when the income stops. This study walks gently into that hard place with both faith and practical help \u2014 steadying the heart, naming the next right steps, and pointing to the God who has fed His people in every famine, drought, and dry brook.",
  "felt_need": "The fear and disorientation of losing my income and not knowing what's next.",
  "why_matters": "God has provided for His people in every famine; He has not forgotten you now.",
  "problem": "Lost income shakes not just the budget but our whole sense of security.",
  "transformation": "From the panic of lost income to steady faith and clear next steps.",
  "formats": ["4-Session", "6-Session", "21-Day"],
  "sessions": [
   ("When It Stops", "The disorientation of lost income"),
   ("Never Forsaken", "God's promise in lean times"),
   ("Fed at the Brook", "Provision in the dry season"),
   ("The Next Right Step", "Practical moves that help"),
   ("Hope for the Season", "Faith while you wait"),
   ("Through to the Other Side", "Trusting God to provide"),
  ],
  "scriptures": ["Psalm 37:25", "Philippians 4:19", "1 Kings 17:8-16", "Matthew 6:31-33", "Isaiah 41:17"],
 },
 {
  "num": 54, "group": "Provision & Trust",
  "title": "Stepping Out in Faith",
  "tagline": "Obedience Before the Provision Is in Sight",
  "tier": T1, "audience": "All Church \u00b7 Workplace Teams \u00b7 Risk-Takers",
  "core_ref": "Joshua 3:13 (NIV)",
  "core_text": "As soon as the priests set foot in the Jordan, its waters will be cut off.",
  "marketing": "Sometimes God asks for the step before He shows the supply. This study is about that gap \u2014 the call to obey, give, or move before the provision is visible \u2014 and the priests at the Jordan whose feet had to touch the water before it parted. Faith often steps first; provision follows.",
  "felt_need": "Waiting for a guarantee before I'll obey, give, or take the risk God is asking.",
  "why_matters": "At the Jordan, the water parted only after their feet stepped in \u2014 faith goes first.",
  "problem": "We demand to see the provision before we'll take the step of obedience.",
  "transformation": "From waiting for guarantees to stepping out and trusting God to provide.",
  "formats": DEF,
  "sessions": [
   ("The Step Before the Supply", "When obedience comes first"),
   ("Feet in the Jordan", "Faith that moves first"),
   ("Abraham Went", "Obeying without the map"),
   ("The Risk of Obedience", "Trusting past the guarantee"),
   ("Provision Follows Faith", "What happens after the step"),
   ("Stepping Out", "Moving when God says go"),
  ],
  "scriptures": ["Joshua 3:13-17", "Hebrews 11:8", "2 Corinthians 5:7", "Matthew 14:28-29", "Proverbs 3:5-6"],
 },
 {
  "num": 55, "group": "Provision & Trust",
  "title": "He Knows Your Needs",
  "tagline": "The Quiet Confidence of a Father Who Knows",
  "tier": T1, "audience": "All Church \u00b7 Anxious Hearts \u00b7 Workplace Teams",
  "core_ref": "Matthew 6:8 (NIV)",
  "core_text": "Your Father knows what you need before you ask him.",
  "marketing": "You don't have to convince God of what you're facing \u2014 He already knows. This study rests in one quietly powerful truth: your Father knows what you need before you ask. It's an invitation to trade the exhausting work of worry for the confidence of being fully known and faithfully cared for.",
  "felt_need": "Feeling unseen, as if I must convince God of needs He hasn't noticed.",
  "why_matters": "Jesus said your Father knows what you need before you even ask Him.",
  "problem": "We carry needs as if everything depends on getting God's attention.",
  "transformation": "From anxious striving to the rest of being fully known and cared for.",
  "formats": DEF,
  "sessions": [
   ("Before You Ask", "The Father who already knows"),
   ("Fully Known", "Seen down to the detail"),
   ("The Worry We Can Drop", "Trusting His attention"),
   ("More Than Sparrows", "The value He places on you"),
   ("A Father's Care", "Why being known brings rest"),
   ("Quiet Confidence", "Resting in the One who knows"),
  ],
  "scriptures": ["Matthew 6:8", "Matthew 6:31-32", "Psalm 139:1-4", "1 Peter 5:7", "Luke 12:30"],
 },
 # ---------------- WISDOM, SAVING & INVESTING ----------------
 {
  "num": 56, "group": "Wisdom, Saving & Investing",
  "title": "Smart With Money",
  "tagline": "Practical, Scripture-Rooted Financial Smarts",
  "tier": T1, "audience": "All Church \u00b7 Workplace Teams \u00b7 Young Professionals",
  "core_ref": "Proverbs 13:16 (NIV)",
  "core_text": "All who are prudent act with knowledge, but fools expose their folly.",
  "marketing": "Wisdom isn't only lofty \u2014 it's practical, everyday smarts. This study mines Scripture for the kind of plain financial intelligence that prevents foolish moves and steadies daily decisions: act on knowledge, look ahead, avoid the obvious traps. It's being shrewd and faithful at the same time.",
  "felt_need": "Feeling naive or foolish with money and tired of making avoidable mistakes.",
  "why_matters": "Scripture says the prudent act with knowledge while fools expose their folly.",
  "problem": "We make money decisions on impulse and feeling instead of knowledge.",
  "transformation": "From naive and impulsive to prudent, knowledgeable, and smart with money.",
  "formats": DEF,
  "sessions": [
   ("Prudent or Naive", "Two ways to handle money"),
   ("Act on Knowledge", "Decisions rooted in wisdom"),
   ("Look Before You Leap", "Seeing what's ahead"),
   ("The Shrewd and Faithful", "Smart without being worldly"),
   ("Everyday Smarts", "Wisdom for daily choices"),
   ("Smart With Money", "Prudence as a way of life"),
  ],
  "scriptures": ["Proverbs 13:16", "Proverbs 14:15", "Proverbs 21:5", "Proverbs 27:12", "Luke 16:8"],
 },
 {
  "num": 57, "group": "Wisdom, Saving & Investing",
  "title": "The Wisdom of Saving",
  "tagline": "Why Saving Is an Act of Faith and Foresight",
  "tier": T1, "audience": "All Church \u00b7 Workplace Teams \u00b7 Every Budget",
  "core_ref": "Genesis 41:36 (NIV)",
  "core_text": "This food should be held in reserve for the country, to be used during the years of famine.",
  "marketing": "Some assume saving shows a lack of faith. Scripture says the opposite: storing up for the lean years is wisdom and foresight, the very thing that saved a nation through Joseph. This study reframes saving as an act of faith and teaches the habit of setting something aside before it's needed.",
  "felt_need": "Living with no cushion \u2014 and unsure whether saving even honors God.",
  "why_matters": "Joseph's storehouses saved nations; saving is foresight, not a lack of faith.",
  "problem": "We spend it all, then have nothing set aside when the lean year comes.",
  "transformation": "From no margin and mixed motives to saving as faithful foresight.",
  "formats": DEF,
  "sessions": [
   ("Is Saving Faithless?", "Clearing up the myth"),
   ("Joseph's Storehouses", "Saving that saved a nation"),
   ("Lessons From the Ant", "Storing before the need"),
   ("Building the Habit", "Setting something aside"),
   ("Saving With Open Hands", "Margin without hoarding"),
   ("The Wisdom of Saving", "Foresight as faithfulness"),
  ],
  "scriptures": ["Genesis 41:34-36", "Proverbs 21:20", "Proverbs 6:6-8", "Proverbs 13:11", "Proverbs 30:24-25"],
 },
 {
  "num": 58, "group": "Wisdom, Saving & Investing",
  "title": "Investing With Eternity in Mind",
  "tagline": "Stewarding What You Grow Toward What Lasts",
  "tier": T1, "audience": "All Church \u00b7 Workplace Teams \u00b7 Investors",
  "core_ref": "Matthew 6:20 (NIV)",
  "core_text": "Store up for yourselves treasures in heaven, where moths and vermin do not destroy.",
  "marketing": "Growing wealth isn't unspiritual \u2014 but it begs a bigger question: invested for what? This study lifts the eyes of the investor toward eternity, stewarding what you grow with one eye always on what truly lasts, and storing up treasure where neither markets nor moths can touch it.",
  "felt_need": "Wondering whether growing wealth has any eternal meaning at all.",
  "why_matters": "Jesus said to store up treasure in heaven \u2014 investing can serve what lasts.",
  "problem": "We grow wealth with no eternal aim, storing treasure that can't last.",
  "transformation": "From investing only for here to stewarding growth toward eternity.",
  "formats": DEF,
  "sessions": [
   ("Invested for What?", "The bigger question"),
   ("Treasure in Heaven", "Where it can't be lost"),
   ("The Eternal Portfolio", "Growth with lasting aim"),
   ("Using Worldly Wealth", "Investing for the kingdom"),
   ("Eyes on What Lasts", "Perspective that reshapes investing"),
   ("Investing for Eternity", "Stewarding growth that matters"),
  ],
  "scriptures": ["Matthew 6:19-21", "1 Timothy 6:17-19", "Luke 16:9", "2 Corinthians 4:18", "Colossians 3:1-2"],
 },
 {
  "num": 59, "group": "Wisdom, Saving & Investing",
  "title": "Avoiding Money Mistakes",
  "tagline": "Sidestepping the Money Traps Scripture Warns About",
  "tier": T1, "audience": "All Church \u00b7 Workplace Teams \u00b7 Every Budget",
  "core_ref": "Proverbs 22:3 (NIV)",
  "core_text": "The prudent see danger and take refuge, but the simple keep going and pay the penalty.",
  "marketing": "Scripture is full of warnings about money traps \u2014 co-signing, get-rich-quick, overspending, neglect. This study turns those warnings into wisdom, helping people see the danger and take refuge before they pay the penalty the simple always do. It's learning from mistakes you never have to make.",
  "felt_need": "Repeating costly money mistakes and the regret that follows them.",
  "why_matters": "The prudent see danger and take refuge; the simple keep going and pay.",
  "problem": "We walk into the same financial traps Scripture clearly warned us about.",
  "transformation": "From repeated costly mistakes to wisely sidestepping the traps.",
  "formats": DEF,
  "sessions": [
   ("See the Danger", "Spotting the trap ahead"),
   ("The Co-Signing Snare", "Warnings about pledges"),
   ("Get-Rich-Quick", "Why shortcuts backfire"),
   ("Spending Past Your Means", "The overspending trap"),
   ("The Cost of Neglect", "When ignoring it costs most"),
   ("Wise and Watchful", "Avoiding the penalty"),
  ],
  "scriptures": ["Proverbs 22:3", "Proverbs 27:12", "Proverbs 22:26-27", "Proverbs 28:19-20", "Proverbs 14:8"],
 },
 {
  "num": 60, "group": "Wisdom, Saving & Investing",
  "title": "Decisions, Decisions",
  "tagline": "A Biblical Framework for Big Money Choices",
  "tier": T1, "audience": "All Church \u00b7 Workplace Teams \u00b7 Decision-Makers",
  "core_ref": "James 1:5 (NIV)",
  "core_text": "If any of you lacks wisdom, you should ask God, who gives generously to all.",
  "marketing": "The house, the job, the major purchase \u2014 big money decisions can freeze us. This study offers a clear, biblical framework for making them with confidence and peace: ask God for wisdom, seek counsel, weigh it prayerfully, and move forward without second-guessing. Big choices, settled with peace.",
  "felt_need": "Anxiety and paralysis when facing big, weighty financial decisions.",
  "why_matters": "Scripture says if we lack wisdom, we can ask God, who gives it generously.",
  "problem": "Big decisions overwhelm us, so we stall, rush, or second-guess endlessly.",
  "transformation": "From paralyzed and anxious to deciding with wisdom and peace.",
  "formats": DEF,
  "sessions": [
   ("The Weight of Big Choices", "Why they freeze us"),
   ("Ask God for Wisdom", "The first move in any decision"),
   ("The Wisdom of Counsel", "Many advisers bring safety"),
   ("Weighing It Prayerfully", "Discerning the right path"),
   ("Moving Without Regret", "Deciding and not looking back"),
   ("Decisions With Peace", "Confidence in big choices"),
  ],
  "scriptures": ["James 1:5", "Proverbs 3:5-6", "Proverbs 15:22", "Proverbs 11:14", "Psalm 32:8"],
 },
 {
  "num": 61, "group": "Wisdom, Saving & Investing",
  "title": "The Patient Path to Wealth",
  "tagline": "Why Little-by-Little Beats Get-Rich-Quick",
  "tier": T1, "audience": "All Church \u00b7 Workplace Teams \u00b7 Long-Term Builders",
  "core_ref": "Proverbs 13:11 (NIV)",
  "core_text": "Dishonest money dwindles away, but whoever gathers money little by little makes it grow.",
  "marketing": "Every generation has its shortcut to riches, and every generation watches them collapse. This study makes the biblical case for the slow road: wealth gathered little by little grows, while quick money dwindles away. It's a study in patience, consistency, and the quiet power of the long game.",
  "felt_need": "Tempted by shortcuts and schemes while honest progress feels painfully slow.",
  "why_matters": "Scripture says money gathered little by little grows; quick money dwindles.",
  "problem": "We chase fast money and lose, instead of trusting slow, steady growth.",
  "transformation": "From chasing shortcuts to the patient, steady path that actually builds.",
  "formats": DEF,
  "sessions": [
   ("The Shortcut Temptation", "Why quick money calls"),
   ("Little by Little", "How wealth actually grows"),
   ("Money That Dwindles", "Why schemes collapse"),
   ("The Power of Patience", "Consistency over time"),
   ("The Long Game", "Trusting slow growth"),
   ("The Patient Path", "Building wealth God's way"),
  ],
  "scriptures": ["Proverbs 13:11", "Proverbs 28:20", "Proverbs 28:22", "Proverbs 21:5", "Ecclesiastes 5:13-15"],
 },
 {
  "num": 62, "group": "Wisdom, Saving & Investing",
  "title": "Counting the Cost",
  "tagline": "Planning the Real Cost Before You Commit",
  "tier": T1, "audience": "All Church \u00b7 Workplace Teams \u00b7 Big-Purchase Planners",
  "core_ref": "Luke 14:28 (NIV)",
  "core_text": "Suppose one of you wants to build a tower. Won't you first sit down and estimate the cost?",
  "marketing": "Jesus pointed to a builder who started a tower he couldn't finish \u2014 and asked why anyone wouldn't first sit down and count the cost. This study applies that wisdom to money: pricing the true, total cost of a commitment before signing, so we finish what we start instead of stalling halfway.",
  "felt_need": "Jumping into purchases and commitments without counting the true cost first.",
  "why_matters": "Jesus said to sit down first and estimate the cost before building.",
  "problem": "We commit on excitement and discover the real cost only when it's too late.",
  "transformation": "From leaping before looking to counting the full cost before committing.",
  "formats": DEF,
  "sessions": [
   ("The Unfinished Tower", "Starting what we can't finish"),
   ("Sit Down First", "The wisdom of estimating"),
   ("The True Total Cost", "Counting more than the price"),
   ("Hidden and Ongoing Costs", "What we forget to add"),
   ("Finish What You Start", "Committing only when ready"),
   ("Counting the Cost", "Wisdom before the commitment"),
  ],
  "scriptures": ["Luke 14:28-30", "Proverbs 24:27", "Proverbs 20:25", "Proverbs 21:5", "Luke 14:31-33"],
 },
 # ---------------- WORK, INCOME & CALLING ----------------
 {
  "num": 63, "group": "Work, Income & Calling",
  "title": "Working as Worship",
  "tagline": "Daily Work as Worship, Your Paycheck as Provision",
  "tier": T1, "audience": "All Church \u00b7 Workplace Teams \u00b7 Every Vocation",
  "core_ref": "Colossians 3:23 (NIV)",
  "core_text": "Whatever you do, work at it with all your heart, as working for the Lord.",
  "marketing": "Most people split life into Sunday worship and Monday work. Scripture refuses the divide: whatever you do, do it for the Lord. This study transforms ordinary work into worship and reframes the paycheck as God's provision through your hands \u2014 making the daily grind sacred ground.",
  "felt_need": "Seeing work as secular drudgery, disconnected from my faith and worship.",
  "why_matters": "Scripture says whatever we do, we work at it for the Lord \u2014 work can be worship.",
  "problem": "We divide sacred and secular, and most of our week falls on the wrong side.",
  "transformation": "From clocking in at a secular job to working as worship for the Lord.",
  "formats": DEF,
  "sessions": [
   ("The Sacred-Secular Divide", "Why we split work and faith"),
   ("As Working for the Lord", "Reframing every task"),
   ("Worship at the Desk", "Making work an offering"),
   ("The Paycheck as Provision", "God providing through hands"),
   ("Excellence as Offering", "Why how we work matters"),
   ("Working as Worship", "The sacred in the ordinary"),
  ],
  "scriptures": ["Colossians 3:23-24", "1 Corinthians 10:31", "Ephesians 6:7", "Genesis 2:15", "1 Corinthians 15:58"],
 },
 {
  "num": 64, "group": "Work, Income & Calling",
  "title": "Faith on the Job",
  "tagline": "Living Your Faith Where You Earn Your Living",
  "tier": T1, "audience": "All Church \u00b7 Workplace Teams \u00b7 Marketplace Christians",
  "core_ref": "Matthew 5:16 (NIV)",
  "core_text": "Let your light shine before others, that they may see your good deeds.",
  "marketing": "Your workplace may be the one mission field you visit every single day. This study is about living out faith there with integrity and purpose \u2014 letting your light shine through honest work and genuine character, without being preachy or compromised. Real faith, lived where you earn your living.",
  "felt_need": "Unsure how to live my faith authentically at work without being preachy.",
  "why_matters": "Jesus said to let our light shine so others see our good deeds at work.",
  "problem": "We leave faith at the door or wear it awkwardly, and witness suffers either way.",
  "transformation": "From compartmentalized faith to a quiet, genuine witness on the job.",
  "formats": DEF,
  "sessions": [
   ("Your Daily Mission Field", "Where faith gets lived"),
   ("Let Your Light Shine", "Witness through good work"),
   ("Integrity Under Pressure", "Faith when it's costly"),
   ("Words and Conduct", "Speaking faith with grace"),
   ("The Daniel Standard", "Excellence that opens doors"),
   ("Faith on the Job", "Living it where you work"),
  ],
  "scriptures": ["Matthew 5:16", "1 Peter 2:12", "Colossians 4:5-6", "Titus 2:9-10", "Daniel 6:3-4"],
 },
 {
  "num": 65, "group": "Work, Income & Calling",
  "title": "Your Work, God's Provision",
  "tagline": "How God Provides Through the Dignity of Work",
  "tier": T1, "audience": "All Church \u00b7 Workplace Teams \u00b7 Every Vocation",
  "core_ref": "Psalm 128:2 (NIV)",
  "core_text": "You will eat the fruit of your labor; blessings and prosperity will be yours.",
  "marketing": "When we pray for provision, we often picture a miracle. More often, God provides through the dignity of ordinary work. This study connects the labor of our hands to the provision of God, restoring honor to honest work and gratitude for the daily bread it earns.",
  "felt_need": "Struggling to see ordinary work as connected to God's provision.",
  "why_matters": "Scripture says you will eat the fruit of your labor \u2014 work is how God often provides.",
  "problem": "We either idolize our work or dismiss it, missing it as God's provision channel.",
  "transformation": "From undervaluing work to honoring it as the means God provides through.",
  "formats": DEF,
  "sessions": [
   ("The Fruit of Your Labor", "Provision through work"),
   ("Dignity in Work", "Why labor is honored"),
   ("Not the Source, the Channel", "God provides through it"),
   ("Remember Who Gives", "The Lord behind the ability"),
   ("Gratitude for Daily Work", "Thanking God for the means"),
   ("Your Work, His Provision", "Labor and the God who provides"),
  ],
  "scriptures": ["Psalm 128:1-2", "2 Thessalonians 3:10", "Genesis 3:19", "Proverbs 14:23", "Deuteronomy 8:17-18"],
 },
 {
  "num": 66, "group": "Work, Income & Calling",
  "title": "The Side Hustle and the Soul",
  "tagline": "Extra Income Without Losing Your Heart",
  "tier": T1, "audience": "All Church \u00b7 Workplace Teams \u00b7 Side-Hustlers",
  "core_ref": "Ecclesiastes 4:6 (NIV)",
  "core_text": "Better one handful with tranquility than two handfuls with toil and chasing after the wind.",
  "marketing": "Extra income can be a real blessing \u2014 or a quiet thief of your time, rest, and heart. This study helps people pursue the side hustle without letting it take over, weighing the cost of two handfuls and toil against one handful with peace, and guarding the soul while growing the income.",
  "felt_need": "Chasing extra income while my time, rest, and heart quietly pay the price.",
  "why_matters": "Scripture warns that two handfuls with toil can cost more than they're worth.",
  "problem": "The hustle expands until it crowds out rest, relationships, and faith.",
  "transformation": "From hustle that consumes the soul to extra income held in its place.",
  "formats": DEF,
  "sessions": [
   ("The Promise of More", "Why the hustle appeals"),
   ("Two Handfuls and Toil", "Counting the real cost"),
   ("What It's Quietly Taking", "The hidden price of hustle"),
   ("Guarding the Soul", "Keeping the heart intact"),
   ("Rest as Resistance", "Why Sabbath matters here"),
   ("Hustle in Its Place", "Income without losing yourself"),
  ],
  "scriptures": ["Ecclesiastes 4:6", "Mark 8:36", "Luke 12:15", "1 Timothy 6:9-10", "Matthew 11:28-30"],
 },
 {
  "num": 67, "group": "Work, Income & Calling",
  "title": "Earning With Integrity",
  "tagline": "Honest Scales and Clean Hands in How You Earn",
  "tier": T1, "audience": "All Church \u00b7 Workplace Teams \u00b7 Business & Sales",
  "core_ref": "Proverbs 11:1 (NIV)",
  "core_text": "The Lord detests dishonest scales, but accurate weights find favor with him.",
  "marketing": "How we make money matters as much to God as how we spend it. This study calls for honest scales and clean hands in earning \u2014 no cut corners, no shady deals, no fudged numbers \u2014 because the Lord detests dishonest scales but delights in those whose gain is clean.",
  "felt_need": "Tempted to cut corners or fudge numbers to earn a little more.",
  "why_matters": "The Lord detests dishonest scales but favors accurate, honest weights.",
  "problem": "Pressure to earn tempts us to compromise honesty in small, costly ways.",
  "transformation": "From cutting corners to earning with honest scales and clean hands.",
  "formats": DEF,
  "sessions": [
   ("How We Earn Matters", "Integrity at the source"),
   ("Honest Scales", "What God detests and delights in"),
   ("The Small Compromises", "Where integrity slips"),
   ("Clean Hands at Work", "Earning without shame"),
   ("Trustworthy With Money", "Faithful in how we gain"),
   ("Earning With Integrity", "Clean gain, clear conscience"),
  ],
  "scriptures": ["Proverbs 11:1", "Proverbs 16:11", "Leviticus 19:35-36", "Proverbs 13:11", "Luke 16:10-11"],
 },
 {
  "num": 68, "group": "Work, Income & Calling",
  "title": "Called to Your Career",
  "tagline": "Discovering the Calling Woven Into Your Work",
  "tier": T1, "audience": "All Church \u00b7 Workplace Teams \u00b7 Purpose-Seekers",
  "core_ref": "Ephesians 2:10 (NIV)",
  "core_text": "For we are God's handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do.",
  "marketing": "Is your job just a paycheck, or is there a calling woven through it? This study helps people discover purpose in their work, seeing themselves as God's handiwork created for good works He prepared in advance. It turns a career into a calling and a job into a place of meaning.",
  "felt_need": "Feeling like my work is just a paycheck, with no real meaning or calling.",
  "why_matters": "We are God's handiwork, created for good works He prepared in advance for us.",
  "problem": "We separate calling from career and treat most of our work as meaningless.",
  "transformation": "From a job that's just a paycheck to a career lived as a calling.",
  "formats": DEF,
  "sessions": [
   ("Job or Calling?", "More than a paycheck"),
   ("God's Handiwork", "Created with purpose"),
   ("Works Prepared in Advance", "Calling woven into work"),
   ("Where You Are", "Calling in your current job"),
   ("Meaning in the Mundane", "Purpose in ordinary work"),
   ("Called to Your Career", "Living work as calling"),
  ],
  "scriptures": ["Ephesians 2:10", "Colossians 3:23-24", "1 Corinthians 7:17", "Romans 12:6-8", "Ecclesiastes 9:10"],
 },
 {
  "num": 69, "group": "Work, Income & Calling",
  "title": "The Diligent Hand",
  "tagline": "The Link Between Diligence and Provision",
  "tier": T1, "audience": "All Church \u00b7 Workplace Teams \u00b7 Every Vocation",
  "core_ref": "Proverbs 10:4 (NIV)",
  "core_text": "Lazy hands make for poverty, but diligent hands bring wealth.",
  "marketing": "Scripture draws a steady line between diligence and provision: lazy hands make for poverty, but diligent hands bring wealth. This study explores the dignity of hard work, the quiet cost of neglect, and the way faithful diligence positions us to receive what God provides.",
  "felt_need": "Battling laziness or neglect, or discouraged that hard work isn't paying off.",
  "why_matters": "Scripture links diligent hands to provision and slack hands to poverty.",
  "problem": "We hope for provision while neglecting the diligent work it usually flows through.",
  "transformation": "From slack or discouraged hands to faithful, diligent, fruitful work.",
  "formats": DEF,
  "sessions": [
   ("Two Kinds of Hands", "Diligent versus slack"),
   ("The Cost of Neglect", "What laziness quietly costs"),
   ("Diligence and Provision", "The link Scripture draws"),
   ("Faithful in the Work", "Showing up consistently"),
   ("When Diligence Feels Vain", "Trusting the long return"),
   ("The Diligent Hand", "Work that bears fruit"),
  ],
  "scriptures": ["Proverbs 10:4", "Proverbs 12:11", "Proverbs 13:4", "Proverbs 21:5", "2 Thessalonians 3:10-12"],
 },
]
