# -*- coding: utf-8 -*-
# Finances Campaign Catalog — Top 10, campaigns 6-10
# Each "movements" list groups the 40 days into 6 thematic movements (7,7,7,7,7,5).

TOP10_B = [
{
 "num": 6,
 "title": "Enough",
 "tagline": "Finding Contentment in a Culture of More",
 "positioning": "A 40-day journey out of the exhausting chase for more and into the quiet, durable freedom of contentment — learning the secret Paul knew in plenty and in want.",
 "felt_need": "The restless ache of never having enough, comparison, and the sense that satisfaction is always one purchase away.",
 "audience": "All church · Workplace teams · Anyone worn out by the chase for more",
 "tier": "Tier 1 — Church & Company",
 "core_ref": "Philippians 4:11-13 (NIV)",
 "core_text": "I have learned to be content whatever the circumstances. I know what it is to be in need, and I know what it is to have plenty.",
 "marketing": "We live inside a machine engineered to keep us wanting. Every screen, every ad, every feed is built to make the life we have feel like it is not quite enough. The result is a low, constant restlessness that no raise and no purchase ever fully quiets. This campaign offers a way out. It walks a congregation through the counter-cultural secret Paul learned in a prison cell — that contentment is not a circumstance to wait for but a skill to be learned — and rebuilds daily life around a startling possibility: that what you already have, in Christ, is genuinely enough.",
 "why_matters": "Discontent is the engine behind overspending, debt, envy, and money fights. Learn contentment, and a dozen financial problems lose their fuel.",
 "problem": "We have been trained to feel that more is always needed, so we never arrive at enough.",
 "transformation": "From the never-enough chase to the learned, settled contentment Paul describes; from comparison to gratitude.",
 "formats": ["4-Session", "6-Session", "21-Day", "30-Day", "40-Day"],
 "sessions": [
   ("The Never-Enough Trap", "Why more never satisfies"),
   ("The Secret of Contentment", "What Paul learned that we can learn too"),
   ("Godliness With Contentment", "The great gain hidden in enough"),
   ("Breaking the Comparison Habit", "Escaping the thief of joy"),
   ("Simplicity and Freedom", "Lightening the load of more"),
   ("The Contented Life", "A heart finally at rest"),
 ],
 "scriptures": ["Philippians 4:11-13", "1 Timothy 6:6-10", "Hebrews 13:5", "Ecclesiastes 5:10", "Luke 12:15-21", "Proverbs 30:7-9"],
 "movements": [
  {"roman":"I","title":"The Never-Enough Trap","subtitle":"Why More Never Satisfies","days":[
    (1,"The Restless Ache","Naming the hunger that never fills","Eccl 5:10; Eccl 1:8"),
    (2,"Engineered to Want","How culture keeps us craving","1 John 2:16; Rom 12:2"),
    (3,"The Moving Finish Line","Why enough keeps retreating","Eccl 4:8; Prov 27:20"),
    (4,"The Cost of More","What the chase quietly takes","Luke 12:15; Mark 8:36"),
    (5,"Treasure That Rusts","Storing up the wrong things","Matt 6:19-21; Jas 5:1-3"),
    (6,"The Rich Fool","A barn-builder who missed it","Luke 12:16-21; Ps 39:6"),
    (7,"Honest Before God","Admitting the discontent","Ps 139:23-24; Phil 4:6"),
  ]},
  {"roman":"II","title":"The Secret of Contentment","subtitle":"What Paul Learned","days":[
    (8,"A Learned Secret","Contentment is a skill, not a mood","Phil 4:11-12; 1 Tim 6:6"),
    (9,"In Plenty and in Want","Steady in every circumstance","Phil 4:12; 2 Cor 6:10"),
    (10,"Strength for the Struggle","The source that makes it possible","Phil 4:13; Isa 40:29"),
    (11,"Enough in Christ","Why He is the real supply","Col 2:9-10; Ps 73:25-26"),
    (12,"The Gratitude Shift","Counting what is already given","1 Thess 5:18; Ps 103:2"),
    (13,"Daily Sufficiency","Receiving today's portion","Lam 3:22-23; Matt 6:11"),
    (14,"Rest for the Restless","Trading striving for trust","Matt 11:28-30; Ps 23:1"),
  ]},
  {"roman":"III","title":"Godliness With Contentment","subtitle":"The Great Gain","days":[
    (15,"Great Gain","The profit hidden in enough","1 Tim 6:6; Prov 15:16"),
    (16,"We Brought Nothing","Coming and going empty-handed","1 Tim 6:7; Job 1:21"),
    (17,"Food and Covering","Redefining what we truly need","1 Tim 6:8; Prov 30:8"),
    (18,"The Snare of Wanting","Where craving leads","1 Tim 6:9; Prov 28:22"),
    (19,"The Root of Trouble","Loving money and its griefs","1 Tim 6:10; Heb 13:5"),
    (20,"Never Will I Forsake","The promise that frees us","Heb 13:5-6; Deut 31:6"),
    (21,"Rich in Good Deeds","Where the wealthy invest","1 Tim 6:17-19; Luke 12:33"),
  ]},
  {"roman":"IV","title":"Breaking Comparison","subtitle":"The Thief of Joy","days":[
    (22,"The Comparison Trap","Measuring against everyone else","Gal 6:4; 2 Cor 10:12"),
    (23,"The Highlight Reel","Envy fed by what we see","Prov 14:30; Ps 73:3"),
    (24,"Your Own Race","Running your assigned lane","Heb 12:1; Gal 6:4-5"),
    (25,"The Tenth Commandment","Why God forbids coveting","Exod 20:17; Rom 7:7"),
    (26,"Rejoicing With Others","Celebrating instead of envying","Rom 12:15; 1 Cor 13:4"),
    (27,"Content in Your Calling","Faithful where you're planted","1 Cor 7:17; Phil 4:11"),
    (28,"Eyes on the Giver","Looking up, not sideways","Heb 12:2; Ps 121:1-2"),
  ]},
  {"roman":"V","title":"Simplicity and Freedom","subtitle":"Lightening the Load","days":[
    (29,"The Weight of Stuff","What possessions quietly cost","Luke 12:15; Matt 6:25"),
    (30,"Travel Light","Holding things loosely","Matt 6:19-21; 1 Tim 6:7"),
    (31,"Give Me Neither","The prayer for just enough","Prov 30:7-9; Matt 6:11"),
    (32,"Less to Manage","Freedom in fewer things","Eccl 5:12; Ps 131:1-2"),
    (33,"Margin and Rest","Room to breathe again","Exod 20:8-10; Mark 6:31"),
    (34,"Generosity From Simplicity","What enough frees you to give","2 Cor 8:2-4; Acts 2:45"),
    (35,"The Unburdened Life","Lighter because content","Heb 12:1; Phil 4:12"),
  ]},
  {"roman":"VI","title":"The Contented Life","subtitle":"A Heart at Rest","days":[
    (36,"My Cup Overflows","Seeing how full life already is","Ps 23:5-6; Ps 16:5-6"),
    (37,"Enough for Today","Trusting tomorrow to God","Matt 6:34; Lam 3:23"),
    (38,"The Secret, Kept","Practicing contentment daily","Phil 4:11-12; 1 Tim 6:6"),
    (39,"Rich Toward God","The wealth that truly lasts","Luke 12:21; Matt 6:20"),
    (40,"Finally, Enough","A settled, grateful heart","Phil 4:13; Ps 73:25-26"),
  ]},
 ],
},
{
 "num": 7,
 "title": "Trusting God to Provide",
 "tagline": "Faith for Every Need, in Every Season",
 "positioning": "A 40-day journey for anyone facing real financial uncertainty — job loss, a gap, an unknown future — moving from gripping anxiety to active, daily trust in the God who provides.",
 "felt_need": "Uncertainty about provision, fear of the gap between need and supply, and the question of whether God will really come through.",
 "audience": "All church · Workplace teams · Anyone facing financial uncertainty or transition",
 "tier": "Tier 1 — Church & Company",
 "core_ref": "Philippians 4:19 (NIV)",
 "core_text": "And my God will meet all your needs according to the riches of his glory in Christ Jesus.",
 "marketing": "There is a particular kind of fear that comes when the math does not work — when the job ends, the bill arrives, or the future refuses to come into focus. In those seasons, trusting God to provide stops being a sermon illustration and becomes the only ground left to stand on. This campaign walks a congregation through the long biblical story of provision: the God who is called Jehovah Jireh, who sent manna in a desert and bread through a widow's hands, who fed five thousand from a boy's lunch. It does not promise an easy life. It builds the kind of faith that can keep walking when provision is still on the way.",
 "why_matters": "Financial fear isolates people and erodes faith. A congregation grounded in God's track record of provision can face uncertainty with courage instead of panic.",
 "problem": "When provision is uncertain, fear takes the wheel and faith goes quiet.",
 "transformation": "From anxious self-reliance to active trust; from \"how will this work?\" to \"He has always provided.\"",
 "formats": ["4-Session", "6-Session", "21-Day", "30-Day", "40-Day"],
 "sessions": [
   ("The God Who Provides", "Meeting Jehovah Jireh"),
   ("Give Us This Day", "Learning to receive daily bread"),
   ("Seek First", "The promise behind the priority"),
   ("In the Wilderness", "Trusting God in the gap"),
   ("Stepping Out in Faith", "Obedience before provision is visible"),
   ("A Lifetime of Faithfulness", "Looking back to walk forward"),
 ],
 "scriptures": ["Philippians 4:19", "Matthew 6:25-34", "Genesis 22:14", "Exodus 16:4", "1 Kings 17:13-16", "Psalm 37:25"],
 "movements": [
  {"roman":"I","title":"The Provider","subtitle":"Meeting Jehovah Jireh","days":[
    (1,"The Lord Will Provide","The name revealed on a mountain","Gen 22:13-14; Phil 4:19"),
    (2,"He Already Knows","Your needs before you ask","Matt 6:8; Ps 139:1-4"),
    (3,"The Father's Care","More than the birds and lilies","Matt 6:25-30; Luke 12:24"),
    (4,"Good Gifts","A Father who gives well","Matt 7:9-11; Jas 1:17"),
    (5,"Owner of Everything","His resources have no limit","Ps 50:10-12; Hag 2:8"),
    (6,"Riches in Glory","The measure of His supply","Phil 4:19; Eph 3:20"),
    (7,"Naming Your Need","Bringing it honestly to Him","Phil 4:6; 1 Pet 5:7"),
  ]},
  {"roman":"II","title":"Daily Bread","subtitle":"Learning to Receive","days":[
    (8,"Bread From Heaven","Manna in the morning","Exod 16:4,14-15; Neh 9:15"),
    (9,"Enough for Today","Gathering only the day's portion","Exod 16:16-18; Matt 6:11"),
    (10,"Do Not Hoard","Trusting tomorrow to come","Exod 16:19-20; Matt 6:34"),
    (11,"New Every Morning","Mercies that never run dry","Lam 3:22-23; Ps 90:14"),
    (12,"The Widow's Jar","Oil and flour that did not fail","1 Kgs 17:13-16; 2 Kgs 4:1-7"),
    (13,"Fed by Ravens","Provision from unexpected places","1 Kgs 17:2-6; Ps 147:9"),
    (14,"Give Us This Day","Praying for daily provision","Matt 6:11; Prov 30:8"),
  ]},
  {"roman":"III","title":"Seek First","subtitle":"The Promise Behind the Priority","days":[
    (15,"Do Not Worry","The command beneath the comfort","Matt 6:25,31; Phil 4:6"),
    (16,"The Pagans Run After","A different way to live","Matt 6:32; 1 Pet 1:14"),
    (17,"Seek First the Kingdom","Where to put your energy","Matt 6:33; Col 3:1-2"),
    (18,"All These Things","The promise attached to seeking","Matt 6:33; Ps 34:9-10"),
    (19,"Treasure and Heart","Following the money to the soul","Matt 6:19-21; Luke 12:34"),
    (20,"One Master","Why divided trust fails","Matt 6:24; Josh 24:15"),
    (21,"Today's Trouble","Letting tomorrow keep its worries","Matt 6:34; Prov 27:1"),
  ]},
  {"roman":"IV","title":"In the Wilderness","subtitle":"Trusting God in the Gap","days":[
    (22,"The Long Way","When God leads through the desert","Deut 8:2; Exod 13:17-18"),
    (23,"Humbled and Tested","What the wilderness reveals","Deut 8:2-3; Jas 1:2-4"),
    (24,"He Sustained You","Clothes and feet that held up","Deut 8:4; Neh 9:21"),
    (25,"Man Does Not Live by Bread","A deeper kind of provision","Deut 8:3; Matt 4:4"),
    (26,"The Valley of Provision","Shepherded through the dark","Ps 23:1-4; Ps 34:18"),
    (27,"Waiting on the Lord","Strength for the delay","Isa 40:31; Ps 27:14"),
    (28,"Remember the Lord","Crediting God when it comes","Deut 8:17-18; Ps 103:2"),
  ]},
  {"roman":"V","title":"Stepping Out","subtitle":"Obedience Before Provision Is Visible","days":[
    (29,"Feed Them","Provision through obedience","John 6:5-13; Mark 6:37"),
    (30,"A Boy's Lunch","God multiplies the little we bring","John 6:9-11; 2 Kgs 4:42-44"),
    (31,"Twelve Baskets Left","More than enough remains","John 6:12-13; 2 Cor 9:8"),
    (32,"Launch Into the Deep","Trusting the word over the odds","Luke 5:4-7; Prov 3:5-6"),
    (33,"Bring It First","Giving before you can see how","1 Kgs 17:13; Mal 3:10"),
    (34,"Sowing in Faith","Provision follows obedience","2 Cor 9:6-10; Gal 6:7-9"),
    (35,"The First Step","Acting on what God said","Josh 3:13-17; Heb 11:8"),
  ]},
  {"roman":"VI","title":"A Lifetime of Faithfulness","subtitle":"Looking Back to Walk Forward","days":[
    (36,"Never Seen Them Forsaken","A lifetime of evidence","Ps 37:25; Josh 1:5"),
    (37,"Raise Your Ebenezer","Marking where God helped","1 Sam 7:12; Ps 77:11"),
    (38,"His Faithfulness Endures","A track record to trust","Ps 100:5; Lam 3:23"),
    (39,"He Who Began a Work","Confidence He will finish","Phil 1:6; 1 Thess 5:24"),
    (40,"Jehovah Jireh, Still","Walking forward in trust","Gen 22:14; Phil 4:19"),
  ]},
 ],
},
{
 "num": 8,
 "title": "Money & Marriage",
 "tagline": "From Financial Conflict to Financial Unity",
 "positioning": "A 40-day journey for couples that turns money from the number-one source of marital conflict into a place of partnership, transparency, and shared mission.",
 "felt_need": "Recurring money fights, hidden spending, mismatched styles, and the loneliness of not being on the same page.",
 "audience": "Married couples · Engaged couples · Church marriage ministries",
 "tier": "Tier 1 — Church & Company",
 "core_ref": "Amos 3:3 (NIV)",
 "core_text": "Do two walk together unless they have agreed to do so?",
 "marketing": "Money is consistently named as the leading source of conflict in marriage, and the leading predictor of divorce. The arguments are rarely really about the dollars; they are about trust, fear, control, and competing dreams. This campaign helps couples stop fighting about money and start building with it. Rooted in the biblical vision of two becoming one, it walks husbands and wives through honest conversation, shared vision, and a single financial plan they own together — turning the most common battleground in marriage into one of its deepest sources of partnership.",
 "why_matters": "Healthy marriages strengthen families, churches, and workplaces. Helping couples unite around money protects relationships at their most vulnerable point.",
 "problem": "Two people with different money histories and habits try to walk together without ever agreeing on the path.",
 "transformation": "From two separate, secret money lives to one transparent, shared plan; from conflict to partnership.",
 "formats": ["4-Session", "6-Session", "21-Day", "30-Day", "40-Day"],
 "sessions": [
   ("Why Money Divides Us", "Naming the real conflict beneath the dollars"),
   ("One Flesh, One Finances", "The theology of shared money"),
   ("Different by Design", "Turning opposite styles into strengths"),
   ("A Plan We Both Own", "Building one budget together"),
   ("Generous Together", "Giving as a united couple"),
   ("A United Financial Future", "Dreaming and planning as one"),
 ],
 "scriptures": ["Amos 3:3", "Genesis 2:24", "Ecclesiastes 4:9-12", "Philippians 2:2-4", "1 Corinthians 1:10", "Proverbs 31:10-31"],
 "movements": [
  {"roman":"I","title":"Why Money Divides","subtitle":"The Real Conflict","days":[
    (1,"The Number-One Fight","Naming money as the battleground","Amos 3:3; Jas 4:1"),
    (2,"It's Not About Money","The trust beneath the tension","Prov 4:23; Luke 6:45"),
    (3,"Two Money Histories","The stories you each brought","Prov 22:6; Ps 139:13-16"),
    (4,"Fear and Control","What drives the conflict","1 John 4:18; Phil 4:6"),
    (5,"Secrets and Trust","The cost of financial hiding","Eph 4:25; Luke 8:17"),
    (6,"Speaking the Truth in Love","Honest, gentle conversation","Eph 4:15; Prov 15:1"),
    (7,"A Fresh Start","Forgiving past money wounds","Col 3:13; Eph 4:32"),
  ]},
  {"roman":"II","title":"One Flesh, One Finances","subtitle":"The Theology of Shared Money","days":[
    (8,"Two Become One","Unity as the design","Gen 2:24; Matt 19:5-6"),
    (9,"What's Mine Is Ours","From separate to shared","Acts 4:32; 1 Cor 7:4"),
    (10,"Of One Mind","Agreeing together in purpose","Phil 2:2; 1 Cor 1:10"),
    (11,"No Longer Two","Tearing down the ledger between you","Mark 10:8; Eph 5:31"),
    (12,"Submitting to One Another","Mutual honor with money","Eph 5:21; Phil 2:3-4"),
    (13,"A Cord of Three Strands","God at the center of it","Eccl 4:12; Ps 127:1"),
    (14,"One Plan, One Team","Deciding to manage as one","Amos 3:3; Eccl 4:9"),
  ]},
  {"roman":"III","title":"Different by Design","subtitle":"Opposite Styles, One Team","days":[
    (15,"Saver and Spender","Why opposites often marry","1 Cor 12:18-20; Rom 12:4-6"),
    (16,"Strength in Difference","Two views see more clearly","Eccl 4:9-10; Prov 27:17"),
    (17,"Honoring Your Spouse's Wiring","Valuing the other's bent","Phil 2:3; Rom 12:10"),
    (18,"Listening First","Understanding before persuading","Jas 1:19; Prov 18:13"),
    (19,"Compromise in Christ","Meeting in the middle","Phil 2:4; Rom 14:19"),
    (20,"The Capable Partner","Honoring a spouse's gifts","Prov 31:10-12; Prov 31:16"),
    (21,"Better Together","Two are better than one","Eccl 4:9-12; Gen 2:18"),
  ]},
  {"roman":"IV","title":"A Shared Plan","subtitle":"One Budget, Built Together","days":[
    (22,"On the Same Page","Why a shared plan matters","Amos 3:3; Prov 21:5"),
    (23,"The Money Date","A regular time to talk numbers","Prov 24:3-4; Luke 14:28"),
    (24,"Naming Our Goals","Dreaming with a purpose","Prov 16:3,9; Hab 2:2"),
    (25,"One Page, Two Names","A budget you both own","Prov 27:23-24; 2 Cor 8:21"),
    (26,"Agreed Boundaries","Spending limits you both set","Prov 25:28; 1 Cor 14:40"),
    (27,"Tackling Debt Together","Facing the load as a team","Prov 22:7; Rom 13:8"),
    (28,"Reviewing as One","Adjusting the plan together","Prov 27:23; Phil 4:9"),
  ]},
  {"roman":"V","title":"Generous Together","subtitle":"Giving as One","days":[
    (29,"A Giving Marriage","Generosity as a shared value","2 Cor 9:7; Acts 20:35"),
    (30,"Deciding Together","Agreeing how you'll give","2 Cor 9:7; 1 Cor 16:2"),
    (31,"First Fruits as One","Honoring God off the top","Prov 3:9-10; Mal 3:10"),
    (32,"An Open Home","Hospitality as a couple","Rom 12:13; 1 Pet 4:9"),
    (33,"Serving Side by Side","Like Aquila and Priscilla","Acts 18:2-3,26; Rom 16:3-4"),
    (34,"The Joy of Giving Together","Shared cheerful generosity","2 Cor 9:7; Phil 4:15-17"),
    (35,"A Legacy of Generosity","Modeling it for your children","Prov 22:6; Deut 6:6-7"),
  ]},
  {"roman":"VI","title":"A United Future","subtitle":"Dreaming and Planning as One","days":[
    (36,"Building Our House","Wisdom that establishes a home","Prov 24:3-4; Ps 127:1"),
    (37,"Saving for Tomorrow","Planning the road ahead","Prov 21:20; Prov 6:6-8"),
    (38,"Through Every Season","Steady in plenty and want","Phil 4:12; Eccl 3:1"),
    (39,"A Heritage for Our Children","Leaving more than money","Prov 13:22; 2 Cor 12:14"),
    (40,"Walking Together","One mission, one plan, one future","Amos 3:3; Eccl 4:12"),
  ]},
 ],
},
{
 "num": 9,
 "title": "Wisdom With Money",
 "tagline": "Making Decisions That Stand the Test of Time",
 "positioning": "A 40-day journey through the Bible's deep well of financial wisdom — saving, planning, decision-making, and counsel — for everyone who wants to handle money wisely rather than foolishly.",
 "felt_need": "Impulsive decisions, no margin, the fear of making a costly money mistake, and not knowing how to choose well.",
 "audience": "All church · Workplace teams · Decision-makers and planners",
 "tier": "Tier 1 — Church & Company",
 "core_ref": "Proverbs 24:3-4 (NIV)",
 "core_text": "By wisdom a house is built, and through understanding it is established; through knowledge its rooms are filled with rare and beautiful treasures.",
 "marketing": "Most money trouble is not a math problem; it is a wisdom problem. The decisions that quietly shape a financial life — whether to save, when to wait, whom to ask, what to avoid — are rarely taught and easily fumbled. This campaign opens the Bible's remarkable treasury of practical wisdom, much of it from Proverbs, and turns it into a way of making decisions that last. It is the difference between the wise builder whose house stands and the foolish one whose house falls. Over 40 days, a congregation learns to ask for wisdom, save with foresight, avoid common traps, seek wise counsel, and build a financial life on rock.",
 "why_matters": "Wise money decisions compound over a lifetime. A congregation that learns biblical financial wisdom avoids predictable disasters and builds something that lasts.",
 "problem": "We make money decisions on impulse and emotion, then live with consequences wisdom would have spared us.",
 "transformation": "From foolish, reactive money choices to wise, deliberate ones; from a house on sand to a house on rock.",
 "formats": ["4-Session", "6-Session", "21-Day", "30-Day", "40-Day"],
 "sessions": [
   ("The Wise and the Foolish", "Two builders, two foundations"),
   ("Asking God for Wisdom", "The wisdom that is freely given"),
   ("The Wisdom of Saving", "Foresight, margin, and the long view"),
   ("Avoiding Financial Folly", "The traps wisdom helps you sidestep"),
   ("The Value of Wise Counsel", "Why no one should decide alone"),
   ("A House That Stands", "Building a financial life on rock"),
 ],
 "scriptures": ["Proverbs 24:3-4", "James 1:5", "Proverbs 21:20", "Proverbs 6:6-8", "Proverbs 15:22", "Matthew 7:24-27"],
 "movements": [
  {"roman":"I","title":"Wise and Foolish","subtitle":"Two Builders, Two Foundations","days":[
    (1,"Two Builders","The wise and foolish foundations","Matt 7:24-27; Luke 6:47-49"),
    (2,"The House on Rock","Wisdom that withstands the storm","Matt 7:24-25; Ps 1:3"),
    (3,"The House on Sand","Where folly leads in the end","Matt 7:26-27; Prov 14:1"),
    (4,"The Beginning of Wisdom","Where real wisdom starts","Prov 9:10; Prov 1:7"),
    (5,"More Than Knowledge","Wisdom is knowledge applied","Jas 3:13; Prov 4:7"),
    (6,"The Cost of Folly","Why foolish choices compound","Prov 13:15; Prov 22:3"),
    (7,"Choosing the Better Way","Deciding to build wisely","Prov 8:10-11; Prov 3:13-15"),
  ]},
  {"roman":"II","title":"Asking for Wisdom","subtitle":"Freely Given","days":[
    (8,"Ask and Receive","Wisdom is yours for the asking","Jas 1:5; Prov 2:3-6"),
    (9,"Without Finding Fault","God gives it generously","Jas 1:5; Matt 7:7-8"),
    (10,"Solomon's Request","Asking for the right thing","1 Kgs 3:5-12; 2 Chr 1:10-12"),
    (11,"Trust, Don't Lean","Wisdom begins with surrender","Prov 3:5-6; Prov 28:26"),
    (12,"He Makes Paths Straight","Guidance for the decision","Prov 3:6; Ps 32:8"),
    (13,"Wisdom From Above","Pure, peaceable, practical","Jas 3:17; Col 1:9"),
    (14,"Pray Before You Decide","Seeking God in the choice","Phil 4:6-7; Prov 16:3"),
  ]},
  {"roman":"III","title":"The Wisdom of Saving","subtitle":"Foresight and the Long View","days":[
    (15,"Consider the Ant","Foresight without a boss","Prov 6:6-8; Prov 30:24-25"),
    (16,"Stores of Plenty","Wisdom keeps a reserve","Prov 21:20; Prov 13:11"),
    (17,"Joseph's Plan","Saving in the good years","Gen 41:34-36,48-49; Prov 22:3"),
    (18,"Little by Little","Wealth that grows steadily","Prov 13:11; Prov 21:5"),
    (19,"The Sluggard's Field","What neglect produces","Prov 24:30-34; Prov 20:4"),
    (20,"Counting the Cost","Planning before you commit","Luke 14:28-30; Prov 24:27"),
    (21,"Patient and Steady","Wealth gained over time","Prov 28:20; Prov 13:11"),
  ]},
  {"roman":"IV","title":"Avoiding Folly","subtitle":"The Traps Wisdom Sidesteps","days":[
    (22,"Get-Rich-Quick","Why shortcuts fail","Prov 28:20,22; Prov 13:11"),
    (23,"The Danger of Cosigning","Wisdom about guaranteeing debt","Prov 6:1-5; Prov 22:26-27"),
    (24,"Borrower and Lender","Understanding the cost of debt","Prov 22:7; Rom 13:8"),
    (25,"Chasing Fantasies","Reality over wishful thinking","Prov 28:19; Prov 12:11"),
    (26,"The Bribe and the Bait","Integrity over easy money","Prov 15:27; Prov 11:1"),
    (27,"Pride Before the Fall","Humility in money matters","Prov 16:18; Prov 11:2"),
    (28,"Test Before You Trust","Wisdom is not gullible","Prov 14:15; 1 Thess 5:21"),
  ]},
  {"roman":"V","title":"Wise Counsel","subtitle":"No One Decides Alone","days":[
    (29,"Plans Fail Without Counsel","Why we need other voices","Prov 15:22; Prov 11:14"),
    (30,"Many Advisers","Safety in wise counsel","Prov 24:6; Prov 20:18"),
    (31,"Choosing Wise Advisers","Whose advice to seek","Prov 13:20; Ps 1:1"),
    (32,"The Humility to Ask","Admitting we don't know","Prov 12:15; Prov 19:20"),
    (33,"Accountability","Letting others speak in","Prov 27:17; Eccl 4:9-10"),
    (34,"Weighing Advice","Discerning good counsel","Prov 18:17; 1 Cor 2:14-15"),
    (35,"Walking With the Wise","Who you learn from matters","Prov 13:20; 1 Cor 15:33"),
  ]},
  {"roman":"VI","title":"A House That Stands","subtitle":"Built on Rock","days":[
    (36,"Built by Wisdom","A home established to last","Prov 24:3-4; Prov 14:1"),
    (37,"Filled With Treasure","The fruit of wise choices","Prov 24:4; Prov 8:18-21"),
    (38,"Wisdom for the Generations","Passing it to your children","Prov 4:1-7; Deut 6:6-7"),
    (39,"Faithful With Talents","Wise stewardship rewarded","Matt 25:20-23; Luke 19:16-17"),
    (40,"Standing in the Storm","A life that does not fall","Matt 7:24-25; Ps 112:5-7"),
  ]},
 ],
},
{
 "num": 10,
 "title": "Your Money Legacy",
 "tagline": "Investing in What Outlives You",
 "positioning": "A 40-day journey that lifts money out of the short term and into eternity — helping people steward their resources to leave a legacy of faith, wisdom, and generosity that outlasts them.",
 "felt_need": "The question of what it all adds up to, the desire to leave something meaningful, and uncertainty about how to finish well.",
 "audience": "Midlife and older adults · Families · Anyone thinking about what they'll leave behind",
 "tier": "Tier 1 — Church & Company",
 "core_ref": "Proverbs 13:22 (NIV)",
 "core_text": "A good person leaves an inheritance for their children's children.",
 "marketing": "Sooner or later, every honest person asks what it all adds up to. The accounts, the years of work, the things accumulated — what will any of it mean when we are gone? This campaign answers that question with hope. It moves a congregation's gaze from the short term to the eternal, from spending it all to investing in what lasts. Drawing on Jesus' teaching about treasure in heaven and Scripture's vision of an inheritance that blesses generations, it helps people steward their resources, their wisdom, and their faith into a legacy that outlives them — and to finish their financial race well.",
 "why_matters": "How a generation handles wealth shapes the families, churches, and causes that come after it. A theology of legacy turns money into multi-generational blessing.",
 "problem": "We manage money only for now, and miss the chance to invest in what will outlast us.",
 "transformation": "From a short-term, self-focused view of money to an eternal, generational one; from accumulating to leaving a blessing.",
 "formats": ["4-Session", "6-Session", "21-Day", "30-Day", "40-Day"],
 "sessions": [
   ("The Legacy Question", "What will all of this add up to?"),
   ("Treasure in Heaven", "Investing where it truly lasts"),
   ("An Inheritance of Wisdom", "Leaving more than money to those you love"),
   ("Generous to the End", "Finishing with open hands"),
   ("Planning the Handoff", "Stewarding the practical transfer well"),
   ("Finishing Well", "Running the last lap with purpose"),
 ],
 "scriptures": ["Proverbs 13:22", "Matthew 6:19-21", "1 Timothy 6:17-19", "Luke 16:9", "Psalm 90:12", "2 Timothy 4:7"],
 "movements": [
  {"roman":"I","title":"The Legacy Question","subtitle":"What Will It Add Up To","days":[
    (1,"Number Our Days","Living with the end in view","Ps 90:12; Ps 39:4-5"),
    (2,"What Will Remain","Looking past the short term","Eccl 2:18-21; 1 Cor 3:13-14"),
    (3,"You Can't Take It","Coming and going empty-handed","1 Tim 6:7; Eccl 5:15"),
    (4,"The Rich Fool's Mistake","Storing up only for self","Luke 12:16-21; Ps 49:16-17"),
    (5,"More Than an Estate","Legacy is bigger than money","Prov 22:1; Prov 10:7"),
    (6,"What Matters in the End","Re-sorting your priorities","Matt 16:26; Phil 1:21"),
    (7,"Beginning With the End","Stewarding for what lasts","Ps 90:12; 2 Cor 4:18"),
  ]},
  {"roman":"II","title":"Treasure in Heaven","subtitle":"Where It Truly Lasts","days":[
    (8,"Treasures That Last","Storing up in heaven","Matt 6:19-21; Luke 12:33"),
    (9,"Where Your Heart Is","Treasure and the heart","Matt 6:21; Col 3:1-2"),
    (10,"Rich Toward God","The wealth that counts","Luke 12:21; 1 Tim 6:18-19"),
    (11,"Investing in Eternity","Sending it ahead","1 Tim 6:19; Matt 19:21"),
    (12,"Friends Welcome You","Using money for eternity","Luke 16:9; Luke 16:11"),
    (13,"A Firm Foundation","Laying up for the future","1 Tim 6:19; Matt 7:24-25"),
    (14,"The Eternal Return","The best investment there is","Mark 10:29-30; 2 Cor 9:6"),
  ]},
  {"roman":"III","title":"An Inheritance of Wisdom","subtitle":"More Than Money","days":[
    (15,"Children's Children","Planning to bless generations","Prov 13:22; Ps 112:1-2"),
    (16,"More Than Money","Passing on faith and wisdom","Deut 6:6-7; 2 Tim 1:5"),
    (17,"Teaching the Next Generation","Modeling stewardship at home","Prov 22:6; Ps 78:4-6"),
    (18,"A Good Name","The inheritance of character","Prov 22:1; Eccl 7:1"),
    (19,"Faith Handed Down","The legacy that matters most","2 Tim 1:5; Josh 24:15"),
    (20,"Blessing, Not Burden","Leaving wisdom with the wealth","Prov 13:22; Prov 20:21"),
    (21,"The Stories You Tell","Passing on what God has done","Ps 78:4; Deut 4:9"),
  ]},
  {"roman":"IV","title":"Generous to the End","subtitle":"Finishing With Open Hands","days":[
    (22,"Command the Rich","Instructions for those with much","1 Tim 6:17; Deut 8:17-18"),
    (23,"Do Good, Be Rich in It","Wealth measured in good deeds","1 Tim 6:18; Gal 6:9-10"),
    (24,"Generous and Willing","Ready to share to the end","1 Tim 6:18; 2 Cor 9:7"),
    (25,"Scattered Yet Increased","The paradox of generosity","Prov 11:24-25; 2 Cor 9:6"),
    (26,"David's Final Gift","Giving generously for God's work","1 Chr 29:2-5,14; 1 Chr 29:9"),
    (27,"Giving While Living","Generosity you get to see","Prov 3:27-28; 2 Cor 8:11-12"),
    (28,"A Cheerful Finish","Open-handed to the last","2 Cor 9:7; Acts 20:35"),
  ]},
  {"roman":"V","title":"Planning the Handoff","subtitle":"Stewarding the Transfer","days":[
    (29,"Set Your House in Order","Wisdom in preparing ahead","Isa 38:1; Prov 24:27"),
    (30,"The Diligent Plan","Foresight for the future","Prov 21:5; Prov 27:23-24"),
    (31,"A Wise Steward to the End","Faithful with the handoff","Luke 12:42-44; 1 Cor 4:2"),
    (32,"Inheritance Done Wisely","Avoiding the hasty windfall","Prov 20:21; Prov 13:11"),
    (33,"Provision, Not Entitlement","Blessing that doesn't harm","2 Thess 3:10; Prov 29:21"),
    (34,"Counsel for the Transfer","Seeking wisdom in the plan","Prov 15:22; Prov 11:14"),
    (35,"Stewarding the Details","Faithfulness in the practical","Luke 16:10-12; Col 3:23"),
  ]},
  {"roman":"VI","title":"Finishing Well","subtitle":"The Last Lap","days":[
    (36,"Running the Race","Finishing with purpose","2 Tim 4:7; Heb 12:1-2"),
    (37,"Faithful to the End","Steady all the way home","1 Cor 4:2; Rev 2:10"),
    (38,"Well Done","The words worth living for","Matt 25:21,23; Luke 19:17"),
    (39,"A Light to Those After","Shining for the next generation","Matt 5:16; Ps 112:4-6"),
    (40,"The Legacy That Lasts","Investing in what outlives you","Prov 13:22; Matt 6:20-21"),
  ]},
 ],
},
]
