# -*- coding: utf-8 -*-
"""40-Day devotional maps — Batch 5 (nums 38-44): Generosity & Giving.
6 movements aligned to the 6 sessions, 40 days in a 7-7-7-7-7-5 arc."""

MAPS = {
 # ---------------- 38 · The Joy of Giving ----------------
 38: [
  {"roman":"I","title":"Bracing for Loss","subtitle":"When Giving Feels Like Losing","days":[
   (1,"The Fear of Less","Giving feels like losing","Luke 6:38; Prov 11:24"),
   (2,"The Tight Grip","Holding back in fear","Prov 11:24; Eccl 5:13"),
   (3,"What If I Run Short?","The scarcity worry","Mal 3:10; Phil 4:19"),
   (4,"Sowing, Not Losing","A different picture","2 Cor 9:6; Gal 6:7"),
   (5,"The Seed in the Ground","Release to multiply","John 12:24; 2 Cor 9:10"),
   (6,"Give and It Will Be Given","The promise","Luke 6:38; Prov 11:25"),
   (7,"Loosening the Grip","Ready to give","Luke 6:38; 2 Cor 9:7"),
  ]},
  {"roman":"II","title":"More Blessed to Give","subtitle":"Jesus' Surprising Word","days":[
   (8,"More Blessed to Give","Jesus' surprising word","Acts 20:35; Luke 14:13-14"),
   (9,"The Backwards Math","Gaining by giving","Prov 11:24; Luke 6:38"),
   (10,"The Giver's Blessing","Joy on the giving end","Acts 20:35; Ps 41:1-2"),
   (11,"Better Than Receiving","Where true joy lies","Acts 20:35; 2 Cor 9:7"),
   (12,"Like the Father","God so loved, He gave","John 3:16; 2 Cor 9:15"),
   (13,"The Blessing Returns","Refreshed in refreshing","Prov 11:25; Luke 6:38"),
   (14,"Blessed in the Giving","The truth received","Acts 20:35; Prov 11:25"),
  ]},
  {"roman":"III","title":"Pressed Down, Running Over","subtitle":"The Generous Return","days":[
   (15,"A Good Measure","The generous return","Luke 6:38; 2 Cor 9:6"),
   (16,"Pressed Down","Filled to the brim","Luke 6:38; Mal 3:10"),
   (17,"Shaken Together","More than expected","Luke 6:38; Prov 3:9-10"),
   (18,"Running Over","Overflowing into your lap","Luke 6:38; 2 Cor 9:8"),
   (19,"The Measure You Use","Returned in kind","Luke 6:38; 2 Cor 9:6"),
   (20,"Sow Bountifully","Reap bountifully","2 Cor 9:6; Prov 11:24"),
   (21,"Overflowing Back","The harvest of giving","Luke 6:38; 2 Cor 9:10-11"),
  ]},
  {"roman":"IV","title":"The First Joyful Gift","subtitle":"Where the Gladness Begins","days":[
   (22,"Decide in the Heart","Plan the gift","2 Cor 9:7; 1 Cor 16:2"),
   (23,"Give the First","Off the top","Prov 3:9-10; 2 Cor 8:5"),
   (24,"Start Where You Are","The willing gift","2 Cor 8:12; Mark 12:43-44"),
   (25,"Cheerful, Not Reluctant","The heart of it","2 Cor 9:7; Deut 15:10"),
   (26,"Give to Real Need","Where it counts","Acts 4:34-35; Prov 19:17"),
   (27,"The First Step of Joy","Tasting the gladness","Phil 4:17; Acts 20:35"),
   (28,"The First Gift Given","Joy begins","2 Cor 9:7; Luke 6:38"),
  ]},
  {"roman":"V","title":"Joy That Grows","subtitle":"Gladness That Compounds","days":[
   (29,"Joy Compounds","Gladness grows with giving","2 Cor 8:2; Phil 4:17"),
   (30,"Abounding Joy","Even in trial","2 Cor 8:2; 2 Cor 9:8"),
   (31,"Fruit to Your Account","What giving builds","Phil 4:17; 1 Tim 6:18-19"),
   (32,"Generous and Glad","The cycle deepens","Prov 11:25; 2 Cor 9:7"),
   (33,"Treasure in Heaven","Joy that lasts","Matt 6:20-21; 1 Tim 6:19"),
   (34,"The Refreshed Soul","Giver refreshed again","Prov 11:25; Isa 58:10-11"),
   (35,"Joy That Grows","Increasing gladness","Phil 4:17; 2 Cor 9:8"),
  ]},
  {"roman":"VI","title":"The Joy of Giving","subtitle":"Gladness That Overflows","days":[
   (36,"A Settled Gladness","Joy in the giving life","Acts 20:35; 2 Cor 9:7"),
   (37,"Giving as Worship","An offering of joy","Phil 4:18; Heb 13:16"),
   (38,"The Cheerful Giver","Loved by God","2 Cor 9:7; Prov 22:9"),
   (39,"Free and Generous","No more bracing","Luke 6:38; Prov 11:24-25"),
   (40,"The Joy of Giving","Gladness that overflows","Luke 6:38; Acts 20:35"),
  ]},
 ],
 # ---------------- 39 · Open Hands, Full Hearts ----------------
 39: [
  {"roman":"I","title":"The Clenched Fist","subtitle":"Holding Too Tight","days":[
   (1,"The Clenched Fist","Holding too tight","Prov 11:24; Luke 12:15"),
   (2,"Grasping and Empty","What clutching costs","Prov 11:24; Eccl 5:13"),
   (3,"Fear Behind the Fist","Scarcity grips us","Prov 11:24; Matt 6:31"),
   (4,"The Withholding That Loses","Coming to poverty","Prov 11:24; Prov 28:27"),
   (5,"A Closed Hand Receives Nothing","Shut to giving and getting","Acts 20:35; Luke 6:38"),
   (6,"What the Grip Reveals","A heart turned inward","Prov 11:24; 1 John 3:17"),
   (7,"Ready to Open","Loosening begins","Prov 11:25; 2 Cor 9:7"),
  ]},
  {"roman":"II","title":"The Generosity Paradox","subtitle":"Giving That Gains","days":[
   (8,"The Paradox","Give and grow richer","Prov 11:24; Luke 6:38"),
   (9,"Scatter, Yet Increase","The upside-down truth","Prov 11:24; 2 Cor 9:6"),
   (10,"Withhold, and Come to Want","The other side","Prov 11:24; Hag 1:6"),
   (11,"Lending to the Lord","Giving to the poor","Prov 19:17; Matt 25:40"),
   (12,"He Will Repay","The Lord's reward","Prov 19:17; Luke 14:14"),
   (13,"Bread Upon the Waters","Returned in time","Eccl 11:1; Gal 6:9"),
   (14,"The Paradox Embraced","Gaining by releasing","Prov 11:24-25; 2 Cor 9:8"),
  ]},
  {"roman":"III","title":"Refreshing and Refreshed","subtitle":"The Watered Become Watered","days":[
   (15,"Whoever Refreshes","Will be refreshed","Prov 11:25; Isa 58:11"),
   (16,"The Generous Prosper","A soul made fat / well-fed","Prov 11:25; Prov 22:9"),
   (17,"Watering Others","And being watered","Prov 11:25; Isa 58:10-11"),
   (18,"Spend Yourself","Light in the darkness","Isa 58:10; Matt 5:16"),
   (19,"A Spring That Doesn't Fail","The refreshed life","Isa 58:11; John 7:38"),
   (20,"Sowing Refreshment","Reaping the same","Prov 11:25; 2 Cor 9:6"),
   (21,"Refreshed in Refreshing","The cycle of grace","Prov 11:25; Luke 6:38"),
  ]},
  {"roman":"IV","title":"Loosening the Grip","subtitle":"Practical Open-Handedness","days":[
   (22,"Open the Hand","First steps of release","Deut 15:10-11; 2 Cor 9:7"),
   (23,"Give Without Grudging","Freely, gladly","Deut 15:10; 2 Cor 9:7"),
   (24,"Plan to Be Generous","Giving by design","1 Cor 16:2; 2 Cor 9:7"),
   (25,"Notice the Need","Eyes open to others","Prov 19:17; 1 John 3:17"),
   (26,"Hold Things Loosely","Owned by nothing","1 Tim 6:7; Luke 12:15"),
   (27,"Generous on Every Occasion","A ready hand","2 Cor 9:11; Prov 3:27-28"),
   (28,"The Grip Loosened","An open hand formed","Prov 11:25; 2 Cor 9:8"),
  ]},
  {"roman":"V","title":"The Fuller Life","subtitle":"Fullness From Openness","days":[
   (29,"The Fuller Heart","Filled by giving","Prov 11:25; Acts 20:35"),
   (30,"Rich Toward Others","And toward God","Luke 12:21; 1 Tim 6:18"),
   (31,"Treasure That Lasts","Stored in heaven","Matt 6:20-21; 1 Tim 6:19"),
   (32,"Joy in the Open Hand","Gladness overflows","2 Cor 9:7; Phil 4:17"),
   (33,"Freed From Greed","The fuller way","Luke 12:15; Heb 13:5"),
   (34,"A Life That Pours Out","And is filled","Isa 58:10-11; John 7:38"),
   (35,"The Fuller Life","Openness brings fullness","Prov 11:25; 2 Cor 9:8"),
  ]},
  {"roman":"VI","title":"Open Hands, Full Hearts","subtitle":"Living Open-Handed","days":[
   (36,"An Open-Handed Life","The settled posture","Prov 11:25; 2 Cor 9:7"),
   (37,"Generous and Full","Hands open, heart full","Prov 11:25; Acts 20:35"),
   (38,"Ready to Give","On every occasion","2 Cor 9:11; Prov 3:27"),
   (39,"Full in the Giving","Refreshed again","Prov 11:25; Luke 6:38"),
   (40,"Open Hands, Full Hearts","The generous life","Prov 11:24-25; 2 Cor 9:8"),
  ]},
 ],
 # ---------------- 40 · The Tithe and Beyond ----------------
 40: [
  {"roman":"I","title":"What Is the Tithe?","subtitle":"The First Tenth","days":[
   (1,"The First Tenth","What the tithe means","Lev 27:30; Mal 3:10"),
   (2,"Holy to the Lord","Set apart for God","Lev 27:30; Deut 14:22-23"),
   (3,"Abraham's Tenth","Before the law","Gen 14:20; Heb 7:2"),
   (4,"Jacob's Vow","A tenth of all","Gen 28:22; Deut 14:22"),
   (5,"Returning, Not Giving","Already His","Lev 27:30; 1 Chr 29:14"),
   (6,"More Than a Rule","The heart in it","Matt 23:23; 2 Cor 9:7"),
   (7,"Understanding the Tithe","A place to begin","Lev 27:30; Mal 3:10"),
  ]},
  {"roman":"II","title":"Bring the Whole Tithe","subtitle":"Test Me in This","days":[
   (8,"Bring the Whole Tithe","Into the storehouse","Mal 3:10; Prov 3:9"),
   (9,"Test Me in This","God's open invitation","Mal 3:10; 2 Cor 9:8"),
   (10,"Windows of Heaven","The promised blessing","Mal 3:10; Luke 6:38"),
   (11,"Will a Man Rob God?","The convicting question","Mal 3:8; Hag 1:9"),
   (12,"First, Not Leftover","Off the top","Prov 3:9-10; Mal 1:8"),
   (13,"The Best, Not the Rest","Honoring with quality","Mal 1:8; Lev 22:20"),
   (14,"The Whole, Brought In","Faith in the giving","Mal 3:10; Prov 3:5"),
  ]},
  {"roman":"III","title":"The Starting Line","subtitle":"A Baseline, Not a Ceiling","days":[
   (15,"A Place to Start","The tithe as baseline","Mal 3:10; 2 Cor 8:7"),
   (16,"Not the Finish Line","Only the beginning","Matt 23:23; 2 Cor 9:6"),
   (17,"Justice, Mercy, Faithfulness","The weightier matters","Matt 23:23; Mic 6:8"),
   (18,"Beyond Mere Duty","Into glad giving","2 Cor 9:7; Rom 12:8"),
   (19,"Begin Faithfully","First steps of obedience","Luke 16:10; Mal 3:10"),
   (20,"The Habit Established","Giving made regular","1 Cor 16:2; 2 Cor 9:7"),
   (21,"From the Starting Line","Ready to grow","Mal 3:10; 2 Cor 8:7"),
  ]},
  {"roman":"IV","title":"Beyond the Baseline","subtitle":"Giving That Grows","days":[
   (22,"Excel in Giving","Grow in this grace","2 Cor 8:7; 2 Cor 9:6"),
   (23,"As You Are Able","And beyond","2 Cor 8:3; 1 Cor 16:2"),
   (24,"Offerings and Gifts","Above the tithe","Ex 35:29; 2 Cor 9:7"),
   (25,"Sow Bountifully","Reap bountifully","2 Cor 9:6; Prov 11:24"),
   (26,"Generous on Every Occasion","Ready to give more","2 Cor 9:11; Prov 3:27"),
   (27,"Rich in Good Deeds","Storing up treasure","1 Tim 6:18-19; Matt 6:20"),
   (28,"Beyond the Baseline","Generosity expanding","2 Cor 8:7; 2 Cor 9:8"),
  ]},
  {"roman":"V","title":"Giving as a Lifestyle","subtitle":"A Generous Way of Life","days":[
   (29,"A Lifestyle, Not an Event","Giving as a way of life","2 Cor 9:7; Acts 2:44-45"),
   (30,"Generous by Habit","Built into the rhythm","1 Cor 16:2; 2 Cor 9:7"),
   (31,"Open on Every Occasion","Always ready","2 Cor 9:11; Prov 3:27-28"),
   (32,"Cheerful, Not Compelled","The settled heart","2 Cor 9:7; Deut 15:10"),
   (33,"Living to Give","Purpose in plenty","Eph 4:28; 2 Cor 9:8"),
   (34,"Generosity as Worship","Offered to God","Phil 4:18; Heb 13:16"),
   (35,"A Giving Life","Generosity sustained","2 Cor 9:7; Prov 11:25"),
  ]},
  {"roman":"VI","title":"The Tithe and Beyond","subtitle":"From Baseline to Lifestyle","days":[
   (36,"Faithful and Free","Tithe kept, heart open","Mal 3:10; 2 Cor 9:7"),
   (37,"More Than Required","Generosity overflowing","2 Cor 8:3; Luke 6:38"),
   (38,"Treasure in Heaven","What giving stores","Matt 6:20-21; 1 Tim 6:19"),
   (39,"A Generous Identity","A giver at heart","2 Cor 9:7; Prov 11:25"),
   (40,"The Tithe and Beyond","Faithful, then generous","Mal 3:10; 2 Cor 9:8"),
  ]},
 ],
 # ---------------- 41 · Generosity for Beginners ----------------
 41: [
  {"roman":"I","title":"Behind the Starting Line","subtitle":"It's Okay to Begin Small","days":[
   (1,"Behind the Line","It's okay to begin","2 Cor 8:12; Zech 4:10"),
   (2,"No Giver Was Born One","Everyone starts somewhere","2 Cor 8:12; Luke 16:10"),
   (3,"The Fear of Not Enough","What holds beginners back","2 Cor 8:12; Phil 4:19"),
   (4,"God Sees the Heart","Not the amount","1 Sam 16:7; 2 Cor 8:12"),
   (5,"Acceptable Gifts","According to what you have","2 Cor 8:12; Mark 12:43-44"),
   (6,"Small Is Not Nothing","The first gift counts","Luke 16:10; Zech 4:10"),
   (7,"Ready to Start","The beginner's step","2 Cor 8:12; 2 Cor 9:7"),
  ]},
  {"roman":"II","title":"The Willing Heart","subtitle":"What Makes a Gift Acceptable","days":[
   (8,"The Willing Gift","Acceptable to God","2 Cor 8:12; Ex 35:5"),
   (9,"According to What You Have","Not what you don't","2 Cor 8:12; 2 Cor 9:7"),
   (10,"God Loves a Cheerful Giver","Heart over amount","2 Cor 9:7; Prov 22:9"),
   (11,"A Heart That Wants To","Willingness first","2 Cor 8:11-12; 1 Chr 29:9"),
   (12,"Not Reluctantly","Free and glad","2 Cor 9:7; Deut 15:10"),
   (13,"The Gift God Receives","Given in faith","Heb 11:4; 2 Cor 8:12"),
   (14,"A Willing Heart","The starting place","2 Cor 8:12; Ex 35:21"),
  ]},
  {"roman":"III","title":"The Widow's Small Gift","subtitle":"More Than All the Rest","days":[
   (15,"Two Small Coins","The widow's offering","Mark 12:42; Luke 21:2"),
   (16,"More Than All the Rest","Jesus' measure","Mark 12:43; Luke 21:3"),
   (17,"Out of Her Poverty","All she had to live on","Mark 12:44; Luke 21:4"),
   (18,"The Heart Behind It","Why it counted most","Mark 12:43-44; 2 Cor 8:12"),
   (19,"Not the Amount, the Cost","Sacrifice over sum","Mark 12:44; 2 Sam 24:24"),
   (20,"Seen and Honored","Jesus noticed","Mark 12:41; Luke 21:1"),
   (21,"The Widow's Lesson","Small gifts, great faith","Mark 12:43-44; 2 Cor 8:12"),
  ]},
  {"roman":"IV","title":"Your First Steps","subtitle":"Beginning to Give","days":[
   (22,"Start With Something","The first gift","2 Cor 9:7; Prov 3:9"),
   (23,"Give the First Part","Honor God off the top","Prov 3:9-10; 1 Cor 16:2"),
   (24,"Set It Aside","Planned, not leftover","1 Cor 16:2; 2 Cor 9:7"),
   (25,"Give to a Real Need","Where it helps","Prov 19:17; Acts 4:34-35"),
   (26,"Cheerfully, Not Grudgingly","The right spirit","2 Cor 9:7; Deut 15:10"),
   (27,"Notice How It Feels","The joy of the first gift","Acts 20:35; Phil 4:17"),
   (28,"First Steps Taken","The beginner gives","2 Cor 9:7; Luke 6:38"),
  ]},
  {"roman":"V","title":"Building the Habit","subtitle":"Generosity Made Regular","days":[
   (29,"On the First Day","A regular rhythm","1 Cor 16:2; 2 Cor 9:7"),
   (30,"Faithful in Little","The growing habit","Luke 16:10; Prov 13:11"),
   (31,"Give Before You Spend","First, not last","Prov 3:9; Matt 6:33"),
   (32,"Grow the Gift","As God provides","1 Cor 16:2; 2 Cor 8:7"),
   (33,"Generosity Repeated","Habit becomes character","Gal 6:9; 2 Cor 9:7"),
   (34,"Not Weary in Giving","Keeping at it","Gal 6:9; 2 Thess 3:13"),
   (35,"The Habit Built","Giving as routine","1 Cor 16:2; Luke 16:10"),
  ]},
  {"roman":"VI","title":"No Longer a Beginner","subtitle":"A Generous Heart Formed","days":[
   (36,"Growing in Grace","Excelling in giving","2 Cor 8:7; 2 Cor 9:6"),
   (37,"A Giver's Heart","Formed over time","2 Cor 9:7; Prov 11:25"),
   (38,"Joy Now Familiar","Gladness in giving","Acts 20:35; Phil 4:17"),
   (39,"Ready to Give More","Beyond the basics","2 Cor 8:3; 2 Cor 9:8"),
   (40,"No Longer a Beginner","A generous life begun","2 Cor 8:7; Luke 6:38"),
  ]},
 ],
 # ---------------- 42 · The Generous Family ----------------
 42: [
  {"roman":"I","title":"Caught at Home","subtitle":"Generosity Is Modeled","days":[
   (1,"More Caught Than Taught","Kids watch and learn","Deut 6:6-7; 1 Cor 11:1"),
   (2,"The Home as Classroom","Where values form","Deut 6:6-7; Prov 22:6"),
   (3,"What They See in Us","Generous or grasping","Luke 6:38; 1 Tim 4:12"),
   (4,"Generosity on Display","Letting kids witness it","2 Cor 9:7; Matt 5:16"),
   (5,"The Family Culture","Open hands at home","Acts 20:35; Ps 112:5"),
   (6,"Starting With Ourselves","Modeled before taught","1 Cor 11:1; Phil 4:9"),
   (7,"Caught at Home","Generosity begins here","Deut 6:6-7; Prov 22:6"),
  ]},
  {"roman":"II","title":"Impress It on Them","subtitle":"Teaching the Next Generation","days":[
   (8,"Impress on Your Children","The command to teach","Deut 6:7; Deut 6:6"),
   (9,"Talk About It","Along the way","Deut 6:7; Deut 11:19"),
   (10,"Tell the Next Generation","God's goodness","Ps 78:4; Ps 145:4"),
   (11,"Train Up a Child","In the way to go","Prov 22:6; Prov 1:8"),
   (12,"Lessons in Giving","Teaching open hands","Acts 20:35; 2 Cor 9:7"),
   (13,"Why We Give","The heart behind it","2 Cor 9:7; 1 John 3:17"),
   (14,"Impressed and Taught","Truth handed down","Deut 6:7; Ps 78:4-7"),
  ]},
  {"roman":"III","title":"Family Giving Rhythms","subtitle":"Generosity Built Into Life","days":[
   (15,"A Family That Gives","Built-in rhythms","1 Cor 16:2; Acts 2:44-45"),
   (16,"Giving Together","A shared offering","2 Cor 9:7; Ps 96:8"),
   (17,"The Giving Jar","Letting kids participate","Mark 12:43-44; 2 Cor 8:12"),
   (18,"First, as a Family","Off the top together","Prov 3:9-10; Matt 6:33"),
   (19,"Choosing a Cause","Generosity with a face","Prov 19:17; Matt 25:40"),
   (20,"Serving Hands Too","Giving time, not just money","Acts 20:35; Gal 5:13"),
   (21,"Rhythms Established","Generosity as routine","1 Cor 16:2; 2 Cor 9:7"),
  ]},
  {"roman":"IV","title":"Generous, Not Entitled","subtitle":"Raising Open Hands","days":[
   (22,"The Pull of Entitlement","A culture of more","Luke 12:15; 1 Tim 6:6-8"),
   (23,"Gratitude First","The antidote to entitlement","1 Thess 5:18; Ps 103:2"),
   (24,"Wants Versus Needs","Teaching the difference","Prov 30:8-9; Phil 4:11-12"),
   (25,"The Joy of Enough","Content children","1 Tim 6:6; Heb 13:5"),
   (26,"Giving Cures Grasping","Open hands, soft hearts","Acts 20:35; Prov 11:24-25"),
   (27,"Serving Others","Eyes off ourselves","Phil 2:3-4; Gal 5:13"),
   (28,"Generous, Not Entitled","Hearts turned outward","Luke 6:38; 1 Tim 6:18"),
  ]},
  {"roman":"V","title":"Kids Who Give","subtitle":"Forming Young Givers","days":[
   (29,"Let the Children Give","Their own gifts","Mark 12:43-44; 2 Cor 8:12"),
   (30,"Earning to Give","Work and generosity","Eph 4:28; Prov 6:6-8"),
   (31,"The Cheerful Young Giver","Joy formed early","2 Cor 9:7; Prov 22:9"),
   (32,"Sharing as Second Nature","Generosity habituated","Heb 13:16; Acts 20:35"),
   (33,"Seeing the Difference","Their giving matters","Prov 19:17; Matt 25:40"),
   (34,"Generosity Celebrated","Encouraging the heart","2 Cor 9:7; 1 Thess 5:11"),
   (35,"Kids Who Give","Young hands opened","Mark 12:43-44; Luke 6:38"),
  ]},
  {"roman":"VI","title":"A Generous Legacy","subtitle":"Passing It On","days":[
   (36,"A Lasting Heritage","Generosity handed down","Ps 112:1-3; Prov 13:22"),
   (37,"Righteousness Endures","A generous family's mark","Ps 112:9; 2 Cor 9:9"),
   (38,"Generations of Givers","The ripple forward","Ps 78:4-7; 2 Tim 1:5"),
   (39,"More Than Money","A heart passed on","Deut 6:6-7; Prov 22:6"),
   (40,"A Generous Legacy","Open hands for generations","Ps 112:5; Luke 6:38"),
  ]},
 ],
 # ---------------- 43 · Radical Generosity ----------------
 43: [
  {"roman":"I","title":"Comfortable Giving","subtitle":"Beyond the Safe Gift","days":[
   (1,"The Safe Gift","Giving from the surplus","Mark 12:44; 2 Cor 8:2-3"),
   (2,"Comfortable Margins","Never feeling it","2 Cor 8:3; Luke 21:4"),
   (3,"The Tip, Not the Sacrifice","Giving what won't be missed","2 Sam 24:24; Mark 12:44"),
   (4,"Called Higher","Beyond the comfortable","2 Cor 8:3; Luke 9:23"),
   (5,"What If We Gave More?","Stretching the gift","2 Cor 8:1-3; Luke 6:38"),
   (6,"Holding Back No Longer","A bigger vision","2 Cor 8:5; Acts 4:32"),
   (7,"Beyond Comfortable","Ready to stretch","2 Cor 8:3; 2 Cor 9:6"),
  ]},
  {"roman":"II","title":"Beyond Their Ability","subtitle":"The Macedonian Example","days":[
   (8,"In Severe Trial","Yet overflowing joy","2 Cor 8:2; Acts 16:9-10"),
   (9,"Out of Deep Poverty","Rich generosity","2 Cor 8:2; Mark 12:44"),
   (10,"As Much as Able","And beyond","2 Cor 8:3; 1 Chr 29:14"),
   (11,"Pleading to Give","The privilege of sharing","2 Cor 8:4; Acts 11:29"),
   (12,"Themselves First","Given to the Lord","2 Cor 8:5; Rom 12:1"),
   (13,"Grace That Gives","God's grace in them","2 Cor 8:1; 2 Cor 9:8"),
   (14,"Beyond Their Ability","Sacrificial generosity","2 Cor 8:3; Phil 4:18"),
  ]},
  {"roman":"III","title":"The Joy in Sacrifice","subtitle":"Gladness That Costs","days":[
   (15,"Overflowing Joy","Even in hardship","2 Cor 8:2; Phil 4:4"),
   (16,"The Gift That Costs","Real sacrifice","2 Sam 24:24; Mark 12:44"),
   (17,"Joy on the Far Side","Gladness in giving up","Acts 20:35; Heb 12:2"),
   (18,"Treasure Re-aimed","Heart following the gift","Matt 6:20-21; Luke 12:33-34"),
   (19,"Counting It Gain","Loss for Christ's sake","Phil 3:7-8; Matt 13:44"),
   (20,"Freed by Letting Go","Lightness in sacrifice","Luke 18:22; 1 Tim 6:7"),
   (21,"Joy in Sacrifice","Glad to give it up","2 Cor 8:2; Acts 20:35"),
  ]},
  {"roman":"IV","title":"Counting It Worth It","subtitle":"The Eternal Trade","days":[
   (22,"The Treasure in the Field","Worth selling all","Matt 13:44; Phil 3:8"),
   (23,"Sell and Give","The rich ruler's test","Luke 18:22; Mark 10:21"),
   (24,"Treasure in Heaven","Where it really counts","Matt 6:20; Luke 12:33"),
   (25,"Storing Up the Eternal","A firm foundation","1 Tim 6:18-19; Matt 6:20"),
   (26,"What's It All For?","Generosity's purpose","Luke 12:21; 2 Cor 9:11"),
   (27,"No Regret in Giving","Worth every gift","2 Cor 9:6; Prov 11:24-25"),
   (28,"Counted Worth It","The eternal trade","Matt 13:44; Phil 3:7-8"),
  ]},
  {"roman":"V","title":"World-Changing Generosity","subtitle":"Generosity That Transforms","days":[
   (29,"All Things in Common","The early church","Acts 4:32; Acts 2:44-45"),
   (30,"No Needy Among Them","Generosity met need","Acts 4:34-35; Deut 15:4"),
   (31,"Generosity as Witness","The watching world","John 13:35; Matt 5:16"),
   (32,"Meeting Real Needs","Faith with works","Jas 2:15-16; 1 John 3:17-18"),
   (33,"Sharing the Gospel and Goods","Word and deed","1 Thess 2:8; Acts 20:35"),
   (34,"A Generosity That Spreads","Overflowing thanks","2 Cor 9:11-13; 2 Cor 8:14"),
   (35,"Changing the World","One gift at a time","Acts 4:32-35; 2 Cor 9:8"),
  ]},
  {"roman":"VI","title":"Living Radically Generous","subtitle":"A Life Poured Out","days":[
   (36,"A Life Poured Out","Generosity as identity","2 Cor 8:5; Phil 2:17"),
   (37,"Holding Nothing Back","Wholehearted giving","Mark 12:44; 1 Chr 29:14"),
   (38,"Rich in Good Deeds","Generous and ready","1 Tim 6:18-19; 2 Cor 9:8"),
   (39,"Following the Generous God","Who gave His Son","John 3:16; 2 Cor 8:9"),
   (40,"Living Radically Generous","No longer holding back","2 Cor 8:1-5; Luke 6:38"),
  ]},
 ],
 # ---------------- 44 · Cheerful Givers ----------------
 44: [
  {"roman":"I","title":"Why It Feels Like Duty","subtitle":"When Giving Is a Chore","days":[
   (1,"Giving as Obligation","The reluctant gift","2 Cor 9:7; 2 Cor 8:8"),
   (2,"Under Compulsion","Squeezed, not glad","2 Cor 9:7; Phlm 1:14"),
   (3,"The Grudging Gift","Heart not in it","Deut 15:10; 2 Cor 9:7"),
   (4,"Duty Without Delight","Going through motions","Matt 23:23; Isa 29:13"),
   (5,"What's Behind the Reluctance","Fear and grip","Prov 11:24; Luke 12:15"),
   (6,"A Better Way to Give","From the heart","2 Cor 9:7; Rom 12:8"),
   (7,"Beyond Duty","Toward gladness","2 Cor 9:7; Ps 100:2"),
  ]},
  {"roman":"II","title":"What God Loves","subtitle":"A Cheerful Giver","days":[
   (8,"God Loves a Cheerful Giver","The heart He delights in","2 Cor 9:7; Prov 22:9"),
   (9,"Not the Amount, the Heart","What matters most","2 Cor 8:12; 1 Sam 16:7"),
   (10,"The Generous Are Blessed","A good eye","Prov 22:9; Prov 11:25"),
   (11,"Give Generously","Without grudging","Deut 15:10; 2 Cor 9:6"),
   (12,"With Cheerfulness","The right spirit","Rom 12:8; 2 Cor 9:7"),
   (13,"A Delight to God","Gladness honors Him","2 Cor 9:7; Heb 13:16"),
   (14,"What God Loves","The cheerful heart","2 Cor 9:7; Prov 22:9"),
  ]},
  {"roman":"III","title":"Decided in the Heart","subtitle":"Giving With Intention","days":[
   (15,"Decide in Your Heart","Not on the spot","2 Cor 9:7; 1 Cor 16:2"),
   (16,"What You Have Decided","Purposeful giving","2 Cor 9:7; 2 Cor 8:11"),
   (17,"Plan the Gift","Set it aside first","1 Cor 16:2; Prov 3:9"),
   (18,"Free From Pressure","No reluctance, no compulsion","2 Cor 9:7; Phlm 1:14"),
   (19,"A Settled Decision","Made ahead of time","2 Cor 9:7; Prov 21:5"),
   (20,"From the Heart, Not the Moment","Intention over impulse","2 Cor 9:7; 2 Cor 8:12"),
   (21,"Decided and Glad","The intentional gift","2 Cor 9:7; 1 Cor 16:2"),
  ]},
  {"roman":"IV","title":"From Compulsion to Gladness","subtitle":"The Heart Transformed","days":[
   (22,"Why We Give Reluctantly","The grip of fear","Prov 11:24; Matt 6:31"),
   (23,"Grace Changes Giving","Freely received, freely give","Matt 10:8; 2 Cor 8:9"),
   (24,"Trust Replaces Fear","God supplies the giver","2 Cor 9:8; Phil 4:19"),
   (25,"Gratitude Fuels Generosity","Thankful, then glad","2 Cor 9:11-12; Ps 116:12"),
   (26,"Seeing the Joy","Better to give","Acts 20:35; Luke 6:38"),
   (27,"The Heart Set Free","Gladness unlocked","2 Cor 9:7; Gal 5:1"),
   (28,"From Compulsion to Gladness","The transformation","2 Cor 9:7; Rom 12:8"),
  ]},
  {"roman":"V","title":"The Glad-Hearted Gift","subtitle":"Joy in the Giving","days":[
   (29,"Giving With Joy","The glad heart","2 Cor 8:2; Phil 4:4"),
   (30,"The Blessing of Giving","More blessed indeed","Acts 20:35; Prov 11:25"),
   (31,"Worship Through Giving","An offering of praise","Phil 4:18; Heb 13:16"),
   (32,"Cheerful and Free","No grudging, no fear","2 Cor 9:7; Deut 15:10"),
   (33,"Sown in Gladness","A bountiful reaping","2 Cor 9:6; Ps 126:5"),
   (34,"The Giver Refreshed","Gladness returns","Prov 11:25; Luke 6:38"),
   (35,"The Glad-Hearted Gift","Joy in every gift","2 Cor 9:7; Phil 4:17"),
  ]},
  {"roman":"VI","title":"Cheerful for Good","subtitle":"A Settled, Glad Generosity","days":[
   (36,"Gladness That Stays","Cheerful giving as habit","2 Cor 9:7; Gal 6:9"),
   (37,"A Generous Eye","Blessed and blessing","Prov 22:9; Prov 11:25"),
   (38,"Ready and Willing","Glad on every occasion","2 Cor 9:11; 2 Cor 8:12"),
   (39,"Loved by God","The cheerful giver's joy","2 Cor 9:7; Heb 13:16"),
   (40,"Cheerful for Good","Glad-hearted giving for life","2 Cor 9:7; Acts 20:35"),
  ]},
 ],
}
