# -*- coding: utf-8 -*-
"""40-Day devotional maps — Batch 2 (nums 17-25):
finishing Foundations & Stewardship (17-18) and the full Fear, Anxiety & Peace
group (19-25). 6 movements aligned to the 6 sessions, 40 days in a 7-7-7-7-7-5 arc."""

MAPS = {
 # ---------------- 17 · Owned by Nothing ----------------
 17: [
  {"roman":"I","title":"Owned by Our Stuff","subtitle":"When Possessions Possess Us","days":[
   (1,"The Things We Own","They own us back","Luke 12:15; 1 Cor 6:12"),
   (2,"The Hidden Leash","Possessions that possess","Matt 19:21-22; Luke 12:34"),
   (3,"More to Maintain","Stuff demands upkeep","Eccl 5:11; Matt 6:19"),
   (4,"The Anxious Owner","Guarding what we hold","Luke 12:16-21; Prov 23:5"),
   (5,"Stuff as Security","A false refuge","Ps 62:10; Prov 18:11"),
   (6,"The Weight We Carry","Heavier than we know","Heb 12:1; Matt 11:28"),
   (7,"Who Owns Whom","An honest inventory","1 Cor 6:12; Luke 16:13"),
  ]},
  {"roman":"II","title":"Mastered by Nothing","subtitle":"Refusing the Grip","days":[
   (8,"Not Mastered by Anything","Paul's freedom","1 Cor 6:12; 1 Cor 10:23"),
   (9,"One Master Only","God, not things","Matt 6:24; Rom 6:16"),
   (10,"The Power to Say No","Refusing the grip","Titus 2:12; 1 Cor 9:25"),
   (11,"Free, Not Enslaved","Liberty in Christ","Gal 5:1; John 8:36"),
   (12,"Things in Their Place","Tools, not masters","1 Tim 6:17; Eccl 5:19"),
   (13,"Holding the Reins","Mastering possessions","Prov 25:28; 1 Cor 6:12"),
   (14,"Owned by God Alone","The only good Master","1 Cor 6:19-20; Ps 24:1"),
  ]},
  {"roman":"III","title":"Treasures That Rust","subtitle":"What Earthly Things Become","days":[
   (15,"Moth and Rust","Earthly treasure decays","Matt 6:19; Jas 5:2-3"),
   (16,"Here Today","The fleeting nature of stuff","Prov 23:5; 1 Pet 1:24"),
   (17,"Thieves Break In","Nothing is secure","Matt 6:19-20; Luke 12:33"),
   (18,"Treasure in Heaven","The store that lasts","Matt 6:20-21; 1 Tim 6:19"),
   (19,"What Outlasts You","Investing beyond the grave","Luke 12:20-21; Eccl 2:18"),
   (20,"Rich Toward God","The real wealth","Luke 12:21; Matt 6:20"),
   (21,"Where Your Heart Goes","Treasure pulls the heart","Matt 6:21; Col 3:1-2"),
  ]},
  {"roman":"IV","title":"Travel Light","subtitle":"Holding Everything Loosely","days":[
   (22,"Pilgrims and Strangers","Just passing through","1 Pet 2:11; Heb 11:13"),
   (23,"Take Nothing Extra","Light for the journey","Luke 9:3; Luke 10:4"),
   (24,"Loosen the Grip","Holding things openly","1 Tim 6:7; Job 1:21"),
   (25,"Lay It Aside","Dropping the weight","Heb 12:1; Phil 3:7-8"),
   (26,"Less to Protect","Freedom in fewer things","Matt 6:25; Luke 12:22-23"),
   (27,"Unencumbered","Free to follow","Matt 8:20; Luke 18:22"),
   (28,"Lighter Already","The traveler's relief","Matt 11:28-30; Ps 23:1-2"),
  ]},
  {"roman":"V","title":"Content With Less","subtitle":"The Secret Worth Learning","days":[
   (29,"The Secret Learned","Content in any state","Phil 4:11-12; 1 Tim 6:6"),
   (30,"Godliness With Contentment","Great gain","1 Tim 6:6-8; Heb 13:5"),
   (31,"Enough Is Plenty","Food and covering","1 Tim 6:8; Prov 30:8"),
   (32,"Never Forsaken","The ground of contentment","Heb 13:5; Deut 31:6"),
   (33,"Less, but Full","Abundance redefined","Phil 4:12; 2 Cor 6:10"),
   (34,"Free From Wanting","Desire at rest","Eccl 5:10; Ps 23:1"),
   (35,"Content and Free","Less holding us","Phil 4:11-13; 1 Tim 6:6"),
  ]},
  {"roman":"VI","title":"The Unburdened Life","subtitle":"Free of the Open Hand","days":[
   (36,"The Open Hand","Living loosely","1 Tim 6:7; Acts 20:35"),
   (37,"Light and Free","The unburdened way","Matt 11:30; Gal 5:1"),
   (38,"Held by Less","Owned by nothing","1 Cor 6:12; Luke 12:15"),
   (39,"Free to Give","Generosity from freedom","2 Cor 9:7; 1 Tim 6:18"),
   (40,"Owned by God Alone","The truly free life","1 Cor 6:19-20; Ps 16:5-6"),
  ]},
 ],
 # ---------------- 18 · The Steward's Mindset ----------------
 18: [
  {"roman":"I","title":"Belief vs. Wiring","subtitle":"Knowing One Thing, Living Another","days":[
   (1,"What You Say You Believe","Knowing versus living","Rom 12:2; Jas 1:22"),
   (2,"The Old Wiring","Default scarcity","Eph 4:22; Rom 8:5-6"),
   (3,"Patterns of This World","Conformed without noticing","Rom 12:2; 1 John 2:15-16"),
   (4,"The Grip Reflex","Wired to clutch","Luke 12:15; Prov 23:4"),
   (5,"Belief Meets Behavior","The honest gap","Jas 2:17; Matt 7:24"),
   (6,"Heart and Mind","Where money lives","Prov 4:23; Rom 12:2"),
   (7,"Ready to Rewire","Naming the patterns","Rom 12:2; Ps 139:23-24"),
  ]},
  {"roman":"II","title":"Renewing the Mind","subtitle":"Transformation by Renewal","days":[
   (8,"Transformed, Not Conformed","The renewal path","Rom 12:2; 2 Cor 5:17"),
   (9,"By the Renewing","How change comes","Rom 12:2; Eph 4:23"),
   (10,"A New Self","Put on the new","Eph 4:22-24; Col 3:9-10"),
   (11,"Set Your Mind Above","Aiming higher","Col 3:1-2; Phil 4:8"),
   (12,"The Word as Mirror","Renewed by truth","Ps 19:7; Jas 1:23-25"),
   (13,"Made New in Attitude","The mind's spirit","Eph 4:23; Rom 8:6"),
   (14,"Renewal in Progress","Daily transformation","2 Cor 4:16; Col 3:10"),
  ]},
  {"roman":"III","title":"New Default Settings","subtitle":"Replacing the Old Patterns","days":[
   (15,"New Defaults","Replacing the old","Eph 4:22-24; Rom 6:11"),
   (16,"From Grip to Open Hand","The new reflex","Acts 20:35; 2 Cor 9:7"),
   (17,"From Scarcity to Trust","A new baseline","Matt 6:33; Phil 4:19"),
   (18,"From Mine to His","The ownership shift","Ps 24:1; 1 Cor 4:7"),
   (19,"From Hoarding to Giving","Generosity by default","Prov 11:24-25; Luke 6:38"),
   (20,"From Fear to Peace","The settled setting","1 Pet 5:7; John 14:27"),
   (21,"Defaults Reset","The steward's baseline","Rom 12:2; Col 3:2"),
  ]},
  {"roman":"IV","title":"Capturing the Thoughts","subtitle":"Taking Every Thought Captive","days":[
   (22,"Take Thoughts Captive","Arresting the lie","2 Cor 10:5; Prov 4:23"),
   (23,"The Scarcity Thought","Catching it early","2 Cor 10:5; Phil 4:6"),
   (24,"Demolish the Strongholds","Tearing down lies","2 Cor 10:4-5; Eph 6:11"),
   (25,"Whatever Is True","Filtering the mind","Phil 4:8; Col 3:2"),
   (26,"Replace the Lie","Truth for falsehood","John 8:32; Ps 119:11"),
   (27,"Guard the Gate","Watching what enters","Prov 4:23; Phil 4:7"),
   (28,"Captive to Christ","Thoughts made obedient","2 Cor 10:5; Rom 8:6"),
  ]},
  {"roman":"V","title":"Thirty Days of Practice","subtitle":"Repetition Rewires","days":[
   (29,"Practice Makes New","Repetition rewires","1 Tim 4:7-8; Heb 5:14"),
   (30,"Daily Renewal","One day at a time","Lam 3:22-23; 2 Cor 4:16"),
   (31,"Train, Don't Try","Habits over willpower","1 Tim 4:7; 1 Cor 9:25"),
   (32,"Small Repeated Choices","The shaping power","Luke 16:10; Gal 6:9"),
   (33,"When You Slip","Grace to begin again","Prov 24:16; Phil 3:13-14"),
   (34,"Renewed by Habit","Practice into character","Heb 5:14; Rom 12:2"),
   (35,"Thirty Days In","The new groove","Gal 6:9; 2 Cor 4:16"),
  ]},
  {"roman":"VI","title":"The Steward by Default","subtitle":"A New Automatic Posture","days":[
   (36,"A New Automatic","Stewardship without thinking","Rom 12:2; Col 3:23"),
   (37,"The Settled Mind","Peace as baseline","Isa 26:3; Phil 4:7"),
   (38,"Open-Handed by Nature","Generosity built in","2 Cor 9:7; Acts 20:35"),
   (39,"The Renewed Steward","Mind made new","Rom 12:2; Eph 4:23"),
   (40,"Steward by Default","The transformed life","Rom 12:1-2; 2 Cor 5:17"),
  ]},
 ],
 # ---------------- 19 · When Money Keeps You Up at Night ----------------
 19: [
  {"roman":"I","title":"The 3 A.M. Fear","subtitle":"The Worry That Wakes Us","days":[
   (1,"Awake at 3 A.M.","The fear that wakes us","Ps 4:8; Ps 77:4"),
   (2,"The Racing Mind","Worry's midnight loop","Ps 94:19; Matt 6:34"),
   (3,"What If","The endless question","Matt 6:27; Ps 56:3"),
   (4,"The Weight in the Dark","Fear feels heavier at night","Ps 42:8; Ps 30:5"),
   (5,"You Are Not Alone","God is awake too","Ps 121:3-4; Ps 139:11-12"),
   (6,"He Hears the Night Cry","Prayers in the dark","Ps 4:1; Ps 42:8"),
   (7,"Naming the Fear","Bringing it to God","Ps 4:8; 1 Pet 5:7"),
  ]},
  {"roman":"II","title":"Why It's Worse at Night","subtitle":"When Darkness Magnifies","days":[
   (8,"Darkness Magnifies","Why night feels worse","Ps 30:5; Ps 143:8"),
   (9,"The Lies We Believe","Midnight isn't reliable","Ps 56:3-4; Isa 41:10"),
   (10,"Joy Comes in the Morning","Weeping for a night","Ps 30:5; Lam 3:22-23"),
   (11,"The Watches of the Night","Remembering Him","Ps 63:6; Ps 119:148"),
   (12,"Light in the Dark","He is still near","Ps 139:11-12; John 1:5"),
   (13,"Songs in the Night","The comfort He gives","Job 35:10; Ps 42:8"),
   (14,"Holding to Morning","Trust until light","Ps 130:5-6; Ps 30:5"),
  ]},
  {"roman":"III","title":"Casting the Care","subtitle":"Releasing It to Him","days":[
   (15,"Cast It on Him","The invitation to release","1 Pet 5:7; Ps 55:22"),
   (16,"He Cares for You","The reason we can","1 Pet 5:7; Matt 6:26"),
   (17,"Roll the Burden","Handing it over","Ps 55:22; Ps 37:5"),
   (18,"Prayer Instead of Worry","The exchange","Phil 4:6-7; Ps 62:8"),
   (19,"Pour Out Your Heart","Honesty before God","Ps 62:8; Ps 142:1-2"),
   (20,"Leave It With Him","Not taking it back","1 Pet 5:7; Matt 11:28"),
   (21,"The Care Released","Hands and heart open","Ps 55:22; Phil 4:6-7"),
  ]},
  {"roman":"IV","title":"He Gives Sleep","subtitle":"Rest as His Gift","days":[
   (22,"He Grants Sleep","Rest as a gift","Ps 127:2; Prov 3:24"),
   (23,"In Peace I Lie Down","Safety in Him","Ps 4:8; Ps 3:5"),
   (24,"Sweet Sleep","No more dread","Prov 3:24; Ps 127:2"),
   (25,"He Sustains Me","Waking again","Ps 3:5; Ps 121:7-8"),
   (26,"Lie Down Unafraid","Security restored","Lev 26:6; Ps 4:8"),
   (27,"The Beloved's Rest","He provides while we sleep","Ps 127:2; Matt 6:33"),
   (28,"Rest Restored","Nights made calm","Ps 4:8; Ps 91:1-2"),
  ]},
  {"roman":"V","title":"Tomorrow's Worries","subtitle":"Today Has Enough","days":[
   (29,"Not About Tomorrow","Today's grace for today","Matt 6:34; Lam 3:23"),
   (30,"Each Day's Trouble","Enough for today","Matt 6:34; Ps 68:19"),
   (31,"Daily Bread","Provision day by day","Matt 6:11; Ex 16:4"),
   (32,"He Goes Before","Tomorrow is His","Deut 31:8; Jer 29:11"),
   (33,"Borrowing Trouble","The futility of worry","Matt 6:27; Luke 12:25-26"),
   (34,"New Mercies Tomorrow","They will be there","Lam 3:22-23; Ps 23:6"),
   (35,"Tomorrow in His Hands","Released again","Matt 6:34; Prov 27:1"),
  ]},
  {"roman":"VI","title":"Rest for the Weary","subtitle":"Coming to Him","days":[
   (36,"Come, All Who Are Weary","The gentle invitation","Matt 11:28; Ps 23:2-3"),
   (37,"He Gives Rest","The promise","Matt 11:28-29; Ex 33:14"),
   (38,"Be Still","Quiet before Him","Ps 46:10; Ps 62:1"),
   (39,"Peace at Night","Settled in trust","Ps 4:8; John 14:27"),
   (40,"Sleeping in Peace","Rest restored for good","Ps 4:8; Ps 127:2"),
  ]},
 ],
 # ---------------- 20 · Anxious for Nothing ----------------
 20: [
  {"roman":"I","title":"The Command and the Method","subtitle":"Worry Traded for Prayer","days":[
   (1,"Do Not Be Anxious","The hard command","Phil 4:6; Matt 6:25"),
   (2,"About Anything","Nothing excluded","Phil 4:6; 1 Pet 5:7"),
   (3,"But in Prayer","The method given","Phil 4:6; Ps 62:8"),
   (4,"By Petition","Asking specifically","Phil 4:6; Matt 7:7"),
   (5,"Present Your Requests","Bringing it to God","Phil 4:6; Ps 37:5"),
   (6,"The Exchange","Worry for prayer","Phil 4:6-7; 1 Pet 5:7"),
   (7,"Beginning the Practice","Anxiety to petition","Phil 4:6; Ps 55:22"),
  ]},
  {"roman":"II","title":"In Every Situation","subtitle":"No Exceptions","days":[
   (8,"In Every Situation","No exceptions","Phil 4:6; 1 Thess 5:18"),
   (9,"The Big and Small","All of it","Luke 12:7; Matt 10:30-31"),
   (10,"When You Don't Know How","The Spirit helps","Rom 8:26; Ps 46:1"),
   (11,"In the Waiting","Praying through delay","Ps 27:14; Ps 40:1"),
   (12,"In the Worst Case","God is still there","Ps 23:4; Isa 43:2"),
   (13,"Continually","Pray without ceasing","1 Thess 5:17; Luke 18:1"),
   (14,"Every Care Brought","Nothing held back","Phil 4:6; 1 Pet 5:7"),
  ]},
  {"roman":"III","title":"With Thanksgiving","subtitle":"The Key Ingredient","days":[
   (15,"With Thanksgiving","The key ingredient","Phil 4:6; Ps 100:4"),
   (16,"Remember His Faithfulness","Counting past mercy","Ps 103:2; Lam 3:22-23"),
   (17,"Gratitude Shifts the Heart","From fear to praise","Ps 95:2; Col 3:15-17"),
   (18,"Give Thanks in All","Even here","1 Thess 5:18; Eph 5:20"),
   (19,"Thankful for Enough","Naming provision","Phil 4:11-12; 1 Tim 6:8"),
   (20,"Praise Before the Answer","Trust expressed","Ps 56:3-4; 2 Chr 20:21"),
   (21,"A Grateful Heart","Anxiety loosened","Phil 4:6; Ps 107:1"),
  ]},
  {"roman":"IV","title":"The Peace That Guards","subtitle":"What Follows Prayer","days":[
   (22,"The Peace of God","What follows prayer","Phil 4:7; John 14:27"),
   (23,"Beyond Understanding","Peace that defies sense","Phil 4:7; Isa 26:3"),
   (24,"It Guards the Heart","A garrison around you","Phil 4:7; Ps 121:7-8"),
   (25,"And the Mind","Thoughts kept safe","Phil 4:7; Isa 26:3"),
   (26,"In Christ Jesus","Where peace is kept","Phil 4:7; John 16:33"),
   (27,"Not as the World Gives","A deeper peace","John 14:27; Ps 4:8"),
   (28,"Guarded and Kept","The peace settles in","Phil 4:7; Ps 29:11"),
  ]},
  {"roman":"V","title":"Thinking on These Things","subtitle":"Retraining the Mind","days":[
   (29,"Whatever Is True","Filtering thoughts","Phil 4:8; 2 Cor 10:5"),
   (30,"Whatever Is Noble","Aiming the mind","Phil 4:8; Col 3:2"),
   (31,"Whatever Is Lovely","Dwelling on good","Phil 4:8; Ps 19:14"),
   (32,"Whatever Is Admirable","Choosing focus","Phil 4:8; Prov 4:23"),
   (33,"Think on These","The mind retrained","Phil 4:8; Rom 12:2"),
   (34,"Renewing the Mind","Replacing worry","Rom 12:2; Eph 4:23"),
   (35,"A Mind Set Right","Peace through focus","Phil 4:8; Isa 26:3"),
  ]},
  {"roman":"VI","title":"A Practiced Peace","subtitle":"Peace as a Habit","days":[
   (36,"Put It Into Practice","Peace as habit","Phil 4:9; Jas 1:22"),
   (37,"The God of Peace","With you","Phil 4:9; Rom 15:33"),
   (38,"Day by Day","Practiced repeatedly","Lam 3:22-23; 2 Cor 4:16"),
   (39,"Anxious for Nothing","The settled heart","Phil 4:6-7; 1 Pet 5:7"),
   (40,"Kept in Peace","Worry replaced","Phil 4:7; Isa 26:3"),
  ]},
 ],
 # ---------------- 21 · The God of Enough ----------------
 21: [
  {"roman":"I","title":"The Scarcity Lie","subtitle":"Believing There's Never Enough","days":[
   (1,"Never Enough","The lie we believe","Eccl 5:10; Prov 27:20"),
   (2,"The Fear of Lack","Scarcity's grip","Matt 6:31; Ps 23:1"),
   (3,"Where the Lie Leads","Hoarding and fear","Luke 12:16-21; 1 Tim 6:9"),
   (4,"Manna and Trust","Enough for the day","Ex 16:18; Matt 6:11"),
   (5,"The Gripping Hand","Holding too tight","Luke 12:15; Eccl 5:13"),
   (6,"Counterfeit Security","Money's empty promise","Prov 18:11; Ps 62:10"),
   (7,"Naming the Lie","Scarcity exposed","2 Cor 9:8; Phil 4:19"),
  ]},
  {"roman":"II","title":"The God Who Abounds","subtitle":"More Than Enough in Him","days":[
   (8,"God Is Able","The abounding God","2 Cor 9:8; Eph 3:20"),
   (9,"All Grace Abounding","More than enough","2 Cor 9:8; John 1:16"),
   (10,"Immeasurably More","Beyond what we ask","Eph 3:20; Ps 23:5"),
   (11,"His Glorious Riches","The supply source","Phil 4:19; Rom 11:33"),
   (12,"Opening His Hand","He satisfies","Ps 145:16; Ps 104:28"),
   (13,"The Cattle on the Hills","He owns it all","Ps 50:10-12; Hag 2:8"),
   (14,"A God Who Overflows","Abundance in Him","2 Cor 9:8; Eph 3:20"),
  ]},
  {"roman":"III","title":"All You Need","subtitle":"The Promise of Sufficiency","days":[
   (15,"All That You Need","The promise","2 Cor 9:8; Phil 4:19"),
   (16,"In All Things, All Times","Always sufficient","2 Cor 9:8; Ps 23:1"),
   (17,"My God Will Meet","Every need supplied","Phil 4:19; Matt 6:33"),
   (18,"Seek First","Needs added to you","Matt 6:33; Luke 12:31"),
   (19,"The Lord My Shepherd","I lack nothing","Ps 23:1; Ps 34:9-10"),
   (20,"Daily Provision","Enough each day","Matt 6:11; Lam 3:23"),
   (21,"Sufficient Grace","Enough for everything","2 Cor 12:9; 2 Cor 9:8"),
  ]},
  {"roman":"IV","title":"From Gripping to Giving","subtitle":"Enough That Flows Out","days":[
   (22,"Enough to Share","Abundance for others","2 Cor 9:8; 2 Cor 9:11"),
   (23,"So You Can Give","The purpose of plenty","2 Cor 9:8; Eph 4:28"),
   (24,"The Open Hand","Letting go in trust","Acts 20:35; Prov 11:24-25"),
   (25,"Sowing Generously","The generous reaping","2 Cor 9:6; Luke 6:38"),
   (26,"Giving Breaks Scarcity","Trust in action","2 Cor 9:7; Mal 3:10"),
   (27,"Cheerful, Not Grudging","The freed giver","2 Cor 9:7; Prov 22:9"),
   (28,"From Grip to Gift","Enough flows out","2 Cor 9:8; Acts 20:35"),
  ]},
  {"roman":"V","title":"The Shepherd's Supply","subtitle":"He Leads and Provides","days":[
   (29,"The Lord My Shepherd","He provides","Ps 23:1; John 10:11"),
   (30,"Green Pastures","Rest and supply","Ps 23:2; Ps 37:25"),
   (31,"He Restores","Renewed by Him","Ps 23:3; Phil 4:19"),
   (32,"A Table Prepared","Provision before enemies","Ps 23:5; Ps 78:19"),
   (33,"My Cup Overflows","More than enough","Ps 23:5; Ps 16:5"),
   (34,"Goodness Follows","All my days","Ps 23:6; Ps 84:11"),
   (35,"The Shepherd Provides","Want gives way","Ps 23:1; Ps 34:10"),
  ]},
  {"roman":"VI","title":"Living From Enough","subtitle":"The Settled, Generous Life","days":[
   (36,"Living From Enough","The settled life","1 Tim 6:6-8; Phil 4:11-12"),
   (37,"Content and Generous","Enough overflowing","2 Cor 9:8; 1 Tim 6:6"),
   (38,"No More Gripping","Hands held open","Luke 12:15; Heb 13:5"),
   (39,"The God of Enough","Trust takes root","2 Cor 9:8; Phil 4:19"),
   (40,"Abounding in All","Enough and to spare","2 Cor 9:8; Eph 3:20"),
  ]},
 ],
 # ---------------- 22 · Calm in the Storm ----------------
 22: [
  {"roman":"I","title":"The Sudden Storm","subtitle":"When Crisis Hits Without Warning","days":[
   (1,"The Squall Rises","Crisis without warning","Mark 4:37; Ps 46:1-3"),
   (2,"Waves Breaking Over","When it overwhelms","Ps 69:1-2; Ps 42:7"),
   (3,"The Sinking Feeling","Fear takes hold","Matt 14:30; Ps 18:4"),
   (4,"In the Same Boat","Jesus is with you","Mark 4:36; Matt 28:20"),
   (5,"A Refuge and Strength","Where to run","Ps 46:1; Nah 1:7"),
   (6,"Storms Will Come","Expecting the wind","John 16:33; Matt 7:25"),
   (7,"Naming the Storm","Honest before Him","Mark 4:38; Ps 107:28"),
  ]},
  {"roman":"II","title":"Where Is Jesus?","subtitle":"He Has Not Forgotten You","days":[
   (8,"Asleep in the Stern","He seems far","Mark 4:38; Ps 44:23-24"),
   (9,"Do You Not Care?","The fearful question","Mark 4:38; Ps 22:1-2"),
   (10,"He Has Not Forgotten","Ever-present help","Ps 46:1; Isa 49:15-16"),
   (11,"Closer Than You Think","With you in it","Ps 23:4; Matt 28:20"),
   (12,"He Sees the Storm","Nothing escapes Him","Ps 33:13-15; Heb 4:13"),
   (13,"Calling Out to Him","Waking faith","Mark 4:38; Ps 107:28"),
   (14,"Present in the Wind","Jesus in the boat","Mark 4:38; Isa 43:2"),
  ]},
  {"roman":"III","title":"Quiet, Be Still","subtitle":"His Word to the Storm","days":[
   (15,"Quiet! Be Still!","His word to the storm","Mark 4:39; Ps 107:29"),
   (16,"He Rebukes the Wind","Authority over chaos","Mark 4:39; Ps 89:9"),
   (17,"Complete Calm","The sudden stillness","Mark 4:39; Ps 107:29-30"),
   (18,"Be Still and Know","Stillness before God","Ps 46:10; Ex 14:14"),
   (19,"Peace in His Voice","The word that calms","Mark 4:39; John 14:27"),
   (20,"He Stills the Storm","The chaos hushed","Ps 107:29; Ps 65:7"),
   (21,"Calm Restored","Quiet after the word","Mark 4:39; Ps 46:10"),
  ]},
  {"roman":"IV","title":"An Anchor That Holds","subtitle":"Hope, Firm and Secure","days":[
   (22,"An Anchor for the Soul","Hope that holds","Heb 6:19; Ps 62:5-6"),
   (23,"Firm and Secure","The steadfast hope","Heb 6:19; Ps 112:7"),
   (24,"The Rock Beneath","Founded on Christ","Matt 7:24-25; Ps 18:2"),
   (25,"Why Are You Afraid?","Faith over fear","Mark 4:40; 2 Tim 1:7"),
   (26,"Do You Still Not Trust?","Faith invited","Mark 4:40; Heb 11:1"),
   (27,"Held by the Anchor","Steady in the swell","Heb 6:19; Ps 16:8"),
   (28,"Anchored, Not Adrift","The soul secured","Heb 6:19; Ps 62:6"),
  ]},
  {"roman":"V","title":"Through the Waters","subtitle":"He Brings Us Across","days":[
   (29,"When You Pass Through","He is with you","Isa 43:2; Ps 23:4"),
   (30,"The Waters Won't Sweep","A sure promise","Isa 43:2; Ps 69:15"),
   (31,"Through, Not Around","He brings us across","Isa 43:2; Josh 1:9"),
   (32,"The Lord Is Good","A refuge in trouble","Nah 1:7; Ps 9:9"),
   (33,"He Knows His Own","Cared for in the storm","Nah 1:7; John 10:14"),
   (34,"Brought to Safe Harbor","Guided to rest","Ps 107:30; Ps 48:14"),
   (35,"Through the Waters","Carried by Him","Isa 43:2; Ps 32:6"),
  ]},
  {"roman":"VI","title":"After the Storm","subtitle":"Peace on the Far Side","days":[
   (36,"The Calm That Follows","Peace on the far side","Ps 107:29-30; Mark 4:39"),
   (37,"What the Storm Taught","Faith grown","Jas 1:2-4; Rom 5:3-4"),
   (38,"He Was Always There","Seeing in hindsight","Ps 46:1; Isa 43:2"),
   (39,"Steady Going Forward","Trust that remains","Ps 112:7; Mark 4:40"),
   (40,"Calm in the Storm","Anchored in Him","Mark 4:39; Heb 6:19"),
  ]},
 ],
 # ---------------- 23 · Provision Over Panic ----------------
 23: [
  {"roman":"I","title":"The Panic Reflex","subtitle":"The Body's First Response","days":[
   (1,"The Panic Reflex","The body's first response","Ps 56:3; Isa 41:10"),
   (2,"The Spike of Fear","When the news hits","Ps 112:7; Prov 3:25"),
   (3,"The Spiral","Fear feeding fear","Matt 6:27; Ps 94:19"),
   (4,"Fight or Flight","The reflex named","Ps 55:4-5; Ps 56:3"),
   (5,"The Reflex Isn't Truth","Feelings versus facts","Ps 42:5; Isa 41:10"),
   (6,"A Better Reflex","Trust can be trained","Ps 56:3-4; Prov 3:5"),
   (7,"Catching the Panic","The first step","Isa 41:10; Ps 56:3"),
  ]},
  {"roman":"II","title":"Do Not Fear","subtitle":"For I Am With You","days":[
   (8,"Do Not Fear","The repeated command","Isa 41:10; Josh 1:9"),
   (9,"For I Am With You","The reason given","Isa 41:10; Deut 31:6"),
   (10,"I Am Your God","Whose you are","Isa 41:10; Ps 46:1"),
   (11,"I Will Strengthen You","Help promised","Isa 41:10; Ps 28:7"),
   (12,"I Will Help You","Never alone","Isa 41:10; Ps 121:1-2"),
   (13,"Upheld by His Hand","The righteous right hand","Isa 41:10; Ps 63:8"),
   (14,"Fear Dismissed","Trust takes its place","Isa 41:10; 2 Tim 1:7"),
  ]},
  {"roman":"III","title":"He Has Provided Before","subtitle":"Remembering His Track Record","days":[
   (15,"Remember the Manna","He fed them daily","Ex 16:15; Ps 78:23-25"),
   (16,"Ebenezer","Thus far He has helped","1 Sam 7:12; Ps 71:17"),
   (17,"The Ravens Fed Elijah","Provision in famine","1 Kgs 17:4-6; Ps 37:25"),
   (18,"Five Loaves, Thousands Fed","More than enough","Matt 14:19-20; John 6:11"),
   (19,"He Has Not Failed","A track record","Josh 23:14; Lam 3:22-23"),
   (20,"Count the Times","Remembering provision","Ps 103:2; Deut 8:2-4"),
   (21,"Provision Remembered","Past mercy fuels trust","Ps 77:11; Phil 4:19"),
  ]},
  {"roman":"IV","title":"Catching the Spike","subtitle":"Interrupting the Panic","days":[
   (22,"Catch It Early","Naming the fear","Ps 56:3; 2 Cor 10:5"),
   (23,"When I Am Afraid","The honest move","Ps 56:3; Ps 34:4"),
   (24,"Trust on Purpose","A chosen response","Ps 56:3-4; Prov 3:5"),
   (25,"Pause and Pray","Interrupting panic","Phil 4:6; 1 Pet 5:7"),
   (26,"Preach to Yourself","Why so downcast?","Ps 42:5; Ps 42:11"),
   (27,"Replace the Spike","Truth over reflex","Isa 41:10; Ps 56:3-4"),
   (28,"Spike Intercepted","The fear caught","Ps 56:3; Isa 41:10"),
  ]},
  {"roman":"V","title":"The Trust Reflex","subtitle":"A New Default Response","days":[
   (29,"A New Reflex","Trust by habit","Ps 112:7; Prov 3:5-6"),
   (30,"No Fear of Bad News","The steadfast heart","Ps 112:7; Ps 57:7"),
   (31,"Heart Steadfast","Fixed on the Lord","Ps 112:7-8; Isa 26:3"),
   (32,"Trusting in the Lord","Where security rests","Ps 112:7; Jer 17:7"),
   (33,"Like a Tree by Water","Unshaken in drought","Jer 17:7-8; Ps 1:3"),
   (34,"The Reflex Rewired","Trust comes first","Ps 112:7; Prov 3:5"),
   (35,"Steady Heart","Trust the new default","Ps 112:7; Isa 41:10"),
  ]},
  {"roman":"VI","title":"Steady Under Pressure","subtitle":"Calm When It Hits","days":[
   (36,"Steady Under Pressure","Calm when it hits","Ps 112:7-8; Isa 41:10"),
   (37,"He Goes Before","Provision ahead","Deut 31:8; Ps 23:1"),
   (38,"Provision Over Panic","The trade made","Isa 41:10; Phil 4:19"),
   (39,"Not Shaken","Firm in the test","Ps 16:8; Ps 112:6"),
   (40,"Trust Over Fear","The settled response","Isa 41:10; Ps 56:3-4"),
  ]},
 ],
 # ---------------- 24 · The Worry-Free Wallet ----------------
 24: [
  {"roman":"I","title":"More Than \u201cDon't Worry\u201d","subtitle":"The Command in Context","days":[
   (1,"Therefore I Tell You","The command in context","Matt 6:25; Luke 12:22"),
   (2,"Do Not Worry","About your life","Matt 6:25; Phil 4:6"),
   (3,"More Than Food","Life is bigger","Matt 6:25; Luke 12:23"),
   (4,"Worry Adds Nothing","The futility","Matt 6:27; Luke 12:25-26"),
   (5,"Worry and Trust","What's really at stake","Matt 6:30; Ps 37:3"),
   (6,"A Habit, Not a Feeling","Worry can be unlearned","Matt 6:34; Rom 12:2"),
   (7,"Beginning to Trust","Replacing worry","Matt 6:25; Ps 55:22"),
  ]},
  {"roman":"II","title":"Consider the Birds","subtitle":"Your Father Feeds Them","days":[
   (8,"Look at the Birds","They neither sow nor reap","Matt 6:26; Luke 12:24"),
   (9,"Your Father Feeds Them","The point of the lesson","Matt 6:26; Ps 147:9"),
   (10,"Worth More Than Sparrows","Your value to Him","Matt 6:26; Matt 10:31"),
   (11,"Consider the Lilies","Clothed by God","Matt 6:28-29; Luke 12:27"),
   (12,"Will He Not Clothe You?","Of little faith","Matt 6:30; Matt 8:26"),
   (13,"He Knows Your Needs","Before you ask","Matt 6:32; Matt 6:8"),
   (14,"Considered and Cared For","Worry quieted","Matt 6:26; Ps 84:11"),
  ]},
  {"roman":"III","title":"Daily Bread Habits","subtitle":"Seeking First, One Day at a Time","days":[
   (15,"Give Us This Day","Praying for daily bread","Matt 6:11; Prov 30:8"),
   (16,"One Day at a Time","Manna habits","Ex 16:4; Lam 3:23"),
   (17,"Enough for Today","Not stockpiling fear","Matt 6:34; Ex 16:19-20"),
   (18,"Seek First the Kingdom","The reordering","Matt 6:33; Luke 12:31"),
   (19,"These Things Added","Provision follows","Matt 6:33; Ps 37:25"),
   (20,"A Habit of Asking","Prayer over panic","Phil 4:6; Matt 7:7-8"),
   (21,"Daily Bread, Daily Trust","The settled rhythm","Matt 6:11; Lam 3:22-23"),
  ]},
  {"roman":"IV","title":"Neither Poverty Nor Riches","subtitle":"The Wisdom of Enough","days":[
   (22,"Two Things I Ask","Agur's prayer","Prov 30:7; Prov 30:8"),
   (23,"Keep Falsehood Far","An honest heart","Prov 30:8; Ps 119:29"),
   (24,"Neither Poverty Nor Riches","The wise middle","Prov 30:8; 1 Tim 6:8"),
   (25,"Only My Daily Bread","Just enough","Prov 30:8; Matt 6:11"),
   (26,"Lest I Be Full","The danger of too much","Prov 30:9; Deut 8:12-14"),
   (27,"Lest I Be Poor","The danger of too little","Prov 30:9; Prov 6:30-31"),
   (28,"Content With Enough","The worry-free middle","Prov 30:8-9; 1 Tim 6:6-8"),
  ]},
  {"roman":"V","title":"Contentment Practiced","subtitle":"Peace Becomes a Habit","days":[
   (29,"The Secret of Content","Learned, not natural","Phil 4:11-12; 1 Tim 6:6"),
   (30,"Free From Love of Money","The guardrail","Heb 13:5; Luke 12:15"),
   (31,"Never Will I Forsake","The anchor of content","Heb 13:5; Deut 31:6"),
   (32,"Never Seen Them Forsaken","The righteous provided for","Ps 37:25; Ps 37:18-19"),
   (33,"Enough and Thankful","Gratitude practiced","1 Thess 5:18; Phil 4:6"),
   (34,"Wanting Less","Contentment grows","Eccl 5:10; 1 Tim 6:8"),
   (35,"Contentment Practiced","Peace becomes habit","Phil 4:11-13; Heb 13:5"),
  ]},
  {"roman":"VI","title":"The Worry-Free Wallet","subtitle":"Carrying Money in Peace","days":[
   (36,"Money Without Dread","Carrying it lightly","Matt 6:25; 1 Pet 5:7"),
   (37,"A Plan, Not Panic","Practical peace","Prov 21:5; Matt 6:34"),
   (38,"Trust Over Worry","The daily choice","Matt 6:25-26; Ps 37:3"),
   (39,"The Worry-Free Wallet","Settled with money","Matt 6:33-34; Phil 4:6-7"),
   (40,"Carried in Peace","Worry left behind","Matt 6:25; Ps 23:1"),
  ]},
 ],
 # ---------------- 25 · Trusting Through Uncertainty ----------------
 25: [
  {"roman":"I","title":"The Fog Ahead","subtitle":"When the Future Won't Focus","days":[
   (1,"The Road Unclear","When the future blurs","Prov 3:5; Jas 4:14"),
   (2,"Not Knowing","The discomfort of fog","Eccl 8:7; Prov 27:1"),
   (3,"The Urge to Figure It Out","Leaning on self","Prov 3:5; Prov 28:26"),
   (4,"What We Cannot See","Limits of our sight","1 Cor 13:12; 2 Cor 5:7"),
   (5,"He Sees the Whole Road","God's full view","Isa 46:9-10; Ps 139:16"),
   (6,"Fog Is Not Absence","He's still there","Ps 23:4; Deut 31:8"),
   (7,"Trusting in the Fog","The first step","Prov 3:5; Ps 32:8"),
  ]},
  {"roman":"II","title":"Lean Not on Understanding","subtitle":"Trusting With the Whole Heart","days":[
   (8,"Trust With All Your Heart","The whole-hearted call","Prov 3:5; Ps 37:5"),
   (9,"Lean Not on Your Own","The warning","Prov 3:5; Prov 14:12"),
   (10,"In All Your Ways","Acknowledge Him","Prov 3:6; Ps 25:4-5"),
   (11,"He Will Make Straight","The promise","Prov 3:6; Isa 45:2"),
   (12,"Wiser Than We Know","His thoughts higher","Isa 55:8-9; Rom 11:33-34"),
   (13,"The Fool Trusts Himself","A better way","Prov 28:26; Jer 17:5"),
   (14,"Leaning on Him","Self set aside","Prov 3:5-6; Ps 62:8"),
  ]},
  {"roman":"III","title":"Plans and Providence","subtitle":"We Plan, He Directs","days":[
   (15,"We Plan Our Course","The human part","Prov 16:9; Prov 19:21"),
   (16,"The Lord Directs Steps","The divine part","Prov 16:9; Ps 37:23"),
   (17,"Many Plans","His purpose prevails","Prov 19:21; Isa 14:24"),
   (18,"Commit Your Way","Plans entrusted","Ps 37:5; Prov 16:3"),
   (19,"Plans to Prosper You","His good intent","Jer 29:11; Rom 8:28"),
   (20,"Held by Providence","Even the detours","Gen 50:20; Rom 8:28"),
   (21,"Planning, Then Trusting","Both held together","Prov 16:9; Jas 4:15"),
  ]},
  {"roman":"IV","title":"A Lamp for the Next Step","subtitle":"Enough Light to Walk","days":[
   (22,"A Lamp to My Feet","Light for the step","Ps 119:105; Prov 4:18"),
   (23,"Not the Whole Road","Just enough light","Ps 119:105; 2 Cor 5:7"),
   (24,"This Is the Way","The guiding whisper","Isa 30:21; Ps 32:8"),
   (25,"I Will Guide You","His counsel promised","Ps 32:8; Ps 73:24"),
   (26,"Step by Step","Following the light","Ps 37:23-24; Prov 3:6"),
   (27,"The Path Grows Brighter","Clarity in time","Prov 4:18; Ps 84:11"),
   (28,"The Next Step Lit","Trust for today","Ps 119:105; Matt 6:34"),
  ]},
  {"roman":"V","title":"If the Lord Wills","subtitle":"Holding the Future Loosely","days":[
   (29,"If the Lord Wills","The humble posture","Jas 4:15; Prov 19:21"),
   (30,"You Don't Know Tomorrow","A mist that vanishes","Jas 4:14; Prov 27:1"),
   (31,"Holding Plans Loosely","Open hands","Jas 4:13-15; Ps 31:15"),
   (32,"My Times in His Hands","Trusting the timing","Ps 31:15; Eccl 3:1"),
   (33,"Not My Will","Surrender modeled","Luke 22:42; Matt 6:10"),
   (34,"Submitting the Future","His will be done","Jas 4:15; 1 John 5:14"),
   (35,"Held by His Will","Plans surrendered","Jas 4:15; Ps 31:15"),
  ]},
  {"roman":"VI","title":"Walking by Faith","subtitle":"One Step at a Time","days":[
   (36,"By Faith, Not Sight","How we walk","2 Cor 5:7; Heb 11:1"),
   (37,"One Step at a Time","Faith in motion","Ps 119:105; Prov 3:6"),
   (38,"Faith Like Abraham","Going without knowing","Heb 11:8; Rom 4:20-21"),
   (39,"Trusting Through Uncertainty","The settled walk","Prov 3:5-6; Ps 32:8"),
   (40,"He Makes the Path Straight","Faith's reward","Prov 3:6; Isa 42:16"),
  ]},
 ],
}
