# -*- coding: utf-8 -*-
"""Volume 2, Batch 4 — architecture blueprints, Groups 10-12:
Money & the Heart, Marriage & Family, Seasons & Life Stages."""

DEF = ["4-Session", "6-Session", "21-Day", "30-Day", "40-Day"]
T1 = "Tier 1 — Church & Company"
T2 = "Tier 2 — Church"

GROUP_DESC = {
    "Money & the Heart":
        "The deepest money work of all \u2014 idolatry, identity, and the slow shaping of the soul, where the real treasure is revealed.",
    "Marriage & Family":
        "Money wisdom for the home \u2014 raising money-smart, generous kids and building open, united households for the next generation.",
    "Seasons & Life Stages":
        "Money for every chapter \u2014 from the first paycheck to the final lap, and through the hardest seasons in between.",
}

ARCH = [
 # ---------------- MONEY & THE HEART ----------------
 {
  "num": 70, "group": "Money & the Heart",
  "title": "The Idol of Money",
  "tagline": "Confronting Money's Bid to Become Your Master",
  "tier": T1, "audience": "All Church \u00b7 Workplace Teams \u00b7 Heart Examiners",
  "core_ref": "Matthew 6:24 (NIV)",
  "core_text": "No one can serve two masters. You cannot serve both God and money.",
  "marketing": "Money makes a quiet, relentless bid to become the master it was never meant to be. This study confronts that idolatry head-on, exposing the false god that promises security and demands everything \u2014 and pointing back to the only Master worth serving. Because no one can serve both God and money.",
  "felt_need": "A growing sense that money has quietly taken a place only God should hold.",
  "why_matters": "Jesus said plainly we cannot serve both God and money; one will be master.",
  "problem": "Money slips onto the throne so gradually we rarely notice it has become our god.",
  "transformation": "From quietly serving money to serving God with money as a tool, not a master.",
  "formats": DEF,
  "sessions": [
   ("The Quiet Bid", "How money seeks the throne"),
   ("Two Masters", "Why we can't serve both"),
   ("The False God's Promise", "What the idol offers and demands"),
   ("Spotting the Idol", "Signs money has taken over"),
   ("Dethroning Money", "Returning God to first place"),
   ("One Master", "Serving God, using money"),
  ],
  "scriptures": ["Matthew 6:24", "Colossians 3:5", "Exodus 20:3-4", "Luke 16:13", "1 John 2:15-16"],
 },
 {
  "num": 71, "group": "Money & the Heart",
  "title": "You Are Not Your Net Worth",
  "tagline": "Untangling Your Worth From Your Bank Balance",
  "tier": T1, "audience": "All Church \u00b7 Young Adults \u00b7 Workplace Teams",
  "core_ref": "1 Samuel 16:7 (NIV)",
  "core_text": "The Lord does not look at the things people look at... the Lord looks at the heart.",
  "marketing": "Somewhere along the way, many of us started measuring our worth by a number \u2014 the balance, the salary, the score. This study cuts that cord, untangling identity from net worth and re-anchoring our value where God places it: not in what we have, but in who we are to Him.",
  "felt_need": "Tying my sense of worth and identity to the number in my bank account.",
  "why_matters": "God does not measure us by outward things; He looks at the heart, not the balance.",
  "problem": "We let net worth define self-worth, so our identity rises and falls with money.",
  "transformation": "From identity tied to a number to worth anchored in who God says you are.",
  "formats": DEF,
  "sessions": [
   ("The Number That Defines Us", "When worth becomes net worth"),
   ("God Looks at the Heart", "A different measure of value"),
   ("Made in His Image", "Worth that money can't touch"),
   ("The Rise and Fall", "Why money is a cruel scorekeeper"),
   ("Cutting the Cord", "Untangling identity from income"),
   ("More Than a Number", "Resting in God-given worth"),
  ],
  "scriptures": ["1 Samuel 16:7", "Luke 12:15", "Galatians 2:20", "Psalm 139:13-14", "1 Peter 2:9"],
 },
 {
  "num": 72, "group": "Money & the Heart",
  "title": "The Love of Money",
  "tagline": "A Clear-Eyed Look at the Root \u2014 and the Freedom Beyond",
  "tier": T1, "audience": "All Church \u00b7 Small Groups \u00b7 Workplace Teams",
  "core_ref": "1 Timothy 6:10 (NIV)",
  "core_text": "For the love of money is a root of all kinds of evil.",
  "marketing": "Scripture doesn't call money evil \u2014 it names the love of money as a root from which all kinds of trouble grow. This study takes a clear-eyed look at that root: how the affection takes hold, what it produces, and the genuine freedom waiting on the other side of loosening its grip.",
  "felt_need": "Suspecting that a love of money has quietly taken root in my heart.",
  "why_matters": "Scripture warns the love of money is a root of all kinds of evil.",
  "problem": "The love of money grows quietly, producing trouble we trace to everything but its root.",
  "transformation": "From a heart rooted in loving money to one free to love God and people.",
  "formats": DEF,
  "sessions": [
   ("Not Money, but Love", "What Scripture actually warns"),
   ("The Root System", "How the affection takes hold"),
   ("What Grows From It", "The fruit of loving money"),
   ("Naming It Honestly", "Seeing the root in ourselves"),
   ("Loosening the Grip", "Pulling up the root"),
   ("The Freedom Beyond", "A heart free to love rightly"),
  ],
  "scriptures": ["1 Timothy 6:9-10", "Hebrews 13:5", "Ecclesiastes 5:10", "Luke 12:15", "Matthew 6:24"],
 },
 {
  "num": 73, "group": "Money & the Heart",
  "title": "What Money Can't Buy",
  "tagline": "Rediscovering the Things No Money Can Purchase",
  "tier": T1, "audience": "All Church \u00b7 Workplace Teams \u00b7 Anyone Chasing More",
  "core_ref": "Proverbs 22:1 (NIV)",
  "core_text": "A good name is more desirable than great riches; to be esteemed is better than silver or gold.",
  "marketing": "We pour enormous energy into earning, and almost none into the things money was never able to buy. This study turns attention to the priceless \u2014 a good name, love, peace, a clear conscience, time with the people we love \u2014 and the quiet wisdom of valuing what isn't for sale.",
  "felt_need": "Chasing money while quietly starving the things it was never able to buy.",
  "why_matters": "Scripture says a good name and being esteemed are worth more than silver or gold.",
  "problem": "We invest everything in what money can buy and neglect what it never could.",
  "transformation": "From chasing the purchasable to treasuring what isn't for sale.",
  "formats": DEF,
  "sessions": [
   ("The Priceless Things", "What isn't for sale"),
   ("A Good Name", "Worth more than riches"),
   ("Love and Peace", "The things money can't reach"),
   ("Time and Presence", "The currency that matters most"),
   ("A Clear Conscience", "Wealth money can't provide"),
   ("What Money Can't Buy", "Treasuring the priceless"),
  ],
  "scriptures": ["Proverbs 22:1", "Song of Songs 8:7", "Mark 8:36-37", "Psalm 49:6-9", "Proverbs 15:16-17"],
 },
 {
  "num": 74, "group": "Money & the Heart",
  "title": "Money and the Soul",
  "tagline": "How Money Quietly Forms \u2014 or Deforms \u2014 the Soul",
  "tier": T1, "audience": "All Church \u00b7 Small Groups \u00b7 Workplace Teams",
  "core_ref": "Mark 8:36 (NIV)",
  "core_text": "What good is it for someone to gain the whole world, yet forfeit their soul?",
  "marketing": "Every dollar decision is also a soul decision. Over time, the way we handle money quietly shapes the kind of person we're becoming \u2014 more generous or more grasping, freer or more fearful. This study traces that hidden formation and asks what our money is making of our souls.",
  "felt_need": "Not seeing how my money habits are slowly shaping the person I'm becoming.",
  "why_matters": "Jesus warned we can gain the whole world and forfeit the soul in the process.",
  "problem": "We watch the balance and ignore what money is quietly doing to the soul.",
  "transformation": "From money shaping the soul by accident to stewarding it as soul-formation.",
  "formats": DEF,
  "sessions": [
   ("More Than Transactions", "Money decisions as soul decisions"),
   ("Forming or Deforming", "What money does over time"),
   ("Gain the World, Lose the Soul", "The trade Jesus warns of"),
   ("The Faithful and the Soul", "How small choices shape us"),
   ("Guarding the Heart", "Tending the soul beneath money"),
   ("Money and the Soul", "Becoming who we want to be"),
  ],
  "scriptures": ["Mark 8:36", "Luke 16:10-11", "1 Timothy 6:9-10", "Matthew 6:21", "Proverbs 4:23"],
 },
 {
  "num": 75, "group": "Money & the Heart",
  "title": "The Treasure Test",
  "tagline": "Follow the Money to Find Your Heart",
  "tier": T1, "audience": "All Church \u00b7 Workplace Teams \u00b7 Self-Examiners",
  "core_ref": "Luke 12:34 (NIV)",
  "core_text": "For where your treasure is, there your heart will be also.",
  "marketing": "Jesus gave us a diagnostic so simple it's unsettling: where your treasure is, there your heart will be. This study turns that into an honest treasure test \u2014 following your money and your calendar to discover where your heart has actually set its treasure, and whether that's where you want it to be.",
  "felt_need": "Wanting an honest read on where my heart has truly set its treasure.",
  "why_matters": "Jesus said where our treasure is, our heart will be also \u2014 money reveals it.",
  "problem": "We assume we know where our heart is, but our spending often tells another story.",
  "transformation": "From assuming where our heart is to honestly locating and redirecting it.",
  "formats": DEF,
  "sessions": [
   ("The Diagnostic", "Treasure reveals the heart"),
   ("Follow the Money", "What spending uncovers"),
   ("Follow the Calendar", "Where time points too"),
   ("The Honest Results", "Facing what we find"),
   ("Resetting the Treasure", "Redirecting the heart"),
   ("The Treasure Test", "Heart where you want it"),
  ],
  "scriptures": ["Luke 12:34", "Matthew 6:19-21", "Matthew 6:24", "2 Corinthians 9:7", "Luke 16:13"],
 },
 # ---------------- MARRIAGE & FAMILY (all Tier 2) ----------------
 {
  "num": 76, "group": "Marriage & Family",
  "title": "Raising Money-Smart Kids",
  "tagline": "Equipping Kids With Wisdom They'll Carry for Life",
  "tier": T2, "audience": "Church Parents \u00b7 Families \u00b7 Households",
  "core_ref": "Proverbs 22:6 (NIV)",
  "core_text": "Start children off on the way they should go, and even when they are old they will not turn from it.",
  "marketing": "The money lessons children absorb at home tend to last a lifetime. This study equips parents to raise money-smart kids \u2014 teaching the wisdom, work ethic, and generosity they'll carry into adulthood \u2014 so the path you start them on is one they won't depart from.",
  "felt_need": "Wanting to raise kids who handle money wisely, but unsure how to teach it.",
  "why_matters": "Scripture says to start children on the right way, and they won't depart from it.",
  "problem": "Money habits form in childhood by default unless parents shape them on purpose.",
  "transformation": "From hoping kids figure money out to intentionally raising them money-smart.",
  "formats": DEF,
  "sessions": [
   ("Lasting Lessons", "Why childhood habits stick"),
   ("Start Them Right", "The path that shapes a life"),
   ("Teaching Work and Earning", "The value of a dollar"),
   ("Teaching Saving and Wisdom", "Patience and planning"),
   ("Teaching Generosity", "Open hands from the start"),
   ("Money-Smart for Life", "Wisdom they'll carry"),
  ],
  "scriptures": ["Proverbs 22:6", "Deuteronomy 6:6-7", "Proverbs 1:8", "Psalm 78:4-7", "Proverbs 13:22"],
 },
 {
  "num": 77, "group": "Marriage & Family",
  "title": "Talking to Your Kids About Money",
  "tagline": "Age-by-Age Conversations That Teach",
  "tier": T2, "audience": "Church Parents \u00b7 Families \u00b7 Households",
  "core_ref": "Proverbs 4:1 (NIV)",
  "core_text": "Listen, my sons, to a father's instruction; pay attention and gain understanding.",
  "marketing": "Many parents never talk to their kids about money \u2014 because no one taught them how. This study turns money into a teaching opportunity with practical, age-by-age conversations, giving parents the words and moments to pass on financial wisdom naturally, from toddlers to teens.",
  "felt_need": "Not knowing what to say, or when, when it comes to money and my kids.",
  "why_matters": "Scripture calls parents to instruct their children so they gain understanding.",
  "problem": "Money stays a silent, awkward topic at home, so kids learn it from everywhere else.",
  "transformation": "From avoiding the topic to natural, age-appropriate money conversations.",
  "formats": DEF,
  "sessions": [
   ("The Silent Subject", "Why we avoid money talk"),
   ("A Father's Instruction", "The call to teach"),
   ("Little Ones", "Money talk for young children"),
   ("The Middle Years", "Allowance, choices, consequences"),
   ("The Teen Years", "Earning, saving, real decisions"),
   ("Always Teaching", "Turning moments into lessons"),
  ],
  "scriptures": ["Proverbs 4:1-2", "Deuteronomy 6:7", "Psalm 78:4", "Ephesians 6:4", "Proverbs 22:6"],
 },
 {
  "num": 78, "group": "Marriage & Family",
  "title": "Money Lessons for the Family",
  "tagline": "A Family-Wide Journey Into Stewardship Together",
  "tier": T2, "audience": "Church Families \u00b7 Parents & Kids \u00b7 Households",
  "core_ref": "Psalm 78:4 (NIV)",
  "core_text": "We will tell the next generation the praiseworthy deeds of the Lord.",
  "marketing": "Some lessons land deepest when the whole family learns them together. This study is a family-wide journey into stewardship, saving, and generosity \u2014 parents and kids growing in the same truths at the same time \u2014 so financial wisdom becomes part of the family's shared story for the next generation.",
  "felt_need": "Wanting the whole family growing in money wisdom together, not just the parents.",
  "why_matters": "Scripture calls us to tell the next generation, so they tell their children too.",
  "problem": "Money values get taught piecemeal instead of shared as a whole family.",
  "transformation": "From scattered lessons to a family growing in stewardship together.",
  "formats": DEF,
  "sessions": [
   ("Learning Together", "Why family-wide matters"),
   ("Tell the Next Generation", "Passing on the truths"),
   ("Stewardship for All Ages", "Whose money it is"),
   ("Saving as a Family", "Patience everyone practices"),
   ("Giving as a Family", "Generosity together"),
   ("A Shared Story", "Wisdom for the next generation"),
  ],
  "scriptures": ["Psalm 78:4-7", "Deuteronomy 11:18-19", "2 Timothy 1:5", "Joshua 24:15", "Proverbs 22:6"],
 },
 {
  "num": 79, "group": "Marriage & Family",
  "title": "The Family Money Meeting",
  "tagline": "A Simple Rhythm of Talking Money Openly at Home",
  "tier": T2, "audience": "Church Households \u00b7 Couples & Families",
  "core_ref": "Ecclesiastes 4:9 (NIV)",
  "core_text": "Two are better than one, because they have a good return for their labor.",
  "marketing": "In many homes, money is handled in silence \u2014 until it erupts. This study builds a healthier rhythm: a simple, regular family money meeting where finances are discussed openly and calmly. Because two are better than one, and a household that talks about money together handles it far better together.",
  "felt_need": "Money handled in silence or stress at home, never discussed openly together.",
  "why_matters": "Scripture says two are better than one \u2014 households do better talking together.",
  "problem": "Without a rhythm to talk money, it festers in silence until it becomes conflict.",
  "transformation": "From money silence and stress to a calm, regular household rhythm.",
  "formats": ["4-Session", "6-Session", "21-Day"],
  "sessions": [
   ("The Money Silence", "Why homes avoid the talk"),
   ("Two Are Better", "The strength of together"),
   ("Setting the Table", "How to start the meeting"),
   ("What to Talk About", "A simple agenda"),
   ("Keeping It Calm", "Money talk without conflict"),
   ("A Household Rhythm", "Making the meeting stick"),
  ],
  "scriptures": ["Ecclesiastes 4:9-10", "Proverbs 15:22", "Amos 3:3", "Proverbs 24:3-4", "Colossians 3:23"],
 },
 {
  "num": 80, "group": "Marriage & Family",
  "title": "Generosity Starts at Home",
  "tagline": "Raising Open-Handed Children by Making Giving Normal",
  "tier": T2, "audience": "Church Parents \u00b7 Families \u00b7 Households",
  "core_ref": "Matthew 10:8 (NIV)",
  "core_text": "Freely you have received; freely give.",
  "marketing": "Generous adults usually started as generous kids. This study helps families make giving a normal, joyful part of childhood \u2014 letting children give from their own hands and see their parents do the same \u2014 so open-handedness becomes second nature long before they ever earn a paycheck.",
  "felt_need": "Wanting to raise open-handed, generous kids in a culture that says it's all mine.",
  "why_matters": "Jesus said freely you have received, freely give \u2014 generosity is learned young.",
  "problem": "Without practice at home, children default to keeping rather than giving.",
  "transformation": "From hoping kids grow generous to forming open hands at home.",
  "formats": DEF,
  "sessions": [
   ("Generous Kids, Generous Adults", "Where it begins"),
   ("Freely Give", "The heart we're forming"),
   ("Letting Children Give", "Hands-on generosity"),
   ("Modeling It Ourselves", "What kids see us do"),
   ("Making Giving Joyful", "Generosity that delights"),
   ("Open Hands at Home", "Generosity as second nature"),
  ],
  "scriptures": ["Matthew 10:8", "2 Corinthians 9:7", "Acts 20:35", "Proverbs 11:25", "1 Timothy 6:18"],
 },
 # ---------------- SEASONS & LIFE STAGES ----------------
 {
  "num": 81, "group": "Seasons & Life Stages",
  "title": "Money in Your 20s",
  "tagline": "Laying a Wise Foundation Before Habits Harden",
  "tier": T1, "audience": "All Church \u00b7 Young Adults \u00b7 College & Career",
  "core_ref": "Ecclesiastes 12:1 (NIV)",
  "core_text": "Remember your Creator in the days of your youth.",
  "marketing": "The financial habits formed in your twenties tend to set the trajectory for decades. This study helps young adults lay a wise foundation early \u2014 before the patterns harden \u2014 covering the first big decisions about earning, saving, debt, and giving while the cement is still wet.",
  "felt_need": "Young, figuring out money, and afraid of setting bad patterns early.",
  "why_matters": "Scripture says to remember your Creator in your youth \u2014 foundations set early last.",
  "problem": "Habits formed carelessly in the twenties quietly shape the decades that follow.",
  "transformation": "From drifting into money habits to laying a wise foundation on purpose.",
  "formats": DEF,
  "sessions": [
   ("The Cement Is Wet", "Why these years matter"),
   ("Remember Your Creator", "God first, early"),
   ("Earning and Spending", "First habits that stick"),
   ("Debt and Its Dangers", "Avoiding early traps"),
   ("Saving Young", "The power of starting now"),
   ("A Foundation That Lasts", "Built right from the start"),
  ],
  "scriptures": ["Ecclesiastes 12:1", "Proverbs 22:6", "Proverbs 13:11", "Lamentations 3:27", "Proverbs 6:6-8"],
 },
 {
  "num": 82, "group": "Seasons & Life Stages",
  "title": "Starting Out, Starting Right",
  "tagline": "First Principles for the Start of Your Financial Life",
  "tier": T1, "audience": "All Church \u00b7 New Believers \u00b7 Fresh Starts",
  "core_ref": "Matthew 7:24 (NIV)",
  "core_text": "Everyone who hears these words of mine and puts them into practice is like a wise man who built his house on the rock.",
  "marketing": "Whether you're new to faith, new to a paycheck, or making a fresh start at any age, the beginning is the best time to build right. This study lays out the first principles of money God's way \u2014 simple, solid foundations that mean you won't have to tear it all down and rebuild later.",
  "felt_need": "At the beginning of my financial life and wanting to start on solid ground.",
  "why_matters": "Jesus said the wise build on the rock \u2014 what we start on determines what stands.",
  "problem": "We build financial lives on shifting sand and pay to rebuild them later.",
  "transformation": "From a shaky start to a financial life built on solid first principles.",
  "formats": DEF,
  "sessions": [
   ("Build on the Rock", "Why the foundation matters"),
   ("Whose Money Is It?", "The first principle of all"),
   ("Live on Less", "Spending under your income"),
   ("Save Something", "Margin from the start"),
   ("Give From the First", "Generosity built in early"),
   ("Starting Right", "A foundation that stands"),
  ],
  "scriptures": ["Matthew 7:24-25", "Proverbs 4:7", "Proverbs 24:3-4", "Luke 14:28", "Proverbs 21:5"],
 },
 {
  "num": 83, "group": "Seasons & Life Stages",
  "title": "Money for Newlyweds",
  "tagline": "Building Shared Money Habits in Your First Season",
  "tier": T1, "audience": "All Church \u00b7 Newly Married Couples",
  "core_ref": "Genesis 2:24 (NIV)",
  "core_text": "A man... is united to his wife, and they become one flesh.",
  "marketing": "The first season of marriage is when money patterns get set \u2014 for better or worse. This study helps newlyweds build shared habits and real unity around finances early, learning to handle money as one before old habits and assumptions quietly drive a wedge between two.",
  "felt_need": "Newly married and unsure how to merge two money histories into one.",
  "why_matters": "Scripture says the two become one \u2014 including how a couple handles money.",
  "problem": "Two money histories collide in marriage and, unaddressed, become a fault line.",
  "transformation": "From two separate money lives to one shared, united approach.",
  "formats": DEF,
  "sessions": [
   ("Two Become One", "Including the finances"),
   ("Two Money Histories", "Understanding each other"),
   ("Shared Goals", "Dreaming and planning together"),
   ("One Plan, One Team", "Handling money as one"),
   ("Talking Without Fighting", "Money conversations that unite"),
   ("United From the Start", "Shared habits for the long haul"),
  ],
  "scriptures": ["Genesis 2:24", "Ecclesiastes 4:9-12", "Amos 3:3", "1 Corinthians 7:3-5", "Proverbs 24:3-4"],
 },
 {
  "num": 84, "group": "Seasons & Life Stages",
  "title": "Finances in the Middle Years",
  "tagline": "Navigating the Squeeze of Peak-Earning Years",
  "tier": T1, "audience": "All Church \u00b7 Workplace Teams \u00b7 Midlife Adults",
  "core_ref": "1 Timothy 5:8 (NIV)",
  "core_text": "Anyone who does not provide for their relatives, and especially for their own household, has denied the faith.",
  "marketing": "The middle years bring a financial squeeze like no other \u2014 peak earning, growing kids, college costs, and aging parents, often all at once. This study offers wisdom for the sandwich generation, helping people steward competing demands without losing themselves, their families, or their faith in the crush.",
  "felt_need": "Stretched between kids, aging parents, and my own future, all at once.",
  "why_matters": "Scripture calls us to provide for our household \u2014 a weighty charge in midlife.",
  "problem": "Competing demands collide in midlife until something important gets squeezed out.",
  "transformation": "From the crush of competing demands to stewarding the middle years wisely.",
  "formats": DEF,
  "sessions": [
   ("The Great Squeeze", "Demands from every side"),
   ("Providing for the Household", "The midlife charge"),
   ("The Sandwich Generation", "Kids and parents at once"),
   ("Not Losing Yourself", "Stewarding your own future too"),
   ("Wisdom Under Pressure", "Priorities that hold"),
   ("Through the Middle", "Faithful in the squeeze"),
  ],
  "scriptures": ["1 Timothy 5:8", "Proverbs 13:22", "Psalm 90:12", "Proverbs 21:5", "Galatians 6:9"],
 },
 {
  "num": 85, "group": "Seasons & Life Stages",
  "title": "Money and Retirement",
  "tagline": "Stewarding Wisely Into and Through Retirement",
  "tier": T1, "audience": "All Church \u00b7 Pre-Retirees & Retirees",
  "core_ref": "Psalm 71:18 (NIV)",
  "core_text": "Even when I am old and gray, do not forsake me, my God.",
  "marketing": "Retirement raises big questions \u2014 will there be enough, and enough for what? This study brings biblical wisdom to stewarding resources into and through the retirement years, replacing anxiety about running out with a vision of finishing faithfully, generously, and on purpose.",
  "felt_need": "Anxious about whether I'll have enough, and what retirement is even for.",
  "why_matters": "The psalmist asked God not to forsake him when old \u2014 later years can still have purpose.",
  "problem": "We approach retirement with fear of scarcity and no vision beyond stopping work.",
  "transformation": "From anxiety about running out to stewarding the later years with purpose.",
  "formats": DEF,
  "sessions": [
   ("Will There Be Enough?", "Facing the big question"),
   ("Enough for What?", "Retirement with purpose"),
   ("Stewarding the Nest Egg", "Wisdom for the resources"),
   ("Still Bearing Fruit", "Purpose in the later years"),
   ("Generous to the End", "Giving in retirement"),
   ("Faithful Through Retirement", "Stewarding the season well"),
  ],
  "scriptures": ["Psalm 71:18", "Proverbs 6:6-8", "Proverbs 13:22", "Psalm 92:14", "1 Timothy 6:17-19"],
 },
 {
  "num": 86, "group": "Seasons & Life Stages",
  "title": "Finishing the Race Financially",
  "tagline": "Running the Last Financial Lap With Purpose",
  "tier": T1, "audience": "All Church \u00b7 Seniors & Finishers",
  "core_ref": "2 Timothy 4:7 (NIV)",
  "core_text": "I have fought the good fight, I have finished the race, I have kept the faith.",
  "marketing": "Every race is won or lost in the final lap. This study is about finishing well financially \u2014 stewarding the last season with wisdom, generosity, and purpose rather than mere survival \u2014 so that, like Paul, you can say you finished the race and kept the faith with everything entrusted to you.",
  "felt_need": "Wanting my final financial season to count, not just coast or survive.",
  "why_matters": "Paul finished the race and kept the faith \u2014 the last lap is meant to count.",
  "problem": "We treat the final stretch as winding down rather than finishing on purpose.",
  "transformation": "From coasting to the end to finishing the financial race with purpose.",
  "formats": DEF,
  "sessions": [
   ("The Final Lap", "Why the finish matters"),
   ("Finished the Race", "Paul's example of finishing"),
   ("Stewarding to the End", "Faithful with what remains"),
   ("Generous at the Finish", "Giving as you go"),
   ("Leaving It Well", "Handing off what's entrusted"),
   ("Finishing Faithful", "Crossing the line well"),
  ],
  "scriptures": ["2 Timothy 4:7", "Philippians 3:14", "Proverbs 13:22", "Matthew 25:21", "1 Corinthians 9:24-25"],
 },
 {
  "num": 87, "group": "Seasons & Life Stages",
  "title": "Single and Stewarding Well",
  "tagline": "Managing Money With Wisdom and Community",
  "tier": T2, "audience": "Church Singles \u00b7 Single Adults \u00b7 Small Groups",
  "core_ref": "1 Corinthians 7:35 (NIV)",
  "core_text": "...that you may live in a right way in undivided devotion to the Lord.",
  "marketing": "Stewarding money as a single person carries unique freedoms and unique weight \u2014 every decision, every safety net, resting on one set of shoulders. This study offers wisdom for the single steward, embracing the focus singleness allows while building the community that keeps no one carrying it entirely alone.",
  "felt_need": "Carrying every financial decision alone, with no built-in partner to share it.",
  "why_matters": "Scripture honors undivided devotion to the Lord \u2014 a gift singleness uniquely allows.",
  "problem": "Single stewards carry the full load solo, without the check of a partner.",
  "transformation": "From carrying money alone to stewarding wisely with focus and community.",
  "formats": DEF,
  "sessions": [
   ("The Single Steward", "Freedom and full responsibility"),
   ("Undivided Devotion", "The gift of focus"),
   ("Decisions of One", "Wisdom without a partner"),
   ("Building Your Community", "Not carrying it alone"),
   ("Safety Nets and Wisdom", "Planning for one"),
   ("Stewarding Well, Single", "Focus, faith, community"),
  ],
  "scriptures": ["1 Corinthians 7:32-35", "Ecclesiastes 4:9-10", "Proverbs 19:14", "Luke 16:10", "Philippians 4:11-13"],
 },
 {
  "num": 88, "group": "Seasons & Life Stages",
  "title": "Money After Loss",
  "tagline": "Tender, Practical Guidance for Finances After Loss",
  "tier": T2, "audience": "Church \u00b7 The Grieving \u00b7 Widows & Widowers",
  "core_ref": "Psalm 68:5 (NIV)",
  "core_text": "A father to the fatherless, a defender of widows, is God in his holy dwelling.",
  "marketing": "Grief and finances are a heavy combination \u2014 paperwork and decisions arriving exactly when the heart has the least to give. This study offers gentle, practical guidance for handling money after loss, holding space for grief while pointing to the God who draws near as a defender of widows and a father to the fatherless.",
  "felt_need": "Facing financial decisions in the fog of grief, with little strength to give them.",
  "why_matters": "Scripture calls God a defender of widows \u2014 He draws near to the grieving.",
  "problem": "Loss brings financial demands precisely when the heart is least able to bear them.",
  "transformation": "From overwhelmed by money in grief to gently, faithfully tended through it.",
  "formats": ["4-Session", "6-Session", "21-Day"],
  "sessions": [
   ("Grief and Money", "A heavy combination"),
   ("Close to the Brokenhearted", "God near in loss"),
   ("First, Be Gentle", "Permission to go slowly"),
   ("The Necessary Steps", "Handling what can't wait"),
   ("Leaning on Others", "Letting the body help"),
   ("Tended Through Loss", "Faithful care in grief"),
  ],
  "scriptures": ["Psalm 68:5", "Psalm 34:18", "Psalm 146:9", "2 Corinthians 1:3-4", "Ruth 1:16-17"],
 },
 {
  "num": 89, "group": "Seasons & Life Stages",
  "title": "Rebuilding After Financial Crisis",
  "tagline": "Hope and a Path Forward After Collapse",
  "tier": T1, "audience": "All Church \u00b7 Those Rebuilding \u00b7 Fresh Starts",
  "core_ref": "Joel 2:25 (NIV)",
  "core_text": "I will repay you for the years the locusts have eaten.",
  "marketing": "Bankruptcy, foreclosure, collapse \u2014 financial crises leave behind more than empty accounts; they leave shame and the question of whether recovery is even possible. This study offers hope and a real path forward, anchored in a God who promises to restore the years the locusts have eaten.",
  "felt_need": "Buried under the shame and wreckage of a financial collapse.",
  "why_matters": "God promised to restore the years the locusts ate \u2014 recovery is possible.",
  "problem": "Financial crisis leaves shame and despair that make rebuilding feel impossible.",
  "transformation": "From the shame of collapse to hope and a real path to rebuild.",
  "formats": DEF,
  "sessions": [
   ("After the Collapse", "Naming the wreckage"),
   ("Restoring the Years", "God's promise of recovery"),
   ("Releasing the Shame", "Grace for the fallen"),
   ("The First Steps Back", "Rebuilding the foundation"),
   ("Steady Progress", "Rebuilding little by little"),
   ("Hope Restored", "A future after crisis"),
  ],
  "scriptures": ["Joel 2:25", "Job 42:10", "Psalm 40:1-2", "Lamentations 3:22-23", "Philippians 3:13-14"],
 },
 {
  "num": 90, "group": "Seasons & Life Stages",
  "title": "Money in Hard Times",
  "tagline": "Faith and Wisdom for a Genuinely Hard Season",
  "tier": T1, "audience": "All Church \u00b7 Workplace Teams \u00b7 Hard Seasons",
  "core_ref": "Habakkuk 3:17-18 (NIV)",
  "core_text": "Though the fig tree does not bud... yet I will rejoice in the Lord.",
  "marketing": "Some financial seasons are simply hard \u2014 recession, scarcity, a long stretch of lean. This study offers faith and practical wisdom for navigating them, learning the secret of Habakkuk, who could say that even when the fig tree didn't bud, he would still rejoice in the Lord.",
  "felt_need": "Trying to keep both faith and finances intact through a genuinely hard season.",
  "why_matters": "Habakkuk rejoiced in the Lord even when the harvest failed \u2014 faith can hold in lean times.",
  "problem": "Hard seasons strain faith and finances at once, and both can buckle under the weight.",
  "transformation": "From buckling in the hard season to faith and wisdom that endure it.",
  "formats": DEF,
  "sessions": [
   ("When Times Are Hard", "Naming the lean season"),
   ("Though the Fig Tree", "Habakkuk's defiant faith"),
   ("The Secret of Content", "Plenty and want"),
   ("Practical Wisdom", "Stewarding through scarcity"),
   ("Rejoicing Anyway", "Joy that doesn't depend on plenty"),
   ("Enduring Hard Times", "Faith and finances intact"),
  ],
  "scriptures": ["Habakkuk 3:17-18", "Philippians 4:12-13", "Psalm 37:18-19", "Matthew 6:31-33", "James 1:2-4"],
 },
]
