# -*- coding: utf-8 -*-
# The original 20 Business & Workplace Intelligence categories, preserved exactly
# as provided across the two source documents.

# Categories with a complete 50-title list (no subtitles in source)
BUSINESS_OWNERS_50 = [
    "Kingdom Entrepreneur", "Built to Bless", "Faith and the Bottom Line", "The Faithful Founder",
    "Business on Mission", "Called to Build", "The Generous Enterprise", "Success Without Losing Your Soul",
    "The Servant CEO", "More Than Profit", "Leading with Purpose", "Faith Through Failure",
    "Vision and Surrender", "Courage to Risk", "Kingdom Companies", "Marketplace Disciple",
    "Business by Design", "Called to Create", "The Entrepreneur's Soul", "Faith That Scales",
    "Stewarding Success", "Building What Lasts", "God's Business Plan", "Entrepreneurs of Faith",
    "Work as Worship", "Leading Through Growth", "Stewarding Opportunity", "The Courageous Founder",
    "Kingdom Innovation", "Building Eternal Value", "Legacy Business", "Faith Beyond the Startup",
    "Resilient Entrepreneur", "Company Culture by Design", "Leading During Uncertainty",
    "Humility and Success", "Stewardship of Growth", "Building with Integrity", "Beyond the Exit",
    "Business Legacy", "Entrepreneurial Faith", "Kingdom Expansion", "Faithful Risk",
    "Business that Serves", "Marketplace Influence", "Stewarding Employees", "Faith Under Pressure",
    "Wise Ownership", "Called to Multiply", "Finish Well in Business",
]
EXECUTIVES_50 = [
    "Faith in the C-Suite", "Executive Stewardship", "Leadership that Lasts", "Beyond Success",
    "Legacy Leadership", "Leading Like Jesus", "Influence with Integrity", "The Servant Executive",
    "Decisions that Matter", "Character at the Top", "The Leader's Soul", "Courage Under Pressure",
    "Vision that Inspires", "Leading Through Change", "Healthy Leadership", "Building Trust",
    "Leadership Multiplication", "Stewarding Influence", "Humble Leadership", "Crisis Leadership",
    "Faithful Decision Making", "Leadership by Grace", "Executive Wisdom", "Leading Teams Well",
    "The Listening Leader", "Building Healthy Culture", "The Resilient Executive", "The Leader's Legacy",
    "Faithful Influence", "Leadership Reset", "The Whole Leader", "Leadership and Family",
    "Purpose Beyond Position", "Wisdom in Leadership", "Leading the Next Generation",
    "Leadership Conversations", "Stewarding Authority", "High-Impact Leadership",
    "Building Great Organizations", "Leading with Compassion", "Leadership for Eternity",
    "The Kingdom Leader", "Building Future Leaders", "Called to Lead", "Strategic Stewardship",
    "Integrity Under Fire", "Faithful Vision", "Leadership in Transition",
    "Servant Leadership Journey", "Finish Well as a Leader",
]
FINANCIAL_ADVISORS_50 = [
    "Faithful Advisor", "Wealth with Purpose", "Trusted Steward", "Beyond the Portfolio",
    "Stewardship Conversations", "Kingdom Advisor", "Financial Wisdom", "Money and the Soul",
    "Rich Toward God", "The Eternal Portfolio", "Advisor as Disciplemaker", "Legacy Conversations",
    "Faith and Finances", "Whole-Life Stewardship", "Serving Families Well", "Biblical Wealth",
    "Advisor with Purpose", "Stewarding Influence", "Wisdom Beyond Wealth", "Financial Disciple",
    "Values-Based Advice", "Families that Flourish", "Generosity Journey", "Family Legacy Coach",
    "Kingdom Capital", "Advisor Leadership", "Biblical Investing", "Trusted Counsel",
    "Wealth Transfer", "Preparing Heirs", "Stewarding Success", "The Legacy Advisor",
    "Family Office Ministry", "Beyond Retirement", "Generous Clients", "The Wise Counselor",
    "Kingdom Conversations", "Faithful Planning", "The Steward's Calling", "Money with Meaning",
    "Advisor Impact", "The Christian Planner", "Legacy by Design", "Eternal Returns",
    "Stewardship First", "Values Before Valuables", "Family Mission", "Advisor Influence",
    "Building Legacy", "Called to Counsel",
]

TITLE_ONLY_CATEGORIES = [
    ("Christian Business Owners & Entrepreneurs", "Helping founders build companies that honor Christ.", BUSINESS_OWNERS_50),
    ("Executives & Senior Leaders", "Leadership under pressure.", EXECUTIVES_50),
    ("Christian Financial Advisors & Wealth Professionals", "Your primary marketplace.", FINANCIAL_ADVISORS_50),
]

# Categories given as "examples" (10 each) in the source doc, with a note that
# the full 50 follows the same 5-part framework used elsewhere in the library.
EXAMPLE_CATEGORIES = [
    ("Healthcare Professionals",
     "50 campaigns around calling, compassion, burnout, ethics, suffering, healing, resilience, spiritual care, grief, and purpose.",
     ["Called to Care", "Compassion Without Burnout", "Healing Hands", "The Weary Healer", "Sacred Work",
      "Grace Under Pressure", "The Caregiver's Soul", "Presence Matters", "Hope at the Bedside", "Caring Like Christ"]),
    ("Educators & School Leaders",
     "50 campaigns around teaching, influence, purpose, burnout, next generation, culture, leadership, resilience, and hope.",
     ["Called to Teach", "Beyond the Lesson Plan", "Shaping Souls", "Every Student Matters", "The Teacher's Calling",
      "Faith in the Classroom", "Hope for Educators", "Courage to Teach", "Wisdom for Schools", "The Legacy Teacher"]),
    ("Technology, AI & Innovation",
     "One of the fastest-growing opportunities.",
     ["Faith in an AI World", "Coding with Character", "Technology with Purpose", "Wisdom in Innovation",
      "Digital Disciple", "Ethics in AI", "Building the Future", "Human in a Digital Age",
      "Created to Create", "Innovation that Serves"]),
    ("Sales, Marketing & Customer Influence",
     "A huge underserved audience.",
     ["Selling with Integrity", "Influence God's Way", "Trust Wins", "The Honest Salesperson",
      "Serving Before Selling", "Faith in Business Development", "Purpose Beyond Quotas",
      "Character Creates Customers", "Relationship First", "Influence with Humility"]),
    ("Real Estate, Construction & Skilled Trades",
     "Builders, contractors, and tradespeople living out their faith on the job.",
     ["Built on the Rock", "Honest Work", "Kingdom Craftsman", "Building More Than Buildings",
      "Faith on the Job Site", "Excellence in Every Task", "Hands That Serve", "Building Legacy",
      "Called to Build", "Foundations that Last"]),
    ("Government, Law & Public Service",
     "Faith and integrity in public office and civic life.",
     ["Called to Serve", "Justice and Mercy", "Faith in Public Life", "Courage Under Pressure",
      "Integrity in Government", "Public Servant", "Defending Justice", "Truth in Leadership",
      "Influence for Good", "Honor in Service"]),
    ("Nonprofit, Ministry & Mission Leaders",
     "Sustainable leadership for those who lead the mission.",
     ["Leading the Mission", "Ministry Without Burnout", "Called to Serve", "The Healthy Leader",
      "Shepherding Well", "Sustainable Ministry", "Faithful Influence", "Mission That Lasts",
      "Kingdom Leadership", "Finish Well"]),
]

# Manufacturing & Marketplace Ministry -- already built to 25 with subtitles in the source doc
MANUFACTURING_ORIGINAL_25 = [
    ("Built to Last", "Building products, people, and purpose"),
    ("The Faithful Builder", "Honoring God through quality work"),
    ("Excellence Every Day", "Glorifying God through craftsmanship"),
    ("Factory Faith", "Living Christ in the workplace"),
    ("Leading the Production Line", "Leadership where it matters"),
    ("Purpose Behind Production", "Seeing eternal value in everyday work"),
    ("Stewarding Operations", "Managing resources with wisdom"),
    ("The Industrial Disciple", "Following Jesus on the factory floor"),
    ("Work Worth Doing", "Bringing dignity to labor"),
    ("Beyond Efficiency", "Building people while building products"),
    ("Faith Under Pressure", "Trusting God through deadlines"),
    ("The Excellent Craftsman", "Excellence as worship"),
    ("Building Better Teams", "Leadership that develops people"),
    ("Hands That Honor God", "Working with integrity"),
    ("Purpose in Production", "More than making things"),
    ("The Stewarded Workplace", "Managing people and resources well"),
    ("Strength and Service", "Leadership through humility"),
    ("Called to Build", "God's purpose in industry"),
    ("Faith That Works", "Living biblical values daily"),
    ("Leading with Character", "Integrity that influences"),
    ("The Productive Life", "Stewardship of time and talent"),
    ("Serving Through Work", "Work as ministry"),
    ("Building Kingdom Culture", "Transforming workplaces"),
    ("The Maker's Calling", "Reflecting the Creator"),
    ("Legacy on the Factory Floor", "Work that outlives you"),
]

AGRICULTURE_10 = [
    ("Faith in the Fields", "Trusting God through every season"),
    ("Seeds of Faith", "Sowing what lasts forever"),
    ("The Good Ground", "Preparing hearts like fertile soil"),
    ("Harvest of Hope", "Trusting God's provision"),
    ("The Faithful Farmer", "Stewardship from sunrise to sunset"),
    ("Planting with Purpose", "Growing more than crops"),
    ("The Shepherd's Heart", "Caring for what God entrusts"),
    ("Growing by Faith", "Trusting God through uncertainty"),
    ("Fields of Grace", "Discovering God in everyday work"),
    ("The Harvest Principle", "Reaping what is faithfully sown"),
]
HOSPITALITY_10 = [
    ("Serving with Joy", "Hospitality that reflects Christ"),
    ("The Welcoming Heart", "Making every guest feel valued"),
    ("Excellence in Service", "Honoring God through hospitality"),
    ("Beyond Customer Service", "Serving people with purpose"),
    ("Open Doors", "Creating environments of welcome"),
    ("The Host's Calling", "Hospitality as ministry"),
    ("Grace Under Pressure", "Thriving in fast-paced service"),
    ("Serving the Stranger", "Biblical hospitality in action"),
    ("A Table for Everyone", "Building belonging"),
    ("The Hospitality Advantage", "Excellence with compassion"),
]
GOV_CIVIC_10 = [
    ("Serving the Public Well", "Leadership with integrity"),
    ("Faith in Public Service", "Honoring Christ in government"),
    ("Called to Serve", "Public leadership with purpose"),
    ("Justice with Mercy", "Biblical leadership in civic life"),
    ("Leading for the Common Good", "Serving communities faithfully"),
    ("Character in Office", "Integrity under pressure"),
    ("Courage to Lead", "Standing firm in difficult times"),
    ("Hope for the City", "Seeking community flourishing"),
    ("Public Faithfulness", "Representing Christ honorably"),
    ("Kingdom Influence", "Serving beyond politics"),
]
ARTS_10 = [
    ("Created to Create", "Reflecting God's creativity"),
    ("Art That Matters", "Using creativity for Kingdom influence"),
    ("The Creative Calling", "Honoring God through imagination"),
    ("Beauty with Purpose", "Creating what points to truth"),
    ("Stories That Change Lives", "Communicating hope"),
    ("The Faithful Artist", "Excellence and integrity"),
    ("Beyond Applause", "Finding identity in Christ"),
    ("Creating for the King", "Worship through creativity"),
    ("The Redemptive Story", "Art that reflects redemption"),
    ("Inspired", "Living creatively with God"),
]
TRANSPORTATION_10 = [
    ("Driven by Purpose", "Honoring God on every journey"),
    ("Faith on the Road", "Walking with Christ wherever work takes you"),
    ("The Long Haul", "Endurance and faithfulness"),
    ("Delivering Hope", "More than moving products"),
    ("Journey with Purpose", "Every mile matters"),
    ("Steady Hands", "Integrity behind the wheel"),
    ("The Road Ahead", "Trusting God through uncertainty"),
    ("Moving Forward", "Faith that keeps going"),
    ("Guided by Grace", "God's presence on the journey"),
    ("Faith in Motion", "Everyday discipleship"),
]
SCIENCE_10 = [
    ("Designed by God", "Discovering the Creator through creation"),
    ("Faith and Discovery", "Integrating science and Scripture"),
    ("Engineering Excellence", "Building with integrity"),
    ("Innovation with Wisdom", "Creating responsibly"),
    ("The Curious Christian", "Loving God with your mind"),
    ("Building Tomorrow", "Stewarding innovation"),
    ("The Designer's Calling", "Creativity with purpose"),
    ("Truth and Discovery", "Pursuing excellence"),
    ("Faith in the Laboratory", "Serving Christ through science"),
    ("Ordered by Design", "Seeing God's fingerprints"),
]
RETAIL_10 = [
    ("Serving Every Customer", "Reflecting Christ through service"),
    ("Excellence on the Front Line", "Faith in everyday interactions"),
    ("The Helpful Heart", "Serving with joy"),
    ("More Than Transactions", "Building relationships"),
    ("Integrity at the Counter", "Honoring God in business"),
    ("Retail with Purpose", "Work that matters"),
    ("Grace Under Pressure", "Thriving in busy seasons"),
    ("Every Customer Matters", "Seeing people as God does"),
    ("Faith Behind the Register", "Worship through work"),
    ("The Servant Associate", "Leadership through service"),
]
MINISTRY_STAFF_10 = [
    ("Serving Behind the Scenes", "Faithfulness that builds the church"),
    ("Healthy Ministry Teams", "Growing together in service"),
    ("Ministry with Joy", "Rediscovering your calling"),
    ("The Staff Journey", "Serving without burnout"),
    ("Faithful in the Little Things", "Excellence in everyday ministry"),
    ("One Team", "Building unity in ministry"),
    ("Leading Together", "Shared vision and purpose"),
    ("The Healthy Staff", "Caring for the soul of ministry"),
    ("Grace-Filled Leadership", "Serving one another"),
    ("Called to Serve", "Ministry as worship"),
]
MARKETPLACE_MINISTRY_ORIGINAL_25 = [
    ("Monday Matters", "Connecting Sunday faith to Monday work"),
    ("The Marketplace Disciple", "Following Christ at work"),
    ("Faith Beyond Sunday", "Living missionally at work"),
    ("Kingdom at Work", "Every profession matters"),
    ("Work Is Worship", "Honoring God through vocation"),
    ("The Sent Worker", "Living on mission in the marketplace"),
    ("Business as Ministry", "Every workplace a mission field"),
    ("Called to Influence", "Using work for Kingdom impact"),
    ("Faith in Every Profession", "Christ in every career"),
    ("Workplace Revival", "Transforming culture through discipleship"),
    ("Purpose Beyond the Paycheck", "Discovering eternal significance"),
    ("Your Monday Mission", "Seeing every workday as ministry"),
    ("Marketplace Light", "Bringing hope into your profession"),
    ("Kingdom Influence at Work", "Leading with Christlike character"),
    ("Work That Worships", "Excellence as an act of devotion"),
    ("The Vocation Journey", "Discovering God's calling through work"),
    ("Faithful Where You Are", "Serving God in your current assignment"),
    ("Mission in the Marketplace", "Reaching people through everyday relationships"),
    ("The Whole-Life Disciple", "Integrating faith, family, and work"),
    ("Beyond Career Success", "Pursuing significance over status"),
    ("Workplace Witness", "Sharing Christ through character and compassion"),
    ("Every Desk an Altar", "Offering your daily work to God"),
    ("Influence That Lasts", "Building an eternal legacy through your vocation"),
    ("The Kingdom Professional", "Living with integrity and purpose"),
    ("Called to the Marketplace", "Embracing your profession as God's assignment"),
]

SUBTITLED_25_CATEGORIES = [
    ("Manufacturing & Industrial Leaders",
     "Helping builders, manufacturers, plant managers, and operations leaders honor God through excellence.",
     MANUFACTURING_ORIGINAL_25),
    ("Marketplace Ministry Leaders",
     "Designed for churches building marketplace ministries.",
     MARKETPLACE_MINISTRY_ORIGINAL_25),
]

# Categories given as "examples" (10, WITH subtitles) plus an explicit expand-note in the source doc
EXAMPLE_WITH_SUBTITLE_CATEGORIES = [
    ("Agriculture & Ranching", AGRICULTURE_10,
     "Expand into stewardship, family farms, succession, resilience, drought, gratitude, generational farming, creation care, generosity, and legacy."),
    ("Hospitality & Tourism", HOSPITALITY_10,
     "Leadership, burnout, teamwork, kindness, influence, generosity, servant leadership."),
    ("Government & Civic Leadership", GOV_CIVIC_10,
     "Ethics, humility, wisdom, conflict, peacebuilding, stewardship."),
    ("Arts, Entertainment & Media", ARTS_10,
     "Music, filmmaking, writing, design, influence, culture."),
    ("Transportation & Logistics", TRANSPORTATION_10,
     "Safety, perseverance, leadership, serving customers, teamwork."),
    ("Science & Engineering", SCIENCE_10,
     "Research, ethics, AI, engineering leadership."),
    ("Retail & Customer Service", RETAIL_10,
     "Character, teamwork, influence, kindness, purpose."),
    ("Ministry Staff & Church Employees", MINISTRY_STAFF_10,
     "Communication, vision, conflict, teamwork, renewal."),
]
