# -*- coding: utf-8 -*-
from es_map1 import apply
import subprocess

M = {}
# ---- session scaffolds ----
M["Close in prayer: thank God for what was shared tonight"] = "Cierren en oraci\u00f3n: agradezcan a Dios lo compartido esta noche, oren por una necesidad espec\u00edfica dicha en el c\u00edrculo y p\u00eddanle que haga real la pr\u00e1ctica de esta semana."
M[" — what made you say yes to this journey"] = " \u2014 \u00bfqu\u00e9 te hizo decirle s\u00ed a este recorrido, y qu\u00e9 esperas que sea distinto al final?"
M[": put this session's big idea into practice through the "] = ": pon en pr\u00e1ctica la gran idea de esta sesi\u00f3n a trav\u00e9s del ejercicio "
M[" exercise, and come ready to share how it went."] = ", y ven listo para contar c\u00f3mo te fue."
M[": work through it together before the next session"] = ": trab\u00e1jenlo juntos antes de la pr\u00f3xima sesi\u00f3n, y traigan una idea de regreso al grupo."
M["As we begin "] = "Al comenzar "
M["This week's challenge — "] = "El reto de esta semana \u2014 "
M["This week's family exercise — "] = "El ejercicio familiar de esta semana \u2014 "
# ---- sermon beats ----
M["Open with a story or moment your people will recognize"] = "Abre con una historia o un momento que tu gente reconozca \u2014 el lugar cotidiano donde aparece la tensi\u00f3n de esta semana \u2014 y n\u00f3mbralo sin rodeos: de esto vamos a hablar hoy."
M["What God declares"] = "Lo que Dios declara"
M["Ground the message in the text before the takeaways"] = "Ancla el mensaje en el texto antes de las conclusiones. Que la congregaci\u00f3n oiga lo que Dios dice sobre "
M[" before hearing what we should do."] = " antes de o\u00edr lo que debemos hacer."
M["Why we struggle"] = "Por qu\u00e9 nos cuesta"
M["Name the honest obstacle"] = "Nombra el obst\u00e1culo honesto \u2014 el miedo, el h\u00e1bito, el gui\u00f3n cultural \u2014 sin verg\u00fcenza. La gente se inclina hacia adelante cuando el predicador dice la verdad sobre lo dif\u00edcil."
M["The way forward"] = "El camino hacia adelante"
M["Show the gospel path: what Christ has done"] = "Muestra el camino del evangelio: lo que Cristo ha hecho, y la respuesta concreta de esta semana. \u00c1talo al estudio de grupo y a las lecturas diarias para que el domingo no termine el domingo."
M["Land the plane on the big idea"] = "Aterriza en la gran idea"
M[" — and give one clear next step: join a group"] = " \u2014 y da un siguiente paso claro: \u00fanete a un grupo, toma el reto de la semana y sigue las lecturas diarias toda la semana."
# ---- youth ----
M["your world — school, friends, family"] = "tu mundo: la escuela, los amigos, la familia y la versi\u00f3n de ti que nadie ve"
M["Start with the real question behind this session"] = "Empieza con la pregunta real detr\u00e1s de esta sesi\u00f3n: \u00bfd\u00f3nde aparece de verdad "
M["\\u201D actually show up in "] = "\u201d en "
M["Be honest — is this easy or hard for you right now"] = "S\u00e9 honesto: \u00bfesto te resulta f\u00e1cil o dif\u00edcil ahora mismo? \u00bfPor qu\u00e9?"
M["What would change at school or online if you actually lived"] = "\u00bfQu\u00e9 cambiar\u00eda en la escuela o en l\u00ednea si de verdad vivieras esto esta semana?"
M["Who's one person who models this well"] = "\u00bfQui\u00e9n es una persona que modela bien esto? \u00bfQu\u00e9 hace diferente?"
M["This week: pick one moment — one conversation, one post"] = "Esta semana: elige un momento \u2014 una conversaci\u00f3n, una publicaci\u00f3n, una decisi\u00f3n \u2014 y deja que la verdad de esta sesi\u00f3n tome la decisi\u00f3n. Vuelve listo para contarlo."
# ---- kids ----
M["Tell the Bible story behind "] = "Cuenta la historia b\u00edblica detr\u00e1s de "
M[" in your own words — keep it short"] = " con tus propias palabras: hazlo corto, act\u00faalo donde puedas, y aterriza en una frase: \u201c"
M["Activity: have the kids draw or build one picture"] = "Actividad: que los ni\u00f1os dibujen o construyan una imagen de la gran verdad de esta semana, y que algunos voluntarios la muestren y la cuenten. Terminen diciendo juntos el vers\u00edculo de memoria."
M["Ask: \\u201CWhere can you live this out at home"] = "Pregunta: \u201c\u00bfD\u00f3nde puedes vivir esto en casa o en la escuela esta semana?\u201d Toma en serio cada respuesta."
M["Close with a simple echo prayer"] = "Cierra con una oraci\u00f3n de eco sencilla \u2014 t\u00fa dices una l\u00ednea y ellos la repiten \u2014 agradeciendo a Dios la verdad de esta semana y pidiendo ayuda para vivirla."
# ---- leader kit ----
M["You don't need to be a teacher — you need to be a host"] = "No necesitas ser maestro: necesitas ser anfitri\u00f3n. Tu trabajo son las preguntas, no las respuestas; el contenido lleva la ense\u00f1anza."
M["Start and end on time, every week"] = "Empieza y termina a tiempo, cada semana. La confianza se construye respetando el reloj."
M["Silence after a question isn't failure"] = "El silencio despu\u00e9s de una pregunta no es fracaso: cuenta hasta diez en tu cabeza antes de rescatarla. Las mejores respuestas llegan despu\u00e9s de la pausa."
M["Follow up midweek with one text to the group"] = "Da seguimiento a mitad de semana con un mensaje al grupo. Los grupos que escuchan a su l\u00edder entre sesiones terminan el recorrido."
M["Share the load early: ask someone to bring snacks"] = "Reparte la carga temprano: pide a alguien traer algo de comer, a alguien leer, a alguien orar. La propiedad compartida es la semilla del pr\u00f3ximo grupo."
M["Gather & check in (10 min)"] = "Re\u00fananse y p\u00f3nganse al d\u00eda (10 min): \u00bfc\u00f3mo fue la pr\u00e1ctica de la semana pasada?"
M["Open the session — welcome and opening question"] = "Abran la sesi\u00f3n: bienvenida y pregunta de apertura (10 min)"
M["Decide the week's practice together (5 min)"] = "Decidan juntos la pr\u00e1ctica de la semana (5 min)"
M["Pray for one another (10 min)"] = "Oren unos por otros (10 min)"
M["Pray for each member by name once a week"] = "Ora por cada miembro por nombre una vez a la semana: cambiar\u00e1 tu manera de liderar."
M["If someone shares something heavy"] = "Si alguien comparte algo pesado, agrad\u00e9cele, no lo arregles, y dale seguimiento en privado dentro de 48 horas."
M["Notice absences early. A 'we missed you' message"] = "Nota las ausencias temprano. Un mensaje de \u00abte extra\u00f1amos\u00bb en la semana dos previene una desaparici\u00f3n en la semana cuatro."
M["Read the session and the week's devotional days before"] = "Lee la sesi\u00f3n y los d\u00edas del devocional de la semana antes de que el grupo se re\u00fana"
M["Confirm host home, time, and childcare plan"] = "Confirma la casa anfitriona, el horario y el plan de cuidado de ni\u00f1os"
M["Have extra devotionals on hand for newcomers"] = "Ten devocionales extra a la mano para los nuevos"
M["Assign next week's snack and Scripture readers"] = "Asigna la comida y los lectores de la Escritura de la pr\u00f3xima semana antes de que todos se vayan"
M["Money topics can surface stress and shame"] = "Los temas de dinero pueden despertar estr\u00e9s y verg\u00fcenza. Recuerda al grupo que este recorrido ense\u00f1a principios b\u00edblicos, no asesor\u00eda financiera profesional, y se\u00f1ala hacia un profesional calificado cuando toque."
# ---- launch kit ----
M["Pastor announces the campaign vision from the platform"] = "El pastor anuncia la visi\u00f3n de la campa\u00f1a desde la plataforma"
M["Open group sign-ups after each service and online"] = "Abre inscripciones de grupos despu\u00e9s de cada culto y en l\u00ednea"
M["Order or print devotionals for the whole congregation"] = "Pide o imprime devocionales para toda la congregaci\u00f3n"
M["Preview the series in services — read Day 1 aloud"] = "Adelanta la serie en los cultos: lee el D\u00eda 1 en voz alta"
M["Youth and children's directors align their editions"] = "Los directores de j\u00f3venes y ni\u00f1os alinean sus ediciones a las mismas semanas"
M["Send the all-church launch email with group placements"] = "Env\u00eda el correo de lanzamiento a toda la iglesia con la asignaci\u00f3n de grupos"
M["Inicio Sunday: sermon 1 + devotionals in every hand"] = "Domingo de inicio: serm\u00f3n 1 + devocionales en cada mano"
M["Preach the six messages in step with the six sessions"] = "Predica los seis mensajes al paso de las seis sesiones"
M["Testimony moment each week from a group member"] = "Momento de testimonio cada semana de un miembro de grupo"
M["On-ramp every Sunday: it's never too late"] = "Rampa de entrada cada domingo: nunca es tarde para unirse a un grupo"
M["Capture testimonies in writing and video"] = "Captura testimonios por escrito y en video para el pr\u00f3ximo lanzamiento"
M["Announce the next campaign date before people leave"] = "Anuncia la fecha de la pr\u00f3xima campa\u00f1a antes de que la gente salga"
M[" walked it together"] = " lo camin\u00f3 junta"
# ---- course / book / training / family / podcast / video format layer ----
M["Read one section a day, or a chapter a week"] = "Lee una secci\u00f3n al d\u00eda, o un cap\u00edtulo a la semana con un l\u00e1piz cerca."
M[" is currently thin in your ordinary week."] = " est\u00e1 escaso en tu semana com\u00fan."
M["Trace what Scripture in this module actually claims about "] = "Rastrea lo que la Escritura de este m\u00f3dulo realmente afirma sobre "
M["Practice one measurable act of "] = "Practica un acto medible de "
M[" before the module closes."] = " antes de que cierre el m\u00f3dulo."
M["By the end of this module you will be able to "] = "Al final de este m\u00f3dulo podr\u00e1s "
M[" \\u2014 The Course"] = " \u2014 El curso"
M[" modules receive the "] = " m\u00f3dulos reciben el "
M[" completion certificate and the alumni discussion track."] = " certificado de finalizaci\u00f3n y la pista de conversaci\u00f3n de exalumnos."
M["Before You Launch"] = "Antes de lanzar"
M["Leading the Room"] = "Liderar la sala"
M["Shepherding the Middle Weeks"] = "Pastorear las semanas del medio"
M["Landing the Plane"] = "Aterrizar el avi\u00f3n"
M["The best facilitators of "] = "Los mejores facilitadores de "
M["Groups rise to the level of their questions, so "] = "Los grupos suben al nivel de sus preguntas, as\u00ed que "
M["Your job is temperature, not content, which means "] = "Tu trabajo es la temperatura, no el contenido, lo cual significa "
M["Silence is a tool here; "] = "El silencio aqu\u00ed es una herramienta; "
M["Nobody joins a group to be lectured, so "] = "Nadie se une a un grupo para recibir c\u00e1tedra, as\u00ed que "
M["ask, wait a full seven seconds, and then wait three more."] = "pregunta, espera siete segundos completos, y luego espera tres m\u00e1s."
M["let the readings do the heavy lifting and keep your own airtime"] = "deja que las lecturas hagan el trabajo pesado y mant\u00e9n tu propio tiempo al aire por debajo de un cuarto."
M["open with the easiest honest question"] = "abre con la pregunta honesta m\u00e1s f\u00e1cil y guarda la profunda para el minuto cuarenta."
M["name the quiet person kindly and hand them the second question"] = "nombra con amabilidad a la persona callada y entr\u00e9gale la segunda pregunta, nunca la primera."
M["end five minutes early on purpose"] = "termina cinco minutos antes a prop\u00f3sito; la gente recuerda las salas que la respetaron."
M["text one member midweek about one thing they said"] = "escribe a un miembro a mitad de semana sobre algo que dijo; la retenci\u00f3n es pastoral, no procedimental."
M[" Trust the process across all "] = " Conf\u00eda en el proceso a lo largo de todas las "
M[" That single habit changes the whole journey."] = " Ese solo h\u00e1bito cambia el recorrido entero."
M[" Do this weekly and the room will start doing it for you."] = " Hazlo cada semana y la sala empezar\u00e1 a hacerlo por ti."
M[" It is small, repeatable, and it works."] = " Es peque\u00f1o, repetible, y funciona."
M["Know exactly what session "] = "Saber exactamente qu\u00e9 busca producir la sesi\u00f3n "
M[" is trying to produce"] = ""
M["Handle the two moments most likely to stall a room"] = "Manejar los dos momentos que m\u00e1s suelen estancar una sala"
M["Leave with one practice you will use this week"] = "Salir con una pr\u00e1ctica que usar\u00e1s esta semana"
M["Forty minutes of training now saves forty awkward minutes"] = "Cuarenta minutos de entrenamiento ahora ahorran cuarenta minutos inc\u00f3modos cada semana del recorrido."
M["Around the table this week, "] = "Alrededor de la mesa esta semana, "
M["One evening this week, "] = "Una noche de esta semana, "
M["On the fridge this week: "] = "En el refrigerador esta semana: "
M["Pick a night and "] = "Elige una noche y "
M["build a family list of places you spotted "] = "armen una lista familiar de lugares donde vieron "
M[" and read it out loud on Sunday."] = " y l\u00e9anla en voz alta el domingo."
M["let the youngest pick one act of "] = "que el m\u00e1s peque\u00f1o elija un acto de "
M[" the whole house does together."] = " que toda la casa haga junta."
M["write the memory verse on the mirror"] = "escriban el vers\u00edculo de memoria en el espejo y d\u00edganlo juntos en el desayuno."
M["cook one meal as a team and pray one sentence each"] = "cocinen una comida en equipo y oren una frase cada uno antes de comer."
M["take a walk and let everyone name one thing"] = "salgan a caminar y que cada uno nombre una cosa por la que est\u00e1 agradecido por cuadra."
M["have each person secretly serve one other person"] = "que cada persona sirva en secreto a otra persona de la casa, y adivinen qui\u00e9n al final de la semana."
M[" Debrief with one question: where did it feel easiest"] = " Conversen con una pregunta: \u00bfd\u00f3nde se sinti\u00f3 m\u00e1s f\u00e1cil, y d\u00f3nde m\u00e1s dif\u00edcil?"
M[" Close by asking what surprised everyone."] = " Cierren preguntando qu\u00e9 sorprendi\u00f3 a cada uno."
M[" No lecture after; the doing is the lesson."] = " Sin serm\u00f3n despu\u00e9s; el hacerlo es la lecci\u00f3n."
M[" Let the kids grade the grown-ups, kindly."] = " Dejen que los ni\u00f1os califiquen a los grandes, con cari\u00f1o."
M["thank You for this family, exactly as it is today."] = "gracias por esta familia, exactamente como es hoy."
M["thank You for our table and everyone around it."] = "gracias por nuestra mesa y por todos los que la rodean."
M[" in our home this week."] = " en nuestro hogar esta semana."
M["Help each of us practice "] = "Ayuda a cada uno de nosotros a practicar "
M[" where we live."] = " donde vivimos."
M["In Jesus\\u2019 name, amen."] = "En el nombre de Jes\u00fas, am\u00e9n."
M["Speak this over each child at bedtime once this week"] = "Di esto sobre cada hijo a la hora de dormir una vez esta semana: \u201cEres amado, eres nuestro y de Dios, y "
M[" looks good on you.\\u201D"] = " te queda bien.\u201d"
M["Ten relaxed minutes, a few nights a week"] = "Diez minutos relajados, algunas noches por semana. La gu\u00eda sigue el mismo recorrido que leen los adultos, as\u00ed que toda la casa va en una sola historia."
M["We pick the road back up next episode with "] = "Retomamos el camino en el pr\u00f3ximo episodio con "
M["Do not miss the next stretch: "] = "No te pierdas el pr\u00f3ximo tramo: "
M["the Celebration episode"] = "el episodio de Celebraci\u00f3n"
M[" \\u2014 The Podcast"] = " \u2014 El p\u00f3dcast"
M[" Subscribe and walk the whole journey with us."] = " Suscr\u00edbete y camina todo el recorrido con nosotros."
M["Shot as direct-to-camera teaching with two b-roll passes"] = "Grabado como ense\u00f1anza directa a c\u00e1mara con dos pasadas de b-roll; los guiones de abajo est\u00e1n listos para grabar y siguen el estudio de grupo paso a paso."
M["your family"] = "tu familia"

if __name__ == '__main__':
    P = '/home/claude/site_es/engine.js'
    h = apply(P, M)
    print('map3 applied:', h, 'literals')
    r = subprocess.run(['node', '--check', P], capture_output=True, text=True)
    print('syntax:', 'OK' if r.returncode == 0 else r.stderr[:300])
