# -*- coding: utf-8 -*-
from es_map1 import apply
import subprocess

M = {}
# ---- session scaffolds ----
M["Close in prayer: thank God for what was shared tonight"] = "Encerrem em ora\u00e7\u00e3o: agrade\u00e7am a Deus pelo que foi compartilhado hoje, orem por uma necessidade espec\u00edfica dita no c\u00edrculo e pe\u00e7am que Ele torne real a pr\u00e1tica desta semana."
M[" — what made you say yes to this journey"] = " \u2014 o que fez voc\u00ea dizer sim a esta jornada, e o que espera que esteja diferente no final?"
M[": put this session's big idea into practice through the "] = ": coloque em pr\u00e1tica a grande ideia desta sess\u00e3o por meio do exerc\u00edcio "
M[" exercise, and come ready to share how it went."] = ", e venha pronto para contar como foi."
M[": work through it together before the next session"] = ": fa\u00e7am juntos antes da pr\u00f3xima sess\u00e3o, e tragam uma descoberta de volta ao grupo."
M["As we begin "] = "Ao come\u00e7ar "
M["This week's challenge — "] = "O desafio desta semana \u2014 "
M["This week's family exercise — "] = "O exerc\u00edcio familiar desta semana \u2014 "
# ---- sermon beats ----
M["Open with a story or moment your people will recognize"] = "Abra com uma hist\u00f3ria ou um momento que o seu povo reconhe\u00e7a \u2014 o lugar cotidiano onde a tens\u00e3o desta semana aparece \u2014 e nomeie sem rodeios: \u00e9 disto que vamos falar hoje."
M["What God declares"] = "O que Deus declara"
M["Ground the message in the text before the takeaways"] = "Ancore a mensagem no texto antes das conclus\u00f5es. Que a congrega\u00e7\u00e3o ou\u00e7a o que Deus diz sobre "
M[" before hearing what we should do."] = " antes de ouvir o que devemos fazer."
M["Why we struggle"] = "Por que \u00e9 dif\u00edcil para n\u00f3s"
M["Name the honest obstacle"] = "Nomeie o obst\u00e1culo honesto \u2014 o medo, o h\u00e1bito, o roteiro cultural \u2014 sem vergonha. As pessoas se inclinam quando o pregador diz a verdade sobre o dif\u00edcil."
M["The way forward"] = "O caminho adiante"
M["Show the gospel path: what Christ has done"] = "Mostre o caminho do evangelho: o que Cristo fez, e a resposta concreta desta semana. Amarre ao estudo de grupo e \u00e0s leituras di\u00e1rias para que o domingo n\u00e3o termine no domingo."
M["Land the plane on the big idea"] = "Aterrisse na grande ideia"
M[" — and give one clear next step: join a group"] = " \u2014 e d\u00ea um pr\u00f3ximo passo claro: entre num grupo, aceite o desafio da semana e siga as leituras di\u00e1rias a semana toda."
# ---- youth ----
M["your world — school, friends, family"] = "seu mundo: a escola, os amigos, a fam\u00edlia e a vers\u00e3o de voc\u00ea que ningu\u00e9m v\u00ea"
M["Start with the real question behind this session"] = "Comece com a pergunta real por tr\u00e1s desta sess\u00e3o: onde \u00e9 que aparece de verdade "
M["\\u201D actually show up in "] = "\u201d em "
M["Be honest — is this easy or hard for you right now"] = "Seja honesto: isto est\u00e1 f\u00e1cil ou dif\u00edcil para voc\u00ea agora? Por qu\u00ea?"
M["What would change at school or online if you actually lived"] = "O que mudaria na escola ou na internet se voc\u00ea realmente vivesse isto esta semana?"
M["Who's one person who models this well"] = "Quem \u00e9 uma pessoa que modela bem isto? O que ela faz de diferente?"
M["This week: pick one moment — one conversation, one post"] = "Esta semana: escolha um momento \u2014 uma conversa, uma publica\u00e7\u00e3o, uma decis\u00e3o \u2014 e deixe a verdade desta sess\u00e3o dar a palavra final. Volte pronto para contar."
# ---- kids ----
M["Tell the Bible story behind "] = "Conte a hist\u00f3ria b\u00edblica por tr\u00e1s de "
M[" in your own words — keep it short"] = " com suas pr\u00f3prias palavras: seja breve, encene onde puder, e termine numa frase: \u201c"
M["Activity: have the kids draw or build one picture"] = "Atividade: pe\u00e7a \u00e0s crian\u00e7as que desenhem ou construam uma imagem da grande verdade desta semana, e deixe volunt\u00e1rios mostrarem e contarem. Terminem dizendo juntos o vers\u00edculo da semana."
M["Ask: \\u201CWhere can you live this out at home"] = "Pergunte: \u201cOnde voc\u00ea pode viver isto em casa ou na escola esta semana?\u201d Leve a s\u00e9rio cada resposta."
M["Close with a simple echo prayer"] = "Encerre com uma ora\u00e7\u00e3o de eco simples \u2014 voc\u00ea diz uma linha e eles repetem \u2014 agradecendo a Deus pela verdade desta semana e pedindo ajuda para viv\u00ea-la."
# ---- leader kit ----
M["You don't need to be a teacher — you need to be a host"] = "Voc\u00ea n\u00e3o precisa ser professor: precisa ser anfitri\u00e3o. Seu trabalho s\u00e3o as perguntas, n\u00e3o as respostas; o conte\u00fado carrega o ensino."
M["Start and end on time, every week"] = "Comece e termine na hora, toda semana. A confian\u00e7a se constr\u00f3i respeitando o rel\u00f3gio."
M["Silence after a question isn't failure"] = "Sil\u00eancio depois de uma pergunta n\u00e3o \u00e9 fracasso: conte at\u00e9 dez na cabe\u00e7a antes de resgat\u00e1-la. As melhores respostas v\u00eam depois da pausa."
M["Follow up midweek with one text to the group"] = "Acompanhe no meio da semana com uma mensagem ao grupo. Grupos que ouvem do l\u00edder entre as sess\u00f5es terminam a jornada."
M["Share the load early: ask someone to bring snacks"] = "Divida a carga cedo: pe\u00e7a a algu\u00e9m para trazer o lanche, a algu\u00e9m para ler, a algu\u00e9m para orar. Propriedade compartilhada \u00e9 a semente do pr\u00f3ximo grupo."
M["Gather & check in (10 min)"] = "Re\u00fanam-se e coloquem a conversa em dia (10 min): como foi a pr\u00e1tica da semana passada?"
M["Open the session — welcome and opening question"] = "Abram a sess\u00e3o: boas-vindas e pergunta de abertura (10 min)"
M["Decide the week's practice together (5 min)"] = "Decidam juntos a pr\u00e1tica da semana (5 min)"
M["Pray for one another (10 min)"] = "Orem uns pelos outros (10 min)"
M["Pray for each member by name once a week"] = "Ore por cada membro pelo nome uma vez por semana: vai mudar o seu jeito de liderar."
M["If someone shares something heavy"] = "Se algu\u00e9m compartilhar algo pesado, agrade\u00e7a, n\u00e3o conserte, e acompanhe em particular dentro de 48 horas."
M["Notice absences early. A 'we missed you' message"] = "Note as aus\u00eancias cedo. Uma mensagem de \u00absentimos sua falta\u00bb na semana dois evita um sumi\u00e7o na semana quatro."
M["Read the session and the week's devotional days before"] = "Leia a sess\u00e3o e os dias do devocional da semana antes de o grupo se reunir"
M["Confirm host home, time, and childcare plan"] = "Confirme a casa anfitri\u00e3, o hor\u00e1rio e o plano de cuidado das crian\u00e7as"
M["Have extra devotionals on hand for newcomers"] = "Tenha devocionais extras \u00e0 m\u00e3o para os novatos"
M["Assign next week's snack and Scripture readers"] = "Combine o lanche e os leitores da Escritura da pr\u00f3xima semana antes de todos sa\u00edrem"
M["Money topics can surface stress and shame"] = "Temas de dinheiro podem despertar estresse e vergonha. Lembre ao grupo que esta jornada ensina princ\u00edpios b\u00edblicos, n\u00e3o assessoria financeira profissional, e aponte para um profissional qualificado quando for o caso."
# ---- launch kit ----
M["Pastor announces the campaign vision from the platform"] = "O pastor anuncia a vis\u00e3o da campanha do p\u00falpito"
M["Open group sign-ups after each service and online"] = "Abra inscri\u00e7\u00f5es de grupos depois de cada culto e on-line"
M["Order or print devotionals for the whole congregation"] = "Encomende ou imprima devocionais para toda a congrega\u00e7\u00e3o"
M["Preview the series in services — read Day 1 aloud"] = "Antecipe a s\u00e9rie nos cultos: leia o Dia 1 em voz alta"
M["Youth and children's directors align their editions"] = "Os diretores de jovens e crian\u00e7as alinham suas edi\u00e7\u00f5es \u00e0s mesmas semanas"
M["Send the all-church launch email with group placements"] = "Envie o e-mail de lan\u00e7amento para toda a igreja com a aloca\u00e7\u00e3o de grupos"
M["Inicio Sunday: sermon 1 + devotionals in every hand"] = "Domingo de abertura: serm\u00e3o 1 + devocionais em cada m\u00e3o"
M["Preach the six messages in step with the six sessions"] = "Pregue as seis mensagens no passo das seis sess\u00f5es"
M["Testimony moment each week from a group member"] = "Momento de testemunho a cada semana de um membro de grupo"
M["On-ramp every Sunday: it's never too late"] = "Porta de entrada todo domingo: nunca \u00e9 tarde para entrar num grupo"
M["Capture testimonies in writing and video"] = "Registre testemunhos por escrito e em v\u00eddeo para o pr\u00f3ximo lan\u00e7amento"
M["Announce the next campaign date before people leave"] = "Anuncie a data da pr\u00f3xima campanha antes de as pessoas sa\u00edrem"
M[" walked it together"] = " caminhou junta"
# ---- format layer ----
M["Read one section a day, or a chapter a week"] = "Leia uma se\u00e7\u00e3o por dia, ou um cap\u00edtulo por semana com uma caneta por perto."
M[" is currently thin in your ordinary week."] = " anda escasso na sua semana comum."
M["Trace what Scripture in this module actually claims about "] = "Trace o que a Escritura deste m\u00f3dulo realmente afirma sobre "
M["Practice one measurable act of "] = "Pratique um ato mensur\u00e1vel de "
M[" before the module closes."] = " antes de o m\u00f3dulo fechar."
M["By the end of this module you will be able to "] = "Ao final deste m\u00f3dulo voc\u00ea poder\u00e1 "
M[" \\u2014 The Course"] = " \u2014 O curso"
M[" modules receive the "] = " m\u00f3dulos recebem o "
M[" completion certificate and the alumni discussion track."] = " certificado de conclus\u00e3o e a trilha de conversa de ex-alunos."
M["Before You Launch"] = "Antes de lan\u00e7ar"
M["Leading the Room"] = "Liderar a sala"
M["Shepherding the Middle Weeks"] = "Pastorear as semanas do meio"
M["Landing the Plane"] = "Aterrissar o avi\u00e3o"
M["The best facilitators of "] = "Os melhores facilitadores de "
M["Groups rise to the level of their questions, so "] = "Os grupos sobem ao n\u00edvel das suas perguntas, ent\u00e3o "
M["Your job is temperature, not content, which means "] = "Seu trabalho \u00e9 a temperatura, n\u00e3o o conte\u00fado, o que significa "
M["Silence is a tool here; "] = "O sil\u00eancio aqui \u00e9 uma ferramenta; "
M["Nobody joins a group to be lectured, so "] = "Ningu\u00e9m entra num grupo para ouvir palestra, ent\u00e3o "
M["ask, wait a full seven seconds, and then wait three more."] = "pergunte, espere sete segundos inteiros, e depois espere mais tr\u00eas."
M["let the readings do the heavy lifting and keep your own airtime"] = "deixe as leituras fazerem o trabalho pesado e mantenha o seu pr\u00f3prio tempo de fala abaixo de um quarto."
M["open with the easiest honest question"] = "abra com a pergunta honesta mais f\u00e1cil e guarde a profunda para o minuto quarenta."
M["name the quiet person kindly and hand them the second question"] = "chame com gentileza a pessoa quieta e entregue a ela a segunda pergunta, nunca a primeira."
M["end five minutes early on purpose"] = "termine cinco minutos mais cedo de prop\u00f3sito; as pessoas lembram das salas que as respeitaram."
M["text one member midweek about one thing they said"] = "mande mensagem a um membro no meio da semana sobre algo que ele disse; reten\u00e7\u00e3o \u00e9 pastoral, n\u00e3o processual."
M[" Trust the process across all "] = " Confie no processo ao longo de todas as "
M[" That single habit changes the whole journey."] = " Esse \u00fanico h\u00e1bito muda a jornada inteira."
M[" Do this weekly and the room will start doing it for you."] = " Fa\u00e7a isso toda semana e a sala come\u00e7ar\u00e1 a fazer por voc\u00ea."
M[" It is small, repeatable, and it works."] = " \u00c9 pequeno, repet\u00edvel, e funciona."
M["Know exactly what session "] = "Saber exatamente o que a sess\u00e3o "
M[" is trying to produce"] = " busca produzir"
M["Handle the two moments most likely to stall a room"] = "Lidar com os dois momentos que mais costumam travar uma sala"
M["Leave with one practice you will use this week"] = "Sair com uma pr\u00e1tica que voc\u00ea usar\u00e1 esta semana"
M["Forty minutes of training now saves forty awkward minutes"] = "Quarenta minutos de treino agora poupam quarenta minutos constrangedores em cada semana da jornada."
M["Around the table this week, "] = "Ao redor da mesa esta semana, "
M["One evening this week, "] = "Uma noite desta semana, "
M["On the fridge this week: "] = "Na geladeira esta semana: "
M["Pick a night and "] = "Escolha uma noite e "
M["build a family list of places you spotted "] = "montem uma lista da fam\u00edlia com lugares onde viram "
M[" and read it out loud on Sunday."] = " e leiam em voz alta no domingo."
M["let the youngest pick one act of "] = "deixe o mais novo escolher um ato de "
M[" the whole house does together."] = " que a casa toda fa\u00e7a junta."
M["write the memory verse on the mirror"] = "escrevam o vers\u00edculo da semana no espelho e digam juntos no caf\u00e9 da manh\u00e3."
M["cook one meal as a team and pray one sentence each"] = "cozinhem uma refei\u00e7\u00e3o em equipe e orem uma frase cada um antes de comer."
M["take a walk and let everyone name one thing"] = "fa\u00e7am uma caminhada e que cada um nomeie uma coisa pela qual \u00e9 grato por quarteir\u00e3o."
M["have each person secretly serve one other person"] = "que cada pessoa sirva em segredo outra pessoa da casa, e adivinhem quem no fim da semana."
M[" Debrief with one question: where did it feel easiest"] = " Conversem com uma pergunta: onde foi mais f\u00e1cil, e onde foi mais dif\u00edcil?"
M[" Close by asking what surprised everyone."] = " Encerrem perguntando o que surpreendeu cada um."
M[" No lecture after; the doing is the lesson."] = " Sem serm\u00e3o depois; o fazer \u00e9 a li\u00e7\u00e3o."
M[" Let the kids grade the grown-ups, kindly."] = " Deixem as crian\u00e7as darem nota aos adultos, com carinho."
M["thank You for this family, exactly as it is today."] = "obrigado por esta fam\u00edlia, exatamente como ela \u00e9 hoje."
M["thank You for our table and everyone around it."] = "obrigado pela nossa mesa e por todos ao redor dela."
M[" in our home this week."] = " no nosso lar esta semana."
M["Help each of us practice "] = "Ajuda cada um de n\u00f3s a praticar "
M[" where we live."] = " onde vivemos."
M["In Jesus\\u2019 name, amen."] = "Em nome de Jesus, am\u00e9m."
M["Speak this over each child at bedtime once this week"] = "Diga isto sobre cada filho na hora de dormir uma vez esta semana: \u201cVoc\u00ea \u00e9 amado, voc\u00ea \u00e9 nosso e de Deus, e "
M[" looks good on you.\\u201D"] = " fica bem em voc\u00ea.\u201d"
M["Ten relaxed minutes, a few nights a week"] = "Dez minutos tranquilos, algumas noites por semana. O guia segue a mesma jornada que os adultos est\u00e3o lendo, ent\u00e3o a casa inteira vai numa hist\u00f3ria s\u00f3."
M["We pick the road back up next episode with "] = "Retomamos a estrada no pr\u00f3ximo epis\u00f3dio com "
M["Do not miss the next stretch: "] = "N\u00e3o perca o pr\u00f3ximo trecho: "
M["the Celebration episode"] = "o epis\u00f3dio de Celebra\u00e7\u00e3o"
M[" \\u2014 The Podcast"] = " \u2014 O podcast"
M[" Subscribe and walk the whole journey with us."] = " Assine e caminhe a jornada inteira conosco."
M["Shot as direct-to-camera teaching with two b-roll passes"] = "Gravado como ensino direto para a c\u00e2mera com duas passagens de b-roll; os roteiros abaixo est\u00e3o prontos para gravar e acompanham o estudo de grupo passo a passo."
M["your family"] = "sua fam\u00edlia"

if __name__ == '__main__':
    P = '/home/claude/site_pt/engine.js'
    h = apply(P, M)
    print('pt map3 applied:', h)
    r = subprocess.run(['node', '--check', P], capture_output=True, text=True)
    print('syntax:', 'OK' if r.returncode == 0 else r.stderr[:300])
