# -*- coding: utf-8 -*-
from es_map1 import apply
import subprocess

M = {}
M["Not that I speak in respect of want"] = "N\u00e3o digo isto como por necessidade, porque j\u00e1 aprendi a contentar-me com o que tenho."
M["A good man leaveth an inheritance"] = "O homem de bem deixa uma heran\u00e7a aos filhos de seus filhos, mas a fazenda do pecador \u00e9 depositada para o justo."
M["He that is faithful in that which is least"] = "Quem \u00e9 fiel no m\u00ednimo tamb\u00e9m \u00e9 fiel no muito; quem \u00e9 injusto no m\u00ednimo tamb\u00e9m \u00e9 injusto no muito."
M["Every man according as he purposeth in his heart"] = "Cada um contribua segundo prop\u00f4s no seu cora\u00e7\u00e3o, n\u00e3o com tristeza ou por necessidade; porque Deus ama ao que d\u00e1 com alegria."
M["And whatsoever ye do, do it heartily"] = "E, tudo quanto fizerdes, fazei-o de todo o cora\u00e7\u00e3o, como ao Senhor e n\u00e3o aos homens."
M["Fear thou not; for I am with thee"] = "N\u00e3o temas, porque eu sou contigo; n\u00e3o te assombres, porque eu sou o teu Deus; eu te esfor\u00e7o, e te ajudo, e te sustento com a destra da minha justi\u00e7a."
M["Peace I leave with you, my peace I give"] = "Deixo-vos a paz, a minha paz vos dou; n\u00e3o vo-la dou como o mundo a d\u00e1. N\u00e3o se turbe o vosso cora\u00e7\u00e3o, nem se atemorize."
M["Be still, and know that I am God: I will be exalted"] = "Aquietai-vos e sabei que eu sou Deus; serei exaltado entre as na\u00e7\u00f5es, serei exaltado sobre a terra."
M["And if it seem evil unto you to serve the LORD"] = "Por\u00e9m, se vos parece mal servir ao Senhor, escolhei hoje a quem sirvais; por\u00e9m eu e a minha casa serviremos ao Senhor."
M["His lord said unto him, Well done"] = "E o seu senhor lhe disse: Bem est\u00e1, servo bom e fiel. Sobre o pouco foste fiel, sobre muito te colocarei; entra no gozo do teu senhor."
M["And let us not be weary in well doing"] = "E n\u00e3o nos cansemos de fazer o bem, porque a seu tempo ceifaremos, se n\u00e3o houvermos desfalecido."
M["If any of you lack wisdom"] = "E, se algum de v\u00f3s tem falta de sabedoria, pe\u00e7a-a a Deus, que a todos d\u00e1 liberalmente e n\u00e3o o lan\u00e7a em rosto; e ser-lhe-\u00e1 dada."
M["Being confident of this very thing"] = "Tendo por certo isto mesmo: que aquele que em v\u00f3s come\u00e7ou a boa obra a aperfei\u00e7oar\u00e1 at\u00e9 ao Dia de Jesus Cristo."
M["And we know that all things work together"] = "E sabemos que todas as coisas contribuem juntamente para o bem daqueles que amam a Deus, daqueles que s\u00e3o chamados por seu decreto."
M["Go ye therefore, and teach all nations"] = "Portanto, ide, ensinai todas as na\u00e7\u00f5es, batizando-as em nome do Pai, e do Filho, e do Esp\u00edrito Santo."
M["For we are his workmanship"] = "Porque somos feitura sua, criados em Cristo Jesus para as boas obras, as quais Deus preparou para que and\u00e1ssemos nelas."
M["I have fought a good fight"] = "Combati o bom combate, acabei a carreira, guardei a f\u00e9."
M["So teach us to number our days"] = "Ensina-nos a contar os nossos dias, de tal maneira que alcancemos cora\u00e7\u00f5es s\u00e1bios."
M["I am the vine, ye are the branches"] = "Eu sou a videira, v\u00f3s, as varas; quem est\u00e1 em mim, e eu nele, esse d\u00e1 muito fruto, porque sem mim nada podereis fazer."
M["Bring ye all the tithes into the storehouse"] = "Trazei todos os d\u00edzimos \u00e0 casa do tesouro, para que haja mantimento na minha casa, e depois fazei prova de mim, diz o Senhor dos Ex\u00e9rcitos, se eu n\u00e3o vos abrir as janelas do c\u00e9u."
M["But who am I, and what is my people"] = "Porque quem sou eu, e quem \u00e9 o meu povo, para que pud\u00e9ssemos oferecer voluntariamente cousas semelhantes? Porque tudo vem de ti, e da tua m\u00e3o to damos."
M["Except the LORD build the house"] = "Se o Senhor n\u00e3o edificar a casa, em v\u00e3o trabalham os que a edificam; se o Senhor n\u00e3o guardar a cidade, em v\u00e3o vigia a sentinela."

M["your church family"] = "sua fam\u00edlia da igreja"
M["your marriage"] = "seu casamento"
M["your grandchildren's lives"] = "a vida dos seus netos"
M["this season of your life"] = "esta temporada da sua vida"
M["the families you serve"] = "as fam\u00edlias que voc\u00ea serve"
M["your leadership"] = "sua lideran\u00e7a"
M["what you've been entrusted with"] = "o que foi confiado a voc\u00ea"

M["Where in your life right now is God inviting you to take {c}"] = "Em que parte da sua vida Deus est\u00e1 convidando voc\u00ea, agora mesmo, a levar {c} mais a s\u00e9rio, e o que torna isso dif\u00edcil?"
M["What would the people closest to you say about how {c}"] = "O que as pessoas mais pr\u00f3ximas diriam sobre como {c} aparece na sua semana comum?"
M["If nothing about {ap} changed for a year"] = "Se nada mudasse em {ap} por um ano, o que isso custaria? E o que uma pequena mudan\u00e7a tornaria poss\u00edvel?"
M["What is one belief about {c} you inherited"] = "Que cren\u00e7a sobre {c} voc\u00ea herdou sem examinar, e a Escritura concorda com ela?"
M["When was the last time {c} cost you something real"] = "Quando foi a \u00faltima vez que {c} custou algo real a voc\u00ea, e o que aprendeu ao pagar?"
M["Who in your life models {c} well"] = "Quem na sua vida modela bem {c}, e o que voc\u00ea poderia emprestar do exemplo dessa pessoa esta semana?"
M["What is the biggest obstacle between you and {c}"] = "Qual \u00e9 o maior obst\u00e1culo entre voc\u00ea e {c} agora: medo, correria, d\u00favida, ou outra coisa que voc\u00ea consiga nomear?"
M["If God answered your prayers about {c} today"] = "Se Deus respondesse hoje suas ora\u00e7\u00f5es sobre {c}, sua agenda de amanh\u00e3 estaria pronta para a resposta?"
M["What is one thing you would attempt in {ap}"] = "O que voc\u00ea tentaria em {ap} se confiasse plenamente o resultado a Deus?"
M["Where have you settled for managing a problem"] = "Onde voc\u00ea se acomodou em administrar um problema que Deus oferece transformar?"
M["What does your calendar say you believe about {c}"] = "O que o seu calend\u00e1rio diz que voc\u00ea cr\u00ea sobre {c}? N\u00e3o suas palavras: seu calend\u00e1rio."
M["What would it look like to give God the first fifteen minutes"] = "Como seria dar a Deus os primeiros quinze minutos de amanh\u00e3 em vez das sobras?"
M["Who needs to hear what you read today"] = "Quem precisa ouvir o que voc\u00ea leu hoje, e o que o impede de contar?"
M["What is one habit quietly working against {c}"] = "Que h\u00e1bito trabalha em sil\u00eancio contra {c} na sua vida, e como seria substitu\u00ed-lo?"
M["If your kids or closest friends copied your version of {c}"] = "Se seus filhos ou amigos mais pr\u00f3ximos copiassem a sua vers\u00e3o de {c}, voc\u00ea ficaria feliz?"
M["What are you asking God for that He may be waiting"] = "O que voc\u00ea est\u00e1 pedindo a Deus que talvez Ele espere fazer atrav\u00e9s de voc\u00ea e n\u00e3o s\u00f3 por voc\u00ea?"
M["Where does fear vote in your decisions about {ap}"] = "Onde o medo vota nas suas decis\u00f5es sobre {ap}, e o que a coragem escolheria no lugar?"
M["What would you stop doing this week if you believed rest"] = "O que voc\u00ea deixaria de fazer esta semana se cresse que o descanso \u00e9 mandamento e n\u00e3o s\u00f3 permiss\u00e3o?"
M["When did God prove Himself faithful to you in the past"] = "Quando Deus se provou fiel a voc\u00ea no passado, e por que \u00e9 dif\u00edcil lembrar disso no presente?"
M["What part of today's reading did you want to skip"] = "Que parte da leitura de hoje voc\u00ea quis pular, e o que pode estar enterrado ali?"
M["How would this week change if you treated {c} as a relationship"] = "Como esta semana mudaria se voc\u00ea tratasse {c} como um relacionamento para desfrutar e n\u00e3o um padr\u00e3o para atingir?"
M["What is one honest sentence you have never prayed"] = "Que frase honesta voc\u00ea nunca orou em voz alta, e que tal or\u00e1-la esta noite?"
M["Where are you strong enough to help someone else with {c}"] = "Onde voc\u00ea \u00e9 forte o bastante para ajudar outra pessoa com {c}, e quem poderia ser essa pessoa?"
M["What would generous look like today"] = "Como seria o generoso hoje: com dinheiro, sim, mas tamb\u00e9m com tempo, cr\u00e9dito e aten\u00e7\u00e3o?"
M["If this journey works, what will be visibly different"] = "Se esta jornada funcionar, o que estar\u00e1 visivelmente diferente em {ap} daqui a sessenta dias?"
M["What is God's track record in your life, written down"] = "Qual \u00e9 o hist\u00f3rico de Deus na sua vida, escrito e n\u00e3o s\u00f3 lembrado? Voc\u00ea j\u00e1 escreveu?"
M["Which relationship in your life would change first"] = "Que relacionamento da sua vida mudaria primeiro se {c} criasse ra\u00edzes, e como?"
M["What are you white-knuckling that today's passage"] = "O que voc\u00ea est\u00e1 segurando com os n\u00f3s dos dedos brancos que a passagem de hoje convida a entregar?"
M["When you picture God thinking about you"] = "Quando voc\u00ea imagina Deus pensando em voc\u00ea, que express\u00e3o h\u00e1 no rosto dele, e o que a verdade de hoje diz sobre essa imagem?"
M["What is one question you would ask Jesus about {c}"] = "Que pergunta voc\u00ea faria a Jesus sobre {c} se ele se sentasse \u00e0 sua frente esta noite? Fa\u00e7a mesmo assim. Ele escuta."
M["Where has cynicism crept in wearing the costume"] = "Onde o cinismo entrou fantasiado de sabedoria, e o que a obedi\u00eancia esperan\u00e7osa faria diferente?"
M["What did you underline today, and more importantly"] = "O que voc\u00ea sublinhou hoje e, mais importante, o que far\u00e1 com isso antes de dormir?"

M["Welcome to Session {n}. Before anything else, take a breath"] = "Bem-vindos \u00e0 Sess\u00e3o {n}. Antes de tudo, respirem. Esta hora n\u00e3o \u00e9 uma apresenta\u00e7\u00e3o; \u00e9 uma mesa. Toda resposta honesta \u00e9 bem-vinda aqui."
M["Good to be together for Session {n}"] = "Que bom estar juntos para a Sess\u00e3o {n}. Hoje \u00e9 simples: uma passagem, quatro conversas curtas e uma pr\u00e1tica que vale levar para casa."
M["Welcome to Session {n} of {t}. Tonight builds"] = "Bem-vindos \u00e0 Sess\u00e3o {n} de {t}. Hoje se constr\u00f3i sobre tudo at\u00e9 aqui, ent\u00e3o vamos come\u00e7ar colocando a conversa em dia."
M["Welcome back. Session {n} is not about having the right answers"] = "Bem-vindos de volta. A Sess\u00e3o {n} n\u00e3o \u00e9 sobre ter as respostas certas, e sim sobre trazer sua semana real para a sala. Comece a\u00ed e a noite se cuida sozinha."
M["Glad you're here for Session {n}"] = "Que alegria ter voc\u00eas na Sess\u00e3o {n}. Regra da casa, como sempre: escutem com generosidade, compartilhem com honestidade e deixem o sil\u00eancio fazer parte do trabalho."
M["Session {n}, friends. Phones down"] = "Sess\u00e3o {n}, amigos. Celulares para baixo se conseguirem, caf\u00e9 para cima, e vamos dar a Deus a pr\u00f3xima hora sem pressa."
M["Welcome to Session {n}. Somebody in this circle"] = "Bem-vindos \u00e0 Sess\u00e3o {n}. Algu\u00e9m neste c\u00edrculo precisava desta noite mais do que vai dizer em voz alta. Sejamos o tipo de grupo onde n\u00e3o precise dizer."
M["Here we are at Session {n}. Quick reminder"] = "C\u00e1 estamos na Sess\u00e3o {n}. Lembrete r\u00e1pido: nada do que for compartilhado nesta sala sai dela. Salas seguras fazem crescer gente honesta."
M["Welcome to Session {n} of {t}. If the week ran you over"] = "Bem-vindos \u00e0 Sess\u00e3o {n} de {t}. Se a semana passou por cima de voc\u00ea, voc\u00ea est\u00e1 exatamente no lugar certo. Venha como est\u00e1; saia um pouco mais leve."
M["Session {n} tonight. The goal is not to finish"] = "Sess\u00e3o {n} hoje. A meta n\u00e3o \u00e9 terminar as perguntas. A meta \u00e9 realmente nos encontrarmos uns com os outros, e com Deus, dentro delas."

M["Read the passage aloud together, then let it breathe"] = "Leiam a passagem em voz alta juntos e deixem-na respirar um momento antes de conversar. Notem o que ela diz de Deus antes de notar o que pede de n\u00f3s."
M["Have two people read the passage in turn"] = "Que duas pessoas leiam a passagem por turnos. Pergunte ao grupo: que palavra ou frase se destaca, e por que Deus pode estar sublinhando isso para voc\u00ea esta semana?"
M["Read the passage, then retell it in your own words"] = "Leiam a passagem e depois recontem com suas pr\u00f3prias palavras como grupo. A linguagem simples costuma revelar o que a linguagem familiar esconde."
M["Read slowly, twice. First time for the room"] = "Leiam devagar, duas vezes. A primeira para a sala, a segunda para voc\u00ea. Depois compartilhem uma primeira rea\u00e7\u00e3o honesta; sem polir est\u00e1 bom."
M["Before discussing, sit with thirty seconds of quiet"] = "Antes de conversar, guardem trinta segundos de sil\u00eancio depois da leitura. Que o leitor mais jovem comece hoje."
M["Read the passage and ask the oldest saint"] = "Leiam a passagem e perguntem ao santo mais velho da sala o que este vers\u00edculo significou ao longo dos anos dele. A experi\u00eancia \u00e9 um coment\u00e1rio que dinheiro n\u00e3o compra."
M["Read the text, then have each person finish this sentence"] = "Leiam o texto e que cada pessoa complete esta frase: se este vers\u00edculo \u00e9 verdade, ent\u00e3o a minha semana..."
M["Read it once in full, then a second time stopping at every verb"] = "Leiam uma vez por inteiro e uma segunda vez parando em cada verbo. Os verbos s\u00e3o onde a Escritura pede as nossas m\u00e3os, n\u00e3o s\u00f3 as nossas cabe\u00e7as."
M["Read the passage and name together what it says about God's character"] = "Leiam a passagem e nomeiem juntos o que ela diz do car\u00e1ter de Deus antes de tudo. Quem Ele \u00e9 sempre vem antes do que fazemos."
M["Read aloud, then ask: what would it look like if our group actually believed"] = "Leiam em voz alta e perguntem: como seria se o nosso grupo realmente cresse nisso at\u00e9 quinta-feira?"
M["Read the passage, then let each person share where their eyes snagged"] = "Leiam a passagem e que cada pessoa conte onde os olhos engancharam. Enganches costumam ser convites."
M["Read the text and ask the room: what does this make possible"] = "Leiam o texto e perguntem \u00e0 sala: o que isto torna poss\u00edvel que na segunda-feira parecia imposs\u00edvel?"

M["Application: name one specific place this truth touches your week"] = "Aplica\u00e7\u00e3o: nomeie um lugar espec\u00edfico onde esta verdade toca sua semana, uma decis\u00e3o, um relacionamento, um h\u00e1bito, e diga em voz alta ao grupo."
M["Application: pair up for three minutes"] = "Aplica\u00e7\u00e3o: em duplas por tr\u00eas minutos. Cada pessoa responde: como seria obedecer a isto para mim antes de nos reunirmos de novo?"
M["Application: write one sentence, privately"] = "Aplica\u00e7\u00e3o: escreva uma frase, em particular, come\u00e7ando com \u00abEsta semana eu vou...\u00bb. Compartilhe s\u00f3 se quiser. Inten\u00e7\u00f5es escritas sobrevivem \u00e0s faladas."
M["Application: pick the smallest real step"] = "Aplica\u00e7\u00e3o: escolha o menor passo real que esta passagem sugere e declare-o diante do grupo. Pequeno e declarado vence grande e vago."
M["Application: identify one person outside this room"] = "Aplica\u00e7\u00e3o: identifique uma pessoa fora desta sala que precisa desta verdade, e decidam juntos como ela pode chegar a essa pessoa esta semana."
M["Application: look at your own calendar for the next three days"] = "Aplica\u00e7\u00e3o: olhe seu calend\u00e1rio dos pr\u00f3ximos tr\u00eas dias. Onde esta passagem ser\u00e1 testada primeiro? Nomeie o momento agora."
M["Application: choose a group-wide experiment"] = "Aplica\u00e7\u00e3o: escolham um experimento de todo o grupo a partir da verdade de hoje, uma pr\u00e1tica compartilhada, na mesma semana, e comparem notas na pr\u00f3xima sess\u00e3o."
M["Application: finish this sentence honestly"] = "Aplica\u00e7\u00e3o: complete esta frase com honestidade: a raz\u00e3o de isto ser dif\u00edcil para mim \u00e9... Depois, que o grupo ore exatamente por isso."
M["Application: turn tonight's big idea into a question"] = "Aplica\u00e7\u00e3o: transforme a grande ideia de hoje numa pergunta que voc\u00ea far\u00e1 na sua pr\u00f3pria mesa esta semana, e volte contando o que a mesa disse."
M["Application: pick one habit that quietly fights this truth"] = "Aplica\u00e7\u00e3o: escolha um h\u00e1bito que luta em sil\u00eancio contra esta verdade e nomeie o substituto. H\u00e1bitos n\u00e3o v\u00e3o embora; s\u00e3o despejados por inquilinos melhores."
M["Application: agree on one text message"] = "Aplica\u00e7\u00e3o: combinem uma mensagem que o grupo enviar\u00e1 entre si no meio da semana, de cinco palavras ou menos, ligada \u00e0 ideia de hoje."
M["Application: decide what 'done' looks like by Sunday"] = "Aplica\u00e7\u00e3o: decidam como \u00e9 o \u00abfeito\u00bb at\u00e9 domingo. Obedi\u00eancia vaga evapora; obedi\u00eancia definida aparece."

M["Exactly what our launch needed"] = "Exatamente o que o nosso lan\u00e7amento precisava"
M["Our groups actually finished this one"] = "Nossos grupos realmente terminaram este"
M["The daily rhythm is the secret"] = "O ritmo di\u00e1rio \u00e9 o segredo"
M["Complete out of the box"] = "Completo desde o primeiro dia"
M["Best on-ramp to groups we've used"] = "A melhor porta de entrada para grupos que j\u00e1 usamos"
M["We ran {t} across our whole church and the {fmt} rhythm"] = "Rodamos {t} na nossa igreja inteira e o ritmo de {fmt} manteve as pessoas al\u00e9m da segunda semana, algo que honestamente nunca tinha acontecido conosco. Os grupos continuam se reunindo."
M["What sold me was how complete it is"] = "O que me convenceu foi o quanto \u00e9 completo. Devocional, estudo de grupo, esbo\u00e7os de serm\u00f5es e a edi\u00e7\u00e3o infantil alinhados semana a semana, ent\u00e3o as fam\u00edlias iam numa hist\u00f3ria s\u00f3."
M["I've launched a lot of series that ended on Sunday"] = "J\u00e1 lancei muitas s\u00e9ries que terminavam no domingo. Esta n\u00e3o. As pessoas me citavam as leituras di\u00e1rias no meio da semana, e tr\u00eas dos nossos grupos continuam se reunindo por conta pr\u00f3pria."
M["As a {role}, I was watching for whether the {th} theme"] = "Como {role}, eu estava atento se o tema de {th} se sustentaria pela jornada inteira. Sustentou: cada semana construiu sobre a anterior, e o desafio semanal tornou tudo pr\u00e1tico."
M["Our hosts are volunteers, not teachers"] = "Nossos anfitri\u00f5es s\u00e3o volunt\u00e1rios, n\u00e3o professores, e o formato de quatro movimentos os carregou por completo. S\u00f3 a dica da mensagem de meio de semana no kit de l\u00edderes j\u00e1 valeu."
M["Honest review: week one felt like any other study"] = "Avalia\u00e7\u00e3o honesta: a primeira semana pareceu um estudo qualquer. Na terceira, o ritmo di\u00e1rio tinha feito algo que uma s\u00e9rie de serm\u00f5es nunca faz. Vamos rodar outro."
M["I recommend campaigns to the families I serve"] = "Recomendo campanhas \u00e0s fam\u00edlias que sirvo, e {t} \u00e9 a que coloco nas m\u00e3os de quem navega exatamente esta temporada. Biblicamente s\u00f3lida e pr\u00e1tica."
M["Senior Pastor"] = "Pastor titular"
M["Executive Pastor"] = "Pastor executivo"
M["Small Groups Pastor"] = "Pastor de pequenos grupos"
M["Discipleship Pastor"] = "Pastor de discipulado"
M["Lead Pastor"] = "Pastor l\u00edder"
M["Campus Pastor"] = "Pastor de campus"
M["Family Ministry Director"] = "Diretor de minist\u00e9rio familiar"
M["Church Planter"] = "Plantador de igrejas"
M["Worship Pastor"] = "Pastor de louvor"
M["Missions Director"] = "Diretor de miss\u00f5es"
M["Financial Advisor"] = "Assessor financeiro"
M["Estate Attorney"] = "Advogado de sucess\u00f5es"
M["Family Office Director"] = "Diretor de family office"
M["Wealth Manager"] = "Gestor de patrim\u00f4nio"
M["Ministry Development Officer"] = "Oficial de desenvolvimento ministerial"
M["January 2026"] = "Janeiro de 2026"
M["February 2026"] = "Fevereiro de 2026"
M["March 2026"] = "Mar\u00e7o de 2026"
M["April 2026"] = "Abril de 2026"
M["May 2026"] = "Maio de 2026"
M["June 2026"] = "Junho de 2026"
M["November 2025"] = "Novembro de 2025"
M["December 2025"] = "Dezembro de 2025"
M["October 2025"] = "Outubro de 2025"
M["September 2025"] = "Setembro de 2025"

if __name__ == '__main__':
    P = '/home/claude/site_pt/engine.js'
    h = apply(P, M)
    print('pt map1 applied:', h)
    r = subprocess.run(['node', '--check', P], capture_output=True, text=True)
    print('syntax:', 'OK' if r.returncode == 0 else r.stderr[:200])
