import json
P = [
("Where every other category begins: whose is it, really? The stewardship shelf reframes money, time, and talent as a trust — and turns the most awkward subject in church into the most freeing one.",
 "Donde empieza toda otra categor\u00eda: \u00bfde qui\u00e9n es, realmente? El estante de mayordom\u00eda replantea el dinero, el tiempo y el talento como un encargo, y convierte el tema m\u00e1s inc\u00f3modo de la iglesia en el m\u00e1s liberador.",
 "Onde toda outra categoria come\u00e7a: de quem \u00e9, realmente? A estante de mordomia reposiciona dinheiro, tempo e talento como algo confiado, e transforma o assunto mais desconfort\u00e1vel da igreja no mais libertador."),
("For the church that has enough and still feels the ache. These journeys trade the treadmill of more for the deep breath of enough — treasure relocated, hearts unclenched.",
 "Para la iglesia que tiene suficiente y a\u00fan siente el vac\u00edo. Estos recorridos cambian la rueda del m\u00e1s por el respiro profundo del suficiente: tesoros reubicados, corazones que se sueltan.",
 "Para a igreja que tem o suficiente e ainda sente o aperto. Essas jornadas trocam a esteira do mais pela respirada funda do suficiente: tesouros realocados, cora\u00e7\u00f5es que se soltam."),
("Generosity that starts in the heart, not the budget meeting. Journeys that make giving contagious — first fruits, open hands, and the strange joy of letting go.",
 "Generosidad que empieza en el coraz\u00f3n, no en la reuni\u00f3n de presupuesto. Recorridos que hacen contagioso el dar: primeros frutos, manos abiertas y el extra\u00f1o gozo de soltar.",
 "Generosidade que come\u00e7a no cora\u00e7\u00e3o, n\u00e3o na reuni\u00e3o de or\u00e7amento. Jornadas que tornam o doar contagiante: primeiros frutos, m\u00e3os abertas e a estranha alegria de soltar."),
("Eyes up. These campaigns lift a congregation from maintenance to mission — kingdom math, sent people, and a church that measures itself by what leaves the building.",
 "La mirada en alto. Estas campa\u00f1as levantan a una congregaci\u00f3n del mantenimiento a la misi\u00f3n: matem\u00e1tica del Reino, gente enviada y una iglesia que se mide por lo que sale del edificio.",
 "Olhos para cima. Essas campanhas erguem uma congrega\u00e7\u00e3o da manuten\u00e7\u00e3o para a miss\u00e3o: matem\u00e1tica do Reino, gente enviada e uma igreja que se mede pelo que sai do pr\u00e9dio."),
("More than money passes down. The legacy shelf helps families move wisdom before wealth — preparing people, not just papers, for what they will one day carry.",
 "Se transmite m\u00e1s que dinero. El estante de legado ayuda a las familias a mover sabidur\u00eda antes que riqueza: preparando personas, no solo papeles, para lo que un d\u00eda cargar\u00e1n.",
 "Passa-se mais do que dinheiro. A estante de legado ajuda as fam\u00edlias a mover sabedoria antes de riqueza: preparando pessoas, n\u00e3o s\u00f3 pap\u00e9is, para o que um dia v\u00e3o carregar."),
("For the ones inheriting everything: identity before assets, character before capital. Journeys that anchor young adults and heirs in who they are before what they own.",
 "Para los que lo heredan todo: identidad antes que bienes, car\u00e1cter antes que capital. Recorridos que anclan a j\u00f3venes y herederos en qui\u00e9nes son antes de lo que poseen.",
 "Para os que herdam tudo: identidade antes de bens, car\u00e1ter antes de capital. Jornadas que ancoram jovens e herdeiros em quem eles s\u00e3o antes do que possuem."),
("The household shelf. Mission statements at the dinner table, values that survive the minivan years, and parents discipling on purpose instead of by accident.",
 "El estante del hogar. Declaraciones de misi\u00f3n en la mesa, valores que sobreviven los a\u00f1os de la minivan y padres discipulando a prop\u00f3sito, no por accidente.",
 "A estante do lar. Declara\u00e7\u00f5es de miss\u00e3o \u00e0 mesa, valores que sobrevivem aos anos de correria e pais discipulando de prop\u00f3sito, n\u00e3o por acidente."),
("Monday matters. Work as worship, the marketplace as a mission field, and succession as stewardship — for the builders, owners, and leaders in your pews.",
 "El lunes importa. El trabajo como adoraci\u00f3n, el mundo laboral como campo de misi\u00f3n y la sucesi\u00f3n como mayordom\u00eda: para los constructores, due\u00f1os y l\u00edderes en tus bancas.",
 "A segunda-feira importa. O trabalho como adora\u00e7\u00e3o, o mercado como campo mission\u00e1rio e a sucess\u00e3o como mordomia: para os construtores, donos e l\u00edderes nos seus bancos."),
("Influence is a trust. These journeys form leaders who serve — wisdom over cleverness, character over charisma, and a long obedience in the same direction.",
 "La influencia es un encargo. Estos recorridos forman l\u00edderes que sirven: sabidur\u00eda sobre astucia, car\u00e1cter sobre carisma y una larga obediencia en la misma direcci\u00f3n.",
 "Influ\u00eancia \u00e9 algo confiado. Essas jornadas formam l\u00edderes que servem: sabedoria acima de esperteza, car\u00e1ter acima de carisma e uma longa obedi\u00eancia na mesma dire\u00e7\u00e3o."),
("Back to bedrock. Faith and trust journeys for seasons of doubt, transition, and beginnings — the promises of God, tested where people actually live.",
 "De vuelta a la roca. Recorridos de fe y confianza para temporadas de duda, transici\u00f3n y comienzos: las promesas de Dios, probadas donde la gente realmente vive.",
 "De volta \u00e0 rocha. Jornadas de f\u00e9 e confian\u00e7a para temporadas de d\u00favida, transi\u00e7\u00e3o e come\u00e7os: as promessas de Deus, testadas onde as pessoas realmente vivem."),
("Every season preaches. From the second half to finishing well, journeys tuned to the age and stage your people are actually in — not the one the curriculum assumed.",
 "Cada temporada predica. De la segunda mitad a terminar bien, recorridos afinados a la edad y etapa real de tu gente, no a la que el curr\u00edculo supuso.",
 "Cada temporada prega. Da segunda metade ao terminar bem, jornadas afinadas \u00e0 idade e fase real do seu povo, n\u00e3o \u00e0 que o curr\u00edculo presumiu."),
("For the church that is tired, grieving, or starting over. Hope, peace, and new beginnings — gentle journeys with real spine, paced for healing.",
 "Para la iglesia cansada, en duelo o empezando de nuevo. Esperanza, paz y nuevos comienzos: recorridos suaves con columna real, a ritmo de sanidad.",
 "Para a igreja cansada, em luto ou recome\u00e7ando. Esperan\u00e7a, paz e novos come\u00e7os: jornadas suaves com espinha de verdade, no ritmo da cura."),
("Two people, one covenant, forty days. Marriage journeys that get couples talking again — honest questions, shared practices, and a table set for grace.",
 "Dos personas, un pacto, cuarenta d\u00edas. Recorridos de matrimonio que hacen que las parejas vuelvan a hablar: preguntas honestas, pr\u00e1cticas compartidas y una mesa puesta para la gracia.",
 "Duas pessoas, uma alian\u00e7a, quarenta dias. Jornadas de casamento que fazem os casais voltarem a conversar: perguntas honestas, pr\u00e1ticas compartilhadas e uma mesa posta para a gra\u00e7a."),
("Who am I, and what am I for? Purpose and identity journeys that move people from drift to direction — calling clarified, gifts named, next steps taken.",
 "\u00bfQui\u00e9n soy y para qu\u00e9 estoy? Recorridos de prop\u00f3sito e identidad que mueven a las personas de la deriva a la direcci\u00f3n: llamado aclarado, dones nombrados, pasos dados.",
 "Quem sou eu, e para que estou aqui? Jornadas de prop\u00f3sito e identidade que movem as pessoas da deriva para a dire\u00e7\u00e3o: chamado esclarecido, dons nomeados, passos dados."),
("The long game of the soul. Prayer, worship, Scripture, and the ordinary habits that form extraordinary people — discipleship with a daily pulse.",
 "El juego largo del alma. Oraci\u00f3n, adoraci\u00f3n, Escritura y los h\u00e1bitos ordinarios que forman personas extraordinarias: discipulado con pulso diario.",
 "O jogo longo da alma. Ora\u00e7\u00e3o, adora\u00e7\u00e3o, Escritura e os h\u00e1bitos comuns que formam pessoas extraordin\u00e1rias: discipulado com pulso di\u00e1rio."),
("Money comes up constantly in Scripture, and these campaigns treat it as a discipleship topic rather than a budgeting one. Most start with a simple question: whose is it, really?",
 "El dinero aparece constantemente en la Escritura, y estas campa\u00f1as lo tratan como tema de discipulado, no de presupuesto. La mayor\u00eda empieza con una pregunta simple: \u00bfde qui\u00e9n es, realmente?",
 "O dinheiro aparece o tempo todo na Escritura, e essas campanhas o tratam como tema de discipulado, n\u00e3o de or\u00e7amento. A maioria come\u00e7a com uma pergunta simples: de quem \u00e9, realmente?"),
("A lot of what looks like ambition in church life is really just comparison. These campaigns work through contentment and gratitude as practical, weekly habits rather than one-time decisions.",
 "Mucho de lo que parece ambici\u00f3n en la vida de iglesia es en realidad comparaci\u00f3n. Estas campa\u00f1as trabajan el contentamiento y la gratitud como h\u00e1bitos semanales pr\u00e1cticos, no decisiones de una sola vez.",
 "Muito do que parece ambi\u00e7\u00e3o na vida da igreja \u00e9 na verdade compara\u00e7\u00e3o. Essas campanhas trabalham contentamento e gratid\u00e3o como h\u00e1bitos semanais pr\u00e1ticos, n\u00e3o decis\u00f5es de uma vez s\u00f3."),
("Giving campaigns tend to work better when generosity is framed as a character trait, not an ask. These journeys focus on building that habit first.",
 "Las campa\u00f1as de dar funcionan mejor cuando la generosidad se plantea como rasgo de car\u00e1cter, no como petici\u00f3n. Estos recorridos se enfocan primero en construir ese h\u00e1bito.",
 "Campanhas de doa\u00e7\u00e3o funcionam melhor quando a generosidade \u00e9 colocada como tra\u00e7o de car\u00e1ter, n\u00e3o como pedido. Essas jornadas focam primeiro em construir esse h\u00e1bito."),
("For churches asking what they exist to do beyond their own walls \u2014 outreach, local mission, and multiplying what they\u2019ve learned into other communities.",
 "Para iglesias que se preguntan qu\u00e9 existen para hacer m\u00e1s all\u00e1 de sus muros: alcance, misi\u00f3n local y multiplicar lo aprendido en otras comunidades.",
 "Para igrejas que perguntam o que existem para fazer al\u00e9m dos pr\u00f3prios muros: alcance, miss\u00e3o local e multiplicar o que aprenderam em outras comunidades."),
("For families thinking beyond a will and a bank account. These campaigns are about passing down faith and judgment, not just assets \u2014 useful alongside estate planning conversations, not instead of them.",
 "Para familias que piensan m\u00e1s all\u00e1 de un testamento y una cuenta bancaria. Estas campa\u00f1as tratan de transmitir fe y criterio, no solo bienes: \u00fatiles junto a las conversaciones de planificaci\u00f3n patrimonial, no en su lugar.",
 "Para fam\u00edlias que pensam al\u00e9m de um testamento e uma conta banc\u00e1ria. Essas campanhas s\u00e3o sobre transmitir f\u00e9 e crit\u00e9rio, n\u00e3o s\u00f3 bens: \u00fateis junto \u00e0s conversas de planejamento patrimonial, n\u00e3o no lugar delas."),
("Written for students and young adults, and for the parents trying to have honest conversations with them about money, character, and what comes next.",
 "Escritas para estudiantes y j\u00f3venes adultos, y para los padres que intentan tener conversaciones honestas con ellos sobre dinero, car\u00e1cter y lo que viene.",
 "Escritas para estudantes e jovens adultos, e para os pais que tentam ter conversas honestas com eles sobre dinheiro, car\u00e1ter e o que vem a seguir."),
("Practical material for the conversations that happen at home \u2014 around the dinner table, in the car, at bedtime \u2014 for parents and grandparents alike.",
 "Material pr\u00e1ctico para las conversaciones que pasan en casa \u2014 en la mesa, en el auto, a la hora de dormir \u2014 tanto para padres como para abuelos.",
 "Material pr\u00e1tico para as conversas que acontecem em casa \u2014 \u00e0 mesa, no carro, na hora de dormir \u2014 para pais e av\u00f3s igualmente."),
("For people who spend most of their week at a job or running a business. These treat work itself as a place for discipleship, not a break from it.",
 "Para quienes pasan la mayor parte de su semana en un empleo o dirigiendo un negocio. Aqu\u00ed el trabajo mismo es lugar de discipulado, no un descanso de \u00e9l.",
 "Para quem passa a maior parte da semana num emprego ou tocando um neg\u00f3cio. Aqui o pr\u00f3prio trabalho \u00e9 lugar de discipulado, n\u00e3o uma pausa dele."),
("On the responsibility that comes with influence \u2014 at church, at work, or in the community \u2014 and how character has to keep pace with growing responsibility.",
 "Sobre la responsabilidad que viene con la influencia \u2014 en la iglesia, el trabajo o la comunidad \u2014 y c\u00f3mo el car\u00e1cter debe ir al paso de la responsabilidad que crece.",
 "Sobre a responsabilidade que vem com a influ\u00eancia \u2014 na igreja, no trabalho ou na comunidade \u2014 e como o car\u00e1ter precisa acompanhar a responsabilidade que cresce."),
("For seasons when trust is genuinely hard \u2014 campaigns about faith holding up under real uncertainty, not just in easier times.",
 "Para temporadas en que confiar es genuinamente dif\u00edcil: campa\u00f1as sobre una fe que se sostiene bajo incertidumbre real, no solo en tiempos f\u00e1ciles.",
 "Para temporadas em que confiar \u00e9 genuinamente dif\u00edcil: campanhas sobre uma f\u00e9 que se sustenta sob incerteza real, n\u00e3o s\u00f3 em tempos f\u00e1ceis."),
("Every season a person and a church walk through. Singleness, midlife, empty nest, retirement, plus the whole church calendar: Thanksgiving, Advent and Christmas, Lent and Easter, New Year, summer, and the fall launch.",
 "Cada temporada que una persona y una iglesia atraviesan. Solter\u00eda, mediana edad, nido vac\u00edo, jubilaci\u00f3n, m\u00e1s todo el calendario de la iglesia: Acci\u00f3n de Gracias, Adviento y Navidad, Cuaresma y Pascua, A\u00f1o Nuevo, verano y el lanzamiento de oto\u00f1o.",
 "Cada temporada que uma pessoa e uma igreja atravessam. Solteirice, meia-idade, ninho vazio, aposentadoria, mais todo o calend\u00e1rio da igreja: A\u00e7\u00e3o de Gra\u00e7as, Advento e Natal, Quaresma e P\u00e1scoa, Ano Novo, ver\u00e3o e o lan\u00e7amento do segundo semestre."),
("Gentler campaigns for people working through grief, a hard season, or starting over. These lean toward encouragement and pacing rather than urgency.",
 "Campa\u00f1as m\u00e1s suaves para quienes atraviesan duelo, una temporada dura o un nuevo comienzo. Se inclinan al \u00e1nimo y al ritmo, no a la urgencia.",
 "Campanhas mais suaves para quem atravessa luto, uma temporada dura ou um recome\u00e7o. Elas pendem para o encorajamento e o ritmo, n\u00e3o para a urg\u00eancia."),
("Covers marriage broadly \u2014 dating and engagement, conflict and repair, in-laws and adult siblings, blended families finding a new rhythm. Not just the newly married or the long-married.",
 "Abarca el matrimonio en sentido amplio: noviazgo y compromiso, conflicto y reparaci\u00f3n, suegros y hermanos adultos, familias ensambladas encontrando un nuevo ritmo. No solo reci\u00e9n casados o matrimonios largos.",
 "Cobre o casamento em sentido amplo: namoro e noivado, conflito e reparo, sogros e irm\u00e3os adultos, fam\u00edlias recompostas achando um novo ritmo. N\u00e3o s\u00f3 rec\u00e9m-casados ou casamentos longos."),
("On identity and calling: figuring out who you are before figuring out what to do next. Includes vision-setting and career-related material as well.",
 "Sobre identidad y llamado: descubrir qui\u00e9n eres antes de decidir qu\u00e9 hacer. Incluye tambi\u00e9n material de visi\u00f3n y de carrera.",
 "Sobre identidade e chamado: descobrir quem voc\u00ea \u00e9 antes de decidir o que fazer. Inclui tamb\u00e9m material de vis\u00e3o e de carreira."),
("The steadier disciplines \u2014 prayer, worship, and regular time in Scripture \u2014 for churches building consistency rather than running a single big push.",
 "Las disciplinas m\u00e1s constantes \u2014 oraci\u00f3n, adoraci\u00f3n y tiempo regular en la Escritura \u2014 para iglesias que construyen constancia en vez de correr un solo gran empuj\u00f3n.",
 "As disciplinas mais constantes \u2014 ora\u00e7\u00e3o, adora\u00e7\u00e3o e tempo regular na Escritura \u2014 para igrejas construindo const\u00e2ncia em vez de um \u00fanico grande empurr\u00e3o."),
]
es={en:es for en,es,pt in P}; pt={en:pt for en,es,pt in P}
json.dump(es, open('/home/claude/tr_es_6.json','w'), ensure_ascii=False)
json.dump(pt, open('/home/claude/tr_pt_6.json','w'), ensure_ascii=False)
print("categories maps:", len(es), "pairs each")
