import json, re, glob

# fix the spelled-out stale counts in ALL builds including English
for d in ['/home/claude/site','/home/claude/site_es','/home/claude/site_pt']:
    for fn,old,new in [
      ('categories.html','Fifteen doors. Five hundred thirty-three journeys.','Fifteen doors. 1,252 journeys.'),
      ('get-access.html','Five hundred thirty-three finished campaigns','1,252 finished campaigns')]:
        p=f'{d}/{fn}'; s=open(p).read()
        if old in s: open(p,'w').write(s.replace(old,new)); print('fixed 533-in-words:',d.split("/")[-1],fn)

ES = {
"Fifteen doors. 1,252 journeys.":"Quince puertas. 1.252 recorridos.",
"1,252 finished campaigns":"1.252 campa\u00f1as terminadas",
# browse
"Browse Campaigns — 40 Day Campaigns":"Explorar campa\u00f1as \u2014 40 Day Campaigns",
"The Library · Est. 2001":"La biblioteca \u00b7 desde 2001",
"The full campaign library.":"La biblioteca completa de campa\u00f1as.",
"1252 hand-curated campaigns in the Purpose Driven tradition, each one complete — daily devotional, small-group study, sermon outlines, and launch materials included.":"1252 campa\u00f1as en la tradici\u00f3n de Una Vida con Prop\u00f3sito, cada una completa: devocional diario, estudio para grupos peque\u00f1os, bosquejos de sermones y materiales de lanzamiento incluidos.",
"All themes":"Todos los temas","All channels":"Todos los canales","Families":"Familias","Financial Advisors":"Asesores financieros","Estate Attorneys":"Abogados de sucesiones","Family Offices":"Family offices","Ministries &amp; Nonprofits":"Ministerios y ONG","Pastors":"Pastores","Business Leaders":"L\u00edderes de empresa","Students &amp; Young Adults":"J\u00f3venes y universitarios","All audiences":"Todas las audiencias","All life events":"Todos los momentos de vida","All formats":"Todos los formatos",
"Top 100":"Top 100","Staff favorites":"Favoritas del equipo","New this month":"Nuevas este mes","Recently ordered":"Pedidas recientemente","Featured":"Destacadas","Most popular":"M\u00e1s populares","Covers":"Portadas",
"No campaigns match those filters.":"Ninguna campa\u00f1a coincide con esos filtros.","Clear everything":"Limpiar todo","or try the":"o prueba el",
"1252 hand-curated campaigns · 94 themes · 15 categories · NIV reading plan · KJV verses labeled ·":"1252 campa\u00f1as \u00b7 94 temas \u00b7 15 categor\u00edas \u00b7 Plan de lectura NVI \u00b7 Vers\u00edculos KJV se\u00f1alados \u00b7",
"Say hello":"Escr\u00edbenos","Privacy":"Privacidad",
"Year-End Giving collection — short campaigns built for the giving season, ready for CPAs, advisors, and churches.":"Colecci\u00f3n de generosidad de fin de a\u00f1o: campa\u00f1as cortas para la temporada de dar, listas para contadores, asesores e iglesias.",
"Seasonal collection:":"Colecci\u00f3n de temporada:",
"That seasonal collection is coming soon — here is the full library in the meantime.":"Esa colecci\u00f3n de temporada llega pronto; mientras tanto, aqu\u00ed est\u00e1 la biblioteca completa.",
"Staff favorites — hand-picked by the Lifetogether team for range, depth, and how well they land.":"Favoritas del equipo: elegidas a mano por Lifetogether por su variedad, profundidad y c\u00f3mo aterrizan.",
"New this month — the newest additions to the library, freshly built and ready to launch.":"Nuevas este mes: las incorporaciones m\u00e1s recientes, reci\u00e9n construidas y listas para lanzar.",
"Recently ordered — campaigns other churches have put on their calendars lately.":"Pedidas recientemente: campa\u00f1as que otras iglesias han puesto en su calendario \u00faltimamente.",
# categories
"Browse by Category — 40 Day Campaigns":"Explorar por categor\u00eda \u2014 40 Day Campaigns",
"The library, by category":"La biblioteca, por categor\u00eda",
"Every category opens with its ten strongest campaigns — the ones churches launch first — with the rest one tap deeper, grouped by theme.":"Cada categor\u00eda abre con sus diez campa\u00f1as m\u00e1s fuertes \u2014 las que las iglesias lanzan primero \u2014 y el resto a un toque de distancia, agrupado por tema.",
"Or start from the very top.":"O empieza desde lo m\u00e1s alto.",
"The one hundred highest-ranked journeys in the whole library, in one shelf.":"Los cien recorridos mejor clasificados de toda la biblioteca, en un solo estante.",
"Open the Top 100 →":"Abrir el Top 100 \u2192",
"© 2026 40daycampaigns.com · A Lifetogether ministry":"\u00a9 2026 40daycampaigns.com \u00b7 Un ministerio de Lifetogether",
"15 categories · 94 themes · 1252 campaigns — every one finished ·":"15 categor\u00edas \u00b7 94 temas \u00b7 1252 campa\u00f1as, cada una terminada \u00b7",
# campaign
"Campaign — 40 Day Campaigns":"Campa\u00f1a \u2014 40 Day Campaigns",
"one campaign · yours forever":"una campa\u00f1a \u00b7 tuya para siempre",
"✓ Instant digital delivery — begin today":"\u2713 Entrega digital instant\u00e1nea \u2014 empieza hoy",
"Add to cart":"Agregar al carrito","Buy now":"Comprar ahora",
"Open Day One in the Reading Room — free":"Abre el D\u00eda Uno en la Sala de lectura \u2014 gratis",
"Plan your launch →":"Planifica tu lanzamiento \u2192",
"Small-Group Edition only — $99":"Solo edici\u00f3n para grupos peque\u00f1os \u2014 $99",
"Order printed copies":"Pedir copias impresas","Printed copies, to your door.":"Copias impresas, hasta tu puerta.",
"Pick a quantity — print-on-demand fulfillment (Ingram Spark) connects at launch. Click order, and they show up at the church.":"Elige una cantidad: la impresi\u00f3n bajo demanda (IngramSpark) se conecta en el lanzamiento. Haz el pedido y llegan a la iglesia.",
"Select a quantity for your quote":"Selecciona una cantidad para tu cotizaci\u00f3n","Order — connects at launch":"Pedir \u2014 se conecta en el lanzamiento",
"Or get every campaign in the library with":"O consigue todas las campa\u00f1as de la biblioteca con",
"— from $49/mo by church size, with a 40% church-plant discount.":"\u2014 desde $49/mes seg\u00fan el tama\u00f1o de la iglesia, con 40% de descuento para plantaciones.",
"Complete daily devotional — every day fully written":"Devocional diario completo \u2014 cada d\u00eda totalmente escrito",
"6-session small-group study with leader notes":"Estudio de 6 sesiones para grupos peque\u00f1os con notas para el l\u00edder",
"6 sermon outlines + full launch kit":"6 bosquejos de sermones + kit de lanzamiento completo",
"Youth &amp; children's editions for every week":"Ediciones para j\u00f3venes y ni\u00f1os cada semana",
"All sixteen formats included — book, course, podcast, video, family guide, and more":"Los diecis\u00e9is formatos incluidos: libro, curso, p\u00f3dcast, video, gu\u00eda familiar y m\u00e1s",
"Congregation-wide print rights included":"Derechos de impresi\u00f3n para toda la congregaci\u00f3n incluidos",
"Open the full documents":"Abrir los documentos completos","More like this":"M\u00e1s como esta","Flagship ·":"Insignia \u00b7","A Family Journey ·":"Un recorrido familiar \u00b7",
"A complete, ready-to-launch campaign in the":"Una campa\u00f1a completa y lista para lanzar en la",
"Anchor scripture:":"Escritura ancla:",
"A complete seven-day experience — kickoff Sunday to Celebration Sunday.":"Una experiencia completa de siete d\u00edas: del domingo de inicio al Domingo de Celebraci\u00f3n.",
"Three to six weeks — choose the length that fits the season.":"De tres a seis semanas: elige la duraci\u00f3n que encaje con la temporada.",
"Small-Group Edition only":"Solo edici\u00f3n para grupos peque\u00f1os","Leader Kit":"Kit del l\u00edder","Primary topic":"Tema principal","Best season":"Mejor temporada","Any season":"Cualquier temporada","Every audience":"Toda audiencia","Launch complexity":"Complejidad de lanzamiento","Speed to launch":"Velocidad de lanzamiento","Begin this Sunday":"Empieza este domingo","Six-week runway":"Pista de seis semanas","Choose a week":"Elige una semana",
"The room does the growing — four movements, one practice.":"La sala hace el crecimiento: cuatro movimientos, una pr\u00e1ctica.",
"A trade-paperback reading edition with chapters and epilogue":"Una edici\u00f3n de lectura tipo libro, con cap\u00edtulos y ep\u00edlogo",
"A one-week on-ramp: kickoff to Celebration Sunday":"Una rampa de una semana: del inicio al Domingo de Celebraci\u00f3n",
"Three focused weeks for a season of momentum":"Tres semanas enfocadas para una temporada de impulso",
"A full month of daily formation":"Un mes completo de formaci\u00f3n diaria",
"The classic churchwide journey":"El recorrido cl\u00e1sico para toda la iglesia",
"Membership Course":"Curso de membres\u00eda",
"Modules, objectives, self-checks, and a completion track":"M\u00f3dulos, objetivos, autoevaluaciones y ruta de finalizaci\u00f3n",
"Small Group Curriculum":"Curr\u00edculo para grupos peque\u00f1os",
"Six sessions with questions, practices, and leader cues":"Seis sesiones con preguntas, pr\u00e1cticas y pautas para el l\u00edder",
"Leader Training":"Entrenamiento de l\u00edderes",
"A facilitator course that trains your hosts before launch":"Un curso que entrena a tus anfitriones antes del lanzamiento",
"Family Guide":"Gu\u00eda familiar",
"Table talk, activities, prayers, and bedtime blessings":"Conversaci\u00f3n de mesa, actividades, oraciones y bendiciones para dormir",
"Youth Edition":"Edici\u00f3n juvenil",
"The same journey, translated for students":"El mismo recorrido, traducido para estudiantes",
"Big ideas, activities, and simple prayers for kids":"Grandes ideas, actividades y oraciones sencillas para ni\u00f1os",
"Podcast Series":"Serie de p\u00f3dcast",
"Episode scripts with cold opens, segments, and outros":"Guiones por episodio con apertura, segmentos y cierre",
"Video Course":"Curso en video",
"Delivery-ready teaching scripts, beat by beat":"Guiones de ense\u00f1anza listos para grabar, paso a paso",
"Upload-ready book spec with back-cover copy":"Especificaci\u00f3n de libro lista para subir, con texto de contraportada",
"Digital Library":"Biblioteca digital",
"Every file, one bundle, one license":"Cada archivo, un paquete, una licencia",
# pricing
"Pricing — 40 Day Campaigns":"Precios \u2014 40 Day Campaigns",
"Own one journey, or open the whole library.":"S\u00e9 due\u00f1o de un recorrido, o abre toda la biblioteca.",
"Two honest prices. No seats, no per-head math, no surprise line items — one license always covers your entire congregation.":"Dos precios honestos. Sin asientos, sin cuentas por persona, sin sorpresas: una licencia siempre cubre a toda tu congregaci\u00f3n.",
"Your price in ten seconds":"Tu precio en diez segundos",
"What All Access costs your church":"Lo que All Access le cuesta a tu iglesia",
"Slide to your average weekend attendance. Every tier includes the entire 1252-campaign library, editable source files, and new releases as they ship.":"Desliza hasta tu asistencia promedio de fin de semana. Cada nivel incluye la biblioteca completa de 1252 campa\u00f1as, archivos editables y los nuevos lanzamientos.",
"Average weekend attendance":"Asistencia promedio de fin de semana",
"We're a church plant (under 3 years) or under 50 in attendance — apply the 40% discount, code":"Somos una plantaci\u00f3n (menos de 3 a\u00f1os) o menos de 50 personas: aplica el 40% de descuento con el c\u00f3digo",
"Churches 100–500":"Iglesias de 100 a 500",
"Billed monthly · cancel anytime · all 1252 campaigns":"Cobro mensual \u00b7 cancela cuando quieras \u00b7 las 1252 campa\u00f1as",
"Get All Access →":"Obtener All Access \u2192",
"Prefer one journey? A single campaign is $199 flat — any size church.":"\u00bfPrefieres un solo recorrido? Una campa\u00f1a cuesta $199 fijos, sin importar el tama\u00f1o de la iglesia.",
"The two doors":"Las dos puertas","Side by side, in full.":"Lado a lado, completo.",
"Single Campaign":"Campa\u00f1a individual","one-time · yours forever · any size church":"pago \u00fanico \u00b7 tuya para siempre \u00b7 cualquier tama\u00f1o de iglesia",
"Any one of the 1252 campaigns, complete — all sixteen formats":"Cualquiera de las 1252 campa\u00f1as, completa: los diecis\u00e9is formatos",
"Small-Group Edition only — $99, when groups are the whole plan":"Solo edici\u00f3n de grupos \u2014 $99, cuando los grupos son todo el plan",
"7, 21, 30, 40-day and 6-week versions of the same journey":"Versiones de 7, 21, 30 y 40 d\u00edas y de 6 semanas del mismo recorrido",
"Congregation-wide license with print rights included":"Licencia para toda la congregaci\u00f3n con derechos de impresi\u00f3n",
"Instant digital delivery — card, Apple&nbsp;Pay, PayPal, or Net-30 church invoice":"Entrega digital instant\u00e1nea: tarjeta, Apple&nbsp;Pay, PayPal o factura Net-30 para iglesias",
"The Reading Room for every member, offline included":"La Sala de lectura para cada miembro, incluso sin conexi\u00f3n",
"Choose a campaign →":"Elegir una campa\u00f1a \u2192",
"by weekend attendance · cancel anytime":"por asistencia de fin de semana \u00b7 cancela cuando quieras",
"Every campaign in the library — all 1252, all seasons":"Todas las campa\u00f1as de la biblioteca: las 1252, todas las temporadas",
"Switch or run multiple campaigns anytime, no per-title fees":"Cambia o ejecuta varias campa\u00f1as cuando quieras, sin costos por t\u00edtulo",
"Editable, print-ready source files for your bulletin and brand":"Archivos editables y listos para imprimir, para tu bolet\u00edn y tu marca",
"New campaigns included as they release":"Las campa\u00f1as nuevas incluidas al publicarse",
"Church plants &amp; churches under 50: 40% off with code PLANT40":"Plantaciones e iglesias de menos de 50: 40% de descuento con el c\u00f3digo PLANT40",
"No fine print, just plain print":"Sin letra peque\u00f1a, solo letra clara",
"Licensing, plainly.":"La licencia, en claro.",
"One license, whole church":"Una licencia, toda la iglesia",
"Print it, email it, hand it out at the door. Your license covers every member of your congregation — including youth and children's editions.":"Impr\u00edmelo, env\u00edalo por correo, rep\u00e1rtelo en la puerta. Tu licencia cubre a cada miembro de tu congregaci\u00f3n, incluidas las ediciones para j\u00f3venes y ni\u00f1os.",
"Delivery is instant":"La entrega es instant\u00e1nea",
"Every edition downloads the moment you check out, and every member can read daily in the Reading Room — on any device, even offline.":"Cada edici\u00f3n se descarga al momento de pagar, y cada miembro puede leer a diario en la Sala de lectura, en cualquier dispositivo, incluso sin conexi\u00f3n.",
"Invoicing welcome":"Facturas bienvenidas",
"Choose \"Invoice my church\" at checkout for Net-30 terms with an optional PO number. Downloads unlock immediately.":"Elige \u201cFacturar a mi iglesia\u201d al pagar, con t\u00e9rminos Net-30 y n\u00famero de orden opcional. Las descargas se desbloquean de inmediato.",
"Attendance, on your word":"Asistencia, bajo tu palabra",
"All Access tiers go by average weekend attendance. We take your word for it — no audits, no forms.":"Los niveles de All Access van por asistencia promedio. Te tomamos la palabra: sin auditor\u00edas, sin formularios.",
"Plants pay less":"Las plantaciones pagan menos",
"Under 3 years old, or under 50 on Sundays? Code":"\u00bfMenos de 3 a\u00f1os, o menos de 50 los domingos? El c\u00f3digo",
"takes 40% off any purchase at checkout. No application.":"aplica 40% de descuento a cualquier compra. Sin solicitudes.",
"Can we run more than one campaign a year?":"\u00bfPodemos ejecutar m\u00e1s de una campa\u00f1a al a\u00f1o?",
"Most All Access churches run two to four — a churchwide 40-day in fall, a shorter 21-day in the new year, plus targeted journeys for marriage or finance ministries. The whole library stays open; run what the season needs.":"La mayor\u00eda de las iglesias con All Access ejecutan de dos a cuatro: una de 40 d\u00edas en oto\u00f1o, una de 21 en el nuevo a\u00f1o, m\u00e1s recorridos espec\u00edficos para matrimonio o finanzas. La biblioteca queda abierta; ejecuta lo que la temporada necesite.",
"What if we outgrow our tier?":"\u00bfY si superamos nuestro nivel?",
"Congratulations — just move up at your next billing month. Tiers exist so small churches never subsidize large ones, not to catch anyone out.":"Felicidades: solo sube de nivel en tu pr\u00f3ximo mes de facturaci\u00f3n. Los niveles existen para que las iglesias peque\u00f1as nunca subsidien a las grandes, no para atrapar a nadie.",
"Is there a way to try before buying?":"\u00bfSe puede probar antes de comprar?",
"Always. Day One of every campaign is free in the Reading Room, and a printable three-day sample is one click from any campaign page.":"Siempre. El D\u00eda Uno de cada campa\u00f1a es gratis en la Sala de lectura, y una muestra imprimible de tres d\u00edas est\u00e1 a un clic desde cualquier p\u00e1gina de campa\u00f1a.",
"Find your next campaign":"Encuentra tu pr\u00f3xima campa\u00f1a","Find your three matches →":"Encuentra tus tres coincidencias \u2192","Read Day One free":"Lee el D\u00eda Uno gratis",
"Which option makes sense for you":"Qu\u00e9 opci\u00f3n tiene sentido para ti",
"Running one campaign this season?":"\u00bfEjecutar\u00e1s una campa\u00f1a esta temporada?",
"A single campaign starting at $199 covers your whole congregation, all sixteen formats, with print rights included and no expiration. If small groups are the whole plan, the Small-Group Edition alone is $99.":"Una campa\u00f1a individual desde $199 cubre a toda tu congregaci\u00f3n, con los diecis\u00e9is formatos, derechos de impresi\u00f3n y sin vencimiento. Si los grupos peque\u00f1os son todo el plan, la edici\u00f3n de grupos sola cuesta $99.",
"Running two or more campaigns a year?":"\u00bfDos o m\u00e1s campa\u00f1as al a\u00f1o?",
"Church plant?":"\u00bfPlantaci\u00f3n de iglesia?",
"Ask about the PLANT40 rate — a 40% discount built for churches in their first few years.":"Pregunta por la tarifa PLANT40: un 40% de descuento pensado para iglesias en sus primeros a\u00f1os.",
"$199 single · All Access $49–$249/mo · PLANT40 saves 40% ·":"$199 individual \u00b7 All Access $49\u2013$249/mes \u00b7 PLANT40 ahorra 40% \u00b7",
# contact / get-access / checkout / cart / confirmation
"Say Hello — 40 Day Campaigns":"Escr\u00edbenos \u2014 40 Day Campaigns",
"Say hello.":"Escr\u00edbenos.",
"A real person reads every message — usually the same day. Pastors planning a launch go to the front of the line.":"Una persona real lee cada mensaje, normalmente el mismo d\u00eda. Los pastores que planean un lanzamiento pasan al frente de la fila.",
"Good reasons to write":"Buenas razones para escribir","Planning a launch":"Planeando un lanzamiento",
"Tell us your kickoff Sunday and church size — we'll sanity-check the runway with you.":"Cu\u00e9ntanos tu domingo de inicio y el tama\u00f1o de tu iglesia; revisaremos contigo el plan de despegue.",
"Licensing questions":"Preguntas de licencias",
"Multi-site, denominations, ministries beyond the local church — ask before you guess.":"Multisitio, denominaciones, ministerios m\u00e1s all\u00e1 de la iglesia local: pregunta antes de suponer.",
"Something looks broken":"Algo se ve roto",
"Tell us the page and the device. We fix fast and say thank you.":"Dinos la p\u00e1gina y el dispositivo. Corregimos r\u00e1pido y damos las gracias.",
"Prefer email?":"\u00bfPrefieres correo?","Your name":"Tu nombre","What's this about?":"\u00bfDe qu\u00e9 se trata?","Licensing question":"Pregunta de licencia","Something's broken":"Algo est\u00e1 roto","Just saying hello":"Solo saludar","Your message":"Tu mensaje","Send it →":"Enviar \u2192","Received.":"Recibido.",
"Thank you — a real person will reply, usually the same day.":"Gracias: una persona real responder\u00e1, normalmente el mismo d\u00eda.",
"Meanwhile,":"Mientras tanto,","Day One is free":"el D\u00eda Uno es gratis","if you'd like a taste.":"si quieres probar.",
"Get All Access — 40 Day Campaigns":"Obt\u00e9n All Access \u2014 40 Day Campaigns",
"Open the whole library for your church.":"Abre toda la biblioteca para tu iglesia.",
"All 1252 campaigns, always":"Las 1252 campa\u00f1as, siempre",
"Run a churchwide 40-day in the fall, a 21-day in January, a marriage journey in spring — switch anytime, no per-title fees.":"Ejecuta una de 40 d\u00edas en oto\u00f1o, una de 21 en enero, un recorrido de matrimonio en primavera; cambia cuando quieras, sin costos por t\u00edtulo.",
"Editable source files":"Archivos editables",
"Print-ready and brandable: your logo on the devotional cover, your service times on the bulletin insert.":"Listos para imprimir y personalizar: tu logo en la portada del devocional, tus horarios en el inserto del bolet\u00edn.",
"Every tool included":"Todas las herramientas incluidas",
"The Reading Room for every member (offline included), the Launch Planner with calendar export, verse cards, samples — all of it.":"La Sala de lectura para cada miembro (incluso sin conexi\u00f3n), el Planificador con exportaci\u00f3n a calendario, tarjetas de vers\u00edculos, muestras: todo.",
"New releases as they ship":"Nuevos lanzamientos al publicarse",
"The library grows; your price doesn't change mid-cycle.":"La biblioteca crece; tu precio no cambia a mitad de ciclo.",
"Cancel anytime":"Cancela cuando quieras",
"Month to month, by attendance tier, on your word — no audits, no contracts, no exit calls.":"Mes a mes, por nivel de asistencia, bajo tu palabra: sin auditor\u00edas, sin contratos, sin llamadas de salida.",
"under 100":"menos de 100","Not sure which tier?":"\u00bfNo sabes qu\u00e9 nivel?","The calculator answers in ten seconds →":"La calculadora responde en diez segundos \u2192",
"Start All Access":"Comenzar All Access",
"Demo signup — no payment is taken today. Billing connects through Stripe at launch.":"Registro de demostraci\u00f3n: hoy no se cobra nada. La facturaci\u00f3n se conecta con Stripe en el lanzamiento.",
"Church name":"Nombre de la iglesia","Under 100 — $49/mo":"Menos de 100 \u2014 $49/mes","100–500 — $99/mo":"100\u2013500 \u2014 $99/mes","500–1,000 — $149/mo":"500\u20131.000 \u2014 $149/mes","1,000–2,000 — $199/mo":"1.000\u20132.000 \u2014 $199/mes","2,000+ — $249/mo":"2.000+ \u2014 $249/mes",
"Your email":"Tu correo","Open the library →":"Abrir la biblioteca \u2192",
"Church plant or under 50? Code":"\u00bfPlantaci\u00f3n o menos de 50? El c\u00f3digo","takes 40% off at checkout.":"da 40% de descuento al pagar.",
"Every tier: all 1252 campaigns · cancel anytime.":"Cada nivel: las 1252 campa\u00f1as \u00b7 cancela cuando quieras.",
"Welcome — the library is open.":"Bienvenido: la biblioteca est\u00e1 abierta.",
"Create your sign-in to keep your journey, launches, and downloads in one place.":"Crea tu acceso para guardar tu recorrido, lanzamientos y descargas en un solo lugar.",
"Create my account →":"Crear mi cuenta \u2192","I already have an account":"Ya tengo una cuenta",
"All Access $49–$249/mo · PLANT40 saves 40% · cancel anytime ·":"All Access $49\u2013$249/mes \u00b7 PLANT40 ahorra 40% \u00b7 cancela cuando quieras \u00b7",
"Secure Checkout — 40 Day Campaigns":"Pago seguro \u2014 40 Day Campaigns",
"Secure checkout":"Pago seguro","return to cart":"volver al carrito","256-bit encrypted · demo mode":"cifrado de 256 bits \u00b7 modo demo",
"Billing contact":"Contacto de facturaci\u00f3n","Full name":"Nombre completo","Church or organization":"Iglesia u organizaci\u00f3n","Email for delivery &amp; receipt":"Correo para entrega y recibo",
"Payment method":"M\u00e9todo de pago","or pay another way":"o paga de otra forma","Credit or debit card":"Tarjeta de cr\u00e9dito o d\u00e9bito",
"All major cards accepted. Instant digital delivery.":"Aceptamos las principales tarjetas. Entrega digital instant\u00e1nea.",
"Name on card":"Nombre en la tarjeta","Card number":"N\u00famero de tarjeta","Expiry (MM/YY)":"Vencimiento (MM/AA)","Security code":"C\u00f3digo de seguridad","Billing ZIP":"C\u00f3digo postal",
"Demo checkout: card details are validated in your browser only and are never stored or transmitted — only the card brand and last four digits appear on your receipt. Live payments connect through Stripe at launch.":"Pago de demostraci\u00f3n: los datos de la tarjeta se validan solo en tu navegador y nunca se guardan ni se transmiten; en el recibo solo aparecen la marca y los \u00faltimos cuatro d\u00edgitos. Los pagos reales se conectan con Stripe en el lanzamiento.",
"Invoice my church (Net-30)":"Facturar a mi iglesia (Net-30)",
"We'll email a Net-30 invoice to your billing contact. Downloads unlock immediately.":"Enviaremos una factura Net-30 a tu contacto de facturaci\u00f3n. Las descargas se desbloquean de inmediato.",
"PO number":"N\u00famero de orden (PO)","Review your order":"Revisa tu pedido",
"By placing this order you agree to the":"Al hacer este pedido aceptas los","Terms of Use":"T\u00e9rminos de uso","Privacy Policy":"Pol\u00edtica de privacidad",
"Place your order":"Hacer el pedido",
"By placing your order you agree to the campaign license terms: one license covers your entire congregation, with print rights included.":"Al hacer tu pedido aceptas los t\u00e9rminos de licencia: una licencia cubre a toda tu congregaci\u00f3n, con derechos de impresi\u00f3n incluidos.",
"Order summary":"Resumen del pedido","Delivery":"Entrega","Instant · digital":"Instant\u00e1nea \u00b7 digital",
"Confirm with Passcode":"Confirmar con c\u00f3digo",
"Demo of the Apple&nbsp;Pay sheet — no wallet is charged. Live Apple&nbsp;Pay arrives with Stripe at launch.":"Demostraci\u00f3n de Apple&nbsp;Pay: no se cobra a ninguna billetera. Apple&nbsp;Pay real llega con Stripe en el lanzamiento.",
"Merchant":"Comercio","PayPal account email":"Correo de tu cuenta PayPal",
"Demo of PayPal checkout — nothing is charged. Live PayPal arrives at launch.":"Demostraci\u00f3n de PayPal: no se cobra nada. PayPal real llega en el lanzamiento.",
"Payment approved":"Pago aprobado",
"Please add your name for the receipt.":"Agrega tu nombre para el recibo.",
"Please add a valid delivery email.":"Agrega un correo de entrega v\u00e1lido.",
"That card looks expired — please use a current card.":"Esa tarjeta parece vencida; usa una vigente.",
"The security code should be":"El c\u00f3digo de seguridad debe tener",
"Please add the name on the card.":"Agrega el nombre que aparece en la tarjeta.",
"Add a delivery email for your receipt, then tap the wallet button again.":"Agrega un correo de entrega para tu recibo y vuelve a tocar el bot\u00f3n de la billetera.",
"Your Cart — 40 Day Campaigns":"Tu carrito \u2014 40 Day Campaigns","Your cart":"Tu carrito",
"Every campaign is a one-time $199 license for your whole congregation — devotional, group study, sermon outlines, youth &amp; children's editions, and the leader &amp; launch kits.":"Cada campa\u00f1a es una licencia \u00fanica de $199 para toda tu congregaci\u00f3n: devocional, estudio de grupos, bosquejos de sermones, ediciones para j\u00f3venes y ni\u00f1os, y los kits de l\u00edder y lanzamiento.",
"Saved for later":"Guardado para despu\u00e9s","Promo code":"C\u00f3digo promocional","Proceed to checkout":"Continuar al pago",
"🔒 Secure demo checkout · instant digital delivery":"\ud83d\udd12 Pago demo seguro \u00b7 entrega digital instant\u00e1nea",
"Buying more than two?":"\u00bfComprar\u00e1s m\u00e1s de dos?",
"covers the entire 1252-campaign library from $49/mo by church size — church plants save 40% with code":"cubre toda la biblioteca de 1252 campa\u00f1as desde $49/mes seg\u00fan el tama\u00f1o de la iglesia; las plantaciones ahorran 40% con el c\u00f3digo",
"Order Confirmed — 40 Day Campaigns":"Pedido confirmado \u2014 40 Day Campaigns","Order confirmed":"Pedido confirmado","Thank you!":"\u00a1Gracias!",
"Your campaign licenses are active. Download any format below — each opens the complete curriculum, ready to print or save as PDF.":"Tus licencias de campa\u00f1a est\u00e1n activas. Descarga cualquier formato abajo: cada uno abre el curr\u00edculo completo, listo para imprimir o guardar en PDF.",
"What’s next:":"Lo que sigue:",
"pick your launch Sunday, recruit hosts three weeks out, and start everyone on Day 1 together. The launch kit is included at the end of every daily-format download. Questions?":"elige tu domingo de lanzamiento, recluta anfitriones con tres semanas de anticipaci\u00f3n y comiencen todos juntos el D\u00eda 1. El kit de lanzamiento va incluido al final de cada descarga de formato diario. \u00bfPreguntas?",
"We’re here.":"Aqu\u00ed estamos.","View my account":"Ver mi cuenta","🖨 Print receipt":"\ud83d\udda8 Imprimir recibo","Begin Day One →":"Comenzar el D\u00eda Uno \u2192","Browse more campaigns":"Ver m\u00e1s campa\u00f1as",
"How It Works":"C\u00f3mo funciona","For Churches":"Para iglesias",
"© 2026 40daycampaigns.com · A Lifetogether ministry · Built in the Purpose Driven tradition":"\u00a9 2026 40daycampaigns.com \u00b7 Un ministerio de Lifetogether \u00b7 En la tradici\u00f3n de Una Vida con Prop\u00f3sito",
"No recent order found":"No se encontr\u00f3 un pedido reciente","Thank you,":"Gracias,",
}
json.dump(ES, open('/home/claude/tr_es_2.json','w'), ensure_ascii=False)
print("ES map:", len(ES), "pairs")
