import json
ES = {
# ---- global fixes ----
"So we built five hundred thirty-three of them. Finished.":"As\u00ed que construimos 1.252. Terminadas.",
# ---- faq.html ----
"Questions &amp; Answers — 40 Day Campaigns":"Preguntas y respuestas \u2014 40 Day Campaigns",
"Questions &amp; answers":"Preguntas y respuestas",
"Everything pastors ask us. Answered straight.":"Todo lo que los pastores nos preguntan. Respondido sin rodeos.",
"No hedging, no \"it depends\" without the depends. If your question isn't here, a person reads every message at":"Sin evasivas, sin \u201cdepende\u201d sin el depende. Si tu pregunta no est\u00e1 aqu\u00ed, una persona lee cada mensaje en",
"The Content":"El contenido","Running It":"C\u00f3mo ejecutarla","Licensing &amp; Money":"Licencias y dinero","The Tools":"Las herramientas",
"Who actually writes these campaigns?":"\u00bfQui\u00e9n escribe realmente estas campa\u00f1as?",
"Lifetogether — the team Brett Eastman founded in 2001 out of the Saddleback small-groups movement. Every campaign is hand-curated against five":"Lifetogether: el equipo que Brett Eastman fund\u00f3 en 2001 desde el movimiento de grupos peque\u00f1os de Saddleback. Cada campa\u00f1a se cuida a mano contra cinco",
"craft standards":"est\u00e1ndares de oficio",
": a distinct angle, a scriptural backbone, a conviction-not-condemnation voice, first-time-host readiness, and finished-means-finished completeness.":": un \u00e1ngulo distinto, una columna b\u00edblica, una voz de convicci\u00f3n sin condenaci\u00f3n, lista para anfitriones primerizos, y terminada de verdad.",
"What Bible translation do you use?":"\u00bfQu\u00e9 traducci\u00f3n de la Biblia usan?",
", with the weekly memory verse presented for households to share. If your church preaches from a different translation, the sermon outlines reference passages, not printed text — your pulpit Bible is your pulpit Bible.":", con el vers\u00edculo semanal presentado para compartir en casa. Si tu iglesia predica con otra traducci\u00f3n, los bosquejos citan referencias, no texto impreso: tu Biblia de p\u00falpito sigue siendo tu Biblia de p\u00falpito.",
"How long is a daily reading, honestly?":"\u00bfCu\u00e1nto dura una lectura diaria, honestamente?",
"Between 413 and 557 words — about three to four minutes — plus a short prayer, one reflection question, and one concrete step. Long enough to matter, short enough to survive a Tuesday.":"Entre 413 y 557 palabras \u2014 unos tres a cuatro minutos \u2014 m\u00e1s una oraci\u00f3n breve, una pregunta de reflexi\u00f3n y un paso concreto. Suficiente para importar, breve para sobrevivir a un martes.",
"Will campaign #4 feel like campaign #1?":"\u00bfLa campa\u00f1a #4 se sentir\u00e1 como la #1?",
"No — that's the first craft standard. Each of the 1252 campaigns carries its own governing question and metaphor, even within the same theme. Your church can run stewardship journeys three falls in a row without déjà vu.":"No: ese es el primer est\u00e1ndar de oficio. Cada una de las 1252 campa\u00f1as lleva su propia pregunta rectora y su met\u00e1fora, incluso dentro del mismo tema. Tu iglesia puede correr recorridos de mayordom\u00eda tres oto\u00f1os seguidos sin d\u00e9j\u00e0 vu.",
"How do sensitive topics get handled?":"\u00bfC\u00f3mo se manejan los temas sensibles?",
"Can we preview before we buy?":"\u00bfPodemos previsualizar antes de comprar?",
"Always.":"Siempre.",
"Day One of every campaign is free":"El D\u00eda Uno de cada campa\u00f1a es gratis",
"in the Reading Room, and every campaign page offers a printable three-day sample plus the full Session 1, all six sermon outlines, and week one of the youth and kids editions.":"en la Sala de lectura, y cada p\u00e1gina ofrece una muestra imprimible de tres d\u00edas m\u00e1s la Sesi\u00f3n 1 completa, los seis bosquejos y la semana uno de las ediciones juvenil e infantil.",
"How much work is this for our senior pastor, really?":"\u00bfCu\u00e1nto trabajo es esto para nuestro pastor principal, en serio?",
"ten hours across twelve weeks":"diez horas en doce semanas",
": cast the vision twice, preach six sermons from provided outlines, commission the hosts, celebrate at the end. The":": presentar la visi\u00f3n dos veces, predicar seis sermones desde los bosquejos, comisionar a los anfitriones y celebrar al final. El",
"honest ledger":"libro mayor honesto",
"lists it line by line — along with everything that's already done.":"lo detalla l\u00ednea por l\u00ednea, junto con todo lo que ya est\u00e1 hecho.",
"We've never done groups. Can our people host?":"Nunca hemos tenido grupos. \u00bfPuede nuestra gente ser anfitriona?",
"Yes — the sessions assume the host has never led anything. Four movements, printed questions, a one-hour orientation the kit runs for you, and a leader guide with the midweek text that keeps rooms warm. The questions do the teaching.":"S\u00ed: las sesiones asumen que el anfitri\u00f3n nunca ha dirigido nada. Cuatro movimientos, preguntas impresas, una orientaci\u00f3n de una hora que el kit ejecuta por ti, y una gu\u00eda con el mensaje de mitad de semana que mantiene c\u00e1lidas las salas. Las preguntas hacen la ense\u00f1anza.",
"How far ahead should we start?":"\u00bfCon cu\u00e1nta anticipaci\u00f3n debemos empezar?",
"Six weeks. Open the":"Seis semanas. Abre el",
"Launch Planner":"Planificador de lanzamiento",
", pick your kickoff Sunday, and it builds the dated runway — recruiting, orientation, sign-up Sunday, group formation — and drops all of it into your calendar as an .ics file.":", elige tu domingo de inicio, y construye la pista con fechas \u2014 reclutamiento, orientaci\u00f3n, domingo de inscripci\u00f3n, formaci\u00f3n de grupos \u2014 y lo deja todo en tu calendario como archivo .ics.",
"What about our youth and children during the campaign?":"\u00bfY nuestros j\u00f3venes y ni\u00f1os durante la campa\u00f1a?",
"Which length should we choose?":"\u00bfQu\u00e9 duraci\u00f3n deber\u00edamos elegir?",
"Forty days for a churchwide movement; 21 or 30 days for habit-forming seasons; 7 days for prayer weeks and staff resets; 6-week for group-first churches. Every campaign composes cleanly at all five lengths —":"Cuarenta d\u00edas para un movimiento de toda la iglesia; 21 o 30 para temporadas de formar h\u00e1bitos; 7 para semanas de oraci\u00f3n y reinicios de equipo; 6 semanas para iglesias centradas en grupos. Cada campa\u00f1a se compone limpiamente en las cinco duraciones \u2014",
"here's the guide":"aqu\u00ed est\u00e1 la gu\u00eda",
"What exactly does $199 buy?":"\u00bfQu\u00e9 compra exactamente el precio de $199?",
"One campaign, complete and forever: all sixteen formats, all five lengths, and a congregation-wide license with print rights. No per-head math, no seat counts — a church of 40 and a church of 4,000 pay the same $199.":"Una campa\u00f1a, completa y para siempre: los diecis\u00e9is formatos, las cinco duraciones y una licencia para toda la congregaci\u00f3n con derechos de impresi\u00f3n. Sin cuentas por persona: una iglesia de 40 y una de 4.000 pagan los mismos $199.",
"How does All Access pricing work?":"\u00bfC\u00f3mo funciona el precio de All Access?",
"By average weekend attendance, from $49 to $249 per month —":"Por asistencia promedio de fin de semana, de $49 a $249 al mes \u2014",
"the calculator":"la calculadora",
"shows your number in ten seconds. Every tier opens the entire 1252-campaign library with editable source files and new releases included. We take your word on attendance; no audits.":"muestra tu n\u00famero en diez segundos. Cada nivel abre la biblioteca completa de 1252 campa\u00f1as con archivos editables y nuevos lanzamientos. Te tomamos la palabra en la asistencia; sin auditor\u00edas.",
"Do you discount for church plants?":"\u00bfDan descuento a plantaciones de iglesias?",
"Forty percent, on anything, with code":"Cuarenta por ciento, en todo, con el c\u00f3digo",
"at checkout — for plants under three years old or churches under fifty. No application, no phone call, no proof required.":"al pagar, para plantaciones de menos de tres a\u00f1os o iglesias de menos de cincuenta. Sin solicitud, sin llamada, sin comprobantes.",
"Can our church pay by invoice?":"\u00bfNuestra iglesia puede pagar con factura?",
"Yes. Choose":"S\u00ed. Elige",
"\"Invoice my church\"":"\u201cFacturar a mi iglesia\u201d",
"at checkout for Net-30 terms with an optional PO number. Downloads unlock immediately; the invoice follows by email. Cards, Apple&nbsp;Pay, and PayPal work too.":"al pagar, con t\u00e9rminos Net-30 y n\u00famero de orden opcional. Las descargas se desbloquean de inmediato; la factura llega por correo. Tarjetas, Apple&nbsp;Pay y PayPal tambi\u00e9n funcionan.",
"Can we edit the materials?":"\u00bfPodemos editar los materiales?",
"All Access includes editable, print-ready source files — drop in your logo, adjust the bulletin insert, match your brand. Single-campaign licenses include print-ready PDFs of every edition.":"All Access incluye archivos editables listos para imprimir: pon tu logo, ajusta el inserto del bolet\u00edn, iguala tu marca. Las licencias individuales incluyen PDF listos para imprimir de cada edici\u00f3n.",
"Can our people read on their phones?":"\u00bfNuestra gente puede leer en el tel\u00e9fono?",
"Every campaign opens in the":"Cada campa\u00f1a se abre en la",
"— a distraction-free daily reader with progress tracking, streaks, adjustable type, a listen-aloud button, shareable verse cards, and a candlelight night mode. Once visited, it works offline: planes, basements, mission fields.":": un lector diario sin distracciones con progreso, rachas, tipograf\u00eda ajustable, bot\u00f3n de lectura en voz alta, tarjetas de vers\u00edculos y modo nocturno de vela. Una vez visitada, funciona sin conexi\u00f3n: aviones, s\u00f3tanos, campos de misi\u00f3n.",
"What is the Launch Planner?":"\u00bfQu\u00e9 es el Planificador de lanzamiento?",
"Do we need to install anything?":"\u00bfNecesitamos instalar algo?",
"No. Everything runs in the browser. If you'd like, the site installs as an app on phones and desktops — but the front door is always just the web address.":"No. Todo corre en el navegador. Si quieres, el sitio se instala como app en tel\u00e9fonos y computadoras, pero la puerta principal siempre es la direcci\u00f3n web.",
"Is there a fast way to find things?":"\u00bfHay una forma r\u00e1pida de encontrar cosas?",
"(or Ctrl-K) anywhere on the site to search all 1252 campaigns, jump to any page, or continue your reading exactly where you left off.":"(o Ctrl-K) en cualquier parte del sitio para buscar entre las 1252 campa\u00f1as, saltar a cualquier p\u00e1gina o continuar tu lectura justo donde quedaste.",
"Still wondering about something?":"\u00bfTodav\u00eda con dudas?",
"A real person reads every message — usually the same day.":"Una persona real lee cada mensaje, normalmente el mismo d\u00eda.",
"Write to us →":"Escr\u00edbenos \u2192",
"A few more common questions":"Algunas preguntas comunes m\u00e1s",
"Can we run a custom length, like five weeks?":"\u00bfPodemos usar una duraci\u00f3n personalizada, como cinco semanas?",
"We only want the small-group study. Do we have to buy the whole campaign?":"Solo queremos el estudio de grupos. \u00bfTenemos que comprar toda la campa\u00f1a?",
"How does ordering printed copies work?":"\u00bfC\u00f3mo funciona pedir copias impresas?",
"Can our pastor edit the sermon outlines?":"\u00bfNuestro pastor puede editar los bosquejos?",
"Yes — that's the intent. Every outline downloads as an editable Word document with five supporting points, texts, and a stated big idea per week. Pastors commonly trim it to three points and add their own stories and application.":"S\u00ed, esa es la intenci\u00f3n. Cada bosquejo se descarga como documento Word editable con cinco puntos de apoyo, textos y una gran idea por semana. Los pastores suelen recortarlo a tres puntos y a\u00f1adir sus historias y aplicaci\u00f3n.",
"What's the difference between a category and a theme?":"\u00bfCu\u00e1l es la diferencia entre una categor\u00eda y un tema?",
"Can we find campaigns for grandparents, singles, or business owners specifically?":"\u00bfHay campa\u00f1as espec\u00edficas para abuelos, solteros o due\u00f1os de negocio?",
"How do we know if we're ready to launch a campaign?":"\u00bfC\u00f3mo sabemos si estamos listos para lanzar una campa\u00f1a?",
"Try the free":"Prueba la gratuita",
"— eight questions about your pulpit, leadership, hosts, and calendar, scored instantly with a recommended next step. Sometimes the answer is to launch now; sometimes it's to start smaller first. Both are useful outcomes.":": ocho preguntas sobre tu p\u00falpito, liderazgo, anfitriones y calendario, calificadas al instante con un siguiente paso recomendado. A veces la respuesta es lanzar ya; a veces es empezar m\u00e1s peque\u00f1o. Ambos resultados son \u00fatiles.",
"Where should we start browsing?":"\u00bfPor d\u00f3nde empezamos a explorar?",
"A few good starting points: the":"Algunos buenos puntos de partida: las",
"category pages":"p\u00e1ginas de categor\u00edas",
"if you already know your topic, the":"si ya conoces tu tema, el",
"if you want to see what other churches run most often, or the":"si quieres ver lo que otras iglesias ejecutan m\u00e1s, o el",
"Finder":"Buscador",
"if you'd rather answer a few questions and get matched.":"si prefieres responder unas preguntas y recibir coincidencias.",
"Day One of every campaign is free —":"El D\u00eda Uno de cada campa\u00f1a es gratis \u2014",
"read one now":"lee uno ahora",
# ---- how-it-works.html ----
"How It Works — 40 Day Campaigns":"C\u00f3mo funciona \u2014 40 Day Campaigns",
"Six weeks. One heartbeat.":"Seis semanas. Un solo latido.",
"The shape of a week":"La forma de una semana",
"One question, three rooms.":"Una pregunta, tres salas.",
"Every week of a campaign asks a single question — and asks it three different ways.":"Cada semana de una campa\u00f1a hace una sola pregunta, y la hace de tres maneras distintas.",
"Sunday · The pulpit":"Domingo \u00b7 El p\u00falpito","You preach it.":"T\u00fa la predicas.",
"Six sermon outlines — text, big idea, three movements, and a landing — build the week's question from Scripture. You bring your voice; the architecture is done.":"Seis bosquejos \u2014 texto, gran idea, tres movimientos y un aterrizaje \u2014 construyen la pregunta de la semana desde la Escritura. T\u00fa pones la voz; la arquitectura ya est\u00e1 hecha.",
"Midweek · The living room":"Entre semana \u00b7 La sala de casa","Groups wrestle with it.":"Los grupos luchan con ella.",
"A six-session study a first-time host can lead cold. Four movements, honest questions, one practice. The questions do the teaching; the room does the growing.":"Un estudio de seis sesiones que un anfitri\u00f3n primerizo puede dirigir sin preparaci\u00f3n. Cuatro movimientos, preguntas honestas, una pr\u00e1ctica. Las preguntas ense\u00f1an; la sala crece.",
"Every day · At home":"Cada d\u00eda \u00b7 En casa","Each person lives it.":"Cada persona la vive.",
"A fully written daily reading — five movements, a prayer, a question, one step — plus a weekly memory verse the whole household shares, kids' table included.":"Una lectura diaria totalmente escrita \u2014 cinco movimientos, una oraci\u00f3n, una pregunta, un paso \u2014 m\u00e1s un vers\u00edculo semanal que toda la casa comparte, mesa de los ni\u00f1os incluida.",
"By Saturday, the question hasn't just been heard. It has been lived with.":"Para el s\u00e1bado, la pregunta no solo se escuch\u00f3. Se vivi\u00f3.",
"See a real aligned week →":"Ver una semana alineada real \u2192",
"Before Day One":"Antes del D\u00eda Uno","The six-week runway.":"La pista de seis semanas.",
"Campaigns don't fail in week three; they fail in the six weeks before they begin. So the launch kit runs those weeks for you — and the Launch Planner puts them on your calendar.":"Las campa\u00f1as no fracasan en la semana tres; fracasan en las seis semanas previas. Por eso el kit de lanzamiento ejecuta esas semanas por ti, y el Planificador las pone en tu calendario.",
"Vision &amp; team":"Visi\u00f3n y equipo",
"Cast it to staff and elders, name a champion, set the print plan. One meeting.":"Pres\u00e9ntala al equipo y a los ancianos, nombra un campe\u00f3n, define el plan de impresi\u00f3n. Una reuni\u00f3n.",
"Open host recruiting":"Abre el reclutamiento de anfitriones",
"\"Open your home for six weeks\" — the most repeatable leadership on-ramp in church life. Invite 20% more hosts than you need.":"\u201cAbre tu casa por seis semanas\u201d: la rampa de liderazgo m\u00e1s repetible de la vida de iglesia. Invita 20% m\u00e1s anfitriones de los que necesitas.",
"Host orientation":"Orientaci\u00f3n de anfitriones",
"One hour. The kit runs it. Every host leaves with the Leader &amp; Launch Kit and the confidence that the questions will carry them.":"Una hora. El kit la ejecuta. Cada anfitri\u00f3n sale con el Kit de l\u00edder y lanzamiento y la confianza de que las preguntas lo sostendr\u00e1n.",
"Church-wide sign-up Sunday":"Domingo de inscripci\u00f3n de toda la iglesia",
"Preach the invitation — nobody does this alone — and open sign-ups in the lobby and online. Youth and children's directors brief their teams the same week.":"Predica la invitaci\u00f3n \u2014 nadie hace esto solo \u2014 y abre inscripciones en el lobby y en l\u00ednea. Los directores de j\u00f3venes y ni\u00f1os informan a sus equipos la misma semana.",
"Form the groups":"Forma los grupos",
"Every name lands in a group. Hosts make first contact. Devotionals reach every household, printed or digital.":"Cada nombre aterriza en un grupo. Los anfitriones hacen el primer contacto. Los devocionales llegan a cada hogar, impresos o digitales.",
"Final prep":"Preparaci\u00f3n final",
"Walk hosts through Session 1, load Sermon 1 into the plan of service, send the \"we begin Sunday\" message. Then begin.":"Repasa la Sesi\u00f3n 1 con los anfitriones, carga el Serm\u00f3n 1 en el orden del culto, env\u00eda el mensaje de \u201cempezamos el domingo\u201d. Y comienza.",
"Open the Launch Planner — dated for your church →":"Abrir el Planificador, con fechas para tu iglesia \u2192",
"Inside every license":"Dentro de cada licencia","Everything in the box.":"Todo lo que viene en la caja.",
"The Daily Devotional":"El devocional diario",
"Every day fully written — 413 to 557 words each — with prayer, reflection, and one step.":"Cada d\u00eda totalmente escrito \u2014 de 413 a 557 palabras \u2014 con oraci\u00f3n, reflexi\u00f3n y un paso.",
"The Six-Session Group Study":"El estudio de grupos de seis sesiones",
"Welcome, four movements, practice, prayer. Built for the newest host in the room.":"Bienvenida, cuatro movimientos, pr\u00e1ctica, oraci\u00f3n. Hecho para el anfitri\u00f3n m\u00e1s nuevo de la sala.",
"Six Sermon Outlines":"Seis bosquejos de sermones",
"Text, big idea, three movements, landing — in step with the week's readings.":"Texto, gran idea, tres movimientos, aterrizaje: al paso de las lecturas de la semana.",
"The Youth Edition":"La edici\u00f3n juvenil",
"The honest version, week by week, for students who can smell a script.":"La versi\u00f3n honesta, semana a semana, para estudiantes que huelen un gui\u00f3n a distancia.",
"The Children's Edition":"La edici\u00f3n infantil",
"The story, the craft, the echo prayer — so dinner tables share one verse.":"La historia, la manualidad, la oraci\u00f3n en eco: para que la mesa comparta un mismo vers\u00edculo.",
"The Leader Kit":"El kit del l\u00edder",
"Host tips, weekly rhythm, shepherding notes, the midweek text that keeps rooms warm.":"Consejos para anfitriones, ritmo semanal, notas de pastoreo y el mensaje de mitad de semana que mantiene c\u00e1lidas las salas.",
"The Launch Kit":"El kit de lanzamiento",
"The full six-week runway — recruiting to Celebration Sunday.":"La pista completa de seis semanas: del reclutamiento al Domingo de Celebraci\u00f3n.",
"The Congregation-Wide License":"La licencia para toda la congregaci\u00f3n",
"Print rights included. One license, your whole church, forever.":"Derechos de impresi\u00f3n incluidos. Una licencia, toda tu iglesia, para siempre.",
"Choose your length":"Elige tu duraci\u00f3n",
"Forty days is the classic. It isn't the only door.":"Cuarenta d\u00edas es el cl\u00e1sico. No es la \u00fanica puerta.",
"Most churches run three to six weeks — and every campaign composes cleanly at any length in that range. Match the season, not the calendar.":"La mayor\u00eda de las iglesias corre de tres a seis semanas, y cada campa\u00f1a se compone limpiamente en ese rango. Ajusta a la temporada, no al calendario.",
"The spark":"La chispa",
"A week of prayer, a staff reset, a taste before the plunge. Low ask, real depth.":"Una semana de oraci\u00f3n, un reinicio de equipo, una probada antes del salto. Poca exigencia, profundidad real.",
"The habit":"El h\u00e1bito",
"Long enough to form a rhythm — new year, new groups, new believers.":"Lo suficiente para formar un ritmo: a\u00f1o nuevo, grupos nuevos, creyentes nuevos.",
"The month":"El mes",
"A clean calendar month with margin. The workhorse for busy seasons.":"Un mes de calendario limpio con margen. El caballo de batalla de las temporadas llenas.",
"The movement":"El movimiento",
"The full journey — six parts, one arc. When you want the whole church changed, not just informed.":"El recorrido completo: seis partes, un arco. Para cuando quieres una iglesia cambiada, no solo informada.",
"Group-first":"Grupos primero",
"Session-led with lighter daily reading. Ideal where groups are the front door.":"Guiado por sesiones con lectura diaria m\u00e1s ligera. Ideal donde los grupos son la puerta de entrada.",
"The voice":"La voz","Conviction, never condemnation.":"Convicci\u00f3n, nunca condenaci\u00f3n.",
"Every campaign is written in one voice: warm, direct, and unembarrassed by Scripture. Readings quote the NIV reading plan · KJV verses labeled, with the weekly memory verse set for households to share.":"Cada campa\u00f1a est\u00e1 escrita en una sola voz: c\u00e1lida, directa y sin verg\u00fcenza de la Escritura. Las lecturas siguen el plan NVI con vers\u00edculos se\u00f1alados, y el vers\u00edculo semanal se presenta para compartir en casa.",
"Sensitive seasons — grief, anxiety, financial fear, burnout — are handled the way a good pastor would: permission to go slow, no shame in the sentence structure, and a gentle note toward pastoral or professional support where it belongs.":"Las temporadas sensibles \u2014 duelo, ansiedad, miedo financiero, agotamiento \u2014 se tratan como lo har\u00eda un buen pastor: permiso para ir despacio, sin verg\u00fcenza en la redacci\u00f3n, y una nota amable hacia apoyo pastoral o profesional donde corresponde.",
"And no two journeys blur together. Each of the 1252 campaigns holds its own angle, its own scriptural backbone, and its own governing metaphor — so the fourth campaign your church runs feels as fresh as the first.":"Y ning\u00fan par de recorridos se confunde. Cada una de las 1252 campa\u00f1as sostiene su \u00e1ngulo, su columna b\u00edblica y su met\u00e1fora rectora, para que la cuarta campa\u00f1a se sienta tan fresca como la primera.",
"The proof is the prose":"La prueba es la prosa",
"Read one, and you'll know.":"Lee una y lo sabr\u00e1s.",
"Read Day One free →":"Lee el D\u00eda Uno gratis \u2192",
"A closer look":"Una mirada m\u00e1s de cerca",
"What a typical week looks like":"C\u00f3mo se ve una semana t\u00edpica",
"Most weeks include a simple action step, specific enough to actually do, tied to that week's theme.":"La mayor\u00eda de las semanas incluye un paso de acci\u00f3n simple, lo bastante espec\u00edfico para hacerse, ligado al tema de esa semana.",
"Over six weeks,":"A lo largo de seis semanas,",
"this rhythm tends to build real momentum. Groups get more comfortable with each other, and by the final week — Celebration Sunday — churches often find people volunteering their own stories without much prompting.":"este ritmo tiende a construir impulso real. Los grupos se sienten m\u00e1s c\u00f3modos entre s\u00ed, y para la \u00faltima semana \u2014 el Domingo de Celebraci\u00f3n \u2014 muchas iglesias encuentran a personas contando sus historias sin que se lo pidan.",
"Picking a length":"Elegir una duraci\u00f3n",
"Which format fits your church right now":"Qu\u00e9 formato encaja con tu iglesia ahora",
"One week, whole church, minimal setup. Good for a January reset, a week of prayer, or a first campaign at a church that hasn't run one before.":"Una semana, toda la iglesia, preparaci\u00f3n m\u00ednima. Ideal para un reinicio de enero, una semana de oraci\u00f3n o una primera campa\u00f1a.",
"Three weeks is usually enough time for a daily habit to stop feeling like an assignment. This length works well when the goal is building a practice — prayer, gratitude, Scripture reading — rather than covering a topic.":"Tres semanas suelen bastar para que un h\u00e1bito diario deje de sentirse como tarea. Esta duraci\u00f3n funciona bien cuando la meta es construir una pr\u00e1ctica \u2014 oraci\u00f3n, gratitud, lectura b\u00edblica \u2014 m\u00e1s que cubrir un tema.",
"Four sermons over four weeks, which matches how a lot of pastors already plan a series. It's the easiest fit on a normal church calendar, and usually what we'd recommend for a first campaign.":"Cuatro sermones en cuatro semanas, que coincide con c\u00f3mo muchos pastores ya planean una serie. Es el encaje m\u00e1s f\u00e1cil en un calendario normal, y lo que solemos recomendar para una primera campa\u00f1a.",
"The full version, and the one most churches mean when they picture \"a campaign.\" Six sermons, six weeks of groups, and the complete daily devotional.":"La versi\u00f3n completa, y la que la mayor\u00eda imagina al decir \u201cuna campa\u00f1a\u201d. Seis sermones, seis semanas de grupos y el devocional diario completo.",
"6-Week and custom.":"6 semanas y personalizada.",
"Groups tend to prefer a six-session study. If your calendar needs something else, choose a custom length between three and six weeks — the sessions, sermons, and daily readings all adjust to fit.":"Los grupos suelen preferir un estudio de seis sesiones. Si tu calendario necesita otra cosa, elige una duraci\u00f3n personalizada entre tres y seis semanas: sesiones, sermones y lecturas se ajustan.",
# ---- about.html ----
"About Lifetogether — 40 Day Campaigns":"Acerca de Lifetogether \u2014 40 Day Campaigns",
"The house behind the campaigns.":"La casa detr\u00e1s de las campa\u00f1as.",
"Twenty-five years of one conviction: churches change most when they move through Scripture together — every room, every age, every day.":"Veinticinco a\u00f1os de una convicci\u00f3n: las iglesias cambian m\u00e1s cuando atraviesan la Escritura juntas, en cada sala, a cada edad, cada d\u00eda.",
"The story":"La historia","It started in living rooms.":"Empez\u00f3 en salas de casa.",
"\"The goal was never content. The goal was a church that moves as one — the content is just how you get there.\"":"\u201cLa meta nunca fue el contenido. La meta era una iglesia que se mueve como una sola; el contenido es solo c\u00f3mo se llega.\u201d",
"The line through it":"La l\u00ednea que lo atraviesa","A quarter century, briefly.":"Un cuarto de siglo, en breve.",
"Lifetogether founded":"Se funda Lifetogether",
"Out of the Saddleback small-groups movement — with a mandate to make churchwide journeys repeatable.":"Desde el movimiento de grupos peque\u00f1os de Saddleback, con el mandato de hacer repetibles los recorridos de toda la iglesia.",
"The campaign era proves the pattern":"La era de las campa\u00f1as prueba el patr\u00f3n",
"The Purpose Driven years show what alignment does at scale; Lifetogether serves the churches building on it.":"Los a\u00f1os de Una Vida con Prop\u00f3sito muestran lo que la alineaci\u00f3n hace a escala; Lifetogether sirve a las iglesias que construyen sobre eso.",
"Five hundred churches deep":"Quinientas iglesias despu\u00e9s",
"Campaigns for stewardship, family, legacy, and formation — refined season after season, host by host.":"Campa\u00f1as de mayordom\u00eda, familia, legado y formaci\u00f3n, refinadas temporada tras temporada, anfitri\u00f3n por anfitri\u00f3n.",
"The library opens":"La biblioteca abre",
"1252 finished campaigns, 94 themes, every edition composed to move together — with the Reading Room, the Launch Planner, and Day One free for anyone.":"1252 campa\u00f1as terminadas, 94 temas, cada edici\u00f3n compuesta para moverse junta, con la Sala de lectura, el Planificador y el D\u00eda Uno gratis para cualquiera.",
"Before you decide anything":"Antes de decidir nada","Ten things worth knowing":"Diez cosas que vale la pena saber",
"Every campaign is complete before you see it.":"Cada campa\u00f1a est\u00e1 completa antes de que la veas.",
"Not outlines or drafts — 1252 finished campaigns, over 15,000 individual daily readings written.":"No bosquejos ni borradores: 1252 campa\u00f1as terminadas, m\u00e1s de 15.000 lecturas diarias escritas.",
"The approach isn't new.":"El enfoque no es nuevo.",
"The aligned pulpit, small-group, and daily-reading model dates back to 40 Days of Purpose, which ran in roughly 30,000 churches. We've continued refining it with more than 500 churches since.":"El modelo alineado de p\u00falpito, grupos y lectura diaria se remonta a 40 D\u00edas con Prop\u00f3sito, que corri\u00f3 en unas 30.000 iglesias. Lo hemos seguido refinando con m\u00e1s de 500 iglesias desde entonces.",
"Your pastor still does the preaching.":"Tu pastor sigue predicando.",
"We provide structure and material; we don't replace the pastor's own voice or delivery.":"Aportamos estructura y material; no reemplazamos la voz ni la entrega del pastor.",
"Sermon outlines are editable.":"Los bosquejos son editables.",
"Each week comes with five supporting points, texts, and a stated big idea, delivered as a Word file so pastors can adjust it.":"Cada semana trae cinco puntos de apoyo, textos y una gran idea declarada, en archivo Word para que el pastor lo ajuste.",
"Kids and students aren't an afterthought.":"Los ni\u00f1os y j\u00f3venes no son una ocurrencia tard\u00eda.",
"Youth and children's editions cover the same weekly themes in age-appropriate language.":"Las ediciones juvenil e infantil cubren los mismos temas semanales en lenguaje apropiado.",
"Groups don't need an experienced leader.":"Los grupos no necesitan un l\u00edder experimentado.",
"Sessions are built so a first-time host can run them using the provided questions.":"Las sesiones est\u00e1n hechas para que un anfitri\u00f3n primerizo las dirija con las preguntas provistas.",
"Length is flexible.":"La duraci\u00f3n es flexible.",
"Anywhere from seven to forty days, or a custom length between three and six weeks.":"Desde siete hasta cuarenta d\u00edas, o una duraci\u00f3n personalizada entre tres y seis semanas.",
"You can preview everything before buying.":"Puedes previsualizar todo antes de comprar.",
"Every day of every devotional is readable on the campaign page.":"Cada d\u00eda de cada devocional se puede leer en la p\u00e1gina de la campa\u00f1a.",
"Print isn't a separate project.":"Imprimir no es un proyecto aparte.",
"Print-ready files are included with every license, and ordering physical copies is a single step.":"Los archivos listos para imprimir vienen con cada licencia, y pedir copias f\u00edsicas es un solo paso.",
"What we care about most:":"Lo que m\u00e1s nos importa:",
"whether groups keep meeting after the campaign ends.":"que los grupos sigan reuni\u00e9ndose cuando la campa\u00f1a termina.",
"Our process":"Nuestro proceso","How a campaign gets built":"C\u00f3mo se construye una campa\u00f1a",
"Start with an actual pastoral need, not just a topic that seems marketable.":"Empieza con una necesidad pastoral real, no con un tema que parezca vendible.",
"Choose a Scripture passage and central idea distinct enough that it doesn't overlap with existing campaigns.":"Elige un pasaje y una idea central lo bastante distintos para no traslaparse con campa\u00f1as existentes.",
"Write the daily devotional, six group sessions, six sermons, and the youth and children's editions around that same idea.":"Escribe el devocional diario, seis sesiones, seis sermones y las ediciones juvenil e infantil alrededor de esa misma idea.",
"Have someone unfamiliar with the material read it aloud and lead a session, then revise based on what didn't land.":"Haz que alguien ajeno al material lo lea en voz alta y dirija una sesi\u00f3n; revisa seg\u00fan lo que no aterriz\u00f3.",
"Prepare print-ready and digital versions so nothing ships as an unfinished outline.":"Prepara versiones digitales y listas para imprimir para que nada salga como bosquejo sin terminar.",
"Life Together Studios":"Life Together Studios",
"Video production, if you want it":"Producci\u00f3n de video, si la quieres",
"Talking head":"Hablando a c\u00e1mara",
"Pastor speaking directly to camera. Quickest to produce.":"El pastor hablando directo a la c\u00e1mara. Lo m\u00e1s r\u00e1pido de producir.",
"Story-driven":"Guiado por historias",
"Testimonies from your own congregation woven into the teaching.":"Testimonios de tu propia congregaci\u00f3n tejidos en la ense\u00f1anza.",
"Town hall":"Conversatorio",
"A more conversational format, filmed in your own space.":"Un formato m\u00e1s conversacional, filmado en tu propio espacio.",
"A small group of voices discussing the topic together.":"Un peque\u00f1o grupo de voces conversando el tema.",
"You shoot, we edit.":"T\u00fa grabas, nosotros editamos.",
"Send us the raw footage and we'll handle cutting, color correction, captions, and delivery — a middle option between doing it entirely yourself and hiring a full production crew.":"Env\u00edanos el material crudo y nos encargamos del corte, color, subt\u00edtulos y entrega: una opci\u00f3n intermedia entre hacerlo todo t\u00fa y contratar una productora completa.",
"Past campaigns":"Campa\u00f1as pasadas",
"A small sample of prior campaigns. We're working on adding trailers and a fuller showcase to this page.":"Una peque\u00f1a muestra de campa\u00f1as anteriores. Estamos a\u00f1adiendo avances y una vitrina m\u00e1s completa a esta p\u00e1gina.",
"The craft standards":"Los est\u00e1ndares de oficio",
"What \"hand-curated\" means here.":"Qu\u00e9 significa aqu\u00ed \u201ccuidado a mano\u201d.",
"Five commitments govern every campaign in the library. They are not marketing; they are the editing checklist.":"Cinco compromisos gobiernan cada campa\u00f1a de la biblioteca. No son marketing; son la lista de edici\u00f3n.",
"A distinct angle, every time.":"Un \u00e1ngulo distinto, siempre.",
"No two campaigns blur. Each holds its own question, its own scriptural backbone, and its own governing metaphor — even inside the same theme.":"Ning\u00fan par de campa\u00f1as se confunde. Cada una sostiene su pregunta, su columna b\u00edblica y su met\u00e1fora rectora, incluso dentro del mismo tema.",
"The voice is warm and direct. Sensitive seasons — grief, anxiety, financial fear — get permission-to-go-slow pacing and a pointer toward pastoral support.":"La voz es c\u00e1lida y directa. Las temporadas sensibles \u2014 duelo, ansiedad, miedo financiero \u2014 reciben un ritmo con permiso para ir despacio y una se\u00f1al hacia apoyo pastoral.",
"Scripture at the center.":"La Escritura al centro.",
"Daily readings follow an NIV reference plan. Quoted memory verses are KJV (public domain) and clearly labeled, with a one-step swap to NIV once licensing completes.":"Las lecturas siguen un plan de referencias NVI. Los vers\u00edculos citados son de dominio p\u00fablico y est\u00e1n se\u00f1alados, con un cambio de un paso a NVI al completarse la licencia.",
"Built for the newest host.":"Hecho para el anfitri\u00f3n m\u00e1s nuevo.",
"Every session assumes the leader has never led. The questions do the teaching; the kit does the coaching.":"Cada sesi\u00f3n asume que el l\u00edder nunca ha dirigido. Las preguntas ense\u00f1an; el kit acompa\u00f1a.",
"Finished means finished.":"Terminado significa terminado.",
"Sixteen formats per campaign, sequenced to move together. If it needs assembling, it isn't done — and it doesn't ship.":"Diecis\u00e9is formatos por campa\u00f1a, secuenciados para moverse juntos. Si requiere ensamblaje, no est\u00e1 terminado, y no se publica.",
"Everything here rests on one verse.":"Todo aqu\u00ed descansa en un vers\u00edculo.",
"\"The earth is the LORD's, and everything in it.\"":"\u201cDe Jehov\u00e1 es la tierra y su plenitud.\u201d",
"Step into the library →":"Entra a la biblioteca \u2192","Write to us":"Escr\u00edbenos",
"© 2026 40daycampaigns.com · A Lifetogether ministry · Founded by Brett Eastman, 2001":"\u00a9 2026 40daycampaigns.com \u00b7 Un ministerio de Lifetogether \u00b7 Fundado por Brett Eastman, 2001",
"Rancho Santa Margarita, California ·":"Rancho Santa Margarita, California \u00b7",
# ---- tools.html ----
"Tools for the Journey — 40 Day Campaigns":"Herramientas para el recorrido \u2014 40 Day Campaigns",
"Free tools for the whole journey.":"Herramientas gratis para todo el recorrido.",
"Before you spend a dollar, spend ten minutes — measure your readiness, find your matches, and see the plan on your own calendar.":"Antes de gastar un d\u00f3lar, invierte diez minutos: mide tu preparaci\u00f3n, encuentra tus coincidencias y mira el plan en tu propio calendario.",
"A pastor's Tuesday, start to finish.":"El martes de un pastor, de principio a fin.",
"These tools were built to be used in sequence — here is the whole decision, one afternoon, no meetings.":"Estas herramientas se hicieron para usarse en secuencia: aqu\u00ed est\u00e1 toda la decisi\u00f3n, una tarde, sin reuniones.",
"Three minutes of honesty. Score says NEARLY READY; the soft spot is hosts. Noted.":"Tres minutos de honestidad. El puntaje dice CASI LISTOS; el punto d\u00e9bil son los anfitriones. Anotado.",
"Seven questions, three matches. One of them names the exact conversation the church has been avoiding.":"Siete preguntas, tres coincidencias. Una de ellas nombra justo la conversaci\u00f3n que la iglesia ha estado evitando.",
"1:25 — The campaign page":"1:25 \u2014 La p\u00e1gina de la campa\u00f1a",
"Reads Day 1, Day 14, Day 33 in full. Downloads the sermon outlines as Word. Theology holds.":"Lee el D\u00eda 1, el 14 y el 33 completos. Descarga los bosquejos en Word. La teolog\u00eda se sostiene.",
"Picks a kickoff Sunday nine weeks out. The dated runway drops straight into the church calendar.":"Elige un domingo de inicio a nueve semanas. La pista con fechas cae directo en el calendario de la iglesia.",
"2:20 — Done":"2:20 \u2014 Listo",
"One email to the team with the plan attached. Host recruiting starts Sunday. Total spend: $0 so far.":"Un correo al equipo con el plan adjunto. El reclutamiento de anfitriones empieza el domingo. Gasto total: $0 hasta ahora.",
"A reasonable order to use these in:":"Un orden razonable para usarlas:",
"start with the":"empieza con la",
"Readiness Assessment":"Evaluaci\u00f3n de preparaci\u00f3n",
"— it takes about three minutes and gives you an honest read on whether to launch this season or build up to it first. From there, the":"\u2014 toma unos tres minutos y te da una lectura honesta sobre lanzar esta temporada o prepararte primero. Desde ah\u00ed, el",
"narrows the library down to a few campaigns worth considering. Every day of a campaign's devotional is visible on its page, so you can read through one before committing. Once you've picked one, the":"reduce la biblioteca a unas pocas campa\u00f1as dignas de considerar. Cada d\u00eda del devocional es visible en su p\u00e1gina, as\u00ed que puedes leer una antes de comprometerte. Cuando elijas, el",
"puts real dates on it, and the":"le pone fechas reales, y el",
"Leader Hub":"Centro del l\u00edder",
"has what your hosts will need.":"tiene lo que tus anfitriones necesitar\u00e1n.",
"Every tool here is free forever, no email required. They exist so that the decision you make is an informed one — whichever way it goes.":"Cada herramienta aqu\u00ed es gratis para siempre, sin pedir correo. Existen para que tu decisi\u00f3n sea informada, sea cual sea.",
"Start here · 3 minutes":"Empieza aqu\u00ed \u00b7 3 minutos",
"Eight honest questions about your pulpit, groups, leaders, and calendar — scored instantly, with the next move for exactly where your church is.":"Ocho preguntas honestas sobre tu p\u00falpito, grupos, l\u00edderes y calendario, calificadas al instante, con el siguiente paso para el punto exacto donde est\u00e1 tu iglesia.",
"Take the assessment →":"Hacer la evaluaci\u00f3n \u2192",
"7 questions":"7 preguntas",
"The Campaign Finder":"El Buscador de campa\u00f1as",
"Who it's for, what season you're in, what outcome you're praying toward — and 1252 campaigns narrow to your three best matches.":"Para qui\u00e9n es, en qu\u00e9 temporada est\u00e1s, qu\u00e9 resultado est\u00e1s orando: y 1252 campa\u00f1as se reducen a tus tres mejores coincidencias.",
"Find your matches →":"Encuentra tus coincidencias \u2192",
"Dated for your church":"Con fechas para tu iglesia",
"The Launch Planner":"El Planificador de lanzamiento",
"Pick a kickoff Sunday and get the full runway — six prep weeks, six campaign weeks, Celebration Sunday — straight into your calendar as an .ics file.":"Elige un domingo de inicio y recibe la pista completa \u2014 seis semanas de preparaci\u00f3n, seis de campa\u00f1a, Domingo de Celebraci\u00f3n \u2014 directo a tu calendario como archivo .ics.",
"Plan a launch →":"Planificar un lanzamiento \u2192",
"Free, every campaign":"Gratis, cada campa\u00f1a",
"The Reading Room":"La Sala de lectura",
"A distraction-free daily reader with progress, streaks, listen-aloud, candlelight mode, and offline reading. Day One is always free.":"Un lector diario sin distracciones con progreso, rachas, lectura en voz alta, modo vela y lectura sin conexi\u00f3n. El D\u00eda Uno siempre es gratis.",
"Read Day One →":"Leer el D\u00eda Uno \u2192",
"Share the week":"Comparte la semana",
"Verse Cards":"Tarjetas de vers\u00edculos",
"Every memory verse renders as a gold-on-ink 1080×1080 image, one tap from the Reading Room — made for church social feeds.":"Cada vers\u00edculo se genera como imagen 1080\u00d71080 en dorado sobre tinta, a un toque desde la Sala de lectura, hecha para las redes de la iglesia.",
"Make a verse card →":"Crear una tarjeta \u2192",
"For hosts &amp; champions":"Para anfitriones y campeones",
"The Leader &amp; Launch Hub":"El Centro de l\u00edder y lanzamiento",
"Host training, the weekly rhythm, social captions, Launch Sunday and Celebration Sunday — the whole operating system, standardized.":"Entrenamiento de anfitriones, ritmo semanal, textos para redes, Domingo de Lanzamiento y de Celebraci\u00f3n: todo el sistema operativo, estandarizado.",
"Open the hub →":"Abrir el centro \u2192",
"Every tool free · press ⌘K anywhere to jump ·":"Cada herramienta gratis \u00b7 presiona \u2318K en cualquier parte para saltar \u00b7",
# ---- groups.html ----
"Small-Group Curriculum — 40 Day Campaigns":"Curr\u00edculo para grupos peque\u00f1os \u2014 40 Day Campaigns",
"Sometimes groups are the whole plan.":"A veces los grupos son todo el plan.",
"What a session is made of.":"De qu\u00e9 est\u00e1 hecha una sesi\u00f3n.",
"Four movements, one practice, zero seminary required. The questions do the teaching; the room does the growing.":"Cuatro movimientos, una pr\u00e1ctica, cero seminario requerido. Las preguntas ense\u00f1an; la sala crece.",
"Welcome — 10 min":"Bienvenida \u2014 10 min",
"An opening question anyone can answer. Ice broken, table level.":"Una pregunta de apertura que cualquiera puede responder. Hielo roto, mesa pareja.",
"Four movements":"Cuatro movimientos",
"Scripture, a paragraph of framing, honest discussion, real application — four times through.":"Escritura, un p\u00e1rrafo de encuadre, conversaci\u00f3n honesta, aplicaci\u00f3n real: cuatro veces.",
"The practice":"La pr\u00e1ctica",
"One concrete thing to try before next week. Small enough to do, real enough to matter.":"Una cosa concreta para intentar antes de la pr\u00f3xima semana. Peque\u00f1a para hacerse, real para importar.",
"Prayer &amp; the leader's edge":"Oraci\u00f3n y la ventaja del l\u00edder",
"A closing prayer plus host notes: the midweek text, the quiet-person question, the runaway-talker grace.":"Una oraci\u00f3n de cierre m\u00e1s notas para el anfitri\u00f3n: el mensaje de mitad de semana, la pregunta para el callado, la gracia para el que habla de m\u00e1s.",
"Small-Group Edition only — $99.":"Solo edici\u00f3n para grupos \u2014 $99.",
"The complete six-session study with leader notes, print rights included. On every campaign page, right beside the full license.":"El estudio completo de seis sesiones con notas de l\u00edder, derechos de impresi\u00f3n incluidos. En cada p\u00e1gina de campa\u00f1a, junto a la licencia completa.",
"Pick a study →":"Elegir un estudio \u2192",
"Read a session before you buy one.":"Lee una sesi\u00f3n antes de comprar una.",
"This is the opening of Session 1 from our flagship study — exactly as your hosts will see it.":"Esta es la apertura de la Sesi\u00f3n 1 de nuestro estudio insignia, exactamente como la ver\u00e1n tus anfitriones.",
"Three questions groups ask.":"Tres preguntas que hacen los grupos.",
"Do we need the sermons?":"\u00bfNecesitamos los sermones?",
"Can a brand-new host lead this?":"\u00bfPuede dirigirlo un anfitri\u00f3n totalmente nuevo?",
"That is the design constraint we test against. Every question is answerable by a normal adult; the leader's edge notes handle the quiet person, the runaway talker, and the week nobody did the reading.":"Esa es la restricci\u00f3n de dise\u00f1o contra la que probamos. Cada pregunta la puede responder un adulto normal; las notas del l\u00edder cubren al callado, al que habla de m\u00e1s y la semana en que nadie ley\u00f3.",
"How long is a session, honestly?":"\u00bfCu\u00e1nto dura una sesi\u00f3n, honestamente?",
"Where most groups begin.":"Donde la mayor\u00eda de los grupos empieza.",
"Twelve studies churches reach for first — every one leadable by someone who has never led.":"Doce estudios que las iglesias toman primero, todos dirigibles por alguien que nunca ha dirigido.",
"What six weeks usually looks like":"C\u00f3mo se ven normalmente seis semanas",
"Groups tend to follow a fairly predictable pattern from Session 1 to Session 6.":"Los grupos tienden a seguir un patr\u00f3n bastante predecible de la Sesi\u00f3n 1 a la 6.",
"By the last session, the conversation often isn't \"are we done?\" so much as \"what should we do next?\" A lot of groups that finish a study together choose to keep meeting.":"Para la \u00faltima sesi\u00f3n, la conversaci\u00f3n no suele ser \u201c\u00bfya terminamos?\u201d sino \u201c\u00bfqu\u00e9 sigue?\u201d. Muchos grupos que terminan un estudio juntos deciden seguir reuni\u00e9ndose.",
"“Life change happens best in a small group.” ·":"\u201cEl cambio de vida sucede mejor en un grupo peque\u00f1o.\u201d \u00b7",
}
json.dump(ES, open('/home/claude/tr_es_3.json','w'), ensure_ascii=False)
print("ES map 3:", len(ES), "pairs")
