import json
PT = {
"Tools for the Journey — 40 Day Campaigns":"Ferramentas para a jornada \u2014 40 Day Campaigns",
"Free tools for the whole journey.":"Ferramentas gr\u00e1tis para a jornada inteira.",
"Before you spend a dollar, spend ten minutes — measure your readiness, find your matches, and see the plan on your own calendar.":"Antes de gastar um d\u00f3lar, invista dez minutos: me\u00e7a sua prontid\u00e3o, encontre suas combina\u00e7\u00f5es e veja o plano no seu pr\u00f3prio calend\u00e1rio.",
"A pastor's Tuesday, start to finish.":"A ter\u00e7a-feira de um pastor, do come\u00e7o ao fim.",
"These tools were built to be used in sequence — here is the whole decision, one afternoon, no meetings.":"Essas ferramentas foram feitas para usar em sequ\u00eancia: aqui est\u00e1 a decis\u00e3o inteira, uma tarde, sem reuni\u00f5es.",
"Three minutes of honesty. Score says NEARLY READY; the soft spot is hosts. Noted.":"Tr\u00eas minutos de honestidade. A pontua\u00e7\u00e3o diz QUASE PRONTOS; o ponto fraco s\u00e3o os anfitri\u00f5es. Anotado.",
"Seven questions, three matches. One of them names the exact conversation the church has been avoiding.":"Sete perguntas, tr\u00eas combina\u00e7\u00f5es. Uma delas nomeia exatamente a conversa que a igreja vinha evitando.",
"1:25 — The campaign page":"1:25 \u2014 A p\u00e1gina da campanha",
"Reads Day 1, Day 14, Day 33 in full. Downloads the sermon outlines as Word. Theology holds.":"L\u00ea o Dia 1, o 14 e o 33 por inteiro. Baixa os esbo\u00e7os em Word. A teologia se sustenta.",
"Picks a kickoff Sunday nine weeks out. The dated runway drops straight into the church calendar.":"Escolhe um domingo de abertura a nove semanas. A pista com datas cai direto no calend\u00e1rio da igreja.",
"2:20 — Done":"2:20 \u2014 Pronto",
"One email to the team with the plan attached. Host recruiting starts Sunday. Total spend: $0 so far.":"Um e-mail para a equipe com o plano anexo. O recrutamento de anfitri\u00f5es come\u00e7a domingo. Gasto total: $0 at\u00e9 agora.",
"A reasonable order to use these in:":"Uma ordem razo\u00e1vel para us\u00e1-las:",
"start with the":"comece pela",
"Readiness Assessment":"Avalia\u00e7\u00e3o de prontid\u00e3o",
"— it takes about three minutes and gives you an honest read on whether to launch this season or build up to it first. From there, the":"\u2014 leva uns tr\u00eas minutos e d\u00e1 uma leitura honesta sobre lan\u00e7ar nesta temporada ou se preparar antes. Da\u00ed, o",
"narrows the library down to a few campaigns worth considering. Every day of a campaign's devotional is visible on its page, so you can read through one before committing. Once you've picked one, the":"reduz a biblioteca a poucas campanhas dignas de considera\u00e7\u00e3o. Cada dia do devocional \u00e9 vis\u00edvel na p\u00e1gina, ent\u00e3o d\u00e1 para ler um antes de se comprometer. Quando escolher, o",
"puts real dates on it, and the":"coloca datas reais, e o",
"Leader Hub":"Centro do l\u00edder",
"has what your hosts will need.":"tem o que seus anfitri\u00f5es v\u00e3o precisar.",
"Every tool here is free forever, no email required. They exist so that the decision you make is an informed one — whichever way it goes.":"Cada ferramenta aqui \u00e9 gr\u00e1tis para sempre, sem pedir e-mail. Elas existem para que sua decis\u00e3o seja informada, seja qual for.",
"Start here · 3 minutes":"Comece aqui \u00b7 3 minutos",
"Eight honest questions about your pulpit, groups, leaders, and calendar — scored instantly, with the next move for exactly where your church is.":"Oito perguntas honestas sobre seu p\u00falpito, grupos, l\u00edderes e calend\u00e1rio, pontuadas na hora, com o pr\u00f3ximo passo para exatamente onde sua igreja est\u00e1.",
"Take the assessment →":"Fazer a avalia\u00e7\u00e3o \u2192",
"7 questions":"7 perguntas",
"The Campaign Finder":"O Localizador de campanhas",
"Who it's for, what season you're in, what outcome you're praying toward — and 1252 campaigns narrow to your three best matches.":"Para quem \u00e9, em que temporada voc\u00ea est\u00e1, que resultado voc\u00ea est\u00e1 orando: e 1252 campanhas se reduzem \u00e0s suas tr\u00eas melhores combina\u00e7\u00f5es.",
"Find your matches →":"Encontre suas combina\u00e7\u00f5es \u2192",
"Dated for your church":"Com datas para a sua igreja",
"The Launch Planner":"O Planejador de lan\u00e7amento",
"Pick a kickoff Sunday and get the full runway — six prep weeks, six campaign weeks, Celebration Sunday — straight into your calendar as an .ics file.":"Escolha um domingo de abertura e receba a pista completa \u2014 seis semanas de prepara\u00e7\u00e3o, seis de campanha, Domingo de Celebra\u00e7\u00e3o \u2014 direto no calend\u00e1rio como arquivo .ics.",
"Plan a launch →":"Planejar um lan\u00e7amento \u2192",
"Free, every campaign":"Gr\u00e1tis, cada campanha",
"The Reading Room":"A Sala de leitura",
"A distraction-free daily reader with progress, streaks, listen-aloud, candlelight mode, and offline reading. Day One is always free.":"Um leitor di\u00e1rio sem distra\u00e7\u00f5es com progresso, sequ\u00eancias, leitura em voz alta, modo vela e leitura offline. O Dia Um \u00e9 sempre gr\u00e1tis.",
"Read Day One →":"Ler o Dia Um \u2192",
"Share the week":"Compartilhe a semana",
"Verse Cards":"Cart\u00f5es de vers\u00edculos",
"Every memory verse renders as a gold-on-ink 1080×1080 image, one tap from the Reading Room — made for church social feeds.":"Cada vers\u00edculo vira uma imagem 1080\u00d71080 em dourado sobre tinta, a um toque da Sala de leitura, feita para as redes da igreja.",
"Make a verse card →":"Criar um cart\u00e3o \u2192",
"For hosts &amp; champions":"Para anfitri\u00f5es e campe\u00f5es",
"The Leader &amp; Launch Hub":"O Centro do l\u00edder e lan\u00e7amento",
"Host training, the weekly rhythm, social captions, Launch Sunday and Celebration Sunday — the whole operating system, standardized.":"Treinamento de anfitri\u00f5es, ritmo semanal, legendas para redes, Domingo de Lan\u00e7amento e de Celebra\u00e7\u00e3o: o sistema operacional inteiro, padronizado.",
"Open the hub →":"Abrir o centro \u2192",
"Every tool free · press ⌘K anywhere to jump ·":"Cada ferramenta gr\u00e1tis \u00b7 aperte \u2318K em qualquer lugar para pular \u00b7",
"Small-Group Curriculum — 40 Day Campaigns":"Curr\u00edculo para pequenos grupos \u2014 40 Day Campaigns",
"Sometimes groups are the whole plan.":"\u00c0s vezes os grupos s\u00e3o o plano inteiro.",
"What a session is made of.":"Do que uma sess\u00e3o \u00e9 feita.",
"Four movements, one practice, zero seminary required. The questions do the teaching; the room does the growing.":"Quatro movimentos, uma pr\u00e1tica, zero semin\u00e1rio exigido. As perguntas ensinam; a sala cresce.",
"Welcome — 10 min":"Boas-vindas \u2014 10 min",
"An opening question anyone can answer. Ice broken, table level.":"Uma pergunta de abertura que qualquer um responde. Gelo quebrado, mesa nivelada.",
"Four movements":"Quatro movimentos",
"Scripture, a paragraph of framing, honest discussion, real application — four times through.":"Escritura, um par\u00e1grafo de enquadramento, conversa honesta, aplica\u00e7\u00e3o real: quatro vezes.",
"The practice":"A pr\u00e1tica",
"One concrete thing to try before next week. Small enough to do, real enough to matter.":"Uma coisa concreta para tentar antes da pr\u00f3xima semana. Pequena para fazer, real para importar.",
"Prayer &amp; the leader's edge":"Ora\u00e7\u00e3o e a vantagem do l\u00edder",
"A closing prayer plus host notes: the midweek text, the quiet-person question, the runaway-talker grace.":"Uma ora\u00e7\u00e3o de encerramento mais notas do anfitri\u00e3o: a mensagem do meio da semana, a pergunta para o quieto, a gra\u00e7a para quem fala demais.",
"Small-Group Edition only — $99.":"S\u00f3 a edi\u00e7\u00e3o de grupos \u2014 $99.",
"The complete six-session study with leader notes, print rights included. On every campaign page, right beside the full license.":"O estudo completo de seis sess\u00f5es com notas de l\u00edder, direitos de impress\u00e3o inclu\u00eddos. Em cada p\u00e1gina de campanha, ao lado da licen\u00e7a completa.",
"Pick a study →":"Escolher um estudo \u2192",
"Read a session before you buy one.":"Leia uma sess\u00e3o antes de comprar.",
"This is the opening of Session 1 from our flagship study — exactly as your hosts will see it.":"Esta \u00e9 a abertura da Sess\u00e3o 1 do nosso estudo principal, exatamente como seus anfitri\u00f5es ver\u00e3o.",
"Three questions groups ask.":"Tr\u00eas perguntas que os grupos fazem.",
"Do we need the sermons?":"Precisamos dos serm\u00f5es?",
"Can a brand-new host lead this?":"Um anfitri\u00e3o totalmente novo consegue conduzir?",
"That is the design constraint we test against. Every question is answerable by a normal adult; the leader's edge notes handle the quiet person, the runaway talker, and the week nobody did the reading.":"Essa \u00e9 a restri\u00e7\u00e3o de design que testamos. Cada pergunta pode ser respondida por um adulto normal; as notas do l\u00edder cobrem o quieto, o que fala demais e a semana em que ningu\u00e9m leu.",
"How long is a session, honestly?":"Quanto dura uma sess\u00e3o, honestamente?",
"Where most groups begin.":"Onde a maioria dos grupos come\u00e7a.",
"Twelve studies churches reach for first — every one leadable by someone who has never led.":"Doze estudos que as igrejas pegam primeiro, todos conduz\u00edveis por quem nunca liderou.",
"What six weeks usually looks like":"Como seis semanas normalmente s\u00e3o",
"Groups tend to follow a fairly predictable pattern from Session 1 to Session 6.":"Os grupos tendem a seguir um padr\u00e3o bem previs\u00edvel da Sess\u00e3o 1 \u00e0 6.",
"By the last session, the conversation often isn't \"are we done?\" so much as \"what should we do next?\" A lot of groups that finish a study together choose to keep meeting.":"Na \u00faltima sess\u00e3o, a conversa costuma n\u00e3o ser \u201cacabou?\u201d, mas \u201co que vem agora?\u201d. Muitos grupos que terminam um estudo juntos decidem continuar se reunindo.",
"“Life change happens best in a small group.” ·":"\u201cA mudan\u00e7a de vida acontece melhor em um pequeno grupo.\u201d \u00b7",
"Campaign Finder — 40 Day Campaigns":"Localizador de campanhas \u2014 40 Day Campaigns",
"Six questions. Three matches.":"Seis perguntas. Tr\u00eas combina\u00e7\u00f5es.",
"Tell us who this is for, the season you're in, and how you want to launch — we'll pull three hand-picked campaigns from the library.":"Diga para quem \u00e9, em que temporada voc\u00ea est\u00e1 e como quer lan\u00e7ar; vamos puxar tr\u00eas campanhas escolhidas a dedo da biblioteca.",
"Your three matches":"Suas tr\u00eas combina\u00e7\u00f5es","Start over":"Recome\u00e7ar",
"Who is this journey for?":"Para quem \u00e9 esta jornada?",
"Our whole church":"Nossa igreja inteira",
"A churchwide campaign — pulpit, groups, and homes together":"Uma campanha de toda a igreja: p\u00falpito, grupos e lares juntos",
"Our family":"Nossa fam\u00edlia",
"Something to walk through around the table":"Algo para percorrer em volta da mesa",
"My clients":"Meus clientes",
"Advisor, attorney, CPA, or family office":"Assessor, advogado, contador ou family office",
"Development officers and generosity ministries":"Captadores e minist\u00e9rios de generosidade",
"A business or team":"Uma empresa ou equipe",
"Owners, executives, and the marketplace":"Donos, executivos e o mercado",
"Students & young adults":"Jovens e universit\u00e1rios",
"High school through the launch years":"Do ensino m\u00e9dio aos anos de decolagem",
"What season or need is front of mind?":"Que temporada ou necessidade est\u00e1 em mente?",
"Money & stewardship":"Dinheiro e mordomia",
"Ownership, wisdom, and financial peace":"Tudo \u00e9 de Deus, sabedoria e paz financeira",
"Generosity & giving":"Generosidade e contribui\u00e7\u00e3o",
"Open hands and a culture of giving":"M\u00e3os abertas e uma cultura de doar",
"Legacy & inheritance":"Legado e heran\u00e7a",
"Estate, wealth transfer, preparing heirs":"Patrim\u00f4nio, transfer\u00eancia e prepara\u00e7\u00e3o de herdeiros",
"Family, marriage & home":"Fam\u00edlia, casamento e lar",
"Mission, conversations, parenting, grandparents":"Miss\u00e3o, conversas, cria\u00e7\u00e3o de filhos, av\u00f3s",
"Work, leadership & purpose":"Trabalho, lideran\u00e7a e prop\u00f3sito",
"Calling, wisdom, business, succession":"Chamado, sabedoria, neg\u00f3cios, sucess\u00e3o",
"Faith & spiritual growth":"F\u00e9 e crescimento espiritual",
"Discipleship, prayer, community":"Discipulado, ora\u00e7\u00e3o, comunidade",
"A life transition":"Uma transi\u00e7\u00e3o de vida",
"Retirement, loss, empty nest, finishing well":"Aposentadoria, perda, ninho vazio, terminar bem",
"Hope, peace & healing":"Esperan\u00e7a, paz e cura",
"For an anxious or grieving season":"Para uma temporada de ansiedade ou luto",
"Kingdom impact & mission":"Impacto do Reino e miss\u00e3o",
"Living and giving for what lasts":"Viver e doar pelo que permanece",
"How long a journey fits right now?":"Que dura\u00e7\u00e3o cabe agora?",
"A focused week":"Uma semana focada",
"About three weeks":"Cerca de tr\u00eas semanas",
"About a month":"Cerca de um m\u00eas",
"A churchwide-scale movement":"Um movimento em escala de toda a igreja",
"Built for small groups and classes":"Feito para pequenos grupos e classes",
"No preference":"Sem prefer\u00eancia",
"Show me the best fit":"Mostre o melhor encaixe",
"What outcome matters most this season?":"Que resultado importa mais nesta temporada?",
"Launch or strengthen groups":"Lan\u00e7ar ou fortalecer grupos",
"Get more people into biblical community":"Levar mais pessoas \u00e0 comunidade b\u00edblica",
"Build a generosity culture":"Construir uma cultura de generosidade",
"Open hands across the whole church":"M\u00e3os abertas na igreja inteira",
"Unite the family":"Unir a fam\u00edlia",
"Shared language around faith, money, and mission":"Uma linguagem comum de f\u00e9, dinheiro e miss\u00e3o",
"Prepare the next generation":"Preparar a pr\u00f3xima gera\u00e7\u00e3o",
"Character, identity, and readiness for heirs":"Car\u00e1ter, identidade e preparo dos herdeiros",
"Develop leaders":"Desenvolver l\u00edderes",
"Wisdom, calling, and marketplace influence":"Sabedoria, chamado e influ\u00eancia no mercado",
"Bring hope & healing":"Trazer esperan\u00e7a e cura",
"For a congregation or family in a hard season":"Para uma congrega\u00e7\u00e3o ou fam\u00edlia em temporada dif\u00edcil",
"Who specifically will walk it?":"Quem especificamente vai percorrer?",
"Everyone together":"Todos juntos",
"The broadest on-ramp for all ages and stages":"A rampa mais ampla para todas as idades e fases",
"Couples & marriages":"Casais e casamentos","Built for two":"Feito para dois",
"Parents of kids at home":"Pais com filhos em casa",
"Faith around the table":"F\u00e9 em volta da mesa",
"Legacy across three generations":"Legado por tr\u00eas gera\u00e7\u00f5es",
"Retirees & later-life families":"Aposentados e fam\u00edlias na segunda metade",
"The second half and finishing well":"A segunda metade e terminar bem",
"When do you want to launch?":"Quando voc\u00ea quer lan\u00e7ar?",
"This ministry season":"Nesta temporada ministerial",
"A full churchwide build-up":"Uma prepara\u00e7\u00e3o completa de toda a igreja",
"Year-end giving season":"Temporada de doa\u00e7\u00f5es de fim de ano",
"Still exploring":"Ainda explorando",
"Just show me the best fits":"S\u00f3 mostre os melhores encaixes",
"Any life stages or affinities to include?":"Fases de vida ou afinidades para incluir?",
"Single adults & single again":"Solteiros e solteiros de novo",
"Empty nesters":"Ninho vazio",
"Business owners & executives":"Empres\u00e1rios e executivos",
"Parents of adult children":"Pais de filhos adultos",
"Newly married":"Rec\u00e9m-casados",
"Retirees & finishing well":"Aposentados e terminar bem",
"Change who this is for":"Mudar para quem \u00e9",
"A flagship of the":"Uma principal da",
"Campaign Readiness Assessment — 40 Day Campaigns":"Avalia\u00e7\u00e3o de prontid\u00e3o \u2014 40 Day Campaigns",
"Tools · Campaign Readiness Assessment":"Ferramentas \u00b7 Avalia\u00e7\u00e3o de prontid\u00e3o",
"How ready is your church, honestly?":"Qu\u00e3o pronta est\u00e1 sua igreja, honestamente?",
"Eight questions, three minutes, scored instantly. Rate each 1 (not us, not yet) to 5 (that's us). No email required — this is for you.":"Oito perguntas, tr\u00eas minutos, pontuadas na hora. D\u00ea nota de 1 (n\u00e3o somos n\u00f3s, ainda) a 5 (somos n\u00f3s). Sem e-mail: isto \u00e9 para voc\u00ea.",
"Answer all eight to see your score":"Responda as oito para ver sua pontua\u00e7\u00e3o",
"Retake the assessment":"Refazer a avalia\u00e7\u00e3o",
"32–40 · Ready":"32\u201340 \u00b7 Prontos",
"The pulpit, the champion, and the runway are real. Pick the journey and the Sunday; momentum will do the rest.":"O p\u00falpito, o campe\u00e3o e a pista s\u00e3o reais. Escolha a jornada e o domingo; o impulso faz o resto.",
"22–31 · Nearly ready":"22\u201331 \u00b7 Quase prontos",
"One or two soft spots — usually hosts or the champion. Four to eight weeks of focused prep turns nearly into fully.":"Um ou dois pontos fracos, normalmente anfitri\u00f5es ou o campe\u00e3o. De quatro a oito semanas de preparo focado transformam o quase em totalmente.",
"8–21 · Building":"8\u201321 \u00b7 Construindo",
"Wisdom, not failure. A 7-day journey builds the muscle and surfaces the hosts a full campaign will need later.":"Sabedoria, n\u00e3o fracasso. Uma jornada de 7 dias constr\u00f3i o m\u00fasculo e revela os anfitri\u00f5es que uma campanha completa vai precisar depois.",
"Part of the free":"Parte da cole\u00e7\u00e3o gratuita","collection ·":"\u00b7",
"Pulpit commitment":"Compromisso do p\u00falpito",
"Our senior pastor would preach six aligned messages and cast the vision twice.":"Nosso pastor titular pregaria seis mensagens alinhadas e apresentaria a vis\u00e3o duas vezes.",
"A champion":"Um campe\u00e3o",
"Someone on staff or a trusted volunteer could own the campaign end to end.":"Algu\u00e9m da equipe ou um volunt\u00e1rio de confian\u00e7a poderia assumir a campanha de ponta a ponta.",
"Host potential":"Potencial de anfitri\u00f5es",
"Calendar runway":"Pista de calend\u00e1rio",
"We have a six-week preparation window before a realistic kickoff Sunday.":"Temos uma janela de seis semanas antes de um domingo de abertura realista.",
"All-ages intent":"Inten\u00e7\u00e3o de todas as idades",
"Follow-through culture":"Cultura de concluir",
"When we start something churchwide, we typically finish it well.":"Quando come\u00e7amos algo de toda a igreja, normalmente terminamos bem.",
"Materials plan":"Plano de materiais",
"We can get a devotional into every household — printed or digital.":"Conseguimos levar um devocional a cada casa, impresso ou digital.",
"Celebration instinct":"Instinto de celebra\u00e7\u00e3o",
"We would actually stop and celebrate at the end — stories, gratitude, commissioning.":"N\u00f3s realmente parar\u00edamos para celebrar no fim: hist\u00f3rias, gratid\u00e3o, comissionamento.",
"READY — LAUNCH THIS SEASON":"PRONTOS \u2014 LANCEM NESTA TEMPORADA",
"Green light. Pick your Sunday.":"Sinal verde. Escolha seu domingo.",
"Run the Finder and pick from your three matches":"Use o Localizador e escolha entre suas tr\u00eas combina\u00e7\u00f5es",
"Open the Launch Planner and lock a kickoff Sunday":"Abra o Planejador e trave um domingo de abertura",
"Plan the launch":"Planejar o lan\u00e7amento",
"Close. Shore up two things first.":"Perto. Refor\u00e7racem duas coisas antes.",
"Name a champion this week and put the runway on the calendar":"Nomeie um campe\u00e3o esta semana e coloque a pista no calend\u00e1rio",
"Start host recruiting before you announce anything else":"Comece a recrutar anfitri\u00f5es antes de anunciar qualquer outra coisa",
"Study the runway":"Estude a pista",
"BUILDING — START SMALLER":"CONSTRUINDO \u2014 COMECEM MENOR",
"Identify two or three future hosts and disciple them now":"Identifique dois ou tr\u00eas futuros anfitri\u00f5es e discipule agora",
"Retake this in eight weeks; the score will move":"Refa\u00e7a em oito semanas; a pontua\u00e7\u00e3o vai mudar",
"Talk it through with us":"Converse com a gente",
"Launch Planner — 40 Day Campaigns":"Planejador de lan\u00e7amento \u2014 40 Day Campaigns",
"Pick a Sunday. We'll plan the rest.":"Escolha um domingo. N\u00f3s planejamos o resto.",
"choose a different campaign":"escolher outra campanha",
"Kickoff Sunday":"Domingo de abertura",
"⤓ Add to calendar (.ics)":"\u2913 Adicionar ao calend\u00e1rio (.ics)",
"🖨 Print plan":"\U0001F5A8 Imprimir plano",
"Save to my account":"Salvar na minha conta",
"Your launch at a glance":"Seu lan\u00e7amento em resumo",
"Prep window":"Janela de preparo",
"6 weeks":"6 semanas",
"Campaign length":"Dura\u00e7\u00e3o da campanha",
"Sermons · Sessions":"Serm\u00f5es \u00b7 Sess\u00f5es",
"Open Day One in the Reading Room":"Abrir o Dia Um na Sala de leitura",
"Open the Leader &amp; Launch Kit":"Abrir o Kit do l\u00edder e lan\u00e7amento",
"© 2026 40daycampaigns.com · The Launch Planner":"\u00a9 2026 40daycampaigns.com \u00b7 O Planejador de lan\u00e7amento",
"Dates snap to Sundays · calendar file works with Google, Apple &amp; Outlook":"As datas se ajustam a domingos \u00b7 o arquivo funciona com Google, Apple e Outlook",
"Cast the vision to staff and elders":"Apresente a vis\u00e3o \u00e0 equipe e aos presb\u00edteros",
"Name a campaign champion":"Nomeie um campe\u00e3o da campanha",
"Launch the host sign-up list":"Lance a lista de inscri\u00e7\u00e3o de anfitri\u00f5es",
"Hand every host the Leader & Launch Kit":"Entregue a cada anfitri\u00e3o o Kit do l\u00edder e lan\u00e7amento",
"Order participant devotionals for print or digital":"Encomende os devocionais, impressos ou digitais",
"Open group sign-ups in the lobby and online":"Abra inscri\u00e7\u00f5es de grupos no sagu\u00e3o e online",
"Youth & children directors brief their teams":"Diretores de jovens e crian\u00e7as orientam suas equipes",
"Place every sign-up in a group and confirm rosters":"Coloque cada inscrito em um grupo e confirme as listas",
"Hosts make first contact with their groups":"Anfitri\u00f5es fazem o primeiro contato",
"Distribute devotionals to every household":"Distribua devocionais a cada casa",
"PREPARE — SIX WEEKS OUT":"PREPARAR \u2014 SEIS SEMANAS ANTES",
"RUN — THE CAMPAIGN":"RODAR \u2014 A CAMPANHA",
"Daily readings:":"Leituras di\u00e1rias:",
"Memory verse:":"Vers\u00edculo da semana:",
"Stories from the journey — two or three voices":"Hist\u00f3rias da jornada: duas ou tr\u00eas vozes",
"Commission the groups that want to continue":"Comissione os grupos que quiserem continuar",
"Kickoffs land on Sundays — snapped to":"As aberturas caem em domingos \u2014 ajustado para",
"For Senior Pastors — 40 Day Campaigns":"Para pastores titulares \u2014 40 Day Campaigns",
"For senior pastors":"Para pastores titulares",
"You bring the pulpit.":"Voc\u00ea traz o p\u00falpito.",
"We bring the forty days.":"N\u00f3s trazemos os quarenta dias.",
"You already carry the weight of Sunday. A campaign doesn't add to it — it multiplies it, by giving the other six days the same care your sermon gets.":"Voc\u00ea j\u00e1 carrega o peso do domingo. Uma campanha n\u00e3o aumenta esse peso: ela o multiplica, dando aos outros seis dias o mesmo cuidado que o seu serm\u00e3o recebe.",
"Plan your launch — pick a Sunday →":"Planeje seu lan\u00e7amento: escolha um domingo \u2192",
"The problem, named honestly":"O problema, nomeado com honestidade",
"Sunday keeps ending on Sunday.":"O domingo continua terminando no domingo.",
"The greatest challenge a campaign solved for us was giving leaders something to use all week — not just on Sunday.":"O maior desafio que uma campanha resolveu para n\u00f3s foi dar aos l\u00edderes algo para usar a semana toda, n\u00e3o s\u00f3 no domingo.",
"During the six weeks":"Durante as seis semanas",
"Three things change — and tend to stay changed.":"Tr\u00eas coisas mudam, e tendem a ficar mudadas.",
"The church aligns.":"A igreja se alinha.",
"For six weeks, everyone is on the same page — literally. Announcements get simpler, staff meetings get shorter, and momentum compounds instead of competing.":"Por seis semanas, todos est\u00e3o na mesma p\u00e1gina, literalmente. Os avisos ficam mais simples, as reuni\u00f5es mais curtas e o impulso se soma em vez de competir.",
"Households join in.":"Os lares entram junto.",
"The same memory verse sits in the adult reading, the youth edition, and the kids' craft. Faith stops being what happens to people separately on Sundays.":"O mesmo vers\u00edculo est\u00e1 na leitura dos adultos, na edi\u00e7\u00e3o jovem e na atividade das crian\u00e7as. A f\u00e9 deixa de ser o que acontece com cada um separadamente aos domingos.",
"Leaders multiply.":"Os l\u00edderes se multiplicam.",
"\"Host a group for six weeks\" is the lowest-threshold leadership invitation in church life. Many hosts keep going when the six weeks end — now you have shepherds you didn't have in August.":"\u201cSeja anfitri\u00e3o de um grupo por seis semanas\u201d \u00e9 o convite \u00e0 lideran\u00e7a de menor barreira na vida da igreja. Muitos anfitri\u00f5es continuam quando as seis semanas acabam: agora voc\u00ea tem pastores que n\u00e3o tinha em agosto.",
"Born from the Purpose Driven campaign era":"Nascida da era de campanhas de Uma Vida com Prop\u00f3sitos",
"500+ churches served":"Mais de 500 igrejas servidas",
"Our story →":"Nossa hist\u00f3ria \u2192",
"What it asks of you. What it doesn't.":"O que pede de voc\u00ea. O que n\u00e3o pede.",
"No platform should hide the pastor's real workload. Here is yours, in full.":"Nenhuma plataforma deveria esconder a carga real do pastor. Aqui est\u00e1 a sua, por inteiro.",
"Yours — about ten hours across twelve weeks":"O seu: cerca de dez horas em doze semanas",
"Cast the vision twice: once to leaders, once from the pulpit":"Apresente a vis\u00e3o duas vezes: uma aos l\u00edderes, outra do p\u00falpito",
"Preach six sermons — outlines, texts, and landings provided":"Pregue seis serm\u00f5es: esbo\u00e7os, textos e aterrissagens fornecidos",
"Commission the hosts and celebrate on the final Sunday":"Comissione os anfitri\u00f5es e celebre no domingo final",
"Pick the campaign (the Finder narrows 1252 to three)":"Escolha a campanha (o Localizador reduz 1252 a tr\u00eas)",
"Done — before you ever download it":"Pronto, antes mesmo de voc\u00ea baixar",
"Every daily reading, all forty days, fully written":"Cada leitura di\u00e1ria, os quarenta dias, totalmente escrita",
"Every session, sermon outline, youth &amp; kids week":"Cada sess\u00e3o, esbo\u00e7o e semana jovem e infantil",
"The recruiting language, orientation, and sign-up plan":"A linguagem de recrutamento, a orienta\u00e7\u00e3o e o plano de inscri\u00e7\u00e3o",
"A dated runway on your calendar, via the":"Uma pista com datas no seu calend\u00e1rio, via",
"Planting, or under fifty on Sundays?":"Plantando, ou menos de cinquenta aos domingos?",
"The whole library shouldn't be a budget line you fear. Church plants and churches under fifty take 40% off everything with code":"A biblioteca inteira n\u00e3o deveria ser uma linha de or\u00e7amento que assusta. Igrejas plantadas e com menos de cinquenta t\u00eam 40% de desconto em tudo com o c\u00f3digo",
"— no application, no call.":", sem inscri\u00e7\u00e3o, sem liga\u00e7\u00e3o.",
"See pricing →":"Ver pre\u00e7os \u2192",
"Twelve weeks from now":"Daqui a doze semanas",
"Imagine Celebration Sunday.":"Imagine o Domingo de Celebra\u00e7\u00e3o.",
"Stories from the journey. Groups that want to keep meeting. A church that read the same forty days — together.":"Hist\u00f3rias da jornada. Grupos que querem continuar se reunindo. Uma igreja que leu os mesmos quarenta dias, junta.",
"Talk to a real person":"Fale com uma pessoa de verdade",
"What's included":"O que est\u00e1 inclu\u00eddo",
"Everything your team gets, spelled out":"Tudo o que sua equipe recebe, detalhado",
"For the pulpit:":"Para o p\u00falpito:",
"For small groups:":"Para os pequenos grupos:",
"For every household:":"Para cada lar:",
"the full daily devotional at any length, available on paper, in the offline Reading Room, or as an audio read-aloud, plus shareable verse graphics.":"o devocional di\u00e1rio completo em qualquer dura\u00e7\u00e3o, em papel, na Sala de leitura offline ou como leitura em voz alta, mais artes de vers\u00edculos para compartilhar.",
"For families:":"Para as fam\u00edlias:",
"youth and children's editions that cover the same weekly idea in age-appropriate language, so different generations in the same house are working through similar material.":"edi\u00e7\u00f5es jovem e infantil que cobrem a mesma ideia semanal em linguagem adequada, para gera\u00e7\u00f5es diferentes da mesma casa trabalharem material semelhante.",
"For whoever's running point:":"Para quem estiver \u00e0 frente:",
"a Leader & Launch Kit with host training, a six-week schedule with real dates, a run-of-show for Launch Sunday, six weeks of social media captions, and a plan for Celebration Sunday.":"um Kit do l\u00edder e lan\u00e7amento com treinamento de anfitri\u00f5es, um cronograma de seis semanas com datas reais, um roteiro para o Domingo de Lan\u00e7amento, seis semanas de legendas para redes e um plano para o Domingo de Celebra\u00e7\u00e3o.",
"Common questions":"Perguntas comuns",
"Three concerns we hear a lot":"Tr\u00eas preocupa\u00e7\u00f5es que ouvimos muito",
"\"Our people won't read every day.\"":"\u201cNossa gente n\u00e3o vai ler todo dia.\u201d",
"Some won't, and the material is built with that in mind. Sessions and sermons each stand on their own, so a household that gets to four days out of seven still stays with the church's rhythm.":"Alguns n\u00e3o v\u00e3o, e o material \u00e9 feito com isso em mente. Sess\u00f5es e serm\u00f5es se sustentam sozinhos, ent\u00e3o uma casa que chega a quatro dias de sete continua no ritmo da igreja.",
"\"We can't find enough hosts.\"":"\u201cN\u00e3o achamos anfitri\u00f5es suficientes.\u201d",
"\"Our pastor already writes his own material.\"":"\u201cNosso pastor j\u00e1 escreve o pr\u00f3prio material.\u201d",
"“Don't let Sunday end on Sunday.” ·":"\u201cN\u00e3o deixe o domingo terminar no domingo.\u201d \u00b7",
"Purpose Built Business — Team Campaigns from Lifetogether":"Purpose Built Business \u2014 Campanhas de equipe da Lifetogether",
"Purpose Built Business · from Lifetogether":"Purpose Built Business \u00b7 da Lifetogether",
"Teams that know why they work.":"Equipes que sabem por que trabalham.",
"Safe for HR":"Seguro para o RH",
"Mixed-faith friendly":"Amig\u00e1vel a equipes de f\u00e9 mista",
"Led by any team lead":"Conduz\u00edvel por qualquer l\u00edder de equipe",
"15 minutes a day, one hour a week":"15 minutos por dia, uma hora por semana",
"Explore the workplace library →":"Explorar a biblioteca corporativa \u2192",
"Talk to us about your team":"Fale conosco sobre sua equipe",
"How it works inside a company":"Como funciona dentro de uma empresa",
"The same rhythm that has moved churches for twenty-five years, translated for the workplace: everyone reading the same short idea, talking about it once a week, and practicing it where it counts.":"O mesmo ritmo que move igrejas h\u00e1 vinte e cinco anos, traduzido para o trabalho: todos lendo a mesma ideia curta, conversando uma vez por semana e praticando onde conta.",
"Pick a campaign":"Escolha uma campanha",
"Choose from the workplace library: trust, burnout, communication, ownership, character, succession. Each one is complete: daily reads, a facilitator guide, and weekly challenges.":"Escolha da biblioteca corporativa: confian\u00e7a, esgotamento, comunica\u00e7\u00e3o, responsabilidade, car\u00e1ter, sucess\u00e3o. Cada uma completa: leituras di\u00e1rias, guia do facilitador e desafios semanais.",
"Run the rhythm":"Rode o ritmo",
"Five short reads a week, one 45-minute team conversation, one concrete practice. No outside speaker, no training budget, no theology degree. A team lead with the guide can run it cold.":"Cinco leituras curtas por semana, uma conversa de 45 minutos, uma pr\u00e1tica concreta. Sem palestrante externo, sem verba de treinamento, sem diploma de teologia. Um l\u00edder com o guia conduz sem preparo.",
"Watch the culture shift":"Veja a cultura mudar",
"Meetings get more honest, feedback gets kinder, ownership gets contagious. Culture doesn't change through posters. It changes when a team thinks about the same thing at the same time.":"As reuni\u00f5es ficam mais honestas, o feedback mais gentil, a responsabilidade contagiante. Cultura n\u00e3o muda com cartazes. Muda quando a equipe pensa na mesma coisa ao mesmo tempo.",
"A week on a team":"Uma semana numa equipe",
"Simple enough to survive a real workweek.":"Simples o bastante para sobreviver a uma semana real de trabalho.",
"The week's one-page brief: the big idea, in plain language.":"O resumo de uma p\u00e1gina da semana: a grande ideia, em linguagem simples.",
"Five-minute daily reads. Phone or paper, coffee-break sized.":"Leituras di\u00e1rias de cinco minutos. Celular ou papel, tamanho pausa para caf\u00e9.",
"Team session":"Sess\u00e3o de equipe",
"45 minutes: one question in, four short conversations, one decision out.":"45 minutos: uma pergunta na entrada, quatro conversas curtas, uma decis\u00e3o na sa\u00edda.",
"One concrete behavior for the week. Small enough to do, real enough to notice.":"Um comportamento concreto para a semana. Pequeno para fazer, real para notar.",
"Two-line check-in: where it worked, where it got hard. Then rest.":"Um registro de duas linhas: onde funcionou, onde ficou dif\u00edcil. Depois, descanso.",
"The workplace library":"A biblioteca corporativa",
"Campaigns built for teams, leaders, and companies — drawn from the same catalog trusted by hundreds of churches, in workplace language.":"Campanhas para equipes, l\u00edderes e empresas, tiradas do mesmo cat\u00e1logo em que centenas de igrejas confiam, em linguagem corporativa.",
"Looking for the full church catalog instead?":"Procurando o cat\u00e1logo completo para igrejas?",
"It's over here →":"Est\u00e1 aqui \u2192",
"Where we're coming from, honestly.":"De onde viemos, honestamente.",
"Questions companies actually ask":"Perguntas que as empresas realmente fazem",
"Is this religious content? We're a mixed-faith team.":"\u00c9 conte\u00fado religioso? Somos uma equipe de f\u00e9 mista.",
"Who leads it? We don't have a facilitator.":"Quem conduz? N\u00e3o temos facilitador.",
"How much time does it really take?":"Quanto tempo realmente leva?",
"About fifteen minutes a day of reading and one 45-minute team session per week, for the length of the campaign. It's designed to fit inside a normal workweek, not on top of one.":"Uns quinze minutos de leitura por dia e uma sess\u00e3o de 45 minutos por semana, pela dura\u00e7\u00e3o da campanha. Foi desenhado para caber dentro de uma semana normal, n\u00e3o em cima de uma.",
"Can we run it company-wide?":"Podemos rodar na empresa toda?",
"talk to us":"fale conosco",
"and we'll scope it to your size.":"e dimensionamos para o seu tamanho.",
"Bring purpose to your team.":"Traga prop\u00f3sito para a sua equipe.",
"Tell us your team size and the challenge you're facing — trust, burnout, ownership, a season of change — and we'll point you to the right campaign and put real dates on it.":"Diga o tamanho da equipe e o desafio que enfrentam \u2014 confian\u00e7a, esgotamento, responsabilidade, uma temporada de mudan\u00e7a \u2014 e indicamos a campanha certa com datas reais.",
"Start the conversation →":"Come\u00e7ar a conversa \u2192",
"Sample — Devotional &amp; Study — 40 Day Campaigns":"Amostra \u2014 Devocional e estudo \u2014 40 Day Campaigns",
"&#8592; Back to campaign":"&#8592; Voltar \u00e0 campanha",
"Download PDF":"Baixar PDF",
"In the print dialog, choose “Save as PDF”":"Na caixa de impress\u00e3o, escolha \u201cSalvar como PDF\u201d",
"In the print dialog, choose &ldquo;Save as PDF&rdquo;":"Na caixa de impress\u00e3o, escolha &ldquo;Salvar como PDF&rdquo;",
"The Reading Room — 40 Day Campaigns":"A Sala de leitura \u2014 40 Day Campaigns",
"— min read":"\u2014 min de leitura",
"TODAY'S READING":"LEITURA DE HOJE",
"Reflect &amp; Respond":"Reflita e responda",
"One Step Today":"Um passo hoje",
"Mark day complete":"Marcar dia como conclu\u00eddo",
"candlelight":"luz de vela",
"Journey complete":"Jornada conclu\u00edda",
"You finished this journey.":"Voc\u00ea terminou esta jornada.",
"Forty small yeses, one changed direction. Carry the anchor verse with you — and don't walk the next season alone.":"Quarenta pequenos sins, uma dire\u00e7\u00e3o mudada. Leve o vers\u00edculo \u00e2ncora com voc\u00ea, e n\u00e3o caminhe a pr\u00f3xima temporada sozinho.",
"Open the group study":"Abrir o estudo de grupo",
"Choose your next journey":"Escolha sua pr\u00f3xima jornada",
"Back to the library":"Voltar \u00e0 biblioteca",
"Completed — Day":"Conclu\u00eddo \u2014 Dia",
"You finished":"Voc\u00ea terminou",
"Go to day":"Ir para o dia",
"Stop listening":"Parar de ouvir",
"Facilitator Course":"Curso de facilitadores",
"Print-on-Demand Edition":"Edi\u00e7\u00e3o de impress\u00e3o sob demanda",
"Complete Digital Library":"Biblioteca digital completa",
"Leader & Launch Kit":"Kit do l\u00edder e lan\u00e7amento",
"My Account — 40 Day Campaigns":"Minha conta \u2014 40 Day Campaigns",
"Your profile, your All Access status, and every campaign license in your library.":"Seu perfil, seu status All Access e cada licen\u00e7a de campanha na sua biblioteca.",
"Profile":"Perfil","Church":"Igreja","Church size":"Tamanho da igreja","Sign out":"Sair",
"No card on file yet — add one at checkout.":"Nenhum cart\u00e3o salvo ainda: adicione um no pagamento.",
"Not active yet. All Access opens the entire 1252-campaign library plus editable source files — from $49/mo by church size, with a 40% church-plant discount.":"Ainda n\u00e3o ativo. O All Access abre a biblioteca completa de 1252 campanhas mais arquivos edit\u00e1veis, a partir de $49/m\u00eas pelo tamanho da igreja, com 40% de desconto para igrejas plantadas.",
"Get All Access":"Assinar o All Access",
"My launch":"Meu lan\u00e7amento","My journey":"Minha jornada","Your orders":"Seus pedidos","My library":"Minha biblioteca","Welcome back,":"Bem-vindo de volta,",
"Lost? Every door is right here — 40 Day Campaigns":"Perdido? Todas as portas est\u00e3o aqui \u2014 40 Day Campaigns",
"Page not found":"P\u00e1gina n\u00e3o encontrada",
"We couldn't find that page.":"N\u00e3o encontramos essa p\u00e1gina.",
"The link may be outdated, mistyped, or point to a page that's moved. Everything on the site is reachable from here — search below, or use one of the links.":"O link pode estar desatualizado, digitado errado ou apontar para uma p\u00e1gina que mudou. Tudo no site \u00e9 alcan\u00e7\u00e1vel daqui: busque abaixo ou use um dos links.",
"Every door on the site.":"Todas as portas do site.",
"The Library":"A biblioteca",
"All 1252 campaigns, filterable by category, theme, and audience":"As 1252 campanhas, filtr\u00e1veis por categoria, tema e p\u00fablico",
"Fifteen doors, top-ten shelves, every theme grouped":"Quinze portas, estantes top dez, cada tema agrupado",
"Seven questions → your three best matches":"Sete perguntas \u2192 suas tr\u00eas melhores combina\u00e7\u00f5es",
"The Top 100":"O Top 100",
"What churches launch first, in one shelf":"O que as igrejas lan\u00e7am primeiro, numa estante",
"Six-session studies on their own — $99":"Estudos de seis sess\u00f5es avulsos \u2014 $99",
"Assessment, Launch Planner, Reading Room, verse cards":"Avalia\u00e7\u00e3o, Planejador, Sala de leitura, cart\u00f5es de vers\u00edculos",
"Eight questions, scored — launch or build first?":"Oito perguntas, pontuadas: lan\u00e7ar ou construir antes?",
"Your kickoff Sunday → a dated six-week runway":"Seu domingo de abertura \u2192 uma pista de seis semanas com datas",
"How it works":"Como funciona",
"The full construct explained":"O modelo completo, explicado",
"For churches":"Para igrejas",
"What your team receives, objections answered":"O que sua equipe recebe, obje\u00e7\u00f5es respondidas",
"All Access from $49 · single campaigns from $199":"All Access a partir de $49 \u00b7 campanhas avulsas a partir de $199",
"Print-ready sample":"Amostra pronta para imprimir",
"Days 1–3 + Session 1, on one sheet":"Dias 1\u20133 + Sess\u00e3o 1, numa folha",
"The story, the process, the Studios":"A hist\u00f3ria, o processo, os Studios",
"Twenty-eight questions, answered plainly":"Vinte e oito perguntas, respondidas com clareza",
"Talk to us":"Fale conosco",
"hello@40daycampaigns.com — a person answers":"hello@40daycampaigns.com \u2014 uma pessoa responde",
"Your library, your launch plan, your progress":"Sua biblioteca, seu plano de lan\u00e7amento, seu progresso",
"Or start where most churches start.":"Ou comece onde a maioria das igrejas come\u00e7a.",
"If you got here from a link elsewhere on this site, please":"Se voc\u00ea chegou aqui por um link deste site, por favor",
"let us know":"avise a gente",
"so we can fix it.":"para corrigirmos.",
"“He leaves the ninety-nine…” — every page finds its way home. ·":"\u201cDeixa as noventa e nove\u2026\u201d: cada p\u00e1gina encontra o caminho de casa. \u00b7",
"Fifteen doors":"Quinze portas",
"Seven questions":"Sete perguntas",
"The most-launched shelf":"A estante mais lan\u00e7ada",
"Studies on their own":"Estudos avulsos",
"All free tools":"Todas as ferramentas gr\u00e1tis",
"Are we ready?":"Estamos prontos?",
"The construct":"O modelo",
"What you receive":"O que voc\u00ea recebe",
"Story · process · Studios":"Hist\u00f3ria \u00b7 processo \u00b7 Studios",
"Talk to a person":"Fale com uma pessoa",
"Read Day One free":"Leia o Dia Um gr\u00e1tis",
"Library & launch":"Biblioteca e lan\u00e7amento",
}
json.dump(PT, open('/home/claude/tr_pt_4.json','w'), ensure_ascii=False)
print("PT map 4:", len(PT), "pairs")
