import json
PT = {
"Fifteen doors. 1,252 journeys.":"Quinze portas. 1.252 jornadas.",
"1,252 finished campaigns":"1.252 campanhas prontas",
"Browse Campaigns — 40 Day Campaigns":"Explorar campanhas \u2014 40 Day Campaigns",
"The Library · Est. 2001":"A biblioteca \u00b7 desde 2001",
"The full campaign library.":"A biblioteca completa de campanhas.",
"1252 hand-curated campaigns in the Purpose Driven tradition, each one complete — daily devotional, small-group study, sermon outlines, and launch materials included.":"1252 campanhas na tradi\u00e7\u00e3o de Uma Vida com Prop\u00f3sitos, cada uma completa: devocional di\u00e1rio, estudo para pequenos grupos, esbo\u00e7os de serm\u00f5es e materiais de lan\u00e7amento inclu\u00eddos.",
"All themes":"Todos os temas","All channels":"Todos os canais","Families":"Fam\u00edlias","Financial Advisors":"Assessores financeiros","Estate Attorneys":"Advogados de sucess\u00f5es","Family Offices":"Family offices","Ministries &amp; Nonprofits":"Minist\u00e9rios e ONGs","Pastors":"Pastores","Business Leaders":"L\u00edderes de neg\u00f3cios","Students &amp; Young Adults":"Jovens e universit\u00e1rios","All audiences":"Todos os p\u00fablicos","All life events":"Todos os momentos de vida","All formats":"Todos os formatos",
"Staff favorites":"Favoritas da equipe","New this month":"Novas este m\u00eas","Recently ordered":"Pedidas recentemente","Featured":"Em destaque","Most popular":"Mais populares","Covers":"Capas",
"No campaigns match those filters.":"Nenhuma campanha corresponde a esses filtros.","Clear everything":"Limpar tudo","or try the":"ou experimente o",
"1252 hand-curated campaigns · 94 themes · 15 categories · NIV reading plan · KJV verses labeled ·":"1252 campanhas \u00b7 94 temas \u00b7 15 categorias \u00b7 Plano de leitura NVI \u00b7 Vers\u00edculos KJV sinalizados \u00b7",
"Say hello":"Fale conosco","Privacy":"Privacidade",
"Year-End Giving collection — short campaigns built for the giving season, ready for CPAs, advisors, and churches.":"Cole\u00e7\u00e3o de generosidade de fim de ano: campanhas curtas para a temporada de doar, prontas para contadores, assessores e igrejas.",
"Seasonal collection:":"Cole\u00e7\u00e3o sazonal:",
"That seasonal collection is coming soon — here is the full library in the meantime.":"Essa cole\u00e7\u00e3o sazonal chega em breve; enquanto isso, aqui est\u00e1 a biblioteca completa.",
"Staff favorites — hand-picked by the Lifetogether team for range, depth, and how well they land.":"Favoritas da equipe: escolhidas a dedo pela Lifetogether por variedade, profundidade e impacto.",
"New this month — the newest additions to the library, freshly built and ready to launch.":"Novas este m\u00eas: as adi\u00e7\u00f5es mais recentes da biblioteca, rec\u00e9m-constru\u00eddas e prontas para lan\u00e7ar.",
"Recently ordered — campaigns other churches have put on their calendars lately.":"Pedidas recentemente: campanhas que outras igrejas colocaram no calend\u00e1rio ultimamente.",
"Browse by Category — 40 Day Campaigns":"Navegar por categoria \u2014 40 Day Campaigns",
"The library, by category":"A biblioteca, por categoria",
"Every category opens with its ten strongest campaigns — the ones churches launch first — with the rest one tap deeper, grouped by theme.":"Cada categoria abre com suas dez campanhas mais fortes \u2014 as que as igrejas lan\u00e7am primeiro \u2014 e o resto a um toque de dist\u00e2ncia, agrupado por tema.",
"Or start from the very top.":"Ou comece pelo topo.",
"The one hundred highest-ranked journeys in the whole library, in one shelf.":"As cem jornadas mais bem classificadas de toda a biblioteca, em uma \u00fanica estante.",
"Open the Top 100 →":"Abrir o Top 100 \u2192",
"© 2026 40daycampaigns.com · A Lifetogether ministry":"\u00a9 2026 40daycampaigns.com \u00b7 Um minist\u00e9rio Lifetogether",
"15 categories · 94 themes · 1252 campaigns — every one finished ·":"15 categorias \u00b7 94 temas \u00b7 1252 campanhas, cada uma pronta \u00b7",
"Campaign — 40 Day Campaigns":"Campanha \u2014 40 Day Campaigns",
"one campaign · yours forever":"uma campanha \u00b7 sua para sempre",
"✓ Instant digital delivery — begin today":"\u2713 Entrega digital instant\u00e2nea \u2014 comece hoje",
"Add to cart":"Adicionar ao carrinho","Buy now":"Comprar agora",
"Open Day One in the Reading Room — free":"Abra o Dia Um na Sala de leitura \u2014 gr\u00e1tis",
"Plan your launch →":"Planeje seu lan\u00e7amento \u2192",
"Small-Group Edition only — $99":"S\u00f3 a edi\u00e7\u00e3o para pequenos grupos \u2014 $99",
"Order printed copies":"Pedir c\u00f3pias impressas","Printed copies, to your door.":"C\u00f3pias impressas, at\u00e9 a sua porta.",
"Pick a quantity — print-on-demand fulfillment (Ingram Spark) connects at launch. Click order, and they show up at the church.":"Escolha a quantidade: a impress\u00e3o sob demanda (IngramSpark) conecta no lan\u00e7amento. Fa\u00e7a o pedido e elas chegam \u00e0 igreja.",
"Select a quantity for your quote":"Selecione a quantidade para a cota\u00e7\u00e3o","Order — connects at launch":"Pedir \u2014 conecta no lan\u00e7amento",
"Or get every campaign in the library with":"Ou tenha todas as campanhas da biblioteca com",
"— from $49/mo by church size, with a 40% church-plant discount.":"\u2014 a partir de $49/m\u00eas pelo tamanho da igreja, com 40% de desconto para plantar igrejas.",
"Complete daily devotional — every day fully written":"Devocional di\u00e1rio completo \u2014 cada dia totalmente escrito",
"6-session small-group study with leader notes":"Estudo de 6 sess\u00f5es para pequenos grupos com notas para o l\u00edder",
"6 sermon outlines + full launch kit":"6 esbo\u00e7os de serm\u00f5es + kit de lan\u00e7amento completo",
"Youth &amp; children's editions for every week":"Edi\u00e7\u00f5es para jovens e crian\u00e7as toda semana",
"All sixteen formats included — book, course, podcast, video, family guide, and more":"Os dezesseis formatos inclu\u00eddos: livro, curso, podcast, v\u00eddeo, guia da fam\u00edlia e mais",
"Congregation-wide print rights included":"Direitos de impress\u00e3o para toda a congrega\u00e7\u00e3o inclu\u00eddos",
"Open the full documents":"Abrir os documentos completos","More like this":"Mais como esta","Flagship ·":"Principal \u00b7","A Family Journey ·":"Uma jornada da fam\u00edlia \u00b7",
"A complete, ready-to-launch campaign in the":"Uma campanha completa e pronta para lan\u00e7ar na",
"Anchor scripture:":"Escritura \u00e2ncora:",
"A complete seven-day experience — kickoff Sunday to Celebration Sunday.":"Uma experi\u00eancia completa de sete dias: do domingo de abertura ao Domingo de Celebra\u00e7\u00e3o.",
"Three to six weeks — choose the length that fits the season.":"De tr\u00eas a seis semanas: escolha a dura\u00e7\u00e3o que combina com a temporada.",
"Small-Group Edition only":"S\u00f3 edi\u00e7\u00e3o para pequenos grupos","Leader Kit":"Kit do l\u00edder","Primary topic":"Tema principal","Best season":"Melhor temporada","Any season":"Qualquer temporada","Every audience":"Todo p\u00fablico","Launch complexity":"Complexidade de lan\u00e7amento","Speed to launch":"Velocidade de lan\u00e7amento","Begin this Sunday":"Comece neste domingo","Six-week runway":"Pista de seis semanas","Choose a week":"Escolha uma semana",
"The room does the growing — four movements, one practice.":"A sala faz o crescimento: quatro movimentos, uma pr\u00e1tica.",
"A trade-paperback reading edition with chapters and epilogue":"Uma edi\u00e7\u00e3o de leitura em formato livro, com cap\u00edtulos e ep\u00edlogo",
"A one-week on-ramp: kickoff to Celebration Sunday":"Uma rampa de uma semana: da abertura ao Domingo de Celebra\u00e7\u00e3o",
"Three focused weeks for a season of momentum":"Tr\u00eas semanas focadas para uma temporada de impulso",
"A full month of daily formation":"Um m\u00eas inteiro de forma\u00e7\u00e3o di\u00e1ria",
"The classic churchwide journey":"A jornada cl\u00e1ssica para toda a igreja",
"Membership Course":"Curso de membresia",
"Modules, objectives, self-checks, and a completion track":"M\u00f3dulos, objetivos, autoavalia\u00e7\u00f5es e trilha de conclus\u00e3o",
"Small Group Curriculum":"Curr\u00edculo para pequenos grupos",
"Six sessions with questions, practices, and leader cues":"Seis sess\u00f5es com perguntas, pr\u00e1ticas e orienta\u00e7\u00f5es para o l\u00edder",
"Leader Training":"Treinamento de l\u00edderes",
"A facilitator course that trains your hosts before launch":"Um curso que treina seus anfitri\u00f5es antes do lan\u00e7amento",
"Family Guide":"Guia da fam\u00edlia",
"Table talk, activities, prayers, and bedtime blessings":"Conversa \u00e0 mesa, atividades, ora\u00e7\u00f5es e b\u00ean\u00e7\u00e3os de boa noite",
"Youth Edition":"Edi\u00e7\u00e3o jovem",
"The same journey, translated for students":"A mesma jornada, traduzida para estudantes",
"Big ideas, activities, and simple prayers for kids":"Grandes ideias, atividades e ora\u00e7\u00f5es simples para crian\u00e7as",
"Podcast Series":"S\u00e9rie de podcast",
"Episode scripts with cold opens, segments, and outros":"Roteiros por epis\u00f3dio com abertura, segmentos e encerramento",
"Video Course":"Curso em v\u00eddeo",
"Delivery-ready teaching scripts, beat by beat":"Roteiros de ensino prontos para gravar, passo a passo",
"Upload-ready book spec with back-cover copy":"Especifica\u00e7\u00e3o de livro pronta para envio, com texto de contracapa",
"Digital Library":"Biblioteca digital",
"Every file, one bundle, one license":"Cada arquivo, um pacote, uma licen\u00e7a",
"Pricing — 40 Day Campaigns":"Pre\u00e7os \u2014 40 Day Campaigns",
"Own one journey, or open the whole library.":"Tenha uma jornada, ou abra a biblioteca inteira.",
"Two honest prices. No seats, no per-head math, no surprise line items — one license always covers your entire congregation.":"Dois pre\u00e7os honestos. Sem assentos, sem conta por pessoa, sem surpresas: uma licen\u00e7a sempre cobre toda a sua congrega\u00e7\u00e3o.",
"Your price in ten seconds":"Seu pre\u00e7o em dez segundos",
"What All Access costs your church":"Quanto o All Access custa para a sua igreja",
"Slide to your average weekend attendance. Every tier includes the entire 1252-campaign library, editable source files, and new releases as they ship.":"Deslize at\u00e9 sua frequ\u00eancia m\u00e9dia de fim de semana. Cada n\u00edvel inclui a biblioteca completa de 1252 campanhas, arquivos edit\u00e1veis e os novos lan\u00e7amentos.",
"Average weekend attendance":"Frequ\u00eancia m\u00e9dia de fim de semana",
"We're a church plant (under 3 years) or under 50 in attendance — apply the 40% discount, code":"Somos uma igreja plantada (menos de 3 anos) ou com menos de 50 pessoas: aplique 40% de desconto com o c\u00f3digo",
"Churches 100–500":"Igrejas de 100 a 500",
"Billed monthly · cancel anytime · all 1252 campaigns":"Cobran\u00e7a mensal \u00b7 cancele quando quiser \u00b7 as 1252 campanhas",
"Get All Access →":"Assinar o All Access \u2192",
"Prefer one journey? A single campaign is $199 flat — any size church.":"Prefere uma \u00fanica jornada? Uma campanha custa $199 fixos, para igreja de qualquer tamanho.",
"The two doors":"As duas portas","Side by side, in full.":"Lado a lado, por inteiro.",
"Single Campaign":"Campanha \u00fanica","one-time · yours forever · any size church":"pagamento \u00fanico \u00b7 sua para sempre \u00b7 igreja de qualquer tamanho",
"Any one of the 1252 campaigns, complete — all sixteen formats":"Qualquer uma das 1252 campanhas, completa: os dezesseis formatos",
"Small-Group Edition only — $99, when groups are the whole plan":"S\u00f3 a edi\u00e7\u00e3o de grupos \u2014 $99, quando os grupos s\u00e3o todo o plano",
"7, 21, 30, 40-day and 6-week versions of the same journey":"Vers\u00f5es de 7, 21, 30 e 40 dias e de 6 semanas da mesma jornada",
"Congregation-wide license with print rights included":"Licen\u00e7a para toda a congrega\u00e7\u00e3o com direitos de impress\u00e3o",
"Instant digital delivery — card, Apple&nbsp;Pay, PayPal, or Net-30 church invoice":"Entrega digital instant\u00e2nea: cart\u00e3o, Apple&nbsp;Pay, PayPal ou fatura Net-30 para igrejas",
"The Reading Room for every member, offline included":"A Sala de leitura para cada membro, at\u00e9 offline",
"Choose a campaign →":"Escolher uma campanha \u2192",
"by weekend attendance · cancel anytime":"pela frequ\u00eancia de fim de semana \u00b7 cancele quando quiser",
"Every campaign in the library — all 1252, all seasons":"Todas as campanhas da biblioteca: as 1252, todas as temporadas",
"Switch or run multiple campaigns anytime, no per-title fees":"Troque ou rode v\u00e1rias campanhas quando quiser, sem taxa por t\u00edtulo",
"Editable, print-ready source files for your bulletin and brand":"Arquivos edit\u00e1veis e prontos para impress\u00e3o, para seu boletim e sua marca",
"New campaigns included as they release":"Campanhas novas inclu\u00eddas assim que lan\u00e7adas",
"Church plants &amp; churches under 50: 40% off with code PLANT40":"Igrejas plantadas e com menos de 50: 40% de desconto com o c\u00f3digo PLANT40",
"No fine print, just plain print":"Sem letras mi\u00fadas, s\u00f3 letras claras",
"Licensing, plainly.":"A licen\u00e7a, \u00e0s claras.",
"One license, whole church":"Uma licen\u00e7a, a igreja inteira",
"Print it, email it, hand it out at the door. Your license covers every member of your congregation — including youth and children's editions.":"Imprima, envie por e-mail, distribua na porta. Sua licen\u00e7a cobre cada membro da congrega\u00e7\u00e3o, incluindo as edi\u00e7\u00f5es para jovens e crian\u00e7as.",
"Delivery is instant":"A entrega \u00e9 instant\u00e2nea",
"Every edition downloads the moment you check out, and every member can read daily in the Reading Room — on any device, even offline.":"Cada edi\u00e7\u00e3o baixa no momento do pagamento, e cada membro pode ler diariamente na Sala de leitura, em qualquer aparelho, at\u00e9 offline.",
"Invoicing welcome":"Fatura bem-vinda",
"Choose \"Invoice my church\" at checkout for Net-30 terms with an optional PO number. Downloads unlock immediately.":"Escolha \u201cFaturar minha igreja\u201d no pagamento, com prazo Net-30 e n\u00famero de pedido opcional. Os downloads liberam na hora.",
"Attendance, on your word":"Frequ\u00eancia, na sua palavra",
"All Access tiers go by average weekend attendance. We take your word for it — no audits, no forms.":"Os n\u00edveis do All Access seguem a frequ\u00eancia m\u00e9dia. Aceitamos a sua palavra: sem auditorias, sem formul\u00e1rios.",
"Plants pay less":"Igrejas plantadas pagam menos",
"Under 3 years old, or under 50 on Sundays? Code":"Menos de 3 anos, ou menos de 50 aos domingos? O c\u00f3digo",
"takes 40% off any purchase at checkout. No application.":"d\u00e1 40% de desconto em qualquer compra. Sem inscri\u00e7\u00e3o.",
"Can we run more than one campaign a year?":"Podemos rodar mais de uma campanha por ano?",
"Most All Access churches run two to four — a churchwide 40-day in fall, a shorter 21-day in the new year, plus targeted journeys for marriage or finance ministries. The whole library stays open; run what the season needs.":"A maioria das igrejas com All Access roda de duas a quatro: uma de 40 dias no segundo semestre, uma de 21 no come\u00e7o do ano, mais jornadas espec\u00edficas para casamento ou finan\u00e7as. A biblioteca fica aberta; rode o que a temporada pedir.",
"What if we outgrow our tier?":"E se ultrapassarmos nosso n\u00edvel?",
"Congratulations — just move up at your next billing month. Tiers exist so small churches never subsidize large ones, not to catch anyone out.":"Parab\u00e9ns \u2014 \u00e9 s\u00f3 subir de n\u00edvel no pr\u00f3ximo m\u00eas de cobran\u00e7a. Os n\u00edveis existem para que igrejas pequenas nunca subsidiem as grandes, n\u00e3o para pegar ningu\u00e9m.",
"Is there a way to try before buying?":"D\u00e1 para experimentar antes de comprar?",
"Always. Day One of every campaign is free in the Reading Room, and a printable three-day sample is one click from any campaign page.":"Sempre. O Dia Um de cada campanha \u00e9 gr\u00e1tis na Sala de leitura, e uma amostra imprim\u00edvel de tr\u00eas dias est\u00e1 a um clique em qualquer p\u00e1gina de campanha.",
"Find your next campaign":"Encontre sua pr\u00f3xima campanha","Find your three matches →":"Encontre suas tr\u00eas combina\u00e7\u00f5es \u2192","Read Day One free":"Leia o Dia Um gr\u00e1tis",
"Which option makes sense for you":"Qual op\u00e7\u00e3o faz sentido para voc\u00ea",
"Running one campaign this season?":"Vai rodar uma campanha nesta temporada?",
"A single campaign starting at $199 covers your whole congregation, all sixteen formats, with print rights included and no expiration. If small groups are the whole plan, the Small-Group Edition alone is $99.":"Uma campanha \u00fanica a partir de $199 cobre toda a congrega\u00e7\u00e3o, com os dezesseis formatos, direitos de impress\u00e3o e sem validade. Se pequenos grupos s\u00e3o todo o plano, a edi\u00e7\u00e3o de grupos sozinha custa $99.",
"Running two or more campaigns a year?":"Duas ou mais campanhas por ano?",
"Church plant?":"Igreja plantada?",
"Ask about the PLANT40 rate — a 40% discount built for churches in their first few years.":"Pergunte pela tarifa PLANT40: 40% de desconto pensado para igrejas nos primeiros anos.",
"$199 single · All Access $49–$249/mo · PLANT40 saves 40% ·":"$199 \u00fanica \u00b7 All Access $49\u2013$249/m\u00eas \u00b7 PLANT40 economiza 40% \u00b7",
"Say Hello — 40 Day Campaigns":"Fale conosco \u2014 40 Day Campaigns",
"Say hello.":"Fale conosco.",
"A real person reads every message — usually the same day. Pastors planning a launch go to the front of the line.":"Uma pessoa de verdade l\u00ea cada mensagem, normalmente no mesmo dia. Pastores planejando um lan\u00e7amento v\u00e3o para a frente da fila.",
"Good reasons to write":"Bons motivos para escrever","Planning a launch":"Planejando um lan\u00e7amento",
"Tell us your kickoff Sunday and church size — we'll sanity-check the runway with you.":"Conte seu domingo de abertura e o tamanho da igreja; revisamos o plano de decolagem com voc\u00ea.",
"Licensing questions":"D\u00favidas de licen\u00e7a",
"Multi-site, denominations, ministries beyond the local church — ask before you guess.":"Multissede, denomina\u00e7\u00f5es, minist\u00e9rios al\u00e9m da igreja local: pergunte antes de supor.",
"Something looks broken":"Algo parece quebrado",
"Tell us the page and the device. We fix fast and say thank you.":"Diga a p\u00e1gina e o aparelho. Corrigimos r\u00e1pido e agradecemos.",
"Prefer email?":"Prefere e-mail?","Your name":"Seu nome","What's this about?":"Sobre o que \u00e9?","Licensing question":"D\u00favida de licen\u00e7a","Something's broken":"Algo quebrou","Just saying hello":"S\u00f3 dizendo oi","Your message":"Sua mensagem","Send it →":"Enviar \u2192","Received.":"Recebido.",
"Thank you — a real person will reply, usually the same day.":"Obrigado \u2014 uma pessoa de verdade vai responder, normalmente no mesmo dia.",
"Meanwhile,":"Enquanto isso,","Day One is free":"o Dia Um \u00e9 gr\u00e1tis","if you'd like a taste.":"se quiser provar.",
"Get All Access — 40 Day Campaigns":"Assine o All Access \u2014 40 Day Campaigns",
"Open the whole library for your church.":"Abra a biblioteca inteira para a sua igreja.",
"All 1252 campaigns, always":"As 1252 campanhas, sempre",
"Run a churchwide 40-day in the fall, a 21-day in January, a marriage journey in spring — switch anytime, no per-title fees.":"Rode uma de 40 dias no segundo semestre, uma de 21 em janeiro, uma jornada de casamento na primavera; troque quando quiser, sem taxa por t\u00edtulo.",
"Editable source files":"Arquivos edit\u00e1veis",
"Print-ready and brandable: your logo on the devotional cover, your service times on the bulletin insert.":"Prontos para imprimir e personalizar: seu logo na capa do devocional, seus hor\u00e1rios no encarte do boletim.",
"Every tool included":"Todas as ferramentas inclu\u00eddas",
"The Reading Room for every member (offline included), the Launch Planner with calendar export, verse cards, samples — all of it.":"A Sala de leitura para cada membro (at\u00e9 offline), o Planejador com exporta\u00e7\u00e3o de calend\u00e1rio, cart\u00f5es de vers\u00edculos, amostras: tudo.",
"New releases as they ship":"Novos lan\u00e7amentos assim que saem",
"The library grows; your price doesn't change mid-cycle.":"A biblioteca cresce; seu pre\u00e7o n\u00e3o muda no meio do ciclo.",
"Cancel anytime":"Cancele quando quiser",
"Month to month, by attendance tier, on your word — no audits, no contracts, no exit calls.":"M\u00eas a m\u00eas, por n\u00edvel de frequ\u00eancia, na sua palavra: sem auditorias, sem contratos, sem liga\u00e7\u00e3o de cancelamento.",
"under 100":"menos de 100","Not sure which tier?":"N\u00e3o sabe qual n\u00edvel?","The calculator answers in ten seconds →":"A calculadora responde em dez segundos \u2192",
"Start All Access":"Come\u00e7ar o All Access",
"Demo signup — no payment is taken today. Billing connects through Stripe at launch.":"Cadastro de demonstra\u00e7\u00e3o: nada \u00e9 cobrado hoje. A cobran\u00e7a conecta com o Stripe no lan\u00e7amento.",
"Church name":"Nome da igreja","Under 100 — $49/mo":"Menos de 100 \u2014 $49/m\u00eas","100–500 — $99/mo":"100\u2013500 \u2014 $99/m\u00eas","500–1,000 — $149/mo":"500\u20131.000 \u2014 $149/m\u00eas","1,000–2,000 — $199/mo":"1.000\u20132.000 \u2014 $199/m\u00eas","2,000+ — $249/mo":"2.000+ \u2014 $249/m\u00eas",
"Your email":"Seu e-mail","Open the library →":"Abrir a biblioteca \u2192",
"Church plant or under 50? Code":"Igreja plantada ou menos de 50? O c\u00f3digo","takes 40% off at checkout.":"d\u00e1 40% de desconto no pagamento.",
"Every tier: all 1252 campaigns · cancel anytime.":"Cada n\u00edvel: as 1252 campanhas \u00b7 cancele quando quiser.",
"Welcome — the library is open.":"Bem-vindo \u2014 a biblioteca est\u00e1 aberta.",
"Create your sign-in to keep your journey, launches, and downloads in one place.":"Crie seu acesso para guardar sua jornada, lan\u00e7amentos e downloads em um s\u00f3 lugar.",
"Create my account →":"Criar minha conta \u2192","I already have an account":"J\u00e1 tenho uma conta",
"All Access $49–$249/mo · PLANT40 saves 40% · cancel anytime ·":"All Access $49\u2013$249/m\u00eas \u00b7 PLANT40 economiza 40% \u00b7 cancele quando quiser \u00b7",
"Secure Checkout — 40 Day Campaigns":"Pagamento seguro \u2014 40 Day Campaigns",
"Secure checkout":"Pagamento seguro","return to cart":"voltar ao carrinho","256-bit encrypted · demo mode":"criptografia de 256 bits \u00b7 modo demo",
"Billing contact":"Contato de cobran\u00e7a","Full name":"Nome completo","Church or organization":"Igreja ou organiza\u00e7\u00e3o","Email for delivery &amp; receipt":"E-mail para entrega e recibo",
"Payment method":"Forma de pagamento","or pay another way":"ou pague de outro jeito","Credit or debit card":"Cart\u00e3o de cr\u00e9dito ou d\u00e9bito",
"All major cards accepted. Instant digital delivery.":"Aceitamos os principais cart\u00f5es. Entrega digital instant\u00e2nea.",
"Name on card":"Nome no cart\u00e3o","Card number":"N\u00famero do cart\u00e3o","Expiry (MM/YY)":"Validade (MM/AA)","Security code":"C\u00f3digo de seguran\u00e7a","Billing ZIP":"CEP de cobran\u00e7a",
"Demo checkout: card details are validated in your browser only and are never stored or transmitted — only the card brand and last four digits appear on your receipt. Live payments connect through Stripe at launch.":"Pagamento de demonstra\u00e7\u00e3o: os dados do cart\u00e3o s\u00e3o validados s\u00f3 no seu navegador e nunca s\u00e3o armazenados nem transmitidos; no recibo aparecem apenas a bandeira e os \u00faltimos quatro d\u00edgitos. Os pagamentos reais conectam com o Stripe no lan\u00e7amento.",
"Invoice my church (Net-30)":"Faturar minha igreja (Net-30)",
"We'll email a Net-30 invoice to your billing contact. Downloads unlock immediately.":"Enviaremos uma fatura Net-30 ao seu contato de cobran\u00e7a. Os downloads liberam na hora.",
"PO number":"N\u00famero do pedido (PO)","Review your order":"Revise seu pedido",
"By placing this order you agree to the":"Ao fazer este pedido voc\u00ea concorda com os","Terms of Use":"Termos de uso","Privacy Policy":"Pol\u00edtica de privacidade",
"Place your order":"Fazer o pedido",
"By placing your order you agree to the campaign license terms: one license covers your entire congregation, with print rights included.":"Ao fazer o pedido voc\u00ea aceita os termos de licen\u00e7a: uma licen\u00e7a cobre toda a congrega\u00e7\u00e3o, com direitos de impress\u00e3o inclu\u00eddos.",
"Order summary":"Resumo do pedido","Delivery":"Entrega","Instant · digital":"Instant\u00e2nea \u00b7 digital",
"Confirm with Passcode":"Confirmar com c\u00f3digo",
"Demo of the Apple&nbsp;Pay sheet — no wallet is charged. Live Apple&nbsp;Pay arrives with Stripe at launch.":"Demonstra\u00e7\u00e3o do Apple&nbsp;Pay: nenhuma carteira \u00e9 cobrada. O Apple&nbsp;Pay real chega com o Stripe no lan\u00e7amento.",
"Merchant":"Loja","PayPal account email":"E-mail da conta PayPal",
"Demo of PayPal checkout — nothing is charged. Live PayPal arrives at launch.":"Demonstra\u00e7\u00e3o do PayPal: nada \u00e9 cobrado. O PayPal real chega no lan\u00e7amento.",
"Payment approved":"Pagamento aprovado",
"Please add your name for the receipt.":"Adicione seu nome para o recibo.",
"Please add a valid delivery email.":"Adicione um e-mail de entrega v\u00e1lido.",
"That card looks expired — please use a current card.":"Esse cart\u00e3o parece vencido; use um atual.",
"The security code should be":"O c\u00f3digo de seguran\u00e7a deve ter",
"Please add the name on the card.":"Adicione o nome que aparece no cart\u00e3o.",
"Add a delivery email for your receipt, then tap the wallet button again.":"Adicione um e-mail de entrega para o recibo e toque de novo no bot\u00e3o da carteira.",
"Your Cart — 40 Day Campaigns":"Seu carrinho \u2014 40 Day Campaigns","Your cart":"Seu carrinho",
"Every campaign is a one-time $199 license for your whole congregation — devotional, group study, sermon outlines, youth &amp; children's editions, and the leader &amp; launch kits.":"Cada campanha \u00e9 uma licen\u00e7a \u00fanica de $199 para toda a congrega\u00e7\u00e3o: devocional, estudo de grupos, esbo\u00e7os de serm\u00f5es, edi\u00e7\u00f5es para jovens e crian\u00e7as, e os kits do l\u00edder e de lan\u00e7amento.",
"Saved for later":"Salvo para depois","Promo code":"C\u00f3digo promocional","Proceed to checkout":"Ir para o pagamento",
"🔒 Secure demo checkout · instant digital delivery":"\ud83d\udd12 Pagamento demo seguro \u00b7 entrega digital instant\u00e2nea",
"Buying more than two?":"Vai comprar mais de duas?",
"covers the entire 1252-campaign library from $49/mo by church size — church plants save 40% with code":"cobre a biblioteca inteira de 1252 campanhas a partir de $49/m\u00eas pelo tamanho da igreja; igrejas plantadas economizam 40% com o c\u00f3digo",
"Order Confirmed — 40 Day Campaigns":"Pedido confirmado \u2014 40 Day Campaigns","Order confirmed":"Pedido confirmado","Thank you!":"Obrigado!",
"Your campaign licenses are active. Download any format below — each opens the complete curriculum, ready to print or save as PDF.":"Suas licen\u00e7as de campanha est\u00e3o ativas. Baixe qualquer formato abaixo: cada um abre o curr\u00edculo completo, pronto para imprimir ou salvar em PDF.",
"What’s next:":"Pr\u00f3ximos passos:",
"pick your launch Sunday, recruit hosts three weeks out, and start everyone on Day 1 together. The launch kit is included at the end of every daily-format download. Questions?":"escolha seu domingo de lan\u00e7amento, recrute anfitri\u00f5es com tr\u00eas semanas de anteced\u00eancia e comecem todos juntos no Dia 1. O kit de lan\u00e7amento vem no fim de cada download de formato di\u00e1rio. D\u00favidas?",
"We’re here.":"Estamos aqui.","View my account":"Ver minha conta","🖨 Print receipt":"\ud83d\udda8 Imprimir recibo","Begin Day One →":"Come\u00e7ar o Dia Um \u2192","Browse more campaigns":"Ver mais campanhas",
"How It Works":"Como funciona","For Churches":"Para igrejas",
"© 2026 40daycampaigns.com · A Lifetogether ministry · Built in the Purpose Driven tradition":"\u00a9 2026 40daycampaigns.com \u00b7 Um minist\u00e9rio Lifetogether \u00b7 Na tradi\u00e7\u00e3o de Uma Vida com Prop\u00f3sitos",
"No recent order found":"Nenhum pedido recente encontrado","Thank you,":"Obrigado,",
}
json.dump(PT, open('/home/claude/tr_pt_2.json','w'), ensure_ascii=False)
print("PT map:", len(PT), "pairs")
