import json
PT = {
"So we built five hundred thirty-three of them. Finished.":"Ent\u00e3o constru\u00edmos 1.252. Prontas.",
"Questions &amp; Answers — 40 Day Campaigns":"Perguntas e respostas \u2014 40 Day Campaigns",
"Questions &amp; answers":"Perguntas e respostas",
"Everything pastors ask us. Answered straight.":"Tudo o que os pastores nos perguntam. Respondido sem rodeios.",
"No hedging, no \"it depends\" without the depends. If your question isn't here, a person reads every message at":"Sem evasivas, sem \u201cdepende\u201d sem o depende. Se sua pergunta n\u00e3o est\u00e1 aqui, uma pessoa l\u00ea cada mensagem em",
"The Content":"O conte\u00fado","Running It":"Como rodar","Licensing &amp; Money":"Licen\u00e7a e dinheiro","The Tools":"As ferramentas",
"Who actually writes these campaigns?":"Quem realmente escreve essas campanhas?",
"Lifetogether — the team Brett Eastman founded in 2001 out of the Saddleback small-groups movement. Every campaign is hand-curated against five":"Lifetogether: a equipe que Brett Eastman fundou em 2001 a partir do movimento de pequenos grupos de Saddleback. Cada campanha \u00e9 cuidada \u00e0 m\u00e3o contra cinco",
"craft standards":"padr\u00f5es de of\u00edcio",
": a distinct angle, a scriptural backbone, a conviction-not-condemnation voice, first-time-host readiness, and finished-means-finished completeness.":": um \u00e2ngulo distinto, uma espinha b\u00edblica, uma voz de convic\u00e7\u00e3o sem condena\u00e7\u00e3o, pronta para anfitri\u00f5es de primeira viagem e conclu\u00edda de verdade.",
"What Bible translation do you use?":"Qual tradu\u00e7\u00e3o da B\u00edblia voc\u00eas usam?",
", with the weekly memory verse presented for households to share. If your church preaches from a different translation, the sermon outlines reference passages, not printed text — your pulpit Bible is your pulpit Bible.":", com o vers\u00edculo semanal apresentado para as casas compartilharem. Se sua igreja prega com outra tradu\u00e7\u00e3o, os esbo\u00e7os citam refer\u00eancias, n\u00e3o texto impresso: sua B\u00edblia de p\u00falpito continua sendo sua B\u00edblia de p\u00falpito.",
"How long is a daily reading, honestly?":"Quanto dura uma leitura di\u00e1ria, honestamente?",
"Between 413 and 557 words — about three to four minutes — plus a short prayer, one reflection question, and one concrete step. Long enough to matter, short enough to survive a Tuesday.":"Entre 413 e 557 palavras \u2014 uns tr\u00eas a quatro minutos \u2014 mais uma ora\u00e7\u00e3o breve, uma pergunta de reflex\u00e3o e um passo concreto. Longo o bastante para importar, curto o bastante para sobreviver a uma ter\u00e7a-feira.",
"Will campaign #4 feel like campaign #1?":"A campanha #4 vai parecer a #1?",
"No — that's the first craft standard. Each of the 1252 campaigns carries its own governing question and metaphor, even within the same theme. Your church can run stewardship journeys three falls in a row without déjà vu.":"N\u00e3o: esse \u00e9 o primeiro padr\u00e3o de of\u00edcio. Cada uma das 1252 campanhas carrega sua pr\u00f3pria pergunta e met\u00e1fora, mesmo dentro do mesmo tema. Sua igreja pode rodar jornadas de mordomia tr\u00eas anos seguidos sem d\u00e9j\u00e0 vu.",
"How do sensitive topics get handled?":"Como os temas sens\u00edveis s\u00e3o tratados?",
"Can we preview before we buy?":"Podemos ver antes de comprar?",
"Always.":"Sempre.",
"Day One of every campaign is free":"O Dia Um de cada campanha \u00e9 gr\u00e1tis",
"in the Reading Room, and every campaign page offers a printable three-day sample plus the full Session 1, all six sermon outlines, and week one of the youth and kids editions.":"na Sala de leitura, e cada p\u00e1gina oferece uma amostra imprim\u00edvel de tr\u00eas dias mais a Sess\u00e3o 1 completa, os seis esbo\u00e7os e a semana um das edi\u00e7\u00f5es jovem e infantil.",
"How much work is this for our senior pastor, really?":"Quanto trabalho isso d\u00e1 para o nosso pastor titular, de verdade?",
"ten hours across twelve weeks":"dez horas em doze semanas",
": cast the vision twice, preach six sermons from provided outlines, commission the hosts, celebrate at the end. The":": apresentar a vis\u00e3o duas vezes, pregar seis serm\u00f5es a partir dos esbo\u00e7os, comissionar os anfitri\u00f5es e celebrar no fim. O",
"honest ledger":"livro-raz\u00e3o honesto",
"lists it line by line — along with everything that's already done.":"detalha linha por linha, junto com tudo o que j\u00e1 est\u00e1 pronto.",
"We've never done groups. Can our people host?":"Nunca tivemos grupos. Nossa gente consegue ser anfitri\u00e3?",
"Yes — the sessions assume the host has never led anything. Four movements, printed questions, a one-hour orientation the kit runs for you, and a leader guide with the midweek text that keeps rooms warm. The questions do the teaching.":"Sim: as sess\u00f5es assumem que o anfitri\u00e3o nunca liderou nada. Quatro movimentos, perguntas impressas, uma orienta\u00e7\u00e3o de uma hora que o kit conduz por voc\u00ea, e um guia com a mensagem do meio da semana que mant\u00e9m as salas aquecidas. As perguntas fazem o ensino.",
"How far ahead should we start?":"Com quanta anteced\u00eancia devemos come\u00e7ar?",
"Six weeks. Open the":"Seis semanas. Abra o",
"Launch Planner":"Planejador de lan\u00e7amento",
", pick your kickoff Sunday, and it builds the dated runway — recruiting, orientation, sign-up Sunday, group formation — and drops all of it into your calendar as an .ics file.":", escolha seu domingo de abertura, e ele monta a pista com datas \u2014 recrutamento, orienta\u00e7\u00e3o, domingo de inscri\u00e7\u00e3o, forma\u00e7\u00e3o de grupos \u2014 e coloca tudo no seu calend\u00e1rio como arquivo .ics.",
"What about our youth and children during the campaign?":"E nossos jovens e crian\u00e7as durante a campanha?",
"Which length should we choose?":"Qual dura\u00e7\u00e3o devemos escolher?",
"Forty days for a churchwide movement; 21 or 30 days for habit-forming seasons; 7 days for prayer weeks and staff resets; 6-week for group-first churches. Every campaign composes cleanly at all five lengths —":"Quarenta dias para um movimento de toda a igreja; 21 ou 30 para temporadas de formar h\u00e1bitos; 7 para semanas de ora\u00e7\u00e3o e reinis\u00edcios de equipe; 6 semanas para igrejas centradas em grupos. Cada campanha se comp\u00f5e limpa nas cinco dura\u00e7\u00f5es \u2014",
"here's the guide":"aqui est\u00e1 o guia",
"What exactly does $199 buy?":"O que exatamente os $199 compram?",
"One campaign, complete and forever: all sixteen formats, all five lengths, and a congregation-wide license with print rights. No per-head math, no seat counts — a church of 40 and a church of 4,000 pay the same $199.":"Uma campanha, completa e para sempre: os dezesseis formatos, as cinco dura\u00e7\u00f5es e uma licen\u00e7a para toda a congrega\u00e7\u00e3o com direitos de impress\u00e3o. Sem conta por pessoa: uma igreja de 40 e uma de 4.000 pagam os mesmos $199.",
"How does All Access pricing work?":"Como funciona o pre\u00e7o do All Access?",
"By average weekend attendance, from $49 to $249 per month —":"Pela frequ\u00eancia m\u00e9dia de fim de semana, de $49 a $249 por m\u00eas \u2014",
"the calculator":"a calculadora",
"shows your number in ten seconds. Every tier opens the entire 1252-campaign library with editable source files and new releases included. We take your word on attendance; no audits.":"mostra seu n\u00famero em dez segundos. Cada n\u00edvel abre a biblioteca completa de 1252 campanhas com arquivos edit\u00e1veis e novos lan\u00e7amentos. Aceitamos sua palavra na frequ\u00eancia; sem auditorias.",
"Do you discount for church plants?":"Tem desconto para igrejas plantadas?",
"Forty percent, on anything, with code":"Quarenta por cento, em tudo, com o c\u00f3digo",
"at checkout — for plants under three years old or churches under fifty. No application, no phone call, no proof required.":"no pagamento, para igrejas com menos de tr\u00eas anos ou menos de cinquenta pessoas. Sem inscri\u00e7\u00e3o, sem liga\u00e7\u00e3o, sem comprova\u00e7\u00e3o.",
"Can our church pay by invoice?":"Nossa igreja pode pagar por fatura?",
"Yes. Choose":"Sim. Escolha",
"\"Invoice my church\"":"\u201cFaturar minha igreja\u201d",
"at checkout for Net-30 terms with an optional PO number. Downloads unlock immediately; the invoice follows by email. Cards, Apple&nbsp;Pay, and PayPal work too.":"no pagamento, com prazo Net-30 e n\u00famero de pedido opcional. Os downloads liberam na hora; a fatura segue por e-mail. Cart\u00f5es, Apple&nbsp;Pay e PayPal tamb\u00e9m funcionam.",
"Can we edit the materials?":"Podemos editar os materiais?",
"All Access includes editable, print-ready source files — drop in your logo, adjust the bulletin insert, match your brand. Single-campaign licenses include print-ready PDFs of every edition.":"O All Access inclui arquivos edit\u00e1veis prontos para impress\u00e3o: coloque seu logo, ajuste o encarte do boletim, iguale sua marca. Licen\u00e7as de campanha \u00fanica incluem PDFs prontos de cada edi\u00e7\u00e3o.",
"Can our people read on their phones?":"Nossa gente pode ler no celular?",
"Every campaign opens in the":"Cada campanha abre na",
"— a distraction-free daily reader with progress tracking, streaks, adjustable type, a listen-aloud button, shareable verse cards, and a candlelight night mode. Once visited, it works offline: planes, basements, mission fields.":": um leitor di\u00e1rio sem distra\u00e7\u00f5es com progresso, sequ\u00eancias, letra ajust\u00e1vel, bot\u00e3o de leitura em voz alta, cart\u00f5es de vers\u00edculos e modo noturno \u00e0 luz de vela. Depois da primeira visita, funciona offline: avi\u00f5es, por\u00f5es, campos mission\u00e1rios.",
"What is the Launch Planner?":"O que \u00e9 o Planejador de lan\u00e7amento?",
"Do we need to install anything?":"Precisamos instalar algo?",
"No. Everything runs in the browser. If you'd like, the site installs as an app on phones and desktops — but the front door is always just the web address.":"N\u00e3o. Tudo roda no navegador. Se quiser, o site se instala como app no celular e no computador, mas a porta da frente \u00e9 sempre o endere\u00e7o web.",
"Is there a fast way to find things?":"Tem um jeito r\u00e1pido de achar as coisas?",
"(or Ctrl-K) anywhere on the site to search all 1252 campaigns, jump to any page, or continue your reading exactly where you left off.":"(ou Ctrl-K) em qualquer lugar do site para buscar nas 1252 campanhas, pular para qualquer p\u00e1gina ou continuar a leitura exatamente de onde parou.",
"Still wondering about something?":"Ainda com alguma d\u00favida?",
"A real person reads every message — usually the same day.":"Uma pessoa de verdade l\u00ea cada mensagem, normalmente no mesmo dia.",
"Write to us →":"Escreva para n\u00f3s \u2192",
"A few more common questions":"Mais algumas perguntas comuns",
"Can we run a custom length, like five weeks?":"Podemos usar uma dura\u00e7\u00e3o personalizada, tipo cinco semanas?",
"We only want the small-group study. Do we have to buy the whole campaign?":"S\u00f3 queremos o estudo de pequenos grupos. Precisamos comprar a campanha inteira?",
"How does ordering printed copies work?":"Como funciona pedir c\u00f3pias impressas?",
"Can our pastor edit the sermon outlines?":"Nosso pastor pode editar os esbo\u00e7os?",
"Yes — that's the intent. Every outline downloads as an editable Word document with five supporting points, texts, and a stated big idea per week. Pastors commonly trim it to three points and add their own stories and application.":"Sim, essa \u00e9 a inten\u00e7\u00e3o. Cada esbo\u00e7o baixa como documento Word edit\u00e1vel com cinco pontos de apoio, textos e uma grande ideia por semana. Os pastores costumam enxugar para tr\u00eas pontos e acrescentar suas hist\u00f3rias e aplica\u00e7\u00e3o.",
"What's the difference between a category and a theme?":"Qual a diferen\u00e7a entre categoria e tema?",
"Can we find campaigns for grandparents, singles, or business owners specifically?":"Existem campanhas espec\u00edficas para av\u00f3s, solteiros ou empres\u00e1rios?",
"How do we know if we're ready to launch a campaign?":"Como sabemos se estamos prontos para lan\u00e7ar uma campanha?",
"Try the free":"Experimente a gratuita",
"— eight questions about your pulpit, leadership, hosts, and calendar, scored instantly with a recommended next step. Sometimes the answer is to launch now; sometimes it's to start smaller first. Both are useful outcomes.":": oito perguntas sobre seu p\u00falpito, lideran\u00e7a, anfitri\u00f5es e calend\u00e1rio, pontuadas na hora com um pr\u00f3ximo passo recomendado. \u00c0s vezes a resposta \u00e9 lan\u00e7ar j\u00e1; \u00e0s vezes \u00e9 come\u00e7ar menor. Os dois resultados s\u00e3o \u00fateis.",
"Where should we start browsing?":"Por onde come\u00e7amos a navegar?",
"A few good starting points: the":"Alguns bons pontos de partida: as",
"category pages":"p\u00e1ginas de categorias",
"if you already know your topic, the":"se voc\u00ea j\u00e1 sabe seu tema, o",
"if you want to see what other churches run most often, or the":"se quer ver o que outras igrejas mais rodam, ou o",
"Finder":"Localizador",
"if you'd rather answer a few questions and get matched.":"se preferir responder algumas perguntas e receber combina\u00e7\u00f5es.",
"Day One of every campaign is free —":"O Dia Um de cada campanha \u00e9 gr\u00e1tis \u2014",
"read one now":"leia um agora",
"How It Works — 40 Day Campaigns":"Como funciona \u2014 40 Day Campaigns",
"Six weeks. One heartbeat.":"Seis semanas. Um s\u00f3 batimento.",
"The shape of a week":"O formato de uma semana",
"One question, three rooms.":"Uma pergunta, tr\u00eas salas.",
"Every week of a campaign asks a single question — and asks it three different ways.":"Cada semana de uma campanha faz uma \u00fanica pergunta, e faz de tr\u00eas maneiras diferentes.",
"Sunday · The pulpit":"Domingo \u00b7 O p\u00falpito","You preach it.":"Voc\u00ea prega.",
"Six sermon outlines — text, big idea, three movements, and a landing — build the week's question from Scripture. You bring your voice; the architecture is done.":"Seis esbo\u00e7os \u2014 texto, grande ideia, tr\u00eas movimentos e uma aterrissagem \u2014 constroem a pergunta da semana a partir da Escritura. Voc\u00ea traz a voz; a arquitetura j\u00e1 est\u00e1 pronta.",
"Midweek · The living room":"Meio da semana \u00b7 A sala de estar","Groups wrestle with it.":"Os grupos lutam com ela.",
"A six-session study a first-time host can lead cold. Four movements, honest questions, one practice. The questions do the teaching; the room does the growing.":"Um estudo de seis sess\u00f5es que um anfitri\u00e3o de primeira viagem consegue conduzir sem preparo. Quatro movimentos, perguntas honestas, uma pr\u00e1tica. As perguntas ensinam; a sala cresce.",
"Every day · At home":"Todo dia \u00b7 Em casa","Each person lives it.":"Cada pessoa vive.",
"A fully written daily reading — five movements, a prayer, a question, one step — plus a weekly memory verse the whole household shares, kids' table included.":"Uma leitura di\u00e1ria totalmente escrita \u2014 cinco movimentos, uma ora\u00e7\u00e3o, uma pergunta, um passo \u2014 mais um vers\u00edculo semanal que a casa toda compartilha, mesa das crian\u00e7as inclu\u00edda.",
"By Saturday, the question hasn't just been heard. It has been lived with.":"At\u00e9 s\u00e1bado, a pergunta n\u00e3o foi s\u00f3 ouvida. Foi vivida.",
"See a real aligned week →":"Veja uma semana alinhada de verdade \u2192",
"Before Day One":"Antes do Dia Um","The six-week runway.":"A pista de seis semanas.",
"Campaigns don't fail in week three; they fail in the six weeks before they begin. So the launch kit runs those weeks for you — and the Launch Planner puts them on your calendar.":"Campanhas n\u00e3o fracassam na semana tr\u00eas; fracassam nas seis semanas antes de come\u00e7arem. Por isso o kit de lan\u00e7amento conduz essas semanas por voc\u00ea, e o Planejador as coloca no seu calend\u00e1rio.",
"Vision &amp; team":"Vis\u00e3o e equipe",
"Cast it to staff and elders, name a champion, set the print plan. One meeting.":"Apresente \u00e0 equipe e aos presb\u00edteros, nomeie um campe\u00e3o, defina o plano de impress\u00e3o. Uma reuni\u00e3o.",
"Open host recruiting":"Abra o recrutamento de anfitri\u00f5es",
"\"Open your home for six weeks\" — the most repeatable leadership on-ramp in church life. Invite 20% more hosts than you need.":"\u201cAbra sua casa por seis semanas\u201d: a rampa de lideran\u00e7a mais repet\u00edvel da vida da igreja. Convide 20% mais anfitri\u00f5es do que precisa.",
"Host orientation":"Orienta\u00e7\u00e3o de anfitri\u00f5es",
"One hour. The kit runs it. Every host leaves with the Leader &amp; Launch Kit and the confidence that the questions will carry them.":"Uma hora. O kit conduz. Cada anfitri\u00e3o sai com o Kit do l\u00edder e lan\u00e7amento e a confian\u00e7a de que as perguntas v\u00e3o sustent\u00e1-lo.",
"Church-wide sign-up Sunday":"Domingo de inscri\u00e7\u00e3o de toda a igreja",
"Preach the invitation — nobody does this alone — and open sign-ups in the lobby and online. Youth and children's directors brief their teams the same week.":"Pregue o convite \u2014 ningu\u00e9m faz isso sozinho \u2014 e abra inscri\u00e7\u00f5es no sagu\u00e3o e online. Os diretores de jovens e crian\u00e7as orientam suas equipes na mesma semana.",
"Form the groups":"Forme os grupos",
"Every name lands in a group. Hosts make first contact. Devotionals reach every household, printed or digital.":"Cada nome cai em um grupo. Os anfitri\u00f5es fazem o primeiro contato. Os devocionais chegam a cada casa, impressos ou digitais.",
"Final prep":"Prepara\u00e7\u00e3o final",
"Walk hosts through Session 1, load Sermon 1 into the plan of service, send the \"we begin Sunday\" message. Then begin.":"Repasse a Sess\u00e3o 1 com os anfitri\u00f5es, carregue o Serm\u00e3o 1 na liturgia, envie a mensagem de \u201ccome\u00e7amos domingo\u201d. E comece.",
"Open the Launch Planner — dated for your church →":"Abrir o Planejador, com datas para a sua igreja \u2192",
"Inside every license":"Dentro de cada licen\u00e7a","Everything in the box.":"Tudo o que vem na caixa.",
"The Daily Devotional":"O devocional di\u00e1rio",
"Every day fully written — 413 to 557 words each — with prayer, reflection, and one step.":"Cada dia totalmente escrito \u2014 de 413 a 557 palavras \u2014 com ora\u00e7\u00e3o, reflex\u00e3o e um passo.",
"The Six-Session Group Study":"O estudo de grupo de seis sess\u00f5es",
"Welcome, four movements, practice, prayer. Built for the newest host in the room.":"Boas-vindas, quatro movimentos, pr\u00e1tica, ora\u00e7\u00e3o. Feito para o anfitri\u00e3o mais novo da sala.",
"Six Sermon Outlines":"Seis esbo\u00e7os de serm\u00f5es",
"Text, big idea, three movements, landing — in step with the week's readings.":"Texto, grande ideia, tr\u00eas movimentos, aterrissagem: no passo das leituras da semana.",
"The Youth Edition":"A edi\u00e7\u00e3o jovem",
"The honest version, week by week, for students who can smell a script.":"A vers\u00e3o honesta, semana a semana, para estudantes que farejam roteiro de longe.",
"The Children's Edition":"A edi\u00e7\u00e3o infantil",
"The story, the craft, the echo prayer — so dinner tables share one verse.":"A hist\u00f3ria, a atividade, a ora\u00e7\u00e3o em eco: para a mesa compartilhar um mesmo vers\u00edculo.",
"The Leader Kit":"O kit do l\u00edder",
"Host tips, weekly rhythm, shepherding notes, the midweek text that keeps rooms warm.":"Dicas de anfitri\u00e3o, ritmo semanal, notas de pastoreio e a mensagem do meio da semana que mant\u00e9m as salas aquecidas.",
"The Launch Kit":"O kit de lan\u00e7amento",
"The full six-week runway — recruiting to Celebration Sunday.":"A pista completa de seis semanas: do recrutamento ao Domingo de Celebra\u00e7\u00e3o.",
"The Congregation-Wide License":"A licen\u00e7a para toda a congrega\u00e7\u00e3o",
"Print rights included. One license, your whole church, forever.":"Direitos de impress\u00e3o inclu\u00eddos. Uma licen\u00e7a, sua igreja inteira, para sempre.",
"Choose your length":"Escolha sua dura\u00e7\u00e3o",
"Forty days is the classic. It isn't the only door.":"Quarenta dias \u00e9 o cl\u00e1ssico. N\u00e3o \u00e9 a \u00fanica porta.",
"Most churches run three to six weeks — and every campaign composes cleanly at any length in that range. Match the season, not the calendar.":"A maioria das igrejas roda de tr\u00eas a seis semanas, e cada campanha se comp\u00f5e limpa em qualquer dura\u00e7\u00e3o nessa faixa. Ajuste \u00e0 temporada, n\u00e3o ao calend\u00e1rio.",
"The spark":"A fa\u00edsca",
"A week of prayer, a staff reset, a taste before the plunge. Low ask, real depth.":"Uma semana de ora\u00e7\u00e3o, um reset da equipe, uma prova antes do mergulho. Pouca exig\u00eancia, profundidade real.",
"The habit":"O h\u00e1bito",
"Long enough to form a rhythm — new year, new groups, new believers.":"Longo o bastante para formar um ritmo: ano novo, grupos novos, novos convertidos.",
"The month":"O m\u00eas",
"A clean calendar month with margin. The workhorse for busy seasons.":"Um m\u00eas de calend\u00e1rio limpo com margem. O cavalo de batalha das temporadas cheias.",
"The movement":"O movimento",
"The full journey — six parts, one arc. When you want the whole church changed, not just informed.":"A jornada completa: seis partes, um arco. Para quando voc\u00ea quer uma igreja transformada, n\u00e3o s\u00f3 informada.",
"Group-first":"Grupos primeiro",
"Session-led with lighter daily reading. Ideal where groups are the front door.":"Conduzido por sess\u00f5es com leitura di\u00e1ria mais leve. Ideal onde os grupos s\u00e3o a porta de entrada.",
"The voice":"A voz","Conviction, never condemnation.":"Convic\u00e7\u00e3o, nunca condena\u00e7\u00e3o.",
"Every campaign is written in one voice: warm, direct, and unembarrassed by Scripture. Readings quote the NIV reading plan · KJV verses labeled, with the weekly memory verse set for households to share.":"Cada campanha \u00e9 escrita em uma s\u00f3 voz: calorosa, direta e sem vergonha da Escritura. As leituras seguem o plano NVI com vers\u00edculos sinalizados, e o vers\u00edculo semanal \u00e9 preparado para as casas compartilharem.",
"Sensitive seasons — grief, anxiety, financial fear, burnout — are handled the way a good pastor would: permission to go slow, no shame in the sentence structure, and a gentle note toward pastoral or professional support where it belongs.":"Temporadas sens\u00edveis \u2014 luto, ansiedade, medo financeiro, esgotamento \u2014 s\u00e3o tratadas como um bom pastor trataria: permiss\u00e3o para ir devagar, sem vergonha na reda\u00e7\u00e3o, e uma nota gentil para apoio pastoral ou profissional onde cabe.",
"And no two journeys blur together. Each of the 1252 campaigns holds its own angle, its own scriptural backbone, and its own governing metaphor — so the fourth campaign your church runs feels as fresh as the first.":"E nenhuma dupla de jornadas se confunde. Cada uma das 1252 campanhas sustenta seu \u00e2ngulo, sua espinha b\u00edblica e sua met\u00e1fora regente, para que a quarta campanha pare\u00e7a t\u00e3o fresca quanto a primeira.",
"The proof is the prose":"A prova \u00e9 a prosa",
"Read one, and you'll know.":"Leia uma e voc\u00ea vai saber.",
"Read Day One free →":"Leia o Dia Um gr\u00e1tis \u2192",
"A closer look":"Um olhar mais de perto",
"What a typical week looks like":"Como \u00e9 uma semana t\u00edpica",
"Most weeks include a simple action step, specific enough to actually do, tied to that week's theme.":"A maioria das semanas inclui um passo de a\u00e7\u00e3o simples, espec\u00edfico o bastante para ser feito, ligado ao tema daquela semana.",
"Over six weeks,":"Ao longo de seis semanas,",
"this rhythm tends to build real momentum. Groups get more comfortable with each other, and by the final week — Celebration Sunday — churches often find people volunteering their own stories without much prompting.":"esse ritmo tende a construir impulso real. Os grupos ficam mais \u00e0 vontade entre si, e na \u00faltima semana \u2014 o Domingo de Celebra\u00e7\u00e3o \u2014 muitas igrejas encontram pessoas contando suas hist\u00f3rias sem que pe\u00e7am.",
"Picking a length":"Escolhendo uma dura\u00e7\u00e3o",
"Which format fits your church right now":"Qual formato serve \u00e0 sua igreja agora",
"One week, whole church, minimal setup. Good for a January reset, a week of prayer, or a first campaign at a church that hasn't run one before.":"Uma semana, igreja inteira, prepara\u00e7\u00e3o m\u00ednima. Bom para um reset de janeiro, uma semana de ora\u00e7\u00e3o ou uma primeira campanha.",
"Three weeks is usually enough time for a daily habit to stop feeling like an assignment. This length works well when the goal is building a practice — prayer, gratitude, Scripture reading — rather than covering a topic.":"Tr\u00eas semanas costumam bastar para um h\u00e1bito di\u00e1rio deixar de parecer tarefa. Essa dura\u00e7\u00e3o funciona bem quando a meta \u00e9 construir uma pr\u00e1tica \u2014 ora\u00e7\u00e3o, gratid\u00e3o, leitura b\u00edblica \u2014 mais do que cobrir um tema.",
"Four sermons over four weeks, which matches how a lot of pastors already plan a series. It's the easiest fit on a normal church calendar, and usually what we'd recommend for a first campaign.":"Quatro serm\u00f5es em quatro semanas, o que combina com o jeito que muitos pastores j\u00e1 planejam uma s\u00e9rie. \u00c9 o encaixe mais f\u00e1cil num calend\u00e1rio normal, e o que costumamos recomendar para uma primeira campanha.",
"The full version, and the one most churches mean when they picture \"a campaign.\" Six sermons, six weeks of groups, and the complete daily devotional.":"A vers\u00e3o completa, e a que a maioria imagina ao dizer \u201cuma campanha\u201d. Seis serm\u00f5es, seis semanas de grupos e o devocional di\u00e1rio completo.",
"6-Week and custom.":"6 semanas e personalizada.",
"Groups tend to prefer a six-session study. If your calendar needs something else, choose a custom length between three and six weeks — the sessions, sermons, and daily readings all adjust to fit.":"Os grupos tendem a preferir um estudo de seis sess\u00f5es. Se o calend\u00e1rio pedir outra coisa, escolha uma dura\u00e7\u00e3o entre tr\u00eas e seis semanas: sess\u00f5es, serm\u00f5es e leituras se ajustam.",
"About Lifetogether — 40 Day Campaigns":"Sobre a Lifetogether \u2014 40 Day Campaigns",
"The house behind the campaigns.":"A casa por tr\u00e1s das campanhas.",
"Twenty-five years of one conviction: churches change most when they move through Scripture together — every room, every age, every day.":"Vinte e cinco anos de uma convic\u00e7\u00e3o: igrejas mudam mais quando atravessam a Escritura juntas, em cada sala, em cada idade, todo dia.",
"The story":"A hist\u00f3ria","It started in living rooms.":"Come\u00e7ou nas salas de estar.",
"\"The goal was never content. The goal was a church that moves as one — the content is just how you get there.\"":"\u201cA meta nunca foi o conte\u00fado. A meta era uma igreja que se move como uma s\u00f3; o conte\u00fado \u00e9 s\u00f3 o caminho.\u201d",
"The line through it":"A linha que atravessa","A quarter century, briefly.":"Um quarto de s\u00e9culo, em resumo.",
"Lifetogether founded":"Lifetogether \u00e9 fundada",
"Out of the Saddleback small-groups movement — with a mandate to make churchwide journeys repeatable.":"A partir do movimento de pequenos grupos de Saddleback, com o mandato de tornar repet\u00edveis as jornadas de toda a igreja.",
"The campaign era proves the pattern":"A era das campanhas prova o padr\u00e3o",
"The Purpose Driven years show what alignment does at scale; Lifetogether serves the churches building on it.":"Os anos de Uma Vida com Prop\u00f3sitos mostram o que o alinhamento faz em escala; a Lifetogether serve as igrejas que constroem sobre isso.",
"Five hundred churches deep":"Quinhentas igrejas depois",
"Campaigns for stewardship, family, legacy, and formation — refined season after season, host by host.":"Campanhas de mordomia, fam\u00edlia, legado e forma\u00e7\u00e3o, refinadas temporada ap\u00f3s temporada, anfitri\u00e3o por anfitri\u00e3o.",
"The library opens":"A biblioteca abre",
"1252 finished campaigns, 94 themes, every edition composed to move together — with the Reading Room, the Launch Planner, and Day One free for anyone.":"1252 campanhas prontas, 94 temas, cada edi\u00e7\u00e3o composta para se mover junta, com a Sala de leitura, o Planejador e o Dia Um gr\u00e1tis para qualquer pessoa.",
"Before you decide anything":"Antes de decidir qualquer coisa","Ten things worth knowing":"Dez coisas que vale a pena saber",
"Every campaign is complete before you see it.":"Cada campanha est\u00e1 completa antes de voc\u00ea v\u00ea-la.",
"Not outlines or drafts — 1252 finished campaigns, over 15,000 individual daily readings written.":"N\u00e3o esbo\u00e7os nem rascunhos: 1252 campanhas prontas, mais de 15.000 leituras di\u00e1rias escritas.",
"The approach isn't new.":"A abordagem n\u00e3o \u00e9 nova.",
"The aligned pulpit, small-group, and daily-reading model dates back to 40 Days of Purpose, which ran in roughly 30,000 churches. We've continued refining it with more than 500 churches since.":"O modelo alinhado de p\u00falpito, grupos e leitura di\u00e1ria remonta aos 40 Dias com Prop\u00f3sitos, que rodou em cerca de 30.000 igrejas. Continuamos refinando com mais de 500 igrejas desde ent\u00e3o.",
"Your pastor still does the preaching.":"Seu pastor continua pregando.",
"We provide structure and material; we don't replace the pastor's own voice or delivery.":"Fornecemos estrutura e material; n\u00e3o substitu\u00edmos a voz nem a entrega do pastor.",
"Sermon outlines are editable.":"Os esbo\u00e7os s\u00e3o edit\u00e1veis.",
"Each week comes with five supporting points, texts, and a stated big idea, delivered as a Word file so pastors can adjust it.":"Cada semana traz cinco pontos de apoio, textos e uma grande ideia declarada, em arquivo Word para o pastor ajustar.",
"Kids and students aren't an afterthought.":"Crian\u00e7as e jovens n\u00e3o s\u00e3o um detalhe.",
"Youth and children's editions cover the same weekly themes in age-appropriate language.":"As edi\u00e7\u00f5es jovem e infantil cobrem os mesmos temas semanais em linguagem apropriada.",
"Groups don't need an experienced leader.":"Os grupos n\u00e3o precisam de l\u00edder experiente.",
"Sessions are built so a first-time host can run them using the provided questions.":"As sess\u00f5es s\u00e3o feitas para um anfitri\u00e3o de primeira viagem conduzir com as perguntas fornecidas.",
"Length is flexible.":"A dura\u00e7\u00e3o \u00e9 flex\u00edvel.",
"Anywhere from seven to forty days, or a custom length between three and six weeks.":"De sete a quarenta dias, ou uma dura\u00e7\u00e3o personalizada entre tr\u00eas e seis semanas.",
"You can preview everything before buying.":"D\u00e1 para ver tudo antes de comprar.",
"Every day of every devotional is readable on the campaign page.":"Cada dia de cada devocional pode ser lido na p\u00e1gina da campanha.",
"Print isn't a separate project.":"Imprimir n\u00e3o \u00e9 um projeto \u00e0 parte.",
"Print-ready files are included with every license, and ordering physical copies is a single step.":"Arquivos prontos para impress\u00e3o v\u00eam com cada licen\u00e7a, e pedir c\u00f3pias f\u00edsicas \u00e9 um \u00fanico passo.",
"What we care about most:":"O que mais nos importa:",
"whether groups keep meeting after the campaign ends.":"se os grupos continuam se reunindo depois que a campanha termina.",
"Our process":"Nosso processo","How a campaign gets built":"Como uma campanha \u00e9 constru\u00edda",
"Start with an actual pastoral need, not just a topic that seems marketable.":"Comece com uma necessidade pastoral real, n\u00e3o com um tema que parece vend\u00e1vel.",
"Choose a Scripture passage and central idea distinct enough that it doesn't overlap with existing campaigns.":"Escolha uma passagem e uma ideia central distintas o bastante para n\u00e3o sobrepor campanhas existentes.",
"Write the daily devotional, six group sessions, six sermons, and the youth and children's editions around that same idea.":"Escreva o devocional di\u00e1rio, seis sess\u00f5es, seis serm\u00f5es e as edi\u00e7\u00f5es jovem e infantil em torno dessa mesma ideia.",
"Have someone unfamiliar with the material read it aloud and lead a session, then revise based on what didn't land.":"Pe\u00e7a a algu\u00e9m de fora que leia em voz alta e conduza uma sess\u00e3o; revise conforme o que n\u00e3o aterrissou.",
"Prepare print-ready and digital versions so nothing ships as an unfinished outline.":"Prepare vers\u00f5es digitais e prontas para impress\u00e3o para nada sair como esbo\u00e7o inacabado.",
"Video production, if you want it":"Produ\u00e7\u00e3o de v\u00eddeo, se voc\u00ea quiser",
"Talking head":"Falando \u00e0 c\u00e2mera",
"Pastor speaking directly to camera. Quickest to produce.":"O pastor falando direto para a c\u00e2mera. O mais r\u00e1pido de produzir.",
"Story-driven":"Guiado por hist\u00f3rias",
"Testimonies from your own congregation woven into the teaching.":"Testemunhos da sua pr\u00f3pria congrega\u00e7\u00e3o tecidos no ensino.",
"Town hall":"Roda de conversa",
"A more conversational format, filmed in your own space.":"Um formato mais conversacional, filmado no seu pr\u00f3prio espa\u00e7o.",
"A small group of voices discussing the topic together.":"Um pequeno grupo de vozes conversando sobre o tema.",
"You shoot, we edit.":"Voc\u00ea grava, n\u00f3s editamos.",
"Send us the raw footage and we'll handle cutting, color correction, captions, and delivery — a middle option between doing it entirely yourself and hiring a full production crew.":"Envie o material bruto e cuidamos do corte, cor, legendas e entrega: uma op\u00e7\u00e3o intermedi\u00e1ria entre fazer tudo sozinho e contratar uma produtora completa.",
"Past campaigns":"Campanhas anteriores",
"A small sample of prior campaigns. We're working on adding trailers and a fuller showcase to this page.":"Uma pequena amostra de campanhas anteriores. Estamos adicionando trailers e uma vitrine mais completa a esta p\u00e1gina.",
"The craft standards":"Os padr\u00f5es de of\u00edcio",
"What \"hand-curated\" means here.":"O que \u201ccuidado \u00e0 m\u00e3o\u201d significa aqui.",
"Five commitments govern every campaign in the library. They are not marketing; they are the editing checklist.":"Cinco compromissos governam cada campanha da biblioteca. N\u00e3o s\u00e3o marketing; s\u00e3o a lista de edi\u00e7\u00e3o.",
"A distinct angle, every time.":"Um \u00e2ngulo distinto, sempre.",
"No two campaigns blur. Each holds its own question, its own scriptural backbone, and its own governing metaphor — even inside the same theme.":"Nenhuma dupla de campanhas se confunde. Cada uma sustenta sua pergunta, sua espinha b\u00edblica e sua met\u00e1fora regente, mesmo dentro do mesmo tema.",
"The voice is warm and direct. Sensitive seasons — grief, anxiety, financial fear — get permission-to-go-slow pacing and a pointer toward pastoral support.":"A voz \u00e9 calorosa e direta. Temporadas sens\u00edveis \u2014 luto, ansiedade, medo financeiro \u2014 recebem ritmo com permiss\u00e3o para ir devagar e um sinal para apoio pastoral.",
"Scripture at the center.":"A Escritura no centro.",
"Daily readings follow an NIV reference plan. Quoted memory verses are KJV (public domain) and clearly labeled, with a one-step swap to NIV once licensing completes.":"As leituras seguem um plano de refer\u00eancias NVI. Os vers\u00edculos citados s\u00e3o de dom\u00ednio p\u00fablico e sinalizados, com troca em um passo para NVI quando o licenciamento concluir.",
"Built for the newest host.":"Feito para o anfitri\u00e3o mais novo.",
"Every session assumes the leader has never led. The questions do the teaching; the kit does the coaching.":"Cada sess\u00e3o assume que o l\u00edder nunca liderou. As perguntas ensinam; o kit acompanha.",
"Finished means finished.":"Pronto significa pronto.",
"Sixteen formats per campaign, sequenced to move together. If it needs assembling, it isn't done — and it doesn't ship.":"Dezesseis formatos por campanha, sequenciados para se moverem juntos. Se precisa de montagem, n\u00e3o est\u00e1 pronto, e n\u00e3o \u00e9 publicado.",
"Everything here rests on one verse.":"Tudo aqui repousa sobre um vers\u00edculo.",
"\"The earth is the LORD's, and everything in it.\"":"\u201cDo Senhor \u00e9 a terra e a sua plenitude.\u201d",
"Step into the library →":"Entre na biblioteca \u2192","Write to us":"Escreva para n\u00f3s",
"© 2026 40daycampaigns.com · A Lifetogether ministry · Founded by Brett Eastman, 2001":"\u00a9 2026 40daycampaigns.com \u00b7 Um minist\u00e9rio Lifetogether \u00b7 Fundado por Brett Eastman, 2001",
"Rancho Santa Margarita, California ·":"Rancho Santa Margarita, Calif\u00f3rnia \u00b7",
}
json.dump(PT, open('/home/claude/tr_pt_3.json','w'), ensure_ascii=False)
print("PT map 3:", len(PT), "pairs")
