# -*- coding: utf-8 -*-
# Axis A - Topical taxonomy, 13 families.
# Each family: (name, definition line, [topics])
# A topic prefixed with "*" is one the public incumbent taxonomy does NOT carry
# as a browse category - i.e. an opening.

TOPIC_FAMILIES = [
 ("God and the Gospel",
  "The doctrinal spine. Every other family borrows its authority from this one, "
  "and a preaching year that never returns here drifts into moralism within about "
  "eighteen months.",
  ["Attributes of God","Names of God","Trinity","Sovereignty","Providence",
   "Holiness of God","God's Goodness","God's Love","God's Provision","God's Will",
   "God's Wrath","Glory","Grace","Grace Alone","Christ Alone","Salvation",
   "Atonement","The Cross","Crucifixion","Resurrection","Ascension","Justification",
   "Redemption","Adoption","Kingdom of God","Covenant","Immanuel","I Am",
   "Incarnation","Gospel Clarity","*The Character of God for Skeptics"]),

 ("Following Jesus",
  "The discipleship arc from first step to long obedience. This is the family most "
  "churches preach in fragments and almost never in sequence.",
  ["Discipleship","New Birth","Repentance","Conversion","Baptism","Communion",
   "Confession","Surrender","Obedience","Abiding","Spiritual Growth",
   "Spiritual Maturity","Sanctification","Identity in Christ","Calling",
   "Following Jesus","Counting the Cost","Perseverance","Endurance","Faithfulness",
   "Commitment","*Next Steps and Spiritual Milestones","*What to Do After You Decide"]),

 ("Spiritual Practices",
  "The habits that carry formation between Sundays. Preached well, this family "
  "converts a message into a week.",
  ["Prayer","Intercession","Fasting","Silence and Solitude","Sabbath","Rest",
   "Studying the Bible","Scripture Memory","Meditation","Worship","Praise",
   "Gratitude","Simplicity","Confession","Solitude","Listening to God",
   "Journaling","Retreat","Spiritual Disciplines","*Daily Devotional Rhythm",
   "*Household Practice","*Digital Fasting"]),

 ("Character and Formation",
  "The fruit. Nine of these are given as a single cluster in Galatians 5 and are "
  "still, in most catalogs, scattered alphabetically across the index.",
  ["Love","Joy","Peace","Patience","Kindness","Goodness","Faithfulness",
   "Gentleness","Self-Control","Fruit of the Spirit","Humility","Integrity",
   "Courage","Contentment","Wisdom","Discernment","Purity","Honesty","Diligence",
   "Compassion","Servanthood","Teachability","Perseverance","Character",
   "*Decision-Making Under Pressure","*The Long Obedience"]),

 ("The Inner Life and the Struggle",
  "Where most people actually live on a Tuesday. The single largest gap between "
  "what is preached and what is searched.",
  ["Anxiety","Fear","Worry","Doubt","Honest Doubt","Depression","Loneliness",
   "Anger","Shame","Guilt","Grief","Lament","Burnout","Exhaustion","Temptation",
   "Addiction","Lust","Pornography","Pride","Envy","Comparison","Bitterness",
   "Unforgiveness","Spiritual Warfare","Strongholds","Backsliding","Suffering",
   "Trials","Waiting","Disappointment","Regret","*Mental Health and Faith",
   "*Anxiety in a Notification Culture","*When God Seems Silent"]),

 ("Money, Work and Stewardship",
  "The AA category. Roughly two-thirds of adults report financial strain and "
  "almost none of them expect the church to speak into it usefully. That gap is "
  "the whole opportunity.",
  ["Stewardship","Generosity","Giving","Tithing","First Fruits","Finances","Debt",
   "Budgeting","Saving","Investing","Contentment","Greed","Materialism",
   "Prosperity","God's Provision","Enough","Work","Vocation","Calling at Work",
   "Business Ethics","Ambition","Success","Career Change","Job Loss",
   "Retirement","Wealth","Inheritance","Estate and Legacy","Wealth Transfer",
   "Wisdom in Decisions","Risk","Margin","*How Much Is Enough","*Money and Marriage",
   "*Teaching Children About Money","*The Generosity Ladder","*Faith and the Family Business"]),

 ("Family, Marriage and Household",
  "The household is the smallest and most durable unit of formation, and the one "
  "least served by a Sunday-only strategy.",
  ["Marriage","Dating","Courtship","Engagement","Singleness","Sexuality","Purity",
   "Parenting","Fatherhood","Motherhood","Children","Teenagers","Blended Families",
   "Divorce","Remarriage","Infertility","Adoption","Foster Care","Aging Parents",
   "Caregiving","Grandparenting","Family Conflict","Forgiveness in Marriage",
   "Family Worship","Household Discipleship","Legacy","Generations",
   "*The Family Meeting","*Passing On What Matters","*Family Values and Mission",
   "*The Legacy Conversation"]),

 ("Relationships and Community",
  "Belonging is now a felt need with the intensity that salvation questions had a "
  "generation ago, and the church has the answer sitting unused in its living rooms.",
  ["Friendship","Fellowship","Small Groups","Community","Belonging","Hospitality",
   "Conflict","Forgiveness","Reconciliation","Boundaries","Encouragement",
   "Speech and the Tongue","Gossip","Judging Others","Unity","Serving One Another",
   "Mentoring","Discipling Others","Accountability","*Spiritual Partners",
   "*Finding Your People","*The Table"]),

 ("Mission, Evangelism and Justice",
  "The outward arc. Note that the incumbent taxonomy carries evangelism and "
  "missions but has thin coverage of neighboring, mercy and vocational witness.",
  ["Evangelism","The Great Commission","Missions","Witness","Testimony",
   "Sharing Your Story","Neighboring","Compassion","The Poor","Justice","Mercy",
   "Orphans and Widows","Hunger","Refugees","Racial Reconciliation",
   "Sanctity of Human Life","Creation Care","Persecution","Cultural Engagement",
   "Apologetics","*Inviting a Friend","*Witness at Work","*The Invisible Neighbor"]),

 ("The Church",
  "How the body works. This family is where a preaching calendar becomes a "
  "ministry strategy or fails to.",
  ["The Church","Church Health","Church Growth","Church Planting","Membership",
   "Spiritual Gifts","Serving","Volunteering","Leadership","Elders and Deacons",
   "Pastoral Ministry","Worship Ministry","Children's Ministry","Student Ministry",
   "Unity in the Body","Revival","Prayer Meeting","Multiplication","Sending",
   "Back to Church","Teamwork","Vision","*Volunteer Culture","*Leadership Pipeline",
   "*Campaign Alignment"]),

 ("Scripture and Doctrine",
  "The teaching floor. Thin here and everything above it becomes advice.",
  ["Bible Authority","Inspiration of Scripture","Bible Study Methods",
   "Interpretation","Law and Grace","Election","Free Will","Christology",
   "The Holy Spirit","Ecclesiology","End Times","Bible Prophecy","Heaven","Hell",
   "Judgment","Resurrection of the Dead","Angels","Demons","Creation",
   "Science and Faith","Theodicy","Parables","Beatitudes","Sermon on the Mount",
   "Miracles","Old Testament","New Testament","*Reading the Bible for Yourself",
   "*Why Four Gospels"]),

 ("Culture, Doubt and Contested Questions",
  "The fastest-moving family and the one where a catalog dates quickest. Half of "
  "these did not exist as browse categories five years ago.",
  ["Faith and Technology","*Faith in the Age of AI","*Attention and Formation",
   "Deconstruction","Honest Doubt","Politics and Faith","Nationalism",
   "Media and Culture","Identity","Gender","Sexuality","Homosexuality",
   "Mental Health","Suicide","Alcohol and Substances","Gambling","Consumerism",
   "Success and Ambition","Loneliness","*Rest in a Speed Culture",
   "*Men and Purpose","*Ancient Practices for a Distracted Age",
   "*From Curious to Committed","*The Upside-Down Kingdom"]),

 ("Seasons of Life",
  "The occasion-driven family. Every entry here is a moment when a person is "
  "already looking for meaning, which makes it the highest-yield preaching in the "
  "index and the least planned.",
  ["Birth","Baby Dedication","Childhood","Graduation","Back to School",
   "Leaving Home","Young Adulthood","Career Change","Job Loss","Marriage",
   "Empty Nest","Midlife","Retirement","Aging","Caregiving","Illness",
   "Terminal Diagnosis","Death","Funeral","Grief","Widowhood","Tragedy",
   "Natural Disaster","Finishing Well","*The Last Third","*Writing Your Legacy Letter"]),
]

# Axis E - People of Scripture. (name, testament, one-line preaching angle)
PEOPLE = [
 ("Adam and Eve","OT","Origin of vocation, marriage, temptation and shame in four chapters."),
 ("Cain and Abel","OT","Worship, anger and the first family fracture."),
 ("Noah","OT","Obedience with no visible evidence and a long build."),
 ("Abraham","OT","Call, waiting, covenant and the surrender of the promise itself."),
 ("Sarah","OT","Laughter, delay and a promise that outlasts a plan."),
 ("Lot","OT","The slow drift of proximity into compromise."),
 ("Isaac","OT","The inherited faith and what a second generation does with it."),
 ("Jacob","OT","Deception, wrestling and the renaming of a manipulator."),
 ("Joseph","OT","Providence through betrayal; the definitive text on interpreting your own story."),
 ("Moses","OT","Reluctant calling, sustained leadership, and the cost of not entering."),
 ("Aaron","OT","Priesthood, pressure and the golden calf."),
 ("Miriam","OT","Leadership, worship and the danger of rivalry."),
 ("Joshua","OT","Courage, succession and the choice speech."),
 ("Rahab","OT","Unlikely faith placed in the genealogy of Christ."),
 ("Deborah","OT","Wisdom, leadership and decisive counsel."),
 ("Gideon","OT","Fear, fleeces and reduction as strategy."),
 ("Samson","OT","Gifting without character."),
 ("Ruth","OT","Loyalty, gleaning and redemption through covenant kindness."),
 ("Naomi","OT","Bitterness honestly named and slowly healed."),
 ("Hannah","OT","Prayer out of anguish and a vow kept."),
 ("Samuel","OT","Hearing God young; anointing and disappointment."),
 ("Saul","OT","Insecurity as the engine of a ruined reign."),
 ("David","OT","Worship, courage, catastrophic failure and durable repentance."),
 ("Jonathan","OT","Covenant friendship that costs a throne."),
 ("Solomon","OT","Wisdom requested, wealth received, heart divided."),
 ("Elijah","OT","Confrontation, collapse and the whisper."),
 ("Elisha","OT","Succession, double portion and quiet miracles."),
 ("Hezekiah","OT","Reform, prayer and a late-career lapse."),
 ("Josiah","OT","A rediscovered scroll and a national turn."),
 ("Job","OT","Suffering without explanation and worship without answers."),
 ("Esther","OT","Position as stewardship; for such a time as this."),
 ("Nehemiah","OT","Burden, planning, opposition and a fifty-two-day wall."),
 ("Ezra","OT","Return, reading and the recovery of the Word."),
 ("Daniel","OT","Faithfulness inside a hostile system, sustained sixty years."),
 ("Jonah","OT","Reluctant mission and a God more merciful than his prophet."),
 ("Isaiah","OT","Vision, holiness and the sending question."),
 ("Jeremiah","OT","Faithfulness without visible fruit."),
 ("Habakkuk","OT","Honest complaint that ends in worship."),
 ("Mary","NT","Consent, magnification and a sword through the soul."),
 ("Joseph of Nazareth","NT","Quiet obedience and protective fatherhood."),
 ("John the Baptist","NT","Decrease as a life strategy."),
 ("The Shepherds","NT","The first audience for the announcement."),
 ("The Wise Men","NT","Long search, costly worship, different road home."),
 ("Herod","NT","Threatened power and the violence of insecurity."),
 ("Jesus Christ","NT","The center of every axis in this index."),
 ("Peter","NT","Impulse, denial, restoration and Pentecost."),
 ("Andrew","NT","The one who brings people."),
 ("James and John","NT","Ambition redirected into service and exile."),
 ("Thomas","NT","Doubt welcomed rather than shamed."),
 ("Matthew","NT","The table as the first evangelistic strategy."),
 ("Judas","NT","Proximity without transformation."),
 ("Mary and Martha","NT","Presence versus productivity."),
 ("Mary Magdalene","NT","Deliverance, loyalty and first witness."),
 ("Lazarus","NT","Delay, death and the demonstration."),
 ("Zacchaeus","NT","Curiosity, welcome and restitution as evidence."),
 ("The Rich Young Ruler","NT","The one thing and the walk away."),
 ("The Good Samaritan","NT","Proximity redefining neighbor."),
 ("The Prodigal Son","NT","Two lost sons and a running father."),
 ("Nicodemus","NT","The night conversation and the slow arrival."),
 ("The Woman at the Well","NT","Thirst, honesty and the first sent Samaritan."),
 ("Pontius Pilate","NT","Truth deferred to expedience."),
 ("Barnabas","NT","Encouragement as an office."),
 ("Stephen","NT","The first martyr and a face like an angel."),
 ("Paul","NT","Conversion, calling, thorn and finishing."),
 ("Timothy","NT","Young leadership and inherited faith."),
 ("Lydia","NT","Business, hospitality and a house church."),
 ("Priscilla and Aquila","NT","A married ministry team and a corrected preacher."),
 ("Philemon and Onesimus","NT","The gospel applied to an actual relationship."),
 ("John the Apostle","NT","Love, letters and the Revelation."),
]
