# -*- coding: utf-8 -*-
# Original LifeTogether title + subtitle pairs generated from the Master Preaching Index.
# (Title, Subtitle, Anchor, Outcome)

CORPUS_1 = [
("God and the Gospel", [
("Before You Were Asked","Grace that arrives ahead of the request","Rom 5:6-11","See it"),
("The God Who Goes First","What Scripture says God did before you did anything","Eph 2:1-10","See it"),
("Holy","The word we sing every week and rarely define","Isa 6:1-8","Sit with it"),
("Names Enough for a Lifetime","Seven names of God and the situation each one answers","Ex 3:13-15","Sit with it"),
("Not a Fair Trade","Substitution, and why it offends before it comforts","Isa 53:4-6","See it"),
("The Cross Was Not Plan B","Reading the whole story backward from Friday","Acts 2:22-24","See it"),
("Grace Is Not Leniency","What forgiveness cost before it was free","Rom 3:21-26","Sit with it"),
("The Kingdom Nobody Voted For","How the reign of God actually arrives","Mark 1:14-15","See it"),
("Sovereign in the Ordinary","Providence during the years nothing happens","Gen 50:15-21","Sit with it"),
("Three, and One","Why the Trinity is pastoral before it is technical","Matt 28:19","Sit with it"),
("Sunday Morning, Empty Tomb","The claim the whole faith stands or falls on","1 Cor 15:12-20","See it"),
("Wrath Is Not a Bad Mood","What we lose when we quietly edit the judgment of God","Rom 1:18-25","Sit with it"),
("Adopted, Not Hired","The difference between a servant's fear and a child's confidence","Rom 8:14-17","Own it"),
("Immanuel","God with us, on the days it does not feel like it","Matt 1:22-23","Sit with it"),
("I Am","Seven sentences that answer seven hungers","John 6-15","See it"),
("The Long Rescue","One story, sixty-six books, one direction","Luke 24:25-27","See it"),
("Enough Righteousness","Why you can stop auditioning","Phil 3:7-11","Own it"),
("Good on a Hard Year","Reading providence without lying about pain","Ps 34:8-19","Sit with it"),
("What the Ascension Changed","The forty days almost nobody preaches","Acts 1:6-11","See it"),
("Glory","The weight of God, and what it does to a room","Ex 33:12-23","Sit with it"),
("Chosen Before","Election taught as comfort rather than argument","Eph 1:3-14","Sit with it"),
("Covenant, Not Contract","Why God binds himself and does not renegotiate","Gen 15:1-21","See it"),
("The Gospel in One Sentence","Say it in thirty seconds, to anyone, without notes","1 Cor 15:3-5","Share it"),
("Redeemed Means Bought","The price, the buyer, and what you now belong to","1 Pet 1:18-21","Own it"),
]),
("Following Jesus", [
("The Second Decision","What happens after the one everybody counts","Luke 9:23-25","Own it"),
("Nobody Drifts Into Depth","Why maturity is scheduled and never accidental","Heb 5:11-14","Do it"),
("Wet","Baptism as a public sentence, not a private feeling","Rom 6:1-4","Do it"),
("Counting the Cost Out Loud","The invitation Jesus made harder on purpose","Luke 14:25-33","Sit with it"),
("Obedience Before Understanding","Doing the next right thing while the reason is still missing","John 2:1-11","Do it"),
("Repentance Is Not Regret","The difference between feeling bad and turning around","2 Cor 7:8-11","Own it"),
("Abide","The one command that makes all the others possible","John 15:1-8","Sit with it"),
("New, Not Improved","Why the gospel is a birth and not a renovation","John 3:1-8","See it"),
("The Table Changes You","Communion as formation rather than ceremony","1 Cor 11:23-29","Sit with it"),
("Surrender Is a Verb","Six areas most Christians never actually hand over","Rom 12:1-2","Do it"),
("Milestones","The seven moments a growing follower should be able to point to","Phil 1:3-6","Own it"),
("You Are Not Your Worst Week","An identity that survives failure","1 John 3:19-24","Own it"),
("Called Before Qualified","Why God's order of operations offends a resume","1 Cor 1:26-31","See it"),
("The Long Obedience","What forty years in the same direction actually looks like","Ps 84:5-7","Sit with it"),
("Say It to Somebody","Why confessing to a person does what confessing to God cannot","James 5:16","Do it"),
("Quit Well","The things a follower of Jesus is supposed to stop","Eph 4:22-24","Do it"),
("First Year","A twelve-month plan for somebody who just said yes","Acts 2:42-47","Do it"),
("Sanctified Is Not Finished","Living honestly between conversion and completion","Phil 3:12-16","Sit with it"),
("Who Told You That","Replacing the sentences you believe about yourself","Gen 3:8-13","Own it"),
("Faithful in the Boring Part","Discipleship on the days nothing is happening","Luke 16:10-12","Do it"),
("Take the Next Step","How to tell which one is actually next","Prov 3:5-6","Do it"),
("A Rule of Life","Deciding how you intend to live before the week decides for you","1 Tim 4:7-8","Do it"),
("Bring It Back","Formation is not finished until you have handed it to somebody","2 Tim 2:1-2","Bring it back"),
("Still Following","A conversation for people who have been at this thirty years","Josh 14:6-12","Deepen it"),
]),
("Spiritual Practices", [
("Pray Like You Mean It","Five honest prayers for people tired of pretending","Ps 62:5-8","Do it"),
("Teach Us","The prayer Jesus gave when they asked for a method","Luke 11:1-13","Do it"),
("The Empty Hour","What silence does that noise cannot","1 Kings 19:9-13","Sit with it"),
("Fast","Skipping a meal on purpose, and what it exposes","Matt 6:16-18","Do it"),
("A Day Off Is Not a Sabbath","Rest as resistance inside a productivity culture","Ex 20:8-11","Own it"),
("Read It Yourself","A method for people who have only ever been read to","2 Tim 3:14-17","Do it"),
("Memorize Something","Twelve verses, and why each one is worth carrying","Ps 119:9-16","Do it"),
("Seven Days Without a Screen","The fast nobody suggests, and what comes back","Isa 58:6-9","Do it"),
("Gratitude on Paper","Why the written list works when the mental one does not","1 Thess 5:16-18","Do it"),
("Worship on a Tuesday","Praise as a practice rather than an event","Ps 34:1-3","Do it"),
("Enough Already","Simplicity as a spiritual discipline, not a decorating style","Luke 12:15-21","Own it"),
("Listen","Telling God's voice from your own preference","John 10:1-5","Sit with it"),
("Alone on Purpose","Solitude for people who are afraid of it","Mark 1:35","Do it"),
("Journal","Writing as a way of noticing what God is already doing","Ps 77:11-12","Do it"),
("Pray for Somebody Else","The least self-focused thing you will do this week","Col 4:2-4","Do it"),
("Retreat","Twenty-four hours, a Bible, and no agenda","Mark 6:30-32","Do it"),
("Fixed Prayer, Unfixed Life","Daniel prayed three times a day while running an empire","Dan 6:10","Do it"),
("One Verse, Slowly","Staying with it until the words stop being familiar","Josh 1:8","Sit with it"),
("The Household Table","Practicing faith where you actually live","Deut 6:4-9","Do it"),
("Practice, Not Performance","Why none of this makes anybody more loved","Gal 3:1-5","Sit with it"),
("Short Accounts","A five-minute examination at the end of the day","Ps 139:23-24","Do it"),
("Give On a Schedule","Generosity as a practice rather than a mood","1 Cor 16:1-2","Do it"),
("Serve Weekly","The discipline nobody calls a discipline","Gal 5:13-14","Do it"),
("Seven Days","A week of practices, one per day, for a whole congregation","Ps 1:1-3","Do it"),
]),
("Character and Formation", [
("The Fruit Is One Thing","Nine words, one crop, and why we keep splitting them","Gal 5:22-23","See it"),
("Patient With People","Where patience actually gets tested","Col 3:12-14","Do it"),
("Self-Control Is a Muscle","Training the thing willpower cannot supply","1 Cor 9:24-27","Do it"),
("Kindness Is Not Niceness","The difference costs something","Luke 6:32-36","Own it"),
("Integrity When It Costs","Four decisions that reveal what you actually are","Ps 15:1-5","Own it"),
("Humble","The virtue you lose the moment you claim it","Phil 2:3-11","Sit with it"),
("Decide Before the Pressure","Courage is chosen early or not at all","Dan 1:8-16","Do it"),
("Contentment","Learning the one thing Paul said he had to learn","Phil 4:11-13","Own it"),
("Wisdom for the Decision in Front of You","A framework for the choice you are actually facing","James 1:5-8","Do it"),
("Tell the Truth","Honesty as a practice with a cost and a payoff","Eph 4:25","Do it"),
("Gentle Strength","Power under control, and why it is rare","Matt 11:28-30","Sit with it"),
("Faithful","The quiet virtue that outlasts the loud ones","Luke 16:10","Own it"),
("Purity in a Saturated World","A workable plan rather than a slogan","1 Thess 4:3-8","Do it"),
("Discernment","Telling good from almost-good","Heb 5:14","Do it"),
("Do the Hard Thing First","Diligence as discipleship","Prov 6:6-11","Do it"),
("Joy Is Not Happiness","What holds when the circumstances do not","Hab 3:17-19","Sit with it"),
("Peace You Can Keep","Guarding the thing anxiety keeps taking","Phil 4:6-9","Do it"),
("Goodness","The virtue with no audience","Matt 6:1-4","Own it"),
("Sixteen Things Love Is","Reading the wedding passage as a character audit","1 Cor 13:4-7","Sit with it"),
("Teachable at Fifty","Why the hardest people to develop are the experienced ones","Prov 9:8-9","Own it"),
("Under Pressure","What comes out of you when you are squeezed","James 1:2-4","Sit with it"),
("Serve Without Credit","The test most leaders quietly fail","Mark 10:42-45","Do it"),
("Compassion That Moves","Feeling is not the same as going","Luke 10:33-35","Do it"),
("Finish the Way You Started","Character measured on a forty-year horizon","2 Tim 4:6-8","Deepen it"),
]),
("The Inner Life and the Struggle", [
("Anxious","What Scripture actually says, and what it does not","Phil 4:6-7","Sit with it"),
("Afraid","Naming the fear before fighting it","Isa 41:10","Own it"),
("When God Seems Silent","Faith through the months nothing is said","Ps 13:1-6","Sit with it"),
("Honest Doubt","Bringing your questions inside instead of leaving over them","Mark 9:21-24","Sit with it"),
("Low","Faith and depression, without the platitudes","Ps 42:1-11","Sit with it"),
("Alone in a Full Room","Loneliness as the defining ache of this decade","Ps 25:16-18","Own it"),
("Angry","What to do with it before it does something with you","Eph 4:26-27","Do it"),
("Ashamed","The difference between guilt and shame, and why it matters","Rom 8:1","Own it"),
("Grief Has No Timeline","Permission to be where you actually are","Lam 3:19-26","Sit with it"),
("Burned Out","Elijah under the broom tree, and the God who fed him first","1 Kings 19:1-9","Sit with it"),
("Tempted","The way out that is always provided and rarely taken","1 Cor 10:12-13","Do it"),
("The Thing You Cannot Stop","Honesty, and the first genuinely useful step","Rom 7:15-25","Own it"),
("Comparison","Why the scroll is making you smaller","Gal 6:4-5","Own it"),
("Bitter","The root that goes down while nobody is looking","Heb 12:14-15","Own it"),
("Release the Debt","Forgiving somebody you have every right to keep charging","Matt 18:21-35","Do it"),
("Proud","The sin that hides behind competence","Prov 16:18","Sit with it"),
("Envy","Wanting what somebody else has, in church clothes","James 3:14-16","Own it"),
("The Battle Is Real","Spiritual warfare without the theatrics","Eph 6:10-18","Do it"),
("Strongholds","Patterns of thought that outlive the events that made them","2 Cor 10:3-5","Own it"),
("Drifting","How people leave the faith slowly, and on purpose","Heb 2:1-3","Sit with it"),
("Waiting","The hardest season to preach and the most common to live","Ps 27:13-14","Sit with it"),
("Disappointed With God","Saying it out loud, in his hearing","Hab 1:1-4","Sit with it"),
("Regret","What to do with the years you cannot get back","Joel 2:25-27","Own it"),
("Carrying It Alone","Why nobody knows, and what it would take to tell one person","Gal 6:1-2","Share it"),
]),
("Money, Work and Stewardship", [
("God Owns It All","Why the first money question is not a money question","1 Chr 29:11-14","See it"),
("How Much Is Enough?","Naming your number before the market names it for you","Eccl 5:10-20","Own it"),
("First, Not Last","What the order of your spending says about what you believe","Prov 3:9-10","Do it"),
("Owe Nothing","A plan for getting out, and what the freedom is actually for","Prov 22:7","Do it"),
("The Rich Fool Had a Retirement Plan","Rereading the parable everybody thinks is about somebody else","Luke 12:13-21","Sit with it"),
("Generous on Purpose","Moving giving from reaction to decision","2 Cor 9:6-8","Do it"),
("The Talents Were Not a Savings Account","Stewardship as risk rather than preservation","Matt 25:14-30","Own it"),
("Money and Marriage","The conversation most couples are quietly avoiding","Amos 3:3","Do it"),
("Teaching Kids About Money","What they learn from you whether you teach them or not","Deut 6:6-9","Do it"),
("Where Your Treasure Is","Why the heart follows the money and not the other way around","Matt 6:19-21","See it"),
("Work Is Not a Curse","Recovering vocation from Genesis","Gen 2:15","See it"),
("Monday Matters","What discipleship looks like at your actual desk","Col 3:23-24","Do it"),
("Called to This Job","Vocation for people who are not in ministry","1 Cor 7:17","Own it"),
("Ambition, Baptized","Wanting more without being owned by it","Jer 45:5","Sit with it"),
("The Generosity Ladder","Five rungs, and honestly locating which one you are on","2 Cor 8:1-15","Own it"),
("Command Those Who Are Rich","A message for the people nobody preaches to","1 Tim 6:17-19","Own it"),
("Margin","Building room into a life that has none","Ex 23:10-11","Do it"),
("What Happens to It Next","The estate decisions you are already making by not making them","Prov 13:22","Do it"),
("The Transfer","Passing money without passing wisdom, and what it costs a family","Eccl 2:18-21","Sit with it"),
("Enough Was Always the Point","Manna, hoarding, and a God who supplies daily","Ex 16:16-20","See it"),
("Out of Work","Faith, identity and provision when the job is gone","Ruth 2:1-12","Sit with it"),
("Retire Toward Something","The last third as a commission rather than a reward","Ps 92:12-15","Own it"),
("Wise With Risk","Deciding when the outcome is genuinely unknown","Prov 21:5","Do it"),
("The Well-Done Life","Living now toward the sentence you want to hear then","Matt 25:21","Deepen it"),
]),
("Family, Marriage and Household", [
("The Legacy Conversation","The talk most families postpone until it is too late","Deut 6:4-9","Share it"),
("One Flesh, Two Histories","What each of you brought that neither of you chose","Gen 2:24","Sit with it"),
("Fight Fair","A method for the argument you are going to have anyway","Eph 4:26-32","Do it"),
("Married and Lonely","Naming the drift before it becomes a decision","Mal 2:13-16","Own it"),
("Single, Not Waiting","A full life that is not a holding pattern","1 Cor 7:32-35","Own it"),
("Dating on Purpose","Questions worth asking before the third month","2 Cor 6:14","Do it"),
("Parenting Past the Rules","Raising a heart and not only a behavior","Eph 6:1-4","Do it"),
("Fathered","What your dad gave you, and what you will do with it","Ps 103:13","Sit with it"),
("The Weight Mothers Carry","Honor, honesty, and the parts nobody photographs","Prov 31:25-30","Sit with it"),
("Teenagers","Staying in the room during the years they leave it","Luke 2:41-52","Do it"),
("Blended","Building one household out of two stories","Ruth 4:13-17","Do it"),
("After the Divorce","Grace, honesty, and what actually comes next","John 4:16-26","Own it"),
("The Empty Room","Marriage after the children go","Ps 71:17-18","Sit with it"),
("Caring for Your Parents","Honor when the roles reverse","1 Tim 5:3-8","Do it"),
("Grandparenting on Purpose","The influence you still have and rarely use","2 Tim 1:5","Do it"),
("Waiting for a Child","Infertility, adoption, and a God who is not absent","1 Sam 1:9-20","Sit with it"),
("A Family Mission Statement","Writing down what your household is actually for","Josh 24:15","Do it"),
("The Family Meeting","Thirty minutes a month that changes a decade","Ps 78:1-8","Do it"),
("Tell Them the Story","Passing on what happened before they were born","Deut 6:20-25","Share it"),
("Your Legacy Letter","Writing the thing your children will read twice","2 Pet 1:12-15","Do it"),
("Home Is a Discipleship Program","You are already running one; the question is which","Deut 11:18-21","See it"),
("Forgiving Your Family","The hardest people in the world to release","Gen 45:1-15","Do it"),
("Desire, Honestly","A theology of sex that is neither prudish nor naive","Song 8:6-7","Sit with it"),
("Four Generations Out","Deciding now what your great-grandchildren inherit","Ps 145:4","Deepen it"),
]),
]
