# -*- coding: utf-8 -*-
# Axis B - Books of the Bible.
# (book, chapters, genre, dominant preaching themes, anchor passages, series potential)

BOOKS = [
("Pentateuch", [
 ("Genesis",50,"Narrative","Creation, image, vocation, fall, covenant, family dysfunction, providence",
  "1:26-28; 3:1-15; 12:1-3; 22:1-14; 50:20",
  "Two natural series: Genesis 1-11 on identity and origins, Genesis 12-50 on covenant and family. The Joseph arc alone carries six weeks."),
 ("Exodus",40,"Narrative / Law","Deliverance, reluctant calling, presence, law, worship, rest",
  "3:1-14; 14:13-14; 20:1-17; 33:12-23; 34:6-7",
  "Deliverance to Sinai is a natural 40-day frame; the Ten Words support a ten-week teaching series."),
 ("Leviticus",27,"Law","Holiness, atonement, sacrifice, clean and unclean, jubilee",
  "11:44-45; 16:1-22; 19:9-18; 25:8-17",
  "Rarely preached and worth a short four-week recovery series on holiness and access."),
 ("Numbers",36,"Narrative / Law","Wilderness, complaint, testing, leadership under strain, blessing",
  "6:24-26; 13:26-33; 14:1-10; 20:1-13",
  "Strong wilderness series for a congregation in a hard season; pairs with Hebrews 3-4."),
 ("Deuteronomy",34,"Sermon / Law","Remembering, covenant renewal, household discipleship, choosing life",
  "6:4-9; 8:1-18; 30:11-20; 31:6",
  "Chapter 6 anchors an entire household-discipleship campaign. Chapter 8 is the definitive prosperity-and-forgetting text."),
]),
("History", [
 ("Joshua",24,"Narrative","Courage, succession, obedience, inheritance, decision",
  "1:1-9; 3:14-17; 6:1-20; 24:14-15",
  "Six weeks on courage and entering; the choose-this-day text is a natural commitment Sunday."),
 ("Judges",21,"Narrative","Cycles of decline, unlikely leaders, gifting without character",
  "2:10-19; 6:11-16; 7:1-8; 21:25",
  "A blunt series on generational drift; Gideon carries four weeks by himself."),
 ("Ruth",4,"Narrative","Loyalty, providence, redemption, grief, covenant kindness",
  "1:16-17; 2:8-12; 3:9-11; 4:13-17",
  "The cleanest four-week book in the Bible, one chapter per week, and a strong series for a grief season."),
 ("1 Samuel",31,"Narrative","Prayer, calling, insecurity, anointing, waiting for the promise",
  "1:9-20; 3:1-10; 15:22-23; 16:7; 17:45-47",
  "David's waiting years are the best available treatment of leading before you are recognized."),
 ("2 Samuel",24,"Narrative","Worship, power, catastrophic failure, repentance, consequence",
  "6:12-22; 7:8-16; 11:1-27; 12:1-14",
  "Chapters 11-12 with Psalm 51 is a four-week integrity series most churches never risk."),
 ("1 Kings",22,"Narrative","Wisdom, temple, divided heart, confrontation, collapse",
  "3:5-14; 8:22-30; 18:20-39; 19:1-18",
  "The Elijah cycle is a five-week series on burnout that speaks directly to pastors."),
 ("2 Kings",25,"Narrative","Succession, reform, exile, the cost of ignoring the Word",
  "2:9-14; 5:1-14; 22:8-13; 25:1-12",
  "Best used in excerpts; Naaman is a standalone message on pride and simple obedience."),
 ("1 Chronicles",29,"Narrative","Genealogy, worship order, generosity, preparing for the next generation",
  "4:9-10; 16:8-36; 28:9-10; 29:10-18",
  "Chapter 29 is arguably the strongest generosity text in the Old Testament and anchors a giving Sunday."),
 ("2 Chronicles",36,"Narrative","Temple, revival, humility, national repentance",
  "7:12-16; 16:9; 20:1-30; 34:1-7",
  "Jehoshaphat's prayer in chapter 20 is a standalone message for a church facing a threat."),
 ("Ezra",10,"Narrative","Return, rebuilding, the recovered Word, opposition",
  "1:1-5; 3:10-13; 7:6-10; 9:5-9",
  "Pairs with Nehemiah into a single eight-week rebuilding series."),
 ("Nehemiah",13,"Narrative","Burden, planning, opposition, leadership, completion",
  "1:1-11; 2:11-18; 4:6-14; 6:1-9; 8:1-12",
  "The most usable leadership book in Scripture and a proven six-week series for a building or capital season."),
 ("Esther",10,"Narrative","Providence, position, courage, timing",
  "4:12-17; 6:1-11; 7:1-6; 9:20-28",
  "Four weeks on stewarding influence; the for-such-a-time text is a vocation message."),
]),
("Wisdom and Poetry", [
 ("Job",42,"Wisdom","Suffering, theodicy, friendship that fails, worship without answers",
  "1:20-22; 2:11-13; 19:25-27; 38:1-11; 42:1-6",
  "A hard six-week series and the right response after a congregational tragedy."),
 ("Psalms",150,"Poetry","Lament, praise, trust, repentance, kingship, the whole emotional range",
  "1; 8; 23; 27; 42; 51; 73; 91; 103; 119; 139",
  "Endlessly seriesable: Psalms of Ascent for a summer, lament for a grief season, Psalm 119 for a Scripture emphasis."),
 ("Proverbs",31,"Wisdom","Wisdom, speech, money, work, friendship, sexual integrity, parenting",
  "1:7; 3:5-10; 4:23; 15:1; 22:6; 31:10-31",
  "A thirty-one-day reading plan and a topical six-week series run naturally together."),
 ("Ecclesiastes",12,"Wisdom","Meaning, vanity, time, enjoyment, limits, death",
  "1:1-11; 3:1-14; 5:10-20; 12:1-14",
  "The best available bridge to a skeptical audience; four weeks on meaning."),
 ("Song of Songs",8,"Poetry","Desire, delight, marriage, covenant love",
  "2:10-13; 4:1-7; 8:6-7",
  "A four-week marriage series with real care taken; not a general-audience default."),
]),
("Major Prophets", [
 ("Isaiah",66,"Prophecy","Holiness, call, servant, comfort, justice, restoration",
  "6:1-8; 9:6-7; 40:28-31; 43:1-3; 53:1-12; 55:1-11; 58:6-12",
  "Three distinct series: the call and holiness (1-12), comfort (40-55), and justice and fasting (58)."),
 ("Jeremiah",52,"Prophecy","Faithfulness without fruit, false hope, new covenant, plans",
  "1:4-10; 17:5-10; 29:10-14; 31:31-34",
  "Chapter 29 needs a corrective message; the whole book supports a series on serving without visible results."),
 ("Lamentations",5,"Poetry","Grief, honest complaint, mercies new every morning",
  "3:19-26; 3:31-33; 5:19-22",
  "A single message or a short Lent series; essential for a church in mourning."),
 ("Ezekiel",48,"Prophecy","Glory, responsibility, dry bones, shepherds, restoration",
  "34:1-16; 36:24-28; 37:1-14; 47:1-12",
  "Chapter 37 is a revival message; chapter 34 is the definitive leadership rebuke."),
 ("Daniel",12,"Narrative / Apocalyptic","Faithfulness in exile, integrity under pressure, prayer, sovereignty",
  "1:8-17; 3:16-18; 6:6-23; 9:1-19",
  "Six weeks on faith in a hostile culture; the strongest workplace-discipleship book in the canon."),
]),
("Minor Prophets", [
 ("Hosea",14,"Prophecy","Covenant love, unfaithfulness, relentless pursuit","1:2-9; 6:1-6; 11:1-9; 14:1-9",
  "Four weeks on the love of God that refuses to quit."),
 ("Joel",3,"Prophecy","Repentance, restoration, outpouring","2:12-17; 2:25-29",
  "Restoring the years the locusts ate is a single strong message."),
 ("Amos",9,"Prophecy","Justice, empty worship, complacency","5:21-24; 6:1-7; 8:11-12",
  "The core justice text; pairs with Isaiah 58 and Micah 6."),
 ("Obadiah",1,"Prophecy","Pride, standing by, the day of the Lord","1:3-4; 1:10-15",
  "One message on the sin of watching."),
 ("Jonah",4,"Narrative","Reluctant mission, mercy, anger at grace","1:1-3; 2:1-9; 3:1-5; 4:1-11",
  "Four chapters, four weeks, and the best missions series that also indicts the missionary."),
 ("Micah",7,"Prophecy","Justice, mercy, humility, Bethlehem","5:2-5; 6:6-8; 7:18-19",
  "Micah 6:8 anchors a values or vision series."),
 ("Nahum",3,"Prophecy","Judgment, refuge, the end of an empire","1:3-7",
  "One message; God as stronghold in the day of trouble."),
 ("Habakkuk",3,"Prophecy","Honest complaint, waiting, faith, joy without harvest","1:1-4; 2:1-4; 3:17-19",
  "Three chapters, three weeks; the finest short series on unanswered prayer."),
 ("Zephaniah",3,"Prophecy","Judgment, humility, the singing God","2:3; 3:14-17",
  "Chapter 3:17 is a standalone message on being delighted in."),
 ("Haggai",2,"Prophecy","Priorities, paneled houses, courage to build","1:2-11; 2:1-9",
  "Two weeks; the definitive text on a stalled building or stalled obedience."),
 ("Zechariah",14,"Prophecy","Return, cleansing, the coming King, small beginnings","4:6-10; 8:1-8; 9:9",
  "Not by might is a vision-Sunday message; despise not small beginnings is a church-plant message."),
 ("Malachi",4,"Prophecy","Half-hearted worship, marriage, tithing, the coming messenger","1:6-14; 2:13-16; 3:6-12; 4:2",
  "Chapter 3 is the most-preached tithing text and needs careful New Testament framing."),
]),
("Gospels and Acts", [
 ("Matthew",28,"Gospel","Kingdom, righteousness, discipleship, the Sermon on the Mount, commission",
  "5:1-16; 6:19-34; 11:28-30; 16:13-20; 25:31-46; 28:16-20",
  "The Sermon on the Mount is a ten-week series on its own; chapter 25 anchors a compassion emphasis."),
 ("Mark",16,"Gospel","Action, authority, servanthood, the cost of following",
  "1:14-20; 8:34-38; 10:35-45; 12:28-34",
  "The fastest gospel to preach straight through; sixteen chapters in sixteen weeks."),
 ("Luke",24,"Gospel","Compassion, the outsider, prayer, money, joy",
  "4:16-21; 10:25-37; 15:1-32; 19:1-10; 24:13-35",
  "Chapter 15 is a three-week series by itself; Luke carries the strongest money material in the Gospels."),
 ("John",21,"Gospel","Belief, I Am, abiding, love, the Spirit, glory",
  "1:1-14; 3:16-21; 10:7-18; 14:1-14; 15:1-17; 20:24-31",
  "The seven I Am statements make a seven-week series; the upper room discourse makes a five-week Lent series."),
 ("Acts",28,"History","Spirit, witness, church formation, opposition, expansion",
  "1:8; 2:1-47; 4:32-37; 9:1-19; 16:6-15; 17:16-34",
  "Chapter 2 anchors a church-vision series; the whole book supports a multiplication campaign."),
]),
("Pauline Letters", [
 ("Romans",16,"Letter","Sin, justification, grace, the Spirit, transformation, unity",
  "1:16-17; 3:21-26; 5:1-11; 8:1-39; 12:1-21",
  "Chapter 8 is a nine-week series; chapters 12-15 are a practical church-life series."),
 ("1 Corinthians",16,"Letter","Unity, wisdom, sexuality, freedom, gifts, love, resurrection",
  "1:18-25; 6:19-20; 10:13; 12:12-27; 13:1-13; 15:50-58",
  "Chapter 13 is a wedding standard and a six-week series on love as practice."),
 ("2 Corinthians",13,"Letter","Comfort, weakness, ministry, generosity, reconciliation",
  "1:3-7; 4:7-18; 5:16-21; 8:1-15; 9:6-15; 12:7-10",
  "Chapters 8 and 9 are the strongest New Testament generosity texts and anchor a giving campaign."),
 ("Galatians",6,"Letter","Freedom, grace versus law, the Spirit, fruit",
  "2:20; 3:26-29; 5:1; 5:16-26; 6:1-10",
  "Six chapters, six weeks; the fruit of the Spirit is a nine-week spin-off."),
 ("Ephesians",6,"Letter","Identity, grace, unity, the church, household, armor",
  "1:3-14; 2:1-10; 3:14-21; 4:1-16; 5:21-33; 6:10-20",
  "The cleanest six-week identity series in the canon and a natural campaign spine."),
 ("Philippians",4,"Letter","Joy, humility, contentment, partnership, peace",
  "1:3-6; 2:1-11; 3:7-14; 4:4-13",
  "Four chapters, four weeks; the best short series for a discouraged congregation."),
 ("Colossians",4,"Letter","Supremacy of Christ, rooted faith, new self, household",
  "1:15-23; 2:6-10; 3:1-17; 3:23-24",
  "Four weeks on the sufficiency of Christ; 3:23 is a workplace message."),
 ("1 Thessalonians",5,"Letter","Hope, holiness, work, grief, the return",
  "1:2-10; 4:11-12; 4:13-18; 5:16-24",
  "Five weeks; chapter 4 is the standard funeral text."),
 ("2 Thessalonians",3,"Letter","Endurance, idleness, standing firm","1:3-12; 3:6-13",
  "Two or three weeks; useful on work and waiting."),
 ("1 Timothy",6,"Letter","Leadership, sound teaching, money, order","3:1-13; 4:11-16; 6:6-19",
  "Chapter 6 is the finest New Testament text on wealth and contentment."),
 ("2 Timothy",4,"Letter","Courage, endurance, Scripture, finishing","1:6-14; 2:1-7; 3:14-17; 4:1-8",
  "Four weeks on finishing well; the best succession series available."),
 ("Titus",3,"Letter","Sound doctrine, good works, grace that trains","2:1-14; 3:3-8",
  "Two or three weeks on character in community."),
 ("Philemon",1,"Letter","Reconciliation, status, the gospel applied to one relationship","1:8-21",
  "A single message with unusual force on forgiveness and social reversal."),
]),
("General Letters", [
 ("Hebrews",13,"Letter","Supremacy of Christ, faith, endurance, rest, community",
  "4:12-16; 10:19-25; 11:1-40; 12:1-3; 13:5-8",
  "Chapter 11 is a six-week faith series; 10:24-25 anchors a small-group launch."),
 ("James",5,"Letter","Trials, wisdom, speech, favoritism, wealth, action",
  "1:2-8; 1:22-25; 2:14-17; 3:1-12; 4:13-17; 5:13-16",
  "Five chapters, five weeks; the most practical book in the New Testament and the best first series for a new believer group."),
 ("1 Peter",5,"Letter","Hope, suffering, identity, exile, humility",
  "1:3-9; 2:9-12; 3:15-16; 4:10-11; 5:6-10",
  "Five weeks on living as exiles; 3:15 is an evangelism message."),
 ("2 Peter",3,"Letter","Growth, false teaching, the promise","1:3-11; 3:8-13",
  "Two weeks; useful on discernment."),
 ("1 John",5,"Letter","Light, love, assurance, obedience, confidence","1:5-10; 3:1-3; 3:16-18; 4:7-21",
  "Five weeks on assurance and love; excellent for a new-believers class."),
 ("2 John",1,"Letter","Truth and love held together","1:4-6",
  "A single message on the pairing most churches split."),
 ("3 John",1,"Letter","Hospitality, support, the local leader","1:2-8",
  "A single message on partnership and welcome."),
 ("Jude",1,"Letter","Contending, mercy, keeping","1:3-4; 1:20-25",
  "One message; the closing doxology is a benediction standard."),
]),
("Apocalyptic", [
 ("Revelation",22,"Apocalyptic","Worship, perseverance, the Lamb, judgment, the new creation",
  "1:12-18; 2:1-7; 3:14-22; 5:1-14; 12:10-11; 21:1-7",
  "The letters to the seven churches are a seven-week series that avoids the timeline fights; chapter 21 is the standard funeral and hope text."),
]),
]
