# -*- coding: utf-8 -*-

CORPUS_2 = [
("Relationships and Community", [
("Two Are Better","Why the Christian life was never designed to be solo","Eccl 4:9-12","See it"),
("Spiritual Partners","One person who knows the truth about your week","James 5:16","Do it"),
("Finding Your People","A practical path out of church-sized loneliness","Acts 2:42-47","Do it"),
("The Table","Hospitality as the most underrated ministry in the building","Rom 12:13","Do it"),
("Say the Hard Thing","Confrontation as an act of love","Matt 18:15-17","Do it"),
("Forgive Anyway","Releasing what you are genuinely owed","Col 3:13","Do it"),
("Reconcile","The step past forgiveness that most people skip","2 Cor 5:18-20","Do it"),
("Boundaries Are Not Unkind","Saying no without leaving","Mark 1:35-38","Do it"),
("Words","What the tongue actually does in a week","James 3:1-12","Own it"),
("Stop Talking About Them","Gossip as the most tolerated sin in the church","Prov 16:28","Own it"),
("Encourage Somebody","Barnabas made a career out of it","Acts 4:36-37","Do it"),
("One Another","Fifty-nine commands, and the twelve most churches never practice","John 13:34-35","Do it"),
("Unity Is Not Agreement","Staying together across real difference","Eph 4:1-6","Sit with it"),
("Who Is Discipling You","Naming the person ahead of you and the person behind you","2 Tim 2:2","Do it"),
("Mentor Somebody","What you know was never yours to keep","Titus 2:1-8","Share it"),
("Show Up","Presence as the ministry nobody trains for","Job 2:11-13","Do it"),
("Small Group, Real Life","What happens when a group stops performing","Gal 6:2","Do it"),
("Host, Do Not Teach","Why the leader you are looking for is easier to find than you think","Luke 10:38-42","Do it"),
("The Friend Who Left","Grieving a friendship that ended","2 Tim 4:9-16","Sit with it"),
("Different, Not Wrong","Loving people who are not like you","Rom 15:5-7","Sit with it"),
("Carry It Together","Bearing a burden that is not yours","Gal 6:1-5","Do it"),
("Ask Better Questions","Six questions that get past how are you","Prov 20:5","Do it"),
("New Friends at Sixty","Building community late, on purpose","Prov 27:17","Do it"),
("A Room Worth Belonging To","Building it before you invite anybody into it","1 Thess 2:8","Deepen it"),
]),
("Mission, Evangelism and Justice", [
("Your Story in Three Minutes","Before, during, after, and where to stop","1 Pet 3:15","Share it"),
("Invite One Person","The lowest-friction evangelism there is","John 1:43-46","Do it"),
("The Invisible Neighbor","Who lives within a hundred yards, and what you know about them","Luke 10:25-37","Do it"),
("Witness at Work","Integrity before words","Col 4:5-6","Do it"),
("Go","The commission as a comma, not a period","Matt 28:16-20","Do it"),
("The Woman at the Well","A conversation model for people who hate confrontation","John 4:1-30","Do it"),
("Justice Is Not a Wing of the Church","Micah, Amos and Isaiah say the same thing","Micah 6:6-8","See it"),
("The Fast God Chooses","Worship joined to the chains you loosen","Isa 58:6-12","Own it"),
("The Least of These","A sermon about the sheep who thought they were goats","Matt 25:31-46","Sit with it"),
("Widows and Orphans","The oldest measure of real religion","James 1:27","Do it"),
("The Poor Are Not a Project","Proximity before programs","Luke 14:12-14","Sit with it"),
("Athens","Speaking to people who share none of your assumptions","Acts 17:16-34","Do it"),
("Sent Where You Already Are","Mission without a passport","Jer 29:4-7","Own it"),
("Persecuted","What Christians elsewhere are paying, and what we owe them","Heb 13:3","See it"),
("Across the Line","A hard conversation the church keeps postponing","Eph 2:14-18","Sit with it"),
("Every Life","A theology of human dignity from Genesis to Revelation","Ps 139:13-16","See it"),
("Keep the Garden","Creation care without the culture war","Gen 2:15","See it"),
("The Question Behind the Question","Apologetics for a congregation, not a debate","Col 4:6","Do it"),
("Send Somebody","What it actually takes to launch a person","Acts 13:1-3","Do it"),
("Bring a Friend Sunday","Designing a service for the person who is not here yet","1 Cor 14:24-25","Do it"),
("Mercy Has a Face","Naming one person before naming a cause","Luke 10:33","Do it"),
("The Party Came First","Matthew threw one before anybody preached","Luke 5:27-32","Do it"),
("Pray for the City","Seeking the welfare of a place you did not choose","Jer 29:7","Do it"),
("A Church That Sends","Measuring by who leaves rather than who stays","Acts 13:1-3","Deepen it"),
]),
("The Church", [
("Not a Building","What the word meant to the people who first heard it","1 Cor 12:12-27","See it"),
("Your Gift Is Not Optional","Finding it, naming it, using it","Rom 12:4-8","Do it"),
("Members, Not Attenders","The difference belonging actually makes","Eph 2:19-22","Own it"),
("Serve Somewhere","The Sunday that turns a consumer into a contributor","1 Pet 4:10-11","Do it"),
("The Leaders We Do Not Have Yet","Building a pipeline instead of making a plea","2 Tim 2:2","Do it"),
("Elders and Deacons","What Scripture asks of the people we appoint","1 Tim 3:1-13","See it"),
("Volunteer Culture","Why people stay, and the three reasons they quit","Ex 18:13-26","Do it"),
("Pray Together","Recovering the meeting we quietly cancelled","Acts 4:23-31","Do it"),
("Vision Sunday","What this church is for, said once a year without apology","Prov 29:18","See it"),
("Aligned","One idea, six ministries, one week","Neh 4:6","Do it"),
("Back to Church","An honest invitation to people who stopped coming","Heb 10:24-25","Share it"),
("Revive Us","Praying for the thing that cannot be programmed","2 Chr 7:14","Sit with it"),
("Plant","Multiplication as obedience rather than ambition","Acts 13:1-3","Do it"),
("Kids Are the Church Now","Not the church of tomorrow","Mark 10:13-16","See it"),
("Students Are Not a Holding Pen","Ministry that treats teenagers as capable","1 Tim 4:12","Do it"),
("Worship Is Not the Music","Recovering a word we shrank","Rom 12:1","See it"),
("The Shepherds Get a Sermon Too","Ezekiel 34, read to a staff","Ezek 34:1-16","Sit with it"),
("Healthy Grows","Why health and not size is the metric","Eph 4:11-16","See it"),
("Assign the Work","What Nehemiah knew about who builds which section","Neh 3:1-32","Do it"),
("When the Church Hurt You","Naming it without leaving","2 Cor 2:5-11","Sit with it"),
("Build","Courage for a congregation facing a capital decision","Haggai 1:2-11","Do it"),
("The Small Church Advantage","What two hundred can do that two thousand cannot","Zech 4:10","Own it"),
("Hand It Over","Succession as an act of faith","Josh 1:1-9","Deepen it"),
("A Hundred Years From Now","Building something that outlives the founder","Ps 78:5-7","Deepen it"),
]),
("Scripture and Doctrine", [
("Why You Can Trust It","How the Bible came to you, and what that means","2 Tim 3:14-17","See it"),
("Read the Whole Thing","A year plan and a method that survives February","Josh 1:8","Do it"),
("One Story","Sixty-six books moving in one direction","Luke 24:44-49","See it"),
("What This Verse Actually Means","Basic interpretation for people who are not scholars","2 Tim 2:15","Do it"),
("Law and Grace","Holding both without collapsing either","Rom 6:14-15","Sit with it"),
("Justified","A courtroom word that changes a Monday","Rom 5:1-5","Own it"),
("Who the Holy Spirit Is","The member of the Trinity most churches under-teach","John 14:15-27","See it"),
("Heaven Is Not the End","New heavens, new earth, and why it matters now","Rev 21:1-5","See it"),
("Hell","Teaching the doctrine we would rather skip","Matt 25:41-46","Sit with it"),
("The Parables Were Not Simple","Stories designed to divide a crowd","Mark 4:10-12","Sit with it"),
("The Sermon on the Mount","The manifesto, read as one piece","Matt 5-7","Sit with it"),
("The Beatitudes","Eight sentences that invert every measure of a good life","Matt 5:1-12","Sit with it"),
("Miracles","What they were for, and what they were not","John 20:30-31","See it"),
("Angels and Demons","A sober treatment of what Scripture actually says","Heb 1:14","See it"),
("In the Beginning","Genesis 1 without the fight","Gen 1:1-2:3","See it"),
("Faith and the Lab","Christians who do science, and the questions they live with","Ps 19:1-4","Sit with it"),
("Why Does God Allow It","Suffering, sovereignty and the honest limits of an answer","Job 38:1-11","Sit with it"),
("Chosen","Election taught pastorally rather than polemically","Eph 1:3-14","Sit with it"),
("The Return","Readiness rather than timelines","Matt 24:36-44","Own it"),
("Bodies Matter","Resurrection of the dead, and what it says about now","1 Cor 15:35-49","See it"),
("What We Believe","A six-session doctrine survey for membership","Jude 1:3","Do it"),
("Old Testament in One Sitting","Thirty-nine books, one arc, ninety minutes","Neh 8:1-12","See it"),
("Covenant","The word that organizes the whole Bible","Jer 31:31-34","See it"),
("Teach Somebody Else","You do not know it until you have handed it over","Neh 8:8","Bring it back"),
]),
("Culture, Doubt and Contested Questions", [
("Faith in the Age of AI","Discernment for a technology that talks back","Gen 1:26-28","Sit with it"),
("Attention Is Formation","You are becoming what you look at","Rom 12:2","Own it"),
("Deconstruction","Staying in the room with people taking their faith apart","Mark 9:24","Sit with it"),
("Ancient Practices, Distracted Age","Old disciplines for a genuinely new problem","Jer 6:16","Do it"),
("Men and Purpose","A message for the half of the room that stopped coming","1 Cor 16:13-14","Own it"),
("Curious to Committed","The path from interested to all in","John 1:35-51","Do it"),
("The Upside-Down Kingdom","Every value Jesus reversed on purpose","Matt 20:20-28","See it"),
("Politics Without Idolatry","Citizenship held at the right depth","Phil 3:20","Sit with it"),
("Loneliness Is a Public Health Problem","And the church already owns the answer","Gen 2:18","See it"),
("Mental Health and Faith","Ending the false choice between prayer and treatment","Ps 34:17-18","Sit with it"),
("Rest in a Speed Culture","Sabbath as counterculture","Mark 2:27","Do it"),
("Enough of Everything","Consumerism as a discipleship problem","Luke 12:15","Own it"),
("Identity","Where the self comes from, and who gets to say","Ps 139:13-16","Sit with it"),
("Conviction and Kindness","Talking about sexuality without shouting","Eph 4:15","Sit with it"),
("Success","Ambition audited against a different scoreboard","Matt 16:26","Own it"),
("What About Suffering","The question every skeptic asks first","Rom 8:18-25","Sit with it"),
("Is It Even True","The evidence, honestly presented","1 Cor 15:3-8","See it"),
("The Church Failed Somebody","Speaking about scandal from the platform","1 Pet 4:17","Sit with it"),
("Screens and Children","A household policy grounded in something","Prov 4:23","Do it"),
("What Owns You","Freedom, wisdom, and the substances nobody discusses","1 Cor 6:12","Own it"),
("Say It Once a Year","Naming pornography from the platform, without shame","Ps 51:1-12","Own it"),
("The Odds","A quiet addiction the church rarely names","Prov 13:11","Own it"),
("Kingdom Is Not Country","Distinguishing the two without insulting either","John 18:36","Sit with it"),
("Belonging Before Believing","Making room for people who are not there yet","Luke 15:1-2","Do it"),
]),
("Seasons of Life", [
("Dedicated","A parent's promise, not a child's ceremony","1 Sam 1:26-28","Do it"),
("First Day","Blessing children, teachers and a nervous household","Num 6:24-26","Do it"),
("Graduation","Sending them with more than advice","1 Tim 4:12","Share it"),
("Leaving Home","Faith that survives the first year away","Dan 1:8","Own it"),
("Twenty-Something","Direction while everything is still open","Prov 3:5-6","Sit with it"),
("The Job Ended","Identity when the title goes","Ruth 1:19-22","Sit with it"),
("Starting Over at Forty","Second acts, and the God of them","Ex 3:1-10","Own it"),
("Midlife, Honestly","The questions that arrive uninvited","Eccl 3:9-14","Sit with it"),
("The Diagnosis","Faith on the day the news comes","Ps 46:1-3","Sit with it"),
("Caring for Somebody Who Is Dying","Presence, exhaustion and grace","John 11:32-36","Sit with it"),
("The Last Third","Retirement as a commission","Ps 71:17-18","Own it"),
("Aging Is Not a Problem to Solve","Dignity, usefulness and the long view","Ps 92:12-15","Sit with it"),
("Widowed","The first year, told honestly","Ruth 1:16-17","Sit with it"),
("When a Child Dies","A church that laments before it explains","2 Sam 12:15-23","Sit with it"),
("Sudden","Faith after an accident, a call, a knock at the door","Ps 46:10","Sit with it"),
("The Funeral You Are Planning","Talking about your own death while you still can","Ps 90:12","Do it"),
("Finish Well","A plan for the last twenty years","2 Tim 4:6-8","Deepen it"),
("Write It Down","The legacy letter your family will read twice","2 Pet 1:13-15","Do it"),
("The Anniversary Nobody Mentions","Grief on the date it happened","Ps 56:8","Sit with it"),
("Moving","Faith when the address changes","Gen 12:1-4","Own it"),
("Wedding Day","What you are actually promising","Eccl 4:9-12","Do it"),
("The Empty Chair at Christmas","Holidays after a loss","Isa 61:1-3","Sit with it"),
("Retirement Party","Blessing somebody into the next assignment","Num 27:18-23","Share it"),
("One Hundred Years","A whole life laid end to end","Ps 90:1-17","Deepen it"),
]),
]

# 66 book-by-book series titles: (Book, Title, Subtitle, Length)
BOOK_SERIES = [
("Genesis","In the Beginning of Everything","Origins, family, and a God who keeps showing up","10 weeks"),
("Exodus","Out","Deliverance, law, and the God who moves in","10 weeks"),
("Leviticus","Holy","Access, atonement, and why the details mattered","4 weeks"),
("Numbers","The Long Way Around","Wilderness, complaint, and the generation that waited","6 weeks"),
("Deuteronomy","Remember","A leader's last sermon and the household it was built for","6 weeks"),
("Joshua","Cross Over","Courage, inheritance, and the choice at the end","6 weeks"),
("Judges","Everyone Did as He Saw Fit","What happens when a generation forgets","6 weeks"),
("Ruth","Four Chapters, One Redemption","Loyalty in the worst year of a family's life","4 weeks"),
("1 Samuel","Before the Crown","Waiting, anointing, and leading before you are recognized","8 weeks"),
("2 Samuel","The Best and Worst of David","Worship, power, failure, and repentance that held","8 weeks"),
("1 Kings","Divided","Wisdom squandered, and a prophet under a tree","8 weeks"),
("2 Kings","Decline","Reform, exile, and the cost of ignoring the Word","6 weeks"),
("1 Chronicles","Everything Comes From You","Worship, order, and the great ownership prayer","5 weeks"),
("2 Chronicles","If My People","Revival, humility, and a nation's turn","6 weeks"),
("Ezra","Back","Return, rebuilding, and the rediscovered Word","4 weeks"),
("Nehemiah","Fifty-Two Days","Burden, plan, opposition, completion","6 weeks"),
("Esther","For Such a Time","Position as stewardship","4 weeks"),
("Job","No Answer, Only Presence","Suffering, friends who failed, worship without explanation","6 weeks"),
("Psalms","The Whole Range","A book with room for everything you actually feel","8 weeks"),
("Proverbs","Wise","Money, words, work, desire and friendship in thirty-one chapters","6 weeks"),
("Ecclesiastes","Everything, and Then What","Meaning for people who have tried the alternatives","4 weeks"),
("Song of Songs","Desire, Rightly Ordered","A theology of delight inside covenant","4 weeks"),
("Isaiah","Holy, Comfort, Servant","Three movements through the largest prophet","10 weeks"),
("Jeremiah","Faithful Without Fruit","Serving God when nothing visibly changes","6 weeks"),
("Lamentations","New Every Morning","Grief with a floor underneath it","3 weeks"),
("Ezekiel","Dry Bones","Glory, responsibility, and a valley that came back","6 weeks"),
("Daniel","Faithful in Babylon","Sixty years of integrity inside a hostile system","6 weeks"),
("Hosea","He Would Not Let Go","Covenant love that refuses to quit","4 weeks"),
("Joel","The Years the Locusts Ate","Repentance, restoration, outpouring","3 weeks"),
("Amos","Let Justice Roll","Worship God will not accept","4 weeks"),
("Obadiah","Standing By","The sin of watching","1 week"),
("Jonah","The Reluctant One","Four chapters, and the prophet is the problem","4 weeks"),
("Micah","Act, Love, Walk","Eight words that could organize a whole church","4 weeks"),
("Nahum","A Stronghold in Trouble","Judgment and refuge in the same breath","2 weeks"),
("Habakkuk","How Long","Honest complaint that ends in singing","3 weeks"),
("Zephaniah","He Sings Over You","Judgment, humility, and a delighted God","2 weeks"),
("Haggai","Paneled Houses","Priorities, and the building that stalled","2 weeks"),
("Zechariah","Not by Might","Small beginnings and a coming King","5 weeks"),
("Malachi","Test Me","Half-hearted worship and the last word before silence","4 weeks"),
("Matthew","The Kingdom Is Here","Righteousness, discipleship, and the commission","12 weeks"),
("Mark","Immediately","The fastest Gospel, and the cost it names","16 weeks"),
("Luke","For Everyone Else","Compassion, money, prayer, and the people nobody counted","12 weeks"),
("John","That You May Believe","Seven signs, seven I Ams, one claim","10 weeks"),
("Acts","To the Ends of the Earth","What the Spirit did with ordinary people","10 weeks"),
("Romans","No Condemnation","Sin, grace, the Spirit, and a transformed life","12 weeks"),
("1 Corinthians","A Church With Problems","Unity, freedom, gifts, and love","10 weeks"),
("2 Corinthians","Jars of Clay","Weakness, comfort, generosity, and a thorn","8 weeks"),
("Galatians","Free","Grace against every attempt to earn it","6 weeks"),
("Ephesians","Who You Are Now","Identity, unity, household, armor","6 weeks"),
("Philippians","Joy From Prison","Contentment written by a man in chains","4 weeks"),
("Colossians","Christ Is Enough","Supremacy, roots, and the new self","4 weeks"),
("1 Thessalonians","Waiting Well","Hope, holiness, work, and grief","5 weeks"),
("2 Thessalonians","Stand Firm","Endurance, and the problem of idleness","3 weeks"),
("1 Timothy","How a Church Works","Leadership, teaching, money, order","6 weeks"),
("2 Timothy","Finish","A last letter about courage and succession","4 weeks"),
("Titus","Grace That Trains","Doctrine you can see in somebody's behavior","3 weeks"),
("Philemon","One Relationship","The gospel applied to a single fracture","1 week"),
("Hebrews","Better","Supremacy, faith, endurance, and the room you cannot skip","10 weeks"),
("James","Do Something","The most practical book in the New Testament","5 weeks"),
("1 Peter","Exiles","Hope and identity for people who do not fit","5 weeks"),
("2 Peter","Grow, and Do Not Be Fooled","Maturity and discernment","3 weeks"),
("1 John","How You Know","Assurance, light, and love","5 weeks"),
("2 John","Truth and Love","Holding both without dropping either","1 week"),
("3 John","Welcome Them","Hospitality, support, and the local leader","1 week"),
("Jude","Contend, and Have Mercy","A short letter with a famous ending","1 week"),
("Revelation","Worthy","Seven churches, one Lamb, a new city","10 weeks"),
]
