# -*- coding: utf-8 -*-
# Axis C - the anchor passage index, grouped by preaching function rather than
# canonical order. A passage can legitimately appear under two functions; where
# it does, the second listing is marked with a dagger in the build.

PASSAGE_GROUPS = [
("Gospel and Salvation", [
 ("John 3:16-21","The single most-preached text in the English-speaking church."),
 ("Romans 3:21-26","Justification stated in its densest form."),
 ("Romans 5:6-11","While we were still sinners; the timing of grace."),
 ("Romans 6:23","The wage and the gift set side by side."),
 ("Romans 10:9-13","Confession and belief; the standard invitation text."),
 ("Ephesians 2:1-10","Dead, loved, raised, seated; grace and works resolved."),
 ("Titus 3:3-8","Not because of righteous things we had done."),
 ("1 Peter 3:18","The righteous for the unrighteous, in one sentence."),
 ("Isaiah 53:1-12","The suffering servant; the Good Friday spine."),
 ("Luke 15:11-32","The running father; the parable that reframes repentance."),
 ("Acts 4:12","Exclusivity stated plainly; needs pastoral care in delivery."),
 ("2 Corinthians 5:16-21","New creation and the ministry of reconciliation."),
]),
("Identity and Assurance", [
 ("Genesis 1:26-28","Image and vocation; the floor under all human dignity."),
 ("Psalm 139:1-18","Known, formed, followed; the anti-anxiety text."),
 ("John 1:12-13","The right to become children of God."),
 ("Romans 8:1-4","No condemnation; the release valve of the New Testament."),
 ("Romans 8:31-39","Nothing can separate; the standard funeral and crisis text."),
 ("Galatians 2:20","Crucified with Christ; identity as substitution."),
 ("Ephesians 1:3-14","Chosen, adopted, sealed."),
 ("Colossians 3:1-4","Hidden with Christ; where your life actually is."),
 ("1 John 3:1-3","See what great love; the assurance text for the doubting."),
 ("1 Peter 2:9-12","Chosen people, royal priesthood; corporate identity."),
]),
("Comfort, Fear and Grief", [
 ("Psalm 23","The most requested passage in pastoral ministry."),
 ("Psalm 27:1-6","The Lord is my light; fear answered with presence."),
 ("Psalm 34:17-19","Close to the brokenhearted."),
 ("Psalm 42","Why so downcast; permission to speak to your own soul."),
 ("Psalm 46:1-11","Be still; the crisis-Sunday text."),
 ("Psalm 121","Where does my help come from."),
 ("Isaiah 41:10","Do not fear, for I am with you."),
 ("Isaiah 43:1-3","Through the waters; the text for a congregation in trouble."),
 ("Lamentations 3:19-26","New every morning; grief that ends in hope."),
 ("Matthew 11:28-30","Come to me; the burnout text."),
 ("John 14:1-6","Do not let your hearts be troubled; the funeral standard."),
 ("2 Corinthians 1:3-7","Comfort received becomes comfort given."),
 ("1 Thessalonians 4:13-18","Grief, but not as those without hope."),
 ("Revelation 21:1-7","No more death or mourning; the closing hope text."),
]),
("Call, Courage and Decision", [
 ("Joshua 1:6-9","Be strong and courageous; the standard commissioning text."),
 ("Joshua 24:14-15","Choose this day; the commitment-Sunday text."),
 ("1 Samuel 16:7","The Lord looks at the heart."),
 ("Esther 4:12-17","For such a time as this."),
 ("Isaiah 6:1-8","Here am I, send me; the call-and-holiness text."),
 ("Jeremiah 1:4-10","Before I formed you; the young-leader text."),
 ("Matthew 4:18-22","Follow me and I will make you."),
 ("Luke 9:23-25","Take up your cross daily."),
 ("Acts 1:8","You will be my witnesses; the mission mandate."),
 ("2 Timothy 1:6-7","Fan into flame; not a spirit of fear."),
]),
("Formation and Character", [
 ("Deuteronomy 6:4-9","Impress them on your children; the household mandate."),
 ("Psalm 1","The tree by the water; the formation image."),
 ("Psalm 119:9-16","How can a young person stay pure."),
 ("Proverbs 3:5-6","Trust in the Lord with all your heart."),
 ("Proverbs 4:23","Guard your heart, for everything flows from it."),
 ("Matthew 5:1-16","The Beatitudes; salt and light."),
 ("Matthew 6:19-24","Treasure, eye, masters; the formation of desire."),
 ("Romans 12:1-2","Living sacrifice; do not conform."),
 ("Galatians 5:16-26","The fruit of the Spirit as a single cluster."),
 ("Ephesians 4:22-32","Put off, be renewed, put on."),
 ("Philippians 4:8-9","Whatever is true; attention as discipleship."),
 ("Colossians 3:12-17","Clothe yourselves; the community wardrobe."),
 ("James 1:22-25","Do not merely listen; the mirror text."),
 ("2 Peter 1:3-11","Add to your faith; the growth ladder."),
]),
("Prayer and Practice", [
 ("1 Chronicles 4:9-10","The prayer of Jabez; use with care and context."),
 ("Psalm 51:1-17","Create in me a clean heart; the repentance standard."),
 ("Isaiah 40:28-31","Those who hope in the Lord will renew their strength."),
 ("Isaiah 58:6-12","The fast the Lord chooses; fasting joined to justice."),
 ("Matthew 6:5-15","The Lord's Prayer; a six-week series on its own."),
 ("Mark 1:35","Very early in the morning; the practice text."),
 ("Luke 11:1-13","Ask, seek, knock; persistence in prayer."),
 ("John 15:1-8","Abide in me; the definitive text on remaining."),
 ("Philippians 4:4-7","Do not be anxious; prayer as the anxiety protocol."),
 ("Colossians 3:16","Let the word dwell richly."),
 ("James 5:13-16","Prayer for the sick and confession to one another."),
]),
("Money, Work and Stewardship", [
 ("Deuteronomy 8:11-18","Remember the Lord; the prosperity-and-forgetting text."),
 ("1 Chronicles 29:10-18","Everything comes from you; the great ownership prayer."),
 ("Proverbs 3:9-10","Honor the Lord with your wealth and firstfruits."),
 ("Proverbs 22:7","The borrower is slave to the lender."),
 ("Ecclesiastes 5:10-20","Whoever loves money never has enough."),
 ("Malachi 3:6-12","Bring the whole tithe; requires New Testament framing."),
 ("Matthew 6:19-21","Where your treasure is; the heart-follows-money text."),
 ("Matthew 25:14-30","The talents; stewardship as risk, not preservation."),
 ("Luke 12:13-21","The rich fool; the retirement and enough text."),
 ("Luke 16:10-13","Faithful with little; you cannot serve both."),
 ("Luke 19:1-10","Zacchaeus; restitution as evidence of conversion."),
 ("Acts 2:44-47","They had everything in common."),
 ("2 Corinthians 8:1-15","The Macedonian churches; joy in poverty."),
 ("2 Corinthians 9:6-15","Cheerful giver; sowing and reaping."),
 ("1 Timothy 6:6-10","Godliness with contentment is great gain."),
 ("1 Timothy 6:17-19","Command those who are rich; the high-capacity text."),
 ("Colossians 3:23-24","Whatever you do, work at it with all your heart."),
]),
("Marriage, Family and Household", [
 ("Genesis 2:18-25","One flesh; the marriage foundation."),
 ("Joshua 24:15","As for me and my household."),
 ("Psalm 127:1-5","Unless the Lord builds the house; children as heritage."),
 ("Psalm 78:1-8","Tell the next generation; the legacy mandate."),
 ("Proverbs 22:6","Start children off on the way they should go."),
 ("Proverbs 31:10-31","A wife of noble character; handle with care."),
 ("Malachi 2:13-16","The covenant of marriage and the God who hates divorce."),
 ("Matthew 19:4-6","What God has joined together."),
 ("1 Corinthians 13:1-13","Love is patient; the wedding standard."),
 ("Ephesians 5:21-33","Mutual submission and Christ-shaped marriage."),
 ("Ephesians 6:1-4","Children, parents, and exasperation."),
 ("Colossians 3:18-21","The household code in its shortest form."),
 ("1 Timothy 5:8","Providing for your own household."),
 ("2 Timothy 1:5","The faith of Lois and Eunice; generational transfer."),
]),
("Community and Forgiveness", [
 ("Ecclesiastes 4:9-12","Two are better than one; the small-group text."),
 ("Matthew 18:15-20","If your brother sins against you; the conflict protocol."),
 ("Matthew 18:21-35","Seventy-seven times; the unmerciful servant."),
 ("John 13:34-35","By this everyone will know."),
 ("Acts 2:42-47","Devoted to teaching, fellowship, breaking bread, prayer."),
 ("Romans 12:9-21","Love must be sincere; the practical community list."),
 ("Romans 15:5-7","Accept one another as Christ accepted you."),
 ("1 Corinthians 12:12-27","One body, many parts."),
 ("Galatians 6:1-10","Restore gently; carry each other's burdens."),
 ("Ephesians 4:1-16","Unity, gifts, and growing into maturity together."),
 ("Hebrews 10:24-25","Spur one another on; the gathering text."),
 ("James 3:1-12","The tongue; the most practical relational passage."),
 ("1 John 4:7-21","Love one another; perfect love drives out fear."),
]),
("Mission, Justice and Witness", [
 ("Isaiah 58:6-12","Loose the chains of injustice."),
 ("Micah 6:6-8","Act justly, love mercy, walk humbly."),
 ("Amos 5:21-24","Let justice roll on like a river."),
 ("Matthew 5:13-16","Salt and light; visible witness."),
 ("Matthew 25:31-46","Whatever you did for the least of these."),
 ("Matthew 28:16-20","The Great Commission."),
 ("Luke 4:16-21","The Nazareth manifesto."),
 ("Luke 10:25-37","The Good Samaritan; who is my neighbor."),
 ("John 4:1-42","The woman at the well; the conversational model."),
 ("Acts 17:16-34","Paul at Athens; cultural engagement."),
 ("Romans 10:14-15","How can they hear without someone preaching."),
 ("1 Peter 3:15-16","Always be prepared to give a reason, with gentleness."),
]),
("Suffering and Endurance", [
 ("Job 1:20-22","Naked I came; worship in loss."),
 ("Job 42:1-6","My ears had heard; the resolution that is not an explanation."),
 ("Psalm 13","How long, Lord; lament with a turn."),
 ("Psalm 73","Until I entered the sanctuary; the envy text."),
 ("Habakkuk 3:17-19","Though the fig tree does not bud; joy without harvest."),
 ("John 11:17-44","Jesus wept; delay and resurrection."),
 ("Romans 5:3-5","Suffering produces perseverance."),
 ("2 Corinthians 4:7-18","Jars of clay; light and momentary."),
 ("2 Corinthians 12:7-10","My grace is sufficient; the thorn."),
 ("Hebrews 12:1-3","Run with perseverance; fix your eyes."),
 ("James 1:2-8","Consider it pure joy; wisdom in trials."),
 ("1 Peter 4:12-19","Do not be surprised at the fiery ordeal."),
]),
("Hope and Last Things", [
 ("Isaiah 65:17-25","New heavens and a new earth."),
 ("Daniel 12:1-3","Those who lead many to righteousness."),
 ("Matthew 24:36-44","No one knows the day; readiness over speculation."),
 ("John 5:24-29","Crossed over from death to life."),
 ("1 Corinthians 15:50-58","The last trumpet; your labor is not in vain."),
 ("Philippians 1:21-26","To live is Christ, to die is gain."),
 ("2 Timothy 4:6-8","I have fought the good fight; the finishing text."),
 ("Revelation 5:1-14","Worthy is the Lamb."),
 ("Revelation 21:1-7","He will wipe every tear."),
 ("Revelation 22:1-5","The river, the tree, and no more curse."),
]),
]

# Axis D - Occasion and Season registers.

CHRISTIAN_YEAR = [
 ("Advent","Four Sundays before Christmas","Hope, peace, joy, love; waiting and arrival",
  "The single best on-ramp of the year. A four-week series plus a household devotional reaches people who attend nothing else."),
 ("Christmas Eve","December 24","Incarnation, light in darkness, welcome",
  "Highest guest attendance of the year alongside Easter. Design for the guest, not the member."),
 ("Christmas Day / Christmastide","December 25 - January 5","Incarnation, family, the Word made flesh",
  "Low attendance, high intimacy; a good week for a household-centered resource instead of a full service."),
 ("Epiphany","January 6","Revelation to the nations, the wise men, light",
  "Underused. A natural missions or vision launch."),
 ("New Year","First Sunday of January","Renewal, direction, commitment, habits",
  "The highest-intent Sunday of the year for a formation campaign. Launch here or lose the window."),
 ("Ash Wednesday","Start of Lent","Mortality, repentance, dust",
  "A short evening service with enormous formational weight for the small group that attends."),
 ("Lent","Forty days before Easter","Repentance, self-examination, fasting, following",
  "The natural home of a forty-day churchwide campaign; the calendar has already done the framing."),
 ("Palm Sunday","Sunday before Easter","Kingship, expectation, the crowd that turns",
  "The pivot into Holy Week; often the best-attended non-Easter spring Sunday."),
 ("Maundy Thursday","Thursday of Holy Week","Servanthood, the table, the new command",
  "Communion and footwashing; high impact with small numbers."),
 ("Good Friday","Friday of Holy Week","Atonement, suffering, the cross",
  "Do not soften. The contrast is what makes Sunday land."),
 ("Easter","Resurrection Sunday","Resurrection, hope, new life, invitation",
  "The largest guest audience of the year and the weakest follow-up in most churches. Plan the next step before planning the service."),
 ("Eastertide","Fifty days after Easter","Appearances, commissioning, joy",
  "The best-timed and least-used season for a new-believers pathway."),
 ("Ascension","Forty days after Easter","Authority, commission, the waiting",
  "One message; pairs naturally with Acts 1."),
 ("Pentecost","Fifty days after Easter","Spirit, power, the birth of the church",
  "A church-vision Sunday and the right week to launch groups."),
 ("Trinity Sunday","Sunday after Pentecost","The nature of God",
  "One theologically weighty message; a good annual doctrinal anchor."),
 ("Ordinary Time","Summer and autumn","Discipleship, wisdom, the long walk",
  "The stretch where most catalogs go quiet and where sustained book-by-book teaching belongs."),
 ("All Saints","November 1","Remembrance, the cloud of witnesses, legacy",
  "A strong and underused legacy Sunday for a congregation with an aging membership."),
 ("Christ the King","Last Sunday before Advent","Kingship, allegiance, the end of the story",
  "Closes the year; pairs with a commitment or generosity moment."),
]

CIVIL_CALENDAR = [
 ("New Year's Day","Renewal, goals, direction","Campaign launch window."),
 ("Martin Luther King, Jr. Day","Justice, reconciliation, dignity","Requires local specificity to avoid abstraction."),
 ("Valentine's Day","Love, marriage, singleness","Marriage series launch; do not neglect the single half of the room."),
 ("Super Bowl Sunday","Community, teamwork, competition","Low attendance; a good week for a group gathering rather than a big service push."),
 ("Mother's Day","Motherhood, honor, grief, longing","Third-highest attendance Sunday. Handle infertility and loss explicitly or lose people."),
 ("Memorial Day","Sacrifice, remembrance, freedom","Attendance dips; brief and honest is better than elaborate."),
 ("Father's Day","Fatherhood, presence, legacy","Best men's-ministry on-ramp of the year."),
 ("Independence Day","Freedom, citizenship, gratitude","Theological care required; distinguish nation from kingdom."),
 ("Back to School","Transition, anxiety, blessing","Blessing of backpacks and teachers; strong family touchpoint."),
 ("Labor Day","Work, vocation, rest","The natural launch for a vocation or workplace series."),
 ("Harvest / Halloween","Light and dark, neighboring, hospitality","The single best neighboring event of the year."),
 ("Veterans Day","Service, sacrifice, honor","Brief recognition; pastoral care for the wounded."),
 ("Thanksgiving","Gratitude, provision, generosity","The natural launch of a generosity emphasis running into year-end."),
 ("Year-End Giving","Generosity, stewardship, completion","The last two weeks of December carry a disproportionate share of annual giving."),
]

CHURCH_OCCASIONS = [
 ("Baptism Sunday","Monthly rather than a few times a year; staff to volunteers to group leaders; supply the shorts, towel and shirt so nobody has an excuse."),
 ("Communion","Whatever the cadence, treat it as formation rather than an appendix to the service."),
 ("Baby Dedication","A parent-facing commitment, not a child-facing ceremony; pair with a household-discipleship resource."),
 ("Membership / Covenant Sunday","Ties directly to the classes-and-courses track; the front door of belonging."),
 ("Vision Sunday","Once a year, non-negotiable, and never combined with a budget appeal."),
 ("Commitment Sunday","The response mechanism the whole campaign has been building toward."),
 ("Small Group Launch","Twice a year, aligned to a campaign; never a standing invitation."),
 ("Ministry Fair / Serve Sunday","Pair with a spiritual-gifts message the same morning, not a month earlier."),
 ("Volunteer Appreciation","Cheap, high-return, and routinely skipped."),
 ("Missions Sunday","Works best as the close of a series rather than a standalone interruption."),
 ("Capital or Building Campaign","Needs its own teaching arc; Nehemiah and Haggai are the source texts."),
 ("Ordination / Commissioning","A leadership-pipeline moment visible to the whole congregation."),
 ("Church Anniversary","Legacy, gratitude and the naming of the next chapter."),
 ("Sending / Church Plant Launch","Multiplication made visible; the strongest teaching moment a church gets."),
]

PASTORAL_OCCASIONS = [
 ("Wedding","Covenant, love, commitment; 1 Corinthians 13, Ephesians 5, Ecclesiastes 4."),
 ("Funeral of a Believer","Hope, resurrection, gratitude; 1 Thessalonians 4, John 14, Revelation 21."),
 ("Funeral of an Unbeliever or Unknown","Comfort without claims; Psalm 23, Romans 8, Lamentations 3."),
 ("Funeral of a Child","Lament first; resist explanation. Psalm 13, Mark 10:13-16."),
 ("Memorial or Celebration of Life","Story-led; the family's testimony carries more than the homily."),
 ("Hospital and Bedside","Short, scriptural, present. Psalm 23, Psalm 121, James 5."),
 ("Congregational Tragedy","Cancel the plan. Lament publicly before interpreting anything."),
 ("Natural Disaster","Practical help announced from the platform is itself the message."),
 ("National Crisis","Prayer, lament and restraint; avoid the temptation to explain."),
 ("Suicide Loss","Care over commentary; involve a trained counselor and provide local resources."),
]
