
BIBLE_A = [
  ("Pentateuch — Deeper Formation", "25 additional formation angles going deeper into the first five books", "Genesis · Exodus · Leviticus · Numbers · Deuteronomy", "#4a5a8a", [
    ("The Breath of Life","What it means that God breathed into dust — the formation of a theology of the animated self","Genesis 2:7","3-Week"),
    ("Before the Fall","What the world was like before Genesis 3 — and why the new creation restores what was there first","Genesis 1–2","4-Week"),
    ("The Cain Question","Am I my brother's keeper — the formation of a theology of responsibility for the person next to you","Genesis 4","3-Week"),
    ("The Covenant with Noah's Children","Genesis 9 and the formation of a universal theology — God's commitment to all humanity, not just Israel","Genesis 9","3-Week"),
    ("The Call of Abram Before the Name Change","Genesis 12:1-3 as a formation text for the call that comes before everything is figured out","Genesis 12","3-Week"),
    ("Hagar Twice","Two encounters in the wilderness and the formation theology of the God who sees you before you see him","Genesis 16 · 21","4-Week"),
    ("The Test of Abraham","Genesis 22 and the formation theology of the command that contradicts the promise — and what God was actually doing","Genesis 22","4-Week"),
    ("Jacob's Ladder","Genesis 28 and the formation of a theology of divine presence in the most ordinary places","Genesis 28","3-Week"),
    ("The Stolen Blessing","Genesis 27 and the formation cost of getting the right thing the wrong way — Jacob's deception and its thirty-year price","Genesis 27","4-Week"),
    ("Joseph's Theology of Suffering","Genesis 50:20 and the formation of a man who could say you meant it for evil, God meant it for good","Genesis 50","4-Week"),
    ("I Am Who I Am","Exodus 3:14 and the formation of a congregation built on the most important name ever spoken","Exodus 3","40-Day"),
    ("Let My People Go Again","The ten plagues as a formation theology of divine persistence — God who keeps asking until the answer changes","Exodus 7–12","4-Week"),
    ("The Passover Lamb","Exodus 12 and the formation of a congregation that reads the Passover through the cross","Exodus 12","Holy Week"),
    ("The Song at the Sea","Exodus 15 as the formation text for a congregation that has just been delivered — singing before the wilderness","Exodus 15","3-Week"),
    ("The Ten Words","The Decalogue not as a code but as a formation architecture — what the commandments form in those who keep them","Exodus 20","40-Day"),
    ("The Sabbath Before the Law","The formation of rest as gift rather than command — Exodus 16 before Sinai","Exodus 16","4-Week"),
    ("The Glory of the Lord","The formation of a congregation that understands what Moses prayed for in Exodus 33 — to see God's glory","Exodus 33–34","4-Week"),
    ("The Priests and the People","Leviticus 8–10 and the formation of a congregation that understands the cost of approaching a holy God carelessly","Leviticus 8–10","4-Week"),
    ("The Jubilee","Leviticus 25 and the formation of a theology of economic reset — the fiftieth year and what it says about ownership","Leviticus 25","4-Week"),
    ("Counting the People","Numbers 1 and the formation theology of being known — the God who counts his people by name","Numbers 1","2-Week"),
    ("The Nazarite Vow","Numbers 6 and the formation of a theology of set-apart living — the formation cost of the consecrated life","Numbers 6","3-Week"),
    ("The Aaronic Blessing","Numbers 6:24-26 and the formation of a congregation that understands benediction as theology","Numbers 6:24–26","3-Week"),
    ("Moses Intercession","Numbers 14 and the formation of a theology of intercession — Moses arguing with God for a people that just rejected him","Numbers 14","4-Week"),
    ("The Cities of Refuge","Numbers 35 and the formation of a theology of sanctuary — what it means to have a place to run to","Numbers 35","3-Week"),
    ("Love the Lord Your God","Deuteronomy 6 and the formation of the Great Commandment as a formation architecture for the whole life","Deuteronomy 6","40-Day"),
  ]),
  ("Historical Books — Deeper Formation", "25 additional formation angles going deeper into Israel's story in the land", "Joshua · Judges · Ruth · Samuel · Kings · Chronicles · Ezra · Nehemiah · Esther", "#3a6a7a", [
    ("The Caleb Clause","Numbers 14 and Joshua 14 together — the formation of the person who waited forty-five years and never stopped believing","Joshua 14","3-Week"),
    ("The Achan Incident","Joshua 7 and the formation of a theology of hidden sin in a community — what one person's choice does to an entire congregation","Joshua 7","3-Week"),
    ("Rahab in the Line","Joshua 2 and Matthew 1 together — the formation of a theology of grace in the genealogy","Joshua 2 · Matthew 1","3-Week"),
    ("The Last Word of Joshua","Joshua 24 and the formation of a congregation that renews its covenant — as for me and my house","Joshua 24","40-Day"),
    ("The Cycle of Judges","The pattern in Judges — sin, consequence, cry, deliverance, rest, repeat — and what it says about human nature","Judges 1–3","4-Week"),
    ("Gideon's Fleece","The formation theology of asking for a sign — what Gideon asked and what it reveals about faith that needs confirmation","Judges 6","3-Week"),
    ("Jephthah's Daughter","Judges 11 and the formation of a theology of vows — the most tragic story in Judges","Judges 11","3-Week"),
    ("The Book of Ruth as Gospel","Ruth's four chapters as a formation gospel — grace, redemption, and the outsider who becomes the ancestor","Ruth","40-Day"),
    ("Boaz at the Gate","Ruth 4 and the formation of a theology of public faithfulness — the covenant-keeping that happens before witnesses","Ruth 4","3-Week"),
    ("The Ark's Journey","1 Samuel 4–7 and the formation of a theology of God's presence — what happens when the ark is treated as a trophy","1 Samuel 4–7","4-Week"),
    ("Give Us a King","1 Samuel 8 and the formation of a congregation that understands what it is asking when it wants to be like everyone else","1 Samuel 8","3-Week"),
    ("David and Goliath Recovered","1 Samuel 17 not as a story about courage but as a formation text about the name of the Lord","1 Samuel 17","3-Week"),
    ("The Lament of David","2 Samuel 1 and the formation of a theology of mourning your enemies — how to grieve the death of someone who tried to kill you","2 Samuel 1","3-Week"),
    ("Mephibosheth at the Table","2 Samuel 9 and the formation of a theology of grace that finds you — the lame man summoned to the king's table","2 Samuel 9","3-Week"),
    ("Nathan's Parable","2 Samuel 12 and the formation of a theology of confrontation — the story that exposed the king","2 Samuel 12","3-Week"),
    ("Solomon's Prayer at the Temple","1 Kings 8 as the most theologically comprehensive prayer in the OT — a formation text for every gathering","1 Kings 8","40-Day"),
    ("The Widow of Zarephath","1 Kings 17 and the formation of a theology of providing for the prophet — and what happens to those who do","1 Kings 17","3-Week"),
    ("The Contest on Carmel","1 Kings 18 and the formation of a congregation that knows what a revival looks like before it prays for one","1 Kings 18","4-Week"),
    ("Elisha's Double Portion","2 Kings 2 and the formation of a theology of succession — what the successor asks for and what it costs","2 Kings 2","3-Week"),
    ("The Shunammite Woman","2 Kings 4 and the formation of a woman who made a room for the prophet — and what the prophet did for her in return","2 Kings 4","3-Week"),
    ("The Four Lepers","2 Kings 7 and the formation of a congregation with good news that it is keeping to itself","2 Kings 7","3-Week"),
    ("The Sealed Scroll","Nehemiah 9–10 and the formation of a congregation that confesses specifically and commits publicly","Nehemiah 9–10","4-Week"),
    ("Esther's Fast","Esther 4 and the formation of a theology of preparation — what Esther did before she approached the king","Esther 4","3-Week"),
    ("The Genealogies of Chronicles","1 Chronicles 1–9 and the formation of a congregation that understands it is part of a longer story than its own lifespan","1 Chronicles 1–9","4-Week"),
    ("Solomon's Decline","1 Kings 11 and the formation of a theology of the divided heart — the slow drift that begins with the thing God said not to","1 Kings 11","4-Week"),
  ]),
  ("Wisdom Literature — Deeper Formation", "25 additional formation angles going deeper into the wisdom books", "Job · Psalms · Proverbs · Ecclesiastes · Song of Solomon", "#6a4a8a", [
    ("Job's First Response","Job 1:20-22 and the formation of a congregation that worships before it understands","Job 1","3-Week"),
    ("The Comforter of Job","Job 2:11-13 and the formation of the best thing Job's friends did — sitting in silence for seven days","Job 2","2-Week"),
    ("Job Vindicated","Job 42 and the formation of a theology of restoration — what God gave back and what the restoration says about the test","Job 42","3-Week"),
    ("The Psalms of Enthronement","Psalms 93–100 and the formation of a congregation that worships a king rather than a consultant","Psalms 93–100","4-Week"),
    ("The Alphabetic Psalms","Psalm 119 and the formation of a theology of Scripture — 176 verses about the word of God","Psalm 119","40-Day"),
    ("Psalm 46 for Turbulent Times","God is our refuge and strength — the formation text for the congregation in the middle of the earthquake","Psalm 46","3-Week"),
    ("The Songs of Zion","Psalms 46, 48, 76, 84, 87 as a formation theology of the city of God","Psalms 46–87","4-Week"),
    ("Praise in the Storm","Psalm 42–43 as a formation text for the person whose soul is cast down — the practice of preaching to yourself","Psalms 42–43","3-Week"),
    ("The Royal Psalms","Psalms 2, 45, 72, 110 as a formation Christology built from the Psalter","Psalms 2 · 45 · 72 · 110","4-Week"),
    ("The Penitential Psalms","Psalms 6, 32, 38, 51, 102, 130, 143 as a formation theology of repentance across seven texts","Seven Psalms","7-Week"),
    ("Proverbs on the Tongue","Proverbs 10–15 and the formation of a congregation whose speech has been disciplined by wisdom","Proverbs 10–15","4-Week"),
    ("Proverbs and the Poor","The formation of a generosity theology from Proverbs — what wisdom says about the person in need","Proverbs 14,17,19,21","4-Week"),
    ("Proverbs on Friendship","What Proverbs says about the formation of friendship — and the nine different kinds Proverbs describes","Proverbs 17–27","4-Week"),
    ("The Book of Proverbs as Formation System","How Proverbs is structured to form a whole person — not aphorisms but an integrated formation manual","Proverbs 1–31","40-Day"),
    ("The Meaninglessness of Comparison","Ecclesiastes 4 on envy — and the formation of a congregation that has stopped keeping score","Ecclesiastes 4","3-Week"),
    ("The Preacher's Final Exam","Ecclesiastes 1 and 12 together — the opening confession and the final counsel","Ecclesiastes 1 · 12","3-Week"),
    ("Joy and Toil Together","Ecclesiastes 2–3 and the formation of a theology of finding joy in ordinary work","Ecclesiastes 2–3","4-Week"),
    ("Better Than","Ecclesiastes' 28 better-than sayings as a formation theology of values — what wisdom considers superior","Ecclesiastes 4–9","4-Week"),
    ("The Vineyard and the Beloved","Song of Songs 1–2 and the formation of a theology of desire as gift — the body as good before it was fallen","Song of Songs 1–2","3-Week"),
    ("The Daughters of Jerusalem","Song of Songs' chorus as a formation text for the community that witnesses love","Song of Songs","3-Week"),
    ("The Dream Sequence","Song of Songs 3 and 5 and the formation of a theology of the love that is sought and lost and found again","Song of Songs 3 · 5","3-Week"),
    ("Love Is as Strong as Death","Song of Songs 8:6-7 and the formation of a theology of love's durability — what love can survive","Song of Songs 8","3-Week"),
    ("Wisdom Before Creation","Proverbs 8 and the formation of a theology of wisdom's presence at the creation — and its presence in the Word made flesh","Proverbs 8","4-Week"),
    ("The Maschil Psalms","The teaching psalms — Psalms 32, 42, 44, 45, 52–55, 74, 78, 88, 89 as a formation curriculum","Various Psalms","6-Week"),
    ("Psalms and the Cross","The five psalms Jesus quoted from the cross — and the formation of a complete theology of lament that becomes resurrection","Psalm 22 · 31 · 69","Holy Week"),
  ]),
  ("Major Prophets — Deeper Formation", "25 additional formation angles going deeper into Isaiah, Jeremiah, Lamentations, Ezekiel, Daniel", "Isaiah · Jeremiah · Lamentations · Ezekiel · Daniel", "#8a4a30", [
    ("Isaiah's Two Halves","Isaiah 1–39 and 40–66 as a formation arc from judgment to consolation — the formation that happens in between","Isaiah 1–66","40-Day"),
    ("The Holy One of Israel","Isaiah's name for God — appearing 26 times — and the formation of a congregation that holds holiness and intimacy together","Isaiah 1–66","4-Week"),
    ("The Peaceable Kingdom","Isaiah 11 and the formation of a congregation shaped by the vision of the end — living from the last chapter","Isaiah 11","4-Week"),
    ("The Vineyard Song","Isaiah 5 and the formation of a congregation that understands what God planted and what he expected — and got","Isaiah 5","3-Week"),
    ("The Suffering Servant's Four Songs","Isaiah 42, 49, 50, 52–53 as a complete formation Christology in four movements","Isaiah 42–53","4-Week"),
    ("I Am Doing a New Thing","Isaiah 43:19 and the formation of a congregation that can see the new thing when the old thing has collapsed","Isaiah 43","4-Week"),
    ("The Potter and the Clay","Isaiah 64 and Jeremiah 18 together — the formation of a complete theology of God's prerogative and our receptivity","Isaiah 64 · Jer 18","4-Week"),
    ("Jeremiah's Reluctance","Jeremiah 1 and the formation of the prophet who tried to refuse — and the formation theology of the called who resist","Jeremiah 1","3-Week"),
    ("Jeremiah's Purchase","Jeremiah 32 — buying a field when the Babylonians have surrounded the city — the formation of hope as action","Jeremiah 32","4-Week"),
    ("The Book of Consolation","Jeremiah 30–33 as a formation arc — the four chapters of hope inside the most heartbreaking prophecy","Jeremiah 30–33","4-Week"),
    ("Lamentations' Acrostic","The formal structure of Lamentations as a formation theology — grief organized rather than chaos expressed","Lamentations","3-Week"),
    ("The Steadfast Love That Does Not Cease","Lamentations 3:22-23 as the formation text that survives inside the darkest book — and what surrounds it","Lamentations 3","7-Day"),
    ("Ezekiel's Temple Vision","Ezekiel 40–48 and the formation of a congregation shaped by the vision of God's house — perfect, ordered, life-giving","Ezekiel 40–48","6-Week"),
    ("The Glory Departs and Returns","Ezekiel 10 and 43 together — the departure and return of God's glory as a formation theology of presence","Ezekiel 10 · 43","4-Week"),
    ("Individual Responsibility","Ezekiel 18 and the formation of a theology of personal responsibility — the children not bearing the fathers' sins","Ezekiel 18","3-Week"),
    ("Gog and Magog","Ezekiel 38–39 and the formation of a congregation that understands spiritual warfare as cosmic","Ezekiel 38–39","4-Week"),
    ("Daniel's Visions","Daniel 7–12 as a formation theology for a congregation facing an overwhelming empire","Daniel 7–12","6-Week"),
    ("The Handwriting on the Wall","Daniel 5 and the formation of a congregation that can read the signs of the times before the fall","Daniel 5","3-Week"),
    ("Daniel's Resolve at the Start","Daniel 1:8 and the formation of the early decision that makes every later decision easier","Daniel 1","3-Week"),
    ("The Ancient of Days","Daniel 7 and the formation of a congregation that sees the throne above every earthly throne","Daniel 7","4-Week"),
    ("Isaiah 53 Verse by Verse","A verse-by-verse formation study of the most prophetically significant passage in the Old Testament","Isaiah 53","5-Week"),
    ("The Year of the Lord's Favor and Vengeance","Isaiah 61 and the formation of a congregation that understands the whole sentence Jesus stopped reading in Luke 4","Isaiah 61","3-Week"),
    ("Jeremiah's Temple Sermon","Jeremiah 7 and the formation of a congregation that has been trusting the building rather than the God in the building","Jeremiah 7","3-Week"),
    ("Ezekiel's Enacted Parables","Ezekiel's thirteen acted parables and the formation theology of embodied proclamation","Ezekiel 4–24","6-Week"),
    ("Cyrus and Providence","Isaiah 44–45 and the formation of a theology of God using the unexpected instrument — including the pagan king","Isaiah 44–45","3-Week"),
  ]),
  ("Minor Prophets — Deeper Formation", "25 additional formation angles going deeper into the twelve", "Hosea · Joel · Amos · Obadiah · Jonah · Micah · Nahum · Habakkuk · Zephaniah · Haggai · Zechariah · Malachi", "#5a7a3a", [
    ("Hosea's Marriage as Lived Theology","The formation of a prophet whose home became the sermon — and what God was saying through the suffering","Hosea 1–3","4-Week"),
    ("The Days of Jezreel","Hosea 2 and the formation of a theology of restored names — the Valley of Trouble becoming a Door of Hope","Hosea 2","3-Week"),
    ("Come Let Us Return","Hosea 6 and the formation of the congregation that knows the rhetoric of return without the reality","Hosea 6","3-Week"),
    ("The Trumpets of Joel","Joel 2:1 and the formation of a congregation that is willing to hear the alarm before the catastrophe","Joel 2","3-Week"),
    ("Old Men Will Dream","Joel 2:28 and the formation of a congregation that expects vision across the generations","Joel 2:28–32","3-Week"),
    ("The Threshing Floor Nations","Amos 1–2 and the formation of a congregation that understands divine judgment as universal","Amos 1–2","4-Week"),
    ("Seek Me and Live","Amos 5:4 and the formation of a theology of seeking — the simplest invitation in the prophets","Amos 5","3-Week"),
    ("Israel's Amos Moment","Amos 7–8 and the formation of a congregation confronted with the basket of summer fruit","Amos 7–8","3-Week"),
    ("Obadiah: The Pride That Precedes","The formation of a congregation that reads the shortest book and finds the largest warning","Obadiah","2-Week"),
    ("Jonah's Prayer from Inside the Fish","Jonah 2 and the formation of a theology of prayer from the worst possible situation","Jonah 2","3-Week"),
    ("Jonah's Anger at the End","Jonah 4 and the formation of the prophet who was angry about mercy — and the God who defended his compassion","Jonah 4","3-Week"),
    ("Micah's Courtroom","Micah 6:1-8 and the formation of a theology of the Lord's case against his people — and what he actually wants","Micah 6","4-Week"),
    ("Micah's Lament and Hope","Micah 7 and the formation of a theology that holds grief and trust simultaneously","Micah 7","3-Week"),
    ("Nahum and the Justice of God","Nahum and the formation of a congregation that understands divine judgment is part of the good news","Nahum","3-Week"),
    ("Habakkuk's Watchtower","Habakkuk 2:1 and the formation of the prayer that waits for an answer — standing at the post","Habakkuk 2","3-Week"),
    ("The Fig Tree Does Not Blossom","Habakkuk 3:17-19 and the formation of a theology of joy not dependent on circumstances","Habakkuk 3","3-Week"),
    ("The Quiet in Zephaniah's Storm","Zephaniah 3:17 as the still center of the most turbulent book","Zephaniah 3","3-Week"),
    ("Haggai's Arithmetic","Haggai 1:5-6 and the formation of a congregation that examines where its resources are going","Haggai 1","3-Week"),
    ("The Signet Ring","Haggai 2:23 and the formation of a theology of reversal — the man cast aside by one king restored by another","Haggai 2","2-Week"),
    ("Zechariah's Eight Visions","The formation of a congregation shaped by eight visions received in a single night","Zechariah 1–6","4-Week"),
    ("The Branch","Zechariah 3 and 6 with Isaiah 11 — the formation of a Christology built from the prophetic image of the Branch","Zechariah 3 · 6 · Isa 11","4-Week"),
    ("Zechariah's Palm Sunday Prophecy","Zechariah 9:9 and the formation of a congregation that reads the triumphal entry through prophecy","Zechariah 9","Advent"),
    ("Zechariah's Thirty Pieces","Zechariah 11:12-13 and the formation of a congregation that traces the betrayal to its prophetic root","Zechariah 11","Holy Week"),
    ("The Messenger I Send","Malachi 3:1 and the formation of a congregation preparing for the One who comes before the One","Malachi 3","Advent"),
    ("The Whole Tithe","Malachi 3:10-12 and the formation of a congregation that tests God — the only place in Scripture where God says test me","Malachi 3","4-Week"),
  ]),
  ("The Gospels — Deeper Formation", "25 additional formation angles going deeper into Matthew, Mark, Luke, and John", "Matthew · Mark · Luke · John", "#4a5a8a", [
    ("The Genealogy as Gospel","Matthew 1 and the formation of a congregation that understands the line that runs from Abraham through four women to Jesus","Matthew 1","Advent"),
    ("The Magi and the King","Matthew 2 and the formation of a congregation that understands Herod and the Magi as two responses to the same news","Matthew 2","Advent"),
    ("The Baptism of Jesus","Matthew 3 and the formation of a theology of the voice from heaven — what the Father said before Jesus had done anything","Matthew 3","4-Week"),
    ("Salt and Light Before Salt and Light","Matthew 5:13-16 and the formation of a congregation that understands its public calling before it hears the private commands","Matthew 5","3-Week"),
    ("The Lord's Prayer Phrase by Phrase","Matthew 6 — one phrase per session — a formation deep dive into the words Jesus taught his disciples to pray","Matthew 6:9–13","7-Week"),
    ("The Eye as the Lamp","Matthew 6:22-23 and the formation of a theology of attention — what you look at is what you become","Matthew 6","3-Week"),
    ("Seek First the Kingdom","Matthew 6:33 and the formation of a theology of priority — the one decision that reorganizes all the others","Matthew 6","40-Day"),
    ("The Narrow Gate","Matthew 7:13-14 and the formation of a congregation that understands the formation life is not the broad way","Matthew 7","3-Week"),
    ("Matthew's Five Discourses","The five great blocks of teaching in Matthew as a complete formation curriculum","Matthew 5–7 · 10 · 13 · 18 · 24–25","10-Week"),
    ("Mark's Messianic Secret","Why Jesus tells people not to tell — and the formation theology of a Messiah who resists being defined by others","Mark 1–9","4-Week"),
    ("The Son of Man Came to Serve","Mark 10:45 and the formation of a theology of service as the grammar of greatness","Mark 10","3-Week"),
    ("The Widow and the Scribes","Mark 12 and the formation of a congregation that notices who gives most — and in what way","Mark 12","3-Week"),
    ("The Anointing at Bethany","Mark 14 and the formation of a theology of extravagant worship — what is wasteful to the disciples is memorial to Jesus","Mark 14","Holy Week"),
    ("Luke's Special Material","Unique to Luke — the Good Samaritan, Prodigal Son, Zacchaeus, Penitent Thief — a formation arc on grace for the excluded","Luke","6-Week"),
    ("The Great Reversal in Luke","Luke's consistent formation arc around wealth, poverty, and the kingdom's reversal","Luke 1–16","40-Day"),
    ("The Journey to Jerusalem","Luke 9–19 as a formation arc — the long journey section and what Jesus teaches on the way to the cross","Luke 9–19","6-Week"),
    ("The Emmaus Road","Luke 24 and the formation of a congregation taught Scripture by the risen Christ and not recognizing him until the bread","Luke 24","4-Week"),
    ("John's Prologue as Foundation","John 1:1-18 as the doctrinal ground of the entire Gospel — and the formation of a Christology that holds","John 1","4-Week"),
    ("The New Birth","John 3 and the formation of a theology of the Spirit's work — born of water and Spirit","John 3","4-Week"),
    ("The Bread of Life Discourse","John 6 and the formation of a congregation that eats the bread that does not lead to eventual hunger","John 6","4-Week"),
    ("The Good Shepherd","John 10 and the formation of a congregation that knows the voice — and what the knowing requires","John 10","4-Week"),
    ("The Hour Has Come","John 12–13 and the formation of a congregation that lives in the shadow of the hour Jesus kept saying had not yet come","John 12–13","Holy Week"),
    ("The Vine and the Branches","John 15 as a formation text for the congregation that does not understand why spiritual formation feels like pruning","John 15","40-Day"),
    ("Come and See Follow Me","John 1:39 and 21:22 as the alpha and omega of discipleship in John","John 1 · 21","3-Week"),
    ("Peace I Leave with You","John 14:27 and the formation of a theology of the peace that the world cannot give — and cannot take","John 14","3-Week"),
  ]),
  ("Acts and Early Church — Deeper Formation", "25 additional formation angles going deeper into Acts", "Acts · Pentecost · Missionary Journeys · Early Church Life", "#3a6a7a", [
    ("You Will Be My Witnesses","Acts 1:8 as the formation architecture of the entire book — Jerusalem, Judea, Samaria, ends of the earth","Acts 1:8","40-Day"),
    ("The Upper Room","Acts 1 and the formation of a congregation that prays together before it launches anywhere","Acts 1","3-Week"),
    ("The Sound of Rushing Wind","Acts 2:2 and the formation of a congregation that understands what the Spirit's arrival sounded like before it looked like anything","Acts 2","3-Week"),
    ("Peter's Pentecost Sermon","Acts 2:14-41 as a formation text for preaching — structure, content, and the three thousand who responded","Acts 2","4-Week"),
    ("Day by Day","Acts 2:46-47 and the formation of a congregation that does the small daily things that produce the large yearly results","Acts 2:46–47","40-Day"),
    ("The Beautiful Gate","Acts 3 and the formation of a congregation that prays on the way to what God is about to do","Acts 3","3-Week"),
    ("When They Saw the Boldness","Acts 4:13 and the formation of a congregation identified by boldness that cannot be explained without Jesus","Acts 4","3-Week"),
    ("The Prayer of Acts 4","Acts 4:24-31 as a formation text for corporate prayer — the early church's response to persecution","Acts 4:24–31","4-Week"),
    ("All Things in Common","Acts 4:32-35 and the formation of a congregation that holds possessions loosely because it holds community tightly","Acts 4","3-Week"),
    ("The Deacon Who Preached","Acts 6–7 and the formation of a congregation that understands service and proclamation as inseparable","Acts 6–7","4-Week"),
    ("Philip in Samaria","Acts 8 and the formation of a congregation that takes the gospel to the place the original community avoided","Acts 8","3-Week"),
    ("Tabitha Raised","Acts 9:36-43 and the formation theology of the congregation that sent for Peter — and the woman who came back","Acts 9","3-Week"),
    ("Peter's Vision","Acts 10:9-16 and the formation of a congregation that has to hear the same vision three times before it believes it","Acts 10","3-Week"),
    ("While Peter Was Still Speaking","Acts 10:44 and the formation of a congregation that stops managing who the Spirit is allowed to fall on","Acts 10","3-Week"),
    ("The Antioch Breakthrough","Acts 11:19-26 and the formation of the church that preached to Greeks and was first called Christians","Acts 11","4-Week"),
    ("The First Mission","Acts 13:1-3 and the formation of a congregation that fasts and prays and sends its best","Acts 13","3-Week"),
    ("Paul and Barnabas at Lystra","Acts 14 and the formation of a congregation that navigates the gap between being worshipped and being stoned","Acts 14","3-Week"),
    ("The Three Missionary Journeys","Acts 13–21 as a formation arc for a congregation that wants to understand the pattern of God's expansion","Acts 13–21","6-Week"),
    ("Paul at Corinth","Acts 18 and the formation of a man told I have many people in this city when the city looked hostile","Acts 18","3-Week"),
    ("The Riot at Ephesus","Acts 19 and the formation of a congregation whose impact changes the economics of an entire city","Acts 19","3-Week"),
    ("Paul's Miletus Speech","Acts 20:17-38 and the formation of a pastor's farewell — what Paul said to the Ephesian elders he would not see again","Acts 20","4-Week"),
    ("Paul Before Agrippa","Acts 26 and the formation of a man who used every audience as an opportunity to tell his story","Acts 26","3-Week"),
    ("The Malta Moment","Acts 28:1-10 and the formation of a congregation that ministers between the storm and the destination","Acts 28","2-Week"),
    ("The House Church Network","Acts 16–18 and the formation of the house church as the primary form of the early community","Acts 16–18","4-Week"),
    ("Women in Acts","The seven women named in Acts and the formation of a congregation that notices who is doing what","Acts","4-Week"),
  ]),
  ("Paul's Letters — Deeper Formation", "25 additional formation angles going deeper into the Pauline corpus", "Romans · Corinthians · Galatians · Ephesians · Philippians · Colossians · Thessalonians · Pastorals · Philemon", "#7a4a8a", [
    ("The Righteousness Revealed","Romans 1:16-17 and the formation of a congregation built on the gospel as the power of God","Romans 1","3-Week"),
    ("Creation Groaning","Romans 8:19-22 and the formation of a congregation that understands its redemption is part of a larger cosmic project","Romans 8","4-Week"),
    ("The Olive Tree","Romans 11 and the formation of a theology of Jew and Gentile — the root that supports the branches","Romans 11","4-Week"),
    ("The Weak and the Strong","Romans 14–15 and the formation of a congregation that holds together people with different convictions","Romans 14–15","4-Week"),
    ("Greet One Another","Romans 16 and the formation of a congregation that names its people — the twenty-seven names Paul closes with","Romans 16","2-Week"),
    ("Apollos and Paul and the Planting","1 Corinthians 3 and the formation of a congregation that understands different leaders do different parts of the same work","1 Corinthians 3","3-Week"),
    ("Flee Sexual Immorality","1 Corinthians 6 and the formation of a theology of the body — the Spirit's temple is the body, not just the spirit","1 Corinthians 6","4-Week"),
    ("To the Married and Unmarried","1 Corinthians 7 and the formation of a congregation that holds singleness and marriage with equal theological weight","1 Corinthians 7","4-Week"),
    ("Food Offered to Idols","1 Corinthians 8 and the formation of a theology of conscience — when freedom must be limited by love for the weaker brother","1 Corinthians 8","3-Week"),
    ("The Lord's Supper Recovered","1 Corinthians 11 and the formation of a congregation that understands why it gathers around the table","1 Corinthians 11","4-Week"),
    ("The Collection for Jerusalem","1 Corinthians 16 and the formation of a theology of financial giving as ecclesial solidarity","1 Corinthians 16","3-Week"),
    ("Ministry as Paul Describes It","2 Corinthians 4–6 as a complete formation theology of pastoral ministry — what it is, what it costs, what it is for","2 Corinthians 4–6","6-Week"),
    ("The Reconciliation Ministry","2 Corinthians 5:18-20 and the formation of a congregation that understands itself as ambassadors of reconciliation","2 Corinthians 5","40-Day"),
    ("Not Because I Desire a Gift","Philippians 4:17 and the formation of a theology of generosity that is about the giver as much as the gift","Philippians 4","3-Week"),
    ("The Kenosis","Philippians 2:5-11 and the formation of a Christology built on emptying — the pattern the congregation is invited to inhabit","Philippians 2","4-Week"),
    ("To Live Is Christ","Philippians 1:21 and the formation of a congregation that has settled the primary question","Philippians 1","40-Day"),
    ("Press Toward the Mark","Philippians 3:12-14 and the formation of a congregation always in motion — not straining to earn but pressing toward","Philippians 3","3-Week"),
    ("The Mystery Hidden for Ages","Colossians 1:26-27 and the formation of a congregation that understands the secret that has been revealed — Christ in you","Colossians 1","4-Week"),
    ("Rooted and Built Up","Colossians 2:6-7 and the formation of a congregation that continues in the same way it began","Colossians 2","3-Week"),
    ("Teach and Admonish","Colossians 3:16 and the formation of a congregation that understands preaching and music as formation tools","Colossians 3","3-Week"),
    ("Comfort One Another","1 Thessalonians 4–5 and the formation of a congregation that uses eschatology as pastoral care","1 Thessalonians 4–5","4-Week"),
    ("The Man of Lawlessness","2 Thessalonians 2 and the formation of a congregation that holds its eschatology clearly without speculation","2 Thessalonians 2","4-Week"),
    ("Godliness with Contentment","1 Timothy 6 and the formation of a congregation that understands what great gain actually looks like","1 Timothy 6","4-Week"),
    ("Entrust to Faithful People","2 Timothy 2:2 and the formation of a congregation built around multiplication — four generations in one verse","2 Timothy 2","4-Week"),
    ("Paul's Letter to Philemon","The shortest Pauline letter as a formation text for reconciliation between equals who are unequal by culture","Philemon","3-Week"),
  ]),
  ("General Epistles — Deeper Formation", "25 additional formation angles going deeper into Hebrews, James, Peter, John, and Jude", "Hebrews · James · 1–2 Peter · 1–2–3 John · Jude", "#8a5a3a", [
    ("Better Covenant Better Promises","Hebrews 8 and the formation of a congregation that understands what the new covenant is better than","Hebrews 8","4-Week"),
    ("The Tabernacle's Shadow","Hebrews 8–10 and the formation of a complete typology — how the tabernacle points to what Christ accomplished","Hebrews 8–10","5-Week"),
    ("Once for All","Hebrews 9:28 and the formation of a congregation that lives from the finished sacrifice","Hebrews 9","3-Week"),
    ("Assembling Together","Hebrews 10:24-25 and the formation of a congregation that understands why showing up to community is formation","Hebrews 10","3-Week"),
    ("The Discipline of the Lord","Hebrews 12:4-11 and the formation of a congregation that understands discipline as evidence of sonship","Hebrews 12","4-Week"),
    ("The City to Come","Hebrews 13:14 and the formation of a congregation that holds its current city loosely because it is looking for the permanent one","Hebrews 13","3-Week"),
    ("Ask in Faith Nothing Wavering","James 1:6 and the formation of a congregation that understands the relationship between faith and prayer","James 1","3-Week"),
    ("The Mirror and the Word","James 1:22-25 and the formation of a congregation that does not just hear the word but allows it to reveal","James 1","4-Week"),
    ("Favoritism in the Congregation","James 2:1-13 and the formation of a congregation confronted with the seating arrangement in its own assembly","James 2","3-Week"),
    ("The Prayer of Faith","James 5:13-18 and the formation of a congregation that prays for healing with the anointing the text describes","James 5","4-Week"),
    ("Born Again to a Living Hope","1 Peter 1:3-5 and the formation of a congregation whose hope is not wishful thinking but inheritance-based certainty","1 Peter 1","4-Week"),
    ("Do Not Fear What They Fear","1 Peter 3:14 and the formation of a congregation that sanctifies Christ as Lord in the middle of anxiety","1 Peter 3","3-Week"),
    ("The Suffering of Christ Followed by Glory","1 Peter 1:10-12 and the formation of a congregation that understands its experience through the prophetic pattern","1 Peter 1","3-Week"),
    ("Elders as Overseers","1 Peter 5:1-4 and the formation of a congregation with a theology of pastoral leadership that serves rather than lords","1 Peter 5","4-Week"),
    ("The False Teachers Among You","2 Peter 2 and the formation of a congregation with the theological discernment to recognize what does not belong","2 Peter 2","4-Week"),
    ("Scoffers in the Last Days","2 Peter 3:3-9 and the formation of a congregation that holds the tension between promise and delay","2 Peter 3","3-Week"),
    ("That Which Was from the Beginning","1 John 1:1-4 and the formation of a congregation whose fellowship is grounded in eyewitness proclamation","1 John 1","3-Week"),
    ("If We Confess","1 John 1:9 and the formation of a congregation that practices confession as a community formation activity","1 John 1","3-Week"),
    ("The Antichrist","1 John 2:18-22 and the formation of a congregation that understands theological discernment as a formation practice","1 John 2","4-Week"),
    ("See What Kind of Love","1 John 3:1 and the formation of a congregation whose identity is built on what the Father has called it","1 John 3","3-Week"),
    ("How We Know We Have Passed from Death to Life","1 John 3:14 and the formation of a congregation that takes its love for one another as a spiritual indicator","1 John 3","3-Week"),
    ("Test the Spirits","1 John 4:1-6 and the formation of a congregation with the theological tools to discern what is from God","1 John 4","4-Week"),
    ("Our Confidence Before Him","1 John 5:14-15 and the formation of a congregation that prays according to his will — and knows what that means","1 John 5","3-Week"),
    ("The Elder to the Elect Lady","2 John and the formation of a congregation that holds truth and love as inseparable standards","2 John","2-Week"),
    ("Building Yourselves Up","Jude 20-21 and the formation of a congregation that understands self-formation as a community responsibility","Jude","3-Week"),
  ]),
  ("Revelation — Deeper Formation", "25 additional formation angles going deeper into Revelation and apocalyptic hope", "Revelation · Apocalyptic · New Creation · The End of the Story", "#8a3a4a", [
    ("Revelation as Pastoral Letter","Revelation 1 and the formation of a congregation that understands John wrote to comfort specific congregations in specific pain","Revelation 1","4-Week"),
    ("The First Love Lost","Revelation 2:4 and the formation of a congregation that understands how first love is lost — and what restores it","Revelation 2","3-Week"),
    ("The Church That Compromises","Revelation 2:12-17 and the formation of a congregation that takes Pergamum's warning as its own","Revelation 2","3-Week"),
    ("Jezebel in the Church","Revelation 2:20 and the formation of a congregation that understands that the false prophet is almost always inside","Revelation 2","3-Week"),
    ("The Lukewarm Church","Revelation 3:14-22 and the formation of a congregation confronted with the most famous thermometer in Scripture","Revelation 3","3-Week"),
    ("The Open Door","Revelation 3:8 and the formation of a congregation with little power offered an open door — and told to walk through","Revelation 3","3-Week"),
    ("The Sealed Scroll","Revelation 5 and the formation of a theology of the worthy one — who can open what no one else can","Revelation 5","4-Week"),
    ("The Prayers of the Saints","Revelation 8:3-4 and the formation of a congregation that understands its prayers as incense before the throne","Revelation 8","3-Week"),
    ("The Two Witnesses","Revelation 11 and the formation of a congregation that understands prophetic witness as the church's core calling","Revelation 11","4-Week"),
    ("The Dragon and the Child","Revelation 12 and the formation of a congregation that understands the cosmic conflict behind every local struggle","Revelation 12","4-Week"),
    ("The 144,000","Revelation 14 and the formation of a theology of the sealed community — who they are and what they sing","Revelation 14","3-Week"),
    ("The Harvest of the Earth","Revelation 14:14-20 and the formation of a congregation that takes the urgency of the harvest seriously","Revelation 14","3-Week"),
    ("The Song of Moses and the Lamb","Revelation 15 and the formation of a congregation that sings both the old exodus and the new one","Revelation 15","3-Week"),
    ("The Fall of Babylon","Revelation 18 and the formation of a congregation that mourns the fall of the system it was tempted to trust","Revelation 18","4-Week"),
    ("The Rider on the White Horse","Revelation 19:11-16 and the formation of a congregation that has a complete Christology for the day of battle","Revelation 19","4-Week"),
    ("The First Resurrection","Revelation 20:4-6 and the formation of a congregation that takes the first resurrection seriously in its theology","Revelation 20","3-Week"),
    ("The White Throne Judgment","Revelation 20:11-15 and the formation of a congregation shaped by the knowledge of the final accounting","Revelation 20","3-Week"),
    ("No Temple in the City","Revelation 21:22 and the formation of a congregation that understands that the city has no temple because it is all temple","Revelation 21","3-Week"),
    ("The Gates Never Shut","Revelation 21:25 and the formation of a congregation shaped by the open city — hospitality as eschatology","Revelation 21","3-Week"),
    ("The Leaves for the Healing of Nations","Revelation 22:2 and the formation of a congregation whose mission is the healing of nations","Revelation 22","3-Week"),
    ("I Am Coming Quickly — Three Times","Revelation 22 and the formation of a congregation that hears the repeated promise as formation for the present","Revelation 22","3-Week"),
    ("The Spirit and the Bride Say Come","Revelation 22:17 and the formation of a congregation that understands the church's eschatological prayer","Revelation 22","3-Week"),
    ("Apocalyptic Hope in the Old Testament","Daniel 7–12, Zechariah 9–14, Ezekiel 38–48 as the formation roots of Revelation's images","Daniel · Zechariah · Ezekiel","6-Week"),
    ("The Letter to Your Church","A formation series using all seven letters — each week a different congregation tests itself against one letter","Revelation 2–3","7-Week"),
    ("Genesis to Revelation in 40 Days","The whole story — creation to new creation — as a formation arc for the congregation that needs the full narrative","Genesis–Revelation","40-Day"),
  ]),
]
