# ── CHAR SERIES: 20 existing cats × 10 additional + 10 new cats × 10 ─────────

CHAR_DEEP_NAMES = [
  "The Patriarchs","The Matriarchs and Women of the OT","The Kings","Queens and Women of Power",
  "The Prophets","Warriors and Judges","The Twelve Disciples","Women of the Gospels",
  "The Unlikely Heroes","Villains and Foils","The Exiles","Reformers and Rebuilders",
  "Wisdom Figures","Lament Figures","The Builders","Covenant Keepers",
  "The Prodigals","Foreign Witnesses","NT Women","Flawed Leaders"
]

CHAR_DEEP_COLORS = [
  "#4a5a8a","#6a4a8a","#8a4a30","#6a3a7a","#4a7a50","#7a5a3a",
  "#3a6a7a","#8a4a6a","#5a7a3a","#8a3a3a","#4a6a9a","#5a6a3a",
  "#4a5a8a","#6a4a6a","#3a5a7a","#5a3a7a","#8a5a3a","#3a7a5a",
  "#8a4a5a","#6a3a4a"
]

CHAR_DEEP_ENTRIES = [
  # Patriarchs
  [("Adam Before the Fall","Walking with God in the cool of the day — what was lost in the fall","Genesis 2","3-Week"),
   ("Cain's Offering","The rejected sacrifice — why it was not accepted — a formation theology","Genesis 4","3-Week"),
   ("The Covenant Before the Name Change","Abram at Genesis 12 — the call before the covenant sign","Genesis 12","3-Week"),
   ("Jacob's Twenty Years in Haran","Serving for the woman he loved — the formation of patient earning","Genesis 29-31","4-Week"),
   ("The Stolen Blessing","Getting the right thing the wrong way — Jacob's deception and its price","Genesis 27","4-Week"),
   ("Joseph's Two Dreams","Genesis 37 — the dreams that started everything — formation before formation","Genesis 37","2-Week"),
   ("Benjamin the Last Son","The youngest who carried the most weight in the family crisis","Genesis 35,42","2-Week"),
   ("Judah's Transformation","From selling his brother to offering himself — the arc of Genesis 44","Genesis 38,44","3-Week"),
   ("Isaac at the Wells","Re-digging his father's wells — the formation of peaceful persistence","Genesis 26","2-Week"),
   ("Shem Ham and Japheth","Three sons and the theology of the nations — the table of Genesis 10","Genesis 9-10","3-Week")],
  # Matriarchs
  [("Leah the Unloved","Children named for longing — the woman whose son carried the Messiah's line","Genesis 29-35","4-Week"),
   ("Rachel the Beloved Who Died in Promise","The death that named a tribe 'son of my right hand'","Genesis 29-35","3-Week"),
   ("Jochebed the Mother of Moses","Hid what was precious, trusted what she could not control, received it back","Exodus 2","2-Week"),
   ("Zipporah Moses' Unexpected Deliverer","Did what Moses failed to do — the circumcision that saved the leader","Exodus 4","2-Week"),
   ("Miriam's Leadership and Leprosy","The woman whose jealousy cost her the congregation's respect","Numbers 12","3-Week"),
   ("Deborah's Song","The warrior-prophetess who led in battle and composed the victory poem","Judges 5","3-Week"),
   ("Naomi the Theologian","Taught theology through grief, bitterness, and restoration","Ruth 1-4","4-Week"),
   ("Rizpah the Vigil","The mother who sat with the dead until the king responded","2 Samuel 21","2-Week"),
   ("Huldah the Prophetess","Authenticated the book — the woman to whom the king sent his priests","2 Kings 22","3-Week"),
   ("The Shunammite's Faith","Made a room for the prophet — and what the prophet did for her in return","2 Kings 4","3-Week")],
  # Kings
  [("Saul's First Failure","1 Samuel 13 — the anatomy of partial obedience and its cost","1 Samuel 13","3-Week"),
   ("David and Abigail","The king stopped by a wise woman — the humility to be grateful","1 Samuel 25","3-Week"),
   ("Rehoboam's Folly","Rejected wise counsel for flattery — split a kingdom","1 Kings 12","3-Week"),
   ("Ahab's Vineyard","The king who wanted what was not his and the wife who got it for him","1 Kings 21","3-Week"),
   ("Jehu's Excessive Zeal","Real zeal, excessive methods — and what God said about it","2 Kings 9-10","3-Week"),
   ("Joash Under Jehoiada","Good only as long as his mentor was alive — the danger of secondhand faith","2 Kings 12","3-Week"),
   ("Jotham the King Nobody Talks About","Did right because he prepared his ways before the Lord — the quiet faithful king","2 Chronicles 27","2-Week"),
   ("Amaziah the Half-Hearted","Did right but not wholeheartedly — the formation cost of the qualifier","2 Chronicles 25","2-Week"),
   ("Zedekiah the Last King","Saw the worst thing a king could see — the formation tragedy of the final chapter","2 Kings 24-25","3-Week"),
   ("Cyrus the Pagan Servant","Isaiah 44-45 — the formation theology of God using the unexpected instrument","Isaiah 44-45,Ezra 1","3-Week")],
  # Queens / Women of Power
  [("Miriam's Leprosy","The prophet who criticized Moses — and the seven days outside the camp","Numbers 12","3-Week"),
   ("Jephthah's Daughter","Met her father's vow with grace — the grief that followed","Judges 11","2-Week"),
   ("Samson's Mother the Unnamed Theologian","Heard the angel's instructions and remembered them better than her husband","Judges 13","2-Week"),
   ("Michal David's First Wife","Her contempt for David's worship — the formation cost of despising holy abandon","2 Samuel 6","2-Week"),
   ("The Wise Woman of Tekoa","Hired by Joab to speak a parable to the king — and what it accomplished","2 Samuel 14","2-Week"),
   ("The Wise Woman of Abel","Negotiated a siege away — wisdom that saved ten thousand lives","2 Samuel 20","2-Week"),
   ("Jehosheba the Aunt Who Hid the King","Six years hiding the heir — the quiet act that preserved the line","2 Kings 11","2-Week"),
   ("Huldah's Authority","The prophetess the king's priests were sent to — authority in unexpected places","2 Kings 22","3-Week"),
   ("Peninnah and Hannah","The cruelty that was the formation furnace — and what God was doing in it","1 Samuel 1","3-Week"),
   ("The Daughters of Zelophehad","Petitioned God for what was right — and won — Numbers 27","Numbers 27","2-Week")],
  # Prophets
  [("Moses' Five Objections","Exodus 3-4 — five reasons he was the wrong person and an answer to each one","Exodus 3-4","5-Week"),
   ("Elisha's Bones","2 Kings 13:21 — the power that continued after death","2 Kings 13","2-Week"),
   ("Micaiah the One Who Told the Truth","Surrounded by four hundred who agreed with each other — and told the king the truth","1 Kings 22","3-Week"),
   ("Jeremiah's Confessions","The prophet's private prayers — six laments that reveal the formation cost","Jeremiah 11-20","6-Week"),
   ("Ezekiel's Wife","Told not to mourn her death — the most painful acted parable in Scripture","Ezekiel 24","2-Week"),
   ("Hosea's Children's Names","Children whose names were the sermon the congregation had to live with","Hosea 1","2-Week"),
   ("Amos the Layman","Not a prophet nor a prophet's son — called anyway","Amos 7","2-Week"),
   ("Habakkuk's Argument","Argued with God about the injustice of the answer — and received a vision","Habakkuk 1-2","3-Week"),
   ("Haggai's Four Messages","Four precisely dated oracles that changed the trajectory of a stalled nation","Haggai 1-2","4-Week"),
   ("Philip the Evangelist","Scattered by persecution, became the first to take the gospel to Samaria","Acts 8","3-Week")],
  # Warriors / Judges
  [("Shamgar One Sentence","Judges 3:31 — one ox goad, six hundred Philistines, one verse — Israel was saved","Judges 3","2-Week"),
   ("Caleb's Daughter Achsah","Joshua 15:16-19 — the daughter who asked for the springs","Joshua 15","2-Week"),
   ("Phinehas the Zealous","The priest whose single act turned away a plague — the formation of decisive intervention","Numbers 25","2-Week"),
   ("The Levite's Concubine","Judges 19-21 — the most disturbing narrative in the OT — and what it demands","Judges 19-21","4-Week"),
   ("Gideon's Three Hundred","Judges 7 — why God kept cutting the army — the formation of divine-credit theology","Judges 7","3-Week"),
   ("Othniel the First Judge","The pattern — what judges were supposed to be before they became what they became","Judges 3","2-Week"),
   ("Barak the Leader Who Needed Company","The formation of the leader who will not go without a companion","Judges 4","3-Week"),
   ("Ehud the Left-Handed Deliverer","The formation theology of God using the non-dominant hand","Judges 3","2-Week"),
   ("Jonathan's Armor-Bearer's Faith","Attacked a garrison with one companion and a theological conviction","1 Samuel 14","3-Week"),
   ("Jephthah's Diplomacy","The most eloquent letter in Judges — the warrior who tried to avoid war","Judges 11","2-Week")],
  # Twelve Disciples
  [("Peter's Mother-in-Law","The first healing in a home — healed and immediately served","Matthew 8","2-Week"),
   ("The Sons of Zebedee's Request","The formation of the request for best seats — and what Jesus said the seats cost","Mark 10","3-Week"),
   ("Matthew's Dinner Party","The first act of the tax collector who followed Jesus — he threw a party","Matthew 9","2-Week"),
   ("Peter and the Rooster","The most specific prophecy of failure in the Gospels — and the specificity of forgiveness","Mark 14,John 21","4-Week"),
   ("John and James at the Samaritan Village","The Sons of Thunder who wanted to call down fire — and Jesus' rebuke","Luke 9","2-Week"),
   ("Andrew's Three Introductions","Always introducing someone to Jesus — John 1, 6, 12","John 1,6,12","3-Week"),
   ("Philip's Calculation","200 denarii — the formation of the disciple who calculated impossibility before possibility","John 6","2-Week"),
   ("Nathanael's Fig Tree","Seen before the introduction — the formation of the skeptic who became a follower","John 1","2-Week"),
   ("The Disciples Sleeping in Gethsemane","The formation community's most significant failure — sleeping when Jesus asked them to watch","Matthew 26","Holy Week"),
   ("Thomas After Resurrection","Eight days of uncertainty — and what Jesus did when he arrived for Thomas","John 20","3-Week")],
  # Women of the Gospels
  [("Anna's Eighty-Four Years","The prophetess who prayed until the answer arrived — and could not stop telling everyone","Luke 2","3-Week"),
   ("Elizabeth the Older Mother","The woman who was barren until the forerunner was planted in her","Luke 1","Advent"),
   ("The Bent Woman","Bent for eighteen years — straightened in the synagogue on the Sabbath","Luke 13","2-Week"),
   ("Joanna the Court Connection","Herod's household manager's wife who funded the ministry and was first at the tomb","Luke 8,24","3-Week"),
   ("The Widow at Nain","Her only son being carried out — and Jesus interrupted the procession","Luke 7","2-Week"),
   ("The Woman Caught","Used as an instrument — and met the one who would not condemn her","John 8","3-Week"),
   ("The Daughters of Jerusalem","Wept for Jesus on the way to the cross — and what he said to them","Luke 23","Holy Week"),
   ("Pilate's Wife","Had the dream and sent the message — the outsider who tried to stop the injustice","Matthew 27","Holy Week"),
   ("Susanna and the Unnamed Women","Luke 8:3 — the women who provided for Jesus out of their own resources","Luke 8","2-Week"),
   ("Salome and the Best Seats","The formation of the mother whose ambition for her sons became a theology of servant greatness","Matthew 20","2-Week")],
  # Unlikely Heroes
  [("The Poor Widow of Mark 12","The smallest offering in the room — the largest by the standard Jesus used","Mark 12","2-Week"),
   ("The Ten Lepers — The One Who Returned","The Samaritan who came back — and the nine who did not","Luke 17","2-Week"),
   ("The Gerasene's First Mission","Asked to go with Jesus — sent home — his first congregation was his town","Mark 5","2-Week"),
   ("The Thief on the Cross","Saved with nothing in hand — the most compressed conversion in Scripture","Luke 23","Holy Week"),
   ("The Lame Man at the Pool","Thirty-eight years — picked up his mat when told to — the formation of immediate obedience","John 5","2-Week"),
   ("The Man Born Blind","I was blind, now I see — the simplest apologetic in the Gospels","John 9","4-Week"),
   ("Simon of Cyrene","Pulled from the crowd to carry a cross — and whose sons were known by the early church","Mark 15","Holy Week"),
   ("The Sinful Woman at Simon's House","Loved much because forgiven much — what Jesus said about why she wept","Luke 7","3-Week"),
   ("The Roman Soldier at the Cross","The first Gentile to confess Jesus as Son of God — watching from the foot of the cross","Matthew 27","Holy Week"),
   ("The Centurion of Capernaum","Such faith as Jesus had not found in Israel — from the mouth of the military","Matthew 8","2-Week")],
  # Villains / Foils
  [("Korah's Rebellion","Numbers 16 — challenged Moses' authority — and what happened","Numbers 16","3-Week"),
   ("The Sons of Eli","Did not know the Lord — and what their father's silence cost","1 Samuel 2","3-Week"),
   ("Joab the Loyal General Who Went Too Far","Loyalty never matched by restraint — the general who outlasted his mandate","2 Samuel,1 Kings","4-Week"),
   ("Haman's Pride","The official whose obsession with one man's refusal to bow cost him everything","Esther 3-7","3-Week"),
   ("Hymenaeus and Alexander","Two men Paul handed over to Satan — what shipwrecked faith looks like","1 Timothy 1","2-Week"),
   ("Demas He Loved the World","2 Timothy 4:10 — with Paul, then not — what happened to Demas","2 Timothy 4","2-Week"),
   ("Cain the First Murderer","The crouching sin, the unaccepted offering, the first act of violence","Genesis 4","3-Week"),
   ("Herod Agrippa and the Worms","The king who accepted worship he should not have accepted","Acts 12","2-Week"),
   ("Shimei's Curse","Cursed David during his flight — and what David said to the offer of revenge","2 Samuel 16","2-Week"),
   ("The Sons of Sceva","Used Jesus' name without Jesus' authority — the spirit who knew the difference","Acts 19","2-Week")],
  # Exiles
  [("The Hebrew Midwives","Feared God more than Pharaoh — the first act of civil disobedience in Scripture","Exodus 1","2-Week"),
   ("Moses in Midian Forty Years","The forty years between the palace and the burning bush — exile as preparation","Exodus 2-3","3-Week"),
   ("Elijah at the Brook Cherith","Fed by ravens in hiddenness — the exile of the hidden season","1 Kings 17","2-Week"),
   ("Jeremiah in the Dungeon","Lowered into a cistern for preaching the truth — and what he preached from it","Jeremiah 37-38","3-Week"),
   ("Ezekiel by the River Chebar","Received his call on foreign soil — the prophet who was himself in exile","Ezekiel 1-3","3-Week"),
   ("Zerubbabel Leading the First Return","The governor who led the first wave home — the first of three","Ezra 1-3","3-Week"),
   ("Nehemiah's Grief in Persia","Sat down and wept — and then prayed — and then acted","Nehemiah 1","3-Week"),
   ("Ezra's Shame","Heard about the mixed marriages and tore his garment — grief as leadership","Ezra 9","2-Week"),
   ("Obadiah in Ahab's Court","Hid one hundred prophets while serving an evil king — faithful presence in a hostile system","1 Kings 18","2-Week"),
   ("The Seven Churches as Exiles","Revelation 2-3 — congregations under pressure — each letter a text for the congregation in exile","Revelation 2-3","7-Week")],
  # Reformers / Rebuilders
  [("Joash and the Money Chest","2 Kings 12 — collected for the temple repair — the one thing that survived his reign","2 Kings 12","2-Week"),
   ("Asa's Early Faithfulness","The king whose early years were the best — and what went wrong later","2 Chronicles 14-16","3-Week"),
   ("Jehoshaphat's Revival","Sent Levites to teach the law in every city — the formation before the reform","2 Chronicles 17","3-Week"),
   ("Hezekiah Opened the Temple First","The first month of his reign — started with worship before anything else","2 Chronicles 29","3-Week"),
   ("Ezra 7:10 in Depth","Set his heart to study, do, and teach — in that order — the formation sequence","Ezra 7","4-Week"),
   ("The Council of Nehemiah 3","Each rebuilt the section in front of their own house — local responsibility","Nehemiah 3","3-Week"),
   ("Zechariah the Priest-Prophet","Eight visions and the hardest formation messages to a stalled rebuilding community","Zechariah 1-8","4-Week"),
   ("Paul and the Philippian Church","The letter to the congregation that gave most and worried most — and what Paul said to both","Philippians","40-Day"),
   ("John the Reformer of the Seven","The elder who was sent from exile to reform seven congregations","Revelation 2-3","7-Week"),
   ("Timothy the Young Pastor","The formation of the next generation — what Paul gave Timothy and what Timothy gave the church","1-2 Timothy","40-Day")],
  # Wisdom Figures
  [("The Two Prostitutes Before Solomon","1 Kings 3:16-28 — the first act of Solomon's wisdom — naming what evidence cannot","1 Kings 3","2-Week"),
   ("The Queen of Sheba's Questions","Traveled to test the king with hard questions — the formation of wisdom sought","1 Kings 10","2-Week"),
   ("Agur's Humility","Proverbs 30:1-4 — began with confession of ignorance — the wisest opening in Proverbs","Proverbs 30","2-Week"),
   ("King Lemuel's Mother","Proverbs 31:1-9 — the queen mother who taught the king how to govern","Proverbs 31","2-Week"),
   ("Kohelet the Preacher","Tried everything, found it all vanity — and still said 'fear God'","Ecclesiastes","4-Week"),
   ("Zophar the Impatient","Job 11 and 20 — always certain and always wrong — the negative wisdom example","Job 11,20","2-Week"),
   ("Elihu the Young Man","Job 32-37 — waited for the elders to finish — the speech the Lord does not rebuke","Job 32-37","3-Week"),
   ("Jesus the Wisdom of God","Proverbs 8, Colossians 1, 1 Corinthians 1 — a Christology built from wisdom's portrait","Proverbs 8,Col 1,1 Cor 1","4-Week"),
   ("Bezalel the Spirit-Filled Craftsman","Exodus 31 — the Spirit given for making things — craft as spiritual gift","Exodus 31,35","2-Week"),
   ("Jethro the Outsider Advisor","Exodus 18 — wisdom received from a father-in-law — the leader who listened","Exodus 18","3-Week")],
  # Lament Figures
  [("Jeremiah Buys a Field in the Siege","Jeremiah 32 — the most hopeful act imaginable while the city falls","Jeremiah 32","3-Week"),
   ("Ezekiel Without Tears","Ezekiel 24 — forbidden to mourn — the embodied theology of lament withheld","Ezekiel 24","2-Week"),
   ("David at the Death of Absalom","2 Samuel 18:33 — the grief for the son who tried to kill him","2 Samuel 18","2-Week"),
   ("The Psalmist Who Fainted","Psalm 77 — refused to be comforted — the memory that finally turned the tide","Psalm 77","3-Week"),
   ("Mary's Seven Sorrows","Luke 2:35 — seven moments where the sword pierced — a theology of maternal grief","Luke 2,John 19","4-Week"),
   ("Stephen's Final Vision","Acts 7:54-60 — saw the throne while being stoned — 'do not hold this against them'","Acts 7","Holy Week"),
   ("Paul Leaving Ephesus","Acts 20:36-38 — the weeping congregation — the grief of good endings","Acts 20","3-Week"),
   ("The Disciples' Grief Before Easter","John 16:20-22 — the community in the gap — the grief that will be turned to joy","John 16","Holy Week"),
   ("1 Thessalonians and Grief","1 Thessalonians 4:13-18 — what Paul said to a congregation grieving without hope","1 Thessalonians 4","3-Week"),
   ("Hezekiah's Illness","Isaiah 38 — wept bitterly when told he was dying — the prayer God heard","Isaiah 38","2-Week")],
  # Builders
  [("The Craftsmen of the Tabernacle","Exodus 35-36 — gave so much Moses told them to stop — the abundance of the willing","Exodus 35-36","3-Week"),
   ("Hiram the Bronze Worker","1 Kings 7 — the craftsman from Tyre who built the sea of bronze — skill serving the sacred","1 Kings 7","2-Week"),
   ("The Priests Who Stepped First","Joshua 3 — stepped into the water before it parted — the formation of wet-feet-first faith","Joshua 3","3-Week"),
   ("Obed-Edom and the Ark","2 Samuel 6:10-12 — kept the ark three months — and whose household was blessed","2 Samuel 6","2-Week"),
   ("Lydia's House as Church","Acts 16:14-15 — the home that became the first European church","Acts 16","2-Week"),
   ("Aquila and Priscilla's Tent-Making Church","Acts 18 — worked with hands, discipled Apollos, planted in Ephesus","Acts 18","3-Week"),
   ("Paul's Building Metaphors","1 Corinthians 3 — the right foundation and what burns vs. what lasts","1 Corinthians 3","4-Week"),
   ("The New Jerusalem as Building","Revelation 21 — the ultimate building project — the city that descends","Revelation 21","4-Week"),
   ("Noah Building What No One Believed","Genesis 6-9 — one hundred years on a project the culture mocked","Genesis 6-9","3-Week"),
   ("Solomon and the Temple Legacy","The son carrying the father's dream — the formation of succession and inherited vision","1 Kings 5-8","4-Week")],
  # Covenant Keepers
  [("Enoch the Walker","Genesis 5:24 — walking so completely that he did not die","Genesis 5","2-Week"),
   ("Noah in a Corrupt Generation","Righteous in a generation that was not — the formation of minority faithfulness","Genesis 5-6","3-Week"),
   ("Caleb's Different Spirit","Numbers 14:24 — having a different spirit from those around him","Numbers 14","3-Week"),
   ("The Rechabites","Jeremiah 35 — had not drunk wine for three hundred years — faithfulness to a family covenant","Jeremiah 35","3-Week"),
   ("The Seven Thousand Who Did Not Bow","1 Kings 19:18 — the hidden covenant community Elijah did not know existed","1 Kings 19","2-Week"),
   ("The Faithful Elders of Hebrews 11","The formation of the congregation that understands what it is surrounded by","Hebrews 11","6-Week"),
   ("Lois and Eunice's Covenant","2 Timothy 1:5 — a two-generation faithfulness that became a three-generation ministry","2 Timothy 1","3-Week"),
   ("The Remnant in Revelation","Revelation 2:24, 3:4, 12:17 — the small faithful community that holds on","Revelation 2-3,12","4-Week"),
   ("Antipas the Faithful Witness","Revelation 2:13 — the one named martyr in the seven letters — what Jesus said about him","Revelation 2","2-Week"),
   ("Anna Eighty-Four Years","Luke 2:36-38 — served in the temple until the promise arrived","Luke 2","3-Week")],
  # Prodigals
  [("Jonah's Second Chance","Jonah 3:1 — the word came a second time — the formation of the re-commissioned servant","Jonah 3","3-Week"),
   ("The Prodigal Father","Luke 15 from the father's perspective — the pursuing parent who runs, robes, rings, and feasts","Luke 15","4-Week"),
   ("Jacob's Return to Esau","Genesis 32-33 — feared the meeting for twenty years — and found a hug","Genesis 32-33","4-Week"),
   ("Gomer's Return","Hosea 3 — told to go buy his wife back — what that cost and what it said","Hosea 3","3-Week"),
   ("Absalom's Return Without Reconciliation","2 Samuel 14-15 — the reunion that looked like reconciliation but was not","2 Samuel 14-15","3-Week"),
   ("Saul Before Damascus","Acts 7:58, 8:1-3 — the persecutor whose story does not end at persecution","Acts 7-9","3-Week"),
   ("Solomon in His Decline","The wisest man in history and the divided heart that undid him","1 Kings 11","3-Week"),
   ("Samson's Repeated Return","The man who kept going back to Delilah — the theology of repeated failure","Judges 13-16","3-Week"),
   ("Mark the Deserter Who Came Back","The abandonment and the rehabilitation — 2 Timothy 4:11","Acts 13,15,2 Tim 4","3-Week"),
   ("Onesimus and the Open Letter","The runaway whose return was announced by a letter — the sponsored return","Philemon","3-Week")],
  # Foreign Witnesses
  [("Melchizedek Before the Covenant","Genesis 14 — no genealogy, no beginning, no end — blessed the father of Israel","Genesis 14","3-Week"),
   ("Balaam's Four Oracles","Numbers 24 — hired to curse and who blessed — formation from a pagan prophet","Numbers 24","4-Week"),
   ("Rahab's Theology","Joshua 2:9-11 — the most complete theological statement in the early conquest narrative","Joshua 2","2-Week"),
   ("Naaman's Conversion","2 Kings 5:15 — no God in all the earth except in Israel — the formation of the foreign convert","2 Kings 5","3-Week"),
   ("Hiram of Tyre's Blessing","1 Kings 5:7 — blessed the God of Israel upon hearing Solomon's request","1 Kings 5","2-Week"),
   ("Nebuchadnezzar's Three Confessions","Daniel 3 and 4 — three declarations about the God of Israel after three encounters","Daniel 3-4","3-Week"),
   ("Darius's Decree","Daniel 6:25-27 — the king who issued a decree about the living God after the lions' den","Daniel 6","2-Week"),
   ("Cyrus's Proclamation","Ezra 1:1-4 — fulfilled a prophecy issued 150 years before his birth","Ezra 1","3-Week"),
   ("The Centurion's Faith at the Cross","Matthew 27:54 — the Roman officer who recognized what he saw","Matthew 27","Holy Week"),
   ("The Samaritan Leper's Return","Luke 17:15-19 — the outsider who returned when nine insiders did not","Luke 17","2-Week")],
  # NT Women
  [("Joanna in Herod's Court and at the Tomb","Luke 8:3, 24:10 — funded the ministry and was first at the empty tomb","Luke 8,24","3-Week"),
   ("The Four Daughters of Philip","Acts 21:9 — the household of the evangelist where prophecy was normal","Acts 21","2-Week"),
   ("Nympha and Her Church","Colossians 4:15 — the woman whose home was the congregation","Colossians 4","2-Week"),
   ("Mary the Mother of Mark","Acts 12:12 — her house was the gathering place that prayed for Peter","Acts 12","2-Week"),
   ("Chloe's People","1 Corinthians 1:11 — the household that reported the Corinthian problems to Paul","1 Corinthians 1","2-Week"),
   ("Tryphena and Tryphosa Workers","Romans 16:12 — two women Paul calls 'workers in the Lord'","Romans 16","2-Week"),
   ("Phoebe the Deaconess","Romans 16 — trusted to carry Paul's most important letter","Romans 16","2-Week"),
   ("Junia Among the Apostles","Romans 16:7 — named among the apostles — and what that means","Romans 16","2-Week"),
   ("Dorcas Full of Good Works","Acts 9 — the woman whose ministry was so essential the church asked for her back","Acts 9","2-Week"),
   ("Lois and Eunice","2 Timothy 1:5 — the grandmother and mother whose faith became a three-generation ministry","2 Timothy 1","3-Week")],
  # Flawed Leaders
  [("Aaron and the Golden Calf","Exodus 32 — the high priest who made the idol — and how Moses interceded for him","Exodus 32","3-Week"),
   ("Aaron's Silence","Leviticus 10 — said nothing when his sons died for unauthorized fire — held silence","Leviticus 10","2-Week"),
   ("Gideon's Ephod","Judges 8:27 — the deliverer who made an object that 'became a snare' after victory","Judges 8","2-Week"),
   ("Eli's Indulgence","1 Samuel 2:29 — honored his sons above God — the leadership failure of conflict avoidance","1 Samuel 2","3-Week"),
   ("Uzziah in the Temple","2 Chronicles 26:16-21 — strong, then entered the sanctuary as if strength made him a priest","2 Chronicles 26","2-Week"),
   ("Hezekiah's Pride","Isaiah 39 — showed off everything to the Babylonians — and the prophecy that followed","Isaiah 39","2-Week"),
   ("Paul and Barnabas's Disagreement","Acts 15:36-41 — two leaders who could not agree — and what happened to both later","Acts 15","3-Week"),
   ("Peter's Hypocrisy in Antioch","Galatians 2:11-14 — a public confrontation between two apostles — what was at stake","Galatians 2","3-Week"),
   ("Solomon's Foreign Alliances","1 Kings 11 — the strategy God had explicitly prohibited — and the formation cost over decades","1 Kings 11","4-Week"),
   ("David's Census","2 Samuel 24 — pride in what he had built — costing seventy thousand lives","2 Samuel 24","2-Week")],
]

CHAR_NEW = [
  ("The Prayer Warriors","Ten men and women whose primary formation gift was how they prayed","","#3a5a7a",[
    ("Daniel Three Times a Day","The prayer posture so established that no prohibition could change it","Daniel 6","40-Day"),
    ("Hannah The Vow That Changed History","Prayed so earnestly the priest thought she was drunk — and received a prophet","1 Samuel 1","4-Week"),
    ("Elijah The Prayer That Stopped Rain","James 5:17-18 and 1 Kings 17-18 — the prayers that controlled the weather","1 Kings 17-18","4-Week"),
    ("Nehemiah The Arrow Prayer","Prayed in the gap between the king's question and his own answer","Nehemiah 2","3-Week"),
    ("Moses Forty Days of Intercession","The most sustained intercession in the Old Testament","Exodus 32-34","5-Week"),
    ("Abraham The Negotiating Prayer","Bargained with God for Sodom — heard — the boldest prayer in Genesis","Genesis 18","3-Week"),
    ("The Church at Acts 4","The corporate prayer that shook the building — and what they asked for","Acts 4","4-Week"),
    ("Paul's Prison Prayers","Ephesians 1,3, Philippians 1, Colossians 1 — the prayers Paul wrote in chains","Various Epistles","4-Week"),
    ("Anna Eighty-Four Years of Night and Day","Fasted and prayed in the temple until the answer arrived","Luke 2","3-Week"),
    ("Jesus in the Garden","The most honest prayer in Scripture — and what the disciples missed","Matthew 26","Holy Week"),
  ]),
  ("The Peacemakers","Ten men and women whose formation gift was bringing reconciliation where division had taken root","","#4a7a5a",[
    ("Abigail Between Rage and Ruin","Stood between David's anger and Nabal's household — the formation of intervening wisdom","1 Samuel 25","3-Week"),
    ("Joseph's Forgiveness","Genesis 45 — the moment that changed the meaning of everything that came before","Genesis 45","4-Week"),
    ("Esau's Embrace","Genesis 33 — Jacob dreaded the meeting and received a hug instead","Genesis 33","3-Week"),
    ("Jonathan and David","1 Samuel 18-20 — the friendship that operated as a peace treaty between two houses","1 Samuel 18-20","3-Week"),
    ("Barnabas the Bridge-Builder","Introduced the dangerous to the doubting — Acts 9, 11, 25","Acts 9-15","3-Week"),
    ("Moses the Mediator","Exodus 32:30-34 — stood between the people and their destruction","Exodus 32","3-Week"),
    ("Paul's Letter to Philemon","The most personal letter in the NT — reuniting two men across a vast cultural divide","Philemon","3-Week"),
    ("The Jerusalem Council","Acts 15 — held together Gentile freedom and Jewish sensitivity","Acts 15","3-Week"),
    ("The Prodigal Father as Peacemaker","Luke 15:20-24 — ran before anyone asked — the preemptive reconciliation","Luke 15","3-Week"),
    ("Gamaliel's Wisdom of Restraint","Acts 5 — the Pharisee whose advice protected the early church from the Sanhedrin","Acts 5","2-Week"),
  ]),
  ("Mentors and Disciples","Ten formation relationships of Scripture — those who passed on what they received","","#4a5a8a",[
    ("Moses and Joshua Forty Years","A forty-year mentoring relationship traced across four books","Exodus-Deuteronomy","4-Week"),
    ("Elijah and Elisha The Double Portion","What the disciple watched and what he asked for","1 Kings 19,2 Kings 2","4-Week"),
    ("Naomi and Ruth The Unlikely Formation Pair","Older woman forming younger through grief, bitterness, wisdom, and restoration","Ruth","40-Day"),
    ("Eli and Samuel The Broken and the New","The boy who received the word that would judge his mentor's household","1 Samuel 3","3-Week"),
    ("Jethro and Moses The Outside Mentor","The leader who received wisdom from his father-in-law — the advisor who saved the ministry","Exodus 18","3-Week"),
    ("Barnabas and Paul Introduction to Argument","Began with sponsorship and ended in disagreement — the full arc of the relationship","Acts 9-15","4-Week"),
    ("Paul and Timothy The Long Apprenticeship","Acts 16 and 1-2 Timothy — the relationship that produced two pastoral letters","Acts 16,1-2 Tim","40-Day"),
    ("Priscilla Aquila and Apollos","The corrective mentoring — the student more eloquent than the teachers","Acts 18","3-Week"),
    ("Jesus and the Twelve","The three years of formation in the Gospels — a complete model for mentoring communities","All Four Gospels","40-Day"),
    ("Paul and Titus The Difficult Mission","Sent to the hardest posting — what Paul told him to do there","Titus","3-Week"),
  ]),
  ("The Intercessors","Ten men and women who stood between God and others in prayer","","#5a4a8a",[
    ("Abraham for Sodom","Negotiated for a city he didn't even like — the formation of intercession for enemies","Genesis 18","3-Week"),
    ("Moses After the Golden Calf","Offered to be blotted out instead of the people — the deepest intercession in the Torah","Exodus 32","4-Week"),
    ("Samuel I Will Not Stop","1 Samuel 12:23 — made intercession a covenant responsibility","1 Samuel 12","3-Week"),
    ("Ezra's Intercessory Grief","Prostrated himself on behalf of people who were not personally his failure","Ezra 9","3-Week"),
    ("Nehemiah's Four-Month Prayer","Wept, fasted, and prayed before asking the king anything","Nehemiah 1","4-Week"),
    ("Job Prayed for His Friends","Prayed for the friends who wounded him — and was restored when he did","Job 42","3-Week"),
    ("Jeremiah Prophet as Intercessor","Told to stop praying for the people — and what that prohibition reveals","Jeremiah 7-14","4-Week"),
    ("Daniel's Prayer for Jerusalem","Read Jeremiah's seventy years and prayed as if the fulfillment required his prayer","Daniel 9","4-Week"),
    ("Jesus' High Priestly Prayer","What Jesus prayed for the disciples and for those who would believe through them","John 17","5-Week"),
    ("Paul's Persistent Intercession","Romans 9:1-3 — willing to be accursed for the sake of his people","Romans 9-10","3-Week"),
  ]),
  ("The Bold Confessors","Ten men and women who made public declarations of faith at enormous personal cost","","#7a4a3a",[
    ("Joshua's Declaration","Joshua 24:15 — as for me and my house — the public commitment that is chosen not coerced","Joshua 24","40-Day"),
    ("The Three Young Men's Even-If Faith","Daniel 3:17-18 — believed but would not leverage belief as a guarantee","Daniel 3","3-Week"),
    ("Daniel's Open Windows","Daniel 6:10 — kept praying with windows open when prayer was outlawed","Daniel 6","40-Day"),
    ("Peter's Pentecost Sermon","Acts 2:14 — fifty days after the denial — standing before thousands","Acts 2","3-Week"),
    ("Stephen Before the Council","Acts 7 — preached the most comprehensive sermon to the people who would kill him for it","Acts 7","4-Week"),
    ("Paul Before Agrippa","Acts 26 — seized every audience as an opportunity to tell his story","Acts 26","3-Week"),
    ("Peter and John Before the Sanhedrin","Acts 4:19-20 — 'whether it is right to listen to you rather than God, you decide'","Acts 4","3-Week"),
    ("Thomas's Confession","John 20:28 — 'my Lord and my God' — the highest Christological declaration in the Gospels","John 20","3-Week"),
    ("Martha's Confession Before the Tomb","John 11:27 — 'you are the Christ, the Son of God' — before the resurrection, at the worst moment","John 11","3-Week"),
    ("Antipas the Martyr","Revelation 2:13 — the one named martyr in the seven letters","Revelation 2","2-Week"),
  ]),
  ("The Restorers","Ten men and women whose primary calling was to restore what sin, time, or disaster had broken","","#6a4a5a",[
    ("Joseph Providing for His Brothers","Had the power to punish and chose to provide instead","Genesis 45-50","4-Week"),
    ("Boaz the Kinsman-Redeemer","Legally restored what poverty had taken from a family","Ruth 4","4-Week"),
    ("Nehemiah the Wall Builder","Complete restoration — walls, worship, community, and the word","Nehemiah","40-Day"),
    ("Josiah Restoring the Temple","Cleaned, repaired, and rededicated the house of God","2 Chronicles 34-35","4-Week"),
    ("Ezra Restoring the Law","Read the law for seven hours while the people stood and wept","Nehemiah 8","4-Week"),
    ("Elijah Restoring the Widow's Son","1 Kings 17 — the first resurrection in the Old Testament","1 Kings 17","3-Week"),
    ("Jesus Restoring the Leper","Mark 1 — touched the untouchable before he healed him — the touch that preceded restoration","Mark 1","3-Week"),
    ("Jesus Restoring Peter","John 21 — threefold restoration matched to threefold denial — and the commission that followed","John 21","4-Week"),
    ("Paul and John Mark","2 Timothy 4:11 — 'bring Mark, he is useful to me' — after fifteen years","2 Timothy 4","3-Week"),
    ("The Reconciliation Ministry","2 Corinthians 5:18-21 — the church called to be the community where restoration happens through it","2 Corinthians 5","40-Day"),
  ]),
  ("The Reluctant and the Willing","The contrast between those who resisted and those who immediately said yes","","#5a7a4a",[
    ("Isaiah's Immediate Yes","Isaiah 6:8 — here am I, send me — before hearing where he was being sent","Isaiah 6","4-Week"),
    ("Jeremiah's Long Protest","Argued with God for forty years but kept preaching anyway","Jeremiah 1","3-Week"),
    ("Moses' Five Objections","Five reasons he was the wrong person — and an answer to each one","Exodus 3-4","5-Week"),
    ("Gideon's Three Signs","Asked for three confirmations before he believed the angel","Judges 6","3-Week"),
    ("Jonah's Complete Resistance","Went in the opposite direction — the most defiant response to a divine call","Jonah 1","21-Day"),
    ("Mary's Immediate Consent","Luke 1:38 — 'let it be to me' with no condition attached","Luke 1","Advent"),
    ("Peter's Depart from Me","Luke 5:8 — the fisherman whose first response to the miraculous was to ask Jesus to leave","Luke 5","2-Week"),
    ("Matthew's Immediate Rising","Matthew 9:9 — rose and followed — the fastest discipleship moment in the Gospels","Matthew 9","2-Week"),
    ("Saul's Three Days of Blindness","Acts 9:9 — between the call and the receiving of the call — what happened in the dark","Acts 9","3-Week"),
    ("Andrew's Immediate Invitation","John 1:41 — found his brother first — the call that is immediately passed on","John 1","2-Week"),
  ]),
  ("The Sleepers and the Wakened","Men and women who missed what was happening — and the formation of waking up to what God is doing","","#4a6a7a",[
    ("The Disciples in Gethsemane","Matthew 26 — slept through the hardest prayer in the Gospels","Matthew 26","Holy Week"),
    ("Jonah Asleep in the Storm","The only one asleep when the ship was sinking","Jonah 1","2-Week"),
    ("Eli's Failing Sight","1 Samuel 3 — 'the word of the Lord was rare' — spiritual and physical blindness mirroring each other","1 Samuel 3","3-Week"),
    ("The Ten Virgins","Matthew 25 — five who were ready and five who were not — the formation of unshared readiness","Matthew 25","4-Week"),
    ("Eutychus Sleeping Through the Sermon","Acts 20 — fell three stories and was raised — and what happened after","Acts 20","2-Week"),
    ("The Church at Sardis","Revelation 3:1-6 — reputation for being alive while being dead","Revelation 3","3-Week"),
    ("Jacob Waking at Bethel","Genesis 28:16 — 'surely God was in this place and I did not know it'","Genesis 28","3-Week"),
    ("Peter Waking in Prison","Acts 12:7 — struck on the side to wake up — still thought he was dreaming","Acts 12","2-Week"),
    ("The Emmaus Road Disciples","Luke 24 — slow of heart to believe — walking with Jesus without recognizing him","Luke 24","3-Week"),
    ("Saul Sleeping Before David","1 Samuel 26:12 — the vulnerability of the king who slept while David spared him again","1 Samuel 26","2-Week"),
  ]),
  ("The Tent-Dwellers and Sojourners","Men and women whose formation happened in movement rather than settlement","","#6a5a3a",[
    ("Abraham Stranger in a Strange Land","Hebrews 11:8-10 — lived in tents in the promised land — the formation of faith without arrival","Genesis 12-25,Heb 11","40-Day"),
    ("Jacob Twenty Years in Haran","Served for the woman he loved and worked his way to independence","Genesis 29-31","4-Week"),
    ("Moses in Midian","The forty years between the palace and the burning bush","Exodus 2-4","4-Week"),
    ("Ruth the Moabite in Bethlehem","The sojourner who found a home — the foreigner who became a daughter of the city","Ruth","40-Day"),
    ("Elijah's Forty Days to Horeb","Fed twice, traveling forty days, arriving at the mountain","1 Kings 19","3-Week"),
    ("Paul the Tent-Maker and Traveler","Acts 18, 2 Corinthians 11 — worked with his hands and never stopped moving","Acts 18,2 Cor 11","4-Week"),
    ("Peter the Pilgrim","1 Peter 1:1 — wrote to 'elect exiles' — from exile himself","1 Peter 1","3-Week"),
    ("John on Patmos","Movement stopped but vision not — the exile who saw the most comprehensive revelation","Revelation 1","4-Week"),
    ("The Cloud of Witnesses Walking","Hebrews 11 — the formation of a congregation that understands life as a walk not a settlement","Hebrews 11","6-Week"),
    ("Abraham Looking for the City","Hebrews 11:10 — lived in tents because looking for the city with foundations","Hebrews 11","3-Week"),
  ]),
  ("The Nomads and Wanderers","Men and women who were displaced, homeless, or fugitive — whose formation happened without a fixed address","","#3a6a5a",[
    ("Cain's Mark and the Wandering","Genesis 4:12-16 — the first wanderer — what God put on the man he expelled","Genesis 4","2-Week"),
    ("Hagar in the Wilderness Twice","Genesis 16 and 21 — God found her on two separate occasions","Genesis 16,21","3-Week"),
    ("Moses as Fugitive in Midian","The prince-become-shepherd — displacement as preparation","Exodus 2","3-Week"),
    ("David Among the Philistines","1 Samuel 21-27 — the anointed king who spent years hiding among enemies","1 Samuel 21-27","5-Week"),
    ("Elijah's Flight to Horeb","1 Kings 19 — fled after his greatest victory — the formation of the wandering burned-out prophet","1 Kings 19","3-Week"),
    ("The Disciples After the Crucifixion","John 20:19 — the scattered community — and what happened when Jesus walked in","John 20","3-Week"),
    ("Paul After Damascus","Galatians 1:17 — went to Arabia for three years before he told anyone what happened","Galatians 1","3-Week"),
    ("The Persecuted Scattered in Acts 8","Acts 8:1-4 — every dispersed believer became an evangelist","Acts 8","3-Week"),
    ("Jeremiah the Displaced Prophet","Jeremiah 37-43 — the prophet who had no safe place — not in the city or out of it","Jeremiah 37-43","4-Week"),
    ("The Beloved Disciple on Patmos","Revelation 1:9 — exiled to an island — and given the most comprehensive vision in Scripture","Revelation 1","4-Week"),
  ]),
]

# ── STORIES DEEP: 10 existing cats × 10 additional ─────────────────────────

STORIES_DEEP = [
  ("Creation and Beginnings — Additional","10 more formation angles on the creation narratives","","#4a5a8a",[
    ("Let There Be Light Before the Sun","Genesis 1:3 — light on day one, sun on day four — the source of all light","Genesis 1","3-Week"),
    ("The Breath of Life","Genesis 2:7 — God breathed into dust — the animated self as formation theology","Genesis 2","3-Week"),
    ("Where Are You","Genesis 3:9 — the first question God asks after the fall — divine pursuit","Genesis 3","40-Day"),
    ("The First Promise","Genesis 3:15 — the proto-evangelium — the seed of the woman","Genesis 3","3-Week"),
    ("The Serpent's Question","Genesis 3:1 — 'did God actually say' — the formation of a theology of temptation's first move","Genesis 3","3-Week"),
    ("Shame and Clothing","Genesis 3:7 — the first emotional consequence of the fall — and what God did about it","Genesis 3","3-Week"),
    ("Where Are You Going Cain","Genesis 4:1-8 — the two ways — what made one offering acceptable and one not","Genesis 4","3-Week"),
    ("The Helper Corresponding","Genesis 2:18-22 — ezer kenegdo — the formation of a theology of partnership","Genesis 2","4-Week"),
    ("The Seventh Day","Genesis 2:1-3 — Sabbath in creation — rest as gift before it was command","Genesis 2","4-Week"),
    ("The Tower of Babel","Genesis 11 — human ambition — and the God who confuses what he could simply destroy","Genesis 11","3-Week"),
  ]),
  ("Covenant Moments — Additional","10 more formation angles on the great covenant texts","","#3a6a4a",[
    ("The Covenant Ceremony of Genesis 15","The deep sleep of Abram — the formation of a theology of the unilateral covenant","Genesis 15","4-Week"),
    ("The Circumcision Sign","Genesis 17 — what gets marked and why the body is the covenant location","Genesis 17","3-Week"),
    ("The Covenant Renewal at Shechem","Joshua 24 — choose this day whom you will serve","Joshua 24","40-Day"),
    ("The Covenant and the Curse","Deuteronomy 27-28 — the stakes of the covenant — blessing and curse","Deuteronomy 27-28","4-Week"),
    ("Covenant in the Old Testament Seven Types","The six major covenants as a formation architecture of Scripture","Gen-Malachi","6-Week"),
    ("The Marriage Covenant","Ephesians 5:25-32, Genesis 2 — marriage as covenant enacted by promise","Genesis 2,Eph 5","4-Week"),
    ("The Lord's Supper as Covenant Renewal","Luke 22:20 — the table where covenant is renewed weekly","Luke 22","40-Day"),
    ("Christ the Mediator of a Better Covenant","Hebrews 12:24 — what Jesus mediates that Moses could not","Hebrews 12","4-Week"),
    ("Sealing the Covenant in Blood","Hebrews 9:15-22 — the blood that seals the testament","Hebrews 9","4-Week"),
    ("The Everlasting Covenant","Revelation 21-22 — covenant consummation — God with his people forever","Revelation 21-22","4-Week"),
  ]),
  ("Wilderness and Wandering — Additional","10 more formation angles on the in-between theology","","#7a6a3a",[
    ("The Wilderness of Testing","Numbers 11 — what comes out of people when provision does not match expectation","Numbers 11","3-Week"),
    ("The Oasis of Elim","Exodus 15:27 — what God provides between two water crises","Exodus 15","2-Week"),
    ("Marah Making Bitter Sweet","Exodus 15:23-25 — the tree that made the bitter water sweet","Exodus 15","3-Week"),
    ("The Second Passover","Numbers 9 — allowed to celebrate a month late — the grace of the second opportunity","Numbers 9","2-Week"),
    ("The Tabernacle in the Wilderness","Exodus 40 — God's dwelling in the middle of an unsettled people","Exodus 40","4-Week"),
    ("Forty Years Reconsidered","Deuteronomy 8 — the years that felt like waste but were formation","Deuteronomy 8","4-Week"),
    ("Jesus in the Wilderness","Matthew 4 — the second Israel passing the test the first one failed","Matthew 4","Lent"),
    ("The Wilderness Church","Acts 7:38 — ekklesia before settlement — the congregation in the wilderness","Acts 7","2-Week"),
    ("The Wilderness of the New Covenant","Hosea 2:14-15 — God leading Israel into the wilderness again — as courtship","Hosea 2","3-Week"),
    ("The Patient Seed","Mark 4:26-29 — the kingdom growing without the farmer seeing it","Mark 4","3-Week"),
  ]),
  ("Exile and Return — Additional","10 more formation angles on displacement theology","","#6a4a8a",[
    ("The Letter Jeremiah Sent","Jeremiah 29:1-14 — build houses, plant gardens — the embedded faithfulness","Jeremiah 29","40-Day"),
    ("Ezekiel's Throne That Could Move","Ezekiel 1 — the God who goes to Babylon when his people go","Ezekiel 1","3-Week"),
    ("The Synagogue as Exile Institution","The institution invented in exile and outlasted it — worship without a temple","Various","3-Week"),
    ("The Return and the Disappointment","Haggai 2:3 — the restored temple smaller than what they remembered","Haggai 2","3-Week"),
    ("The People Who Never Left","2 Kings 25:22-26 — the community that stayed when the exile happened","2 Kings 25","2-Week"),
    ("Voluntary Exiles","Jeremiah 24 — the good figs and the bad figs — which ones God sent to Babylon","Jeremiah 24","3-Week"),
    ("Jesus' Exile in Egypt","Matthew 2:13-15 — recapitulating Israel's exodus — 'out of Egypt I called my son'","Matthew 2","Advent"),
    ("Paul's Philippian Citizenship","Philippians 3:20 — the theology of the dual citizenship — whose colony you actually live in","Philippians 3","3-Week"),
    ("Exile as Participation in Christ","Colossians 1:24 — suffering in exile as filling up what is lacking in Christ's afflictions","Colossians 1","3-Week"),
    ("Daniel's Three-Times-a-Day Prayer","Daniel 6:10 — the prayer practice that does not bend to prohibition","Daniel 6","40-Day"),
  ]),
  ("Birth, Death, and Resurrection — Additional","10 more formation angles on the hinge moments","","#8a3a4a",[
    ("The Death of Moses","Deuteronomy 34 — the greatest prophet's death — and the man who buried him alone","Deuteronomy 34","2-Week"),
    ("The First Death","Genesis 4:8 — the first murder — the world after the fall","Genesis 4","2-Week"),
    ("The Death of a King's Son","2 Samuel 12:15-23 — David's theology of death — 'I will go to him'","2 Samuel 12","3-Week"),
    ("The Raising of Jairus's Daughter","Mark 5:35-43 — the private miracle — cleared the house before speaking to the girl","Mark 5","3-Week"),
    ("What Happened Between Death and Resurrection","1 Peter 3:18-22 — what Christ did in three days — and what it means","1 Peter 3","3-Week"),
    ("The First Day of the Week","John 20:1 — why Sunday matters — the theology of the resurrection day","John 20","Easter"),
    ("Mary Magdalene's First Words","John 20:11-18 — 'why are you weeping' and 'go and tell' — the first resurrection conversation","John 20","Easter"),
    ("The Last Enemy","1 Corinthians 15:26 — death as enemy being destroyed — not romanticized","1 Corinthians 15","4-Week"),
    ("Born Again of Imperishable Seed","1 Peter 1:23 — regeneration as the beginning of the resurrection life","1 Peter 1","3-Week"),
    ("The Transfiguration as Resurrection Preview","Matthew 17 — the unveiled Christ — what the disciples were supposed to carry down the mountain","Matthew 17","3-Week"),
  ]),
  ("Prayer and Divine Encounter — Additional","10 more formation angles on the moments when humans came near to God","","#3a5a7a",[
    ("Jacob's Night at Jabbok","Genesis 32:22-32 — the prayer that cannot be walked away from unchanged","Genesis 32","4-Week"),
    ("Moses and the Cleft of the Rock","Exodus 33:18-23 — asked to see God's glory — placed in the rock","Exodus 33","4-Week"),
    ("Isaiah in the Throne Room","Isaiah 6:1-8 — 'woe is me' to 'here I am' — the encounter arc","Isaiah 6","4-Week"),
    ("Ezekiel's Overwhelming Vision","Ezekiel 1 — multiple words and still insufficient — the vision of the living creatures","Ezekiel 1","4-Week"),
    ("Daniel's Terror and Touch","Daniel 10:9-19 — prostrated by the encounter — strengthened by the hand","Daniel 10","3-Week"),
    ("The Road to Emmaus Encounter","Luke 24:13-35 — Scriptures explained, bread broken, recognition — the formation of Sunday","Luke 24","4-Week"),
    ("Paul's Vision of the Third Heaven","2 Corinthians 12:1-4 — heard things he could not tell — and what balanced it","2 Corinthians 12","3-Week"),
    ("John's Vision of the Risen Christ","Revelation 1:12-17 — fell as though dead — and the hand that raised him","Revelation 1","4-Week"),
    ("The Throne Room in Revelation 4","Revelation 4 — the formation of a congregation that orients itself to what is always happening in heaven","Revelation 4","40-Day"),
    ("Elijah's Still Small Voice","1 Kings 19:11-13 — after the wind, earthquake, and fire — the sound of sheer silence","1 Kings 19","3-Week"),
  ]),
  ("Miracles and Signs — Additional","10 more formation angles on the moments of divine intervention","","#4a7a5a",[
    ("The Burning Bush That Wasn't Consumed","Exodus 3:2-3 — the sign that stops you — what God does to get your attention","Exodus 3","3-Week"),
    ("The Jordan Divided Twice","Joshua 3 and 2 Kings 2 — two crossings — the theology of new beginnings marked by water","Joshua 3,2 Kings 2","3-Week"),
    ("Gideon's Wet Fleece and Dry","Judges 6:36-40 — the sign requested — and what it reveals about faith that needs confirmation","Judges 6","2-Week"),
    ("Elisha and the Floating Axhead","2 Kings 6:1-7 — the small miracle — God's attention to the ordinary need","2 Kings 6","2-Week"),
    ("The Withered Fig Tree","Matthew 21:18-22 — the only destructive miracle — a theology of the fruitless life","Matthew 21","3-Week"),
    ("The Coin in the Fish's Mouth","Matthew 17:24-27 — provision for the obligation — the miracle that met the tax","Matthew 17","2-Week"),
    ("The Raising of Lazarus in Full","John 11:1-45 — the most thoroughly narrated miracle — delay, death, grief, resurrection","John 11","5-Week"),
    ("The Miracles of Acts","Acts 3,5,9,14,16,20 — a theology of signs continuing in the early church","Various Acts","4-Week"),
    ("The Manna and the Sabbath","Exodus 16:22-30 — double provision on Friday so the people could rest","Exodus 16","3-Week"),
    ("The Sun Stands Still","Joshua 10 — the request that should not have been made — and the God who granted it","Joshua 10","2-Week"),
  ]),
  ("Kingdom Parables — Additional","10 more formation angles on the kingdom stories","","#6a5a3a",[
    ("The Two Sons","Matthew 21:28-32 — said yes and did nothing, said no and went — the formation of actual obedience","Matthew 21","3-Week"),
    ("The Tenants in the Vineyard","Matthew 21:33-46 — the parable that made the chief priests want to arrest Jesus","Matthew 21","3-Week"),
    ("The Wedding Banquet","Matthew 22:1-14 — filled the hall with whoever he could find — and the man without a garment","Matthew 22","3-Week"),
    ("The Pharisee and the Tax Collector","Luke 18:9-14 — two prayers — the one that justified — a formation text for Sunday morning","Luke 18","40-Day"),
    ("The Two Debtors","Luke 7:41-43 — the arithmetic of forgiveness — why the woman loved much","Luke 7","2-Week"),
    ("The Unforgiving Servant","Matthew 18:21-35 — answers Peter's question about forgiveness with a formation parable","Matthew 18","4-Week"),
    ("The Tower Builder and the King at War","Luke 14:28-33 — two parables of counting the cost before beginning","Luke 14","3-Week"),
    ("The Lost Coin","Luke 15:8-10 — the middle parable — the woman who searches the house","Luke 15","2-Week"),
    ("The Persistent Widow","Luke 18:1-8 — the judge who feared neither God nor man — worn out by a widow","Luke 18","3-Week"),
    ("The Friend at Midnight","Luke 11:5-13 — shameless asking — what the parable is actually teaching","Luke 11","3-Week"),
  ]),
  ("Crucifixion Theology — Additional","10 more formation angles on the center of Scripture","","#8a3a3a",[
    ("The Cross as Victory","Colossians 2:13-15 — the cross as a triumphal procession — the powers disarmed","Colossians 2","4-Week"),
    ("The Cross as Ransom","Mark 10:45 — what Jesus gave and to whom — a formation theology of the ransom","Mark 10","3-Week"),
    ("The Cross as Propitiation","Romans 3:25, 1 John 2:2 — what God's wrath and love look like at the same time","Romans 3,1 John 2","4-Week"),
    ("The Cross as New Exodus","1 Corinthians 5:7, Luke 9:31 — the crucifixion as the ultimate exodus","1 Cor 5,Luke 9","4-Week"),
    ("The Cross as New Creation","2 Corinthians 5:17-21 — the cross at the center of the new creation's beginning","2 Corinthians 5","4-Week"),
    ("The Friday Before Sunday","Matthew 27 — a congregation that spends more time on Good Friday before celebrating Easter","Matthew 27","Holy Week"),
    ("What the Cross Says About God","Romans 5:8 — the cross as the primary argument about who God is","Romans 5","40-Day"),
    ("Crucifixion in the Psalms","Psalms 22,31,69 — hearing the cross in the Psalter before the Gospels","Ps 22,31,69","Holy Week"),
    ("The Cross as Moral Influence","1 Peter 2:21-25 — the cross as the pattern of formation — leaving an example","1 Peter 2","3-Week"),
    ("The Cross as Expiation","Leviticus 16 and Romans 3 — sin removed, not just wrath satisfied","Lev 16,Romans 3","4-Week"),
  ]),
  ("New Creation — Additional","10 more formation angles on the eschatological hope","","#3a6a7a",[
    ("The New Creation Has Already Come","2 Corinthians 5:17 — the congregation's conversion as participation in new creation now","2 Corinthians 5","4-Week"),
    ("The Groaning and the Hope","Romans 8:18-25 — part of the groaning — holding the hope","Romans 8","4-Week"),
    ("The New Song","Revelation 5:9-10 — given the song before seeing the fulfillment","Revelation 5","3-Week"),
    ("The Redemption of the Body","Romans 8:23 — awaiting the adoption — the body specifically","Romans 8","3-Week"),
    ("The First Fruits of the Spirit","Romans 8:23 — what the Spirit's present presence says about the future's certainty","Romans 8","3-Week"),
    ("Cosmic Reconciliation","Colossians 1:19-20 — the scope of Christ's reconciling work — all things","Colossians 1","4-Week"),
    ("The Restoration of All Things","Acts 3:21 — the apokatastasis panton — the restoration of all things","Acts 3","3-Week"),
    ("The Resurrection as New Creation","1 Corinthians 15 — the resurrection as the first installment","1 Corinthians 15","4-Week"),
    ("If Anyone Is in Christ","2 Corinthians 5:17 — new creation as present experience, not future event","2 Corinthians 5","3-Week"),
    ("Living Toward the End","1 Thessalonians 4-5 — eschatology as ethics — what you do while you wait","1 Thessalonians 4-5","4-Week"),
  ]),
]

# ── 10 NEW STORY / THEME CATEGORIES ─────────────────────────────────────────

STORIES_NEW = [
  ("The Seven Last Words of Christ","Ten series built from the seven sayings of Jesus on the cross","","#8a3a3a",[
    ("Father Forgive Them","Luke 23:34 — the prayer for those who are crucifying you","Luke 23","Holy Week"),
    ("Today You Will Be With Me","Luke 23:43 — last-moment salvation — the gospel not a loophole","Luke 23","Holy Week"),
    ("Woman Behold Your Son","John 19:26-27 — community care arranged from the cross while dying","John 19","Holy Week"),
    ("My God My God Why","Matthew 27:46 — divine abandonment — what it was and what it was not","Matthew 27","Holy Week"),
    ("I Thirst","John 19:28 — the eternal Word saying 'I am thirsty' — the incarnation's last moment","John 19","Holy Week"),
    ("It Is Finished","John 19:30 — tetelestai — the accounting term that ended the debt","John 19","Holy Week"),
    ("Father Into Your Hands","Luke 23:46 — Psalm 31 as a bedtime prayer becoming a death prayer","Luke 23,Ps 31","Holy Week"),
    ("The Cross as Seven Formation Moments","All seven last words as a complete formation theology","Luke 23,John 19","7-Week"),
    ("The Mockery Surrounding the Statements","Matthew 27:39-44 — what the crowd saw vs. what Jesus was doing","Matthew 27","Holy Week"),
    ("The Silence After the Cross","Mark 15:37-39 — the tearing curtain, the centurion's confession, the empty sky","Mark 15","Holy Week"),
  ]),
  ("The Beatitudes in Depth","Ten formation series — one beatitude per series","","#4a5a8a",[
    ("Blessed Are the Poor in Spirit","Matthew 5:3 — spiritual poverty as the beginning of the formation life","Matthew 5","3-Week"),
    ("Blessed Are Those Who Mourn","Matthew 5:4 — grief allowed — why the mourning are blessed","Matthew 5","3-Week"),
    ("Blessed Are the Meek","Matthew 5:5 — the most countercultural beatitude — meekness as strength","Matthew 5","3-Week"),
    ("Blessed Are Those Who Hunger","Matthew 5:6 — built on appetite — what it means to hunger for righteousness","Matthew 5","3-Week"),
    ("Blessed Are the Merciful","Matthew 5:7 — giving what you have received — the mercy that comes back","Matthew 5","3-Week"),
    ("Blessed Are the Pure in Heart","Matthew 5:8 — purity as integration — single-heartedness","Matthew 5","3-Week"),
    ("Blessed Are the Peacemakers","Matthew 5:9 — the active verb — peacemakers, not peace lovers","Matthew 5","3-Week"),
    ("Blessed Are the Persecuted","Matthew 5:10-12 — why the blessed are persecuted — the formation of theology of opposition","Matthew 5","3-Week"),
    ("The Eight Together","The formation of a congregation that reads the Beatitudes as a portrait of one person","Matthew 5:3-12","40-Day"),
    ("The Beatitudes and the Lord's Prayer","Matthew 5:3-12 and 6:9-13 — inner life and outer practice as a complete unit","Matthew 5-6","40-Day"),
  ]),
  ("The I Am Sayings of Jesus","Ten series built from John's seven I Am statements","","#3a5a7a",[
    ("I Am the Bread of Life","John 6:35 — the claim made after the feeding of the five thousand","John 6","4-Week"),
    ("I Am the Light of the World","John 8:12 — the claim made in the middle of the Feast of Tabernacles","John 8","3-Week"),
    ("I Am the Door","John 10:7-9 — access and protection — both meanings held together","John 10","3-Week"),
    ("I Am the Good Shepherd","John 10:11-18 — the shepherd who lays down his life","John 10","40-Day"),
    ("I Am the Resurrection and the Life","John 11:25-26 — the claim made at the graveside before the miracle","John 11","4-Week"),
    ("I Am the Way the Truth and the Life","John 14:6 — three nouns and how they hold together","John 14","4-Week"),
    ("I Am the True Vine","John 15:1-8 — abiding — the relationship that is the source of everything","John 15","40-Day"),
    ("The Seven Together as Christology","All seven I Am sayings as a complete formation Christology","John 6-15","7-Week"),
    ("Before Abraham Was I Am","John 8:58 — applying Exodus 3:14 to himself — the divine name claim","John 8","3-Week"),
    ("The I Am Sayings and the Old Testament","Each of the seven traced back to its OT background","John 6-15","7-Week"),
  ]),
  ("The Lord's Prayer Phrase by Phrase","Ten series — one phrase per series — a complete formation curriculum","","#5a4a8a",[
    ("Our Father","Matthew 6:9 — addressing God as Father — what the word meant and what it forms","Matthew 6","4-Week"),
    ("Who Art in Heaven","Matthew 6:9 — divine transcendence that does not become remoteness","Matthew 6","3-Week"),
    ("Hallowed Be Your Name","Matthew 6:9 — caring about God's reputation — what hallowing requires","Matthew 6","4-Week"),
    ("Your Kingdom Come","Matthew 6:10 — the primary prayer as kingdom-oriented — wanting the kingdom","Matthew 6","40-Day"),
    ("Your Will Be Done on Earth as in Heaven","Matthew 6:10 — the most ambitious phrase in the prayer","Matthew 6","4-Week"),
    ("Give Us This Day Our Daily Bread","Matthew 6:11 — the theology of daily dependence","Matthew 6","4-Week"),
    ("Forgive Us as We Forgive","Matthew 6:12 — the only petition tied to our performance","Matthew 6","40-Day"),
    ("Lead Us Not into Temptation","Matthew 6:13 — praying about temptation before it arrives","Matthew 6","3-Week"),
    ("Deliver Us from Evil","Matthew 6:13 — what evil is and what deliverance from it looks like","Matthew 6","3-Week"),
    ("The Lord's Prayer as Daily Formation","Praying the Lord's Prayer every day — understanding what you are doing each time","Matthew 6","40-Day"),
  ]),
  ("The Ten Commandments as Formation","Ten series — one commandment per series — the Decalogue as formation curriculum","","#4a7a5a",[
    ("No Other Gods","Exodus 20:3 — the commandment that makes all others possible","Exodus 20","4-Week"),
    ("No Idols","Exodus 20:4-6 — idolatry not as ancient superstition but as present default","Exodus 20","4-Week"),
    ("The Name","Exodus 20:7 — not about swearing but about misrepresenting God","Exodus 20","3-Week"),
    ("Remember the Sabbath","Exodus 20:8-11 — a formation practice, not a rule","Exodus 20","40-Day"),
    ("Honor Father and Mother","Exodus 20:12 — the only commandment with a promise — what honoring looks like","Exodus 20","3-Week"),
    ("You Shall Not Murder","Exodus 20:13 — and the Sermon on the Mount's extension of it","Exodus 20","3-Week"),
    ("You Shall Not Commit Adultery","Exodus 20:14 — a complete theology of fidelity in marriage and covenant","Exodus 20","3-Week"),
    ("You Shall Not Steal","Exodus 20:15 — beyond crime to economic injustice","Exodus 20","3-Week"),
    ("You Shall Not Bear False Witness","Exodus 20:16 — a complete theology of truth in court and in community","Exodus 20","3-Week"),
    ("You Shall Not Covet","Exodus 20:17 — the only commandment about an internal state — desire itself","Exodus 20","40-Day"),
  ]),
  ("The Fruits of the Spirit in Depth","Ten formation series — one fruit per series — Galatians 5:22-23 in full","","#5a7a3a",[
    ("Love The Root of the Fruit","Galatians 5:22 — why love is listed first — not the first among equals","Galatians 5","40-Day"),
    ("Joy Not Happiness","Galatians 5:22 — the joy that does not depend on circumstances","Galatians 5","4-Week"),
    ("Peace The Shalom Formation","Galatians 5:22 — shalom as wholeness, not just cessation","Galatians 5","4-Week"),
    ("Patience The Long-Suffering Formation","Galatians 5:22 — makrothumia — the long-tempered person","Galatians 5","4-Week"),
    ("Kindness The Goodness of Manner","Galatians 5:22 — chrestotes — not using your rightness as a weapon","Galatians 5","3-Week"),
    ("Goodness The Moral Strength","Galatians 5:22 — agathosune — not only good but does good","Galatians 5","3-Week"),
    ("Faithfulness The Reliable Life","Galatians 5:22 — pistis as trustworthiness — the same person tomorrow as today","Galatians 5","4-Week"),
    ("Gentleness The Strength Submitted","Galatians 5:23 — prautes — the power that has been bridled","Galatians 5","3-Week"),
    ("Self-Control The Trained Will","Galatians 5:23 — egkrateia — holding yourself to what you know is true when you do not feel it","Galatians 5","40-Day"),
    ("The Nine Together A Formation Portrait","All nine as a portrait of the person the Spirit is forming","Galatians 5:22-23","9-Week"),
  ]),
  ("The Resurrection Appearances","Ten series — one appearance per series — what the risen Christ did when he showed up","","#8a4a3a",[
    ("Mary Magdalene in the Garden","John 20:11-18 — the first appearance — to a weeping woman — spoken by name","John 20","Easter"),
    ("The Women on the Road","Matthew 28:9-10 — grabbed his feet and worshipped him","Matthew 28","Easter"),
    ("The Two on the Emmaus Road","Luke 24:13-35 — walked, opened Scriptures, broke bread","Luke 24","Easter"),
    ("Simon Peter Alone","Luke 24:34 — mentioned in one sentence — the private encounter that changed Peter","Luke 24","Easter"),
    ("The Disciples Without Thomas","John 20:19-23 — peace, breath, commissioning — the first Sunday evening","John 20","Easter"),
    ("Thomas One Week Later","John 20:24-29 — 'reach your hand here' — and the highest confession","John 20","Easter"),
    ("The Seven by the Sea","John 21:1-23 — the fire, the fish, the three questions","John 21","Easter"),
    ("The Great Commission Appearance","Matthew 28:16-20 — worshipped and doubted simultaneously — and were sent anyway","Matthew 28","Easter"),
    ("The Ascension","Acts 1:1-11 — the cloud, the two men, the question about gazing","Acts 1","Easter"),
    ("The Damascus Road Appearance","Acts 9, 1 Corinthians 15:8 — last in the list, most unexpected — born out of due time","Acts 9","Easter"),
  ]),
  ("The Parables of Lostness","Ten series built from Luke 15 and the companion parables","","#6a4a8a",[
    ("The Lost Sheep Full Formation","Luke 15:3-7 — leaving the ninety-nine — the arithmetic of grace","Luke 15","4-Week"),
    ("The Lost Coin Full Formation","Luke 15:8-10 — searches until she finds — and calls her neighbors","Luke 15","3-Week"),
    ("The Lost Son Full Formation","Luke 15:11-24 — far country, pig pen, coming to himself, return","Luke 15","40-Day"),
    ("The Elder Brother Full Formation","Luke 15:25-32 — home all along, could not find his way to the celebration","Luke 15","4-Week"),
    ("The Running Father Full Formation","Luke 15:20 — the most shocking verb in the parable","Luke 15","3-Week"),
    ("What Was Lost Is Found","Luke 15 as a complete theology of finding — sheep, coin, son, and celebration","Luke 15","4-Week"),
    ("The Lost Kingdom Matthew 13","Matthew 13:44-46 — the treasure and the pearl — different finders, same response","Matthew 13","3-Week"),
    ("The Prodigal as Resurrection","Luke 15:24 — 'dead and alive again, lost and found' — the death-and-resurrection language","Luke 15","3-Week"),
    ("Lostness in Ezekiel 34","Ezekiel 34:16 and Luke 15 — the theology of lostness Jesus inherited from the prophet","Ezekiel 34,Luke 15","4-Week"),
    ("The Lost in Isaiah","Isaiah 53:6 and Luke 15 — 'all we like sheep have gone astray' — the prophetic root of the parables","Isaiah 53,Luke 15","3-Week"),
  ]),
  ("The Armor of God in Depth","Ten series — the full armor of Ephesians 6 — one piece per series","","#5a3a6a",[
    ("The Full Armor — Why All of It","Ephesians 6:11 — the piece you skip is the vulnerability","Ephesians 6","3-Week"),
    ("The Belt of Truth","Ephesians 6:14 — the foundation garment — what makes everything else stay in place","Ephesians 6","4-Week"),
    ("The Breastplate of Righteousness","Ephesians 6:14 — the imputed righteousness that protects the heart","Ephesians 6","4-Week"),
    ("Feet Shod with the Gospel","Ephesians 6:15 — readiness as a formation posture — always prepared to move","Ephesians 6","3-Week"),
    ("The Shield of Faith","Ephesians 6:16 — how to use faith as a shield — the defensive application","Ephesians 6","4-Week"),
    ("The Helmet of Salvation","Ephesians 6:17 — the identity that cannot be taken — protecting the mind","Ephesians 6","4-Week"),
    ("The Sword of the Spirit","Ephesians 6:17 — using the word offensively — not just to comfort but to engage","Ephesians 6","4-Week"),
    ("Prayer as the Context of the Armor","Ephesians 6:18-20 — the atmosphere the armor requires","Ephesians 6","4-Week"),
    ("The Armor and Spiritual Warfare","Ephesians 6:10-20 — the opponent, the armor, and the posture — a complete theology","Ephesians 6","6-Week"),
    ("The Armor in Thessalonians and Isaiah","1 Thessalonians 5:8, Isaiah 59:17 — Paul's imagery traced back through the prophets","Isa 59,1 Thess 5,Eph 6","4-Week"),
  ]),
  ("The Wonders of the Incarnation","Ten series — a formation theology of the incarnation for Advent and the whole year","","#4a5a8a",[
    ("The Word Became Flesh","John 1:14 — the complete theology of the incarnation","John 1","Advent"),
    ("Born of a Woman","Galatians 4:4 — 'in the fullness of time' — the timing and manner of the incarnation","Galatians 4","Advent"),
    ("The Emptying","Philippians 2:5-8 — kenosis — what the Son gave up and what he kept","Philippians 2","Advent"),
    ("God With Us","Matthew 1:23 — Immanuel — what the name means and what it produces","Matthew 1","Advent"),
    ("The Manger as Statement","Luke 2:7 — what the first bed says about what the incarnation was like","Luke 2","Advent"),
    ("Visited and Redeemed","Luke 1:68 — Zechariah's song — the formation text for the congregation that has been waiting","Luke 1","Advent"),
    ("The Light Shining in Darkness","John 1:5 — the light the darkness has not overcome — the theology of Advent","John 1","Advent"),
    ("The Incarnation and Suffering","Hebrews 2:14-18 — why the incarnation required full humanity — the solidarity of suffering","Hebrews 2","3-Week"),
    ("The Incarnation as Model","Philippians 2:5-11 — receiving the incarnation as the pattern for the congregation's life","Philippians 2","4-Week"),
    ("Before the Incarnation","John 1:1-3 — the Word's pre-existence — before Bethlehem","John 1","Advent"),
  ]),
]
