BIBLE_DEEP = [
  ("Pentateuch — Deeper Angles","25 more formation approaches to the first five books","Genesis · Exodus · Leviticus · Numbers · Deuteronomy","#4a5a8a",[
    ("Let There Be Light Before the Sun","Genesis 1:3 — light on day one, sun on day four — the formation of a theology of the source of all light","Genesis 1","3-Week"),
    ("The Breath of Life","Genesis 2:7 — what it means that God breathed into dust — the animated self as formation theology","Genesis 2","3-Week"),
    ("Where Are You","Genesis 3:9 — the first question God asks after the fall — the formation of a theology of divine pursuit","Genesis 3","40-Day"),
    ("The First Promise","Genesis 3:15 — the proto-evangelium — the formation of a congregation that reads all of Scripture as the story of the seed","Genesis 3","3-Week"),
    ("The Cain Question","Genesis 4 — am I my brother's keeper — the formation of a theology of responsibility for the person next to you","Genesis 4","3-Week"),
    ("Enoch Who Walked With God","Genesis 5:24 — the man whose greatest achievement was a relationship — the formation of proximity","Genesis 5","2-Week"),
    ("The Covenant Before the Law","Genesis 9 — the rainbow covenant — God's commitment to all humanity before Israel existed","Genesis 9","3-Week"),
    ("Abram's First Step","Genesis 12:1-3 — the formation of the call that arrives before everything is figured out","Genesis 12","3-Week"),
    ("Hagar Twice","Genesis 16 and 21 — two wilderness encounters — the formation of the God who sees before you see him","Genesis 16,21","4-Week"),
    ("The Deep Sleep of Abraham","Genesis 15 — God passed between the pieces while Abram slept — the formation of unilateral covenant","Genesis 15","4-Week"),
    ("The Test of Everything","Genesis 22 — the command that contradicts the promise — and what God was actually doing","Genesis 22","4-Week"),
    ("Jacob's Ladder","Genesis 28 — the formation of God's presence in the most ordinary displaced moment","Genesis 28","3-Week"),
    ("Joseph's Theology of Suffering","Genesis 50:20 — you meant it for evil, God meant it for good — formed in the pit over years","Genesis 50","4-Week"),
    ("I Am Who I Am","Exodus 3:14 — the most important name ever spoken — the formation of a congregation built on it","Exodus 3","40-Day"),
    ("The Passover Lamb","Exodus 12 — the formation of a complete substitutionary theology before the New Testament explains it","Exodus 12","Holy Week"),
    ("The Song at the Sea","Exodus 15 — singing before the wilderness arrives — the formation of praise before the next crisis","Exodus 15","3-Week"),
    ("The Ten Words","Exodus 20 — the Decalogue as formation architecture, not legal code","Exodus 20","40-Day"),
    ("The Glory of the Lord","Exodus 33-34 — Moses asked to see God's glory — and what God showed him instead","Exodus 33","4-Week"),
    ("The Jubilee","Leviticus 25 — the formation of a theology of economic reset — what the fiftieth year says about ownership","Leviticus 25","4-Week"),
    ("The Aaronic Blessing","Numbers 6:24-26 — the formation of a congregation that understands benediction as theology","Numbers 6","3-Week"),
    ("Moses' Intercession","Numbers 14 — arguing with God on behalf of the people who just rejected him — intercession's formation cost","Numbers 14","4-Week"),
    ("The Bronze Serpent","Numbers 21 — look and live — the formation text Jesus applied to himself in John 3","Numbers 21","3-Week"),
    ("Forty Years Reconsidered","Deuteronomy 8 — the formation theology of the years that felt like waste but were formation","Deuteronomy 8","4-Week"),
    ("Love the Lord Your God","Deuteronomy 6 — the Great Commandment as complete formation architecture for the whole life","Deuteronomy 6","40-Day"),
    ("Choices Set Before You","Deuteronomy 30 — life and death, blessing and curse — the architecture of the formation choice","Deuteronomy 30","3-Week"),
  ]),
  ("Historical Books — Deeper Angles","25 more formation approaches to Israel's story in the land","Joshua · Judges · Ruth · Samuel · Kings · Chronicles · Ezra · Nehemiah · Esther","#3a6a7a",[
    ("The Caleb Clause","Joshua 14 — waited forty-five years for the mountain God promised and climbed it when he got there","Joshua 14","3-Week"),
    ("As for Me and My House","Joshua 24:15 — the formation of the public covenant commitment that is chosen, not coerced","Joshua 24","40-Day"),
    ("The Cycle in Judges","Judges 1-3 — sin, consequence, cry, deliverance, rest, repeat — the anatomy of drift","Judges 1-3","4-Week"),
    ("Gideon's Fleece","Judges 6 — the formation theology of the sign requested — what it reveals about faith needing confirmation","Judges 6","3-Week"),
    ("Boaz at the Gate","Ruth 4 — the covenant-keeping that happens in front of witnesses — public faithfulness","Ruth 4","3-Week"),
    ("The Book of Ruth as Gospel","Ruth — grace, redemption, the outsider who becomes the ancestor — a four-chapter gospel","Ruth","40-Day"),
    ("Give Us a King","1 Samuel 8 — the formation of a congregation that understands what it is asking when it wants to be like everyone else","1 Samuel 8","3-Week"),
    ("David and Goliath Recovered","1 Samuel 17 — not a story about courage but a formation text about the name of the Lord","1 Samuel 17","3-Week"),
    ("Nathan's Parable","2 Samuel 12 — the story that exposed the king — the formation of confrontational wisdom","2 Samuel 12","3-Week"),
    ("Mephibosheth at the Table","2 Samuel 9 — the lame man summoned to the king's table not for merit but for covenant","2 Samuel 9","3-Week"),
    ("Solomon's Prayer at the Temple","1 Kings 8 — the most comprehensive prayer in the OT — a formation text for every gathering","1 Kings 8","40-Day"),
    ("The Contest on Carmel","1 Kings 18 — the formation of a congregation that knows what revival looks like before it prays for one","1 Kings 18","4-Week"),
    ("The Widow of Zarephath","1 Kings 17 — the last handful given first — and what happens to those who give to the prophet","1 Kings 17","3-Week"),
    ("The Four Lepers","2 Kings 7 — a congregation with good news that it is keeping to itself","2 Kings 7","3-Week"),
    ("The Shunammite Woman","2 Kings 4 — the woman who made a room for the prophet and received a son she did not ask for","2 Kings 4","3-Week"),
    ("Josiah and the Found Book","2 Kings 22-23 — a king who heard the law read and tore his robes — and changed a nation","2 Kings 22","3-Week"),
    ("Hezekiah's Letter Before the Lord","2 Kings 19 — spreading the enemy's letter before God — prayer as presentation","2 Kings 19","3-Week"),
    ("Elisha's Double Portion","2 Kings 2 — the formation of the successor who asked for what no human could grant","2 Kings 2","3-Week"),
    ("Rebuilding the Altar First","Ezra 3 — not the walls first, the altar — the formation of a community that worships before it builds","Ezra 3","3-Week"),
    ("Nehemiah's Arrow Prayer","Nehemiah 2:4 — the prayer in the gap between the king's question and the answer","Nehemiah 2","3-Week"),
    ("Builders with Swords","Nehemiah 4-6 — building and guarding simultaneously — the formation of dual-handed leadership","Nehemiah 4","4-Week"),
    ("Esther's Fast","Esther 4 — preparation before access — what Esther did before she approached the king","Esther 4","3-Week"),
    ("The God Who Is Not Mentioned","Esther — providence in the book where God is hidden — the formation of a trust that does not require visibility","Esther","40-Day"),
    ("The Genealogies as Formation","1 Chronicles 1-9 — the formation of a congregation that understands it is part of a longer story than its own lifespan","1 Chronicles 1","3-Week"),
    ("Solomon's Decline","1 Kings 11 — the formation cost of the divided heart — the slow drift that begins with the thing God said not to","1 Kings 11","4-Week"),
  ]),
  ("Wisdom Literature — Deeper Angles","25 more formation approaches to Job, Psalms, Proverbs, Ecclesiastes, Song of Solomon","Job · Psalms · Proverbs · Ecclesiastes · Song of Solomon","#6a4a8a",[
    ("Job's First Response","Job 1:20-22 — the formation of worshipping before you understand","Job 1","3-Week"),
    ("The Comforter of Job","Job 2:11-13 — sitting in silence for seven days — the best thing Job's friends did","Job 2","2-Week"),
    ("Elihu the Young Man","Job 32-37 — the speech the Lord does not rebuke — the formation of the young voice that waited","Job 32","3-Week"),
    ("Job After the Whirlwind","Job 42 — restoration and the formation theology of what was given back","Job 42","3-Week"),
    ("Psalm 46 for Turbulent Times","God is our refuge and strength — the formation text for the congregation in the earthquake","Psalm 46","3-Week"),
    ("The Alphabetic Psalm","Psalm 119 — 176 verses on the word of God — the formation of a Scripture-saturated congregation","Psalm 119","40-Day"),
    ("The Enthronement Psalms","Psalms 93-100 — the formation of a congregation that worships a king before it reads the news","Psalms 93","4-Week"),
    ("The Penitential Psalms","Psalms 6,32,38,51,102,130,143 — a formation theology of repentance across seven texts","Seven Psalms","7-Week"),
    ("Praise in the Storm","Psalm 42-43 — preaching to yourself — the formation of the soul that addresses its own despair","Psalm 42","3-Week"),
    ("The Royal Psalms","Psalms 2,45,72,110 — a formation Christology built from the Psalter","Various Psalms","4-Week"),
    ("Proverbs on the Tongue","Proverbs 10-15 — the formation of a congregation whose speech has been disciplined by wisdom","Proverbs 10","4-Week"),
    ("Wisdom Before Creation","Proverbs 8 — wisdom present at the creation — and the formation of a Christology from the image","Proverbs 8","4-Week"),
    ("Proverbs on Friendship","What Proverbs says about forming friendship — nine different kinds described across the book","Proverbs 17","4-Week"),
    ("The Preacher's Final Exam","Ecclesiastes 1 and 12 together — the opening confession and the final counsel","Ecclesiastes 1,12","3-Week"),
    ("Better Than","Ecclesiastes' 28 'better than' sayings — what wisdom considers superior — a formation value inventory","Ecclesiastes 4","4-Week"),
    ("Joy and Toil Together","Ecclesiastes 2-3 — the formation of finding joy in ordinary work before the meaning question is answered","Ecclesiastes 2","4-Week"),
    ("The Meaninglessness of Comparison","Ecclesiastes 4 on envy — the formation of a congregation that has stopped keeping score","Ecclesiastes 4","3-Week"),
    ("The Vineyard and the Beloved","Song of Songs 1-2 — the formation of a theology of desire as gift — the body as good before it was fallen","Song of Songs 1","3-Week"),
    ("Love Is as Strong as Death","Song of Songs 8:6-7 — the formation of a theology of love's durability — what love can survive","Song of Songs 8","3-Week"),
    ("The Dream Sequence","Song of Songs 3 and 5 — the love sought, lost, and found again — the formation of covenant persistence","Song of Songs 3,5","3-Week"),
    ("The Maschil Psalms","The teaching psalms — Psalms 32,42,44,45,52-55 — a formation curriculum from the Psalter's wisdom genre","Various Psalms","6-Week"),
    ("Psalms of Trust","Psalms 11,16,23,27,46,62,91,121,131 — the formation of a trusting congregation across nine texts","Various Psalms","9-Week"),
    ("Ancient Wisdom for the Digital Age","Proverbs on speech, attention, friendship, money — the most current book in the Bible","Proverbs","21-Day"),
    ("The Asaph Psalms","Psalms 50,73-83 — the formation of a congregation shaped by the worship leader who asked hardest questions","Asaph Psalms","11-Week"),
    ("The Psalms of Ascent in Full","Psalms 120-134 — fifteen songs as a complete formation pilgrimage — one per session","Psalms 120","15-Week"),
  ]),
  ("Major Prophets — Deeper Angles","25 more formation approaches to Isaiah, Jeremiah, Lamentations, Ezekiel, Daniel","Isaiah · Jeremiah · Lamentations · Ezekiel · Daniel","#8a4a30",[
    ("The Holy One of Israel","Isaiah's name for God — 26 times — the formation of holiness and intimacy held together","Isaiah 1","4-Week"),
    ("The Peaceable Kingdom","Isaiah 11 — the formation of a congregation shaped by the vision of the end — living from the last chapter","Isaiah 11","4-Week"),
    ("The Vineyard Song","Isaiah 5 — what God planted and what he expected — and what he got — the anatomy of unfaithfulness","Isaiah 5","3-Week"),
    ("I Am Doing a New Thing","Isaiah 43:19 — the formation of a congregation that can see the new thing when the old thing has collapsed","Isaiah 43","4-Week"),
    ("Streams in the Desert","Isaiah 43-44 — the formation of trust when the route seems impassable","Isaiah 43","3-Week"),
    ("Isaiah 53 Verse by Verse","Five sessions through the most prophetically significant passage in the Old Testament","Isaiah 53","5-Week"),
    ("The Year of the Lord's Favor","Isaiah 61 — the full sentence Jesus stopped reading — the formation of the whole mandate","Isaiah 61","3-Week"),
    ("The Potter and the Clay","Isaiah 64 and Jeremiah 18 — the formation of a complete theology of God's prerogative and our receptivity","Isaiah 64,Jer 18","4-Week"),
    ("Jeremiah's Purchase","Jeremiah 32 — buying a field during a siege — the formation of hope as embodied action","Jeremiah 32","4-Week"),
    ("The Book of Consolation","Jeremiah 30-33 — four chapters of hope inside the most heartbreaking prophecy","Jeremiah 30","4-Week"),
    ("The Letter to the Exiles","Jeremiah 29 — build houses, plant gardens, seek the peace of the city — the formation of embedded faithfulness","Jeremiah 29","40-Day"),
    ("The Steadfast Love That Does Not Cease","Lamentations 3:22-23 — great is your faithfulness — the formation text that survives inside the darkest book","Lamentations 3","7-Day"),
    ("Lamentations in Full","Five poems — one per session — the complete formation curriculum for grief","Lamentations 1","5-Week"),
    ("The Glory Departs and Returns","Ezekiel 10 and 43 — departure and return of God's glory — the formation of presence theology","Ezekiel 10,43","4-Week"),
    ("The Watchman","Ezekiel 3 and 33 — the formation of the leader who carries the weight of the word","Ezekiel 3,33","4-Week"),
    ("Individual Responsibility","Ezekiel 18 — the soul who sins shall die — the formation of personal accountability","Ezekiel 18","3-Week"),
    ("The Shepherd and the Flock","Ezekiel 34 — the most honest text on pastoral leadership in Scripture","Ezekiel 34","4-Week"),
    ("The Temple Vision of Ezekiel","Ezekiel 40-48 — the formation of a congregation shaped by the vision of God's house — perfect, ordered, life-giving","Ezekiel 40","6-Week"),
    ("Faithful in Babylon","Daniel 1 — the first decision that made every later decision easier — integrity as formation strategy","Daniel 1","40-Day"),
    ("Even If He Does Not","Daniel 3 — the formation of faith that does not require rescue to remain faith","Daniel 3","3-Week"),
    ("Daniel's Prayer for Jerusalem","Daniel 9 — reading Jeremiah and then praying as if the fulfillment required his intercession","Daniel 9","4-Week"),
    ("The Ancient of Days","Daniel 7 — the formation of a congregation that sees the throne above every earthly throne","Daniel 7","4-Week"),
    ("Cyrus and Providence","Isaiah 44-45 — the formation of a theology of God using the unexpected instrument","Isaiah 44","3-Week"),
    ("Ezekiel's Enacted Parables","Thirteen acted parables — the formation of embodied proclamation","Ezekiel 4","6-Week"),
    ("His Mercies New Every Morning","Lamentations 3 in context — hope inside despair — the formation that survives the surrounding darkness","Lamentations 3","3-Week"),
  ]),
  ("Minor Prophets — Deeper Angles","25 more formation approaches to the twelve","Hosea · Joel · Amos · Obadiah · Jonah · Micah · Nahum · Habakkuk · Zephaniah · Haggai · Zechariah · Malachi","#5a7a3a",[
    ("The Days of Jezreel","Hosea 2 — the Valley of Trouble becoming a Door of Hope — the formation of restored names","Hosea 2","3-Week"),
    ("Come Let Us Return","Hosea 6 — the formation of a congregation that knows the rhetoric of return without the reality","Hosea 6","3-Week"),
    ("God's Broken Heart","Hosea 11 — the most tender portrait of God's love in the Old Testament","Hosea 11","3-Week"),
    ("The Trumpets of Joel","Joel 2:1 — the formation of a congregation willing to hear the alarm before the catastrophe","Joel 2","3-Week"),
    ("Old Men Will Dream","Joel 2:28 — the formation of a congregation that expects vision across generations","Joel 2","3-Week"),
    ("Seek Me and Live","Amos 5:4 — the simplest invitation in the prophets — the formation of the congregation that responds","Amos 5","3-Week"),
    ("The Plumb Line","Amos 7 — the formation of a theology of measurement — what God uses to evaluate","Amos 7","3-Week"),
    ("Obadiah's Pride Warning","The formation of a congregation that reads the shortest book and finds the largest warning","Obadiah","2-Week"),
    ("Jonah's Prayer from the Fish","Jonah 2 — prayer from the worst possible situation — and what it produced","Jonah 2","3-Week"),
    ("Jonah's Anger at Mercy","Jonah 4 — the prophet furious about grace — and the God who defended his compassion","Jonah 4","3-Week"),
    ("Micah's Courtroom","Micah 6:1-8 — the Lord's case against his people — and what he actually wants","Micah 6","4-Week"),
    ("The Remnant Shall Return","Micah 4-5 — the formation of hope — what the end of the story changes about the middle","Micah 4","3-Week"),
    ("The Fig Tree Does Not Blossom","Habakkuk 3:17-19 — the formation of joy that is not dependent on circumstances","Habakkuk 3","3-Week"),
    ("Habakkuk's Watchtower","Habakkuk 2:1 — standing at the post — the formation of the prayer that waits for an answer","Habakkuk 2","3-Week"),
    ("The Quiet in Zephaniah's Storm","Zephaniah 3:17 — the Lord will quiet you with his love — the still center of the turbulent book","Zephaniah 3","3-Week"),
    ("Haggai's Arithmetic","Haggai 1:5-6 — the formation of a congregation that examines where its resources are going","Haggai 1","3-Week"),
    ("The Signet Ring","Haggai 2:23 — the man cast aside by one king restored by another — the formation of reversal","Haggai 2","2-Week"),
    ("Zechariah's Eight Visions","Eight visions in a single night — hope in concentrated form for the stalled congregation","Zechariah 1","4-Week"),
    ("The Branch","Zechariah 3,6 — the formation of a Christology built from the prophetic Branch image","Zechariah 3,6","4-Week"),
    ("Zechariah's Palm Sunday Prophecy","Zechariah 9:9 — the formation of a congregation that reads the triumphal entry through prophecy","Zechariah 9","Advent"),
    ("I Have Loved You","Malachi 1 — the formation of a congregation that doubts God's love and hears his answer","Malachi 1","4-Week"),
    ("Will a Man Rob God","Malachi 3:10 — the only place God says 'test me' — the formation of a generous congregation","Malachi 3","4-Week"),
    ("The Messenger I Send","Malachi 3:1 — the formation of a congregation preparing for the one who comes before the One","Malachi 3","Advent"),
    ("Prepare the Way","Malachi 4, Isaiah 40, Mark 1 — the formation arc of expectancy across three centuries","Malachi 4,Isa 40","Advent"),
    ("The Sun of Righteousness","Malachi 4:2 — the formation of a congregation that reads the last word of the OT as a formation text for Advent","Malachi 4","Advent"),
  ]),
  ("The Gospels — Deeper Angles","25 more formation approaches to Matthew, Mark, Luke, and John","Matthew · Mark · Luke · John","#4a5a8a",[
    ("The Genealogy as Gospel","Matthew 1 — four women in the line — the formation of a congregation that reads the genealogy as grace","Matthew 1","Advent"),
    ("The Baptism of Jesus","Matthew 3 — the voice from heaven before Jesus had done anything — the formation of identity before performance","Matthew 3","4-Week"),
    ("Salt and Light","Matthew 5:13-16 — the formation of a congregation that understands its public calling before it hears private commands","Matthew 5","3-Week"),
    ("Seek First the Kingdom","Matthew 6:33 — the formation of a theology of priority — the one decision that reorganizes all others","Matthew 6","40-Day"),
    ("The Narrow Gate","Matthew 7:13-14 — the formation of a congregation that understands the formation life is not the broad way","Matthew 7","3-Week"),
    ("Matthew's Five Discourses","The five great teaching blocks as a complete formation curriculum for the people of God","Matthew 5-25","10-Week"),
    ("Mark's Messianic Secret","Why Jesus told people not to tell — the formation of a Messiah who resists being defined by others","Mark 1","4-Week"),
    ("The Servant King","Mark 10:45 — the formation of a theology of service as the grammar of greatness","Mark 10","3-Week"),
    ("The Anointing at Bethany","Mark 14 — what is wasteful to the disciples is memorial to Jesus — the formation of extravagant worship","Mark 14","Holy Week"),
    ("Luke's Special Material","Good Samaritan, Prodigal, Zacchaeus, the Penitent Thief — Luke's unique grace-for-excluded arc","Luke","6-Week"),
    ("The Journey to Jerusalem","Luke 9-19 — what Jesus teaches on the long road to the cross — the formation of a traveling congregation","Luke 9","6-Week"),
    ("The Great Reversal in Luke","Mary, Beatitudes, Rich Fool, Rich Man and Lazarus — the upside-down kingdom arc in Luke","Luke 1-16","40-Day"),
    ("The Emmaus Road","Luke 24 — Scriptures explained, bread broken, recognition — the formation of Sunday encounter","Luke 24","4-Week"),
    ("John's Prologue as Foundation","John 1:1-18 — the doctrinal ground of the entire Gospel — the formation of a Christology that holds","John 1","4-Week"),
    ("The New Birth","John 3 — born of water and Spirit — the formation of a congregation that understands regeneration","John 3","4-Week"),
    ("The Good Shepherd","John 10 — the formation of a congregation that knows the voice — and what the knowing requires","John 10","4-Week"),
    ("The Bread of Life Discourse","John 6 — the formation of a congregation that eats the bread that does not lead to eventual hunger","John 6","4-Week"),
    ("The Vine and the Branches","John 15 — the formation of the congregation that understands why spiritual formation feels like pruning","John 15","40-Day"),
    ("The Upper Room Discourse","John 13-17 — the formation theology of the night before — what Jesus said when time was short","John 13","5-Week"),
    ("Peace I Leave With You","John 14:27 — the formation of a theology of the peace that the world cannot give or take","John 14","3-Week"),
    ("Thomas After Resurrection","John 20:24-29 — the eight days of uncertainty and what Jesus did when he arrived for Thomas","John 20","3-Week"),
    ("Do You Love Me","John 21 — the threefold restoration at a fire — and the commission that followed","John 21","4-Week"),
    ("Come and See — Follow Me","John 1:39 and 21:22 — the alpha and omega of discipleship in the Fourth Gospel","John 1,21","3-Week"),
    ("The High Priestly Prayer in Full","John 17 — the model of priestly intercession — what Jesus prayed and what it means we are prayed for","John 17","5-Week"),
    ("The Women at the Tomb","All four resurrection accounts — the formation theology of being chosen as first witness","Matt 28,Mark 16,Luke 24,John 20","Easter"),
  ]),
  ("Acts — Deeper Angles","25 more formation approaches to Acts","Acts · Early Church · Pentecost · Missionary Journeys","#3a6a7a",[
    ("You Will Be My Witnesses","Acts 1:8 — the formation architecture of the whole book — Jerusalem to ends of the earth","Acts 1","40-Day"),
    ("Day by Day","Acts 2:46-47 — the small daily things that produce the large yearly results","Acts 2","40-Day"),
    ("When They Saw the Boldness","Acts 4:13 — the formation of a congregation identified by boldness that cannot be explained without Jesus","Acts 4","3-Week"),
    ("The Prayer of Acts 4","Acts 4:24-31 — the early church's response to persecution — what they actually asked for","Acts 4","4-Week"),
    ("All Things in Common","Acts 4:32-35 — the formation of a congregation that holds possessions loosely because it holds community tightly","Acts 4","3-Week"),
    ("The Deacon Who Preached","Acts 6-7 — service and proclamation as inseparable — the formation of Stephen","Acts 6","4-Week"),
    ("Philip in Samaria","Acts 8 — taking the gospel to the place the original community avoided","Acts 8","3-Week"),
    ("Peter's Vision Three Times","Acts 10:9-16 — the formation of a congregation that has to hear the same vision three times before it believes it","Acts 10","3-Week"),
    ("While Peter Was Still Speaking","Acts 10:44 — the formation of a congregation that stops managing who the Spirit is allowed to fall on","Acts 10","3-Week"),
    ("The Antioch Breakthrough","Acts 11:19-26 — the church that preached to Greeks and was first called Christians","Acts 11","4-Week"),
    ("The First Mission","Acts 13:1-3 — the congregation that fasted, prayed, and sent its best people","Acts 13","3-Week"),
    ("Lydia's Household","Acts 16 — the first European convert — faith and the household that became a church","Acts 16","3-Week"),
    ("Prison and Praise","Acts 16 — the formation of a theology of worship in confinement","Acts 16","3-Week"),
    ("Mars Hill","Acts 17 — the formation of cultural engagement without cultural capitulation","Acts 17","3-Week"),
    ("The Ephesian Riot","Acts 19 — the formation of a congregation whose impact changes the economics of a city","Acts 19","3-Week"),
    ("Paul's Miletus Farewell","Acts 20:17-38 — the pastor's farewell speech — what Paul said to the elders he would not see again","Acts 20","4-Week"),
    ("The Shipwreck","Acts 27 — the formation of a theology of storms — Paul's calm in the catastrophic","Acts 27","3-Week"),
    ("Unhindered","Acts 28 — the final word — the formation theology of a gospel that cannot be stopped","Acts 28","3-Week"),
    ("The House Church Network","Acts 16-18 — the formation of the house church as the primary early community form","Acts 16","4-Week"),
    ("Women in Acts","Seven named women — the formation of a congregation that notices who is doing what","Acts","4-Week"),
    ("The Jerusalem Council","Acts 15 — the formation of a theology of disagreement — how the church makes hard decisions","Acts 15","3-Week"),
    ("Philip and the Ethiopian","Acts 8 — the extraordinary ordinary encounter — one person, one chariot, one text","Acts 8","3-Week"),
    ("The Church That Prayed for Peter","Acts 12 — the formation of a congregation that prays when it can do nothing else","Acts 12","3-Week"),
    ("Paul Before Agrippa","Acts 26 — the formation of a man who turned every audience into an opportunity to tell his story","Acts 26","3-Week"),
    ("From Jerusalem to Rome","Acts as a complete formation theology of how the gospel travels — person by person","Acts 1-28","40-Day"),
  ]),
  ("Paul's Letters — Deeper Angles","25 more formation approaches to the Pauline corpus","Romans · Corinthians · Galatians · Ephesians · Philippians · Colossians · Thessalonians · Pastorals","#7a4a8a",[
    ("The Righteousness Revealed","Romans 1:16-17 — the formation of a congregation built on the power of God for salvation","Romans 1","3-Week"),
    ("Creation Groaning","Romans 8:19-22 — the formation of a congregation that understands its redemption as part of a cosmic project","Romans 8","4-Week"),
    ("The Olive Tree","Romans 11 — the root that supports the branches — the formation of Jew and Gentile theology","Romans 11","4-Week"),
    ("The Weak and the Strong","Romans 14-15 — the formation of a congregation that holds together people with different convictions","Romans 14","4-Week"),
    ("Greet One Another","Romans 16 — 27 names — the formation of a congregation that knows and honors its people","Romans 16","2-Week"),
    ("Flee Sexual Immorality","1 Corinthians 6 — the formation of a theology of the body — the Spirit's temple is not just the spirit","1 Corinthians 6","4-Week"),
    ("To the Married and Unmarried","1 Corinthians 7 — singleness and marriage held with equal theological weight","1 Corinthians 7","4-Week"),
    ("The Lord's Supper Recovered","1 Corinthians 11 — the formation of a congregation that understands why it gathers around the table","1 Corinthians 11","4-Week"),
    ("The Collection for Jerusalem","1 Corinthians 16 — financial giving as ecclesial solidarity — the theology of the collection","1 Corinthians 16","3-Week"),
    ("Ministry as Paul Describes It","2 Corinthians 4-6 — the complete formation theology of pastoral ministry","2 Corinthians 4","6-Week"),
    ("The Reconciliation Ministry","2 Corinthians 5:18-20 — the formation of a congregation that understands itself as ambassadors","2 Corinthians 5","40-Day"),
    ("Heirs with Abraham","Galatians 3 — the formation of a theology of belonging — who is in the family of God","Galatians 3","3-Week"),
    ("The Kenosis","Philippians 2:5-11 — the formation of the emptying pattern the congregation is invited to inhabit","Philippians 2","4-Week"),
    ("To Live Is Christ","Philippians 1:21 — the formation of a congregation that has settled the primary question","Philippians 1","40-Day"),
    ("Press Toward the Mark","Philippians 3:12-14 — pressing toward rather than straining to earn — the formation of forward motion","Philippians 3","3-Week"),
    ("Not Because I Desire a Gift","Philippians 4:17 — the formation of a theology of generosity that is about the giver as much as the gift","Philippians 4","3-Week"),
    ("The Mystery Hidden for Ages","Colossians 1:26-27 — Christ in you the hope of glory — the secret that has been revealed","Colossians 1","4-Week"),
    ("Rooted and Built Up","Colossians 2:6-7 — the formation of a congregation that continues in the same way it began","Colossians 2","3-Week"),
    ("Set Your Minds on Things Above","Colossians 3:1-4 — the cognitive dimension of sanctification — the formation of thinking differently","Colossians 3","4-Week"),
    ("Comfort One Another","1 Thessalonians 4-5 — the formation of a congregation that uses eschatology as pastoral care","1 Thessalonians 4","4-Week"),
    ("Godliness with Contentment","1 Timothy 6 — the formation of a congregation that understands what great gain actually is","1 Timothy 6","4-Week"),
    ("Entrust to Faithful People","2 Timothy 2:2 — four generations in one verse — the formation of multiplication","2 Timothy 2","4-Week"),
    ("Fan Into Flame","2 Timothy 1:6 — the formation of the gift that has to be stirred — the ministry that goes cold without tending","2 Timothy 1","3-Week"),
    ("Paul's Letter to Philemon","The shortest Pauline letter — a formation text for reconciliation between equals made unequal by culture","Philemon","3-Week"),
    ("The Thorn and the Grace","2 Corinthians 12 — the formation of the man who prayed three times and received 'my grace is sufficient'","2 Corinthians 12","4-Week"),
  ]),
  ("General Epistles — Deeper Angles","25 more formation approaches to Hebrews through Jude","Hebrews · James · 1-2 Peter · 1-2-3 John · Jude","#8a5a3a",[
    ("Better Covenant Better Promises","Hebrews 8 — the formation of a congregation that understands what the new covenant is better than","Hebrews 8","4-Week"),
    ("The Tabernacle's Shadow","Hebrews 8-10 — how the tabernacle points to what Christ accomplished — a formation typology","Hebrews 8","5-Week"),
    ("Once for All","Hebrews 9:28 — the formation of a congregation that lives from the finished sacrifice","Hebrews 9","3-Week"),
    ("Assembling Together","Hebrews 10:24-25 — the formation of a congregation that understands why showing up to community is formation","Hebrews 10","3-Week"),
    ("The Discipline of the Lord","Hebrews 12:4-11 — the formation of a congregation that understands discipline as evidence of sonship","Hebrews 12","4-Week"),
    ("The City to Come","Hebrews 13:14 — the formation of a congregation that holds its current city loosely","Hebrews 13","3-Week"),
    ("The Mirror and the Word","James 1:22-25 — the formation of a congregation that allows the word to reveal rather than confirm","James 1","4-Week"),
    ("Favoritism in the Congregation","James 2:1-13 — the formation confrontation of the seating arrangement in its own assembly","James 2","3-Week"),
    ("The Prayer of Faith","James 5:13-18 — the formation of a congregation that prays for healing with the anointing the text describes","James 5","4-Week"),
    ("Born Again to a Living Hope","1 Peter 1:3-5 — the formation of a congregation whose hope is inheritance-based certainty","1 Peter 1","4-Week"),
    ("Do Not Fear What They Fear","1 Peter 3:14 — the formation of a congregation that sanctifies Christ as Lord in anxiety","1 Peter 3","3-Week"),
    ("Elders as Overseers","1 Peter 5:1-4 — the formation of a theology of pastoral leadership that serves rather than lords","1 Peter 5","4-Week"),
    ("The False Teachers Among You","2 Peter 2 — the formation of a congregation with theological discernment","2 Peter 2","4-Week"),
    ("Scoffers in the Last Days","2 Peter 3:3-9 — the formation of a congregation that holds the tension between promise and delay","2 Peter 3","3-Week"),
    ("That Which Was from the Beginning","1 John 1:1-4 — fellowship grounded in eyewitness proclamation — the formation of first-century authority","1 John 1","3-Week"),
    ("If We Confess","1 John 1:9 — the formation of a congregation that practices confession as a community activity","1 John 1","3-Week"),
    ("The Antichrist","1 John 2:18-22 — the formation of theological discernment as a formation practice","1 John 2","4-Week"),
    ("See What Kind of Love","1 John 3:1 — the formation of a congregation whose identity is built on what the Father has called it","1 John 3","3-Week"),
    ("How We Know We Have Passed from Death","1 John 3:14 — love for one another as an indicator of spiritual condition","1 John 3","3-Week"),
    ("Test the Spirits","1 John 4:1-6 — the formation of a congregation with tools to discern what is from God","1 John 4","4-Week"),
    ("Our Confidence Before Him","1 John 5:14-15 — the formation of a congregation that prays according to his will","1 John 5","3-Week"),
    ("Walk in the Truth","2-3 John — the formation of a congregation where truth and love are both non-negotiable","2-3 John","2-Week"),
    ("Contend for the Faith","Jude — the formation of a congregation that knows what it believes and why it matters","Jude","3-Week"),
    ("Building Yourselves Up","Jude 20-21 — the formation of a congregation that understands self-formation as a community responsibility","Jude","3-Week"),
    ("Holding Fast","Hebrews' five warning passages — the formation of perseverance in a congregation that wants to quit","Hebrews","5-Week"),
  ]),
  ("Revelation — Deeper Angles","25 more formation approaches to Revelation and eschatological hope","Revelation · Apocalyptic · New Creation · End of the Story","#8a3a4a",[
    ("Revelation as Pastoral Letter","Revelation 1 — written to comfort specific congregations in specific pain — the formation of pastoral eschatology","Revelation 1","4-Week"),
    ("The First Love Lost","Revelation 2:4 — how first love is lost — and what restores it — the formation of returning","Revelation 2","3-Week"),
    ("The Lukewarm Church","Revelation 3:14-22 — the most famous thermometer in Scripture — the formation of temperature awareness","Revelation 3","3-Week"),
    ("The Open Door","Revelation 3:8 — the formation of a congregation with little power offered an open door","Revelation 3","3-Week"),
    ("The Sealed Scroll","Revelation 5 — the formation of a theology of the worthy one — who can open what no one else can","Revelation 5","4-Week"),
    ("The Prayers of the Saints","Revelation 8:3-4 — the formation of a congregation that understands its prayers as incense before the throne","Revelation 8","3-Week"),
    ("The Two Witnesses","Revelation 11 — the formation of a congregation that understands prophetic witness as core calling","Revelation 11","4-Week"),
    ("The Dragon and the Child","Revelation 12 — the cosmic conflict behind every local struggle — the formation of a warfare theology","Revelation 12","4-Week"),
    ("The Song of Moses and the Lamb","Revelation 15 — the formation of a congregation that sings both the old exodus and the new one","Revelation 15","3-Week"),
    ("The Fall of Babylon","Revelation 18 — the formation of a congregation that mourns the fall of the system it was tempted to trust","Revelation 18","4-Week"),
    ("The Rider on the White Horse","Revelation 19:11-16 — the formation of a complete Christology for the day of battle","Revelation 19","4-Week"),
    ("The White Throne Judgment","Revelation 20:11-15 — the formation of a congregation shaped by the knowledge of final accounting","Revelation 20","3-Week"),
    ("No Temple in the City","Revelation 21:22 — the city has no temple because it is all temple — the formation of the presence that fills everything","Revelation 21","3-Week"),
    ("The Gates Never Shut","Revelation 21:25 — the formation of a congregation shaped by the open city — hospitality as eschatology","Revelation 21","3-Week"),
    ("The Leaves for the Healing of Nations","Revelation 22:2 — the formation of a congregation whose mission is the healing of nations","Revelation 22","3-Week"),
    ("The Spirit and the Bride Say Come","Revelation 22:17 — the formation of a congregation that understands the church's eschatological prayer","Revelation 22","3-Week"),
    ("Overcomers","Seven promises to the one who overcomes — a formation arc across the seven letters","Revelation 2-3","7-Week"),
    ("Alpha and Omega","Five 'I am' statements of Jesus in Revelation — a formation Christology for the last book","Revelation 1,21,22","5-Week"),
    ("The Book of Life","Revelation's formation theology of name and identity — whose book you are written in","Revelation 3,20,21","3-Week"),
    ("The Tree of Life Returns","Revelation 22 and Genesis 3 together — the arc from exile to return","Genesis 3,Revelation 22","4-Week"),
    ("Apocalyptic in the Old Testament","Daniel, Zechariah, Ezekiel — the formation roots of Revelation's images","Daniel,Zechariah,Ezekiel","6-Week"),
    ("The Letter to Your Church","All seven letters — each week test your congregation against one letter","Revelation 2-3","7-Week"),
    ("Come Lord Jesus","Revelation 22 — maranatha as formation posture — the prayer that changes how you live today","Revelation 22","3-Week"),
    ("The Marriage Supper of the Lamb","Revelation 19 — the formation of a congregation that lives as the bride, not the guest","Revelation 19","3-Week"),
    ("Genesis to Revelation in 40 Days","Creation to new creation — the formation arc of the whole story in 40 sessions","Genesis-Revelation","40-Day"),
  ]),
]
