# -*- coding: utf-8 -*-
# Family Legacy Category — Strategic Opportunity document content.
# Original marketing/strategy copy, grounded in the Family Legacy by Design framework
# (legacy by design vs. default, the Five Areas of Legacy, the F.A.M.I.L.Y. Review,
# wisdom transfer vs. wealth transfer, multi-generational faith transfer, family mission/values,
# the legacy letter, Tom Conway's Multi-Generational Legacy Coaching Process).

AUDIENCE_VALUE = [
    ("Why pastors should care", "M12 2 4 6v6c0 5 3.5 9.5 8 11 4.5-1.5 8-6 8-11V6z",
     "Pastors are called to disciple whole families but rarely have tools that reach the dinner table. "
     "Family Legacy is a turnkey, gospel-centered campaign that equips parents and grandparents to pass "
     "faith forward \u2014 multiplying ministry into homes the church can\u2019t otherwise enter."),
    ("Why churches need this", "M12 3 2 9h2v9h5v-5h6v5h5V9h2zM9 14",
     "A church is one generation from decline whenever faith fails to transfer. A church-wide Family Legacy "
     "campaign aligns every group and every age around one vision for one season \u2014 the proven 40-day "
     "campaign model that shaped a generation of churches, now aimed squarely at the family."),
    ("Why advisors would use it", "M3 13h2v7H3zm4-4h2v11H7zm4-4h2v15h-2zm4 7h2v8h-2zm4-3h2v11h-2z",
     "Christian advisors want to serve clients beyond the balance sheet but lack a credible, faith-aligned "
     "framework. Built on Tom Conway\u2019s coaching process, Family Legacy gives advisors a way to open deeper "
     "conversations, strengthen relationships, and become the trusted guide for the whole family across generations."),
    ("Why families need it", "M12 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zm-7 8c0-3 3-5 7-5s7 2 7 5v1H5z",
     "Families are passing down wealth without wisdom \u2014 leaving heirs a fortune and no compass. This gives "
     "families a clear, doable path to name their values, write their mission, and hand on a faith and character "
     "the next generation will actually own."),
    ("Why donors & partners care", "M12 21s-7-4.5-9.5-9A5 5 0 0 1 12 6a5 5 0 0 1 9.5 6c-2.5 4.5-9.5 9-9.5 9z",
     "This is leverage. One body of work multiplied across audiences and formats reaches families, churches, "
     "and the advisors who serve the wealthy \u2014 the very people positioned to fund the Kingdom. An investment "
     "here multiplies generosity for generations, not just a single program."),
]

CATEGORIES = ["Family Legacy", "Next Generations", "Purpose at Work", "Stewardship",
              "Generosity", "Financial Wisdom", "Multiplication", "Kingdom Impact"]
AFFINITIES = ["Business Owners", "Advisors", "Attorneys", "CPAs",
              "Family Offices", "Pastors", "Donors", "Counselors"]

FORMATS = [
    ("4-Session Study", "A focused small-group on-ramp \u2014 ideal for a busy season or a first taste."),
    ("6-Session Study", "The core small-group experience with discussion, steps, and a commitment close."),
    ("21-Day Experience", "A three-week personal or family devotional sprint."),
    ("30-Day Experience", "A month-long journey pairing daily readings with weekly gatherings."),
    ("40-Day Campaign", "The full church-wide alignment \u2014 every group, every age, one vision."),
    ("Workshop", "A live, advisor- or leader-led intensive for families or professionals."),
    ("Devotional", "A daily reading plan with scripture and a practice prompt."),
    ("Family Conversation Guide", "Prompts that move the message from the room to the dinner table."),
]

# Top 10 developed campaigns
CAMPAIGNS = [
  dict(rank=1, title="Family Legacy", tag="Live by design, not by default.",
    problem="Most families pass down assets without ever passing down meaning \u2014 leaving heirs a balance sheet but no compass for what matters most.",
    promise="A family that lives by design, not by default \u2014 clear on who they are, what they value, and the legacy they intend to leave.",
    why="The flagship on-ramp to the entire Family Legacy by Design ecosystem. It turns a vague hope \u2014 \u201cI want my kids to turn out well\u201d \u2014 into a written, shared family mission.",
    needs=["\u201cWill my kids be ready?\u201d", "\u201cWhat holds us together when we\u2019re gone?\u201d", "\u201cIs there more to leave than money?\u201d"],
    audience="Parents & grandparents \u00b7 church families \u00b7 business-owning families \u00b7 advisor client families",
    outcomes=["A written family mission & values", "A first legacy conversation held", "Families connected to a coach or advisor"],
    sessions=[("Legacy by Design vs. Default","Choosing intention over drift."),
              ("The Five Areas of Legacy","Personal, family, financial, business, kingdom."),
              ("Wisdom Before Wealth","Why character outlasts the inheritance."),
              ("Naming Your Family Values","Surfacing what you actually stand for."),
              ("Writing Your Family Mission","One clear, memorable statement."),
              ("The First Legacy Conversation","Bringing the family to the table.")]),
  dict(rank=2, title="Leaving a Lasting Legacy", tag="Invest in heirs, not just estates.",
    problem="We spend decades building wealth and almost no time preparing the people who will receive it.",
    promise="Families who invest in heirs, not just estates \u2014 so what transfers is a blessing, never a burden.",
    why="Reframes inheritance around the question Tom Conway asks every family: \u201cWhat amount will be a blessing \u2014 and not a curse?\u201d",
    needs=["Fear of entitled or unprepared heirs", "Wealth quietly dividing the family", "\u201cDid my life actually count?\u201d"],
    audience="High-capacity families \u00b7 pre-transition business owners \u00b7 donors",
    outcomes=["An heirs-readiness honest assessment", "A wealth-as-blessing plan", "A charitable / kingdom legacy named"],
    sessions=[("The Final Exam","Stewardship and \u2018well done, good and faithful servant.\u2019"),
              ("Blessing or Curse?","What inheritance does to the unprepared."),
              ("Preparing Heirs, Not Just Estates","Investing in people first."),
              ("The Five Areas Inventory","Where the real gaps are."),
              ("Generosity as Legacy","Giving while living."),
              ("Your Lasting Mark","Defining what must endure.")]),
  dict(rank=3, title="Generations", tag="Think in generations, not years.",
    problem="Each generation tends to start from scratch, losing the faith, wisdom, and unity the last one fought for.",
    promise="A family that thinks in generations \u2014 connected across G1, G2, and G3 by covenant, not just DNA.",
    why="Anchors the multi-generational vision (Psalm 78, Deuteronomy 6) that drives the entire framework.",
    needs=["Drift between the generations", "Worry over the grandkids\u2019 faith", "\u201cWill any of this last past me?\u201d"],
    audience="Multi-generational families \u00b7 grandparents \u00b7 family offices",
    outcomes=["A multi-generational connection plan", "A G2/G3 conversation started", "The family story captured"],
    sessions=[("A God of Generations","His covenant runs through time."),
              ("The Faith Handoff","Psalm 78 and telling the next generation."),
              ("What Got Lost","Naming the breaks in the chain."),
              ("Telling the Family Story","Memory as inheritance."),
              ("Grandparenting on Purpose","The unique role of G1."),
              ("A Covenant Across Generations","Binding the family by promise.")]),
  dict(rank=4, title="Faith for Generations", tag="A faith the next generation owns.",
    problem="Faith is one generation from extinction; values caught at home are no longer being intentionally taught.",
    promise="A living faith the next generation owns for themselves \u2014 not inherited tradition, but personal conviction.",
    why="Tackles wisdom transfer head-on \u2014 the heart of a legacy that goes far beyond money.",
    needs=["Children drifting from faith", "\u201cHow do I pass on what I believe?\u201d", "Spiritual conversations feel awkward"],
    audience="Christian families \u00b7 church-wide campaign \u00b7 parents of teens & young adults",
    outcomes=["A family discipleship rhythm", "Faith conversations normalized", "Next-generation ownership of faith"],
    sessions=[("One Generation Away","Why faith doesn\u2019t transfer automatically."),
              ("Caught and Taught","Modeling and teaching together."),
              ("The Deuteronomy 6 Home","Faith woven into ordinary days."),
              ("Talking Faith Without Forcing It","Invitation over pressure."),
              ("Blessing & Prayer","Speaking faith over your children."),
              ("Faith They Call Their Own","Handing off ownership.")]),
  dict(rank=5, title="Family by Design", tag="Build your home on purpose.",
    problem="We design our careers, finances, and houses \u2014 but leave the most important thing, our family culture, to chance.",
    promise="A home built on purpose, with clear values, life-giving rhythms, and a shared sense of mission.",
    why="The \u2018by design\u2019 thesis applied to everyday family life \u2014 a natural gateway into Family Legacy by Design.",
    needs=["Busyness crowding out what matters", "Reactive, exhausted parenting", "No shared sense of direction"],
    audience="Younger families \u00b7 church-wide campaign \u00b7 small groups",
    outcomes=["Family rhythms established", "Mission & values drafted", "A regular family meeting started"],
    sessions=[("Default vs. Design","Two ways to build a family."),
              ("Your Family Culture","Naming the air your home breathes."),
              ("Values on Purpose","Choosing what you\u2019ll be known for."),
              ("Rhythms That Form Us","Habits that shape character."),
              ("The Family Meeting","A simple tool that changes everything."),
              ("Designing Forward","A blueprint for the years ahead.")]),
  dict(rank=6, title="Legacy Living", tag="Legacy is a verb \u2014 start now.",
    problem="People treat legacy as an end-of-life event, so they postpone the very choices that actually build it.",
    promise="Legacy lived today \u2014 ordinary, daily faithfulness that compounds across a lifetime.",
    why="Moves legacy from \u2018someday\u2019 to \u2018this week,\u2019 driving high engagement among active midlife families.",
    needs=["\u201cI\u2019ll deal with it later\u201d", "Feeling time-poor and stretched", "Wanting life to count now"],
    audience="Midlife adults \u00b7 working professionals \u00b7 church",
    outcomes=["Present-tense legacy habits", "Stewardship of time & influence", "A first concrete legacy action"],
    sessions=[("Legacy Is a Verb","Built in the present tense."),
              ("Stewarding Today","Faithful with this day\u2019s gifts."),
              ("Influence Where You Are","Legacy in your everyday spheres."),
              ("Money That Serves","Resources on mission."),
              ("Relationships First","People over possessions."),
              ("Start Now","One step you take this week.")]),
  dict(rank=7, title="Blessing the Next Generation", tag="Speak the blessing out loud.",
    problem="Many children grow up never having heard a parent\u2019s blessing \u2014 a spoken affirmation of identity and worth.",
    promise="A generation that knows it is seen, valued, and blessed \u2014 set free to live with confidence and purpose.",
    why="Recovers the biblical blessing as a tangible, repeatable legacy practice families can do this month.",
    needs=["Strained parent-child bonds", "Words of affirmation left unsaid", "Children unsure of their worth"],
    audience="Parents \u00b7 grandparents \u00b7 church families",
    outcomes=["Spoken & written blessings given", "Reconciliation conversations opened", "Identity affirmed in the young"],
    sessions=[("The Power of Blessing","Why words spoken matter."),
              ("What a Blessing Includes","Touch, words, value, future."),
              ("Words We Withheld","Naming what went unsaid."),
              ("Blessing Each Child","Personal and specific."),
              ("Blessing the Grandchildren","The reach of G1."),
              ("The Letter of Blessing","Putting it in writing.")]),
  dict(rank=8, title="The Generational Life", tag="Choose interdependence over isolation.",
    problem="Our culture prizes independence so highly that families fragment, and elders and youth quietly lose each other.",
    promise="A family that chooses interdependence \u2014 generations needing, knowing, and strengthening one another.",
    why="A counter-cultural vision of the connected family that pairs naturally with the family-meeting practice.",
    needs=["Isolation and scattered family", "\u201cWe only see each other at holidays\u201d", "Elders feeling sidelined"],
    audience="Extended families \u00b7 grandparents \u00b7 family offices",
    outcomes=["Intentional, recurring gatherings", "Roles across generations clarified", "A shared family mission"],
    sessions=[("Made for Each Other","Designed for connection."),
              ("The Cost of Independence","What isolation takes."),
              ("Honoring the Elders","Wisdom worth receiving."),
              ("Investing in the Young","Presence over presents."),
              ("The Family That Gathers","Rhythms of reunion."),
              ("An Interdependent Future","Building it on purpose.")]),
  dict(rank=9, title="Building a Spiritual Legacy", tag="The only foundation that lasts.",
    problem="Families build financial foundations while neglecting the spiritual foundation that alone outlasts them.",
    promise="A family whose deepest inheritance is faith \u2014 a spiritual foundation that holds when everything else shifts.",
    why="Names faith as the load-bearing wall of legacy, the framework\u2019s \u2018spiritual health\u2019 check made practical.",
    needs=["Wealth without meaning", "\u201cWhat really lasts?\u201d", "Quiet spiritual drift"],
    audience="Christian families \u00b7 donors \u00b7 church",
    outcomes=["A spiritual-health assessment", "Faith practices set in the home", "A kingdom legacy defined"],
    sessions=[("The Only Foundation","Why faith bears the weight."),
              ("Spiritual Health Check","An honest family x-ray."),
              ("Practices That Form Faith","Prayer, scripture, service."),
              ("Generosity & the Kingdom","Treasure that endures."),
              ("Faith Under Pressure","Holding when life shifts."),
              ("A Foundation That Holds","Building to last.")]),
  dict(rank=10, title="Passing Faith Forward", tag="Complete the handoff on purpose.",
    problem="The handoff fails not for lack of love but for lack of intention \u2014 faith is assumed instead of deliberately transferred.",
    promise="A completed handoff \u2014 the next generation receiving and carrying faith forward on purpose.",
    why="Brings the collection home: the deliberate, finished transfer of faith and values to those who follow.",
    needs=["Fear the chain breaks here", "\u201cHave I done enough?\u201d", "A longing to finish well"],
    audience="Parents \u00b7 grandparents \u00b7 church-wide \u00b7 advisors\u2019 client families",
    outcomes=["A written legacy letter", "A transfer plan in place", "A next-generation commitment"],
    sessions=[("The Handoff","Faith is meant to be passed."),
              ("Why Transfers Fail","Closing the intention gap."),
              ("What We\u2019re Handing On","Naming the inheritance."),
              ("The Legacy Letter","Words for those who follow."),
              ("Equipping the Receiver","Readying the next runner."),
              ("Carrying It Forward","The race continues.")]),
]

# Deeper catalog beneath the Top 10 (ranks 11-20)
CATALOG_MORE = ["Family Legacy by Design","Family Mission","The Legacy Family","Spiritual Inheritance",
                "Legacy Conversations","Blessing Your Children","Family Values","Heritage of Faith",
                "Legacy Journey","The Family Table"]
