# -*- coding: utf-8 -*-
# Finances Campaign Catalog -- Top 10 Edition. Content data.
# Day tuple: (day_no, title, subtitle, scripture_refs)

CATEGORY = {
  "title_html": 'Finances<br>Campaign <span class="it">Catalog</span>',
  "kicker": "Lifetogether &middot; Campaign Library",
  "positioning": "A strategic library of ten flagship campaigns that move a congregation from financial fear to faithful peace &mdash; built for churches and workplaces, ready to launch in any season.",
  "conviction": "The way you handle money is never only a financial matter. It is one of the clearest windows into what you actually believe about God.",
  "why_now_title": "Why This Category Matters Now",
  "why_now": "Money is the number-one source of stress in the average household and one of the leading strains on marriages, yet it is the subject most people are least equipped to discuss honestly &mdash; especially at church. Scripture speaks about money more than almost any other practical subject, because God knows that our wallets and our hearts are wired together. A church that helps its people find peace with money does not just relieve pressure; it opens one of the widest doors to genuine discipleship available in modern life.",
  "problem_title": "The Core Problem",
  "problem": "Most people carry quiet, constant anxiety about money &mdash; debt they can't see past, comparison they can't switch off, and a nagging fear that they will never have enough &mdash; while believing, deep down, that faith has little to say about it.",
  "transform_title": "The Transformation",
  "transform": "Participants move from fear to peace, from scarcity to contentment, and from owners to stewards &mdash; discovering that the most generous person in the room is always the most free, and that financial faithfulness is one of the most joyful disciplines of the Christian life.",
  "outcomes": [
    ("Reduced financial stress", "Practical biblical principles that bring calm to the most anxious area of daily life."),
    ("Deeper discipleship", "Money becomes the on-ramp to trust, surrender, and worship &mdash; not a taboo subject."),
    ("Stronger households", "Couples and families align around shared values, easing one of the top sources of conflict."),
    ("A culture of generosity", "Congregations and teams that give freely, serve gladly, and hold everything open-handed."),
  ],
  "use_cases": [
    ("Churchwide campaign", "A 40-day, all-church series with weekend messages, daily devotionals, and small groups."),
    ("Small group study", "A standalone 4- or 6-session curriculum for existing groups or new launches."),
    ("Workplace cohort", "A faith-and-work financial track for companies and marketplace ministries."),
    ("Stewardship season", "A focused giving or generosity emphasis tied to year-end or budget season."),
  ],
}

# ---------------------------------------------------------------------------
def days(*items):
    return list(items)

CAMPAIGNS = []

# ============================ 01 FAITH & FINANCES ============================
CAMPAIGNS.append({
  "num":"01","badge":"Flagship Campaign","accent":"flagship",
  "title_html":'Faith &amp; <span class="it">Finances</span>',
  "title_plain":"Faith & Finances",
  "tier":"Tier 1","audience":"Church &amp; Company",
  "scripture":'"No one can serve two masters... You cannot serve both God and money." &mdash; Matthew 6:24 (NIV)',
  "positioning":"The flagship campaign that tears down the wall between Sunday faith and Monday money.",
  "description":"Most people quietly keep money in one room of life and faith in another. This campaign brings the two together, helping every participant discover that how they earn, spend, save, and give is one of the truest expressions of what they believe about God &mdash; and that financial peace begins not with a bigger income but with a surrendered heart.",
  "why":"This is the cornerstone of the entire Finances library. It reframes the whole conversation: money is not a secular subject the church reluctantly addresses, but a spiritual one God speaks to constantly. It works as the natural front door &mdash; the campaign a church runs first to open the door to every other financial conversation.",
  "problem":"Faith and money feel disconnected &mdash; Sunday convictions rarely reach the weekday bank account.",
  "transform":"A congregation that handles money as an act of worship, with peace instead of pressure and trust instead of fear.",
  "audience_detail":"All church and workplace audiences &mdash; from new believers to mature stewards, every household regardless of income.",
  "tags":["Stewardship","Trust","Surrender","Worship","Whole-life faith"],
  "formats":["4-Session","6-Session","21-Day","30-Day","40-Day"],
  "sessions":[
    ("Who Owns It All?","Moving from owner to steward of everything God has entrusted to us."),
    ("What Money Reveals","Your spending and saving as a spiritual diagnostic of the heart."),
    ("What the Bible Actually Says","Discovering how much &mdash; and how practically &mdash; Scripture speaks about money."),
    ("From Fear to Trust","Replacing the anxiety of provision with confidence in a faithful God."),
    ("The Joy of Giving","How generosity rewires our relationship with money and with God."),
    ("A Faithful Future","Building a life and a legacy that hold everything open-handed."),
  ],
  "scriptures":[
    ("Psalm 24:1","The earth and everything in it belong to the Lord."),
    ("Matthew 6:21, 24","Where your treasure is, there your heart will be."),
    ("Luke 16:10-11","Faithfulness with worldly wealth is a test of true riches."),
    ("Philippians 4:19","God will meet all your needs according to his riches."),
    ("2 Corinthians 9:7","God loves a cheerful giver."),
    ("1 Timothy 6:17-19","Be rich in good deeds, generous and willing to share."),
  ],
  "map":[
    ("I &mdash; The Ownership Question","Who really owns it all?", days(
      (1,"The Great Transfer","Peace begins when \"mine\" becomes \"His.\"","Psalm 24:1; 1 Chronicles 29:11&ndash;12"),
      (2,"Every Dollar a Decision","Money reveals what you trust.","Matthew 6:21, 24"),
      (3,"Manager, Not Owner","The freedom of stewardship.","Luke 16:1&ndash;2; Genesis 1:28"),
      (4,"Faithful in Little","God measures the heart, not the amount.","Luke 16:10; Mark 12:41&ndash;44"),
      (5,"A Daily Surrender","Living like a steward before you feel ready.","Romans 11:36; Psalm 50:10&ndash;12"),
      (6,"Open Hands","Holding everything loosely.","Job 1:21; Ecclesiastes 5:15"),
      (7,"Rest in His Ownership","The Sabbath heart toward money.","Exodus 20:8&ndash;11; Hebrews 4:9&ndash;10"),
    )),
    ("II &mdash; The Heart Question","What does money reveal in me?", days(
      (8,"Treasure and Heart","Your bank statement is a spiritual map.","Matthew 6:19&ndash;21"),
      (9,"The Two Masters","You cannot serve both.","Matthew 6:24; Luke 16:13"),
      (10,"The Love of Money","The root, not the thing itself.","1 Timothy 6:10; Hebrews 13:5"),
      (11,"Comparison's Trap","Stop measuring your life by another's.","Galatians 6:4; Exodus 20:17"),
      (12,"Contentment Learned","A secret worth knowing.","Philippians 4:11&ndash;13"),
      (13,"Naming the Idols","What competes for first place.","Colossians 3:5; Matthew 6:33"),
      (14,"A Grateful Reset","Thankfulness changes the math.","1 Thessalonians 5:18; Psalm 103:2"),
    )),
    ("III &mdash; The Wisdom Question","What does Scripture say to do?", days(
      (15,"God's Wisdom on Money","More verses than you'd expect.","Proverbs 21:20; James 1:5"),
      (16,"A Plan on Paper","Wisdom counts the cost.","Luke 14:28; Proverbs 21:5"),
      (17,"The Danger of Debt","Why borrowing binds.","Proverbs 22:7; Romans 13:8"),
      (18,"Save for Tomorrow","The ant's quiet wisdom.","Proverbs 6:6&ndash;8; Proverbs 30:24&ndash;25"),
      (19,"Honest Scales","Integrity in every transaction.","Proverbs 11:1; Leviticus 19:35&ndash;36"),
      (20,"Wise Counsel","Many advisers bring victory.","Proverbs 15:22; Proverbs 11:14"),
      (21,"First Things First","Give to God off the top.","Proverbs 3:9&ndash;10; Malachi 3:10"),
    )),
    ("IV &mdash; The Trust Question","Will I really be okay?", days(
      (22,"Do Not Worry","The cure for financial anxiety.","Matthew 6:25&ndash;27"),
      (23,"Consider the Birds","Provision you didn't earn.","Matthew 6:26; Psalm 145:15&ndash;16"),
      (24,"Seek First","The promise that reorders everything.","Matthew 6:33; Luke 12:31"),
      (25,"Daily Bread","Enough for today is enough.","Matthew 6:11; Exodus 16:4"),
      (26,"The God Who Provides","Jehovah-Jireh in your story.","Genesis 22:14; Philippians 4:19"),
      (27,"Fear Not","His perfect love for the anxious.","Isaiah 41:10; 1 John 4:18"),
      (28,"Casting It on Him","Hand the weight to the One who carries you.","1 Peter 5:7; Psalm 55:22"),
    )),
    ("V &mdash; The Worship Question","How does giving change me?", days(
      (29,"Giving as Worship","The offering of a willing heart.","2 Corinthians 9:7; Romans 12:1"),
      (30,"The Cheerful Giver","Joy, not obligation.","2 Corinthians 9:6&ndash;8"),
      (31,"The Widow's Coins","Sacrifice God notices.","Mark 12:41&ndash;44; Luke 21:1&ndash;4"),
      (32,"Sowing and Reaping","The harvest of generosity.","2 Corinthians 9:10&ndash;11; Luke 6:38"),
      (33,"Storing Up Treasure","An eternal portfolio.","Matthew 6:19&ndash;20; 1 Timothy 6:18&ndash;19"),
      (34,"More Blessed to Give","The upside-down economy.","Acts 20:35; Proverbs 11:24&ndash;25"),
      (35,"Generosity as Freedom","The most generous are the most free.","2 Corinthians 8:1&ndash;5"),
    )),
    ("VI &mdash; The Legacy Question","What will I leave behind?", days(
      (36,"A Lasting Inheritance","More than money for those who follow.","Proverbs 13:22; Psalm 112:1&ndash;3"),
      (37,"Faithful to the End","Hearing \"well done.\"","Matthew 25:21; 1 Corinthians 4:2"),
      (38,"Teaching the Next Generation","Passing on what matters.","Deuteronomy 6:6&ndash;7; Psalm 78:4"),
      (39,"Rich Toward God","The only wealth that lasts.","Luke 12:20&ndash;21; 1 Timothy 6:17"),
      (40,"A Life Held Open","Beginning the rest of the journey.","Philippians 1:6; Joshua 24:15"),
    )),
  ],
})

# ============================ 02 MONEY MADE SIMPLE ============================
CAMPAIGNS.append({
  "num":"02","badge":"Core Campaign","accent":"core",
  "title_html":'Money Made <span class="it">Simple</span>',
  "title_plain":"Money Made Simple",
  "tier":"Tier 1","audience":"Church &amp; Company",
  "scripture":'"The plans of the diligent lead to profit as surely as haste leads to poverty." &mdash; Proverbs 21:5 (NIV)',
  "positioning":"A clear, jargon-free path for anyone who has ever felt overwhelmed by money.",
  "description":"For most people, the problem isn't a lack of willpower &mdash; it's a lack of clarity. Money feels complicated, so they avoid it, and avoidance makes everything worse. This campaign strips financial faithfulness down to a few simple, repeatable steps anyone can follow, replacing confusion and shame with a plan that finally makes sense.",
  "why":"This is the most accessible on-ramp in the library. It meets people exactly where the anxiety starts &mdash; the overwhelm &mdash; and gives them an early win. Churches love it as a first study for new groups and for households living paycheck to paycheck.",
  "problem":"Money feels confusing and overwhelming, so people avoid it &mdash; and avoidance quietly makes everything worse.",
  "transform":"Confidence and calm in place of confusion: a simple, sustainable plan that anyone can actually follow.",
  "audience_detail":"Young adults, new families, the financially overwhelmed, and anyone starting over &mdash; church or workplace.",
  "tags":["Budgeting","Clarity","Simplicity","First steps","Confidence"],
  "formats":["4-Session","6-Session","21-Day","30-Day","40-Day"],
  "sessions":[
    ("Start Where You Are","An honest, shame-free look at the numbers."),
    ("A Simple Plan","The few basics that bring everything into focus."),
    ("Spending on Purpose","Telling your money where to go before it's gone."),
    ("Saving Without Stress","Building a cushion one small step at a time."),
    ("Give First","Putting God at the front of the plan, not the leftovers."),
    ("Keep It Going","Simple rhythms that last long after the campaign."),
  ],
  "scriptures":[
    ("Proverbs 21:5","Diligent planning leads to profit."),
    ("Luke 14:28","Count the cost before you build."),
    ("Proverbs 27:23-24","Know well the condition of your flocks."),
    ("Proverbs 13:11","Whoever gathers money little by little makes it grow."),
    ("Proverbs 16:3","Commit your work to the Lord."),
    ("1 Corinthians 14:33","God is not a God of disorder but of peace."),
  ],
  "map":[
    ("I &mdash; Start Where You Are","An honest look without shame.", days(
      (1,"No More Avoiding","Clarity beats fear every time.","Luke 14:28; Proverbs 27:23"),
      (2,"The Honest Number","Naming what you actually have.","Proverbs 24:3&ndash;4; Haggai 1:5&ndash;7"),
      (3,"No Shame Here","Grace meets you at the starting line.","Romans 8:1; Lamentations 3:22&ndash;23"),
      (4,"Where It Went","Tracking the small leaks.","Proverbs 21:20; Haggai 1:6"),
      (5,"One Step at a Time","Faithfulness, not perfection.","Zechariah 4:10; Luke 16:10"),
      (6,"Asking for Help","Wisdom in many counselors.","Proverbs 15:22; Galatians 6:2"),
      (7,"A Calm Beginning","Trading panic for a plan.","Philippians 4:6&ndash;7; Isaiah 26:3"),
    )),
    ("II &mdash; A Simple Plan","The basics that make it work.", days(
      (8,"A Plan on Paper","Diligence beats good intentions.","Proverbs 21:5; Proverbs 16:3"),
      (9,"Money Has a Job","Telling every dollar where to go.","1 Corinthians 14:40; Proverbs 6:6&ndash;8"),
      (10,"Needs Before Wants","Knowing the difference.","1 Timothy 6:8; Matthew 6:31&ndash;32"),
      (11,"The Simple Split","Give, save, live.","Proverbs 3:9; Genesis 41:34&ndash;36"),
      (12,"Margin Matters","Spend less than you make.","Proverbs 13:11; Proverbs 21:17"),
      (13,"Automate the Good","Make faithfulness the default.","Proverbs 20:4; Proverbs 12:24"),
      (14,"A Weekly Check-In","Small habits, steady progress.","Proverbs 27:23&ndash;24; Luke 16:10"),
    )),
    ("III &mdash; Spending on Purpose","Tell your money where to go.", days(
      (15,"Before It's Gone","Direction beats drift.","Proverbs 21:5; Ephesians 5:15&ndash;16"),
      (16,"The Impulse Pause","Wisdom waits a beat.","Proverbs 14:29; Proverbs 19:2"),
      (17,"Enough Is Enough","Quieting the upgrade urge.","1 Timothy 6:6&ndash;8; Hebrews 13:5"),
      (18,"Contentment in Small Things","Joy without the price tag.","Philippians 4:11&ndash;12; Ecclesiastes 5:10"),
      (19,"Value, Not Just Price","Spending that reflects your values.","Matthew 6:21; Proverbs 31:16"),
      (20,"The Gift of No","Freedom in saying it.","Proverbs 22:3; Matthew 5:37"),
      (21,"Spending with Gratitude","Receiving every good gift.","James 1:17; 1 Timothy 4:4"),
    )),
    ("IV &mdash; Saving Without Stress","A cushion, one step at a time.", days(
      (22,"Start Small","A little, gathered faithfully.","Proverbs 13:11; Luke 16:10"),
      (23,"The Rainy Day","Wisdom prepares ahead.","Proverbs 6:6&ndash;8; Proverbs 21:20"),
      (24,"Joseph's Storehouse","Saving in the years of plenty.","Genesis 41:34&ndash;36; Proverbs 30:24&ndash;25"),
      (25,"Saving Is Not Hoarding","The heart behind the habit.","Luke 12:16&ndash;21; Proverbs 11:24"),
      (26,"Patience Over Hurry","Slow growth that lasts.","Proverbs 28:20; Proverbs 21:5"),
      (27,"Out of Debt, Into Margin","Freedom opens room.","Proverbs 22:7; Romans 13:8"),
      (28,"Resting in Enough","Trust quiets the scramble.","Matthew 6:31&ndash;33; Hebrews 13:5"),
    )),
    ("V &mdash; Give First","God at the front, not the leftovers.", days(
      (29,"Firstfruits","Honor God off the top.","Proverbs 3:9&ndash;10; Exodus 23:19"),
      (30,"A Willing Heart","Give cheerfully, not grudgingly.","2 Corinthians 9:7; Exodus 35:5"),
      (31,"Even from Little","The widow's full offering.","Mark 12:41&ndash;44; 2 Corinthians 8:2&ndash;3"),
      (32,"The Tithe Test","God's invitation to trust.","Malachi 3:10; Deuteronomy 14:23"),
      (33,"Generosity Multiplies","You can't out-give God.","Luke 6:38; Proverbs 11:24&ndash;25"),
      (34,"Giving Brings Joy","The happiest line in the budget.","Acts 20:35; 2 Corinthians 9:8"),
      (35,"A Generous Plan","Build giving into the budget.","1 Corinthians 16:2; 2 Corinthians 9:5"),
    )),
    ("VI &mdash; Keep It Going","Rhythms that last.", days(
      (36,"Faithful, Not Flawless","Progress over perfection.","Luke 16:10; Philippians 3:13&ndash;14"),
      (37,"When You Slip","Grace to begin again.","Lamentations 3:22&ndash;23; Proverbs 24:16"),
      (38,"Simple, Repeatable Steps","The power of a routine.","Proverbs 21:5; 1 Corinthians 14:33"),
      (39,"Inviting Others In","Two are better than one.","Ecclesiastes 4:9&ndash;10; Hebrews 10:24"),
      (40,"A Steady Life","Calm finances, quiet heart.","Proverbs 14:30; Philippians 4:7"),
    )),
  ],
})

# ============================ 03 GETTING OUT OF DEBT ============================
CAMPAIGNS.append({
  "num":"03","badge":"Core Campaign","accent":"core",
  "title_html":'Getting Out of <span class="it">Debt</span>',
  "title_plain":"Getting Out of Debt",
  "tier":"Tier 1","audience":"Church &amp; Company",
  "scripture":'"The borrower is slave to the lender." &mdash; Proverbs 22:7 (NIV)',
  "positioning":"A grace-filled path out of the weight of debt and into lasting freedom.",
  "description":"Debt is more than a math problem &mdash; it is a weight people carry in their chest, a quiet shame that steals sleep and strains marriages. This campaign combines biblical conviction with a clear, hopeful plan, walking participants out of bondage step by step while reminding them at every turn that their worth was never measured by their balance sheet.",
  "why":"Few felt needs are more urgent or more universal. This campaign offers something the culture cannot: freedom from debt without condemnation, and a vision of the open-handed life waiting on the other side. It is a powerful invitation to people who would never otherwise walk into a church.",
  "problem":"Debt feels like a prison &mdash; a constant weight of stress, shame, and lost freedom that seems impossible to escape.",
  "transform":"Freedom and breathing room: a clear plan, renewed hope, and the lightness of a life no longer owned by what is owed.",
  "audience_detail":"Households under financial pressure, young adults, couples, and anyone ready to break free &mdash; church or workplace.",
  "tags":["Debt freedom","Hope","Discipline","Breakthrough","Freedom"],
  "formats":["4-Session","6-Session","30-Day","40-Day"],
  "sessions":[
    ("Naming the Weight","Bringing debt into the light without shame."),
    ("The Truth About Debt","What Scripture really says about borrowing."),
    ("A Plan to Break Free","Practical, proven steps toward zero."),
    ("Changing the Habits","Healing the patterns that created the debt."),
    ("Walking in Freedom","Living and giving from a place of release."),
    ("Staying Free","Guarding the freedom and helping others find it."),
  ],
  "scriptures":[
    ("Proverbs 22:7","The borrower is slave to the lender."),
    ("Romans 13:8","Let no debt remain outstanding, except love."),
    ("Proverbs 22:26-27","Do not be one who shakes hands in pledge."),
    ("2 Kings 4:1-7","God multiplies what little remains."),
    ("Luke 4:18","He has sent me to proclaim freedom."),
    ("Galatians 5:1","It is for freedom that Christ has set us free."),
  ],
  "map":[
    ("I &mdash; Naming the Weight","Bringing debt into the light.", days(
      (1,"The Honest Total","Freedom starts with the truth.","Proverbs 22:7; John 8:32"),
      (2,"No Condemnation","Your worth is not your balance.","Romans 8:1; Psalm 103:12"),
      (3,"Out of the Dark","Shame loses power in the light.","Ephesians 5:13&ndash;14; 1 John 1:7"),
      (4,"How We Got Here","Understanding without self-attack.","Psalm 139:23&ndash;24; Proverbs 20:5"),
      (5,"A God Who Frees","He breaks every chain.","Luke 4:18; Isaiah 61:1"),
      (6,"Hope on the Horizon","This is not the end of your story.","Jeremiah 29:11; Romans 15:13"),
      (7,"The First Decision","Choosing freedom today.","Joshua 24:15; Deuteronomy 30:19"),
    )),
    ("II &mdash; The Truth About Debt","What Scripture really says.", days(
      (8,"Slave to the Lender","Why debt binds the soul.","Proverbs 22:7; Proverbs 22:26&ndash;27"),
      (9,"Owe Nothing But Love","God's vision for freedom.","Romans 13:8; 1 Corinthians 7:23"),
      (10,"The Cost of Easy Money","Counting what it truly takes.","Luke 14:28; Proverbs 21:17"),
      (11,"Presumption About Tomorrow","Borrowing against a day not promised.","James 4:13&ndash;15; Proverbs 27:1"),
      (12,"Contentment Cuts the Cord","Wanting less, owing less.","1 Timothy 6:6&ndash;8; Hebrews 13:5"),
      (13,"Honesty With Creditors","Integrity in repayment.","Psalm 37:21; Proverbs 3:27&ndash;28"),
      (14,"Freedom Is the Goal","Why God wants you free.","Galatians 5:1; 2 Corinthians 3:17"),
    )),
    ("III &mdash; A Plan to Break Free","Clear steps toward zero.", days(
      (15,"Count the Cost","A plan turns hope into action.","Luke 14:28; Proverbs 21:5"),
      (16,"A Starter Cushion","Stop the bleeding first.","Proverbs 6:6&ndash;8; Proverbs 21:20"),
      (17,"Smallest First","Momentum from early wins.","Zechariah 4:10; Ecclesiastes 7:8"),
      (18,"One Debt at a Time","Focused effort wins.","Philippians 3:13&ndash;14; 1 Corinthians 9:26"),
      (19,"Find Extra Margin","Free up every dollar to fight.","Proverbs 13:11; Proverbs 12:11"),
      (20,"The Widow's Oil","God multiplies what's left.","2 Kings 4:1&ndash;7; Mark 6:41&ndash;42"),
      (21,"Stay the Course","Perseverance finishes the race.","Galatians 6:9; Hebrews 12:1"),
    )),
    ("IV &mdash; Changing the Habits","Healing the patterns.", days(
      (22,"The Heart Behind Spending","Why we reach for more.","Proverbs 4:23; Matthew 6:21"),
      (23,"Breaking the Impulse","A pause that protects.","Proverbs 14:29; Proverbs 25:28"),
      (24,"Comparison's Cost","Keeping up is a trap.","Exodus 20:17; Galatians 6:4"),
      (25,"New Margin, New Mind","Renewing how you think about money.","Romans 12:2; Ephesians 4:22&ndash;24"),
      (26,"Gratitude Over Grasping","Thankfulness loosens the grip.","1 Thessalonians 5:18; Philippians 4:11&ndash;12"),
      (27,"Accountability","Don't fight alone.","Ecclesiastes 4:9&ndash;12; James 5:16"),
      (28,"Self-Control as Fruit","The Spirit empowers the change.","Galatians 5:22&ndash;23; 2 Peter 1:5&ndash;6"),
    )),
    ("V &mdash; Walking in Freedom","Living from release.", days(
      (29,"The First Paid-Off Day","Tasting freedom.","Psalm 126:3; Galatians 5:1"),
      (30,"From Debtor to Giver","A new identity emerges.","Acts 20:35; 2 Corinthians 9:7"),
      (31,"Breathing Room","Margin becomes ministry.","Proverbs 11:25; 2 Corinthians 9:8"),
      (32,"Saving With Purpose","Building instead of borrowing.","Proverbs 21:20; Genesis 41:35"),
      (33,"Generosity Returns","Freed to bless others.","Luke 6:38; Proverbs 11:24"),
      (34,"Peace Where There Was Panic","Rest replaces dread.","Philippians 4:6&ndash;7; Isaiah 26:3"),
      (35,"A Testimony of Freedom","Your story gives others hope.","Psalm 40:1&ndash;3; Revelation 12:11"),
    )),
    ("VI &mdash; Staying Free","Guarding and sharing it.", days(
      (36,"Guard the Gains","Don't return to the chains.","Galatians 5:1; 2 Peter 2:20"),
      (37,"Wise Boundaries","Habits that keep you free.","Proverbs 22:3; Proverbs 4:26&ndash;27"),
      (38,"A Buffer for Storms","Prepared, not panicked.","Proverbs 6:6&ndash;8; Matthew 7:24&ndash;25"),
      (39,"Helping Others Out","Lend hope, not just money.","Galatians 6:1&ndash;2; Isaiah 58:6"),
      (40,"Free Indeed","Living the unburdened life.","John 8:36; Galatians 5:13"),
    )),
  ],
})

# ============================ 04 BREAKING FINANCIAL FEAR ============================
CAMPAIGNS.append({
  "num":"04","badge":"Core Campaign","accent":"core",
  "title_html":'Breaking Financial <span class="it">Fear</span>',
  "title_plain":"Breaking Financial Fear",
  "tier":"Tier 1","audience":"Church &amp; Company",
  "scripture":'"So do not fear, for I am with you." &mdash; Isaiah 41:10 (NIV)',
  "positioning":"For the anxious heart that quietly asks, \"Will I really be okay?\"",
  "description":"Beneath most money stress is not a spreadsheet but a fear &mdash; the fear of not having enough, of losing it all, of an uncertain future. This campaign takes that fear seriously and answers it with the deep, repeated promise of Scripture: a God who provides, who sees, and who has never once abandoned His own. It moves participants from scarcity and dread to settled, trusting peace.",
  "why":"This campaign reaches the emotional core of the entire category. It pairs naturally with seasons of economic uncertainty, layoffs, or change, and gives the church a pastoral, hope-filled word precisely when people are most afraid. It is discipleship aimed at the anxious heart.",
  "problem":"A constant, low-grade fear about money &mdash; not having enough, losing what little there is, and an uncertain future that won't stop whispering.",
  "transform":"A settled, trusting peace rooted in the character of a God who provides &mdash; freedom from the tyranny of \"what if.\"",
  "audience_detail":"The anxious, those in transition or uncertainty, savers and worriers alike &mdash; church and workplace.",
  "tags":["Anxiety","Provision","Trust","Peace","Scarcity"],
  "formats":["4-Session","6-Session","21-Day","30-Day","40-Day"],
  "sessions":[
    ("Naming the Fear","Bringing money anxiety honestly before God."),
    ("The God Who Provides","Rediscovering His track record of faithfulness."),
    ("Worry's Lies, God's Truth","Replacing anxious thoughts with His promises."),
    ("Daily Bread","Learning to trust Him one day at a time."),
    ("The Peace That Guards","Experiencing the peace beyond understanding."),
    ("Living Unafraid","Walking forward with open hands and a quiet heart."),
  ],
  "scriptures":[
    ("Isaiah 41:10","Do not fear, for I am with you."),
    ("Matthew 6:25-34","Do not worry about your life."),
    ("Philippians 4:6-7","The peace of God will guard your heart."),
    ("Philippians 4:19","God will meet all your needs."),
    ("Psalm 23:1","The Lord is my shepherd, I lack nothing."),
    ("1 Peter 5:7","Cast all your anxiety on him."),
  ],
  "map":[
    ("I &mdash; Naming the Fear","Honest before God.", days(
      (1,"The Fear Beneath","What money worry is really about.","Matthew 6:25; Psalm 38:18"),
      (2,"Will I Be Okay?","Bringing the question into the open.","Psalm 13:1&ndash;2; 1 Peter 5:7"),
      (3,"The Voice of Scarcity","Recognizing the lie of \"never enough.\"","Matthew 6:31&ndash;32; Exodus 16:18"),
      (4,"God Already Knows","Your needs are no surprise to Him.","Matthew 6:8; Psalm 139:1&ndash;4"),
      (5,"Honest Lament","Telling God exactly how it feels.","Psalm 62:8; Psalm 142:1&ndash;2"),
      (6,"You Are Not Alone","He is with you in it.","Isaiah 41:10; Deuteronomy 31:6"),
      (7,"A Place to Begin","Turning fear into prayer.","Philippians 4:6; Psalm 56:3"),
    )),
    ("II &mdash; The God Who Provides","His track record.", days(
      (8,"Jehovah-Jireh","The Lord will provide.","Genesis 22:13&ndash;14; Philippians 4:19"),
      (9,"Manna Every Morning","Daily provision in the desert.","Exodus 16:4; Nehemiah 9:21"),
      (10,"Ravens and a Brook","Fed by unlikely means.","1 Kings 17:2&ndash;6; Psalm 147:9"),
      (11,"The Flour and the Oil","Enough that never ran out.","1 Kings 17:8&ndash;16; 2 Kings 4:1&ndash;7"),
      (12,"Five Loaves, Thousands Fed","Little becomes more than enough.","Matthew 14:17&ndash;20; John 6:11"),
      (13,"Your Own Story","Remembering when He came through.","Psalm 77:11&ndash;12; 1 Samuel 7:12"),
      (14,"He Has Not Changed","The Provider is still providing.","Hebrews 13:8; Lamentations 3:22&ndash;23"),
    )),
    ("III &mdash; Worry's Lies, God's Truth","Replacing the script.", days(
      (15,"Do Not Worry","The command and the comfort.","Matthew 6:25&ndash;27; Luke 12:22&ndash;26"),
      (16,"Consider the Birds","Cared for without anxiety.","Matthew 6:26; Psalm 145:15&ndash;16"),
      (17,"Look at the Lilies","Clothed in beauty you didn't earn.","Matthew 6:28&ndash;30; Luke 12:27&ndash;28"),
      (18,"Today's Trouble","Don't borrow tomorrow's worry.","Matthew 6:34; James 4:14"),
      (19,"Take Every Thought","Capturing anxious thinking.","2 Corinthians 10:5; Philippians 4:8"),
      (20,"Truth Over Feeling","Standing on what God said.","Isaiah 26:3; John 14:27"),
      (21,"Renew the Mind","A new way of thinking about lack.","Romans 12:2; Colossians 3:2"),
    )),
    ("IV &mdash; Daily Bread","One day at a time.", days(
      (22,"Give Us This Day","Trust shaped one day at a time.","Matthew 6:11; Proverbs 30:8&ndash;9"),
      (23,"Enough for Today","Yesterday's manna couldn't be hoarded.","Exodus 16:19&ndash;20; Lamentations 3:23"),
      (24,"Seek First","The promise that reorders worry.","Matthew 6:33; Psalm 37:25"),
      (25,"The Shepherd's Care","With Him you lack nothing.","Psalm 23:1&ndash;3; John 10:11"),
      (26,"He Knows Your Needs","Provision precedes the request.","Matthew 6:8, 32; Philippians 4:19"),
      (27,"Contentment in Plenty and Want","The learned secret.","Philippians 4:11&ndash;13; 1 Timothy 6:6&ndash;8"),
      (28,"Trust for Tomorrow","Releasing the unknown future.","Jeremiah 29:11; Proverbs 16:9"),
    )),
    ("V &mdash; The Peace That Guards","Beyond understanding.", days(
      (29,"Cast Your Anxiety","Hand Him the weight.","1 Peter 5:7; Psalm 55:22"),
      (30,"Peace Like a River","Settled in the storm.","Isaiah 48:18; Isaiah 26:3"),
      (31,"Prayer Over Panic","The pathway to peace.","Philippians 4:6&ndash;7; Psalm 34:4"),
      (32,"Be Still","Quiet enough to trust.","Psalm 46:10; Exodus 14:14"),
      (33,"Perfect Love Casts Out Fear","Held by the One who loves you.","1 John 4:18; Romans 8:38&ndash;39"),
      (34,"A Sound Mind","Power, love, and self-control.","2 Timothy 1:7; Isaiah 41:13"),
      (35,"Rest for the Weary","His unforced rhythms of grace.","Matthew 11:28&ndash;30; Hebrews 4:9&ndash;10"),
    )),
    ("VI &mdash; Living Unafraid","Open hands, quiet heart.", days(
      (36,"Generosity Defies Fear","Giving is trust in action.","2 Corinthians 9:7&ndash;8; Proverbs 11:24&ndash;25"),
      (37,"Open Hands","Holding everything loosely.","Job 1:21; 1 Timothy 6:17&ndash;18"),
      (38,"Courage to Step Out","Faith moves forward.","Joshua 1:9; Matthew 14:29"),
      (39,"A Future Secured","Your hope is eternal.","1 Peter 1:3&ndash;4; Matthew 6:19&ndash;20"),
      (40,"Unafraid","Walking free of the \"what if.\"","Isaiah 41:10; Psalm 112:7"),
    )),
  ],
})
