/* ============================================================
   THE FAMILY LEGACY COLLECTION — catalog
   Content drawn from the Family Legacy by Design library and
   the Lifetogether campaign craft. Ten journeys, sixty sessions.
   ============================================================ */
window.FLC = {

areas: {
  personal:   { n:"Personal",   c:"#B08A3E", d:"Character, calling, spiritual foundation." },
  family:     { n:"Family",     c:"#2E6B4F", d:"Unity, shared values, communication." },
  financial:  { n:"Financial",  c:"#7E601C", d:"Stewardship, planning, generational transfer." },
  business:   { n:"Business",   c:"#5A6B8C", d:"Succession, leadership continuity." },
  charitable: { n:"Charitable", c:"#A04E3C", d:"Kingdom impact and purposeful generosity." }
},

campaigns: [

/* ─────────────────────────── 1 · FLAGSHIP ─────────────────────────── */
{ id:"family-legacy", flagship:true,
  title:"Family Legacy",
  sub:"A 40-Day Journey from Legacy by Default to Legacy by Design",
  quote:"Every family leaves a legacy. The only question is whether yours will be left by design — or by default.",
  desc:"Family Legacy addresses the most important question a household will ever face: not how much we will leave, but who we will send into the generations that follow. Scripture defines inheritance not as the wealthy person’s privilege but as the good person’s intention. A family that simply drifts will still pass something on; the only choice is whether what they pass on was chosen, or inherited from the culture by default. This journey gives every household the biblical vision, the practical framework, and the honest conversations to build a legacy on purpose.",
  big:"God designed the family to be the primary place where faith, wisdom, character, and blessing pass from one generation to the next — and the family that lives that calling on purpose leaves a legacy that outlasts every account, title, and possession.",
  scrRef:"Proverbs 13:22",
  scrKJV:"A good man leaveth an inheritance to his children’s children.",
  areas:["family","financial"], hue:["#2E6B4F","#0E3A2D"],
  audience:"Parents, grandparents, couples, single adults — every household",
  season:"Fall family launch · New Year · Father’s & Mother’s Day",
  related:"Feeds naturally into the Legacy by Design coaching process",
  sessions:[
    { t:"Legacy by Design, Not by Default", scr:"Proverbs 27:23",
      sq:"“Be sure you know the condition of your flocks, give careful attention to your herds.”",
      qs:["When you hear the word “legacy,” what comes to mind first — and how much of it is about money versus faith, character, and relationships?",
          "Every family is already passing something on, intentionally or not. What do you think your family is currently catching from you by default?",
          "What would it mean for your family’s legacy to be built “by design” — and what is the first decision that would change?"],
      step:"Finish this sentence in writing: “The legacy I most want to leave my family is …” Share it with your group partner this week." },
    { t:"More Than Money", scr:"Ecclesiastes 7:11–12",
      sq:"“Wisdom, like an inheritance, is a good thing … wisdom preserves those who have it.”",
      qs:["Where have you seen money passed down without the wisdom to handle it — and what happened?",
          "What non-financial inheritance did you receive from those before you — for better or worse — and how is it shaping you today?",
          "If you could pass on only three things that are not money, what would they be?"],
      step:"List the five most valuable things you have to pass on that cannot be deposited in a bank. Bring it to the next session." },
    { t:"God’s Multi-Generational Design", scr:"Psalm 78:5–7",
      sq:"“…that the generation to come might know … that they may arise and tell them to their children.”",
      qs:["Psalm 78 names five generations in a single breath. How far down the line are you actually thinking when you make decisions today?",
          "The modern view says “raise them and release them”; the biblical view is multi-generational and interdependent. Which view has shaped your family more?",
          "What is one work of God in your own story that the next generation will never know unless you intentionally tell them?"],
      step:"This week, tell one child, grandchild, or younger person a specific story of how God has been faithful in your life." },
    { t:"The Honest Inventory", scr:"Psalm 139:23",
      sq:"“Search me, God, and know my heart; test me and know my anxious thoughts.”",
      qs:["Look honestly at your family’s spiritual, relational, and financial health. Which of the three is strongest right now — and which most needs attention?",
          "Are the people who will receive what you pass on actually prepared to steward it well? What would “prepared” look like?",
          "What is one hard but necessary conversation your family has been avoiding?"],
      step:"Privately rate your family’s spiritual, relational, and financial health from 1–10. Name the lowest score and one step to raise it." },
    { t:"A Family on Mission", scr:"Joshua 24:15",
      sq:"“…as for me and my household, we will serve the Lord.”",
      qs:["Joshua made a public declaration for his whole household. If your family had a one-sentence mission statement, what would you want it to say?",
          "What three or four values do you most want to define your family — and are they actually visible in how you spend time and money?",
          "Who in your family will help carry the torch of these values into the next generation?"],
      step:"Draft a first attempt at a one-sentence family mission: “Our family exists to …” Share it and refine it together." },
    { t:"Building It on Purpose", scr:"Galatians 6:9",
      sq:"“Let us not become weary in doing good, for at the proper time we will reap a harvest.”",
      qs:["After these 40 days, what is the single most important shift in how you think about the legacy you are leaving?",
          "The keys to passing on a legacy begin with “be intentional” and “be humble enough to ask for help.” Which do you most need to grow in?",
          "What is one concrete, repeatable rhythm — a family meeting, a weekly meal, a yearly retreat — you will build to keep this legacy on purpose?"],
      step:"Each person names one legacy commitment for the next 12 months and one person in the group who will ask them about it. Close by praying over each family by name." }
  ],
  weeks:[
    { t:"Legacy by Design, Not by Default", days:[
      ["Every Family Leaves One","Proverbs 13:22","Every family leaves a legacy. Tonight, name out loud what yours is leaving so far."],
      ["The State of the Flocks","Proverbs 27:23","Diligence begins with looking. Take one honest look at what you are actually tending."],
      ["Drift Divides","Proverbs 29:18","Without a vision, a family drifts. Name one place yours has been drifting."],
      ["Written So They Can Run","Habakkuk 2:2","What is written can be carried. Write one sentence of what your family is for."],
      ["More Caught Than Taught","1 Corinthians 11:1","Your family is catching something from you today. Ask yourself what."],
      ["The Good Man’s Intention","Psalm 112:1–2","Blessing runs downstream from reverence. Ask God to make yours a Psalm 112 house."],
      ["Choose This Day","Joshua 24:15","Say it out loud at the table tonight: as for our house."]]},
    { t:"More Than Money", days:[
      ["Wisdom With an Inheritance","Ecclesiastes 7:11","List what you own that no bank can hold."],
      ["Instruction Before Transfer","Proverbs 4:1–2","Give one instruction today worth more than money."],
      ["Treasure That Doesn’t Rust","Matthew 6:19–21","Follow your treasure and you will find your heart. Notice where it led today."],
      ["The Borrowed Estate","Psalm 24:1","You are managing, not owning. Hold one thing with open hands today."],
      ["Rich Toward God","Luke 12:20–21","Bigger barns are not a legacy. Name what “rich toward God” means for your family."],
      ["A Good Name","Proverbs 22:1","Ask at dinner: what do we want our name to mean?"],
      ["Contentment’s Great Gain","1 Timothy 6:6–7","Practice one act of “enough” today — and say why at the table."]]},
    { t:"God’s Multi-Generational Design", days:[
      ["Five Generations in a Breath","Psalm 78:5–7","Think five generations down before one decision today."],
      ["A Covenant for a Thousand","Deuteronomy 7:9","You are living inside a promise older than your family tree."],
      ["The Generation That Forgot","Judges 2:10","Faith is one untold story from vanishing. Tell one tonight."],
      ["Lois and Eunice","2 Timothy 1:5","Trace the faith that reached you. Thank one carrier by name."],
      ["When Your Children Ask","Joshua 4:6–7","Set one “stone” in your home that makes children ask questions."],
      ["Olive Shoots Around the Table","Psalm 128:3–6","Interdependence is the design. Pull the generations one act closer."],
      ["Hearts Turned Home","Malachi 4:6","Ask God to turn one distant heart — perhaps yours first."]]},
    { t:"The Honest Inventory", days:[
      ["Search Me","Psalm 139:23–24","Invite God into the family’s real condition today."],
      ["Three Ledgers","3 John 2","Rate the spiritual, relational, and financial health of your house — honestly."],
      ["The Unready Heir","Proverbs 20:21","An inheritance gained too fast blesses no one. Prepare before you provide."],
      ["The Avoided Conversation","Ephesians 4:15","Truth in love: name the talk your family keeps postponing."],
      ["Faithful in Little","Luke 16:10","Entrust one small, real thing to a younger hand this week."],
      ["Counsel Makes Plans Stand","Proverbs 15:22","Invite one wise outside voice into your family’s plans."],
      ["Confess and Mend","James 5:16","Healing at home begins with the first honest sentence. Say it."]]},
    { t:"A Family on Mission", days:[
      ["As For Me and My House","Joshua 24:15","Draft the sentence: our family exists to ______."],
      ["Values You Can See","Philippians 4:8","Choose five family values — then check the calendar for evidence."],
      ["Written on the Doorframes","Deuteronomy 6:9","Post what you believe where the family cannot miss it."],
      ["A Light on Its Stand","Matthew 5:14–16","Decide one way your family will shine for your neighbors."],
      ["Generosity as Identity","2 Corinthians 9:7","Give one gift together as a family — and talk about why."],
      ["The Family Meeting","Acts 2:46","Set the first (or next) family meeting: a date, a table, no screens."],
      ["Carrying the Torch","2 Peter 1:13","Invite one younger member to own one family value."]]},
    { t:"Building It on Purpose", days:[
      ["Hear and Build","Matthew 7:24–25","Pick one thing you have heard these forty days and build it today."],
      ["Not Weary in Doing Good","Galatians 6:9","Legacy is a long obedience. Take today’s small faithful step."],
      ["The Legacy Letter","Deuteronomy 6:6–7","Begin the letter: “What I most want you to know is …”"],
      ["Bless Them Out Loud","Numbers 6:24–26","Speak a blessing, by name, over each person at your table."],
      ["Well Done","Matthew 25:21","Aim the whole estate of your life at six words: well done, good and faithful servant."]]}
  ]
},

/* ─────────────────────────── 2 ─────────────────────────── */
{ id:"leaving-a-lasting-legacy",
  title:"Leaving a Lasting Legacy",
  sub:"A 40-Day Journey into What Truly Lasts",
  quote:"A lasting legacy is not the size of an estate but the depth of the faith, the strength of the relationships, and the wisdom that remain long after the assets are spent.",
  desc:"A lasting legacy is built deliberately, one ordinary decision at a time. This journey lifts a family’s eyes from what merely glitters to what actually endures — the faith, the good name, the stories, and the finish that outlive every balance sheet.",
  big:"A lasting legacy is not the size of an estate but the depth of the faith, the strength of the relationships, and the wisdom that remain long after the assets are spent — and that kind of legacy is built deliberately, one ordinary decision at a time.",
  scrRef:"Psalm 90:12",
  scrKJV:"So teach us to number our days, that we may apply our hearts unto wisdom.",
  areas:["personal"], hue:["#C9A44E","#7E601C"],
  audience:"Every stage of life — especially those weighing what their years are building",
  season:"New Year · Year-end reflection · Legacy emphasis",
  sessions:[
    { t:"What Actually Lasts", scr:"Psalm 90:12",
      sq:"“Teach us to number our days, that we may gain a heart of wisdom.”",
      qs:["If you knew your days were numbered, what would suddenly matter more — and what would matter far less?",
          "Name something you are pouring energy into now that will not last a generation. Why does it still hold so much of your attention?",
          "What is one thing in your life you are confident will still matter in a hundred years?"],
      step:"Write a short list this week titled “What I want to still be true of my family in 100 years.”" },
    { t:"The Inheritance That Outlives the Estate", scr:"Proverbs 13:22",
      sq:"“A good person leaves an inheritance for their children’s children.”",
      qs:["Proverbs says a good person — not a wealthy person — leaves an inheritance. What does that distinction change for you?",
          "What would it look like to leave your children wise rather than merely wealthy?",
          "Have you ever seen an inheritance become a burden instead of a blessing? What was missing?"],
      step:"Identify one piece of hard-won wisdom you want your heirs to receive, and write down how you will pass it on." },
    { t:"A Thousand Generations", scr:"Deuteronomy 7:9",
      sq:"“He keeps his covenant of love to a thousand generations of those who love him.”",
      qs:["God thinks in terms of a thousand generations. How does that scale reframe the decisions you make this year?",
          "What promise of God do you most want the generations after you to stake their lives on?",
          "Where are you tempted to live for the short term at the expense of the long story?"],
      step:"Choose one promise of God to memorize and pass to someone younger this week, explaining why it has held you." },
    { t:"Remembered Well", scr:"Proverbs 22:1",
      sq:"“A good name is more desirable than great riches; to be esteemed is better than silver or gold.”",
      qs:["If your family described your character in one sentence at your funeral, what do you hope — and fear — they would say?",
          "Where is there a gap between the reputation you have and the character you actually want?",
          "Whose “good name” shaped you, and what specifically did they model?"],
      step:"Identify one area where your private character and public reputation don’t yet match, and take one step to close the gap." },
    { t:"Telling the Story", scr:"Psalm 145:4",
      sq:"“One generation commends your works to another; they tell of your mighty acts.”",
      qs:["What is the family story — of faith, struggle, or provision — that the next generation must not lose?",
          "Why do family stories so easily disappear, and what would it take to capture yours?",
          "Who in your family is the keeper of the stories, and what happens when they are gone?"],
      step:"Record one family God-story this week — written, audio, or video — and share it at the next gathering." },
    { t:"Finishing Well", scr:"2 Timothy 4:7",
      sq:"“I have fought the good fight, I have finished the race, I have kept the faith.”",
      qs:["What would it mean for you, specifically, to “finish well” in this season of life?",
          "What is the one thing you do not want to leave undone or unsaid with your family?",
          "Over these 40 days, what has shifted in how you weigh what lasts against what merely glitters?"],
      step:"Each person names one enduring investment — a relationship, a habit, a story to be told — they will give themselves to, and one person who will check in at 30 days." }
  ]
},

/* ─────────────────────────── 3 ─────────────────────────── */
{ id:"generations",
  title:"Generations",
  sub:"A 40-Day Journey into God’s Generational Story",
  quote:"God’s promises are not loans for a lifetime. They are covenants that run a thousand generations deep.",
  desc:"God has never worked one life at a time. From Abraham forward, His promises run like a river through generations — and your family is meant to be part of that current, not a dam that stops it. The greatest threat to a family of faith is rarely an attack from outside; it is a single generation that fails to pass it on. This journey helps a family recover God’s multi-generational vision and take up their place in a story far longer than their own lives.",
  big:"God’s design has always been multi-generational — He commits Himself to families across time and calls each generation to make Him known to the next, so the children yet unborn might know Him, trust Him, and keep His commandments.",
  scrRef:"Psalm 105:8",
  scrKJV:"He hath remembered his covenant for ever, the word which he commanded to a thousand generations.",
  areas:["family"], hue:["#5A6B8C","#2E3A52"],
  audience:"Grandparents, parents, young families",
  season:"Fall · New Year · Grandparents’ emphasis",
  sessions:[
    { t:"A God of Generations", scr:"Genesis 17:7",
      sq:"“I will establish my covenant … between me and you and your descendants after you for the generations to come.”",
      qs:["God made His covenant not just with Abraham but with his descendants “for generations to come.” How does it feel to be downstream of a promise like that?",
          "What spiritual covenant or commitment in your family began before you were born?",
          "What promise of God do you most want to be true of your descendants after you?"],
      step:"Trace your family’s faith back as far as you can this week, and thank God for one person who carried it to you." },
    { t:"The Generation That Forgot", scr:"Judges 2:10",
      sq:"“Another generation grew up who knew neither the Lord nor what he had done for Israel.”",
      qs:["Judges describes faith collapsing in a single generation. How does that happen so quickly — even in good families?",
          "What is the difference between a child who knows about God and a child who knows God?",
          "Where might your family be one step away from a generation that “forgets”?"],
      step:"Name one specific way you will help a younger person know God — not just know about Him — this month." },
    { t:"From Independence to Interdependence", scr:"Psalm 128:3,6",
      sq:"“Your children will be like olive shoots around your table … may you live to see your children’s children.”",
      qs:["The culture’s goal is to raise children to independence and send them off. God’s vision adds interdependence. What would change if you aimed for both?",
          "What does healthy lifelong connection between generations look like — versus unhealthy dependence?",
          "How could your extended family become more of a team and less of a collection of individuals?"],
      step:"Take one action this week to strengthen a cross-generational relationship in your family." },
    { t:"The Voices That Shape Us", scr:"2 Timothy 1:5",
      sq:"“I am reminded of your sincere faith, which first lived in your grandmother Lois and in your mother Eunice.”",
      qs:["Timothy’s faith was traced through his grandmother and mother. Whose faith can you trace in your own story?",
          "What did the most influential believer in your life do that actually formed you?",
          "Whose faith are you currently shaping, whether you intended to or not?"],
      step:"Write a short thank-you to someone whose faith shaped yours — or, if they’re gone, write what you’d say." },
    { t:"Bridging the Gap", scr:"Malachi 4:6",
      sq:"“He will turn the hearts of the parents to their children, and the hearts of the children to their parents.”",
      qs:["Is there a gap between generations in your family — of distance, hurt, or silence — that needs a heart turned back?",
          "What keeps families from repairing generational wounds, and what would a first step toward repair cost you?",
          "How does unresolved relational distance threaten everything else you hope to pass on?"],
      step:"Identify one relationship across generations that needs a step toward repair. Pray about it daily, then take the step." },
    { t:"The Generation to Come", scr:"Psalm 78:6",
      sq:"“…so the next generation would know them, even the children yet to be born.”",
      qs:["Picture a descendant you will never meet. What do you most want to be true of their faith because of choices you make now?",
          "What is the single most important thing this group has helped you see about generational faith?",
          "What will you do differently, starting this week, so the generation to come will know the Lord?"],
      step:"Each person names one commitment for the generations to come — a story to tell, a relationship to mend, a faith habit to model — and one person to ask about it in 30 days. Close by praying for children yet unborn." }
  ]
},

/* ─────────────────────────── 4 ─────────────────────────── */
{ id:"faith-for-generations",
  title:"Faith for Generations",
  sub:"A 40-Day Journey to a Faith Worth Passing On",
  quote:"The most valuable thing you will ever hand your children is not in your will. It is in your walk.",
  desc:"You can leave your children money and they may lose it. You can leave them a name and they may forget it. But a living faith, handed on with intention, can carry a family for centuries. Deuteronomy 6 does not describe a program; it describes a lifestyle — faith impressed on children in the ordinary moments of sitting at home, walking along the road, lying down, and getting up.",
  big:"Faith is not transferred automatically — it is handed on deliberately, modeled in daily life and spoken into ordinary moments, so the generation to come knows God for themselves and not merely by reputation.",
  scrRef:"Deuteronomy 6:7",
  scrKJV:"And thou shalt teach them diligently unto thy children, and shalt talk of them when thou sittest in thine house, and when thou walkest by the way, and when thou liest down, and when thou risest up.",
  areas:["personal","family"], hue:["#7C8A3F","#45511C"],
  audience:"Parents, grandparents, mentors, ministry leaders",
  season:"Fall discipleship launch · New Year · Back-to-school",
  sessions:[
    { t:"Caught and Taught", scr:"Deuteronomy 6:6–7",
      sq:"“These commandments … are to be on your hearts. Impress them on your children.”",
      qs:["Faith is more often caught than taught. What is your family currently catching from your everyday life with God?",
          "Deuteronomy locates faith formation in ordinary moments — meals, drives, bedtimes. Which of those moments could become spiritual ground in your home?",
          "What would have to change for faith conversations to feel natural rather than forced in your family?"],
      step:"Pick one daily moment — a meal, a drive, bedtime — and use it for one short faith conversation every day this week." },
    { t:"A Faith of Their Own", scr:"2 Timothy 1:5",
      sq:"“Your sincere faith … first lived in your grandmother … and … your mother, and … now lives in you also.”",
      qs:["Inherited faith eventually has to become owned faith. When did your faith become genuinely your own — and what helped?",
          "How can you create space for a young person to question and wrestle without losing their faith?",
          "What’s the difference between pressuring a child toward faith and inviting them into it?"],
      step:"Ask a younger person an open, non-anxious question about what they actually believe — and listen without correcting." },
    { t:"Modeled, Not Just Mentioned", scr:"1 Corinthians 11:1",
      sq:"“Follow my example, as I follow the example of Christ.”",
      qs:["The next generations are always watching. What are they learning about God from watching you, not hearing you?",
          "Where is there a gap between the faith you talk about and the faith you live? How might a child read that gap?",
          "What is one practice you’d want a young person to imitate after watching your life?"],
      step:"Let someone younger see one part of your real walk with God this week — your prayer, your repentance, your generosity." },
    { t:"The Table and the Talk", scr:"Psalm 78:4",
      sq:"“We will tell the next generation the praiseworthy deeds of the Lord … the wonders he has done.”",
      qs:["Where does meaningful conversation actually happen in your family — and how could faith have a place there?",
          "What keeps the dinner table (or its equivalent) from becoming a place of real connection?",
          "What is one “praiseworthy deed of the Lord” from your life the next generation has never heard?"],
      step:"Protect one shared meal this week with no screens, and tell one story of God’s faithfulness at it." },
    { t:"Faith Under Pressure", scr:"1 Peter 3:15",
      sq:"“Always be prepared to give an answer to everyone who asks you to give the reason for the hope that you have.”",
      qs:["The next generation is growing up with hard questions about faith. Are you a safe place for those questions, or a place to avoid them?",
          "What is a question about faith you’re afraid a younger person will ask — and what would it take to face it together?",
          "How do you pass on a faith sturdy enough to survive a secular culture?"],
      step:"Invite a young person to bring you their hardest question about faith — and commit to seeking the answer together." },
    { t:"Handing Off the Baton", scr:"2 Timothy 2:2",
      sq:"“…entrust to reliable people who will also be qualified to teach others.”",
      qs:["A baton dropped in the handoff loses the race. Where is your family’s faith “handoff” strongest — and where is it most at risk?",
          "Beyond your own children, who is one younger believer you could pour faith into?",
          "What is the most important thing you’ve learned in 40 days about passing on a living faith?"],
      step:"Each person names one young person they will intentionally disciple over the next year and one specific first step. The group prays over each name." }
  ]
},

/* ─────────────────────────── 5 ─────────────────────────── */
{ id:"family-by-design",
  title:"Family by Design",
  sub:"A 40-Day Journey to an Intentional Family",
  quote:"A family without a design will be designed by everything else competing for it.",
  desc:"No one builds a house by accident — yet most families are constructed by drift, reacting to schedules and screens instead of being designed around a shared purpose. A flourishing family is not the accidental product of love alone but the deliberate result of a clear vision, a shared mission, and stated values. This journey walks a household through drafting its vision, mission, and values, and building the rhythms that hold them.",
  big:"A flourishing family is not the product of good intentions but of intentional design — a clear vision, a shared mission, and stated values that turn a household from a collection of busy individuals into a family on purpose.",
  scrRef:"Proverbs 24:3",
  scrKJV:"Through wisdom is an house builded; and by understanding it is established.",
  areas:["family"], hue:["#8A5A3C","#4A2C14"],
  audience:"Couples, parents, blended families, engaged couples",
  season:"New Year · Fall · Marriage & family emphasis",
  sessions:[
    { t:"Built or Drifted?", scr:"Proverbs 24:3–4",
      sq:"“By wisdom a house is built … through knowledge its rooms are filled with rare and beautiful treasures.”",
      qs:["Be honest: is your family more the result of intentional design or of drift and reaction? What’s the evidence?",
          "If your family is a house, what is it currently being “built” around — and is that what you actually want?",
          "What would it look like to build your home “by wisdom” rather than by whatever fits the schedule?"],
      step:"Name the one thing your family’s life is most organized around right now, and ask whether it deserves that place." },
    { t:"A Vision Only God Could Do", scr:"Habakkuk 2:2",
      sq:"“Write down the revelation and make it plain … so that whoever reads it may run with it.”",
      qs:["A vision statement is a short, memorable picture of a future only God could bring about. What future do you long for your family?",
          "If God did something in your family in the next 20 years that only He could do, what would it be?",
          "Why does a family rarely move toward a future it has never named?"],
      step:"Draft a one-line family vision: “Our family vision is …” Make it short, memorable, and God-sized." },
    { t:"Your Family Mission", scr:"Joshua 24:15",
      sq:"“But as for me and my household, we will serve the Lord.”",
      qs:["A mission says why your family exists. Complete it roughly: “Our family exists to …” What surfaces?",
          "How would a clear mission make hard family decisions — about money, time, conflict — simpler?",
          "Whose voice in the family still needs to be heard before a mission can truly be shared?"],
      step:"Bring a draft family mission to the people it describes and invite their words into it before the next session." },
    { t:"The Values That Guide Us", scr:"Philippians 4:8",
      sq:"“Whatever is true … noble … right … pure … lovely … admirable — think about such things.”",
      qs:["What five or six values do you most want to define your family — and which are actually lived right now?",
          "Where is there a gap between the values you claim and the values your calendar and bank statement reveal?",
          "Which one value, if your family truly lived it, would change the most?"],
      step:"Write your family’s top five values on paper, post them where everyone sees them, and pick one to practice this week." },
    { t:"Rhythms and the Family Table", scr:"Acts 2:46",
      sq:"“They broke bread in their homes and ate together with glad and sincere hearts.”",
      qs:["Values live or die in rhythms. What weekly or yearly rhythm could carry your family’s mission and values?",
          "What is one tradition from your past you want to keep — and one you want to start?",
          "What would a simple, regular family meeting look like in your home?"],
      step:"Schedule one recurring family rhythm — a weekly meal, a monthly meeting, a yearly retreat — and put it on the calendar." },
    { t:"Living the Design", scr:"Matthew 7:24",
      sq:"“Everyone who hears these words of mine and puts them into practice is like a wise man who built his house on the rock.”",
      qs:["A design on paper changes nothing until it’s practiced. What is the first thing you’ll actually do?",
          "Who in the family will help “carry the torch” to keep the vision and values alive over time?",
          "What’s the most important shift these 40 days have produced in how you build your home?"],
      step:"Each person commits to finalizing one element — vision, mission, or values — with their family in the next 30 days, and names one person to check in. Close by praying over each household." }
  ]
},

/* ─────────────────────────── 6 ─────────────────────────── */
{ id:"legacy-living",
  title:"Legacy Living",
  sub:"A 40-Day Journey to Living Your Legacy Now",
  quote:"Your legacy is not written in your will. It is written in your Tuesdays.",
  desc:"Legacy is not something you arrange at the end of your life. It is something you are building today, in a thousand ordinary moments you barely notice. The most important legacy work does not happen in an estate attorney’s office; it happens in the ordinary rhythms your family watches you live. This journey helps a household stop postponing legacy to “someday” and start building it in the present.",
  big:"Legacy is not a document you sign at the end — it is the cumulative weight of how you live every ordinary day, which means the most important legacy work happens now, in the habits and choices your family watches you make.",
  scrRef:"Colossians 3:23",
  scrKJV:"And whatsoever ye do, do it heartily, as to the Lord, and not unto men.",
  areas:["personal","charitable"], hue:["#A04E3C","#5F2A1C"],
  audience:"Every household and stage of life",
  season:"Any season · New Year · Stewardship emphasis",
  sessions:[
    { t:"Made in the Ordinary", scr:"Colossians 3:23",
      sq:"“Whatever you do, work at it with all your heart, as working for the Lord, not for human masters.”",
      qs:["If legacy is built in ordinary days, what is your typical Tuesday teaching your family about what matters?",
          "Where do you tend to “phone it in” — and what might your family be learning from that?",
          "What would change if you treated your most routine responsibilities as work done for the Lord?"],
      step:"Choose one ordinary, repeated task this week and do it as worship — fully present, with all your heart." },
    { t:"What They See Is What They Keep", scr:"Matthew 5:16",
      sq:"“Let your light shine before others, that they may see your good deeds and glorify your Father.”",
      qs:["Your family keeps what they see far longer than what they’re told. What are they seeing most consistently?",
          "What is one good habit you hope a younger person imitates — and are you actually living it visibly?",
          "What private inconsistency would most undermine the legacy you want to live?"],
      step:"Identify one good practice you do privately and let it become visible to your family this week." },
    { t:"Habits That Outlive Us", scr:"Daniel 6:10",
      sq:"“Three times a day he got down on his knees and prayed … just as he had done before.”",
      qs:["Daniel’s legacy was built on a settled, unshakable habit. What daily habit do you most want to outlive you?",
          "Which of your current habits, if multiplied across your descendants, would you be proud of — and which would worry you?",
          "What is one small habit you could begin now that could echo for generations?"],
      step:"Start one simple, daily faith habit this week and track it — small and consistent beats large and occasional." },
    { t:"Generosity as a Way of Life", scr:"2 Corinthians 9:7",
      sq:"“Each of you should give what you have decided in your heart to give … for God loves a cheerful giver.”",
      qs:["Is generosity a special event in your family or a normal rhythm? What are your children catching about giving?",
          "What would it take to make generosity part of your family’s identity rather than an occasional gesture?",
          "Who is the most genuinely generous person you know, and what is different about how they hold money?"],
      step:"Make one act of generosity together as a family this week — and talk about why you did it." },
    { t:"Margin for What Matters", scr:"Ephesians 5:15–16",
      sq:"“Be very careful, then, how you live … making the most of every opportunity.”",
      qs:["Presence is the currency of legacy. Where is your time actually going — and where do you wish it went?",
          "What good thing is crowding out the best thing in your family’s schedule?",
          "What would you have to say no to in order to be more present to the people who matter most?"],
      step:"Protect one block of unhurried, agenda-free time with your family this week, and guard it like an appointment." },
    { t:"Start Today", scr:"Galatians 6:9–10",
      sq:"“Let us not become weary in doing good … as we have opportunity, let us do good to all.”",
      qs:["If legacy is built today, what is the one thing you will stop postponing to “someday”?",
          "Which daily rhythm from these 40 days do you most want to keep?",
          "What has shifted in how you understand when legacy actually gets built?"],
      step:"Each person names one everyday legacy practice — a habit, a generosity, a rhythm of presence — they will begin now and sustain, and one person to ask about it in 30 days." }
  ]
},

/* ─────────────────────────── 7 ─────────────────────────── */
{ id:"blessing-the-next-generation",
  title:"Blessing the Next Generation",
  sub:"A 40-Day Journey into the Power of Blessing",
  quote:"Children do not outgrow their need for a blessing. They simply learn to stop asking for it.",
  desc:"Every child is asking two silent questions: Do you see me? Am I valued? The blessing is how a parent answers — with words, with presence, and with a future spoken over a life. An unblessed generation will spend its life trying to earn what should have been freely given. This journey equips parents, grandparents, and mentors to speak meaningful blessing and to prepare, not merely provide for, those who come after them.",
  big:"A blessing is more than a kind word — it is the intentional act of conferring value, affirming identity, and speaking a future over the next generation, the way God blessed His people and fathers in Scripture blessed their children.",
  scrRef:"Numbers 6:24–25",
  scrKJV:"The Lord bless thee, and keep thee: the Lord make his face shine upon thee, and be gracious unto thee.",
  areas:["family"], hue:["#D89A3E","#8A5A10"],
  audience:"Parents, grandparents, mentors, spiritual parents",
  season:"Father’s & Mother’s Day · Fall · Graduation season",
  sessions:[
    { t:"The Power of a Blessing", scr:"Numbers 6:24–25",
      sq:"“The Lord bless you and keep you; the Lord make his face shine on you.”",
      qs:["Did you receive a clear blessing from your parents — a sense of being seen and believed in? How has its presence or absence shaped you?",
          "What is the difference between approval of what a child does and blessing of who a child is?",
          "Who in your life still needs to hear a blessing from you?"],
      step:"Speak one specific, unearned word of blessing over a child or younger person this week — out loud." },
    { t:"Words That Build a Life", scr:"Proverbs 18:21",
      sq:"“The tongue has the power of life and death.”",
      qs:["What words — said or unsaid — from a parent still echo in you, for good or ill?",
          "What is the ratio of correction to blessing in how you speak to the next generation?",
          "What specific words of life does someone in your family most need to hear from you right now?"],
      step:"For one week, deliberately give one specific, genuine word of affirmation each day to someone younger." },
    { t:"Seeing Each Child Uniquely", scr:"Proverbs 22:6",
      sq:"“Start children off on the way they should go, and even when they are old they will not turn from it.”",
      qs:["Proverbs points to a child’s unique bent. What is the unique design of each young person in your life?",
          "Where might you be trying to shape a child into your plan rather than blessing the person God made them to be?",
          "What gift or strength in a young person have you noticed but never named to them?"],
      step:"Tell one young person a specific strength or calling you see in them — something only attentive love would notice." },
    { t:"Preparing, Not Just Providing", scr:"Luke 16:10",
      sq:"“Whoever can be trusted with very little can also be trusted with much.”",
      qs:["It’s easier to provide for children than to prepare them. Where have you defaulted to providing instead of preparing?",
          "What would it look like to hand on responsibility in increasing measures rather than all at once?",
          "Is the next generation ready to steward what you hope to leave them — and if not, what is the first lesson?"],
      step:"Give a young person one new, real responsibility this week — and coach rather than rescue them through it." },
    { t:"The Gift of Presence", scr:"Mark 10:14,16",
      sq:"“Let the little children come to me … And he took the children in his arms … and blessed them.”",
      qs:["Jesus blessed children by stopping for them. Where do the young people in your life experience your full, unhurried attention?",
          "What competes most for the presence your family actually needs from you?",
          "When did you last give someone younger your undivided attention — and what did it do for them?"],
      step:"Give one young person an hour of undistracted, agenda-free presence this week." },
    { t:"Speaking the Blessing", scr:"Genesis 27:28–29",
      sq:"“May he give you the dew of heaven … may nations serve you …”",
      qs:["What full, intentional blessing do you most want to speak over the next generation — and what has held you back?",
          "How could blessing become a regular practice in your family rather than a one-time event?",
          "What has changed in these 40 days about how you understand the power of a spoken blessing?"],
      step:"Each person commits to writing and speaking one full blessing over a specific child or young person in the next 30 days, and names someone to follow up." }
  ]
},

/* ─────────────────────────── 8 ─────────────────────────── */
{ id:"the-generational-life",
  title:"The Generational Life",
  sub:"A 40-Day Journey into the Multi-Generational Family",
  quote:"Independence raises a child. Interdependence raises a family that lasts a hundred years.",
  desc:"The world tells you to raise children to independence and send them off. God designed something richer — a family woven across generations, each one needing and strengthening the others, where wisdom flows down, honor flows up, and faith is reaffirmed by each succeeding generation. This journey helps a family think in centuries and become a family that endures.",
  big:"God’s vision for the family is not isolated independence but covenant interdependence — multiple generations loving, serving, and strengthening one another, so the family becomes a living testimony that outlasts any single life.",
  scrRef:"Psalm 145:4",
  scrKJV:"One generation shall praise thy works to another, and shall declare thy mighty acts.",
  areas:["family"], hue:["#3FA796","#1E5C52"],
  audience:"Extended families, grandparents, adult children",
  season:"Fall · Holidays · Family-reunion season",
  sessions:[
    { t:"Up-and-Out or All-In?", scr:"Psalm 128:6",
      sq:"“May you live to see your children’s children. Peace be on Israel.”",
      qs:["The culture’s goal is independence; God’s vision adds lifelong connection. Which has shaped your family more, and with what result?",
          "What’s the difference between healthy interdependence and unhealthy dependence between generations?",
          "What would a more connected, all-in family look like for you — without losing healthy maturity?"],
      step:"Take one step this week to deepen connection with a generation above or below you — a call, a visit, a meal." },
    { t:"The Hundred-Year Family", scr:"Deuteronomy 7:9",
      sq:"“Know therefore that the Lord your God is … the faithful God, keeping his covenant … to a thousand generations.”",
      qs:["What would change in your decisions if you genuinely thought of your family as a hundred-year project?",
          "What do you most hope is still true of your family in three generations?",
          "What would have to be intentionally articulated and reaffirmed for that to happen?"],
      step:"Write one paragraph describing your family three generations from now if God answers your deepest prayers." },
    { t:"Strength in Connection", scr:"Ecclesiastes 4:12",
      sq:"“A cord of three strands is not quickly broken.”",
      qs:["Where has connection across generations made your family stronger — and where has isolation made it weaker?",
          "Who in your family is currently carrying a burden alone that the family could help bear?",
          "How could your family function more like a team and less like separate households?"],
      step:"Identify one family member carrying something heavy, and offer specific, practical help this week." },
    { t:"Honoring Those Before Us", scr:"Exodus 20:12",
      sq:"“Honor your father and your mother, so that you may live long in the land.”",
      qs:["Honor flows up as wisdom flows down. How well does your family honor its older generations?",
          "What wisdom or story would be lost if the oldest member of your family passed tomorrow?",
          "What is one way you could honor an older family member that you’ve been meaning to do?"],
      step:"Honor one older family member this week — a visit, a recorded conversation, a written word of gratitude." },
    { t:"Carrying the Torch", scr:"2 Peter 1:13",
      sq:"“I think it is right … to refresh your memory … to stir you up by way of reminder.”",
      qs:["A hundred-year family requires values reaffirmed by each generation. Who in your family “carries the torch” of what matters?",
          "What values or traditions are at risk of fading if no one deliberately keeps them alive?",
          "How do you pass responsibility for the family’s heart to the next generation without forcing it?"],
      step:"Name one value or tradition worth preserving and one younger person you’ll invite to help carry it." },
    { t:"A Family That Endures", scr:"Psalm 145:4",
      sq:"“One generation commends your works to another; they tell of your mighty acts.”",
      qs:["What is the single most important thing this group has shown you about the generational life?",
          "What is one way you will move your family from isolated independence toward covenant interdependence?",
          "Who will you commit to staying connected with across generations — and how?"],
      step:"Each person names one commitment to strengthen the multi-generational life of their family — a rhythm of connection, an act of honor, a tradition to keep — and one person to ask about it in 30 days." }
  ]
},

/* ─────────────────────────── 9 ─────────────────────────── */
{ id:"building-a-spiritual-legacy",
  title:"Building a Spiritual Legacy",
  sub:"A 40-Day Journey to a Spiritual Foundation That Lasts",
  quote:"Wealth transfer fills a bank account. Wisdom transfer fills a life. Only one of them lasts.",
  desc:"You can transfer wealth in an afternoon. Transferring wisdom takes a lifetime — and it is the only transfer that decides whether everything else becomes a blessing or a burden. The hard work of legacy planning usually fixates on the wealth transfer, but the greater and more neglected work is the wisdom transfer: passing on the faith, convictions, and character that make wealth a blessing rather than a curse.",
  big:"The foundation of every lasting legacy is spiritual — a transfer of faith and wisdom that must be built deliberately, because without it wealth becomes an idol and an inheritance becomes a burden instead of a blessing.",
  scrRef:"1 Corinthians 3:10",
  scrKJV:"According to the grace of God which is given unto me, as a wise masterbuilder, I have laid the foundation.",
  areas:["financial","personal"], hue:["#9B7937","#5A4210"],
  audience:"Parents, business owners, those with assets to steward",
  season:"Year-end · New Year · Stewardship season",
  sessions:[
    { t:"The Foundation Under Everything", scr:"1 Corinthians 3:11",
      sq:"“No one can lay any foundation other than the one already laid, which is Jesus Christ.”",
      qs:["Every legacy is built on some foundation. What is your family’s legacy actually built on right now?",
          "What happens to a family’s wealth, name, or business when the spiritual foundation is missing?",
          "Where do you most need to strengthen the foundation before building anything else?"],
      step:"Name the foundation your family’s legacy is currently built on, and one way to make Christ more central to it." },
    { t:"Wisdom Transfer vs. Wealth Transfer", scr:"Proverbs 4:7",
      sq:"“The beginning of wisdom is this: Get wisdom. Though it cost all you have, get understanding.”",
      qs:["Most legacy energy goes into transferring wealth. What would it look like to invest equally in transferring wisdom?",
          "What is the most important piece of wisdom you’ve learned — from success or from failure — that the next generation needs?",
          "Why is wisdom so much harder to pass on than money, and what does that require of you?"],
      step:"Write down three life lessons — including from your mistakes — you most want to transfer to those after you." },
    { t:"The Faith You Model", scr:"Psalm 78:5",
      sq:"“He decreed statutes … which he commanded our ancestors to teach their children.”",
      qs:["The strongest spiritual legacy is modeled, not lectured. What is your life actually teaching about following Jesus?",
          "Are you cultivating a family culture that visibly prioritizes Christ — prayer, Scripture, service? Where is it strong, where thin?",
          "What is one spiritual practice you want to be unmistakably part of your family’s identity?"],
      step:"Invite your family into one shared spiritual practice this week — prayer, Scripture, or serving someone together." },
    { t:"Stewards, Not Owners", scr:"Psalm 24:1",
      sq:"“The earth is the Lord’s, and everything in it.”",
      qs:["If God owns it all and you are a steward, how does that reframe what you’re really “leaving” anyone?",
          "Where do you still live as an owner rather than a manager of what God has entrusted to you?",
          "What would your family learn about money if they saw you hold it with open hands?"],
      step:"Identify one area where you’ve been holding tightly as an owner, and take one step to steward it with open hands." },
    { t:"The Legacy Letter", scr:"Deuteronomy 6:9",
      sq:"“Write them on the doorframes of your house and on your gates.”",
      qs:["If you wrote a letter to your children and grandchildren about faith and what matters most, what would it have to say?",
          "What spiritual conviction or family value has never been written down — and is therefore at risk of being lost?",
          "Why do we so often leave the most important things unspoken until it’s too late?"],
      step:"Begin a legacy letter this week: “The most important thing I want you to know about God and life is …”" },
    { t:"Laying the Cornerstone", scr:"Ephesians 2:20",
      sq:"“…built on the foundation … with Christ Jesus himself as the chief cornerstone.”",
      qs:["What is the most important thing you’ve learned in 40 days about building a spiritual legacy?",
          "What is the one piece of wisdom or faith you are most determined to transfer — and to whom?",
          "What concrete step will you take to make your family’s foundation more clearly Christ?"],
      step:"Each person commits to one act of wisdom transfer in the next 30 days — finishing a legacy letter, a recorded lesson, a discipleship conversation — and names one person to ask about it." }
  ]
},

/* ─────────────────────────── 10 ─────────────────────────── */
{ id:"passing-faith-forward",
  title:"Passing Faith Forward",
  sub:"A 40-Day Journey to Completing the Handoff of Faith",
  quote:"Faith is always one generation away from extinction. The handoff is everything.",
  desc:"A faith that is not handed forward dies in a single generation. The great commission begins at your own kitchen table — and the first people you are sent to are the ones who share your last name. Faith does not survive by inheritance alone; it survives by being deliberately told and retold, modeled and multiplied, until the next generation owns it and hands it on again.",
  big:"Faith does not survive by inheritance alone — it survives by being deliberately handed forward, told and retold, modeled and multiplied, until the next generation owns it and hands it on again.",
  scrRef:"Psalm 78:4",
  scrKJV:"…shewing to the generation to come the praises of the Lord, and his strength, and his wonderful works that he hath done.",
  areas:["charitable","family"], hue:["#7A3A4E","#45202C"],
  audience:"Parents, grandparents, mentors, whole congregations",
  season:"Fall discipleship launch · New Year · Any season",
  sessions:[
    { t:"One Generation Away", scr:"Judges 2:10",
      sq:"“After that whole generation … another generation grew up who knew neither the Lord nor what he had done.”",
      qs:["Faith collapsed in Israel in one generation. What makes the handoff so fragile — even for committed families?",
          "Where do you sense the handoff is strong in your family — and where is it most at risk?",
          "What would it cost your family’s future if this generation simply assumed faith would pass on by itself?"],
      step:"Identify the weakest link in your family’s faith handoff right now, and one step to strengthen it this month." },
    { t:"Tell the Story", scr:"Joshua 4:6–7",
      sq:"“In the future, when your children ask … tell them …”",
      qs:["Israel built stone memorials so children would ask, “What do these mean?” What memorials prompt faith conversations in your family?",
          "What is the central God-story of your family that must be told and retold?",
          "How do you tell your faith story in a way that invites the next generation in rather than lecturing them?"],
      step:"Tell one God-story from your life to a younger person this week, and end with what it taught you about God." },
    { t:"The Power of Remembering", scr:"Deuteronomy 6:12",
      sq:"“Be careful that you do not forget the Lord …”",
      qs:["Forgetting is the enemy of faith. How does your family deliberately remember what God has done?",
          "What spiritual marker or tradition helps your family remember — and what could you add?",
          "What past faithfulness of God are you in danger of forgetting in this season?"],
      step:"Start one simple practice of remembrance — a family journal of answered prayers, a regular testimony time." },
    { t:"From My Faith to Their Faith", scr:"2 Timothy 3:14–15",
      sq:"“Continue in what you have learned … from infancy you have known the Holy Scriptures.”",
      qs:["Faith must move from your conviction to their conviction. How do you help a young person own faith rather than just inherit it?",
          "What’s the difference between forcing belief and forming the conditions where belief can take root?",
          "Who in your family is on the edge of owning — or walking away from — faith, and how can you walk with them?"],
      step:"Have one unhurried, non-defensive conversation with a younger person about where they actually are with God." },
    { t:"Multiplying Beyond the Family", scr:"2 Timothy 2:2",
      sq:"“Entrust to reliable people who will also be qualified to teach others.”",
      qs:["Passing faith forward isn’t limited to bloodline. Who outside your family could you invest in spiritually?",
          "Who poured into you who wasn’t a relative — and what did that mean?",
          "What would it look like to become a spiritual parent to someone who has no one passing faith to them?"],
      step:"Identify one person beyond your family you could begin to disciple, and take a first step toward them this week." },
    { t:"The Handoff", scr:"Matthew 28:19–20",
      sq:"“Go and make disciples … teaching them to obey everything I have commanded you.”",
      qs:["The great commission starts at home. Who are the people you are most clearly “sent” to with the gospel?",
          "What is the most important thing these 40 days have shown you about passing faith forward?",
          "What is the one handoff you will not leave to chance, starting now?"],
      step:"Each person names the specific people — within and beyond the family — they will intentionally pass faith to, one concrete next step, and one person to ask about it in 30 days. The group prays over each name to close the journey." }
  ]
},

/* ─────────────────────── COMPANION · WISDOM ─────────────────────── */
{ id:"wisdom-driven-life", companion:true,
  title:"The Wisdom-Driven Life",
  sub:"A 40-Day Journey from Information to Wisdom",
  quote:"Knowledge is knowing what is true. Wisdom is knowing what to do. One fills your head; the other builds your life.",
  desc:"We have never had more access to information — and never felt less sure of what to do with it. Scripture insists that wisdom is not the same as intelligence, education, or data — it is the God-given skill of living well, of making the right call in the real, pressured, ordinary moments of a life. This companion journey pairs with the Family Legacy Collection as the wisdom transfer — trading reactive, anxious living for a life quietly built on the wisdom that comes from God.",
  big:"Wisdom is not the same as knowledge — it is the God-given skill of living well: fearing the Lord, asking Him for direction, weighing decisions, guarding our words, and building a life on the rock rather than the sand. The wise life is not the smartest life; it is the most surrendered one.",
  scrRef:"James 1:5",
  scrKJV:"If any of you lack wisdom, let him ask of God, that giveth to all men liberally, and upbraideth not; and it shall be given him.",
  areas:["personal","business"], hue:["#22335C","#16223D"],
  audience:"Anyone facing decisions, change, or overwhelm — family, company, or church",
  season:"New Year · Fall launch · Any season",
  related:"Pairs with Family Legacy — the wisdom transfer",
  sessions:[
    { t:"Two Ways to Live", scr:"Proverbs 9:10",
      sq:"“The fear of the Lord is the beginning of wisdom, and knowledge of the Holy One is understanding.”",
      qs:["Wisdom begins with the fear of the Lord — a reverent trust that He, not you, is God. Where is that trust strong in your life, and where is it thin?",
          "What is the difference between being smart and being wise? Name someone you’d call truly wise — what marks their life?",
          "Where have you recently confused having information with actually knowing what to do?"],
      step:"Before each decision this week, pause and ask one question: “What would the fear of the Lord lead me to do here?”" },
    { t:"Ask for It", scr:"James 1:5",
      sq:"“If any of you lacks wisdom, you should ask God, who gives generously to all without finding fault.”",
      qs:["James says wisdom is available simply for the asking. Why do we so rarely ask — and what does that reluctance reveal?",
          "Where are you currently leaning on your own understanding instead of asking God for wisdom?",
          "What decision are you facing right now that you have never actually prayed about?"],
      step:"Name one decision you’re facing and pray James 1:5 over it every day this week, watching for how God answers." },
    { t:"Wisdom in the Decision", scr:"Proverbs 3:5–6",
      sq:"“Trust in the Lord with all your heart and lean not on your own understanding … and he will make your paths straight.”",
      qs:["When has your own understanding led you wrong — and what would leaning on God have looked like?",
          "How do you usually make big decisions — by fear, by impulse, by what others think, or by seeking God? Be honest.",
          "What is one area where you sense God asking you to trust Him beyond what makes sense to you?"],
      step:"Run one decision you’re wrestling with through a simple grid this week: Is it wise? Is it loving? Does it honor God? Write your answers down." },
    { t:"The Words of the Wise", scr:"James 3:17",
      sq:"“The wisdom that comes from heaven is first of all pure; then peace-loving, considerate … full of mercy.”",
      qs:["Heavenly wisdom is peace-loving and considerate — not just correct. Where are you “right” but not wise in how you speak?",
          "Wisdom balances truth and love. Which do you tend to drop under pressure — truth or love?",
          "What is one relationship where wiser words would change everything?"],
      step:"Before speaking into anything tense this week, ask: “Is it true? Is it kind? Is it the right time?” Hold your words until all three are yes." },
    { t:"Wisdom in Community", scr:"Proverbs 15:22",
      sq:"“Plans fail for lack of counsel, but with many advisers they succeed.”",
      qs:["Who are the wise voices you actually invite into your decisions — and is that circle big enough?",
          "“Walk with the wise and become wise.” Who are you becoming like, based on who you spend the most time with?",
          "Where have you made an important decision in isolation that wise counsel might have changed?"],
      step:"Identify one wise person and ask them for honest input on a real decision or area of your life this week." },
    { t:"The Wise Builder", scr:"Matthew 7:24",
      sq:"“Everyone who hears these words of mine and puts them into practice is like a wise man who built his house on the rock.”",
      qs:["Jesus says wisdom is not hearing truth but doing it. Where do you already know the wise thing — and simply need to do it?",
          "Integrity means your life looks the same on Tuesday as on Sunday. Where is the gap between what you know and how you live?",
          "After these 40 days, in what one area do you most want your life to become wisdom-driven?"],
      step:"Each person names one area of life they will hand over to God’s wisdom for the next 90 days, and one person who will ask them about it. Close by asking God together for the wisdom He promises to give." }
  ],
  weeks:[
    { t:"Two Ways to Live · The Fear of the Lord", days:[
      ["Begin Here","Proverbs 9:10","Wisdom starts with the fear of the Lord. Name where you have been starting instead."],
      ["Wisdom or Folly","Proverbs 14:8","The wise think about where the road leads; the fool does not. Which are you today?"],
      ["Two Builders","Matthew 7:24–27","Same storm, two foundations. Honestly, what is your life built on?"],
      ["Not Wise in Your Own Eyes","Proverbs 3:7","Where are you trusting only your own judgment? Hand it to God."],
      ["Everything Is Vanity","Ecclesiastes 1:2","Solomon had it all and called it meaningless. What are you chasing that can’t satisfy?"],
      ["A Reverent Heart","Psalm 111:10","Reverence isn’t dread of punishment; it’s awe that reorders everything. Sit in it."],
      ["The Tree by Water","Psalm 1:1–3","Two ways diverge. Choose the path that leads to a tree planted by streams of water."]]},
    { t:"Ask for It · Wisdom from God", days:[
      ["Just Ask","James 1:5","Wisdom is one honest prayer away. Ask for it today, out loud."],
      ["Ask Without Doubting","James 1:6","Bring God your real question and trust Him with the answer."],
      ["Solomon’s Request","1 Kings 3:9","He could ask for anything and asked for a discerning heart. What would you ask for?"],
      ["More Than Gold","Proverbs 3:13–14","Wisdom is more profitable than silver. Treat it that way today."],
      ["The Spirit Guides","John 16:13","You are not left to figure life out alone. Invite the Spirit into one decision."],
      ["Hidden in Christ","Colossians 2:3","All wisdom is hidden in Jesus. Go to Him, not just to more information."],
      ["Dig for It","Proverbs 2:3–5","Wisdom is found by those who search like miners. Where will you dig this week?"]]},
    { t:"Wisdom in the Decision · Trust & Discernment", days:[
      ["Lean Not","Proverbs 3:5","Trust Him with your whole heart; lean not on your own understanding."],
      ["Straight Paths","Proverbs 3:6","Submit your ways and He straightens the path. Name one way to submit today."],
      ["Count the Cost","Luke 14:28","The wise build only after counting the cost. What decision needs honest counting?"],
      ["Slow the Impulse","Proverbs 19:2","“To be hasty is to miss the way.” Where do you need to slow down?"],
      ["Test It","1 Thessalonians 5:21","Test everything; hold to what is good. What needs testing before you commit?"],
      ["Peace as Umpire","Colossians 3:15","Let the peace of Christ rule — and referee — your decisions today."],
      ["Wise, Loving, Honoring","Philippians 1:9–10","Run today’s choice through three filters: Is it wise? Loving? Honoring to God?"]]},
    { t:"The Words of the Wise · Wisdom in Speech", days:[
      ["Life and Death","Proverbs 18:21","The tongue carries life or death. Which did your words carry today?"],
      ["Slow to Speak","James 1:19","Quick to listen, slow to speak, slow to anger. Practice the order."],
      ["The Right Word","Proverbs 25:11","A word fitly spoken is gold set in silver. Whom can you encourage with one?"],
      ["Truth in Love","Ephesians 4:15","Truth without love wounds; love without truth flatters. Aim for both."],
      ["Guard the Gate","Proverbs 21:23","Guarding your mouth guards your life. Hold back one word you’d regret."],
      ["A Gentle Answer","Proverbs 15:1","A gentle answer turns away wrath. Try it in your hardest conversation."],
      ["Wisdom from Above","James 3:17","Pure, peace-loving, considerate, merciful. Let that describe your speech today."]]},
    { t:"Wisdom in Community · Counsel & Companions", days:[
      ["Many Counselors","Proverbs 15:22","Plans fail without counsel. Who will you invite into yours?"],
      ["Walk with the Wise","Proverbs 13:20","You become like your company. Audit your closest five."],
      ["Iron Sharpens Iron","Proverbs 27:17","Growth needs friction from a faithful friend. Who sharpens you?"],
      ["Faithful Wounds","Proverbs 27:6","A friend’s honest wound beats an enemy’s flattery. Receive correction well."],
      ["Carry the Load","Galatians 6:2","Wisdom shares the weight. Whose burden can you help carry today?"],
      ["Humble Enough to Ask","Proverbs 11:2","“With humility comes wisdom.” Ask for help in one area of pride."],
      ["Two Are Better","Ecclesiastes 4:9–12","A cord of three strands is not quickly broken. Gather your people."]]},
    { t:"The Wise Builder · Doing the Word", days:[
      ["Hear and Do","Matthew 7:24","The wise don’t just hear; they build. What will you build today?"],
      ["Not Hearers Only","James 1:22","Hearing without doing deceives us. Put one truth into practice now."],
      ["Tuesday Integrity","Luke 16:10","Faithful in little, faithful in much. Be the same on Tuesday as on Sunday."],
      ["Don’t Grow Weary","Galatians 6:9","The harvest comes to those who don’t give up. Keep building."],
      ["Built on the Rock","Matthew 7:25","The storm came and the house stood. Commit to the life you’ve begun."]]}
  ]
}
],

/* ───────────── the Reading Room · fully written days (flagship) ───────────── */
readings: {
  "family-legacy": {
    1: {
      title:"Every Family Leaves One",
      ref:"Proverbs 13:22",
      verse:"A good man leaveth an inheritance to his children’s children.",
      verseLabel:"Proverbs 13:22 · KJV",
      body:[
        "Here is a sentence worth sitting with before the coffee is finished: your family is already leaving a legacy. Not will leave. Is leaving. Right now, in the way this morning started, in what got talked about at dinner last night and what got avoided, in what your children or grandchildren watch you reach for when the day gets hard — something is being handed down. The only real question, and it is the question these forty days will keep asking, is whether what gets handed down was chosen.",
        "Notice what Proverbs does not say. It does not say a rich man leaves an inheritance for his children’s children. It says a good one. Scripture quietly moves inheritance out of the category of net worth and into the category of intention. Which means the family with modest means and deliberate love can leave more than the family with everything except a plan for what it all was for. Anyone who has sat with enough families knows both kinds, and knows which one the grandchildren still talk about.",
        "And notice the reach of it — children’s children. Two generations down. The writer assumes you are thinking past the people at your table to the people who will sit at tables you will never see. Most of us do not plan that far. We plan for the quarter, the school year, maybe the retirement. Proverbs plans for people who have not been born yet.",
        "There is a word for what happens when a family does not choose: drift. Drift is quiet. Drift feels like busyness, like normal life, like we’ll get to it. And drift always hands the pen to someone else — the culture, the calendar, the loudest voice in the room — to write the family story instead. A legacy left by default is still a legacy. It is just one nobody sat down and meant.",
        "So today, day one, the assignment is small and unglamorous, the way most important things are. Simply look. Look at what your family is passing on as it stands — the habits, the words, the faith or the silence about faith. No fixing yet. No guilt. Farmers walk the fields before they plant. Tonight, at your table, you will walk the field together."
      ],
      pray:"Father, You have been thinking about my children’s children longer than I have. Open my eyes today to what our family is already handing down — the good I never noticed and the drift I never meant. Give me the courage to look honestly, and the faith to believe that with You, a legacy can still be chosen. Amen.",
      table:"Go around the table once, everyone answers: “What is one thing — good or bad — that our family would pass on if nothing ever changed?” No fixing, no defending. Just listen.",
      step:"Before you sleep, write down one sentence: “The legacy our family is currently leaving is ____.” Keep it somewhere you will find it on Day 40."
    },
    2: {
      title:"The State of the Flocks",
      ref:"Proverbs 27:23",
      verse:"Be thou diligent to know the state of thy flocks, and look well to thy herds.",
      verseLabel:"Proverbs 27:23 · KJV",
      body:[
        "A shepherd in the ancient world had no dashboard. If he wanted to know how the flock was doing, he had to go stand among the sheep — count them, run his hands over them, notice the limp nobody else would catch. Proverbs turns that into a command for anyone entrusted with anything: be diligent to know the state of what is yours to tend.",
        "Most families can tell you the state of their accounts to the dollar and cannot tell you the state of their household to the heart. We audit what is easy to measure. But the flock God actually handed you sleeps down the hall, calls on Sundays, sits across the table scrolling. When did you last look — really look — at the state of those flocks? Not their grades or their portfolios. Their faith. Their loneliness. What they believe about you, and about God, because of you.",
        "Looking is not the same as fixing, and today is not a day for fixing. It is a day for the shepherd’s slow walk through the field. Diligence begins with attention, and attention is the first form love takes.",
        "Tonight, do the shepherd’s work. Ask one person in your family a question you do not already know the answer to — and then do the hardest part of tending. Stay quiet long enough to hear the whole answer."
      ],
      pray:"Lord, You know the state of every flock, including the one You placed in my care. Slow me down enough to look. Show me what I have stopped noticing. Make me diligent in attention before I am ambitious in plans. Amen.",
      table:"Each person asks the one across from them a question they genuinely don’t know the answer to. The only rule: the asker cannot talk until the answer is completely finished.",
      step:"Write down one thing you learned tonight about someone in your family that you did not know this morning."
    },
    3: {
      title:"Drift Divides",
      ref:"Proverbs 29:18",
      verse:"Where there is no vision, the people perish.",
      verseLabel:"Proverbs 29:18 · KJV",
      body:[
        "No family ever sat down and decided to drift apart. It happens the way a boat leaves a beach — nobody pushed it, the water just did what water does, and by the time anyone looked up, the shore was far away. Proverbs names the mechanism with unsettling precision: where there is no vision, the people scatter. Not because they are bad people. Because nothing was holding them together on purpose.",
        "Here is the hard mathematics of a household: a family that has not named where it is going will be carried wherever the current runs — and the current always runs toward busy, toward separate screens in separate rooms, toward conversations postponed until they are eulogies. Drift never announces itself. It just quietly divides.",
        "The remedy is not more effort. Tired families do not need another program. The remedy is a vision — a picture of what this family is for, clear enough that a child could repeat it. That picture is coming; you will draft it before these forty days are done. Today’s work is simpler and braver: admit the drift. Name one place where the current, not your convictions, has been steering.",
        "Every family is moving. The only question is whether anyone is at the wheel."
      ],
      pray:"God, You see where our family is actually headed, not just where we say we are going. Show us the drift we have baptized as busyness. And before You give us a vision, give us the honesty to admit we need one. Amen.",
      table:"One question, everyone answers: “Where has our family been drifting — one place where things just happen to us instead of being chosen by us?”",
      step:"As a family, pick one small current to swim against this week — one screen-free dinner, one call to a distant relative, one postponed conversation begun."
    }
  }
}
};
