# -*- coding: utf-8 -*-
"""The Campaign Discernment Guide — trilingual content.
Brett's instrument pattern: six dimensions, twenty-four statements, scored out of 120,
then season, congregation, felt needs, and one discernment sentence. Statements are
written about the congregation in the Purpose Driven cadence: concrete, honest,
second-person-plural, never clinical."""

FIN_EN = {
 "h1":"The Campaign Discernment Guide",
 "sub":"Not a quiz — a mirror. Ten unhurried minutes, and this guide will tell you where your church actually is, and which campaign meets it there.",
 "intro_h":"Before you pick a campaign, take your church's pulse.",
 "intro_p":"Answer for your congregation as it is, not as the brochure describes it. Low scores aren't failure — they're direction. The dimensions where you score lowest are exactly where a churchwide campaign does its deepest work.",
 "intro_meta":"Six dimensions · Twenty-four statements · Scored out of 120 · About ten minutes",
 "begin":"Begin the guide","back":"Back","next":"Next","see":"See my direction",
 "scale":["Not yet true of us","Rarely true","Sometimes","Often true","True of us"],
 "dims":[
  {"t":"Word & Worship","s":"Is Scripture a book we own, or a voice we hear?","st":[
   "Most of our people opened a Bible at home this week — and could tell you where.",
   "Prayer in our church is a first response, not a closing formality.",
   "Our people can name one thing God said to them through Scripture this month.",
   "Sunday's sermon is still being talked about on Thursday."]},
  {"t":"Belonging","s":"Nobody was meant to do this alone. Is anyone doing it alone here?","st":[
   "If we canceled our groups tomorrow, most of the church would notice by Friday.",
   "A newcomer here is known by name within a month.",
   "Our people confess real things to each other — not just prayer requests about relatives.",
   "The lonely and the homebound would say this church has not forgotten them."]},
  {"t":"Whole Hearts","s":"The anxious, the doubting, the fighting-a-private-battle. Do they heal here?","st":[
   "The anxious and the grieving in our pews would say church helps — not just fills a morning.",
   "People fighting private battles here know exactly where to take them.",
   "Our young adults' hardest questions get honored, not hushed.",
   "Our people's screens serve their souls more than they steal from them."]},
  {"t":"Open Hands","s":"Money talks in every home. Does it get discipled in this one?","st":[
   "Money is a discipleship topic here, not a crisis topic.",
   "Our people give in a way that requires faith, not just habit.",
   "A financial storm in a member's home would surface at church before it surfaced at the bank.",
   "Generosity stories get told from our platform as often as attendance numbers."]},
  {"t":"Home & Legacy","s":"The faith of this house — is it being handed down on purpose?","st":[
   "Marriages here get strengthened before they need rescuing.",
   "Our parents feel equipped for faith at home, not outsourced to the youth room.",
   "Three generations could each tell you what this church family believes.",
   "The faith of our grandparents is being told to our grandchildren — on purpose."]},
  {"t":"Sent","s":"If this church closed its doors, would the neighborhood grieve?","st":[
   "Our people can name a neighbor they are praying toward.",
   "Serving here has a waiting list, not a recruiting crisis.",
   "We are raising up more leaders than we are borrowing.",
   "If our church closed, the neighborhood would grieve."]}],
 "season":{"t":"The launch window","s":"Campaigns land differently in different seasons. When does this one leave the runway?",
  "opts":[["New Year — fresh starts","2"],["Lent & Easter","3"],["Spring","4"],["Summer","8"],
   ["Fall — back to school","9"],["Advent & Christmas","0"],["No fixed date yet","-1"]]},
 "church":{"t":"Your church, honestly","s":"Three quick facts. No wrong answers — only wrong pretending.",
  "size":{"q":"Weekend attendance","opts":[["Under 200","s"],["200–800","m"],["800–2,500","l"],["2,500 and up","xl"]]},
  "groups":{"q":"Small groups today","opts":[["We barely have any","none"],["Some, but thin","some"],["A real groups culture","strong"]]},
  "hist":{"q":"Campaign history","opts":[["This would be our first","first"],["We've run one or two","some"],["Campaigns are our rhythm","rhythm"]]}},
 "felt":{"t":"The conversations finding you","s":"Which of these keep meeting you in the lobby, the inbox, the parking lot? Choose up to three.","cap":3,
  "opts":[["Marriages under strain","marriage"],["Money pressure at home","money"],["Anxiety and burnout","anx"],
   ["Grief and loss","grief"],["Kids, teens, and screens","teens"],["Doubt and deconstruction","doubt"],
   ["Loneliness and isolation","lonely"],["People ready to serve","serve"]]},
 "outcome":{"t":"The sentence that matters","s":"Every campaign should be able to finish this sentence before it starts.",
  "lead":"Forty days from launch, I want it said of our church that…",
  "ph":"…our people finally believe God can be trusted with their money. …no one sits alone on Sunday. Write yours.",
  "fmt_q":"Length — or let the guide decide",
  "fmt_opts":[["Let the guide decide","auto"],["One catalytic Sunday","sunday"],["21-Day Challenge","21"],["30-Day Journey","30"],["40-Day Journey","40"]]},
 "res":{"h":"Your direction","total_l":"out of 120",
  "bands":[[9,"Foundation season","This is soil work — the campaign that serves you here builds basics without shame."],
   [14,"Growing edge","Real life exists here, and real hunger. The right campaign turns momentum into practice."],
   [20,"Strength to send","This is a strength. Steward it — and let it fund the dimensions still waiting."]],
  "low_line":"Your two lowest dimensions set the direction. That is not bad news — it is the assignment.",
  "fmt_h":"The shape of the launch",
  "fmt_line":{"sunday":"Start with one catalytic Sunday — a spark before the fire.",
   "21":"A 21-Day Challenge fits where you are: long enough to form a habit, short enough to finish strong the first time.",
   "30":"A 30-Day Journey gives the message a month to move from notebooks into households.",
   "40":"Your church is built for the full 40 — six weeks, whole church, all in, the Purpose Driven way."},
  "season_pre":"aimed at","outcome_pre":"You wrote:","outcome_post":"That sentence is this campaign's job description.",
  "picks_h":"Campaigns that meet you there","wild_h":"And one you didn't see coming",
  "why":{"dim":"speaks straight into your {d} score","season":"made for this exact launch window","flag":"a hand-curated flagship",
   "felt":{"marriage":"meets marriages under strain","money":"answers money pressure at home","anx":"built for the anxious and burned out",
    "grief":"walks with grief","teens":"speaks to kids, teens, and screens","doubt":"honors doubt and hard questions",
    "lonely":"gathers the lonely","serve":"mobilizes people ready to serve"}},
  "print":"Print my profile","again":"Start over"}}

FIN_ES = {
 "h1":"La Guía de Discernimiento de Campañas",
 "sub":"No es un cuestionario — es un espejo. Diez minutos sin prisa, y esta guía te dirá dónde está realmente tu iglesia y qué campaña la encuentra allí.",
 "intro_h":"Antes de elegir una campaña, tómale el pulso a tu iglesia.",
 "intro_p":"Responde por tu congregación tal como es, no como la describe el folleto. Un puntaje bajo no es fracaso — es dirección. Las dimensiones donde puntúas más bajo son exactamente donde una campaña hace su obra más profunda.",
 "intro_meta":"Seis dimensiones · Veinticuatro afirmaciones · Puntaje sobre 120 · Unos diez minutos",
 "begin":"Comenzar la guía","back":"Atrás","next":"Siguiente","see":"Ver mi dirección",
 "scale":["Aún no es cierto de nosotros","Rara vez","A veces","A menudo","Es cierto de nosotros"],
 "dims":[
  {"t":"Palabra y Adoración","s":"¿La Escritura es un libro que tenemos, o una voz que escuchamos?","st":[
   "La mayoría de nuestra gente abrió la Biblia en casa esta semana — y podría decirte dónde.",
   "En nuestra iglesia la oración es la primera respuesta, no una formalidad de cierre.",
   "Nuestra gente puede nombrar algo que Dios le dijo por la Escritura este mes.",
   "El sermón del domingo todavía se comenta el jueves."]},
  {"t":"Pertenencia","s":"Nadie fue hecho para vivir esto solo. ¿Alguien lo está viviendo solo aquí?","st":[
   "Si canceláramos los grupos mañana, la mayoría lo notaría antes del viernes.",
   "Aquí, a un recién llegado se le conoce por nombre en un mes.",
   "Nuestra gente se confiesa cosas reales — no solo peticiones por los parientes.",
   "Los solitarios y los que no pueden salir dirían que esta iglesia no los ha olvidado."]},
  {"t":"Corazones Enteros","s":"Los ansiosos, los que dudan, los que pelean batallas privadas. ¿Sanan aquí?","st":[
   "Los ansiosos y los que lloran en nuestras bancas dirían que la iglesia ayuda — no solo llena una mañana.",
   "Quien pelea una batalla privada aquí sabe exactamente adónde llevarla.",
   "Las preguntas más difíciles de nuestros jóvenes se honran, no se silencian.",
   "Las pantallas de nuestra gente sirven a su alma más de lo que le roban."]},
  {"t":"Manos Abiertas","s":"El dinero habla en cada hogar. ¿Se discipula en este?","st":[
   "Aquí el dinero es tema de discipulado, no tema de crisis.",
   "Nuestra gente da de una manera que requiere fe, no solo costumbre.",
   "Una tormenta financiera en un hogar aparecería en la iglesia antes que en el banco.",
   "Las historias de generosidad se cuentan desde la plataforma tanto como los números de asistencia."]},
  {"t":"Hogar y Legado","s":"La fe de esta casa — ¿se está entregando a propósito?","st":[
   "Aquí los matrimonios se fortalecen antes de necesitar rescate.",
   "Nuestros padres se sienten equipados para la fe en casa, no delegados al salón de jóvenes.",
   "Tres generaciones podrían decirte, cada una, qué cree esta familia de fe.",
   "La fe de nuestros abuelos se les está contando a nuestros nietos — a propósito."]},
  {"t":"Enviados","s":"Si esta iglesia cerrara sus puertas, ¿el barrio la lloraría?","st":[
   "Nuestra gente puede nombrar a un vecino por quien está orando.",
   "Servir aquí tiene lista de espera, no crisis de reclutamiento.",
   "Estamos levantando más líderes de los que pedimos prestados.",
   "Si nuestra iglesia cerrara, el barrio la lloraría."]}],
 "season":{"t":"La ventana de lanzamiento","s":"Las campañas aterrizan distinto según la temporada. ¿Cuándo despega esta?",
  "opts":[["Año Nuevo — nuevos comienzos","2"],["Cuaresma y Pascua","3"],["Primavera","4"],["Verano","8"],
   ["Otoño — regreso a clases","9"],["Adviento y Navidad","0"],["Aún sin fecha fija","-1"]]},
 "church":{"t":"Tu iglesia, con honestidad","s":"Tres datos rápidos. No hay respuestas malas — solo simulaciones malas.",
  "size":{"q":"Asistencia de fin de semana","opts":[["Menos de 200","s"],["200–800","m"],["800–2,500","l"],["2,500 o más","xl"]]},
  "groups":{"q":"Grupos pequeños hoy","opts":[["Casi no tenemos","none"],["Algunos, pero débiles","some"],["Una verdadera cultura de grupos","strong"]]},
  "hist":{"q":"Historial de campañas","opts":[["Sería nuestra primera","first"],["Hemos hecho una o dos","some"],["Las campañas son nuestro ritmo","rhythm"]]}},
 "felt":{"t":"Las conversaciones que te encuentran","s":"¿Cuáles de estas te siguen encontrando en el lobby, el correo, el estacionamiento? Elige hasta tres.","cap":3,
  "opts":[["Matrimonios bajo tensión","marriage"],["Presión económica en casa","money"],["Ansiedad y agotamiento","anx"],
   ["Duelo y pérdida","grief"],["Niños, jóvenes y pantallas","teens"],["Duda y deconstrucción","doubt"],
   ["Soledad y aislamiento","lonely"],["Gente lista para servir","serve"]]},
 "outcome":{"t":"La frase que importa","s":"Toda campaña debería poder terminar esta frase antes de empezar.",
  "lead":"A cuarenta días del lanzamiento, quiero que se diga de nuestra iglesia que…",
  "ph":"…nuestra gente por fin cree que puede confiarle a Dios su dinero. …nadie se sienta solo el domingo. Escribe la tuya.",
  "fmt_q":"Duración — o deja que la guía decida",
  "fmt_opts":[["Que la guía decida","auto"],["Un domingo catalizador","sunday"],["Desafío de 21 Días","21"],["Jornada de 30 Días","30"],["Jornada de 40 Días","40"]]},
 "res":{"h":"Tu dirección","total_l":"sobre 120",
  "bands":[[9,"Temporada de cimientos","Esto es trabajo de suelo — la campaña que te sirve aquí construye lo básico sin vergüenza."],
   [14,"Borde de crecimiento","Aquí hay vida real y hambre real. La campaña correcta convierte impulso en práctica."],
   [20,"Fuerza para enviar","Esto es una fortaleza. Adminístrala — y que financie las dimensiones que aún esperan."]],
  "low_line":"Tus dos dimensiones más bajas marcan la dirección. No es mala noticia — es la asignación.",
  "fmt_h":"La forma del lanzamiento",
  "fmt_line":{"sunday":"Comienza con un domingo catalizador — una chispa antes del fuego.",
   "21":"Un Desafío de 21 Días encaja donde estás: suficiente para formar un hábito, corto para terminar fuerte la primera vez.",
   "30":"Una Jornada de 30 Días le da al mensaje un mes para pasar de los apuntes a los hogares.",
   "40":"Tu iglesia está hecha para los 40 completos — seis semanas, toda la iglesia, sin reservas."},
  "season_pre":"apuntada a","outcome_pre":"Escribiste:","outcome_post":"Esa frase es la descripción de trabajo de esta campaña.",
  "picks_h":"Campañas que te encuentran allí","wild_h":"Y una que no viste venir",
  "why":{"dim":"habla directo a tu puntaje de {d}","season":"hecha para esta ventana exacta","flag":"una campaña insignia curada a mano",
   "felt":{"marriage":"encuentra a los matrimonios bajo tensión","money":"responde a la presión económica","anx":"hecha para los ansiosos y agotados",
    "grief":"camina con el duelo","teens":"habla a niños, jóvenes y pantallas","doubt":"honra la duda y las preguntas difíciles",
    "lonely":"reúne a los solitarios","serve":"moviliza a la gente lista para servir"}},
  "print":"Imprimir mi perfil","again":"Empezar de nuevo"}}

FIN_PT = {
 "h1":"O Guia de Discernimento de Campanhas",
 "sub":"Não é um questionário — é um espelho. Dez minutos sem pressa, e este guia dirá onde a sua igreja realmente está e qual campanha a encontra ali.",
 "intro_h":"Antes de escolher uma campanha, tome o pulso da sua igreja.",
 "intro_p":"Responda pela sua congregação como ela é, não como o folheto a descreve. Nota baixa não é fracasso — é direção. As dimensões com menor pontuação são exatamente onde uma campanha faz sua obra mais profunda.",
 "intro_meta":"Seis dimensões · Vinte e quatro afirmações · Pontuação sobre 120 · Cerca de dez minutos",
 "begin":"Começar o guia","back":"Voltar","next":"Avançar","see":"Ver minha direção",
 "scale":["Ainda não é verdade de nós","Raramente","Às vezes","Frequentemente","É verdade de nós"],
 "dims":[
  {"t":"Palavra e Adoração","s":"A Escritura é um livro que possuímos, ou uma voz que ouvimos?","st":[
   "A maioria do nosso povo abriu a Bíblia em casa esta semana — e saberia dizer onde.",
   "Na nossa igreja, oração é primeira resposta, não formalidade de encerramento.",
   "Nosso povo consegue nomear algo que Deus lhe disse pela Escritura este mês.",
   "O sermão de domingo ainda é assunto na quinta-feira."]},
  {"t":"Pertencimento","s":"Ninguém foi feito para viver isso sozinho. Alguém está vivendo sozinho aqui?","st":[
   "Se cancelássemos os grupos amanhã, a maioria notaria antes de sexta.",
   "Aqui, um recém-chegado é conhecido pelo nome em um mês.",
   "Nosso povo confessa coisas reais uns aos outros — não só pedidos pelos parentes.",
   "Os solitários e os que não podem sair diriam que esta igreja não os esqueceu."]},
  {"t":"Corações Inteiros","s":"Os ansiosos, os que duvidam, os que lutam batalhas privadas. Eles saram aqui?","st":[
   "Os ansiosos e enlutados em nossos bancos diriam que a igreja ajuda — não só preenche uma manhã.",
   "Quem luta uma batalha privada aqui sabe exatamente aonde levá-la.",
   "As perguntas mais difíceis dos nossos jovens são honradas, não silenciadas.",
   "As telas do nosso povo servem à alma mais do que roubam dela."]},
  {"t":"Mãos Abertas","s":"O dinheiro fala em toda casa. Ele é discipulado nesta?","st":[
   "Aqui, dinheiro é tema de discipulado, não tema de crise.",
   "Nosso povo dá de um jeito que exige fé, não apenas costume.",
   "Uma tempestade financeira num lar apareceria na igreja antes do banco.",
   "Histórias de generosidade são contadas do púlpito tanto quanto números de presença."]},
  {"t":"Lar e Legado","s":"A fé desta casa — está sendo entregue de propósito?","st":[
   "Aqui os casamentos são fortalecidos antes de precisarem de resgate.",
   "Nossos pais se sentem equipados para a fé em casa, não terceirizados ao ministério jovem.",
   "Três gerações saberiam dizer, cada uma, no que esta família de fé crê.",
   "A fé dos nossos avós está sendo contada aos nossos netos — de propósito."]},
  {"t":"Enviados","s":"Se esta igreja fechasse as portas, o bairro sentiria a falta?","st":[
   "Nosso povo consegue nomear um vizinho por quem está orando.",
   "Servir aqui tem lista de espera, não crise de recrutamento.",
   "Estamos levantando mais líderes do que tomando emprestado.",
   "Se a nossa igreja fechasse, o bairro choraria."]}],
 "season":{"t":"A janela de lançamento","s":"Campanhas aterrissam diferente conforme a estação. Quando esta decola?",
  "opts":[["Ano Novo — recomeços","2"],["Quaresma e Páscoa","3"],["Primavera","4"],["Verão","8"],
   ["Outono — volta às aulas","9"],["Advento e Natal","0"],["Ainda sem data","-1"]]},
 "church":{"t":"Sua igreja, com honestidade","s":"Três fatos rápidos. Não há resposta errada — só fingimento errado.",
  "size":{"q":"Presença de fim de semana","opts":[["Menos de 200","s"],["200–800","m"],["800–2.500","l"],["2.500 ou mais","xl"]]},
  "groups":{"q":"Pequenos grupos hoje","opts":[["Quase não temos","none"],["Alguns, mas frágeis","some"],["Uma verdadeira cultura de grupos","strong"]]},
  "hist":{"q":"Histórico de campanhas","opts":[["Seria a nossa primeira","first"],["Já fizemos uma ou duas","some"],["Campanhas são o nosso ritmo","rhythm"]]}},
 "felt":{"t":"As conversas que encontram você","s":"Quais destas continuam encontrando você no saguão, no e-mail, no estacionamento? Escolha até três.","cap":3,
  "opts":[["Casamentos sob tensão","marriage"],["Pressão financeira em casa","money"],["Ansiedade e esgotamento","anx"],
   ["Luto e perda","grief"],["Crianças, jovens e telas","teens"],["Dúvida e desconstrução","doubt"],
   ["Solidão e isolamento","lonely"],["Gente pronta para servir","serve"]]},
 "outcome":{"t":"A frase que importa","s":"Toda campanha deveria conseguir terminar esta frase antes de começar.",
  "lead":"Quarenta dias após o lançamento, quero que se diga da nossa igreja que…",
  "ph":"…nosso povo finalmente crê que pode confiar seu dinheiro a Deus. …ninguém se senta sozinho no domingo. Escreva a sua.",
  "fmt_q":"Duração — ou deixe o guia decidir",
  "fmt_opts":[["Deixar o guia decidir","auto"],["Um domingo catalisador","sunday"],["Desafio de 21 Dias","21"],["Jornada de 30 Dias","30"],["Jornada de 40 Dias","40"]]},
 "res":{"h":"Sua direção","total_l":"sobre 120",
  "bands":[[9,"Estação de alicerces","Isto é trabalho de solo — a campanha que serve aqui constrói o básico sem vergonha."],
   [14,"Fronteira de crescimento","Há vida real aqui, e fome real. A campanha certa transforma impulso em prática."],
   [20,"Força para enviar","Isto é uma força. Administre-a — e que financie as dimensões que ainda esperam."]],
  "low_line":"Suas duas dimensões mais baixas definem a direção. Não é má notícia — é a missão.",
  "fmt_h":"O formato do lançamento",
  "fmt_line":{"sunday":"Comece com um domingo catalisador — uma faísca antes do fogo.",
   "21":"Um Desafio de 21 Dias cabe onde você está: longo para formar hábito, curto para terminar forte na primeira vez.",
   "30":"Uma Jornada de 30 Dias dá ao mensagem um mês para ir dos cadernos aos lares.",
   "40":"Sua igreja foi feita para os 40 completos — seis semanas, igreja inteira, sem reservas."},
  "season_pre":"mirando","outcome_pre":"Você escreveu:","outcome_post":"Essa frase é a descrição de trabalho desta campanha.",
  "picks_h":"Campanhas que encontram você ali","wild_h":"E uma que você não viu chegando",
  "why":{"dim":"fala direto à sua nota de {d}","season":"feita para esta janela exata","flag":"uma campanha de destaque curada à mão",
   "felt":{"marriage":"encontra casamentos sob tensão","money":"responde à pressão financeira","anx":"feita para ansiosos e esgotados",
    "grief":"caminha com o luto","teens":"fala a crianças, jovens e telas","doubt":"honra a dúvida e as perguntas difíceis",
    "lonely":"reúne os solitários","serve":"mobiliza gente pronta para servir"}},
  "print":"Imprimir meu perfil","again":"Recomeçar"}}
