# -*- coding: utf-8 -*-
"""Authoring material for the flagship depth layer.
Every list here was written by hand for this layer — none of it is shared with the
runtime engine, so flagship prose cannot collide with engine prose. Voice rules:
no journey/unpack/lean into/season of life/do life together; concrete over abstract;
second person to the pastor, second-person-plural about the congregation."""

# ---- metaphor lexicon: title keywords → imagery domain -------------------------
# Each domain: nouns (arc material), lines (thesis imagery), first (day-one image).
METAPHORS = {
 "fire":     {"keys":["fire","flame","burn","ablaze","ignite","spark","kindle","revival","awaken","awakening"],
  "nouns":["the first spark","a tended flame","borrowed fire","the slow burn","banked coals","a shared torch"],
  "lines":["Fires are not argued into existence; they are kindled, fed, and guarded.",
   "Most churches do not lack matches. They lack someone willing to stack the wood."],
  "first":"a single match struck in a dark room"},
 "light":    {"keys":["light","lamp","shine","dawn","morning","sunrise","radiant","glow","bright"],
  "nouns":["the first light","a lamp trimmed","light on a stand","the long dawn","a lit window","light carried outdoors"],
  "lines":["Light does not compete with darkness; it simply outlasts it.",
   "A lamp is not asked to explain itself. It is asked to be lit."],
  "first":"a porch light left on for someone still out"},
 "table":    {"keys":["table","feast","bread","meal","supper","banquet","hunger","taste","fed","food"],
  "nouns":["an open seat","the longer table","bread broken slowly","a standing reservation","crumbs and abundance","the host's welcome"],
  "lines":["Every table teaches a theology: who is welcome, who serves, who is fed.",
   "The gospel has always moved at the speed of a shared meal."],
  "first":"an extra chair pulled up before the guest arrives"},
 "water":    {"keys":["water","river","rain","well","ocean","overflow","stream","flood","thirst","fountain","spring"],
  "nouns":["the deeper well","living water","the overflow","a river finding its bed","first rain on dry ground","the spring that does not fail"],
  "lines":["Thirst is not a design flaw. It is a homing signal.",
   "You cannot manufacture rain. You can dig where the water runs."],
  "first":"the first rain after a long dry summer"},
 "road":     {"keys":["road","path","way","walk","step","steps","follow","travel","pilgrim","trail","direction"],
  "nouns":["the next right step","a narrow road walked wide-eyed","the long obedience","mile markers","a companioned walk","the road home"],
  "lines":["Nobody drifts to a destination worth reaching.",
   "The road is learned by walking it, not by admiring the map."],
  "first":"lacing up shoes at the trailhead before sunrise"},
 "home":     {"keys":["home","house","dwell","room","door","welcome","family","household","belong","place"],
  "nouns":["a door left unlocked","the room prepared","foundations checked","a house that breathes","the long welcome","keys entrusted"],
  "lines":["A church is not a building people visit. It is a household people join.",
   "Every welcome we extend is rehearsal for the welcome we have received."],
  "first":"a front door opening before the knock finishes"},
 "anchor":   {"keys":["anchor","storm","steady","unshaken","firm","rock","foundation","secure","stand","strong"],
  "nouns":["the tested anchor","rock under the sand","a hold that holds","weathered rigging","the unmoved point","deep moorings"],
  "lines":["Anchors are not judged in harbors. They are judged in weather.",
   "What you are tied to is revealed by what the storm cannot move."],
  "first":"a harbor rope creaking against a rising tide"},
 "seed":     {"keys":["seed","grow","growth","harvest","fruit","root","plant","garden","vine","branch","soil","sow"],
  "nouns":["seed in honest soil","the hidden root","first fruit","a patient harvest","pruning that heals","the orchard mindset"],
  "lines":["Nothing in a garden is in a hurry, and nothing in a garden is idle.",
   "The harvest is decided months before anyone sees it."],
  "first":"a seed pressed into dark soil by a hopeful thumb"},
 "treasure": {"keys":["treasure","rich","riches","gold","pearl","inheritance","reward","worth","value","gain","fullness"],
  "nouns":["the buried field","one pearl worth everything","an audited heart","treasure that transfers","the truer ledger","riches that outlive us"],
  "lines":["Every heart keeps a ledger. This campaign reads yours out loud, kindly.",
   "What we treasure is not what we praise. It is what we protect."],
  "first":"an old key turning in a box everyone forgot"},
 "heart":    {"keys":["heart","love","beloved","desire","affection","devotion","passion","soul"],
  "nouns":["the guarded heart","first love recovered","an undivided yes","affections retrained","the softened place","a heart at home"],
  "lines":["The heart is not persuaded by information. It is won by attention.",
   "Whatever gets your best attention is quietly becoming your god."],
  "first":"a pulse felt at the wrist in a quiet room"},
 "voice":    {"keys":["voice","word","words","speak","listen","hear","call","calling","whisper","story","tell"],
  "nouns":["the listening posture","a word that lands","the quieted room","God's first language","a story retold true","the answered call"],
  "lines":["God has never had a volume problem. We have an attention problem.",
   "The Word was never meant to be skimmed. It was meant to be heard."],
  "first":"a phone set face-down so a voice can be heard"},
 "rest":     {"keys":["rest","sabbath","still","stillness","quiet","peace","slow","pause","breathe","selah","unhurried"],
  "nouns":["the practiced pause","an unhurried hour","sabbath kept badly at first","the quiet that heals","margin rebuilt","rest as trust"],
  "lines":["Rest is not the reward for finished work. It is the declaration that God works while we sleep.",
   "Hurry is not a schedule problem. It is a discipleship problem."],
  "first":"a kettle coming to boil with nowhere to be"},
 "risen":    {"keys":["risen","easter","resurrection","cross","empty","tomb","alive","victory","hope","new"],
  "nouns":["the emptied tomb","hope with scars","death rehearsing its defeat","the first Easter breath","stone-rolling faith","life that leaks out"],
  "lines":["Resurrection is not an idea to defend. It is a life to practice.",
   "Every Sunday is a small Easter, whether we notice or not."],
  "first":"morning light finding the seam of a rolled-away stone"},
 "advent":   {"keys":["advent","christmas","bethlehem","emmanuel","incarnation","manger","nativity","noel"],
  "nouns":["the lit candle","a waiting people","God in small places","the crowded inn","Emmanuel practiced","gifts rightly ordered"],
  "lines":["Advent is not the countdown to Christmas. It is training in holy waiting.",
   "God did not shout the gospel into the world. He whispered it into a manger."],
  "first":"one candle lit in a dark December kitchen"},
 "prayer":   {"keys":["pray","prayer","praying","intercede","fast","fasting","knees","altar"],
  "nouns":["the closed door","first-response prayer","an honest altar","the long ask","listening past the list","prayer as a place"],
  "lines":["Prayer is not preparation for the work. Prayer is the work.",
   "Churches do not rise above the level of their praying."],
  "first":"a kitchen chair turned into an altar at 6 a.m."},
 "kingdom":  {"keys":["kingdom","reign","king","throne","crown","rule","majesty","glory"],
  "nouns":["the upside-down kingdom","a crown of thorns first","allegiance rehearsed","the King's economy","small seeds, vast reign","citizens in exile"],
  "lines":["The kingdom does not arrive by force. It arrives by yeast and seed and secret.",
   "Every heart has a throne, and something is always on it."],
  "first":"a mustard seed lost in the lines of a palm"},
 "grace":    {"keys":["grace","mercy","forgiven","forgiveness","gospel","redeemed","redemption","freedom","free","amazing"],
  "nouns":["grace with your name on it","the debt torn up","mercy that walks first","scandalous welcome","chains rehearsed no more","the freer life"],
  "lines":["Grace is not God lowering the bar. It is God carrying you over it.",
   "Forgiven people forgive. It is the family resemblance."],
  "first":"a debt ledger fed page by page into a fire"},
 "joy":      {"keys":["joy","rejoice","gladness","celebrate","celebration","delight","happy","praise","worship","sing"],
  "nouns":["defiant joy","a rehearsed hallelujah","gladness with roots","the feast after the fast","joy that does not check the news first","songs in the second verse of life"],
  "lines":["Joy is not the absence of trouble. It is the presence of a stubborn hope.",
   "Praise is how faith breathes out."],
  "first":"laughter escaping a hospital waiting room"},
 "hope":     {"keys":["hope","promise","future","tomorrow","horizon","waiting","wait","expect"],
  "nouns":["hope with an address","the kept promise","a horizon worth walking toward","waiting made active","anchored expectation","tomorrow held loosely"],
  "lines":["Hope is not optimism. Optimism reads the odds; hope reads the promises.",
   "God's promises do not expire in transit."],
  "first":"a saved seat at a table for someone not yet arrived"},
 "battle":   {"keys":["battle","fight","war","armor","victory","overcome","enemy","stand","warfare","giants","goliath"],
  "nouns":["armor put on daily","the fight already won","giants measured against God","the stand that holds","weapons that heal","courage borrowed from heaven"],
  "lines":["The Christian fight is fought from victory, not for it.",
   "Most giants fall to a shepherd who practiced in private."],
  "first":"five smooth stones weighed in a young hand"},
 "vision":   {"keys":["vision","dream","future","build","rebuild","wall","city","arise","forward","next","launch","first"],
  "nouns":["the wall rebuilt gate by gate","a vision plain enough to run with","holy discontent","the God-sized ask","bricks and prayers together","the city on purpose"],
  "lines":["Vision is not a poster. It is a people who can finish the sentence.",
   "God-sized dreams start with an honest inventory of rubble."],
  "first":"blueprints unrolled and weighted with coffee cups"},
 "wisdom":   {"keys":["wisdom","wise","proverbs","choices","decide","decision","discern","truth","mind","think"],
  "nouns":["wisdom that walks","the counseled life","fear-of-the-Lord footing","choices compounding quietly","a renewed mind","truth with skin on"],
  "lines":["Wisdom is not knowing more. It is wanting better.",
   "Every life is an argument for whatever it believed."],
  "first":"a fork in a trail and a worn map"},
 "money":    {"keys":["money","finance","financial","budget","debt","steward","stewardship","giving","give","generous","generosity","tithe","provision","enough","contentment"],
  "nouns":["the open hand","a surrendered ledger","enough, discovered","firstfruits before leftovers","the generosity muscle","money in its place"],
  "lines":["Money makes an excellent servant and a merciless king.",
   "Generosity is not a transaction. It is a training program for trust."],
  "first":"a fist relaxing, coin by coin, into an open palm"},
 "together": {"keys":["together","community","group","groups","one","unity","belong","connect","friendship","circle","us"],
  "nouns":["chairs in a circle","the borrowed strength","tables that heal","known and kept anyway","one anothering","the unfaked welcome"],
  "lines":["Nobody was meant to carry a life alone, and nobody has to.",
   "Community is not found. It is built, on purpose, on a calendar."],
  "first":"folding chairs arranged in a circle before anyone arrives"},
 "children": {"keys":["child","children","kids","generation","generations","legacy","family","parent","parents","father","mother","grand"],
  "nouns":["faith handed down warm","the watching generation","a table of four generations","stories that outlive us","the blessing spoken aloud","arrows aimed with care"],
  "lines":["Faith is always one generation from extinction and one dinner table from renewal.",
   "Children learn what God is like from how home feels."],
  "first":"a grandfather's Bible opened by small hands"},
 "work":     {"keys":["work","job","career","calling","marketplace","monday","office","labor","business","excellence"],
  "nouns":["the desk as an altar","Monday faith","excellence as witness","integrity under deadline","work that worships","the whole-week disciple"],
  "lines":["God does not clock out of your life at nine on Monday.",
   "Your work is not the interruption of your calling. It is the address of it."],
  "first":"a laptop opened with a thirty-second prayer"},
 "heal":     {"keys":["heal","healing","whole","wholeness","broken","mend","restore","comfort","grief","tears","wounds"],
  "nouns":["the binding of wounds","grief given a chair","healing at its own pace","the God of the broken places","comfort that transfers","scars that testify"],
  "lines":["God does not waste wounds. He redeems them slowly and thoroughly.",
   "Healing is rarely a moment. It is usually a direction."],
  "first":"stitches doing their quiet work under a bandage"},
 "identity": {"keys":["identity","name","named","beloved","chosen","child","son","daughter","who","made","image"],
  "nouns":["the truer name","belovedness practiced","the mirror corrected","performance retired","adoption papers signed","who you already are"],
  "lines":["You cannot out-perform a verdict God has already rendered.",
   "Identity is not achieved. It is received, and then lived into."],
  "first":"a name spoken across a crowded room, and a head turning"},
 "doubt":    {"keys":["doubt","question","questions","honest","wrestle","wrestling","faith","believe","belief","skeptic"],
  "nouns":["questions asked out loud","the wrestle that blesses","faith with a limp","scars offered to Thomas","room to not know","belief helped along"],
  "lines":["Doubt is not the opposite of faith. Certainty without love is.",
   "Jesus has never once been scared of a sincere question."],
  "first":"a hand reaching toward scars it needs to touch"},
 "digital":  {"keys":["digital","screen","screens","phone","online","scroll","attention","technology","ai","device"],
  "nouns":["attention reclaimed","the phone in its place","a guarded gate","presence over pixels","the undistracted table","eyes lifted"],
  "lines":["The most contested real estate on earth is your attention.",
   "Whoever forms your attention forms your soul."],
  "first":"a phone face-down at a dinner table, screen dark"},
}

# ---- per-channel pastoral case (fresh; not shared with engine) -----------------
CASES = [
 "Purpose is the question under every other question your people are asking; a church that answers it churchwide changes its own weather.",
 "Half your congregation is performing for a verdict God already rendered; settle identity and watch a dozen other struggles quiet down.",
 "Attendance can hide isolation for years; belonging has to be built on purpose, on a calendar, with names attached.",
 "Prayer is the first thing every church affirms and the last thing most schedule; a praying church is decided in its calendar, not its statements.",
 "Money is discipled somewhere — by advertisers if not by Scripture; the church that breaks the silence gains the whole household's trust.",
 "Generosity is caught before it is taught; a congregation that practices open hands together learns trust no sermon alone can produce.",
 "Every family in your church is handing something down; this campaign makes the handoff deliberate instead of accidental.",
 "Marriages rarely fail loudly at first; they drift quietly, and a churchwide season of tending them reverses the drift before the crisis.",
 "Parents feel outgunned and outnumbered; equip the home and you multiply every hour the church ever gets with a child.",
 "The anxious and grieving are already in your pews, deciding quietly whether church helps; this campaign answers them out loud.",
 "Bodies wear out and caregivers wear thin; a church that honors limits ministers to the exhausted majority nobody schedules for.",
 "Private battles thrive on silence; a whole church walking into the light together lowers the cost of honesty for everyone.",
 "Transitions are where faith either deepens or quietly leaks away; meeting a change season head-on keeps your people from navigating it alone.",
 "Your people spend most of their waking lives at work; connect Sunday to Monday and the church shows up everywhere your city does business.",
 "Leaders burn out privately long before it shows publicly; a church that develops and guards its leaders never runs short of them.",
 "A vision lives or dies by whether the congregation can finish the sentence; a churchwide season makes the vision everyone's sentence.",
 "Ministries run on volunteers who need more than a schedule; give them a shared formation season and recruiting becomes commissioning.",
 "Your neighborhood will not read a statement of faith, but it will read forty days of your people's changed behavior.",
 "The calendar already gives you the moment; a campaign built for the season turns cultural attention into spiritual formation.",
 "The words of Jesus are widely quoted and rarely obeyed at scale; a red-letter season closes the gap between admiration and following.",
 "Bible ownership is not Bible engagement; a church reading the same words daily becomes a church with a shared vocabulary for its life.",
 "The doubters in your church are not leaving because they doubt; they leave when doubt has nowhere honest to go.",
 "Attention is the discipleship battleground of this decade; a church that trains it together reclaims its people's souls from the scroll.",
]

# ---- frame pools ----------------------------------------------------------------
THESIS_OPEN = [
 "“{title}” is not a slogan for your bulletin — it is a season with a job to do.",
 "Some campaigns inform a church. “{title}” is built to change one.",
 "There is a reason “{title}” names this campaign: it is the one thing your church cannot delegate.",
 "“{title}” begins where most series end — with the assumption that something must actually change.",
 "Behind the words “{title}” sits a conviction: {line0}",
 "“{title}” was built on a simple wager: {line0}",
 "Start with the image at the center of “{title}”: {first}. Hold it — the whole campaign lives there.",
 "Every church needs a season it can point back to. “{title}” is designed to be that season.",
]
THESIS_MID = [
 "Over {weeks} weeks, the whole church — platform, groups, homes — moves through one arc together, from invitation to commissioning, anchored in {ref}.",
 "For {weeks} weeks, sermons, groups, and daily readings pull in one direction, with {ref} as the backbone text the whole church learns by heart.",
 "The design is deliberately churchwide: {weeks} weeks where the sermon, the small group question, and the kitchen-table conversation are finally the same conversation, grounded in {ref}.",
 "It runs {weeks} weeks, whole-church: one text ({ref}), one arc, every generation reading the same words on the same days.",
]
THESIS_CASE = list(range(23))  # placeholder — resolved to CASES[ch] at build
THESIS_CLOSE = [
 "By the final Sunday, the goal is not that your people finished a study, but that they kept {noun} — and know it.",
 "The finish line is visible change: {noun}, practiced long enough to survive the campaign's end.",
 "Success is measurable on purpose: stories captured, a next step named, and {noun} still standing ninety days later.",
 "The campaign ends with commissioning, not applause — sending your people out with {noun} in hand.",
 "When it works — and it is built to — the lasting artifact is {noun}, owned by the whole church.",
]
WEEK_FRAMES = [  # (phase 0..4 index guides tone); {n}=metaphor noun, {N}=capitalized
 ["The Invitation to {n}","Why {N} Now","Opening the Door to {n}","The Case for {n}"],
 ["The Ground Under {n}","What {N} Requires","Foundations of {n}","Learning {n} Slowly"],
 ["Practicing {n}","{N} on a Tuesday","The Daily Shape of {n}","{N} in Ordinary Time"],
 ["When {N} Gets Tested","Keeping {n} in the Storm","The Cost of {n}","{N} Against Resistance"],
 ["Sent with {n}","{N} That Outlives the Campaign","Carrying {n} Home","The Commissioning of {n}"],
 ["{N}, Together","The Church That Keeps {n}","{N} for the Sake of Others","Handing {n} On"],
]
SERMON_FRAMES = [
 "The {N} You Were Promised","Where {N} Begins","{N} Under Pressure","The Economics of {n}",
 "What {N} Costs and Pays","{N} for the Long Haul","The People of {n}","{N} Goes Public",
 "When {N} Feels Impossible","The Quiet Power of {n}","{N} at Home","Sending {N} Out",
]
DAY1_WELCOME = [
 "Welcome to day one of “{title}.” Before anything is asked of you, hear the invitation plainly: for the next {days} days, your whole church is reading these same words — the platform, the small groups, the kitchen tables. You are not starting a program. You are joining a company.",
 "This is the first day of “{title},” and the bar is deliberately low: ten minutes, one passage, one honest step. The power is not in any single day. It is in a whole church doing small things in the same direction for {days} days.",
 "“{title}” starts here, and it starts small on purpose. Grand beginnings burn out; ten faithful minutes compound. Today your only assignment is to show up — and to know that hundreds of others in your church are showing up to the same page.",
 "Day one of “{title}.” Every campaign is a wager that {days} days of shared attention can do what years of good intentions have not. Your part today is modest: read, sit still for one minute, take one step.",
]
DAY1_VERSE = [
 "Start with the anchor text your church will return to all season — {ref}. Read it twice, slower the second time. Its claim is direct: {promise}. Do not rush past that sentence; the entire campaign is that sentence learning to walk in your church.",
 "The backbone of this whole campaign is {ref}, and its claim could not be plainer: {promise}. Everything the next {days} days ask of you assumes that sentence is true — today is for deciding whether you will let it be true of you.",
 "Open to {ref} and read it aloud if you can. Here is what it says without decoration: {promise}. Churches drift when verses like this stay framed on walls; campaigns exist to take them off the wall.",
 "Your church's text for this season is {ref}. Strip it to one sentence: {promise}. Write that sentence somewhere you will see it daily — mirror, dashboard, lock screen — because {days} days from now it should read like a family motto, not a caption.",
]
DAY1_STEP = [
 "Today's step: text one person these exact words — “I'm starting {title} today. Check on me at the end of week one.” That text is your first act of the campaign, and it makes quitting quietly impossible.",
 "One step before the day ends: decide your slot. Same time, same chair, phone in another room, ten minutes. Formation is mostly scheduling; put it on the calendar now, all {days} days.",
 "Your step today is an image: picture {first}. Then do the small version — tell one person you are in, and ask them to be your check-in partner for the next {weeks} weeks.",
 "Before tonight: write one sentence — what would make these {days} days worth it to you? Keep it. On the final day, this campaign will hand that sentence back to you and ask what happened.",
]
DAY1_PRAY = [
 "Father, I am beginning something my whole church is beginning with me. I bring You an honest heart, not an impressive one. Meet me in these {days} days, and do in our church what none of us can schedule. Amen.",
 "Lord, You know how many things I have started and quietly abandoned. Not this one. Give me ten faithful minutes a day, a person to walk with, and eyes to see what You are doing in the whole church around me. Amen.",
 "God, thank You that {promise2}. I am staking the next {days} days on it. Guard my slot, soften my heart, and let my house feel the difference before my mouth explains it. Amen.",
 "Spirit of God, campaigns do not change churches — You do, and You are pleased to use campaigns. Use this one. Start with me, today, in the next ten minutes. Amen.",
]
LAUNCH_NOTE = [
 "Pastor: the campaigns that change churches are the ones the pastor visibly runs first. Read day one before you announce it, tell your own story on launch Sunday, and name the finish line out loud. {case}",
 "A note before launch: do not announce this cold. Give it a runway Sunday, recruit hosts by name, and put the campaign's one sentence on everything for {weeks} weeks. {case}",
 "For the launch: this works when the platform, the groups, and the homes hear one voice. Preach the arc, hand every household the daily readings, and protect the final Sunday for stories. {case}",
 "Before you schedule this: pick the window, then work backward — three weeks of runway, hosts recruited two Sundays out, and a commissioning Sunday nobody schedules over. {case}",
]
