# -*- coding: utf-8 -*-
# Annual Catalytic Sunday calendar map.
# Note: searched past conversations for Brett's original calendar map and could not
# locate a standalone file under that name — only a passing mention of "calendar locks:
# Easter, Christmas/Advent, Mother's Day, and the annual At the Movies outreach series"
# inside the Preaching Forecast research. This map is rebuilt fresh, in full, below.

CALENDAR_MAP = [
    ("Early January", "New Year's Sunday", "New Beginnings & Fresh Starts",
     "The Sunday on What God Is Doing Next",
     "The single highest-attendance 'fresh start' Sunday of the year outside Easter. Pair with a vision-casting message and the launch of a January 40-day or 30-day campaign."),
    ("Mid-January", "Vision Sunday", "Kingdom Living & Impact",
     "The Kingdom Vision Sunday",
     "Many churches' highest-stakes Sunday — casting the year's direction. Strong pairing with a capital campaign or new-initiative launch."),
    ("Early February", "Super Bowl Sunday", "Community & Unity",
     "The Belonging Sunday",
     "Cultural moment, not liturgical — some churches lean into a watch-party outreach angle; others simply keep it low-key and light."),
    ("Mid-February", "Marriage & Relationships Sunday (Valentine's)", "Family, Marriage & Parenting",
     "The Marriage Sunday",
     "Natural anchor for launching a marriage-focused 40-day, 30-day, or 21-day series the following week."),
    ("February/March", "Ash Wednesday & First Sunday of Lent", "Surrender & Total Trust",
     "The Surrender Sunday",
     "Opens the Lenten season — strong anchor for a Surrender, Grief, or Renewal series running through to Easter."),
    ("Late March/April", "Palm Sunday", "Christ-Centered & Biblical Living",
     "The King Who Came Anyway Sunday",
     "The Sunday before Easter — triumphal entry, strong bridge into Holy Week and Easter."),
    ("March/April", "Easter Sunday", "Renewal & Spiritual Awakening",
     "The Resurrection Sunday",
     "The single biggest Sunday of the church year, nearly everywhere. Every campaign format in this library should have an Easter-week on-ramp ready — this is the highest-traffic guest Sunday of the year."),
    ("Early May", "National Day of Prayer Sunday", "Prayer & Intimacy with God",
     "The Nation at Prayer Sunday",
     "Lower-key civic-adjacent Sunday; strong for launching a prayer-focused 7-day or 21-day experience."),
    ("Second Sunday of May", "Mother's Day", "Family, Marriage & Parenting",
     "The Honor Your Mother Sunday",
     "One of the top 3 highest-attendance Sundays of the year. Handle grief and complicated-family-history pastorally — never assume every mother in the room is celebrating."),
    ("Late May", "Graduation Sunday", "Identity: Who You Are in Christ",
     "The Sent Out Sunday",
     "Strong for a graduating-seniors commissioning moment layered into the regular service; pairs with the Purpose & Calling category."),
    ("Last Monday-adjacent Sunday of May", "Memorial Day Sunday", "Legacy & Generational Faith",
     "The Sunday of Remembrance and Gratitude",
     "Honors those who died in service; pastorally distinct from Veterans Day (which honors the living). Keep gratitude and legacy at the center, not politics."),
    ("Mid-June", "Father's Day", "Family, Marriage & Parenting",
     "The Honor Your Father Sunday",
     "Second only to Mother's Day and Easter in many churches. Same pastoral caution: absent, difficult, or deceased fathers are in every room."),
    ("Sunday nearest July 4th", "Independence Day Sunday", "Freedom & Breakthrough",
     "The True Freedom Sunday",
     "Civic and spiritual freedom themes overlap naturally here — keep the gospel freedom message primary."),
    ("Late August/Early September", "Back-to-School Sunday", "New Beginnings & Fresh Starts",
     "The Fresh Start Sunday",
     "Strong for a teacher/student commissioning and the fall semester's first-series launch — often the unofficial start of the church program year."),
    ("First Monday-adjacent Sunday of September", "Labor Day Sunday", "Purpose & Calling",
     "The Faith at Work Sunday",
     "Natural tie-in to the Purpose Driven Business / marketplace-ministry content ladder."),
    ("September 11-adjacent Sunday", "Remembrance Sunday", "Hope",
     "The Hope After Hard Things Sunday",
     "Handle with care — national tragedy remembrance, not a theology lecture. Brief, honoring, hope-forward."),
    ("Second Sunday of September", "Grandparents Day Sunday", "Legacy & Generational Faith",
     "The Wisdom to Offer Sunday",
     "Strong pairing with the Legacy & Generational Faith category's flagship title."),
    ("First Sunday of October", "World Communion / Global Church Sunday", "Community & Unity",
     "The One Body, One Table Sunday",
     "Strong for casting a global-church, missions-minded vision alongside the Lord's Table."),
    ("Mid-October", "Pastor Appreciation Sunday", "Leadership & Influence",
     "The Shepherd's Heart Sunday",
     "Internal, congregation-facing — a Sunday to honor pastoral staff, not a public campaign moment."),
    ("Early November", "All Saints / Remembrance Sunday", "Grief, Suffering & Hard Seasons",
     "The Held in Loss Sunday",
     "Strong for a congregation-wide moment naming those lost in the past year — pairs naturally with the Grief & Hard Seasons category."),
    ("Sunday nearest Veterans Day", "Veterans Day Sunday", "Courage & Boldness",
     "The Courage to Serve Sunday",
     "Honors the living who served — distinct from Memorial Day. Strong Courage & Boldness category tie-in."),
    ("Sunday before Thanksgiving", "Thanksgiving Sunday", "Joy & Gratitude",
     "The Gratitude Sunday",
     "One of the most naturally joyful, easy-invite Sundays of the year — strong pairing with a Joy & Gratitude series launch the following week."),
    ("Last Sunday of November / First of Advent", "First Sunday of Advent", "Hope",
     "The Waiting for Hope Sunday",
     "Opens the four-week Advent arc; pairs with a Hope-category series running through Christmas."),
    ("December Sundays", "Advent Series (4 Sundays)", "Hope",
     "Hope, Peace, Joy, and Love Sundays",
     "The classic four-Sunday Advent candle progression — one Sunday per theme, closing on Christmas Eve or Christmas Sunday."),
    ("December 24/25", "Christmas Eve / Christmas Sunday", "Joy & Gratitude",
     "The Long-Awaited Sunday",
     "Second only to Easter for guest attendance in most churches — treat with the same production and follow-up planning as Easter."),
    ("December 31 / January 1", "Watch Night / New Year's Eve Sunday", "New Beginnings & Fresh Starts",
     "The Threshold Sunday",
     "Closes the old year, opens the door to the January launch — natural bridge back to the top of this calendar."),
]
