# -*- coding: utf-8 -*-
# Master 40-Day Campaign Library — LifeTogether
# 30 categories x 20 titles = 600 churchwide, all-ages, weekend-driven campaign titles

PALETTE = ["navy", "forest", "plum", "olive", "teal", "umber"]

NAMING_FORMULAS = [
    ("Direct", "40 Days of [Theme]", "The classic. Clear, punchy, easy to put on a banner."),
    ("Journey", "The 40-Day [Theme] Journey", "Frames the series as a path walked together, not a topic list."),
    ("Promise", "[Emotional Hook]: A 40-Day Journey to [Theme]", "Leads with the felt need, then delivers the 40-day promise."),
    ("Single-Word", "[One Word]: A 40-Day Journey to [Outcome]", "A one-word anchor plus a colon promise — premium, book-cover feel."),
    ("Experience", "The 40-Day [Theme] Experience / Challenge / Adventure", "Signals participation and momentum — strong for launch Sundays."),
]

CATEGORIES = []

def cat(roman, name, tag, tagline, description, flagship, titles):
    CATEGORIES.append({
        "roman": roman, "name": name, "tag": tag, "tagline": tagline,
        "description": description, "flagship": flagship, "titles": titles
    })

# ============================================================
# CORE 20 — drawn and consolidated from the existing library
# ============================================================

cat("I", "Purpose & Calling", "Foundational",
    "Why am I here?",
    "The entry-point category for any church — the felt need underneath every other series. Works for a first-time guest and a forty-year member alike.",
    [("Direct","40 Days of Purpose"),("Journey","The 40-Day Purpose Journey"),
     ("Promise","Life on Purpose: A 40-Day Journey to Meaningful Living"),
     ("Single-Word","Called: A 40-Day Journey to Discover Your Assignment")],
    [
        ("40 Days of Purpose","Direct","The evergreen flagship; still the most requested churchwide series in America"),
        ("The 40-Day Purpose Journey","Journey","Same promise, journey framing for a repeat-campaign year"),
        ("Life on Purpose: A 40-Day Journey to Meaningful Living","Promise","Softer entry point for guests wary of a 'purpose' cliché"),
        ("Called: A 40-Day Journey to Discover Your Assignment","Single-Word","Premium cover-style title for a print/leader-guide launch"),
        ("40 Days of Discovering Your Calling","Direct","Pairs well with a spiritual gifts assessment week"),
        ("The 40-Day Calling Discovery","Experience","Good subtitle for a vocational/marketplace-leaning version"),
        ("Made for More: A 40-Day Journey to Purpose and Passion","Promise","Strong youth/young-adult crossover energy"),
        ("40 Days to a Life That Matters","Direct","Legacy-adjacent close to a purpose series"),
        ("The Purpose Path: A 40-Day Journey to Clarity and Calling","Journey","Good for a new-year clarity-and-goals launch"),
        ("40 Days to Discover the Life You Were Made For","Direct","Strongest closing-week title for a purpose arc"),
        ("Finding Your Mission: A 40-Day Journey","Promise","Pair with local outreach commitments in week 6"),
        ("40 Days of Discovering Your Mission","Direct","Companion series to Evangelism & Mission category"),
        ("Uncommon Life: A 40-Day Journey to Kingdom Living","Single-Word","Bridges Purpose into Kingdom Living category"),
        ("40 Days of Living on Purpose","Direct","Daily-habit framing rather than one big decision"),
        ("The Purpose-Driven Life Plan: A 40-Day Journey","Experience","Direct nod to the founding Purpose Driven framework"),
        ("40 Days of Becoming More","Direct","Identity-adjacent purpose framing"),
        ("Reclaiming Your Purpose: A 40-Day Journey","Promise","Strong for a post-crisis or rebuild-season church calendar"),
        ("40 Days of Rediscovering Your Purpose","Direct","For congregations coming off a hard season"),
        ("The 40-Day Assignment: Finding What You're Made For","Experience","Marketplace/workplace-leaning purpose variant"),
        ("Made for This: A 40-Day Journey to Your God-Given Purpose","Promise","Strong graphic-driven title, reads well on a sermon bumper"),
    ])

cat("II", "Faith & Trust", "Foundational",
    "Believing bigger.",
    "The category every pastor returns to — building or rebuilding confidence in God's character. Works equally for new believers and seasoned members.",
    [("Direct","40 Days of Faith"),("Journey","The 40-Day Faith Challenge"),
     ("Promise","The Trust Adventure: A 40-Day Journey to Letting God Lead"),
     ("Single-Word","Anchored: A 40-Day Journey to Unshakable Faith")],
    [
        ("40 Days of Faith","Direct","The single most reused campaign word in the library"),
        ("The 40-Day Faith Challenge","Experience","Good for a step-of-faith giving or mission-commitment close"),
        ("40 Days of Deep Faith","Direct","Discipleship-leaning, for a returning-congregation second run"),
        ("Anchored: A 40-Day Journey to Unshakable Faith","Single-Word","Strong storm/crisis-season title"),
        ("40 Days of Radical Faith","Direct","High-energy title for a youth-adjacent all-ages launch"),
        ("The Courage to Trust: A 40-Day Journey through Life's Unknowns","Promise","Pairs faith with courage for a transition-season church"),
        ("40 Days of Building Lasting Faith","Direct","Foundations series for a new-members season"),
        ("Unwavering: A 40-Day Journey to Faithfulness in Every Season","Single-Word","Strong for a multi-generational, long-tenure congregation"),
        ("40 Days of Faith Over Fear","Direct","Crosses well into the Anxiety & Emotional Wellness category"),
        ("The Trust Adventure: A 40-Day Journey to Letting God Lead","Promise","Best for a leadership-transition or vision-casting season"),
        ("40 Days of Walking by Faith","Direct","Classic 2 Corinthians 5:7 framing"),
        ("Deeply Rooted: A 40-Day Journey to Lasting Faith","Single-Word","Pairs with a tree/roots visual campaign theme"),
        ("40 Days of Faith that Changes Everything","Direct","Strong closing-series title, high emotional payoff"),
        ("The Surrendered Life: A 40-Day Journey to Total Trust","Promise","Bridges into Surrender & Total Trust category"),
        ("40 Days of Strengthening Your Faith","Direct","Good mid-year 'tune-up' series"),
        ("Rooted: A 40-Day Journey to Spiritual Depth and Stability","Single-Word","Foundations series, strong visual branding potential"),
        ("40 Days of Living by Faith","Direct","Everyday-obedience framing rather than crisis framing"),
        ("The 40-Day Faith Reset","Experience","Good post-holiday or new-year restart series"),
        ("40 Days of Believing Bigger","Direct","High-energy vision-Sunday opener"),
        ("Faith That Moves: A 40-Day Journey to Courageous Obedience","Promise","Strong for a step-of-obedience giving or mission campaign"),
    ])

cat("III", "Hope", "Foundational",
    "Hope that holds.",
    "One of the shortest paths from a hurting guest to a hopeful next step — hope series consistently outperform for first-time visitors.",
    [("Direct","40 Days of Hope"),("Journey","The 40-Day Hope Project"),
     ("Promise","Hope Rising: A 40-Day Journey through Fear, Loss, and Uncertainty"),
     ("Single-Word","Restored: A 40-Day Journey to Renewed Hope")],
    [
        ("40 Days of Hope","Direct","The flagship — works in any season, any size church"),
        ("The 40-Day Hope Project","Experience","Good for a church-and-community outreach hybrid campaign"),
        ("40 Days of Restored Hope","Direct","Post-crisis or post-loss congregational season"),
        ("Hope Rising: A 40-Day Journey through Fear, Loss, and Uncertainty","Promise","Strongest title for a genuinely hard congregational season"),
        ("40 Days of Hope for Today","Direct","Simple, warm, works across every age group"),
        ("40 Days of Unshakable Hope","Direct","Pairs well with an Anchored/Faith series as a two-part year"),
        ("40 Days of Abiding Hope","Direct","Quieter, contemplative framing — good for Lent timing"),
        ("Restored: A 40-Day Journey to Renewed Hope","Single-Word","Premium cover title, strong for a hardcover devotional release"),
        ("40 Days of Hope for Hurting Hearts","Direct","Grief-adjacent; consider cross-listing with that category"),
        ("The 40-Day Hope Reset","Experience","New Year or post-holiday-season opener"),
        ("40 Days of Hope for Families","Direct","Strong all-ages crossover with the Family category"),
        ("Never Without Hope: A 40-Day Journey","Promise","Strong closing-week tagline for a hope series finale"),
        ("40 Days of Rediscovering Joy and Hope","Direct","Bridges Hope with the Joy & Gratitude category"),
        ("The Hope Adventure: A 40-Day Journey Forward","Experience","Momentum-building series for a growth-season church"),
        ("40 Days of Hope in Hard Times","Direct","Direct, honest naming for a season of real hardship"),
        ("Anchored in Hope: A 40-Day Journey","Single-Word","Nautical/storm visual theme option"),
        ("40 Days of Hope that Doesn't Disappoint","Direct","Romans 5:5 framing"),
        ("A Reason for Hope: 40 Days to Renewed Confidence","Promise","Apologetics-adjacent, good for a skeptic-friendly series"),
        ("40 Days of Living Hope","Direct","1 Peter 1:3 framing, strong for Easter season"),
        ("The 40-Day Hope Journey: From Surviving to Thriving","Journey","Strong for a recovery-season or post-crisis congregation"),
    ])

cat("IV", "Freedom & Breakthrough", "Foundational",
    "Break every chain.",
    "High-energy category built around momentum and decision — strong for a spring or fall kickoff series with a clear 'before and after.'",
    [("Direct","40 Days of Freedom"),("Journey","The 40-Day Freedom Path"),
     ("Promise","Living Light: A 40-Day Journey to Freedom from Anxiety"),
     ("Single-Word","Unshackled: A 40-Day Journey to True Freedom")],
    [
        ("40 Days of Freedom","Direct","The flagship — pairs naturally with a baptism Sunday close"),
        ("The 40-Day Freedom Path: 40 Days to Peace, Margin, and Simplicity","Journey","Best for a burned-out, overcommitted congregation"),
        ("40 Days of Breakthrough","Direct","High-momentum opener, strong graphic potential"),
        ("40 Days of Breakthrough Prayer","Direct","Prayer-and-freedom hybrid; pairs with the Prayer category"),
        ("Living Light: A 40-Day Journey to Freedom from Anxiety","Promise","Strong crossover with Anxiety & Emotional Wellness"),
        ("40 Days of Living Free","Direct","Simple, singable, works as a sermon series title and song"),
        ("40 Days of Walking in Freedom","Direct","Galatians 5:1 framing"),
        ("Unshackled: A 40-Day Journey to True Freedom","Single-Word","Premium cover title, strong for a recovery ministry tie-in"),
        ("40 Days of Freedom from Anxiety","Direct","Direct, searchable title for a mental-health-aware season"),
        ("The 40-Day Breakthrough Experience","Experience","Momentum series for a growth or building season"),
        ("40 Days to Change Your World","Direct","Outward-facing close to a freedom/breakthrough series"),
        ("40 Days of Kingdom Breakthrough","Direct","Bridges into Kingdom Living category"),
        ("Set Free: A 40-Day Journey Out of What's Holding You Back","Promise","Strong for a series addressing habitual sin or addiction"),
        ("40 Days of Radical Trust","Direct","Faith-and-freedom crossover"),
        ("The Freedom Adventure: 40 Days to a Life Unbound","Experience","High-energy all-ages launch title"),
        ("40 Days of Faith and Freedom","Direct","Pairs two flagship themes into one series"),
        ("Breakthrough: A 40-Day Journey from Stuck to Sent","Single-Word","Strong for a vision-and-mission-season closer"),
        ("40 Days of Overcoming","Direct","Simple, broad, works for almost any obstacle-season series"),
        ("The 40-Day Reset: Breaking Old Patterns, Building New Ones","Experience","New Year or habit-formation framing"),
        ("40 Days of Living Beyond Yourself","Direct","Freedom-from-self-focus framing, bridges into Serving category"),
    ])

cat("V", "Prayer & Intimacy with God", "Foundational",
    "Learning to listen.",
    "The habit-formation category — best paired with a 21-day on-ramp before the full 40-day arc, per the shorter-format ladder above.",
    [("Direct","40 Days of Prayer"),("Journey","The 40-Day Prayer Adventure"),
     ("Promise","Whispers of the Spirit: A 40-Day Guide to Intimate Prayer"),
     ("Single-Word","Abiding: A 40-Day Journey of Prayer")],
    [
        ("40 Days of Prayer","Direct","The most requested churchwide prayer series, any denomination"),
        ("The 40-Day Prayer Adventure","Experience","Family-friendly framing for an all-ages prayer emphasis"),
        ("40 Days of Purposeful Prayer","Direct","Habit-formation framing, strong with a printed prayer journal"),
        ("40 Days of Breakthrough Prayer","Direct","Crosses with Freedom & Breakthrough category"),
        ("Whispers of the Spirit: A 40-Day Guide to Intimate Prayer","Promise","Contemplative, strong for a Lent-season timing"),
        ("40 Days of Walking with God","Direct","Broader spiritual-formation framing beyond prayer alone"),
        ("40 Days of Hearing God's Voice","Direct","Discernment-adjacent; strong small-group discussion hook"),
        ("Abiding: A 40-Day Journey of Prayer","Single-Word","John 15 framing, quiet premium cover title"),
        ("40 Days of Experiencing God","Direct","Classic Blackaby-adjacent framing, strong with older congregations"),
        ("40 Days of Becoming Spirit-Led","Direct","Pairs prayer with everyday Spirit-guided decision making"),
        ("The 40-Day Prayer Reset","Experience","Good for a New Year spiritual-disciplines launch"),
        ("40 Days of Kingdom Vision","Direct","Prayer-and-vision hybrid for a planning-season church"),
        ("Daily Liturgy: 40 Days of Worship and Prayer","Promise","Structured, thematic — strong for a print devotional release"),
        ("40 Days of Following God Daily","Direct","Everyday-obedience framing, broad all-ages appeal"),
        ("The Listening Life: A 40-Day Journey in Prayer","Promise","Contemplative framing, strong for a quieter season"),
        ("40 Days of Praying Like Jesus","Direct","Lord's Prayer-based structure across six weeks"),
        ("40 Days of Spiritual Confidence","Direct","Prayer-and-boldness hybrid, bridges Courage category"),
        ("In the Presence of Jesus: A 40-Day Devotional","Promise","Strong existing-title precedent in the wider devotional market"),
        ("40 Days of Constant Conversation","Direct","Brother Lawrence-adjacent, practicing-the-presence framing"),
        ("The 40-Day Prayer Journey: From Routine to Relationship","Journey","Strong for a congregation naming prayer fatigue or dryness"),
    ])

cat("VI", "Grace, Peace & Rest", "Foundational",
    "Enough, already.",
    "Anti-hustle category that consistently resonates with overcommitted, burned-out congregations — a natural summer or post-holiday series.",
    [("Direct","40 Days of Peace"),("Journey","The 40-Day Peace Journey"),
     ("Promise","Cast Your Cares: A 40-Day Journey to Rest for Your Soul"),
     ("Single-Word","Unhurried: A 40-Day Journey to Rest")],
    [
        ("40 Days of Peace","Direct","The flagship; works in nearly any season"),
        ("The 40-Day Peace Journey","Journey","Second-run framing for a repeat peace series"),
        ("40 Days of Grace and Truth","Direct","John 1:14 framing, foundational gospel series"),
        ("Cast Your Cares: A 40-Day Journey to Rest for Your Soul","Promise","Strong market precedent, proven title formula"),
        ("40 Days of Rest","Direct","Simple, restorative, ideal for a summer sabbath series"),
        ("40 Days of Renewal and Rest","Direct","Pairs rest with the broader Renewal category"),
        ("Unhurried: A 40-Day Journey to Rest","Single-Word","Premium cover title for a burnout-aware congregation"),
        ("40 Days of Living with Margin","Direct","Practical, calendar-and-schedule framing"),
        ("40 Days of Living in Grace","Direct","Foundational gospel-of-grace series"),
        ("The 40-Day Grace Adventure","Experience","Lighter, more celebratory grace framing"),
        ("40 Days of Overflow","Direct","Abundance-and-rest hybrid, bridges Stewardship category"),
        ("Grace for the Journey: A 40-Day Path to Healing and Renewal","Promise","Strong for a congregation coming out of a hard year"),
        ("40 Days of Finding Peace","Direct","Anxiety-adjacent peace framing"),
        ("40 Days of Living with Gratitude","Direct","Peace-through-thankfulness framing; crosses Joy category"),
        ("The Sabbath Reset: A 40-Day Journey to Rest and Rhythm","Promise","Strong for a rhythms-and-margin teaching series"),
        ("40 Days of Peace That Passes Understanding","Direct","Philippians 4:7 framing"),
        ("Still: A 40-Day Journey to Quiet Confidence","Single-Word","Psalm 46:10 framing, contemplative cover title"),
        ("40 Days of Grace Upon Grace","Direct","John 1:16 framing, second-year grace series"),
        ("The 40-Day Rest and Renewal Journey","Journey","Combined title for a two-theme summer series"),
        ("40 Days of Everyday Peace","Direct","Practical, non-crisis framing for ordinary time"),
    ])

cat("VII", "Wisdom & Discernment", "Foundational",
    "Living smart.",
    "Practical, decision-focused series — strong for graduation season, new-year planning, or any teaching arc built around Proverbs.",
    [("Direct","40 Days of Wisdom"),("Journey","The 40-Day Wisdom Journey"),
     ("Promise","Powerful Self-Talk from the Psalms: 40 Days to a Biblical Mindset"),
     ("Single-Word","Discerning: A 40-Day Journey to Wisdom for Real Life")],
    [
        ("40 Days of Wisdom","Direct","The flagship, strong pairing with a Proverbs teaching arc"),
        ("The 40-Day Wisdom Journey","Journey","Second-run or small-group companion framing"),
        ("40 Days of Pursuing Wisdom","Direct","Active-pursuit framing, strong for a student ministry crossover"),
        ("40 Days of Growing in Wisdom","Direct","Everyday-formation framing rather than crisis-decision framing"),
        ("Powerful Self-Talk from the Psalms: 40 Days to a Biblical Mindset","Promise","Mental-renewal framing, crosses into Emotional Wellness"),
        ("40 Days of Kingdom Wisdom","Direct","Bridges Wisdom into the Kingdom Living category"),
        ("Discerning: A 40-Day Journey to Wisdom for Real Life","Single-Word","Premium cover title for a decision-season launch"),
        ("40 Days to a Biblical Mindset","Direct","Renewing-the-mind framing, Romans 12:2"),
        ("The Wisdom Path: 40 Days to Clearer Decisions","Journey","Practical, decision-focused series for graduates or career changers"),
        ("40 Days of Discernment for a Noisy World","Direct","Strong crossover with Digital Discernment category"),
        ("Ancient Wisdom, Modern Life: A 40-Day Journey","Promise","Strong for a Proverbs-through-culture teaching series"),
        ("40 Days of Choosing Well","Direct","Simple, decision-focused, all-ages friendly"),
        ("The Proverbs Project: 40 Days of Everyday Wisdom","Experience","Structured devotional format, one proverb per day"),
        ("40 Days of Wisdom for the Wandering","Direct","Strong for a season addressing cultural confusion"),
        ("Clear-Eyed: A 40-Day Journey to Discernment","Single-Word","Contemporary cover title, strong minimalist branding"),
        ("40 Days of Wisdom for Families","Direct","All-ages crossover with the Family category"),
        ("The 40-Day Wisdom Reset","Experience","New Year decision-making and goal-setting series"),
        ("40 Days of Thinking Rightly","Direct","Mind-renewal framing, philosophically grounded teaching arc"),
        ("Solomon's Path: 40 Days in the Wisdom Books","Journey","Strong expository series through Proverbs/Ecclesiastes"),
        ("40 Days of Wisdom Over Noise","Direct","Cultural-discernment framing for an information-overload season"),
    ])

cat("VIII", "Courage & Boldness", "Foundational",
    "Brave enough to obey.",
    "High-energy, decision-forward series — strong for a missions-launch Sunday or a season calling the church to a specific step.",
    [("Direct","40 Days of Courage"),("Journey","The 40-Day Courage Challenge"),
     ("Promise","The Courage to Trust: A 40-Day Journey through Life's Unknowns"),
     ("Single-Word","Bold: A 40-Day Journey to Fearless Faith")],
    [
        ("40 Days of Courage","Direct","The flagship, strong for any decision-forward season"),
        ("The 40-Day Courage Challenge","Experience","Momentum series, strong graphic and t-shirt potential"),
        ("40 Days of Courageous Faith","Direct","Faith-and-courage hybrid for a step-of-obedience series"),
        ("40 Days of Biblical Courage","Direct","Old Testament hero-based teaching arc"),
        ("Bold: A 40-Day Journey to Fearless Faith","Single-Word","Premium cover title, strong minimalist branding"),
        ("40 Days of Living Fearlessly","Direct","Everyday-courage framing rather than crisis-courage"),
        ("40 Days of Courageous Leadership","Direct","Bridges into Leadership & Influence category"),
        ("The Courage to Trust: A 40-Day Journey through Life's Unknowns","Promise","Strong for a season of major congregational transition"),
        ("40 Days of Kingdom Courage","Direct","Bridges into Kingdom Living category"),
        ("40 Days of Becoming a Better Leader","Direct","Practical leadership-development crossover series"),
        ("Unafraid: A 40-Day Journey Past Your Fears","Single-Word","Strong for an anxiety-and-courage combined series"),
        ("40 Days of Faith Over Fear","Direct","Cross-listed with Faith & Trust category"),
        ("The 40-Day Courage Adventure","Experience","All-ages, family-friendly boldness series"),
        ("40 Days of Standing Firm","Direct","Ephesians 6-adjacent, spiritual-warfare-lite framing"),
        ("Say Yes: A 40-Day Journey to Bold Obedience","Promise","Strong for a specific ask — missions, giving, or serving"),
        ("40 Days of Courageous Generosity","Direct","Bridges into the Stewardship category"),
        ("The Brave Life: 40 Days to Fearless Faith","Journey","Family-and-student crossover framing"),
        ("40 Days of Holy Boldness","Direct","Acts 4:31 framing, strong for an evangelism-season pairing"),
        ("Undeterred: A 40-Day Journey Through Opposition","Single-Word","Strong for a church facing real external pressure"),
        ("40 Days of Choosing Courage Daily","Direct","Habit-formation framing rather than one-time decision"),
    ])

cat("IX", "Joy & Gratitude", "Foundational",
    "Choosing joy on purpose.",
    "Consistently one of the highest-attendance, easiest-invite series — strong for a fall kickoff or Thanksgiving-season launch.",
    [("Direct","40 Days of Joy"),("Journey","The 40-Day Joy Project"),
     ("Promise","The Abundant Life Journey: 40 Days to Joy and Contentment"),
     ("Single-Word","Overjoyed: A 40-Day Journey to Lasting Joy")],
    [
        ("40 Days of Joy","Direct","The flagship, easiest all-ages invite series in the library"),
        ("The 40-Day Joy Project","Experience","Momentum framing, strong for a fall kickoff"),
        ("40 Days of Overflowing Joy","Direct","Philippians-adjacent, strong for a giving-season pairing"),
        ("40 Days of Choosing Joy","Direct","Daily-decision framing rather than circumstantial happiness"),
        ("The Abundant Life Journey: 40 Days to Joy and Contentment","Promise","Strong for a contentment-and-comparison culture teaching arc"),
        ("40 Days of Rediscovering Joy","Direct","Strong for a congregation coming out of a hard season"),
        ("Overjoyed: A 40-Day Journey to Lasting Joy","Single-Word","Premium cover title, celebratory branding"),
        ("40 Days of Gratitude","Direct","Natural November/Thanksgiving-season launch"),
        ("40 Days of Living with Gratitude","Direct","Habit-formation framing with a daily gratitude journal tie-in"),
        ("40 Days of Discovering Joy Again","Direct","Strong for a grief-adjacent, second-half-of-year series"),
        ("The Gratitude Project: 40 Days of Everyday Thanks","Experience","Structured devotional, one gratitude prompt per day"),
        ("40 Days of Thanksgiving","Direct","Classic title, strongest around the November holiday"),
        ("Joy Unshaken: A 40-Day Journey Regardless of Circumstance","Promise","James 1:2 framing, strong for a hard-season church"),
        ("40 Days of Celebrating Everyday Grace","Direct","Gratitude-and-grace hybrid framing"),
        ("The 40-Day Joy Reset","Experience","New Year or post-holiday-season joy renewal"),
        ("40 Days of Grateful Living","Direct","Everyday-practice framing, strong all-ages appeal"),
        ("Radiant: A 40-Day Journey to Contagious Joy","Single-Word","Strong for an outward-facing, evangelism-adjacent joy series"),
        ("40 Days of Delight in the Lord","Direct","Psalm 37:4 framing"),
        ("The Thankful Heart: A 40-Day Gratitude Journey","Journey","Strong for a print devotional with daily prompts"),
        ("40 Days of Joy in the Ordinary","Direct","Everyday-life framing, resonates with working-family audiences"),
    ])

cat("X", "Renewal & Spiritual Awakening", "Foundational",
    "Fresh fire.",
    "The 'come back to life' category — strong for Lent, a post-plateau congregation, or a church emerging from a hard season.",
    [("Direct","40 Days of Renewal"),("Journey","The 40-Day Spiritual Reset"),
     ("Promise","Awakened: A 40-Day Journey to Spiritual Passion and Purpose"),
     ("Single-Word","Revived: A 40-Day Journey Back to Life")],
    [
        ("40 Days of Renewal","Direct","The flagship, strong for any post-plateau season"),
        ("The 40-Day Spiritual Reset","Experience","New Year or new-season restart framing"),
        ("40 Days of Spiritual Awakening","Direct","High-energy, revival-adjacent framing"),
        ("40 Days of Revival","Direct","Direct, historic revival-language framing"),
        ("Awakened: A 40-Day Journey to Spiritual Passion and Purpose","Promise","Premium cover title for a rekindled-passion series"),
        ("40 Days of Spiritual Renewal","Direct","Everyday-renewal framing, gentler than 'revival'"),
        ("Revived: A 40-Day Journey Back to Life","Single-Word","Strong for a church coming back from decline or crisis"),
        ("40 Days of Renewed Vision","Direct","Vision-casting and renewal hybrid"),
        ("The 40-Day Life Transformation","Experience","Broader renewal-and-transformation combined framing"),
        ("40 Days of Restored Vision","Direct","Strong for a leadership-transition season"),
        ("Fresh Fire: A 40-Day Journey to Renewed Passion","Promise","High-energy title, strong for a youth-adjacent all-ages launch"),
        ("40 Days of Whole Life Renewal","Direct","Broad, comprehensive renewal across every life area"),
        ("The Reawakening: 40 Days to a Renewed Heart","Journey","Strong for a Lent-season contemplative arc"),
        ("40 Days of a Renewed Heart","Direct","Ezekiel 36:26 framing"),
        ("Come Alive: A 40-Day Journey to Spiritual Awakening","Promise","Strong graphic and music potential for a launch Sunday"),
        ("40 Days of Restoring Your Vision","Direct","Vision-and-direction renewal framing"),
        ("The 40-Day Rebuild: Restoring What Was Lost","Experience","Strong for a church rebuilding after a difficult chapter"),
        ("40 Days of Renewal and Rest","Direct","Cross-listed with Grace, Peace & Rest category"),
        ("Second Wind: A 40-Day Journey to Renewed Strength","Single-Word","Strong for a tired, long-tenured leadership team"),
        ("40 Days of a Fresh Start with God","Direct","Simple, warm, all-ages new-beginnings framing"),
    ])

cat("XI", "Transformation & Life Change", "Foundational",
    "Real change that lasts.",
    "The category for a church ready to name a specific, tangible before-and-after — strongest when paired with a personal testimony close.",
    [("Direct","40 Days of Transformation"),("Journey","The 40-Day Life Transformation"),
     ("Promise","The Transformational Life: A 40-Day Journey to Spiritual Growth"),
     ("Single-Word","Transformed: A 40-Day Journey from Who You Were to Who You're Becoming")],
    [
        ("40 Days of Transformation","Direct","The flagship, strong when paired with a testimony-driven finale"),
        ("The 40-Day Life Transformation","Journey","Same promise, journey framing"),
        ("40 Days of Heart Transformation","Direct","Inner-life framing rather than circumstantial change"),
        ("40 Days of Transformational Living","Direct","Everyday-practice framing across all six weeks"),
        ("Transformed: A 40-Day Journey from Who You Were to Who You're Becoming","Promise","Strong identity-and-change combined framing"),
        ("40 Days of Life Change","Direct","Simple, direct, easy to promote"),
        ("The 40-Day Rebuild: Rebuilding Your Life","Experience","Strong for a recovery or post-crisis season"),
        ("40 Days of Rebuilding Your Life","Direct","Direct pairing with a Nehemiah-style teaching arc"),
        ("Renewing Your Heart: A 40-Day Journey","Promise","Romans 12:2 framing, quieter than 'transformation'"),
        ("40 Days of Becoming Whole","Direct","Bridges into the Healing & Wholeness category"),
        ("The Metamorphosis: 40 Days of Becoming Who God Made You","Journey","Premium, image-forward branding option"),
        ("40 Days of Real Change","Direct","Honest, no-hype framing for a skeptical audience"),
        ("New Creation: A 40-Day Journey into Who You Are Now","Promise","2 Corinthians 5:17 framing, strong for new believers"),
        ("40 Days of Growing Through Adversity","Direct","Strong for a church that just walked through hardship"),
        ("The 40-Day Turnaround","Experience","High-energy, momentum-driven framing"),
        ("40 Days of Living with Wisdom and Purpose","Direct","Bridges Wisdom, Purpose, and Transformation categories"),
        ("From the Inside Out: A 40-Day Transformation Journey","Journey","Strong for a heart-first, behavior-second teaching arc"),
        ("40 Days of a Changed Life","Direct","Simple testimony-forward framing"),
        ("The Refining: 40 Days of Becoming More Like Christ","Experience","Sanctification-focused, discipleship-adjacent framing"),
        ("40 Days of Living Transformed","Direct","Sustained, everyday framing rather than a single event"),
    ])

cat("XII", "Healing & Wholeness", "Foundational",
    "Every part made well.",
    "Covers physical, emotional, relational, and spiritual healing together — a genuinely all-ages series when framed around wholeness rather than a single ailment.",
    [("Direct","40 Days of Healing"),("Journey","The 40-Day Healing Experience"),
     ("Promise","Becoming Whole: A 40-Day Journey to Whole Life Health"),
     ("Single-Word","Whole: A 40-Day Journey to Complete Healing")],
    [
        ("40 Days of Healing","Direct","The flagship, broad enough to cover every kind of hurt"),
        ("The 40-Day Healing Experience","Experience","Structured, ministry-team-supported framing"),
        ("40 Days of Whole Life Health","Direct","Body-mind-spirit integrated framing"),
        ("40 Days of Soul Care","Direct","Contemplative, self-care-adjacent framing without the cultural baggage"),
        ("Becoming Whole: A 40-Day Journey to Whole Life Health","Promise","Strong for a series addressing burnout and neglect together"),
        ("40 Days of Emotional Health","Direct","Direct crossover with the Emotional Wellness category"),
        ("Whole: A 40-Day Journey to Complete Healing","Single-Word","Premium cover title, minimalist and warm"),
        ("40 Days of Restoring Your Soul","Direct","Psalm 23:3 framing"),
        ("40 Days of Healing Relationships","Direct","Bridges into Community & Unity category"),
        ("The 40-Day Wholeness Journey: Body, Mind, and Spirit","Journey","Comprehensive, strong for a health-and-wellness-emphasis season"),
        ("40 Days of Hope and Healing","Direct","Pairs two flagship themes"),
        ("Restoring What Matters Most: A 40-Day Journey","Promise","Strong for a marriage-or-family healing emphasis"),
        ("40 Days of Living with Compassion for Yourself and Others","Direct","Inner-healing and outward-compassion combined"),
        ("The Mending: 40 Days to a Healed and Whole Life","Experience","Contemplative branding, strong for a grief-adjacent season"),
        ("40 Days of Renewing Your Body and Soul","Direct","Physical-and-spiritual health combined series"),
        ("Made Whole: A 40-Day Journey Through Healing","Promise","Mark 5-style healing-narrative teaching arc"),
        ("40 Days of Wholehearted Living","Direct","Everyday-integrity framing, Brene-Brown-adjacent without overlap"),
        ("The 40-Day Recovery Journey","Journey","Strong for a recovery-ministry partnership series"),
        ("40 Days of Healing What's Broken","Direct","Broad framing, works for relational or personal brokenness"),
        ("Restored and Whole: A 40-Day Journey to Full Healing","Promise","Strong closing-week title for a healing-series finale"),
    ])

cat("XIII", "Family, Marriage & Parenting", "Foundational",
    "Home, done well.",
    "The category most requested by congregations directly — genuinely all-ages, since kids, teens, and adult tracks can run the same six weeks together.",
    [("Direct","40 Days of Family"),("Journey","The 40-Day Family Legacy Journey"),
     ("Promise","Better Together: A 40-Day Journey to Biblical Community"),
     ("Single-Word","Home: A 40-Day Journey to a Thriving Family")],
    [
        ("40 Days of Family","Direct","The flagship, natural fit for a whole-church, all-ages emphasis"),
        ("40 Days of Marriage","Direct","Strong for a couples-focused six-week arc with date-night content"),
        ("40 Days of Parenting","Direct","Practical, strong small-group discussion potential"),
        ("The 40-Day Family Legacy Journey","Journey","Multi-generational framing, strong for a grandparent-inclusive series"),
        ("40 Days of Purposeful Parenting","Direct","Values-and-intention framing rather than technique-driven"),
        ("40 Days of Leading Your Family","Direct","Bridges into the Leadership category"),
        ("Home: A 40-Day Journey to a Thriving Family","Single-Word","Premium cover title, warm and simple"),
        ("40 Days of Building Strong Families","Direct","Broad, foundational family-health framing"),
        ("The 40-Day Marriage Renewal","Journey","Strong for an anniversary-season or Valentine's-timed series"),
        ("40 Days of Faithful Parenting","Direct","Values-and-faith-transfer framing"),
        ("Better Together: A 40-Day Journey to Biblical Community","Promise","Whole-family, whole-church community framing"),
        ("40 Days of Christ-Centered Relationships","Direct","Broad relational framing beyond just marriage or parenting"),
        ("The Family Table: 40 Days of Connection and Faith at Home","Experience","Strong for a family-devotional or dinner-table companion resource"),
        ("40 Days of Kingdom Family","Direct","Faith-legacy framing across generations"),
        ("Raising Rooted Kids: A 40-Day Parenting Journey","Promise","Strong for a parents-only breakout track alongside the main series"),
        ("40 Days of Life-Giving Relationships","Direct","Broad relational health, works beyond immediate family"),
        ("The 40-Day Marriage Adventure: Rediscovering Each Other","Experience","Lighter, date-night-driven marriage series"),
        ("40 Days of Restoring What Matters Most","Direct","Strong for a family recovering from a hard season"),
        ("Family Legacy by Design: A 40-Day Journey to Bless the Next Generation","Promise","Multi-generational legacy framing, premium title"),
        ("40 Days of Building a Gospel-Centered Home","Direct","Values-and-discipleship-at-home framing"),
    ])

cat("XIV", "Leadership & Influence", "Foundational",
    "Lead like it matters.",
    "Best positioned as a churchwide series with a dedicated leader/volunteer track — genuinely useful for staff, elders, and everyday influencers alike.",
    [("Direct","40 Days of Leadership"),("Journey","The 40-Day Leadership Journey"),
     ("Promise","From Success to Significance: A 40-Day Journey to Lasting Impact"),
     ("Single-Word","Influence: A 40-Day Journey to Leading Like Jesus")],
    [
        ("40 Days of Leadership","Direct","The flagship, works for staff, volunteers, and everyday influencers"),
        ("The 40-Day Leadership Journey","Journey","Strong for a volunteer-training or elder-board companion track"),
        ("40 Days of Influence","Direct","Broader than formal leadership — everyone influences someone"),
        ("40 Days of Courageous Leadership","Direct","Cross-listed with Courage & Boldness category"),
        ("From Success to Significance: A 40-Day Journey to Lasting Impact","Promise","Strong for a marketplace or Purpose Driven Business audience"),
        ("40 Days of Becoming a Servant Leader","Direct","Mark 10:45 framing, core discipleship-leadership crossover"),
        ("Influence: A 40-Day Journey to Leading Like Jesus","Single-Word","Premium cover title, strong for a staff/board resource"),
        ("40 Days of Purposeful Leadership","Direct","Bridges Leadership and Purpose categories"),
        ("The Leadership Path: 40 Days to Leading with Character","Journey","Character-first framing, strong for a values-driven org"),
        ("40 Days of Biblical Leadership","Direct","Old and New Testament leader case-study framing"),
        ("Heart of a Steward: A 40-Day Journey to Faithful Influence","Promise","Bridges into the Stewardship category"),
        ("40 Days of Becoming a Better Leader","Direct","Simple, practical, works for a lay-leader audience"),
        ("The Influence Effect: 40 Days to Leading Where You Are","Experience","Strong for an everyday-influence, non-titled-leader audience"),
        ("40 Days of Living a Life of Influence","Direct","Everyday-impact framing beyond formal titles"),
        ("Lead Well: A 40-Day Journey for Everyday Leaders","Promise","Broad appeal — parents, coaches, managers, volunteers"),
        ("40 Days of Spiritual Leadership","Direct","Discipleship-and-leadership combined framing"),
        ("The 40-Day Leader Reset: Leading from Overflow, Not Burnout","Experience","Strong for a tired staff or volunteer-team renewal series"),
        ("40 Days of Kingdom Leadership","Direct","Bridges into the Kingdom Living category"),
        ("Multiply: A 40-Day Journey to Developing Others","Single-Word","Discipleship-multiplication framing, strong for a staff track"),
        ("40 Days of Leading with Integrity","Direct","Character-first, values-driven leadership framing"),
    ])

cat("XV", "Community & Unity", "Foundational",
    "Better together.",
    "One of the strongest small-group-launch pairings in the library — every week points naturally toward a group, a table, or a next relational step.",
    [("Direct","40 Days of Community"),("Journey","The 40-Day Community Journey"),
     ("Promise","Better Together: A 40-Day Journey to Biblical Community"),
     ("Single-Word","Belong: A 40-Day Journey into Real Community")],
    [
        ("40 Days of Community","Direct","The flagship, strong companion to a small-group launch season"),
        ("The 40-Day Community Journey","Journey","Second-run or ongoing-groups framing"),
        ("40 Days of Unity","Direct","Strong for a church addressing division or a multi-campus merge"),
        ("Belong: A 40-Day Journey into Real Community","Single-Word","Premium cover title, strong for a guest-focused series"),
        ("40 Days of Building Community","Direct","Practical, action-step framing for group formation"),
        ("40 Days of Living in Community","Direct","Everyday-practice framing rather than event-based"),
        ("Better Together: A 40-Day Journey to Biblical Community","Promise","Strong all-ages, whole-church community framing"),
        ("40 Days of Christ-Centered Relationships","Direct","Cross-listed with the Family category"),
        ("The 40-Day Belonging Project","Experience","Strong for a new-members or assimilation-season campaign"),
        ("40 Days of Loving Your Neighbor","Direct","Outward-facing community framing, strong for a local-outreach tie-in"),
        ("One Body: A 40-Day Journey to Real Belonging","Promise","1 Corinthians 12 framing, strong for a diverse congregation"),
        ("40 Days of Kingdom Relationships","Direct","Broader relational framing across the whole church family"),
        ("The Table: 40 Days of Radical Hospitality and Connection","Experience","Strong for a hospitality-and-outreach-emphasis series"),
        ("40 Days of Restoring Relationships","Direct","Reconciliation-focused, strong for a divided congregation"),
        ("Connected: A 40-Day Journey Out of Isolation","Single-Word","Strong for a post-pandemic or loneliness-aware culture series"),
        ("40 Days of Becoming a Peacemaker","Direct","Matthew 5:9 framing, conflict-and-unity teaching arc"),
        ("The 40-Day Unity Challenge","Experience","Strong for a church navigating real internal tension"),
        ("40 Days of Life-Giving Relationships","Direct","Cross-listed with the Family category"),
        ("Bridge Builders: A 40-Day Journey to Reconciliation","Promise","Strong for a racial-reconciliation or generational-gap series"),
        ("40 Days of Growing Spiritually Together","Direct","Group-based discipleship framing"),
    ])

cat("XVI", "Discipleship & Following Jesus", "Foundational",
    "Learning the way of Jesus.",
    "The core formation category — best run as an annual or biennial rhythm rather than a one-time campaign, since it establishes the church's discipleship pathway.",
    [("Direct","40 Days of Discipleship"),("Journey","The 40-Day Discipleship Experience"),
     ("Promise","Everyday Discipleship: A 40-Day Journey to Following Jesus Daily"),
     ("Single-Word","Follow: A 40-Day Journey with Jesus")],
    [
        ("40 Days of Discipleship","Direct","The flagship, foundational to any discipleship-pathway launch"),
        ("The 40-Day Discipleship Experience","Experience","Strong for a formal next-steps or membership-class companion"),
        ("40 Days of Following Jesus","Direct","Simple, direct, works for new believers and lifelong members alike"),
        ("Everyday Discipleship: A 40-Day Journey to Following Jesus Daily","Promise","Habit-formation framing, strong daily-rhythm companion guide"),
        ("40 Days of Everyday Discipleship","Direct","Same theme, direct-title variant"),
        ("Follow: A 40-Day Journey with Jesus","Single-Word","Premium cover title, gospel-narrative framing"),
        ("40 Days of Becoming a Disciple","Direct","Foundational identity framing"),
        ("40 Days of Becoming a Disciple Maker","Direct","Multiplication-focused, strong for a leadership-pipeline series"),
        ("Loved to Life: A 40-Day Journey with Jesus","Promise","Strong existing market precedent, warm relational framing"),
        ("40 Days of Living the Way of Jesus","Direct","Sermon-on-the-Mount-adjacent teaching arc"),
        ("The 40-Day Follower's Path: Walking as Jesus Walked","Journey","1 John 2:6 framing, strong six-week expository arc"),
        ("40 Days of Becoming a Person of Faith","Direct","Character-formation framing"),
        ("Walking with Jesus: A 40-Day Journey to a Deeper Faith","Promise","Broad, warm, all-ages discipleship framing"),
        ("40 Days of Living the Gospel","Direct","Gospel-centered everyday-life framing"),
        ("The Apprentice: 40 Days of Learning to Live Like Jesus","Experience","Dallas Willard-adjacent framing, strong for a teaching church"),
        ("40 Days of Growing Spiritually Together","Direct","Group-based discipleship, cross-listed with Community category"),
        ("Formed: A 40-Day Journey of Spiritual Formation","Single-Word","Premium cover title for a formation-focused congregation"),
        ("40 Days of Being Rooted in Christ","Direct","Colossians 2:7 framing"),
        ("The Way, the Truth, the Life: A 40-Day Discipleship Journey","Journey","John 14:6 framing, strong for a foundational teaching series"),
        ("40 Days of Becoming More Like Jesus","Direct","Sanctification-focused, closing-series title"),
    ])

cat("XVII", "Evangelism & Mission", "Foundational",
    "Sent, not just gathered.",
    "Outward-facing category built around a specific invite-and-send moment — strongest when the closing week includes a real, local commitment.",
    [("Direct","40 Days of Evangelism"),("Journey","The 40-Day Mission Experience"),
     ("Promise","Living Sent: A 40-Day Journey to Everyday Mission"),
     ("Single-Word","Sent: A 40-Day Journey to Bold Witness")],
    [
        ("40 Days of Evangelism","Direct","The flagship, strong for a fall invite-a-friend season"),
        ("40 Days of Mission","Direct","Broader than evangelism alone — local and global together"),
        ("The 40-Day Mission Experience","Experience","Strong companion to a missions-trip or local-outreach launch"),
        ("Living Sent: A 40-Day Journey to Everyday Mission","Promise","Everyday-witness framing rather than event-based evangelism"),
        ("40 Days of Living on Mission","Direct","Habit-formation framing for ordinary, everyday witness"),
        ("Sent: A 40-Day Journey to Bold Witness","Single-Word","Premium cover title, strong for a commissioning Sunday"),
        ("40 Days of Marketplace Ministry","Direct","Bridges into Purpose Driven Business and workplace faith"),
        ("40 Days of Faith at Work","Direct","Workplace-witness framing, strong marketplace crossover"),
        ("The 40-Day Great Commission Journey","Journey","Matthew 28:19 framing, foundational sending-series"),
        ("40 Days of Living the Great Commission","Direct","Direct scriptural anchor for a global-missions emphasis"),
        ("Curious to Committed: A 40-Day Journey for Seekers","Promise","Strong seeker-friendly series for a skeptic-aware culture"),
        ("40 Days of Becoming a Light","Direct","Matthew 5:14 framing, simple and warm"),
        ("The Uncommon Invitation: 40 Days of Bold, Everyday Witness","Experience","Strong for a church rethinking traditional evangelism methods"),
        ("40 Days of Loving Your Neighbor as Mission","Direct","Local-outreach framing, cross-listed with Community category"),
        ("Everyday Witness: A 40-Day Journey to Sharing Your Story","Promise","Testimony-training framing, strong small-group companion"),
        ("40 Days of Living the Gospel Out Loud","Direct","Bold-witness framing for a growth-season congregation"),
        ("The 40-Day Send: From the Seats to the Streets","Experience","Strong for a church repositioning beyond weekend-only ministry"),
        ("40 Days of Being the Church, Not Just Attending It","Direct","Outward-facing identity framing"),
        ("Uncommon Compassion: A 40-Day Mission Journey","Promise","Compassion-and-mission combined, strong for a justice-emphasis series"),
        ("40 Days of Kingdom Impact","Direct","Broad missional framing, bridges into Kingdom Living category"),
    ])

cat("XVIII", "Kingdom Living & Impact", "Foundational",
    "Living like the Kingdom is now.",
    "A whole-life, whole-church vision category — often the closing series of a multi-year teaching arc that ties earlier campaigns together.",
    [("Direct","40 Days of Kingdom Living"),("Journey","The 40-Day Kingdom Living Plan"),
     ("Promise","Kingdom Impact: A 40-Day Journey to Purpose Beyond Success"),
     ("Single-Word","Kingdom: A 40-Day Journey to Living Like It's Already Here")],
    [
        ("40 Days of Kingdom Living","Direct","The flagship, strong as a capstone teaching series"),
        ("The 40-Day Kingdom Living Plan","Journey","Structured, practical framing for a whole-church emphasis"),
        ("40 Days of Kingdom Purpose","Direct","Bridges Kingdom Living with the Purpose category"),
        ("Kingdom Impact: A 40-Day Journey to Purpose Beyond Success","Promise","Strong marketplace and Purpose Driven Business crossover"),
        ("40 Days of Kingdom Impact","Direct","Simple, direct, outward-facing"),
        ("The 40-Day Kingdom Builder Challenge","Experience","Strong for a building or vision-campaign season"),
        ("40 Days of Becoming a Kingdom Builder","Direct","Active-participation framing, strong for a capital campaign pairing"),
        ("Kingdom: A 40-Day Journey to Living Like It's Already Here","Single-Word","Premium cover title, eschatological hope framing"),
        ("40 Days of Kingdom Vision","Direct","Vision-casting and Kingdom-imagination combined"),
        ("The Upside-Down Kingdom: 40 Days of Living the Sermon on the Mount","Journey","Strong expository series through Matthew 5-7"),
        ("40 Days of Kingdom Confidence","Direct","Identity-in-Christ framing tied to Kingdom citizenship"),
        ("Beyond Success: A 40-Day Journey to Significance","Promise","Strong for a marketplace or achievement-oriented congregation"),
        ("40 Days of Kingdom Wisdom","Direct","Cross-listed with the Wisdom & Discernment category"),
        ("The 40-Day Kingdom Family Journey","Journey","Multi-generational Kingdom-legacy framing"),
        ("40 Days of Kingdom Alignment","Direct","Priorities-and-values realignment framing"),
        ("Citizens of Heaven: A 40-Day Kingdom Living Journey","Promise","Philippians 3:20 framing, strong identity-and-Kingdom series"),
        ("40 Days of Kingdom Breakthrough","Direct","Cross-listed with the Freedom & Breakthrough category"),
        ("The 40-Day Kingdom Vision for Life","Journey","Whole-life, long-arc Kingdom framing"),
        ("40 Days of Kingdom Courage","Direct","Cross-listed with the Courage & Boldness category"),
        ("Here and Now: A 40-Day Journey into Kingdom Living Today","Promise","Present-tense, practical Kingdom-living framing"),
    ])

cat("XIX", "Spiritual Growth & Maturity", "Foundational",
    "Growing up in Christ.",
    "The 'next level' category for congregations past the basics — strong as a second-year or advanced-track series following a Discipleship 101 campaign.",
    [("Direct","40 Days of Spiritual Growth"),("Journey","The 40-Day Spiritual Growth Plan"),
     ("Promise","Living Fully Alive: A 40-Day Journey to Spiritual Renewal"),
     ("Single-Word","Maturing: A 40-Day Journey to Spiritual Depth")],
    [
        ("40 Days of Spiritual Growth","Direct","The flagship, strong second-year or advanced-track series"),
        ("The 40-Day Spiritual Growth Plan","Journey","Structured, milestone-based growth framing"),
        ("40 Days of Spiritual Maturity","Direct","Ephesians 4:13 framing, strong for a long-tenured congregation"),
        ("40 Days of Spiritual Momentum","Direct","Practical, habit-and-rhythm framing"),
        ("Maturing: A 40-Day Journey to Spiritual Depth","Single-Word","Premium cover title, strong for a formation-focused church"),
        ("40 Days of Spiritual Resilience","Direct","Endurance-and-growth combined framing"),
        ("40 Days of Spiritual Depth","Direct","Contemplative, quieter growth framing"),
        ("The 40-Day Growth Track: Moving from Milk to Meat","Journey","1 Corinthians 3:2 framing, strong next-steps series"),
        ("40 Days of Building Spiritual Habits","Direct","Practical rhythms-and-disciplines framing"),
        ("Rooted and Growing: A 40-Day Journey to Lasting Maturity","Promise","Strong for a foundational, roots-and-fruit teaching arc"),
        ("40 Days of Spiritual Confidence","Direct","Cross-listed with the Prayer & Intimacy category"),
        ("40 Days of Growing Spiritually Together","Direct","Group-based growth, cross-listed with Community category"),
        ("The Deep End: 40 Days to Real Spiritual Depth","Experience","Strong for a congregation ready to move past surface-level faith"),
        ("40 Days of Spiritual Clarity for Life","Direct","Direction-and-discernment combined with growth"),
        ("Growing Up: A 40-Day Journey to Spiritual Maturity","Promise","Simple, honest, all-ages growth framing"),
        ("40 Days of Deepening Your Faith","Direct","Cross-listed with the Faith & Trust category"),
        ("The 40-Day Formation Journey: Becoming Who You're Meant to Be","Journey","Broad, whole-person spiritual-formation framing"),
        ("40 Days of Bearing Fruit","Direct","Galatians 5:22-23 framing, strong expository series"),
        ("Living Fully Alive: A 40-Day Journey to Spiritual Renewal","Promise","Strong crossover with the Renewal category"),
        ("40 Days of Spiritual Passion","Direct","Renewed-zeal framing, strong for a plateaued congregation"),
    ])

cat("XX", "Stewardship, Generosity & Finances", "Foundational",
    "Everything belongs to God.",
    "The proven category from the existing library — anchored by 'God Owns It All,' this remains the strongest financial-discipleship arc for a churchwide or corporate audience.",
    [("Direct","40 Days of Generosity"),("Journey","The 40-Day Financial Wisdom Challenge"),
     ("Promise","God Owns It All: A 40-Day Journey to Freedom, Wisdom, and Generosity"),
     ("Single-Word","Enough: A 40-Day Journey to Contentment and Generosity")],
    [
        ("God Owns It All: A 40-Day Journey to Freedom, Wisdom, and Generosity","Promise","The anchor title of the entire stewardship line"),
        ("40 Days of Open Hands","Direct","The most pastoral, most visually clear stewardship title"),
        ("40 Days of Enough","Direct","Reframes giving as contentment rather than sacrifice"),
        ("The Generous Life: A 40-Day Journey to Trust God with Everything","Promise","Whole-life stewardship framing beyond a giving campaign"),
        ("40 Days of Faithful with Much","Direct","Parable-of-the-talents framing, speaks to every income level"),
        ("40 Days of Kingdom Finances","Direct","Comprehensive, theologically anchored financial-discipleship framing"),
        ("Faith & Finances: A 40-Day Journey to Align Your Heart, Habits, and Household","Promise","Strong for a couples or household-budgeting companion track"),
        ("40 Days of Living Generously","Direct","Everyday-practice framing rather than one annual ask"),
        ("The Blessed Life Journey: 40 Days to Freedom from Financial Fear","Journey","Strong for a congregation carrying real financial anxiety"),
        ("40 Days of Biblical Generosity","Direct","Foundational, scripture-anchored generosity teaching"),
        ("More Than Enough: A 40-Day Journey to Contentment and Generosity","Promise","Strong for a comparison-and-contentment teaching arc"),
        ("40 Days of Purposeful Generosity","Direct","Intentional, values-driven giving framing"),
        ("The Stewardship Revolution: A 40-Day Journey to Faithful Living","Journey","Whole-life stewardship beyond money — time, talent, treasure"),
        ("40 Days of Becoming a Faithful Steward","Direct","Identity-based stewardship framing"),
        ("Money, Meaning, and Mission: A 40-Day Journey to God's Economy","Promise","Strong for a marketplace or Purpose Driven Business audience"),
        ("40 Days of Courageous Generosity","Direct","Cross-listed with the Courage & Boldness category"),
        ("The Generosity Factor: A 40-Day Journey to Radical Living","Journey","High-energy framing for a capital-campaign season"),
        ("40 Days of Living Open-Handed","Direct","Direct variant of the flagship 'Open Hands' theme"),
        ("Master Your Money: A 40-Day Financial Wisdom Journey","Journey","Practical, budgeting-and-planning-forward framing"),
        ("40 Days of Master Your Money","Direct","Straightforward personal-finance discipleship series"),
    ])

# ============================================================
# NEW 10 — additional categories, grounded in current research
# ============================================================

cat("XXI", "Surrender & Total Trust", "New",
    "Open hands, open heart.",
    "A focused category on the single hardest spiritual move — letting go of control. Strong for a congregation facing a major transition or loss of control.",
    [("Direct","40 Days of Surrender"),("Journey","The 40-Day Surrender Journey"),
     ("Promise","Open Hands, Open Heart: A 40-Day Journey to Surrender"),
     ("Single-Word","Yielded: A 40-Day Journey to Letting Go")],
    [
        ("40 Days of Surrender","Direct","The flagship, simple and direct"),
        ("Open Hands, Open Heart: A 40-Day Journey to Surrender","Promise","Pastoral, image-forward framing"),
        ("40 Days of Trust","Direct","Broad trust framing, foundational to the whole category"),
        ("Yielded: A 40-Day Journey to Letting Go","Single-Word","Premium cover title, contemplative"),
        ("40 Days of Radical Trust","Direct","Cross-listed with Faith & Trust category"),
        ("The Surrendered Life: A 40-Day Journey to Total Trust","Journey","Strong for a season requiring a major life decision"),
        ("40 Days of Trusting God in Every Season","Direct","Broad, all-seasons framing"),
        ("Let Go: A 40-Day Journey to Real Surrender","Promise","Simple, honest, direct-address framing"),
        ("40 Days of Obedience","Direct","Action-oriented surrender framing"),
        ("The 40-Day Release: Letting Go of What You Can't Control","Experience","Strong for a control-and-anxiety combined teaching arc"),
        ("40 Days of Following Without Knowing the Whole Path","Direct","Abraham-narrative framing, strong expository option"),
        ("Not My Will: A 40-Day Journey Through Surrender","Promise","Gethsemane framing, strong for a Lent-season series"),
        ("40 Days of Trading Control for Peace","Direct","Direct benefit-framing for an anxious congregation"),
        ("The Yielded Heart: 40 Days of Saying Yes to God","Journey","Warm, relational surrender framing"),
        ("40 Days of Living Surrendered","Direct","Everyday-practice framing"),
        ("All In: A 40-Day Journey of Full Surrender","Single-Word","High-commitment framing, strong for a membership or baptism season"),
        ("40 Days of Trusting the Process","Direct","Practical, patience-and-trust combined framing"),
        ("The Empty Hands Journey: 40 Days to Releasing What You're Gripping","Journey","Strong visual/graphic potential"),
        ("40 Days of Total Surrender to God's Plan","Direct","Direct, comprehensive surrender framing"),
        ("Letting God Lead: A 40-Day Journey of Trust","Promise","Simple, practical, all-ages accessible"),
    ])

cat("XXII", "Christ-Centered & Biblical Living", "New",
    "Every day, His way.",
    "A foundational orthodoxy category — keeps Jesus and Scripture, not self-improvement, at the center of the whole-church teaching calendar.",
    [("Direct","40 Days of Christ-Centered Living"),("Journey","The 40-Day Biblical Living Plan"),
     ("Promise","Walking with Jesus: A 40-Day Journey to a Deeper Faith"),
     ("Single-Word","Centered: A 40-Day Journey on Christ Alone")],
    [
        ("40 Days of Christ-Centered Living","Direct","The flagship, foundational orthodoxy framing"),
        ("The 40-Day Biblical Living Plan","Journey","Practical, Scripture-first everyday-life framing"),
        ("40 Days of Biblical Living","Direct","Direct-title variant of the flagship"),
        ("Centered: A 40-Day Journey on Christ Alone","Single-Word","Premium cover title, minimalist and strong"),
        ("40 Days of Living the Way of Jesus","Direct","Cross-listed with the Discipleship category"),
        ("40 Days of Living in Truth","Direct","Foundational, apologetics-adjacent everyday-life framing"),
        ("The Gospel Life: A 40-Day Journey to Living the Gospel","Journey","Comprehensive gospel-centered daily-life framing"),
        ("40 Days of Living the Gospel","Direct","Direct-title variant"),
        ("Anchored in the Word: A 40-Day Scripture Journey","Promise","Strong for a Bible-engagement-emphasis series"),
        ("40 Days of Following God Daily","Direct","Cross-listed with Prayer & Intimacy category"),
        ("40 Days of Loving God First","Direct","Greatest-commandment framing, foundational priorities series"),
        ("The First Priority: 40 Days of Putting God First","Experience","Practical priorities-and-calendar framing"),
        ("40 Days of Christ in Every Corner of Life","Direct","Whole-life integration framing, marketplace crossover"),
        ("His Story, My Life: A 40-Day Journey Through Scripture","Promise","Bible-overview-adjacent, strong for a new-believer track"),
        ("40 Days of Living with Wisdom and Purpose","Direct","Cross-listed with Wisdom category"),
        ("The Blessed Life: 40 Days of Living the Beatitudes","Journey","Direct Matthew 5 expository series"),
        ("40 Days of The Blessed Life","Direct","Simple direct-title companion"),
        ("Rooted in Him: A 40-Day Journey of Christ-Centered Living","Promise","Colossians 2:7 framing"),
        ("40 Days of Living a Blessed Life","Direct","Everyday-practice, gratitude-adjacent framing"),
        ("The Narrow Road: 40 Days of Christ-Centered Choices","Journey","Matthew 7:13-14 framing, strong decision-focused series"),
    ])

cat("XXIII", "Serving Others & Compassion", "New",
    "Love with your hands.",
    "An action-oriented category built for a hands-on serve day or ongoing volunteer-team launch — strongest when every week ends in a real act of service.",
    [("Direct","40 Days of Serving Others"),("Journey","The 40-Day Serve Challenge"),
     ("Promise","Radical Compassion: A 40-Day Journey to Loving Like Jesus"),
     ("Single-Word","Serve: A 40-Day Journey to a Others-First Life")],
    [
        ("40 Days of Serving Others","Direct","The flagship, strong companion to a churchwide serve day"),
        ("Serve: A 40-Day Journey to a Others-First Life","Single-Word","Premium cover title, action-forward"),
        ("40 Days of Radical Compassion","Direct","High-energy, outward-focused framing"),
        ("40 Days of Living with Compassion","Direct","Everyday-practice framing rather than event-based"),
        ("Radical Compassion: A 40-Day Journey to Loving Like Jesus","Promise","Strong for a justice-and-mercy teaching arc"),
        ("40 Days of Loving Your Neighbor","Direct","Cross-listed with Community category"),
        ("The 40-Day Serve Challenge","Experience","Momentum-building, strong volunteer-recruitment tool"),
        ("40 Days of Living Sacrificially","Direct","Deeper commitment framing, strong for a mature congregation"),
        ("Others First: A 40-Day Journey Out of Self-Focus","Promise","Philippians 2:3-4 framing"),
        ("40 Days of Radical Kindness","Direct","Simple, all-ages, easy-to-practice framing"),
        ("The Good Samaritan Life: 40 Days of Everyday Compassion","Journey","Direct Luke 10 expository series"),
        ("40 Days of Living Beyond Yourself","Direct","Cross-listed with Freedom & Breakthrough category"),
        ("Hands and Feet: A 40-Day Journey to Being the Church","Promise","Outward identity framing, strong for a missional-culture shift"),
        ("40 Days of Building Community Through Service","Direct","Combines serving with belonging"),
        ("The 40-Day Compassion Project: Loving Your City Well","Experience","Strong local-outreach and city-engagement framing"),
        ("40 Days of Small Acts, Big Love","Direct","Approachable, low-barrier serving framing"),
        ("Uncommon Compassion: A 40-Day Mission Journey","Promise","Cross-listed with Evangelism & Mission category"),
        ("40 Days of Living Generously with Your Time","Direct","Time-as-generosity framing, bridges Stewardship category"),
        ("The Servant's Heart: 40 Days of Learning to Serve Like Jesus","Journey","John 13 foot-washing narrative framing"),
        ("40 Days of Loving in Action, Not Just Words","Direct","1 John 3:18 framing"),
    ])

cat("XXIV", "Legacy & Generational Faith", "New",
    "Faith worth passing down.",
    "A multi-generational category built for grandparents, parents, and children to walk through together — genuinely all-ages by design, not just in theory.",
    [("Direct","40 Days of Legacy"),("Journey","The 40-Day Family Legacy Journey"),
     ("Promise","Family Legacy by Design: A 40-Day Journey to Bless the Next Generation"),
     ("Single-Word","Legacy: A 40-Day Journey to What Outlasts You")],
    [
        ("40 Days of Legacy","Direct","The flagship, strong for a multi-generational whole-church series"),
        ("Legacy: A 40-Day Journey to What Outlasts You","Single-Word","Premium cover title, reflective and warm"),
        ("Family Legacy by Design: A 40-Day Journey to Bless the Next Generation","Promise","Strong for a grandparent-and-grandchild companion track"),
        ("40 Days of Living Generationally","Direct","Direct-title variant, broad generational framing"),
        ("The Legacy Life: A 40-Day Journey to What Matters Most","Journey","Priorities-and-legacy combined framing"),
        ("40 Days of Wisdom to Offer","Direct","Positions older generations as deployed, not just served"),
        ("Passing the Baton: A 40-Day Journey of Generational Faith","Promise","Strong relay/handoff visual and graphic theme"),
        ("40 Days of Building a Faith Worth Passing Down","Direct","Direct, parent-and-grandparent-focused framing"),
        ("The 40-Day Heritage Journey: Faith Across Generations","Journey","Strong for a church with deep multi-generational roots"),
        ("40 Days of Raising the Next Generation of Faith","Direct","Youth-and-family discipleship framing"),
        ("Roots and Wings: A 40-Day Legacy Journey","Promise","Strong graphic potential, launching and grounding combined"),
        ("40 Days of Kingdom Family","Direct","Cross-listed with the Family category"),
        ("The Faithful Line: 40 Days of Generational Blessing","Journey","Old Testament covenant-and-blessing framing"),
        ("40 Days of Blessing the Next Generation","Direct","Simple, warm, direct-benefit framing"),
        ("Grandparenting with Purpose: A 40-Day Legacy Journey","Promise","Strong dedicated track for the grandparent audience"),
        ("40 Days of Living So the Next Generation Remembers","Direct","Reflective, testimony-and-memory framing"),
        ("The 40-Day Generational Reset: Breaking Cycles, Building Legacy","Experience","Strong for a family-healing and generational-pattern series"),
        ("40 Days of Deuteronomy 6: Teaching Faith at Home","Direct","Direct scriptural anchor, strong expository option"),
        ("Handed Down: A 40-Day Journey of Faith That Lasts","Promise","Warm, heirloom-style branding potential"),
        ("40 Days of Living for What Outlasts You","Direct","Reflective closing-week framing for a legacy series"),
    ])

cat("XXV", "Identity: Who You Are in Christ", "New",
    "Known, named, and loved.",
    "Foundational identity category, strong across every age — the teen and adult versions ask the same core question with age-appropriate language.",
    [("Direct","40 Days of Identity in Christ"),("Journey","The 40-Day Identity Journey"),
     ("Promise","New Creation: A 40-Day Journey into Who You Are Now"),
     ("Single-Word","Known: A 40-Day Journey to Your True Identity")],
    [
        ("40 Days of Identity in Christ","Direct","The flagship, foundational for teens and adults alike"),
        ("Known: A 40-Day Journey to Your True Identity","Single-Word","Premium cover title, warm and personal"),
        ("New Creation: A 40-Day Journey into Who You Are Now","Promise","2 Corinthians 5:17 framing, cross-listed with Transformation"),
        ("40 Days of Becoming Who You Were Made to Be","Direct","Direct-title variant of the flagship theme"),
        ("The 40-Day Identity Journey: From Performance to Belonging","Journey","Strong for a comparison-and-approval-culture teaching arc"),
        ("40 Days of Living from Belovedness, Not Performance","Direct","Grace-based identity framing, strong for a burned-out audience"),
        ("Chosen: A 40-Day Journey to Knowing You Belong","Single-Word","Strong for a rejection-and-belonging teaching arc"),
        ("40 Days of Who God Says You Are","Direct","Simple, direct, all-ages accessible framing"),
        ("The Mirror and the Word: 40 Days of Seeing Yourself Rightly","Journey","James 1:23-24 framing, strong for a self-image-focused series"),
        ("40 Days of Becoming Whole","Direct","Cross-listed with the Healing & Wholeness category"),
        ("Beloved: A 40-Day Journey to Living Fully Known","Promise","Warm, relational identity framing"),
        ("40 Days of Freedom from Comparison","Direct","Direct crossover with the Freedom & Breakthrough category"),
        ("The 40-Day Adoption Journey: Living as God's Child","Journey","Romans 8:15 framing, strong for a family-and-belonging series"),
        ("40 Days of Living Unashamed","Direct","Shame-and-identity teaching arc, strong for a recovery-adjacent series"),
        ("Set Apart: A 40-Day Journey to a Holy, Whole Identity","Single-Word","1 Peter 2:9 framing"),
        ("40 Days of Discovering Your Gifts","Direct","Practical, spiritual-gifts-assessment framing"),
        ("The Name God Gave You: 40 Days of Reclaiming Your Identity","Journey","Strong for a season addressing labels and past mistakes"),
        ("40 Days of Living Free from Labels","Direct","Culture-and-identity teaching arc, strong student-ministry crossover"),
        ("Fully Known, Fully Loved: A 40-Day Identity Journey","Promise","Psalm 139 framing, warm and comprehensive"),
        ("40 Days of Living as God's Masterpiece","Direct","Ephesians 2:10 framing, closing-series title"),
    ])

cat("XXVI", "Anxiety, Fear & Emotional Wellness", "New",
    "Peace for an anxious mind.",
    "One of the two highest-demand rising categories nationally — nearly every congregation now has a significant share of members naming anxiety as their top felt need.",
    [("Direct","40 Days of Freedom from Anxiety"),("Journey","The 40-Day Anxious Heart Journey"),
     ("Promise","Powerful Self-Talk from the Psalms: 40 Days to a Biblical Mindset"),
     ("Single-Word","Steady: A 40-Day Journey to a Calm and Anchored Mind")],
    [
        ("40 Days of Freedom from Anxiety","Direct","The flagship, the single most requested emerging-theme series"),
        ("Quiet Moments for the Anxious Heart: A 40-Day Journey","Promise","Strong existing market precedent, gentle framing"),
        ("Steady: A 40-Day Journey to a Calm and Anchored Mind","Single-Word","Premium cover title, calming visual branding"),
        ("40 Days of Peace Over Panic","Direct","Direct, honest, non-clinical framing"),
        ("Powerful Self-Talk from the Psalms: 40 Days to a Biblical Mindset","Promise","Renewing-the-mind framing, cross-listed with Wisdom category"),
        ("40 Days of Casting Your Anxiety on Him","Direct","1 Peter 5:7 framing"),
        ("The 40-Day Calm: Trading Worry for Trust","Experience","Strong for a whole-church emphasis on mental and emotional health"),
        ("40 Days of a Renewed, Peaceful Mind","Direct","Romans 12:2 framing, mental-renewal emphasis"),
        ("Unshaken: A 40-Day Journey Through Worry and Fear","Single-Word","Strong for a genuinely anxious season in the congregation"),
        ("40 Days of Naming What's Weighing You Down","Direct","Honest, vulnerability-forward opening-week framing"),
        ("Be Still: A 40-Day Journey to a Quiet, Confident Heart","Promise","Psalm 46:10 framing, contemplative and calming"),
        ("40 Days of Faith Over Fear","Direct","Cross-listed with the Faith & Trust category"),
        ("The Anxious Heart Journey: 40 Days from Worry to Worship","Journey","Strong for a worship-service-integrated emotional-health series"),
        ("40 Days of Trading Worry for Worship","Direct","Direct-title variant, action-oriented"),
        ("Held: A 40-Day Journey Through Fear to Peace","Single-Word","Warm, comforting cover title"),
        ("40 Days of a Sound Mind","Direct","2 Timothy 1:7 framing"),
        ("The Peace That Passes Understanding: A 40-Day Journey","Promise","Philippians 4:6-7 framing, strong all-ages accessibility"),
        ("40 Days of Rest for the Restless Mind","Direct","Cross-listed with Grace, Peace & Rest category"),
        ("Grounded: A 40-Day Journey to Emotional Stability","Single-Word","Strong for a mental-health-aware, clinically informed series"),
        ("40 Days of Letting Go of What You Can't Control","Direct","Cross-listed with the Surrender category"),
    ])

cat("XXVII", "Grief, Suffering & Hard Seasons", "New",
    "Hope in the hard.",
    "Handled with real pastoral care, this is among the most trusted, most-thanked-for series a church can run — designed for slow, honest, unhurried teaching.",
    [("Direct","40 Days of Grief and Hope"),("Journey","The 40-Day Grief Journey"),
     ("Promise","Beyond the Darkness: 40 Days of Encouragement in Grief"),
     ("Single-Word","Held: A 40-Day Journey Through Loss")],
    [
        ("40 Days of Grief and Hope","Direct","The flagship, pastoral and honest framing"),
        ("Beyond the Darkness: 40 Days of Encouragement in Grief","Promise","Strong existing market precedent, direct and honest"),
        ("Held: A 40-Day Journey Through Loss","Single-Word","Premium cover title, comforting and simple"),
        ("40 Days in the Valley: Finding God in the Hard Season","Direct","Psalm 23:4 framing"),
        ("The 40-Day Grief Journey: Permission to Not Be Okay","Journey","Strong for a congregation needing explicit permission to grieve"),
        ("40 Days of Hope for Hurting Hearts","Direct","Cross-listed with the Hope category"),
        ("Lament and Hope: A 40-Day Journey Through Suffering","Promise","Biblical-lament framing, strong expository option through Psalms/Job"),
        ("40 Days of Sitting with Sorrow, Standing on Hope","Direct","Honest, dual-posture framing"),
        ("The Long Way Home: 40 Days for Those Who Are Grieving","Journey","Warm, patient, unhurried framing"),
        ("40 Days of God's Nearness in Suffering","Direct","Psalm 34:18 framing"),
        ("Weeping May Stay for the Night: A 40-Day Grief Journey","Promise","Psalm 30:5 framing, strong contemplative title"),
        ("40 Days of Grieving Well","Direct","Direct, permission-giving framing"),
        ("The Comfort Journey: 40 Days of God's Presence in Pain","Journey","2 Corinthians 1:3-4 framing"),
        ("40 Days of Hard Questions, Honest Faith","Direct","Cross-listed with the Doubt & Questions category"),
        ("Anchored in the Storm: A 40-Day Journey Through Hard Seasons","Promise","Broad hard-season framing beyond grief alone"),
        ("40 Days of Finding God in the Waiting","Direct","Strong for a season of unresolved hardship or diagnosis"),
        ("The 40-Day Companion for Grief and Loss","Experience","Structured, resource-forward framing for a care-ministry pairing"),
        ("40 Days of Carrying Each Other's Burdens","Direct","Galatians 6:2 framing, community-and-grief combined"),
        ("Still Standing: A 40-Day Journey Through Suffering","Single-Word","Resilience-and-suffering combined framing"),
        ("40 Days of Trusting God When Life Doesn't Make Sense","Direct","Honest, unresolved-tension framing"),
    ])

cat("XXVIII", "Doubt, Questions & Honest Faith", "New",
    "Real questions welcome.",
    "A trust-building category for a skeptical culture — gives permission to ask hard questions without penalty, which research shows increasingly matters to younger generations.",
    [("Direct","40 Days of Honest Questions"),("Journey","The 40-Day Doubt Journey"),
     ("Promise","A Reason for Hope: 40 Days to Renewed Confidence"),
     ("Single-Word","Wrestle: A 40-Day Journey Through Doubt to Deeper Faith")],
    [
        ("40 Days of Honest Questions","Direct","The flagship, gives explicit permission to doubt out loud"),
        ("Wrestle: A 40-Day Journey Through Doubt to Deeper Faith","Single-Word","Premium cover title, Jacob-at-the-Jabbok framing"),
        ("40 Days of Doubt, Faith, and the Space Between","Direct","Honest, non-resolving framing for genuine seekers"),
        ("A Reason for Hope: 40 Days to Renewed Confidence","Promise","Apologetics-adjacent, strong for a skeptic-friendly series"),
        ("The 40-Day Question Series: What If It's Not True?","Experience","Bold, direct engagement with the culture's hardest objections"),
        ("40 Days of Faith That Asks Questions","Direct","Reframes doubt as part of faith rather than opposed to it"),
        ("Honest to God: A 40-Day Journey of Real Faith","Promise","Warm, permission-giving, all-ages accessible framing"),
        ("40 Days of Thomas: Faith for the Skeptical","Direct","John 20 expository framing, strong for a doubt-focused series"),
        ("The 40-Day Deconstruction to Reconstruction Journey","Journey","Direct engagement with a major generational faith trend"),
        ("40 Days of What I Actually Believe and Why","Direct","Apologetics-and-ownership framing, strong for young adults"),
        ("Unresolved: A 40-Day Journey with Faith's Hardest Questions","Single-Word","Honest title, doesn't over-promise easy answers"),
        ("40 Days of Doubt Isn't the Opposite of Faith","Direct","Reassuring, theologically grounded framing"),
        ("The Skeptic's Path: 40 Days to an Examined Faith","Journey","Strong for a church with many spiritually curious attenders"),
        ("40 Days of Asking God the Hard Questions","Direct","Psalm-of-lament framing, strong expository option"),
        ("Faith Undone and Remade: A 40-Day Journey","Promise","Strong for a congregation navigating real deconstruction"),
        ("40 Days of Living with Unanswered Questions","Direct","Honest, mystery-embracing framing"),
        ("The 40-Day Apologetics Primer: Reasons to Believe","Experience","Practical, teaching-forward framing for a skeptical culture"),
        ("40 Days of Questions Jesus Asked","Direct","Gospel-based expository series, strong small-group discussion hook"),
        ("Between Doubt and Devotion: A 40-Day Journey","Promise","Contemplative, honest framing for the mid-faith-journey attender"),
        ("40 Days of Choosing Faith Anyway","Direct","Closing-series title, strong for a decision-forward finale"),
    ])

cat("XXIX", "Digital Discernment & Faith in the Age of AI", "New",
    "Wisdom for a wired world.",
    "The single highest-opportunity emerging category identified in current preaching-trend research — most churchgoers are already forming views on AI with little pastoral guidance.",
    [("Direct","40 Days of Digital Discernment"),("Journey","The 40-Day Faith and Technology Journey"),
     ("Promise","Wisdom for a Wired World: A 40-Day Journey to Digital Discernment"),
     ("Single-Word","Discerning: A 40-Day Journey Through the Digital Age")],
    [
        ("40 Days of Digital Discernment","Direct","The flagship, the single highest-opportunity emerging category"),
        ("Wisdom for a Wired World: A 40-Day Journey to Digital Discernment","Promise","Broad framing, strong for an all-ages digital-life series"),
        ("40 Days of Faith in the Age of AI","Direct","Direct engagement with the era's defining question"),
        ("Discerning: A 40-Day Journey Through the Digital Age","Single-Word","Premium cover title, contemporary and credible"),
        ("The 40-Day Screen Wisdom Journey: Living Well in a Digital World","Journey","Practical, whole-family screen-habits framing"),
        ("40 Days of Being Formed by God, Not Your Feed","Direct","Direct, provocative framing for a social-media-saturated culture"),
        ("Human and Holy: A 40-Day Journey to Wisdom in a Digital Age","Promise","Strong for a series naming what technology can't replace"),
        ("40 Days of Unplugging to Reconnect with God","Direct","Practical digital-sabbath framing"),
        ("The Algorithm and the Almighty: 40 Days of Discernment","Journey","Bold, attention-grabbing title for a culture-engagement series"),
        ("40 Days of Wisdom for Your Timeline","Direct","Simple, practical, social-media-specific framing"),
        ("Real Presence in a Virtual World: A 40-Day Journey","Promise","Community-and-technology combined framing"),
        ("40 Days of Raising Kids in a Digital Age","Direct","Strong parent-track companion within the all-ages series"),
        ("The 40-Day AI and Faith Conversation: What Machines Can't Do","Experience","Direct, teaching-forward engagement with congregational curiosity"),
        ("40 Days of Guarding Your Heart Online","Direct","Proverbs 4:23 framing, applied to digital life"),
        ("Still Human: A 40-Day Journey to Presence in a Digital World","Single-Word","Strong for a series on embodiment, presence, and community"),
        ("40 Days of Discipling Through the Noise","Direct","Cross-listed with the Wisdom & Discernment category"),
        ("The Wired and the Whole: 40 Days to a Healthy Digital Life","Journey","Whole-person framing, physical and spiritual health combined"),
        ("40 Days of Technology as Tool, Not Master","Direct","Direct theological framing on technology's proper place"),
        ("Unplugged and Present: A 40-Day Family Digital Wisdom Journey","Promise","All-ages family companion track, strong practical application"),
        ("40 Days of Faithful Discernment in an AI World","Direct","Closing-series title, comprehensive digital-discernment framing"),
    ])

cat("XXX", "New Beginnings & Fresh Starts", "New",
    "Every ending is a doorway.",
    "The flexible, evergreen 'restart' category — usable for a January launch, a new building, a new pastor, or simply a congregation ready to turn a page.",
    [("Direct","40 Days of New Beginnings"),("Journey","The 40-Day Fresh Start Journey"),
     ("Promise","A New Chapter: A 40-Day Journey to a Fresh Start with God"),
     ("Single-Word","New: A 40-Day Journey into What God Is Doing Next")],
    [
        ("40 Days of New Beginnings","Direct","The flagship, flexible for any season of transition"),
        ("A New Chapter: A 40-Day Journey to a Fresh Start with God","Promise","Warm, all-ages new-year or new-season framing"),
        ("New: A 40-Day Journey into What God Is Doing Next","Single-Word","Premium cover title, forward-looking and hopeful"),
        ("40 Days of New Life","Direct","Simple, resurrection-adjacent framing, strong for Easter timing"),
        ("The 40-Day Fresh Start Journey","Journey","Direct-title variant of the flagship"),
        ("40 Days of Starting Over with God","Direct","Honest, second-chance framing"),
        ("Behold, New Things: A 40-Day Journey of Fresh Starts","Promise","Isaiah 43:19 framing"),
        ("40 Days of Turning the Page","Direct","Simple, accessible metaphor for any transition season"),
        ("The 40-Day Reset: A New Rhythm for a New Season","Experience","Practical, habit-and-rhythm framing, strong New Year launch"),
        ("40 Days of a Do-Over That Actually Works","Direct","Honest, slightly playful framing for a fresh-start series"),
        ("New Mercies: A 40-Day Journey of Fresh Starts Every Morning","Promise","Lamentations 3:22-23 framing, daily-renewal emphasis"),
        ("40 Days of Leaving the Old Behind","Direct","Direct, decision-forward framing"),
        ("The Threshold: 40 Days of Stepping Into What's Next","Journey","Strong for a church moving into a new building or season"),
        ("40 Days of a Blank Page with God","Direct","Simple, hopeful, all-ages accessible framing"),
        ("Beginning Again: A 40-Day Journey After the Hard Season","Promise","Strong for a congregation coming out of genuine hardship"),
        ("40 Days of New Mercies Every Morning","Direct","Direct-title variant, daily-renewal framing"),
        ("The 40-Day Launch: Stepping Into God's New Thing","Experience","High-energy, strong for a church-plant or new-campus launch"),
        ("40 Days of Closing One Door, Opening Another","Direct","Transition-and-calling framing, strong for a life-stage series"),
        ("Fresh Start Family: A 40-Day Journey for Every Age and Stage","Promise","Genuinely all-ages framing, explicit kids-teens-adults design"),
        ("40 Days of What God Is Doing Next","Direct","Forward-looking, vision-adjacent closing-series title"),
    ])

print(f"Total categories: {len(CATEGORIES)}")
total_titles = sum(len(c['titles']) for c in CATEGORIES)
print(f"Total titles: {total_titles}")
