# -*- coding: utf-8 -*-
# Palacios Fine Art — Journey Library v2
# 15 categories x 10 journeys = 150. Each: title, values-title, subtitle, format, scripture, value anchor.
# Fields: (title, values_title_or_blank, subtitle, format, scripture, value_anchor)

CATS = [
("Rest & Renewal", "\u201cI\u2019m so tired I can\u2019t think straight.\u201d", [
 ("Breathe Again","","Ten quiet days for someone who has forgotten how to stop","10","Psalm 23:2\u20133 \u00b7 Matthew 11:28","Rest is a discipline, not a reward you earn"),
 ("Still Waters","Still Water","Five unhurried minutes at a time, and nothing else asked of you","10","Psalm 23:1\u20133 \u00b7 Mark 6:31","Stillness is what makes attention possible"),
 ("The Sabbath Palette","The Weekly Color","One color, one week, one rhythm you actually keep","10","Genesis 2:2\u20133 \u00b7 Exodus 20:8\u201310","One kept rhythm beats ten good intentions"),
 ("Permission to Stop","","Naming the thing you are allowed to put down this season","10","Psalm 46:10 \u00b7 Matthew 11:29","You are allowed to set something down"),
 ("The Quiet Hour","","Building one hour a week that belongs to nobody else","10","Mark 1:35 \u00b7 Psalm 62:1","Solitude is a skill, and it is learnable"),
 ("Enough for Today","","Ten days of not carrying tomorrow before it arrives","10","Matthew 6:34 \u00b7 Exodus 16:4","Sufficiency is steadier than accumulation"),
 ("Room to Breathe","","Three weeks of clearing space in a life that has none","21","Psalm 18:19 \u00b7 Psalm 31:8","Margin is created on purpose, never found"),
 ("Unhurried","","Learning a slower pace with a brush in your hand","21","Matthew 11:28\u201330 \u00b7 Isaiah 30:15","Pace determines presence"),
 ("The Well-Kept Week","","Three weeks of guarding what matters before it disappears","21","Psalm 90:12 \u00b7 Ecclesiastes 3:1","Attention is the scarcest resource you own"),
 ("Restored","","A full month of coming back to yourself, slowly","30","Psalm 23:3 \u00b7 Jeremiah 31:25","Recovery takes a season, not a weekend"),
]),
("Freedom & Perfectionism", "\u201cI\u2019m not creative. I\u2019d ruin it.\u201d", [
 ("Created Free","","Out of pressure and comparison, into play and grace","10","2 Corinthians 3:17 \u00b7 Galatians 5:1","Freedom is permission to make it badly"),
 ("The Ruined Page","","Ten days of marking the canvas on purpose","10","Isaiah 64:8 \u00b7 2 Corinthians 4:7","Begin before you are ready"),
 ("Good Enough","","A recovering perfectionist learns to call something finished","10","Philippians 1:6 \u00b7 Ecclesiastes 11:4","Finished teaches more than perfect"),
 ("The Inner Critic","","Give the voice a shape and a color, then work anyway","10","Romans 8:1 \u00b7 Psalm 139:14","Name the voice; it loses most of its power"),
 ("Play First","","Twelve short exercises that get your hands moving","10","Matthew 18:3 \u00b7 Psalm 126:2","Play is serious practice, not a break from it"),
 ("Nothing to Prove","","Ten days of making something for no one\u2019s approval","10","Galatians 1:10 \u00b7 Psalm 139:1","Worth is not earned by output"),
 ("Joy Restored","","Three weeks of recovering delight, play, and permission","21","Psalm 51:12 \u00b7 Nehemiah 8:10","Delight can be deliberately rebuilt"),
 ("Fearless Hands","","Undoing the voice that said you were never the creative one","21","2 Timothy 1:7 \u00b7 Joshua 1:9","Courage is a habit, not a temperament"),
 ("The Comparison Fast","","Twenty-one days without measuring yourself against anyone","21","Galatians 6:4\u20135 \u00b7 Psalm 16:5","Compare only to who you were yesterday"),
 ("Made to Make","","A month proving that you were, in fact, made for this","30","Genesis 1:27 \u00b7 Exodus 35:31\u201332","Everyone makes something; the only question is what"),
]),
("Grief & Loss", "\u201cI don\u2019t have words for this anymore.\u201d", [
 ("Beauty from Brokenness","","Gentle days written for the second year, not the first month","10","Isaiah 61:3 \u00b7 Psalm 34:18","Repair has a beauty of its own"),
 ("The Remembrance Piece","","A photograph, a phrase, a memory \u2014 made visible and kept","10","Psalm 56:8 \u00b7 Joshua 4:6\u20137","Memory deserves a form you can hold"),
 ("Light in the Darkness","","Hope worked slowly back into places that went quiet","10","John 1:5 \u00b7 Psalm 30:5","Hope returns in fragments before it returns whole"),
 ("Lament in Color","Sorrow in Color","Ten days of honest sorrow without hurrying it along","10","Psalm 13:1\u20132 \u00b7 Lamentations 3:19\u201323","Honest sorrow is not weakness"),
 ("The Empty Chair","","For a first holiday, birthday, or anniversary without them","10","Psalm 147:3 \u00b7 Revelation 21:4","Absence can be honored rather than avoided"),
 ("Carrying It Well","","Ten days learning to hold what will not be fixed","10","Matthew 5:4 \u00b7 2 Corinthians 1:3\u20134","Grief is carried, not solved"),
 ("Kintsugi","","Gold in the break: three weeks on the craft of repair","21","Isaiah 61:1\u20133 \u00b7 2 Corinthians 4:16\u201318","The mend can be the most beautiful part"),
 ("Seasons of Sorrow","","Three weeks tracing how grief actually moves","21","Ecclesiastes 3:4 \u00b7 Psalm 126:5\u20136","Grief moves in seasons, not stages"),
 ("What Remains","","Three weeks naming what loss could not take","21","Psalm 90:12 \u00b7 1 Corinthians 13:13","Loss clarifies what actually lasts"),
 ("A Crown of Beauty","","A month across a season of mourning, ending in something made","30","Isaiah 61:1\u20133 \u00b7 Psalm 30:11","Mourning turns \u2014 slowly, and with company"),
]),
("Direction & Discernment", "\u201cI don\u2019t know what season I\u2019m in.\u201d", [
 ("My Word for This Season","","Naming what is forming in you, then painting it where you\u2019ll see it","10","Proverbs 3:5\u20136 \u00b7 Psalm 25:4\u20135","One word focuses an entire year"),
 ("The Doorway","","The room you are leaving and the door you are standing in front of","10","Isaiah 43:18\u201319 \u00b7 Revelation 3:8","Leaving and entering are the same act"),
 ("Two Roads","","Scripture, counsel, and color for a decision you cannot make","10","Psalm 32:8 \u00b7 James 1:5","Decide with counsel and quiet, not pressure"),
 ("Listening","","Ten days of turning the volume down far enough to hear","10","1 Kings 19:11\u201312 \u00b7 John 10:27","Direction requires silence first"),
 ("The Next Right Thing","","Ten days of not needing the whole plan yet","10","Psalm 119:105 \u00b7 Proverbs 16:9","Clarity comes by walking, not by waiting"),
 ("What Am I For","","Ten days on purpose, before the next set of plans","10","Ephesians 2:10 \u00b7 Micah 6:8","Purpose precedes planning"),
 ("Sacred Seasons","","Discerning your season and marking the faithfulness inside it","21","Ecclesiastes 3:1\u20138 \u00b7 Psalm 1:3","Name the season honestly and it stops fighting you"),
 ("Wait Well","","Three weeks in the part nobody writes books about","21","Isaiah 40:31 \u00b7 Psalm 27:14","Waiting is active work"),
 ("Open Doors","","Testing an opening before you run through it","21","Proverbs 16:3 \u00b7 Psalm 37:4\u20135","Test the opening; opportunity is not always direction"),
 ("Courage to Begin Again","","A month of starting over, honestly and without hurrying","30","Joshua 1:9 \u00b7 Philippians 3:13\u201314","Starting over is a learnable skill"),
]),
("Identity & Belovedness", "\u201cI\u2019ve been everyone\u2019s everything for twenty years.\u201d", [
 ("Known by Name","","The names you are given, and the one you need this year","10","Isaiah 43:1 \u00b7 John 10:3","You are more than the roles you fill"),
 ("Beloved","Worthy","Ten days of identity, painted without a face","10","Zephaniah 3:17 \u00b7 1 John 3:1","Worth comes before usefulness"),
 ("The Labels","","Writing what you have been called \u2014 and covering it in color","10","Psalm 139:13\u201314 \u00b7 Isaiah 62:2","What you have been called is not what you are"),
 ("Who Am I Now","","For the season after the role you were known for ended","10","2 Corinthians 5:17 \u00b7 Psalm 71:17\u201318","Identity survives change; it just needs rewriting"),
 ("Unhidden","","Ten days of being seen without managing the impression","10","Psalm 139:1\u20133 \u00b7 Genesis 16:13","Being known is safer than being admired"),
 ("Enough","","Ten days of adding nothing in order to be worth something","10","2 Corinthians 12:9 \u00b7 Psalm 73:26","There is nothing to add to be worthy"),
 ("Rooted","","Three weeks of being grounded in something you did not earn","21","Jeremiah 17:7\u20138 \u00b7 Ephesians 3:17\u201319","Grounded comes before growing"),
 ("Her Voice","Your Voice","Three weeks of taking up the space you actually occupy","21","Proverbs 31:26 \u00b7 Esther 4:14","Your voice belongs in the room"),
 ("Beauty Reclaimed","","Three weeks on beauty that is not performance","21","1 Peter 3:3\u20134 \u00b7 Psalm 45:11","Beauty is not a performance for anyone"),
 ("Her Story in Color","Your Story in Color","A whole life mapped across one long canvas","30","Psalm 139:16 \u00b7 Revelation 12:11","A life told honestly is worth telling"),
]),
("Marriage & Couples", "\u201cWe want something better than another dinner out.\u201d", [
 ("The Art of Us","","Ten evenings, thirty questions, one canvas you share","10","Ecclesiastes 4:9\u201312 \u00b7 Genesis 2:24","Two people, one shared piece of work"),
 ("Canvas & Covenant","Canvas & Promise","Revisiting the promise and painting what has actually been kept","10","Song of Songs 8:6\u20137 \u00b7 Malachi 2:15","A promise is worth revisiting out loud"),
 ("Grace in the Gaps","Repair","For a couple finding their way back toward each other","10","Colossians 3:13 \u00b7 Ephesians 4:2\u20133","Repair matters more than being right"),
 ("Learning You Again","","Ten days of curiosity about a person you already know","10","1 Corinthians 13:4\u20137 \u00b7 Proverbs 5:18\u201319","Curiosity is the long fuel of a marriage"),
 ("Two Palettes","","One painting, two people, and everything that surfaces","10","Romans 12:10 \u00b7 Philippians 2:3\u20134","Compromise is a creative act"),
 ("The Table We Build","","Ten days on the home the two of you are actually making","10","Psalm 128:3 \u00b7 Acts 2:46","A home is constructed daily, not once"),
 ("The Story We\u2019re Writing","","Three weeks on the chapter still ahead of you","21","Isaiah 43:19 \u00b7 Psalm 90:17","The next chapter deserves to be chosen"),
 ("A Legacy of Love","","What this marriage hands down when neither of you is in the room","21","Deuteronomy 6:6\u20137 \u00b7 Psalm 78:4","A marriage leaves something behind either way"),
 ("Stronger Than We Knew","","Three weeks with what the two of you have already survived","21","Ecclesiastes 4:12 \u00b7 Romans 5:3\u20135","Endurance is a shared craft"),
 ("Covenant Renewed","Choosing Again","A month of choosing each other on purpose, fully","30","Hosea 2:19\u201320 \u00b7 Song of Songs 2:10\u201313","Choosing again is the whole practice"),
]),
("Family & Legacy", "\u201cWe want to leave them more than money.\u201d", [
 ("Legacy in Color","","Values, story, and blessing \u2014 finally made visible","10","Deuteronomy 6:6\u20139 \u00b7 Psalm 145:4","Values that are never named are rarely inherited"),
 ("Symbols We Live By","","Five family values, five images, one visual language","10","Joshua 4:6\u20137 \u00b7 Exodus 13:9","A family needs language for what it believes"),
 ("The Blessing","","A written and painted blessing for each child and grandchild","10","Numbers 6:24\u201326 \u00b7 Genesis 27:27\u201329","A blessing has to be spoken out loud to land"),
 ("The Stories We Keep","","Ten days recovering the stories nobody has written down","10","Psalm 78:3\u20134 \u00b7 Deuteronomy 4:9","Story outlives every possession"),
 ("The Table","","Ten days on the place your family actually becomes a family","10","Psalm 128 \u00b7 Acts 2:46\u201347","Families are built at tables, not in speeches"),
 ("More Than Money","","Ten days on what you want to transfer besides assets","10","Proverbs 13:22 \u00b7 Matthew 6:19\u201321","Wealth without meaning divides the people who receive it"),
 ("Handing It Down","","Three weeks naming the convictions you want to outlive you","21","2 Timothy 1:5 \u00b7 Psalm 71:18","Transfer requires intention or it does not happen"),
 ("The Family Mission","","Three weeks writing what this family is actually for","21","Joshua 24:15 \u00b7 Proverbs 29:18","A family without a stated purpose drifts to one"),
 ("Next Generation","","Three weeks preparing heirs rather than only heirlooms","21","Psalm 145:4 \u00b7 Proverbs 22:6","Prepare the people, not just the estate"),
 ("Generations","","A month-long family project ending in one heirloom piece","30","Psalm 102:18 \u00b7 Deuteronomy 7:9","What one generation names, the next can carry"),
]),
("Community & Worship", "\u201cWe want them to see it, not only hear it.\u201d", [
 ("The Word Made Visible","The Idea Made Visible","Ten days of seeing what you have only ever heard","10","Psalm 19:1 \u00b7 Habakkuk 2:2","Seeing deepens what hearing began"),
 ("Sacred Ordinary","The Sacred Ordinary","Ten days finding what is remarkable in an ordinary week","10","Colossians 3:17 \u00b7 1 Corinthians 10:31","Attention is what makes the ordinary matter"),
 ("Open Hands","","Ten days of holding what you have loosely","10","Psalm 24:1 \u00b7 1 Chronicles 29:14","What you grip too hard begins to grip you"),
 ("The Beauty of Holiness","The Beauty of Craft","Ten days treating craft itself as an act of devotion","10","Psalm 96:9 \u00b7 Exodus 31:1\u20135","Skill offered carefully is its own kind of reverence"),
 ("Together","","Ten days of making in company rather than alone","10","Hebrews 10:24\u201325 \u00b7 Acts 2:42","We make better things in the presence of others"),
 ("Prayer in Color","Reflection in Color","Ten days for when the words have run out","10","Psalm 141:2 \u00b7 Romans 8:26","When language fails, image still works"),
 ("Art as Worship","Art as Practice","A congregation-wide creative practice, licensed and self-run","21","Exodus 35:30\u201335 \u00b7 Psalm 150","Skill offered publicly becomes a gift"),
 ("A People of Beauty","A Culture of Beauty","Three weeks on what a community makes together","21","Ephesians 2:10 \u00b7 Psalm 27:4","Communities are known by what they make"),
 ("The Season of Light","","Three weeks of waiting, light, and hope","21","John 8:12 \u00b7 Isaiah 9:2","Light means more to people who have waited"),
 ("The Painted Liturgy","The Painted Season","Advent or Lent walked together, one image each week","30","Luke 1:46\u201355 \u00b7 Isaiah 40:3\u20135","A season walked together changes a community"),
]),
("Leaders & Burnout", "\u201cI don\u2019t remember the last thing I did for joy.\u201d", [
 ("Creative Sabbath","","Ten days for someone who genuinely does not know how to rest","10","Mark 6:31 \u00b7 Exodus 33:14","Rest is part of the work, not a reward for it"),
 ("The Output Detox","","Making things nobody will see, review, or measure","10","Psalm 127:1\u20132 \u00b7 Luke 10:41\u201342","Not everything you make needs an audience"),
 ("Presence Over Pressure","","Recovering imagination and joy without leaving the job","10","Psalm 16:11 \u00b7 Matthew 6:6","Presence outperforms pressure over any long run"),
 ("The Well","","Ten days on what you have been pouring out of","10","Isaiah 58:11 \u00b7 John 4:14","Nobody pours from an empty container"),
 ("Unseen Faithfulness","","Ten days on the work nobody claps for","10","Matthew 6:1\u20134 \u00b7 Colossians 3:23","Hidden work is still the work"),
 ("Leading From Rest","","Ten days on why a calm leader changes a whole room","10","Psalm 23:1\u20133 \u00b7 Hebrews 4:9\u201310","Calm is contagious; so is depletion"),
 ("Made to Flourish","","From surviving the work to actually living inside it","21","Psalm 92:12\u201314 \u00b7 John 15:5","Sustainable beats heroic every year"),
 ("The Long Obedience","The Long Game","Three weeks on endurance rather than intensity","21","Galatians 6:9 \u00b7 Hebrews 12:1","Endurance outlasts intensity"),
 ("Refilled","","Three weeks of putting back what leadership quietly drains","21","1 Kings 19:5\u20138 \u00b7 Psalm 103:5","Recovery is a practice, not an event"),
 ("The Second Wind","","A full month of coming back from empty","30","Isaiah 40:29\u201331 \u00b7 2 Corinthians 4:16","Depletion took months; recovery will too"),
]),
("Artists & Calling", "\u201cI think I\u2019m supposed to make things.\u201d", [
 ("Created to Create","Made to Make Things","Permission, identity, and the instinct to make","10","Genesis 1:27 \u00b7 Exodus 35:31\u201335","Making things is a human birthright"),
 ("Voice & Vocabulary","","Finding your actual signature instead of chasing what sells","10","1 Corinthians 12:4\u20136 \u00b7 Psalm 45:1","Your signature is discovered, not designed"),
 ("The Working Artist","","Pricing, commissions, and talking about money without apologizing","10","Proverbs 22:29 \u00b7 Colossians 3:23\u201324","Craft is a trade and deserves to be paid"),
 ("Fear of the Blank","","Ten days of beginning before you feel ready","10","2 Timothy 1:7 \u00b7 Psalm 90:17","The blank page is a threshold, not a verdict"),
 ("The Work of Your Hands","","Ten days on the dignity of skilled work","10","Psalm 90:17 \u00b7 Ecclesiastes 9:10","Good work done well carries its own dignity"),
 ("Show Your Work","","Ten days on visibility as generosity rather than ego","10","Matthew 5:14\u201316 \u00b7 Proverbs 18:16","Hiding good work helps nobody"),
 ("Comparison & Calling","Comparison & Craft","Three weeks with the thing that steals most artists\u2019 joy","21","Galatians 6:4 \u00b7 John 21:21\u201322","Run your own race or you will run nobody\u2019s"),
 ("The Discipline of Making","","Three weeks of showing up whether or not it is working","21","Proverbs 12:11 \u00b7 1 Corinthians 9:24\u201327","Consistency beats inspiration, permanently"),
 ("Faith & the Marketplace","Craft & the Marketplace","Three weeks on making a living by making things","21","Proverbs 16:3 \u00b7 Colossians 3:23","Meaningful work still has to be sold"),
 ("The Body of Work","","A month of daily making that ends in a real, showable series","30","Exodus 36:1\u20137 \u00b7 Psalm 90:17","A body of work is built one ordinary day at a time"),
]),
("Fear & Anxiety", "\u201cI can\u2019t turn my mind off.\u201d", [
 ("Do Not Be Afraid","Naming the Fear","Ten days of saying the fear out loud and watching it shrink","10","Isaiah 41:10 \u00b7 Joshua 1:9","A named fear is smaller than an unnamed one"),
 ("The Worry Map","","Sorting what is actually yours to carry from what is not","10","Matthew 6:25\u201327 \u00b7 Philippians 4:6\u20137","Most of what we carry was never ours"),
 ("Peace That Holds","","Ten days practicing a calm that survives contact with real life","10","John 14:27 \u00b7 Isaiah 26:3","Peace is practiced, not stumbled into"),
 ("What If","","Ten days of not rehearsing disasters that have not happened","10","Psalm 91:1\u20132 \u00b7 1 Peter 5:7","Rehearsing disaster costs you today"),
 ("Ground Yourself","","Ten short practices for returning to the present moment","10","Psalm 46:1\u20133 \u00b7 Psalm 62:6","The present is the only place you can act"),
 ("Sleep Again","","Ten evenings of putting the day down properly","10","Psalm 4:8 \u00b7 Proverbs 3:24","Nights can be reclaimed with a ritual"),
 ("Courage in Color","","Three weeks of doing the thing while still afraid","21","Deuteronomy 31:6 \u00b7 Psalm 27:1","Courage is repetition, not the absence of fear"),
 ("The Anxious Mind","","Three weeks of retraining where your attention goes","21","Philippians 4:8 \u00b7 Romans 12:2","Attention can be retrained like any muscle"),
 ("Held","Not Alone in It","Three weeks of learning you are not carrying this by yourself","21","Isaiah 43:2 \u00b7 Psalm 139:9\u201310","Almost nothing is meant to be carried alone"),
 ("Unafraid","Steadier Ground","A month toward steadier ground","30","Psalm 23:4 \u00b7 2 Timothy 1:7","Steadiness is built in ordinary days"),
]),
("Gratitude & Wonder", "\u201cI want to notice my life while I\u2019m still in it.\u201d", [
 ("Gratitude in Color","","Ten days of noticing, in paint, what you usually walk past","10","1 Thessalonians 5:16\u201318 \u00b7 Psalm 100:4","Noticing changes how a day feels"),
 ("Seeing Beauty","","Ten days of looking on purpose","10","Psalm 19:1\u20134 \u00b7 Philippians 4:8","Beauty has to be looked for to be found"),
 ("Small Mercies","Small Graces","Ten days of the daily rather than the dramatic","10","Lamentations 3:22\u201323 \u00b7 Psalm 68:19","The daily is where most of the good actually lives"),
 ("The Gratitude Wall","","Ten days building something you will keep seeing","10","Psalm 103:2 \u00b7 Deuteronomy 8:2","Remembering out loud is a practice"),
 ("Wonder Again","","Ten days of recovering the thing children have and adults lose","10","Matthew 18:3 \u00b7 Psalm 8:3\u20134","Wonder is recoverable at any age"),
 ("Enough and More","","Ten days of abundance as a lens rather than a bank balance","10","Psalm 23:5 \u00b7 2 Corinthians 9:8","Abundance is mostly a way of looking"),
 ("A Thankful Life","","Three weeks turning gratitude from a mood into a habit","21","Colossians 3:15\u201317 \u00b7 Psalm 107:1","Gratitude is a habit before it is a feeling"),
 ("Eyes to See","","Three weeks of trained attention","21","Psalm 119:18 \u00b7 Matthew 13:16","What you train yourself to see, you see"),
 ("The Ordinary Miracle","","Three weeks on everyday awe","21","Psalm 145:5 \u00b7 Acts 17:28","Ordinary things repay close attention"),
 ("A Month of Wonder","","Thirty days of noticing, recorded in color","30","Psalm 65:8 \u00b7 Job 12:7\u20139","A month of noticing changes a year of living"),
]),
("Work & Calling", "\u201cThere has to be more to this than Monday.\u201d", [
 ("Monday Morning","","Ten days on the dignity of the work in front of you","10","Colossians 3:23 \u00b7 1 Corinthians 10:31","Ordinary work is dignified work"),
 ("More Than a Job","","Ten days finding meaning inside the role you already have","10","Ephesians 2:10 \u00b7 Proverbs 16:3","Meaning is usually found in place, not elsewhere"),
 ("The Hard Season at Work","","Ten days of enduring without shrinking","10","Psalm 37:5\u20137 \u00b7 Galatians 6:9","Hard seasons end; who you become in them does not"),
 ("Ambition, Rightly Held","","Ten days on wanting things without being owned by them","10","Jeremiah 45:5 \u00b7 Philippians 2:3\u20134","Ambition needs a governor or it takes the wheel"),
 ("Retiring Well","","Ten days ending a career on purpose rather than by default","10","Psalm 71:18 \u00b7 Proverbs 16:31","An ending deserves as much design as a beginning"),
 ("What I\u2019m Good At","","Ten days naming your strengths without flinching","10","Romans 12:6 \u00b7 1 Peter 4:10","Strengths are a stewardship, not a boast"),
 ("Called, Not Just Employed","Work Worth Doing","Three weeks on vocation rather than occupation","21","1 Corinthians 7:17 \u00b7 Colossians 3:23\u201324","Vocation is bigger than the job title"),
 ("Rebuilding After a Loss","","Three weeks after the layoff, the failure, or the ending","21","Job 42:10 \u00b7 Joel 2:25","A setback is data, not a verdict"),
 ("The Second Half","","Three weeks designing the years everyone assumes are winding down","21","Psalm 90:12 \u00b7 Psalm 92:14","The best years need a plan like any other"),
 ("The Work Worth Doing","","A month on what you are actually for","30","Ephesians 2:10 \u00b7 Proverbs 19:21","Purpose is discovered by working, not by waiting"),
]),
("Money & Generosity", "\u201cWe have more than we need and less peace than we expected.\u201d", [
 ("Everything Belongs","It Isn\u2019t All Mine","Ten days on the difference between owning and stewarding","10","Psalm 24:1 \u00b7 1 Chronicles 29:14","You are a steward of everything you hold"),
 ("Generous by Design","","Ten days on giving that is planned rather than reactive","10","2 Corinthians 9:6\u20138 \u00b7 Proverbs 11:24\u201325","Generosity works best when it is designed"),
 ("Contentment","","Ten days deciding what enough actually looks like","10","Philippians 4:11\u201313 \u00b7 1 Timothy 6:6\u20138","Enough is a decision, never an amount"),
 ("The Grip","","Ten days on what you are holding too tightly","10","Matthew 6:19\u201321 \u00b7 Luke 12:15","What you grip too hard ends up gripping you"),
 ("Giving Together","","Ten days of deciding as a family where it goes","10","Acts 4:32\u201335 \u00b7 2 Corinthians 8:1\u20135","Shared giving bonds the people who do it"),
 ("The First Yes","","Ten days on giving first rather than last","10","Proverbs 3:9\u201310 \u00b7 Malachi 3:10","What comes first reveals what comes first"),
 ("A Generous Family","","Three weeks teaching generosity to people who are watching you","21","Deuteronomy 15:10 \u00b7 1 Timothy 6:17\u201319","Generosity is caught before it is taught"),
 ("Wealth With Meaning","","Three weeks on what money is revealing about your values","21","Ecclesiastes 5:10\u201311 \u00b7 Luke 16:10\u201311","Money is the loudest statement of values you make"),
 ("The Giving Journey","","Three weeks on how generosity grows in stages","21","2 Corinthians 9:10\u201311 \u00b7 Luke 6:38","Generosity matures like anything else practiced"),
 ("Beyond the Estate","","A month on what actually transfers when the documents are done","30","Proverbs 13:22 \u00b7 Matthew 25:14\u201321","Documents move assets; conversations move values"),
]),
("Friendship & Belonging", "\u201cI have a full calendar and almost nobody to call.\u201d", [
 ("The Long Table","","Ten days on hospitality as an ordinary practice","10","Romans 12:13 \u00b7 Hebrews 13:2","Hospitality is a practice, not a personality"),
 ("Known","","Ten days on the difference between being liked and being known","10","Proverbs 17:17 \u00b7 John 15:15","Being known takes time nobody feels they have"),
 ("The Lonely Season","","Ten days for a stretch you did not expect to be in","10","Psalm 68:6 \u00b7 Psalm 25:16","Loneliness is common and not shameful"),
 ("Friendship in Color","","Ten days of making something alongside someone","10","Ecclesiastes 4:9\u201310 \u00b7 1 Samuel 18:1","Friendship needs occasions, not intentions"),
 ("Making Room","","Ten days of widening the circle you already have","10","Romans 15:7 \u00b7 Luke 14:13\u201314","Belonging has to be offered before it is felt"),
 ("Hard Conversations","","Ten days on the talk you have been avoiding","10","Proverbs 27:6 \u00b7 Ephesians 4:15","Truth kindly told is what keeps friendships"),
 ("The Circle","","Three weeks building the community you keep waiting to find","21","Acts 2:44\u201347 \u00b7 Galatians 6:2","Community is built, never discovered"),
 ("Beginning Again","","Three weeks on making real friends after fifty","21","Ecclesiastes 4:12 \u00b7 Proverbs 18:24","New friendship is possible at any age"),
 ("The Welcome","","Three weeks of hosting rather than waiting to be invited","21","1 Peter 4:9 \u00b7 Romans 12:10","Host; do not wait to be hosted"),
 ("Together for Good","","A month of showing up for the same people repeatedly","30","Hebrews 10:24\u201325 \u00b7 Psalm 133:1","Showing up repeatedly is the whole secret"),
]),
]

# ---- integrity checks ----
titles = []
fmts = {"10":0,"21":0,"30":0}
for c in CATS:
    assert len(c[2]) == 10, (c[0], len(c[2]))
    for j in c[2]:
        assert len(j) == 6, j
        titles.append(j[0]); fmts[j[3]] += 1
assert len(CATS) == 15, len(CATS)
dupes = set([t for t in titles if titles.count(t) > 1])
print("categories:", len(CATS), "journeys:", len(titles), "unique:", len(set(titles)))
print("format split:", fmts)
if dupes: print("DUPLICATE TITLES:", dupes)
