# (theme, category#, scripture, felt need, [(title, subtitle) x20])
THEMES_A = [
("Made for This",1,"Ephesians 2:10","I don't know why I'm here",[
("Made for This","You were created on purpose"),("The Masterpiece","God's workmanship, your calling"),
("Prepared in Advance","Good works with your name on them"),("Wired by Design","Gifts, passions & personality"),
("Not an Accident","The story behind your story"),("Fearfully & Wonderfully","Loving how God made you"),
("Handcrafted","No one else can be you"),("The Original","Escaping the copy-paste life"),
("For Such a Time","Esther's courage, your moment"),("The Potter's Hands","Shaped for something more"),
("Blueprints","Discovering your God-given design"),("Made to Matter","Significance beyond success"),
("Custom Built","Your shape, your assignment"),("The Craftsman's Mark","Bearing the Maker's image"),
("On Purpose","Living intentionally every day"),("Designed for Good","Work that outlasts you"),
("More Than a Résumé","Identity beneath the achievements"),("The Reason You're Here","Answering life's biggest question"),
("Uniquely You","Comparison-free living"),("Signature","The life only you can live")]),
("Who You Are",1,"1 Peter 2:9","I don't know who I am anymore",[
("Who You Are","Identity that can't be shaken"),("Child of God","The name above every label"),
("In Christ","The truest thing about you"),("The Mirror","Seeing yourself as God sees you"),
("Beloved","The voice that ends striving"),("New Name","Leaving old labels behind"),
("Whose You Are","Identity starts with belonging"),("Unfiltered","Real identity in a filtered world"),
("The Imposter Cure","Ending the fear of being found out"),("Secure","Confidence that isn't arrogance"),
("Image Bearers","Made to reflect God"),("Set Free","From performing to belonging"),
("Adopted","Full rights of a son or daughter"),("The Approval Trap","Freedom from people-pleasing"),
("Enough Already","Resting from proving yourself"),("Named","What God calls you matters most"),
("Heirs","Your inheritance in Christ"),("Identity Theft","Taking back who you really are"),
("Rooted Identity","Deeper than roles and seasons"),("You Are Here","Identity for a new chapter")]),
("Significance",1,"Psalm 139:13-14","Does my life matter?",[
("Significance","Your life matters more than you know"),("The Dash","Making the years between count"),
("Ripples","Small faithfulness, lasting impact"),("Seen","The God who notices you"),
("Ordinary Heroes","Everyday lives, eternal weight"),("The Widow's Mite","Small gifts God calls great"),
("Counted","No forgotten people in God's story"),("Your Corner of the World","Influence where you already are"),
("Eternal Weight","Living for the long game"),("Mustard Seed","The math of the Kingdom"),
("Unsung","Faithfulness nobody applauds"),("The Cloud of Witnesses","Joining a bigger story"),
("Every Number Has a Name","Why individuals matter to God"),("Salt & Light","Quiet influence that changes rooms"),
("More Than a Moment","A life that echoes"),("Well Done","The only review that matters"),
("Hidden Years","When God works in obscurity"),("The Faithful Years","Significance through consistency"),
("Legacy of One","What one surrendered life can do"),("It All Counts","No wasted days in God's economy")]),
("Purpose",1,"Jeremiah 29:11","What am I supposed to do with my life?",[
("40 Days of Purpose","The churchwide journey"),("The Why","Getting to the reason underneath"),
("Driven","Purpose that moves you"),("True North","Direction for the decade ahead"),
("The Compass","Five questions that set your course"),("Next","Purpose for your new season"),
("Assignment","What God is asking of you now"),("The Sweet Spot","Where gifts meet needs"),
("Wake Up Call","From drifting to directed"),("Onward","Purpose after the plan fell apart"),
("The Second Half","Purpose after fifty"),("Say Yes","Obedience one step at a time"),
("Threads","Seeing purpose in your whole story"),("Why You Work","Vocation as calling"),
("The Deep End","Trading comfort for calling"),("Course Correct","It's not too late to start"),
("Purpose in the Pause","When life puts you on hold"),("Aim","Goals that honor God"),
("The One Thing","Focus in a distracted age"),("Finish the Race","Purpose that goes the distance")]),
("Calling",1,"Romans 12:6-8","Is there more than this?",[
("Calling","Hearing the voice that names you"),("Here Am I","Answering when God speaks"),
("The Nudge","Following holy promptings"),("Burning Bush","Ordinary ground, holy moments"),
("Sent Ones","Every believer commissioned"),("The Summons","When God interrupts your plans"),
("Full-Time Faith","Called beyond Sunday"),("Tentmakers","Calling in the marketplace"),
("The Reluctant Yes","Moses, fear & obedience"),("Anointed","Set apart for service"),
("Open Doors","Discerning God's invitations"),("The Voice","Learning to recognize God"),
("Called Together","Discovering calling as a couple"),("Little Ways","Great love in small tasks"),
("Deploy","Your gifts, God's mission"),("Answer the Call","Stop waiting for certainty"),
("Vocation","Work as worship"),("Called to Stay","When obedience means remaining"),
("Called to Go","When obedience means leaving"),("The Commissioning","Stepping into your assignment")]),
("Peace",2,"John 14:27","My mind never stops racing",[
("40 Days of Peace","From anxiety to anchored"),("Perfect Peace","A mind stayed on God"),
("The Exchange","Trading worry for trust"),("Shalom","Wholeness in every direction"),
("Peace That Passes","Beyond-understanding calm"),("Guarded","Hearts and minds kept safe"),
("Still Waters","Psalm 23 for stressed people"),("The Peacemaker","Bringing calm into conflict"),
("Untroubled","Jesus' parting gift"),("Quiet the Noise","Stillness in a loud world"),
("Sleep in the Storm","Rest when life rocks"),("De-escalate","Peace practices for hot moments"),
("The Worry Fast","40 days without borrowing trouble"),("Breathe Deep","Prayer for anxious moments"),
("Even Now","Peace in an uncertain world"),("Steadfast","A settled heart in shifting times"),
("Peace at Home","Lowering the temperature under your roof"),("Cease Fire","Ending the war inside"),
("The Gift","Receiving what Jesus left behind"),("All Is Well","Learning the anthem of trust")]),
("Unshaken",2,"Psalm 16:8","Everything feels unstable",[
("Unshaken","Standing when everything moves"),("On the Rock","A foundation that holds"),
("Immovable","Steadfast in shifting culture"),("The House That Stood","Building on bedrock"),
("Firm Footing","Confidence for slippery seasons"),("Earthquake Proof","Faith that survives the shaking"),
("Bedrock","What remains when all else falls"),("Steady On","Endurance for the long storm"),
("The Anchor Holds","Hope behind the veil"),("Fortress","God our refuge and strength"),
("Not Moved","Psalm 16 for hard days"),("Weathered","Stronger after the storm"),
("Roots Before Fruits","Depth that withstands drought"),("Holding Fast","Grip strength for your faith"),
("The Unshakable Kingdom","What cannot be taken"),("Braced","Ready before trouble comes"),
("Stand Firm","Ephesians 6 for daily battles"),("Ballast","Inner weight for outer waves"),
("After the Shaking","Rebuilding on what remains"),("Still Standing","Testimonies of endurance")]),
("Rest",2,"Matthew 11:28-30","I'm exhausted all the time",[
("Rest","Unforced rhythms of grace"),("Sabbath","The gift you keep refusing"),
("The Off Switch","Learning to stop"),("Come Away","Retreating with Jesus"),
("Margin","Breathing room by design"),("The Unhurried Life","Slowing to the speed of grace"),
("Recovering From Burnout","Gentle steps back to whole"),("Lighten the Load","Yokes easy, burdens light"),
("Bread & Rest","Elijah's gentle recovery"),("Green Pastures","Letting the Shepherd lead"),
("Off the Clock","Trusting God with unfinished work"),("Selah","Sacred pauses in a rushed life"),
("Rhythms","Work, rest, worship, repeat"),("The Seventh Day","Why God rested first"),
("Permission to Stop","Grace for the driven"),("Recharge","Soul care that actually works"),
("Slow","The spiritual discipline of unhurry"),("Rest for Caregivers","Sustaining the ones who sustain"),
("Sabbath Beyond Sunday","Rest as a way of life"),("Deep Rest","Sleep, soul & sanity")]),
("Fear Not",2,"Isaiah 41:10","Fear is running my decisions",[
("Fear Not","The Bible's most repeated command"),("Do It Afraid","Courage isn't the absence of fear"),
("The Lion's Den","Faith in frightening places"),("Every Morning Brave","Daily courage from daily mercy"),
("Brave","Ordinary courage for ordinary people"),("What If","Answering anxiety's favorite question"),
("The Other Boat","Jesus in your storm"),("Giants","Facing what towers over you"),
("Take Heart","Jesus has overcome"),("No Fear in Love","How love evicts fear"),
("The Shadow Valley","Walking through, not around"),("Fear of Man","Escaping the approval cage"),
("Afraid of the Dark","Light for life's unknowns"),("The Worst Case","When fear meets sovereignty"),
("Lionhearted","Bold as the righteous"),("Fear of the Future","Trusting the God already there"),
("Steel & Velvet","Gentle strength under pressure"),("Front Line","Courage for public faith"),
("The Red Sea Road","When there's no way out"),("Fearless Parenting","Raising kids without panic")]),
("Anxious for Nothing",2,"Philippians 4:6-7","Anxiety controls my days",[
("Anxious for Nothing","Philippians 4 for modern minds"),("Present Over Panic","Prayer in every situation"),
("Overthinkers Anonymous","Rest for racing minds"),("Spiral","Stopping anxious thoughts early"),
("Cast It","Throwing your cares on him"),("The Peace Protocol","Daily practice for anxious days"),
("Birds & Lilies","The Sermon-on-the-Mount cure"),("Tomorrow's Trouble","Living one day at a time"),
("Untangled","Loosening anxiety's knots"),("The Grateful Reset","How thanksgiving rewires worry"),
("Mind Renewal","Taking thoughts captive"),("Panic to Prayer","A new first response"),
("White-Knuckle Faith","Releasing your grip"),("Inner Quiet","Practices for a settled soul"),
("Anxious Parents","Peace for the ones raising kids"),("Test Day","Peace for students under pressure"),
("The News Fast","Peace in an outraged age"),("Enough for Today","Manna-style trust"),
("Set It Down","Releasing what you carry"),("He Cares for You","The truth beneath the verse")]),
("Love That Lasts",3,"1 Corinthians 13:4-7","We're drifting apart",[
("Love That Lasts","Building a marriage for decades"),("The Long Love","Romance beyond the honeymoon"),
("Still the One","Choosing each other again"),("Golden","Lessons from fifty-year couples"),
("The Slow Burn","Deep love over fast feelings"),("Anniversary","Celebrating & recommitting"),
("Love Is","First Corinthians 13, lived"),("Through Every Season","Vows for real life"),
("The Daily I Do","Small choices, lasting marriage"),("Keeping the Spark","Delight after the decades"),
("Grow Old With Me","A vision for the far future"),("The Third Strand","God at the center"),
("First Love","Remembering why you married"),("Love After Loss","Marriage through grief together"),
("The Empty Nest Marriage","Rediscovering us"),("Weathering","Love through hard years"),
("Tend the Garden","Daily care for a living love"),("Promises Kept","The power of covenant faithfulness"),
("Better With Time","Aging love, deepening joy"),("Date Night Forever","Playfulness that protects marriage")]),
("Better Together",3,"Ecclesiastes 4:9-12","We feel like roommates",[
("Better Together","Why we need each other"),("Team Us","From roommates to teammates"),
("Two Becoming One","Unity without losing yourself"),("Side by Side","Facing life shoulder to shoulder"),
("The Home Team","Winning at home first"),("In Sync","Aligning calendars, money & dreams"),
("Pulling Together","One direction, two people"),("The Great Alliance","Marriage as partnership"),
("Shared Load","Dividing labor with grace"),("Dream Again","Building a future together"),
("Us Against the Problem","Fighting fair, together"),("The Couple's Compass","Making decisions as one"),
("Two Are Better","Ecclesiastes for couples"),("Joint Venture","Money & marriage in step"),
("The Balanced Yoke","Equally matched, equally committed"),("Together Through Transition","Moving, jobs & new seasons"),
("New Parents, Same Team","Marriage after baby"),("The Blend","Becoming one blended family"),
("Empty Nest, New Us","Partnership's second act"),("Retire Together","A shared vision for the next chapter")]),
("Covenant",3,"Malachi 2:14-15","We're not sure we'll make it",[
("Covenant","More than a contract"),("The Vow","Words that hold a life"),
("Witness","God in your marriage story"),("Unbreakable Promise","Covenant when feelings fade"),
("The Ring","What the circle means"),("For Better or Worse","Loving through the worst"),
("In Sickness","Marriage through illness"),("A Love That Finishes","Faithfulness to the end"),
("Sacred Knot","Why God ties marriages"),("Renewal","Re-saying your vows with new depth"),
("Hesed","The loyal love of God, at home"),("Faithful","Fidelity in a faithless age"),
("Guard Your Heart","Protecting the covenant"),("Rebuilding Trust","Repair after betrayal, with help"),
("The Second Yes","Recommitting after crisis"),("Covenant Kids","What your marriage teaches them"),
("The Longest Promise","Endurance as love language"),("First Comes Faith","Engaged couples & covenant"),
("The Wedding Sermon","What your marriage preaches"),("Anchor of Home","Covenant as family stability")]),
("Stronger",3,"Song of Songs 8:6-7","Our marriage needs a reset",[
("Stronger","A 40-day marriage reset"),("The Marriage Tune-Up","Small fixes, big difference"),
("From Good to Great","Upgrading a fine marriage"),("The Reset","Starting over without starting over"),
("Marriage Strong","Training for the long haul"),("Repair","Mending what's frayed"),
("The Comeback Couple","Hope after hard years"),("Rekindled","Warmth after a cold season"),
("Ten Rounds","Fighting for, not with, each other"),("Skills of Love","What healthy couples practice"),
("Speak Life","Words that build your spouse"),("The Apology","Repair after rupture"),
("Forgive Forward","Releasing the record of wrongs"),("Closer","Rebuilding intimacy after distance"),
("The Pursuit","Dating your spouse again"),("Storm-Tested","Stronger after the crisis"),
("Iron Couples","Sharpening one another"),("The Growth Plan","A yearly rhythm for marriage"),
("Stronger After Loss","Grieving together, growing together"),("The Marriage Check-In","Weekly questions that change everything")]),
("Communication",3,"James 1:19","We can't talk without fighting",[
("Communication","Talking without fighting"),("Quick to Listen","James 1:19 at home"),
("The Pause","Responding instead of reacting"),("Say What You Mean","Honesty with kindness"),
("Decode","Understanding how your spouse hears"),("The Heat Index","Cooling conflict before it burns"),
("Words That Heal","Speech that restores"),("The Unsaid","Surfacing what silence buries"),
("Listen Louder","Hearing the heart behind the words"),("Fight Right","Rules of engagement for couples"),
("The Weekly Sit-Down","A rhythm of real talk"),("Tone","It's not what you said…"),
("Ask Better Questions","Curiosity as love"),("The Repair Attempt","Small moves that save arguments"),
("Screens Down","Presence over devices"),("Talking Money","The conversation couples avoid"),
("Talking In-Laws","Boundaries with grace"),("Talking Kids","Parenting on the same page"),
("Hard Conversations","Saying the difficult thing well"),("The Blessing of Words","Speaking future over each other")]),
("Family Legacy",4,"Psalm 78:4-7","What will survive me?",[
("40 Days of Family Legacy","What will survive you"),("Behind the Wealth","The life your money can't measure"),
("Lasting Wealth","Passing down more than money"),("Preparing the Ones You Love","Getting heirs ready"),
("The Family Table","Conversations that change generations"),("Generations","Faith that outlives you"),
("The Blessing","Speaking life over your grandchildren"),("Heirlooms","The stories behind what we keep"),
("Our Family Story","Where you came from & why it matters"),("House of Values","Naming what your family stands for"),
("The First Family Meeting","Starting the conversation"),("The Responsible Heir","Raising kids who can handle it"),
("Beyond the Estate Plan","What documents can't do"),("Legacy Letters","Writing what they need to hear"),
("The Ethical Will","Leaving wisdom, not just wealth"),("The Long View","Thinking in generations"),
("Handing It Down","Transferring what matters"),("Unity","Keeping family whole when wealth could divide"),
("Succession","Handing over the keys"),("After the Sale","Who we are when the business is gone")]),
("Passing Down Faith",4,"Deuteronomy 6:6-7","Will my kids own their faith?",[
("Passing Down Faith","The inheritance money can't buy"),("Deuteronomy Six","Faith talk on the way"),
("The Faith Baton","A clean handoff between generations"),("Tell the Next Generation","Psalm 78 for families"),
("Dinner Table Discipleship","Faith over food"),("The Family Altar","Reviving household worship"),
("Stories of God","Testimony as inheritance"),("Faith They Own","From borrowed belief to their own"),
("The Question Jar","Letting kids ask anything"),("Milestones","Marking spiritual moments"),
("The Prodigal's Parent","Hope for wandering kids"),("Grandma's Bible","Heirloom faith"),
("Everyday Liturgy","Small habits, deep roots"),("The Doubter's Dinner","Making room for questions"),
("Raising Worshipers","More than church attendance"),("The Family Creed","What we believe around here"),
("Bedtime Blessings","Ending days with truth"),("Faith in the Car","Discipleship in transit"),
("The Send-Off","Blessing kids as they launch"),("Three Generations Deep","Grandparents, parents & kids together")]),
("Parenting on Purpose",4,"Proverbs 22:6","I'm parenting on autopilot",[
("Parenting on Purpose","Off autopilot, on mission"),("The Intentional Home","Designing family culture"),
("Begin With the End","Parenting toward age 25"),("The Family Playbook","Values, rules & rhythms"),
("Shepherding Hearts","Beyond behavior management"),("First Five Years","Foundations for littles"),
("The Middle Years","Parenting ages 6–12"),("Raising Teens","Staying connected through adolescence"),
("The Launch Plan","Preparing them to leave well"),("Discipline That Disciples","Correction with connection"),
("Screens & Souls","Technology with wisdom"),("The Overscheduled Family","Choosing less on purpose"),
("One-on-One","The power of individual time"),("Catch Them Doing Good","Encouragement as strategy"),
("The Family Meeting","Giving kids a voice"),("Praying Parents","Interceding for your children"),
("Single & Strong","Purposeful single parenting"),("The Village","Building your family's support team"),
("Grace-Based Home","When kids (and parents) fail"),("Parenting Together","One team, one plan")]),
("Grandparent Legacy",4,"Psalm 71:18","How do I bless my grandchildren?",[
("Grandparent Legacy","40 days to bless the next generation"),("The Grand Influence","Your outsized role"),
("The Psalm 71 Project","Declaring his power to the next generation"),("Cookies & Catechism","Faith in grandma's kitchen"),
("The Storyteller","Passing down the family story"),("Long-Distance Grandparenting","Close hearts across miles"),
("The Grandparent's Prayer","Covering them daily"),("Wisdom Keepers","What only elders can give"),
("Grace & Gifts","Spoiling them toward Jesus"),("Summer at Grandpa's","Making memories that disciple"),
("The Second Chance","Grandparenting after parenting regrets"),("Grand Camp","A week that marks a life"),
("The Blessing Bench","Words every grandchild needs"),("Skip-Generation Faith","When you're the spiritual anchor"),
("The Legacy Box","Letters, photos & faith"),("Backup, Not Boss","Supporting without overstepping"),
("The Family Historian","Capturing a century"),("New Grandparent","Starting the role well"),
("Grand Finale","Finishing your race in front of them"),("The Inheritance of Prayer","A prayer legacy they'll feel")]),
("Family Mission",4,"Joshua 24:15","Why does our family exist?",[
("Family Mission","Why your family exists"),("As for Me and My House","Joshua's declaration, your home"),
("The Family Mission Statement","Writing your why"),("On Mission Together","Serving as a household"),
("The Family Vision Retreat","A weekend that sets direction"),("Our Family Values","Choosing five that define you"),
("The Sending Family","A home that launches people"),("Mission Trip: Home","Serving your own street"),
("The Open Door","Hospitality as family calling"),("Family on Assignment","Discerning your shared work"),
("The Giving Family","Generosity as household identity"),("Adopt a Cause","Choosing your family's fight"),
("The Yearly Summit","Annual planning with purpose"),("The Family Crest","Symbols of what you stand for"),
("Everyone Plays","Gifts of every family member"),("The Neighbor Plan","Loving the five houses nearest"),
("Missional Holidays","Redeeming your calendar"),("Work With a Why","The family business of blessing"),
("Passing the Torch","Kids leading the mission"),("A House for God","Making home a lighthouse")]),
("God Owns It All",5,"Psalm 24:1","Whose money is it, really?",[
("God Owns It All","Freedom, wisdom & generosity"),("The Owner's Manual","Managing what belongs to God"),
("Whose Money Is It?","The question that changes everything"),("The Trustee","Living as a manager, not an owner"),
("The Psalm 24 Life","The earth is the Lord's"),("Deed Transfer","Signing it all over"),
("The Steward's Prayer","Daily surrender of stuff"),("Loose Grip","Receiving & releasing"),
("The Audit","A loving look at your money story"),("It Was Never Yours","The relief of stewardship"),
("The Master's Money","Parable of the talents, applied"),("Account","Living ready to give one"),
("On Loan","Temporary custody, eternal purpose"),("The Big Release","Letting go of ownership anxiety"),
("Owner to Steward","A 40-day identity shift"),("Off the Top","Honoring God first"),
("The Storehouse","Provision & trust"),("Everything Under Heaven","Job's God, your finances"),
("Signature Authority","Spending like it's his"),("The Stewardship Family","Teaching kids God owns it all")]),
("Money Wise",5,"Proverbs 3:9-10","I need practical wisdom with money",[
("Money Wise","Practical wisdom with money"),("Proverbs & Pennies","Ancient wisdom, modern wallet"),
("The Wise Builder","Financial foundations that last"),("Slow Money","Steady plans, growing gains"),
("The Ant's Way","Diligence & saving"),("Counsel","Why wise people ask for help"),
("The Budget Blessing","A plan that brings peace"),("Debt-Free Direction","A gentle path out"),
("The Rainy Day","Wisdom for emergencies"),("Big Purchases","Discernment before buying"),
("Before You Sign","Wisdom for contracts & commitments"),("Teach Them Young","Money lessons for kids"),
("The College Question","Wisdom for the biggest decision"),("House Wisdom","Buying a home God's way"),
("The Raise","Stewarding an increase"),("Windfall","Wisdom for sudden money"),
("Two Incomes, One Plan","Couples & money"),("The Retirement Runway","Wisdom for the descent"),
("Prudence Without Fear","Insurance, planning & trust"),("The Wise Giver","Generosity with discernment")]),
("Money Made Simple",5,"Proverbs 21:5","Money feels overwhelming",[
("Money Made Simple","Overwhelm to order"),("The One Page Plan","Your finances on a single sheet"),
("Four Buckets","Give, save, spend, grow"),("Start Where You Are","First steps without shame"),
("The Money Date","A monthly hour that changes everything"),("Automatic","Set-and-forget stewardship"),
("Small Steps","Tiny habits, big turnaround"),("Simple Limits","Old tools for modern peace"),
("Declutter Your Money","Fewer accounts, clearer mind"),("The Simple Budget","Three numbers to know"),
("Cut the Noise","Ignoring bad money advice"),("The Beginner's Guide","Money basics with grace"),
("The Checklist","Twelve tasks for financial order"),("Paper to Peace","Organizing the file drawer"),
("Money for Newlyweds","Starting simple together"),("The First Paycheck","A student's guide"),
("Simple Generosity","Giving without complexity"),("The Reset Month","Thirty days to order"),
("Enough Math","Calculating your contentment line"),("Keep It Simple","Guardrails against complexity")]),
("Contentment",5,"Philippians 4:11-13","I always want more",[
("Contentment","The secret Paul learned"),("Enough","Escaping the more trap"),
("The Comparison Fast","40 days without measuring"),("Full","Satisfied in every circumstance"),
("The Upgrade Cycle","Getting off the treadmill"),("Rich Toward God","Redefining wealth"),
("The Grateful Ledger","Counting what you have"),("Want Less","The freedom of fewer desires"),
("The Ceiling","Choosing a lifestyle cap"),("Godliness With Gain","First Timothy's formula"),
("Neither Poverty Nor Riches","The Proverbs 30 prayer"),("The Joneses","Retiring from keeping up"),
("Abundant Enough","Plenty redefined"),("Plenty & Need","Steady in both seasons"),
("The Anti-Ad","Resisting manufactured desire"),("Home Sweet Enough","Contentment with your house"),
("The Contented Kid","Raising gratitude in a gimme world"),("Slow Wants","Waiting before wanting"),
("The Thanks Habit","Gratitude as money strategy"),("Already Rich","Seeing your real wealth")]),
("First Things First",5,"Matthew 6:33","My priorities are out of order",[
("First Things First","Getting priorities in order"),("Seek First","Matthew 6:33 as operating system"),
("The Top Line","Giving before spending"),("Tithe & Trust","The first tenth"),
("The Priority Audit","Where your money says you worship"),("Calendar & Checkbook","The two truest documents"),
("God First Finances","Reordering the flow"),("The Altar of More","Tearing down money idols"),
("Treasure Map","Where your treasure leads your heart"),("The First Hour","Morning priorities that shape money"),
("Kingdom First Family","Household priorities reset"),("No Other Gods","Money as modern idol"),
("The Reorder","40 days of realignment"),("Margin First","Building space before spending"),
("The First Check","The discipline of priority giving"),("The Main Thing","Keeping it the main thing"),
("Sabbath Economics","Rest as financial priority"),("The Second Look","Reviewing commitments annually"),
("One Yes, Many Nos","The freedom of a single priority"),("The Next Decade","A ten-year first-things plan")]),
]
