THEMES_B = [
("Generous Life",6,"2 Corinthians 9:6-7","I want giving to define me",[
("The Generous Life","Open-handed living"),("Generosity as Identity","Becoming, not just giving"),
("The Giver's Joy","Why generous people smile"),("Open-Handed","A posture for everything"),
("The Generosity Ladder","Your next step up"),("More Blessed","Acts 20:35, tested"),
("The Generous Table","Hospitality as giving"),("Time, Talent, Treasure","Whole-life generosity"),
("The Secret Giver","Matthew 6 generosity"),("Generous in Obscurity","When no one sees"),
("Everyday Generosity","Giving in ordinary moments"),("Radical Ordinary","Small consistent giving"),
("The Generosity Journal","Tracking grace given"),("Give Your Way Out","Generosity as cure for greed"),
("The Blessing Loop","Blessed to be a blessing"),("Generous Kids","Raising open-handed children"),
("The Generous Business","Profit with purpose"),("Sunrise Giving","Starting days with generosity"),
("The Second Mile","Beyond what's asked"),("A Generous Eye","Seeing needs others miss")]),
("The Joy of Giving",6,"Acts 20:35","Giving feels like obligation, not joy",[
("The Joy of Giving","From obligation to delight"),("Cheerful","The giver God loves"),
("Hilarious Generosity","The Greek behind cheerful"),("The Happiness Study","Why givers flourish"),
("Delight in Giving","Recovering the smile"),("The Grudge-Free Gift","Giving without strings"),
("Joy Math","How giving multiplies happiness"),("The Christmas Heart","Year-round giving joy"),
("Give & Grin","Family generosity experiments"),("The Party of Heaven","Celebration & generosity"),
("Gifts With Gladness","Bringing offerings joyfully"),("The Overjoyed Widow","Two coins, full heart"),
("Macedonian Joy","Overflowing in hard times"),("The Thank-You Effect","Gratitude that fuels giving"),
("Joyful Sacrifice","When it costs & still delights"),("The Giving Game","Making generosity fun for kids"),
("Surprise Giving","The joy of unexpected gifts"),("Receiving Well","The other half of generosity"),
("The Gift That Returns","Sowing & reaping joy"),("Celebration Generosity","Marking milestones with giving")]),
("Kingdom Impact",6,"Matthew 6:19-21","I want my resources to count forever",[
("Kingdom Impact","Deploying resources for what lasts"),("Treasure in Heaven","The only secure portfolio"),
("The Eternal ROI","Investing where moth can't touch"),("Kingdom Portfolio","Diversifying into eternity"),
("The Hundredfold","Kingdom math"),("Send It Ahead","Transferring treasure forward"),
("The Impact Map","Where your giving goes"),("Fund the Mission","Fueling what God is doing"),
("The Multiplier","Gifts that keep giving"),("Strategic Generosity","Thoughtful kingdom deployment"),
("The Great Exchange","Temporal for eternal"),("Legacy Gifts","Giving beyond your lifetime"),
("The Ministry Investor","Backing kingdom ventures"),("Global Impact","Giving beyond your zip code"),
("The Local Mission","Impact on your own streets"),("Measure What Matters","Kingdom metrics"),
("The Barn Problem","Luke 12 & bigger purposes"),("Assets on Assignment","Every resource deployed"),
("The Finish Line Gift","Completing what you started"),("Eternity in View","Decisions with forever in mind")]),
("Give First",6,"Proverbs 3:9","Giving is my leftover, not my first fruit",[
("Give First","First fruits, not leftovers"),("Before Anything Else","The order of generosity"),
("The Priority Gift","Giving off the top"),("Top of the Pile","Generosity before the bills"),
("Firstborn & First Fruits","The biblical pattern"),("The Proportion","Growing percentage giving"),
("Start With Ten","A first step into tithing"),("Beyond the Tithe","When ten percent is the floor"),
("The Faith Gap","Giving before you see how"),("Seed First","Sowing before harvest"),
("Automatic Firstfruits","Making first giving effortless"),("Paycheck Liturgy","A ritual for payday"),
("The Firstfruit Family","Teaching first-giving at home"),("Harvest Order","Old truths for modern income"),
("The Commitment Card","A promise with a date"),("Give, Save, Live","The order that frees"),
("The Early Giver","Generosity in your twenties"),("First in Famine","Giving in lean seasons"),
("The Pledge","Faith promises & follow-through"),("The Standing Order","Consistency as worship")]),
("Overflow",6,"Malachi 3:10","I want to be a channel, not a reservoir",[
("Overflow","Channel, not reservoir"),("The Open Floodgates","Malachi's invitation"),
("Rivers","Blessing that flows through"),("The Conduit","Wealth passing through clean hands"),
("Poured Out","A life spent, not saved"),("The Spring","Sources that never run dry"),
("Running Over","Luke 6:38 measures"),("The Cup","Filled to share"),
("Irrigation","Directing abundance to dry places"),("The Overflow Budget","Planning to pour out"),
("Water in Dry Places","Generosity where it's needed most"),("More Than Enough","Abundance with an assignment"),
("The Generous Flood","When God gives big"),("Spillover","Blessing your neighborhood"),
("The Increase","Stewarding growth for giving"),("Channels Only","An old prayer for open hands"),
("The Reservoir Trap","Why stored blessing stagnates"),("Overflow at Work","Generous leadership"),
("The Widow's Oil","Vessels for God's supply"),("Let It Flow","Removing generosity's dams")]),
("Following Jesus",7,"Luke 9:23","What does it actually mean to follow him?",[
("Following Jesus","The invitation that changes everything"),("Come, Follow Me","First steps of discipleship"),
("The Way","Life in the footsteps of Jesus"),("Deny, Take Up, Follow","Luke 9:23 in practice"),
("Following God","When obedience is hard"),("Red Letters","Living the words of Jesus"),
("The Narrow Road","Choosing the harder path"),("Leave the Nets","What following costs"),
("The First Disciples","Lessons from the twelve"),("Yes, Lord","A 40-day obedience experiment"),
("Footsteps","Walking where he walked"),("The Cost","Counting it, paying it"),
("Lord of All","No compartments"),("Follow in the Fog","Obedience without full answers"),
("The Second Call","Returning after failure"),("Sandals & Dust","Becoming like your rabbi"),
("The Daily Cross","Dying to live"),("Follow Me Home","Discipleship in your house"),
("Follow Me to Work","Discipleship on the job"),("The Long Walk","A lifetime of following")]),
("Rooted",7,"Colossians 2:6-7","My faith is a mile wide and an inch deep",[
("Rooted","A deeper walk with Christ"),("Deep Soil","Where strong faith grows"),
("The Root System","Unseen depth, visible fruit"),("Planted","Psalm 1 by the stream"),
("Taproot","One deep source"),("Below the Surface","The hidden life of faith"),
("Ground Work","Preparing the soil of your heart"),("Go Deep","Beyond shallow faith"),
("Rooted in Love","Ephesians 3 foundations"),("The Drought Test","Faith that survives dry seasons"),
("Old Growth","Wisdom of long-rooted saints"),("Transplanted","Rerooting after upheaval"),
("The Greenhouse","Environments where faith grows"),("Tending the Roots","Dealing with hidden decay"),
("Established","Stability through habit"),("The Orchard","Fruit that comes with time"),
("Water the Roots","Word & prayer as irrigation"),("Rooted Together","Community as soil"),
("Storm Roots","Why shaken trees grow deeper"),("The Hundred-Year Faith","Growing something that lasts")]),
("Abide",7,"John 15:4-5","I'm working for God but not with God",[
("Abide","The vine & the branches"),("Remain","John 15's one command"),
("The Vineyard","Life connected to the source"),("Apart From Me, Nothing","Dependence as strategy"),
("Fruit Happens","What abiding produces"),("The Pruning","When God cuts for growth"),
("Stay","The discipline of remaining"),("Sap","The life that flows unseen"),
("The Gardener","Trusting the one who tends"),("Attached","Connection over performance"),
("Dwell","Making your home in God"),("The Secret Place","Psalm 91 living"),
("The With-God Life","Practicing the presence"),("The Branch's Job","Rest, receive, bear"),
("Reconnected","Recovering from drift"),("Grafted","Belonging to the vine"),
("The Slow Fruit","Patience with your growth"),("Morning Vine","Starting days connected"),
("Abide at Work","Presence in the pressure"),("Much Fruit","The promise of John 15:8")]),
("Apprentice",7,"Matthew 11:29","I want to learn to live like Jesus",[
("Apprentice","Learning from the Master"),("The Easy Yoke","Learning from the gentle teacher"),
("Be With Jesus","The first movement"),("Do What He Did","The second movement"),
("Become Like Him","The third movement"),("The Workshop","Where character is formed"),
("Master Class","Sitting under the teacher"),("The Curriculum of Christ","What Jesus teaches first"),
("Slow Apprenticeship","No shortcuts to Christlike"),("The Practice Field","Failing forward in faith"),
("Journeyman","Mid-stage discipleship"),("The Toolbox","Skills of the spiritual life"),
("Imitate","Following followers of Christ"),("The Guild","Apprenticing together"),
("On-the-Job Training","Formation in daily life"),("The Master's Voice","Learning to hear instruction"),
("Repetition","Why practice makes faithful"),("The Apprentice Parent","Learning as you lead"),
("The Cost of Mastery","Years, not weekends"),("Graduation Day","Sent to make disciples")]),
("The Practices",7,"1 Timothy 4:7-8","I need habits that form my soul",[
("The Practices","Habits that form your soul"),("Rule of Life","A trellis for growth"),
("The Hour","Daily time with God"),("Fixed-Hour Prayer","Praying at set times"),
("The Examen","Reviewing days with God"),("Silence & Solitude","The quiet disciplines"),
("Fasting","Hunger that feeds the soul"),("Feasting","Celebration as discipline"),
("The Scripture Habit","Word before world"),("Memorize","Hiding the Word in your heart"),
("The Prayer Walk","Moving meditation"),("Simplicity","The discipline of less"),
("Confession","The freedom of telling the truth"),("The Sabbath Practice","A day set apart"),
("Service","Hidden acts of love"),("Worship Beyond Sunday","Adoration all week"),
("The Gratitude Practice","Daily thanks on purpose"),("Journaling","Writing your walk"),
("The Digital Fast","Unplugged for presence"),("Keystone Habits","Start with one")]),
("Never Alone",8,"Ecclesiastes 4:9-10","I'm doing life by myself",[
("Never Alone","You were not meant to do life solo"),("The Loneliness Cure","God's design for connection"),
("Two by Two","Why Jesus sent pairs"),("The Friend of Sinners","Jesus & the isolated"),
("With You Always","The presence promise"),("Alone in a Crowd","Connection beyond proximity"),
("Table for One","Hope for the solo season"),("Found","From invisible to known"),
("The Phone Call","Small moves against isolation"),("Companions","Doing hard things together"),
("The Extra Chair","Filling it on purpose"),("New in Town","Building community from scratch"),
("Alone at the Top","Community for leaders"),("The Widow's Table","Belonging after loss"),
("Not Good to Be Alone","Genesis 2 & human design"),("The Lifeline","Who to call at 2 a.m."),
("Digital Isn't Enough","Embodied friendship"),("The Third Place","Community beyond home & work"),
("Come Sit With Us","The ministry of inclusion"),("God With Us","Presence in lonely nights")]),
("Belong",8,"Romans 12:5","I don't fit anywhere",[
("Belonging","Everyone needs a place"),("The Welcome","First impressions of grace"),
("A Place at the Table","Room for you"),("Members of One Another","Romans 12 belonging"),
("The Family of God","More than a metaphor"),("Brought In","Belonging by grace"),
("The Outsider's Gospel","Good news for the excluded"),("Fit","Finding your place in the body"),
("The Name Tag","From visitor to family"),("Long Belonging","Staying planted in one church"),
("The Misfit's Home","Church for the unconventional"),("Belong Before Believe","Community as front door"),
("The Circle Widens","Making room for more"),("Second Family","When church fills the gap"),
("The Belonging Wound","Healing from exclusion"),("Home Church","Belonging in living rooms"),
("The New Member","Joining well"),("Cross-Generational","Belonging across ages"),
("The Body","Every part needed"),("You Belong Here","A church-wide welcome campaign")]),
("Group Up",8,"Hebrews 10:24-25","I want people to do life with",[
("Group Up","People to do life with"),("The Group Effect","What happens in circles"),
("Start a Group","From invitation to launch"),("The First Six Weeks","A group's fragile beginning"),
("Host","Your living room as ministry"),("The Empty Seat","Always room for one more"),
("Group Up for a Season","Committing to a stretch together"),("The Semester","A rhythm for groups"),
("The Circle","Where rows become relationships"),("The Icebreaker","Getting past small talk"),
("Go Deeper","Moving groups past surface"),("The Group Covenant","Agreements that hold groups"),
("Multiply","Birthing new groups well"),("The Off-Week","Groups beyond curriculum"),
("Serve Together","Groups on mission"),("Pray Together","Groups that intercede"),
("Eat Together","The shared table habit"),("The Yearlong Group","From study to family"),
("Restart","Rebooting a stalled group"),("The Group Leader's Heart","Shepherding a circle")]),
("One Another",8,"John 13:34-35","I attend church but I'm not connected",[
("One Another","The one anothers, lived"),("Love One Another","The command that proves discipleship"),
("Bear the Load","Carrying each other's burdens"),("Encourage Daily","Hebrews 3:13 in practice"),
("Forgive One Another","Grace in community"),("Spur On","Provoking love & good deeds"),
("Honor First","Outdoing in honor"),("Confess to Each Other","Healing in the open"),
("Accept One Another","Welcome as Christ welcomed"),("Teach & Admonish","Truth among friends"),
("Greet Warmly","The holy hello"),("Serve One Another","Towel-and-basin living"),
("Be Devoted","Family-level commitment"),("Live in Harmony","Unity without uniformity"),
("Build Each Other Up","Words as bricks"),("Pray for Each Other","James 5 community"),
("Show Hospitality","Without grumbling"),("Submit to One Another","Mutual deference"),
("Comfort One Another","Presence in grief"),("The 59 Commands","A tour of every one another")]),
("Life Together",8,"Acts 2:42-47","I want real community, not small talk",[
("40 Days of Life Together","Loneliness to community"),("The Acts 2 Church","Devoted, together, daily"),
("The Common Life","Sharing more than Sundays"),("Everything in Common","Radical shared living"),
("Daily Bread Together","Meals as ministry"),("The Household of Faith","Church as family"),
("Rhythms of Community","Weekly, monthly, yearly"),("The Long Table","Feasts that form family"),
("Neighbors & Brothers","Proximity plus commitment"),("Beyond the Service","Doing Sundays together"),
("The Interruptible Life","Available to one another"),("Vacation Together","Shared rest, deeper bonds"),
("Through Thick & Thin","Community in crisis"),("The Casserole Brigade","Practical love in hard times"),
("Celebrate Together","Marking milestones as family"),("Grieve Together","Companioned sorrow"),
("The Front Porch","Slow community in fast times"),("Small Church, Big Family","Intimacy as advantage"),
("The Village Church","Raising kids in community"),("Life Together at Work","Community on the job")]),
("Hope Rising",9,"Romans 15:13","I've lost hope",[
("Hope Rising","When you've lost hope"),("Hope Is Alive","Resurrection changes all"),
("The Dawn","Joy comes in the morning"),("Reasons to Hope","An inventory of promises"),
("Hope Deferred","When waiting hurts"),("The God of Hope","Romans 15:13 for empty tanks"),
("Borrowed Hope","Leaning on others' faith"),("The Waiting Room","Hope in seasons of unknown"),
("The Sunrise Habit","Daily hope practices"),("Against All Hope","Abraham's impossible faith"),
("Hope for the Prodigal","Waiting with the Father"),("Future Grace","Hope with a foundation"),
("The Green Shoot","Small signs of new life"),("Hope & Healing","Faith through medical seasons"),
("Prisoner of Hope","Zechariah's strange phrase"),("The Second Wind","Hope for the exhausted"),
("Hope for the New Year","Fresh mercies, fresh start"),("The Anchor & the Sail","Hope that holds & moves"),
("Living Hope","First Peter's birthright"),("Hope Passed Down","Giving the next generation reasons")]),
("Unbreakable",9,"2 Corinthians 4:8-9","Life keeps knocking me down",[
("Unbreakable","Pressed but not crushed"),("The Four Nots","2 Corinthians 4:8–9"),
("Resilient","Bouncing forward, not just back"),("The Refiner's Fire","What trials produce"),
("Tempered","Strength through heat"),("Jars of Clay","Fragile vessels, unbreakable treasure"),
("Down but Not Out","Getting up again"),("The Comeback","Believing after failure"),
("Mended Strong","Stronger where you healed"),("Job's Endurance","Faith that outlasts loss"),
("Grit & Grace","Holy stubbornness"),("The Long Haul","Endurance for extended trials"),
("Under Pressure","Faith in the crucible"),("The Palm Tree","Bending without breaking"),
("Battle Tested","What survival teaches"),("Keep Going","One more day faith"),
("The Fourth Man","Presence in the furnace"),("Unsinkable","Peter, waves & the grip of grace"),
("The Thorn","Grace for what won't go away"),("Overcomers","Revelation's repeated promise")]),
("When Life Hurts",9,"Romans 8:28","Why is this happening to me?",[
("When Life Hurts","Where is God in pain?"),("The Question Why","Honest lament, real faith"),
("Psalms in the Dark","Praying your pain"),("The God Who Weeps","Jesus at the tomb"),
("Beauty From Ashes","Trading despair for hope"),("The Broken Road","When plans fall apart"),
("Lament","The prayer language of grief"),("Where Was God?","Facing the hardest question"),
("The Fellowship of Suffering","Not alone in pain"),("Through the Valley","Psalm 23's dark stretch"),
("After the Fall","Recovering from life's blows"),("Healed to Heal","Your pain, someone's hope"),
("Job's Friends","What (not) to say in suffering"),("The Slow Healing","Patience with recovery"),
("Unanswered","Faith when prayers seem silent"),("Pain With a Purpose","Romans 5 perseverance"),
("The Night Season","Faith between dusk & dawn"),("Honest to God","Bringing anger to the altar"),
("Held","When you can't hold on"),("The Morning After","First steps beyond crisis")]),
("Grief to Grace",9,"Psalm 34:18","I'm walking through loss",[
("Grief to Grace","Walking through loss"),("Blessed Are Those Who Mourn","The strange beatitude"),
("The Valley of Weeping","Psalm 84's hard road"),("Good Grief","Permission to mourn fully"),
("The Empty Chair","First holidays after loss"),("A Time to Mourn","Ecclesiastes & seasons of sorrow"),
("The Grief Year","Twelve months of firsts"),("Widowed","Grace for the road ahead"),
("Losing a Parent","Grieving the ones who raised you"),("The Hardest Goodbye","Grace for unimaginable loss"),
("Grieving What Never Was","Loss of dreams & hopes"),("After Everyone Moves On","Grief's quiet months"),
("Tears in a Bottle","The God who keeps count"),("Grief & the Body","Caring for yourself in sorrow"),
("Companioning","Helping a friend who mourns"),("The Anniversary","Marking loss with meaning"),
("Laughter Again","Guilt-free joy after loss"),("What Death Cannot Do","Resurrection hope for mourners"),
("The Long Goodbye","Grieving through dementia"),("Grief in Community","Mourning together, healing together")]),
("Trust in the Dark",9,"Proverbs 3:5-6","I can't see what God is doing",[
("Trust in the Dark","When you can't see what God is doing"),("Lean Not","Proverbs 3 for foggy seasons"),
("The Unseen Hand","Providence in hindsight"),("Blind Curves","Trusting past what you can see"),
("The Silent Years","When heaven seems quiet"),("Even If","Furnace faith of the three"),
("The Detour","When God reroutes your life"),("Midnight Faith","Songs in the prison"),
("Between Diagnosis & Answer","Trust in the waiting"),("Unmapped","Following without an itinerary"),
("The Cloud & the Fire","Guidance one day at a time"),("Trusting the Timing","God's clock, your calendar"),
("In the Meantime","Faithfulness while waiting"),("The Backstory","Chapters you can't read yet"),
("Night Vision","Seeing by faith, not sight"),("The Hidden God","Faith when he feels absent"),
("Hold the Rope","Trust when others waver"),("The Dark Room","Where God develops us"),
("The Question Mark","Living with unanswered"),("Sunrise Is Coming","Trust with a horizon")]),
("Sent",10,"John 20:21","My faith is for me but not through me",[
("Sent","Faith for you, through you"),("Life on Mission","A household sent"),
("As the Father Sent Me","John 20:21 commissioning"),("The Sent Church","Every member a missionary"),
("Ready to Go","Prepared for the mission"),("The Great Commission","Making disciples where you are"),
("Sent to the City","Urban mission"),("Sent to the Suburbs","Mission in the cul-de-sac"),
("Sent to School","Students on assignment"),("Sent to Work","The office as mission field"),
("The Short Trip","Making mission trips matter"),("The Long Stay","Missional living for decades"),
("Everyday Missionaries","No passport required"),("The Sending Prayer","Lord of the harvest"),
("Sent Together","Teams over lone rangers"),("The 9-to-5 Mission","Vocational sentness"),
("Passport Faith","Global heart, local hands"),("The Sent Family","Kids on mission too"),
("First, Pray","Mission begins on knees"),("Sent Back","Returning to hard places")]),
("Love Your City",10,"Jeremiah 29:7","I want our church to matter to our town",[
("Love Your City","A church your town would miss"),("Seek the Welfare","Jeremiah 29 for your zip code"),
("The City Gates","Presence in public places"),("Bless the Block","Hyper-local mission"),
("The Mayor's Question","What if the church left town?"),("City of Refuge","Church as safe haven"),
("Streets & Steeples","Faith beyond the building"),("Adopt-a-School","Serving local education"),
("Feed the City","Food ministry that dignifies"),("The Civic Table","Christians in public life"),
("Love Where You Live","Rooted local mission"),("Showing Up","The parade, the game & the prayer"),
("City Lights","Visible good works"),("The Third Space","Ministry in cafes & courts"),
("Hometown Prophets","Honoring & challenging your city"),("The Long Renewal","Decades-long city commitment"),
("Small Town, Big Mission","Rural & small-city faith"),("The Crisis Response","Church in local emergencies"),
("Pray for the City","Intercession with a map"),("The City That Prays Back","When blessing returns")]),
("Every Neighbor",10,"Luke 10:27","I don't know the people next door",[
("Every Neighbor","The people next door"),("The Good Neighbor","A parable for your street"),
("Eight Front Doors","Knowing the homes around you"),("The Block Party","Feasts that open doors"),
("Over the Fence","Conversations that count"),("The Welcome Wagon","First to greet the new"),
("Neighbors","Loving the people next door"),("The Borrowed Cup","Small asks, real bonds"),
("Front Yard Faith","Visible, available, unhurried"),("The Neighborhood Map","Praying house by house"),
("Snow Shovels & Casseroles","Practical neighbor love"),("The Lonely House","Noticing the isolated"),
("Kids & Cul-de-Sacs","Family-friendly outreach"),("The Difficult Neighbor","Grace for hard relationships"),
("The Dinner Invitation","Tables that turn strangers to friends"),("Holiday Open House","Seasonal on-ramps"),
("The Emergency Contact","Becoming the one they call"),("Streetwise Prayer","Walking & interceding"),
("The Neighbor's Keeper","Watching out for one another"),("From Neighbor to Brother","Friendship that leads to faith")]),
("What Matters Most",10,"Matthew 16:26","I'm busy with things that won't last",[
("What Matters Most","The life behind the busy"),("The One Question","What will you wish you'd done?"),
("Gaining the World","Mark 8:36 economics"),("The Eulogy Test","Living for the second speech"),
("Essential","Cutting to what counts"),("The Short List","Five things worth your life"),
("Deathbed Wisdom","What the dying teach the living"),("The Great Subtraction","Removing what doesn't matter"),
("Time Audit","Where your hours really go"),("The Hourglass","Numbering your days"),
("Legacy Over Currency","Wealth that outlives wallets"),("Main Things","Majoring on the majors"),
("The Regret List","Avoiding the top five"),("The Top Shelf","What belongs above everything"),
("The Simple Life","Less stuff, more meaning"),("Measured","Success by heaven's metrics"),
("What You Keep","The only things you take with you"),("The Unhurried Goodbye","Ending seasons well"),
("Enough Time","Making space for what matters"),("The Examined Life","Yearly questions worth asking")]),
("Finish Strong",10,"2 Timothy 4:7","The last chapters should be the best",[
("Finish Strong","The last chapters are the best"),("The Fourth Quarter","Playing your best at the end"),
("Grown Up Faith","Faith that lasts"),("The Race Set Before Us","Hebrews 12 endurance"),
("No Coasting","Rejecting spiritual retirement"),("The Elder's Fire","Passion in the gray years"),
("Caleb's Mountain","Bold asks at eighty-five"),("The Mentor Years","Pouring into the next generation"),
("Second Wind","Fresh vision after sixty"),("The Blessing Years","A season of giving away"),
("The Turn","From achievement to meaning"),("Final Words","Saying what must be said"),
("Strong to the End","Health, habits & holiness"),("Still Bearing Fruit","Psalm 92's promise"),
("Retire to Something","Purpose after the paycheck"),("The Torch","Handing off well"),
("Unfinished Business","Completing your assignments"),("The Sage","Becoming the elder they need"),
("Last Will & Testimony","More than an estate plan"),("The Homestretch","Eyes on the finish line")]),
]
