# -*- coding: utf-8 -*-
def T(*p): return list(p)

EOY = ("End-of-Year Giving", [
("The Year Behind You", T(
("A Year of Provision","Gratitude as an honest ledger"),
("Where Did It Go","Twelve months of spending, examined"),
("What You Were Afraid Of in January","And what actually happened"),
("Count What Came In","Naming provision specifically"),
("The Year You Almost Did Not Make","Testimony from a hard twelve months"),
("What God Did Through This Church","Impact before ask"),
("The Gifts That Made It Possible","Honoring the givers"),
("Every Number Has a Name","Humanizing the report"),
("What We Learned About Money This Year","Honest reflection"),
("The Debt You Paid Off","Celebrating personal wins"),
("The Debt You Did Not","Grace and a plan"),
("Twelve Months of Faithfulness","The annual review as worship"),
("What You Gave Away","Remembering it, not for credit"),
("The Raise You Did Not Notice","Lifestyle creep, examined"),
("What Changed in Your Giving","A year-over-year honest look"),
("The Year in One Sentence","Compression as clarity"),
("Provision Is Not Always Comfort","Honest theology of supply"),
("The Prayer God Answered With Money","Testimony"),
("You Survived a Hard Year","A word for the strained"),
("Thank Someone Who Helped You","Gratitude aimed at people"),
("What You Would Do Differently","Learning before planning"),
("Ebenezer","Thus far the Lord has helped us"),
("Set Up a Marker","Remembering deliberately"),
("The Ledger and the Altar","Two ways of counting a year"),
("End It With Thanks","The posture before the ask"))),
("Why We Give", T(
("God Gave First","Response, never leverage"),
("You Cannot Outgive God","The surprising math"),
("Giving Is a Discipleship Issue","Not a budget issue"),
("Where Your Treasure Is","Heart follows money"),
("Worship With Your Wallet","Giving as an act of worship"),
("The Antidote to Greed","Why generosity is prescribed"),
("Trust, Made Visible","Faith you can see in a statement"),
("It Was Never Yours","Stewardship as premise"),
("Cheerfully, or Not at All","Motive over compliance"),
("Sow Generously","2 Corinthians 9's harvest logic"),
("Two Small Coins","Proportion over amount"),
("Giving Breaks Something in You","Formation through release"),
("The Macedonian Churches","Poverty and overflowing generosity"),
("Give to Whom It Is Owed","Justice inside generosity"),
("Store Up Treasure","Where moth and rust do not"),
("You Will Not Regret This","Testimony from long-time givers"),
("It Is More Blessed to Give","The verse Paul quoted from Jesus"),
("Generosity Is Contagious","How one gift moves a church"),
("Giving Beyond the Tithe","When ten percent is the floor"),
("The First Check You Write","Order of operations"),
("Giving When You Are Afraid","Faith at its most practical"),
("What Giving Does to Anxiety","The connection nobody names"),
("Freed From What You Held","The release nobody expects"),
("You Give Because You Were Given To","The whole theology in one line"),
("Zacchaeus Gave Half","Generosity as evidence of a changed life"))),
("The Practical Ask", T(
("Before the Calendar Turns","The window that closes"),
("Here Is Exactly What We Are Asking","Clarity as respect"),
("What Would It Take","Naming the number"),
("Fill the Gap","A specific, named shortfall"),
("The Last Decision of the Year","Choosing rather than drifting"),
("Everyone Gives Something","Participation before amount"),
("Pray First, Then Decide","Process over pressure"),
("Give Once and Give Again","One-time and ongoing, distinguished"),
("Set Up the Recurring Gift","The mechanic that changes a year"),
("Give From Assets, Not Only Income","A conversation most churches skip"),
("Year-End and the Tax Question","Handled plainly and without hype"),
("Sponsor a Specific Outcome","Naming what the gift does"),
("One More Family, One More Story","The human result"),
("Give a Percentage, Not a Number","How to decide"),
("What Does Sacrificial Mean for You","Personalizing the ask"),
("The Gift Nobody Sees","Anonymous giving"),
("Give as a Household","Deciding together"),
("Teach Your Children by Doing It","Generosity, modeled"),
("Give Before December Twenty-Fourth","A practical deadline"),
("Where Your Offering Goes","Radical transparency"),
("If You Cannot Give This Year","Grace, said out loud"),
("Give Your Time Instead","The other currency"),
("Start in January If Not Now","Making a future commitment"),
("Commit Today, Give by the Thirty-First","The two-step ask"),
("Thank You, Church","The close"))),
("The Heart Behind It", T(
("Enough","Contentment as the foundation"),
("The Rich Fool","Barns, and a man who used the word my too often"),
("The Rich Young Ruler","The one who walked away sad"),
("You Cannot Serve Both","The rival named"),
("What Money Promises","And what it delivers"),
("Comparison and the Christmas Season","The trap in December"),
("Greed Nobody Confesses","The sin with no support group"),
("Anxiety Is a Money Symptom","The link, examined"),
("Simplify Something","One decision toward less"),
("What Owns You","The honest inventory"),
("Money and Marriage","The fight underneath the fight"),
("Teaching Children Contentment","In the most acquisitive month"),
("Wealth Is Not a Sin","And it is not a reward"),
("The Danger of Having Enough","Comfort and spiritual drift"),
("Generosity Toward the Ungrateful","Giving without conditions"),
("The Widow Gave Everything","And Jesus was watching"),
("What Would You Do With Ten Times More","The revealing question"),
("Open Hands","The posture, held long enough to feel"),
("Trusting God With Next Year","Faith beyond the balance"),
("Gratitude Precedes Generosity","The order that matters"),
("Give Until It Reorders Something","The sacrificial definition"),
("The Freedom on the Other Side","Testimony from the generous"),
("Money Is a Tool and a Test","Both, held together"),
("You Will Take None of It","Perspective, gently"),
("Free","The one-word close"))),
("Giving Past This Year", T(
("What You Leave Behind","Values before assets"),
("Legacy Giving, Explained","Estate and planned gifts, plainly"),
("Give While You Live","Seeing it happen"),
("The Inheritance Question","How much, and to whom"),
("Teaching the Next Generation to Give","Transfer of practice, not only wealth"),
("The Fund That Outlives You","Endowment, honestly explained"),
("Wills and Wisdom","The document most people never make"),
("A Family Giving Plan","Deciding together, annually"),
("Business Owners and Generosity","Giving from the enterprise"),
("Appreciated Assets","A conversation most churches avoid"),
("Give the Second Home","Naming unusual gifts"),
("The Donor Advised Fund","Explained without jargon"),
("What Would Change in Thirty Years","Long-horizon impact"),
("The Gift That Started a Ministry","Testimony of a legacy"),
("Generosity Across Three Generations","Family patterns"),
("What Your Children Will Copy","Modeling as inheritance"),
("Plan It Now, Not Later","Urgency without morbidity"),
("Talk to Your Family About Money","The conversation nobody starts"),
("A Letter to Your Heirs","Values written down"),
("Sponsor Something Beyond Your Lifetime","Long-range vision"),
("The Kingdom Portfolio","Investing with eternity in view"),
("Do Not Wait for the Will","Giving now"),
("Steward the Whole of It","Time, talent, treasure, and body"),
("The Last Gift","Handled with dignity"),
("Finish Generous","The close"))),
("The Last Sunday", T(
("Finish the Year Well","The final Sunday message"),
("What Will You Send Ahead","Treasure in heaven, practically"),
("Close the Books Honestly","Personal and corporate"),
("One Last Decision","The year-end moment"),
("Do Not Drift Into January","Deciding rather than defaulting"),
("Communion at the Year's End","The table on the last Sunday"),
("Confess the Year","What you would do differently"),
("Release the Year","Letting go of what did not happen"),
("Number Your Days","Psalm 90 at the close"),
("Thank the People Who Carried You","Gratitude aimed outward"),
("What God Did That You Missed","Retrospect as worship"),
("Write It Down Before You Forget","Recording the year"),
("The Prayer for the Coming Year","Corporate and out loud"),
("Give, and Then Rest","Ending without striving"),
("The Testimony of a Year","One story from the congregation"),
("What We Will Do Next","The runway into vision"),
("Come Back on the First","Bridging into New Year's"),
("One More Family","The impact story, at the end"),
("Bless the Church","A benediction over a congregation"),
("Well Done","What we would say if we said it plainly"),
("Ebenezer, One More Time","The marker set"),
("Hand It Over","Surrendering the year"),
("Grateful and Unfinished","Both, honestly"),
("The Books Are Closed, the Story Is Not","The close"),
("See You in January","Sending them into the new year")))])

NEWYEAR = ("New Year's Sunday", [
("Beginning Again", T(
("New Year, Same God","Stability when the calendar turns"),
("His Mercies Are New Every Morning","Lamentations at the turn"),
("The God of New Things","Isaiah 43 and genuine fresh starts"),
("Begin Again","The invitation the gospel keeps offering"),
("Fresh Start for the Failed Start","For anyone who has broken this before"),
("Grace for January Second","When it collapses immediately"),
("Repentance Beats Resolution","The difference that lasts"),
("You Are Not Behind","Comparison at the year's start"),
("Start From Where You Are","Not from where you wish you were"),
("The Clean Slate Is Real","Forgiveness as an actual event"),
("Forget What Is Behind","Paul on moving forward without denial"),
("Do Not Rebuild the Same Thing","Change over repetition"),
("The Year You Stop Waiting","Acting on what you know"),
("A New Name","Identity at the turn of a year"),
("Behold, I Am Doing a New Thing","The promise, examined"),
("You Cannot Start Over Alone","Community from day one"),
("What Would Have to Die","Subtraction before addition"),
("The Old Self and the New","Colossians 3, in January"),
("Beginning Without Guilt","Removing the shame from restarting"),
("The Second Half of Your Life","Urgency for the middle-aged"),
("It Is Not Too Late","For anyone who thinks it is"),
("What You Are Not Going Back To","Naming the exit"),
("Take the First Step Today","Same-day action"),
("Twelve Months From Now","Working backward"),
("Begin","The one-word message))"))),
("Looking Back Honestly", T(
("Where Did Last Year Go","Honest review before planning"),
("The Year You Would Rather Forget","Naming it out loud"),
("What Actually Changed","Assessment without flattery"),
("The Goal You Abandoned in March","Grace and diagnosis"),
("What You Learned the Hard Way","Wisdom purchased expensively"),
("Who You Became","Character review over achievement"),
("The Relationship That Suffered","Honest cost accounting"),
("What You Gave Your Attention To","Formation by default"),
("Your Calendar Tells the Truth","Where the year actually went"),
("What God Did That You Did Not Notice","Retrospect as gratitude"),
("The Prayer That Was Not Answered","Faith in the unresolved"),
("The Prayer That Was","Testimony, recorded"),
("What You Are Still Carrying","Naming the unfinished"),
("Forgive Last Year","Yourself and others"),
("The Loss You Have Not Grieved","Permission to name it"),
("What Was Given to You","Provision, counted"),
("Confess and Move","The order that frees"),
("The Habit That Formed Without Permission","Drift, examined"),
("Who Helped You","Gratitude aimed at people"),
("What You Are Proud Of","Permission to name a win"),
("The Version of You in January","Comparison across twelve months"),
("What You Would Tell Yourself Last January","Hindsight as counsel"),
("Number Your Days","Psalm 90 and honest math"),
("Close It Before You Open the Next","Finishing well"),
("Thank God for a Finished Year","The close"))),
("Habits and Rhythms", T(
("The Habits That Will Build You","Small practices, long obedience"),
("Compound Interest on Character","The math of daily"),
("One Habit, Not Twelve","Focus over ambition"),
("Make It Small Enough to Keep","The design principle"),
("Attach It to Something You Already Do","Practical habit formation"),
("Who Will Ask You About It","Accountability from day one"),
("You Will Quit on Day Four","Naming the wall in advance"),
("Grace for the Days You Miss","Preventing the shame spiral"),
("Do Not Start Over, Start Again","Continuing after a lapse"),
("The Morning Decides the Day","A rhythm worth building"),
("Sabbath as a Yearly Commitment","Rest, scheduled"),
("The Practice You Have Been Avoiding","Named"),
("Read Something Every Day","The simplest discipline"),
("Pray at the Same Time","Consistency over intensity"),
("Move Your Body","Stewardship, not vanity"),
("Money Habits That Hold","Automating obedience"),
("Screens and the Coming Year","One decision about attention"),
("A Weekly Rhythm, Not a Daily One","For people who fail at daily"),
("Do It With Someone","The variable that predicts success"),
("Track It Visibly","Why a checkbox works"),
("Rhythms for a Household","Family practices for a year"),
("What You Repeat, You Become","Formation stated plainly"),
("Choose the Cost Now","Deciding in advance"),
("Ninety Days Makes It Yours","The honest timeline"),
("Start Tomorrow Morning","The launch"))),
("The Year Ahead", T(
("Where Do You Want to Be Next December","Working backward"),
("One Word for the Year","A discipline simple enough to keep"),
("Write It Down and Date It","Making it real"),
("Plan Like a Steward","Goals under providence"),
("Redeeming the Time","Stewardship of twelve months"),
("What Will You Say No To","Focus as strategy"),
("The Relationship You Will Invest In","Choosing one"),
("The Thing You Will Finally Face","Naming the avoided"),
("A Year of Generosity","Deciding the number in advance"),
("A Year of Learning","One book a month, or one skill"),
("A Year of Serving","Committing before you are asked"),
("A Year in the Word","The reading plan, launched"),
("Your Marriage This Year","One decision that changes it"),
("Your Children This Year","One rhythm, twelve months"),
("Your Work This Year","Vocation examined"),
("Your Body This Year","Health as stewardship"),
("Your Church This Year","Belonging with intent"),
("The Trip, the Move, the Change","Naming the big decision"),
("If God Interrupts the Plan","Holding it loosely"),
("What If This Is Your Last Year","Urgency, handled gently"),
("Make One Commitment Public","Saying it out loud"),
("The Card You Will Carry","A physical reminder"),
("Review It Quarterly","The follow-through nobody schedules"),
("Ask God for the Year","Discernment before planning"),
("Commit It to the Lord","Proverbs 16:3, plainly"))),
("For the Discouraged", T(
("Not Everyone Starts January Excited","Naming it from the platform"),
("For Anyone Dreading This Year","Direct address"),
("You Have Broken This Promise Before","Grace for the repeat failure"),
("When Last Year Broke You","Honest about a hard twelve months"),
("The New Year That Changes Nothing","When circumstances will not move"),
("Grief Does Not Reset on January First","Loss across a calendar line"),
("The Diagnosis You Carry Into the Year","Faith with a hard prognosis"),
("Unemployment in January","Practical and pastoral"),
("The Marriage That Is Not Better Yet","Patience without resignation"),
("The Prodigal Who Did Not Come Home","Another year of waiting"),
("When You Cannot Set a Goal","Survival as faithfulness"),
("Small Is Enough This Year","Lowering the bar deliberately"),
("You Do Not Have to Be Optimistic","Hope is not a mood"),
("God Is Not Disappointed in You","Correcting the picture"),
("The Year You Just Need to Hold On","Endurance as the goal"),
("Ask for Help in the First Week","The step that changes it"),
("Somebody Notice Them","A word to the congregation"),
("One Person to Walk With You","The minimum viable support"),
("What Got You Through Last Year","Naming your own resources"),
("Strength for Today","Enough, daily"),
("This Too Is a Season","Without minimizing it"),
("He Restores My Soul","Psalm 23 in January"),
("Come as You Are on January First","No performance required"),
("You Are Still Here","The evidence in front of you"),
("Take My Hand","The close"))),
("New Year Communion and Consecration", T(
("Consecrate Yourselves","Joshua 3, before crossing"),
("Communion at the Turn","The table on the first Sunday"),
("A Covenant for the Year","Written and signed"),
("The Wesley Covenant Prayer","An old practice, recovered"),
("Consecration Sunday","The whole service explained"),
("Lay It on the Altar","A physical act of surrender"),
("Twenty-One Days of Prayer","The January launch"),
("Fasting to Start the Year","The corporate practice"),
("First Fruits of the Year","Giving as consecration"),
("Dedicate Your Work","Vocation offered"),
("Dedicate Your Home","The household consecrated"),
("Dedicate Your Body","A living sacrifice"),
("Whatever You Ask","Boldness in the first prayer of the year"),
("A Prayer of Surrender","The words, supplied"),
("The Blank Check","Signing before the terms are known"),
("What We Will Ask God For","Corporate petition"),
("Pray for This Church by Name","The congregation, individually"),
("The Year Belongs to Him","Ownership stated"),
("Kneel on the First Sunday","The posture"),
("Write Your Prayer and Leave It","Physical and collected"),
("A Church That Starts on Its Knees","Vision through practice"),
("Renew the Vows","Membership and covenant, recommitted"),
("Send Us Where You Want Us","The missional prayer"),
("Bless This Year","The benediction"),
("Here Am I","The close")))])
