# -*- coding: utf-8 -*-
def T(*p): return list(p)

ADVENT = ("Advent Kickoff", [
("The Waiting", T(
("Advent Means Arrival","Why the church invented this season"),
("Four Hundred Years of Silence","What waiting does to a people"),
("Do Not Skip to the Manger","The value of waiting on purpose"),
("Waiting Is Not Wasting","A theology of the in-between"),
("Learning to Wait Well","Patience as a spiritual muscle"),
("The Waiting Room of God","For anyone between prayer and answer"),
("Not Yet Is Not No","Faith in the gap"),
("What Are You Waiting For This Year","Naming the longing"),
("Longing Is Not Failure","A season built for the aching"),
("The Ache Under December","What the shopping covers"),
("Hope Deferred","Proverbs on the cost of waiting"),
("Simeon Waited a Lifetime","And said it was enough"),
("Anna Never Left","Faithfulness nobody recorded"),
("Israel Waited in Occupation","The political weight of Advent"),
("Waiting Together","The congregation as company"),
("Advent for the Impatient","A word to the achievers"),
("What Grows in the Waiting","Formation you cannot rush"),
("The Second Advent","Christmas as rehearsal for his return"),
("Keep Awake","Advent's forgotten warning"),
("Watch for Him","Vigilance without anxiety"),
("Come, Lord Jesus","The oldest Christian prayer"),
("The Waiting Ends","And what that promises"),
("Twenty-One Days of Waiting","The devotional, launched"),
("Light One Candle at a Time","Hope in increments"),
("Begin the Season Tonight","The household start"))),
("The Prophets Saw It", T(
("The Prophets Saw It Coming","Setting the biblical stage"),
("The Seed of the Woman","Genesis 3 and the first promise"),
("A Shoot From the Stump","Hope out of what looked dead"),
("Out of Bethlehem","Micah, seven hundred years early"),
("A Virgin Will Conceive","Isaiah 7 and a sign to a frightened king"),
("Unto Us a Child Is Born","Four names for one boy"),
("The Government on His Shoulders","A political claim in a manger"),
("Prince of Peace","A title, not a mood"),
("Out of Egypt I Called My Son","Hosea and a refugee family"),
("A Voice in Ramah","Jeremiah and the grief inside the story"),
("The Messenger Before Him","Malachi and camel's hair"),
("The Sceptre Shall Not Depart","Genesis 49 and timing"),
("Seventy Weeks","Daniel and the question of when"),
("Riding on a Donkey","Zechariah, and the week it came true"),
("Pierced for Our Transgressions","The cross, written centuries early"),
("The Desire of Nations","Haggai's global promise"),
("The Star Out of Jacob","Balaam's unlikely prophecy"),
("Every Valley Shall Be Raised","What God does to terrain"),
("Comfort, Comfort My People","Isaiah 40 as Advent's overture"),
("The Suffering Servant in December","Isaiah 53 read early"),
("Why So Many Promises","The cumulative case"),
("They Died Without Seeing It","Hebrews 11 and unfulfilled waiting"),
("Every Promise Kept","The whole prophetic case, in one message"),
("Read the Prophets This December","The reading plan"),
("He Was Always Coming","The close))"))),
("Preparing the Home", T(
("Prepare Him Room","Making space before December fills it"),
("An Advent Wreath at Your Table","Four candles, five minutes a week"),
("Twenty-One Nights With Your Household","The family devotional"),
("One Family, One Practice","The achievable ask"),
("Light the First Candle Tonight","The household launch"),
("Move the Wise Men Slowly","Teaching with the nativity set"),
("Read It Before the Presents","Establishing the order"),
("Teaching Waiting to Children","The hardest and most useful lesson"),
("The Advent Calendar, Redeemed","Chocolate and Scripture together"),
("A Blessing for Each Night","Words spoken over the household"),
("Serve as a Family This December","The antidote to a receiving month"),
("Give the First Gift Away","Generosity before receiving"),
("Simplify Before It Starts","Deciding in November"),
("A Household That Is Not Exhausted","Planning December on purpose"),
("Traditions Built This Year","Culture created deliberately"),
("The Empty Chair at Your Table","Grief in the household"),
("Invite the Neighbors In","Home as the December mission field"),
("Say No to Three Things","Protecting the season"),
("The Phones Go in a Basket","One hour a night"),
("Sing at Home","Badly, on purpose"),
("Write One Letter as a Family","Slowness as practice"),
("A Household Advent Liturgy","The whole thing, supplied"),
("What Your Children Will Remember","Working backward from thirty"),
("Take the Devotional Home Today","The mechanic"),
("Start Tonight","The close"))),
("Advent for the Busy", T(
("Slow Down December","Counter-formation in the busiest month"),
("December Will Form You","The only question is what into"),
("The Calendar You Did Not Choose","Naming the pressure"),
("Five Minutes Is Enough","Lowering the bar"),
("You Cannot Do It All This Year","Permission"),
("What Are You Actually Celebrating","The reorienting question"),
("The Party You Can Skip","Saying no in December"),
("Buying Our Way Through Advent","Consumerism as formation"),
("The Comparison Trap in December","Nobody's month is the feed"),
("Exhausted by the Fifteenth","Naming the wall"),
("A Fast in the Feasting Season","Advent's forgotten discipline"),
("Silence in the Loudest Month","Ten minutes a day"),
("The Sunday You Almost Skipped","A word to the ones who came"),
("Ministry Staff in December","The people serving the season"),
("Retail and Shift Workers","The ones who cannot slow down"),
("Advent While Traveling","Practices that move"),
("One Candle, One Verse, One Minute","The minimum viable Advent"),
("What Would You Drop","The honest audit"),
("Rest Is Part of the Season","Sabbath in Advent"),
("Do Not Perform Christmas","Grace for the tired"),
("The Best Christmas in Years","Casting a different vision"),
("You Have Twenty-One Days","Framing the runway"),
("A December Plan","Written before it starts"),
("Peace That Does Not Depend on December","The offer"),
("Begin Slowly","The close"))),
("Both Comings", T(
("Two Comings, One Season","Christmas and the return"),
("Advent Is Not Only About the Past","The forward half"),
("Keep Watch","The parable of the ten virgins"),
("The Master Returns","Faithfulness while he is away"),
("He Will Come Again","The creed, said in December"),
("Every Eye Will See Him","The second arrival, unlike the first"),
("Maranatha","The prayer of the early church"),
("Living Between the Advents","Where the church actually stands"),
("The Groaning of Creation","Romans 8 and a world waiting"),
("Hope Is a Forward-Facing Word","Correcting sentimental Advent"),
("What Are You Waiting For Now","Turning the question forward"),
("He Came Quietly, He Will Not","The contrast"),
("Judgment Is Part of Advent","The half nobody preaches"),
("Be Ready","Preparedness without panic"),
("Occupy Until I Come","Faithfulness in the meantime"),
("The Kingdom Already and Not Yet","The tension, explained"),
("Revelation in December","A carefully handled reading"),
("Behold, He Is Coming With Clouds","The other announcement"),
("What Would You Change if He Came Friday","The clarifying question"),
("No One Knows the Day","Humility about timing"),
("The Waiting Church","Two thousand years of it"),
("He Will Wipe Every Tear","The ending, promised"),
("Come, Lord Jesus","The prayer that ends the Bible"),
("Advent Ends Twice","The structure of the season"),
("Watch and Wait","The close")))])

LENT = ("Lent Kickoff", [
("Ashes and Dust", T(
("Remember You Are Dust","The most freeing sentence in the calendar"),
("The Mark on Your Forehead","Wearing mortality in public"),
("Dust That God Breathed On","Mortality and dignity together"),
("Number Your Days","Psalm 90 at the start of Lent"),
("You Are Going to Die","Said gently, and once"),
("The Ash Is From Last Year's Palms","The cycle explained"),
("Mortality Is Not Morbid","Why the church says this out loud"),
("What Would You Do With One Year","The clarifying question"),
("Ashes and Baptism","Death and life, marked on the same body"),
("Rend Your Heart, Not Your Garments","Sorrow versus show"),
("Return to Me","Joel's call and a God who runs"),
("Repent Is an Invitation","Recovering the word"),
("Confession Is a Gift","Naming it so it loses its grip"),
("Lament as the Season's Language","Making room for grief"),
("The Dust of the Ground","Genesis 2 in February"),
("Nothing to Prove for Forty Days","Rest from performance"),
("Ash Wednesday in the Middle of a Week","Interrupting ordinary time"),
("A Service in the Evening","Designing the night"),
("The Sign You Wear to Work","Public faith, awkwardly"),
("Bring Your Children to the Ashes","Explaining it to them"),
("From Ashes to Glory","The whole arc in one message"),
("Marked and Loved","Both at once"),
("What Are You Bringing Into Lent","The honest inventory"),
("Forty Days Starts Tonight","The launch"),
("Dust, and Beloved","The close"))),
("The Wilderness", T(
("Forty Days in the Wilderness","Why Jesus began hungry"),
("Led by the Spirit Into It","The detail nobody notices"),
("Not by Bread Alone","The first temptation"),
("Prove It","Why he refused to perform"),
("All This Can Be Yours","The shortcut he turned down"),
("He Answered With Scripture","Preparation before the moment"),
("The Desert Is Not a Detour","Wilderness as formation"),
("Israel's Forty Years","The pattern behind the forty days"),
("What Surfaces When You Are Empty","Fasting as exposure"),
("The Wilderness You Are In","Naming a current season"),
("Angels Attended Him","Provision in the desert"),
("Alone Is Not Abandoned","Solitude and presence"),
("The Voice Before the Wilderness","This is my Son, spoken first"),
("Temptation Is Not Sin","The distinction that frees"),
("He Was Tempted in Every Way","Sympathy from the inside"),
("The Devil Left Until an Opportune Time","Vigilance after victory"),
("Hunger as a Teacher","What the body reveals"),
("The Silence of the Desert","Practicing it"),
("Elijah in the Wilderness","Food, sleep, and a whisper"),
("Moses on the Back Side of Nowhere","Forty years of preparation"),
("John the Baptist Lived There","The prophet from the margins"),
("What God Does in Barren Places","The pattern across Scripture"),
("Do Not Rush Out of It","Staying long enough to be formed"),
("Your Own Forty Days","Making it personal"),
("Into the Wilderness With Him","The close"))),
("Fasting and Practice", T(
("When You Fast","Jesus assumed you would"),
("Give Something Up, Gain Something Better","Fasting as addition"),
("Pick One Thing","Small enough to keep"),
("Fast From More Than Food","Screens, noise, comfort, opinion"),
("A Season for Subtraction","Making room by making less"),
("What Are You Hungry For","Appetite as a diagnostic"),
("The Fast God Chooses","Isaiah 58 and justice"),
("Secret Giving, Secret Praying, Secret Fasting","Matthew 6"),
("Fasting and Prayer Together","The pairing the church dropped"),
("Add Something Instead","Lent as practice, not only denial"),
("Forty Days of Scripture","The reading discipline"),
("Forty Days of Silence","Ten minutes daily"),
("Forty Days of Generosity","Giving what the fast saves"),
("Forty Days of Confession","The practice nobody does"),
("Forty Days of Service","Lent that goes outward"),
("Sundays Are Feast Days","The rhythm explained"),
("When You Break the Fast","Grace for failure"),
("Do Not Announce It","The discipline of secrecy"),
("Fasting Is Not a Diet","Correcting the modern confusion"),
("Physical Limits and Fasting","Health, honestly addressed"),
("Fasting as a Household","The family version"),
("Fasting as a Church","Corporate practice, scheduled"),
("What You Will Notice by Week Two","Preparing for it"),
("Choose Yours Today","Written and signed"),
("Give and Take Up","The close"))),
("The Road to the Cross", T(
("The Slow Walk to the Cross","Why Easter needs a runway"),
("Reading the Passion Over Six Weeks","The plan"),
("He Set His Face Toward Jerusalem","Resolve in Luke 9"),
("Take Up Your Cross","Daily, and what that means"),
("Whoever Loses His Life","The paradox at the center"),
("The Cost of Following","Luke 14 without softening"),
("Deny Yourself","The verb nobody wants"),
("Unless a Grain of Wheat Falls","Death before fruit"),
("The Cup He Did Not Pass","Gethsemane in Lent"),
("The Transfiguration","Glory before the descent"),
("He Told Them Three Times","Predictions they could not hear"),
("The Triumphal Entry Is Coming","Building toward Palm Sunday"),
("Betrayal and the Table","Judas in the Lenten arc"),
("The Trial and the Silence","What he did not say"),
("Simon Carried It","Conscripted into the walk"),
("The Words From the Cross","Preached across the season"),
("Good Friday Is Coming","Preparing the congregation"),
("Silent Saturday","The day of absence"),
("Why the Cross and Not Something Easier","The question underneath"),
("Substitution, Plainly","The doctrine at the center"),
("It Is Finished","Where the road ends"),
("Sunday Is Not Yet","Holding the tension"),
("Walk It, Do Not Watch It","The Lenten posture"),
("Six Weeks to Resurrection","The runway named"),
("Follow Him There","The close"))),
("Lent for Beginners", T(
("Lent for People Who Do Not Do Lent","A practical entry point"),
("Where This Came From","A short honest history"),
("Is This Even Biblical","Answering the objection directly"),
("You Are Not Earning Anything","Grace inside a discipline"),
("Forty Days, Not Forever","The finite frame"),
("The Simplest Possible Lent","One thing, one practice"),
("What If You Fail at It","Grace built in from the start"),
("Do It With Someone","The variable that predicts finishing"),
("Lent With Children","Household-appropriate practice"),
("Lent for Teenagers","Making it theirs"),
("Lent Without Guilt","Correcting the tone"),
("What Do I Tell People at Work","Handling the questions"),
("A Lent That Fits Your Life","Adapting to real constraints"),
("Every Tradition Does This Differently","Humility about practice"),
("The Point Is Not the Giving Up","Keeping the aim in view"),
("Forty Days to Honest","Using the season to stop pretending"),
("Sackcloth and Smartphones","Ancient repentance in a distracted age"),
("What Would You Notice if It Were Quiet","Silence as practice"),
("The Journal for the Season","The printed companion"),
("A Church Doing This Together","Corporate rather than individual"),
("Week One Is the Hardest","Preparing for it"),
("Report Back at Easter","The celebration built in"),
("Try It Once","The lowest-pressure invitation"),
("Start Wednesday","The date named"),
("Take the Guide Home","The close")))])

THANKS = ("Thanksgiving", [
("Gratitude as Practice", T(
("Give Thanks in All Circumstances","Gratitude that does not require good news"),
("Count It Out Loud","Why gratitude has to be spoken"),
("Gratitude Rewires You","The formation argument"),
("Complaining Is a Habit","Not a personality"),
("Bless the Lord, O My Soul","Preaching gratitude to yourself"),
("Name Three Things","The exercise, done in the room"),
("A Gratitude Practice for Thirty Days","The challenge, launched"),
("Write It Down","Recording as remembering"),
("Say It to Them","Gratitude that reaches the person"),
("Thank Someone Who Cannot Repay You","Gratitude without transaction"),
("The Ten Who Were Healed","Nine kept walking"),
("Remember What He Has Done","Rehearsing God's history with you"),
("An Altar of Stones","Building markers so you do not forget"),
("Ungratefulness Is a Spiritual Condition","Romans 1 and the first step away"),
("Gratitude Before the Provision","He gave thanks, then broke it"),
("The Entitlement Underneath","What gratitude exposes"),
("Notice Small Things","Attention as the practice"),
("Gratitude and Contentment","The link between them"),
("Thanksgiving as Worship","Not a mood, an offering"),
("Teach Children to Say It","Formation at the table"),
("The Thank You You Have Not Said","Named, and assigned"),
("Gratitude in the Middle of the Story","Not only at the end"),
("Sing a Thanksgiving","Worship as the response"),
("A Thankful Church","Corporate gratitude as witness"),
("Start Today","The close"))),
("The Table", T(
("The Meal That Makes a Family","Table, hospitality, belonging"),
("Who Set Your Table","Naming the people who got you here"),
("Set a Wider Table","An invitation to the excluded"),
("The Empty Seat","Grief and gratitude in one room"),
("Who Is Alone This Week","The congregation's assignment"),
("Invite Someone With Nowhere to Go","The concrete ask"),
("The Relative You Dread","Grace at a full table"),
("Say Grace Like You Mean It","Recovering the practice"),
("Let Everyone Speak","A table liturgy"),
("The Kids' Table","Intergenerational hospitality"),
("Feeding People Is Ministry","The simplest act"),
("Jesus at Dinner Parties","Where most of his ministry happened"),
("The Table in Acts 2","Meals as the church's foundation"),
("Communion Is a Meal","Connecting the two tables"),
("What Your Table Says","Who is welcome, revealed"),
("Cooking as Service","Honoring the ones in the kitchen"),
("Leftovers and the Neighbor","Practical generosity"),
("A Table Without Phones","One meal, undivided"),
("The Story Told Every Year","Family narrative at the table"),
("Bless the Food and the People","Both, out loud"),
("The Table After a Loss","First holiday without them"),
("A Meal for Someone Who Is Struggling","Assigned, not suggested"),
("Open Your Home This Week","The ask"),
("Come to the Table","The gospel invitation"),
("Set One More Place","The close"))),
("When Gratitude Is Hard", T(
("Thanksgiving When the Year Was Hard","Honest gratitude"),
("You Do Not Have to Feel It","Gratitude as obedience first"),
("The Empty Chair at the Table","Naming the loss out loud"),
("Grief in the Season of Gratitude","Holding both"),
("Job Said Blessed Be the Name","After everything"),
("Habakkuk's Yet I Will Rejoice","Gratitude without the harvest"),
("Thankful and Angry","Both at once"),
("When You Cannot Find Three Things","Grace for the depleted"),
("Gratitude Is Not Denial","Correcting the toxic version"),
("Do Not Tell Grieving People to Be Grateful","A word to the well-meaning"),
("The Year You Lost Everything","Testimony from the far side"),
("Thankful for the Hard Thing","Only sometimes, and only later"),
("Praise in the Prison","Paul and Silas at midnight"),
("A Sacrifice of Praise","Hebrews 13 and what it costs"),
("When the Family Is Fractured","Thanksgiving with estrangement"),
("Financial Strain in November","Gratitude without means"),
("Illness at the Holiday","Faith in a hospital"),
("The Prodigal's Empty Chair","Waiting through another holiday"),
("Thankful for Small Mercies","Lowering the threshold"),
("God Is Still Good","Said carefully, not glibly"),
("Give Thanks for the People Who Stayed","Naming your support"),
("The Practice That Carried You","What got you through"),
("Lament and Thanksgiving Together","Both in one service"),
("You Made It to November","The evidence in front of you"),
("Hold On and Give Thanks","The close"))),
("Harvest and Provision", T(
("First Fruits","Gratitude expressed in what you give away"),
("Harvest","Reaping what someone else planted"),
("Provision, Counted","Naming what came in"),
("Daily Bread","Enough, on purpose, daily"),
("The Manna Would Not Keep","Trusting a daily supply"),
("Do Not Forget the Lord Your God","Deuteronomy 8 and prosperity's danger"),
("When You Have Eaten and Are Satisfied","The warning inside abundance"),
("The Barns You Built","Luke 12 and the man who said my"),
("Enough","Contentment as the root of thanks"),
("The Land Gave Its Increase","Agricultural gratitude in a digital age"),
("Whose Harvest Is It","Ownership, revisited"),
("Gleaning","Leaving margin for others"),
("Ruth in the Field","Provision through another's generosity"),
("The Widow's Jar","Supply that did not run out"),
("Five Loaves and a Crowd","Multiplication of the small"),
("Seed for the Sower","Provision given to be given"),
("You Did Not Build This Alone","Naming the help"),
("The Farmers in the Room","Honoring agricultural work"),
("Blessing Is Not a Reward","Correcting the prosperity assumption"),
("What Will You Do With the Increase","The stewardship question"),
("Return a Portion","Giving as gratitude"),
("Store Some, Give Some, Live on Some","Three uses"),
("Provision for the Coming Year","Faith forward"),
("Thank the Provider, Not the Provision","Aiming gratitude correctly"),
("Bring the First of It","The close"))),
("Gratitude That Moves Outward", T(
("Gratitude Becomes Generosity","The natural sequence"),
("From Full to Poured Out","What thanks produces"),
("Who Fed You When You Had Nothing","Remembering, then repeating"),
("Feed Someone This Week","The concrete assignment"),
("The Food Drive Is Not Enough","Serving that costs something"),
("Adopt a Family for December","Thanksgiving into Christmas"),
("Serve the Meal, Do Not Send It","Presence over provision"),
("The Hungry in Your Own City","Local, named, specific"),
("Gratitude and the Stranger","Hospitality to the outsider"),
("Remember You Were Slaves","Israel's memory as motive for mercy"),
("Give From the Overflow","And then past it"),
("A Thanksgiving Offering","The generosity moment"),
("Thank a Teacher, a Nurse, a Neighbor","Gratitude with an address"),
("Write Five Notes This Week","The practice, assigned"),
("Honor the People Who Serve You","The invisible labor around you"),
("Bless Someone Anonymously","Gratitude without credit"),
("The Church That Fed a City","Vision through outcome"),
("Volunteer on Thanksgiving Day","The ask"),
("Bring Someone Home With You","Hospitality as mission"),
("Gratitude Toward the Difficult Person","The hardest version"),
("Forgive as an Act of Thanks","Grace received, passed on"),
("What Would the City Notice","The clarifying question"),
("Give Thanks, Then Give","The order"),
("One Family, One Church, One Week","The specific commitment"),
("Pass It On","The close")))])
