# -*- coding: utf-8 -*-
def T(*p): return list(p)

NEXTSTEP = ("Next Step Sundays", [
("The First Step", T(
("What Is Your Next Step","The question the whole category asks"),
("Smaller Than You Think","Removing the intimidation"),
("You Cannot Take Step Four First","Sequence matters"),
("Start Where You Actually Are","Honest self-location"),
("The Step You Have Been Avoiding","Named gently"),
("One Step Is Enough Today","Lowering the ask"),
("Believe","The first step, plainly"),
("Be Baptized","The second, without delay"),
("Find Three People","The third"),
("Serve Once","The fourth"),
("Tell Somebody","The fifth"),
("The Pathway, Explained","Making it visible"),
("Nobody Grows by Accident","Intentionality required"),
("What Got You Stuck","Diagnosing the plateau"),
("You Have Been Here Long Enough","A gentle confrontation"),
("Attending Is Not the Goal","Reframing membership in the room"),
("Write It Down and Hand It In","The mechanic"),
("Who Will Walk With You","Accountability for the step"),
("Take It Before You Leave","Same-day response"),
("The Step After the Step","Building the sequence in"),
("What Would Have to Change","Making it concrete"),
("A Church With a Path","Vision for the pathway"),
("The Stations at the Back","The physical mechanic"),
("Ask Somebody What Theirs Is","The congregation's assignment"),
("Take One Step Today","The close"))),
("Belonging", T(
("From Attender to Member","What actually changes"),
("You Cannot Be Discipled Anonymously","The limit of showing up"),
("Get Counted","Membership as visibility"),
("Find Your People","Three friends as the threshold"),
("Rows and Circles","Different work"),
("Six Weeks, One Room","The finite group ask"),
("Say Yes to a Table","The lowest barrier"),
("Who Would Notice","The diagnostic question"),
("Belonging Before Believing","The order that works"),
("The Class Starts This Month","The specific ask"),
("Open Your Home","Hosting rather than leading"),
("The Lobby Is Not Community","Honest about proximity"),
("Come Early, Stay Late","The simplest habit"),
("Learn Ten Names","The assignment"),
("Sit Somewhere Different","Disrupting the pattern"),
("Bring Someone With You","Belonging through inviting"),
("What a Small Group Actually Is","Demystifying it"),
("Groups Are Not for Extroverts","Addressing the real fear"),
("The Second Year","When belonging deepens or stalls"),
("Serve Alongside Someone","Connection through doing"),
("The Meal After the Service","Where friendship starts"),
("You Are Not a Guest Anymore","Naming the shift"),
("This Is Your Church","Ownership language"),
("Sign Up in the Lobby","The mechanic"),
("Belong Here","The close"))),
("Going Deeper", T(
("Milk and Solid Food","Hebrews 5 and arrested development"),
("Depth Is Not Complexity","What maturity looks like"),
("Read It Yourself","First-hand Scripture"),
("Learn to Study","The inductive method, simply"),
("Read a Whole Book","Context over fragments"),
("Memorize Something","Scripture in your bones"),
("Learn to Pray","Practical instruction"),
("The Disciplines Nobody Teaches","Fasting, solitude, silence"),
("Sabbath","The discipline that exposes trust"),
("Confession","The practice that changes everything"),
("Journaling","Recording what God does"),
("Solitude in a Loud World","Alone on purpose"),
("Fasting","Recovering a dropped practice"),
("Sit Under Someone Older","Mentorship as discipline"),
("Ask the Hard Question","Doubt as a doorway"),
("Theology Is for Everyone","Demystifying it"),
("Learn the Story of the Church","History as formation"),
("Study One Book Deeply","Depth over breadth"),
("Take a Class","The concrete step"),
("Seminary Is Not Required","Depth without credentials"),
("Teach Something","Learning by explaining"),
("Go Deeper This Season","Time-bound invitation"),
("What You Do Not Know Yet","Humility as fuel"),
("Pick One Discipline","Focus over ambition"),
("Deeper","The close"))),
("Serving and Giving", T(
("Everyone Got Something","1 Corinthians 12"),
("Find Your Place","Serving as belonging"),
("Serve Once and See","The finite ask"),
("Use What You Already Have","Monday's skills"),
("Say Yes for One Season","With an end date"),
("Start Giving","The first step, plainly"),
("Give First, Not Last","Order of operations"),
("Give a Percentage","How to decide"),
("Automate It","The mechanic that holds"),
("Generosity Is a Discipline","Formation through giving"),
("Give Your Time","The harder currency"),
("Open Your Home","Hospitality as a next step"),
("Lead Something Small","The first leadership step"),
("Take the Training","Equipping as a step"),
("Serve Outside the Building","Mission as a next step"),
("Sponsor Somebody","Directed generosity"),
("Go on the Trip","Short-term mission as a step"),
("Give Something Away This Week","Immediate action"),
("Tithe for Ninety Days","The experiment framing"),
("Serve With Your Family","Household step"),
("Bring Someone Onto the Team","Multiplication"),
("What Would You Do for Free","Following the energy"),
("The Ministry That Needs You","Casting it"),
("Walk to a Table","Four words"),
("Serve","The close"))),
("Telling Your Story", T(
("You Have a Story","Whether or not it feels dramatic"),
("Before, During, After","The three-part shape"),
("Three Minutes","Learning to tell it short"),
("Write It Down First","The exercise"),
("Practice on Someone Safe","Building the muscle"),
("Do Not Sanitize It","Honesty makes it usable"),
("The Boring Testimony Counts","For lifelong church people"),
("Where You Are Still in the Middle","Unfinished stories"),
("Your Scars Are Credentials","The healed wound"),
("Tell It Without Church Words","Translating"),
("Answer the Question They Asked","Listening first"),
("Give a Reason for the Hope","1 Peter 3"),
("One Person This Month","The assignment"),
("Tell It at Your Table","Family as first audience"),
("Record It for Your Children","Legacy"),
("Post It","Testimony in public"),
("Stand Up and Say It","Same-day invitation"),
("What God Did This Year","The recent testimony"),
("Who Discipled You","Honoring the chain"),
("Bring the Person You Told","Full circle"),
("The Story You Have Not Told","Naming what you omit"),
("Testimony Sunday","Building a service on it"),
("Learn to Listen First","The other half"),
("Practice It Today","In pairs, in the room"),
("Tell Someone","The close"))),
("Multiplying", T(
("Make Disciples, Not Converts","The difference"),
("Who Are You Discipling","The question nobody asks"),
("Two Timothys","Paul's model, applied"),
("Pass It On","2 Timothy 2:2"),
("You Know Enough to Start","Removing the qualification"),
("Read Something With Someone","The simplest form"),
("Meet for Six Weeks","The finite discipling ask"),
("Multiply the Group","Building it in from the start"),
("Raise Up a Leader","The step past serving"),
("Train Your Replacement","Sustainability as multiplication"),
("Host, Then Lead","The natural progression"),
("Give Your Ministry Away","Releasing what you built"),
("Send Someone","Multiplication that costs you"),
("Start Something New","For the person carrying a burden"),
("Plant a Group in Your Neighborhood","Local multiplication"),
("Disciple Your Own Children","The nearest assignment"),
("Mentor Someone Younger","The step older adults skip"),
("Be Discipled Yourself","You cannot give what you lack"),
("Four Generations Deep","The measure that matters"),
("What Outlives You","Legacy through people"),
("Do Not Keep It","Multiplication as obedience"),
("Who Is Your One","The whole thing, reduced"),
("Ask Somebody This Week","The concrete step"),
("Start With One Person","The close"),
("Go and Make","The commission, applied")))])

MENTAL = ("Mental Health Sundays", [
("Naming It", T(
("It Is Okay to Not Be Okay","Said from the platform"),
("The Silence Is the Problem","Why churches do not talk about this"),
("You Are Not the Only One","The count, said out loud"),
("Mental Illness Is Not a Faith Failure","Correcting a teaching that wounded people"),
("The Sentences That Hurt","Retiring what we say"),
("Just Pray More Is Not Counsel","Naming bad advice"),
("Shame and Guilt Are Different","One of them is from God"),
("The Mask You Wear on Sunday","Performance in a church lobby"),
("How Are You, Really","The question we ask badly"),
("Making This Room Safe","What has to be true before anyone speaks"),
("What We Get Wrong","An honest institutional confession"),
("Diagnosis Is Not Identity","Holding both"),
("Your Brain Is Part of Your Body","The theological point underneath"),
("Sin, Sickness, and Suffering","Distinguishing three things"),
("Spiritual Warfare and Mental Illness","Handled with care"),
("The Person You Are Worried About","A word to the family"),
("Tell One Person","The first step"),
("You Do Not Owe Anyone Your Story","Boundaries around disclosure"),
("Stop Apologizing for It","Permission"),
("Language Matters","How we talk about this"),
("The Statistics in This Room","Made real"),
("It Is Not a Character Flaw","Said plainly"),
("You Are Not Weak","Correcting the assumption"),
("We Are Talking About It Now","The commitment"),
("Bring It Into the Light","The close"))),
("Anxiety", T(
("Anxiety Is Not a Sin","The message that frees people"),
("Three in the Morning","The particular quality of 2 a.m."),
("Do Not Be Anxious","Read as an invitation, not a command to perform"),
("The Peace That Guards","A military verb"),
("Anxious for Nothing, With Instructions","Philippians 4's specific replacement"),
("Look at the Birds","Jesus argues from observation"),
("Today Has Enough","Matthew 6:34 as a practice"),
("The List You Keep Rewriting","A worry solved eleven times on paper"),
("What You Are Actually Afraid Of","Underneath the presenting worry"),
("Panic in the Middle of the Night","Practical and unashamed"),
("Anxiety and the Body","Breath, sleep, and movement"),
("The News Cycle and Your Nervous System","Attention and fear"),
("Anxiety in Children","A word to parents"),
("Social Anxiety at Church","The lobby as an ordeal"),
("Health Anxiety","When the fear is your own body"),
("Financial Anxiety","Money and the 2 a.m. mind"),
("Anxiety About the Future","Providence, practically"),
("Elijah Under the Broom Tree","Food and sleep first"),
("Cast Your Cares","1 Peter 5 and an actual transfer"),
("Write It Down and Hand It Over","The physical practice"),
("Breath Prayer","Ancient practice, simply taught"),
("What Helps and What Does Not","Honest inventory"),
("Medication and Anxiety","Without stigma"),
("You Have Survived Every One","Evidence over reassurance"),
("Peace Be With You","The close"))),
("The Dark", T(
("Depression and Faith","Both true at once"),
("The Dark Night","When God feels absent and you did nothing wrong"),
("David Talked to Himself","Why are you downcast, O my soul"),
("Psalm 88 Has No Happy Ending","And it is in the Bible"),
("A Third of the Psalms Are Laments","Written for this"),
("When You Cannot Feel Anything","Faith without feelings"),
("Getting Out of Bed Is Obedience","Lowering the bar"),
("The Fog","Describing it for those who have not been there"),
("Nothing Is Wrong and Everything Is","The confusing version"),
("Depression After a Loss","Grief that did not lift"),
("Postpartum","A word rarely said in church"),
("Seasonal Darkness","Winter and the body"),
("When It Runs in the Family","Inheritance and hope"),
("The Christian Who Wants to Die","Handled with enormous care"),
("Suicidal Thoughts","Help named in the room"),
("A Friend in the Dark","How to actually show up"),
("Do Not Fix Them","What helping looks like"),
("Sit With Them","Job's friends before they spoke"),
("Jeremiah Wished He Had Not Been Born","In the canon"),
("Small Mercies","What to hold when nothing else"),
("One Day at a Time","Endurance as the goal"),
("It Will Not Always Be Like This","Said without promising a timeline"),
("You Are Still Here","The evidence in front of you"),
("Hold On","The close"),
("He Is Close to the Brokenhearted","Psalm 34, plainly"))),
("Help", T(
("Ask for Help","The hardest step"),
("Therapy and the Church","Allies rather than rivals"),
("Medication Is Not a Failure","A pastoral position, stated clearly"),
("How to Find a Counselor","Practical, with a list"),
("What Therapy Actually Is","Demystifying it"),
("Your Pastor Is Not Your Therapist","Naming the limit honestly"),
("When to Get Help Now","Warning signs, plainly"),
("Paying for Care","The barrier nobody names"),
("Support Groups","What they do that nothing else does"),
("Community Is Treatment","Isolation as the danger"),
("Sleep, Food, Movement","The unspiritual foundation"),
("Screens and Your Mental Health","Attention as a health issue"),
("Substance Use and Self-Medication","Honest and unshaming"),
("The Body Keeps Score","Physical and mental together"),
("Trauma, Briefly and Carefully","Naming without prying"),
("Caring for the Caregiver","The person nobody asks about"),
("A Word to Spouses","Loving someone through it"),
("A Word to Parents","When your child is struggling"),
("A Word to Children of Parents Who Struggle","The other direction"),
("Burnout in Ministry","Naming it about ourselves first"),
("Boundaries as Health","No without guilt"),
("Take the Referral","The specific step"),
("The List in the Lobby","The mechanic"),
("You Do Not Have to White-Knuckle This","The invitation"),
("Get Help This Week","The close"))),
("The Church's Part", T(
("What a Church Owes People Who Struggle","The obligation, named"),
("Preach It More Than Once a Year","Consistency as care"),
("Train the Volunteers","Practical equipping"),
("The Counselor in the Building","Partnership with professionals"),
("A Support Group That Meets Here","The launch"),
("Language From the Platform","Small changes with large effects"),
("Do Not Make It a Testimony Trope","Honoring unresolved stories"),
("The People Who Stopped Coming","Why, and what we would do differently"),
("Care for the Staff","Ministry burnout, addressed institutionally"),
("Confidentiality and Care","Trust as infrastructure"),
("When to Call for Help","Protocol, plainly"),
("Follow Up in Forty-Eight Hours","The commitment"),
("Meals, Rides, and Childcare","Practical care as ministry"),
("Do Not Rush Anyone","Patience as policy"),
("Include Rather Than Refer Away","Belonging through it"),
("A Church That Says the Word","Naming depression out loud"),
("Prayer and Professional Care Together","Both, without apology"),
("The Room After the Service","Staffed and announced"),
("Ask Twice","The pastoral practice"),
("Who Is Missing Today","Noticing as ministry"),
("Build the Referral List","The unglamorous work"),
("Talk to Your Elders About This","Institutional commitment"),
("A Congregation That Carries Each Other","Galatians 6, applied"),
("This Church Will Not Look Away","The promise"),
("You Belong Here","The close"))),
("Hope and Recovery", T(
("The Slow Return of Joy","What healing actually looks like"),
("Recovery Is Not Linear","Preparing for setbacks"),
("You Are Not Where You Were","Progress, honestly measured"),
("What Helped","Testimony from the far side"),
("He Restores My Soul","Psalm 23 for the depleted"),
("Beauty From Ashes","What God grows in scorched ground"),
("The Scars That Stayed","Healing without erasure"),
("Your Story Will Help Someone","Purpose from the pit"),
("From Patient to Helper","2 Corinthians 1"),
("Small Wins Count","Celebrating the incremental"),
("A Rhythm That Holds You","Practices for maintenance"),
("Relapse and Grace","When it comes back"),
("Naming the Warning Signs","Self-knowledge as protection"),
("The People Who Stayed","Gratitude toward the faithful"),
("Learning to Receive Care","Harder than giving it"),
("Joy Is Coming","Promised, not manufactured"),
("Weeping May Stay for the Night","Psalm 30"),
("You Made It Through the Worst Day","Evidence"),
("Purpose After the Dark","Calling from the far side"),
("Help Someone Else Now","The step outward"),
("Tell Your Story Carefully","Testimony that does not wound"),
("Thank the Ones Who Sat With You","Gratitude assigned"),
("God Was There the Whole Time","Said gently, and later"),
("There Is a Way Through","The claim"),
("Keep Going","The close")))])

ANYGIVEN = ("Any Given Sunday", [
("The Gospel, Plainly", T(
("Start Here","For anyone walking in cold"),
("Who Do You Say That He Is","The central question"),
("God Is Not Angry With You","Correcting the picture"),
("Grace, Explained Once","Without jargon"),
("You Cannot Earn It","The offense of the gospel"),
("Sin, Honestly","Named without shaming"),
("Why the Cross","The mechanism, plainly"),
("He Rose","The claim at the center"),
("Repent and Believe","The two verbs"),
("Come as You Are, Actually","Meaning it"),
("Nobody Is Too Far","For the person who thinks they are"),
("It Is Not Too Late","For any closed door"),
("Second Chances Are the Whole Point","Grace without occasion"),
("The Invitation Is Still Open","No expiration"),
("What Would Change If It Were True","Implications over information"),
("Religion or Rescue","The distinction"),
("Follow Me","The invitation Jesus repeated"),
("One Decision Away","The turning point"),
("Today","Urgency without manipulation"),
("Believe","The one-word message"),
("Why Anyone Believes This","The reasons, briefly"),
("What About Your Doubts","Room made"),
("The Whole Gospel in Fifteen Minutes","Compression"),
("What Happens If You Say Yes","Demystifying the decision"),
("He Came for You","Second person, at the end"))),
("Life Questions", T(
("Is This All There Is","Meaning as an entry point"),
("What Are You Building On","Foundations"),
("The Life You Actually Want","Desire and where it points"),
("Why Am I Here","Purpose, plainly"),
("What Happens When You Die","Handled honestly"),
("Why Is There Suffering","The hardest question"),
("Does God Care About My Job","Vocation"),
("Am I Enough","Worth and identity"),
("Why Do I Feel Alone","Loneliness, addressed"),
("What Do I Do With My Anger","Practical"),
("How Do I Forgive","The mechanics"),
("Can People Actually Change","Hope for transformation"),
("What Should I Do With My Money","Stewardship for anyone"),
("How Do I Know What Is Right","Ethics without a lecture"),
("Why Does Nothing Satisfy","Restlessness examined"),
("What Do I Do About Guilt","The relief on offer"),
("How Do I Handle Fear","Practical faith"),
("What Makes a Life Good","The question underneath everything"),
("Who Am I When Nobody Is Watching","Integrity"),
("Why Do I Keep Doing This","Habit and bondage"),
("What Do I Owe My Family","Obligation and love"),
("Is There a Point to Work","Monday, reframed"),
("How Much Is Enough","The question that reorders"),
("What Are You Afraid Of","Naming it"),
("What Do You Want","Jesus' own question))"))),
("Character and Everyday Faith", T(
("Integrity in Private","When nobody is watching"),
("Tell the Truth","Including the small ones"),
("Keep Your Word","Promises as character"),
("Do Your Work Well","Excellence as worship"),
("Be Patient","In traffic and at home"),
("Do Not Repay Evil","The hardest instruction"),
("Guard Your Tongue","James 3, practically"),
("Stop Gossiping","Named directly"),
("Be Generous Quietly","Matthew 6"),
("Forgive Quickly","The discipline"),
("Apologize First","Going first as strength"),
("Own Your Part","The end of blame"),
("Show Up on Time","Small faithfulness"),
("Do the Hard Thing First","Discipline as freedom"),
("Finish What You Start","Follow-through as character"),
("Be Kind to People Who Cannot Help You","The test"),
("Handle Money Honestly","Integrity where it counts"),
("Keep Your Marriage Vows","Fidelity, plainly"),
("Raise Your Children Well","The long assignment"),
("Serve Without Credit","Anonymous faithfulness"),
("Rest Without Guilt","Sabbath as character"),
("Learn to Listen","The underrated virtue"),
("Be Teachable","The trait that predicts everything"),
("Stay Faithful in the Small","Luke 16:10"),
("Character Is What Is Left","The close"))),
("Invitation and Decision", T(
("Come and See","The oldest invitation"),
("What Are You Waiting For","Removing the reasons"),
("The Door Is Open","Access, plainly"),
("You Do Not Have to Clean Up First","Grace ahead of change"),
("Nobody Is Going to Corner You","Removing pressure"),
("Ask Your Question Here","Doubt welcomed"),
("Take a Next Step Today","The mechanic"),
("Say a Prayer You Are Not Sure Of","Honest first prayers"),
("Try It for Ninety Days","The experiment"),
("Read One Gospel","A concrete step"),
("Come Back Next Week","The lowest ask"),
("Talk to Someone After","The relational path"),
("Get Baptized","The public step"),
("Find Three People","Belonging as a step"),
("Bring Someone With You","Multiplication"),
("What Is Actually Stopping You","Naming it"),
("The Cost, Honestly","Counting it"),
("What You Get and What It Asks","Both halves"),
("Half-Belief Is Not Available","Clarifying the choice"),
("Decide Something Today","The close, direct"),
("Nothing Is Required of You Right Now","The close, gentle"),
("Come Home","For the returning"),
("The Table Is Set","Communion as invitation"),
("Stay for Coffee","The relational next step"),
("Yes","The one-word close")))])

BAPTISM = ("Baptism Sunday", [
("What It Means", T(
("Buried and Raised","What happens in that water"),
("Dead to That, Alive to This","Romans 6, plainly"),
("Water Does Not Save You","Clarifying the theology"),
("The First Step of Obedience","Why it comes early"),
("He Was Baptized Too","Jesus in the Jordan"),
("Confess With Your Mouth","The public nature of faith"),
("A Sign and a Seal","What the church has meant by it"),
("Into a Family, Not Just a Faith","Belonging as part of it"),
("The Old Life Is Over","Identity, marked"),
("Union With Christ","The doctrine underneath"),
("Circumcision of the Heart","The Old Testament thread"),
("Noah, the Red Sea, the Jordan","Water throughout the story"),
("One Lord, One Faith, One Baptism","Ephesians 4"),
("Why We Do Not Baptize Twice","Answering the question"),
("Where Christians Disagree","Humility about mode and age"),
("Why We Do It in Public","The congregation as witness"),
("Baptism and Communion","Two signs, one gospel"),
("What It Is Not","Clearing the misunderstandings"),
("The Commission Includes It","Matthew 28's second verb"),
("Every Believer, Without Exception","Nobody is exempt"),
("Marked as His","Ownership language"),
("A Grave and a Womb","Both images at once"),
("Do You Remember Yours","A word to the already baptized"),
("The Water and the Spirit","John 3, carefully"),
("Buried With Him","The close"))),
("Removing the Barriers", T(
("What Are You Waiting For","Removing the reasons people delay"),
("I Am Not Good Enough Yet","The most common obstacle"),
("I Want to Be Sure First","Certainty and obedience"),
("I Do Not Want the Attention","Handling the fear"),
("My Family Will Not Understand","Cost, honestly named"),
("I Was Baptized as a Baby","Handled with respect"),
("I Have Done Too Much","Nobody is too far"),
("I Do Not Have Anyone Here","Belonging offered"),
("What Do I Wear","The practical question nobody asks"),
("Do I Have to Speak","Removing the requirement"),
("What Is Stopping Me","The Ethiopian's question"),
("Today, If You Are Ready","Same-day invitation"),
("You Do Not Have to Plan It","Spontaneous baptism, explained"),
("I Am Not Sure I Will Keep It Up","Grace ahead of performance"),
("I Am Too Old for This","A word to later-life believers"),
("I Am Too Young","A word to students and children"),
("My Spouse Is Not There Yet","Obedience in a divided house"),
("I Did It Before and Walked Away","Returning"),
("What Happens Afterward","Demystifying the next step"),
("The Water Is Warm","Removing the formality"),
("Nobody Is Judging You","Making the room safe"),
("Bring Your Family to Watch","Inviting the household"),
("You Can Decide in the Service","The mechanic"),
("Sign Up in the Lobby","The specific step"),
("Come On In","The close"))),
("Testimony and Witness", T(
("Your Story Is Someone Else's Door","Testimony as evangelism"),
("What Changed","The before and after"),
("Three Minutes in the Water","Coaching the testimony"),
("Testimony Sunday","Building the service on stories"),
("The Whole Church Watches","Why witnesses matter"),
("Invite the People Who Prayed for You","Closing the loop"),
("Baptism as an Invitation","The highest-converting invite a church has"),
("Bring the Person Who Brought You","Full circle"),
("The Family Who Came Because of This","Testimony from the pews"),
("Whole Households","Family baptism"),
("Fathers and Sons in the Water","Generational moments"),
("Baptizing Your Own Child","Handled with care"),
("A Spouse Baptized Later","Patience rewarded"),
("The Friend Who Would Not Give Up","Persistence honored"),
("Record It","Something to keep"),
("Write Your Story Down","Before the memory softens"),
("Tell It This Week","The assignment after"),
("The Congregation Says Yes","Responsive commitment"),
("Applaud","Permission to celebrate loudly"),
("A Photograph and a Certificate","Marking it physically"),
("The Testimony That Filled a Room","Impact, reported"),
("Who Is Watching From the Back","The person deciding"),
("Come Out of the Water Different","The commissioning built in"),
("Say Their Name","Personalizing the moment"),
("Witnesses","The close"))),
("After the Water", T(
("Baptism Is Not Graduation","What comes the day after"),
("Start Here","The seven-day jumpstart for new believers"),
("Find Three People","The first belonging step"),
("Read One Gospel","The first Scripture habit"),
("Learn to Pray","Practical instruction"),
("Tell Someone This Week","The first witness step"),
("Serve Once This Month","The first serving step"),
("Give Something","The first generosity step"),
("Join a Group","The retention mechanic"),
("Take the Class","Membership as the next step"),
("What to Expect in Year One","Honest preparation"),
("You Will Struggle","Grace ahead of the failure"),
("The First Doubt","Preparing them for it"),
("The Friends You Had Before","Relational change"),
("Your Family's Reaction","Handling it"),
("Who Is Discipling You","Assigning a person"),
("The Ninety-Day Follow-Up","The church's obligation"),
("Do Not Disappear","The honest warning"),
("Bring Somebody Next Time","Multiplication from day one"),
("Get Baptized, Then Get Going","Momentum"),
("A Mentor for Every New Believer","The system"),
("What the Church Owes You Now","The commitment, stated"),
("One Year Later","The anniversary check-in"),
("Keep Walking","The close"),
("Now Go","The commission")))])
