# -*- coding: utf-8 -*-
def T(*p): return list(p)

MEMB = ("Membership Sundays", [
("Why Membership", T(
("Committed, Not Merely Present","The difference attendance never makes"),
("The Church Is Not an Audience","What the word meant before we changed it"),
("Members of One Body","1 Corinthians 12 as a membership case"),
("You Cannot Be Discipled Anonymously","The limit of showing up"),
("Be Countable","Join something people can count on you for"),
("Consumers, Critics, or Owners","Three ways to attend"),
("The Covenant Underneath","Promise rather than paperwork"),
("Who Are You Accountable To","The question nobody asks adults"),
("Grafted In","Belonging in Romans 11"),
("Added to Their Number","A church that counted"),
("Membership Is How We Care for You","The pastoral argument"),
("This Is Our Church","Ownership as the shift"),
("The Priesthood of Every Believer","What it obligates you to"),
("Sheep Need a Shepherd","Oversight as a gift"),
("Submit to Your Leaders","Hebrews 13, handled honestly"),
("Church Discipline Requires Membership","The uncomfortable necessity"),
("You Were Placed Here","God arranged the parts"),
("Commitment in a Non-Committal Age","Countercultural belonging"),
("Six Reasons People Wait","And why none hold up"),
("The Cost of Staying a Guest","Ten years, unnoticed"),
("What You Get and What We Ask","Both halves, plainly"),
("Membership Is Not Salvation","Clarifying the distinction"),
("Why We Ask You to Sign","The reason behind the form"),
("What Changes on Monday","Making it concrete"),
("Belong Here","The close"))),
("The Class and the Path", T(
("Come to the Class","The specific, dated ask"),
("What Happens in Four Weeks","Demystifying it"),
("Bring Your Spouse and Your Questions","Lowering the barrier"),
("What We Believe, Plainly","Doctrine without jargon"),
("How We Got Here","The church's own story"),
("Where You Would Fit","Gifts and honest placement"),
("You Can Say No at the End","Removing the pressure"),
("Membership and Baptism Together","Sequencing the steps"),
("Transferring From Another Church","Honoring where you came from"),
("New to Faith Entirely","A different path through the class"),
("What We Expect of Members","Stated without euphemism"),
("What Members Can Expect of Us","The other direction"),
("Giving and Membership","The honest conversation"),
("Serving and Membership","Placement, not pressure"),
("Attendance and Membership","What faithfulness looks like"),
("Voting and Governance","How decisions get made"),
("When Members Disagree","Conflict inside covenant"),
("Leaving Well","The conversation nobody plans"),
("Reaffirming Membership","An annual practice"),
("Members Who Moved Away","Handling it graciously"),
("The Covenant, Read Aloud","Before anyone signs"),
("Sign It in the Service","The public moment"),
("Welcome the New Members","The Sunday after"),
("The Class Starts This Month","The mechanic"),
("Sign Up Today","The close"))),
("The Body Together", T(
("The Parts That Seem Weaker","Indispensable, not tolerated"),
("I Do Not Need You","The sentence Paul rules out"),
("I Am Not Needed","The other excuse"),
("When One Part Suffers","What membership covers"),
("When One Part Is Honored","Shared joy"),
("No Spare Parts","Every member counted"),
("Devoted to One Another","The New Testament's phrase"),
("Bear With Each Other","The unglamorous command"),
("Carry Each Other's Burdens","Galatians 6"),
("Confess to Each Other","James 5's assumed community"),
("Spur One Another On","Hebrews 10's stated purpose"),
("Do Not Give Up Meeting","The habit behind the command"),
("Forgive as You Were Forgiven","Inside a congregation"),
("Speak the Truth in Love","Both halves"),
("Honor One Another","Romans 12's instruction"),
("Serve One Another","The towel, applied"),
("Pray for One Another","The mutual obligation"),
("Welcome One Another","Romans 15's command"),
("Do Not Grumble Against Each Other","James 5:9"),
("Submit to One Another","Mutual, before anything else"),
("The Unity Worth Protecting","Ephesians 4"),
("A Church That Stayed Together","Testimony"),
("Every Member a Minister","Ephesians 4:12"),
("Built Together Into a Dwelling","The building metaphor"),
("Together","The close"))),
("Life as a Member", T(
("Your First Year Here","What to expect"),
("Show Up Consistently","The unglamorous foundation"),
("Find a Group in Ninety Days","The retention step"),
("Serve Somewhere","Placement within a season"),
("Give Regularly","Membership and money"),
("Learn the Names","Belonging as practice"),
("Bring Someone","Members invite"),
("Support the Leaders","Practically and in prayer"),
("Attend the Meeting","Governance participation"),
("Raise Concerns the Right Way","Process over grumbling"),
("Do Not Church Shop From Inside","Faithfulness in a season"),
("When You Are Hurt Here","Staying and speaking"),
("When You Disagree With a Decision","Covenant under tension"),
("Take a Season Off Serving","Sustainability"),
("Mentor Someone Newer","Passing it on"),
("Your Family's Life Here","Household membership"),
("Ten Years From Now","The long view"),
("What You Will Give This Church","Contribution over consumption"),
("What This Church Will Give You","The reciprocal"),
("Members Who Made a Difference","Honoring the faithful"),
("The Meeting You Should Not Miss","Naming it"),
("Renew Your Commitment","The annual moment"),
("Finish Here Well","Long-term faithfulness"),
("Hand It to the Next Generation","Legacy inside a congregation"),
("Stay","The close")))])

FRIENDS = ("Friends Day", [
("Preparing the Congregation", T(
("Who Are You Bringing","The assignment, three weeks out"),
("One Name","Ask God, then write it down"),
("Map Your Circles","The 5F exercise in the service"),
("Everybody Knows Somebody","Removing the excuse"),
("Pray for Three Weeks First","The runway"),
("Somebody Brought You","The reason you are here"),
("What If They Say No","Handling the fear"),
("You Do Not Have to Explain Everything","Lowering the bar"),
("Invite Them to This, Not to Church","Specificity wins"),
("The Text You Have Not Sent","Making it concrete"),
("Offer to Go Together","The variable that moves acceptance"),
("Sit With Them When They Come","The follow-through"),
("Andrew Brought His Brother","The pattern"),
("They Dug Through the Roof","Faith that carries someone"),
("She Told the Whole Town","Testimony without training"),
("Come and See","Philip's answer to an objection"),
("Your Table Is the Front Door","Hospitality first"),
("Belonging Before Believing","The order that works"),
("Make Room","Congregational posture"),
("Empty Seats Are the Point","Reframing a full room"),
("Give Up Your Seat","Practical hospitality"),
("Learn One Name Today","The assignment"),
("What They Will Notice","Seeing your church as a guest does"),
("Next Week Matters More","Sending them with a job"),
("Bring One","The close"))),
("The Day Itself", T(
("Glad You Are Here","The first thing they hear"),
("Start Here","Nothing assumed"),
("Your Friend Brought You for a Reason","Named warmly"),
("Nobody Will Ask Anything of You","Removing the fear"),
("What This Church Actually Believes","Stated once, clearly"),
("Come as You Are, Actually","Meaning it"),
("Nobody Is Doing Fine","Honesty as the front door"),
("What Are You Looking For","Desire as entry"),
("Is This All There Is","Meaning, without a hard sell"),
("God Is Not Angry With You","The assumption, corrected"),
("You Are Not Too Far","For the person who decided they are"),
("The Church Has Hurt You","Conceded, not deflected"),
("Doubt Is Welcome Here","In the first two minutes"),
("Why Bother With Church","The objection, answered"),
("What If It Is True","Following it gently"),
("Second Chances Are the Whole Point","Grace without occasion"),
("The Question Underneath Your Question","Getting to the real one"),
("One Decision Away","The turning point"),
("Everybody Worships Something","Identifying the object"),
("Stay for Coffee","The relational next step"),
("Come Back Next Week","The lowest ask"),
("Take This With You","A physical next step"),
("You Are Welcome Here Anytime","No conditions"),
("Thank You for Coming","Said plainly"),
("Come and See","The close"))),
("Hospitality and the Guest Experience", T(
("The First Ninety Seconds","Where a church is judged"),
("The Parking Lot","The most common reason guests turn around"),
("Signs a Stranger Can Follow","Wayfinding as hospitality"),
("Where Do I Put My Kids","The question that decides it"),
("Do Not Make Them Stand Up","The greeting that repels"),
("What We Say From the Platform","Language a guest can follow"),
("Explain the Offering","Removing the awkwardness"),
("Explain Communion","Or they will feel excluded"),
("The Insider Jokes","What they cost"),
("Announce Less","Guests do not care about the potluck"),
("A Bulletin a Stranger Can Read","Design as welcome"),
("The Bathroom Test","Facilities as hospitality"),
("Coffee That Is Actually Good","Small things that signal care"),
("Train the Greeters","The most undertrained team"),
("Nobody Sits Alone","The congregational assignment"),
("Follow Up Within Forty-Eight Hours","The mechanic"),
("Do Not Ask for Their Money","Not on the first visit"),
("Do Not Ask Them to Sign Anything","Lowering every barrier"),
("What a Guest Notices That You Cannot","Bringing in fresh eyes"),
("Walk Your Own Building","The exercise for the staff"),
("The Second Visit Decides","Where retention happens"),
("Invite Them to One Person, Not a Program","Relational assimilation"),
("Remember Their Name","The simplest ministry"),
("Make It Easy to Come Back","Design for return"),
("Welcome","The close"))),
("Follow-Through", T(
("The Week After Friends Day","The Sunday nobody plans"),
("Call the Ones Who Came","Within two days"),
("Do Not Sell Them Anything","The first follow-up rule"),
("Ask Them to Coffee","The relational path"),
("Invite Them to a Group, Not a Class","Belonging before information"),
("The Second Invitation","Harder and more important"),
("What Did You Think","Asking honestly"),
("If They Do Not Come Back","Grace and persistence"),
("Keep Inviting","Long-obedience evangelism"),
("The Person Who Came for a Year","Patience with the seeker"),
("Baptism Six Months Later","Testimony from a Friends Day"),
("Report the Number","Celebrating the ask"),
("Thank the Inviters","Honoring the congregation"),
("Do It Again in September","Rhythm over event"),
("The Friend Who Became a Member","The full arc"),
("What We Learned","Honest assessment"),
("The Ones Who Almost Came","Following up on the no"),
("Turn Guests Into Hosts","Multiplication"),
("A Culture, Not a Sunday","The real goal"),
("Every Sunday Is Friends Day","Reframing the whole calendar"),
("Ask Again Next Month","Sustained invitation"),
("Keep the Seat Open","Ongoing posture"),
("Who Is Missing Now","Turning it forward"),
("One More","The close"),
("Go and Bring","The commission")))])

BIBLECH = ("Bible Reading Challenge Sundays", [
("Starting", T(
("Read the Bible This Year","The annual launch"),
("You Have Tried This Before","Grace for the failed attempts"),
("Start With One Gospel","The beginner's on-ramp"),
("Twenty Minutes a Day","Making the math achievable"),
("Pick a Plan You Will Finish","Realism over ambition"),
("A Story, Not a Rulebook","Reframing before page one"),
("Which Translation","Answering the question plainly"),
("Read It in Community","The group plan"),
("Listen Instead","Audio for the commute"),
("Read It Out Loud","The ancient practice"),
("Read It With Your Family","The household plan"),
("One Chapter of Proverbs a Day","The simplest plan"),
("Thirty Days in the New Testament","A short first win"),
("Ninety Days Through the New Testament","The intensive"),
("The Psalms for the Hard Year","Reading for your season"),
("A Book a Month","Depth over speed"),
("What to Do When You Hit Leviticus","Naming the wall in advance"),
("Fall Behind and Keep Going","Amnesty built in"),
("Do Not Read Alone","Accountability from day one"),
("Take the Bible We Are Handing Out","The mechanic"),
("Same Page, Same Church","Corporate reading"),
("Mark It Up","Permission to write in it"),
("Ten Minutes Is Not Failure","Lowering the bar"),
("Begin Tomorrow Morning","The launch"),
("Open It","The close"))),
("Staying With It", T(
("Week Three Is Where People Quit","Naming it"),
("The Habit Before the Insight","Consistency first"),
("Attach It to Something You Do","Habit stacking"),
("Journal One Sentence","The retention practice"),
("Memorize While You Read","Adding depth"),
("Read It Slowly","Against the checkbox mentality"),
("What Do You Do With the Hard Parts","Difficult texts, honestly"),
("When It Feels Dry","Faithfulness without feeling"),
("Do Not Skip the Genealogies","Or do, and here is why"),
("Read Until It Reads You","Formation over information"),
("Ask One Question of the Text","The simple method"),
("Who, What, So What","Three questions per chapter"),
("Context Changes Everything","Reading responsibly"),
("Look for Jesus","Christ across the whole"),
("Read It as One Story","The arc"),
("Talk About It at Dinner","Household reinforcement"),
("Text a Verse to Someone","Sharing as retention"),
("Find a Reading Partner","The variable that predicts finishing"),
("The Day You Missed","Restart without starting over"),
("Halfway Through","The mid-plan encouragement"),
("What You Have Noticed","Testimony mid-plan"),
("Do Not Trade Reading for Reading About","Commentaries in their place"),
("The Bible You Will Keep","One physical copy for life"),
("Keep Going","The close"),
("Finish It","The year-end challenge"))),
("Deeper Study", T(
("Study One Book Deeply","Inductive method, simply taught"),
("Observation, Interpretation, Application","The three steps"),
("What Did It Mean Then","Before what it means now"),
("Who Wrote It and Why","Authorship as a key"),
("The Genre Matters","Poetry is not history"),
("Read a Whole Letter in One Sitting","As the church first heard it"),
("Cross-References","Letting Scripture interpret Scripture"),
("Word Studies Without Damage","Doing it responsibly"),
("Read the Old Testament","The half most skip"),
("Read the Prophets","The hardest and most neglected"),
("Read Revelation Carefully","Humility about disagreement"),
("Read Romans Slowly","A chapter a week"),
("Read the Gospels Side by Side","Harmony and difference"),
("Read Acts as a Sequel","Luke's second volume"),
("Read the Psalms as Prayers","Praying rather than studying"),
("Read Proverbs as Probability","Not promise"),
("Read Job Without Fixing It","Sitting in the tension"),
("The Bible on the Bible","2 Timothy 3 and 2 Peter 1"),
("How We Got This Book","Canon, briefly and honestly"),
("Where Scholars Disagree","Humility as method"),
("Tools Worth Owning","Three, not thirty"),
("Teach It to Someone","Learning by explaining"),
("Take the Class","The concrete step"),
("Depth Over Years","The long horizon"),
("Study","The close"))),
("Reading as a Church", T(
("The Bible in a Year, Together","The churchwide campaign"),
("Same Chapter, Same Week","Corporate alignment"),
("Preach What We Are Reading","Aligning the pulpit"),
("Groups Discuss the Reading","Aligning the circles"),
("Families Read the Same Passage","Aligning the homes"),
("Kids Read a Version of It","Aligning the children"),
("An Amnesty Sunday","Everyone behind restarts together"),
("Report the Number Reading","Social proof"),
("Testimony From the Plan","What people are finding"),
("Give a Bible Away","Reading as an outward act"),
("Bibles for the School","A local partnership"),
("Bibles for the Prison","Where the demand exceeds supply"),
("Fund Translation","Two thousand languages waiting"),
("The Church That Read It Together","Vision through outcome"),
("What Changed in a Year","The honest assessment"),
("Read Aloud in the Service","Scripture as its own event"),
("A Church That Knows Its Bible","The long-range goal"),
("Do Not Outsource It to the Pastor","Every member reading"),
("Handle It Reverently","Formation through posture"),
("The Book at the Center","Ecclesiology through Scripture"),
("Start Again Next January","The annual rhythm"),
("Finish Together","The celebration"),
("What We Read, We Became","The retrospective"),
("Give One to a Neighbor","The outward step"),
("Take and Read","The close")))])

IMPACT = ("Impact Sundays", [
("Reporting Well", T(
("What Difference Are We Making","The honest question"),
("Count What Matters","Beyond attendance and giving"),
("Every Number Has a Name","Humanizing the data"),
("Impact Is a Person","Grounding it in one story"),
("Bring the Actual Person","Not the video"),
("Your Giving Did This","Outcome before need"),
("Where Your Offering Went","Radical transparency"),
("Twelve Months of Faithfulness","The annual report as worship"),
("What Ten Dollars a Week Did","Small giving, aggregated"),
("This Is What Your Serving Did","The volunteer report"),
("The Ripple You Cannot See","Long-range impact"),
("Report and Rejoice","Worship rather than marketing"),
("Do Not Ask Today","The discipline of the no-ask Sunday"),
("Honest About What Failed","Credibility through candor"),
("Impact Takes Time","Patience for slow fruit"),
("What We Measured Wrong","Institutional humility"),
("Show the Faces","Photography as reporting"),
("Read the Letter","Testimony from the field"),
("The Family You Helped","One story, told fully"),
("What the City Noticed","External validation"),
("The Numbers and the Names","Both together"),
("What Is Still Undone","Honest about the gap"),
("Thank You, Church","Honoring the congregation"),
("What We Will Do Next","The runway to vision"),
("Well Done","The close"))),
("Local Impact", T(
("Salt and Light in This Zip Code","Local framing"),
("What If We Were Not Here","The clarifying question"),
("The School We Adopted","One partnership, reported"),
("Nobody in This Church Goes Without","Benevolence, reported"),
("We Fed, We Housed, We Sat With","Naming the work"),
("The Street That Changed","Neighborhood impact"),
("Families Out of Crisis","Specific outcomes"),
("The Recovery Group That Started Here","Ministry multiplied"),
("Foster Families Supported","One church, real numbers"),
("The Widow Nobody Forgot","Care, reported"),
("Meals Delivered","Unglamorous and countable"),
("Beds Filled","Housing and shelter partnership"),
("The Prison Where We Show Up","Faithful presence"),
("Jobs Found","Employment ministry outcomes"),
("Debt Eliminated","Financial ministry results"),
("Marriages That Made It","Counseling and mentoring outcomes"),
("Kids Who Stayed","Student ministry retention"),
("The Neighbor Who Came","Outreach that worked"),
("Partners We Funded","Honoring the organizations"),
("The Mayor Called","When a city notices"),
("What We Learned About Our City","Listening reported"),
("Do It Again, Bigger","Scaling what worked"),
("Adopt Another Street","The next commitment"),
("This City Is Better","The claim, evidenced"),
("Keep Going","The close"))),
("Global Impact", T(
("From This Church to the Nations","The global report"),
("The Village That Has Water","Specific and visible"),
("A Church Planted There","Multiplication reported"),
("Translation Progress","Chapters, not abstractions"),
("The Missionary You Support","Made a person"),
("Children Sponsored","Names and photographs"),
("Disaster Response","Where the money went"),
("The Partner Church","Two congregations, one work"),
("Believers Where There Were None","The unreached, reported"),
("Baptisms on the Other Side of the World","Outcome shown"),
("Persecution and Perseverance","Honest reporting"),
("What Our Trip Accomplished","And what it did not"),
("The Nationals Are Leading Now","Indigenous leadership as success"),
("Twenty Years of Faithfulness","Long-horizon fruit"),
("The Well, the School, the Clinic","Development reported"),
("Medical Missions Outcomes","Care and gospel together"),
("Refugees Resettled","Local and global together"),
("Bibles Delivered","Countable ministry"),
("Pastors Trained","Multiplication measured"),
("Where We Are Going Next","The forward ask"),
("Meet the Family You Support","Making it personal"),
("A Video From the Field","Closing the loop"),
("Our Part in a Global Story","Locating the church"),
("Send Us Again","The response"),
("Until Everyone Has Heard","The close"))),
("Impact and the Congregation", T(
("You Did This","Attribution to the church"),
("Not the Staff, the Church","Ownership stated"),
("The Volunteer Hours Behind It","Honoring the labor"),
("The Prayers Behind It","Honoring the intercession"),
("The Givers Behind It","Honoring quietly"),
("Multiplied, Not Added","Impact through the sent"),
("The People We Gave Away","Counting sending as gain"),
("What Ordinary Members Did","Not the professionals"),
("The Ministry Somebody Started","Lay initiative honored"),
("Twenty Years in the Nursery","The long faithfulness"),
("The Person Nobody Sees","Invisible impact"),
("The Family That Fostered","One household's outcome"),
("The Business That Funded It","Marketplace generosity"),
("Students Who Served","The next generation's work"),
("Seniors Who Prayed","The generation that carried it"),
("What This Church Is Known For","Reputation as report"),
("What We Want to Be Known For","Vision through impact"),
("The Ones You Will Meet Later","Eternal framing, carefully"),
("Impact Beyond the Building","Monday through Saturday"),
("The Least of These Have Names","Matthew 25 with faces"),
("Impact on the People Doing It","How serving changed them"),
("Now Imagine Doubling It","The forward vision"),
("What Would You Add","Congregational input"),
("Keep Building","The forward close"),
("Thank You, Church","The close")))])
