# -*- coding: utf-8 -*-
def T(*p): return list(p)

YOUTH = ("Youth Sunday", [
("Student-Led Sunday", T(
("They Preach, We Listen","Handing the platform over entirely"),
("Do Not Let Anyone Look Down on You","Paul to a young leader"),
("The Student Testimony","Ninety seconds, coached, unforgettable"),
("A Student Worship Team","Letting it be imperfect on purpose"),
("What Our Students Would Tell You","The message the adults need to hear"),
("Josiah Was Eight","Young leadership in Scripture"),
("David Was the Youngest","The one nobody called in from the field"),
("Mary Was a Teenager","Courage at fifteen"),
("Samuel Heard First","A boy who heard what the priest missed"),
("Jeremiah Said I Am Too Young","And God disagreed"),
("Timothy's Assignment","Leadership handed to someone under thirty"),
("The Boy With the Lunch","Small offerings, enormous outcomes"),
("Let Them Lead Now","Not later, not eventually"),
("What They See in Us","An honest word from students to adults"),
("Our Church Through Their Eyes","The feedback nobody asks for"),
("Students Serving the Whole Church","Beyond the youth room"),
("The Next Generation Is Here","Present tense"),
("Commission the Seniors","Sending them well"),
("Ask a Student a Real Question","The exercise for the congregation"),
("Hand Them Something Real","Responsibility as discipleship"))),
("Messages for Students", T(
("Who Are You When Nobody Is Watching","Integrity at sixteen"),
("The Phone in Your Hand","Formation by algorithm"),
("Comparison Is Killing You","Naming it plainly"),
("Your Parents' Faith Will Not Carry You","Ownership"),
("Doubt Is Not the Enemy","Making room for questions"),
("Friends Decide Your Future","Proverbs on the company you keep"),
("Sex, Honestly","Without shame and without evasion"),
("Anxiety at School","Practical and unashamed"),
("You Are Not What You Failed At","Identity beyond performance"),
("The Pressure You Are Not Naming","Academic, social, athletic"),
("What Are You For","Purpose before a major"),
("Loneliness in a Crowded Room","The condition nobody posts"),
("Standing Alone","Conviction under social pressure"),
("Your Body Is Not the Point","Image and worth"),
("When Your Family Is Hard","Grace for the student going home to it"),
("The Habits You Build Now","Compound interest on character"),
("What You Do With Your Free Time","Attention as formation"),
("Money at Seventeen","First job, first decisions"),
("Follow Me","The invitation, stated for a student"),
("You Are Not Too Young for Any of This","The whole faith, now"))),
("Parents of Students", T(
("When the Rules Change","Parenting a teenager"),
("Pray More, Say Less","The new primary tool"),
("Your Kid Is Not You","Releasing the projection"),
("The Argument You Keep Having","Naming what it is actually about"),
("Screens and the Household","Practical, without panic"),
("When They Doubt","Do not flinch"),
("The Friends You Do Not Like","Handling it without losing the relationship"),
("Keep the Door Open","The thing that matters most"),
("Apologize to Your Teenager","The most powerful move available"),
("What They Actually Need From You","Shorter list than you think"),
("You Have Four Years Left","Urgency without panic"),
("When They Stop Coming to Church","Grace, patience, and no ultimatums"),
("The Family Table Still Works","Even at sixteen"),
("Their Mental Health","Signs, help, and no shame"),
("Do Not Outsource Discipleship","The youth pastor is not the parent"),
("Model It","The only curriculum that reaches them"),
("Talk About the Hard Things First","Before someone else does"),
("Bless Them Out Loud","Words for a teenager"),
("Let Them Fail Safely","Consequences as formation"),
("Send Them Well","Preparing for the launch"))),
("The Church and the Next Generation", T(
("We Are Not Losing Them, We Are Ignoring Them","The honest diagnosis"),
("Five Adults Per Student","The number that predicts a lasting faith"),
("Do Not Segregate the Whole Church","Intergenerational as strategy"),
("Give Them Something to Do","Responsibility over entertainment"),
("Teach Them the Hard Parts","Depth as respect"),
("A Faith Worth Keeping","What survives college"),
("The Youth Room Is Not a Holding Pen","Integrating students into the body"),
("Older Adults and Students","The relationship nobody builds"),
("Ask Them Their Opinion","And then use it"),
("What We Handed Them","An honest generational assessment"),
("Deconstruction, Pastorally","Non-defensive and unafraid"),
("The Ones Who Left","Why, honestly, and what we would do differently"),
("Budget Like You Mean It","Money as a statement of priority"),
("Volunteers Who Stay","The single biggest factor in youth ministry"),
("Do Not Wait for Them to Be Adults","Ministry now"),
("Baptize the Students","Publicly, and with the whole church watching"),
("Send Them on Mission","The trip that changes a trajectory"),
("Let Them Fail in Ministry","Leadership requires room to be bad at it"),
("Twenty Years From Now","Working backward"),
("They Are the Church Today","Not the church of tomorrow"))),
("Youth Ministry Launch", T(
("More Than a Youth Group","Launching student ministry"),
("We Need Adults","The volunteer recruitment message"),
("Open Your Home to Teenagers","Hosting as ministry"),
("The Small Group That Changed a Kid","Testimony-driven recruitment"),
("You Do Not Have to Be Cool","Removing the qualification myth"),
("What a Youth Leader Actually Does","Demystifying the role"),
("Middle School Is a Calling","Honoring the hardest room"),
("Drive the Van","Serving without teaching"),
("One Year, One Group","The finite ask"),
("Parents as Volunteers","Handled well or handled badly"),
("Safety and Trust","Background checks as care, not bureaucracy"),
("Train Them, Then Trust Them","Leader development"),
("Consistency Beats Charisma","What students actually respond to"),
("The Adult Who Stayed","Longevity as the variable"),
("Feed Them and They Will Come","Practical ministry, unglamorous"),
("Show Up at Their Game","Presence outside the building"),
("Sunday Is Not Enough","The case for midweek"),
("Camp, Retreats, and the Mountaintop","Making it stick afterward"),
("Launch a Ministry to Their Parents","The other half"),
("Sign Up Today","The same-day ask")))])

FAMILY_SVC = ("Family Service Sunday", [
("All-Ages Worship", T(
("Everybody in One Room","The case for worshiping together"),
("Let the Little Children Come","And the disciples who blocked them"),
("Noise Is Not Irreverence","Permission for parents"),
("What Kids Learn by Watching","Formation without instruction"),
("A Service a Nine-Year-Old Can Follow","Designing for the whole room"),
("Sing Something They Know","Music for every age"),
("The Shortest Sermon of the Year","And the most remembered"),
("Kids Serving the Whole Church","Ushers, readers, greeters at eight years old"),
("Read It Together","Scripture in unison, across generations"),
("Communion With Children Present","Explaining it as you go"),
("Baptism With the Kids Up Front","Letting them see it"),
("Object Lessons for Adults","What works for children works for everyone"),
("The Question Time","Letting kids ask from the floor"),
("Grandparents and Grandchildren Together","Four generations, one room"),
("A Family Blessing","Households blessing each other in the seats"),
("Pray Out Loud, Simply","Modeling prayer a child could copy"),
("The Whole Church Says It","Responsive reading as formation"),
("Why We Do What We Do","Explaining the service itself"),
("No Children's Ministry Today","On purpose, once a quarter"),
("Come as a Household","The invitation restated"))),
("Messages Kids Can Follow", T(
("God Made You on Purpose","Identity, simply"),
("Jesus Is Not Angry With You","Correcting an early picture"),
("The Lost Sheep","One story, told well"),
("The Boy With the Lunch","Small things and big outcomes"),
("David and the Giant","Courage, without the moralism"),
("Daniel and the Lions","Faith when it is hard"),
("Noah and the Promise","Judgment and mercy for young ears"),
("Jonah Ran","Nobody is out of reach"),
("The Good Samaritan","Who is my neighbor"),
("Zacchaeus in the Tree","Jesus goes to the wrong house"),
("The Prodigal's Father","Running before the speech is over"),
("Jesus Calms the Storm","Fear, addressed"),
("The Empty Tomb","Easter for children"),
("The First Christmas","Christmas for children"),
("Talking to God","Prayer, taught simply"),
("Saying Sorry and Meaning It","Repentance for a seven-year-old"),
("Being Kind Is Not Enough","The gospel, carefully"),
("You Belong Here","Church as family"),
("The Fruit of the Spirit","Character, memorably"),
("Follow Jesus","The invitation for a child"))),
("Family Formation", T(
("The Home Is the First Church","Where discipleship happens"),
("One Rhythm Is Enough","Starting small"),
("Eat Together","The habit with the deepest effect"),
("Bless Your Children Out Loud","Words for fifty years"),
("Pray Before Bed","The simplest practice"),
("Read One Chapter","Scripture at the table"),
("Talk About the Hard Things","Age-appropriate honesty"),
("Apologize First","Modeling repentance at home"),
("Your Marriage Is Their Foundation","What they absorb"),
("Traditions Built on Purpose","Household culture"),
("Serve as a Family","Mission at home scale"),
("Sabbath in a Busy House","Rest as a family value"),
("The Screens Conversation","Practical, not panicked"),
("Money at the Kitchen Table","Teaching stewardship early"),
("When Your Household Is Hard","Grace for strained homes"),
("Blended Families","Honored rather than tolerated"),
("Single Parents","Carrying it, with a church around them"),
("Grandparents in the Household","Three generations, one roof"),
("What They Will Remember","Working backward"),
("Start This Week","The same-day household commitment"))),
("Milestones and Blessings", T(
("Baby Dedication","The congregation's half of the promise"),
("First Communion","Marking it well"),
("Baptism of a Child","Readiness and how to know"),
("Starting School","Blessing the first day"),
("Entering Middle School","The hardest transition"),
("Getting a Driver's License","Freedom and responsibility"),
("First Job","Work as formation"),
("Graduation","Commissioning rather than releasing"),
("Leaving Home","The blessing at the door"),
("Engagement and Marriage","The household changing shape"),
("A New Baby in the Family","Welcoming across generations"),
("Moving to a New City","Sending a family well"),
("A New Home","Blessing a house"),
("Adoption Finalized","Celebrating with the whole church"),
("Retirement","A milestone the church usually skips"),
("A Significant Birthday","Marking decades"),
("Anniversary Blessings","Honoring long marriages"),
("Loss in the Family","The milestone nobody plans"),
("Becoming a Grandparent","A second assignment"),
("Bless Them Today","Doing it in the service"))),
("Households on Mission", T(
("Your Family Has an Assignment","Mission at household scale"),
("Open Your Table","Hospitality as the family's ministry"),
("Serve Somewhere Together","Once a season, as a household"),
("Know Your Neighbors","The family exercise"),
("Adopt a Family","One household serving another"),
("Give as a Family","Generosity taught by doing"),
("Pray for the Nations at Dinner","One country a week"),
("Foster or Support Someone Who Does","Every family can do one"),
("Invite Someone to Church as a Household","Together rather than individually"),
("The Family That Sent a Missionary","Long-range obedience"),
("Your Home as a Group Host","Opening the living room"),
("Take a Trip Together","Mission as family formation"),
("Teach Your Kids to Notice","Attention as compassion"),
("The Widow Down the Street","One relationship, sustained"),
("Bless Your Block","One street, one household"),
("Say Yes as a Family","Deciding together"),
("What Your Children Will Copy","Mission modeled"),
("A Household That Prays for Others","Intercession as a family habit"),
("Send Your Kids Out","Letting them serve without you"),
("Start on Your Street","The whole message in four words")))])

VOLUNTEER = ("Volunteer Sunday", [
("The Call to Serve", T(
("He Took a Towel","Leadership according to the God who washed feet"),
("Everyone Got Something","1 Corinthians 12 and the end of spectator faith"),
("Serving Is Not Volunteering","Redefining the category"),
("The Body Has No Spare Parts","Why your absence registers"),
("Whatever You Did for the Least of These","Matthew 25, plainly"),
("Use What You Already Have","Monday's skills on Sunday"),
("You Are More Ready Than You Think","For everyone who feels unqualified"),
("Faith Without Works","James, without the guilt trip"),
("Serve Before You Believe","Belonging through doing"),
("The Gift You Have Not Used","Dormant, not absent"),
("Greatness Is Downward","The kingdom's inverted ladder"),
("Two Small Coins","Small offerings and their actual weight"),
("Nobody Is Too New","Serving as the fastest way in"),
("Nobody Is Too Old","The most available people in the church"),
("What Happens If Nobody Does It","The honest math"),
("The Ministry of Showing Up","Consistency over talent"),
("Behind the Scenes","Honoring the invisible ministries"),
("Serving Changed Me","Testimony from someone who did not expect it"),
("Do It for One Person","Scale was never the point"),
("Start With One Hour","The smallest possible yes"))),
("The Ask", T(
("Say Yes for One Season","A finite commitment with an end date"),
("Serve Once and See","No permanent commitment implied"),
("Try Three Things","Discovery through doing"),
("What Are You Good At","Competence as a clue"),
("What Breaks Your Heart","The truer clue"),
("The Slot We Cannot Fill","Naming the specific need"),
("Kids Ministry Is Not the Consolation Prize","Reframing the hardest ask"),
("Parking Lot Ministry","The first ninety seconds of a guest's experience"),
("Hospitality and the Front Door","Where a church is actually judged"),
("Behind a Camera or a Coffee Pot","Technical and practical gifts, honored"),
("Sunday Is Not the Only Option","Serving outside the service"),
("Serve From Home","For the homebound and the busy"),
("Bring Your Family","Serving as household formation"),
("Your Second Yes","For the person already serving somewhere"),
("Lead Rather Than Do","Knowing which one you are for"),
("We Will Train You","Removing the fear of being thrown in"),
("Who Will Be With You","Naming the team before the task"),
("Walk to a Table","The whole ask in four words"),
("Sign Up Before You Leave","The same-day mechanic"),
("The Yes You Have Been Avoiding","Named gently"))),
("Honoring Volunteers", T(
("Thank You, Church","The message that is only gratitude"),
("The Names Nobody Knows","Reading them out loud"),
("Twenty Years in the Nursery","Honoring the long faithfulness"),
("Well Done","What we would say if we said it plainly"),
("You Made This Possible","Impact reported to the ones who did it"),
("The Volunteer Who Never Missed","Consistency, celebrated"),
("What It Cost You","Naming the sacrifice"),
("Your Family Served Too","Honoring the household behind the volunteer"),
("The Ministry You Built","Legacy inside a church"),
("Serve the Servants","A Sunday where staff serves volunteers"),
("Honor Publicly","Why recognition is not vanity"),
("The Ones Who Left and Came Back","Grace for the returning"),
("Nobody Saw It But God","The reward Jesus named"),
("The Church You Are Making","Vision through their eyes"),
("A Meal for the Team","Gratitude with a table"),
("Testimony From Someone You Served","Closing the loop"),
("You Are Not Interchangeable","The specific value of a person"),
("Rest Is Part of Honoring You","Permission built into thanks"),
("What We Would Be Without You","The honest counterfactual"),
("Thank You Is Not Enough","And we will say it anyway"))),
("Sustaining the Team", T(
("Burnout Is Not the Goal","Sustainable serving, stated from the platform"),
("Boundaries Are Spiritual","No without guilt"),
("Serve From Fullness","Refill before you pour"),
("The Volunteer Nobody Replaced","When one person carries too much"),
("It Is Fine to Quit One","Permission that keeps people serving longer"),
("Season, Not Sentence","Matching commitment to life stage"),
("Sabbath for the Serving","Rest built into the schedule"),
("When Serving Became a Job","Recovering the why"),
("The Resentment Nobody Names","Honest about what builds up"),
("Two Deep Everywhere","Building teams that survive a departure"),
("Do Not Serve Alone","Teams over individuals"),
("Ask for Help Before You Need It","The discipline of early asking"),
("When Your Family Is Paying","An honest look at the cost"),
("Take a Break, Not an Exit","Sabbatical for volunteers"),
("The Leader Who Burned Out","Testimony and recovery"),
("Care for the Caregivers","Ministry to the ministering"),
("What We Owe You","The church's obligations to volunteers"),
("Train Your Replacement","Multiplication as sustainability"),
("Say No to Good Things","Focus for the overcommitted"),
("Stay, But Differently","Changing roles rather than leaving"))),
("Leading Volunteers", T(
("You Are More Ready Than You Think","Recruiting leaders who feel unqualified"),
("From Volunteer to Leader","The step that scales a church"),
("Delegate or Drown","Jethro's advice to an exhausted leader"),
("Give the Job Away Completely","Half-delegation is worse than none"),
("Train, Then Trust","Development with a release date"),
("The Leader Who Recruits","Multiplication as a leadership function"),
("Cast Vision Weekly","Why they stay"),
("Know Their Names and Their Lives","Care as leadership"),
("Handle the Volunteer Who Should Not Serve","The conversation nobody wants"),
("When Someone Quits","Responding well"),
("Meetings People Do Not Dread","Respecting their time"),
("Communicate Once, Clearly","The most common failure"),
("Thank Specifically","Generic praise does nothing"),
("Build a Bench","Two deep in every role"),
("Let Them Do It Badly","Room to grow"),
("Ask Them What They Think","And then act on it"),
("Protect Their Sabbath","Leading people who also have jobs"),
("The Team That Became Friends","Community as retention"),
("Raise Up, Then Release","Sending your best leaders out"),
("Lead Like You Are Building People","Not filling slots")))])
