# -*- coding: utf-8 -*-
def T(*p): return list(p)

CATALYTIC = ("Catalytic Sunday", [
("The Single Big Idea", T(
("One Thing","A message with exactly one point and no subpoints"),
("If You Remember Nothing Else","The sermon reduced to a sentence"),
("The Question That Will Not Leave","Landing on an ask rather than an answer"),
("What If This Is True","Following one claim all the way down"),
("Everything Changes Here","The hinge message"),
("The Sentence You Will Repeat","Writing for what gets quoted Tuesday"),
("Say Less","A shorter message that lands harder"),
("The Thing Nobody Says","Naming what the room already knows"),
("Start With the End","Preaching backward from the close"),
("One Passage, All the Way","Depth in place of breadth"),
("The Idea Worth a Whole Sunday","When one thought deserves the room"),
("No Series Required","Complete in itself, by design"),
("What Would You Do With Forty Minutes","Using the whole runway on one thing"),
("The Message You Have Been Avoiding","The one you keep postponing"),
("A Single Story","One narrative, told well, nothing added"),
("The Big Rock","What has to move before anything else can"),
("Preach the Obvious","The thing everyone knows and nobody does"),
("One Word","A message built on a single term"),
("The Sermon That Started It","How a movement begins with one Sunday"),
("Now What","Landing every message on an action"),
("The Idea That Outlives the Series","What people carry past the arc"),
("Say It Once, Say It Well","Repetition is not emphasis"),
("The Uncluttered Sunday","Removing everything that competes"),
("Clarity Over Cleverness","The discipline that costs the most"),
("What Are We Actually Doing Here","The message a church needs annually"))),
("Turning Points", T(
("The Decision You Keep Postponing","Naming it from the platform"),
("Choose Today","Joshua's line, preached as a moment"),
("The Line You Have Been Standing On","Fence-sitting as a decision"),
("Two Roads","The choice, made concrete"),
("What Are You Waiting For","Removing the reasons for delay"),
("The Cost of Not Deciding","Drift as its own answer"),
("Halfway Committed","The most exhausting place to live"),
("Burn the Plow","Elisha, and the decision with no way back"),
("Count the Cost","Luke 14, said plainly before the ask"),
("The Yes You Have Been Avoiding","Gently, and by name"),
("Today If You Hear His Voice","Urgency without manipulation"),
("The Fork","Where two futures separate"),
("One Decision Away","The turning point message"),
("Step Out of the Boat","Faith with a first move attached"),
("Nobody Drifts Somewhere Good","Passivity, honestly examined"),
("What Would Have to Be True","Reverse-engineering a decision"),
("The Prayer That Changes Everything","Not my will but yours"),
("Say Yes Before You Understand","Obedience ahead of clarity"),
("Cross the Jordan","Commitment with a river in front of it"),
("You Cannot Stay Here","When staying is no longer neutral"),
("The Moment You Knew","Testimony-driven turning points"),
("Decide in the Room","Same-day response, structured"),
("What Changes Tomorrow Morning","Making the decision operational"),
("The Door Is Open Now","Windows that do not stay open"),
("Sign It","Written commitment as the turn"))),
("Wake-Up Calls", T(
("You Have Been Coasting","Named without condemnation"),
("Wake Up, Sleeper","Ephesians 5, preached as an alarm"),
("The Slow Drift","How nobody notices leaving"),
("Lukewarm","Revelation 3, and the temperature nobody defends"),
("You Left Your First Love","Diagnosis before remedy"),
("The Comfortable Church","Prosperity as a spiritual risk"),
("Busy Is Not Faithful","Activity mistaken for obedience"),
("What You Tolerate","The standard you actually keep"),
("The Fruit Tells You","Assessment without introspection"),
("Nathan Went to David","Confrontation that saved a king"),
("The Emperor Has No Clothes","Saying what the room knows"),
("You Are Not as Fine as You Think","Honest self-assessment"),
("Repent Is Not a Harsh Word","Recovering the invitation in it"),
("The Second Half of Your Life","Urgency for the middle-aged"),
("What Are You Building","Foundations, tested"),
("Time Is Not Neutral","Numbering your days"),
("The Warning Nobody Heeded","Prophets and their reception"),
("Examine Yourself","The instruction we apply to others"),
("The Sin You Have Made Peace With","Naming it once"),
("Complacency Is Expensive","The compounding cost"),
("If Nothing Changes","The honest projection"),
("You Would Not Accept This Anywhere Else","Standards, applied evenly"),
("The Alarm Is a Mercy","Why God disrupts"),
("Hard Words From Someone Who Loves You","Framing the confrontation"),
("It Is Not Too Late","Landing the wake-up in hope"))),
("Momentum and Starting", T(
("Start Something","The message that begins a movement"),
("Small Beginnings","Zechariah 4, and despising the day of small things"),
("The First Domino","Where a chain reaction begins"),
("Do the Next Thing","Action without the whole plan"),
("Begin Before You Are Ready","Readiness as a moving target"),
("What Are You Waiting For Permission To Do","Naming the self-imposed gate"),
("Momentum Is a Stewardship","Protecting what God started"),
("The First Ninety Days","Establishing something new"),
("One Person Started This","How movements actually begin"),
("Build While You Wait","Faithfulness in the interim"),
("The Compound Effect","Small and daily beats big and occasional"),
("Get in the Game","For the long-time spectator"),
("Break the Inertia","Physics as a spiritual metaphor"),
("Your First Yes","The one that makes the rest easier"),
("Twelve Ordinary People","How the church started"),
("Plant Something","Long-horizon obedience"),
("The Power of a Public Start","Announcing it as commitment"),
("Who Is Going With You","Momentum requires company"),
("Celebrate the First Win","Reinforcing early"),
("Do Not Wait for the Vote","Initiative as faithfulness"),
("Five Loaves","Starting with what is in your hand"),
("The Second Week Is Harder","Preparing for the drop"),
("Keep Going","The message for week four"),
("Multiply It","Building the next round in"),
("Start Today","The same-day launch"))),
("Reset and Return", T(
("Start Over","Grace for the failed start"),
("Come Home","The invitation, made easy"),
("The Prodigal's Long Walk","Returning before you feel ready"),
("New Every Morning","Lamentations at the reset"),
("You Are Allowed to Begin Again","Removing the shame from restarting"),
("Rebuild the Altar","Ezra, and returning to what was abandoned"),
("The Faith You Left","For anyone who walked away"),
("Restore the Years","Joel's promise about lost time"),
("Peter After the Fire","Restoration for the one who failed publicly"),
("Return to Me","Joel's call and a God who runs"),
("What You Went Back To","The old life, honestly assessed"),
("The Church You Left","Naming the hurt before the invitation"),
("Nobody Here Is Keeping Score","Making the return possible"),
("Clean Slate","Forgiveness as an actual event"),
("Rebuild the Wall","Nehemiah applied personally"),
("Start With One Habit","Reset as a small mechanic"),
("Grace for the Relapse","When you have restarted before"),
("The Second Chance Is the Whole Point","Gospel without an occasion"),
("What Kept You Away","Naming it out loud"),
("A God Who Restores","The pattern across Scripture"),
("Forgetting What Is Behind","Paul on moving forward"),
("You Have Not Missed It","Timing and the fear of being too late"),
("Return, and Rest","Isaiah 30 and the shape of repentance"),
("The Table Is Still Set","Communion as the return"),
("Come Back Whenever","The standing invitation"))),
("Hope and Lift", T(
("It Will Not Always Be Like This","Hope for a hard season"),
("Weeping May Stay for the Night","Psalm 30 preached honestly"),
("The Middle Chapter","When the story is not finished"),
("God Is Not Finished With You","Philippians 1:6"),
("Beauty From Ashes","What God grows in scorched ground"),
("The Long Winter","Faithfulness without visible fruit"),
("Hope Is Not Optimism","Anchored in an event, not a temperament"),
("Look Up","Lifting the gaze without denying the ground"),
("He Is Not Done Building","Unfinished work as good news"),
("What God Did in the Waiting","Retrospect as encouragement"),
("The Dawn Comes","Assurance without a timetable"),
("You Have Survived Every Worst Day","Evidence over reassurance"),
("A Future and a Hope","Jeremiah 29, in its actual context"),
("Do Not Grow Weary","Galatians 6:9"),
("Strength for Today","Enough, daily"),
("The God Who Sees You","Hagar in the desert"),
("Carried","When you cannot walk"),
("Songs in the Night","Worship in the dark"),
("He Restores My Soul","Psalm 23 for the depleted"),
("The Anchor Holds","Hebrews 6 and something that does not move"),
("Joy Is Coming","Not manufactured, promised"),
("You Are Not Forgotten","For the overlooked"),
("Lift Your Head","The posture of hope"),
("Something Good Is Coming","Expectation without presumption"),
("Hold On","The whole message in two words")))])

MISSIONS = ("Missions Sunday", [
("The Call to Go", T(
("Here Am I, Send Me","Isaiah 6, and volunteering before you know the job"),
("Go","The command that starts the church"),
("How Will They Hear","Romans 10 and the chain of sending"),
("The Harvest Is Plentiful","The shortage was never on that side"),
("Whom Shall I Send","The question still being asked"),
("You Are Already Sent","Commissioning is not an event"),
("What Would It Cost You","Counting before committing"),
("Go, Send, or Disobey","Three options, honestly named"),
("The Nations Are Waiting","Urgency without manipulation"),
("Called for Life or for a Season","Both are real callings"),
("The Missionary Who Never Left","Local calling honored equally"),
("Your Job Is Your Mission Field","Vocation as deployment"),
("Short Term, Honestly Assessed","What trips do and do not accomplish"),
("Would You Go If Asked","The hypothetical made real"),
("Who Will Go for Us","The plural in Isaiah's call"),
("Abraham Left","Obedience without a map"),
("The Cost of Following","Luke 9 and the hard sayings"),
("Send Me Anywhere","Surrender as the actual prayer"),
("Not Everyone Goes","Grace for the ones who stay"),
("Ask God Where","Discernment before decision"),
("The Missionary Call Today","What it looks like now"),
("Trained, Sent, Supported","The pipeline a church needs"),
("Families on the Field","The whole household goes"),
("Retire to the Field","Second-half calling"),
("Say Yes Before You Know Where","The blank-check prayer"))),
("The Global Church", T(
("Every Tribe and Tongue","Revelation 7 and the finish line"),
("The Church You Have Never Met","Two billion, and growing fastest where it costs most"),
("Where the Gospel Is New","The unreached, defined honestly"),
("Bible Translation","Two thousand languages still waiting"),
("The Persecuted Are Your Family","1 Corinthians 12, globally"),
("What They Pray For","Boldness rather than rescue"),
("The Church in the Global South","Where the center of gravity moved"),
("Missionaries Sent to Us","Reverse mission, and what it exposes"),
("The Ten Forty Window","Geography as a prayer assignment"),
("Cities and the Gospel","Urban mission in a moving world"),
("Refugees in Your Own City","The nations, already here"),
("Islam, Honestly and Charitably","Preparing a congregation to love neighbors"),
("Partnership Over Paternalism","Doing missions without doing harm"),
("Indigenous Leadership","Building what outlives us"),
("Orality","Reaching people who do not read"),
("Medical Missions","The gospel through care"),
("Business as Mission","Access through vocation"),
("Digital Mission","The gospel where borders are closed"),
("Children in the Global Church","The half nobody counts"),
("Pray for a Country","One place, all month"),
("The Long Faithfulness","Fields with no visible fruit for decades"),
("What Your Giving Reached","Impact reported, not requested"),
("Adopt an Unreached People","A church-sized commitment"),
("Come Back and Tell Us","Testimony from the field"),
("Until Everyone Has Heard","The finish line, and why it matters"))),
("The Mission Where You Live", T(
("Your City Is Your Parish","Adopting a place rather than a cause"),
("Jerusalem First","Acts 1:8 in order"),
("The Neighbor You Have Never Met","Proximity as mission"),
("Learn Their Names","The simplest first step"),
("Seek the Welfare of the City","Jeremiah 29, applied"),
("The School Down the Street","One partnership, done well"),
("Adopt a Street","Ninety houses, one church"),
("Presence Before Program","Being there before doing anything"),
("Listen to Your City","Before you serve it"),
("The Least of These Have an Address","Matthew 25, locally"),
("Poverty Without Paternalism","Helping without hurting"),
("Housing, Hunger, and the Church","Practical, local, measurable"),
("Prison and Reentry","The mission field with a gate"),
("Addiction in Your Congregation","Mission that starts inside"),
("The Marketplace as a Field","Where your people already are"),
("Third Places","Where mission actually happens"),
("Hospitality Is Evangelism","The table as strategy"),
("Serve Before You Speak","Earning the conversation"),
("The Church That Blessed Its City","Vision through outcome"),
("What Would the City Miss","The question that clarifies everything"),
("Partner, Do Not Duplicate","Working with what exists"),
("Long Obedience in One Zip Code","Staying as strategy"),
("Every Member a Missionary","Without the slogan"),
("The Mission Field on Your Street","Naming it plainly"),
("Start Where Your Feet Are","The whole message in six words"))),
("Sending and Supporting", T(
("They Sent Their Best","Antioch and the cost of sending"),
("Give, Pray, Go","Three doors, one of them yours"),
("Supporting a Missionary Family","What they actually need"),
("More Than Money","The support nobody budgets"),
("Praying by Name","Specific intercession over general concern"),
("The Home Team","Ministry to those who stay"),
("When They Come Home","Reentry, and the church's part in it"),
("Missionary Kids","The ones who did not choose it"),
("The Field Is Hard","Honest about attrition"),
("Sending Your Own Children","The hardest yes a parent gives"),
("Funding the Work","Faith promise, explained plainly"),
("Adopt a Family","One church, one field, long term"),
("Care Packages Are Not Enough","Deepening the relationship"),
("Visit the Field","What a trip does for the sender"),
("The Missionary Nobody Supports","The gap in every church's list"),
("Retirement and the Field","Aging missionaries and our obligation"),
("When a Missionary Fails","Grace and honesty together"),
("Sending Rather Than Keeping","Giving away your best leaders"),
("The Sending Church","What it costs and what it produces"),
("Multiply Rather Than Add","Churches that plant churches"),
("Your Church Should Have Grandchildren","Measured in generations"),
("A Line Item and a Person","Making the budget human"),
("Report Back to the Church","Closing the loop"),
("Commission Them Well","The service, done right"),
("Go With Them","The invitation to join"))),
("Missions and the Marketplace", T(
("Monday Is Ministry","The largest untapped mission force"),
("Business as Mission","Access where missionaries cannot go"),
("Your Skills Are Needed","Trades, medicine, tech, teaching"),
("The Professional on the Field","Vocation as a visa"),
("Tentmaking","Paul made tents and it was not a fallback"),
("The Company That Blessed a Country","Enterprise as mission"),
("Ethical Business Is Witness","Integrity as evangelism"),
("Employ, Do Not Only Give","Dignity through work"),
("Microenterprise and the Poor","Development that lasts"),
("The Executive Who Went","Second-career mission"),
("Sabbaticals for Mission","A model for professionals"),
("Travel With Purpose","Business trips as ministry"),
("Your Network Is a Field","Relationships as reach"),
("Kingdom Investing","Capital deployed for mission"),
("Give From Your Business","Corporate generosity"),
("Teach a Trade","Skills transfer as ministry"),
("Technology and Access","Digital reach into closed places"),
("Agriculture and the Gospel","Food security as mission"),
("Legal and Advocacy Work","Justice as a mission field"),
("Healthcare Access","Medicine that opens doors"),
("Education as Mission","Schools that change generations"),
("Build Something There","Long-term presence through enterprise"),
("The Marketplace Missionary","Named and commissioned"),
("Your Career Is the Assignment","Reframing a whole life"),
("Deploy What You Already Do","The message that ends the excuse"))),
("Report and Celebrate", T(
("What Your Giving Did","Outcome before the next ask"),
("One Hundred Names","Impact made human"),
("The Village That Has a Well","Specific, visible, measurable"),
("Come and See","Bringing the field into the room"),
("A Letter From the Field","Read aloud, in full"),
("The Church That Started There","Multiplication reported"),
("Twelve Months on the Field","The annual report as worship"),
("Testimony From a Translator","The work behind a Bible"),
("The Trip That Changed Us","Reporting on the senders too"),
("Faces, Not Percentages","How to report impact"),
("What We Learned","Honest about what did not work"),
("Thank You, Church","Honoring the ones who gave"),
("The Long View","Fruit that took twenty years"),
("Where We Are Going Next","Report as a runway to vision"),
("A Baptism on the Other Side of the World","The result, shown"),
("Meet the Family You Support","Making the line item a person"),
("The Partner Church","Two congregations, one work"),
("Send a Video Back","Closing the loop for the field"),
("Celebrate the Senders","The people who never went"),
("Answered Prayer From the Field","Reporting what God did"),
("The Numbers and the Names","Both, held together"),
("What Is Still Undone","Honest about the remaining work"),
("Our Part in a Global Story","Locating a church in the whole"),
("Report and Rejoice","Impact as worship rather than marketing"),
("Now, Who Will Go","Closing the report with the ask")))])
