# -*- coding: utf-8 -*-
def T(*p): return list(p)

# (name, explainer, experience, hinge, items)
NEW10 = [
("Pentecost and the Holy Spirit",
"The birthday of the church, and the doctrine most evangelical congregations never hear a full message on. Twenty-five that treat the Spirit as a person rather than a topic.",
"Read Acts 2 in as many languages as your congregation actually speaks — one verse each, no translation offered. The room hears Pentecost instead of hearing about it.",
{"roll":"A series on the Spirit, spiritual gifts, or the book of Acts.","give":"Church planting and global translation work.",
 "gospel":"The Spirit is how anyone believes anything. Preach the mechanism, not just the invitation.",
 "act":"Ask for one specific thing you cannot do on your own strength this week."},
T(("The Birthday of the Church","Acts 2, and a movement that started in a rented room"),
("Wind and Fire","What the images are doing and what they are not"),
("They Heard in Their Own Language","Pentecost as the reversal of Babel"),
("You Will Receive Power","The promise, and what it was actually for"),
("Who Is the Holy Spirit?","A person, not a force or a feeling"),
("The Comforter","The word Jesus chose, and what it carries"),
("He Will Teach You All Things","The Spirit and how anyone understands Scripture"),
("Grieving the Spirit","A verse that assumes a relationship"),
("Filled, and Filled Again","The tense Paul uses, and why it matters"),
("The Fruit Takes Time","Galatians 5, and formation on a slow clock"),
("The Gifts Are for the Body","1 Corinthians 12, and gifts as plumbing rather than jewelry"),
("Where Christians Disagree","Handling the charismatic question with humility"),
("Led by the Spirit","What guidance actually looks like on a Tuesday"),
("He Intercedes for You","Romans 8 when you have no words"),
("The Deposit Guaranteeing What Is Coming","Ephesians 1 and the down payment"),
("Quench Not","The instruction nobody preaches"),
("Power for Witness, Not Display","Acts 1:8 and the stated purpose"),
("The Spirit and Your Body","Temple language, taken seriously"),
("Three Thousand in One Day","What happened when they finally spoke"),
("Come, Holy Spirit","Asking, plainly, as a congregation"))),

("Crisis Response Sundays",
"The message written in forty-eight hours after a local tragedy, a national event, or a loss inside the congregation. Every pastor needs these and almost none have them ready.",
"Cancel whatever was planned and say so. Then shorten the message, lengthen the silence, and open the front of the room for prayer with staff standing there before the last song ends.",
{"roll":"Grief support, a lament series, or a community response effort.","give":"Direct benevolence to those affected, named specifically.",
 "gospel":"People ask real questions in crisis weeks. Answer them rather than performing certainty.",
 "act":"One concrete act of care this week, assigned rather than suggested."},
T(("When the News Broke","Preaching the Sunday after"),
("We Do Not Have Answers Today","Honest ministry in the absence of explanation"),
("Where Was God?","The question, asked out loud from the platform"),
("Jesus Wept","Grief before theology, in that order"),
("A Psalm for This Week","Lament as the church's oldest response"),
("When It Happened Here","A loss inside this congregation"),
("When It Happened to a Child","The hardest message a pastor preaches"),
("A Death by Suicide","Handling it with care, honesty, and hope"),
("After the Violence","Preaching into fear without feeding it"),
("Natural Disaster","When the loss has no villain"),
("The Long Aftermath","Six weeks later, when the casseroles stop"),
("Anger Is Allowed Here","Making room for the response nobody sanctions"),
("Do Not Explain It Away","The sentences to never say from a pulpit"),
("Sit With Them","What the church is actually for this week"),
("Practical Help, Named","Turning sympathy into a schedule"),
("The Children Are Listening","How to speak so a nine-year-old is not damaged"),
("Rachel Refused to Be Comforted","And God let the grief stand"),
("Job's Friends Got It Right for Seven Days","Then they opened their mouths"),
("Hope That Is Not a Platitude","Resurrection preached where it is tested"),
("We Will Not Rush You","Ending the service by saying it plainly"))),

("Fall Launch and Back to Church",
"Late August through September — the second-biggest reset of the year, when families re-enter routine and will commit for the first time since January. Most churches sleep through the window.",
"Put everything on one card: the group semester, the serving teams, the kids' registration, and one date for all of it. Then hold a single sign-up Sunday rather than four competing announcements across five weeks.",
{"roll":"The full fall semester — groups, serving, kids and student ministry, and the fall series.","give":"Curriculum, childcare, and leader training for the semester.",
 "gospel":"Back to Church Sunday brings people who left. Preach for the returning, not only the new.",
 "act":"One card, every commitment, signed and handed in before you leave."},
T(("Start Again","The Sunday the whole church resets"),
("Back to Church","A word for anyone who has been away"),
("The Second January","Why late August matters more than you think"),
("What Are You Committing To This Year?","One card, every decision"),
("Summer Scattered Us","Regathering as a spiritual act"),
("The First Day of School for Everyone","Households in transition, all at once"),
("Bring Someone Back","Reaching the ones who drifted"),
("New Rhythms, Chosen on Purpose","Building the calendar before it builds you"),
("What Slipped Over the Summer","Honest reassessment without shame"),
("The Year Ahead in One Page","Casting the whole fall in ten minutes"),
("Sign Up for One Thing","Focus over enthusiasm"),
("Your Kids Need a Place","Registration as discipleship"),
("If You Are New to This Town","September is when people move"),
("Come Back Whenever","The standing invitation, restated"),
("This Church Missed You","Said plainly, without guilt"),
("Fresh Start in September","For anyone who failed at January"),
("Who Is Not Back Yet?","The congregation's assignment"),
("Teachers, Students, and the School Year","Blessing the ones going back"),
("The Fall Table","Hospitality as the season's practice"),
("Everything Starts Next Week","Momentum with a date on it"))),

("Church Anniversary and Homecoming",
"The Sunday a congregation tells its own story. Honoring the people who built it, naming what has changed, and handing the next chapter to a generation that was not there for the first one.",
"Line the walls with photographs from every decade, unlabeled, and let people find themselves. Then have the oldest member and the youngest read the same passage back to back.",
{"roll":"A vision series, a legacy giving conversation, or a capital effort.","give":"Legacy and endowment giving, introduced with the history in the room.",
 "gospel":"Former members return on homecoming. Some of them left the faith, not just the church.",
 "act":"Write one memory on a card for the archive. Invite one person who used to be here."},
T(("Ebenezer","Thus far the Lord has helped us"),
("The People Who Built This","Honoring the ones who are not here to hear it"),
("What This Church Was For","Recovering the original assignment"),
("Tell the Story Again","Because half the room has never heard it"),
("The Founders' Faith","What they risked, and what it cost them"),
("What Has Changed and What Has Not","Honest continuity"),
("The Building Is Not the Church","Said in the building, on its birthday"),
("Homecoming","A word to everyone who used to be here"),
("Why People Left","Naming it honestly rather than politely"),
("The Second Generation","Owning a faith you inherited"),
("Stones of Remembrance","Building a marker the next decade will need"),
("Every Name in the Book","The people this church actually reached"),
("The Hard Years","Telling the parts nobody puts in the brochure"),
("Who Prayed for You Before You Were Born","Intercession across generations"),
("Passing the Baton","Handing leadership to people under forty"),
("What Will They Say in Twenty Years?","Working backward from the next anniversary"),
("The Cemetery and the Nursery","Both on one property, both telling the truth"),
("Faithful in a Small Place","For congregations that never grew large"),
("A Church That Sent People Away","Counting what you gave up as gain"),
("The Next Chapter Starts Today","Anniversary as a launch rather than a look back"))),

("Healing and Anointing Sundays",
"James 5 taken at face value. A service built around praying for the sick, with oil, with elders, and without either theatrics or embarrassment.",
"Elders at the front with oil, and no music playing. Let it be quiet enough that people can hear each other being prayed for. Announce it two weeks ahead so nobody is ambushed.",
{"roll":"A series on suffering, or the launch of a care and visitation ministry.","give":"Benevolence and medical assistance for people in this congregation.",
 "gospel":"Physical need brings people who would never come for a sermon.",
 "act":"Come forward, or name one person you are coming forward on behalf of."},
T(("Is Anyone Among You Sick?","James 5, read plainly"),
("Call for the Elders","The instruction the church quietly stopped following"),
("Anointing With Oil","What it means and what it does not"),
("The Prayer Offered in Faith","Handling the promise honestly"),
("When Healing Does Not Come","The message that has to be preached alongside"),
("Paul's Thorn","A man who asked three times and was told no"),
("He Healed Them All, and Then He Left Town","Jesus and the ones still waiting"),
("Confess to Each Other","The clause in James nobody quotes"),
("The Friends Who Carried Him","Faith exercised on someone else's behalf"),
("Do You Want to Get Well?","The question Jesus asked a paralyzed man"),
("Bodies Matter","Why the incarnation makes this Christian"),
("Chronic","Faith over decades rather than moments"),
("Mental and Physical","Refusing the false split"),
("The Doctor and the Elder","Medicine and prayer as allies"),
("Caring for the Caregiver","The person nobody prays for"),
("Anointing the Dying","When healing means something else"),
("Lament as Part of Healing","Naming it before asking"),
("Testimony, Carefully","Sharing answered prayer without wounding the unanswered"),
("The Church as a Hospital","What that metaphor obligates us to"),
("Come Forward","The invitation, made easy"))),

("Mental Health Sundays",
"The fastest-growing pastoral need in most congregations and one of the thinnest areas of preaching resource. Twenty-five written to reduce shame rather than manage it.",
"Have a licensed counselor present and introduced by name, seated in the room rather than mentioned in an announcement. Publish the referral list in the bulletin before the message rather than after.",
{"roll":"A support group launch, a care ministry, or a series on the Psalms.","give":"Counseling subsidy for people who cannot afford it.",
 "gospel":"Grace for people who have been told their struggle is a faith problem.",
 "act":"One person told the truth, and one referral taken from the table in the lobby."},
T(("It Is Okay to Not Be Okay","Said from the platform, which is the point"),
("Anxiety Is Not a Sin","Correcting a teaching that has wounded people"),
("Elijah Under the Broom Tree","Food and sleep before a word from God"),
("The Dark Night","When God feels absent and you are not doing anything wrong"),
("David Talked to Himself","Preaching to your own soul"),
("Depression and Faith","Both true at the same time"),
("Medication Is Not a Failure","A pastoral position, stated clearly"),
("Therapy and the Church","Allies rather than rivals"),
("The Psalms Were Written for This","A third of them are laments"),
("Just Pray More Is Not Counsel","Retiring the sentences that hurt"),
("Panic in the Middle of the Night","Practical, unashamed, and specific"),
("Shame and Guilt Are Different","One of them is from God"),
("Loneliness","The condition underneath a great deal of it"),
("When Your Child Is Struggling","A word to parents"),
("When Your Spouse Is Struggling","A word to the other half"),
("Burnout in Ministry","Naming it about ourselves first"),
("Addiction and the Long Road","Grace without minimizing"),
("Suicidal Thoughts","Handled with care, with help named in the room"),
("The Body Keeps Score","Physical health and mental health together"),
("You Are Not Alone in This Room","The count, said out loud"))),

("Orphan, Foster and Adoption Sunday",
"November's emphasis, and one of the few Sundays where a message converts directly into a household changing shape. Twenty-five that make the ask without making anyone feel guilty for not answering it.",
"Have three families stand — one fostering, one adopting, one supporting — and name the specific ways the church backs each of them. Then hand out three cards: foster, adopt, and support. Most people take the third and that is a win.",
{"roll":"A foster and adoption support ministry, and a wraparound care team.","give":"Adoption fund, foster care supplies, and respite childcare.",
 "gospel":"Adoption is the metaphor Scripture uses for what God did. Preach it both ways.",
 "act":"Take a card. Foster, adopt, or support — everyone can do one of the three."},
T(("Religion That God Accepts","James 1:27, read as an assignment"),
("You Were Adopted First","The gospel in the same word"),
("A Father to the Fatherless","God's self-chosen title"),
("Not Everyone Can Adopt","Everyone can do something"),
("The Wraparound Team","How a church makes one family possible"),
("Moses in a Basket","The Bible's first foster placement"),
("Esther Was Raised by a Cousin","Family formed by need rather than birth"),
("Defend the Cause of the Fatherless","Isaiah's repeated instruction"),
("The Cost, Honestly","What nobody tells you before you say yes"),
("When It Is Hard","Trauma, disruption, and staying anyway"),
("Aging Out","The eighteen-year-olds nobody talks about"),
("Reunification Is the Goal","Loving a child you may not keep"),
("Kinship Care","Grandparents and relatives raising children"),
("The Birth Mother","Honoring her in the story"),
("Transracial Families","Handled with humility and honesty"),
("The Siblings Already in the House","What it costs your other children"),
("Respite Is Ministry","The simplest way in"),
("One Church, One Agency","Partnership over program"),
("What the City Would Notice","If every church took one family"),
("Take a Card","Foster, adopt, or support"))),

("The Persecuted Church",
"The global body, and the Sundays that reframe what American Christians call hardship. Twenty-five written to inform and intercede rather than to alarm.",
"Read a letter from a believer in a restricted country, in full, in place of the sermon's opening. Then pray by country, out loud, with the names on the screen.",
{"roll":"A missions emphasis, a global prayer season, or a partnership with a specific field.","give":"Bible translation, persecuted-church relief, and field partners.",
 "gospel":"A faith worth dying for is a faith worth examining. Say that to the skeptic in the room.",
 "act":"Adopt one country and pray for it every day this month."},
T(("The Church You Have Never Met","Two hundred million and counting"),
("Blessed Are the Persecuted","The beatitude nobody wants"),
("Remember Those in Prison","Hebrews 13, as though you were with them"),
("If One Part Suffers","1 Corinthians 12 applied globally"),
("The Cost of a Bible","Where owning one is a crime"),
("Paul Wrote From Jail","Most of the New Testament's joy came from a cell"),
("The Blood of the Martyrs","Why persecution has never worked"),
("What They Pray For","Not rescue. Boldness."),
("Comfort Is Not the Goal","Reframing American expectation"),
("The Underground Church","Meeting in houses, as it began"),
("Converts From Other Faiths","What it costs to change your mind"),
("The Families Left Behind","Widows and children of the imprisoned"),
("Praying by Name","Specific intercession over general concern"),
("Do Not Be Surprised","1 Peter and the expectation of hostility"),
("Loving Enemies Under Real Threat","The hardest command, tested"),
("Where the Church Is Growing Fastest","And why that is not a coincidence"),
("Refugees in Your City","The persecuted church, already here"),
("Advocacy as Ministry","Using a voice that is not restricted"),
("The Long Faithfulness","Believers who never saw relief"),
("Adopt a Country","The month-long assignment"))),

("Weddings, Funerals and Milestones",
"Not Sundays, and the highest-stakes preaching a pastor ever does. Two hundred people who never attend church, forty-eight hours to write, and no library anywhere. This is the largest gap in the whole collection.",
"Preach the gospel in both, briefly and without an altar call. The room is not hostile, it is unfamiliar, and a short honest word lands where a long one would not.",
{"roll":"Premarital or grief ministry, and the follow-up nobody does two weeks later.","give":"None. Never at either service.",
 "gospel":"The highest concentration of unchurched people a pastor will address all year, in a moment when they are actually asking.",
 "act":"Follow up with the family fourteen days later, when everyone else has stopped."},
T(("A Wedding Homily in Eight Minutes","Short, warm, and about more than the couple"),
("The First Miracle Was at a Wedding","John 2, and a God who came to a party"),
("Covenant, Not Contract","The distinction the whole ceremony rests on"),
("Love Is Patient, Read Honestly","1 Corinthians 13 rescued from the greeting card"),
("A Second Wedding","Grace and honesty at a remarriage"),
("When the Family Is Complicated","Blended households at the altar"),
("The Charge to the Couple","What to say that they will still remember"),
("A Funeral for a Believer","Grief and confidence, held together"),
("A Funeral for Someone You Are Not Sure About","Honesty without false comfort"),
("A Funeral for a Child","The hardest forty-eight hours of a pastor's life"),
("A Funeral After a Suicide","Care, truth, and no speculation"),
("A Graveside in Ten Minutes","Cold, short, and unforgettable"),
("Eulogy Versus Sermon","Knowing which one you were asked for"),
("The Room Is Full of People Who Never Come","Preaching to them without ambushing them"),
("Reading the Twenty-Third Psalm Well","The most-requested text, done with care"),
("What We Say About Heaven","What Scripture actually promises"),
("A Memorial Months Later","When the service is delayed"),
("Infant Dedication and Loss","Both, and how to hold them"),
("Milestone Blessings","Confirmation, license, first job, new home"),
("Fourteen Days Later","The follow-up that makes the difference"))),

("Sending and Multiplication",
"The Sundays a church gives away its best people on purpose — a plant team, a campus launch, a missionary family, a staff member leaving well.",
"Have the sending church physically surround the team, hands on shoulders, and read the commissioning aloud together rather than having the pastor read it over them.",
{"roll":"A church planting residency, a missions pipeline, or a campus launch season.","give":"Plant funding, missionary support, and the first year of a new work.",
 "gospel":"Multiplication is the visible argument that this is worth giving your life to.",
 "act":"Commit to the team financially, in prayer, or by going with them."},
T(("Send Us","Antioch gave away its two best leaders"),
("The Church That Gives People Away","Counting the loss as gain"),
("Commissioning a Plant Team","The service, done well"),
("A New Campus","Multiplication rather than addition"),
("Sending a Missionary Family","The cost to them and to us"),
("When a Staff Member Leaves Well","Honoring rather than absorbing the loss"),
("The Ones Who Stay","A word to the congregation that remains"),
("Every Church Should Have Grandchildren","Multiplication measured in generations"),
("Paul and Barnabas Split","Two fruitful works from one conflict"),
("Timothy Went","Discipleship that ends in deployment"),
("Raise Up, Then Release","Leadership development with an exit"),
("The Cost of Sending","Money, people, and momentum"),
("You Are Not Losing Them","Reframing for the people who feel it as loss"),
("Go With Them","The invitation to join the team"),
("A Church of Two Hundred Can Do This","Multiplication is not a size question"),
("Praying for the New Work","Ongoing rather than ceremonial"),
("The First Year Is the Hardest","Honest expectations for a plant"),
("Sending Into Your Own City","Multiplication does not require distance"),
("Sending Students","Commissioning the ones going to college"),
("Lay Hands and Let Go","The commissioning moment itself"))),
]

FORTY = ("40-Day Campaigns",[
("Formation", T(
("Forty Days of Purpose","Why you are here, over six weeks"),
("Forty Days of Prayer","The church's longest sustained ask"),
("Forty Days in the Word","Scripture as a churchwide habit"),
("Forty Days of Surrender","Laying it down in stages"),
("Forty Days of Listening","Learning to hear rather than only speak"),
("Forty Days of Obedience","One thing, all the way through"),
("Forty Days of Worship","Beyond Sunday and into ordinary time"),
("Forty Days in the Wilderness","Lent as formation rather than deprivation"),
("Forty Days of Freedom","Naming and breaking what holds you"),
("Forty Days of Rest","Sabbath as a churchwide discipline"),
("Forty Days of Humility","Going last, deliberately, for six weeks"),
("Forty Days of Faith","Trust built by repetition"),
("Forty Days of Gratitude","The practice that reorders a congregation"),
("Forty Days of Confession","The discipline the church dropped"),
("Forty Days of Following","Discipleship as apprenticeship"),
("Forty Days with Jesus","The Gospels, read as a church"),
("Forty Days of Becoming","Character over six weeks"),
("Forty Days of Silence","Ten minutes a day, for a whole congregation"),
("Forty Days of Renewal","For a church that needs one"),
("Forty Days of Beginning Again","The restart campaign"))),
("Family and Home", T(
("Forty Days of Family","The household as the unit of formation"),
("Forty Days of Marriage","Six weeks aimed at the foundation"),
("Forty Days of Parenting","One practice a day"),
("Forty Days of Blessing","Words spoken over the people in your house"),
("Forty Days at the Table","Meals as the church's oldest formation tool"),
("Forty Days of Legacy","What transfers, and what does not"),
("Forty Days of Forgiveness","Working one relationship all the way through"),
("Forty Days of Presence","Attention as the scarce resource"),
("Forty Days of Home","Building a household culture on purpose"),
("Forty Days of Honor","The commandment, applied for six weeks"),
("Forty Days for Fathers","A churchwide campaign aimed at the men"),
("Forty Days for Mothers","The parallel, and the harder one to schedule"),
("Forty Days of Grandparenting","The generation with the longest view"),
("Forty Days for Single Parents","Carrying it, with a church around you"),
("Forty Days of Rebuilding","After the household broke"),
("Forty Days of Family Prayer","The rhythm most homes never establish"),
("Forty Days of Stories","Telling your family its own history"),
("Forty Days of Hospitality","Opening the door for six weeks"),
("Forty Days of Peace at Home","Changing the tone of a household"),
("Forty Days Together","The whole-church family campaign"))),
("Mission and Community", T(
("Forty Days of Community","Life together, as a churchwide practice"),
("Forty Days of Serving","Everybody serves somebody, for six weeks"),
("Forty Days of Neighboring","The people whose names you do not know"),
("Forty Days of Invitation","One name, prayed for and asked"),
("Forty Days of the City","Adopting a place rather than a cause"),
("Forty Days of Witness","Telling it, daily, in your own words"),
("Forty Days of Compassion","Practical mercy over six weeks"),
("Forty Days of Justice","Micah 6:8 as a campaign"),
("Forty Days of Reconciliation","Going first, across every line"),
("Forty Days of the Nations","Global prayer, a country a day"),
("Forty Days of Multiplication","A church that sends"),
("Forty Days of Hospitality","The table as the mission field"),
("Forty Days of Unity","For a church that has been divided"),
("Forty Days of Presence in the Marketplace","Monday as ministry"),
("Forty Days of Encouragement","One person a day, named"),
("Forty Days of Listening to Your City","Before you serve it"),
("Forty Days of Prayer Walking","The neighborhood, on foot"),
("Forty Days of Open Homes","Every household hosts once"),
("Forty Days of Going","The step you keep avoiding"),
("Forty Days of Better Together","The whole-church initiative"))),
("Generosity and Stewardship", T(
("Forty Days of Generosity","The flagship giving campaign"),
("Forty Days of Financial Freedom","Debt, margin, and a plan"),
("Forty Days of Enough","Contentment as a churchwide discipline"),
("Forty Days of Open Hands","Holding everything loosely"),
("Forty Days of First Fruits","Reordering a budget"),
("Forty Days of Stewardship","Time, talent, treasure, and body"),
("Forty Days of Simplicity","Less, on purpose, together"),
("Forty Days of Giving It Away","One thing a day"),
("Forty Days of Trust","Providence tested in a bank account"),
("Forty Days of Work","Vocation as worship"),
("Forty Days of Time","The harder currency"),
("Forty Days Toward Debt-Free","A church that changes its own numbers"),
("Forty Days of Legacy Giving","Past your own lifetime"),
("Forty Days of Sacrifice","The campaign that costs something"),
("Forty Days of Sowing","2 Corinthians 9, over six weeks"),
("Forty Days of Honest Money","Looking at the actual numbers"),
("Forty Days for Business Owners","Profit and faithfulness together"),
("Forty Days of Provision","Counting what came"),
("Forty Days of Building","The capital campaign devotional"),
("Forty Days of God Owns It All","The Ron Blue line, as a campaign"))),
("Health and Wholeness", T(
("Forty Days of Whole Life Health","Body, soul, mind, and relationships"),
("Forty Days of Flourishing","The Harvard framework, biblically anchored"),
("Forty Days of Rest","Sleep, Sabbath, and margin"),
("Forty Days of Movement","Stewardship of a body"),
("Forty Days of Emotional Health","Naming what you feel"),
("Forty Days of Healing","After the loss, the diagnosis, the betrayal"),
("Forty Days of Peace","Anxiety, addressed daily"),
("Forty Days of Freedom From Comparison","Off the feed, together"),
("Forty Days of Nourishment","Food, honestly and without shame"),
("Forty Days of Boundaries","Saying no as a spiritual practice"),
("Forty Days of Recovery","One day at a time, with a church around you"),
("Forty Days of Wholeness","Integration rather than compartments"),
("Forty Days of Sabbath Rhythm","Weekly rest as a churchwide commitment"),
("Forty Days of Attention","What you look at is forming you"),
("Forty Days of Courage","One brave thing a day"),
("Forty Days of Hope","For a congregation in a hard season"),
("Forty Days of Renewal for Leaders","Aimed at the staff and volunteers"),
("Forty Days of Whole Family Health","The household edition"),
("Forty Days of Coming Alive","The invitation campaign"),
("Forty Days to Whole","The flagship health campaign")))])

SPRINTS = ("10-Day Sprints",
"Fifty short, intense, finishable pushes. A sprint is not a shorter journey — it is a different instrument. One thing, ten days, all in, and a visible finish line the whole way.",
"Announce the finish line before the start line. Put the end date on the screen, the card, and the wall, and run a two-minute report on day eleven. A sprint without a public finish is just a suggestion.",
{"roll":"Any campaign as an on-ramp, or standalone between series.","give":"Sprint guides and the cause the sprint serves.",
 "gospel":"Ten days is short enough that a skeptical friend will do it alongside someone.",
 "act":"Pick your sprint today. It starts tomorrow morning and ends on a date you can see."},
T(("Ten Days of Prayer","The sprint that starts everything else"),
("Ten Days of Silence","Ten minutes of nothing, daily"),
("Ten Days of Scripture","One chapter, every morning"),
("Ten Days of Gratitude","Named out loud, daily"),
("Ten Days of Generosity","One act a day, escalating"),
("Ten Days of Serving","Somebody, every single day"),
("Ten Days of Fasting","Food, screens, noise, or opinion"),
("Ten Days of Forgiveness","One person, worked all the way through"),
("Ten Days of Encouragement","One specific word to one person daily"),
("Ten Days of Invitation","One name, prayed for and asked"),
("Ten Days Off the Feed","The fast you will actually feel"),
("Ten Days of Early Mornings","The hour before the house wakes"),
("Ten Days of Rest","Margin, imposed deliberately"),
("Ten Days of Honesty","Including the small ones"),
("Ten Days Without Complaining","The reflex, examined"),
("Ten Days of Listening","To God and to one person"),
("Ten Days of Confession","The practice nobody teaches"),
("Ten Days of Memorizing","One passage, built in"),
("Ten Days of Sabbath Practice","Rest as trust"),
("Ten Days of Simplicity","Less, on purpose"),
("Ten Days of Family Prayer","The household sprint"),
("Ten Days of Marriage Attention","The foundation, ten days running"),
("Ten Days of Blessing Your Children","Words spoken daily"),
("Ten Days at the Table","Eating together, every night"),
("Ten Days of Undivided Attention","Phones in a basket"),
("Ten Days of Going First","Repair, daily"),
("Ten Days of Honoring Your Parents","The commandment, sprinted"),
("Ten Days of Hospitality","The door opened daily"),
("Ten Days of Neighboring","Learning names"),
("Ten Days of Prayer Walking","Your street, on foot"),
("Ten Days of Courage","One brave thing a day"),
("Ten Days of Humility","Going last"),
("Ten Days of Patience","In traffic and at home"),
("Ten Days of Self-Control","The fruit nobody wants"),
("Ten Days of Boundaries","No without guilt"),
("Ten Days of Renewing Your Mind","What you feed it"),
("Ten Days of Caring for Your Body","Stewardship, not vanity"),
("Ten Days of Facing the Fear","The thing you avoid"),
("Ten Days of Contentment","Wanting what you have"),
("Ten Days of Honest Money","The actual numbers"),
("Ten Days of Giving First","Order of operations"),
("Ten Days of Work as Worship","Monday, reframed"),
("Ten Days of Purpose","Why you are here"),
("Ten Days for New Believers","The first ten days after a decision"),
("Ten Days Back","For anyone restarting"),
("Ten Days for the Skeptic","For anyone still deciding"),
("Ten Days in John","The flagship reading sprint"),
("Ten Days in Philippians","Joy from a cell"),
("Ten Days in James","Practical faith, a page a day"),
("Ten Days to Easter","The final sprint into Holy Week")))
