# -*- coding: utf-8 -*-

CURRIC = {
"line":"You already preached it. Now make it a curriculum.",
"intro":"Every sermon series a pastor has ever preached is a small group study he never got around to writing. The material exists, the exegesis is done, the illustrations are already tested on a live room. What is missing is the six-session shape, the questions, and the leader notes &mdash; and that is the part we have done thirty thousand times.",
"how":[
("Give us the series","Six sermons, or four, or the whole year. Audio, video, manuscripts or bullet-point notes &mdash; whatever exists. If it was preached, it can be converted."),
("We find the shape","A sermon is built to be heard once. A session is built to be discussed. The big idea usually survives; the structure almost never does, so it gets rebuilt around a question rather than a point."),
("Questions that open, not quiz","Nobody answers a question they think has a right answer. The opening question is one anybody can answer, the middle ones go somewhere, and the last one asks for a decision."),
("The leader gets help","Notes in the margin: what this question is for, what to do when nobody talks, what to do when one person talks too much, and where the session is likely to go sideways."),
("Then the rest of it","Once there is a session, everything else follows &mdash; the daily devotional, the student version, the children's version, the journal, the host guide."),
],
"formats":[
("Six-session study","The default. Fits a semester, a campaign, or a fall launch."),
("Four-session study","For a shorter series or a first attempt at group life."),
("Eight to twelve weeks","The Adult Bible Fellowship shape, for churches that teach in class format."),
("One-off session","A single message, discussed once. The lowest-commitment thing a group can do."),
("Sermon-based, weekly","The series and the group run in the same week, all season. This is the model that grows churches."),
],
"leader":[
("Host, do not teach","The single most important sentence in leader training. A host opens a home and asks the questions. Nobody has to be a Bible teacher, and telling people otherwise is why churches cannot recruit."),
("The first four minutes","How a group starts decides how it goes. There is a script for it."),
("Silence is working","Count to seven before you rescue a question. The answer is almost always in the pause."),
("The talker and the silent one","What to do about both, without embarrassing either."),
("When someone says something wrong","The hardest moment in group leadership, handled without a lecture."),
("Care beyond the study","When to pray, when to call, and when to bring in a pastor."),
],
"why":"This is the part of the business nobody else is in. Sermon sites sell study questions as an attachment to a series they wrote. Nobody takes what a pastor already preached and turns it into curriculum his own people will recognize.",
}

CAMPAIGN = {
"line":"Forty days is not a longer series. It is a different instrument.",
"intro":"A series changes what a congregation thinks about for six weeks. A campaign changes what a church does &mdash; because the preaching, the groups, the devotions, the households, the students and the children are all pointed at one thing for forty days, and then everyone comes back and says what happened.",
"parts":[
("The weekend","Six messages, one arc, with the kickoff built to enroll rather than to teach."),
("The daily","Forty days of devotional in every household, in print and on a phone."),
("The room","Six group sessions aligned to the messages, running the same week."),
("The house","A family table edition so a household is on one thing, at one table, all season."),
("The ages","Student and children's versions of the same big idea, so a family can actually talk about it."),
("The mechanics","Invitations, the commitment card, the spiritual partner, the tracker, the response loop."),
("The ending","A Celebration Sunday where people report what happened, and the next thing gets announced before anyone leaves."),
],
"why40":[
("Long enough to change something","Three weeks changes a habit. Six changes a household. Forty days is the length at which a church stops describing itself differently and starts behaving differently."),
("Short enough to finish","A congregation will commit to something with an end date. The same congregation will not commit to a program."),
("It has a scriptural spine","Forty days appears throughout Scripture as a season of formation rather than an arbitrary number, and pastors know that without being told."),
("It creates a shared story","The reason campaigns work is not the content. It is that four hundred people did the same hard thing in the same six weeks and can talk about it afterward."),
],
"library":"There are a hundred forty-day campaigns in the library across five tracks &mdash; formation, family and home, mission and community, generosity and stewardship, health and wholeness. Every one of them can be run as written, adapted to a church, or built from a pastor's own material.",
"custom":"Or bring your own. A campaign can be built out of a series you already preached, a book you wrote, a theme your elders chose, or a number your church has to hit. That is the version most churches want and almost none can produce.",
}

COMPARE = {
"note":"Verified against their published tiers and kit pages rather than from memory. Where they are stronger, it says so &mdash; a comparison nobody loses is a comparison nobody believes.",
"theirs":"SermonCentral",
"ours":"The Sermon Library",
"rows":[
["THE MESSAGE","",""],
["Sermon library, free to browse","300,000+, growing ~300/week","5,155 messages, 73 categories"],
["Sermon manuscripts and outlines","Yes","Yes"],
["AI sermon generation","Yes &mdash; full draft in 5-10 min","Yes &mdash; built from your profile"],
["Illustration library","Very large","Excavation prompts to surface your own"],
["Deeper exegetical study","Limited","Included with every message"],
["Cross-purpose Scripture","&mdash;","Four passages per message"],
["THE SERVICE","",""],
["PowerPoint and slides","3,500+ slides","Included per message"],
["Videos, bumpers, countdowns","Strong &mdash; professionally produced","Not yet. Their advantage."],
["Motion backgrounds and worship media","Unlimited on Plus","&mdash;"],
["Run sheet, minute by minute","&mdash;","Yes"],
["Worship set suggestions","&mdash;","Keyed to the big idea"],
["Lay introduction, offertory prayer, benediction","&mdash;","Written per message"],
["Experiential staging ideas","&mdash;","Per category and per message"],
["THE SERIES","",""],
["Series kits","30+, four weeks each, $49.99 standalone","100 campaigns plus 5,155 standalone messages"],
["Series length","Four weeks","One Sunday to forty days"],
["Social and invite graphics","Yes","Invite cards and three scripts; graphics in progress"],
["Week one free to preach","&mdash;","Every campaign"],
["THE WEEK","",""],
["Daily devotional","&mdash;","7, 10, 21, 30 or 40 days"],
["Video devotional scripts","&mdash;","Seven, shot in an hour on a phone"],
["Daily emails from the pastor","&mdash;","Drafted, one field for him"],
["Printable participant journal","&mdash;","Print-ready template"],
["THE ROOM","",""],
["Small group material","Study questions with a kit","Full six-session curriculum"],
["Curriculum from your own sermons","&mdash;","Yes &mdash; the Curriculum tab"],
["Small group leader training","&mdash;","Included"],
["Host guides and open-house kits","&mdash;","Included"],
["THE FAMILY","",""],
["Student version of the same message","&mdash;","Yes"],
["Children's version","&mdash;","Yes"],
["Parenting series","&mdash;","Yes"],
["Family table edition","&mdash;","Seven nights per message"],
["THE SEASON","",""],
["Forty-day churchwide campaign","&mdash;","100 in the library"],
["Kickoff Sunday design","&mdash;","Six musts, six-week arc"],
["Celebration Sunday","&mdash;","Designed, with testimony capture"],
["Commitment mechanic and live count","&mdash;","The I&rsquo;m In card"],
["Spiritual partner and 5F invite","&mdash;","Included"],
["Response loop back to the pulpit","&mdash;","Included"],
["PUBLISHING","",""],
["Print templates you can brand","&mdash;","Journals, guides, campaign books"],
["Production training","&mdash;","Six-module masterclass"],
["Print-on-demand path","&mdash;","Yes"],
["PRICE","",""],
["Free tier","Full sermon library","5,155 messages plus week one of any campaign"],
["Entry subscription","~$120 a year","Founders year: $1 per adult attender"],
["Top tier","Premium &mdash; all series kits","All-access, everything above"],
["Custom build for your church","&mdash;","$500 to $2,500"],
],
"fair":[
("Where they win","Volume, video production, twenty years of brand, and a contributor network adding three hundred sermons a week. On raw library size and media, do not compete &mdash; concede it out loud and move the conversation."),
("Where we win","Everything after the sermon ends. The week, the room, the household, the ages, the season. They sell a better Sunday morning. We sell the six weeks around it."),
("The honest gap to close","Video. They have professionally produced bumpers, mini-movies and countdowns; we have none. That is the one line on this chart a pastor might buy them for on its own."),
],
}

REVENUE = {
"model":"$1 per average adult attendance, for the founders year. A church of 100 pays $100. A church of 1,000 pays $1,000. Unlimited access for twelve months, at whatever state the product is in.",
"verdict":"It is a good founders offer and a dangerous permanent price. Good, because it is instantly understandable, self-tiering, needs no negotiation, and removes price entirely as an objection while you are still learning what churches actually use. Dangerous, because $100 anchors below the incumbent, and renewing at $190 is a ninety percent increase to a church that already told its board what this costs.",
"fixes":[
("Name it a founders year, with the renewal price printed","Say the future number on the same page as the founders number. A church that knew is a church that renews."),
("Cap the cohort","One hundred founding churches, or ninety days, whichever comes first. Scarcity turns a low price into an offer. Without a cap it is just cheap."),
("Floor at $100, cap at $2,500","A church of forty still pays $100 or you cannot afford to serve them. A church of ten thousand does not pay $10,000 for a product with eight finished examples."),
("Ask for something other than money","Founders give you a testimonial, completion data, and one hour on the phone at ninety days. That is worth more than the difference between $100 and $190."),
("Collect the year up front","Annual prepay is what funds the build. Monthly at these numbers is not worth the processing."),
],
"assume":[
("Blended revenue per church","About $310, on a size mix weighted toward his existing relationships"),
("Size mix","30% under 100 &middot; 30% at 100-250 &middot; 22% at 250-500 &middot; 18% at 500+"),
("Custom builds","A small share of subscribers, averaging $1,200 to $1,500"),
("Print","15-20% of churches order journals, averaging $450"),
("Everything collected up front","Annual prepay, so cash lands when they sign"),
],
"scenarios":[
["","Careful","Base","Strong"],
["Churches at 90 days","30","60","120"],
["Churches at 6 months","65","160","350"],
["Churches at 9 months","120","320","700"],
["Subscription cash, 9 months","$37,000","$99,000","$217,000"],
["Custom builds","$5,000","$18,000","$45,000"],
["Print and journals","$3,000","$22,000","$70,000"],
["Total cash, 9 months","$45,000","$139,000","$332,000"],
],
"read":"The base case is not a marketing number. It assumes about one church a day signing in the back half of the year from a warm network of five hundred relationships and twenty-five years of goodwill. If that feels slow, it is because founders sales are conversations rather than clicks.",
"risks":[
("The real constraint is not price, it is proof","Eight built messages against 5,155 titles. Every founder conversation will arrive at that ratio. Build the flagship kits before the outreach, not after."),
("The second constraint is delivery","Three hundred churches asking for custom devotionals is an operations problem, not a content problem. Decide now how many custom builds a month you can actually finish."),
("Renewal is the whole business","At these numbers year one barely pays for itself. The model only works if founders renew at a real price, which means year one has to visibly work for them."),
("Do not discount the second year","A church that joined at half price churns when it renews at full. Discount annual against monthly instead."),
],
"legal":"These are modeling scenarios built on stated assumptions, not forecasts, and none of the conversion rates have been tested. I am not a financial advisor &mdash; run the assumptions past someone who is before you build a budget on them.",
}
