# -*- coding: utf-8 -*-
# 8 categories, 5 tracks of 20 each = 100 per category, 800 total slots
# Delivered: 3 calendar locks (300) + 5 strategic weekends (100) = 400

def T(*p):
    return list(p)

LOCKS = [
("Mother's Day",
 "The third-highest attendance Sunday of the year, and the one most likely to wound the person sitting in row nine.",
 {"roll":"A family and parenting series, or a women's ministry launch running through early summer.",
  "give":"Pregnancy resource centers, foster and adoption fund, benevolence for single mothers.",
  "gospel":"Adult children bring parents who attend nowhere else. Preach the gospel plainly and briefly.",
  "act":"A spoken honor practice this week, plus one named commitment to care for someone for whom the day is hard."},
 [
 ("Honoring Mothers", T(
 ("She Kept Showing Up","The unglamorous faithfulness that formed you"),
 ("Her Name Is in Your Story","Tracing the influence you never fully credited"),
 ("The Woman Who Prayed for You","What happened in rooms you never saw"),
 ("Strength and Dignity","Proverbs 31 rescued from the pressure it became"),
 ("What She Gave Up","The costs mothers absorb and rarely name"),
 ("Call Her Blessed","Turning gratitude into words she can actually hear"),
 ("The First Voice You Trusted","How mothers shape what we believe about God"),
 ("Ordinary Days Built You","Formation happens in the routine, not the milestone"),
 ("Honor Your Mother","The commandment with a promise attached"),
 ("She Was Not Perfect and She Was Enough","Grace for real mothers"),
 ("The Hands That Held You","A meditation on presence"),
 ("Behind Every Steady Person","The quiet architecture of a childhood"),
 ("Thank You Is Not Too Late","Repairing what went unsaid"),
 ("The Sacrifice Nobody Applauded","Honoring the invisible work"),
 ("What My Mother Taught Me About God","A testimony-driven message"),
 ("She Believed You Before You Did","Faith held on someone else's behalf"),
 ("A Legacy You Can Measure","What actually transfers between generations"),
 ("Honoring Her Now","Practical honor for adult children"),
 ("The Mother Who Made Room","Hospitality as spiritual formation"),
 ("Well Done","What we would say if we said it plainly"))),
 ("The Hard Mother's Day", T(
 ("When Mother's Day Hurts","Naming it from the platform before the flowers come out"),
 ("Empty Arms","Infertility, miscarriage, and a God who has not forgotten"),
 ("The Mother You Lost","Grieving on the day the calendar celebrates"),
 ("When Your Mother Wounded You","Honor without pretending"),
 ("Hannah Wept in the Temple","Bitter prayer, and the God who received it"),
 ("The Estranged Table","When the relationship is broken and the day arrives anyway"),
 ("She Wanted to Be a Mother","Longing the church routinely steps over"),
 ("Single and Carrying It All","A word for mothers doing it alone"),
 ("The Loss Nobody Mentioned","Grief that was never given a funeral"),
 ("When You Had to Walk Away","Boundaries, honor, and the fifth commandment"),
 ("Foster, Adoptive, and Chosen","Motherhood that came a different way"),
 ("The Prodigal's Mother","Waiting on a child who has not come home"),
 ("Rachel Weeping","Grief that refuses easy comfort, and the God who allows it"),
 ("The Day You Dread","Permission not to be fine"),
 ("God Sets the Lonely in Families","Belonging for those without one"),
 ("Naomi Called Herself Bitter","Honest lament from a woman who lost everything"),
 ("Not the Mother You Wanted to Be","Grace for the ones who feel they failed"),
 ("Motherhood Interrupted","Illness, distance, incarceration, and love that persists"),
 ("He Sees You","For the woman sitting through this service in pain"),
 ("Mourning and Honoring at the Same Time","Holding both without having to choose"))),
 ("Mothers of Scripture", T(
 ("Hannah's Bargain","Prayer that gave away the answer"),
 ("Jochebed Let Him Go","The mother who put her son in the river"),
 ("Mary Said Yes","Courage in a teenage girl"),
 ("The Mother of All Living","The name Adam gave her after everything went wrong"),
 ("Naomi and Ruth","Family that was chosen rather than born"),
 ("Elizabeth Believed for Her","Friendship in the season of waiting"),
 ("Sarah Laughed","Doubt, delay, and a promise that outlasted both"),
 ("Rebekah's Interference","When a mother's plan gets ahead of God's"),
 ("The Widow of Zarephath","Feeding a prophet with the last of everything"),
 ("Lois and Eunice","The faith that ran through three generations"),
 ("Bathsheba's Second Chapter","From scandal to the mother of a king"),
 ("The Shunammite Woman","Faith that would not accept the ending"),
 ("Rizpah Kept Watch","The fiercest mother in the Old Testament"),
 ("Miriam at the Riverbank","A sister's courage inside her mother's plan"),
 ("Mary at the Cross","The sword Simeon promised her"),
 ("Hagar Was Seen","The God who found a mother in the desert"),
 ("The Mother Who Argued With Jesus","Persistence he called great faith"),
 ("Zipporah's Hard Obedience","An overlooked mother in Exodus"),
 ("She Asked Too Much","Ambition for our children, corrected by Jesus"),
 ("The Mothers Who Brought Their Children","And the disciples who tried to stop them"))),
 ("Motherhood as Calling", T(
 ("This Is Ministry","Motherhood as vocation, not a break from it"),
 ("The Long Obedience of Raising Children","Formation measured in decades"),
 ("When You Sit and When You Walk","Deuteronomy 6 inside a modern house"),
 ("You Are Not Behind","Comparison, feeds, and the mother's inner monologue"),
 ("Rest Is Not a Reward","Sabbath for people who cannot clock out"),
 ("The Days Are Long","Endurance theology for the young-children years"),
 ("What You Model Outlasts What You Say","The curriculum of ordinary life"),
 ("Discipline Is Love With a Long View","Correction as care"),
 ("Letting Them Fail","The courage to allow a consequence"),
 ("Praying for Children You Cannot Control","Surrender as parenting strategy"),
 ("Your Marriage Is Their Foundation","What children absorb before they understand it"),
 ("Mothering Teenagers","When the job description changes overnight"),
 ("The Empty Nest Is Not the End of the Calling","What comes after they go"),
 ("Guilt Is Not the Holy Spirit","Distinguishing conviction from condemnation"),
 ("Building a Home, Not Just Running One","Culture over logistics"),
 ("When You Have Nothing Left to Give","Depletion, and the God who refills"),
 ("Raising Kids Who Own Their Faith","Ownership rather than inheritance"),
 ("The Family Table","Why shared meals form what sermons cannot"),
 ("What You Want Them to Remember","Working backward from the eulogy"),
 ("Faithful, Not Perfect","Releasing a standard nobody can meet"))),
 ("Spiritual Mothers", T(
 ("Not Every Mother Gave Birth","Honoring the women who raised us anyway"),
 ("The Church Has Always Had Mothers","Spiritual maternity in the New Testament"),
 ("Older Women, Younger Women","Titus 2 and the transfer that keeps a church alive"),
 ("Who Mothered You in the Faith","Naming the women who shaped what you believe"),
 ("Aunties, Teachers, and Neighbors","The wider circle that raises a child"),
 ("Be That Woman for Someone","An invitation into spiritual mothering"),
 ("Deborah Led","Motherhood language applied to leadership"),
 ("Lydia Opened Her Home","Hospitality as ministry"),
 ("Priscilla Taught","A woman who discipled a preacher"),
 ("The Women Who Funded Jesus","Luke's overlooked list"),
 ("Mothering Without Children","A calling that does not require biology"),
 ("Grandmothers Hold the Long Thread","Generational faith and the ones who carry it"),
 ("Adopt Someone This Year","A concrete call into spiritual family"),
 ("The Village Is Not Optional","Why isolated parenting fails"),
 ("Mary and Elizabeth in the Same Room","Mutual encouragement in hard seasons"),
 ("She Discipled Me","A testimony message"),
 ("Room in the Family of God","Belonging for anyone without a mother to call"),
 ("Foster Care Is the Church's Work","A direct ministry challenge"),
 ("The Widow Who Gave Everything","Mark 12 and generosity from empty hands"),
 ("Mothers in Israel","The biblical honor given to women who built a people"))),
 ]),

("Father's Day",
 "The lowest-attendance major holiday and the highest-stakes one, because the men in the room are the ones least likely to return.",
 {"roll":"A men's ministry launch, or a marriage and legacy series running into fall.",
  "give":"Men's discipleship, fatherhood initiatives, mentoring and reentry ministries.",
  "gospel":"Men attend today who attend nowhere else. Low shame, high dignity, clear invitation.",
  "act":"Men's group registration in the lobby, and a blessing spoken over their children this week."},
 [
 ("Honoring Fathers", T(
 ("What He Never Said","Reading love in a man who did not use words"),
 ("The Man Who Showed Up","Presence as the underrated inheritance"),
 ("Steady","The quiet virtue that raised you"),
 ("He Worked So You Could","Sacrifices measured in early mornings"),
 ("Honor Your Father","The commandment applied to real, complicated men"),
 ("What My Father Taught Me About God","A testimony-driven message"),
 ("He Was Not Perfect and He Tried","Grace for real fathers"),
 ("The Weight He Carried","Provision, pressure, and what men do not say"),
 ("Say It While He Can Hear It","Gratitude that does not wait for a eulogy"),
 ("The Blessing You Are Still Waiting For","Approval, and where to finally get it"),
 ("Hands That Fixed Things","A meditation on practical love"),
 ("He Taught You to Work","Vocation as inheritance"),
 ("The Father Who Came Back","Honoring the man who repaired it"),
 ("Not Every Lesson Was a Lecture","What men teach by doing"),
 ("Your Father's Faith","Whether you kept it, left it, or are still deciding"),
 ("He Chose You","Adoptive, step, and foster fathers"),
 ("The Long Shadow","Influence you are still living inside"),
 ("What He Gave Up","Ambition traded for a family"),
 ("Well Done, Dad","What we would say if we said it plainly"),
 ("The Man in the Photograph","Remembering a father who is gone"))),
 ("The Absent or Failing Father", T(
 ("When Father's Day Hurts","Naming it before the ties and the jokes"),
 ("The Father Who Left","Abandonment, and the God who does not"),
 ("Forgiving a Man Who Never Apologized","Forgiveness without reconciliation"),
 ("Your Father Is Not Your Ceiling","Breaking a generational pattern"),
 ("The Father Ran","Luke 15 and the son who assumed he could not come back"),
 ("When Your Dad Was the Wound","Honoring without pretending"),
 ("Fatherlessness Is a Spiritual Condition","What the church owes a generation"),
 ("I Do Not Want to Be Like Him","Fear, inheritance, and the freedom to differ"),
 ("The Empty Chair on Father's Day","Grieving the man you lost"),
 ("He Was There and Not There","Presence without connection"),
 ("A Father to the Fatherless","Psalm 68 and a promise with teeth"),
 ("Breaking the Cycle Takes a Decision","Practical steps for men who want different"),
 ("When You Are the Father Who Failed","Repentance, repair, and the road back"),
 ("Eli's Sons","A good man who would not confront his children"),
 ("David and Absalom","Love, failure, and a father who grieved too late"),
 ("Your Story Does Not End With His","Identity beyond inheritance"),
 ("The Father Wound Is Real","Naming it without becoming it"),
 ("Adopted","What God did about your fatherlessness"),
 ("When He Never Believed in You","Finding your worth somewhere sturdier"),
 ("Grace for Men Who Are Trying","A word to fathers who feel behind"))),
 ("Fathers of Scripture", T(
 ("Abraham on the Mountain","The hardest obedience in Scripture"),
 ("Jacob's Twelve","A flawed father and a family that survived him"),
 ("Joseph Stayed","The quiet integrity of a man who could have walked away"),
 ("Noah Built Because He Believed","Faith that took a hundred years"),
 ("Jairus Fell at His Feet","A father's desperate faith for his daughter"),
 ("Help My Unbelief","The father who brought his son and his doubt together"),
 ("Eli's Silence","When love refuses to correct"),
 ("David's Grief for Absalom","The cost of a father's absence"),
 ("Zechariah Lost His Voice","Doubt, silence, and a song restored"),
 ("Job Prayed for His Children","Intercession as a father's daily work"),
 ("The Prodigal's Father","The most surprising man Jesus ever described"),
 ("Manoah Asked How","A father who wanted instructions"),
 ("Jesse Forgot His Youngest","A father who overlooked the one God chose"),
 ("Boaz Redeemed a Family","Fatherhood as covering"),
 ("Letters to His Son","Proverbs read as a father's voice"),
 ("Jethro's Advice","The wisdom of an older man, and a leader who took it"),
 ("Amram and Jochebed","Parents who defied a king"),
 ("Timothy's Missing Father","And the men who stepped in"),
 ("He Taught Him a Trade","The ordinary work of raising the Son of God"),
 ("Our Father","The name Jesus taught us to use"))),
 ("Fatherhood as Calling", T(
 ("The Job Nobody Trained You For","Fatherhood as vocation"),
 ("Your Presence Is the Program","Why showing up outperforms everything else"),
 ("Blessing Your Children Out Loud","Words they will carry for fifty years"),
 ("Provider Is Not the Whole Job Description","Redefining what a father owes"),
 ("Teach Them to Work","Vocation, character, and the dignity of labor"),
 ("Lead Your Home Without Ruling It","Authority as service"),
 ("Apologize to Your Kids","The most powerful thing a father can model"),
 ("Pray With Them, Not Just for Them","Spiritual leadership that is actually simple"),
 ("What You Tolerate, They Inherit","Fathers and the culture of a home"),
 ("Discipline Without Anger","Correction that does not wound"),
 ("Fathering Teenagers","When the relationship has to change shape"),
 ("Be the Man in the Room","Character under pressure"),
 ("Your Marriage Is Your First Ministry","What children learn watching you love their mother"),
 ("Working Late Has a Price","Honest math on ambition and family"),
 ("Raising Sons","Manhood taught rather than assumed"),
 ("Raising Daughters","What a father's voice does to a woman's sense of worth"),
 ("Let Them See You Fail Well","Modeling repentance and resilience"),
 ("The Legacy You Are Actually Building","Values transfer over asset transfer"),
 ("Finish Strong","Fathering adult children and grandchildren"),
 ("What Will They Say at Your Funeral","Working backward from the end"))),
 ("God as Father", T(
 ("Our Father in Heaven","The most radical two words Jesus taught us"),
 ("Abba","The intimacy of the name Jesus used in Gethsemane"),
 ("He Did Not Stand on Ceremony","Luke 15 and a father who ran"),
 ("Adopted, Not Tolerated","Sonship as legal standing, not sentiment"),
 ("He Is Not Your Father Amplified","Correcting the picture you inherited"),
 ("The Father Who Disciplines Is the Father Who Stays","Hebrews 12 on love that corrects"),
 ("How Much More","Jesus' argument from imperfect fathers to a perfect one"),
 ("This Is My Son, Whom I Love","Approval spoken before the ministry began"),
 ("He Knows What You Need Before You Ask","Providence and the Father's attention"),
 ("The Older Brother","Sons who stayed and never felt it"),
 ("Good Gifts","What the Father actually gives, and what he does not"),
 ("He Numbered Your Hairs","Attention that borders on absurd"),
 ("When the Father Feels Absent","Silence, and what to do inside it"),
 ("Consequence Is Not Rejection","Distinguishing discipline from abandonment"),
 ("You Did Not Choose Him First","Adoption and unearned belonging"),
 ("A Father to the Fatherless","God's self-chosen title"),
 ("I Will Not Leave You as Orphans","The promise Jesus made before he left"),
 ("Starting From Zero","For anyone who has no working picture of a father"),
 ("Nothing Can Separate You","Romans 8 and the permanence of sonship"),
 ("Call Him Father Today","An invitation, not a lecture"))),
 ]),

("Graduation",
 "Extended family in the room, a launching student, and a set of parents quietly grieving. Three audiences, one service.",
 {"roll":"A summer young-adult track, then a fall college and career connection push.",
  "give":"Scholarship fund, student ministry, campus ministry partnerships.",
  "gospel":"Grandparents and extended family attend who never otherwise would.",
  "act":"Commission each graduate by name, connect every one to a church in their new city before they leave, and bless the parents."},
 [
 ("Commissioning the Graduate", T(
 ("Go","The one-word commission"),
 ("Do Not Let Anyone Look Down on You","Paul to a young leader"),
 ("Sent, Not Just Released","Commissioning language for a graduation Sunday"),
 ("The Church Is Behind You","A congregation's promise to its graduates"),
 ("Take Something With You","What we hope you carry out the door"),
 ("Be Strong and Courageous","Joshua's charge to a new generation"),
 ("The Blessing We Send You With","A spoken benediction message"),
 ("You Were Formed Here","Naming what this church built into them"),
 ("Now It Is Yours","The handoff from inherited faith to owned faith"),
 ("Remember Where You Came From","Roots without limits"),
 ("Come Back and Tell Us","Keeping the relationship after the launch"),
 ("We Are Not Finished With You","Belonging beyond the milestone"),
 ("Carry the Name Well","Representation and character"),
 ("Your First Year Will Test It","Honest preparation for what is coming"),
 ("Commissioned, Not Graduated","Language that reframes the whole day"),
 ("The Torch Is Not Heavy","Encouragement for a nervous generation"),
 ("Go and Make Disciples","The Great Commission preached at a launch"),
 ("You Have Everything You Need","Confidence grounded in Christ, not credentials"),
 ("This Class, By Name","A message written for them specifically"),
 ("Send Them Out With Something","A charge to the congregation, not the graduates"))),
 ("Calling and Vocation", T(
 ("What Are You For?","Purpose beyond a major"),
 ("Your Job Is Not Your Calling","Distinguishing the two before you confuse them for life"),
 ("Whatever You Do, Work at It","Colossians 3 and the dignity of every field"),
 ("God Does Not Waste a Degree","Vocation as ministry"),
 ("The Career You Have Not Considered","Calling into overlooked places"),
 ("Success Is Not the Same as Significance","The question that reorders a life"),
 ("Making a Living, Building a Life","Two different projects"),
 ("Do Not Pick a Path to Impress Anyone","Freedom from the audience in your head"),
 ("Called to the Marketplace","Ministry outside the church building"),
 ("The First Job Is Rarely the Right One","Patience with the early years"),
 ("What Breaks Your Heart?","Finding calling in what you cannot ignore"),
 ("Money Will Ask You Questions","Financial wisdom at the starting line"),
 ("Excellence Is Worship","Craft as devotion"),
 ("The Long Game","Careers built in decades, not semesters"),
 ("When the Plan Falls Apart","Providence and detours"),
 ("Do the Next Right Thing","Guidance when the whole map is not given"),
 ("Your Twenties Are Not a Waiting Room","Living now rather than later"),
 ("Contentment Without Passivity","Bloom where you are planted, then move"),
 ("Called Together","Vocation discerned in community"),
 ("Whose Voice Are You Following?","Discernment among competing counsel"))),
 ("Wisdom for the Next Chapter", T(
 ("The Choices That Will Define You","Decisions made in the first two years"),
 ("Who You Marry Matters More Than Where You Work","The highest-leverage decision"),
 ("Choose Your Friends Carefully","Proverbs on the company you keep"),
 ("Debt Is a Decision","Financial wisdom before the first credit card"),
 ("The Habits You Build Now","Compound interest applied to character"),
 ("Guard Your Heart","What Proverbs 4 actually means"),
 ("Nobody Is Watching. That Is the Test.","Integrity in private"),
 ("Learn to Be Alone","Solitude as a survival skill"),
 ("Ask for Help Early","Pride, isolation, and the cost of both"),
 ("Wisdom Is Not the Same as Intelligence","The difference nobody teaches"),
 ("Say No to Good Things","Focus as a spiritual discipline"),
 ("You Will Be Tempted to Coast","Diligence in the unsupervised years"),
 ("Find Older People","Mentorship as a deliberate strategy"),
 ("Your Phone Is Forming You","Attention, formation, and the algorithm"),
 ("Handle Failure Before It Handles You","Resilience taught in advance"),
 ("Trust the Lord With All Your Heart","Proverbs 3 for a generation that wants control"),
 ("Be Teachable","The one trait that predicts everything else"),
 ("The Body You Are Given","Stewardship of health in the years you feel invincible"),
 ("Rest Is a Command","Sabbath for people entering a hustle culture"),
 ("Begin With the End in Mind","Numbering your days early"))),
 ("Faith That Survives the Launch", T(
 ("Will Your Faith Survive Next Year?","The honest question nobody asks out loud"),
 ("Your Parents' Faith Will Not Carry You","The handoff to ownership"),
 ("Doubt Is Not the Opposite of Faith","Making room for hard questions"),
 ("What They Will Say About Christianity","Preparing for the objections in advance"),
 ("Find a Church in the First Two Weeks","The single best predictor of a faith that lasts"),
 ("You Will Be the Only One","Standing alone with conviction"),
 ("Ask the Hard Questions Here First","An invitation to bring doubt to the church"),
 ("Deconstruction and What Comes After","A pastoral, non-defensive treatment"),
 ("Daniel Was a College Student","Faith inside a foreign system"),
 ("The Lions Are Real","Pressure, compromise, and courage"),
 ("When Nobody Is Making You Go","Self-directed spiritual discipline"),
 ("What You Believe When It Costs You","Conviction under social pressure"),
 ("Community Is Not Optional","Isolation as the primary spiritual danger"),
 ("Read It for Yourself","Building a first-hand relationship with Scripture"),
 ("What Nobody Explained to You","Honest, non-shaming teaching on sex and dating"),
 ("Grace for the Year You Wander","For the ones who will drift and come back"),
 ("Keep the Door Open","A message to parents about what to do next"),
 ("Your Questions Are Welcome","Repeated, because they will not believe it the first time"),
 ("Shipwrecked Faith","Paul's warning, and how it actually happens"),
 ("Come Home Whenever","The church's standing invitation"))),
 ("Blessing the Family Letting Go", T(
 ("The Hardest Part Is the Letting Go","A message for the parents, not the graduates"),
 ("You Did Enough","Grace for parents second-guessing eighteen years"),
 ("She Took Him to the Temple","Hannah, and the mother who gave her son back"),
 ("From Manager to Consultant","The role change parents have to make"),
 ("The Empty Room","Grief that nobody calls grief"),
 ("Your Job Changes, It Does Not End","Parenting adult children"),
 ("Pray More, Say Less","The new primary tool"),
 ("When They Do Not Choose What You Hoped","Releasing outcomes"),
 ("Let Them Own It","Faith cannot be inherited by force"),
 ("The Marriage After the Kids Leave","Rebuilding what the years crowded out"),
 ("What You Modeled Is Now Their Baseline","The long echo of a household"),
 ("Bless Them Out Loud","A specific practice before they go"),
 ("Send Them, Do Not Just Miss Them","Purpose over sentiment"),
 ("The Fear You Are Not Naming","Honest pastoral care for anxious parents"),
 ("Trust the God Who Goes With Them","Providence beyond your reach"),
 ("Younger Siblings Are Watching","The family recalibration"),
 ("Grandparents and the Long Thread","The generation with the longest view"),
 ("Your Next Chapter Starts Too","Purpose for parents in a new season"),
 ("Keep the Table Set","Making home a place they want to return to"),
 ("Release With Blessing, Not Anxiety","The tone that determines the relationship"))),
 ]),
]

STRATEGIC = [
("End-of-Year Giving",
 "The last four Sundays of the calendar, when the largest gifts of the year are decided and most churches say nothing.",
 {"roll":"A January generosity campaign or a new-year vision series, with the year-end gift as the on-ramp.",
  "give":"The year-end gift itself, plus a first-fruits commitment for the coming year.",
  "gospel":"God gave first. Generosity preached as response, never as fundraising.",
  "act":"A one-time year-end decision and a chosen giving rhythm for January."},
 T(
 ("Finish the Year Well","What December giving says about the whole year"),
 ("Before the Calendar Turns","A window that closes on the thirty-first"),
 ("God Gave First","Generosity as response, never as leverage"),
 ("What Will You Send Ahead?","Treasure in heaven, understood practically"),
 ("The Last Decision of the Year","Choosing instead of drifting"),
 ("Everything You Have Was Given to You","Stewardship as the starting premise"),
 ("A Year of Provision","Gratitude as an honest ledger"),
 ("Where Did It Go?","A candid look at twelve months of spending"),
 ("Two Small Coins","Proportion over amount"),
 ("You Cannot Outgive God","The surprising math of generosity"),
 ("Giving Is a Discipleship Issue","Not a budget issue"),
 ("Start the New Year Free","Debt, margin, and the decision to change"),
 ("Sow Generously","Paul's harvest logic in 2 Corinthians 9"),
 ("What Your Money Does While You Sleep","Investment, impact, and eternity"),
 ("The Gift That Changes Something Specific","Naming the actual outcome"),
 ("Enough","Contentment as the foundation of generosity"),
 ("Giving Past Your Lifetime","A word to families thinking generationally"),
 ("Cheerfully, or Not at All","Why motive matters more than amount"),
 ("First, Not Last","Where giving belongs in the order of a budget"),
 ("One More Family, One More Story","The human result of a year-end decision"))),

("Baptism Sunday",
 "The clearest evangelistic Sunday available to a church, and the one most often buried at the end of a service.",
 {"roll":"A new believers and next-steps track, or a spring growth series on the Christian life.",
  "give":"Baptism kits and towels, church planting, missions.",
  "gospel":"Testimony carries the message. The gospel is preached by the people in the water.",
  "act":"Same-day signup and same-day baptism. Remove every step between decision and obedience."},
 T(
 ("Buried and Raised","What actually happens in that water"),
 ("Go Public","Faith that stops being private"),
 ("The First Step of Obedience","Why baptism comes early rather than late"),
 ("What Are You Waiting For?","Removing the reasons people delay"),
 ("He Was Baptized Too","Jesus in the Jordan, and what it means for you"),
 ("Water Does Not Save You. It Says Something.","Clarifying the theology plainly"),
 ("Testimony Sunday","Building the message around the stories"),
 ("Dead to That, Alive to This","Romans 6 preached without jargon"),
 ("Today, If You Are Ready","A direct, low-friction invitation"),
 ("What Is Stopping Me?","Acts 8 and immediate obedience"),
 ("Into a Family, Not Just a Faith","Belonging as part of the act"),
 ("Your Story Is Someone Else's Door","Testimony as evangelism"),
 ("The Water Is Warm","Removing the fear and the formality"),
 ("Nobody Is Too Far","For the person who thinks their past disqualifies them"),
 ("Whole Households","Family baptism and generational faith"),
 ("What Changed?","The before and after that makes a testimony land"),
 ("Confess With Your Mouth","The public nature of Christian faith"),
 ("Baptism Is Not Graduation","What comes the day after"),
 ("The Church Witnesses It","Why the congregation's role matters"),
 ("Come Out of the Water Different","The commissioning built into the moment"))),

("Baby Dedication and Family Blessing",
 "Extended family attends who never otherwise walk in, and the congregation makes a promise most of them do not notice they are making.",
 {"roll":"A parenting and family-discipleship series, plus children's ministry volunteer recruitment.",
  "give":"Children's ministry, nursery buildout, foster and adoption fund.",
  "gospel":"Grandparents, in-laws, and neighbors in the room. Preach to them, not past them.",
  "act":"Parents commit to one home discipleship rhythm; the church commits out loud; grandparents are blessed."},
 T(
 ("We Are Making a Promise Too","The congregation's half of the dedication"),
 ("Train Them Up","Proverbs 22 without the guarantee people read into it"),
 ("She Gave Him Back","Dedication as release, not ceremony"),
 ("The Faith of a Household","Deuteronomy 6 inside a modern home"),
 ("You Are Their First Picture of God","The weight and the grace of it"),
 ("It Takes a Church","Why we do this in public"),
 ("Grandparents Hold the Long Thread","Honoring the generation before"),
 ("What Will They Inherit?","Values before assets"),
 ("Let the Little Children Come","Jesus, and the disciples who blocked them"),
 ("Dedicated, Not Insured","Honest theology about what today does and does not do"),
 ("The Home Is the First Church","Where discipleship primarily happens"),
 ("Every Child Needs More Than Two Adults","The case for church family"),
 ("A Blessing Spoken Over Them","The practice of blessing, taught and modeled"),
 ("You Will Not Do This Perfectly","Grace for new parents"),
 ("Formed by a Community","Samuel, and a child raised inside the temple"),
 ("However Your Family Was Formed","Honoring adoptive and foster families"),
 ("Three Generations Deep","Timothy's grandmother and the chain that held"),
 ("Start the Rhythms Now","Practical home discipleship for parents of infants"),
 ("For the World, Not From It","Formation over insulation"),
 ("Your Home Has a Culture","Building it on purpose rather than by accident"))),

("Series Launch and Friends Sunday",
 "The single highest-leverage Sunday in a church's year, because everything downstream depends on who is in the room.",
 {"roll":"This is the launch. It rolls directly into the 40-day, 30-day, or six-week arc that follows.",
  "give":"Campaign underwriting, invite cards, and outreach production costs.",
  "gospel":"The highest invite density of the year. Preach for the guest who has not arrived yet.",
  "act":"Take a card, write one name on it, bring that person next week. Register for the series today."},
 T(
 ("Who Are You Bringing?","The invitation is the assignment"),
 ("One Name","Ask God for one person, then write it down"),
 ("Come and See","The oldest evangelism strategy in the Bible"),
 ("Andrew Brought His Brother","The disciple who is only ever bringing someone"),
 ("Your Table Is a Mission Field","Hospitality as evangelism"),
 ("Everybody Knows Somebody","Removing the excuse before it forms"),
 ("They Dug Through the Roof","Faith that carries someone else to Jesus"),
 ("Built for the Person You Are Thinking Of","Framing the launch around the absent guest"),
 ("Do Not Invite Them to Church","Invite them to this, specifically"),
 ("Six Weeks That Could Change Your Year","Casting the vision for the whole arc"),
 ("You Do Not Have to Explain Everything","Lowering the bar for the inviter"),
 ("She Told the Whole Town","Testimony without training"),
 ("Empty Seats Are the Point","Reframing what a full room is for"),
 ("Bring Them Before You Convince Them","Belonging before believing"),
 ("What If They Say No?","Handling the fear that stops the ask"),
 ("Make Room","A congregation's posture toward newcomers"),
 ("Start Here","A message built for a first-time guest"),
 ("The Best Six Weeks of the Year","Momentum framing for the launch"),
 ("Everyone Gets a Card","The physical mechanic of the invite"),
 ("Next Week Matters More Than Today","Sending them out with a job"))),

("Group Life Launch and the Call to Serve",
 "The retention Sunday. Everyone who came at Easter and Christmas either connects here or quietly disappears by March.",
 {"roll":"The small-group semester launch and serving-team onboarding, running the length of the campaign.",
  "give":"Leader training, curriculum subsidy, host-home support.",
  "gospel":"Connection is how a first-time guest becomes a disciple. Name that plainly.",
  "act":"Register for a group in the lobby today and sign up for one serving team before you leave."},
 T(
 ("You Were Not Built to Do This Alone","The case for group life"),
 ("Rows and Circles Do Different Work","Why attendance is not connection"),
 ("Six Weeks, Six People, One Room","Lowering the commitment barrier"),
 ("They Devoted Themselves","Acts 2 as the original small group"),
 ("Nobody Grows in a Crowd","Formation requires proximity"),
 ("Say Yes for Six Weeks","A finite, specific ask"),
 ("Open Your Living Room","The call to host, not to teach"),
 ("You Are More Ready Than You Think","Recruiting leaders who feel unqualified"),
 ("Every Member Has a Gift","1 Corinthians 12 and the end of spectator faith"),
 ("Find Your Place","Serving as belonging, not obligation"),
 ("The Body Has No Spare Parts","Why your absence is felt"),
 ("He Could Not Do It Alone","Jethro's advice and the necessity of sharing the load"),
 ("Serve Once and See","Removing the fear of a permanent commitment"),
 ("Who Is Missing?","The ministries waiting on someone who has not stepped up"),
 ("The Church Runs on Volunteers","Honest, honoring, and direct"),
 ("Use What You Already Have","Skills from Monday applied on Sunday"),
 ("Burnout Is Not the Goal","Sustainable serving and healthy boundaries"),
 ("Two Are Better Than One","Ecclesiastes on the strength of company"),
 ("Register Today, Start This Week","Urgency with a clear mechanic"),
 ("The Ministry That Needs You","Casting vision at the fair"))),
]
