# -*- coding: utf-8 -*-

THESIS = ("Every campaign in the library can produce one standalone sermon that stands completely on its own. "
 "Not the first week of six &mdash; the whole argument compressed into forty minutes, ending complete, "
 "preachable on any given Sunday by a pastor who will never run the campaign at all.")

DISTINCTION = {
 "line":"Week one and the overview sermon are not the same message, and shipping only week one is why sampling fails.",
 "rows":[
  ["Week One","The first movement of an argument","Assumes five more messages. Ends deliberately incomplete &mdash; it opens a loop the series closes. Preached alone, it feels like a trailer that never became a film.",
   "For a pastor who has already committed to the campaign."],
  ["The Overview Sermon","The whole argument compressed","Carries the entire idea to a landing. Ends complete. Nothing is owed. A congregation could hear it once, never hear another word, and have received something whole.",
   "For a pastor deciding whether to commit &mdash; and for the fifty Sundays a year that are not a campaign."],
 ],
 "why":("Most campaign kits ship week one as the sample, so the pastor previewing it experiences an unfinished thought "
  "and concludes the material is thin. He is not wrong about what he read. He read the wrong thing."),
}

PLACEMENTS = [
 ["The week before","Trailer","Preach the overview, then announce that the six weeks start next Sunday. The room is warmest in the four minutes after a message lands, and this is the placement that fills groups.",
  "Best for enrollment. Highest sign-up rate of the three."],
 ["Week one","Session One","The overview is week one, and weeks two through six go deeper into what it introduced. Nothing is repeated because the overview was altitude and the rest is ground level.",
  "Best for continuity. Nothing is wasted and the arc feels designed."],
 ["Standalone, forever","Any Given Sunday","Preached once, never continued, and complete. This is the version that has to work with no campaign behind it at all &mdash; and it is the version that makes the whole library free to sample.",
  "Best for the fifty Sundays a year that are not a campaign."],
]

WHAT_YOU_GET = [
 ["The sermon","Title, subtitle, big idea, text, opening, three or four movements with landing lines written out, illustration slots, and a close."],
 ["Seven daily devotionals","The same message broken into seven days. Not seven new ideas &mdash; the one idea, walked through a week."],
 ["A small group guide","One session for the week, aligned to the message so the leader's prep is reading it once."],
 ["The next-step ladder","The same content at three weeks, four weeks, six weeks, twenty-one days, thirty days or forty days."],
 ["The service kit","Order of service, worship suggestions, slides, response mechanic and the announcement copy."],
]

DEVO_PATTERN = [
 ["Day 1","See it","The passage itself, read slowly. What does it actually say, before what it means to me."],
 ["Day 2","Sit with it","The one idea, restated. Where does this land in my life right now?"],
 ["Day 3","Own it","The honest part. What is true about me here that I would rather not name?"],
 ["Day 4","Do it","One concrete action, today, small enough to actually happen."],
 ["Day 5","Share it","Somebody else hears about it from you. The idea leaves your head."],
 ["Day 6","Deepen it","A second passage and a harder question. This is the day the shallow version breaks."],
 ["Day 7","Bring it back","What happened this week? Come to Sunday with something to say."],
]

DEVO_RULE = ("Seven days is not seven ideas. It is one idea moved through a person &mdash; seen, felt, owned, done, "
 "shared, deepened, reported. A devotional that introduces a new concept each day teaches a congregation that "
 "nothing has to be finished.")

def C(t, sub, sermon, days, group, ladder):
    return {"t": t, "sub": sub, "s": sermon, "d": days, "g": group, "l": ladder}

def SER(t, sub, idea, text, hook, moves, close, ask):
    return {"t": t, "sub": sub, "idea": idea, "text": text, "hook": hook, "moves": moves, "close": close, "ask": ask}

CAMPAIGNS = [

C("God Owns It All","What changes when nothing is yours",
 SER("God Owns It All","What changes when nothing is yours",
  "If God owns everything, then every financial decision is a management decision rather than an ownership decision.",
  "Psalm 24:1; Deuteronomy 8:17-18; Luke 12:16-21",
  "Ask the room to picture the last significant purchase they made, and hold it. Then ask one question: whose was it?",
  [["Ownership is the question underneath every other question","Before budgeting, before debt, before giving &mdash; the argument is about who holds the title."],
   ["We say He owns it and we live like we do","The gap is not in our theology. It is in the calendar and the statement."],
   ["The rich fool used one word too often","Read Luke 12 and count the pronouns. That is the whole diagnosis."],
   ["Manager is a better job than owner","An owner carries the risk. A manager carries an assignment, and that is lighter."]],
  "You are not being asked to give something away. You are being asked to stop pretending it was ever yours.",
  "One number, written down this week, that you have been avoiding looking at."),
 [["Whose Is It","Psalm 24:1","The earth is the Lord's and everything in it. Start with the deed, not the budget.","What do you most think of as yours?","Write down the three things you would find hardest to release."],
  ["The Danger of Having Enough","Deuteronomy 8:11-18","Prosperity's risk is forgetting who gave it.","When did you last thank God for something you earned?","Say thank you out loud for one thing you worked for."],
  ["Count the Pronouns","Luke 12:16-21","The rich fool says I or my eleven times in four verses.","Where does that language show up in yours?","Reread your last month of spending as a sentence about what you believe."],
  ["The First Check","Proverbs 3:9-10","Order of operations reveals priority more honestly than amount.","What gets paid first in your household?","Change one line in the order this month."],
  ["Tell Someone","2 Corinthians 9:11-13","Generosity is contagious only when it is visible enough to catch.","Who taught you about money, well or badly?","Tell one person what you are learning this week."],
  ["Enough","1 Timothy 6:6-10","Contentment is the foundation everything else is built on.","What number would be enough? Have you ever named it?","Write the number. Then ask why that one."],
  ["What Changed","Matthew 6:19-21","The heart follows the treasure, not the other way around.","What moved this week?","Come Sunday ready to say one sentence about it."]],
 {"open":"What is the first thing you remember learning about money, and who taught you?",
  "qs":["If God owns everything, what changes on Monday?","Where is the gap widest between what we say and what we do?",
        "What did you notice counting the pronouns in Luke 12?","What would be different if you managed rather than owned?"],
  "apply":"Each person names one financial decision they will make differently this month.",
  "pray":"Pray for the person on your left by name, about the specific thing they named."},
 {"3":["Whose Is It","Enough","Open Hands"],
  "4":["Whose Is It","Enough","Open Hands","What Changed"],
  "6":["Whose Is It","What He Entrusted to You","Spend Less Than You Earn","Avoid Debt","Build Margin","Set Long-Term Goals"],
  "21":"Twenty-one days on ownership, contentment and the first check.",
  "30":"Thirty days of honest money &mdash; the numbers, the heart and the household.",
  "40":"40 Days of Financial Wisdom, the full churchwide campaign."}),

C("Doing Life Together","You were not built to do this alone",
 SER("You Were Not Built to Do This Alone","The life God designed does not work in isolation",
  "Isolation is not a personality preference. It is a condition Scripture treats as dangerous.",
  "Ecclesiastes 4:9-12; Acts 2:42-47; Hebrews 10:24-25",
  "Ask how many people in the room could name three people who would notice if they disappeared for two weeks. Do not ask for hands.",
  [["It was not good for the man to be alone before sin entered the world","Aloneness is the first thing God called not good, and nothing had gone wrong yet."],
   ["We have confused proximity with community","Four hundred people in a room is not the same as three people who know."],
   ["The early church met in the temple and from house to house","Both. Not one or the other, and the second one is the half we dropped."],
   ["A cord of three strands is a load-bearing image","Ecclesiastes is not being sentimental. It is describing structural capacity."]],
  "The question is not whether you like small groups. The question is who will show up at the hospital.",
  "Name one person you will ask into your life this week, and ask them."),
 [["Not Good to Be Alone","Genesis 2:18","The first not good, before anything went wrong.","Who knows the actual state of your life?","Write the names. Notice how long the list is."],
  ["Rows and Circles","Acts 2:46","Temple courts and house to house. Both, always.","Which one is missing for you?","Sit somewhere different this Sunday and learn one name."],
  ["The Honest Part","James 5:16","Confession requires a room small enough to be honest in.","What have you never said out loud?","Tell one safe person one true thing."],
  ["Carry Something","Galatians 6:2","Bearing burdens is a command, which means it is not optional and not automatic.","Whose burden could you carry this week?","Do one specific thing for one specific person."],
  ["Let Someone Carry Yours","Galatians 6:5","The harder half. Receiving is harder than giving for most of us.","What would you have to admit to accept help?","Ask for one thing you have been handling alone."],
  ["Spur One Another On","Hebrews 10:24-25","The stated purpose of meeting together, and it is active.","Who spurs you on?","Send one message that spurs somebody on."],
  ["Who Is Coming With You","Ecclesiastes 4:9-12","Three strands, not one. Come back with a name.","Who is your one?","Ask them this week, before Sunday."]],
 {"open":"Who is one person who showed up for you when they did not have to?",
  "qs":["Why is it so much easier to attend than to belong?","What has stopped you from being known here?",
        "What would it cost you to let someone carry something?","Who is missing from this room who should be in it?"],
  "apply":"Each person names one person they will invite into their life this week.",
  "pray":"Pray in pairs, for the person each of you named."},
 {"3":["Not Built Alone","Rows and Circles","Who Is Coming With You"],
  "4":["Not Built Alone","Rows and Circles","Carry and Be Carried","Who Is Coming With You"],
  "6":["Connecting","Growing","Serving","Sharing","Surrendering","Together"],
  "21":"Twenty-one days of showing up for someone.",
  "30":"Thirty days of community &mdash; one relationship, deepened.",
  "40":"Forty days of life together, churchwide, with groups launching in week one."}),

C("Twenty-One Days of Prayer","Learning it by doing it",
 SER("Teach Us to Pray","The disciples asked for one thing, and this was it",
  "The disciples watched Jesus do everything and asked to be taught only this.",
  "Luke 11:1-13; Matthew 6:5-13",
  "They saw him heal, teach, still storms and raise the dead. They asked to be taught one thing. Read Luke 11:1 and stop.",
  [["They asked for the one thing they could not reverse-engineer","Everything else looked like technique. This looked like relationship."],
   ["He gave them a shape, not a script","Father, name, kingdom, bread, forgiveness, deliverance. Six moves, endlessly reusable."],
   ["Then he told a story about a man being annoying at midnight","Persistence is not a lack of faith. Jesus commends it in the next paragraph."],
   ["Ask, seek, knock &mdash; all three are present tense","Keep asking. The tense is doing theological work."]],
  "You do not need a better prayer life. You need to pray. Those are different problems and only one of them is solvable this week.",
  "Ten minutes, five days, starting tomorrow. That is the whole ask."),
 [["Lord, Teach Us","Luke 11:1","They asked for this and nothing else.","What would you ask to be taught?","Ask God for one thing, plainly, out loud."],
  ["Father","Luke 11:2","The first word reframes everything after it.","What picture of a father do you bring to that word?","Begin tomorrow with that one word and stop for a minute."],
  ["Your Kingdom Come","Matthew 6:10","Praying for God's agenda before your own.","What would you pray if your own needs were not first?","Pray for something that does not benefit you."],
  ["Daily Bread","Matthew 6:11","Daily. Not weekly, not a year's supply.","What do you want a year's supply of?","Ask for today only, and notice how that feels."],
  ["Forgive Us As","Matthew 6:12","The most dangerous line in the prayer, because of the word as.","Who are you asking God to forgive you like you forgive them?","Forgive one thing today."],
  ["Keep Asking","Luke 11:5-10","The friend at midnight, and persistence commended.","What did you stop praying for?","Restart it today."],
  ["What Happened","Luke 11:13","Come back with something.","What changed in seven days?","Come Sunday with one sentence."]],
 {"open":"What is your honest prayer life like right now?",
  "qs":["Why do you think that is what they asked for?","Which line of the prayer is hardest for you?",
        "What did the midnight story do to your view of persistence?","What stopped you praying for something?"],
  "apply":"Ten minutes, five days this week. Report back next session.",
  "pray":"Pray the Lord's Prayer together, slowly, one line per person."},
 {"3":["Teach Us to Pray","Keep Asking","What Happened"],
  "4":["Teach Us to Pray","Father","Keep Asking","What Happened"],
  "6":["Teach Us to Pray","Father","Your Kingdom Come","Daily Bread","Forgive Us As","Keep Asking"],
  "21":"The full twenty-one days, one line of the prayer at a time.",
  "30":"Thirty days of prayer, adding silence and listening in week three.",
  "40":"Forty days of prayer churchwide, with a prayer room and nightly gatherings."}),

C("Purpose at Work","Monday is the mission field",
 SER("Monday Is the Mission Field","Where you spend most of your life is not a waiting room",
  "Most Christians spend the majority of their waking life in a place the church has never taught them to think about theologically.",
  "Colossians 3:23-24; Genesis 2:15; 1 Corinthians 7:17",
  "Ask the room to add up the hours they will spend at work this year. Then ask how many sermons they have heard about it.",
  [["Work existed before sin did","God put the man in the garden to work it. That is chapter two, not chapter three."],
   ["The curse made work hard; it did not make work bad","Thorns and sweat were added. The assignment was not withdrawn."],
   ["Whatever you do, work at it with all your heart, as for the Lord","Paul wrote that to slaves. If it applied there, it applies to your inbox."],
   ["Your job is not a platform for ministry; it is the ministry","The plumbing, the spreadsheet and the diagnosis are the work, not the cover for it."]],
  "You have been waiting for permission to believe your work matters. Consider it given, and it was never mine to give.",
  "Name one way you will do your actual job differently on Monday."),
 [["Before the Fall","Genesis 2:15","Work is older than sin.","What did you learn about work growing up?","Name one good thing about your work."],
  ["Thorns","Genesis 3:17-19","What actually changed, and what did not.","What is the thorn in your work right now?","Name it honestly instead of pretending."],
  ["As for the Lord","Colossians 3:23","The audience changes everything about the effort.","Who are you actually working for?","Do one task tomorrow as if He were the client."],
  ["Excellence Is Witness","Proverbs 22:29","Skill gets a hearing that argument does not.","Where are you coasting?","Fix one thing you have been doing at eighty percent."],
  ["The People There","Matthew 5:16","Your colleagues see more of you than your church does.","Who at work is watching you?","Do one thing for a colleague with no return."],
  ["Integrity When It Costs","Proverbs 11:1","The moment that defines a working life.","Where is the pressure?","Decide now what you will do before it arrives."],
  ["Sent There","1 Corinthians 7:17","You were placed, not stranded.","What if this is the assignment?","Come Sunday with one sentence about Monday."]],
 {"open":"What do you actually do all day, and does it feel like it matters?",
  "qs":["What have you been taught about work, directly or indirectly?","What changes if work existed before the fall?",
        "Where does integrity cost you something?","Who at your work would notice if your faith were real?"],
  "apply":"Each person names one change to how they work this week.",
  "pray":"Pray for each other's actual workplaces by name."},
 {"3":["Monday Is the Mission Field","As for the Lord","Sent There"],
  "4":["Monday Is the Mission Field","Thorns","Excellence Is Witness","Sent There"],
  "6":["Before the Fall","Thorns","As for the Lord","Excellence Is Witness","The People There","Sent There"],
  "21":"Twenty-one days of work as worship.",
  "30":"Thirty days of vocation &mdash; calling, craft and the people there.",
  "40":"Forty days of purpose at work, with a marketplace track and business-owner cohort."}),

C("He's Not Where You Left Him","Resurrection Sunday",
 SER("He&rsquo;s Not Where You Left Him","You came looking for a body",
  "The women came to finish a burial and found the grave had a different plan.",
  "Luke 24:1-8; 1 Corinthians 15:14-20",
  "They brought spices. That detail is the whole sermon &mdash; they came prepared for a corpse.",
  [["They were not expecting this","Nobody in the story anticipated resurrection. That is why the accounts are credible."],
   ["Why do you look for the living among the dead","The angel's question is aimed at us too."],
   ["Some of you came here today looking in the wrong place","For a marriage, a diagnosis, a prodigal, a career &mdash; still looking at the tomb."],
   ["He is not there, and that is the problem and the point","You will not find him where you last left him. He has moved, and he expects you to follow."]],
  "You came here to finish burying something. He is not in that grave, and neither is your story.",
  "Name the thing you have already buried, and ask one person to pray with you before you leave."),
 [["The Spices","Luke 24:1","They came prepared for the wrong thing.","What are you prepared for that may not be true?","Name what you have given up on."],
  ["The Stone","Luke 24:2","The obstacle was already handled before they arrived.","What are you carrying that is already dealt with?","Stop carrying one thing today."],
  ["The Question","Luke 24:5","Why do you look for the living among the dead?","Where are you looking?","Look somewhere else today."],
  ["Remember What He Said","Luke 24:6-8","They remembered. Memory was the turn.","What has God said that you have forgotten?","Write down one promise you have stopped believing."],
  ["They Told the Others","Luke 24:9","The first response was to go tell somebody.","Who needs to hear this?","Tell one person."],
  ["If Christ Has Not Been Raised","1 Corinthians 15:14-19","Paul stakes everything on this one claim.","What if it is true?","Follow one implication all the way."],
  ["First Fruits","1 Corinthians 15:20","His resurrection is the first of many, not the only one.","What does that mean for what you buried?","Come Sunday ready to say what moved."]],
 {"open":"What did you come here today hoping was still true?",
  "qs":["Why do you think nobody expected the resurrection?","Where are you looking for life in a grave?",
        "What have you already buried that God has not?","What changes if this is historically true?"],
  "apply":"Each person names one thing they had given up on.",
  "pray":"Pray specifically over what each person named. Do not rush this."},
 {"3":["He&rsquo;s Not Where You Left Him","The Stone","They Told the Others"],
  "4":["The Spices","The Stone","The Question","First Fruits"],
  "6":["He&rsquo;s Not Where You Left Him","Doubting Thomas","The Road to Emmaus","Breakfast on the Beach","Feed My Sheep","Until He Comes"],
  "21":"Twenty-one days from the empty tomb into Acts.",
  "30":"Thirty days of resurrection life &mdash; the great fifty days, compressed.",
  "40":"Forty days in Acts, launching the Sunday after Easter."}),

C("Enough","Contentment as the foundation",
 SER("Enough","The number you have never named",
  "Almost nobody has ever written down what would be enough, which is why nothing ever is.",
  "1 Timothy 6:6-10; Philippians 4:11-13; Ecclesiastes 5:10",
  "Ask everyone to think of a number that would be enough. Give them ten seconds. Then ask how many had one ready.",
  [["Whoever loves money never has enough","Ecclesiastes says it flatly, and it is an observation rather than a rule."],
   ["Godliness with contentment is great gain","Paul pairs them deliberately. Godliness alone is not the claim."],
   ["I have learned to be content","Learned. It is a skill, acquired over time, not a temperament."],
   ["The finish line moves unless you draw it","If you have never named the number, every increase resets the target."]],
  "Contentment is not the absence of desire. It is the presence of a line you drew on purpose.",
  "Write the number this week. Then ask why that one."),
 [["The Never","Ecclesiastes 5:10","Never has enough. A description, not a threat.","When did you last feel it was enough?","Notice one moment of enough today."],
  ["Great Gain","1 Timothy 6:6","The pairing that makes it work.","Which half is missing for you?","Name it honestly."],
  ["I Have Learned","Philippians 4:11-12","Learned, in both directions &mdash; plenty and want.","Which is harder for you?","Practise the harder one today."],
  ["The Comparison","Galatians 6:4","Comparison is the mechanism that steals it.","Who do you compare with?","Unfollow or step back from one source."],
  ["Tell Someone Your Number","Proverbs 27:17","Naming it out loud makes it real.","Who could you say it to?","Say it to one person."],
  ["Give From Enough","2 Corinthians 8:12-14","Contentment is what makes generosity possible rather than heroic.","What could you release?","Give one thing away."],
  ["The Line You Drew","Matthew 6:33","Seek first, and the rest is added.","Where is your line now?","Come Sunday with the number."]],
 {"open":"What is one thing you wanted badly and got, and how long did it satisfy?",
  "qs":["Why do you think most people have never named a number?","Where does comparison do the most damage for you?",
        "What would it take to learn contentment?","What would change if you drew the line?"],
  "apply":"Each person writes a number privately and says only whether they wrote one.",
  "pray":"Pray for freedom from comparison, by name."},
 {"3":["Enough","The Comparison","The Line You Drew"],
  "4":["The Never","Great Gain","I Have Learned","The Line You Drew"],
  "6":["Enough","The Comparison","I Have Learned","Give From Enough","Money and Anxiety","The Line You Drew"],
  "21":"Twenty-one days of contentment.",
  "30":"Thirty days without comparison.",
  "40":"How Much Is Enough? &mdash; the full campaign, with a family and a legacy track."}),
]
