# -*- coding: utf-8 -*-
# Catalytic Sundays - Easter & Christmas Edition
# 16 categories x 20 titles = 320

EASTER = [
("Resurrection Sunday", "The main event. The one Sunday of the year when the whole claim of Christianity is on the table.", [
("He's Not Where You Left Him", "Why the empty tomb undoes every assumption you brought with you"),
("The Stone Was Already Moved", "God goes ahead of the obstacle you are still dreading"),
("Sunday's Coming", "What to do with the Friday you are living in right now"),
("Death Backwards", "The one grave that ran in reverse, and what it means for yours"),
("The First Witness Was a Woman", "What God trusted to the people nobody believed"),
("Alive", "The single word the entire faith rests on"),
("Say His Name", "The moment grief turned around and recognized Jesus"),
("The Undoing", "Everything the resurrection reversed in one Sunday morning"),
("Proof You Can Stand On", "Why the resurrection is a historical claim, not a spiritual mood"),
("He Called You by Name", "The resurrection was personal before it was cosmic"),
("Roll Away the Rest", "What Easter frees you from besides death"),
("The Empty Tomb and the Full Room", "Why the resurrection creates a people, not just a belief"),
("Still Wounded, Still Risen", "The scars Jesus kept on purpose"),
("Not a Ghost Story", "Why the disciples ate breakfast with a man who had been dead"),
("Hope With a Pulse", "The difference between wishing something were true and knowing it is"),
("Because He Lives", "Three things that are now permanently true about your future"),
("The Best News Ever Told, Told Again", "Why we say the same thing every single year and never tire of it"),
("From the Garden to the Garden", "How Easter finishes what Genesis started"),
("Why Do You Look for the Living Among the Dead?", "The question the angels asked, and why it still lands"),
("The Last Enemy", "What the resurrection did to the thing you fear most"),
]),
("Good Friday", "The heaviest service of the year. These carry weight without rushing to Sunday.", [
("It Is Finished", "The three words that ended the striving"),
("The Trade", "What He took, and what you got"),
("Between Two Thieves", "Where Jesus chose to die, and who He chose to die beside"),
("The Silence of God", "What the Father did while the Son was dying"),
("Nailed", "The record standing against you, and where it went"),
("Why the Cross and Not Something Easier", "The question every honest person eventually asks"),
("Forgive Them", "Grace spoken from the worst seat in history"),
("The Curtain Tore", "The barrier came down from the top, which means God moved first"),
("Barabbas Went Free", "The guiltiest man in Jerusalem got the best day of his life"),
("Carrying What He Did Not Owe", "The weight Jesus refused to put down"),
("My God, My God", "When Jesus prayed the prayer you are afraid to pray"),
("Today You Will Be With Me", "The shortest conversion in Scripture"),
("The Kindest Cruelty", "Why love looked like this and could not have looked like less"),
("Six Hours", "What happened in the darkest afternoon in human history"),
("He Could Have Come Down", "The strongest man on the hill chose not to save Himself"),
("Blood on the Doorframe", "The Passover that Friday finally explained"),
("The Cup He Did Not Pass", "Gethsemane and the strange freedom of a surrendered will"),
("Guilty and Loved", "Both are true, and only one of them changes"),
("The Cross Is Not a Metaphor", "Recovering the offense we have decorated over"),
("Friday Is Not the End of the Sentence", "Naming the grief honestly before naming the hope"),
]),
("Palm Sunday", "The entry week. Celebration with an edge, and the setup for everything that follows.", [
("The Wrong Kind of King", "They wanted a general and God sent a donkey"),
("Hosanna Means Save Us", "The desperate cry underneath the celebration"),
("From Palms to Nails", "How a crowd changes its mind in five days"),
("He Wept Over the City", "What Jesus saw that the cheering crowd could not"),
("The Parade That Was a Protest", "Reading the triumphal entry the way Rome read it"),
("If They Stay Silent, the Stones Will Shout", "Why worship was never optional"),
("Borrowed Donkey, Borrowed Tomb", "The King who owned nothing owns everything"),
("The King Who Came Through the Wrong Gate", "Expectation, disappointment, and the God who will not be managed"),
("Cloaks on the Road", "What the crowd threw down, and what it cost them"),
("When God Will Not Be the Savior You Ordered", "Palm Sunday for people who want a different Jesus"),
("He Came for the City That Killed Him", "Love that walks in with open eyes"),
("The Week That Changed Everything Started on a Sunday", "Setting the table for Holy Week"),
("Zechariah's Long Wait", "A five-hundred-year-old prophecy walking through the gate"),
("Turning Over the Tables", "What made the gentle Jesus furious"),
("What Are You Shouting?", "The distance between a crowd and a disciple"),
("The Fig Tree and the Fake", "Jesus and the fruitless religious life"),
("Blessed Is He Who Comes", "Why we still say the same words two thousand years later"),
("Entering Your City", "What it looks like when Jesus comes to where you actually live"),
("Two Processions", "Pilate on a warhorse, Jesus on a colt, and the choice between them"),
("The Countdown Begins", "Six days that reordered eternity"),
]),
("Holy Week & Maundy Thursday", "Midweek services, the table, the garden, and the long night before the cross.", [
("The Towel and the Basin", "Leadership according to the God who washed feet"),
("Do This in Remembrance", "Why the table still gathers us"),
("The Longest Night", "Gethsemane, betrayal, and the friends who fell asleep"),
("Judas Had a Seat at the Table", "Jesus served the man who was selling Him"),
("A New Command", "Love as the one thing Jesus made mandatory"),
("The Cup and the Bread", "What we are actually holding in our hands"),
("Peter's Worst Night", "Denial, roosters, and a grace that came back for him"),
("Not My Will", "The prayer that saved the world"),
("Betrayed With a Kiss", "When the wound comes from close range"),
("Stay Awake With Me", "The friendship Jesus asked for and did not get"),
("Thursday People", "Living in the room between the meal and the trial"),
("The Trial That Broke Every Rule", "Justice on the night justice died"),
("He Knew and He Stayed", "Foreknowledge, love, and the decision to remain"),
("Feet He Knew Would Run", "Washing the disciples who were about to abandon Him"),
("The Passover He Fulfilled", "Reading Exodus at the Last Supper"),
("Sifted Like Wheat", "What Jesus prayed over Peter before Peter ever failed"),
("Silent Saturday", "The day between, and the God who seems absent"),
("What Holy Week Asks of You", "Walking it instead of watching it"),
("Thirty Pieces", "The price of a friend, and what we still sell Him for"),
("The Garden and the Grave", "Two places Jesus went so you would never go alone"),
]),
("Easter for the Skeptic", "Your biggest guest Sunday of the year. Written for the person dragged in by family.", [
("If It Is True, Nothing Else Matters", "And if it is not, nothing else matters either"),
("The Evidence for an Empty Tomb", "What a courtroom would actually do with the resurrection"),
("Doubt Is Welcome Here", "The disciple who needed to touch it before he would believe it"),
("Too Good to Be True?", "Examining the claim instead of dismissing it"),
("Why Would Anyone Die for a Lie?", "What happened to the eyewitnesses, one by one"),
("The Evidence Problem Cuts Both Ways", "Unbelief requires faith too"),
("Smart People Believe This", "Faith and intellectual honesty in the same room"),
("What If You Are Wrong?", "An invitation to actually look before deciding"),
("The Church Has Hurt You. Jesus Has Not.", "Separating the institution from the man"),
("Three Days That Will Not Go Away", "Why this story outlived every attempt to kill it"),
("Come and See", "The oldest invitation in Christianity"),
("Christianity Rises or Falls Right Here", "Paul's own bet on the resurrection"),
("The Theories and Why They Do Not Hold", "Swoon, theft, hallucination, legend"),
("You Do Not Have to Have It Figured Out", "Belief as a direction, not a destination"),
("Religion Did Not Do This. God Did.", "The difference between a system and a Savior"),
("Skeptics Made the Best Apostles", "Thomas, Paul, and the brother who did not believe"),
("One Question Worth Your Whole Life", "Who do you say that He is?"),
("If He Rose, He Is Still Here", "The uncomfortable implication of an empty grave"),
("Never Been to Church Before? Start Here.", "The whole gospel in one Sunday, no background required"),
("The Most Investigated Claim in History", "And why it is still standing"),
]),
("The Sunday After Easter", "The week attendance drops and the follow-through decides whether Easter mattered.", [
("Now What?", "The Monday after the miracle"),
("Back to the Boats", "What Peter did when he did not know what to do"),
("Breakfast on the Beach", "Jesus restores the ones who ran"),
("Do You Love Me?", "Three questions for a man who denied Him three times"),
("The Attendance Drops. The Mission Does Not.", "A word for the ones who came back"),
("Feed My Sheep", "What resurrection people are actually for"),
("Thomas Gets a Second Sunday", "Grace for the one who missed it the first time"),
("Peace Be With You", "The first words out of the risen Christ's mouth"),
("The Road to Emmaus", "Two grieving people and a stranger who explained everything"),
("Our Hearts Were Burning", "Recognizing Jesus in hindsight"),
("Living Like It Happened", "Turning an Easter feeling into an ordinary Tuesday"),
("The Long Obedience After the Big Moment", "Momentum without hype"),
("He Breathed on Them", "The Spirit given before Pentecost"),
("Forty More Days", "What Jesus did between the tomb and the ascension"),
("From Witness to Witnesses", "The commission handed to ordinary people"),
("Ordinary Time Is Where Faith Is Built", "Why the unglamorous stretch matters most"),
("Still Locked in the Room", "Fear that lingers after the good news arrives"),
("Take the Next Step", "Making Easter decisions stick past April"),
("Resurrection Is a Practice, Not an Event", "Learning to rise daily"),
("Who Are You Going to Tell?", "The natural overflow of news this good"),
]),
("Ash Wednesday & the Road to Lent", "The on-ramp. Forty days of preparation that make Easter land harder.", [
("Remember You Are Dust", "The most freeing sentence in the church calendar"),
("Forty Days in the Wilderness", "Why Jesus began His ministry hungry"),
("Give Something Up, Gain Something Better", "Fasting as addition, not subtraction"),
("The Mark on Your Forehead", "Wearing your mortality in public"),
("Return to Me", "Joel's call and the God who runs toward repentance"),
("Rend Your Heart, Not Your Garments", "The difference between sorrow and show"),
("Not by Bread Alone", "The first temptation and the appetite underneath it"),
("Prove It", "Why Jesus refused to perform for the devil"),
("All This Can Be Yours", "The shortcut Jesus turned down"),
("A Season for Subtraction", "Making room by making less"),
("Confession Is a Gift, Not a Punishment", "Naming it out loud so it loses its grip"),
("The Slow Walk to the Cross", "Why Easter needs a runway"),
("Lent for People Who Do Not Do Lent", "A practical entry point with no assumed background"),
("Secret Giving, Secret Praying, Secret Fasting", "Matthew 6 and the audience of One"),
("What Are You Hungry For?", "Appetite as a spiritual diagnostic"),
("From Ashes to Glory", "The arc of the whole season in a single message"),
("The Desert Is Not a Detour", "Wilderness as formation, not punishment"),
("Sackcloth and Smartphones", "Ancient repentance in a distracted age"),
("Forty Days to Honest", "Using the season to stop pretending"),
("Dust That God Breathed On", "Mortality and dignity held together"),
]),
("Easter for the Grieving", "For the people in the room who buried someone this year. Hope without denial.", [
("Jesus Wept First", "He grieved before He raised"),
("Lazarus, Come Out", "Resurrection in the middle of a funeral"),
("If You Had Been Here", "Faith and disappointment in the same sentence"),
("Where Is God on Saturday?", "The day between loss and hope"),
("He Kept the Scars", "Healing that does not erase the history"),
("Mourning Is Not a Lack of Faith", "Permission to grieve all the way down"),
("The Last Enemy Will Be Destroyed", "A promise for people standing at graves"),
("She Thought He Was the Gardener", "When grief blurs the God standing right there"),
("Weeping May Stay for the Night", "What the Psalms hand the brokenhearted"),
("Grief and Hope Are Not Opposites", "Holding both without having to choose"),
("The Empty Chair at Easter", "Naming the loss the holiday makes louder"),
("Death Is Real. It Is Not Final.", "Honest theology for the bereaved"),
("For the Ones Who Cannot Sing Yet", "Worship when the words will not come"),
("He Descended", "Where Christ went for the ones in the dark"),
("Reunion", "What Scripture actually promises about seeing them again"),
("The God Who Sits With You", "Presence offered before answers"),
("Rachel Weeping", "Grief that refuses easy comfort, and the God who allows it"),
("Your Story Is Not Over", "Hope for anyone stuck in the middle chapter"),
("Beauty From Ashes", "What God grows in scorched ground"),
("A Promise With Your Name On It", "Personal hope, not general optimism"),
]),
]

CHRISTMAS = [
("Christmas Eve", "Candlelight, families home for the holidays, and the highest attendance night of the year.", [
("The Night the Waiting Ended", "Four hundred silent years and one cry in the dark"),
("Light in the Dark", "Why we hold candles and sing in the middle of the night"),
("Come and Behold Him", "An invitation older than the carol"),
("No Room", "The first thing the world ever told Jesus"),
("Glory in a Feed Trough", "God's entrance had no red carpet"),
("Fear Not", "The angel's opening line, and why we needed it first"),
("Silent Night, Sleepless World", "Peace offered to people who cannot turn their minds off"),
("Wrapped in Cloths", "The King who arrived helpless"),
("The Word Became Flesh and Moved In", "John's version of the Christmas story"),
("Emmanuel", "God with us, and what it cost Him to be"),
("To You Is Born This Day", "The most personal announcement in history"),
("The Shepherds Went to See", "Ordinary people, first invitation"),
("Peace on Earth", "The promise we hear every year and still need"),
("Away in a Manger, Bound for a Cross", "The shadow lying across the nativity"),
("Joy to the World, Now", "Not sentiment, but a claim about reality"),
("One Candle Is Enough", "Small light in real darkness"),
("He Came at Night", "Why God so often arrives after dark"),
("The Angels Could Not Keep Quiet", "Worship as an involuntary response"),
("What Are You Hoping For This Year?", "Longing, and the God who meets it"),
("Christmas Eve for the Weary", "A quiet word for people running on empty"),
]),
("Christmas Day & Christmas Sunday", "The morning itself. The claim at the center of the season, stated plainly.", [
("Unto Us a Child Is Born", "Isaiah's promise, delivered on time"),
("God in a Body", "The most audacious claim any religion has ever made"),
("The Gift You Did Not Know to Ask For", "Grace that arrives before the request"),
("The Name Above Every Name Began as a Baby's", "Humility as the shape of God"),
("Wonderful Counselor, Mighty God", "Four names for one child"),
("He Emptied Himself", "Philippians 2 and the descent of God"),
("The First Christmas Had No Decorations", "Recovering the story underneath the wrapping"),
("What Christmas Is Actually For", "The purpose behind the party"),
("God Chose a Family", "Why the incarnation came through ordinary people"),
("From Eternity Into a Calendar", "The day God entered time"),
("Christmas Is a Rescue Mission", "Not a birthday. A landing."),
("The Genealogy Nobody Reads", "Matthew's messy family tree and what it says about you"),
("Born to Die", "The manger explained by the cross"),
("Immanuel for the Overwhelmed", "God with us in a season that exhausts us"),
("Good News of Great Joy for All People", "The scandal hiding in the word all"),
("He Came to His Own", "Rejection built into the story from day one"),
("Full of Grace and Truth", "What we saw when God finally showed up"),
("The Light Shines in the Darkness", "And what the darkness could never do to it"),
("Merry Christmas Is a Theological Statement", "Reclaiming the greeting we say without thinking"),
("What Will You Do With Him?", "The question the manger eventually asks everyone"),
]),
("Advent Sunday Singles", "Each Advent theme built to stand alone, for churches that do not run the full series.", [
("Hope Has a Name", "Advent week one, standing on its own"),
("Peace That Does Not Depend on Circumstances", "Advent week two"),
("Joy Is Not the Same as Happy", "Advent week three"),
("Love Came Down", "Advent week four"),
("Keep Awake", "Advent's forgotten warning"),
("The Long Wait", "What God's people did for four hundred years"),
("Prepare the Way", "John the Baptist crashes the Christmas party"),
("Advent Means Arrival", "Two comings, one season"),
("Learning to Wait Well", "Patience as a spiritual muscle"),
("The Prophets Saw It Coming", "Isaiah, Micah, Malachi and the long promise"),
("A Shoot From the Stump", "Hope rising out of what looked dead"),
("O Come, O Come, Emmanuel", "Singing the longing before the answer arrives"),
("Not Yet Is Not No", "Faith in the gap between prayer and answer"),
("The Second Advent", "Christmas as a rehearsal for His return"),
("Little Among the Thousands", "God's preference for the overlooked place"),
("Repent", "The unexpected first word of the season"),
("The Waiting Room of God", "Advent for anyone stuck between the request and the reply"),
("Watch for Him", "Vigilance without anxiety"),
("Every Valley Shall Be Raised", "What God does to the terrain of a life"),
("Light One Candle at a Time", "Hope arriving in increments"),
]),
("Christmas for the Skeptic", "Your second-biggest guest Sunday. For the visitor who came for the music.", [
("Is Any of This Actually True?", "Examining the Christmas story honestly"),
("A Virgin Birth in a Scientific Age", "The claim, and the questions it raises"),
("Why December 25th Does Not Matter", "Clearing the objection so we can get to the point"),
("The Most Famous Story You Have Never Examined", "Familiarity as the enemy of belief"),
("If God Wanted to Reach Us, This Is How", "The logic of the incarnation"),
("Not a Fairy Tale", "Census records, named rulers, actual geography"),
("What Christianity Says That No Other Religion Does", "God came down"),
("You Came for the Music. Stay for the Claim.", "An honest word to Christmas visitors"),
("The Problem With a Distant God", "Why Christmas is the answer to a watchmaker deity"),
("Herod Believed It Enough to Be Afraid", "Even the enemies took it seriously"),
("Wise Men Still Ask Questions", "Seeking as a legitimate place to begin"),
("Religion or Rescue", "What Christmas is actually offering you"),
("If It Happened, It Changes Everything", "Following the claim all the way to its conclusion"),
("Full Tonight, Empty in February", "A gentle, honest conversation about why"),
("God Does Not Need Your Performance", "Grace explained through a manger"),
("The Story Beneath the Sentiment", "Getting underneath the nostalgia"),
("What Do You Do With Jesus?", "He left us no neutral option"),
("Come as You Are. Really.", "The doors open wider than you think"),
("A Faith That Survived Rome", "Why this particular story did not die"),
("One Honest Look", "An invitation, not a pitch"),
]),
("The Characters of the Nativity", "Character-driven messages. Works as a series or as standalone Sundays.", [
("Mary Said Yes", "Courage in a teenage girl"),
("Joseph Stayed", "The quiet integrity of a man who could have walked away"),
("The Shepherds Were Nobody", "And God told them first"),
("The Magi Traveled Anyway", "Faith that goes the distance"),
("Herod Was Threatened", "What happens when Jesus disrupts your throne"),
("Elizabeth Believed for Her", "Friendship in the season of waiting"),
("Zechariah Lost His Voice", "Doubt, silence, and a song restored"),
("Simeon Waited His Whole Life", "Faithfulness that outlasts a lifetime"),
("Anna Never Left the Temple", "The prayer warrior nobody noticed"),
("The Innkeeper's Missed Moment", "Too busy for the most important guest who ever came"),
("John Leapt in the Womb", "Recognition before words"),
("Gabriel's Assignment", "The messenger and the weight of the message"),
("Heaven's Reaction", "What the angels did when God became small"),
("Mary's Magnificat", "The most revolutionary song in the Bible"),
("Joseph's Dreams", "Guidance for a man who kept getting woken up"),
("Caesar Never Knew", "Empires serving purposes they cannot see"),
("The Mothers of Bethlehem", "Grief written into the Christmas story itself"),
("Refugees in Egypt", "The holy family on the run"),
("The Four Women in the Genealogy", "Tamar, Rahab, Ruth, Bathsheba, and a God who redeems"),
("Which One Are You?", "Finding yourself somewhere in the cast"),
]),
("Blue Christmas", "For the people white-knuckling the season. Increasingly the most-needed service you offer.", [
("Christmas When You Are Not Okay", "Permission to feel exactly what you feel"),
("The Empty Chair", "Grief at a table set for one less"),
("A Man of Sorrows", "Jesus knows the season you are in"),
("Hope for the Ones Faking It", "Honesty in a season that demands cheer"),
("When the Carols Make You Cry", "What worship does with sorrow"),
("Christmas After Divorce", "Rebuilding a holiday that broke"),
("The First Christmas Without Them", "Naming the loss out loud"),
("Silent Night for the Sleepless", "Anxiety, insomnia, and the peace of Christ"),
("Bethlehem Was Not a Happy Town", "Grief inside the original story"),
("God Draws Near to the Brokenhearted", "Psalm 34 at Christmas"),
("When the Family Gathering Is the Hard Part", "Estrangement and the holidays"),
("Christmas on a Tight Budget", "Financial pressure and the meaning of enough"),
("He Came Into a Broken World on Purpose", "Not despite the mess. Into it."),
("Longing Is Not Failure", "Advent as a season built for the aching"),
("A Candle for the Grieving", "Making space in the service for the ones who need it"),
("When You Cannot Feel God This Year", "Faith without the feelings"),
("Christmas in the Hospital", "Presence when the plans collapse"),
("The Slow Return of Joy", "What healing actually looks like"),
("Weary World, Rejoice", "The line in the carol that names it exactly"),
("You Are Not the Only One", "Company in a hard season"),
]),
("After Christmas & New Year", "The low-attendance Sunday nobody plans for, and the highest-leverage vision moment of the year.", [
("Now That the Guests Have Gone", "Living with Jesus after the holiday ends"),
("What Will You Carry Into January?", "Turning a season into a habit"),
("New Year, Same God", "Stability when the calendar changes"),
("Mary Treasured These Things", "Reflection as a spiritual practice"),
("The Boy in the Temple", "The only story we have from Jesus' childhood, and what it teaches"),
("One Word for the Year", "A simple discipline that actually sticks"),
("Forgetting What Is Behind", "Paul on moving forward without denial"),
("Resolutions Fail. Repentance Works.", "The difference that lasts past February"),
("Take Down the Tree, Keep the Truth", "What stays after the decorations come down"),
("Numbering Our Days", "Psalm 90 at the turn of the year"),
("The God of New Things", "Isaiah 43 and genuine fresh starts"),
("Where Do You Want to Be Next December?", "Vision Sunday framing"),
("Ready for Whatever Comes", "Simeon's song at the turn of the year"),
("Redeeming the Time", "Stewardship of the year in front of you"),
("Not Everyone Starts January Excited", "Grace for the discouraged"),
("The Habits That Made the Saints", "Small practices, long obedience"),
("Fresh Start for the Failed Start", "For anyone who has broken this promise before"),
("Anna's Long Faithfulness", "Endurance as the underrated virtue"),
("They Went Home a Different Way", "Encounter changes the route"),
("The First Sunday of the Rest of It", "Beginning again with God"),
]),
("The Incarnation", "The theology underneath the season. For churches that want depth, not just warmth.", [
("Why God Had to Have a Body", "The theology under the nativity"),
("In the Beginning Was the Word", "John's Christmas, no shepherds required"),
("Fully God, Fully Man", "Holding both without flinching"),
("The Humility of God", "What it cost the infinite to become small"),
("He Learned to Walk", "The staggering ordinariness of a divine childhood"),
("Tempted in Every Way", "Why the incarnation matters most when you are struggling"),
("The Image of the Invisible God", "Colossians and the visible Christ"),
("Not Something to Be Grasped", "Descent as divine strategy"),
("God Understands, Literally", "Sympathy from the inside"),
("The Second Adam", "What Jesus came to redo"),
("Christmas Is the Beginning of the Cross", "One continuous rescue"),
("Flesh and Blood Like Us", "Hebrews on why the incarnation was necessary"),
("The Scandal of Particularity", "One time, one place, one people"),
("If God Is Like Jesus", "Recalibrating your picture of the Father"),
("He Emptied, Then He Filled", "The pattern of the whole Christian life"),
("The Bridge Only God Could Build", "Why nothing else could reach"),
("What Angels Long to Look Into", "Heaven's astonishment at grace"),
("Born Under the Law", "Jesus kept what we could not"),
("He Took On What He Came to Heal", "The logic of the incarnation, applied"),
("God With Us Is Still True in February", "Carrying the incarnation past the season"),
]),
]
