# -*- coding: utf-8 -*-
def G(t, when, mins, beats, sc, line): return {"t":t,"w":when,"m":mins,"b":beats,"sc":sc,"l":line}

GRAVE_NOTE = ("Ten minutes maximum, whatever the weather, and usually fewer. Stand where the family can see you. "
 "Know who lowers the casket and when. Have it printed even if you never look at it, because wind takes paper "
 "and grief takes memory.")

GRAVE_RULES = [
 ["Shorter than you think","Six to eight minutes is right. Ten is the ceiling. In cold or rain, three."],
 ["Face the family, not the crowd","Position yourself so the closest family can see your face without turning."],
 ["Know the mechanics first","Who lowers, when, whether the family stays, where the cars are. Ask the funeral director before anyone arrives."],
 ["Say the name","Three times at least. At a graveside the name is the whole ministry."],
 ["No new content","This is not a second sermon. Everything here was already said inside; this is the sealing of it."],
 ["Stay after","The five minutes after you finish matter more than the eight before. Do not walk to your car."],
]

GRAVESIDE = [
# --- Standard ---
G("The Traditional Committal","Any burial, the default","7 min",
 ["Gather and name","Read the committal words","Earth to earth","A short prayer","The benediction"],
 ["Genesis 3:19","John 11:25-26","1 Corinthians 15:42-44"],
 "We commit the body to the ground, and we commit the soul to the God who made it."),
G("A Short Committal","When time or weather is against you","5 min",
 ["Name and gather","One verse","The committal","Amen"],
 ["Psalm 23:4","John 11:25"],
 "We do not have long here, and we do not need long. What matters was already said."),
G("A Very Short Committal","Rain, cold, or a frail family","3 min",
 ["One sentence","The committal words","One-line prayer"],
 ["Psalm 23:4"],
 "We stand here for a moment, and then we go home and remember well."),
G("The Extended Committal","When the graveside is the whole service","12 min",
 ["Welcome","Scripture reading","Brief message","The committal","Prayer","Benediction"],
 ["Psalm 23","John 14:1-6","Revelation 21:4"],
 "For some families this is the service. Give it the weight it carries."),
G("Committal With Communion","A small family, a long faith","10 min",
 ["Gather","The words of institution","Communion","The committal","Benediction"],
 ["1 Corinthians 11:23-26","Luke 22:19-20"],
 "The table at the grave is a strange and right thing. He said do this until he comes."),
G("Committal With a Hymn","When the family sings","9 min",
 ["Gather","A verse of the hymn","Scripture","The committal","The last verse","Prayer"],
 ["Psalm 46:1-3","Romans 8:38-39"],
 "Sing the first verse and the last. Nobody knows the middle ones and the wind takes them anyway."),
G("The Family Committal","Six people, no public service","6 min",
 ["Sit or stand close","Read one psalm","The committal","Pray by name for each person present"],
 ["Psalm 121","Isaiah 43:1-3"],
 "With six people you can say each name. Do it."),
G("Committal Before the Service","When burial precedes the memorial","6 min",
 ["Gather","Name what happens later","The committal","A prayer that points forward"],
 ["Ecclesiastes 3:1-2","John 11:25"],
 "We do this first, quietly, and then we will remember together in an hour."),
G("Committal After the Service","The standard sequence","7 min",
 ["Gather","One line from the message","The committal","Benediction"],
 ["Romans 8:38-39","2 Corinthians 5:1"],
 "Pick one sentence from inside and repeat it here. Repetition at a grave is not redundancy."),
G("A Delayed Burial","Months after the death","8 min",
 ["Name the gap honestly","Scripture","The committal","Prayer for what has already been carried"],
 ["Psalm 30:5","Lamentations 3:22-23"],
 "Time has passed and grief has not. Both of those things are true today."),
# --- By life stage ---
G("An Infant","Stillbirth or infant loss","6 min",
 ["Say the child's name","Hold the silence","A psalm, not an explanation","The committal","Prayer for the parents by name"],
 ["Psalm 139:13-16","2 Samuel 12:23","Mark 10:14"],
 "We name this child, because this child had a name and has one still."),
G("A Child","Any age up to twelve","7 min",
 ["Name the child","Let the children present see you","One verse","The committal","Prayer for the family"],
 ["Mark 10:13-16","Matthew 18:10","Revelation 21:4"],
 "Never explain. Never say God needed them. Say the name and say that God is close to the broken-hearted."),
G("A Teenager","Thirteen to nineteen","8 min",
 ["Name","Acknowledge the friends present","Scripture","The committal","A word to the young people"],
 ["Psalm 34:18","John 11:35","1 Thessalonians 4:13"],
 "Half the people standing here are seventeen and have never been to a grave. Speak to them."),
G("A Young Adult","Twenties and thirties","8 min",
 ["Name","Name the unfinished","Scripture","The committal","Prayer"],
 ["Psalm 90:12","James 4:14","Romans 8:38-39"],
 "There was a life that was going to happen. Say that out loud rather than around it."),
G("A Parent of Young Children","The hardest ordinary funeral","9 min",
 ["Name","Speak to the children directly, by name","Scripture","The committal","Prayer over the household"],
 ["Psalm 68:5","John 14:18","Deuteronomy 31:8"],
 "Kneel to the children's height if you can. They will remember that longer than the words."),
G("A Person in Midlife","Forties and fifties","7 min",
 ["Name","The work left undone","Scripture","The committal","Prayer"],
 ["Psalm 90:12","2 Timothy 4:7"],
 "Midlife deaths carry a particular unfairness. Do not smooth it."),
G("A Long Life Well Lived","Eighty and beyond","7 min",
 ["Name and the years","Give thanks for the length","Scripture","The committal","Blessing over the generations present"],
 ["Psalm 92:12-14","Genesis 25:8","2 Timothy 4:7-8"],
 "Grief and gratitude both belong here. Give each of them a sentence."),
G("A Very Old Person","Ninety and beyond, outlived their peers","7 min",
 ["Name","Acknowledge the small crowd","Scripture","The committal","Prayer"],
 ["Psalm 71:18","Isaiah 46:4"],
 "Few people are here because they all went first. Say that kindly and it becomes a tribute rather than a lack."),
# --- Hard deaths ---
G("A Death by Suicide","With care and no speculation","8 min",
 ["Say the name","Say nothing about cause","One psalm","The committal","Prayer for those carrying guilt"],
 ["Psalm 34:18","Psalm 139:7-12","Romans 8:38-39"],
 "Never speculate about eternity. Say that nothing separates us from the love of God, and stop there."),
G("A Sudden Death","Accident, heart attack, no warning","7 min",
 ["Name","Acknowledge there was no goodbye","Scripture","The committal","Prayer"],
 ["James 4:14","Psalm 31:15","John 14:1-3"],
 "There was no goodbye. That is its own wound and it deserves a sentence."),
G("A Violent Death","Where anger is in the ground with the grief","8 min",
 ["Name","Let the anger be present","A lament psalm","The committal","Prayer for those who want justice"],
 ["Psalm 10:1","Psalm 13:1-2","Romans 12:19"],
 "Anger at a graveside is not a failure of faith. The psalms are full of it."),
G("An Overdose","Dignity and honesty together","8 min",
 ["Name the person, not the manner","One psalm","The committal","Prayer for a family who has grieved for years"],
 ["Psalm 34:18","Isaiah 53:4","Romans 8:38-39"],
 "This family has been grieving for years already. Today is not the beginning."),
G("A Long Illness","When everyone is exhausted","7 min",
 ["Name","Acknowledge the exhaustion and the relief","Scripture","The committal","Prayer for rest"],
 ["Revelation 14:13","Matthew 11:28","2 Corinthians 4:16-18"],
 "Relief and grief arrive together and people feel guilty about the relief. Name it so they do not have to."),
G("Dementia","Grieving someone who left before they died","8 min",
 ["Name","Acknowledge the long goodbye","Scripture","The committal","Prayer"],
 ["Psalm 139:1-6","Isaiah 49:15-16"],
 "You have been saying goodbye for years. Today is the last of many."),
G("A Missing Person Declared Dead","A service with no body","8 min",
 ["Name","Acknowledge what is absent","Scripture","A committal of memory rather than remains","Prayer"],
 ["Psalm 139:7-10","Romans 8:38-39"],
 "There is nothing to commit but a life. That is enough and it is what we do today."),
G("A Death Far From Home","Cremated or buried elsewhere","7 min",
 ["Name","Acknowledge the distance","Scripture","Committal of ashes or memory","Prayer"],
 ["Psalm 139:9-10","Acts 17:26-27"],
 "Distance does not put anyone outside the reach of God."),
G("Multiple Deaths","One family, more than one loss","9 min",
 ["Say every name","Do not merge them","Scripture","One committal naming each","Prayer"],
 ["Psalm 46:1-3","2 Corinthians 1:3-4"],
 "Each person gets their own sentence. Merging them is the fastest way to wound this family."),
G("A Public Death","When the news is already covering it","8 min",
 ["Name","Reclaim them from the story","Scripture","The committal","Prayer for privacy"],
 ["Psalm 27:5","Isaiah 43:1"],
 "The world knows a story. This family knows a person. Speak about the person."),
G("An Estranged Family","When the grief is complicated","8 min",
 ["Name","Do not resolve what is not resolved","Scripture","The committal","Prayer for everyone present"],
 ["Romans 12:18","Psalm 51:17"],
 "Some things do not get fixed at a graveside. Do not pretend they did."),
# --- Special circumstances ---
G("A Military Funeral","With honours and a folded flag","9 min",
 ["Coordinate with the honour guard first","Name","Scripture","The committal","Stand back for the honours","Prayer after"],
 ["John 15:13","Psalm 91:1-2","Revelation 21:4"],
 "The honour guard runs their part. Know exactly where yours ends and theirs begins."),
G("A Veteran's Committal","Service noted, no full honours","8 min",
 ["Name and service","Scripture","The committal","Prayer","Moment of silence"],
 ["John 15:13","2 Timothy 4:7"],
 "Name the service branch and the years. Veterans notice whether you got it right."),
G("A First Responder","Line of duty or after service","9 min",
 ["Coordinate with the department","Name","Scripture","The committal","Prayer for those still serving"],
 ["John 15:13","Isaiah 6:8","Psalm 91"],
 "Half the people here go back on shift tomorrow. Say something to them."),
G("Fraternal or Civic Rites","When another group has a part","8 min",
 ["Agree the order in advance","Your portion first or last, not interleaved","Scripture","The committal","Prayer"],
 ["Psalm 90:1-2","Ecclesiastes 12:7"],
 "Never improvise around another group's ritual. Agree the sequence before anyone arrives."),
G("Cremation and Interment of Ashes","Ashes to ashes","7 min",
 ["Name","Scripture","The committal adapted for ashes","Prayer"],
 ["Genesis 3:19","Ecclesiastes 12:7","1 Corinthians 15:42-44"],
 "Ashes to ashes, dust to dust. The words hold; only the object changes."),
G("Scattering Ashes","In a chosen place","7 min",
 ["Name the place and why","Scripture","Words as the ashes are scattered","Prayer"],
 ["Psalm 104:29-30","Ecclesiastes 12:7"],
 "The place matters to this family. Say why it was chosen."),
G("Burial at Sea","Rare and worth having ready","8 min",
 ["Name","Scripture","The committal to the deep","Prayer","Silence"],
 ["Psalm 107:23-31","Revelation 20:13"],
 "Those who go down to the sea in ships. Read Psalm 107 and let it carry the weight."),
G("A Columbarium or Niche","Interment in a wall","6 min",
 ["Name","Scripture","The committal","Prayer"],
 ["Ecclesiastes 12:7","John 14:2"],
 "In my Father's house are many rooms. The image is close enough to use."),
G("A Family Plot","Where others are already buried","7 min",
 ["Name","Name those already there","Scripture","The committal","Prayer over the generations"],
 ["Genesis 49:29-31","Hebrews 11:13"],
 "Naming the others buried here turns a plot into a story."),
G("An Unmarked or Pauper's Grave","Dignity without resources","7 min",
 ["Name, deliberately and repeatedly","Scripture","The committal","Prayer"],
 ["Psalm 139:16","Isaiah 43:1","Luke 16:22"],
 "No stone will carry this name. Say it enough times that the ground remembers."),
G("A Green or Natural Burial","No vault, no embalming","7 min",
 ["Name","Scripture on dust and creation","The committal","Prayer"],
 ["Genesis 2:7","Genesis 3:19","Psalm 104"],
 "The theology of dust fits this burial better than any other."),
G("A Grave Beside a Spouse","Reuniting a plot","7 min",
 ["Name both","The years apart","Scripture","The committal","Prayer"],
 ["Ecclesiastes 4:9-12","Romans 8:38-39"],
 "Name the one already here and how long they waited."),
# --- Logistics variants ---
G("Winter Graveside","Cold, ice and short","4 min",
 ["Gather fast","One verse","The committal","Amen"],
 ["Psalm 23:4"],
 "Cold makes people stop listening at four minutes. Finish before that."),
G("Rain","Umbrellas and noise","4 min",
 ["Project or step closer","One verse","The committal","Amen"],
 ["Isaiah 43:2"],
 "Rain eats your voice. Step in, speak up, finish early."),
G("Extreme Heat","Elderly mourners standing","4 min",
 ["Invite people to sit","One verse","The committal","Amen"],
 ["Psalm 121:5-6"],
 "Someone here will faint if this runs long. Give permission to sit and be brief."),
G("A Very Large Crowd","Hundreds outdoors","8 min",
 ["Use the sound system or project","Name","Scripture","The committal","Benediction"],
 ["Psalm 90:1-2","Revelation 7:9"],
 "Face the family, project to the back. Both, at once."),
G("A Distant or Difficult Site","Steep, muddy or remote","6 min",
 ["Check access for the frail before arriving","Name","Scripture","The committal","Prayer"],
 ["Psalm 121:1-2"],
 "Someone with a walker is coming. Walk the ground first."),
G("When the Family Fills the Grave","Participation at the graveside","9 min",
 ["Explain what will happen","The committal","Invite the first handful","Stay through the silence","Prayer to close"],
 ["Genesis 3:19","Ecclesiastes 3:1-4"],
 "The sound of soil on a casket is the hardest sound there is. Do not rush the family through it."),
# --- Additional ---
G("A Graveside for Someone Outside the Faith","Integrity and love together","7 min",
 ["Name","Speak truthfully about the person","Scripture about God's character, not their destiny","The committal","Prayer for the family"],
 ["Genesis 18:25","Psalm 145:8-9"],
 "Speak about God's character rather than making claims about a soul you cannot see."),
G("A Graveside You Were Called Into Late","You never met them","7 min",
 ["Say so honestly and briefly","Ask the family for one word about them","Scripture","The committal","Prayer"],
 ["Psalm 23","Romans 8:38-39"],
 "Do not pretend you knew them. Ask the family for one sentence in the car and use it."),
G("A Second Graveside for the Same Family","Within a year","8 min",
 ["Name both losses","Acknowledge the weight","Scripture","The committal","Prayer"],
 ["Psalm 42:7","Lamentations 3:19-24"],
 "This family has stood here before. Say that you remember."),
G("The Last Words Before You Walk Away","How to end anything","2 min",
 ["A blessing over the family","One line","Silence","Stay"],
 ["Numbers 6:24-26"],
 "The Lord bless you and keep you. Then stop talking and do not leave."),
]

# ===== WEDDING & FUNERAL INTELLIGENCE =====
WFI_THESIS = ("A pastor has forty-eight hours, a family he may not know, and a room where half the people have no "
 "category for what is happening. Intelligence is asking the right questions fast enough that the service fits "
 "this family rather than the last one.")

WFI_FLOW = [
 ["01","Intake","The first phone call. Fifteen questions that determine everything else, asked while the family is still in shock and answering plainly."],
 ["02","Situation profile","Type of death or wedding, family shape, faith of the family, the room you will face, and the constraints."],
 ["03","The gap","What this family needs that a standard service will not give them. This is the whole product."],
 ["04","Service assembly","The right category, the right entries, the right tools, the right add-ins, generated against the profile."],
 ["05","The family conversation","One meeting with the questions written out. Most pastors improvise this and lose material they cannot recover."],
 ["06","Delivery and follow-up","The service, then the follow-up schedule that begins the same week."],
]

WFI_INTAKE_F = [
 ["Who died and what did they go by","The legal name and the name the family uses are often different. Get both."],
 ["How did they die","Asked plainly. The answer changes the entire category."],
 ["Was it expected","Sudden and expected are different services."],
 ["Who is the primary contact","And who is actually deciding, which may not be the same person."],
 ["Who is in the immediate family","Names, relationships, ages of any children."],
 ["Is there anyone estranged","Ask directly. It will surface at the service if it does not surface now."],
 ["Was this person a person of faith","Asked without pressure and answered honestly."],
 ["Is the family churched","This determines how much you explain."],
 ["Burial or cremation","And when, relative to the service."],
 ["Who else is speaking","And do they know how long they have."],
 ["Is there music they wanted","Including secular music, which is fine."],
 ["Is there a text they wanted","Or one that meant something to them."],
 ["What do you most want people to know about them","The single most useful question on this list."],
 ["What are you most worried about","Surfaces the real problem in one sentence."],
 ["Is there anything I should not say","Ask this. Always."],
]

WFI_INTAKE_W = [
 ["Both full names, and what they go by","Pronunciation checked out loud."],
 ["How did you meet","The story you will use."],
 ["Is this a first marriage for both","Changes the ceremony and the premarital."],
 ["Are there children","From this relationship or a previous one, and will they participate."],
 ["Who is giving a blessing","And are both sets of parents in agreement."],
 ["Is anyone estranged","Seating and honouring depend on the answer."],
 ["Do you both share a faith","Answered honestly, without pressure."],
 ["Have you attended a wedding you loved","Tells you their taste faster than any question about preferences."],
 ["Traditional or written vows","Or both."],
 ["Any symbols","Unity candle, cord, communion, foot washing."],
 ["How long do you want the ceremony","Most couples say twenty and mean fifteen."],
 ["Indoors or out","And what the weather plan is."],
 ["Who else is participating","Readers, musicians, the wedding party."],
 ["What are you most nervous about","Usually a family member, and usually worth knowing."],
 ["Is there anything I should not say","Ask this at a wedding too."],
]

WFI_GAPS = [
 ["The family nobody prepared","No funeral plans, no wishes written, deciding everything in two days. Give them fewer choices, not more."],
 ["The unchurched room","Explain everything, assume nothing, and never use an insider word without defining it."],
 ["The divided family","Two households, two stories, and a service that has to honour both. Agree the seating before the day."],
 ["The person you never met","Ask the family three questions in the car and use their words rather than generic ones."],
 ["The complicated life","Honesty without a eulogy that becomes fiction. Say what was true and what was hard, briefly."],
 ["The room with children in it","Speak to them directly at least once. They will remember it for decades."],
 ["The competing officiant","Another minister, a celebrant or a family member with a part. Agree the order in advance."],
 ["The very short timeline","Twelve hours instead of forty-eight. Cut to the intake questions and one text."],
]

WFI_FOLLOW = [
 ["Day 2","The service","Deliver it. Stay after."],
 ["Day 14","The first call","When the casseroles stop. The call that makes the difference."],
 ["Month 3","The check-in","A coffee, not a call. Grief is at its loneliest here."],
 ["Month 6","The invitation","To a grief group, or just to something."],
 ["Month 11","The warning","Put the anniversary in your calendar now, before you forget it."],
 ["Year 1","The anniversary","Nobody else will remember. The family will remember that you did."],
]
