# -*- coding: utf-8 -*-

ILL_THESIS = ("Most pastors do not have an illustration problem. They have a retrieval problem. The stories are "
 "already in their life, their archive and their congregation &mdash; and there has never been a system for "
 "getting them out. Buying somebody else's illustrations is the least effective option available and it is the "
 "only one anyone sells.")

METHODS = [
 ["Prompting","Questions that surface what is already there",
  "The fastest method and the least used. A well-built question pulls an illustration out of a pastor's own memory in under a minute. This is not creativity, it is retrieval.",
  ["When did you last feel this way yourself?","What is the most ordinary version of this idea?",
   "Who in your life is the picture of this?","What did you believe about this at twenty that you do not now?",
   "What object in your house explains this?","What is the first time you understood this?",
   "What would a child compare this to?","Where have you seen this go badly?"],
  "Under a minute per illustration. Works on any topic, any time, no archive required."],
 ["Mining","The pastor's own archive and life",
  "Thirty years of preaching contains hundreds of illustrations that were used once and forgotten. Nobody else has access to this material and nobody else is asking for it. This is the only method a competitor cannot copy.",
  ["Every sermon indexed and every illustration extracted","Tagged by topic, emotion, passage and audience",
   "Flagged when last used and to whom","His own family stories, told once and lost",
   "Stories from his first church that his current one has never heard","Illustrations that landed and illustrations that died",
   "The ones he has overused without noticing","The ones he has never reused and should"],
  "Requires the archive. This is the Pastor's Library Project doing its work."],
 ["Creating","Constructing one that does not exist yet",
  "When nothing in memory or the archive fits, build one. This is a craft with rules rather than a gift some people have.",
  ["Start with the point, not the story","Name the abstract idea in one sentence",
   "Ask what physical thing behaves the same way","Test it against the theology before the audience",
   "Add one sensory detail and cut two adjectives","Make the specific carry the general",
   "Find where the analogy breaks and say so","Keep it under ninety seconds"],
  "Ten to fifteen minutes per illustration once the method is learned."],
 ["Coaching","Helping somebody else find theirs",
  "A staff of eight with an illustration method produces forty times what one pastor does. This is the multiplication step and almost nobody teaches it.",
  ["Teach the prompting questions to the whole team","Every teacher keeps their own bank",
   "A shared bank with attribution and last-used dates","Review what landed after every service",
   "Train small group hosts to prompt rather than supply","Students and volunteers learn it too",
   "The congregation becomes a source, with permission","Nobody borrows without saying so"],
  "One training session, then a rhythm. The compounding method."],
]

STORY_FINDER = {
 "line":"The Story Finder — the congregation as the source nobody uses.",
 "body":("The best illustration in any room on any Sunday is sitting in row twelve. It is recent, it is local, "
  "the people around them know it is true, and no library on earth contains it. The devotional reply question "
  "is what harvests it, and the forward-looking version gathers illustrations for a sermon that has not been "
  "preached yet."),
 "steps":[
  ["Ask three weeks ahead","Have you ever lived this out? Asked before the message, not after."],
  ["Read the replies","A named person, fifteen minutes a week. Most are unusable and that is fine."],
  ["Ask permission separately","Three options — full name, first name only, anonymous. Never assume."],
  ["Use three on Sunday","The congregation hears itself and the next twenty replies arrive."],
  ["Tag the rest","By theme, passage and campaign. Next year's sermon already has stories attached."],
 ],
}

SOURCES = [
 ["Biblical","The Bible illustrating itself",
  "The most underused source in preaching. Scripture is full of narrative that explains other Scripture, and it needs no permission, no attribution and no apology.",
  ["Old Testament narrative explaining a New Testament idea","Parables as illustrations for non-parable texts",
   "The lives of minor characters","Kings and their decisions","Prophetic sign-acts",
   "The wilderness as a picture of any hard season","Exile and return","The tabernacle and temple",
   "Feasts and festivals","Genealogies and what they carry","Miracles as pictures of larger truths",
   "The failures of the patriarchs"]],
 ["Historical","What actually happened",
  "Verifiable, weighty, and free of permission problems. The risk is getting it wrong, so check before you use it.",
  ["Church history and the martyrs","Reformers and revivalists","Missionary biography","Wartime accounts",
   "Exploration and expedition","Medicine and its breakthroughs","Civil rights and justice movements",
   "Engineering feats and failures","Shipwrecks and rescues","Famines and relief",
   "Inventions and the people behind them","Ordinary people in extraordinary moments"]],
 ["Nature & Science","How the world behaves",
  "Universally accessible and rarely dated. The best of these carry theology without forcing it.",
  ["Seeds, roots and growth","Pruning and grafting","Migration","Symbiosis and dependence",
   "Erosion and slow change","Storms and weather systems","Astronomy and scale","Light and refraction",
   "The immune system","Fault lines and pressure","Tides and cycles","Ecosystems and interdependence"]],
 ["Everyday Life","The ordinary made visible",
  "The most effective category and the least impressive-sounding. A congregation trusts an illustration about a kitchen more than one about a mountaineer.",
  ["Kitchens and cooking","Cars breaking down","Home repair and things left undone","Laundry and the endless",
   "Traffic and waiting","Queues","Neighbours","Losing keys","Moving house","Packing and unpacking",
   "Bills and post","Cleaning what nobody sees"]],
 ["Work & Trade","Where people spend their lives",
  "Every trade has a picture in it, and the person in that trade will never forget the sermon that used theirs.",
  ["Construction and foundations","Farming and harvest","Fishing and nets","Medicine and diagnosis",
   "Teaching and the slow student","Law and evidence","Accounting and reconciliation","Sales and rejection",
   "Retail and customers","Trucking and the long haul","Nursing and night shifts","Engineering and tolerance"]],
 ["Family & Childhood","The room everyone has been in",
  "Highest emotional access, highest risk of sentimentality. One specific detail rescues it; three break it.",
  ["First steps and first words","Teaching a child to ride","Bedtime","The empty nest","Sibling rivalry",
   "A parent's hands","Family meals","Holidays and traditions","Coming home","Grandparents",
   "The photograph nobody threw away","Waiting up for a teenager"]],
 ["Sport & Competition","Effort, failure and finishing",
  "Effective with half a room and lost on the other half. Explain the sport in one sentence and it works for everyone.",
  ["The last mile","Training in the off-season","The substitute who never plays","Coaching",
   "Losing well","The team that overachieved","Injury and comeback","The rules nobody likes",
   "Marathon versus sprint","The bench","Practice nobody sees","Retirement from a sport"]],
 ["Journey & Travel","Getting from here to there",
  "The oldest metaphor in Scripture and still working. Watch for overuse.",
  ["Maps and getting lost","The wrong turn","Roadworks and detours","Travelling light",
   "Arriving late","The long drive","Border crossings","Airports and waiting",
   "Coming home after a long time","A journey taken alone","Companions on a road","The last mile"]],
 ["Building & Craft","Making something that lasts",
  "Foundations, materials, tolerance, finish. Scripture uses this constantly and so should preaching.",
  ["Foundations and what is buried","Load-bearing walls","Measuring twice","Cheap materials",
   "The tolerance that matters","Sanding and finishing","Repairing versus replacing","Restoration",
   "Blueprints and reality","The unfinished project","Craftsmanship nobody sees","Tools that fit the hand"]],
 ["Food & Table","Hunger, feeding, hospitality",
  "Every culture, every age, every room. Jesus used it more than almost anything else.",
  ["Bread and the making of it","Yeast and slow change","Salt","Feasts","An empty chair at a table",
   "Recipes handed down","Feeding a crowd","Hunger","Sharing what is not enough",
   "The meal after a funeral","Cooking for someone who cannot","The table nobody was turned away from"]],
 ["Money & Commerce","Debt, value and exchange",
  "Uncomfortable, memorable and biblical. Handle with care in a mixed-income room.",
  ["Debt and what it does","Interest compounding","The bargain that was not","Value and price",
   "Insurance","Inheritance","The receipt","Bartering","Investment and patience",
   "Bankruptcy and starting over","The gift with no invoice","What you would not sell"]],
 ["Medicine & Healing","Diagnosis, treatment, recovery",
  "Powerful and risky. Somebody in the room is currently ill; never use their situation carelessly.",
  ["Diagnosis and denial","The second opinion","Chronic versus acute","Physiotherapy and the slow work",
   "Anaesthetic","Scar tissue","Transplants","Triage","Bedside manner",
   "The waiting room","Remission","Learning to walk again"]],
 ["Law & Justice","Guilt, evidence and verdict",
  "Central to the gospel and often skipped. Keep the legal detail correct.",
  ["The courtroom","Evidence and testimony","The advocate","Pardon versus acquittal",
   "Sentencing","Restitution","The statute of limitations","Contracts",
   "Witnesses","Appeal","The judge who paid the fine","Records expunged"]],
 ["Music & Art","Harmony, practice and beauty",
  "Works well with creative congregations and needs translating for others.",
  ["Practising scales","An orchestra and its parts","Tuning","Dissonance resolving",
   "Rehearsal versus performance","The conductor","Restoring a painting","A rough sketch",
   "The unfinished symphony","Learning an instrument as an adult","Silence in music","Improvisation"]],
 ["Technology","The world people actually live in",
  "Dates fastest of any category. Check whether it will still make sense in five years.",
  ["Updates and what breaks","Backups nobody made","Passwords","The algorithm",
   "Notifications","Bandwidth","Battery life","Autocorrect",
   "Cloud storage","The device that outlived its support","Debugging","Signal and noise"]],
 ["Animals","Instinct, loyalty and behaviour",
  "Accessible to every age. Biblical and often gentle enough for a hard subject.",
  ["Sheep and shepherds","Dogs and loyalty","Migration and instinct","Herding",
   "The lost one","Predators and prey","Hibernation","Nest-building",
   "Working animals","The runt","Pack behaviour","Animals that mate for life"]],
 ["Weather & Seasons","Change you cannot control",
  "Universal and gentle. Good for grief, waiting and slow work.",
  ["Winter and what is happening underground","The first thaw","Drought","Floods",
   "The storm that passed","Fog","Frost and hardening","Long summers",
   "Harvest weather","The forecast that was wrong","Seasons out of order","Waiting for rain"]],
 ["War & Conflict","Cost, courage and aftermath",
  "Weighty and easily misused. Never trivialise and never use a recent conflict casually.",
  ["The forward position","Supply lines","Reconnaissance","Surrender",
   "The armistice","Coming home","Field medicine","The map room",
   "Holding ground","The one who went back","Occupation","Rebuilding after"]],
 ["Death & Loss","The universal",
  "Handle with the awareness that someone in the room is inside this today.",
  ["The empty chair","Sorting their things","The first Christmas","Anniversaries",
   "A voice on an old recording","Handwriting","The last conversation","Waiting rooms",
   "The funeral of a stranger","What people say and should not","Grief that ambushes","Remembering well"]],
 ["Light & Dark","The oldest picture there is",
  "Biblical, universal, and easy to make trite. Specificity is the whole defence.",
  ["A single candle","Dawn","Power cuts","Adjusting to the dark",
   "Lighthouses","The tunnel","Shadows and their sources","Night shift",
   "Stars only visible far from a city","Sunrise after a bad night","Blindness and adjustment","A lit window"]],
]

CRAFT = [
 ["Specific beats general","A dog is nothing. A three-legged beagle called Duke is an illustration. The detail does the work, not the category."],
 ["One sensory detail, not three","The smell of the room, or the sound of the door, or the cold of the handle. Choose one. Three is a novel."],
 ["Under ninety seconds","An illustration longer than the point it illustrates has become the sermon. Time it out loud."],
 ["Name where it breaks","Every analogy fails somewhere. Say where before somebody in the room finds it and stops listening."],
 ["Never the hero","A pastor who is the hero of his own illustration has spent credibility he will need later."],
 ["Check before you use it","A historical illustration that turns out to be false costs more than it ever gained."],
 ["Attribute or do not use","Borrowed stories told as your own end ministries. Say where it came from in five words."],
 ["Land on the point, not the story","The last sentence should be the truth, not the punchline. People remember the last thing."],
 ["Cut the setup","Most illustrations start thirty seconds before they need to. Begin at the moment of tension."],
 ["Say it out loud first","An illustration that reads well and speaks badly is common. Test every one aloud."],
]

TECHNIQUES = [
 ["The analogy ladder","Take the abstract idea and step down one rung at a time until it touches something physical. Grace becomes forgiveness becomes a debt cancelled becomes a torn-up invoice on a kitchen table."],
 ["The reversal","Illustrate what the thing is not, then turn. Show a room the counterfeit and the real thing becomes visible without being described."],
 ["The zoom","Start impossibly wide or impossibly close, then move. A galaxy, then a single cell. A hospital, then one hand on a rail."],
 ["The unexpected pairing","Two things nobody puts together. Grief and a supermarket. Holiness and a woodworking tolerance. The surprise is what makes it memorable."],
 ["The withheld ending","Tell most of it, make the point, then finish the story. The room stays with you through the teaching to get the ending."],
 ["The ordinary object","Hold something up. A key, a receipt, a photograph, a stone. Physical objects survive in memory long after words."],
 ["The overheard","Something someone actually said, quoted exactly. Real speech has a texture nobody can write."],
 ["The number that lands","One statistic, made human. Not forty per cent — four people in this row."],
 ["The recurring image","One picture introduced in week one and returned to in every week of a series. By week six the image carries the whole argument."],
 ["The local","Something in this town that everybody in the room has driven past. Nothing beats it and no library contains it."],
]

TOPICS = ["Grace","Forgiveness","Faith","Doubt","Hope","Love","Prayer","Suffering","Joy","Patience",
 "Money","Generosity","Work","Rest","Marriage","Parenting","Friendship","Loneliness","Anxiety","Grief",
 "Identity","Purpose","Calling","Obedience","Repentance","Humility","Pride","Anger","Fear","Courage",
 "Community","Serving","Leadership","Discipline","Change","Waiting","Endurance","Failure","Success","Legacy",
 "Justice","Mercy","Truth","Integrity","Temptation","Freedom","Salvation","The Cross","Resurrection","Heaven"]

BANK_SPEC = [
 ["Tagged by topic","Fifty topics minimum, matched to the sermon library's own taxonomy."],
 ["Tagged by source","Which of the twenty source categories it came from, so a preacher can avoid using three farming illustrations in one message."],
 ["Tagged by emotion","What it makes a room feel. The most useful tag and the one nobody builds."],
 ["Tagged by passage","So next year's sermon on the same text has stories already attached."],
 ["Last used and to whom","The single most important field. An illustration used eighteen months ago at this church is fresh; one used in March is not."],
 ["Length in seconds","Timed, not estimated. A preacher building a message needs to know if this is forty seconds or two minutes."],
 ["Permission status","Own story, congregational with permission, public domain, attributed, or do not use."],
 ["Landed or died","Marked after the service. Six months of this is worth more than any purchased library."],
]
