# -*- coding: utf-8 -*-
# Master Illustration Library
# Each entry: name, frame, open[3], close[3], humor[2], cross[4], prompt[4]

def E(name, frame, op, cl, hu, cr, pr):
    return {"n":name,"f":frame,"o":op,"c":cl,"h":hu,"x":cr,"p":pr}

THEMES = [
E("Grace and Forgiveness",
"Grace is only felt when the debt was real and the one who covered it had a genuine choice not to.",
[("The Bill Someone Else Paid","A debt you fully owed, covered by someone with no obligation to you. Works because the amount has to be specific. Avoid the version where you partly deserved it."),
 ("The Phone Call You Dreaded","Rehearsing an apology the whole drive over and being interrupted before you finish the first sentence."),
 ("What You Assumed Would Happen","Bracing for a consequence that never came, and the strange disorientation of being let off."),],
[("Still Carrying the Receipt","Someone who was genuinely forgiven and kept apologizing for years. Grace received is different from grace believed."),
 ("The Debt You Are Still Collecting","Turning it outward &mdash; who do you have a running tab on."),
 ("The Room Where It Was Torn Up","A physical moment of a record being destroyed. Works best if you can put an object in your hand."),],
[("The Apology Note From Age Seven","A childhood apology you were forced to write, and the gap between the words and the feeling."),
 ("The Grudge You Cannot Remember the Cause Of","Everyone has one. Ask the room if anyone can still name the original offense."),],
[("Luke 15:11-32","The father runs before the speech is finished, which is the whole doctrine in one motion."),
 ("Matthew 18:21-35","The forgiven servant who would not forgive &mdash; grace received without grace transmitted."),
 ("Colossians 2:13-14","The record of debt cancelled, nailed to the cross. A legal image, not an emotional one."),
 ("John 8:1-11","Neither do I condemn you. Grace and instruction in the same breath, neither cancelling the other."),],
["When did someone forgive you something specific, and how quickly did it happen?",
 "What did you assume was coming instead? Describe the version you rehearsed.",
 "Who else was in the room, and what did their face do?",
 "What did you do in the days after &mdash; did you actually believe it, or keep waiting for the bill?"]),

E("Anxiety and Worry",
"Worry is not a failure of faith so much as a failure of location. The anxious mind is always somewhere it cannot act.",
[("Three in the Morning","The particular quality of 2 a.m. thinking, and how differently the same problem reads at nine."),
 ("The List You Keep Rewriting","A worry you have solved on paper eleven times and never once in reality."),
 ("Packing for the Trip That Never Happened","Preparing exhaustively for a disaster that did not come. What did the preparation cost?"),],
[("Today Has Enough","Landing on Matthew 6:34 as a practice rather than a platitude &mdash; what one day's worth of trouble actually looks like."),
 ("The Thing You Survived","Naming a past fear that arrived and was survivable. Evidence over reassurance."),
 ("Hand It Over, Out Loud","A physical transfer &mdash; written, spoken, given to someone. Anxiety loosens when it leaves the head."),],
[("The Worry You Outsourced","Assigning your anxiety to a spouse or friend and watching them not carry it at all."),
 ("Search History at Midnight","Everyone has diagnosed themselves with something terrible at 1 a.m. Nobody has been right."),],
[("Matthew 6:25-34","Look at the birds. Jesus argues from observation rather than from feeling."),
 ("Philippians 4:6-7","Anxious for nothing, with a specific replacement action rather than a prohibition."),
 ("1 Kings 19:1-9","Elijah gets food and sleep before he gets a word from God. Sometimes the answer is a nap."),
 ("Psalm 131","A weaned child with its mother &mdash; the picture of a mind that has stopped grasping."),],
["What is the specific 2 a.m. thought &mdash; not the category, the sentence?",
 "Name a fear you had five years ago that arrived. What actually happened?",
 "Who has seen you at your most anxious, and what did they do that helped?",
 "What is the smallest thing you could actually do today about it?"]),

E("Money and Generosity",
"Money illustrations fail when the amounts are abstract. Name a real number or do not tell the story.",
[("The First Time You Gave Something That Hurt","The specific amount and what you had to not buy. Vagueness kills this one."),
 ("What You Learned From Watching Someone Give","A parent, a stranger, a widow. Formation by observation."),
 ("Where the Money Actually Went Last Month","An honest ledger read aloud. Uncomfortable and clarifying."),],
[("The Open Hand","A physical posture &mdash; closed fist, open palm &mdash; held long enough that the room feels it."),
 ("Two Small Coins","Proportion over amount. The widow gave less and more at the same time."),
 ("What You Would Do With Ten Years of Margin","Casting a vision forward rather than convicting backward."),],
[("The Subscription You Forgot About","Everyone is paying for something they stopped using in 2019."),
 ("The Budget You Made in January","Held up against the actual bank statement. Universally funny and mildly convicting."),],
[("Mark 12:41-44","The widow's offering &mdash; Jesus measures what was kept, not what was given."),
 ("Luke 12:13-21","The barn-builder. Not condemned for wealth but for the pronoun count in his own speech."),
 ("2 Corinthians 9:6-11","Sowing and reaping, cheerfully rather than reluctantly. Motive as the whole subject."),
 ("1 Timothy 6:17-19","Instruction to the rich that is neither shaming nor flattering. Rare and worth preaching."),],
["What is the largest gift you have given, and what did you give up to give it?",
 "Who taught you what money means, and did they teach it on purpose?",
 "When did generosity cost you something you actually wanted?",
 "What number would you be uncomfortable saying out loud from the platform, and why?"]),

E("Suffering and Grief",
"The most common failure here is resolving too fast. Let the story sit in the hard part longer than is comfortable.",
[("The Phone Call","The moment the news arrived, described in ordinary detail &mdash; where you were standing, what you were holding."),
 ("The Casserole Nobody Ate","The specific, awkward kindness of people who did not know what to do."),
 ("What People Said That Did Not Help","Naming the well-meant sentences that landed badly. The room will exhale."),],
[("He Wept First","Jesus grieves before he raises. Order matters and the order is pastoral."),
 ("The Scar That Stayed","Healing that does not erase history. Works if you can name a visible one."),
 ("Who Sat Down","The person who came and said nothing. Presence as the whole answer."),],
[("The Funeral Detail Nobody Planned","Grief and absurdity live together. Handle only with permission and only from your own family."),
 ("The Thing They Would Have Found Funny","Honoring someone by laughing at what they laughed at. Gentle, not deflecting."),],
[("John 11:32-36","Jesus wept, at a funeral where he knew the outcome. Grief is not a lack of faith."),
 ("Psalm 88","The lament that never resolves. The Bible includes a psalm with no happy ending on purpose."),
 ("Job 2:11-13","Seven days of silence. The friends were at their best before they opened their mouths."),
 ("2 Corinthians 1:3-7","Comfort received becomes comfort given. Grief as an eventual credential."),],
["What did you lose, and how long ago &mdash; be honest about whether you are ready to tell it.",
 "What did someone do for you that actually helped? Be specific.",
 "What did you believe about God then that you no longer believe, or believe differently?",
 "Who in this congregation is where you were? Preach to them, not about them."]),

E("Identity and Worth",
"Identity illustrations work when the false version is named as precisely as the true one.",
[("The Thing You Introduce Yourself As","What comes after your name at a party, and what that reveals."),
 ("The Grade That Defined a Decade","One evaluation absorbed as a verdict on your whole self."),
 ("Whose Voice Is in Your Head","Naming the specific person whose approval still runs your decisions."),],
[("Named Before You Performed","Jesus hears this is my Son before a single miracle. Approval precedes achievement."),
 ("The Resume You Would Not Read at Your Funeral","Separating what you do from what you are."),
 ("Say the True Sentence Out Loud","Have the room speak an identity statement together. Physical and memorable."),],
[("Your Childhood Nickname","Every room has someone whose family still calls them something humiliating."),
 ("The Bio You Rewrote Eleven Times","The comedy of self-presentation in a hundred and sixty characters."),],
[("Mark 1:9-11","The Father's approval spoken before the ministry begins. Nothing had been accomplished yet."),
 ("1 Samuel 16:1-13","Man looks at the outward appearance. Even the prophet got it wrong seven times."),
 ("Ephesians 2:8-10","Saved by grace, then called his handiwork. Standing first, purpose second."),
 ("1 John 3:1","Called children of God, and that is what we are. The clause after the comma is the sermon."),],
["What do you say when someone asks what you do, and what does the answer protect?",
 "Whose approval do you still catch yourself working for?",
 "When did someone see something in you before you had earned it?",
 "What would you have to stop doing if you actually believed you were already accepted?"]),

E("Doubt and Faith",
"The best doubt illustrations come from the preacher's own unresolved questions, not from a story where doubt got tidily fixed.",
[("The Question You Stopped Asking","A doubt you buried rather than answered, and what burying it cost."),
 ("The Prayer That Was Not Answered","Naming it plainly, without a redemptive bow on it."),
 ("The Person Whose Faith Broke","Someone you watched walk away, and what you understood about it later."),],
[("Help My Unbelief","The father's honest prayer in Mark 9. Belief and doubt in the same sentence, and Jesus accepts it."),
 ("Come and Touch It","Thomas is given exactly what he asked for. Doubt is not punished here."),
 ("Bring the Question Here","An explicit invitation for people to ask the church rather than leave over it."),],
[("The Sunday School Answer","Everyone knows Jesus is always the right answer, which is why nobody is listening to the question."),
 ("Your Confident Wrong Opinion","A thing you argued passionately for at nineteen and now find embarrassing."),],
[("Mark 9:14-27","I do believe, help my unbelief. The most honest prayer in Scripture."),
 ("John 20:24-29","Thomas gets the evidence. Then a blessing for everyone who will not."),
 ("Psalm 73","Asaph nearly loses his faith over the prosperity of the wicked, and says so out loud."),
 ("Habakkuk 1:1-4","A prophet filing a formal complaint against God. It is in the canon."),],
["What do you still not have an answer for? Say the actual question.",
 "When did you nearly walk away, and what kept you?",
 "Who let you ask a hard question without flinching, and what did that do for you?",
 "What are you pretending to be more certain about than you are?"]),

E("Marriage and Family",
"Never tell a story about your spouse or children that you have not read to them first. That is the rule, and it is not optional.",
[("The Fight About the Dishwasher","The small conflict that was never about the small thing."),
 ("What Your Parents Did Without Explaining","A household habit you only understood as an adult."),
 ("The Text You Almost Sent","Restraint as a marriage skill, described in one specific moment."),],
[("Go First","Repair as a decision one person makes without waiting for the other."),
 ("The Blessing Spoken Out Loud","Words said over a child that were still being carried at fifty."),
 ("Set the Table Tonight","A specific, small, immediate household action rather than a principle."),],
[("The Family Group Chat","Universally recognizable, and nobody has to be the villain."),
 ("How You Load the Dishwasher","Two people, two correct methods, one marriage."),],
[("Ephesians 5:21-33","Mutual submission first, which is the verse most often skipped on the way to the others."),
 ("Deuteronomy 6:4-9","Faith taught in the ordinary movements of a day, not in a scheduled program."),
 ("Genesis 33:1-11","Esau runs to meet Jacob. Family reconciliation with twenty years of silence behind it."),
 ("Luke 15:25-32","The older brother. The family story most congregations have never had preached to them."),],
["What did your parents do that you swore you would never do, and now do?",
 "What is the recurring argument in your house, and what is it actually about?",
 "When did someone in your family go first, and what did it cost them?",
 "Have you read this story to the person it is about?"]),

E("Purpose and Calling",
"Calling illustrations fail when they only feature dramatic redirection. Most calling is discovered by staying, not by leaving.",
[("The Job You Took for the Money","And what it taught you that nothing else would have."),
 ("What You Cannot Stop Noticing","The problem that bothers you more than it bothers other people."),
 ("The Detour That Was the Road","A season you considered wasted that turned out to be the training."),],
[("Bloom, Then Move","Contentment and ambition held together rather than opposed."),
 ("Who Is Waiting on Your Yes","Calling framed by the people served rather than the fulfillment gained."),
 ("Name the Next Faithful Step","Not the whole map. The next step, written down before leaving."),],
[("Your Childhood Career Plan","Everyone wanted to be something absurd. Ask for a show of hands."),
 ("The Major You Have Never Used","Half the room. Instant recognition, no shame in it."),],
[("Exodus 3:1-12","Moses argues with the call for a full chapter. Reluctance is normal and biblical."),
 ("Esther 4:12-16","For such a time as this. Position as assignment rather than reward."),
 ("Colossians 3:23-24","Whatever you do, work at it. Every field dignified, no hierarchy of callings."),
 ("Acts 18:1-4","Paul makes tents. The apostle had a day job and it was not a failure."),],
["What problem bothers you more than it seems to bother other people?",
 "What season did you think was wasted, and what did it actually build?",
 "Who told you what you were good at before you believed it?",
 "If nothing changed about your job, what could still change about your work?"]),

E("Prayer",
"The most useful prayer illustration is a specific prayer you actually prayed, including the ones that were not answered.",
[("The Prayer You Prayed in the Car","Location matters. Real prayer usually happens somewhere undignified."),
 ("The One-Word Prayer","A moment when you had nothing else. Help. Please. Why."),
 ("The Prayer Someone Prayed Over You","Words spoken for you that you still carry."),],
[("Teach Us to Pray","The disciples watched him do everything and asked to learn one thing."),
 ("Pray It Now, Out Loud","Stop preaching and do it. Circles of three, sixty seconds, right now."),
 ("Write It Down and Date It","Recording a prayer so the answer can be recognized when it comes."),],
[("The Prayer at the Restaurant","The volume calculation everyone performs before praying in public."),
 ("Praying for a Parking Space","We have all done it. We are all slightly ashamed. It sometimes works."),],
[("Luke 11:1-13","Teach us to pray, followed by shameless persistence at midnight."),
 ("Matthew 6:5-13","Go into your room. Prayer with an audience of one."),
 ("Romans 8:26-27","The Spirit intercedes when you have no words. Permission for inarticulate prayer."),
 ("1 Samuel 1:9-18","Hannah pours out her soul and is mistaken for drunk by the priest."),],
["What is the most desperate prayer you have prayed, and where were you?",
 "What have you asked for repeatedly and not received?",
 "Who prayed for you before you could pray for yourself?",
 "What would change about this week if you prayed first rather than last?"]),

E("Community and Belonging",
"Belonging illustrations land when the loneliness is described honestly before the community arrives.",
[("The Room Where You Knew Nobody","The specific physical discomfort of walking in alone."),
 ("Who Would Notice","A week when you could have disappeared and no one would have called."),
 ("The Invitation You Almost Declined","The threshold moment, and what nearly stopped you."),],
[("They Devoted Themselves","Acts 2 as a description of an actual week, not a slogan."),
 ("Two Are Better Than One","Pity the one who falls and has no one. The warning, not the sentiment."),
 ("Turn and Meet One Person","Do it in the room. Sixty seconds, name and one true sentence."),],
[("The Church Lobby Handshake","The three-minute window everyone has strong feelings about."),
 ("Where You Sit Every Week","The unassigned assigned seating of every congregation on earth."),],
[("Acts 2:42-47","Four devotions held together, plus meals and property. Community with economics attached."),
 ("Ecclesiastes 4:9-12","Two are better than one, and the cord of three strands. Unsentimental reasoning."),
 ("Mark 2:1-5","Four friends and a roof. Faith that carries someone who cannot get there alone."),
 ("Romans 12:3-8","Different gifts, one body. Nobody is redundant and nobody is self-sufficient."),],
["When have you been the only one in a room, and what did that feel like physically?",
 "Who noticed you before you were interesting to them?",
 "What group has actually changed you, and what did it require?",
 "Who would call if you stopped showing up?"]),

E("Death and Hope",
"Never resolve death quickly from a platform. The people who have buried someone can tell instantly whether you have.",
[("The Last Conversation","What you said, or did not get to say. Ordinary words made enormous."),
 ("The Empty Chair at the Table","A holiday after a loss, described without commentary."),
 ("What They Left Behind","An object. A jacket, a recipe card, a voicemail nobody can delete."),],
[("The Last Enemy","Paul calls death an enemy, not a friend or a transition. Christian honesty is a gift."),
 ("He Kept the Scars","A resurrection body that still bore wounds. History not erased."),
 ("Say Their Name","Speak the names of those the church lost this year, out loud, slowly."),],
[("The Thing They Said at the Funeral","Only from your own family, only with permission, and only if it was actually funny."),
 ("The Voicemail You Will Not Delete","Recognizable to almost everyone. Tender rather than comic."),],
[("1 Corinthians 15:50-57","Where is your victory. A taunt only available because of an empty tomb."),
 ("John 11:17-27","I am the resurrection. Said to a grieving woman before anything was fixed."),
 ("Revelation 21:1-5","He will wipe every tear. The specificity of the promise is the comfort."),
 ("Psalm 23:4","Through the valley, not around it. The preposition carries the whole verse."),],
["Who have you buried, and what do you still carry from it?",
 "What do you actually believe happens next &mdash; not the answer you would give, the one you hold?",
 "What did someone say to you in that season that helped?",
 "Whose name should this church say out loud this Sunday?"]),

E("Temptation and Freedom",
"Confession from the platform must be past-tense and processed. Present-tense struggle belongs in a room with three people, not three hundred.",
[("The Thing You Almost Did","A near miss described honestly, without glamour and without a hero ending."),
 ("What It Promised","Temptation is a sales pitch. Name what it claimed it would deliver."),
 ("The Second Look","The moment the decision was actually made, well before the visible one."),],
[("The Way Out Was Already There","1 Corinthians 10:13 as an escape door rather than a guarantee of strength."),
 ("Who Knows","Freedom is downstream of disclosure. Name one person to tell."),
 ("It Owns You Until You Say It","Confession as the moment the grip loosens. Offer a room and a time."),],
[("The Snooze Button","The most universally lost daily battle in the room."),
 ("The Thing in Your Cart You Did Not Buy","Small victories count. Everyone has abandoned a cart at 11 p.m."),],
[("1 Corinthians 10:12-13","A way out provided. Not the absence of temptation but the presence of an exit."),
 ("Genesis 39:6-12","Joseph runs. The spiritual strategy is literally physical relocation."),
 ("James 1:13-15","Desire conceives and gives birth. A sequence, which means it can be interrupted early."),
 ("Matthew 4:1-11","Jesus answers with Scripture three times. Preparation before the moment, not during."),],
["What has had a grip on you that no longer does? Only tell the ones that are finished.",
 "What did it promise, and what did it actually deliver?",
 "Who did you finally tell, and what happened in the twenty minutes after?",
 "What would you need to be true to say this out loud?"]),
]

BOOKS = [
E("Genesis",
"Origins, family dysfunction, and covenant. The book that establishes every theme the rest of Scripture develops.",
[("Everything Was Good First","Genesis 1 before Genesis 3. Most people's theology starts at the fall and it should not."),
 ("The First Question God Asks","Where are you. God asking a question he knows the answer to."),
 ("The Family You Would Not Put on a Brochure","Deception, favoritism, and violence in the founding household of the faith."),],
[("He Made Them Clothes","God's first act after judgment is a covering. Grace in Genesis 3."),
 ("You Intended Harm, God Intended Good","Joseph's sentence, which reframes an entire biography."),
 ("The Wrestling Left a Limp","Jacob is renamed and injured in the same night."),],
[("Naming the Animals","Somebody had to be the one who came up with platypus."),
 ("Noah's Neighbors","A hundred years of building a boat in a dry field. The small talk must have been remarkable."),],
[("Genesis 1:26-28","Image and vocation given together. Identity precedes assignment."),
 ("Genesis 3:8-9","Where are you. The first question, asked by the one who already knows."),
 ("Genesis 22:1-14","The mountain. Obedience with everything at stake and a provision already in the thicket."),
 ("Genesis 50:15-21","Intended for harm, meant for good. Providence read backwards."),],
["Which Genesis family most resembles your own?",
 "Where has God asked you a question he already knew the answer to?",
 "What in your story only makes sense read backwards?",
 "What did you inherit from a generation before you, for better and worse?"]),

E("Exodus",
"Rescue, law, and presence. The template for every deliverance story Scripture tells afterward.",
[("Forty Years on the Back Side of Nowhere","Moses at eighty, tending someone else's sheep. Preparation that looks like waste."),
 ("The Cry That Reached God","Groaning under slavery, and a God who says I have heard."),
 ("Send Someone Else","Moses argues with his own calling for an entire chapter."),],
[("Blood on the Doorframe","Passover as the pattern the whole gospel later fulfills."),
 ("If Your Presence Does Not Go","Moses would rather have God than the promise. The best prayer in the book."),
 ("Remember the Night You Left","Instituting a meal so a people would not forget a rescue."),],
[("The Complaining in the Desert","Freed from slavery on Tuesday, nostalgic for the food by Thursday."),
 ("Aaron's Explanation","I threw the gold in the fire and out came this calf. The worst excuse ever recorded."),],
[("Exodus 3:1-14","The burning bush and the name. God defines himself by being rather than doing."),
 ("Exodus 12:1-13","Passover. Substitution, blood, and a meal that becomes memory."),
 ("Exodus 33:12-18","If your presence does not go with us, do not send us up."),
 ("Exodus 16:1-5","Manna, daily. Enough for one day, on purpose, for forty years."),],
["What season of your life looked like wasted preparation?",
 "What have you argued with God about, and how long did it take?",
 "What has God given you daily that you wanted delivered in bulk?",
 "What rescue in your life needs a meal built around remembering it?"]),

E("Psalms",
"The prayer book of Scripture, including the prayers the modern church is uncomfortable praying out loud.",
[("The Psalm That Does Not Resolve","Psalm 88 ends in darkness. The Bible includes it on purpose."),
 ("How Long, O Lord","The most repeated question in the Psalter and the one we sing least."),
 ("David Talks to Himself","Why are you downcast, O my soul. Preaching to yourself as a discipline."),],
[("Through the Valley","The preposition carries it. Not around, not over."),
 ("Bless the Lord, O My Soul","Gratitude commanded to oneself rather than felt spontaneously."),
 ("Pray One Out Loud","Read a whole psalm as the closing rather than summarizing it."),],
[("The Imprecatory Psalms","There are prayers in this book you would be uncomfortable praying in a small group."),
 ("David's Range","The same author writes the Lord is my shepherd and how long will you hide your face."),],
[("Psalm 23","The most quoted and least examined. Every phrase is a sermon."),
 ("Psalm 51","Confession after the worst chapter of David's life. Specific, not general."),
 ("Psalm 88","Lament with no resolution. Permission for the season you are actually in."),
 ("Psalm 139","Searched and known, and nowhere you can go from his presence."),],
["Which psalm have you actually prayed rather than read?",
 "What have you been afraid to say to God that a psalmist already said?",
 "When have you had to preach to yourself?",
 "Which psalm would your last five years be written in?"]),

E("Proverbs",
"Practical wisdom, best preached in clusters rather than verse by verse, and honestly qualified as probability rather than promise.",
[("The Advice You Ignored","Counsel you received and dismissed, and the price of the dismissal."),
 ("Who Are You Walking With","The company you keep as the strongest predictor of where you end up."),
 ("The Small Decision That Compounded","Proverbs is a book about slopes, not cliffs."),],
[("Trust With All Your Heart","Proverbs 3:5-6 rescued from the graduation card."),
 ("Guard Your Heart","Above all else, because everything flows from it. A watchman image, not a romantic one."),
 ("Choose One Proverb for a Month","A specific, small practice rather than a general appreciation."),],
[("The Contentious Wife Verses","Read them, then acknowledge that Proverbs would have a lot to say about husbands too."),
 ("Answer a Fool According to His Folly","Followed immediately by do not. The book knows exactly what it is doing."),],
[("Proverbs 3:5-8","Trust, lean not, acknowledge. Three verbs and a promise about paths."),
 ("Proverbs 4:23","Guard your heart, for everything you do flows from it."),
 ("Proverbs 13:20","Walk with the wise and become wise. Formation by proximity."),
 ("Proverbs 22:6","Train up a child. Preach it as a probability, not a guarantee, and say why."),],
["What counsel did you ignore, and what did it cost?",
 "Who are the five people you spend the most time with?",
 "What small decision, repeated, has shaped your last decade?",
 "Which proverb do you personally need for the next thirty days?"]),

E("Isaiah",
"Judgment and comfort held together, and the book the New Testament quotes most when it wants to explain Jesus.",
[("Woe Is Me","Isaiah 6. Encountering holiness and immediately understanding your own condition."),
 ("Here Am I, Send Me","Volunteering before knowing the assignment. The assignment is hard."),
 ("The Fast God Chooses","Isaiah 58 dismantles religious performance in one chapter."),],
[("They Will Soar on Wings","Isaiah 40 for the exhausted, preached without turning it into a poster."),
 ("A Shoot From the Stump","Hope rising out of what looked finished."),
 ("He Was Pierced","Isaiah 53 read slowly, without commentary, as the close."),],
[("The Length of the Book","Sixty-six chapters, and most congregations know four of them."),
 ("Isaiah's Object Lessons","The prophets were asked to do genuinely strange things to make a point."),],
[("Isaiah 6:1-8","The throne, the coal, and the volunteer. Holiness, cleansing, commission."),
 ("Isaiah 40:27-31","Those who hope in the Lord. Written to people in exile, not to people on a run."),
 ("Isaiah 53","The suffering servant. The chapter that makes the crucifixion legible."),
 ("Isaiah 58:1-12","Fasting God chooses &mdash; justice, not abstinence. Uncomfortable and necessary."),],
["When have you encountered something that made you aware of your own condition?",
 "What have you volunteered for before knowing what it required?",
 "Where has your religious practice replaced actual obedience?",
 "What in your life looks like a stump right now?"]),

E("Luke",
"The gospel of the outsider. Luke consistently puts the wrong people at the center of the story.",
[("The Shepherds Were Nobody","Heaven's press list was upside down from the first night."),
 ("He Ate With the Wrong People","The consistent complaint against Jesus in this gospel."),
 ("The Tax Collector in the Tree","A grown man climbing a tree because he could not see over a crowd."),],
[("The Father Ran","Luke 15. Undignified, sprinting, before the speech was finished."),
 ("Today, With Me","The shortest conversion in Scripture, spoken to a dying criminal."),
 ("Our Hearts Were Burning","Emmaus. Recognizing him in hindsight and going back immediately."),],
[("The Dinner Party Seating","Luke 14 is essentially Jesus giving etiquette advice that offends everyone present."),
 ("Zacchaeus","A wealthy adult man in a tree. Luke includes the detail because it is funny."),],
[("Luke 15:11-32","Three parables about lost things, escalating to a father and two lost sons."),
 ("Luke 10:25-37","The Samaritan. The hero is the one the audience despised."),
 ("Luke 19:1-10","Zacchaeus. Jesus invites himself to dinner and the whole town complains."),
 ("Luke 24:13-35","Emmaus. Scripture explained by the risen Christ to two people who do not recognize him."),],
["Who are the people your church would be surprised to see at the center of a story?",
 "When did God use someone you had written off?",
 "Where have you recognized God only in hindsight?",
 "Whose table are you not sitting at?"]),

E("John",
"Signs, I Am statements, and long conversations. The gospel that slows down where the others move.",
[("The Word Became Flesh","No shepherds, no manger. John states the claim at its most naked."),
 ("A Conversation at Noon","The Samaritan woman, at the hottest hour, because nobody else was there."),
 ("Do You Want to Get Well","Jesus asks a paralyzed man a question that sounds almost rude."),],
[("It Is Finished","Three words that ended the striving."),
 ("Do You Love Me","Three questions for a man who denied him three times."),
 ("Come and Have Breakfast","Restoration over a charcoal fire. The same smell as the denial."),],
[("The Wedding at Cana","Jesus' first miracle solves a catering problem. His mother volunteered him for it."),
 ("Peter's Swim","Peter puts his clothes on to jump in the water. John records it deadpan."),],
[("John 1:1-14","In the beginning was the Word, and the Word became flesh."),
 ("John 4:1-26","The Samaritan woman. The longest recorded conversation Jesus has with anyone."),
 ("John 11:1-44","Lazarus. Jesus weeps at a funeral where he knows what is about to happen."),
 ("John 21:15-19","Do you love me. Restoration by the fire, three times over."),],
["What question has God asked you that you did not want to answer?",
 "Where has restoration happened for you, and who initiated it?",
 "What have you been waiting beside a pool for?",
 "What did Jesus say to you that you have not said out loud?"]),

E("Acts",
"The church in motion, including the arguments. Acts is honest about how messy multiplication actually is.",
[("They Were Ordinary and Unschooled","The council notices they had been with Jesus. That was the only credential."),
 ("The Church Was Born in a Language Barrier","Pentecost as the reversal of Babel."),
 ("A Disagreement Sharp Enough to Split a Team","Paul and Barnabas over Mark. Scripture does not tidy it up."),],
[("They Devoted Themselves","Acts 2:42-47 as a description of an actual week."),
 ("What Is Stopping Me","The Ethiopian's question. Immediate obedience without a class first."),
 ("Send Us","Antioch sends away its two best leaders. Multiplication costs the sending church."),],
[("Eutychus","A young man falls asleep during Paul's sermon and out a window. Every preacher's fear, recorded in canon."),
 ("Rhoda Leaves Peter at the Gate","She is so excited he is out of prison that she forgets to open the door."),],
[("Acts 2:42-47","The four devotions, the meals, the shared property, the daily growth."),
 ("Acts 4:13","Unschooled, ordinary, and unmistakably marked by time with Jesus."),
 ("Acts 8:26-40","Philip and the Ethiopian. What is stopping me from being baptized?"),
 ("Acts 13:1-3","Antioch sends its best. The church that gives people away."),],
["Who would say about you that you have been with Jesus, and why?",
 "What has your church given away that cost you something?",
 "Where has a conflict in ministry actually produced two fruitful things?",
 "What is stopping you from the obedience you already know about?"]),

E("Romans",
"The most systematic book in the New Testament, and the one most in need of illustration to stay human.",
[("The Thing I Do Not Want to Do","Romans 7 is the most relatable paragraph Paul ever wrote."),
 ("All Have Sinned","Leveling the room before offering anything to anyone in it."),
 ("While We Were Still","The timing of the demonstration is the whole point."),],
[("Nothing Can Separate","Romans 8:38-39 read as a list, slowly, letting each item land."),
 ("Therefore, Offer Your Bodies","Romans 12:1. Doctrine turning into a Tuesday."),
 ("The Spirit Who Raised Him Lives in You","Resurrection power with a current address."),],
[("The Length of Romans 7","Paul spends a whole chapter admitting he cannot get his act together. It is oddly comforting."),
 ("Paul's Sentence Structure","Some of these sentences require a diagram and a lawyer."),],
[("Romans 3:21-26","Justified freely by his grace. The hinge of the entire letter."),
 ("Romans 5:6-8","While we were still sinners. The timing carries the theology."),
 ("Romans 8:28-39","All things work together, then nothing can separate. Two claims, one argument."),
 ("Romans 12:1-2","Therefore. Doctrine becoming daily life at the turn of a single word."),],
["Where do you do what you do not want to do?",
 "What separated you from God, and when did you realize it had not?",
 "What would offering your body as a living sacrifice change about your week?",
 "What are you conformed to that you have stopped noticing?"]),

E("James",
"Blunt, practical, and short. The book that will not let a congregation hide behind belief.",
[("Consider It Pure Joy","An instruction that sounds unreasonable until you read the next clause."),
 ("The Mirror You Walk Away From","Hearing without doing, described as forgetting your own face."),
 ("The Small Rudder","Something tiny steering something enormous. The tongue."),],
[("Faith Without Works","Not a contradiction of Paul but a test of what belief actually is."),
 ("Draw Near and He Will Draw Near","Reciprocity stated plainly, with a specific action attached."),
 ("Confess to Each Other","James assumes a room where this is possible. Ask whether yours is."),],
[("If Anyone Lacks Wisdom","James assumes you do. He is right and he is not being subtle about it."),
 ("The Tongue Is a Fire","James clearly knew someone specific when he wrote this chapter."),],
[("James 1:2-4","Trials producing perseverance. The mechanism, not just the encouragement."),
 ("James 1:22-25","Hearing without doing. The mirror image is the sermon."),
 ("James 2:14-17","Faith without works. Deeds as evidence rather than as payment."),
 ("James 5:13-16","Confess to each other and pray for each other, so that you may be healed."),],
["Where are you a hearer and not a doer?",
 "What has a trial in your life actually produced?",
 "Who can you confess to, and if nobody, why not?",
 "What does your calendar say you believe?"]),
]

PASSAGES = [
E("Psalm 23",
"The most quoted passage in Scripture and the least examined. Every phrase will carry a full message.",
[("Who Is Your Shepherd Actually","Naming the thing currently leading you before naming the one who should."),
 ("I Shall Not Want","Contentment stated as a consequence, not a command."),
 ("He Makes Me Lie Down","The verb is coercive. Sometimes rest is imposed rather than chosen."),],
[("Through, Not Around","The preposition. Say it three times and let it sit."),
 ("A Table in the Presence of Enemies","Provision that does not wait for the threat to be removed."),
 ("Goodness and Mercy Follow","Pursued by kindness rather than by consequence."),],
[("Everyone Knows It, Nobody Knows It","Ask the room to recite it. Watch it fall apart at verse four."),
 ("Sheep Are Not Flattering","Look up what shepherds actually say about sheep before you use this as a compliment."),],
[("John 10:11-18","I am the good shepherd. Jesus applies the psalm to himself deliberately."),
 ("Ezekiel 34:11-16","God against the bad shepherds, promising to do it himself."),
 ("Isaiah 40:11","He tends his flock like a shepherd, gathering the lambs."),
 ("Luke 15:3-7","The shepherd who leaves ninety-nine to find one."),],
["What has been shepherding you &mdash; what actually decides your days?",
 "When has God made you lie down rather than invited you to?",
 "What valley have you been through, not around?",
 "Where has provision come while the threat was still present?"]),

E("Luke 15 &mdash; The Prodigal",
"Three parables, one argument, and two lost sons. Most churches have never had the second half preached to them.",
[("He Was Still a Long Way Off","The father was watching. The watching is the sermon."),
 ("Give Me My Share Now","A request that functions as wishing your father dead."),
 ("He Came to His Senses","Repentance beginning as a calculation about food, not a spiritual awakening."),],
[("The Father Ran","An older man in that culture running. Undignified, on purpose."),
 ("The Speech He Never Finished","The prepared apology gets interrupted by an embrace."),
 ("The Story Has No Ending","Jesus stops before the older brother answers. He leaves the door open on purpose."),],
[("The Fattened Calf","Somebody had been keeping that calf ready. The father had been planning this."),
 ("The Older Brother's Complaint","You never gave me a young goat. The pettiness is precisely the point."),],
[("Luke 15:1-7","The lost sheep. The shepherd goes after it rather than waiting."),
 ("Luke 15:8-10","The lost coin. A woman turns the house upside down for one."),
 ("Ezekiel 34:16","I will search for the lost and bring back the strays."),
 ("2 Corinthians 5:18-20","The ministry of reconciliation, given to us. We are now the ones running."),],
["Which son are you, honestly, right now?",
 "What did you assume the reception would be when you came back?",
 "Who are you resentful of for being welcomed?",
 "Who is a long way off that you should be watching for?"]),

E("Romans 8:28-39",
"The most quoted comfort passage in Paul, and the most often misapplied. Verse 28 is not a promise that things will feel good.",
[("All Things, Not Each Thing","The most commonly misread verse in the New Testament. Correct it early."),
 ("The Worst Thing Someone Said to You","Romans 8:28 quoted at a funeral, badly. Name the misuse before the use."),
 ("The Groaning of Creation","Verses 18-27 give this passage its weight. Do not start at 28."),],
[("Read the List Slowly","Death, life, angels, demons, present, future. Let each one land as its own sentence."),
 ("Neither Height Nor Depth","The list is exhaustive on purpose. Ask what people would add to it."),
 ("Nothing. Full Stop.","End on the word and do not explain it further."),],
[("The Bumper Sticker Version","Verse 28 has been printed on more mugs than it has been read in context."),
 ("Paul's List Keeps Going","He appears to be worried he has left something out, so he adds anything else in all creation."),],
[("Genesis 50:20","Intended for harm, meant for good. The Old Testament version of the same claim."),
 ("2 Corinthians 4:16-18","Light and momentary troubles, written by a man who was regularly beaten."),
 ("John 10:27-29","No one can snatch them out of my hand. Security stated twice, two ways."),
 ("Philippians 1:6","He who began a good work will carry it on to completion."),],
["What has been said to you with Romans 8:28 that did not help?",
 "What has actually worked together for good in your story, and how long did it take?",
 "What would you add to Paul's list of things that might separate you?",
 "Where do you currently feel separated, even if you know you are not?"]),

E("Philippians 4:4-13",
"Joy, anxiety, contentment, and strength, in thirteen verses written from a prison cell.",
[("Rejoice Always, From Prison","The circumstance of the author changes how the instruction reads."),
 ("Two Women Who Could Not Agree","Verse 2. Paul names an actual church conflict by name."),
 ("Whatever Is True","A list of what to feed your mind, in an age that decides that for us."),],
[("The Peace That Guards","A military verb. Peace as a garrison rather than a feeling."),
 ("I Have Learned","Contentment is stated as an acquired skill, not a temperament."),
 ("Through Him Who Gives Me Strength","Verse 13 restored to its actual context, which is scarcity."),],
[("Philippians 4:13 on Sports Gear","The verse is about being hungry, not about winning. Say so kindly."),
 ("Euodia and Syntyche","Two thousand years later, we still know they were arguing. A cautionary tale."),],
[("Matthew 6:25-34","Do not worry. The same instruction, with the birds as the argument."),
 ("1 Timothy 6:6-8","Godliness with contentment is great gain. Food and clothing as the baseline."),
 ("2 Corinthians 12:7-10","When I am weak, then I am strong. The strength passage's companion."),
 ("Colossians 3:1-4","Set your minds on things above. The same discipline of attention."),],
["What have you learned contentment in, and what did the learning cost?",
 "What are you feeding your mind that you would not feed a child?",
 "Where are you strongest, and where did that strength actually come from?",
 "What conflict in your church would still be remembered in two thousand years?"]),
]
