# -*- coding: utf-8 -*-
def D(n, q, sub, why, dims, qs, bands, prod, form, line, tools):
    return {"n":n,"q":q,"sub":sub,"why":why,"dims":dims,"qs":qs,"bands":bands,
            "prod":prod,"form":form,"line":line,"tools":tools}

FAMILY = ("Six intelligences, one architecture. Each asks what is actually happening, discerns what matters now, "
 "and turns the answer into a formation pathway. Intelligence without formation becomes information. "
 "Formation without intelligence becomes generic programming.")

ARCH = [
 ["Discover","What is actually happening here, measured rather than assumed."],
 ["Discern","What matters most now. Not every need requires a new programme."],
 ["Form","An intentional pathway toward transformation rather than activity."],
 ["Multiply","Turn the pathway into resources the whole church can carry."],
 ["Measure","Listen again. What changed, and what is the next faithful step."],
]

PLATFORMS = [

D("Pastor Intelligence","What has God uniquely formed in this pastor?","Understand the voice",
 "Every church resource ever sold to a pastor was written by somebody else for somebody else. Pastor Intelligence starts from what is already his — his voice, his convictions, his archive, his church's DNA — and builds outward from that rather than over it.",
 [["Purpose","Why he believes he was put here, in one sentence he can say without notes."],
  ["Passion","What he cannot stop preaching about, whether or not he planned to."],
  ["Philosophy","How he believes ministry ought to be done, and where that came from."],
  ["Paradigm","The lens he reads everything through, usually unnamed."],
  ["Pathway","How he believes a person actually grows, stated rather than assumed."],
  ["People","Who he is for. The room he sees when he writes."],
  ["Possibilities","What he would attempt if the constraints lifted."],
  ["The Archive","Everything he has already preached, indexed and analysed."]],
 [["Could you state your ministry purpose in one sentence, right now?",["Yes, immediately","With a moment","Roughly","No"]],
  ["Is your preaching archive searchable?",["Fully indexed","Files I could find","Scattered","Effectively lost"]],
  ["Do you know which topics you have never preached?",["Yes, documented","Roughly","No idea","Never considered it"]],
  ["Has anyone ever analysed your teaching for patterns?",["Yes","Informally","No","No"]],
  ["Do your staff know what you actually believe about how people grow?",["It is written down","They could say it","Approximately","No"]],
  ["What percentage of what your church uses was written by you?",["Most of it","About half","A little","Almost none"]],
  ["Could a new staff member learn your voice from a document?",["Yes","Partly","No","There is no document"]],
  ["If you left, what would be lost that nobody could reconstruct?",["Very little, it is captured","Some","Most of it","All of it"]]],
 [["8 to 13","Undocumented","Thirty years of ministry lives in one head and one hard drive. Start with the archive; everything else in this platform depends on it existing in a usable form."],
  ["14 to 20","Partially captured","Some of it exists somewhere. The gap is indexing rather than collecting. Six weeks of transcription changes this band entirely."],
  ["21 to 26","Indexed","The archive is usable. The next step is analysis — coverage, patterns and gaps — which turns a library into intelligence."],
  ["27 to 32","Intelligent","Voice, convictions and archive are all captured and usable. The frontier is multiplication: turning it into resources the church can carry without him."]],
 "A Pastor Intelligence Profile — purpose, passion, philosophy, paradigm, pathway, people and possibilities, written out, plus the coverage report against his own archive.",
 "Pastor Formation — calling, character, spiritual health, biblical depth, preaching, leadership, vision, team building, decision making, succession, personal rhythms, family health, multiplication, legacy.",
 "Everything else on this platform is what we bring. This is what he brings. The product is the intersection, and it is the only part nobody can replicate.",
 ["Archive upload and transcription","Coverage Report against 98 topics","The seven A's audit","P-lens interview instrument","Voice and style profile","Succession capture"]),

D("Sermon Intelligence","What could this message become?","Understand the multiplication",
 "A sermon is preached once and dies on a Sunday afternoon. Sermon Intelligence treats every message as the seed of a series, a study, a campaign and a household rhythm — and makes the conversion automatic rather than heroic.",
 [["The Message","Big idea, text, structure and what it actually claims."],
  ["The Multiplication","What it becomes: series, group study, devotional, campaign, family edition."],
  ["The Illustration","What is in it, where it came from, and when it was last used."],
  ["The Response","What the message asks a person to do, named before it is preached."],
  ["The Reach","Who heard it, who acted on it, and who never came."],
  ["The Recurrence","How often this idea is preached here and whether it is a strength or a rut."]],
 [["Do you know your big idea before you start writing?",["Always","Usually","Sometimes","Rarely"]],
  ["Does every message land on one named next step?",["Every week","Most","Occasionally","No"]],
  ["Does anything happen to a message after Sunday?",["Groups, devotionals and more","Group questions","A podcast","Nothing"]],
  ["Do you know which illustrations you have used and when?",["Tracked","Roughly remember","No","Never thought about it"]],
  ["Is your preaching planned twelve months out?",["Yes, on a calendar","A few months","Series by series","Week by week"]],
  ["Do your groups study what you preached?",["Same week, same text","Loosely aligned","Unrelated","No groups"]],
  ["Do you know what people actually did because of a message?",["We collect stories","Anecdotes","No","Never asked"]],
  ["Could one message become a six-week campaign without starting over?",["Routinely","With work","Not really","Never done it"]]],
 [["8 to 13","One and done","Every message is written from scratch and dies on Sunday afternoon. The single highest-return fix is aligning groups to the weekend text."],
  ["14 to 20","Partially reused","Some multiplication happens, usually by hand. The gap is a system rather than effort."],
  ["21 to 26","Multiplying","Messages become more than themselves routinely. The frontier is measurement — knowing what actually changed."],
  ["27 to 32","Compounding","Every message produces a week, a group session and a household rhythm, and the archive is getting stronger rather than longer."]],
 "A Message Profile — big idea, structure, illustrations tagged, response named, and the six multiplication paths already generated.",
 "Sermon Multiplication — one message becomes a series, a group study, six daily readings, a family edition, a campaign and a permanent entry in the archive.",
 "The sermon is the least valuable thing you produce and the most expensive. Everything built around it is where the value actually sits.",
 ["Sermon Finder","Sermon Curator","Sermon Builder","Sermon Accelerator","Sermon Multiplier","Message to Movement"]),

D("Volunteer Intelligence","Who is serving, who has stopped, and why?","Understand the serving body",
 "Most churches know how many volunteers they have and almost nothing else. Volunteer Intelligence measures the pipeline rather than the headcount — where people enter, where they stall, why they leave, and who is ready for more.",
 [["The Pipeline","From first interest to team leader, and where people stall."],
  ["The Ask","How people are recruited, by whom, and with what yield."],
  ["The Onboard","Time from yes to first serve. The single strongest predictor of retention."],
  ["The Load","Who is carrying too much and who has not been asked in a year."],
  ["The Retention","Who stopped, when, and whether anybody noticed."],
  ["The Bench","Who could lead, who is ready now, and who has plateaued."]],
 [["What percentage of adults serve somewhere?",["Over half","A third","Under a quarter","Not tracked"]],
  ["How long from someone saying yes to their first serve?",["Under three weeks","Three to six","Over six","No idea"]],
  ["Do you know who stopped serving this year?",["By name","Roughly","No","Not tracked"]],
  ["Has anyone asked a lapsed volunteer why?",["Routinely","Occasionally","Never","Never"]],
  ["Are volunteers recruited personally or announced?",["Personally, by name","Both","Mostly announced","Announcements only"]],
  ["Do you know who is carrying too much?",["Yes, and we act on it","Roughly","No","No"]],
  ["Is there a written role description for every job?",["All of them","Most","A few","None"]],
  ["How many team leaders have you developed in two years?",["Five or more","Two to four","One","None"]]],
 [["8 to 13","Invisible","You know the headcount and nothing else. Start with two things: role descriptions and a list of who stopped this year."],
  ["14 to 20","Managed","People are recruited and placed. The gaps are almost always onboarding time and lapsed follow-up."],
  ["21 to 26","Developed","The pipeline works and people are growing. The frontier is team leaders — the layer that scales everything."],
  ["27 to 32","Multiplying","Teams produce their own leaders. The question now is whether serving is discipleship or staffing, and whether the people can tell."]],
 "A Serving Profile for the whole church — pipeline by stage, coverage by ministry, load distribution, retention curve and a named bench.",
 "Volunteer Formation — serving as discipleship rather than staffing. Placement by gifting, training that fits, honour that is specific, and every team producing its next leader.",
 "Most volunteers do not quit. They drift out, and nobody notices for two months. That gap is the entire retention problem.",
 ["Pipeline map by ministry","Role description generator","21-day onboarding tracker","Load and burnout flags","Lapsed volunteer list","Bench and apprentice tracker"]),

D("Small Group Intelligence","Who is known, and who is not?","Understand the circles",
 "Attendance measures who came. Group Intelligence measures who is known — which is the only number that predicts whether somebody is still here in two years.",
 [["The Coverage","What share of the congregation is in a circle, by demographic and by campus."],
  ["The Placement","Time from interest to first meeting, and how many never land."],
  ["The Leader","Who is leading, how they were trained, and how long they last."],
  ["The Health","Whether groups are forming people or simply meeting."],
  ["The Multiplication","Which groups produce leaders and which are closed rooms."],
  ["The Gap","Who is not in a group and has never been asked."]],
 [["What percentage of adults are in a group?",["Over half","A third","Under a quarter","Not tracked"]],
  ["How long from interest to first meeting?",["Under three weeks","Three to six","Over six","People fall through"]],
  ["When did you last run a churchwide launch?",["Within six months","Within a year","Over a year","Never"]],
  ["Is there a coaching layer above your leaders?",["Yes, one per five","Informal","No","No"]],
  ["Do groups study what is preached?",["Same week","Loosely","No","No groups"]],
  ["How many groups multiplied last year?",["Several","One or two","None","Not tracked"]],
  ["Do you know who is not in a group?",["By name","By segment","No","Not tracked"]],
  ["Do you measure anything besides attendance?",["Formation outcomes","Some","Attendance only","Nothing"]]],
 [["8 to 13","Attending","People come and are not known. Ten households, six weeks and sermon-aligned material is the entire first move."],
  ["14 to 20","Grouped","Groups exist and plateau, usually around thirty percent. The constraint is leaders, and leaders come from inside existing groups."],
  ["21 to 26","Coached","The coaching layer exists and leaders last. The frontier is multiplication — naming the apprentice in week one rather than week ten."],
  ["27 to 32","Multiplying","Groups produce groups. The question now is whether they are forming people or just meeting well."]],
 "A Group Profile — coverage by segment, placement times, leader tenure, health by group, multiplication rate, and a named list of who has never been asked.",
 "Group Formation — rows into circles, hosts rather than teachers, finite terms, sermon-aligned material, a coaching layer, and an apprentice named in week one.",
 "The strongest predictor of whether somebody is still attending in two years is whether they have friends here. Groups are not a programme, they are the retention system.",
 ["Coverage map by segment","Placement tracker","Leader tenure and health","Coaching structure builder","Multiplication tracker","Never-been-asked list"]),

D("Church Vision & Values Intelligence","Can anyone here say what we are for?","Understand the identity",
 "Most churches have a vision statement on a wall and six different answers in the staff room. This measures the gap between what is written, what leaders say, what members say and what the calendar actually funds.",
 [["The Stated","What is written down, in the words it is written in."],
  ["The Spoken","What leaders actually say when asked without warning."],
  ["The Heard","What members repeat back, which is the only version that counts."],
  ["The Funded","What the budget says the church believes, regardless of what it preaches."],
  ["The Calendared","What the year is actually built around."],
  ["The Rewarded","What behaviour gets noticed here, which is the real values statement."]],
 [["Could every staff member state the vision in one sentence?",["Yes, the same one","Roughly the same","Different versions","No"]],
  ["Could a two-year member state it?",["Yes","Approximately","No","Unlikely"]],
  ["Are your values written in words people use?",["Yes, plain","Somewhat","Churchy","Not written"]],
  ["Does the budget reflect the stated priorities?",["Clearly","Mostly","Not really","Never compared"]],
  ["Does the calendar reflect them?",["Built around them","Partly","No","No"]],
  ["When did you last revisit the vision?",["This year","Two years","Longer","Never"]],
  ["Do you know what behaviour gets rewarded here?",["Named and examined","Roughly","No","Never asked"]],
  ["Is there anything in the vision you no longer believe?",["Nothing","One thing","Several","Most of it"]]],
 [["8 to 13","Divergent","Six people are working toward six futures. This is not a communication problem, it is a clarity problem, and it is fixed in a room rather than on a poster."],
  ["14 to 20","Stated","It is written and not carried. The gap is repetition and ownership — people carry what they helped shape."],
  ["21 to 26","Aligned","Leaders and members can say it and the budget mostly agrees. The frontier is the rewarded values, which nobody examines."],
  ["27 to 32","Embodied","Stated, spoken, heard, funded and calendared all agree. Rare. The question is whether it survives the current leader."]],
 "An Identity Profile — the four versions of the vision side by side (stated, spoken, heard, funded), the values audit, and the gaps named in plain language.",
 "Church Formation — one direction everyone can repeat, values written in words people use, a budget and calendar that agree with the preaching, and a culture taught rather than caught.",
 "Culture is not what is written on the wall. It is the worst behaviour the leader walked past this month.",
 ["Vision statement audit","Four-version comparison","Values in plain language builder","Budget and calendar alignment check","Rewarded-behaviour audit","Staff and member survey"]),

D("Evangelism Intelligence","Who is coming, who is missing, and who has ever been asked?","Understand the reach",
 "Almost every church measures attendance and almost none measures reach. This distinguishes growth by transfer from growth by conversion, and names who the congregation has stopped seeing.",
 [["The Source","Where growth actually comes from: new believers, invitation, transfer or return."],
  ["The Invitation","How many members invited anyone this year, and how many were asked to."],
  ["The Guest","How many first-time guests, and what share return."],
  ["The Missing","Who is not here — by age, by neighbourhood, by language, by circumstance."],
  ["The Conversation","Whether people can explain the gospel and their own story."],
  ["The City","What the surrounding community would miss if this church closed."]],
 [["Where does most of your growth come from?",["New believers","Invitation","Transfer","We are not growing"]],
  ["What share of guests return for a second visit?",["Over half","A third","Under a fifth","Unknown"]],
  ["What percentage of members invited anyone this year?",["Over half","A third","A handful","Unknown"]],
  ["Have you asked the congregation to invite, specifically?",["Several times","Once or twice","Vaguely","No"]],
  ["Could a typical member tell their story in three minutes?",["Most could","Some","Few","No"]],
  ["Do you know who is missing from your congregation?",["Named by segment","Roughly","No","Never asked"]],
  ["Is anyone following up guests within forty-eight hours?",["Every guest","Most","Sometimes","No"]],
  ["Would the neighbourhood notice if you closed?",["Clearly yes","Some would","Probably not","No"]]],
 [["8 to 13","Closed","Growth is transfer or nothing, and nobody has been asked to invite. Start with one ask from the platform and forty-eight hour follow-up."],
  ["14 to 20","Attracting","Guests arrive and most do not return. This is a retention problem misread as a reach problem — fix the leak before opening the tap."],
  ["21 to 26","Reaching","Guests come and stay, and members invite. The frontier is equipping people to have the conversation rather than only make the introduction."],
  ["27 to 32","Sent","People are being reached, formed and sent. The question now is whether the city would notice, and the honest answer takes asking somebody outside."]],
 "A Reach Profile — growth by source, invitation rate, guest return rate, the missing segments named, and an honest answer to what the city would miss.",
 "Mission Formation — members who invite by name, guests who are followed up within forty-eight hours, people equipped to tell their own story, and a church its neighbourhood would miss.",
 "A church that is not missed by its own neighbourhood has been meeting rather than serving. That is a measurable thing and almost nobody measures it.",
 ["Growth-by-source analysis","Invitation rate tracker","Guest return measurement","Missing-segment map","Three-minute story training","City impact audit"]),
]
