# -*- coding: utf-8 -*-
from intel_lib import D

MORE = [

D("Discipleship Intelligence","How does a person actually grow here?","Understand the pathway",
 "Every church says it makes disciples and most cannot describe how. Discipleship Intelligence measures whether a pathway exists, whether anyone can name it, and whether people are moving along it &mdash; or simply attending for a decade.",
 [["The Pathway","Whether one exists, whether it is written, and whether a member could describe it."],
  ["The Entry","How a new believer or a new attender gets started, and how long it takes."],
  ["The Steps","What the visible next step is at every stage, and who names it."],
  ["The Environments","Where formation actually happens here: weekend, group, class, household, serving."],
  ["The Movement","Whether people are progressing or plateaued, measured rather than assumed."],
  ["The Outcome","What a mature disciple looks like in this church, written down."]],
 [["Could a member describe how someone grows here?",["In one sentence","Roughly","No","There is nothing to describe"]],
  ["Is the pathway written down anywhere?",["Yes, one page","In someone&rsquo;s head","No","No"]],
  ["Does every step name the next one?",["Every step","Most","Some","No"]],
  ["What happens to a new believer in the first ninety days?",["A defined plan","Someone follows up","Ad hoc","Nothing"]],
  ["Do you know who has plateaued?",["By name","By segment","No","Not tracked"]],
  ["Have you written what a mature disciple looks like here?",["Yes","Roughly","No","Never considered it"]],
  ["Do your environments connect, or compete?",["Deliberately connected","Mostly","They compete","No idea"]],
  ["Do you measure formation or attendance?",["Formation outcomes","Both","Attendance only","Nothing"]]],
 [["8 to 13","Attending","There is no pathway, only activity. Write one page that a member could read: entry, three steps, and what each one leads to."],
  ["14 to 20","Programmed","Environments exist and do not connect. The fix is sequence rather than more programmes &mdash; name what follows what."],
  ["21 to 26","Pathwayed","A path exists and people walk it. The gap is usually measurement: you know who attends and not who has grown."],
  ["27 to 32","Forming","Path, steps and measurement all working. The frontier is whether people are producing disciples or only becoming them."]],
 "A Formation Profile &mdash; the pathway as it actually exists, the gaps between stages, who has plateaued, and a written definition of what maturity looks like in this church.",
 "Church Formation &mdash; a visible pathway from first visit to leading, every step naming the next, aligned environments and formation measured rather than assumed.",
 "If nobody can describe how a person grows here, it is not happening on purpose. It may still be happening, but nobody is stewarding it.",
 ["Pathway map and gap audit","New believer 90-day plan","Next-step inventory by stage","Environment alignment check","Plateau identification","Maturity definition builder"]),

D("Family Intelligence","What actually happens in the household between Sundays?","Understand the home",
 "A church gets a person for one hour and a household gets them for the other hundred and sixty-seven. Family Intelligence measures what is happening in the home &mdash; and whether the church is equipping it or quietly competing with it.",
 [["The Households","What shapes are actually in this congregation: nuclear, single-parent, blended, single, empty nest, multigenerational."],
  ["The Rhythms","What a household actually practises, if anything, between Sundays."],
  ["The Handoff","What goes home from every environment, and whether a parent reads it."],
  ["The Milestones","Dedication, first Bible, baptism, graduation, marriage &mdash; whether they are marked or missed."],
  ["The Equipping","What parents have been given, and whether they asked for it."],
  ["The Competition","Whether the church calendar takes households out of the home or supports them in it."]],
 [["Do you know the household shapes in your congregation?",["Measured","Roughly","No","Never asked"]],
  ["Does anything go home from the weekend?",["Every week, and it is read","Every week","Sometimes","No"]],
  ["Have you asked parents what they actually need?",["Yes, and acted on it","Asked","No","No"]],
  ["Is there a milestone pathway from birth to launch?",["Yes, mapped","Some milestones","One or two","None"]],
  ["Does your language assume a nuclear family?",["Deliberately not","Sometimes","Usually","Never examined"]],
  ["How many nights a week does church take a family out?",["One or fewer","Two","Three or more","Never counted"]],
  ["Do households have one shared rhythm they actually keep?",["Most do","Some","Few","No idea"]],
  ["Are single and blended households named directly?",["Yes, in the material","Sometimes","No","No"]]],
 [["8 to 13","Assumed","The church has no picture of its own households and is probably competing with them. Count the nights first &mdash; the answer usually surprises the staff."],
  ["14 to 20","Supplied","Things go home and nobody reads them. One rhythm a household will keep beats five they will not."],
  ["21 to 26","Equipped","Parents are supported and milestones are marked. The gap is usually household shapes the language still ignores."],
  ["27 to 32","Partnered","The home is the primary environment and the church resources it. Rare, and the question is whether it survives a staff change."]],
 "A Household Profile &mdash; the shapes actually present, the nights the calendar takes, what goes home and whether it lands, the milestone map with its gaps, and what parents said when asked.",
 "Family Formation &mdash; one household rhythm rather than five, a milestone pathway from birth to launch, parents equipped rather than instructed, and a calendar that gives households back their evenings.",
 "Most households will not add a devotional. They will add one question at dinner. Start there and stop apologising for it.",
 ["Household shape census","Calendar-night audit","Take-home effectiveness check","Milestone pathway map","Parent needs survey","Language inclusion review"]),

D("Stewardship Intelligence","Are people becoming generous, or is the church just funded?","Understand the giver",
 "A funded church and a generous church are not the same thing, and confusing them is how a budget gets met while a congregation stays exactly as it was. This measures formation rather than revenue.",
 [["The Participation","What share of households give at all &mdash; the number that matters more than the total."],
  ["The Journey","First gift, second gift, lapse and return, tracked by household rather than in aggregate."],
  ["The Teaching","How often money is taught, in what tone, and whether it is ever taught without an ask."],
  ["The Discipleship","Whether anyone is helping households with their own money, not only the church&rsquo;s."],
  ["The Assets","Whether anything beyond income has ever been discussed."],
  ["The Legacy","What leaves this congregation at death, and whether anyone has ever mentioned it."]],
 [["What percentage of households give in a year?",["Over 50%","30 to 50%","Under 30%","Not tracked"]],
  ["Do you know your first-time giver retention?",["Measured","Roughly","No","Never considered it"]],
  ["How often is money taught from the platform?",["A series plus moments","Two or three times","Once","We avoid it"]],
  ["Is money ever taught with no ask attached?",["Regularly","Occasionally","No","No"]],
  ["Is a financial discipleship class running this year?",["Twice a year","Once","Occasionally","Never"]],
  ["Has anyone taught on wills or estates in two years?",["More than once","Once","No","Never"]],
  ["Has anyone discussed giving assets rather than cash?",["Yes, with a process","Mentioned","No","No"]],
  ["Do givers hear what their giving did?",["Reported regularly","Occasionally","Rarely","No"]]],
 [["8 to 13","Funded or not","Money is a need rather than a discipleship subject. Teach it four times this year with no ask attached and the tone changes within a season."],
  ["14 to 20","Collected","Giving works and formation does not. Start a financial discipleship track &mdash; it serves the strained half and earns the right to speak to the generous half."],
  ["21 to 26","Forming","People are being discipled with money and participation is healthy. The gap is almost always assets and legacy, which nobody has raised."],
  ["27 to 32","Generous","Formation, participation, assets and legacy all live. The question is whether generosity would continue if the church stopped asking."]],
 "A Generosity Profile &mdash; participation by household, the giving journey with its leak points, teaching frequency and tone, discipleship coverage, and the untouched asset and legacy conversation.",
 "Generosity Formation &mdash; teaching before asking, participation before amount, financial discipleship for every income level, and the asset conversation nobody else is having.",
 "Percentage of households giving matters more than total dollars. Under thirty percent is a formation problem, not a funding one.",
 ["Household participation analysis","Giving journey and leak points","Teaching frequency and tone audit","Financial discipleship coverage","Asset conversation readiness","Legacy and estate gap check"]),

D("Church Campaign Intelligence","Should we run one, and what should it be?","Understand the readiness",
 "Most churches run a campaign because it is autumn, not because the congregation needs one. This measures readiness, capacity and fit before anything is announced &mdash; and sometimes the honest answer is not this year.",
 [["The Need","What the congregation actually needs, measured rather than assumed by the staff."],
  ["The Readiness","Whether leaders, groups and volunteers have capacity for a churchwide push."],
  ["The Capacity","How many groups you can actually host, which is the real ceiling on any campaign."],
  ["The Timing","What else is on the calendar, what happened last year, and how long since the last one."],
  ["The Alignment","Whether the weekend, groups, households and every age can carry the same idea."],
  ["The Follow-Through","What happens in week seven, decided before week one."]],
 [["Do you know what the congregation actually needs?",["Surveyed","We have a sense","Staff opinion","No"]],
  ["How many groups could you host right now?",["More than we need","About enough","Fewer than needed","Unknown"]],
  ["How long since the last churchwide campaign?",["Over a year","Under a year","Months","We run several"]],
  ["Do you have enough trained hosts?",["Yes, with a bench","Just enough","Short","No hosts"]],
  ["Will the weekend, groups and households carry the same idea?",["All of them","Two of three","One","No"]],
  ["Is there a kids and student edition?",["Both","One","No","Never considered"]],
  ["Is week seven planned?",["Yes, before week one","Roughly","No","What happens in week seven"]],
  ["Did you measure the last one?",["Outcomes measured","Attendance","No","Never ran one"]]],
 [["8 to 13","Not this year","Running a campaign now would cost more than it produces. Build group capacity first &mdash; that is the ceiling, and no amount of promotion raises it."],
  ["14 to 20","Possible with work","You could run one and it would strain. Spend a season recruiting and training hosts, then launch."],
  ["21 to 26","Ready","Capacity, alignment and timing all work. The usual gap is week seven, which decides whether anything survives the six weeks."],
  ["27 to 32","Campaign capable","You can run one well and repeat it. The frontier is measuring formation rather than participation."]],
 "A Campaign Readiness Profile &mdash; the congregation&rsquo;s actual need, host and group capacity, calendar conflicts, alignment across environments, and a recommendation including whether to wait.",
 "Campaign Formation &mdash; a churchwide season with the weekend, groups, households and every age carrying one idea, and a week seven that was planned before week one.",
 "Group capacity is the ceiling on every campaign, and no amount of promotion raises it. Count the hosts before you choose the theme.",
 ["Congregational needs survey","Host and group capacity count","Calendar conflict check","Alignment readiness by environment","Week-seven planner","Post-campaign measurement"]),

D("Sunday School & ABF Intelligence","Who is teaching, what are they teaching, and is anyone learning?","Understand the classroom",
 "The class that has run for forty years is usually the least examined ministry in the building. This measures the teachers, the content and the outcomes in a room that most churches have simply stopped looking at.",
 [["The Classes","What exists, who attends, and whether the roster reflects the congregation."],
  ["The Teachers","Who teaches, how they were chosen, when they were last trained, and how long they have taught."],
  ["The Content","What is being taught, who chose it, and whether anyone has read it recently."],
  ["The Term","Whether classes run in terms with a start and an end, or continue indefinitely."],
  ["The Room","Physical space, table structure, and whether discussion actually happens."],
  ["The Succession","Who could teach if a long-serving teacher stopped, which happens without warning."]],
 [["Do you know what is being taught in every class?",["Yes, reviewed","Roughly","No","No"]],
  ["When were teachers last trained?",["Within a year","One to three years","Longer","Never"]],
  ["How were current teachers chosen?",["A process","They volunteered","They always have","Nobody remembers"]],
  ["Do classes run in defined terms?",["Yes, quarterly","Loosely","They continue","Indefinitely"]],
  ["Does the class roster reflect the congregation?",["Closely","Somewhat","No","Never compared"]],
  ["Is there an apprentice for each teacher?",["Nearly all","Some","Few","None"]],
  ["Are teachers supplied with content?",["Full teacher manual","An outline","They build it","Nothing"]],
  ["Has a class closed or started in three years?",["Both","One","No","Nothing changes"]]],
 [["8 to 13","Unexamined","Classes run and nobody looks. Start by finding out what is actually being taught &mdash; the answer is often a surprise and occasionally a problem."],
  ["14 to 20","Running","Classes work and depend entirely on individuals. Every long-serving teacher is a single point of failure until there is an apprentice."],
  ["21 to 26","Resourced","Teachers are trained and supplied. The gap is usually terms &mdash; classes that never end never renew."],
  ["27 to 32","Multiplying","Teachers are developed, content is chosen, terms turn over and classes start and close. Rare in this ministry."]],
 "A Classroom Profile &mdash; every class with its roster, teacher tenure and training date, what is actually being taught, term structure, apprentice coverage and the succession risks named.",
 "Teacher Formation &mdash; the ABF library of twelve categories and two hundred and forty courses, with a teacher manual for every one so the person up front is prepared rather than improvising.",
 "A teacher who has to build the content will teach for one term and quit. Supply the content and the same person teaches for a decade.",
 ["Class and roster audit","Teacher tenure and training log","Content review","Term structure planner","Apprentice coverage map","Succession risk flags"]),

D("Ministry Intelligence","Why does this ministry exist, and is it doing that?","Understand any ministry",
 "This is the engine the others run on. Every ministry &mdash; men, women, students, care, recovery, missions, worship, any of them &mdash; can be examined with the same six dimensions, which is what makes it a platform rather than a set of separate products.",
 [["The Purpose","Why this ministry exists, in a sentence, and whether anyone wrote it down."],
  ["The People","Who it serves, who it reaches, and who it is quietly missing."],
  ["The Pathway","How somebody enters, what the next step is, and where they exit."],
  ["The Leaders","Who leads, how they were developed, and who follows them."],
  ["The Outcomes","What it is producing, measured against what it says it is for."],
  ["The Resources","Content, budget, space and time &mdash; and whether the ministry is under-resourced or simply unclear."]],
 [["Is this ministry&rsquo;s purpose written down?",["One clear sentence","Roughly known","Inherited","Unclear"]],
  ["Do you know who it is missing?",["Named","Roughly","No","Never asked"]],
  ["Is the entry point obvious to a newcomer?",["Very","Somewhat","No","There isn&rsquo;t one"]],
  ["What is the next step after someone joins?",["Named and taken","Named","Vague","None"]],
  ["How were the current leaders developed?",["A pathway","On the job","They volunteered","Nobody knows"]],
  ["Is there an apprentice for the leader?",["Yes, named","Maybe","No","No"]],
  ["What outcome is this measured against?",["A named outcome","Participation","Attendance","Nothing"]],
  ["Is it under-resourced or unclear?",["Clear and resourced","Clear, under-resourced","Unclear","Both"]]],
 [["8 to 13","Inherited","This ministry runs because it always has. Name the outcome first &mdash; most ministries in this band are unclear rather than under-resourced, and money will not fix that."],
  ["14 to 20","Operating","It works and nobody could say what it is for. Write the purpose sentence with the leaders, not for them."],
  ["21 to 26","Purposeful","Clear, resourced and producing. The gap is usually the pathway &mdash; people join and nothing follows."],
  ["27 to 32","Multiplying","Purpose, pathway, leaders and outcomes all working, with an apprentice named. This is what every other ministry should be measured against."]],
 "A Ministry Profile &mdash; purpose as stated versus as practised, who is served and who is missed, the pathway with its break point, leader development and succession, and outcomes against the stated aim.",
 "Ministry Formation &mdash; clear pathways, leader training, curriculum, coaching, campaigns, resources, communication, measurement and multiplication, applied to whichever ministry was examined.",
 "Instead of running programmes because we have always run them, a ministry becomes an intentional formation environment. The same six questions work on every one of them.",
 ["Purpose statement builder","Who-is-missing audit","Pathway map and break-point finder","Leader development check","Outcome definition","Resource versus clarity diagnostic"]),
]

# ===== THE CONSOLIDATION =====
CONSOL_LINE = "Thirteen intelligences is a pile. Six is a platform."

CONSOL_WHY = ("Building all thirteen surfaced the problem I flagged last time and made it worse. Four of them "
 "duplicate the original brochure, and seven of them are not separate systems at all &mdash; they are the same "
 "engine pointed at different ministries. A pastor looking at thirteen products reads a catalogue and buys nothing. "
 "Here is the map that fixes it without discarding a single piece of the work.")

CORE = [
 ["Pastor Intelligence","The voice","Structurally distinct because the subject is one person and his archive. Nothing else on the platform examines an individual leader's body of work.",
  ["Absorbs nothing. It is already singular."]],
 ["Church Staff Intelligence","The team","Distinct because staff are employed, supervised and paid. Volunteers are not, and the questions genuinely differ.",
  ["Absorbs nothing."]],
 ["Sermon Intelligence","The message","Distinct because the subject is content rather than people. It measures what a message becomes, not who is growing.",
  ["Absorbs nothing."]],
 ["Church Intelligence","The body","One intelligence for the congregation as a whole, examining identity, reach and growth together because they are one question asked three ways.",
  ["Absorbs Church Vision &amp; Values Intelligence","Absorbs Evangelism Intelligence","Absorbs the growth diagnostic"]],
 ["Ministry Intelligence","Any ministry","The engine. Six dimensions that work on every ministry in the building, which is what makes this a platform rather than seven products.",
  ["Absorbs Volunteer Intelligence","Absorbs Small Group Intelligence","Absorbs Sunday School &amp; ABF Intelligence",
   "Absorbs Discipleship Intelligence","Absorbs Family Intelligence","Absorbs Stewardship Intelligence",
   "Absorbs Church Campaign Intelligence"]],
 ["Christian Life Intelligence","The person","The individual believer, from the original brochure. Distinct because the subject is one ordinary person rather than a leader, a team or a ministry.",
  ["Absorbs nothing. Carried forward unchanged."]],
]

APPS = [
 ["Volunteer","Ministry Intelligence pointed at the serving body"],
 ["Small Group","Pointed at the circles"],
 ["Sunday School and ABF","Pointed at the classroom"],
 ["Discipleship","Pointed at the pathway"],
 ["Family","Pointed at the household"],
 ["Stewardship","Pointed at generosity"],
 ["Campaign","Pointed at a churchwide season"],
 ["Care, Missions, Worship, Men, Women, Students","And every other ministry, using the identical six dimensions"],
]

CONSOL_GAIN = [
 ["Six products instead of thirteen","A pastor can hold six in his head. He cannot hold thirteen, and a catalogue he cannot hold is a catalogue he does not buy."],
 ["Nothing is discarded","Every diagnostic, dimension and tool built here survives. Seven of them become applications of one engine rather than separate products."],
 ["The pricing gets simpler","Six libraries at a per-library price, or all-access. Thirteen line items forces a decision nobody wants to make."],
 ["The engine becomes the story","One set of six questions that works on any ministry is a far better claim than seven ministry-specific products."],
 ["New ministries cost nothing","Recovery Intelligence, Worship Intelligence, Missions Intelligence &mdash; each is a configuration rather than a build."],
]
