# -*- coding: utf-8 -*-
# Catalyst Kit = 1 sermon outline + 7-day devotional + 1 group session
# Four kits, each proving the format under different pressure.

KITS = [
{
"cat":"Resurrection Sunday",
"t":"He's Not Where You Left Him",
"s":"Why the empty tomb undoes every assumption you brought with you",
"x":"Luke 24:1-8 (NIV)",
"b":"The women came to finish a burial and found that God had already moved past the ending they had accepted.",
"m":["They came prepared for the wrong thing. Spices, early light, a plan for a corpse. Grief is efficient; it makes arrangements.",
"The angels' question is the sermon: why look for the living among the dead. It is not a rebuke, it is a reorientation.",
"Remember how he told you. The resurrection was not new information. It was information they had already heard and filed under impossible."],
"story":"A moment when you organized your life around an outcome that had already changed. A diagnosis that came back different. A door you assumed was closed that had been open for months.",
"turn":"Name the place where you have already decided how the story ends. That is the tomb you are standing in front of with spices in your hands.",
"close":"He is not where you left him. He is ahead of you, in the part of the story you stopped reading.",
"why":"The flagship. If the kit format cannot carry Easter morning, it cannot carry anything.",
"dev":[
("Spices in Your Hands","Luke 24:1",
 "They got up while it was still dark, and they brought what they had prepared. Think about that preparation. Someone measured out the spices. Someone wrapped them. Someone decided who would carry what and how early they would need to leave to beat the heat. All of it careful, all of it loving, and all of it aimed at a body that was no longer there.\n\nGrief is not lazy. It organizes. It makes arrangements and sets alarms and shows up on time. That is what makes this moment so tender rather than foolish. These women were not failing. They were doing the last kind thing they knew how to do.\n\nBut they were prepared for a version of the story that God had already moved past. Before you judge them, consider how much of your own week is spent carefully preparing for an ending you have simply assumed.",
 "What have you carefully prepared for that may no longer be the situation you are in?",
 "Write down the one outcome you have quietly accepted as settled. Do not solve it yet. Just name it."),
("Very Early in the Morning","Luke 24:1",
 "Luke tells us the time of day twice in this story, which is his way of saying it matters. It was dark. Nobody was up. There was no crowd to perform for and no reason to go except love.\n\nThere is a particular kind of faithfulness that only happens early, before anyone is watching. It rarely feels like faith while you are doing it. It feels like duty, or habit, or the thing you do because you cannot think of anything else to do.\n\nThat is where these women were. Not hopeful. Not expectant. Just present, in the dark, doing the next obedient thing.\n\nIf that is where you are this week, you are in better company than you think. God has a long history of showing up in the part of the story that happens before dawn.",
 "Where in your life are you doing the next obedient thing without feeling anything?",
 "Do one small faithful thing today that nobody will see or thank you for."),
("They Found the Stone Rolled Away","Luke 24:2",
 "Mark's version tells us they worried about the stone the whole way there. Who will move it. It was far too heavy for them and they knew it. They went anyway, carrying a problem they had no ability to solve.\n\nAnd then they arrived, and it was already handled.\n\nNotice that Scripture gives us no scene of the stone moving. There is no dramatic description, no angel straining. God did it before they got there and did not feel the need to let them watch. The stone was not moved so Jesus could get out. It was moved so they could see in.\n\nSome of what you are carrying up the hill this week has already been dealt with. You will not know until you get there. That is not a promise that every stone moves. It is a reminder that you are not the one who moves them.",
 "What obstacle are you rehearsing that you have not actually checked on yet?",
 "Make the call, send the message, or ask the question you have been dreading. Find out what is actually true."),
("They Did Not Find the Body","Luke 24:3",
 "This is the strangest sentence in the account. The turning point of human history is described as an absence. They looked, and what they were looking for was not there.\n\nGood news does not always arrive as an addition. Sometimes it arrives as a subtraction. The tumor is not there. The debt is not there. The accusation that has followed you for fifteen years is, according to Colossians, no longer on file anywhere.\n\nWe are trained to look for God in what appears. It is worth learning to look for him in what disappears.\n\nThe women stood in an empty room and did not yet understand that empty was the whole point. Give yourself permission to be slow about this too. Understanding usually lags behind the fact.",
 "What is gone from your life that you have not yet recognized as grace?",
 "Name one thing you no longer carry that you carried five years ago. Thank God for the absence."),
("Why Do You Look for the Living Among the Dead?","Luke 24:5",
 "The question is diagnostic, not condemning. The angels are not scolding these women. They are pointing out that the search is aimed at the wrong location.\n\nEveryone has a tomb they keep revisiting. An old version of yourself. A relationship that ended. A career that did not happen. A season when you felt closest to God, which you now visit the way people visit a grave, hoping to feel something.\n\nThere is nothing wrong with remembering. There is something quietly exhausting about looking for life in a place that no longer holds it.\n\nThe question is worth carrying around for a day. Not as an accusation, but as an honest inventory. Where am I looking, and is he actually there?",
 "What place, season, or version of yourself do you keep returning to hoping to find life?",
 "Say out loud where you have been looking. Then ask God where he actually is."),
("Remember How He Told You","Luke 24:6-7",
 "This is the part that should unsettle us. Jesus had told them. More than once, plainly, before it happened. The resurrection was not new information delivered on Sunday morning. It was old information that nobody could hold.\n\nWe do the same thing constantly. We have heard the promise, underlined it, maybe even taught it, and then filed it somewhere in the back where impossible things go. Not disbelieved exactly. Just shelved.\n\nWhich means the cure for standing in front of the wrong tomb is not usually new revelation. It is remembering what he already said.\n\nBefore you ask God for a new word this week, go back and look at what he has already told you and see whether you have been living as though he meant it.",
 "What has God already told you that you have quietly filed under impossible?",
 "Find that promise in Scripture, write it out by hand, and put it somewhere you will see it tomorrow."),
("Then They Remembered","Luke 24:8-9",
 "Luke gives remembering its own sentence, and then immediately tells us what remembering produced. They went back and told the eleven and everyone else.\n\nThat is the whole shape of the Christian life in two verses. Something is true, we remember it, and remembering moves us toward people.\n\nNotice they were not believed. Luke says the apostles thought it was nonsense. The women told the truth and were dismissed by the people who should have known better, and they told it anyway.\n\nYou have spent a week with this story. The question now is not whether you found it moving. It is who you are going to tell, and whether you will still tell them if it lands badly.",
 "Who needs to hear what you have seen this week, even if they may not receive it well?",
 "Tell one person one true thing about what God has done. Today, not eventually."),
],
"grp":{
"open":"Tell us about a time you were completely, carefully prepared for the wrong thing.",
"read":"Luke 24:1-12. Have someone read it aloud slowly, then read it a second time from a different translation if one is available.",
"qs":["The women brought spices to anoint a body. What were they assuming, and what did that assumption cost them in the moment?",
"The angels ask why they are looking for the living among the dead. Where in your own life are you looking for something in a place it is no longer found?",
"Jesus had already told them this would happen. Why do you think they could not hold on to it, and where do you do the same thing?",
"Verse 11 says the apostles did not believe the women. What does it tell us that God chose witnesses who would be dismissed?",
"What would change about this coming week if you actually lived as though the tomb is empty?"],
"personal":["Name the ending you have already accepted, and bring it into prayer daily this week.",
"Find one promise God has already given you that you have shelved. Write it out and put it where you will see it.",
"Do one obedient thing this week that nobody will notice."],
"family":["Read Luke 24:1-8 together at a meal this week and ask each person what surprises them.",
"Tell your children or your spouse about one time God did something you had stopped expecting.",
"Name one family situation you have privately given up on, and pray about it together."],
"group":["Each person names one person to tell this week, and the group follows up next meeting.",
"Identify one member in a long Saturday season and decide together how you will show up for them.",
"Commit to one act of service that only makes sense if the resurrection is true."],
}
},

{
"cat":"Mother's Day, The Hard Track",
"t":"When Mother's Day Hurts",
"s":"Naming it from the platform before the flowers come out",
"x":"1 Samuel 1:9-18 with Psalm 34:18 (NIV)",
"b":"The church's job on Mother's Day is not to celebrate around the pain in the room but to name it first, because God does.",
"m":["Hannah prayed in the temple in a way that looked like drunkenness to the professional clergyman standing there. Grief is often mistaken for something else.",
"Eli got it wrong before he got it right. The church has a long history of misreading pain and a real capacity to correct itself.",
"Psalm 34 does not say God fixes the brokenhearted. It says he is close to them. Proximity is the promise; outcome is not."],
"story":"A moment when someone named the hard thing out loud in a room that expected celebration, and the relief that followed. Do not use a story you have not been given permission to tell.",
"turn":"Name the pain from the platform before the flowers are handed out, not after. Then give a specific next step for the person for whom this day is hard.",
"close":"You are not the only one sitting here today with a knot in your chest. God knows exactly where you are, and he did not need you to pretend.",
"why":"The hardest pastoral Sunday on the calendar. If the kit works here, it works anywhere.",
"dev":[
("Deeply Troubled","1 Samuel 1:10",
 "Scripture does not soften Hannah. It says she was in deep anguish and wept bitterly. There is no attempt to make her more presentable, no note that she kept a good attitude about it.\n\nThat matters, because most of us learned somewhere that faith means managing our face. We learned that the spiritual response to disappointment is a quick pivot to gratitude, and that lingering in the hurt is a sign that something is wrong with our belief.\n\nHannah did not get that memo. She brought her bitterness into the house of God and let it out there.\n\nIf today is hard for you, you do not need to clean it up before you bring it. The temple has always been a place where people wept badly.",
 "Where have you been managing your face instead of bringing the actual thing?",
 "Tell God one true sentence about how you feel, without adding a hopeful clause at the end."),
("Pouring Out Your Soul","1 Samuel 1:15",
 "When Eli accuses her, Hannah's defense is one of the most honest descriptions of prayer in Scripture. She says she has been pouring out her soul to the Lord.\n\nNot presenting a request. Not making a case. Pouring out, the way you empty a container that has gotten too heavy to keep holding level.\n\nMost of us pray as though we are writing a memo. Hannah prayed the way you cry in a parked car.\n\nGod did not correct her posture. Eli did, and Eli was wrong. The only person in that story who understood what was happening was the woman on the floor.",
 "What have you been carrying that you have never actually poured out?",
 "Find fifteen minutes and a place where nobody will interrupt you, and say all of it out loud."),
("When the Church Gets It Wrong","1 Samuel 1:13-14",
 "The priest looked at a grieving woman and assumed she was drunk. He was the spiritual authority in the building and he read her completely backwards.\n\nSome of you have been on the receiving end of that. A comment about how everything happens for a reason. A well-meant question about when you are going to have children. A card handed to you in the lobby on a day you were barely holding together.\n\nHere is what is worth noticing. Eli was wrong, and the story does not end there. When Hannah told him the truth, he changed his response and blessed her.\n\nThe church misreads pain. The church can also learn. Do not let the person who got it wrong become the reason you stop bringing it.",
 "Has someone in the church misread your pain? What did it cost you?",
 "If you can, tell one trusted person what you actually needed and did not get."),
("Close to the Brokenhearted","Psalm 34:18",
 "The promise here is more specific than we usually preach it. It does not say God fixes the brokenhearted or explains things to them or shortens their season.\n\nIt says he is close.\n\nThat is either deeply insufficient or it is the only thing that has ever actually helped, depending on the day. Most people who have walked through real grief will tell you it is the second one. What they remember is not the advice. It is who sat down.\n\nGod's first response to a crushed spirit is proximity. Not a lesson. Not a silver lining. Presence.\n\nWhich means you are not waiting for God to show up on the other side of this. He is already sitting in it with you.",
 "Do you experience God as close right now, or as distant? Say which, honestly.",
 "Ask God for a sense of his nearness today rather than for an explanation."),
("Refusing to Be Comforted","Jeremiah 31:15-17",
 "Jeremiah describes Rachel weeping for her children and refusing to be comforted. What is remarkable is that God does not rebuke her for the refusal.\n\nHe lets the grief stand in the text. And then, without minimizing it, he speaks a promise over it.\n\nWe are usually in a hurry to get people to the promise. God is not. He allows the weeping to be recorded first, in full, and only then says there is hope for your future.\n\nIf you have been told that your grief has gone on too long, notice that Scripture is more patient with you than people have been.",
 "Have you been rushed through your grief by someone, or by yourself?",
 "Give yourself permission today to not be finished grieving. Say it plainly to God."),
("She Went Away and Ate Something","1 Samuel 1:18",
 "This is the verse that changes the story, and nothing external has changed yet. She is not pregnant. Nothing has been promised except a blessing from a priest who had misjudged her ten minutes earlier.\n\nAnd she goes away, eats something, and her face is no longer downcast.\n\nWhat shifted was not her circumstance. It was that she had finally been able to put it down somewhere.\n\nThere is a kind of relief available before resolution. It is not denial and it is not pretending. It is what happens when you stop carrying something alone.\n\nIf you have been waiting to feel better until the situation changes, this verse is an invitation to a different order of operations.",
 "What would it look like to eat something and rest, before anything is resolved?",
 "Do one ordinary, restorative thing today. A meal, a walk, a full night's sleep. Treat it as obedience."),
("God Sets the Lonely in Families","Psalm 68:5-6",
 "God's self-chosen titles in this psalm are father to the fatherless and defender of widows. He identifies himself by who he shows up for.\n\nAnd then the psalm says he sets the lonely in families. Not that he removes loneliness in the abstract, but that he places people with people.\n\nWhich means the answer God most often gives to isolation is a room, a table, a group of ordinary believers who make space.\n\nIf today has been hard, the next step is probably not more solitude with a Bible. It is likely a person. That feels like the harder assignment, which is usually a sign it is the right one.",
 "Who is the one person you could tell about this week?",
 "Reach out to one person today. Not to explain everything. Just to stop being alone with it."),
],
"grp":{
"open":"Was there a day on the calendar this year that was harder than you expected? You do not have to say why.",
"read":"1 Samuel 1:9-18, then Psalm 34:18. Read slowly. Allow silence afterward before anyone speaks.",
"qs":["Hannah wept bitterly in the house of God. What does it do to your picture of faith that Scripture records this without correcting her?",
"Eli misread her completely. When has the church misread pain, and what would it look like to do better?",
"Psalm 34 promises nearness rather than repair. Is that enough for you right now? Answer honestly.",
"Hannah's face changed before her circumstance did. What made that possible?",
"Who in our circles is carrying something on days everyone else is celebrating?"],
"personal":["Tell one trusted person the true version of how you are doing.",
"Write out the prayer you have been afraid to pray, and pray it once out loud.",
"Do one restorative thing this week and treat it as obedience rather than indulgence."],
"family":["Talk with your family about who in your extended family finds this season hard.",
"Choose one relative or friend to check on with no agenda and no advice.",
"Tell your children age-appropriately about a time you grieved and God stayed close."],
"group":["Each member names one person for whom the next holiday will be hard, and the group commits to a specific act of care.",
"Decide as a group how you will mark hard days going forward rather than skipping past them.",
"Identify whether anyone in this group needs help beyond what we can give, and help them find it."],
}
},

{
"cat":"Series Launch and Friends Sunday",
"t":"Who Are You Bringing?",
"s":"The invitation is the assignment",
"x":"John 1:40-42 (NIV)",
"b":"The most consistent thing Andrew ever does in the gospels is bring someone to Jesus, and it required no training, no argument, and no theological degree.",
"m":["Andrew appears three times in John, and all three times he is bringing someone. It is the entire shape of his ministry.",
"The first thing he did was find his own brother. Not a stranger, not a project. The person already at his table.",
"He brought him to Jesus. He did not convince him, correct him, or prepare him. He moved him into proximity and let Jesus do the rest."],
"story":"The person who brought you. Name them from the platform if they are living and you have permission. If not, describe the moment.",
"turn":"Hand out the card. Have people write one name on it during the service, not after. Then tell them exactly what next week is and what to say.",
"close":"Somebody brought you. That is why you are sitting here. This week, be that for one person.",
"why":"The campaign hinge in its purest form. This kit has to produce a filled room next Sunday or it has failed.",
"dev":[
("The First Thing He Did","John 1:41",
 "John records the sequence carefully. Andrew spends a day with Jesus, and then the first thing he does is go find his brother.\n\nNot the first thing after he studied. Not the first thing after he was sure. The first thing.\n\nThere is something clarifying about that. Andrew had roughly one day of information. He could not have answered a hard question about anything. What he had was an encounter and a brother, and he put the two together.\n\nMost of us have been waiting until we feel qualified. Andrew suggests the qualification is considerably lower than we assumed, and the window is considerably earlier.",
 "Who is the person you would go find first if you were not worried about doing it wrong?",
 "Write that person's name down somewhere you will see it every day this week."),
("He Brought Him to Jesus","John 1:42",
 "Read the verb again. He brought him. Not persuaded, not convinced, not won.\n\nThis is the single most freeing sentence in evangelism. Your job is transportation, not transformation. You get someone into proximity. What happens next is not yours to engineer, and honestly never was.\n\nWe have made this so much heavier than it is. We rehearse arguments and worry about follow-up questions and decide we are not the right person.\n\nAndrew got his brother into the room. Jesus renamed him on the spot. Andrew did not do that part and was never asked to.",
 "What have you been assuming is your job that is actually God's?",
 "Say this out loud: my job is to bring, not to convince. Then decide what bringing looks like this week."),
("Come and See","John 1:46",
 "Nathanael's objection is a real one and it is dismissive. Can anything good come from Nazareth. He has already decided.\n\nPhilip does not argue. He does not build a case or take offense. He says four words: come and see.\n\nThat is the oldest and still the best response to skepticism. Not a counterargument, an invitation. It refuses to fight and it refuses to give up, and it puts the burden where it belongs, on the encounter rather than on your debating skill.\n\nIf someone in your life has an objection, you do not have to answer it this week. You have to invite them anyway.",
 "What objection have you been trying to answer when you should have been inviting?",
 "Practice saying come and see. Out loud, in your own words, until it sounds like you."),
("She Told the Whole Town","John 4:28-30, 39",
 "The Samaritan woman had a complicated history, no standing in her community, and about twenty minutes of theological education.\n\nShe left her water jar, went back to the town that had every reason to dismiss her, and told them. John says many believed because of her testimony.\n\nHer message was not sophisticated. Come and see a man who told me everything I ever did. That is it. Her whole evangelistic method was reporting what happened to her.\n\nYou have that. Whatever else you lack, you have what happened to you, and nobody can argue with it.",
 "What is the one-sentence version of what God has done in your life?",
 "Write it down in under thirty words. Practice saying it until it is natural."),
("Four Men and a Roof","Mark 2:1-5",
 "The house was full. There was no way in. So they went up on the roof, dug through it, and lowered their friend down in front of Jesus.\n\nMark says something startling next. When Jesus saw their faith. Not his. Theirs.\n\nSometimes a person cannot get themselves there. They are too tired, too skeptical, too hurt by church, too far into something. And the faith that carries them is not their own.\n\nThat is a heavier and more beautiful assignment than handing out an invitation. It means some people in your life are waiting on your persistence, not on their own readiness.",
 "Who in your life cannot get there on their own right now?",
 "Do one concrete thing for that person this week. Drive them, sit with them, or simply keep showing up."),
("What If They Say No?","1 Corinthians 3:6-7",
 "Here is the fear that stops most people. You ask, they decline, and now it is awkward forever.\n\nPaul's answer reframes the whole thing. One plants, another waters, God makes it grow. You are one step in a process you will mostly not get to see.\n\nA no this year is not a verdict. It is a seed in the ground, and someone else may water it in four years.\n\nThe only real failure available to you is not asking, because that is the one outcome that guarantees nothing was planted at all.",
 "What is the actual worst case if you ask and they say no?",
 "Ask anyway. This week. Decide the day right now."),
("Write the Name Down","Colossians 4:2-6",
 "Paul gives a short, practical sequence. Pray. Watch for the open door. Be wise in how you act toward outsiders. Make the most of the opportunity. Let your conversation be full of grace, seasoned with salt.\n\nThat is the whole method. Pray for them, watch for the moment, speak with warmth rather than pressure.\n\nYou have carried a name for a week now. You have prayed over it, thought about your own story, and decided what you would say.\n\nToday is the day. Not because there is anything magic about today, but because a week from now the resolve will have faded and the name will still be on the paper.",
 "Is there anything still stopping you, and is it a real obstacle or just discomfort?",
 "Send the message. Make the call. Extend the actual invitation today."),
],
"grp":{
"open":"Who brought you? Tell us about the person who first got you into a room where you met Jesus.",
"read":"John 1:35-42, then Mark 2:1-5.",
"qs":["Andrew had roughly one day of information before he went and found his brother. What does that do to the idea that you need to be ready?",
"John says Andrew brought him to Jesus. What is the difference between bringing someone and convincing someone, and which one have you been attempting?",
"Philip answered a dismissive objection with an invitation rather than an argument. When has that worked on you?",
"Jesus responded to the faith of the four friends, not the paralyzed man. Who in your life is waiting on someone else's persistence?",
"What is the real reason you have not invited the person you are thinking of right now?"],
"personal":["Write one name down and pray for that person every day this week.",
"Write your story in under thirty words and practice saying it out loud.",
"Extend the invitation before this group meets again."],
"family":["Decide as a household who you are inviting, and invite them together.",
"Plan the meal or the coffee after the service before you extend the invitation.",
"Let your children see you invite someone, and talk about it afterward."],
"group":["Every member brings one person during this series, and we make room for them here afterward.",
"Assign one member to follow up with each guest within forty-eight hours.",
"Hold one open chair in this group all season and pray over it by name."],
}
},

{
"cat":"Group Life Launch",
"t":"You Were Not Built to Do This Alone",
"s":"The case for group life",
"x":"Acts 2:42-47 with Ecclesiastes 4:9-12 (NIV)",
"b":"The New Testament has no category for a solitary Christian, because formation happens in proximity and cannot be achieved in rows.",
"m":["They devoted themselves to four things and held all four together. Teaching, fellowship, breaking bread, prayer. Remove any one and the shape collapses.",
"Verse 46 tells us where it happened. In the temple courts and in their homes. Both. The large gathering and the living room were never in competition.",
"Ecclesiastes is blunt about the alternative. If one falls down alone, there is nobody to help them up. That is not a motivational line, it is a warning."],
"story":"A specific person in this church whose life changed in a small group. Get permission and let them tell it in ninety seconds rather than describing it yourself.",
"turn":"Registration happens today, in the lobby, before anyone leaves. Every additional day between the message and the signup costs you people.",
"close":"You can attend this church for a decade and never be known. That is not the church's fault and it is not yours. It is a decision, and you can make it in the next ten minutes.",
"why":"The retention Sunday. This is the kit that determines whether everyone Easter brought in is still here in March.",
"dev":[
("They Devoted Themselves","Acts 2:42",
 "Four things, listed together, all governed by one verb. Devoted.\n\nThe teaching, the fellowship, the shared meals, the prayers. We tend to rank these, treating teaching as essential and fellowship as optional, the spiritual part and the social part.\n\nLuke does not rank them. He lists them as a single practice.\n\nWhich means the meal is not the warm-up act for the study. The conversation in the kitchen is not what happens before the real thing starts. In Acts 2 it was all the real thing, and the church that came out of it turned the ancient world upside down.",
 "Which of the four have you quietly treated as optional?",
 "Name the one you have been skipping and decide what adding it back would require."),
("Two Are Better Than One","Ecclesiastes 4:9-10",
 "The reasoning here is unsentimental. Two are better than one because they get a better return on their work, and because if one falls down the other can help them up.\n\nThen the writer adds the line that lands hardest. Pity anyone who falls and has no one to help them up.\n\nThis is not a passage about how nice friendship is. It is about what happens when you go down and there is nobody there.\n\nMost people do not decide to isolate. They just never decide not to, and then something happens and the room is empty.",
 "If you fell down this month, who would actually notice?",
 "Name three people who would notice. If you cannot name three, that is the finding."),
("A Cord of Three Strands","Ecclesiastes 4:12",
 "One can be overpowered. Two can defend themselves. A cord of three strands is not quickly broken.\n\nThe image is worth sitting with, because a rope is not three separate strings lying next to each other. The strength comes from being wound together, under tension, over time.\n\nThat is what a group is. Not proximity, not attendance. Braided.\n\nAnd braiding takes longer than one meeting. It requires showing up when it is inconvenient and staying past the point where it is still novel.",
 "Are you near people, or actually braided into their lives?",
 "Identify one relationship where you are near but not woven in, and take one step closer this week."),
("They Broke Bread in Their Homes","Acts 2:46",
 "Every day, Luke says. They met in the temple courts and they broke bread in their homes.\n\nThe temple was the large gathering. The homes were where they ate. Both are named, and neither replaced the other.\n\nThis is worth saying clearly because a lot of people have been told that small groups are a program the church invented to solve an attendance problem. They are not. The house was there from the first week, and the church grew out of both rooms at once.\n\nThere is something a living room does that a sanctuary cannot, and it has nothing to do with the quality of the preaching.",
 "What do you get in a living room that you cannot get in a sanctuary?",
 "Offer your home once this season, even if you are not the one leading."),
("Carry Each Other's Burdens","Galatians 6:2",
 "Paul says carrying each other's burdens fulfills the law of Christ. That is unusually strong language for something that sounds like ordinary friendship.\n\nBut notice the mechanics. You cannot carry a burden you do not know about. Which means this verse quietly requires two things, not one. Someone willing to carry, and someone willing to say what they are carrying.\n\nMost of us have practiced the first half and avoided the second. We will help anyone. We will tell no one.\n\nA group where everybody is carrying and nobody is disclosing is not a group. It is a room full of very kind, very lonely people.",
 "Are you better at carrying or at disclosing? Be honest about the imbalance.",
 "Tell one person one true thing you are carrying this week."),
("Not Giving Up Meeting Together","Hebrews 10:24-25",
 "The instruction is usually quoted as an attendance rule, which misses what the writer actually says. The purpose named is to spur one another on toward love and good deeds.\n\nMeeting together is the mechanism. Provocation toward love is the point.\n\nThat reframes what a group is for. It is not primarily comfort, and it is not primarily information. It is a room designed to move you toward things you would not do on your own.\n\nWhich means a good group should occasionally be uncomfortable. If nobody has ever pushed you in it, it may be pleasant, but it is not doing the job Hebrews describes.",
 "When was the last time someone spurred you toward something you were avoiding?",
 "Give one person in your life explicit permission to ask you a hard question."),
("The Body Has Many Parts","1 Corinthians 12:14-22",
 "Paul spends most of a chapter on a single point. The body needs every part, including the parts that seem weaker and the parts nobody sees.\n\nHe is arguing against two opposite errors, and both are alive in every church. The first says I am not needed here. The second says I do not need them.\n\nBoth are described in this chapter as impossible. The foot cannot opt out. The eye cannot dismiss the hand.\n\nYou have spent a week considering what community would cost you. It is worth ending on what your absence costs everyone else.",
 "Which error is more yours: I am not needed, or I do not need them?",
 "Register for a group and sign up for one serving team. Do both before the week ends."),
],
"grp":{
"open":"What is the best group, team, or circle you have ever been part of, and what made it work?",
"read":"Acts 2:42-47, then Ecclesiastes 4:9-12.",
"qs":["Luke lists teaching, fellowship, breaking bread, and prayer under one verb. Which have you treated as optional, and why?",
"Ecclesiastes says pity the one who falls and has no one to help them up. Have you been in that position? What happened?",
"They met in the temple courts and in their homes. What does a living room do that a sanctuary cannot?",
"Hebrews says the point of meeting is to spur one another toward love and good deeds. Is that happening here? Answer honestly.",
"Paul says the body needs every part. Which error is more natural for you, thinking you are not needed or thinking you do not need anyone?"],
"personal":["Commit to six weeks with this group and put every date on your calendar tonight.",
"Tell one person in this room one true thing you are carrying.",
"Sign up for one serving team this week."],
"family":["Choose one shared spiritual rhythm your household will keep for six weeks.",
"Eat one unhurried meal together each week with phones in another room.",
"Serve somewhere together once this season."],
"group":["Keep one chair open all season and pray for the person who will fill it.",
"Identify and encourage one member who could host or lead a new group next semester.",
"Decide now what this group will do for someone outside it before the six weeks end."],
}
},
]
