# -*- coding: utf-8 -*-

DRAFTS = {
"He's Not Where You Left Him":[
"They left while it was still dark.",
"Luke tells us the time twice in this account, which is his way of saying it matters. It was early. Nobody else was up. There was no crowd to perform for and nothing to gain by going, and they went anyway, carrying spices they had prepared the night before.",
"Sit with that preparation for a second, because it is the most tender detail in the story. Somebody measured those spices out. Somebody wrapped them and set them by the door. Somebody worked out who would carry what and how early they would have to leave to beat the heat. All of it careful. All of it loving. And all of it aimed at a body that was no longer in the tomb.",
"Grief is not lazy. That is the thing nobody tells you about it. Grief organizes. It makes arrangements and sets alarms and shows up on time, because doing the next practical thing is sometimes the only way through a Tuesday. These women were not failing at faith. They were doing the last kind thing they knew how to do for someone they loved.",
"But they were prepared for a version of the story that God had already moved past.",
"[ILLUSTRATION &mdash; a time you organized your life around an outcome that had already changed]",
"Then they get there, and the stone is gone.",
"Mark tells us they worried about that stone the whole walk. Who will roll it away for us. It was far too heavy for the three of them and they knew it before they left the house, and they went anyway, carrying a problem they had no ability to solve.",
"Notice what Scripture does not give us. There is no scene of the stone moving. No description, no straining angel, no sound. God handled it before they arrived and did not feel any need to let them watch. And the stone was not moved so Jesus could get out &mdash; he was already gone. It was moved so they could see in.",
"Two men in clothes that gleamed like lightning, and one question. Why do you look for the living among the dead?",
"I want to be careful here, because that question gets preached as a rebuke and it is not one. These women were doing something loving. They were also, at that exact moment, searching a location that no longer held what they came for. The question is diagnostic, not condemning.",
"And everybody in this room has a tomb they keep going back to. An old version of yourself that you liked better. A relationship that ended, and you still drive past the house. A career that did not happen. A season when you felt closer to God than you do now, which you revisit the way people visit a grave, standing there hoping to feel something.",
"Then comes the sentence that should unsettle anyone who has been in church a while. Remember how he told you.",
"He had told them. Plainly, more than once, before any of it happened. The resurrection was not new information delivered on Sunday morning. It was old information that nobody had been able to hold.",
"We do that constantly. We hear the promise, underline it, maybe even teach it, and then file it somewhere in the back where impossible things go. Not disbelieved exactly. Just shelved. Which means the cure for standing in front of the wrong tomb is usually not new revelation. It is remembering what he already said.",
"[ILLUSTRATION &mdash; a promise you have known for years and never leaned on]",
"Luke gives remembering its own sentence. Then they remembered his words. And the very next thing he tells us is that they went back and told the eleven and everyone else.",
"They were not believed, incidentally. Luke says the apostles thought it was nonsense. These women told the truth and were dismissed by the people who should have known better, and they told it anyway.",
"So here is where I want to leave you. Somewhere in your life there is an ending you have already accepted. You have made the arrangements. You have measured out the spices. And you are walking toward a situation you have privately decided is finished.",
"He is not where you left him. He is ahead of you, in the part of the story you stopped reading."],

"When Mother's Day Hurts":[
"Before we do anything else this morning, I want to say something to a specific group of people in this room, and I want to say it before the flowers come out rather than after.",
"For some of you, today is hard. Not mildly awkward. Hard. You buried your mother this year. You wanted to be a mother and it has not happened. You lost a pregnancy that most people here never knew about. Your relationship with your mother is broken and you are not sure it can be repaired. Or you are a mother and you are carrying a private conviction that you have failed at it.",
"You did not need me to tell you that. But you may have needed to hear that somebody at the front of the room knows you are here.",
"There is a woman in Scripture who would understand this morning completely. Her name is Hannah, and the first thing the Bible tells us about her prayer life is that she wept bitterly.",
"Not that she prayed with quiet confidence. Not that she kept a good attitude. She was in deep anguish, and she brought all of it into the house of God and let it out there.",
"That matters, because most of us learned somewhere along the way that faith means managing your face. We learned that the spiritual response to disappointment is a quick pivot to gratitude, and that lingering in the hurt means something has gone wrong with your belief. Hannah did not get that memo. She prayed the way you cry in a parked car.",
"[ILLUSTRATION &mdash; a moment when honesty was more useful than composure]",
"And here is the part of the story the church needs to hear about itself.",
"Eli, the priest, watched her praying and concluded she was drunk. The spiritual authority in the building looked at a grieving woman and read her completely backwards.",
"Some of you have been on the receiving end of that. A comment about how everything happens for a reason. A cheerful question about when you are going to have children, asked in a hallway by someone who meant nothing by it. A card handed to you in a lobby on a day you were barely holding together.",
"I want to say plainly that when the church does that, the church is wrong. And I want you to notice what happens next in the text, because it is important. Hannah tells him the truth. She says she is not drunk, she is pouring out her soul to the Lord. And Eli changes. He blesses her.",
"The church misreads pain. The church can also learn. Please do not let the person who got it wrong become the reason you stop bringing it here.",
"Now I want to give you the promise, and I want to be careful about what it does and does not say.",
"Psalm 34 says the Lord is close to the brokenhearted and saves those who are crushed in spirit. It does not say he fixes them on a schedule. It does not say he explains it. It says he is close.",
"That is either deeply insufficient, or it is the only thing that has ever actually helped, depending on what kind of day you are having. Most people who have walked through real grief will tell you it is the second one. What they remember is not the advice anybody gave them. What they remember is who sat down.",
"[ILLUSTRATION &mdash; the person who showed up and said nothing]",
"There is one more detail in Hannah's story that I do not want you to miss. After she prays, and after Eli blesses her, verse eighteen says she went away and ate something, and her face was no longer downcast.",
"Nothing had changed yet. She was not pregnant. Nothing had been promised except a blessing from a priest who had misjudged her ten minutes earlier. What shifted was that she had finally been able to put it down somewhere.",
"There is a kind of relief available before resolution. It is not denial and it is not pretending. It is what happens when you stop carrying something alone.",
"So here is what I want you to do today, and it is small. If this day is hard for you, tell one person the true version. Not the version where you are fine.",
"And to everyone else in this room, hear this: you are almost certainly sitting near somebody for whom today is heavy. You do not need the right words. You need to sit down.",
"You are not the only one here with a knot in your chest this morning. God knows exactly where you are, and he never needed you to pretend."],

"Who Are You Bringing?":[
"I want to tell you about the least famous of the twelve disciples, and then I want to give you an assignment.",
"His name is Andrew, and he appears three times in John's gospel. Here is what is remarkable about that. All three times, he is bringing somebody to Jesus.",
"Chapter one, he brings his brother. Chapter six, he brings the boy with the loaves and fish. Chapter twelve, he brings some Greeks who have asked to see Jesus. That is the entire recorded ministry of Andrew. He is the guy who is always bringing someone.",
"Look at how the first one happens, because the details matter more than they look like they do.",
"Andrew spends one day with Jesus. One. And then the very first thing he does is go find his brother Simon.",
"Not the first thing after he studied. Not the first thing after he was confident he could answer questions. The first thing.",
"That should clarify something for a lot of us. Andrew had roughly a day of information. He could not have defended a single doctrine. What he had was an encounter and a brother, and he put the two together.",
"[ILLUSTRATION &mdash; the person who brought you, and what they actually said]",
"Now read the next verb, because this is the sentence that sets people free.",
"He brought him to Jesus.",
"Not persuaded him. Not convinced him. Not won the argument and then walked him in. He brought him.",
"Your job is transportation. It was never transformation.",
"We have made this so much heavier than it is. We rehearse arguments in the shower. We worry about the follow-up question we will not be able to answer. We decide that somebody else in the church is better equipped, and then we do nothing for eleven years.",
"Andrew got his brother into the room. Jesus renamed him on the spot and built a church on him. Andrew did not do that part, and he was never asked to.",
"Philip does the same thing one paragraph later, and he does it under pressure. He invites Nathanael, and Nathanael responds with an insult about Nazareth. He has already decided.",
"Philip does not argue. He does not build a case or take offense. He says four words. Come and see.",
"That is still the best available response to skepticism. Not a counterargument, an invitation. It refuses to fight and it refuses to give up, and it puts the weight where it belongs, on the encounter rather than on how well you debate.",
"[ILLUSTRATION &mdash; an objection you tried to answer when you should have just invited]",
"Let me raise the one thing that is actually stopping most of you, because it is not theology.",
"It is that you are afraid they will say no, and then it will be awkward at work forever.",
"Paul answers that in one line. One plants, another waters, God makes it grow. You are one step in a process you will mostly never get to see. A no this year is not a verdict; it is a seed in the ground that somebody may water four years from now.",
"The only real failure available to you is not asking, because that is the only outcome that guarantees nothing was planted at all.",
"So here is the assignment, and we are going to do it right now rather than talking about doing it.",
"There is a card in your seat. I want you to write one name on it. Not five. One.",
"Ask God for the name. Take a second. I will wait, and it is going to feel long, and that is fine.",
"[PAUSE &mdash; do not fill this. Let it be uncomfortable.]",
"Now look at it. That is not a project. That is a person who has a whole life and a set of reasons and a Tuesday afternoon just like yours.",
"Somebody wrote your name down once. That is why you are sitting in this room.",
"This week, be that for one person."],

"You Were Not Built to Do This Alone":[
"I want to start with a sentence from Ecclesiastes that is more blunt than anything you will hear in a worship song.",
"Pity anyone who falls and has no one to help them up.",
"That is not a passage about how nice friendship is. It is about what happens when you go down and the room is empty.",
"And most people do not choose isolation. Nobody wakes up at thirty-four and decides to have no one. What happens is that they simply never decide the other way, and then something goes wrong, and they discover the room is empty at exactly the moment they cannot do anything about it.",
"[ILLUSTRATION &mdash; a season when you needed someone and had to think about who to call]",
"Let me show you what the first church actually did, because it is more ordinary than we make it sound.",
"Acts chapter two, verse forty-two. They devoted themselves to the apostles' teaching and to fellowship, to the breaking of bread and to prayer.",
"Four things, and one verb governing all of them. Devoted.",
"We tend to rank these. Teaching is the essential part; fellowship is the optional part. The spiritual thing and the social thing. Luke does not rank them. He lists them as a single practice.",
"Which means the meal is not the warm-up for the study. The conversation in the kitchen is not what happens before the real thing starts. In Acts two it was all the real thing, and the community that came out of it turned the ancient world upside down inside a generation.",
"Four verses later, Luke tells us where it happened. They met every day in the temple courts, and they broke bread in their homes.",
"Both. The large gathering and the living room, and neither one replaced the other.",
"I want to be honest with you about what that means for this church. What we do in this room is good and it is not sufficient. You can sit in this seat every Sunday for ten years and never once be known, and that will not be my fault or yours. It will just be what happens when nobody decides otherwise.",
"[ILLUSTRATION &mdash; someone whose life changed in a small room, told by them if possible]",
"Paul gives the picture in First Corinthians twelve, and he spends most of a chapter on one point. The body needs every part, including the parts that seem weaker and the parts nobody sees.",
"He is arguing against two opposite errors, and both are in this room right now.",
"The first says I am not needed here. There are plenty of people, the church is fine, nobody would notice. The second says I do not need them. I am fine on my own, I read, I pray, I have my faith.",
"Paul describes both as physically impossible. The foot cannot opt out of the body. The eye cannot dismiss the hand.",
"Here is what I am actually asking. Not for a lifetime. Six weeks.",
"Six weeks, one room, a handful of people, and a set of questions somebody else already wrote so nobody has to teach. That is the entire commitment.",
"If it is not for you, six weeks from now you will know, and nobody will chase you.",
"But I would ask you to consider the possibility that the thing you have been missing is not more information. You have been to a lot of services. You know a great deal.",
"What you may not have is three people who would notice.",
"The leaders are standing at the front with signs. They have a neighborhood and a night on them. When we finish, do not walk past them.",
"Two are better than one. That is not a sentiment. It is a warning with a solution attached."],

"Light in the Dark":[
"We are about to do something a little strange, and I want to tell you why before we do it.",
"In a few minutes we are going to turn off every light in this building. And then we are going to light one candle, and pass the flame from that candle to the person next to you, and to the person next to them, until this whole room is lit by fire that started in one place.",
"We do that every year, and I think most of us have stopped asking why.",
"Here is why. Because the claim of Christmas is not that the darkness is imaginary. It is a claim about what the darkness has never once been able to do.",
"John begins his gospel with no shepherds, no manger, no star. He begins before all of it. In the beginning was the Word, and the Word was with God, and the Word was God.",
"Before Bethlehem. Before Mary. Before the world existed to need saving.",
"[ILLUSTRATION &mdash; something small that changed a whole room]",
"Then John says something that should stop us. Through him all things were made.",
"Which means the one lying in a feed trough that night had made the wood it was built from. He had made the animals standing around it. He had made the lungs he was learning to use.",
"In him was life, and that life was the light of all mankind.",
"Notice the order. Life first, then light. The light is not a rule we are given or a standard we are measured by. It is what life looks like when it is present in a room.",
"And then verse five, which is the sentence I want you to carry out of here tonight.",
"The light shines in the darkness.",
"Present tense. Not shone, once, two thousand years ago in a stable in an occupied province. Shines. Right now. In this room, into whatever you walked in here carrying tonight.",
"Some of you had a genuinely good year and you came tonight full. I am glad you are here.",
"Some of you came tonight and the seat next to you is empty for the first time. Some of you are holding a diagnosis, or a marriage that is quieter than it used to be, or a January you are already dreading.",
"John is not asking you to pretend about any of that. He names the darkness in the same sentence. He simply refuses to let it have the last word.",
"[ILLUSTRATION &mdash; a light in a genuinely dark place, from your own life]",
"And the darkness has not overcome it.",
"The word John chooses there carries two meanings at once, and scholars have argued about which one he meant for centuries. It can mean the darkness did not understand it. It can also mean the darkness could not put it out.",
"I have come to think he meant both, and that he knew exactly what he was doing.",
"Because here is what is true about light and dark, and it is not a fair fight. Darkness is not a substance. It is an absence. It cannot advance into a lit room. It cannot push back. One candle in a dark space wins, every time, and no amount of dark has ever extinguished a single flame.",
"Which means you were never asked to be the sun.",
"You do not have to fix your family this year. You do not have to have answers for everything your kids are asking. You are not responsible for the state of the world.",
"You have to be one candle. That is the whole assignment, and it is enough, because of the way the math works.",
"So in a moment the lights are going down. Hold your candle. Let it stay dark a little longer than is comfortable.",
"And then watch what one flame does to this room."],

"Do Not Rush This":[
"We are going to take communion this morning, and we are going to take a long time doing it.",
"I want to tell you why up front, because if I do not, some of you will spend the next twenty minutes wondering whether something has gone wrong with the schedule.",
"Nothing has gone wrong. This is the schedule.",
"Most of us have received communion hundreds of times, almost always in the last six minutes of a service, usually while a song plays and the band prepares for the closing number. We have taken the most theologically dense thing this church does and given it the slot we give announcements.",
"I do not think that was a decision anyone made. I think it is just what happened. But I want to undo it this morning.",
"[ILLUSTRATION &mdash; something you rushed for years before you slowed down and saw it]",
"Paul writes about this table in First Corinthians eleven, and the first thing he does is give us a timestamp.",
"On the night he was betrayed.",
"He could have said on the night before he died. He could have said at the Passover meal. He chose the detail that hurts.",
"Because Judas was at that table. Jesus knew, and served him anyway. He handed bread to the man who had already been paid to hand him over.",
"If you have ever wondered whether you belong at this table, sit with that for a second. The first communion service in history included someone who was actively betraying the host, and the host served him personally.",
"Then Paul says something easy to read past. When he had given thanks, he broke it.",
"Gratitude came before the breaking. Jesus gave thanks over bread that he was about to use to describe his own body being torn apart.",
"I do not fully know what to do with that. I only know that I want to be the kind of person who can give thanks before the cost, and I am not there yet.",
"This is my body, which is for you. Do this in remembrance of me.",
"Remembrance, in Scripture, is almost never a feeling. It is an act. Israel did not remember the exodus by thinking warm thoughts about it. They remembered it by eating a specific meal on a specific night, every year, for centuries, with their children asking why.",
"That is what this is. Not a mood. A practice, done with your hands, that puts something true back into your body when your mind has drifted.",
"[ILLUSTRATION &mdash; a practice in your family that carries meaning without needing explanation]",
"And there is one more phrase that almost nobody mentions.",
"Whenever you eat this bread and drink this cup, you proclaim the Lord's death until he comes.",
"Until he comes. This table looks forward as much as it looks back. Every time we do this we are saying that we expect an ending we have not seen yet.",
"So here is how we are going to do it.",
"There is one loaf on this table. Not trays, not cups arranged in rows. One loaf, and you are going to come and tear from it, and then serve the person you came with. Say their name. Tell them this is the body of Christ, broken for them.",
"If you came alone, come to me, or come to one of the people standing at the front, and we will serve you and we will use your name.",
"Before you come, I want to give you two minutes of quiet. If there is somebody you need to make peace with, Jesus was fairly direct about doing that before you approach the altar rather than after. Send the message now. I will wait.",
"Then come. And do not hurry."],
}

DELIVERY = {
"steps":[
("One &mdash; Block the hour, once",
"Put a recurring ninety-minute block on the calendar the week before each message. Ninety, not sixty, because the first fifteen minutes are always setup and the last fifteen are always the take you redo. Do it the same day every time and it becomes a habit instead of a decision."),
("Two &mdash; Build the corner once and never move it",
"One chair, one background, one window to your left or right. Mark the chair legs on the floor with tape. If the corner is permanent, every future shoot starts at minute zero rather than minute twenty, and seven weeks of videos look like a series instead of seven unrelated clips."),
("Three &mdash; Lay out seven shirts",
"This is the whole trick. Seven shirts on hangers, in order, changed between takes. Two minutes of wardrobe is the entire difference between an hour of work and something that looks like a week of daily discipline. Nothing else you do will matter as much as this."),
("Four &mdash; Shoot all seven without watching any of them",
"Phone horizontal, locked on anything stable, ninety seconds each. Know the six beats and talk &mdash; do not memorize, because memorized delivery is the one thing a congregation can hear immediately. If a take runs past two minutes, stop and start over rather than fixing it later. Reviewing between takes is what turns one hour into four."),
("Five &mdash; Hand it off and forget it",
"Everything goes to one person &mdash; files, the sermon title, and your two-sentence note for each day. They trim, caption, schedule, and send. You do not touch it again. The pastor who edits his own videos stops making them by week three, every single time."),
],
"emails":[
(1,"Spices in Your Hands","I have been thinking about the fact that those women brought burial spices to a tomb that was already empty. I do that more than I would like to admit. Watch this one before you look at your calendar today."),
(2,"Very Early in the Morning","Short one today, about doing the right thing when you feel nothing at all. If that is where you are this week, this one is for you specifically."),
(3,"The Stone Was Already Moved","This is the one I needed most while I was preparing this series. If you are rehearsing something you are dreading, give me three minutes."),
(4,"They Did Not Find the Body","Today is about the good news that shows up as an absence rather than an addition. It took me a long time to learn to look for God in what disappears."),
(5,"Why Look Among the Dead?","Fair warning, this one asks a question I am still answering myself. Everybody has a place they keep going back to."),
(6,"Remember How He Told You","We are almost through the week. Today is about the promise you already have and have quietly filed away. I would love to hear which one came to mind."),
(7,"Then They Remembered","Last one. It ends with an assignment rather than an encouragement, and I am doing it too. See you Sunday &mdash; and bring someone if you can."),
],
}
