# -*- coding: utf-8 -*-

SESSION_ONE = {
"idea":"I built Launch Pairs the wrong direction. I went catalytic Sunday first, then found a journey to follow it. Your version runs the other way and it is better, for one reason that matters more than any other: <em>session one already exists.</em> You are not writing a new message. You are lifting a week you already own, letting it stand alone, and pointing at the five behind it.",
"why":[
("It costs nothing to produce","Every campaign in the backlist already has a first session. Extract it, add the standalone close, and you have a new product with no new writing."),
("The title does the selling","When the standalone message is called <em>God Owns It All</em>, the pastor who preaches it has already said the campaign's name from his own platform, in his own voice, to his own people. No marketing asset performs like that."),
("It is a trailer that is also a complete film","A pastor can preach it once and stop, and nothing is missing. That is what makes it worth taking. And the room's response is what makes him ask whether there is more."),
("It reverses who does the convincing","Instead of you persuading a pastor that a campaign works, he watches it work in his own room first. The rest of the sale happens without you."),
("It is the free tier","This is the answer to the pricing question. Session one, free, forever. The sample is the sale."),
],
"list":[
{"t":"God Owns It All","c":"Ron Blue's published work, in the Financial Wisdom track","s":"Ron Blue line &middot; active",
 "l":"6 weeks","w":"The single strongest title in the catalog for this treatment. It is a complete sermon on its own and a whole stewardship framework underneath.",
 "sess":["Who Owns It","What He Entrusted to You","Spend Less Than You Earn","Avoid Debt","Build Margin","Set Long-Term Goals"]},
{"t":"Master Your Money","c":"Ron Blue's published work","s":"Ron Blue line &middot; active",
 "l":"5 weeks","w":"Practical enough that week one holds attention on its own, and the remaining weeks are the obvious next question.",
 "sess":["The Master You Serve","Where It Actually Goes","Getting Out From Under","Giving First","The Long Plan"]},
{"t":"How Much Is Enough?","c":"Ron Blue, high-capacity families edition","s":"Ron Blue line &middot; active",
 "l":"5 weeks","w":"The question is the sermon. Works as a standalone in any congregation and as a whole framework for families with more than they need.",
 "sess":["The Question Nobody Answers","Enough for What","The Finish Line","Giving While Living","What You Leave"]},
{"t":"Generous Living","c":"Flagship generosity line, with Youth, Children's and Preschool editions","s":"active",
 "l":"6 weeks","w":"Week one stands alone cleanly and the edition ladder means a whole household can be in it at once.",
 "sess":["The Generous Life","You Cannot Outgive God","Open Hands","First, Not Last","Generosity at Home","The Overflow"]},
{"t":"40 Days of Financial Wisdom","c":"Campaign, with a Senior Pastor Edition","s":"active",
 "l":"40 days","w":"The full campaign architecture. Week one preached alone becomes the highest-converting trailer in the financial line.",
 "sess":["Whose Is It","The Honest Number","Debt and Freedom","Enough","Generosity","The Legacy"]},
{"t":"Journey of Generosity","c":"Running in local churches","s":"active",
 "l":"Retreat plus follow-up","w":"Different shape &mdash; the standalone Sunday functions as the invitation to the retreat rather than to a series."},
{"t":"Doing Life Together","c":"The historic LifeTogether small group curriculum","s":"backlist &middot; digitization candidate",
 "l":"6 weeks","w":"The name is the pitch. Week one preached as a standalone is the single best group-launch Sunday in the whole catalog.",
 "sess":["Connecting","Growing","Serving","Sharing","Surrendering","Together"]},
{"t":"Purpose Driven Business","c":"Corporate adaptation of the 40-day architecture","s":"developing",
 "l":"6 weeks","w":"Works both as a Sunday message to marketplace leaders and as the entry to the business edition."},
{"t":"Purpose at Work","c":"Named by Brett this session","s":"concept &mdash; not yet built",
 "l":"4-6 weeks","w":"Strong title. Broader and less encumbered than the Purpose Driven line, and it aims squarely at the Monday-through-Friday gap most churches never preach into."},
{"t":"Whole Life Health","c":"Movement concept across family, church, community and world","s":"developmental",
 "l":"40 days","w":"Health as the universal entry point. Week one is a genuine outsider-friendly standalone."},
{"t":"Built to Grow","c":"The advisor book","s":"in progress &mdash; book not finished",
 "l":"n/a for church use","w":"Advisor audience rather than congregational. Belongs in the Equity Partners line, not this one."},
],
"flag":"One conflict worth surfacing rather than quietly working around: you floated <em>Flourishing LifeTogether</em> here, but earlier in this project you concluded that <em>Flourish</em> has too much trademark crowding and that Bloom or Vitality were the more viable names. Either that decision changed or the title slipped back in by habit. Worth settling before it goes on a cover.",
}

PRICING = {
"principle":"Do not price a sermon. Price a Sunday. A sermon competes with free &mdash; with SermonCentral, with a blog, with a language model. A complete Sunday has no substitute at any price, because nobody else is shipping the message, the devotional week, the group session, the service kit, the graphics and the invite assets as one object.",
"tiers":[
("Session One","Free, forever","The first week of every campaign, plus the whole title library browsable. This is not a loss leader &mdash; it is the sales force. A pastor who preaches week one and watches his room respond will buy weeks two through six without ever speaking to anyone."),
("A single Sunday kit","$79","One message, complete. Outline, draft, seven-day devotional, group session, service kit, slides, bulletin insert, invite assets. Priced deliberately under the threshold where a pastor needs anyone's approval to spend it."),
("A single campaign kit","$399","The full four to six week or forty-day arc, everything above times six, plus the kickoff and Celebration Sunday designs. Excludes participant books, which price separately per copy."),
("Individual","$9 / month","Devotionals, journals and reading plans for one person. A different buyer than the church &mdash; do not confuse the two ladders."),
("Small group","$19 / month","Group sessions and the leader guides. Also a different buyer."),
],
"church":[
("Under 100 in weekly attendance","$790 / year","or $79 monthly"),
("100 to 499","$1,990 / year","or $199 monthly &mdash; the anchor tier"),
("500 to 1,499","$3,490 / year","or $349 monthly"),
("1,500 and up, or multisite","$5,990 / year","or $599 monthly"),
("Denomination or network","Custom","Priced per congregation, with a floor"),
],
"math":"The ladder has to make the subscription obviously correct, and this one does. A church running three campaigns and a dozen standalone Sundays in a year spends $1,197 plus $948, which is $2,145 &mdash; more than the $1,990 annual subscription that includes everything else in the library. Any church actually using the system arrives at that conclusion without being argued into it.",
"why_tier":"Tier by attendance, not by feature. A church of two thousand extracts twenty times the value from the identical file that a church of eighty does. Flat pricing simultaneously leaves a great deal of money on the table at the top and prices out the bottom, which is the half of the market that needs this most and talks about it the loudest.",
"dont":[
("Do not sell individual sermons at ten or twenty dollars","It competes directly with free, and worse, it teaches the market that a message is a commodity. Your entire differentiation is that you sell a Sunday rather than a sermon."),
("Do not discount the first year","Discount the annual against the monthly instead. A church that joined at half price churns when it renews at full."),
("Do not gate the library itself","Let every pastor browse all five thousand titles without an account. The catalog is the argument. What is gated is the finished kit."),
("Do not price the small church out","The under-100 tier will never be your revenue. It will be most of your word of mouth, and small-church pastors talk to each other constantly."),
],
"validate":"These are reasoned starting points from the shape of the market, not researched figures &mdash; before you publish them, price-check against what churches currently pay for sermon-resource subscriptions and curriculum kits, and test the $79 and $399 numbers on ten pastors you know. The tier structure will hold up better than the specific dollars.",
}
