# -*- coding: utf-8 -*-
# Full sermon outlines - Resurrection Sunday + Christmas Eve
# Fields: title, subtitle, text, bigidea, [movements], story, turn, close, bulletin

RESURRECTION = [
{
"t":"He's Not Where You Left Him","s":"Why the empty tomb undoes every assumption you brought with you",
"x":"Luke 24:1-8 (NIV)",
"b":"The women came to finish a burial and found that God had already moved past the ending they had accepted.",
"m":["They came prepared for the wrong thing. Spices, early light, a plan for a corpse. Grief is efficient; it makes arrangements.",
"The angels' question is the sermon: why look for the living among the dead. It is not a rebuke. It is a reorientation.",
"Remember how he told you. The resurrection was not new information. It was information they had heard and filed under impossible."],
"story":"A moment when you organized your life around an outcome that had already changed. A diagnosis that came back different. A door you assumed was closed that had been open for months.",
"turn":"Name the place where you have already decided how the story ends. That is the tomb you are standing in front of with spices in your hands.",
"close":"He is not where you left him. He is ahead of you, in the part of the story you stopped reading.",
"bl":"You came ready for an ending. Easter has other plans."
},
{
"t":"The Stone Was Already Moved","s":"God goes ahead of the obstacle you are still dreading",
"x":"Mark 16:1-6 (NIV)",
"b":"The problem they rehearsed the whole way there had been solved before they arrived.",
"m":["The question on the road: who will roll the stone away. Anxiety always does its work in transit.",
"They looked up and it was done. Mark gives us no scene of the stone moving. God did it off-camera, before the worry was finished.",
"The obstacle was never the point. The stone was moved so they could see in, not so he could get out."],
"story":"The conversation you rehearsed for two weeks that lasted ninety seconds. The bill that got covered. The thing you carried up the hill that was already handled at the top.",
"turn":"Write down the stone you are currently rehearsing. Then ask honestly whether you have checked, or only worried.",
"close":"Some of what you are dreading has already been dealt with by a God who works while you are still on the road.",
"bl":"The thing you have been dreading may already be handled."
},
{
"t":"Sunday's Coming","s":"What to do with the Friday you are living in right now",
"x":"Luke 23:54-24:3 (NIV)",
"b":"Saturday is a real day in the story, and God does not skip it just because we would like him to.",
"m":["Luke records the waiting. They rested on the Sabbath, obedient and devastated at the same time.",
"Faith in the middle is not the absence of grief. It is obedience without evidence.",
"Sunday is coming, but it comes on God's clock. The promise is certainty, not speed."],
"story":"Someone in a long middle: a job search past the encouraging stage, a marriage in counseling, a prodigal who has not called. Do not resolve the story too quickly.",
"turn":"Do the next obedient thing while you wait. They kept the Sabbath. Keep yours.",
"close":"You may be in Saturday. Saturday has an expiration date.",
"bl":"For anyone stuck between the loss and the answer."
},
{
"t":"Death Backwards","s":"The one grave that ran in reverse, and what it means for yours",
"x":"1 Corinthians 15:20-26 (NIV)",
"b":"Christ's resurrection is not an exception to the rule of death; it is the first instance of a new rule.",
"m":["Firstfruits language: the first sheaf guarantees the harvest. One grave opened means a field of them will.",
"Paul's order matters. Christ first, then those who belong to him, then the end. You are in the sequence.",
"The last enemy to be destroyed is death. Last, not never."],
"story":"A first of something that guaranteed the rest: the first paycheck after a long unemployment, the first clear scan, the first honest conversation after years of silence.",
"turn":"Consider what changes about the next forty years if the last one is not the end.",
"close":"His grave ran backwards first. Yours is in line.",
"bl":"One grave already ran in reverse. It was not the last one."
},
{
"t":"The First Witness Was a Woman","s":"What God trusted to the people nobody believed",
"x":"John 20:1-18 (NIV)",
"b":"God entrusted the most important news in history to a witness first-century courts would not have accepted.",
"m":["The historical detail nobody would invent. If you are fabricating a resurrection story in that culture, you do not choose this witness.",
"Mary is not chosen for her credibility. She is chosen because she stayed.",
"Go and tell. The commission comes before the credentials."],
"story":"Someone overlooked who turned out to be the one who knew. Keep it specific and avoid making it a lesson about titles.",
"turn":"If you have been waiting to be qualified before you speak, Mary is your permission.",
"close":"God's first evangelist was a woman nobody would have called as a witness, and she was right.",
"bl":"The most important news in history went first to someone nobody would have believed."
},
{
"t":"Alive","s":"The single word the entire faith rests on",
"x":"Revelation 1:17-18 (NIV)",
"b":"Christianity is not primarily a moral system or a comfort; it is a claim that a specific dead man is currently alive.",
"m":["The risen Christ introduces himself by his resume: I was dead, and now I am alive forever.",
"Present tense changes everything. A dead teacher leaves instructions. A living one gives orders.",
"He holds the keys. Authority over the one door nobody else has ever opened from the inside."],
"story":"The difference between inheriting advice from someone gone and having them in the room. A letter from a father versus a phone call.",
"turn":"Ask what you would do differently this week if he is not a memory but a presence.",
"close":"Everything else in this room is commentary on one word.",
"bl":"The whole faith rests on one word, and it is present tense."
},
{
"t":"Say His Name","s":"The moment grief turned around and recognized Jesus",
"x":"John 20:11-16 (NIV)",
"b":"Mary did not recognize the risen Christ by sight or argument; she recognized him when he said her name.",
"m":["She is weeping at the right tomb, talking to the right person, and completely wrong about both.",
"Grief distorts recognition. She assumed a gardener. Sorrow narrows the field of what we expect God to be doing.",
"One word: Mary. Not a proof, not a lecture. A name. Recognition came through being known."],
"story":"Being recognized by someone who had no business remembering you. The teacher who used your name twenty years later.",
"turn":"Stop trying to reason your way to certainty this morning and listen for your name.",
"close":"He did not argue her into belief. He called her.",
"bl":"She recognized him the moment he said her name."
},
{
"t":"The Undoing","s":"Everything the resurrection reversed in one Sunday morning",
"x":"Colossians 2:13-15 (NIV)",
"b":"The resurrection did not merely add hope to the world; it reversed specific things that were true about you on Friday.",
"m":["The record of debt: cancelled. Not reduced, not refinanced.",
"The powers: disarmed and publicly exposed. What accused you has been made a spectacle.",
"You who were dead: made alive with him. The verb is passive. It was done to you."],
"story":"A debt genuinely forgiven, not deferred. Someone who found out a judgment against them had been vacated.",
"turn":"Name one thing you are still carrying that was cancelled two thousand years ago.",
"close":"Sunday did not improve your situation. It reversed it.",
"bl":"Four things that were true about you on Friday and are not true today."
},
{
"t":"Proof You Can Stand On","s":"Why the resurrection is a historical claim, not a spiritual mood",
"x":"1 Corinthians 15:3-8 (NIV)",
"b":"Paul stakes the entire faith on a falsifiable public claim and invites investigation rather than sentiment.",
"m":["The creed Paul received is dated within a few years of the events. This is not legend accumulating over centuries.",
"More than five hundred witnesses, most still living. That is an invitation to go ask them.",
"Paul includes himself last, and he was an enemy. The hostile witness is part of the evidence."],
"story":"How we normally evaluate a claim we cannot personally verify: courts, history, journalism. We believe many true things on testimony.",
"turn":"Give an honest next step for the skeptic in the room. A book, a conversation, a question worth pursuing.",
"close":"You are not asked to feel this. You are asked to look at it.",
"bl":"Christianity makes a claim you can actually investigate."
},
{
"t":"He Called You by Name","s":"The resurrection was personal before it was cosmic",
"x":"John 10:3, 27 with John 20:16 (NIV)",
"b":"The cosmic scope of Easter never dissolves the individual; the Shepherd who defeated death knows his sheep by name.",
"m":["He calls his own by name and leads them out. The shepherd image is not sentimental, it is proprietary.",
"On resurrection morning he demonstrates it. One name, spoken, and everything changes.",
"Scale and intimacy are not in tension in God. The one who emptied a grave learned your name first."],
"story":"Being one of thousands and still being known. A nurse who remembered a detail. A coach who knew your family.",
"turn":"Consider that the God who is handling the universe is not distracted from you.",
"close":"He did not save humanity in general. He saved you in particular.",
"bl":"The God who emptied a grave knows your name."
},
{
"t":"Roll Away the Rest","s":"What Easter frees you from besides death",
"x":"Colossians 3:1-4 (NIV)",
"b":"If you were raised with Christ, resurrection has present-tense implications for shame, fear, and identity, not just for the afterlife.",
"m":["Since you have been raised. Past tense, already accomplished, not aspirational.",
"Set your heart on things above. The command follows the fact, never the reverse.",
"Your life is hidden with Christ. Identity secured somewhere you cannot lose it."],
"story":"Someone who kept living under an old identity after the circumstance changed. Still budgeting like they were broke a decade after they were not.",
"turn":"Name the grave clothes you are still wearing on the other side of the resurrection.",
"close":"He did not roll the stone away so you could keep living in the tomb.",
"bl":"Easter frees you from more than death."
},
{
"t":"The Empty Tomb and the Full Room","s":"Why the resurrection creates a people, not just a belief",
"x":"Acts 2:42-47 (NIV)",
"b":"The first result of the resurrection was not a doctrine but a community that ate together and shared what they had.",
"m":["They devoted themselves. Four things, held together, none optional.",
"Resurrection produced economics. People sold property. Belief reached the bank account within weeks.",
"The Lord added to their number daily. Growth was the byproduct of life together, not a strategy."],
"story":"A community formed around something true. Keep it out of church-marketing language.",
"turn":"An invitation into a group, a table, a next step. Make it concrete and make it this week.",
"close":"An empty tomb has always produced a full room.",
"bl":"The first thing the resurrection produced was a table."
},
{
"t":"Still Wounded, Still Risen","s":"The scars Jesus kept on purpose",
"x":"John 20:24-29 (NIV)",
"b":"The risen Christ kept his wounds, which means glorification does not require the erasure of history.",
"m":["A resurrection body could have been unmarked. He chose otherwise.",
"He offers the wounds as evidence. The scars are how Thomas gets home.",
"Blessed are those who have not seen. Thomas gets what he needs and the rest of us get a promise."],
"story":"A scar that became credential rather than shame. Someone whose healed wound is the reason others trust them.",
"turn":"Your history is not disqualifying. It may be the evidence someone else needs.",
"close":"He is not less risen for being still wounded, and neither are you.",
"bl":"He kept the scars. That was a decision."
},
{
"t":"Not a Ghost Story","s":"Why the disciples ate breakfast with a man who had been dead",
"x":"Luke 24:36-43 (NIV)",
"b":"The resurrection is bodily and physical, which makes Christianity a claim about matter and not merely about spirit.",
"m":["Touch me and see. He invites the most ordinary verification available.",
"He asks for food. A ghost does not want fish.",
"Christianity has never been about escaping the body. God got one and kept it."],
"story":"Physical presence versus a good idea. The difference between a condolence card and someone in your kitchen.",
"turn":"What changes if God takes your body, your work, your ordinary Tuesday as seriously as your soul.",
"close":"The risen Christ ate breakfast. Christianity has been stubbornly physical ever since.",
"bl":"He asked for something to eat. Ghosts do not."
},
{
"t":"Hope With a Pulse","s":"The difference between wishing something were true and knowing it is",
"x":"1 Peter 1:3-5 (NIV)",
"b":"Peter calls it a living hope because it is anchored in an event, not in optimism about how things generally go.",
"m":["Born again into a living hope, through the resurrection. The mechanism is named.",
"An inheritance that cannot perish, spoil, or fade. Three things that happen to everything else you own.",
"Shielded by God's power. The hope is kept, and so are you."],
"story":"The difference between hoping for good weather and having a signed contract. Wishing versus holding a document.",
"turn":"Name what your hope is currently anchored to, honestly.",
"close":"Christian hope is not a mood you work up. It has a pulse.",
"bl":"There is a difference between wishing and knowing."
},
{
"t":"Because He Lives","s":"Three things that are now permanently true about your future",
"x":"Romans 8:11 (NIV)",
"b":"The same Spirit that raised Jesus is at work in believers now, which makes resurrection a present power and a future guarantee.",
"m":["If the Spirit lives in you. The condition is stated plainly and should be preached plainly.",
"He will also give life to your mortal body. Future, physical, promised.",
"The resurrection power is not stored for later. It is the operating power of the Christian life today."],
"story":"Power available and unused. Someone with a resource they never accessed.",
"turn":"Offer a clear step into faith for anyone who does not yet have the Spirit in them.",
"close":"The power that opened that grave has an address, and it is you.",
"bl":"Resurrection power is not stored for later."
},
{
"t":"The Best News Ever Told, Told Again","s":"Why we say the same thing every single year and never tire of it",
"x":"1 Corinthians 15:1-8 (NIV)",
"b":"Repetition is not a failure of imagination; the gospel is the kind of news that has to be received again, not merely remembered.",
"m":["I want to remind you of the gospel. Paul repeats himself to people who already believe.",
"By this gospel you are saved, if you hold firmly. Holding is ongoing work.",
"Of first importance. Everything else in church life sits downstream of this."],
"story":"Something you needed to hear again from someone who had already said it. Vows, a diagnosis of health, a father's approval.",
"turn":"Receive it today rather than recognize it. There is a difference.",
"close":"We say it every year because it is the kind of news you never stop needing.",
"bl":"Why we tell the same story every single spring."
},
{
"t":"From the Garden to the Garden","s":"How Easter finishes what Genesis started",
"x":"Genesis 3:17-19 with John 19:41, 20:15 (NIV)",
"b":"Scripture opens in a garden with a curse and closes the decisive act in a garden with a gardener who is not who Mary thought.",
"m":["The first garden: a curse, thorns, exile, and a flaming sword at the gate.",
"The second garden: a tomb in the middle of it, and a crown of the same thorns.",
"She supposed him to be the gardener. John is not being casual. The new Adam is tending a new creation."],
"story":"A story that came full circle in a way nobody planned. Use a family or place image rather than a literary one.",
"turn":"Consider that your story may be following a shape you cannot see from inside it.",
"close":"It began in a garden. He made sure it ended in one.",
"bl":"The Bible opens in a garden. Easter ends in one."
},
{
"t":"Why Do You Look for the Living Among the Dead?","s":"The question the angels asked, and why it still lands",
"x":"Luke 24:1-12 (NIV)",
"b":"We keep returning to dead places to find life, and the angels' question exposes the habit.",
"m":["The question is diagnostic, not condemning. They were doing something loving and something futile at the same time.",
"Everyone has a tomb they revisit. An old identity, an ended relationship, a version of themselves that is gone.",
"Remember how he told you. The cure for looking in the wrong place is recalling what he said."],
"story":"Returning repeatedly to a place that no longer holds what you are looking for. A house that was sold. A group chat that went quiet.",
"turn":"Name your tomb. Then name what he actually told you.",
"close":"You have been looking in a place he already left.",
"bl":"A question worth carrying out of this room."
},
{
"t":"The Last Enemy","s":"What the resurrection did to the thing you fear most",
"x":"1 Corinthians 15:50-57 (NIV)",
"b":"Death is treated in Scripture as an enemy to be destroyed, not a natural friend, and Easter is its defeat notice.",
"m":["Paul does not soften death. He calls it an enemy. Christian honesty about death is a gift.",
"Where, O death, is your victory. The taunt is only available because of an empty tomb.",
"Therefore stand firm. The application of resurrection is stability, not escapism."],
"story":"Someone who faced death without denial and without terror. Handle with care and get permission before naming anyone.",
"turn":"Name the fear plainly, then name what has been done about it.",
"close":"It is still an enemy. It is a defeated one.",
"bl":"Christianity does not pretend death is a friend."
},
]

CHRISTMAS_EVE = [
{
"t":"The Night the Waiting Ended","s":"Four hundred silent years and one cry in the dark",
"x":"Luke 2:1-7 (NIV)",
"b":"God's longest silence ended not with an announcement to the powerful but with a birth in an occupied backwater.",
"m":["Four centuries between Malachi and Luke. No prophet, no word. Set the weight of that before the manger.",
"Caesar issues a decree and unknowingly moves a pregnant teenager to the town the prophets named.",
"The waiting ended with a sound only a few people heard."],
"story":"A long silence that ended quietly rather than dramatically. The call that came after months of nothing.",
"turn":"If you are in a silent stretch, note that God's silences in Scripture end, and they end suddenly.",
"close":"The longest silence in the Bible was broken by a newborn.",
"bl":"Four hundred years of silence ended in a room nobody was watching."
},
{
"t":"Light in the Dark","s":"Why we hold candles and sing in the middle of the night",
"x":"John 1:1-5 (NIV)",
"b":"Christianity does not deny the darkness; it makes a claim about what the darkness has never been able to do to the light.",
"m":["In him was life, and that life was the light of all mankind.",
"The light shines in the darkness. Present tense. It is still shining, right now, in whatever you walked in carrying.",
"The darkness has not overcome it. The verb carries both not understood and not extinguished."],
"story":"A small light in real dark. A power outage, a hospital corridor, a candle passed down a row.",
"turn":"The candle moment. Let the room be dark long enough to mean something before the light travels.",
"close":"We do not light candles because the dark is not real. We light them because it is.",
"bl":"We do this in the dark on purpose."
},
{
"t":"Come and Behold Him","s":"An invitation older than the carol",
"x":"Luke 2:15-16 (NIV)",
"b":"The shepherds' response to the announcement was movement, and the invitation of Christmas is still to go and see rather than to consider from a distance.",
"m":["Let us go and see. They did not debate it, they went.",
"They hurried off. Urgency is the appropriate response to news this size.",
"They found. Seeking in Scripture is generally rewarded with finding."],
"story":"Someone who went to see for themselves rather than taking a secondhand report.",
"turn":"A specific invitation to investigate rather than assent. Name what going and seeing looks like in January.",
"close":"The carol is quoting shepherds. Come and see is the oldest invitation we have.",
"bl":"The shepherds did not discuss it. They went."
},
{
"t":"No Room","s":"The first thing the world ever told Jesus",
"x":"Luke 2:7 (NIV)",
"b":"The rejection that would define his life met him on the first night of it.",
"m":["No guest room available. Luke states it without editorial. The understatement is the point.",
"It was not malice, it was capacity. Bethlehem was full. That is how Jesus usually gets displaced.",
"He came anyway, and was born in the space that was left."],
"story":"Something important crowded out by things that were not more important, only more urgent. Keep it honest rather than scolding.",
"turn":"Audit December honestly. Not guilt, just an accurate look at what filled the calendar.",
"close":"There was no room, and he came anyway. That is the whole gospel in one sentence.",
"bl":"The first thing the world told Jesus was that it was full."
},
{
"t":"Glory in a Feed Trough","s":"God's entrance had no red carpet",
"x":"Luke 2:8-14 (NIV)",
"b":"The greatest disclosure of glory in history was staged in the least glorious setting available.",
"m":["The glory of the Lord shone around the shepherds. Heaven did not understate it.",
"And the sign is a baby in a feeding trough. Heaven's glory pointed at the least glorious thing in the county.",
"God's pattern is consistent. He puts weight in places we would not check."],
"story":"Significance found in an unimpressive container. Avoid the well-worn versions.",
"turn":"Where are you refusing to look for God because the container is not impressive.",
"close":"Angels filled the sky to point at a feed trough.",
"bl":"Heaven's glory pointed at the least glorious thing in the county."
},
{
"t":"Fear Not","s":"The angel's opening line, and why we needed it first",
"x":"Luke 2:8-11 (NIV)",
"b":"Before God delivered the good news he addressed the fear, because fear makes good news unhearable.",
"m":["They were terrified. The appropriate response to the presence of God is not warmth.",
"Do not be afraid comes first, before the announcement. Order matters.",
"I bring you good news of great joy. Joy is what fear becomes when it is addressed rather than suppressed."],
"story":"Someone who could not hear good news until the fear was named. A doctor who says the outcome first.",
"turn":"Name the fear you carried into this service. God addresses it before he asks anything of you.",
"close":"Heaven's first word to human beings that night was do not be afraid.",
"bl":"Before the good news, God dealt with the fear."
},
{
"t":"Silent Night, Sleepless World","s":"Peace offered to people who cannot turn their minds off",
"x":"Isaiah 9:6-7 with Matthew 11:28 (NIV)",
"b":"The Prince of Peace offers rest that is not the absence of pressure but the presence of a person.",
"m":["Prince of Peace is a title, not a mood. Peace has a name and a face.",
"Of the greatness of his government and peace there will be no end. Peace here is governmental, structural, durable.",
"Come to me, all you who are weary. The invitation is to a person, not to a technique."],
"story":"The 2 a.m. mind. Be specific and non-judgmental about what actually keeps people awake.",
"turn":"One practice for the week that puts a person, not a technique, at the center.",
"close":"The night was silent. The world was not, and is not. He came into that one.",
"bl":"For anyone who cannot turn their mind off at night."
},
{
"t":"Wrapped in Cloths","s":"The King who arrived helpless",
"x":"Luke 2:12 (NIV)",
"b":"Omnipotence chose infancy, and the helplessness was not incidental to the plan but central to it.",
"m":["The sign is not power, it is swaddling. God gave a vulnerability as the identifying mark.",
"He could not lift his head. Hold that against every image of God you were handed.",
"The one who holds the universe together needed to be held."],
"story":"Holding a newborn. Their weight, their total dependence. Do not rush past the physicality.",
"turn":"What does it change about prayer if God has been on the receiving end of care.",
"close":"He was wrapped in cloths by a teenager, and that was the sign.",
"bl":"God arrived unable to lift his own head."
},
{
"t":"The Word Became Flesh and Moved In","s":"John's version of the Christmas story",
"x":"John 1:14 (NIV)",
"b":"John gives Christmas without shepherds or a manger and states the claim at its most naked: God took on a body and moved into the neighborhood.",
"m":["The Word became flesh. Two words that no other religion puts together.",
"Made his dwelling among us. The verb carries tabernacle, tent, the presence of God pitching camp.",
"We have seen his glory. Eyewitness language, not theory."],
"story":"The difference between someone helping from a distance and someone moving in. A neighbor who showed up versus one who sent a card.",
"turn":"God's method has always been proximity. Consider whether yours is.",
"close":"He did not send instructions. He moved in.",
"bl":"Christmas without a manger, told by the one who was there."
},
{
"t":"Emmanuel","s":"God with us, and what it cost him to be",
"x":"Matthew 1:22-23 with Isaiah 7:14 (NIV)",
"b":"With us is not a sentiment; it is a location God chose at enormous cost.",
"m":["A prophecy spoken seven hundred years earlier into a political crisis nobody remembers.",
"They will call him Emmanuel. God with us is the name, and the name is the summary.",
"With us cost him everything that made with easy. He gave up distance."],
"story":"Someone who chose to be present at real cost. Sitting in a waiting room. Moving for a parent.",
"turn":"With us on the hardest night of your year is the claim. Test it rather than assume it.",
"close":"Not God above us, not God watching us. With.",
"bl":"One word summarizes the whole night, and it is with."
},
{
"t":"To You Is Born This Day","s":"The most personal announcement in history",
"x":"Luke 2:10-11 (NIV)",
"b":"The angel's grammar is second person: the birth is announced not as a cosmic event but as something that happened for the people standing there.",
"m":["Good news of great joy for all the people. The scope is total.",
"Today in the town of David a Savior has been born to you. From all people to you in a single sentence.",
"Scripture keeps refusing to let the universal cancel the personal."],
"story":"News that was technically public but landed as personal. A verdict, an acceptance, a name called.",
"turn":"Receive it in the second person tonight. Not for people. For you.",
"close":"To you. The angel could have said anything and said that.",
"bl":"The announcement was made in the second person."
},
{
"t":"The Shepherds Went to See","s":"Ordinary people, first invitation",
"x":"Luke 2:15-20 (NIV)",
"b":"God announced the incarnation to men whose testimony was legally worthless, and they became the first to tell it.",
"m":["Shepherds were unclean, unschooled, and unwelcome as witnesses. Heaven's press list was upside down.",
"They went, they saw, they spread the word. No training, no delay.",
"They returned glorifying and praising God. They went back to the same field. Encounter did not change their job."],
"story":"Someone unqualified who carried the news anyway. Keep the class dynamics honest without being sentimental about poverty.",
"turn":"You do not need standing to tell someone what you have seen.",
"close":"They went back to the sheep, and they went back different.",
"bl":"Heaven's first announcement went to men nobody would have believed."
},
{
"t":"Peace on Earth","s":"The promise we hear every year and still need",
"x":"Luke 2:14 with Isaiah 9:6 (NIV)",
"b":"The peace the angels announced is not the absence of conflict but the arrival of a King, and it is offered before it is fully visible.",
"m":["Glory to God in the highest, and on earth peace. The vertical comes first and the horizontal follows.",
"Peace to those on whom his favor rests. Not a blanket sentiment, a specific gift.",
"Announced then, not yet complete now. Christians live between the announcement and the fulfillment."],
"story":"A peace treaty signed before the fighting stopped everywhere. Handle current events with care or avoid them entirely.",
"turn":"Where do you need this peace to be more than a card sentiment this year.",
"close":"They announced it over a country under military occupation. It was not naive then either.",
"bl":"The angels announced peace over an occupied country."
},
{
"t":"Away in a Manger, Bound for a Cross","s":"The shadow lying across the nativity",
"x":"Luke 2:33-35 (NIV)",
"b":"Simeon put the cross into the Christmas story eight days in, and the church has been trying to separate them ever since.",
"m":["Simeon blesses them and then says something no parent wants to hear.",
"A sword will pierce your own soul too. Mary is told at the dedication how this ends.",
"The manger only makes sense pointed at something. Christmas is not complete on its own."],
"story":"Knowing the cost at the beginning and choosing anyway. A calling accepted with eyes open.",
"turn":"Do not let the sentiment of the season detach the birth from its purpose.",
"close":"He was born to die, and the first person told was his mother.",
"bl":"Someone told Mary how this ends when the baby was eight days old."
},
{
"t":"Joy to the World, Now","s":"Not sentiment, but a claim about reality",
"x":"Luke 2:10 with Psalm 98 (NIV)",
"b":"Christian joy is a response to something that happened, which is why it can survive a year that did not go well.",
"m":["Good news of great joy. The joy is downstream of the news, never manufactured upstream.",
"The carol is drawn from a psalm about God's coming reign, not about a nativity scene.",
"Joy and happiness are different instruments. One responds to circumstance, the other to fact."],
"story":"Joy that persisted through a hard year because it was attached to something that did not move.",
"turn":"Name what your joy is currently attached to, and whether that thing can hold it.",
"close":"Joy to the world is not a wish. It is an announcement.",
"bl":"Joy that does not require a good year."
},
{
"t":"One Candle Is Enough","s":"Small light in real darkness",
"x":"John 1:5 (NIV)",
"b":"Light does not need to match darkness in volume to defeat it; it only needs to be present.",
"m":["Darkness is not a substance. It is an absence, and it cannot advance into light.",
"The math is asymmetrical. One candle in a dark room wins; no amount of dark puts out one flame.",
"You are not asked to be a floodlight."],
"story":"A single small act that changed the atmosphere of a room, a family, a workplace.",
"turn":"Name one candle-sized thing you could carry into January.",
"close":"You do not have to be the sun. Nobody in this room was asked to be.",
"bl":"One candle beats a whole room of dark. The math is not fair."
},
{
"t":"He Came at Night","s":"Why God so often arrives after dark",
"x":"Luke 2:8 (NIV)",
"b":"The pattern of Scripture is that God shows up in the night watches, which is exactly when most people assume he has gone.",
"m":["Shepherds keeping watch over their flocks at night. The detail is not decorative.",
"Jacob wrestles at night. Passover happens at night. The tomb opens before dawn.",
"Night is not the absence of God in Scripture. It is frequently the setting."],
"story":"Something that arrived in a person's worst stretch rather than after it.",
"turn":"If you are in a night, you are in the part of the story where God usually moves.",
"close":"He did not wait for morning. He never has.",
"bl":"God has a long history of showing up after dark."
},
{
"t":"The Angels Could Not Keep Quiet","s":"Worship as an involuntary response",
"x":"Luke 2:13-14 (NIV)",
"b":"The angelic response to the incarnation was not decision but overflow, and it exposes worship as reaction rather than duty.",
"m":["Suddenly a great company. The word suggests an army, not a choir.",
"They praised God and saying. The content is theological, not emotional.",
"Beings who had watched creation itself lost composure over a baby."],
"story":"The moment someone could not stay quiet. A stadium, a delivery room, a courtroom verdict.",
"turn":"If worship feels like an obligation, the problem is usually upstream of the singing.",
"close":"The creatures who had seen everything could not stay quiet about this.",
"bl":"Beings who watched creation happen lost their composure over a baby."
},
{
"t":"What Are You Hoping For This Year?","s":"Longing, and the God who meets it",
"x":"Luke 2:25-32 (NIV)",
"b":"Simeon waited a lifetime for a promise and got to hold it, which makes him the patron saint of everyone still waiting.",
"m":["He was waiting for the consolation of Israel. Waiting is named as his defining activity.",
"It had been revealed to him that he would not die before he had seen. Some promises come with a guarantee and no date.",
"Now dismiss your servant in peace. Fulfillment did not make him ambitious. It made him ready."],
"story":"Someone who waited a very long time and was not disappointed. Do not use it to promise outcomes.",
"turn":"Name the thing you are still hoping for. Say it out loud on the way home.",
"close":"He waited a whole life for ten minutes, and said it was enough.",
"bl":"For anyone still waiting on something."
},
{
"t":"Christmas Eve for the Weary","s":"A quiet word for people running on empty",
"x":"Matthew 11:28-30 (NIV)",
"b":"The season that is supposed to restore people most often exhausts them, and the invitation of Christ is aimed precisely at that condition.",
"m":["Come to me, all you who are weary and burdened. The qualification is exhaustion, not performance.",
"Take my yoke. Rest is not the absence of load, it is a better distribution of it.",
"You will find rest for your souls. The rest offered is deeper than sleep, which is why sleep has not fixed it."],
"story":"Someone who arrived at Christmas depleted rather than joyful. Be gentle and do not resolve it too fast.",
"turn":"One thing to lay down before January. Make it small enough to actually do.",
"close":"If you came in tired tonight, you are exactly who this was addressed to.",
"bl":"If you arrived at Christmas exhausted, this one is for you."
},
]
