# -*- coding: utf-8 -*-

TRANSCRIPT = {
"intro":"One forty-minute shoot produces fifteen interviews and roughly forty-five answers. Most churches use ninety seconds of that and delete the rest. The transcript is what turns a single morning of filming into six weeks of video, and it lets a volunteer do the work without ever watching the footage.",
"key":"Sort the transcript by question, not by person. That one move is the entire method.",
"steps":[
("One &mdash; Transcribe it the free way","Every phone will now transcribe video automatically, and so will every editing app. Export the transcript with timecodes. This step costs nothing and takes about four minutes."),
("Two &mdash; Re-sort by question","Cut and paste so that all fifteen answers to question one sit together, then all fifteen to question two. You are no longer looking at fifteen interviews. You are looking at three collections of fifteen answers."),
("Three &mdash; Read, do not watch","Whoever is choosing clips reads the transcript and highlights eight to ten lines per question. They never open the video. This is why a volunteer can do it in half an hour instead of a staff member losing an afternoon."),
("Four &mdash; Hand over a timecode list","The chooser gives the editor a plain list: 04:12&ndash;04:24, 11:03&ndash;11:19, and so on. The editor pulls them in order and does nothing else. Two people, ninety minutes total, no meetings."),
("Five &mdash; One question becomes one week","Question one is week one's clip. Question two is week two. Question three is week three. Same faces every week, different answers, which builds recognition across the run &mdash; the congregation starts looking for the man in the blue jacket."),
("Six &mdash; Or sort by theme instead","For a challenge rather than a series, ignore the questions and sort the highlighted lines by what they are actually about. Doubt in one pile, family in another, money in a third. Now the clips match your teaching weeks rather than your shoot order."),
],
"yield":[
("One 40-minute shoot","15 interviews, 3 questions each, roughly 45 usable answers"),
("Sorted by question","3 weekly clips of 8-10 answers each"),
("Sorted by theme","5 to 6 clips, matched to whatever you are teaching"),
("Light plus heartfelt","2 distinct videos from the same footage &mdash; one opens a campaign, one closes it"),
("Total staff time","About two hours, and most of it is not the staff"),
],
"rule":"Film once per campaign, not once per weekend. The single biggest reason these stop after two weeks is that somebody decided they needed fresh footage every Saturday. They do not.",
}

PAIRS = [
("Winter and the New Year",[
{"k":"Begin Again","kc":"New Year's Sunday","j":"30 Days to a New You","l":"30-day journey","t":"Session One",
 "s":["Where You Actually Are","One Thing","The Habits That Build You","Who You Walk With","Numbering Your Days","Finish What You Start"],
 "w":"January is the only month of the year when an entire congregation is already trying to change something. Meet them in the week they are already motivated rather than three weeks after the motivation is gone.",
 "c":"First Sunday of January, running into early February."},
{"k":"Where We Are Going","kc":"Vision Sunday","j":"Build the Wall","l":"6-week series","t":"Session One",
 "s":["He Wept, Then He Planned","Survey the Wall First","Let Us Rise Up and Build","The Opposition Is Normal","Every Family a Section","Dedication"],
 "w":"Nehemiah is the only book in Scripture that is entirely about a congregation executing a shared vision, and it is honest about the discouragement in the middle. It turns a vision message into a working plan.",
 "c":"Mid-January through late February, ahead of the giving year."},
{"k":"Finish the Year Well","kc":"End-of-Year Giving","j":"Free","l":"21-day challenge","t":"Trailer",
 "s":["What Owns You","The Honest Number","Give First","Debt Is a Decision","Enough","Open Hands"],
 "w":"December decides and January acts. Preach the vision while the year-end gift is live, then launch the teaching the week the credit card statement lands.",
 "c":"Kickoff the last Sunday of December; journey starts the second week of January."},
]),
("Lent and Easter",[
{"k":"Remember You Are Dust","kc":"Ash Wednesday","j":"Forty Days to Easter","l":"40-day journey","t":"Session One",
 "s":["The Wilderness","Not by Bread Alone","Give Something Up","Secret Practices","The Slow Walk","From Ashes to Glory"],
 "w":"Lent is the only forty-day journey the church calendar builds for you. The runway already exists and most evangelical churches leave it empty.",
 "c":"Ash Wednesday through Resurrection Sunday."},
{"k":"Two Processions","kc":"Palm Sunday","j":"Seven Days to the Cross","l":"7-day daily","t":"Session One",
 "s":["The Entry","The Temple","The Table","The Garden","The Trial","The Cross","The Silence"],
 "w":"The only week of the year where a daily devotional matches the calendar exactly, day for day. People read Thursday's entry on Thursday. Nothing else in the year does that.",
 "c":"Palm Sunday through Holy Saturday."},
{"k":"He's Not Where You Left Him","kc":"Resurrection Sunday","j":"What They Did Next","l":"6-week series","t":"Session One",
 "s":["They Devoted Themselves","Ordinary and Unschooled","Everything in Common","The First Opposition","Sent","To the Ends of the Earth"],
 "w":"Acts begins precisely where Easter ends. It is also the answer to the question every Easter guest is silently asking on the drive home, which is: so what. This is the strongest pairing in the entire library.",
 "c":"Launches the Sunday after Easter &mdash; exactly when you need to give four hundred visitors a reason to come back."},
{"k":"If It Is True, Nothing Else Matters","kc":"Easter for the Skeptic","j":"Reasons","l":"4-week series","t":"Session One",
 "s":["Is There a God","Can I Trust This Book","Why Is There Suffering","What About the Church"],
 "w":"You have more skeptics in the building on Easter morning than on any other day, and most churches give them nowhere to go on the eighth. Four weeks aimed at them costs you nothing and catches the ones who were curious.",
 "c":"The four Sundays following Easter."},
]),
("Spring",[
{"k":"When Mother's Day Hurts","kc":"Mother's Day","j":"Home","l":"5-week series","t":"Trailer",
 "s":["The House You Grew Up In","The Family Table","Blessing Out Loud","When It Is Broken","The Legacy You Are Building"],
 "w":"Mother's Day surfaces every family wound in the room and then the church moves on the following week. Do not open something you are not going to stay with.",
 "c":"Starts the week after Mother's Day, running to early June."},
{"k":"The Father Ran","kc":"Father's Day","j":"Legacy","l":"6-week series","t":"Session One",
 "s":["What You Inherited","The Weight You Carry","Lead Without Ruling","Bless Them Out Loud","The Long Shadow","Finish Strong"],
 "w":"You have men in the room on Father's Day who will not be back for a month. Give them a reason, a group, and a start date before they leave the parking lot.",
 "c":"Father's Day into late July."},
{"k":"Sent, Not Just Released","kc":"Graduation","j":"First Year","l":"21-day challenge","t":"Trailer",
 "s":["Find a Church in Two Weeks","Doubt Is Not the Enemy","Who You Walk With","Money at the Start","Read It Yourself","Come Home Whenever"],
 "w":"The twenty-one days runs through the first three weeks on campus, which is the precise window in which a young adult's faith survives or quietly does not.",
 "c":"Kickoff at graduation; the journey starts the week they move."},
{"k":"Buried and Raised","kc":"Baptism Sunday","j":"Start Here","l":"7-day jumpstart","t":"Session One",
 "s":["You Belong","Talk to Him","Read It Yourself","Tell Someone","Find Your People","Give Something","What Now"],
 "w":"The gap between the water and the first discipleship step is where most new believers are lost. This closes it to zero &mdash; they start the morning after.",
 "c":"Any baptism Sunday, all year."},
]),
("Summer",[
{"k":"Everybody Serves Somebody","kc":"Serve Sunday","j":"21 Days of Serving","l":"21-day challenge","t":"Session One",
 "s":["Start at Home","The Need in Front of You","Someone Who Cannot Repay","Invisible Service","Serve Until It Costs","What Happened"],
 "w":"Summer is the season a church has willing people and no program. Serving fills the gap, and the testimonies you collect in July become your fall launch video.",
 "c":"Late June through July."},
{"k":"What Are You Building On?","kc":"Any Given Sunday","j":"Ten Days Through James","l":"10-day jumpstart","t":"Trailer",
 "s":["Consider It Joy","Ask for Wisdom","Hearing and Doing","The Tongue","Faith and Works","Draw Near"],
 "w":"Summer attendance is inconsistent by nature. A ten-weekday jumpstart survives vacation schedules that would kill a six-week series, because nobody has to be in the room for it to work.",
 "c":"Any two weeks in July or August."},
{"k":"Church at Home","kc":"Church at Home Sunday","j":"Table","l":"4-week series","t":"Session One",
 "s":["The Home Is the First Church","One Rhythm","Bless Them Out Loud","Invite the Neighbors In"],
 "w":"Summer scatters families across three months of travel. Give them something that runs in a backyard on a Tuesday and does not require the building.",
 "c":"Any four weeks between June and August."},
]),
("Fall",[
{"k":"Start Again","kc":"Fall Launch","j":"The Group Semester","l":"6-week series","t":"Session One",
 "s":["Rows and Circles","Six People, One Room","Devoted","Carry Each Other","Spur One Another","Who Is Missing"],
 "w":"The second-biggest reset of the year. Families re-enter routine in late August and will commit to something for the first time since January, and most churches sleep straight through the window.",
 "c":"The Sunday after school starts."},
{"k":"Who Are You Bringing?","kc":"Series Launch and Friends Day","j":"Come and See","l":"4-week series","t":"Session One",
 "s":["Who Is He","What Did He Actually Say","Why the Cross","What Now"],
 "w":"You just filled the room with guests. Four weeks aimed at them rather than at the regulars is the difference between a full Sunday and a growing church.",
 "c":"September or October, four weeks."},
{"k":"Teach Us to Pray","kc":"Prayer Sunday","j":"21 Days of Prayer","l":"21-day challenge","t":"Session One",
 "s":["Our Father","Ask, Seek, Knock","Learning to Listen","Lament","Pray Together","What Changed"],
 "w":"A church that prays together for three weeks before a capital ask, a vision Sunday, or a hard season behaves differently than one that does not. Put this ahead of whatever is coming.",
 "c":"October, or immediately before any major initiative."},
{"k":"Give Thanks in All Circumstances","kc":"Thanksgiving","j":"Generous","l":"21-day challenge","t":"Trailer",
 "s":["God Gave First","Enough","Where It Actually Goes","Sow Generously","First, Not Last","One More Family"],
 "w":"Thanksgiving to year-end is the shortest and highest-yield generosity window on the calendar, and the only one where gratitude is already the cultural mood rather than something you have to build.",
 "c":"Kickoff Thanksgiving Sunday; journey runs to December 31."},
]),
("Advent and Christmas",[
{"k":"Twenty-One Days to Christmas","kc":"Advent Kickoff","j":"21 Days of Advent","l":"21-day devotional","t":"Session One",
 "s":["Hope","Peace","Joy","Love","Prepare the Way","Emmanuel"],
 "w":"Twenty-one days lands exactly on Christmas Eve if you start the first Sunday of Advent. The calendar does the work for you.",
 "c":"First Sunday of Advent through Christmas Eve."},
{"k":"Light in the Dark","kc":"Christmas Eve","j":"Ten Days Through John","l":"10-day jumpstart","t":"Trailer",
 "s":["In the Beginning","Come and See","Born Again","The Woman at the Well","Bread of Life","I Am the Resurrection"],
 "w":"You preached John 1 on the twenty-fourth. The jumpstart continues the same book on the first weekday of January and finishes before anyone's resolve fades. The continuity is the sell &mdash; say from the platform that you are picking the book back up.",
 "c":"Kickoff Christmas Eve; ten weekdays starting the first Monday of January."},
{"k":"Christmas When You Are Not Okay","kc":"Blue Christmas","j":"After the Loss","l":"6-week series","t":"Trailer",
 "s":["Naming It","Jesus Wept First","The God Who Sits With You","Refusing Easy Comfort","The Slow Return of Joy","Reunion"],
 "w":"A Blue Christmas service identifies the grieving people in your church and then most churches lose the list. Launch the group in January while the ache is still named.",
 "c":"Kickoff in December; the series or group starts mid-January."},
{"k":"One Word for the Year","kc":"After Christmas","j":"The Word for Your Year","l":"30-day journey","t":"Session One",
 "s":["Choose It","Test It","Live It","Share It","Keep It"],
 "w":"The lowest-attendance Sunday of the year is full of the people who will carry the next twelve months. Send them into January with one thing rather than twelve.",
 "c":"The Sunday between Christmas and New Year."},
]),
]

PAIRNOTE = {
"types":[
("Session One","The catalytic message <em>is</em> the first lesson. The journey continues it directly and the pastor says so from the platform: this is week one of six. Highest continuity, and it requires the calendar to cooperate."),
("Trailer","The catalytic message stands entirely on its own and the journey starts later &mdash; the following week, or in January. Use this when the calendar makes continuity impossible, which is most of December."),
],
"rule":"Announce the journey from the platform on the catalytic Sunday itself, not the week after. The room is never warmer than it is in the four minutes after that message ends, and a church that waits seven days to make the ask has already lost a third of the people who would have said yes.",
}
