# -*- coding: utf-8 -*-

# Six sermons, fully populated: outline + the 7 devotional day titles + what ships with it
SERMONS = [
{"cat":"Resurrection Sunday","t":"He's Not Where You Left Him",
"s":"Why the empty tomb undoes every assumption you brought with you",
"x":"Luke 24:1-8","b":"The women came to finish a burial and found that God had already moved past the ending they had accepted.",
"m":["They came prepared for the wrong thing. Grief is efficient; it makes arrangements.",
"Why look for the living among the dead. Not a rebuke &mdash; a reorientation.",
"Remember how he told you. Old information nobody could hold."],
"dev":[("Spices in Your Hands","Prepared carefully for a story God had already moved past"),
("Very Early in the Morning","The faithfulness that only happens before anyone is watching"),
("The Stone Was Already Moved","The problem you rehearsed the whole way there"),
("They Did Not Find the Body","When good news arrives as a subtraction"),
("Why Look Among the Dead?","The tomb you keep revisiting"),
("Remember How He Told You","What you filed under impossible"),
("Then They Remembered","Remembering moves you toward people")],
"exp":["Open in the dark. Three minutes of Friday &mdash; no lights, no music &mdash; before a single note of Easter.",
"Put a stone at the door. A real one, heavy, that people have to walk past on the way in and see rolled aside on the way out.",
"Spices on the communion table. Myrrh and aloes in an open dish. The room will smell like the first verse of the passage.",
"Send them out with the assignment, not the applause. Last line is a question, not a benediction."]},

{"cat":"Mother's Day","t":"When Mother's Day Hurts",
"s":"Naming it from the platform before the flowers come out",
"x":"1 Samuel 1:9-18 with Psalm 34:18","b":"The church's job on Mother's Day is not to celebrate around the pain in the room but to name it first, because God does.",
"m":["Hannah prayed in a way that looked like drunkenness to the clergyman standing there.",
"Eli got it wrong before he got it right. The church can correct itself.",
"Psalm 34 promises nearness, not repair. Proximity is the promise."],
"dev":[("Deeply Troubled","Scripture does not clean Hannah up before recording her"),
("Pouring Out Your Soul","Prayer the way you cry in a parked car"),
("When the Church Gets It Wrong","The priest read her completely backwards"),
("Close to the Brokenhearted","The promise is presence, not explanation"),
("Refusing to Be Comforted","God lets the grief stand in the text"),
("She Went Away and Ate Something","Relief before resolution"),
("God Sets the Lonely in Families","The answer to isolation is usually a person")],
"exp":["Name it in the first ninety seconds, before a single flower is handed out. Everything after depends on that.",
"A staffed room, announced by name and location, open immediately after. Not a card, a room.",
"Skip the stand-up-if-you're-a-mother moment entirely. Honor everyone seated.",
"A candle table at the back with blank cards. No explanation needed &mdash; the people who need it will know."]},

{"cat":"Series Launch &amp; Friends Day","t":"Who Are You Bringing?",
"s":"The invitation is the assignment",
"x":"John 1:40-42","b":"The most consistent thing Andrew ever does in the gospels is bring someone to Jesus, and it required no training.",
"m":["Andrew appears three times in John, and all three times he is bringing someone.",
"The first thing he did was find his own brother &mdash; the person already at his table.",
"He brought him. He did not convince him. Transportation, not transformation."],
"dev":[("The First Thing He Did","One day of information and he went to find his brother"),
("He Brought Him to Jesus","Your job is transportation, not transformation"),
("Come and See","Philip answers an objection with an invitation"),
("She Told the Whole Town","Twenty minutes of theology and a whole town believed"),
("Four Men and a Roof","When Jesus saw their faith. Not his &mdash; theirs"),
("What If They Say No?","One plants, another waters"),
("Write the Name Down","Pray, watch, ask &mdash; and then actually ask")],
"exp":["Cards and pens in every seat. Everyone writes one name during the service while the pastor waits in silence.",
"Have people text that person before the closing song. Phones out, on purpose, from the platform.",
"Print the 5F insert on the back of the card so they map their circles instead of drawing a blank.",
"Reserve a row and mark it. Physically hold space for the people who are not there yet."]},

{"cat":"Group Life Launch","t":"You Were Not Built to Do This Alone",
"s":"The case for group life",
"x":"Acts 2:42-47 with Ecclesiastes 4:9-12","b":"The New Testament has no category for a solitary Christian, because formation happens in proximity.",
"m":["Four devotions held together under one verb. Remove one and the shape collapses.",
"The temple courts and their homes. Both, never in competition.",
"Pity the one who falls and has no one. That is a warning, not a sentiment."],
"dev":[("They Devoted Themselves","Four things, one verb, none of them optional"),
("Two Are Better Than One","If you fell this month, who would notice?"),
("A Cord of Three Strands","Near people, or actually braided into their lives?"),
("They Broke Bread in Their Homes","What a living room does that a sanctuary cannot"),
("Carry Each Other's Burdens","Better at carrying than at disclosing"),
("Not Giving Up Meeting Together","A group should occasionally be uncomfortable"),
("The Body Has Many Parts","Not needed, or do not need them &mdash; which error is yours?")],
"exp":["Leaders stand at the front holding signs with a neighborhood and a night. Dismiss into them, not past them.",
"Groups meet in the room before anyone leaves. Sixty seconds, names only. Connection happens or it does not.",
"Rearrange one service into circles of six. Ten-minute message, forty minutes of the thing you are selling.",
"Every group holds one open chair all season and prays over it by name."]},

{"cat":"Christmas Eve","t":"Light in the Dark",
"s":"Why we hold candles and sing in the middle of the night",
"x":"John 1:1-5","b":"Christianity does not deny the darkness; it makes a claim about what the darkness has never been able to do to the light.",
"m":["In him was life, and that life was the light of all mankind.",
"The light shines. Present tense &mdash; right now, in whatever you carried in.",
"The darkness has not overcome it. The verb means both not understood and not extinguished."],
"dev":[("In the Beginning","Before the manger, before the star, before anything"),
("Through Him All Things","The one in the feed trough made the wood it was built from"),
("In Him Was Life","Life as the source, never the reward"),
("The Light of All Mankind","Not a private light, and never was"),
("The Light Shines","Present tense, in whatever you walked in carrying"),
("Not Overcome","What darkness has never once managed to do"),
("Carry One Candle","You were not asked to be the sun")],
"exp":["Kill every light in the building. Light the room from one flame outward and hold the silence past comfortable.",
"Have the youngest reader in the church read John 1:1-5 before anyone preaches.",
"Send every household home with the candle and one line to say over each other at the door.",
"End without a closing announcement. Sing, then let people leave into the dark carrying light."]},

{"cat":"Communion Sundays","t":"Do Not Rush This",
"s":"Making a bigger deal of it, on purpose",
"x":"1 Corinthians 11:23-26","b":"The most theologically dense thing a church does each month usually gets six rushed minutes at the end of a service.",
"m":["On the night he was betrayed. Paul refuses to leave the timestamp out.",
"He gave thanks before he broke it. Gratitude offered before the cost.",
"Until he comes. The table looks forward as much as back."],
"dev":[("On the Night He Was Betrayed","The timestamp Paul will not leave out"),
("He Gave Thanks","Gratitude offered before the breaking"),
("This Is My Body","Four words that have both divided and united the church"),
("Do This in Remembrance","Memory as an act rather than a feeling"),
("The New Covenant","What was actually established that night"),
("You Proclaim His Death","The table preaches whether or not anyone speaks"),
("Until He Comes","The forward-looking half nobody mentions")],
"exp":["One loaf. Families tear from it and serve each other rather than receiving from a tray.",
"Twenty minutes, and do not apologize for the length. Build the service around it instead of after it.",
"Make peace first. Two minutes of silence for people to text or find someone before anyone eats.",
"Collect a benevolence offering at the table, the way the church did for its first three centuries."]},
]

JUMPSTART = [
("Ten Days Through John","The Gospel in two working weeks &mdash; the flagship edition"),
("Ten Weekdays, One Habit","Why the format skips the weekend on purpose"),
("Ten Days in the Life of Jesus","The Gospels condensed to a commute"),
("Ten Days Through Philippians","Joy, written from a prison cell"),
("Ten Days Through James","Practical faith, one page a day"),
("Ten Days in the Psalms","Praying the emotions you actually have"),
("Ten Days Through Acts","How the church started, and what it cost"),
("Ten Days on Prayer","Learning to pray in two working weeks"),
("Ten Days on Money","Financial discipleship for the Monday-to-Friday life"),
("Ten Days on Anxiety","The commute-length antidote"),
("Ten Days on Identity","Who you are before what you do"),
("Ten Days on Marriage","Ten weekday conversations, five minutes each"),
("Ten Days on Parenting","One practice a day, no curriculum required"),
("Ten Days on Forgiveness","Working one thing all the way through"),
("Ten Days on Purpose","Vocation for people with jobs"),
("Ten Days Through Romans 8","Two verses a day, one chapter, ten days"),
("Ten Days on the Names of God","One name a day, said out loud"),
("Ten Days for New Believers","The first two weeks after a decision"),
("Ten Days Back","For anyone restarting after a long absence"),
("Ten Days as a Household","The family edition, at the dinner table"),
]

JOHN10 = [
(1,"In the Beginning Was the Word","John 1:1-18","The claim before the manger"),
(2,"Come and See","John 1:35-51","The first invitation, and the first objection"),
(3,"You Must Be Born Again","John 3:1-21","A respected man arrives at night with questions"),
(4,"The Conversation at Noon","John 4:1-26","The longest recorded conversation Jesus has with anyone"),
(5,"I Am the Bread of Life","John 6:25-40","The crowd wants lunch; he offers himself"),
(6,"The Light of the World","John 8:12 and 9:1-12","A blind man's answer that nobody can argue with"),
(7,"I Am the Good Shepherd","John 10:1-18","He lays it down of his own accord"),
(8,"I Am the Resurrection","John 11:1-44","He weeps at a funeral where he knows the outcome"),
(9,"Love One Another","John 13:1-17, 34-35","The towel, the basin, and the one command"),
(10,"That You May Believe","John 20:24-31","Why the book was written, stated in the book"),
]

FRIENDS_DAY = [
("Glad You Are Here","Written for the person who came because someone asked"),
("Start Here","No background required, nothing assumed"),
("Come and See","The oldest invitation in Christianity"),
("What Are You Actually Looking For?","Desire as the entry point"),
("Nobody Is Doing Fine","Honesty as the front door"),
("The God You Think You Rejected","Correcting the picture they arrived with"),
("You Are Not Too Far","For the person who has already decided they are"),
("Is This All There Is?","Meaning, without a hard sell"),
("Why Bother With Church?","Answering the objection out loud, first"),
("Come as You Are. Really.","The lowest-barrier message in the library"),
("What If It Is True?","Following the claim all the way to its end"),
("Your Friend Brought You for a Reason","Naming it warmly rather than awkwardly"),
("The Question Underneath Your Question","Getting to the real one"),
("Second Chances Are the Whole Point","Grace without an occasion"),
("God Is Not Angry With You","What most guests walk in assuming"),
("Doubt Is Welcome Here","Said in the first two minutes, and meant"),
("One Decision Away","The turning point, offered gently"),
("The Church Has Hurt You. Jesus Has Not.","Separating the institution from the man"),
("Everybody Worships Something","Identifying the actual object"),
("Stay for Coffee","The relational next step, not the aisle"),
]

FRIENDS_MOTIVATE = [
("Who Are You Bringing?","The assignment, given three weeks out"),
("One Name","Ask God for one person and write it on the card"),
("Andrew Brought His Brother","The entire shape of one disciple's ministry"),
("Everybody Knows Somebody","Removing the excuse before it forms"),
("You Do Not Have to Explain Everything","Lowering the bar for the inviter"),
("They Dug Through the Roof","Faith that carries someone who cannot get there"),
("Your Table Is the Front Door","Hospitality before the building"),
("What If They Say No?","Handling the fear that stops the ask"),
("Somebody Brought You","The reason you are sitting in this room"),
("Map Your Circles","The 5F exercise, completed during the service"),
("Invite Them to This, Not to Church","Specificity beats generality every time"),
("Pray for One Person for Three Weeks","The runway before the ask"),
("She Told the Whole Town","Testimony without training"),
("Empty Seats Are the Point","Reframing what a full room is for"),
("Belonging Before Believing","Why bringing beats convincing"),
("The Text You Have Not Sent","The ask, made concrete and dated"),
("Make Room","A congregation's posture toward the new"),
("Who Would Miss You?","Turning the question outward"),
("Bring Them, Then Sit With Them","What happens after they walk in"),
("Next Week Is the Point","Sending them out with a job"),
]
