# -*- coding: utf-8 -*-
def T(n, fmt, spec, use): return [n, fmt, spec, use]

PRINT_THESIS = ("Every library on this platform describes a deliverable. None of them produces one. A hundred print "
 "templates is the layer that turns a described resource into a file a church can hand somebody on Sunday.")

PRINT_RULES = [
 ["Page counts are multiples of four","Saddle-stitch binding folds sheets in half. A 22-page booklet does not exist; it is 24 with two blanks."],
 ["Trim size decides the cost, not the page count","5.5 x 8.5 is two-up on letter stock and roughly half the price of a 6 x 9. Choose the size before you write."],
 ["Every template ships in two states","A designed version for a church with no designer, and an editable version for a church that has one."],
 ["No logo on the cover of a family-facing piece","A keepsake with a church logo on the front is a brochure. Put the mark on the back."],
 ["Type is set for the eye that will read it","Devotionals for older congregations set at 11pt minimum with generous leading. Student material can go to 9.5."],
 ["Bleed, margin and gutter are set before content","Nothing kills a print job later than text sitting 3mm from a trim line."],
 ["One family, ninety-nine variations","Every template shares the same grid, type scale and spacing rules so a church's whole shelf looks related."],
]

GROUPS = [

("Curriculum & Study Guides","15 templates",
 "The core of the catalogue. Everything a group meets around.",
 [T("Six-Session Participant Guide","5.5 x 8.5 booklet","48 pp saddle-stitch","The workhorse. One session per eight pages with room to write."),
  T("Six-Session Leader Guide","5.5 x 8.5 booklet","64 pp","Participant content plus facilitator margins, timings and answers."),
  T("Four-Session Short Study","5.5 x 8.5","32 pp","For a month-long study or a seasonal series."),
  T("Eight-Session Deep Study","6 x 9","96 pp","Longer form, more text, footnote space."),
  T("Twelve-Session Semester","6 x 9","144 pp perfect bound","Classes, ABF and semester-length courses."),
  T("Single-Session Handout","Letter, folded","4 pp","One meeting, no commitment, hand it out at the door."),
  T("Group Discussion Card","4 x 6 card","2 sides","The whole session on one card for a host who forgot."),
  T("Leader Quick-Reference","5.5 x 8.5","4 pp","Timings, transitions and what to do if nobody talks."),
  T("Host Training Booklet","5.5 x 8.5","24 pp","Six modules for a first-time host."),
  T("Study Journal","6 x 9","120 pp","Lined and prompted, for a study that runs a full term."),
  T("Workbook with Exercises","8.5 x 11","64 pp","Assessments, worksheets and tools that need writing room."),
  T("Couples Study Guide","5.5 x 8.5","48 pp","Two-column format so both partners write."),
  T("Men's Study Guide","5.5 x 8.5","40 pp","Shorter sessions, task-oriented layout."),
  T("Women's Study Guide","5.5 x 8.5","56 pp","More reflective space, longer readings."),
  T("Sermon-Aligned Group Guide","5.5 x 8.5","4 pp weekly","Printed each week to match Sunday.")]),

("Devotionals & Journals","15 templates",
 "The daily layer. Where a message becomes a week.",
 [T("Six-Day Devotional Insert","5.5 x 8.5","8 pp","One week, one message. The core of the six-day engine."),
  T("21-Day Devotional","5.5 x 8.5","48 pp","Three weeks with rest days built in."),
  T("30-Day Devotional","5.5 x 8.5","64 pp","A month, with weekly review spreads."),
  T("40-Day Campaign Reader","5.5 x 8.5","96 pp","The churchwide flagship. Six weeks plus front and back matter."),
  T("10-Day Challenge Card Set","3.5 x 5 cards","10 cards + box","One action a day, pocket format."),
  T("Daily Reading Bookmark","2 x 7","2 sides","The cheapest thing you will ever print and among the most used."),
  T("Advent Devotional","5.5 x 8.5","32 pp","Four weeks, family-readable."),
  T("Lent Devotional","5.5 x 8.5","56 pp","Forty days plus Sundays."),
  T("Prayer Journal","6 x 9","96 pp","Prompted, dated, with margins for answers."),
  T("Gratitude Journal","5.5 x 8.5","64 pp","Three lines a day for ninety days."),
  T("Scripture Memory Cards","2.5 x 3.5","52 cards","One a week for a year, boxed."),
  T("Family Table Devotional","5.5 x 8.5","32 pp","One question a night, fifteen minutes."),
  T("Children's Devotional","7 x 7 square","32 pp","Large type, illustration frames, one idea a page."),
  T("Student Devotional","5 x 7","48 pp","Shorter entries, wider margins, room to draw."),
  T("Household Reading Plan","Letter, folded","4 pp","A fridge document for a whole family.")]),

("Campaign & Churchwide","12 templates",
 "Everything a forty-day season needs on paper.",
 [T("Campaign Poster","11 x 17 and 18 x 24","1 side","Lobby and street-facing, two sizes from one file."),
  T("Campaign Invite Card","4 x 6","2 sides","The thing a member hands a neighbour."),
  T("Series Graphic Pack","Screen and print","Multiple","Title slide, lower third, and print-ready title card."),
  T("Lobby Banner","33 x 80 retractable","1 side","Standard retractable dimensions, safe-zone marked."),
  T("Campaign Handbook","5.5 x 8.5","32 pp","The twelve-week countdown for the staff."),
  T("Host Recruitment Card","4 x 6","2 sides","The ask, printed, with the commitment stated plainly."),
  T("Sign-Up Form","Half letter","1 side","Groups, serving and next steps in one form."),
  T("Weekly Bulletin Insert","5.5 x 8.5","2 sides","One per week of the campaign."),
  T("Commitment Card","3.5 x 5","2 sides","For a response moment, with three options and no amount."),
  T("Campaign Calendar","Letter","1 side","Six weeks on a fridge."),
  T("Kickoff Sunday Programme","5.5 x 8.5","4 pp","Order of service plus the campaign explained."),
  T("Celebration Sunday Programme","5.5 x 8.5","4 pp","The close, with stories and the next step.")]),

("Service & Worship","12 templates",
 "The Sunday paper layer.",
 [T("Weekly Bulletin","5.5 x 8.5","4 pp","The standard weekly, four-page fold."),
  T("Expanded Bulletin","8.5 x 11 folded","8 pp","For larger churches with more to say."),
  T("Order of Service","5.5 x 8.5","2 pp","Liturgical churches and special services."),
  T("Sermon Notes Insert","5.5 x 8.5","2 pp","Fill-in outline plus the six-day plan on the back."),
  T("Guest Card","4 x 6","2 sides","Short, warm and asks for less than you think."),
  T("Connection Card","Half letter","2 sides","Next steps, prayer requests and contact."),
  T("Communion Guide","4 x 6","2 sides","For a room where half do not know what this is."),
  T("Baptism Programme","5.5 x 8.5","4 pp","Names, testimonies and what baptism means."),
  T("Child Dedication Certificate","8.5 x 11","1 side","Keepsake, no logo on the front."),
  T("Baptism Certificate","8.5 x 11","1 side","Same family, same grid."),
  T("Membership Booklet","5.5 x 8.5","24 pp","What we believe, how we operate, what membership means."),
  T("Annual Report","8.5 x 11","24 pp","Stories first, numbers second.")]),

("Weddings & Funerals","10 templates",
 "The moment a family first meets a church, printed properly.",
 [T("Wedding Order of Service","5.5 x 8.5","4 pp","Ceremony, readings and the party names."),
  T("Wedding Keepsake Booklet","5.5 x 8.5","8 pp","The homily printed for the couple. No church logo on the cover."),
  T("Premarital Couple Workbook","8.5 x 11","48 pp","Room for two people to write in the same book."),
  T("Funeral Order of Service","5.5 x 8.5","4 pp","Photograph, order, readings and the family's thanks."),
  T("Memorial Programme","5.5 x 8.5","8 pp","For a celebration of life with speakers and images."),
  T("Memory Card","4 x 6","2 sides","Photograph one side, Psalm 23 or a chosen text the other."),
  T("Family Keepsake Booklet","6 x 9","16 pp","The message, the eulogy and photographs, for the family only."),
  T("Committal Card","4 x 6","1 side","The graveside words, printed, for the family to keep."),
  T("Grief Follow-Up Card Set","4 x 6","4 cards","Fourteen days, three months, six months, one year."),
  T("Holiday Grief Guide","5.5 x 8.5","16 pp","For the first Christmas, given in November.")]),

("Children & Student","10 templates",
 "The most defensible line in the catalogue and the least built.",
 [T("Children's Session Take-Home","Letter","1 side","One page a parent will actually read."),
  T("Children's Activity Book","8.5 x 11","32 pp","Six weeks of a campaign, age five to ten."),
  T("Preschool Picture Card","5 x 7","2 sides","One image, one sentence, one action."),
  T("Kids Campaign Journal","7 x 7","48 pp","Large type, drawing space, forty days."),
  T("Three-Jar Money Kit","Print + labels","4 pp + labels","Give, save, spend. The children's generosity spine."),
  T("Student Small Group Guide","5 x 7","40 pp","Six sessions, student-facing."),
  T("Student Leader Guide","5.5 x 8.5","56 pp","For adult leaders of student groups."),
  T("Milestone Certificate Set","8.5 x 11","6 designs","Dedication, first Bible, baptism, graduation and two blanks."),
  T("Parent Equipping Booklet","5.5 x 8.5","16 pp","One rhythm, not five."),
  T("Family Milestone Journal","6 x 9","64 pp","A record kept across a childhood.")]),

("Leader & Training","10 templates",
 "For the people who run everything.",
 [T("Role Development Workbook","8.5 x 11","64 pp","One level of a staff intelligence track."),
  T("Quarterly Planner","8.5 x 11","32 pp","Team plan and personal plan, eight quarters."),
  T("Staff Meeting Session Card","5.5 x 8.5","2 pp","One session, printed, ready to run."),
  T("Volunteer Role Description","Half letter","1 side","The ask, the term and the training, on one page."),
  T("Volunteer Handbook","5.5 x 8.5","24 pp","Onboarding, expectations and safeguarding."),
  T("Leader Training Workbook","8.5 x 11","48 pp","Six modules with exercises."),
  T("Coaching Conversation Guide","5.5 x 8.5","16 pp","Structure for a monthly coaching meeting."),
  T("Assessment Booklet","8.5 x 11","16 pp","Questions, scoring and bands, printed."),
  T("Retreat Run Sheet","Letter","2 pp","The one-day quarterly, timed."),
  T("Certification Portfolio","8.5 x 11","Binder insert set","Evidence pages for a level completion.")]),

("Invitation & Outreach","8 templates",
 "What a member hands a neighbour.",
 [T("Invite Card","4 x 6","2 sides","The single most printed item in any church."),
  T("Door Hanger","4.25 x 11","2 sides","Neighbourhood canvassing."),
  T("Series Postcard","5 x 7","2 sides","Mailable, one series."),
  T("Christmas Invitation","5 x 7","2 sides","Service times, no small print."),
  T("Easter Invitation","5 x 7","2 sides","Same family, different season."),
  T("Guest Welcome Folder","9 x 12 pocket","Folder + inserts","What a first-time family leaves with."),
  T("Community Event Flyer","8.5 x 11","1 side","For a table at a school fair."),
  T("Business Card Invite","3.5 x 2","2 sides","The one a member carries in a wallet.")]),

("Reports & Admin","8 templates",
 "The unglamorous half that builds trust.",
 [T("Monthly Financial Report","8.5 x 11","4 pp","What a board can actually read."),
  T("Impact Report","8.5 x 11","16 pp","Faces first, percentages second, no ask."),
  T("Budget Summary","8.5 x 11","2 pp","One page for the congregation, one for the board."),
  T("Ministry Plan Template","8.5 x 11","8 pp","Annual plan for one department."),
  T("Board Meeting Pack","8.5 x 11","Variable","Agenda, reports and decisions, one cover sheet."),
  T("Gift Acceptance Policy","8.5 x 11","4 pp","The document almost no church has."),
  T("Compensation Philosophy","8.5 x 11","4 pp","Written, defensible and dull on purpose."),
  T("Safeguarding Policy Summary","8.5 x 11","2 pp","The version volunteers actually read.")]),
]

INTEGRATION = [
 ["Every library entry names its template","A session in the staff meeting builder is a Staff Meeting Session Card. A campaign is a 40-Day Campaign Reader plus eight companions. The mapping is fixed, not chosen each time."],
 ["The profile fills the template","Church name, colours, service times and the pastor's voice come from one profile. The template is populated, not designed from scratch."],
 ["Two states ship together","Designed PDF for a church with nobody, editable file for a church with somebody. Same content, same grid."],
 ["Page counts are validated before generation","The engine refuses to output a booklet that is not a multiple of four, which is the error that kills a print run."],
 ["Cover art comes from the cover pipeline","Image-led, built from the title's essence, series reading as a family. Type on a plain colour is not a cover."],
 ["The kit is the unit, not the file","A campaign ships as poster, invite, reader, group guide, bulletin insert, commitment card and calendar. Nobody buys one page."],
]

ECONOMICS = [
 ["Printed journals are the recurring line","A campaign reader at cost plus margin, ordered per household, every campaign, every year. It is the only per-copy revenue in the catalogue."],
 ["Digital is the sample, print is the product","A church will download a PDF and never use it. A box of ninety journals arriving on a Tuesday gets used."],
 ["Print forces the decision","Nobody orders a hundred readers for a campaign they are not going to run."],
 ["Templates make custom builds profitable","A custom build is expensive because it is designed from nothing. Against a hundred templates it is population, not design."],
]
