# -*- coding: utf-8 -*-
from sg50a import C, T

B = [

C("Community & Friendship","Relationships",
 ["Alone","Known","Carried","Honest","Conflict","Together"],
 ["Ecclesiastes 4:9-12","Acts 2:42-47","Hebrews 10:24-25"],
 "The people who most need this study are the least likely to speak. Ask direct questions and wait.",
 [T("Doing Life Together","Not built alone"),T("Friendship","The relationship nobody teaches"),
  T("Being Known","The risk and the reward"),T("Loneliness","Named rather than fixed"),
  T("One Another","The commands that need a small room"),T("Hospitality","Opening a door"),
  T("Community That Lasts","Beyond six weeks"),T("Making Friends as an Adult","Practical"),
  T("Boundaries","Love with edges"),T("Vulnerability","How much and with whom"),
  T("Carrying and Being Carried","Galatians 6, six weeks"),T("When a Friendship Ends","Grief nobody names"),
  T("Jonathan and David","Six weeks in one friendship"),T("Digital Community","Real and not"),
  T("Belonging","Before believing"),T("The Table","Eating together as practice"),
  T("Neighbours","The literal ones"),T("Community and Conflict","Surviving it"),
  T("Multiplying a Group","Handing it on"),T("A Life With People In It","Six weeks toward one")]),

C("Marriage","Relationships",
 ["What you built","How you talk","How you fight","What you spend","How you connect","The long haul"],
 ["Genesis 2:24","Ephesians 5:21-33","1 Corinthians 13:4-7"],
 "Never make couples share in front of the group. Pair work and written exercises do the real work here.",
 [T("The Marriage You Want","Six weeks of practical work"),T("Communication","The skill under everything"),
  T("Conflict","How you fight matters more than whether"),T("Money and Marriage","The fight underneath"),
  T("Intimacy","Handled plainly"),T("Expectations","The assumptions nobody said"),
  T("Forgiveness in Marriage","The daily practice"),T("Roles","Where Christians disagree"),
  T("In-Laws","The relationship nobody plans for"),T("The First Year","For newlyweds"),
  T("Marriage After Children","When it got harder"),T("The Empty Nest","Rediscovering each other"),
  T("Second Marriage","What is different"),T("Blended Marriage","Two households, one home"),
  T("When One Believes","Living with difference"),T("Rebuilding After Betrayal","Slow and honest"),
  T("Praying Together","Six weeks of trying"),T("Serving Together","The habit that binds"),
  T("Friendship in Marriage","The part that has to survive"),T("Marriage for the Long Haul","Decades")]),

C("Parenting","Relationships",
 ["What you are building","Discipline","Discipleship","The culture","Letting go","The blessing"],
 ["Deuteronomy 6:4-9","Ephesians 6:4","Proverbs 22:6"],
 "Every parent in the room feels behind. Say that in session one and the honesty follows.",
 [T("Parenting With Purpose","Beyond survival"),T("Discipline","Correction that forms"),
  T("Discipleship at Home","One rhythm, not five"),T("Screens","The hardest six weeks"),
  T("Parenting Toddlers","Six weeks in the hard years"),T("Parenting Elementary","The window that opens"),
  T("Parenting Teenagers","When the influence shifts"),T("Launching Adults","Letting go well"),
  T("Adult Children","When they are grown"),T("Blessing Your Children","Words they carry"),
  T("Anger in Parenting","Handled honestly"),T("Single Parenting","Named and supported"),
  T("Blended Family Parenting","Two sets of rules"),T("Parenting a Prodigal","The long wait"),
  T("Special Needs Parenting","Six weeks of honesty"),T("Faith at Home","What you actually practise"),
  T("Money and Children","Three jars"),T("Sex and Your Children","The conversations"),
  T("Grandparenting","The second run"),T("Parenting Together","When you disagree")]),

C("Family & Household","Relationships",
 ["The household","The rhythms","The table","The hard parts","The generations","The legacy"],
 ["Joshua 24:15","Psalm 127:1-2","2 Timothy 1:5"],
 "Households come in many shapes. Do not assume a nuclear family in the room or in the language.",
 [T("Household Rhythms","One thing, not five"),T("The Table","Eating together"),
  T("Sabbath at Home","A family day"),T("Family Traditions","Deciding rather than defaulting"),
  T("Caring for Parents","The sandwich years"),T("Siblings","The relationship that outlasts"),
  T("Extended Family","Holidays and boundaries"),T("Family Conflict","Handled honestly"),
  T("Family Secrets","Six weeks of light"),T("Estrangement","When it is broken"),
  T("Serving as a Family","Together, outward"),T("Money in the Household","Shared and honest"),
  T("Hospitality at Home","Opening your door"),T("The Family Story","Knowing where you came from"),
  T("Generational Patterns","Breaking and keeping"),T("Household Prayer","Six weeks of trying"),
  T("Grief in a Family","When one is missing"),T("Adoption and Fostering","Six weeks of preparation"),
  T("Legacy","What you leave"),T("The Household of Faith","Church as family")]),

C("Conflict & Forgiveness","Relationships",
 ["The rupture","The story you told","The conversation","The forgiveness","The repair","The peace"],
 ["Matthew 18:15-17","Ephesians 4:26-32","Romans 12:18"],
 "If there is live conflict in the group, do not run this as a proxy. Handle the specific privately.",
 [T("Hard Conversations","Six weeks learning a skill"),T("Forgiveness","The hardest thing he asked"),
  T("Conflict","Why we avoid it"),T("Assume the Best","The discipline underneath"),
  T("Apologizing","Doing it properly"),T("When They Are Not Sorry","Forgiving anyway"),
  T("Forgiving Yourself","The hardest one"),T("Reconciliation","When it is possible"),
  T("Boundaries and Forgiveness","Both, together"),T("Anger","What is underneath it"),
  T("Bitterness","The root that defiles"),T("Gossip","The sin with no support group"),
  T("Matthew 18","Six weeks in the process"),T("Repair","Coming back after a bad week"),
  T("Peacemaking","Blessed are the"),T("When You Were Wrong","Owning it"),
  T("Family Conflict","The hardest room"),T("Conflict at Work","Six weeks of it"),
  T("Church Conflict","When it happens here"),T("Living at Peace","So far as it depends on you")]),

C("Singleness","Life Stage",
 ["The assumption","The season","The desire","The community","The purpose","The life"],
 ["1 Corinthians 7:32-35","Isaiah 56:3-5","Psalm 68:6"],
 "Never frame singleness as waiting. Check the language in every session before you use it.",
 [T("Singleness","Whole, not waiting"),T("Contentment","In this season"),
  T("Desire","Named honestly"),T("Community for Singles","Building it"),
  T("Purpose","Undivided devotion"),T("Dating","With wisdom"),
  T("Loneliness","Named rather than fixed"),T("Sexuality and Singleness","Handled with care"),
  T("Family for Singles","Chosen and given"),T("The Church and Singles","When it gets it wrong"),
  T("Career and Calling","Freedom to go"),T("Money as a Single","Practical"),
  T("Aging Single","The long view"),T("Single Again","After divorce or death"),
  T("Single Parents","Named and supported"),T("Waiting","And whether that is the word"),
  T("Friendship","The primary relationship"),T("Serving","Where the time goes"),
  T("Hope","Without a promise"),T("A Full Life","Six weeks toward one")]),

C("Young Adults","Life Stage",
 ["The questions","The decisions","The pressure","The faith","The community","The direction"],
 ["1 Timothy 4:12","Ecclesiastes 12:1","Jeremiah 29:11"],
 "Faster pace, harder questions, less assumed background. Do not soften the text for this room.",
 [T("Owning Your Faith","Making it yours"),T("Big Decisions","Six weeks of discernment"),
  T("Money in Your Twenties","Debt, saving and giving"),T("Career","Calling and the first job"),
  T("Dating and Relationships","With intention"),T("Doubt","Handled without panic"),
  T("Community","Building it as an adult"),T("Identity","Beyond what you do"),
  T("Anxiety","The defining struggle"),T("Social Media","Comparison and attention"),
  T("Purpose","When everyone asks what is next"),T("Independence","And what it costs"),
  T("Faith and Culture","Living in the tension"),T("Sex","Honestly and without shame"),
  T("Failure","The first real one"),T("Church","Why bother"),
  T("Habits","What you build now"),T("Family of Origin","What you carry"),
  T("The Next Ten Years","Six weeks of thinking"),T("Following Jesus Now","Not later")]),

C("Midlife & Second Half","Life Stage",
 ["The reckoning","The regret","The reset","The purpose","The generativity","The finish"],
 ["Psalm 90:12","Ecclesiastes 3:1-8","Joel 2:25"],
 "Regret surfaces fast here. Give it room in session two rather than letting it leak through all six.",
 [T("The Second Half","Purpose after fifty"),T("Midlife","Honest six weeks"),
  T("Regret","Naming it and moving"),T("Success to Significance","The turn"),
  T("Mentoring","Giving it away"),T("Aging Well","Body, mind and soul"),
  T("Caring for Parents","The sandwich years"),T("Empty Nest","They left"),
  T("Career Change","At fifty"),T("Money in the Second Half","Retirement and generosity"),
  T("Health","Stewardship in a changing body"),T("Marriage at Midlife","Rediscovering"),
  T("Faith at Midlife","Deeper or drifting"),T("Grandparenting","The second run"),
  T("What You Carry","Wisdom worth passing"),T("Losing Parents","Becoming the elder generation"),
  T("Purpose Now","Not someday"),T("Legacy","What you leave"),
  T("The Years Left","Numbering days"),T("Finishing Well","Working backward")]),

C("Seniors & Legacy","Life Stage",
 ["The season","The losses","The gifts","The passing on","The hope","The finish"],
 ["Psalm 71:18","Psalm 92:12-14","Titus 2:2-5"],
 "Larger type, slower pace, longer memory prompts. Build in time for stories; they are the point.",
 [T("Finishing Well","The last quarter"),T("Legacy","More than money"),
  T("Mentoring the Young","Titus 2, six weeks"),T("Losses","Naming them"),
  T("Grief in Later Life","So many goodbyes"),T("Health and Dependence","Dignity"),
  T("Purpose Now","Still sent"),T("Grandparenting","Influence at a distance"),
  T("Telling Your Story","For the generations"),T("Wills and Estates","Practical and spiritual"),
  T("Forgiveness Late","Making things right"),T("Loneliness","The most common"),
  T("Faith at the End","Deepening"),T("Fear of Dying","Named honestly"),
  T("Heaven","What we actually know"),T("Prayer as Ministry","The work of later years"),
  T("Generosity Late","Giving while living"),T("What You Learned","Six weeks of harvest"),
  T("Blessing the Next Generation","Words that carry"),T("Well Done","The finish line")]),

C("Students & Teens","Life Stage",
 ["The question","The pressure","The truth","The choice","The friends","The next step"],
 ["1 Timothy 4:12","Ecclesiastes 12:1","Proverbs 3:5-6"],
 "Shorter readings, more room to draw, leader carries more. Never shame a student into sharing.",
 [T("Who Am I","Identity for teenagers"),T("Owning Your Faith","Not your parents'"),
  T("Friends","Who you become like"),T("Doubt","It is allowed"),
  T("Anxiety","Named and normal"),T("Social Media","Comparison and worth"),
  T("Sex and Dating","Honest and unashamed"),T("Family","When home is hard"),
  T("School","Purpose in the ordinary"),T("The Bible","How to actually read it"),
  T("Prayer","Starting"),T("Purpose","More than a career"),
  T("Money","Starting early"),T("Courage","Standing alone"),
  T("Failure","When you blew it"),T("Body Image","Handled carefully"),
  T("Serving","Doing something that matters"),T("Telling Your Story","Three minutes"),
  T("After Graduation","Six weeks of preparation"),T("Following Jesus Now","Not later")]),

C("Money & Stewardship","Money",
 ["Whose","The heart","The plan","The debt","The margin","The freedom"],
 ["Psalm 24:1","Luke 16:10-11","1 Timothy 6:6-10"],
 "Never ask anyone to disclose amounts. Income range varies more in this room than in any other study.",
 [T("God Owns It All","Six weeks on ownership"),T("Enough","The number you never named"),
  T("Getting Out of Debt","Practical and pastoral"),T("Budgeting","A plan on paper"),
  T("Saving","Wisdom and worry"),T("Money and Anxiety","The worry underneath"),
  T("Money and Marriage","The fight underneath"),T("Teaching Children About Money","Three jars"),
  T("Contentment","Learned in both directions"),T("Comparison","The joy thief"),
  T("Financial Crisis","Six weeks in the hard place"),T("Money and Work","Earning it well"),
  T("Investing","Wisdom, not tips"),T("Retirement","Planning and purpose"),
  T("Wills and Estates","What leaves at the end"),T("Money and Faith","Trusting with the practical"),
  T("The Danger of Wealth","Uncomfortable and necessary"),T("Financial Margin","Room to say yes"),
  T("Money in the Bible","Six passages"),T("A Faithful Financial Life","Six weeks toward it")]),

C("Generosity","Money",
 ["The premise","The heart","The practice","The obstacle","The community","The life"],
 ["2 Corinthians 9:6-8","Mark 12:41-44","Acts 20:35"],
 "No ask. State that in session one. If the church is running a campaign, say so and separate it clearly.",
 [T("Generous Living","Beyond the tithe"),T("Why We Give","The premise"),
  T("First Fruits","Order reveals priority"),T("Proportion","Percentage over amount"),
  T("Cheerful, Not Compelled","Motive over compliance"),T("The Widow's Mite","Six weeks in four verses"),
  T("Giving Beyond Money","Time, home, attention"),T("Generosity as Discipleship","Not fundraising"),
  T("The Rich Fool","Counting the pronouns"),T("Giving While Living","Not at the end"),
  T("Generosity in Hard Times","When there is less"),T("Teaching Children Generosity","The give jar"),
  T("Generous Community","Acts 4, six weeks"),T("Hospitality as Generosity","The table"),
  T("Generosity and Justice","Where it goes"),T("The Joy of Giving","Six weeks of it"),
  T("Legacy Giving","Past your lifetime"),T("Business and Generosity","For owners"),
  T("Generosity and Contentment","The connection"),T("A Generous Life","Six weeks toward one")]),

C("Work & Vocation","Money",
 ["The design","The curse","The audience","The excellence","The people","The sending"],
 ["Genesis 2:15","Colossians 3:23-24","1 Corinthians 7:17"],
 "Most people have never heard a theology of work. Session one should surprise them.",
 [T("Purpose at Work","Monday is the mission field"),T("Finding Your Calling","More than a job"),
  T("Work Before the Fall","It was always good"),T("As for the Lord","Who you work for"),
  T("Excellence","Skill as witness"),T("Integrity at Work","When it costs"),
  T("Difficult Bosses","Six weeks of reality"),T("Difficult Colleagues","Loving them"),
  T("Ambition","Wanting the right things"),T("Rest and Work","Both"),
  T("When Work Is Hard","Or boring, or wrong"),T("Changing Jobs","Discernment"),
  T("Unemployment","Six weeks of honesty"),T("Retirement","Purpose after work"),
  T("Faith at Work","Witness on Monday"),T("Your Gifts","Discovering and using"),
  T("Work and Family","The negotiation"),T("Money and Work","Earning it well"),
  T("Work as Worship","Romans 12, six weeks"),T("Sent There","1 Corinthians 7:17")]),

C("Business & Marketplace","Money",
 ["The enterprise","The people","The pressure","The profit","The purpose","The exit"],
 ["Proverbs 11:1","Luke 16:10","Colossians 3:23"],
 "Owners carry things employees do not. Do not mix owners and employees in the same group for this one.",
 [T("Business as Ministry","The whole enterprise"),T("Integrity in Business","Honest scales"),
  T("Leading People","Employees as image bearers"),T("Profit","Handled theologically"),
  T("Hiring and Firing","With dignity"),T("Competition","Without compromise"),
  T("Debt and Risk","Wisdom in leverage"),T("Growth","When and whether"),
  T("Partners","Choosing and keeping"),T("Failure","When the business fails"),
  T("Succession","Passing it on"),T("The Exit","Selling, and what then"),
  T("Generosity as an Owner","Giving from the enterprise"),T("Rest as an Owner","The hardest"),
  T("Family Business","Two systems, one table"),T("Culture","What you build"),
  T("Customers","Serving them well"),T("The Weight of It","Six weeks of honesty"),
  T("Kingdom Business","Purpose beyond profit"),T("Finishing as an Owner","The long view")]),

C("Ambition & Success","Money",
 ["The drive","The motive","The cost","The redirect","The measure","The enough"],
 ["Jeremiah 45:5","Philippians 2:3","Mark 8:36"],
 "This study cuts high achievers. Expect defensiveness and let the text do the work.",
 [T("Ambition","Wanting the right things"),T("Success","Redefined"),
  T("The Cost of Getting There","What it took"),T("Comparison","The joy thief"),
  T("Enough Achievement","The line you never drew"),T("Recognition","What praise does"),
  T("Failure","And what it teaches"),T("Drive and Rest","Both"),
  T("Great Things for Yourself","Jeremiah 45, six weeks"),T("Serving Ambition","Redirected"),
  T("The Second Chair","Leading from beside"),T("Losing","Six weeks of honesty"),
  T("Identity and Work","When the job is who you are"),T("What You Would Trade","Mark 8:36"),
  T("Legacy Over Résumé","The two lists"),T("Contentment and Drive","Held together"),
  T("Ambition in Ministry","The unnamed one"),T("Ambition at Home","The family cost"),
  T("Holy Ambition","Romans 15:20"),T("The Measure That Matters","Six weeks toward it")]),

C("Suffering & Lament","Struggle",
 ["The pain","The question","The lament","The silence","The presence","The hope"],
 ["Psalm 88","Lamentations 3:19-24","2 Corinthians 1:3-4"],
 "Do not rush to resolution. Psalm 88 ends in darkness and God put it in the book.",
 [T("When God Feels Far","Six weeks in the dark"),T("Suffering","The oldest question"),
  T("Lament","The prayer we stopped praying"),T("Job","Six weeks in the hardest book"),
  T("Why","And whether it gets answered"),T("The Silence of God","Named honestly"),
  T("Anger at God","Making room for it"),T("Waiting","The season nobody chooses"),
  T("Disappointment With God","Saying it out loud"),T("Chronic Pain","Faith in a failing body"),
  T("Illness","The diagnosis and after"),T("Caregiving","The invisible suffering"),
  T("Injustice","When it is not fair"),T("Comfort","2 Corinthians 1, six weeks"),
  T("Presence","What actually helps"),T("Hope","Without pretending"),
  T("The Psalms of Lament","Six of them"),T("Suffering and Community","Not alone"),
  T("What Suffering Produces","Romans 5, carefully"),T("Still Here","Six weeks of endurance")]),

C("Anxiety & Mental Health","Struggle",
 ["The reality","The body","The thoughts","The practices","The help","The peace"],
 ["Philippians 4:6-7","Psalm 42:5","1 Peter 5:7"],
 "Have three referral names before session one. Say clearly that this study is not treatment and does not replace it.",
 [T("Anxiety","Named honestly"),T("Do Not Worry","Matthew 6, carefully"),
  T("The Body","Sleep, movement and the physical"),T("Thoughts","Taken captive"),
  T("Depression","Six weeks of honesty"),T("Panic","What happens and what helps"),
  T("Getting Help","Counselling and medication"),T("Faith and Mental Health","Both taken seriously"),
  T("Shame","The one nobody names"),T("Perfectionism","The driver underneath"),
  T("Burnout","Before and after"),T("Loneliness","The health risk"),
  T("Grief and Depression","Telling them apart"),T("Supporting Someone","When it is not you"),
  T("Practices That Help","Six weeks of them"),T("Prayer and Anxiety","Honest praying"),
  T("Community and Mental Health","Not alone"),T("The Psalms and the Mind","Borrowed words"),
  T("Hope","Without minimising"),T("Peace","Six weeks toward it")]),

C("Grief & Loss","Struggle",
 ["The loss","The wave","The anger","The guilt","The remembering","The living"],
 ["Psalm 34:18","John 11:35","Revelation 21:4"],
 "Slower pace, permission to pass every week, no forced sharing. Ninety seconds of silence is fine.",
 [T("Grief","Walking through loss"),T("What Is Normal","There is no timeline"),
  T("Losing a Spouse","The particular loneliness"),T("Losing a Parent","Becoming the elder"),
  T("Losing a Child","The grief with no order"),T("Losing a Friend","Unrecognised grief"),
  T("Sudden Loss","When there was no goodbye"),T("Long Illness","Exhausted and relieved"),
  T("Anger in Grief","Making room"),T("Guilt and What-If","The questions that will not stop"),
  T("The First Year","Every first"),T("The Second Year","Often harder"),
  T("Holidays","The hardest days"),T("Remembering","Keeping them present"),
  T("Grief and Faith","When you cannot pray"),T("Children Grieving","What is normal at each age"),
  T("Miscarriage and Infertility","The grief nobody names"),T("Losing a Marriage","Divorce as grief"),
  T("Living Again","Without betraying them"),T("Grief That Becomes Ministry","Comfort with comfort")]),

C("Recovery & Freedom","Struggle",
 ["The truth","The powerlessness","The honesty","The community","The amends","The day"],
 ["James 5:16","1 Corinthians 10:13","Galatians 5:1"],
 "Trauma-aware language throughout. No shame framing. Referral names ready and offered without being asked.",
 [T("Freedom","Six weeks toward it"),T("Shame","The one nobody names"),
  T("Addiction","Named honestly"),T("Codependency","Love with boundaries"),
  T("Anger","What is underneath"),T("Pornography","Handled without shame"),
  T("Food","A hard and careful six weeks"),T("Alcohol","Honest questions"),
  T("Control","The addiction nobody calls one"),T("Approval","Needing to be liked"),
  T("After Betrayal","Rebuilding"),T("Hope After Failure","When you caused it"),
  T("The Long Recovery","Year two and beyond"),T("Relapse","And getting back up"),
  T("Making Amends","The hardest step"),T("Family in Recovery","When one is and one is not"),
  T("Trauma","With care and referral"),T("Forgiving Someone Who Hurt You","Slowly"),
  T("Sponsorship and Support","Who walks with you"),T("One Day","Six weeks of practice")]),

C("Doubt & Deconstruction","Struggle",
 ["The crack","The question","The honesty","The tradition","The community","The way through"],
 ["Mark 9:24","Psalm 73","John 20:24-29"],
 "Do not defend. The person who feels argued with will leave and not come back.",
 [T("Doubt","It is allowed"),T("Deconstruction","Six weeks of honesty"),
  T("Thomas","The doubter Jesus welcomed"),T("Psalm 73","When the wicked prosper"),
  T("When Church Hurt You","Named and heard"),T("Hard Questions","Six of them"),
  T("Faith and Evidence","What we actually have"),T("The Bible and Doubt","Reading it again"),
  T("Hell","The doctrine that breaks people"),T("Science and Faith","No false conflict"),
  T("Sexuality and Faith","With humility and care"),T("Politics and Faith","Untangling them"),
  T("What You Actually Believe","Six weeks of inventory"),T("Rebuilding","After deconstruction"),
  T("Staying","When leaving is easier"),T("Community in Doubt","Not alone"),
  T("The Dark Night","A long tradition"),T("Honest Prayer","When you are not sure"),
  T("Help My Unbelief","Mark 9, six weeks"),T("Faith on the Other Side","What it looks like")]),

C("Evangelism & Witness","Mission",
 ["The fear","The story","The relationship","The invitation","The question","The going"],
 ["1 Peter 3:15","John 1:45-46","Matthew 28:18-20"],
 "Guilt kills this study. Aim at one relationship rather than a strategy.",
 [T("Come and See","Inviting without being weird"),T("Your Story","Three minutes"),
  T("The Gospel","Explaining it simply"),T("Your One","Praying for a name"),
  T("Answering Questions","When you do not know"),T("Loving Your Neighbour","The literal ones"),
  T("Faith at Work","Witness on Monday"),T("When They Say No","And staying friends"),
  T("Hospitality as Evangelism","The table"),T("Fear","What actually stops us"),
  T("Talking About Jesus","Naturally"),T("Praying for the Lost","Six weeks of it"),
  T("Family Members","The hardest ones"),T("Serving as Witness","Deeds and words"),
  T("Cultural Objections","Six common ones"),T("Discipling a New Believer","What comes after"),
  T("Bringing Someone to Church","The invitation"),T("Following Up","Not letting it drop"),
  T("A Witnessing Life","Six weeks toward it"),T("Sent","Every day, everywhere")]),

C("Mission & the City","Mission",
 ["The place","The need","The partner","The work","The relationship","The blessing"],
 ["Jeremiah 29:4-7","Matthew 5:13-16","Luke 10:25-37"],
 "Push toward specifics — streets, schools, names. Mission conversations die on abstraction.",
 [T("Seek the Welfare of the City","Jeremiah 29, six weeks"),T("Who Is My Neighbour","The parable"),
  T("Serving the City","Beyond the walls"),T("Helping Without Hurting","Doing no harm"),
  T("Poverty","Six weeks of understanding"),T("Homelessness","With dignity"),
  T("Refugees","The nations already here"),T("Schools","Where a church can serve"),
  T("Prisons","The ministry nobody wants"),T("Foster and Adoption","Six weeks of preparation"),
  T("Partnership","Joining rather than duplicating"),T("Short-Term Missions","Done well"),
  T("Global Missions","Sending and going"),T("The Persecuted Church","Our family"),
  T("Business as Mission","Access through vocation"),T("Your Street","Starting where you are"),
  T("Long Faithfulness","Decades in one place"),T("What Would the City Miss","The question"),
  T("Mission as a Family","Serving together"),T("A Sent Life","Six weeks toward it")]),

C("Justice & Mercy","Mission",
 ["The command","The seeing","The learning","The listening","The doing","The staying"],
 ["Micah 6:8","Isaiah 1:17","James 1:27"],
 "Learn before you speak. Groups that move to action in week one usually do harm.",
 [T("Micah 6:8","Six weeks in one verse"),T("Justice in Scripture","The thread"),
  T("The Prophets and Justice","Amos and Isaiah"),T("Jesus and the Marginalised","Who he went to"),
  T("Mercy","More than kindness"),T("Poverty","Understanding before acting"),
  T("Race","With humility and honesty"),T("The Orphan and the Widow","The measure God uses"),
  T("Immigration","Scripture and the stranger"),T("Human Trafficking","Six weeks of awareness"),
  T("Creation Care","Stewardship of a place"),T("Advocacy","Speaking for those who cannot"),
  T("Charity and Justice","The difference"),T("Listening First","Before helping"),
  T("Long Obedience in Justice","Not a season"),T("Justice and the Gospel","Held together"),
  T("Justice at Home","Starting close"),T("When You Get It Wrong","Repair"),
  T("Justice and Worship","When God rejects the offering"),T("A Just Life","Six weeks toward it")]),

C("Leadership","Leadership",
 ["Yourself","Your character","Your people","Your decisions","Your limits","Your finish"],
 ["1 Peter 5:2-3","Mark 10:42-45","2 Timothy 2:2"],
 "Works for volunteer leaders as well as staff. Ask who they lead in session one and keep it concrete.",
 [T("Leading Yourself","Before you lead anyone"),T("Serving Leadership","The towel model"),
  T("Developing People","Growing others"),T("Difficult Conversations","A leadership skill"),
  T("Vision","Seeing and saying"),T("Decisions","How to make them"),
  T("Delegation","Jethro's advice"),T("Burnout","Before it arrives"),
  T("Character in Leadership","The whole risk"),T("Feedback","Giving and receiving"),
  T("Leading Change","Sequencing it"),T("Conflict as a Leader","Six weeks of it"),
  T("Leading Volunteers","Different from employees"),T("Building a Team","Six weeks"),
  T("Leading Peers","Without authority"),T("Leading Up","Telling your leader the truth"),
  T("Succession","Raising your replacement"),T("Failure as a Leader","When it was you"),
  T("Finishing Well","The long view"),T("A Leader Worth Following","Six weeks toward it")]),

C("Seasons & Church Calendar","Seasons",
 ["The season","The text","The practice","The household","The community","The next"],
 ["Ecclesiastes 3:1","Luke 2:1-20","1 Corinthians 15:20"],
 "Run these when they are actually happening. A Lent study in September teaches nothing.",
 [T("Advent","Four weeks plus two"),T("Christmas","The incarnation"),
  T("Epiphany","Light to the nations"),T("Lent","Toward the cross"),
  T("Holy Week","Sunday to Sunday"),T("Easter Season","Six weeks after the tomb"),
  T("Pentecost","The Spirit given"),T("Ordinary Time","Most of the year"),
  T("New Year","Starting again"),T("Summer","Six weeks, lighter"),
  T("Back to School","For households with children"),T("Thanksgiving","Gratitude for six weeks"),
  T("Year End","Closing well"),T("All Saints","Remembering together"),
  T("Fall Launch","Getting a group started"),T("The Church Year","Six weeks of orientation"),
  T("Seasons of Life","And the church calendar"),T("Waiting Seasons","Advent as a metaphor"),
  T("Fasting Seasons","Lent beyond chocolate"),T("A Rhythm of Seasons","Six weeks to plan a year")]),
]
