# -*- coding: utf-8 -*-
def C(n, grp, arc, pas, notes, tt): return {"n":n,"g":grp,"arc":arc,"pas":pas,"notes":notes,"tt":tt}
def T(a,b): return [a,b]

A = [

C("The Gospels","Bible",
 ["Meet him","Watch him","Hear him","Follow him","Lose him","Find him"],
 ["Mark 1:1","John 20:31","Luke 1:1-4"],
 "Read the text aloud every week before discussing it. Groups drift into opinion the moment the passage is left behind.",
 [T("Mark","The fastest gospel, six weeks"),T("John","That you may believe"),
  T("Luke","The gospel for outsiders"),T("Matthew","The King and his kingdom"),
  T("The Sermon on the Mount","Six weeks in Matthew 5 to 7"),T("The Passion Week","Sunday to Sunday"),
  T("The Last Supper","John 13 to 17"),T("The Birth Narratives","Both accounts, honestly"),
  T("Jesus and Women","Every encounter, six weeks"),T("Jesus and Money","What he actually said"),
  T("The I Am Sayings","Seven claims, six weeks"),T("Jesus and the Outsider","Who he went to"),
  T("The Temptations","Forty days in the wilderness"),T("Jesus and the Religious","The conflict that killed him"),
  T("The Resurrection Appearances","Six encounters after the tomb"),T("Jesus and the Twelve","How he built a team"),
  T("The Beatitudes","Eight blessings, six weeks"),T("Jesus and Suffering","What he did with pain"),
  T("The Great Commission","Sent, six weeks"),T("Who Do You Say I Am","The question at the centre")]),

C("Old Testament Narrative","Bible",
 ["The call","The struggle","The failure","The mercy","The turn","The legacy"],
 ["Genesis 12:1-3","Exodus 3:1-14","1 Samuel 16:7"],
 "These are stories before they are lessons. Let the narrative land before anyone applies it.",
 [T("Abraham","Six weeks with the man who went"),T("Joseph","From the pit to the palace"),
  T("Moses","The reluctant deliverer"),T("Joshua","Courage and the land"),
  T("Ruth","Loyalty in a hard season"),T("David","The heart God chose"),
  T("Elijah","Fire, cave and whisper"),T("Nehemiah","Building against opposition"),
  T("Esther","For such a time"),T("Daniel","Faithful in Babylon"),
  T("Gideon","The least likely"),T("Samson","Strength and failure"),
  T("Hannah","The prayer that changed a nation"),T("Jacob","Wrestling with God"),
  T("Job","Six weeks in the hardest book"),T("Jonah","The reluctant prophet"),
  T("Solomon","Wisdom and its limits"),T("The Exodus","Out of Egypt"),
  T("The Judges","When everyone did what was right"),T("The Exile","When it all fell apart")]),

C("Psalms & Wisdom","Bible",
 ["Praise","Lament","Trust","Wisdom","Confession","Thanksgiving"],
 ["Psalm 1","Proverbs 1:7","Ecclesiastes 1:2"],
 "Read psalms aloud. They were written to be spoken and they collapse on the page in silence.",
 [T("Psalms for Every Season","Six moods, six weeks"),T("The Psalms of Lament","Permission to complain"),
  T("Psalm 23","Six weeks in six verses"),T("Psalm 119","The longest chapter, in six"),
  T("The Psalms of Ascent","Songs for the journey"),T("Proverbs on Money","What wisdom says"),
  T("Proverbs on Speech","The tongue, six weeks"),T("Proverbs on Work","Diligence and the sluggard"),
  T("Proverbs on Relationships","Friends, family and fools"),T("Proverbs for Parents","Raising wise children"),
  T("Ecclesiastes","Meaning under the sun"),T("Song of Songs","Love, handled honestly"),
  T("The Wisdom of Job","When wisdom fails"),T("Praying the Psalms","Six weeks of borrowed words"),
  T("Psalms of Confession","Coming clean"),T("Psalms of Trust","When you cannot see"),
  T("The Imprecatory Psalms","The angry ones nobody preaches"),T("Wisdom and Folly","The two roads"),
  T("The Fear of the Lord","Where wisdom starts"),T("Psalms of Thanksgiving","Naming what he did")]),

C("The Prophets","Bible",
 ["The word","The warning","The refusal","The judgement","The promise","The hope"],
 ["Isaiah 6:8","Jeremiah 1:4-10","Amos 5:24"],
 "Prophets are not fortune tellers. Keep the group in the historical situation before applying anything.",
 [T("Isaiah","The holy one of Israel"),T("Jeremiah","The weeping prophet"),
  T("Ezekiel","Visions in exile"),T("Hosea","Love that will not quit"),
  T("Amos","Justice rolls down"),T("Micah","What the Lord requires"),
  T("Habakkuk","How long, O Lord"),T("Malachi","The last word before silence"),
  T("Joel","The day of the Lord"),T("Zechariah","Visions of what is coming"),
  T("The Minor Prophets","Twelve books, six weeks"),T("Prophets and Justice","The social conscience of Scripture"),
  T("Prophets and Worship","When God rejects the offering"),T("Messianic Prophecy","What they saw coming"),
  T("Prophets and Exile","Faith when the world ends"),T("The Suffering Servant","Isaiah 53, six weeks"),
  T("Calling and Reluctance","The prophets who said no"),T("Judgement and Mercy","Both, always"),
  T("Prophets for Today","Reading them without abusing them"),T("The Silence Between","Four hundred years")]),

C("Paul's Letters","Bible",
 ["The greeting","The problem","The gospel","The argument","The application","The blessing"],
 ["Romans 1:16","Galatians 2:20","Philippians 1:6"],
 "Read the whole letter in one sitting before session one. Everything makes more sense afterwards.",
 [T("Romans","The gospel, six weeks"),T("Galatians","Freedom"),
  T("Ephesians","Who you are now"),T("Philippians","Joy from a prison"),
  T("Colossians","Christ above all"),T("1 Thessalonians","Waiting well"),
  T("1 Corinthians","A messy church"),T("2 Corinthians","Strength in weakness"),
  T("1 Timothy","How to lead a church"),T("2 Timothy","Paul's last letter"),
  T("Titus","Sound doctrine, good works"),T("Philemon","A runaway and a brother"),
  T("Romans 8","Six weeks in one chapter"),T("1 Corinthians 13","Love, honestly"),
  T("The Armour of God","Ephesians 6, six weeks"),T("Paul on Grace","The centre of it all"),
  T("Paul on the Church","One body"),T("Paul on Suffering","The thorn"),
  T("Paul on Money","Contentment and generosity"),T("Paul's Prayers","Six he prayed for churches")]),

C("General Epistles & Revelation","Bible",
 ["The situation","The exhortation","The warning","The comfort","The endurance","The end"],
 ["Hebrews 12:1-2","James 1:2-4","Revelation 21:5"],
 "Revelation groups derail into speculation fast. Keep returning to the question: what did this say to a suffering church?",
 [T("Hebrews","Better, six weeks"),T("James","Faith that works"),
  T("1 Peter","Living as exiles"),T("2 Peter","Guarding the truth"),
  T("1 John","How to know"),T("Jude","Contending"),
  T("Revelation","Hope for a suffering church"),T("The Seven Churches","Revelation 2 and 3"),
  T("Hebrews 11","The hall of faith"),T("The Hard Sayings of Hebrews","Warning passages"),
  T("James on the Tongue","Six weeks on speech"),T("James on Wealth","Uncomfortable and necessary"),
  T("1 Peter on Suffering","When it costs"),T("1 John on Love","The test"),
  T("The Return of Christ","What we actually know"),T("Heaven","What Scripture promises"),
  T("The New Creation","Revelation 21 and 22"),T("Endurance","The theme of the epistles"),
  T("Assurance","How you can be sure"),T("Worship in Revelation","Joining what is already happening")]),

C("Torah & Law","Bible",
 ["Creation","Covenant","Command","Failure","Mercy","Fulfilment"],
 ["Genesis 1:1","Exodus 20:1-17","Deuteronomy 6:4-5"],
 "Groups get stuck on the strange laws. Give the historical context early and keep moving to the covenant story.",
 [T("Genesis 1 to 11","Beginnings"),T("Genesis 12 to 50","The family God chose"),
  T("Exodus","Rescued"),T("The Ten Commandments","Six weeks, ten words"),
  T("Leviticus","Holiness, made understandable"),T("Numbers","Wandering"),
  T("Deuteronomy","The second telling"),T("The Tabernacle","God with them"),
  T("The Sacrificial System","Why blood"),T("The Sabbath","The commandment we skip"),
  T("Creation","Six weeks in Genesis 1 and 2"),T("The Fall","What broke"),
  T("The Flood","Judgement and covenant"),T("The Covenants","Six agreements, six weeks"),
  T("Clean and Unclean","Making sense of it"),T("The Feasts","Israel's calendar"),
  T("Law and Grace","How they fit"),T("The Image of God","What it means"),
  T("Land and Promise","The thread through the Torah"),T("Reading the Old Testament as a Christian","Six weeks of method")]),

C("Parables of Jesus","Bible",
 ["The setup","The story","The twist","The offence","The point","The response"],
 ["Matthew 13:10-17","Luke 15:1-2","Mark 4:33-34"],
 "Do not explain the parable before the group sits in it. The discomfort is the teaching.",
 [T("The Parables","Six of the greatest"),T("The Prodigal Son","Three characters, six weeks"),
  T("The Good Samaritan","Who is my neighbour"),T("The Sower","Four soils"),
  T("The Talents","What you did with it"),T("The Rich Fool","Counting the pronouns"),
  T("The Lost Things","Luke 15, six weeks"),T("The Unforgiving Servant","Seventy times seven"),
  T("The Ten Virgins","Ready or not"),T("The Sheep and the Goats","What you did for the least"),
  T("The Vineyard Workers","Grace that offends"),T("The Rich Man and Lazarus","The great reversal"),
  T("The Persistent Widow","Keep asking"),T("The Pharisee and the Tax Collector","Two prayers"),
  T("The Wedding Banquet","The invitation refused"),T("The Mustard Seed","Small beginnings"),
  T("The Hidden Treasure","Worth everything"),T("Parables of the Kingdom","What it is like"),
  T("Parables of Judgement","The hard ones"),T("Parables About Money","Six of them")]),

C("Miracles & Signs","Bible",
 ["The need","The faith","The word","The change","The response","The meaning"],
 ["John 2:11","Mark 2:1-12","John 9:1-7"],
 "Someone in the room has prayed for a healing that did not come. Acknowledge that in session one, not at the end.",
 [T("The Signs of John","Seven miracles, six weeks"),T("The Healings","Who Jesus touched"),
  T("Feeding the Five Thousand","Six weeks in one miracle"),T("Water into Wine","The first sign"),
  T("Calming the Storm","Who is this"),T("Raising Lazarus","I am the resurrection"),
  T("The Blind Man","John 9, six weeks"),T("Walking on Water","Peter got out"),
  T("The Bleeding Woman","She touched him"),T("Miracles in Acts","The church continues"),
  T("Old Testament Miracles","Elijah and Elisha"),T("When Healing Does Not Come","Honest and pastoral"),
  T("The Miracles of Provision","Manna to loaves"),T("Deliverance","The unseen realm"),
  T("Faith and Healing","What Scripture actually says"),T("The Purpose of Signs","Why they happened"),
  T("Miracles and Doubt","Holding both"),T("The Greatest Miracle","Resurrection"),
  T("Praying for Healing","How, and what then"),T("Everyday Miracles","Seeing what is already there")]),

C("People of the Bible","Bible",
 ["Who they were","What they faced","What they did","What it cost","What God did","What we learn"],
 ["Hebrews 11:32-40","1 Corinthians 10:11","Romans 15:4"],
 "Do not sanitise them. The Bible does not, and groups trust the material more when the failures stay in.",
 [T("Women of the Bible","Twelve, six weeks"),T("Unlikely Leaders","The ones nobody picked"),
  T("The Twelve","Who they were before"),T("Peter","Failure and restoration"),
  T("Paul","From persecutor to apostle"),T("Mary","The mother of Jesus"),
  T("Barnabas","The encourager"),T("Timothy","Young and leading"),
  T("Priscilla and Aquila","A couple in ministry"),T("The Outsiders","Rahab, Ruth, the centurion"),
  T("Kings of Israel","Six of them"),T("Fathers in Scripture","Good and terrible"),
  T("Mothers in Scripture","Six women, six weeks"),T("The Prophets' Lives","Costly obedience"),
  T("Friends in Scripture","Six friendships"),T("Enemies of God's People","And what happened"),
  T("Those Who Finished Well","And those who did not"),T("The Minor Characters","Named once and remembered"),
  T("The Family Tree of Jesus","Matthew 1, six weeks"),T("People Who Doubted","And stayed")]),

C("Foundations of Faith","Doctrine",
 ["The question","The claim","The evidence","The objection","The response","The step"],
 ["John 3:16","Romans 10:9","Acts 2:38"],
 "Assume nothing. If a term appears, define it the first time, every time.",
 [T("Who Is Jesus","Six weeks in the claims"),T("What We Believe","The core, no jargon"),
  T("How to Read the Bible","For someone who never has"),T("Prayer for Beginners","Learning by doing"),
  T("Following Jesus","What actually changes"),T("The Gospel in Six Words","Creation to restoration"),
  T("Questions People Ask","Six honest objections"),T("Your First Ninety Days","For someone who just started"),
  T("Baptism","What it is and why"),T("Communion","The table explained"),
  T("The Church","Why you need one"),T("Sin and Grace","The two words"),
  T("Repentance","What it actually means"),T("Assurance","How you can know"),
  T("The Holy Spirit","Who he is"),T("Reading a Gospel","Mark in six weeks"),
  T("Belonging Before Believing","Six weeks for someone exploring"),T("Starting Over","For someone coming back"),
  T("What Happens When You Die","Handled plainly"),T("The Next Step","Six weeks toward baptism")]),

C("Doctrine & Theology","Doctrine",
 ["The doctrine","The Scripture","The history","The disagreement","The application","The worship"],
 ["2 Timothy 3:16-17","Jude 3","Titus 2:1"],
 "Name where mature Christians disagree and hold it there. A group that thinks its view is the only view is not being formed.",
 [T("The Trinity","One God, three persons"),T("The Attributes of God","Six weeks on who he is"),
  T("Christology","Fully God, fully man"),T("The Holy Spirit","Person and work"),
  T("Salvation","Six weeks on how"),T("Grace","The centre"),
  T("The Cross","What happened there"),T("Justification","Declared righteous"),
  T("Sanctification","Becoming"),T("Election and Free Will","Held with humility"),
  T("The Bible","Inspiration and authority"),T("Sin","The doctrine nobody wants"),
  T("The Image of God","Human dignity"),T("The Church","What it is for"),
  T("The Sacraments","Baptism and communion"),T("Eschatology","Last things, held loosely"),
  T("Heaven and Hell","What Scripture says"),T("Creation","Six weeks, several views"),
  T("Covenant","The thread"),T("Why Doctrine Matters","For a group that thinks it does not")]),

C("Apologetics & Hard Questions","Doctrine",
 ["The question","Why it is asked","What Scripture says","What history shows","What remains","How to answer"],
 ["1 Peter 3:15","Acts 17:16-34","Colossians 4:5-6"],
 "The goal is not winning. If someone leaves feeling defeated rather than heard, the session failed.",
 [T("Hard Questions","Six honest ones"),T("Why Suffering","The oldest objection"),
  T("Can I Trust the Bible","Manuscripts and history"),T("Science and Faith","Six weeks, no false conflict"),
  T("Other Religions","Handled with respect"),T("The Church's Failures","Owned honestly"),
  T("Miracles","Are they reasonable"),T("The Resurrection","The evidence"),
  T("Hell","The hardest doctrine"),T("Sexuality and Scripture","With care and humility"),
  T("Violence in the Old Testament","Not explained away"),T("Does God Exist","Six weeks of argument"),
  T("Why This Religion","The uniqueness question"),T("Faith and Doubt","Held together"),
  T("Answering a Friend","How to have the conversation"),T("The Problem of Evil","Six weeks in it"),
  T("Prayer and Unanswered Prayer","The honest version"),T("Was Jesus Real","The historical case"),
  T("Church History's Hard Chapters","Facing them"),T("Living the Answer","When argument runs out")]),

C("The Church","Doctrine",
 ["What it is","What it is for","How it works","Where it fails","What it needs","Your part"],
 ["Acts 2:42-47","Ephesians 4:11-16","1 Corinthians 12:12-27"],
 "Someone in the room has been hurt by a church. Make room for that in session one or it will surface as cynicism in session four.",
 [T("The Church","What it actually is"),T("Membership","Why it matters"),
  T("Body Life","1 Corinthians 12, six weeks"),T("Church History","Two thousand years, six weeks"),
  T("The Early Church","Acts, six weeks"),T("Leadership in the Church","Elders and deacons"),
  T("Worship","Why we gather"),T("The Ordinances","Baptism and the table"),
  T("Church Discipline","Matthew 18, handled well"),T("Unity","Why it is so hard"),
  T("When Church Hurts","Six weeks of honest repair"),T("Denominations","Why there are so many"),
  T("The Global Church","Beyond our building"),T("The Persecuted Church","Our family"),
  T("Serving in the Church","Finding your place"),T("Giving to the Church","Why and how"),
  T("The Church and Culture","Engagement without capitulation"),T("Planting Churches","Multiplication"),
  T("Why Church at All","For the deconstructing"),T("Loving Your Church","Warts and all")]),

C("Spiritual Warfare & the Unseen","Doctrine",
 ["The reality","The enemy","The battle","The armour","The victory","The vigilance"],
 ["Ephesians 6:10-18","1 Peter 5:8-9","James 4:7"],
 "Two errors: obsession and dismissal. Name both in session one and steer between them.",
 [T("The Armour of God","Ephesians 6, six weeks"),T("The Unseen Realm","What Scripture describes"),
  T("Temptation","How it works and what to do"),T("The Lies We Believe","And the truth that answers"),
  T("Angels","What Scripture actually says"),T("Spiritual Disciplines as Defence","Practices that protect"),
  T("Standing Firm","When you are under pressure"),T("Prayer as Warfare","Six weeks of praying differently"),
  T("The Battle for the Mind","Thoughts taken captive"),T("Deliverance","Handled carefully"),
  T("The Enemy's Tactics","Six of them"),T("Victory in Christ","Already won"),
  T("Guarding Your Heart","Proverbs 4:23, six weeks"),T("Community as Protection","Not alone"),
  T("Fear","The weapon he uses most"),T("Accusation and Condemnation","Telling the difference"),
  T("Discernment","Testing what you hear"),T("When You Fall","Getting back up"),
  T("Persevering Under Attack","The long fight"),T("The End of the Story","How it finishes")]),

C("Spiritual Practices","Practices",
 ["Why","What it is","How to start","The obstacle","Doing it together","Keeping it"],
 ["1 Timothy 4:7-8","Psalm 1:2","Colossians 3:16"],
 "Every session assigns something to do. A practices group that only discusses practices has failed.",
 [T("The Practices","Six disciplines, six weeks"),T("Sabbath","The day we gave away"),
  T("Fasting","A dropped discipline"),T("Silence and Solitude","Alone on purpose"),
  T("Scripture Memory","Hiding it in your heart"),T("Confession","The practice we lost"),
  T("Simplicity","Wanting less"),T("Gratitude","Three things, every morning"),
  T("Journaling","Writing your way to clarity"),T("Meditation","Biblical, not Eastern"),
  T("Service as a Practice","Formed by doing"),T("Hospitality","Opening a door"),
  T("Generosity as a Practice","Formed by giving"),T("Examen","Reviewing a day with God"),
  T("Lectio Divina","Reading slowly"),T("Fixed-Hour Prayer","Praying by the clock"),
  T("Retreat","A day away"),T("Rule of Life","Rhythms written down"),
  T("Digital Sabbath","Attention as stewardship"),T("A Year of Practices","Six weeks to plan it")]),

C("Prayer","Practices",
 ["Learning","Asking","Listening","Persisting","Together","Living it"],
 ["Luke 11:1-13","Matthew 6:5-15","Philippians 4:6-7"],
 "Keep commitments small. Ambitious prayer commitments made in a room fail by Wednesday.",
 [T("Teach Us to Pray","Luke 11, six weeks"),T("The Lord's Prayer","Line by line"),
  T("Praying the Psalms","Borrowed words"),T("Listening Prayer","The half we skip"),
  T("Persistent Prayer","Keep asking"),T("Praying for Others","Intercession"),
  T("Praying Together","In a group and in a household"),T("When Prayer Feels Empty","Honest and pastoral"),
  T("Unanswered Prayer","The hardest six weeks"),T("Praying Scripture","Letting the Word shape it"),
  T("Praying for Your City","Beyond your walls"),T("Praying With Your Spouse","Six weeks of trying"),
  T("Praying With Your Children","A household rhythm"),T("Fasting and Prayer","The pairing"),
  T("Praying Through Grief","Words when there are none"),T("Praying Boldly","Asking for more"),
  T("Contemplative Prayer","Being before asking"),T("Warfare Prayer","Standing firm"),
  T("Twenty-One Days of Prayer","A group challenge"),T("A Praying Life","Six weeks to build one")]),

C("Scripture Engagement","Practices",
 ["Why","What it is","How","When it is dry","Together","For life"],
 ["Psalm 119:105","2 Timothy 3:16-17","James 1:22-25"],
 "Most people have tried and stopped. Ask about the failed attempt in session one; it removes the shame.",
 [T("How to Read the Bible","Six weeks of method"),T("The Whole Story","Genesis to Revelation"),
  T("Reading a Gospel","Mark, slowly"),T("Reading a Letter","Philippians, slowly"),
  T("Reading a Psalm","Six weeks of poetry"),T("Reading the Old Testament","As a Christian"),
  T("Study Tools","Three, not thirty"),T("Context","Why it changes everything"),
  T("Memorizing Scripture","Six weeks, six verses"),T("Meditating on Scripture","Slow reading"),
  T("Bible Reading Plans","Choosing one that fits"),T("When the Bible Is Boring","Honest six weeks"),
  T("The Hard Passages","The ones we skip"),T("Reading With Others","Community and text"),
  T("Teaching What You Read","Handing it on"),T("Obeying What You Read","Doers not hearers"),
  T("Reading With Your Family","At the table"),T("A Year in the Word","Six weeks to plan"),
  T("Journaling Scripture","Writing to remember"),T("Living in the Text","Six weeks of immersion")]),

C("Worship","Practices",
 ["Who he is","Why we respond","How we express it","When it is hard","Together","All week"],
 ["Psalm 95:1-7","John 4:23-24","Romans 12:1"],
 "Consider actually worshipping in one session rather than discussing it. Sing something.",
 [T("What Is Worship","More than music"),T("Worship in the Psalms","Six weeks of songs"),
  T("Wonder","The thing that goes first"),T("Worship as a Lifestyle","Romans 12, six weeks"),
  T("The Songs We Sing","Theology at singing speed"),T("Lament as Worship","The songs we stopped"),
  T("Worship in Revelation","Joining what is happening"),T("Bodies in Worship","Standing, kneeling, raising"),
  T("Silence","Making room"),T("The Table","Communion, six weeks"),
  T("Worship and Justice","When God rejects the offering"),T("Private Worship","Alone with God"),
  T("Family Worship","At home"),T("Worship in Suffering","Habakkuk 3"),
  T("Awe","Recovering the fear of God"),T("Worship and Culture","Style and substance"),
  T("Every Tribe and Tongue","The global song"),T("Worship on a Tuesday","Beyond the service"),
  T("Serving in Worship","For the team"),T("A Worshipping Life","Six weeks to build one")]),

C("Sabbath & Rest","Practices",
 ["The command","The refusal","The trust","The practice","The obstacle","The rhythm"],
 ["Exodus 20:8-11","Mark 2:27","Matthew 11:28-30"],
 "Nobody in the room is resting. Start there, without judgement, and keep the first commitment tiny.",
 [T("Sabbath","Six weeks recovering a day"),T("Rest","Why you cannot stop"),
  T("Sleep","The most spiritual thing this week"),T("Margin","Space for the interruption"),
  T("Hurry","The thing to eliminate"),T("The Yoke Is Easy","When ministry got heavy"),
  T("Play","The thing we stopped doing"),T("Screens and Attention","Six weeks of reclaiming"),
  T("Seasons of Rest","Beyond a day"),T("Rest and Ambition","Both, held together"),
  T("Rhythms","What holds when willpower fails"),T("Trusting God With What Is Undone","The real issue"),
  T("Rest for Caregivers","When there is no off"),T("Rest and the Body","Physical stewardship"),
  T("The Sabbath Year","Fallow ground"),T("Rest in Scripture","Six passages"),
  T("Rest for Leaders","Giving permission"),T("A Slower Life","Six weeks toward it"),
  T("Rest and Anxiety","The connection"),T("Keeping Sabbath","After the six weeks")]),

C("Character & Integrity","Character",
 ["The trait","The Scripture","The failure","The cost","The practice","The formation"],
 ["Proverbs 4:23","Psalm 139:23-24","1 Timothy 4:16"],
 "Model disclosure lightly and never require it. Silence is an acceptable answer in every session.",
 [T("Integrity","When nobody is watching"),T("Honesty","Including the small ones"),
  T("Faithfulness","Showing up over years"),T("Purity","Handled without shame"),
  T("Humility","The towel before the title"),T("Patience","The fruit nobody wants"),
  T("Self-Control","The last one listed"),T("Contentment","Learned, not felt"),
  T("Courage","Doing it afraid"),T("Generosity of Spirit","Beyond money"),
  T("Kindness","Underrated and hard"),T("Perseverance","Staying when it is hard"),
  T("Wisdom","Six weeks of Proverbs"),T("Discernment","Testing what you hear"),
  T("Repentance","As a practice"),T("Consistency","Same person everywhere"),
  T("Trustworthiness","Being someone people rely on"),T("Compassion","Feeling and acting"),
  T("Character Under Pressure","What comes out"),T("Finishing Well","Working backward")]),

C("The Fruit of the Spirit","Character",
 ["The fruit","Where it comes from","What blocks it","Practising it","In community","Bearing fruit"],
 ["Galatians 5:22-23","John 15:1-8","Matthew 7:16-20"],
 "Fruit is grown, not manufactured. Keep the group from turning this into a self-improvement plan.",
 [T("The Fruit of the Spirit","All nine, six weeks"),T("Love","The first and the sum"),
  T("Joy","Not the same as happy"),T("Peace","With God, with others, within"),
  T("Patience","Long-suffering, honestly"),T("Kindness","Practical and costly"),
  T("Goodness","What it actually means"),T("Faithfulness","Over decades"),
  T("Gentleness","Strength under control"),T("Self-Control","The one we want most"),
  T("Abiding","John 15, six weeks"),T("Pruning","Why it hurts"),
  T("The Works of the Flesh","The contrast Paul draws"),T("Walking by the Spirit","Daily"),
  T("Fruit in a Hard Season","When it is not blooming"),T("Fruit in Community","Grown in a group"),
  T("Testing the Fruit","How you know"),T("Fruit and Gifts","The difference"),
  T("A Fruitful Life","Six weeks toward it"),T("Bearing Fruit That Lasts","The long view")]),

C("Identity","Character",
 ["Who they say","Who you think","Who he says","The lie","The truth","Living from it"],
 ["Ephesians 1:3-14","1 John 3:1","Romans 8:14-17"],
 "This is the study that surfaces the most pain. Have referral names ready before session one.",
 [T("Who You Are","Six weeks in Ephesians 1"),T("Beloved","The first identity"),
  T("Chosen","Election, pastorally"),T("Adopted","Sons and daughters"),
  T("Free","Galatians, six weeks"),T("New Creation","What actually changed"),
  T("The Lies We Believe","And the truth that answers"),T("Shame","The one nobody names"),
  T("Comparison","The joy thief"),T("Performance","When you cannot stop earning"),
  T("Made in His Image","Human dignity"),T("Your Story","And how God is in it"),
  T("Worth","Where it actually comes from"),T("Belonging","Before behaving"),
  T("Identity and Work","When the job is who you are"),T("Identity and Failure","When you blew it"),
  T("Identity and Body","Six weeks of honesty"),T("Names God Gives","Six of them"),
  T("Living Loved","Six weeks of practice"),T("Who You Are Becoming","The long view")]),

C("Humility & Servanthood","Character",
 ["The example","The command","The resistance","The practice","The cost","The freedom"],
 ["Philippians 2:5-11","John 13:1-17","Micah 6:8"],
 "The person who most needs this study will not know it. Do not aim the sessions at anyone.",
 [T("He Took a Towel","John 13, six weeks"),T("Consider Others Better","Philippians 2"),
  T("Serving Down","Honouring the invisible"),T("The Credit","Who needs it"),
  T("Receiving Correction","Without defending"),T("Micah 6:8","Six weeks in one verse"),
  T("Serving When It Costs","The real test"),T("Ambition Redirected","Wanting the right things"),
  T("The Interruptions","Where ministry happens"),T("Apologizing","As a practice"),
  T("Position and Identity","When the role becomes you"),T("Anonymous Service","Six weeks unseen"),
  T("Washing Feet Today","What it looks like now"),T("Power","Using it well"),
  T("Listening","The humblest act"),T("Being Wrong","And saying so"),
  T("Serving Difficult People","The hard six weeks"),T("The Last Shall Be First","The great reversal"),
  T("Greatness","Redefined"),T("A Servant's Life","Six weeks toward it")]),

C("Courage & Faith","Character",
 ["The fear","The call","The step","The cost","The company","The outcome"],
 ["Joshua 1:9","Hebrews 11:1","2 Timothy 1:7"],
 "Every faith study risks producing guilt. Keep asking what the next honest small step is rather than the heroic one.",
 [T("Be Strong and Courageous","Joshua, six weeks"),T("Faith","Hebrews 11, six weeks"),
  T("Fear","What it does and what to do"),T("Step Into the Water","Before it parts"),
  T("Faith Goals","Sized to God"),T("Obedience Without Clarity","Going before you understand"),
  T("When It Failed","Faith after a loss"),T("Small Beginnings","Despising the day"),
  T("The Ten and the Two","Two reports, one giant"),T("Risk","Holy and otherwise"),
  T("Playing Safe","The buried talent"),T("Bold Prayers","Asking for more"),
  T("Standing Alone","When nobody agrees"),T("Speaking Up","The brave sentence"),
  T("Faith and Planning","Both, not either"),T("Waiting in Faith","The hardest kind"),
  T("Faith in the Ordinary","Tuesday courage"),T("Faith Under Pressure","When it is tested"),
  T("Doubt and Faith","Held together"),T("A Life of Faith","Six weeks toward it")]),
]
