# -*- coding: utf-8 -*-
def S(t, sub, ss): return {"t":t,"sub":sub,"ss":ss}
def CL(n, sub, why, studies): return {"n":n,"sub":sub,"why":why,"st":studies}

THESIS = ("Every small group in every church asks the same question on the same day: what are we studying next? "
 "Most answer it by asking around, buying whatever is on the shelf, and starting three weeks late. "
 "This answers it in ninety seconds, in the right edition for that room, at six sessions every time.")

SIX_WHY = [
 ["Six is what a group will actually finish","Eight-week studies are started by many and finished by few. Six matches a term, a season and an attention span."],
 ["Six fits four times a year","Fall, January, spring, summer. Four terms of six, with breaks that let people re-choose rather than quietly drift."],
 ["A finite ask gets a yes","A host says yes to six weeks. The same host says no to indefinitely, and means it."],
 ["Six lets a leader multiply","Naming the next host in week one and handing off at week six is a rhythm. There is no handoff point in an open-ended group."],
 ["Every study is six, without exception","One length means one format, one leader training, one print template, and a group that never has to relearn anything."],
]

AUDIENCES = [
 ["Church members","Pick a study, start a group","Browse by who is in the room, get the guide and the leader notes, and start. No staff approval, no gatekeeping."],
 ["Small group leaders","Run it without preparing from scratch","Session guide, leader notes, timing and the questions that actually open a room."],
 ["Ministry directors","Run a whole ministry on it","Every affinity edition for their people, aligned to what the church is teaching, with leader training built in."],
 ["Church staff","Align the whole church","Choose the churchwide study, push it to every group, and use the same content for their own team."],
]

PACK = [
 ["Participant guide","~1,200 words per session","What the group member reads and writes in. Six sessions, print-ready.","7,200"],
 ["Leader notes","~450 words per session","What this session is for, where it goes sideways, what to do if nobody talks, and when to move on.","2,700"],
 ["Pastor teaching script","~1,350 words per session","A ten-minute talk, written out. For a pastor, a ministry leader or a host who would rather read than wing it.","8,100"],
 ["Daily readings","~180 words x 6 days","The week between sessions. Six days, one idea, from the same passage.","6,480"],
 ["Discussion questions","3 opening, 4 core, 2 closing","Written to open a room rather than test it.","included"],
 ["Application and next step","One per session","Something done before the next meeting, small enough that it happens.","included"],
]

WORDMATH = [
 ["Per session","~3,000 words","Participant guide, leader notes, teaching script and the six daily readings"],
 ["Per six-session study","~18,000 words","Roughly the length of a short book, per study"],
 ["Per study across all editions","~18,000 base","Editions change stakes and examples, not the theology or the structure"],
 ["The library at 120 studies","~2,160,000 words","Which is why this is generated from a source rather than written by hand"],
 ["The ten-minute script alone","1,350 words","At 135 words a minute. Short enough to read, long enough to say something."],
]

AFFINITY = [
 ["Anyone","Mixed groups, no adaptation. The default edition."],
 ["Men","Shorter sessions, task framing, shoulder-to-shoulder questions."],
 ["Women","More reflective space, longer readings, mentoring prompts."],
 ["Couples","Two-column format so both partners write. Paired exercises."],
 ["Young Adults","Faster pace, harder questions, less assumed background."],
 ["Students","Shorter readings, more room to draw, leader-heavy."],
 ["Seniors","Larger type, longer memory prompts, legacy framing."],
 ["New Believers","Nothing assumed. Every term explained the first time it appears."],
 ["Parents","Household application in every session."],
 ["Blended Families","Named directly rather than assumed away."],
 ["Singles","Written without the assumption that marriage is coming."],
 ["Empty Nesters","Second-half framing, purpose and legacy."],
 ["Marketplace","Vocation, integrity and Monday application."],
 ["Business Owners","Ownership, exit, employees and the weight of it."],
 ["Leaders","Applied to the people they lead, not just themselves."],
 ["Volunteers","Shorter, serving-oriented, fits a team meeting."],
 ["Recovery","Trauma-aware language, no shame framing, referral notes."],
 ["Grief","Slower pace, permission to pass, no forced sharing."],
 ["First Responders & Military","Shift-friendly length, plain language, high trust."],
 ["Spanish","Full translation, not a rendering. Idiom checked by a native speaker."],
]

CLUSTERS = [

CL("Foundations","Where anyone starts","The studies a church can hand to anyone, in any season, with no prerequisites.",
 [S("Who Is Jesus","Six weeks in the claims he made about himself",
    ["The Question He Asked","The Claims He Made","The Life He Lived","The Death He Died","The Empty Tomb","Who Do You Say I Am"]),
  S("What We Believe","The core, without the jargon",
    ["God","Scripture","Jesus","The Spirit","The Church","What Happens Next"]),
  S("How to Read the Bible","For someone who has never opened one",
    ["What This Book Is","The Whole Story","Reading a Gospel","Reading a Letter","Reading a Psalm","Reading It for Yourself"]),
  S("Prayer for Beginners","Six weeks learning it by doing it",
    ["Teach Us to Pray","Father","Asking","Listening","When Nothing Happens","Praying Together"]),
  S("Following Jesus","What actually changes",
    ["The Invitation","Repentance","Belief","Baptism","Community","The Long Walk"]),
  S("The Gospel in Six Words","Creation, fall, promise, Christ, church, restoration",
    ["Created","Broken","Promised","Rescued","Gathered","Restored"]),
  S("Questions People Actually Ask","Six honest objections, handled honestly",
    ["Why Is There Suffering","Can I Trust the Bible","What About Other Religions","Science and Faith","The Church's Failures","What If I Doubt"]),
  S("Your First Ninety Days","For someone who just started",
    ["What Just Happened","Reading","Praying","Belonging","Telling Someone","What Now"])]),

CL("Spiritual Practices","The habits that form a life","Practices rather than topics. Each session assigns something to do.",
 [S("The Practices","Six disciplines, six weeks, one at a time",
    ["Scripture","Prayer","Sabbath","Fasting","Generosity","Service"]),
  S("Sabbath","Recovering the day we gave away",
    ["The Fourth Commandment","Why We Stopped","What It Is Not","Planning One","The First Attempt","Keeping It"]),
  S("Fasting","A dropped discipline, recovered",
    ["Why Fast","What Runs You","Choosing a Fast","The First Day","What Surfaces","Fasting Together"]),
  S("Silence and Solitude","Alone on purpose",
    ["The Noise","Jesus Withdrew","Your First Hour","What Comes Up","Listening","A Rhythm"]),
  S("Scripture Memory","Hiding it in your heart",
    ["Why Memorize","Choosing a Verse","How to Do It","Reviewing","In the Hard Moment","A Year of It"]),
  S("Confession","The practice we lost",
    ["Why It Matters","To God","To Each Other","Choosing a Person","The First Time","A Rhythm of It"]),
  S("Simplicity","Wanting less on purpose",
    ["Enough","What Owns You","Giving Something Away","Buying Less","Time","A Simpler Life"]),
  S("Gratitude","Three things, every morning",
    ["Ingratitude","Naming Three","The Hard Season","Telling Someone","Gratitude and Money","Ninety Days"])]),

CL("Relationships","The people around you","Studies about the rooms people actually live in.",
 [S("Doing Life Together","Why you were not built alone",
    ["Not Good to Be Alone","Rows and Circles","Being Known","Carrying and Being Carried","Conflict","Who Is Coming With You"]),
  S("Hard Conversations","Six weeks learning a skill",
    ["Why We Avoid Them","Assume the Best","Say the Thing","Listen First","Repair Fast","Forgiveness"]),
  S("Forgiveness","The hardest thing Jesus asked",
    ["What It Is Not","Seventy Times Seven","When They Are Not Sorry","Forgiving Yourself","Reconciliation","Letting It Go"]),
  S("Friendship","The relationship nobody teaches",
    ["Jonathan and David","Making Friends as an Adult","Depth","Loyalty","When a Friendship Ends","Being a Friend"]),
  S("Boundaries","Love with edges",
    ["Why Boundaries","Saying No","Difficult People","Family","At Work","Holding the Line"]),
  S("Loneliness","Named rather than fixed",
    ["The Ache","Alone and Lonely","In a Crowd","What Helps","Reaching Out","Being Found"]),
  S("Hospitality","Opening a door",
    ["The Table","Abraham's Guests","Practical Hospitality","Who to Invite","When Your House Is Not Ready","A Rhythm"]),
  S("Community That Lasts","Beyond six weeks",
    ["What Holds","Commitment","Honesty","Serving Together","Surviving Conflict","Multiplying"])]),

CL("Marriage & Family","The household","Studies for the room where most formation happens.",
 [S("The Marriage You Want","Six weeks of practical work",
    ["What You Married For","Communication","Conflict","Money","Intimacy","The Long Haul"]),
  S("Money and Marriage","The fight underneath the fight",
    ["Whose Money","Two Histories","A Shared Plan","Debt","Giving Together","Enough"]),
  S("Parenting With Purpose","Beyond survival",
    ["What You Are Building","Discipline","Discipleship at Home","Screens","Letting Go","Blessing Them"]),
  S("Blended Families","Named directly",
    ["What Is Different","Two Sets of Rules","The Other Household","Loyalty","Building New","Patience"]),
  S("Empty Nest","The second half begins",
    ["They Left","Rediscovering Each Other","Purpose Now","Adult Children","Grandparenting","What Is Next"]),
  S("Caring for Parents","The sandwich years",
    ["The Shift","Honour","Practical Care","Guilt","Siblings","Letting Go"]),
  S("Singleness","Whole, not waiting",
    ["The Assumption","Contentment","Community","Purpose","Desire","A Full Life"]),
  S("Household Rhythms","One thing, not five",
    ["What You Do Now","Choosing One","The Table","Sabbath at Home","Serving Together","Keeping It"])]),

CL("Money & Generosity","What we do with what we have","Financial discipleship for every income level.",
 [S("God Owns It All","What changes when nothing is yours",
    ["Whose Is It","The Danger of Enough","Count the Pronouns","The First Check","Tell Someone","What Changed"]),
  S("Getting Out of Debt","Practical and pastoral",
    ["The Honest Number","How It Happened","A Plan","Cutting","Momentum","Staying Out"]),
  S("Enough","The number you never named",
    ["The Never","Great Gain","I Have Learned","Comparison","Say It Out Loud","The Line You Drew"]),
  S("Generous Living","Beyond the tithe",
    ["Why We Give","First Fruits","Proportion","Giving Beyond Money","Generosity Together","A Generous Life"]),
  S("Money and Anxiety","The worry underneath",
    ["Do Not Worry","What You Are Afraid Of","Margin","Trust","Contentment","Sleeping at Night"]),
  S("Work and Money","Earning it well",
    ["Why We Work","Integrity","Ambition","Rest","Enough Income","Working as Worship"]),
  S("Teaching Children About Money","Three jars",
    ["Starting Young","Give","Save","Spend","Earning","Letting Them Fail"]),
  S("Legacy","What leaves at the end",
    ["Past Your Lifetime","A Will","Giving While Living","Talking to Your Family","Values Before Assets","Finishing"])]),

CL("Purpose & Calling","Why you are here","Studies about vocation, gifting and the shape of a life.",
 [S("Purpose at Work","Monday is the mission field",
    ["Before the Fall","Thorns","As for the Lord","Excellence","The People There","Sent There"]),
  S("Finding Your Calling","More than a job",
    ["What Calling Is Not","Your Story","Your Gifts","Your Burden","The Next Step","Faithful Where You Are"]),
  S("Your Gifts","Discovering and using them",
    ["Everyone Has Some","Identifying Yours","Confirmed by Others","Using Them","When They Are Not Wanted","Serving"]),
  S("The Second Half","Purpose after fifty",
    ["Success to Significance","What You Carry","Mentoring","Giving It Away","Health and Time","Finishing Well"]),
  S("Ambition","Wanting the right things",
    ["Is It Wrong","Examining It","Great Things for Yourself","Redirecting It","Contentment and Drive","A Holy Ambition"]),
  S("When Work Is Hard","Difficult jobs and difficult bosses",
    ["The Reality","Integrity Under Pressure","A Difficult Boss","When to Leave","Providing","Faithfulness"]),
  S("Rest and Ambition","Both, held together",
    ["Driven","The Cost","Sabbath","Enough Achievement","Rhythm","Sustainable"]),
  S("What You Were Made For","The whole question",
    ["Made","Broken","Redeemed","Gifted","Sent","Home"])]),

CL("Suffering & Hope","When it is hard","Studies for the seasons nobody chooses.",
 [S("When God Feels Far","Six weeks in the dark",
    ["Psalm 88","How Long","The Silence","What Helps","Company","Still Here"]),
  S("Grief","Walking through loss",
    ["The Loss","What Is Normal","Anger","Guilt and What-If","Remembering","Living Again"]),
  S("Anxiety","Named honestly",
    ["What It Is","Do Not Worry","The Body","Practices That Help","When to Get Help","Peace"]),
  S("Suffering","The oldest question",
    ["Why","Job","Lament","Presence","Purpose in Pain","Hope"]),
  S("Waiting","The season nobody chooses",
    ["Not Yet","Abraham","What to Do While Waiting","Trust","When It Does Not Come","Faithful Anyway"]),
  S("Disappointment With God","Saying it out loud",
    ["The Prayer Unanswered","Naming It","The Psalms of Complaint","Staying","What Changed","Trust Again"]),
  S("Illness","Faith in a body that is failing",
    ["The Diagnosis","Praying for Healing","When It Does Not Come","Caregivers","Dignity","Hope"]),
  S("Starting Over","After a loss, a failure or an ending",
    ["The Ending","Grieving It","What You Learned","The First Step","New Ground","Forward"])]),

CL("Character & Integrity","Who you are","Studies about the interior life.",
 [S("Integrity","When nobody is watching",
    ["The Private Life","Small Compromises","Truth","Money","Purity","Finishing Clean"]),
  S("Humility","The towel before the title",
    ["He Took a Towel","Others First","Correction","The Credit","Position","Micah 6:8"]),
  S("Patience","The fruit nobody wants",
    ["Why It Is Hard","With People","With God","With Yourself","In Traffic and Elsewhere","Long-Suffering"]),
  S("Anger","What is underneath it",
    ["Be Angry and Do Not Sin","The Trigger","What Is Beneath","In the Household","Righteous Anger","Letting Go"]),
  S("Envy and Comparison","The joy thief",
    ["The Tenth Commandment","Social Comparison","What You Actually Want","Celebrating Others","Contentment","Free"]),
  S("Speech","The tongue",
    ["A Small Fire","Gossip","Complaining","Honesty","Encouragement","Words That Build"]),
  S("Courage","Doing it afraid",
    ["Be Strong and Courageous","Fear","The Small Brave Thing","Speaking Up","Standing Alone","Faithful Courage"]),
  S("Self-Control","The last fruit listed",
    ["Why It Matters","Habits","Appetite","Impulse","Rhythms Over Willpower","Freedom"])]),

CL("Mission & Witness","Outward","Studies about the people who are not here yet.",
 [S("Come and See","Inviting without being weird",
    ["The Oldest Invitation","Your One","The Ask","Going With Them","When They Say No","Keep Asking"]),
  S("Your Story","Learning to tell it in three minutes",
    ["Before","What Happened","After","Three Minutes","Practising","Telling It"]),
  S("Loving Your Neighbour","The literal ones",
    ["Who Is My Neighbour","Learning Names","The First Kindness","The Table","Over Time","The Long Neighbour"]),
  S("Serving the City","Beyond the walls",
    ["Seek Its Welfare","What Is Needed","Partnering","Helping Without Hurting","Consistency","A Blessed City"]),
  S("Justice and Mercy","Both, not one",
    ["Micah 6:8","Seeing","Learning First","Doing Something","Sustaining It","Advocacy"]),
  S("Faith at Work","Witness on Monday",
    ["Where You Already Are","Excellence","Integrity","Relationships","Answering Questions","Sent"]),
  S("The Nations Here","Refugees and neighbours",
    ["They Arrived","Learning","Welcoming","Practical Help","Friendship","Together"]),
  S("Going","Short-term and long",
    ["Why Go","Preparing","While You Are There","Coming Back","What Changed","Staying Sent"])]),

CL("Books of the Bible","Straight through a text","Six weeks in one book, for groups that want the text itself.",
 [S("Mark","The fastest gospel",["The King Arrives","Authority","Opposition","Who Do You Say","The Road to the Cross","The Empty Tomb"]),
  S("John","That you may believe",["The Word","Signs","I Am","The Upper Room","The Cross","Believe"]),
  S("Philippians","Joy from a prison",["Partnership","Christ's Mind","Knowing Him","Pressing On","Rejoice","Contentment"]),
  S("James","Faith that works",["Trials","Hearing and Doing","The Tongue","Wisdom","Money","Prayer"]),
  S("Ruth","Loyalty in a hard season",["Loss","Loyalty","The Field","The Threshing Floor","Redemption","The Line of David"]),
  S("Jonah","The reluctant prophet",["The Call","The Storm","The Fish","The City","The Vine","The Question"]),
  S("Psalms","Prayers for every season",["Praise","Lament","Trust","Confession","Thanksgiving","Wisdom"]),
  S("Ephesians","Who you are now",["Chosen","Alive","One","Built","Walk","Armour"])]),

CL("Health & Flourishing","The whole person","Body, mind and soul as one.",
 [S("Whole Life Health","Six dimensions, six weeks",["The Body","The Mind","The Soul","Relationships","Work","Rhythm"]),
  S("Rest","The commandment we skip",["Tired","Sabbath","Sleep","Margin","Play","A Rested Life"]),
  S("The Body","Stewardship, not shame",["A Temple","Movement","Food","Sleep","Aging","Honouring It"]),
  S("Mental Health and Faith","Both taken seriously",["Naming It","What Scripture Says","Getting Help","Community","Practices","Hope"]),
  S("Habits","What you repeat",["You Are Your Habits","Starting One","Stopping One","Environment","Rhythm Over Willpower","A Year"]),
  S("Screens","Attention as stewardship",["What It Costs","Noticing","Boundaries","Sabbath From It","Presence","Reclaimed"]),
  S("Flourishing","More than not struggling",["What It Means","Happiness and Health","Meaning","Character","Relationships","Whole"]),
  S("Aging Well","The second half of the body",["What Changes","Acceptance","Health","Purpose","Legacy","Finishing"])]),

CL("Leadership","For those who lead others","Studies for leaders in any room.",
 [S("Leading Yourself","Before you lead anyone",["Your Soul","Your Rhythms","Your Character","Your Growth","Your Limits","Your Finish"]),
  S("Serving Leadership","The towel model",["Not So With You","Serving Down","Giving Credit","The Interruptions","Humility","The Basin"]),
  S("Developing People","Growing others",["See Them","Invest","Give Real Work","Feedback","Release","Multiply"]),
  S("Difficult Conversations","A leadership skill",["Why We Avoid","Preparing","Saying It","Listening","Repair","Following Up"]),
  S("Vision","Seeing and saying",["What Could Be","Naming It","Saying It Again","Resistance","The Middle","Landing It"]),
  S("Decisions","How to make them",["Gathering","Praying","Deciding","Communicating","Living With It","When You Were Wrong"]),
  S("Burnout","Before it arrives",["The Signs","The Causes","Saying No","Delegating","Rest","Sustainable"]),
  S("Finishing Well","The long view",["The End in Mind","Character","Succession","Releasing","Legacy","Well Done"])]),

CL("Recovery & Healing","Slow, safe and honest","Trauma-aware studies with referral notes for every leader.",
 [S("Freedom","Six weeks toward it",["Naming It","Powerlessness","Honesty","Community","Making Amends","One Day"]),
  S("Shame","The one nobody names",["What Shame Is","Where It Came From","Hiding","Grace","Telling Someone","Free"]),
  S("Forgiving Someone Who Hurt You","Slowly and honestly",["What It Is Not","The Cost","Anger First","The Choice","Safety and Forgiveness","Release"]),
  S("Codependency","Love with boundaries",["The Pattern","Rescuing","Saying No","Your Own Life","Healthy Love","Change"]),
  S("Anxiety and Panic","Practical and spiritual",["What Happens","The Body","Thoughts","Practices","Help","Peace"]),
  S("After Betrayal","Rebuilding",["What Happened","Grief","Anger","Trust","Rebuilding or Not","Forward"]),
  S("Hope After Failure","When you caused it",["What You Did","Confession","Consequences","Grace","Restoration","Usefulness Again"]),
  S("The Long Recovery","Year two and beyond",["The Plateau","Complacency","Relapse","Community","Purpose","Helping Others"])]),

CL("Seasons & Calendar","Timed to the year","Studies designed for a specific season on the church calendar.",
 [S("Advent","Four weeks plus two",["Hope","Peace","Joy","Love","The Arrival","Emmanuel"]),
  S("Lent","Six weeks toward the cross",["Dust","Wilderness","Temptation","The Road","The Table","The Cross"]),
  S("Easter Season","Six weeks after the tomb",["The Empty Tomb","Thomas","Emmaus","Breakfast","Feed My Sheep","Until He Comes"]),
  S("New Year","Starting again",["Looking Back","Honest Assessment","One Thing","Habits","Accountability","The Year Ahead"]),
  S("Summer","Six weeks, lighter",["Rest","Play","Wonder","Hospitality","Simplicity","Return"]),
  S("Thanksgiving","Gratitude for six weeks",["Notice","Name","Say","Give","Remember","Content"]),
  S("Back to School","For households with children",["The Transition","Rhythms","Anxiety","Friendship","Faith at School","The Year"]),
  S("Year End","Closing well",["What Happened","What You Learned","What You Lost","Gratitude","Forgiveness","Forward"])]),

CL("Churchwide Alignment","When everyone studies the same thing","The six-session versions of the churchwide campaigns.",
 [S("40 Days of Generosity","The six-session edition",["Who Owns It","Enough","Open Hands","What Do You See","Together","The Return"]),
  S("40 Days of Financial Wisdom","The six H's",["Honor","Heart","Health","Habits","Hope","Harvest"]),
  S("40 Days of Prayer","Six weeks in the Lord's Prayer",["Teach Us","Father","Kingdom","Bread","Forgive","Deliver"]),
  S("40 Days of Purpose at Work","Vocation churchwide",["Before the Fall","Thorns","As for the Lord","Excellence","The People","Sent"]),
  S("40 Days in Community","The group launch campaign",["Not Alone","Known","Carried","Honest","Serving","Multiplying"]),
  S("40 Days of Obedience","Saying yes",["The Yes","The Cost","The Ordinary Yes","When It Is Hard","Together","A Life of Yes"]),
  S("40 Days of Health","Whole life",["Body","Mind","Soul","Relationships","Work","Rhythm"]),
  S("40 Days in the Word","Churchwide reading",["Why This Book","The Story","Reading It","Obeying It","Sharing It","Living It"])]),
]

# The pastor's library upload pipeline
PIPELINE = [
 ["01","Upload whatever exists","Audio files, video, manuscripts, outlines, bulletins, hand-written notes photographed on a phone. No format is refused and nothing needs organising first.",
  ["MP3, WAV, M4A, MP4","DOC, DOCX, PDF, TXT, RTF","Photographs of handwritten notes","Podcast RSS feed","A folder, a drive or a box"]],
 ["02","Transcribe","Audio and video become text. Speaker-separated, timestamped, punctuated. A thirty-minute sermon transcribes in roughly two minutes.",
  ["Speaker separation","Timestamps to the sentence","Scripture references detected and linked","Filler words removed, voice preserved","Confidence flags on unclear audio"]],
 ["03","Index","Every message tagged by topic, passage, series, date, occasion and audience. This is the step that turns a folder into a library.",
  ["Topic and theme tags","Every Scripture reference indexed","Series and standalone identified","Illustrations extracted and tagged","Stories separated from exposition"]],
 ["04","Report the coverage","What he has preached, what he returns to, and what he has never addressed. Most ten-year libraries cover under half of what a congregation needs.",
  ["Topics covered and at what depth","Topics never addressed","Passages preached more than three times","Books of the Bible never opened","Seasonal gaps"]],
 ["05","Convert","A series becomes a six-session study. A message becomes a week. An illustration goes into the bank. His words, his structure, his theology.",
  ["Series to six-session curriculum","Message to six daily readings","Message to a ten-minute teaching script","Illustrations to a searchable bank","Series to a 40-day campaign"]],
 ["06","Approve","Nothing ships that he has not read and signed. The archive is his and stays his.",
  ["Every output reviewed before release","Edit in place","Reject and regenerate","Rights and ownership stay with the pastor","Nothing published without approval"]],
]

PIPELINE_NOTE = ("This is the Pastor&rsquo;s Library Project, and it is the layer underneath every other library on this "
 "platform. Everything else is what we bring. This is what he brings. The product is the intersection, and it is the "
 "only part no competitor can replicate &mdash; because nobody else asks for the archive.")

SEVEN_A = [
 ["Authentic","His words, his stories, his voice &mdash; not a generated approximation of them."],
 ["Actual","What he really preached, not what he remembers preaching. The archive corrects the memory."],
 ["Aggregated","All of it in one place for the first time, searchable rather than scattered."],
 ["Aligned","Matched to what this church is teaching and where it is going."],
 ["Analyzed","Themes, gaps, patterns and coverage named &mdash; what he returns to and what he has never addressed."],
 ["Applied","Converted into things a church can use on a Sunday, not filed more neatly."],
 ["Approved","Nothing ships that he has not read and signed off on. The archive is his."],
]

WEEK_ANSWER = [
 ["Who is in the room","Twenty affinity editions. The same study reads differently for men, for a recovery group and for new believers."],
 ["What season is it","Advent, Lent, fall launch, January, summer. The calendar narrows the list before anyone browses."],
 ["What is the church teaching","If a churchwide series is running, the aligned study is the default and everything else is optional."],
 ["What did you just finish","The library will not recommend the same cluster twice in a row unless asked."],
 ["How much preparation does the leader have","A first-time host gets the script version. An experienced leader gets the discussion-only version."],
]
