# -*- coding: utf-8 -*-
def S(t,sub,pas,pts,pr,ns): return [t,sub,pas,pts,pr,ns]
def C(n,sub,why,ice,close,deep,notes,ss): return [n,sub,why,ice,close,deep,notes,ss]

PART1 = [

C("Vision & Direction","Where we are going and whether anyone can say it",
"Six people quietly working toward six different pictures of the future is the most common staff dysfunction there is.",
["What is one thing you are looking forward to this month?","Describe your job in five words.",
 "What did you want to be at ten years old?","What is the best decision this church made in the last two years?"],
["Lord, give us one clear direction and the humility to walk it together. Keep us from building anything you did not ask for.",
 "Father, we hold this church loosely. Show us where you are going and give us the courage to follow rather than lead."],
["Proverbs 29:18","Habakkuk 2:1-4","Nehemiah 2:11-18","Acts 15:6-22","Philippians 3:12-14"],
"Vision sessions surface disagreement. That is the point. Never resolve a live conflict here — name it and handle it privately.",
[S("Say It in One Sentence","If we cannot, neither can they",["Habakkuk 2:2","Proverbs 29:18","1 Corinthians 1:10"],
  ["Clarity is a leadership duty, not a communications task","A vision nobody repeats is a vision nobody holds","The test is whether a member can say it in the parking lot"],
  "Lord, give us one clear word and the courage to keep saying it.",
  ["Write your sentence on a card and carry it","Ask three members what they think we do","Say it from the platform this month"]),
 S("The Vision Leak","Why you say it again in March",["Nehemiah 4:10","Deuteronomy 6:6-9","2 Peter 1:12-15"],
  ["Vision leaks at the rate of a slow puncture","Repetition is not redundancy, it is maintenance","Somebody has to own the reminding"],
  "Father, keep us faithful in the saying, not just the launching.",
  ["Restate one thing publicly this month","Add vision to a recurring meeting agenda","Ask who has stopped hearing it"]),
 S("What We Are Not Doing","The list that makes the list possible",["Luke 14:28","Ecclesiastes 3:1-8","Mark 1:35-38"],
  ["Every yes was a no to something else","Jesus left towns that wanted him","Subtraction is a strategy, not a failure"],
  "Lord, give us the courage to stop good things for better ones.",
  ["Bring one stop-doing candidate","Audit last quarter's calendar","Name what one new yes would displace"]),
 S("A Preferred Future","Describing it rather than defending it",["Proverbs 29:18","Isaiah 43:18-19","Revelation 21:1-5"],
  ["Vision is a picture before it is a plan","If it fits any church it is not a vision","People follow specificity, not sincerity"],
  "God, show us the church you are making rather than the one we imagine.",
  ["Write one dated outcome for your area","Describe it in present tense to your team","Ask what would have to be true this year"]),
 S("Whose Vision Is It","Inherited, borrowed or owned",["1 Corinthians 1:10","Acts 15:36-41","Philippians 2:1-4"],
  ["Loyal execution of a vision you disbelieve has a shelf life","Disagreement voiced is safer than disagreement carried","Ownership requires the chance to shape it"],
  "Father, make us honest with each other before we are united in public.",
  ["Say one honest thing to your supervisor","Name which part you would change","Ask to be part of the next revision"]),
 S("The Quiet Majority","Leading the ninety percent who never speak",["Numbers 13:30-33","Proverbs 18:17","1 Thessalonians 4:11"],
  ["Strategy built on the loudest fifty misreads the room","Silence is not agreement or disagreement","Someone has to go and ask"],
  "Lord, help us hear the people who will never raise a hand.",
  ["Talk to three people who never comment","Ask one question in three settings","Bring what you heard back here"]),
 S("Explaining It to a Child","The compression test",["Deuteronomy 6:6-7","Matthew 18:2-4","1 Corinthians 14:9"],
  ["If a nine-year-old cannot repeat it, an adult will not remember it","Jargon is a symptom of unfinished thinking","Simple is the last step, not the first"],
  "Father, give us plain words for holy things.",
  ["Rewrite your purpose for a child","Test it on an actual child","Cut every insider word from one document"]),
 S("The Cost of Standing Still","Drift as a decision",["Revelation 3:15-16","Haggai 1:2-9","Hebrews 2:1"],
  ["Doing nothing is a decision made quietly","Drift is always downhill and never announced","The honest projection is a spiritual exercise"],
  "Lord, wake us where we have grown comfortable.",
  ["Name what you have been avoiding","Put a date on it","Tell one person so it is real"]),
 S("What Would We Attempt","Faith-sized rather than budget-sized",["Ephesians 3:20","Joshua 14:10-12","2 Samuel 7:1-3"],
  ["Some financial constraint is courage constraint","Faith-sized does not mean reckless","Every attempt needs a real next step"],
  "God, enlarge what we are willing to ask you for.",
  ["Cost out one idea from today","Bring it to the next meeting","Ask who would have to say yes"]),
 S("Here Is the Plan","Vision translated into a calendar",["Proverbs 16:3","Proverbs 21:5","Nehemiah 2:6"],
  ["A vision without a date is a sermon to ourselves","Three outcomes, not eleven","Owners and dates or it did not happen"],
  "Father, let our calendar match our confession.",
  ["Put three outcomes on the shared calendar","Name one owner per outcome","Book the review date now"])]),

C("Team Health & Trust","The room before the work",
"A staff that cannot disagree in the meeting will disagree in the parking lot, and that is where churches actually break.",
["What is one thing about you nobody here knows?","Who is a leader you admire and why?",
 "What is the best team you were ever part of?","High and low from last week, in one sentence each."],
["Lord, make this a room where the truth is safe. Bind us together in something stronger than agreement.",
 "Father, give us thick skin and soft hearts, and let us assume the best about each other this week."],
["Ephesians 4:1-3","Romans 12:9-18","Philippians 2:1-11","Proverbs 27:5-6","1 Corinthians 12:12-26"],
"These sessions need a year of shared history. Do not run them with a brand new team, and never to correct one person.",
[S("The Meeting After the Meeting","Where the real decision gets made",["Ephesians 4:25","Proverbs 11:13","Matthew 18:15"],
  ["The parking lot is a symptom, not a character flaw","Safety is built by the leader going first","Say it here or do not say it"],
  "Lord, give us courage in the room and restraint outside it.",
  ["Say one parking-lot thing in the room","Take one concern directly to the person","Name what would make this safer"]),
 S("Trust in Small Moments","Not on retreats",["Proverbs 3:3-4","Luke 16:10","Matthew 5:37"],
  ["Trust is built by Thursday deliverables, not annual retreats","Small broken promises cost more than large ones","Reliability is a spiritual practice"],
  "Father, make us people whose word can be leaned on.",
  ["Follow through on one small commitment visibly","Tell someone what they did that built trust","Renegotiate a promise you cannot keep"]),
 S("Disagree Without Damage","Conflict as a skill",["Proverbs 27:17","Acts 15:1-21","Galatians 2:11-14"],
  ["Artificial harmony charges you later with interest","Paul opposed Peter to his face and the church survived","Disagreement is data, not disloyalty"],
  "Lord, teach us to fight for each other rather than with each other.",
  ["Raise one disagreement you have been sitting on","Ask someone what they really think","Thank someone who pushed back on you"]),
 S("What You Tolerate","The standard you actually keep",["Galatians 6:1","1 Corinthians 5:6","Hebrews 12:15"],
  ["Culture is the worst behaviour the leader walked past","A little yeast works through the whole batch","Restoration is the goal, not punishment"],
  "Father, give us the courage to say the hard thing gently.",
  ["Have one conversation you have been avoiding","Name the pattern without naming a person","Ask who should address it"]),
 S("Assume the Best","The discipline behind every healthy team",["1 Corinthians 13:7","Proverbs 18:13","James 1:19"],
  ["Most conflict is an uncorrected story about motive","Answering before listening is folly, plainly stated","Checking costs a sentence"],
  "Lord, guard us from the stories we tell ourselves.",
  ["Check one assumption directly","Ask rather than conclude","Apologize for one story you got wrong"]),
 S("The Person Nobody Thanks","Honour inside the team",["Romans 12:10","1 Thessalonians 5:12-13","1 Timothy 5:17"],
  ["Generic appreciation is a form of not paying attention","Honour is a command, not a management technique","Specific and public beats warm and vague"],
  "Father, help us notice what is easy to miss.",
  ["Thank one person specifically in front of others","Write one note by hand","Name the invisible work out loud"]),
 S("Your Family Is Watching","The household cost of ministry",["1 Timothy 3:4-5","Mark 8:36","Psalm 127:1-2"],
  ["A healthy church and an unhealthy home can coexist for years","The household is not the ministry's overflow","Nobody outside will notice until it is late"],
  "Lord, protect the people who pay for our ministry without choosing it.",
  ["Ask your household what it has cost them","Protect one evening this week","Say no to one thing for their sake"]),
 S("When Somebody Leaves","Handling departure well",["Acts 15:36-41","2 Timothy 4:11","Romans 12:18"],
  ["How you treat the leaver is a message to everyone staying","Paul and Barnabas split and both works grew","We owe honesty and honour, not agreement"],
  "Father, let us release people the way you would.",
  ["Write our departure practice down","Reach out to someone who left","Bless one person publicly on the way out"]),
 S("Who Pastors the Pastor","The care nobody schedules",["Exodus 17:12","Galatians 6:2","Ecclesiastes 4:9-10"],
  ["Everyone here is somebody's pastor and almost nobody has one","Moses needed two men holding his arms","Care that is not scheduled does not happen"],
  "Lord, send us people who will hold up our arms.",
  ["Book one conversation outside this staff","Ask someone to ask you hard questions","Name who is doing this for you"]),
 S("One Team, Not Six Departments","Shared ownership",["1 Corinthians 12:12-26","Philippians 2:3-4","Nehemiah 3"],
  ["Departments defend territory; teams defend a mission","Every family repaired the section in front of their house","A shared win has to be named as one"],
  "Father, make us one body rather than six ministries.",
  ["Help another department win this month","Name the last shared win out loud","Give one resource away internally"])]),

C("Character & Integrity","Who you are when nobody is checking",
"More ministries end from character than competence, and everyone in the room knows the name of someone it happened to.",
["What is a small habit you are proud of?","Who shaped your character most?",
 "What is one thing you do that nobody sees?","What is the hardest right thing you ever did?"],
["Lord, make our private life match our public one. Search us and know us and lead us in the way everlasting.",
 "Father, we ask for integrity more than influence, and for a clean heart more than a full room."],
["Psalm 139:23-24","Psalm 51:1-12","Proverbs 4:23","1 Timothy 4:16","Daniel 6:1-5"],
"Never require disclosure. Model it lightly, let silence be acceptable, and offer a private follow-up after every session.",
[S("The Private Life","What nobody can see",["Psalm 51:6","Luke 12:2-3","1 Timothy 4:16"],
  ["The gap between public and private is the whole risk","Nothing concealed will not be disclosed","Watch your life and doctrine, in that order"],
  "Search us, God, and show us what we have stopped seeing.",
  ["Tell one true thing to one safe person","Review your guardrails this week","Name who has full access to you"]),
 S("Small Compromises","How it always starts",["Song of Songs 2:15","Luke 16:10","James 1:14-15"],
  ["Nobody falls off a cliff; everyone walks down a slope","Little foxes ruin the vineyard","Desire conceived becomes something else"],
  "Lord, keep us faithful in the small unwatched things.",
  ["Correct one small thing this week","Name what you have let slide","Ask someone to check on it"]),
 S("Money, Honestly","The area we teach and avoid",["Luke 16:10-11","1 Timothy 6:6-10","Proverbs 11:1"],
  ["We ask the congregation for a transparency we do not practise","Trustworthy with worldly wealth precedes true riches","Honest scales are a spiritual matter"],
  "Father, make us trustworthy with what is not ours.",
  ["Look at one number you have avoided","Talk to your spouse about it","Ask someone to help you plan"]),
 S("Guardrails","Reviewed, not assumed",["Job 31:1","Matthew 5:29-30","Proverbs 4:25-27"],
  ["Guardrails built five years ago do not cover a phone bought last year","Job made a covenant with his eyes before he needed to","Radical is the language Jesus used"],
  "Lord, protect us from what we are too tired to resist.",
  ["Update one guardrail","Give someone access to check","Name what changed that they no longer cover"]),
 S("Telling the Truth","Including the small ones",["Ephesians 4:15","Proverbs 12:22","Colossians 3:9"],
  ["Small untruths are kindness in intent and corrosion in effect","Truth in love is one instruction, not two","Shading is still shading"],
  "Father, give us plain speech and clean hands.",
  ["Correct one thing you shaded","Say the harder true version","Apologize where you softened too far"]),
 S("Ambition","The motive nobody names",["Philippians 2:3","Jeremiah 45:5","Mark 10:35-45"],
  ["Ambition is not the enemy; unexamined ambition is","James and John asked for seats and Jesus reframed the question","The honest answer is usually both"],
  "Lord, purify what we want.",
  ["Name one motive honestly to someone","Do one thing anonymously","Ask why you want the thing you want"]),
 S("When You Were Wrong","Repentance as a leadership practice",["James 5:16","Psalm 32:3-5","2 Samuel 12:13"],
  ["A leader who never apologizes teaches that being wrong is unsurvivable","David's response to Nathan was four words","Silence about sin costs the body"],
  "Father, make repentance normal here.",
  ["Apologize to one person specifically","Own one thing publicly","Thank whoever told you the truth"]),
 S("The Applause Problem","What praise does to a soul",["John 12:43","Galatians 1:10","Matthew 6:1-4"],
  ["The danger is making decisions to keep the applause coming","Loving human praise more than God's is named as a condition","Secret giving is the antidote"],
  "Lord, free us from needing to be seen.",
  ["Do one significant thing nobody will know about","Notice when you angle for credit","Give credit away this week"]),
 S("Sabbath","The commandment we exempt ourselves from",["Exodus 20:8-11","Mark 2:27","Hebrews 4:9-11"],
  ["We preach a commandment we personally break and call it faithfulness","Sabbath was made for us","Rest requires trust that God runs it without us"],
  "Father, teach us to stop.",
  ["Schedule one full day and defend it","Tell someone so they hold you to it","Remove one thing that always steals it"]),
 S("Finish Well","Working backward from the end",["2 Timothy 4:6-8","Acts 20:24","1 Corinthians 9:24-27"],
  ["Nobody sets out to finish badly; they just never work backward","Paul disciplined himself so as not to be disqualified","The end is a design question"],
  "Lord, let us finish what you gave us to do.",
  ["Write one sentence you want true at the end","Name what is inconsistent with it","Tell someone who will walk it with you"])]),
]
