# -*- coding: utf-8 -*-
from sm1 import S, C

PART2 = [

C("Spiritual Formation","The leader's own soul",
"It is possible to run a growing church while your own life with God quietly stops, and the church may be the last to notice.",
["When did you last feel close to God?","What is your favourite psalm and why?",
 "Where do you think best?","What is one spiritual practice you have kept for years?"],
["Father, we have been busy for you and distant from you. Bring us back without shame.",
 "Lord, we abide before we produce. Remind us that apart from you we can do nothing."],
["John 15:1-8","Psalm 63:1-8","Isaiah 40:28-31","Mark 1:35","Psalm 46:10"],
"Expect low answers. Do not rush to encourage. Let the honest number stand and follow up privately with anyone at empty.",
[S("Running on Empty","Ministry from a depleted place",["1 Kings 19:4-8","Matthew 11:28-30","Psalm 23:2-3"],
  ["God's first response to an exhausted prophet was food and sleep","Come to me is an invitation, not a rebuke","He restores; we do not restore ourselves"],
  "Lord, feed us before you send us.",
  ["Do one refilling thing this week","Put it on the calendar","Tell someone your honest number"]),
 S("Reading for Yourself","Not for Sunday",["Psalm 1:2","Jeremiah 15:16","Deuteronomy 8:3"],
  ["Professional handling of Scripture replaces personal receiving unless you fight both","His words were found and eaten","We do not live on bread alone"],
  "Father, let your Word feed us before it feeds anyone else.",
  ["Read one chapter with no sermon attached","Choose a book you will not preach","Read at a different time of day"]),
 S("Prayer Beyond the Meeting","Private, not performed",["Matthew 6:6","Luke 5:16","Colossians 4:2"],
  ["We open every meeting in prayer and can go a week without praying alone","Jesus often withdrew, which means it was a pattern","Devote yourselves is present tense"],
  "Lord, teach us to pray when nobody is listening.",
  ["Ten minutes alone, five days","Pick a fixed time","Start with one sentence and stop"]),
 S("Solitude","Alone on purpose",["Mark 1:35","Psalm 46:10","Luke 6:12"],
  ["Some noise is there because silence asks questions we avoid","Very early, while it was still dark, he went out","Be still is a command"],
  "Father, quiet us enough to hear you.",
  ["One hour with no input","Leave the phone behind","Notice what surfaces and write it down"]),
 S("Confession","The practice we dropped",["James 5:16","1 John 1:9","Psalm 32:3-5"],
  ["Unspoken sin has more power than it should","Confess to each other, not only to God","Silence made his bones waste away"],
  "Lord, bring into the light what we keep in the dark.",
  ["Say one true thing to one safe person","Choose who that person is","Set a rhythm rather than an emergency"]),
 S("Fasting","Recovering a dropped discipline",["Matthew 6:16-18","Isaiah 58:6-9","Joel 2:12"],
  ["Fasting shows you what has been running your life underneath","When you fast assumes you will","The fast God chooses includes justice"],
  "Father, empty us enough to want you.",
  ["Fast from one thing for a week","Choose food or screens or opinion","Replace the time with prayer"]),
 S("Gratitude","The practice that reorders a leader",["1 Thessalonians 5:16-18","Psalm 103:1-5","Luke 17:11-19"],
  ["Ingratitude in ministry is usually exhaustion that stopped noticing","Nine did not come back","Forget not all his benefits"],
  "Lord, make us people who notice.",
  ["Three specifics every morning this week","Tell one person one of them","Keep a list where you will see it"]),
 S("The Dark Stretch","When God feels absent",["Psalm 88","Psalm 13:1-2","Isaiah 50:10"],
  ["Psalm 88 ends in darkness with no resolution and God put it in the book","How long, O Lord is a prayer","Walking in darkness with no light is a named condition"],
  "Father, be near even when you feel far.",
  ["Tell one person you are in it","Read a lament out loud","Ask for company rather than answers"]),
 S("Rule of Life","Rhythms written down",["Daniel 6:10","Acts 2:42","Psalm 119:164"],
  ["A rhythm not written down is a preference, and preferences lose to urgency","Daniel prayed three times a day as he had always done","They devoted themselves"],
  "Lord, give us rhythms that hold in a hard week.",
  ["Write a one-page rule of life","Name what survives a busy week","Share it with one person"]),
 S("Abide","The whole thing in one word",["John 15:1-8","Psalm 1:3","Galatians 5:22-23"],
  ["Apart from me you can do nothing is a description we have all experienced","Fruit is produced, not manufactured","Pruning is care, not punishment"],
  "Jesus, keep us in you.",
  ["Pick one practice for a month","Name where you are producing without abiding","Ask what needs pruning"])]),

C("Leadership Craft","The skills nobody taught you in seminary",
"Most church staff were trained to preach and then asked to hire, budget, manage and lead change with no training at all.",
["What is a skill you wish someone had taught you?","What is the best leadership advice you received?",
 "What part of your job do you enjoy most?","Who took a chance on you?"],
["Father, make us competent as well as faithful. Give us wisdom for the parts of this work we were never trained for.",
 "Lord, teach us to lead people the way you lead us — patiently, clearly and without manipulation."],
["Exodus 18:13-26","Nehemiah 2:11-18","Proverbs 15:22","Luke 14:28-32","1 Peter 5:2-3"],
"Practical sessions. Get people to rehearse actual sentences out loud — most leaders avoid these because they lack the words.",
[S("Delegate or Drown","Jethro's advice, still unheeded",["Exodus 18:17-23","Acts 6:1-4","2 Timothy 2:2"],
  ["We keep tasks because doing feels like contributing","It is not right for us to neglect the word","Entrust to reliable people who will teach others"],
  "Lord, help us give away what we are holding too tightly.",
  ["Give one task away completely","Name who could do it at eighty percent","Stop checking it after you hand it over"]),
 S("The Hard Conversation","The one you have been avoiding",["Matthew 18:15","Proverbs 27:5-6","Ephesians 4:15"],
  ["A conversation avoided six months becomes one you cannot have","Go and point it out, just between the two of you","Open rebuke is better than hidden love"],
  "Father, give us courage and gentleness in the same sentence.",
  ["Have it this week","Rehearse the opening sentence","Ask someone to pray while you do it"]),
 S("Hiring Well","The decision that costs the most",["Acts 6:3","Exodus 18:21","1 Timothy 3:10"],
  ["Most bad hires were visible in the reference calls nobody made","Choose people known to be full of the Spirit and wisdom","Let them first be tested"],
  "Lord, give us discernment about people.",
  ["Write the scorecard before the posting","Make three real reference calls","Add one testing step"]),
 S("Meetings People Do Not Dread","Respect as a practice",["1 Corinthians 14:40","Ecclesiastes 5:2","Proverbs 15:22"],
  ["The hours we take from staff are a stewardship question","Let all things be done decently and in order","Plans succeed with many advisers, not many meetings"],
  "Father, help us honour people's time.",
  ["Cut one meeting or halve it","Publish an agenda in advance","End five minutes early on purpose"]),
 S("Giving Feedback","Clarity as kindness",["Proverbs 27:6","Ephesians 4:29","Galatians 6:1"],
  ["Vague feedback protects the giver","Wounds from a friend can be trusted","Restore gently, watching yourself"],
  "Lord, let our words build rather than bruise.",
  ["Give one specific piece of feedback","Rehearse it in pairs first","Ask how it landed afterwards"]),
 S("Leading Change","Sequencing what people can absorb",["Nehemiah 2:11-18","Mark 4:33","Acts 15:19-21"],
  ["Most failed change was the right change in the wrong order","Nehemiah surveyed at night before announcing","He spoke as much as they could bear"],
  "Father, give us patience with the pace of people.",
  ["Map who must be consulted first","Delay one announcement by two weeks","Ask three people before you decide"]),
 S("Decisions","How we actually make them",["Acts 15:6-22","Proverbs 11:14","Joshua 9:14"],
  ["Undefined decision rights produce slow decisions and resentful people","The council debated and then decided","They did not inquire of the Lord"],
  "Lord, give us clarity about who decides what.",
  ["Write the decision rights for your area","Get them confirmed","Name one decision nobody owns"]),
 S("Managing Up","Telling your leader the truth",["2 Samuel 12:1-7","Proverbs 28:23","Galatians 2:11"],
  ["A leader surrounded by mood-managers operates on bad information","Nathan told a story and then said you are the man","Rebuke earns more favour than flattery"],
  "Father, make us honest upward and gracious about it.",
  ["Say one honest thing upward","Ask what your leader is not hearing","Offer a solution alongside it"]),
 S("Time","Where it actually goes",["Ephesians 5:15-16","Psalm 90:12","Luke 10:38-42"],
  ["The calendar is the most honest document in your life","Teach us to number our days","Martha was distracted by much serving"],
  "Lord, help us spend our hours the way we say we value them.",
  ["Audit one week honestly","Compare it to your stated priorities","Protect one block next week"]),
 S("Finishing","Follow-through as character",["Ecclesiastes 5:5","John 17:4","Luke 14:29-30"],
  ["A leader who does not finish teaches that commitments are provisional","I have finished the work you gave me","Everyone who sees it will ridicule the unfinished tower"],
  "Father, help us complete what we start.",
  ["Finish one unfinished thing","Kill one thing that will never finish","Name what is blocking it"])]),

C("Strategy & Execution","Turning intention into a calendar",
"Churches rarely fail from a shortage of good ideas. They fail from a shortage of finished ones.",
["What is one thing you finished recently?","What is your favourite tool or system?",
 "What would you do with an extra day a week?","What is a plan that actually worked?"],
["Lord, order our steps. Let our plans be yours and our effort be faithful.",
 "Father, we commit these plans to you. Establish what is from you and dismantle what is not."],
["Proverbs 16:1-3","Proverbs 21:5","Luke 14:28-32","James 4:13-15","Nehemiah 6:15-16"],
"Bring the actual calendar and budget into the room. These sessions fail as abstract discussions.",
[S("The One Thing","Focus as a discipline",["Luke 10:41-42","Philippians 3:13","Mark 1:38"],
  ["A staff with five priorities has none","One thing is needed, and Mary chose it","Jesus named why he had come and left the crowd"],
  "Lord, give us the courage to choose one thing.",
  ["Rank your priorities and defend the top","Name what you drop","Get one shared answer in the room"]),
 S("What Gets Measured","Choosing the number honestly",["Luke 14:28","Matthew 7:16","1 Chronicles 21:1-8"],
  ["We measure attendance because it is easy and then optimize for it","By their fruit you will recognise them","David's census was counting the wrong thing"],
  "Father, help us count what you care about.",
  ["Name one better metric for your area","Stop reporting one vanity number","Ask what we are afraid to measure"]),
 S("The Annual Calendar","Protecting the big rocks",["Ecclesiastes 3:1","Proverbs 24:27","Nehemiah 2:6"],
  ["The calendar you did not design was designed for you","Prepare the field before building the house","Nehemiah named a time"],
  "Lord, give us wisdom about seasons.",
  ["Put three big rocks on the calendar first","Name what always gets squeezed","Remove one habitual repeat"]),
 S("Saying No","The skill that protects everything",["Matthew 5:37","Mark 1:35-38","Nehemiah 6:2-3"],
  ["Every yes is a no to something that mattered more","Jesus left towns that wanted him","I am doing a great work and cannot come down"],
  "Father, give us clean yeses and clean noes.",
  ["Decline one thing this week","Practise the sentence out loud","Name what the yes displaced"]),
 S("Why It Stalled","Diagnosing a stuck initiative",["Luke 14:29-30","Haggai 1:2-4","Proverbs 13:4"],
  ["Most stalled initiatives had no single owner","The time has not yet come, they said","The diligent are fully satisfied"],
  "Lord, help us finish or honestly stop.",
  ["Restart or formally kill one thing","Name the owner","Say publicly which it is"]),
 S("Ninety Days","The only horizon that works",["Proverbs 21:5","Nehemiah 6:15","Galatians 6:9"],
  ["Annual plans without checkpoints are aspirations with a longer runway","The wall was finished in fifty-two days","We reap at the proper time if we do not give up"],
  "Father, give us diligence in short seasons.",
  ["Write one ninety-day outcome","Book the review date now","Name the first two-week step"]),
 S("The Second Year","When novelty is gone",["Galatians 6:9","2 Corinthians 8:11","Revelation 2:4"],
  ["Year one runs on excitement; year two runs on conviction","Finish the work so your eagerness is matched by completion","You have forsaken the love you had at first"],
  "Lord, sustain us past the excitement.",
  ["Recommit to or retire one second-year initiative","Honour whoever launched it","Name what would make year two better"]),
 S("Resourcing Reality","Money, people and time",["Luke 14:31-32","Exodus 36:5-7","Proverbs 27:23"],
  ["A plan without money and people is a hope with a schedule","They had more than enough and were told to stop","Know well the condition of your flocks"],
  "Father, help us count honestly before we commit.",
  ["Cost out your biggest initiative","Name what you cut if it is not funded","Bring the finance leader in"]),
 S("Simplify","Doing fewer things better",["Ecclesiastes 6:11","Luke 10:42","Acts 6:2-4"],
  ["Church calendars accumulate and nothing is ever removed","More words, more meaninglessness","The apostles refused to be spread thin"],
  "Lord, give us the courage to subtract.",
  ["Propose one reduction in frequency","Name who will object","Say what improves as a result"]),
 S("Report Honestly","Including what failed",["Proverbs 28:13","Acts 5:1-11","2 Corinthians 8:20-21"],
  ["A staff that only reports wins will repeat its losses","Concealing does not prosper","We take pains to do what is right in the eyes of everyone"],
  "Father, make us truthful about results.",
  ["Report one failure honestly","Name what you learned","Change one thing because of it"])]),
]
