# -*- coding: utf-8 -*-
# Per-role extensions. Keyed to role id in staff_roles.py

def E(pb, qa, cs, jd, bs, vol, tk):
    return {"pb": pb, "qa": qa, "cs": cs, "jd": jd, "bs": bs, "vol": vol, "tk": tk}

# pb  = 7-step playbook to start this ministry from nothing
# qa  = 6 question/answer pairs
# cs  = 3 composite scenarios (small / mid / large)
# jd  = [purpose, reports_to, [responsibilities], [qualifications], [first90], [measures]]
# bs  = 6-session biblical study
# vol = volunteer roles this ministry needs
# tk  = toolbox by level: 4 lists

EXT = {

"senior": E(
 [["Preach a full year before changing anything","Credibility is spent, not granted. A year of faithful Sundays buys the right to redirect."],
  ["Find the twelve","Every congregation has twelve people whose opinion moves the rest. Know all of them by name in ninety days."],
  ["Name one direction, not five","A church can absorb one change at a time. Choosing which one is the whole job."],
  ["Get the elders aligned first","Never announce something the board heard the same day the congregation did."],
  ["Build a preaching calendar","Twelve months on paper turns preaching from weekly survival into a strategy."],
  ["Give away your best thing","Whatever you are most gifted at is what you must train someone else to do."],
  ["Write your own rhythms down","The pastor with no written plan for his soul is the pastor who leaves in year six."]],
 [["How long before I should change something?","Longer than you want. Most pastors move at month four and spend two years recovering. A year of listening is not passivity — it is the only way to find out what is load-bearing."],
  ["What if the elders and I disagree on direction?","Then you do not have a direction problem, you have an alignment problem, and preaching harder will not fix it. Slow down and get one written sentence everyone can say the same way."],
  ["How do I preach on money without losing people?","Preach it more, not less. Churches that address money once a year make it strange; churches that address it as one topic among many make it normal."],
  ["What do I do when giving drops?","Say something within two weeks. Silence is read as either denial or crisis, and both are worse than the number."],
  ["Should I hire staff or develop volunteers?","Below 250, develop. Above 250, both. Hiring to solve a leadership development problem produces an expensive version of the same problem."],
  ["How do I know if I should leave?","Not from a hard year — every year has one. The honest questions are whether you still love these people and whether the church is healthier than when you came."]],
 [["Church of 90, first-time solo pastor","Bivocational, preaching 48 weeks a year, doing every funeral and every hospital visit. The whole leverage is one thing: recruiting and training three people to share care so the pastor can think past Sunday.","The care team is the first hire even when it is unpaid."],
  ["Church of 400, plateaued six years","Everything runs and nothing grows. Usually a retention problem read as a reach problem. Start by finding out how many first-time guests return, which nobody currently knows.","Measure before you spend."],
  ["Church of 1,600, staff of eighteen","The senior pastor is now a leader of leaders and still preaching every week. The failure mode is doing both badly. Protect twelve hours a week for message preparation and give away everything else that can be given.","Preaching is the one thing that cannot be delegated."]],
 ["Provide spiritual leadership, biblical teaching and directional clarity for the whole congregation.","Elder board / governing body",
  ["Preach and teach at weekend services","Set and communicate vision and direction","Lead the staff and elder team",
   "Shepherd the congregation through crisis and celebration","Guard doctrine and church health","Represent the church publicly"],
  ["Ordained or ordination-track per denomination","Theological training or demonstrated equivalent","Proven teaching gift","Household in good order per 1 Timothy 3","Five years of ministry leadership"],
  ["Meet the twelve most influential members individually","Preach twelve consecutive weeks","Read the last three years of board minutes and budgets","Write a one-page assessment of what you found","Change nothing structural"],
  ["Weekly attendance and first-time guest return rate","Percentage of adults in groups and serving","Leaders developed and released","Giving households, not just total giving","Elder and staff health"]],
 [["The Shepherd and the Flock","1 Peter 5:1-4 — willingly, not for gain, not domineering, being examples"],
  ["Paul's Farewell","Acts 20:17-38 — three years of tears, and the elders he warned"],
  ["The Weight of Teaching","James 3:1 — judged more strictly, and why that should slow you down"],
  ["Moses and Delegation","Exodus 18 — the outside voice who saw what the leader could not"],
  ["Nehemiah's Four Months","Nehemiah 1-2 — grief, prayer, planning and the ask, in that order"],
  ["Finish the Race","2 Timothy 4:1-8 — preaching in season and out, and what finishing well requires"]],
 ["Prayer team","Care and visitation team","Hospitality host","Elder or board member","Sermon feedback group","Administrative support"],
 [["First 90 days assessment template","Preaching calendar builder","Personal rhythms plan","The twelve influencers map"],
  ["Annual preaching plan","Staff meeting agenda template","Difficult conversation prep sheet","Vision one-pager"],
  ["Churchwide formation plan","Leadership pipeline map","Crisis message framework","Change sequencing worksheet"],
  ["Succession plan template","Mentoring covenant","Institutional health scorecard","Legacy transition checklist"]]),

"exec": E(
 [["Read three years of financials before opinions","You cannot lead a budget you have not understood line by line."],
  ["Document one process end to end","Pick the messiest recurring thing and write it down. That document is your credibility."],
  ["Learn what the senior pastor is bad at","That is your actual job description, whatever the posted one said."],
  ["Fix the meeting","Agendas, decisions, owners, dates. Most church dysfunction is a meeting problem wearing a costume."],
  ["Build the staffing plan before the budget","Roles first, then people, then money. Reversing that order produces org charts built around personalities."],
  ["Get one dashboard working","Five numbers the board sees monthly. Fewer than five is thin, more than eight is noise."],
  ["Establish the annual planning rhythm","Calendar, budget and priorities set at the same time each year, not negotiated continuously."]],
 [["What if the senior pastor will not delegate?","Take things he does not enjoy first and do them visibly well. Trust is transferred through completed work, never through org charts."],
  ["Where do I draw the line on decisions?","Write it down and get it approved: spend limits, hiring authority, what needs board approval. Ambiguity here produces conflict later, always."],
  ["How much should we hold in reserve?","Three months of operating expense is the working floor. Six is healthy. Under one month, that is the only project this year."],
  ["How do I handle an underperforming staff member?","Clarity first. Most underperformance is unclear expectations, not unwillingness. If it survives clarity, then it is a performance issue and you move fast."],
  ["When do we need another staff member?","When a function has broken twice for lack of ownership, not when someone is busy. Busy is a scheduling problem."],
  ["Should the XP preach?","Occasionally is healthy. Regularly usually means the role is being used to fill a gap rather than run the organization."]],
 [["Church of 200, first XP hire","Usually a part-time or converted role. The temptation is to do everything; the job is to pick the three systems that are failing and fix those.","Do three things well, not eleven adequately."],
  ["Church of 700, five-person staff","Alignment is the problem — five ministries each optimizing themselves. The fix is one annual plan everyone contributes to and nobody can opt out of.","One calendar, one budget, one set of priorities."],
  ["Church of 2,000, multisite","Standards and replication. Everything undocumented breaks at the second location, and it breaks quietly for six months first.","Write it down before you replicate it."]],
 ["Convert vision into systems, staffing, budget and execution so ministry actually happens.","Senior Pastor",
  ["Supervise and develop staff","Own budget construction and monitoring","Lead annual and strategic planning",
   "Build and maintain operational systems","Oversee facilities, risk and compliance","Align ministries to the church's direction"],
  ["Demonstrated organizational leadership","Financial literacy","Experience supervising staff","Systems and process aptitude","Theological alignment and church experience"],
  ["Read three years of financials and board minutes","Meet every staff member individually","Document one broken process","Draft a staffing structure proposal","Establish the weekly staff meeting rhythm"],
  ["Budget accuracy against forecast","Staff retention and development","On-time completion of the annual plan","Systems documented and running without heroics","Reserve position"]],
 [["Jethro's Counsel","Exodus 18:13-26 — you will wear yourself out, and the structure that saved a leader"],
  ["The Seven Chosen","Acts 6:1-7 — a real complaint, a real process, and the word of God spread"],
  ["Counting the Cost","Luke 14:28-30 — planning as an act of faithfulness rather than a failure of faith"],
  ["Faithful With Little","Luke 16:10 — the principle that governs every administrative decision"],
  ["Joseph in Egypt","Genesis 41 — administration as ministry at national scale"],
  ["Order and Peace","1 Corinthians 14:33,40 — why decency and order is a theological claim, not a preference"]],
 ["Office and administrative volunteers","Data and database team","Finance counting team","Facilities crew","Event coordinators","IT support"],
 [["Budget reading guide","Process documentation template","Staff meeting agenda","Decision authority matrix"],
  ["Annual operating plan","Staffing plan builder","Interview structure and scorecard","Performance conversation guide"],
  ["Organizational design worksheet","Change sequencing plan","Risk register","Leadership pipeline map"],
  ["Governance framework template","Multisite operations standards","Executive coaching guide","Succession bench plan"]]),

"groups": E(
 [["Start with ten households, not a campaign","Ten groups that finish beats forty that dissolve by week four."],
  ["Recruit hosts, never teachers","The word teacher costs you nine of every ten potential leaders. Host is the whole unlock."],
  ["Give them six weeks, not forever","A finite ask gets a yes. Groups that finish well usually re-up; groups with no end date quietly stop."],
  ["Use material tied to the weekend","Same week, same passage. It doubles the sermon and halves the leader's prep."],
  ["Train in ninety minutes","One session before launch. Long training is a barrier disguised as excellence."],
  ["Coach the leaders weekly for six weeks","A text on Tuesday. The coaching layer is what most churches skip and it is the whole difference."],
  ["Celebrate publicly and immediately","Report the number from the platform in week seven. Momentum is a stewardship."]],
 [["Nobody will lead. What do we do?","You are almost certainly asking people to teach. Change the word to host, cap the commitment at six weeks, supply the material and the questions, and the yes rate changes immediately."],
  ["Should groups be free-form or curriculum-based?","Curriculum for new leaders, freedom for experienced ones. Handing a first-time host a blank page is how you lose them."],
  ["Open groups or closed groups?","Closed for the six weeks, open between terms. Ongoing open groups sound hospitable and usually produce neither depth nor growth."],
  ["How do we handle a group that goes doctrinally sideways?","Coaching, not policing. A weekly touch with each leader catches it in week two, while an annual review catches it after the damage."],
  ["What about people who will not join a group?","Some never will, and forcing it produces resentment. Serving teams are the other on-ramp and often the better one for men."],
  ["How do we multiply without splitting friendships?","Name the apprentice in week one, before there are friendships to protect. Multiplication decided in week ten always feels like divorce."]],
 [["Church of 120, no group structure","Ten households, six weeks, sermon-aligned material, pastor coaching each host by text. This is the entire strategy and it works.","Ten groups is a movement in a church of 120."],
  ["Church of 450, groups plateaued at 30%","Almost always a leader pipeline problem. The fix is naming apprentices in existing groups rather than recruiting new strangers.","Grow leaders from inside, not from the lobby."],
  ["Church of 1,800, 200 groups","Coaching structure is the constraint. One coach per five leaders, and the group pastor develops the coaches rather than the leaders.","Above 100 groups you lead coaches, not hosts."]],
 ["Build and sustain a group structure where people are known, cared for and formed.","Executive Pastor or Discipleship Pastor",
  ["Recruit, train and coach group leaders","Run group launches at least twice a year","Select or write group curriculum",
   "Place new people into groups within three weeks","Build the coaching layer","Track group health and multiplication"],
  ["Personal experience leading a group","Relational recruiting ability","Organizational follow-through","Theological soundness","Comfort developing others"],
  ["Attend every existing group once","Interview ten current and former group members","Map the current placement process","Recruit and train the first new cohort","Set the launch date"],
  ["Percentage of adults in a group","Leader retention term over term","Groups multiplied","Placement time from interest to first meeting","Leader satisfaction"]],
 [["From House to House","Acts 2:42-47 — devoted, together, and daily"],
  ["One Another","Romans 12:10-16 — the commands that require a small room to obey"],
  ["Bear One Another's Burdens","Galatians 6:1-5 — restoration and the limits of it"],
  ["Confess to Each Other","James 5:13-16 — the practice a Sunday service cannot host"],
  ["Do Not Give Up Meeting","Hebrews 10:23-25 — spurring one another on as a stated purpose"],
  ["Entrust to Faithful Others","2 Timothy 2:2 — four generations in one verse"]],
 ["Group host","Group apprentice or co-leader","Coach over five leaders","Placement and connection volunteer","Childcare coordinator","Curriculum reviewer"],
 [["Ten-household launch checklist","90-minute host training outline","Six-week curriculum selection guide","Host covenant"],
  ["Churchwide launch campaign plan","Placement workflow","Group health survey","Leader coaching text scripts"],
  ["Coach training curriculum","Multiplication conversation guide","Specialized group playbooks","Curriculum writing template"],
  ["Group system design document","Cross-church training curriculum","Formation measurement instrument","Publishing framework"]]),

"kids": E(
 [["Fix safety before anything else","Background checks, ratios, check-in and the two-adult rule. Nothing else matters if this is not right."],
  ["Recruit five people for one hour","Not a year. One hour, one Sunday a month, with a defined job and a named person who trains them."],
  ["Pick one curriculum and stay with it","Curriculum churn exhausts volunteers. Consistency beats novelty every time in children's ministry."],
  ["Win the parent handoff","Sixty seconds at pickup decides whether the family returns. Train every volunteer on what to say."],
  ["Align to the church's big idea","When the kids hear what the adults heard, a family has something to talk about at dinner."],
  ["Build one milestone","Dedication, first Bible, or baptism. One well-run milestone teaches parents that this ministry is serious."],
  ["Ask parents what they need","Then do one of the things they said. Parent partnership starts by listening rather than instructing."]],
 [["How do we recruit when nobody wants kids ministry?","Stop calling it childcare and stop asking for a year. Ask for one Sunday a month with a defined role, name the person who trains them, and make the room a place adults enjoy being in."],
  ["What ratio do we need?","One adult to four for preschool, one to eight for elementary, and never one adult alone with children regardless of size. Check your insurer and your state, because the requirements vary."],
  ["Should kids be in the service?","Some of the time, deliberately. A family service each quarter forms children in ways a separate room cannot, and it teaches the congregation that children belong."],
  ["What if a child discloses abuse?","You have a protocol before it happens, not after. Listen, do not investigate, document, and report per your legal obligation the same day. Every volunteer should know this."],
  ["How do we include children with special needs?","Ask the parents first — they know what works. A buddy volunteer solves most situations and costs nothing."],
  ["How much should parents be doing at home?","One rhythm, not five. Most families will not add a devotional; they will add one question at dinner. Start there."]],
 [["Church of 80, one combined room","Ages three to eleven together. The answer is not more rooms, it is one strong volunteer team and material designed for mixed ages.","Depth of relationship beats age precision at this size."],
  ["Church of 350, growing families","The bottleneck is usually space and safety systems, not curriculum. Check-in, ratios and room capacity limit growth before content does.","Fix the system before buying new material."],
  ["Church of 2,000, multi-service","Volunteer coverage across services is the whole game. A pipeline that produces coordinators, not just helpers, is what makes it sustainable.","Recruit leaders of teams, not members of teams."]],
 ["Lead the spiritual formation of children and partner with parents who do the daily work.","Family Ministry Pastor or Executive Pastor",
  ["Run safe, welcoming weekend environments","Recruit, screen and train volunteers","Select and align curriculum",
   "Partner with and equip parents","Design family milestones","Maintain safeguarding standards"],
  ["Experience with children's ministry","Background check clearance","Recruiting and volunteer leadership ability","Understanding of child development","Theological alignment"],
  ["Complete safeguarding certification","Audit check-in, ratios and rooms","Meet every current volunteer","Survey twenty parents","Fix the single biggest safety gap"]],
 [["Impress Them on Your Children","Deuteronomy 6:4-9 — the home as the primary classroom"],
  ["Let the Children Come","Mark 10:13-16 — and the disciples who got it wrong"],
  ["Train Up a Child","Proverbs 22:6 — read as proverb, not guarantee"],
  ["From Infancy You Have Known","2 Timothy 3:14-15 — Lois, Eunice and a faith that held"],
  ["The Boy Samuel","1 Samuel 3 — a child who heard what the priest missed"],
  ["Millstones","Matthew 18:1-6 — the seriousness of causing a child to stumble"]],
 ["Small group leader","Large group teacher","Check-in and safety team","Buddy for special needs","Room setup crew","Parent liaison"],
 [["Safeguarding checklist","Ratio and room capacity guide","Volunteer role descriptions","Parent handoff script"],
  ["Curriculum alignment map","Milestone pathway design","Parent equipping series","Volunteer training session"],
  ["Department plan template","Crisis and disclosure protocol","Coordinator development track","Space and facility brief"],
  ["Family formation strategy","Cross-church training curriculum","Curriculum authorship guide","Safeguarding standard for a network"]]),

"steward": E(
 [["Teach before you ask","A church that only hears about money when it needs money has been taught that money is need. Reverse that order for a full year."],
  ["Look at the household data","Not totals — how many households give, how many gave once and stopped, how many are new. Totals hide everything."],
  ["Fix the first-gift follow-up","Almost no church thanks a first-time giver well. This is the cheapest, highest-return fix available."],
  ["Run one financial discipleship class","Serving the strained half of your congregation buys the right to speak to the generous half."],
  ["Build the annual rhythm","Generosity taught at four planned moments a year, not one appeal in November."],
  ["Start the legacy conversation","One teaching moment a year on wills and estates. Most churches have never had one."],
  ["Report impact without asking","At least twice a year, tell people what their giving did and ask for nothing that day."]],
 [["When should we talk about money?","More often and more calmly than you do. Four planned moments a year makes it normal; one November appeal makes it transactional."],
  ["What if the pastor will not preach on giving?","Find out why. It is usually either a bad experience elsewhere or discomfort about his own finances, and both are addressable — but not by pressure."],
  ["Do we name the amount we need?","Yes, in a campaign. Vague asks produce vague responses. Outside a campaign, teach the principle and let people decide the number."],
  ["Should we pursue major donors?","Pursue relationships, not donors. The moment a family senses they are a revenue line, the pastoral relationship is finished and it does not come back."],
  ["What about the asset conversation?","This is the largest untapped area in almost every church. Most people give from income; the wealth is in assets. That conversation requires an advisor in the room and a policy before it starts."],
  ["Is a capital campaign worth it?","Only if the vision is real and the timing is clear. A campaign for a building nobody wants will fund the building and cost you the congregation."]],
 [["Church of 150, giving flat","Start with participation, not amount. Find out what percentage of households give — it is usually far lower than anyone assumes — then work on first-time and lapsed givers.","Participation before amount, always."],
  ["Church of 600, planning a building","The campaign will succeed or fail on the twelve months before it, not the six weeks of it. Formation first, ninety-day gap, then the ask.","Never run formation and an ask in the same season."],
  ["Church of 3,000, strong giving, no legacy program","The largest wealth transfer in history is passing through this congregation untouched. A gift acceptance policy and one annual teaching moment is the entry point.","The money leaving is bigger than the money coming."]],
 ["Form generous disciples and fund the mission without ever manipulating anyone.","Executive Pastor or Senior Pastor",
  ["Teach and champion biblical generosity","Design the annual generosity rhythm","Run campaigns when needed",
   "Care for givers and report impact","Lead financial discipleship offerings","Develop legacy and asset giving"],
  ["Theological grounding in stewardship","Comfort with money conversations","Relational and pastoral instincts","Data literacy","Absolute discretion"],
  ["Analyze three years of giving by household","Meet the finance team and read the budget","Draft the annual generosity calendar","Fix first-gift follow-up","Teach once"]],
 [["God Owns It All","Psalm 24:1, Deuteronomy 8:17-18 — ownership as the starting premise"],
  ["The Macedonian Churches","2 Corinthians 8:1-5 — poverty overflowing in generosity"],
  ["Cheerfully, Not Reluctantly","2 Corinthians 9:6-8 — motive over compliance"],
  ["Two Small Coins","Mark 12:41-44 — proportion, and a Jesus who was watching"],
  ["The Rich Fool","Luke 12:13-21 — the man who used the word my too often"],
  ["Treasure and Heart","Matthew 6:19-24 — the direction of the relationship"]],
 ["Financial coach or mentor","Class facilitator","Testimony coordinator","Thank-you note team","Legacy conversation host","Campaign team lead"],
 [["Giving analysis worksheet","First-gift follow-up sequence","Annual generosity calendar","Teaching outline set"],
  ["Financial discipleship class kit","Donor care system","Impact report template","Lapsed giver recovery plan"],
  ["Capital campaign playbook","Asset track seminar","Legacy conversation guide","Gift acceptance policy"],
  ["Advisor partnership brief","Foundation engagement plan","Cross-church training","Multigenerational family framework"]]),
}

# Roles without a bespoke extension inherit a generated one built from their level data.
GENERIC_PB = [
 ["Assess before you build","Two weeks of listening. What exists, what died, and why — the history explains most of the resistance you will meet."],
 ["Name the one outcome","Not a programme. One thing that will be different in twelve months, written in a sentence."],
 ["Find two people","Not a committee. Two people who care about this already, who will do the work with you."],
 ["Run one small thing well","A single event or group, executed properly. Credibility comes from finishing, not from announcing."],
 ["Write down what worked","The first documented process is what makes the second attempt cheaper than the first."],
 ["Recruit from the people who came","Your best volunteers are already in the room. Ask them personally within two weeks."],
 ["Put it on the church calendar","A ministry that is not on the calendar and in the budget is a hobby with good intentions."],
]
