# -*- coding: utf-8 -*-
# Church Staff Intelligence — 20 roles x 4 levels

def R(rid, name, cat, purpose, resp, anchor, figure, levels):
    return {"id": rid, "n": name, "cat": cat, "p": purpose, "r": resp,
            "a": anchor, "fig": figure, "lv": levels}

def L(mods, outcome, cert):
    return {"m": mods, "o": outcome, "c": cert}

ROLES = [

R("senior","Senior Pastor","Leadership",
 "Carries the vision, the teaching and the spiritual weight of the whole congregation.",
 ["Preaching and teaching","Vision and direction","Elder and staff leadership","Pastoral care of leaders","Spiritual formation of the body","Public representation of the church"],
 "1 Peter 5:1-4","Paul at Miletus, Acts 20 — three years of tears, and the elders he wept with",
 [L([["The call and the cost","What you actually signed up for, before the first crisis"],
     ["Preaching that lands","One idea, one text, one action"],
     ["Your own soul first","Rhythms that survive a hard year"],
     ["Reading a congregation","What people are saying and what they mean"],
     ["The first hundred days","Listening before changing anything"]],
    "Can preach a clear message weekly and describe the church's actual condition honestly.",
    "Six sermons reviewed; one written personal rhythm plan."),
  L([["Vision that holds","Casting it, repeating it, and surviving the leak"],
     ["Leading a staff","Hiring, aligning, and the conversations nobody wants"],
     ["Board and elder health","Governance without politics"],
     ["Conflict without casualties","The five conversations that decide a tenure"],
     ["Preaching a series and a season","Arc over episode"],
     ["Money from the platform","Teaching generosity without flinching"]],
    "Can lead a staff, chair an elder meeting, and carry a twelve-month preaching plan.",
    "One vision document; one recorded difficult conversation debrief."),
  L([["Formation over programming","Building a discipleship pathway, not a calendar"],
     ["Leading change","Sequencing what a congregation can absorb"],
     ["Multiplying leaders","Giving away what you are best at"],
     ["Preaching in a crisis","The forty-eight hour message"],
     ["The second decade","Staying fresh without novelty"],
     ["Community and city","Leading a church that is not only for itself"]],
    "Can design and lead a churchwide formation strategy across a full year.",
    "One annual formation plan; two leaders raised and released."),
  L([["Succession","Building past yourself, on purpose"],
     ["Multiplying churches","Sending, planting, and campus work"],
     ["Mentoring other pastors","The generational assignment"],
     ["Institutional health","What outlives a personality"],
     ["Finishing well","The last quarter of a ministry"]],
    "Can develop other senior pastors and hand a healthy church to the next leader.",
    "Two pastors mentored to completion; one written succession plan.")]),

R("exec","Executive Pastor","Leadership",
 "Turns vision into systems, budget, staffing and execution so the church actually runs.",
 ["Staff supervision","Budget and operations","Strategic planning","Systems and process","Ministry alignment","Risk and compliance"],
 "Exodus 18:13-26","Jethro, who told Moses he would wear himself out, and gave him a structure",
 [L([["What an XP actually does","And the four things that are not the job"],
     ["Reading a church budget","Line by line, without embarrassment"],
     ["Meeting discipline","Agendas, decisions, and follow-through"],
     ["Working for a visionary","Translating without resenting"],
     ["Systems thinking","Why the same problem keeps recurring"]],
    "Can run a staff meeting and read a budget with confidence.",
    "One process documented end to end."),
  L([["Building a staffing plan","Roles before people"],
     ["Performance conversations","Clarity as kindness"],
     ["Annual planning and calendar","Protecting the big rocks"],
     ["Dashboards that matter","Measuring formation, not just attendance"],
     ["Vendor and facility stewardship","The unglamorous half"],
     ["Hiring well","Interview structure and reference discipline"]],
    "Can build an annual plan, budget and staffing structure.",
    "One annual operating plan; three structured interviews conducted."),
  L([["Organizational design","Structure that fits the size you are becoming"],
     ["Leading through change","Sequencing, communication and resistance"],
     ["Multisite and expansion operations","What breaks at every threshold"],
     ["Legal, risk and safeguarding","Where churches actually get hurt"],
     ["Developing the leadership pipeline","Every seat two deep"],
     ["Culture as a system","What you tolerate is what you get"]],
    "Can restructure an organization and lead it through a major transition.",
    "One reorganization plan; one risk audit completed."),
  L([["Executive coaching","Developing other XPs"],
     ["Governance architecture","Board, elders, staff, and where authority sits"],
     ["Scaling past a thousand","The systems that only matter at size"],
     ["Succession across a staff","Bench strength as strategy"],
     ["The XP as second chair","Partnership without shadow leadership"]],
    "Can coach other executive pastors and design governance for a complex church.",
    "Two XPs coached; one full governance framework authored.")]),

R("worship","Worship Pastor","Ministry",
 "Leads the congregation into worship and builds the team that carries it every week.",
 ["Weekend worship planning","Team recruitment and rehearsal","Song selection and theology","Tech and production","Volunteer development","Service flow with the preaching"],
 "1 Chronicles 15:16-22","Asaph and the Levites appointed to sing — a role, a roster and a rehearsal",
 [L([["Worship is not music","What the word means before it means a set"],
     ["Building a set","Keys, flow, and the congregation's voice"],
     ["Leading rehearsal","Ninety minutes that decide Sunday"],
     ["Working with a preacher","Serving the message rather than competing"],
     ["Your own worship","Leading from full rather than empty"]],
    "Can plan and lead a weekend service with a small team.",
    "Four services led and reviewed."),
  L([["Song theology","What you sing is what they will believe in ten years"],
     ["Recruiting musicians","Where they are and how to ask"],
     ["Tech and production basics","Sound, lights, screens, and the people running them"],
     ["Service design","The whole hour, not just the songs"],
     ["Developing vocalists and players","Coaching without crushing"],
     ["The seasons","Advent, Lent, Easter and the church year"]],
    "Can build a rotating team and design a full service.",
    "One team of twelve built; one seasonal service designed."),
  L([["Leading a department","Budget, staff and volunteers"],
     ["Writing and original music","When a church should write its own"],
     ["Multisite and multi-service worship","Consistency without cloning"],
     ["Worship and formation","Connecting Sunday to the week"],
     ["Raising worship leaders","Giving the platform away"],
     ["Cultural and generational tension","Leading a room that disagrees"]],
    "Can lead a worship department and develop other leaders.",
    "Three worship leaders raised; one department plan."),
  L([["Worship theology, deeply","The historic church and the contemporary room"],
     ["Training other worship pastors","Beyond your own church"],
     ["Building a worship residency","A pipeline rather than a hire"],
     ["Producing","Recording, streaming and original content"],
     ["Legacy and succession","Handing off a culture"]],
    "Can train worship pastors and build a residency pipeline.",
    "Two worship pastors trained; one residency curriculum.")]),

R("groups","Small Group Pastor","Ministry",
 "Gets people out of rows and into circles, then keeps them there.",
 ["Group launch and placement","Leader recruitment and training","Curriculum selection","Group health and multiplication","Host home network","Care through groups"],
 "Acts 2:42-47","The Jerusalem church, meeting in the temple courts and from house to house",
 [L([["Rows and circles","Why the service alone will never form anyone"],
     ["Host, do not teach","The single sentence that fixes recruiting"],
     ["Launching your first groups","Ten households, six weeks"],
     ["Choosing curriculum","Fit over fashion"],
     ["The first four minutes","How a group starts decides how it goes"]],
    "Can launch and support a first wave of groups.",
    "Ten groups launched; six leaders trained."),
  L([["A group launch campaign","The churchwide on-ramp"],
     ["Leader training that sticks","Six sessions, then coaching"],
     ["Placement and assimilation","The connection card to the living room"],
     ["Group health","What to measure besides attendance"],
     ["Care inside groups","When to pray and when to call a pastor"],
     ["Sermon-aligned groups","Same week, same text"]],
    "Can run a churchwide group launch and train leaders at scale.",
    "One launch campaign executed; twenty-five leaders trained."),
  L([["Coaching the coaches","The layer most churches skip"],
     ["Multiplication","Building the next leader into week one"],
     ["Specialized groups","Recovery, marriage, men, women, students"],
     ["Groups at every campus","Consistency across locations"],
     ["Curriculum development","Writing your own from your own preaching"],
     ["The group life system","From first visit to leading"]],
    "Can build a coaching structure and a multiplying system.",
    "One coaching layer built; one original curriculum written."),
  L([["Small group movements","What scale actually requires"],
     ["Training other group pastors","Beyond your church"],
     ["Denominational and network work","Multiplying across churches"],
     ["Research and measurement","Proving formation, not participation"],
     ["Writing and publishing","Turning a system into a resource"]],
    "Can train group pastors across churches and publish a system.",
    "Two group pastors trained; one published system.")]),

R("kids","Children's Pastor","Ministry",
 "Forms the youngest disciples and partners with parents who do the daily work.",
 ["Weekend children's ministry","Volunteer recruitment and safety","Curriculum and formation","Parent partnership","Family milestones","Safeguarding and check-in"],
 "Deuteronomy 6:4-9","Jesus in Mark 10, indignant with the disciples for keeping children away",
 [L([["Children's ministry is not childcare","The theological correction that changes everything"],
     ["Safety and safeguarding","Background checks, ratios, check-in, two-adult rule"],
     ["Recruiting volunteers","Why this is the hardest ask and how to make it"],
     ["Age-appropriate formation","What a five-year-old can actually receive"],
     ["The parent handoff","Sixty seconds that decide whether they come back"]],
    "Can run a safe, welcoming weekend ministry with a small team.",
    "Safeguarding certification; one volunteer team of ten."),
  L([["Curriculum and the big idea","Aligning with what the church is teaching"],
     ["Parents as the primary discipler","And what the church is actually for"],
     ["Milestones","Dedication, first communion, baptism, transitions"],
     ["Special needs inclusion","Making room rather than making do"],
     ["Volunteer development","Training, retention and honour"],
     ["Kids and the gospel","Presenting it without manipulating"]],
    "Can build a curriculum plan and a parent partnership strategy.",
    "One year of curriculum planned; one milestone pathway built."),
  L([["Leading a family ministry department","Kids, students and parents as one"],
     ["Nursery through fifth grade pathway","Formation across seven years"],
     ["Multi-service and multisite kids","Consistency and staffing"],
     ["Budget, space and facility","Designing rooms that work"],
     ["Raising volunteer leaders","Coordinators who run their own areas"],
     ["Crisis and disclosure","What to do when a child tells you something"]],
    "Can lead a department and design a full formation pathway.",
    "One department plan; one crisis protocol authored."),
  L([["Family formation strategy","Church and household as one system"],
     ["Training other children's pastors","Coaching beyond your building"],
     ["Curriculum authorship","Writing for children well"],
     ["Advocacy and safeguarding leadership","Setting the standard for a network"],
     ["Generational vision","Twenty years out"]],
    "Can train children's pastors and author curriculum.",
    "Two pastors trained; one curriculum published.")]),

R("students","Student Pastor","Ministry",
 "Walks with teenagers through the years that decide whether faith becomes theirs.",
 ["Weekly student gathering","Small group leaders","Parent ministry","Camps, retreats and trips","Discipleship and next steps","Transition to adult ministry"],
 "1 Timothy 4:12","Timothy, young and told not to let anyone look down on him",
 [L([["Adolescence, honestly","What is actually happening developmentally"],
     ["Building a weekly gathering","Rhythm over spectacle"],
     ["Recruiting adult leaders","Five adults per student is the number that predicts staying"],
     ["Talking to teenagers","Without performing youth"],
     ["Safety, boundaries and social media","The non-negotiables"]],
    "Can run a healthy weekly gathering with volunteer leaders.",
    "Safeguarding certification; one leader team of six."),
  L([["Student small groups","Where the actual discipleship happens"],
     ["Parent partnership","Ministering to the household, not just the student"],
     ["Camps and retreats","Designing for what happens afterward"],
     ["Mental health in students","Signs, referrals and staying in your lane"],
     ["Teaching students","Depth as respect"],
     ["Middle school and high school","Two different ministries"]],
    "Can build a group structure and a parent strategy.",
    "One retreat designed and led; one parent track launched."),
  L([["Leading a student department","Staff, budget, volunteers"],
     ["The senior year and the launch","Sending them well"],
     ["Students on mission","Trips that form rather than tour"],
     ["Student leadership","Handing them real responsibility"],
     ["Doubt and deconstruction","Non-defensive, unafraid"],
     ["Integration with the whole church","Not a holding pen"]],
    "Can lead a department and build a leadership pipeline.",
    "One department plan; six student leaders developed."),
  L([["Generational discipleship strategy","Cradle to launch as one system"],
     ["Training other student pastors","Beyond your church"],
     ["Longitudinal research","Who stayed, and why"],
     ["Curriculum and resource authorship","Writing for teenagers"],
     ["Advocacy and network leadership","Setting standards"]],
    "Can train student pastors and lead a network.",
    "Two pastors trained; one longitudinal study.")]),

R("elder","Elder / Board Member","Governance",
 "Shepherds, governs and guards the doctrine and direction of the church.",
 ["Spiritual oversight","Doctrinal guardianship","Pastoral care and prayer","Governance and major decisions","Pastor support and accountability","Church discipline"],
 "Titus 1:5-9","The elders of Ephesus, charged to keep watch over themselves and the flock",
 [L([["What an elder is","And what a board member is not"],
     ["The qualifications","1 Timothy 3 and Titus 1, read slowly"],
     ["Shepherding, not managing","The distinction most boards miss"],
     ["Praying for a congregation","The primary work"],
     ["Reading a church financial statement","Fiduciary basics"]],
    "Can serve faithfully in an elder meeting and pray pastorally.",
    "Written affirmation of qualifications; six meetings attended."),
  L([["Governance models","Elder-led, congregational, staff-led and hybrids"],
     ["Supporting and holding a pastor","Both at once"],
     ["Doctrinal guardianship","What we believe and how we defend it"],
     ["Handling conflict","When members are at odds"],
     ["Church discipline","Matthew 18 with pastoral care"],
     ["Confidentiality","What stays in the room"]],
    "Can participate fully in governance and doctrinal decisions.",
    "One doctrinal position paper; one conflict mediated."),
  L([["Leading a board","Chairing, agendas and decisions"],
     ["Senior pastor evaluation","Honest, structured, annual"],
     ["Major decisions","Buildings, budgets, staffing, direction"],
     ["Crisis governance","Scandal, resignation, moral failure"],
     ["Legal and fiduciary duty","Where boards are actually liable"],
     ["Elder development","Raising the next board"]],
    "Can chair a board and lead through a governance crisis.",
    "One crisis protocol; two elders mentored."),
  L([["Institutional stewardship","What outlives everyone in the room"],
     ["Pastoral succession","The board's hardest assignment"],
     ["Training elders in other churches","Beyond your own"],
     ["Denominational and network governance","Wider accountability"],
     ["Finishing an eldership well","Handing it on"]],
    "Can train elder boards and lead a pastoral succession.",
    "One succession led; one board trained externally.")]),

R("finance","Finance & Administration Pastor","Operations",
 "Stewards the money, the buildings and the compliance so ministry can happen.",
 ["Budgeting and forecasting","Accounting and reporting","Payroll and benefits","Facilities and insurance","Compliance and audit","Counting and controls"],
 "1 Corinthians 4:2","Joseph in Egypt, trusted with everything and accountable for all of it",
 [L([["Church accounting basics","Fund accounting and why it differs"],
     ["Building a budget","From ministry plans, not last year plus three percent"],
     ["Internal controls","Two-person counting and why it protects everyone"],
     ["Payroll and clergy tax","Housing allowance and the common mistakes"],
     ["Monthly reporting","What a board actually needs to see"]],
    "Can produce accurate monthly financials and a working budget.",
    "Twelve months of clean reporting; one control audit."),
  L([["Cash flow and reserves","How many months, and why"],
     ["Facilities stewardship","Preventive maintenance as discipleship"],
     ["Insurance and risk","What is actually covered"],
     ["Designated gifts and restrictions","Legal and ethical handling"],
     ["Vendor management","Contracts and negotiation"],
     ["Communicating finances","Transparency that builds trust"]],
    "Can manage cash, facilities and risk across a full year.",
    "One reserve policy; one risk register."),
  L([["Capital projects and debt","Building, borrowing and the real cost"],
     ["Multi-entity structures","Campuses, schools and nonprofits"],
     ["Audit readiness","External review without panic"],
     ["Compensation philosophy","Fair, defensible and documented"],
     ["Financial leadership at the table","Advising, not just reporting"],
     ["Long-range financial planning","Five and ten year models"]],
    "Can lead a capital project and pass an external audit.",
    "One capital plan; one clean external audit."),
  L([["Financial governance design","Policy, oversight and delegation"],
     ["Endowment and legacy funds","Stewardship past a lifetime"],
     ["Training other church administrators","Beyond your church"],
     ["Crisis financial leadership","Shortfall, fraud and recovery"],
     ["Institutional sustainability","Twenty-year health"]],
    "Can train administrators and lead through financial crisis.",
    "Two administrators trained; one endowment established.")]),

R("steward","Stewardship & Generosity Pastor","Operations",
 "Forms generous disciples and funds the mission without manipulating anyone.",
 ["Generosity teaching","Giving campaigns","Major and legacy giving","Donor care","Financial discipleship classes","Annual and capital funding"],
 "2 Corinthians 9:6-8","The Macedonian churches, whose poverty overflowed in generosity",
 [L([["Generosity is discipleship","Not fundraising with a Bible verse"],
     ["The theology of ownership","God owns it all as the starting premise"],
     ["Teaching money from the platform","Without flinching or apologizing"],
     ["Giving basics","First fruits, proportion and the tithe conversation"],
     ["Reading giving data","Households, not just totals"]],
    "Can teach generosity biblically and read the church's giving picture.",
    "Four generosity messages; one giving analysis."),
  L([["Annual generosity strategy","A rhythm rather than an appeal"],
     ["Financial discipleship classes","Budgeting, debt and margin"],
     ["Donor care","Thanking well and reporting impact"],
     ["First-time and lapsed givers","The two most important segments"],
     ["Campaign basics","Case, ask, and follow-through"],
     ["Digital and recurring giving","Removing friction"]],
    "Can run an annual generosity plan and a financial discipleship track.",
    "One annual plan; one class taught to completion."),
  L([["Capital campaigns","Vision, case, sequence and the quiet phase"],
     ["Major donor relationships","Ministry, not cultivation"],
     ["Legacy and estate giving","The conversation nobody starts"],
     ["Business owners and marketplace givers","A different conversation"],
     ["Generosity culture","Beyond the campaign"],
     ["Kingdom investing","Capital deployed for mission"]],
    "Can lead a capital campaign and a legacy giving programme.",
    "One campaign led; one legacy programme launched."),
  L([["Generosity movements","Beyond a single church"],
     ["Training other stewardship pastors","Coaching across churches"],
     ["Advisor and foundation partnerships","Working with the professionals"],
     ["Multigenerational wealth transfer","Families, not just donors"],
     ["Writing and teaching nationally","Turning practice into resource"]],
    "Can train stewardship pastors and work with foundations and advisors.",
    "Two pastors trained; one foundation partnership.")]),

R("marriage","Marriage & Family Pastor","Ministry",
 "Strengthens the households the church is actually made of.",
 ["Premarital preparation","Marriage enrichment","Crisis and restoration","Parenting ministry","Blended and single-parent families","Family milestones"],
 "Ephesians 5:21-33","Priscilla and Aquila, always named together, always working together",
 [L([["Why marriage ministry","And why most churches do not have one"],
     ["Premarital counselling","A structure that actually prepares people"],
     ["Communication and conflict","The two skills underneath everything"],
     ["Money and marriage","The fight underneath the fight"],
     ["Referral boundaries","What is pastoral and what is clinical"]],
    "Can run premarital preparation and basic marriage enrichment.",
    "Six couples through premarital; referral list built."),
  L([["Marriage enrichment programming","Retreats, classes and groups"],
     ["Parenting ministry","By stage, from infants to launching"],
     ["Blended families","Honoured rather than tolerated"],
     ["Single parents","Carrying it with a church around them"],
     ["Marriages in trouble","Triage, referral and walking alongside"],
     ["Mentor couples","The multiplication model"]],
    "Can build a marriage and parenting ministry with mentor couples.",
    "One retreat led; eight mentor couples trained."),
  L([["Crisis and restoration","Affairs, addiction and separation"],
     ["Leading a family ministry department","Marriage, parenting and family together"],
     ["Working with counsellors","Partnership and boundaries"],
     ["Family formation strategy","The household as the unit"],
     ["Difficult topics","Abuse, divorce and remarriage with theological care"],
     ["Multiplying mentor couples","A movement rather than a class"]],
    "Can lead a department and handle marriage crisis well.",
    "One restoration protocol; twenty mentor couples."),
  L([["Family formation across a church","Every ministry aligned to the household"],
     ["Training other marriage pastors","Beyond your church"],
     ["Curriculum authorship","Writing for couples"],
     ["Community and marketplace marriage work","Outside the church walls"],
     ["Generational family legacy","Three generations at a time"]],
    "Can train marriage pastors and author curriculum.",
    "Two pastors trained; one curriculum published.")]),

R("men","Men's Ministry Director","Ministry",
 "Calls men into faith, brotherhood and responsibility.",
 ["Men's groups and studies","Retreats and events","Discipleship and accountability","Service projects","Fathers and husbands","Leadership development"],
 "1 Corinthians 16:13-14","Nehemiah's builders, each family repairing the section in front of their own house",
 [L([["Why men are missing","The honest diagnosis before the programme"],
     ["Starting a men's group","Six men, six weeks, one room"],
     ["What men actually respond to","Task, challenge and shoulder-to-shoulder"],
     ["Spiritual partners","Not accountability with a clipboard"],
     ["The first invitation","Getting a man through the door once"]],
    "Can launch and sustain a men's group.",
    "One group of eight sustained six months."),
  L([["Retreats and events","Designing for follow-through, not a weekend high"],
     ["Fathers and sons","The relationship most men want help with"],
     ["Men in crisis","Job loss, addiction, marriage and shame"],
     ["Serving as discipleship","Work projects that form"],
     ["Multiplying groups","Every group producing the next leader"],
     ["Reaching the unchurched man","The hardest demographic in America"]],
    "Can run a retreat and multiply groups.",
    "One retreat led; four groups multiplied."),
  L([["Leading a men's ministry","Structure, budget and volunteers"],
     ["Men's discipleship pathway","From first invitation to leading"],
     ["Marketplace men","Vocation, integrity and influence"],
     ["Mentoring across generations","Older men and younger men"],
     ["Purity and integrity","Handled with honesty, not shame"],
     ["Men and the household","Husband, father, son"]],
    "Can lead a ministry with a full discipleship pathway.",
    "One pathway built; twelve leaders raised."),
  L([["Men's movements","Beyond one church"],
     ["Training other directors","Coaching across churches"],
     ["Curriculum and resource writing","Material men will actually use"],
     ["Community and city work","Men serving a place"],
     ["Legacy and generational vision","Fathers to grandfathers"]],
    "Can train directors and lead a regional movement.",
    "Two directors trained; one regional gathering.")]),

R("women","Women's Ministry Director","Ministry",
 "Builds a community where women are discipled, known and deployed.",
 ["Women's studies and groups","Events and retreats","Mentoring across generations","Care and crisis support","Leadership development","Mothers and caregivers"],
 "Titus 2:3-5","The women at the tomb, first to see it and first sent to tell",
 [L([["Beyond tea and crafts","A ministry of formation, not decoration"],
     ["Starting a women's study","Small, consistent, and honest"],
     ["Reaching every season","Single, married, mothering, empty nest, widowed"],
     ["Creating safety","Where women will actually tell the truth"],
     ["The first invitation","Getting a woman through the door once"]],
    "Can lead a women's study across life stages.",
    "One study of twelve completed."),
  L([["Events and retreats","Designing for depth, not just attendance"],
     ["Mentoring pairs","Titus 2, made practical"],
     ["Women in crisis","Abuse, infertility, grief and referral boundaries"],
     ["Mothers of young children","The season with no margin"],
     ["Working women and marketplace","Vocation and calling"],
     ["Multiplying leaders","Every study producing the next leader"]],
    "Can run a retreat and build a mentoring structure.",
    "One retreat led; ten mentor pairs formed."),
  L([["Leading a women's ministry","Structure, budget and volunteers"],
     ["Discipleship pathway","From first event to leading"],
     ["Teaching women well","Depth and biblical handling"],
     ["Where churches disagree","Women's roles, held with humility"],
     ["Care networks","Meals, crisis and the practical ministry"],
     ["Intergenerational community","Twenty-somethings and eighty-somethings"]],
    "Can lead a ministry with a full pathway.",
    "One pathway built; twelve leaders raised."),
  L([["Women's movements","Beyond one church"],
     ["Training other directors","Coaching across churches"],
     ["Writing and teaching","Resources women will use"],
     ["Advocacy and community work","Serving vulnerable women"],
     ["Generational legacy","Mothers, daughters, grandmothers"]],
    "Can train directors and lead a regional movement.",
    "Two directors trained; one published resource.")]),

R("missions","Missions & Outreach Pastor","Ministry",
 "Sends the church outward — into the city and to the nations.",
 ["Local outreach partnerships","Global missions strategy","Short-term teams","Missionary care","Church planting support","Mobilizing the congregation"],
 "Acts 13:1-3","The church at Antioch, fasting and sending away its two best leaders",
 [L([["Missions is not a department","It is the church's direction"],
     ["Your city, honestly assessed","Who is here and what is needed"],
     ["Choosing partners","Depth over breadth"],
     ["Short-term trips","What they do and do not accomplish"],
     ["Mobilizing a congregation","Give, pray or go"]],
    "Can run a local partnership and a short-term team.",
    "One partnership established; one trip led."),
  L([["Global strategy","Focus rather than a list of everyone"],
     ["Missionary care","What they actually need from a sending church"],
     ["Helping without hurting","Development that does not harm"],
     ["Team preparation and debrief","Where the formation happens"],
     ["Refugees and diaspora","The nations already here"],
     ["Reporting impact","Faces and numbers together"]],
    "Can build a global strategy and care for sent workers.",
    "One strategy document; three workers supported well."),
  L([["Leading a missions department","Budget, teams and partnerships"],
     ["Church planting","Supporting and sending"],
     ["Indigenous leadership","Building what outlives us"],
     ["Business as mission","Access through vocation"],
     ["Crisis and disaster response","Ready before it happens"],
     ["Sending your own people","The cost and the gain"]],
    "Can lead a department and send workers and planters.",
    "One planter sent; one department plan."),
  L([["Multiplication strategy","Churches planting churches"],
     ["Network and denominational work","Beyond one congregation"],
     ["Training other missions pastors","Coaching across churches"],
     ["Unreached peoples strategy","Where the gospel is genuinely new"],
     ["Legacy and long faithfulness","Fields with fruit in decades"]],
    "Can lead network missions strategy and train others.",
    "Two pastors trained; one people group adopted.")]),

R("care","Care & Counseling Pastor","Ministry",
 "Carries people through the worst weeks of their lives.",
 ["Crisis response","Hospital and home visitation","Grief and loss","Counselling and referral","Benevolence","Support groups"],
 "2 Corinthians 1:3-4","Job's friends, who got it right for seven days before they opened their mouths",
 [L([["Presence before answers","The first thing to unlearn"],
     ["Hospital and home visits","What to say and what never to say"],
     ["Grief basics","What is normal and what is not"],
     ["Your limits","Pastoral care is not therapy"],
     ["Building a referral list","Before you need it"]],
    "Can visit, sit with and pray for people in crisis.",
    "Twenty visits completed; referral list built."),
  L([["Crisis response","Death, suicide, accident and violence"],
     ["Funerals and memorials","The highest-stakes preaching there is"],
     ["Benevolence","Helping without enabling"],
     ["Mental health literacy","Signs, language and referral"],
     ["Support groups","Grief, divorce, recovery and caregiving"],
     ["Care teams","Multiplying yourself through volunteers"]],
    "Can lead crisis response and build care teams.",
    "One care team of twelve; six funerals led."),
  L([["Leading a care department","Structure, coverage and on-call"],
     ["Trauma-informed ministry","Doing no further harm"],
     ["Abuse disclosure and mandatory reporting","Protocol, not improvisation"],
     ["Addiction and recovery ministry","Grace without minimizing"],
     ["Caring for staff and leaders","The people nobody cares for"],
     ["Long-term care","After the casseroles stop"]],
    "Can lead a department and handle trauma and disclosure properly.",
    "One protocol authored; one recovery ministry launched."),
  L([["Congregational care systems","Care that scales past one person"],
     ["Training other care pastors","Coaching across churches"],
     ["Clinical partnerships","Working with licensed professionals"],
     ["Community mental health","The church's role in a city"],
     ["Teaching and writing","Turning practice into resource"]],
    "Can train care pastors and build clinical partnerships.",
    "Two pastors trained; one clinical partnership.")]),

R("disciple","Discipleship & Formation Pastor","Leadership",
 "Owns the answer to how someone actually grows in this church.",
 ["The discipleship pathway","Classes and courses","Spiritual practices","Leader development","Assessment and next steps","Curriculum oversight"],
 "2 Timothy 2:2","Jesus and the twelve — three years, in public, with the same people",
 [L([["What discipleship actually is","Beyond attendance and information"],
     ["Mapping your current pathway","Honestly, including the gaps"],
     ["Spiritual practices","Prayer, Scripture, Sabbath, solitude, fasting"],
     ["Teaching adults","How grown-ups actually learn"],
     ["Next steps","Naming one, every time"]],
    "Can describe and teach a basic discipleship pathway.",
    "One pathway map; one class taught."),
  L([["Designing a pathway","Entry to leadership, with visible steps"],
     ["Core classes","Membership, new believers, theology, gifts"],
     ["Curriculum selection and alignment","Fit, theology and sequence"],
     ["Assessment","Where is this person, and what is next"],
     ["Discipleship in groups","The primary environment"],
     ["Measuring formation","Not activity"]],
    "Can design a full pathway with classes and assessment.",
    "One pathway built; four core classes running."),
  L([["Churchwide alignment","Weekend, groups, households and ages on one idea"],
     ["Leader development pipeline","Every seat two deep"],
     ["Campaigns and seasons","Aligned formation across forty days"],
     ["Formation for every stage","New believer to elder"],
     ["Writing your own curriculum","From your own preaching"],
     ["Culture of formation","Beyond programming"]],
    "Can align an entire church around one formation strategy.",
    "One annual alignment plan; one original curriculum."),
  L([["Formation architecture","Designing for a church of any size"],
     ["Training other formation pastors","Coaching across churches"],
     ["Research and measurement","Proving transformation"],
     ["Publishing","Turning a system into a resource"],
     ["Movement thinking","Formation beyond one congregation"]],
    "Can train formation pastors and publish a system.",
    "Two pastors trained; one published pathway.")]),

R("connect","Connections & Assimilation Director","Operations",
 "Makes sure the person who visited once comes back and belongs.",
 ["Guest experience","Follow-up systems","Membership process","Volunteer placement","Data and tracking","Hospitality teams"],
 "Romans 12:13","Barnabas, who took a stranger nobody trusted and vouched for him",
 [L([["The first ninety seconds","Where churches are actually judged"],
     ["Guest experience audit","Walking your own building as a stranger"],
     ["Follow-up that works","Forty-eight hours, and what to say"],
     ["Hospitality teams","Recruiting and training greeters"],
     ["Capturing information","Without making it awkward"]],
    "Can run a guest experience and a follow-up system.",
    "One audit completed; one follow-up system live."),
  L([["The assimilation pathway","Visit to belonging, step by step"],
     ["Membership process","What it is for and how to run it"],
     ["Connecting people to groups","The highest-value handoff"],
     ["Volunteer placement","From interest to serving in three weeks"],
     ["Data and tracking","Knowing who is actually connected"],
     ["The second visit","Where retention is won or lost"]],
    "Can build a full assimilation pathway with tracking.",
    "One pathway built; retention measured for six months."),
  L([["Leading a connections department","Teams, systems and staff"],
     ["Retention analysis","Who stays, who leaves, and why"],
     ["Multi-service and multisite connection","Consistency at scale"],
     ["Reconnecting the drifted","The list nobody works"],
     ["Culture of welcome","Beyond the greeter team"],
     ["Integration with every ministry","Connections is not a department"]],
    "Can lead a department and measurably improve retention.",
    "One retention study; one department plan."),
  L([["Assimilation systems design","For churches of any size"],
     ["Training other directors","Coaching across churches"],
     ["Guest experience consulting","Auditing other churches"],
     ["Research","What actually predicts belonging"],
     ["Publishing","Turning a system into a resource"]],
    "Can consult with other churches on assimilation.",
    "Two directors trained; three churches audited.")]),

R("comms","Communications & Media Director","Operations",
 "Makes sure the right message reaches the right people in time to act.",
 ["Weekend media and slides","Website and app","Email and social","Branding and design","Video production","Internal communication"],
 "Habakkuk 2:2","The scribes of Nehemiah's day, who read clearly and gave the meaning",
 [L([["Communication is stewardship","Not marketing with a cross on it"],
     ["Weekend media","Slides, lower thirds and the run sheet"],
     ["Writing for a congregation","Clear, short and actionable"],
     ["Email and social basics","Cadence over volume"],
     ["Brand consistency","One church, one voice"]],
    "Can run weekend media and a communication calendar.",
    "One brand guide; twelve weeks of clean media."),
  L([["The communication calendar","Announcing less, better"],
     ["Website and digital front door","Where most guests actually visit first"],
     ["Video production basics","Phone-level, done well"],
     ["Storytelling","Testimony as the best content there is"],
     ["Internal communication","Staff and volunteers informed"],
     ["Crisis communication","What to say and how fast"]],
    "Can run an integrated communication strategy.",
    "One calendar built; one crisis plan authored."),
  L([["Leading a communications department","Staff, budget and vendors"],
     ["Campaign communication","Launching a churchwide season"],
     ["Analytics","What people actually open and act on"],
     ["Live production","Streaming, multi-service, multisite"],
     ["Developing volunteers","Photographers, writers and editors"],
     ["Digital discipleship","Content that forms rather than announces"]],
    "Can lead a department and run a churchwide campaign.",
    "One campaign communicated end to end."),
  L([["Communication strategy design","For churches of any size"],
     ["Training other directors","Coaching across churches"],
     ["Production leadership","Original content at scale"],
     ["Brand architecture","Multisite, ministries and sub-brands"],
     ["Teaching and consulting","Beyond one church"]],
    "Can consult with churches on communication strategy.",
    "Two directors trained; one brand architecture built.")]),

R("volunteer","Volunteer & Serving Director","Operations",
 "Turns attenders into servants and keeps them from burning out.",
 ["Recruitment","Placement and onboarding","Training","Retention and honour","Background checks","Team leader development"],
 "Ephesians 4:11-12","The seven chosen in Acts 6 — a real need, a real process, a real appointment",
 [L([["Serving is not volunteering","Redefining the category"],
     ["The ask","Specific, finite and with an end date"],
     ["Onboarding","From yes to serving in three weeks"],
     ["Background checks and safety","Non-negotiable and non-awkward"],
     ["The first serve","Making it a good experience"]],
    "Can recruit, screen and place volunteers.",
    "Twenty volunteers placed; screening process live."),
  L([["The serving pathway","Interest to team leader"],
     ["Training volunteers","Enough to succeed, not enough to overwhelm"],
     ["Retention","Why people quit and what prevents it"],
     ["Honouring well","Specific, public and regular"],
     ["Ministry fair and serving Sundays","Churchwide recruitment"],
     ["Placement by gifting","Fit over slot-filling"]],
    "Can build a serving pathway with training and retention.",
    "One pathway built; one ministry fair run."),
  L([["Leading a serving culture","Beyond a department"],
     ["Team leader development","The layer that scales everything"],
     ["Burnout prevention","Seasons, sabbaticals and boundaries"],
     ["Serving across every ministry","Alignment and shared systems"],
     ["Data and coverage","Knowing where the holes are"],
     ["Volunteers as disciples","Serving as formation"]],
    "Can build a churchwide serving culture and leader pipeline.",
    "One leader pipeline; ninety percent coverage sustained."),
  L([["Serving systems design","For churches of any size"],
     ["Training other directors","Coaching across churches"],
     ["Research","What actually predicts long-term serving"],
     ["Consulting","Auditing other churches"],
     ["Publishing","Turning a system into a resource"]],
    "Can consult and train other serving directors.",
    "Two directors trained; one published system.")]),

R("campus","Campus Pastor","Leadership",
 "Leads one location of a church whose vision is set somewhere else.",
 ["Weekend leadership","Campus staff and volunteers","Local pastoral care","Community presence","Alignment with central","Campus growth and health"],
 "Titus 1:5","Titus, left in Crete to appoint elders in every town and finish what was unfinished",
 [L([["What a campus pastor is","And the tension built into the role"],
     ["Leading a weekend","Everything from the parking lot in"],
     ["Volunteer leadership","Your campus runs on them"],
     ["Local pastoral care","Being the pastor of that room"],
     ["Alignment","Carrying someone else's vision faithfully"]],
    "Can lead a campus weekend and care for its people.",
    "Twelve weekends led; volunteer team built."),
  L([["Campus staff leadership","Hiring, aligning and developing"],
     ["Community presence","Being a church in that neighbourhood"],
     ["Campus health metrics","What to measure locally"],
     ["Local outreach","Contextualized without going rogue"],
     ["Groups and serving at a campus","Full ministry, not a viewing room"],
     ["Managing up","Honest communication with central"]],
    "Can lead a healthy campus with local ministry depth.",
    "One campus plan; one local partnership."),
  L([["Launching a campus","Site, team, timeline and first service"],
     ["Campus growth","From launch to sustainability"],
     ["Preaching at a campus","Live, video and hybrid models"],
     ["Multi-campus leadership","Peer relationships across sites"],
     ["Crisis at a campus","Local response, central support"],
     ["Raising the next campus pastor","From your own campus"]],
    "Can launch a campus and develop the next campus pastor.",
    "One campus launched; one successor developed."),
  L([["Multisite strategy","When, where and whether to expand"],
     ["Systems for many locations","What breaks at five, and at ten"],
     ["Training campus pastors","Across a network"],
     ["Church planting versus campusing","The honest comparison"],
     ["Regional leadership","Overseeing multiple campuses"]],
    "Can design multisite strategy and train campus pastors.",
    "Two campus pastors trained; one expansion plan.")]),

R("ops","Church Operations & Facilities","Operations",
 "Keeps the building, the systems and the logistics working invisibly.",
 ["Facilities and maintenance","Technology and systems","Scheduling and logistics","Safety and security","Vendors and contracts","Event operations"],
 "1 Corinthians 14:40","Bezalel in Exodus 31, filled with the Spirit for craftsmanship and construction",
 [L([["Operations as ministry","Invisible work that makes everything possible"],
     ["Facility basics","Cleaning, maintenance and the walkthrough"],
     ["Room scheduling","The system that prevents most conflicts"],
     ["Safety and security basics","Doors, drills and the team"],
     ["Event setup","Checklists over heroics"]],
    "Can run weekly facility operations and events.",
    "One maintenance schedule; twelve events run."),
  L([["Preventive maintenance","Planned rather than reactive"],
     ["Technology systems","Network, database and integration"],
     ["Security teams","Recruiting, training and protocol"],
     ["Vendor management","Contracts, bids and relationships"],
     ["Capital planning","What breaks in five years"],
     ["Emergency preparedness","Fire, medical, weather and threat"]],
    "Can manage systems, security and preventive maintenance.",
    "One capital schedule; one emergency plan."),
  L([["Leading an operations department","Staff, budget and contractors"],
     ["Building projects","Renovation and construction management"],
     ["Multisite operations","Standards across locations"],
     ["Sustainability and cost","Energy, efficiency and stewardship"],
     ["Space design for ministry","Rooms that serve the work"],
     ["Risk management","Insurance, liability and inspection"]],
    "Can lead a department and manage a building project.",
    "One project completed; one risk audit."),
  L([["Facilities strategy","Ten and twenty year planning"],
     ["Training other operations leaders","Coaching across churches"],
     ["Master planning","Campus design and phased growth"],
     ["Consulting","Auditing other churches"],
     ["Institutional stewardship","Buildings that outlive us"]],
    "Can master-plan a campus and train other operations leaders.",
    "Two leaders trained; one master plan.")]),
]

LEVEL_NAMES = [
 ["Foundation","Beginning","6 weeks","The role, its theology, and the first competencies. Assumes nothing."],
 ["Competence","Intermediate","8 weeks","Doing the job well without supervision. Systems, planning and people."],
 ["Leadership","Advanced","10 weeks","Leading a department, developing others, and handling what goes wrong."],
 ["Multiplication","Expert","12 weeks","Training people beyond your own church, and building what outlives you."],
]
