# -*- coding: utf-8 -*-

SVC_THESIS = ("A pastor spends fifteen hours on twenty-five minutes and about ten minutes on the other thirty-five. "
 "The sermon is the part everyone works on and the service is the part nobody designs. That is the gap, and it is "
 "where the competition is not standing.")

SVC_WHY = [
 ["The sermon is a third of the hour","Twenty-five minutes of seventy. The other forty-five arrive by habit."],
 ["The guest decides before the message","Parking, welcome, the first song and the children's handoff all happen first."],
 ["Transitions are where energy dies","More services are lost in the eleven seconds between elements than in any single element."],
 ["The response is usually an afterthought","The most important ninety seconds of the hour, designed last if at all."],
 ["Everything else is copied","Order of service, song count, announcement placement. Inherited rather than chosen."],
 ["It is the only category we can win","Sermon libraries are crowded. Service design is empty."],
]

ELEMENTS = [
 ["Pre-service","Before anyone speaks",
  ["Countdown and pre-roll","Ambient music and volume","Lighting state","Greeter positions",
   "The lobby as an element","Seating and where people are guided","What is on the screen","When the doors open"],
  "The service starts when the first person walks in, not when the first note plays."],
 ["The Open","The first ninety seconds",
  ["Cold open with music","A spoken welcome first","A call to worship","Scripture read cold",
   "Video open","Silence to begin","A question from the front","Announcement-free opening"],
  "Whatever happens first teaches the room what kind of hour this is. Choose it rather than inherit it."],
 ["Worship in Song","The sung portion",
  ["Set length and song count","Key and congregational range","The order of energy","Where the familiar song sits",
   "Talking between songs, or not","A hymn among modern songs","Spontaneous space","The last song before the message"],
  "Four to five songs. Past six the congregation stops singing and starts watching."],
 ["Scripture Reading","The text, read aloud",
  ["Who reads","Standing or seated","One voice or several","Responsive reading",
   "The whole passage or a portion","Translation choice","Read before or after the songs","Read again before the message"],
  "The most neglected element in modern services and the cheapest to fix."],
 ["Prayer","Corporate praying",
  ["Pastoral prayer","Guided silence","Written prayer read together","Prayer in pairs",
   "Prayer for the city","Prayer over people going out","The Lord's Prayer","A lament"],
  "Corporate prayer that is only a transition has stopped being prayer."],
 ["Giving","The offering moment",
  ["Taught or announced","A story before the ask","No ask at all this week","Impact reported",
   "Digital and physical both","Placement in the order","Who speaks","How long it takes"],
  "The moment most churches handle worst. Teach it four times a year and it stops being awkward."],
 ["Testimony","A congregant speaks",
  ["Live and unscripted","Live and rehearsed","Interview format","Read by the pastor with permission",
   "Three minutes maximum","One story, one point","Where it sits in the order","How it hands off"],
  "The most powerful element available and the one requiring the most preparation."],
 ["The Message","The sermon",
  ["Length","Notes provided or not","One point or several","Where the gospel goes",
   "Interaction or straight delivery","The close","Where the response begins","Handing off afterwards"],
  "Twenty-five to thirty-five minutes. The number matters less than whether it earns its length."],
 ["Response","What happens after the point",
  ["A minute of silence","Prayer at the front","A card or a step","Communion as response",
   "Standing to commit","A named next step","Nothing, deliberately","Prayer teams available"],
  "The ninety seconds that decide whether anything changes. Design it first, not last."],
 ["Communion","The table",
  ["Weekly, monthly or quarterly","Served or come forward","Explained for guests","In families",
   "During worship or alone","Words of institution","Silence around it","Who is invited"],
  "In a room where half do not know what this is, explaining it is not condescension."],
 ["Baptism","Public profession",
  ["In the service or separately","Testimony first","Family involved","How long each takes",
   "Music during","Celebration after","Photographs and permission","The invitation to others"],
  "The best evangelistic moment a church has and often the worst-run."],
 ["Announcements","Information",
  ["How many","Where in the order","Spoken or on screen","Who delivers",
   "Tied to a next step or not","Cut ruthlessly","Print versus platform","The one that matters"],
  "Every additional announcement reduces the impact of all the others."],
 ["The Send","How it ends",
  ["A benediction","A charge","A final song","Silence",
   "One sentence to carry out","The next step repeated","Dismissal","What happens in the lobby after"],
  "The last thing said is the most remembered. Most services end by accident."],
 ["Transitions","The seams",
  ["Who moves and when","Music under or silence","Lighting change","The eleven seconds",
   "Handoff language","Dead air","Walking while talking","Pre-agreed cues"],
  "More energy is lost in transitions than in any single element. Rehearse the seams, not just the parts."],
]

FLOWS = [
 ["The Standard","Most churches, most weeks",
  ["Pre-service","Open","Worship set","Welcome and announcements","Giving","Message","Response","Send"],
  "Works. Familiar. The risk is that nobody ever asks whether it should be different this week."],
 ["Message First","When the text should land cold",
  ["Pre-service","Scripture read cold","Message","Worship as response","Giving","Communion","Send"],
  "Powerful two or three times a year. Everything after the message becomes response rather than preamble."],
 ["Communion Centred","The table as the destination",
  ["Open","Confession","Worship","Scripture","Short message","Communion","Send"],
  "Shorter message, longer table. The oldest shape in the church."],
 ["Testimony Driven","When the story is the point",
  ["Open","Worship","Testimony","Message built on it","Response","Send"],
  "The testimony must come before the message, not after. Otherwise it is an illustration."],
 ["The Guest Service","Easter, Christmas, invite Sunday",
  ["Pre-service","Warm open","Two familiar songs","Explain everything","Short message","Clear next step","Send"],
  "Shorter, warmer, more explained. Cut anything that assumes background."],
 ["The Quiet Service","Grief, crisis or Good Friday",
  ["Silence","Scripture","One song","Lament","Short reflection","Silence","Send without a flourish"],
  "Do not fill the silence. The silence is the service."],
 ["Celebration","Baptism, anniversary, launch",
  ["Loud open","Celebration element","Worship","Story","Short message","Send with joy"],
  "The message is shorter on purpose. The celebration is the content."],
 ["The Send Service","Commissioning, mission, launch",
  ["Open","Worship","The charge","Message","Laying on of hands","Send"],
  "The commissioning is the climax, not an add-on before the last song."],
]

SVC_TYPES = [
 ["Ordinary Sunday","The forty weeks nobody plans","The service that runs when there is no season, no guest push and no campaign. Most churches run this on autopilot for two-thirds of the year."],
 ["Guest Sunday","Easter, Christmas, invite weekends","Everything explained, everything shorter, one clear next step. Cut anything requiring background."],
 ["Campaign Kickoff","Launching a churchwide season","The service that fills groups. The four minutes after the message are the warmest of the year."],
 ["Vision Sunday","Direction and the ask","Once a year, and the whole service points at it. The message is not the vision; the service is."],
 ["Celebration Sunday","Baptism, milestones, anniversary","The celebration is the content. Shorten the message rather than squeezing the celebration."],
 ["Communion Service","The table centred","Shorter message, longer table, more silence."],
 ["Grief or Crisis Sunday","After a death or a public tragedy","Named from the front in the first two minutes. Never proceed as normal and hope."],
 ["Commissioning","Sending people out","Laying on of hands is the climax. Build the hour toward it."],
 ["Family Service","All ages in the room","Shorter, more visual, participation built in. Adults do not resent this if it is done well."],
 ["Prayer Service","When the church gathers to pray","Prayer is the content rather than the transition. Requires an entirely different order."],
 ["Good Friday","The service that should not resolve","Ends in darkness and silence. Do not rescue it with a closing song."],
 ["Christmas Eve","Multiple services, mostly guests","Candles, familiarity and brevity. Twelve-minute message maximum."],
]

DIAG = [
 ["What is the one thing this service is for?",["One clear thing","Two or three","We had not decided","Whatever is on the calendar"]],
 ["Who designs the order each week?",["A team, deliberately","One person, deliberately","It is a template","It has not changed in years"]],
 ["When did you last change the shape of a service?",["This quarter","This year","Over a year ago","I cannot remember"]],
 ["Are transitions rehearsed?",["Every week","Sometimes","Only for big Sundays","Never"]],
 ["Is the response designed before the message is written?",["Always","Sometimes","Afterwards","There is no response"]],
 ["How many announcements last Sunday?",["Two or fewer","Three to four","Five to six","More than six"]],
 ["Does the worship set connect to the message?",["Deliberately, every week","Usually","Occasionally","No"]],
 ["Is Scripture read aloud apart from the sermon text?",["Every week","Most weeks","Rarely","No"]],
 ["Would a guest understand communion and the offering?",["Both explained","One explained","Neither","We assume they know"]],
 ["How does the service end?",["A designed send","A song","Announcements","It just stops"]],
]

BANDS = [
 ["10 to 16","Inherited","Nobody is designing this. Start with one thing: put the response before the message in your planning order, and cut the announcements in half."],
 ["17 to 24","Templated","The shape works and nothing is chosen. Pick four Sundays this year to use a different flow and see what the room does."],
 ["25 to 32","Designed","Most of the hour is intentional. The gaps are usually transitions and the send, which are the cheapest things left to fix."],
 ["33 to 40","Composed","Rare. The next frontier is whether somebody other than you could design a service to this standard, which is a training problem rather than a design one."],
]

SVC_RULES = [
 ["Design the response first","Everything before it is preparation for it. Planning it last guarantees it is thin."],
 ["Name the one thing","One service, one thing. A service with four aims accomplishes none of them and exhausts the room."],
 ["Rehearse the seams","The elements are usually fine. The eleven seconds between them are where it dies."],
 ["Cut one thing every week","There is always one element that is there because it was there last week."],
 ["Explain for the stranger","Communion, the offering, standing, the Bible reference. Assume nothing without being condescending."],
 ["Vary the shape four times a year","A congregation that has experienced only one order for a decade has stopped noticing it."],
 ["Time it honestly","Not the plan, the actual. Record it and compare. Every service runs longer than its planners think."],
 ["End on purpose","The last sentence is the most remembered thing in the hour. Write it."],
]
