# -*- coding: utf-8 -*-
def T(*p): return list(p)

# (name, blurb, hinge, tracks) where tracks = [(trackname_or_None, items)]
CATS = [

("Thanksgiving",
"The one holiday nobody argues about, and a rare open door for gratitude preached as formation rather than sentiment.",
{"roll":"A December generosity arc, or a gratitude practice running to the new year.",
 "give":"Benevolence, food ministry, year-end giving on-ramp.",
 "gospel":"Extended family in town. Preach grace as the reason for gratitude.",
 "act":"Name three people out loud this week and tell them. Begin a written gratitude practice."},
[(None, T(
("Give Thanks in All Circumstances","Gratitude that does not require good news"),
("The One Who Came Back","Luke 17, ten healed, and the ninety percent who kept walking"),
("Count It Out Loud","Why gratitude has to be spoken before it works"),
("Remember What He Has Done","The discipline of rehearsing God's history with you"),
("An Altar of Stones","Building markers so you do not forget"),
("Thanksgiving When the Year Was Hard","Honest gratitude in a bad season"),
("The Empty Seat at the Table","Grief and gratitude in the same room"),
("Enough","Contentment as the root of thanks"),
("Ungratefulness Is a Spiritual Condition","Romans 1 and the first step away from God"),
("First Fruits","Gratitude expressed in what you give away"),
("The Meal That Makes a Family","Table, hospitality, and belonging"),
("Who Set Your Table","Naming the people who got you here"),
("Bless the Lord, O My Soul","Preaching gratitude to yourself"),
("He Gave Thanks Before He Broke It","Jesus, the loaves, and thanks offered before provision"),
("Complaining Is a Habit, Not a Personality","Practical retraining"),
("Harvest","What you are reaping from what someone else planted"),
("Set a Wider Table","Thanksgiving as an invitation to the excluded"),
("Gratitude Rewires You","The formation argument for thanks"),
("Say It to Them","Gratitude that reaches the person, not only God"),
("A Thankful Church","Corporate gratitude as witness"))),]),

("Next Step Sundays",
"The Sundays that move people from attending to following. Three tracks, because a next step means something different depending on where someone is standing.",
{"roll":"A discipleship pathway, a class term, or a testimony series.",
 "give":"Discipleship resources, leader training, curriculum subsidy.",
 "gospel":"Preached as the first step, not assumed as already taken.",
 "act":"One named, dated next step taken before leaving the building."},
[("Discipleship", T(
("Follow Me","The only invitation Jesus ever repeated"),
("What Is a Disciple, Actually?","Definition before decision"),
("Believing Is the Start, Not the Finish","Where most people quietly stop"),
("He Told You the Cost Up Front","Luke 14 and honest recruiting"),
("Come and Die","What Jesus meant, and what he did not"),
("Apprenticed to Jesus","Discipleship as a trade, not a curriculum"),
("You Are Already Being Formed","The only question is by what"),
("Obedience Is the Curriculum","Learning by doing rather than by knowing"),
("The Next Step Is Smaller Than You Think","Removing the intimidation"),
("Who Is Discipling You?","The question nobody asks adults"),
("Habits Beat Intentions","Practices that actually form people"),
("Read It Yourself","Building a first-hand relationship with Scripture"),
("Learn to Pray","Practical instruction rather than inspiration"),
("Give It Away","Generosity as a discipleship marker"),
("Tell Someone","Witness as a stage of growth, not a spiritual gift"),
("Submit to Someone","Accountability and the end of self-direction"),
("The Long Middle","Faithfulness after the excitement wears off"),
("Multiply","When a disciple starts making disciples"),
("What Would Have to Change?","Making the next step concrete"),
("Take One Step Today","A same-day commitment message"))),
("Going Deeper", T(
("Milk and Solid Food","Hebrews 5 and the church's arrested development"),
("You Have Been Here Long Enough","A gentle confrontation"),
("Depth Is Not Complexity","What maturity actually looks like"),
("Study to Show Yourself Approved","The case for real learning"),
("Learn to Read the Bible for Yourself","A practical on-ramp"),
("Theology Is for Everyone","Demystifying the word"),
("The Disciplines Nobody Teaches Anymore","Fasting, solitude, and silence"),
("Fasting","Recovering a practice the modern church dropped"),
("Solitude in a Loud World","Learning to be alone with God"),
("Journaling the Journey","Recording what God is doing"),
("Memorize Something","Scripture in your bones rather than your bookmarks"),
("Serve Where It Costs You","Depth measured in inconvenience"),
("Sit Under Someone Older","Mentorship as a spiritual discipline"),
("Ask the Question You Are Afraid Of","Doubt as a doorway"),
("Sabbath","The discipline that exposes what you actually trust"),
("Confession","The practice that changes everything and nobody does"),
("Generosity as a Discipline","Giving that forms the giver"),
("Review Your Day With God","An ancient practice, simply taught"),
("Read a Whole Book","Scripture in context rather than in fragments"),
("Go Deeper This Season","A specific, time-bound invitation"))),
("Sharing Your Spiritual Story", T(
("You Have a Story","Whether or not it feels dramatic"),
("Before, During, After","The three-part shape of every testimony"),
("Three Minutes","Learning to tell it short"),
("He Told Me Everything I Ever Did","The woman at the well's entire method"),
("I Was Blind, Now I See","John 9 and the power of the simple version"),
("Your Story Is Not About You","Where Jesus enters it"),
("The Boring Testimony Is Still a Testimony","For lifelong church people"),
("Do Not Sanitize It","Honesty is what makes it usable"),
("Where Are You Still in the Middle?","Telling an unfinished story"),
("Write It Down","The exercise that comes before the telling"),
("Practice on Someone Safe","Building the muscle"),
("Answer the Question They Actually Asked","Listening before telling"),
("Give a Reason for the Hope","1 Peter 3, gently and respectfully"),
("Your Scars Are Credentials","Testimony from the healed wound"),
("Tell It at Your Table","Family as the first audience"),
("What God Did This Year","The recent, ongoing testimony"),
("Testimony Sunday","Building an entire service around the stories"),
("Record It","Capturing your story for your children"),
("One Person This Month","A concrete assignment"),
("Stand Up and Say It","A same-day invitation to share"))),]),

("Any Given Sunday",
"Deployable any week of the year, with no seasonal anchor. The drop-in messages for a gap, a guest speaker, or a Sunday that needs to carry itself.",
{"roll":"Anything. That is the design. Each one can front-load a series or stand entirely alone.",
 "give":"General fund, or whatever the current need is.",
 "gospel":"Every message in this category is built to be preachable to someone attending for the first time.",
 "act":"A single clear response, adaptable to whatever the church is currently asking for."},
[(None, T(
("Start Here","A message for anyone walking in cold"),
("Who Do You Say That He Is?","The central question, any week of the year"),
("What Are You Building On?","Foundations, deployable anytime"),
("The Invitation Is Still Open","Grace without an occasion"),
("Come as You Are","The lowest-barrier message in the library"),
("What Would Change If It Were True?","Implications over information"),
("You Are Not Too Far","For anyone who has decided they are"),
("Everybody Worships Something","Identifying the actual object"),
("The Life You Actually Want","Desire, and where it points"),
("God Is Not Angry With You","Correcting the picture people arrive with"),
("Is This All There Is?","Meaning as an entry point"),
("What Are You Carrying?","Burden, and the offer of rest"),
("Second Chances Are the Whole Point","The gospel without a calendar"),
("Nobody Is Doing Fine","Honesty as an evangelistic strategy"),
("The Question Underneath Your Question","Getting to the real issue"),
("Follow Me","Jesus' invitation, any Sunday of the year"),
("It Is Not Too Late","For any decision that feels closed"),
("Why Bother With Church?","Answering the objection directly"),
("One Decision Away","The turning point message"),
("Today","Urgency without manipulation"))),]),

("Communion Sundays",
"Twenty-five ways to stop rushing the table. Most churches spend six minutes on the most theologically dense thing they do all month.",
{"roll":"A season on the cross, the covenant, or church unity. Also the natural companion to Holy Week.",
 "give":"Benevolence collected at the table, following the historic pattern.",
 "gospel":"The table itself preaches. Explain it plainly for the person who has never taken it.",
 "act":"Reconcile with one person before the next communion. Come to the table having done it."},
[(None, T(
("Do This in Remembrance","Why we keep coming back to the table"),
("The Table Is Not Ours","Whose meal this actually is"),
("Broken for You","The specificity of the words"),
("Take, Eat","Obedience in its simplest available form"),
("Judas Was at the Table","Jesus served the man who was selling him"),
("Examine Yourself","1 Corinthians 11 without the fear"),
("Come With Whatever You Brought","The table meets you as you are"),
("Not a Reward for a Good Week","Grace, not merit"),
("The Passover He Fulfilled","Reading Exodus at the table"),
("Until He Comes","The forward-looking half of communion"),
("One Loaf, One Body","Communion as a unity statement"),
("Make Peace Before You Come","Matthew 5 and the altar"),
("The Cup of the New Covenant","What was actually established that night"),
("Communion for the Doubting","For anyone unsure they belong here"),
("Children at the Table","Explaining it to the next generation"),
("The Table in a Divided Church","Communion as reconciliation"),
("Remember, Proclaim, Anticipate","The three tenses of one meal"),
("The Meal That Made a Church","Communion in the earliest congregations"),
("Come Hungry","Longing as the right posture"),
("He Knew and He Served Anyway","Foreknowledge and love at one table"),
("Wider Than You Think","Welcome, boundaries, and who this is for"),
("Communion as Protest","Allegiance to a different kingdom"),
("Bread in Your Hands","The stubborn physicality of grace"),
("What You Are Actually Holding","Slowing the moment all the way down"),
("Do Not Rush This","Making a bigger deal of it, on purpose"))),]),

("Prayer Sundays",
"Services built around praying rather than talking about prayer. The congregation circles up for the church, then each family, then each person.",
{"roll":"A season of prayer, a 21-day prayer emphasis, or the runway into a capital or vision moment.",
 "give":"Prayer ministry, benevolence prayed over and then met.",
 "gospel":"Pray for the people who are not here, by name, out loud.",
 "act":"Circle up before leaving. Pray for the church, then each household, then each person in the circle."},
[(None, T(
("Teach Us to Pray","The only thing the disciples ever asked to learn"),
("A House of Prayer","What Jesus said the building was for"),
("Pray for This Church, By Name","Corporate intercession as the entire service"),
("Circle Up","Praying for each family, then each person in the room"),
("When You Do Not Know What to Say","Romans 8 and the Spirit's help"),
("Pray Without Ceasing","What Paul actually meant by it"),
("Ask, Seek, Knock","Persistence as a form of faith"),
("Four Months of Praying","Nehemiah before he ever picked up a tool"),
("Fasting and Prayer Together","The pairing the church quietly dropped"),
("Praying Scripture","Using God's words when yours run out"),
("Unanswered","Honest theology for the prayers that were not"),
("Praying for Your Family Out Loud","A practice, taught and modeled"),
("The Prayer List Nobody Keeps","Making intercession sustainable"),
("Praying for Those Who Are Not Here","The empty chairs"),
("Corporate Prayer Is Not a Filler","Recovering the practice"),
("He Withdrew to Lonely Places","Jesus' own prayer habit"),
("Praying Together Changes a Church","The congregational case"),
("Lament as Prayer","Bringing the hard thing to God"),
("Thy Kingdom Come","Praying past your own needs"),
("Stay and Pray","An extended, unhurried prayer service"))),]),

("Advent Kickoff",
"The Sunday that launches a 21-day household devotional and decides whether December forms a family or simply exhausts one.",
{"roll":"The 21-day Advent devotional, running to Christmas Eve.",
 "give":"Christmas offering, benevolence, missions.",
 "gospel":"The waiting explained, so the arrival lands.",
 "act":"Every household takes a devotional and starts tonight. Light the first candle at home this week."},
[(None, T(
("Twenty-One Days to Christmas","Launching the season with an actual plan"),
("Advent Means Arrival","Why the church invented this season"),
("Do Not Skip to the Manger","The value of waiting on purpose"),
("Prepare Him Room","Making space before December fills it for you"),
("The Long Wait","Four hundred years, and what they teach us"),
("Hope Has a Name","Week one, standing on its own"),
("Slow Down December","Counter-formation in the busiest month"),
("Light One Candle","Beginning the practice as a household"),
("Keep Awake","Advent's forgotten warning"),
("Prepare the Way","John the Baptist crashes the season"),
("One Family, One Practice","The household on-ramp for twenty-one days"),
("What Are You Waiting For This Year?","Naming the longing out loud"),
("The Prophets Saw It Coming","Setting the biblical stage"),
("A Season Built for the Aching","Advent for the grieving"),
("Two Comings, One Season","Christmas and the return, held together"),
("Start the Devotional Today","A same-day commitment message"),
("December Will Form You","The only question is what into"),
("O Come, O Come, Emmanuel","Singing the longing before the answer"),
("Waiting Is Not Wasting","A theology of the in-between"),
("The Best Christmas in Years","Casting vision for the whole season"))),]),

("Lent Kickoff",
"The Sunday that gives Easter a runway. Forty days of preparation, launched from the platform rather than assumed.",
{"roll":"A 40-day Lenten devotional and a Holy Week arc ending at Resurrection Sunday.",
 "give":"Fast-and-give: the cost of what is given up, redirected to a named need.",
 "gospel":"Repentance preached as invitation, not as performance.",
 "act":"Choose one thing to lay down and one thing to take up. Write both down before you leave."},
[(None, T(
("Forty Days to Easter","Launching the season with a plan"),
("Remember You Are Dust","The most freeing sentence in the church calendar"),
("Lent for People Who Do Not Do Lent","A practical entry point"),
("Give Something Up, Gain Something Better","Fasting as addition"),
("Forty Days in the Wilderness","Why Jesus began his ministry hungry"),
("Return to Me","Joel's call, and a God who runs toward repentance"),
("A Season for Subtraction","Making room by making less"),
("Rend Your Heart","The difference between sorrow and show"),
("What Are You Hungry For?","Appetite as a spiritual diagnostic"),
("The Desert Is Not a Detour","Wilderness as formation"),
("Easter Needs a Runway","Why we prepare at all"),
("Forty Days to Honest","Using the season to stop pretending"),
("Pick One Thing","Making the commitment small enough to keep"),
("Secret Giving, Secret Praying, Secret Fasting","Matthew 6 and the audience of One"),
("Confession Is a Gift","Naming it so it loses its grip"),
("The Slow Walk to the Cross","Reading the passion over six weeks"),
("Sackcloth and Smartphones","Ancient repentance in a distracted age"),
("What Would You Notice If It Were Quiet?","Silence as a practice"),
("From Ashes to Glory","The arc of the whole season in one message"),
("Start Today","A same-day commitment message"))),]),

("Vision Sunday",
"The single most consequential message a senior pastor preaches all year, and the one most often written last.",
{"roll":"The annual ministry plan, the budget year, and every campaign that follows it.",
 "give":"The annual commitment, faith-promise, or capital ask.",
 "gospel":"Vision defined by who is not here yet keeps the mission from becoming maintenance.",
 "act":"A written, signed commitment card taken today, not mailed later."},
[(None, T(
("Where We Are Going","The annual vision message"),
("Without Vision, People Scatter","Proverbs and the cost of drift"),
("Write the Vision, Make It Plain","Habakkuk on clarity"),
("One Church, One Direction","Alignment as a spiritual act"),
("What God Is Asking of Us This Year","Corporate calling, stated plainly"),
("The Next Twelve Months","Specific, dated, and measurable"),
("We Cannot Do This Without You","The congregational ask"),
("He Surveyed the Wall First","Nehemiah, and honest assessment before vision"),
("Build the Section in Front of You","Every family taking a piece of the wall"),
("What We Will Say No To","Focus as strategy"),
("The Church We Want to Be in Five Years","Long-horizon casting"),
("Count the Cost With Me","Honest about what this will require"),
("Who Is Not Here Yet","Vision defined by the missing"),
("From Attenders to Owners","The shift a church has to make"),
("Your Part Is Not Optional","Every member, named"),
("Faith Requires a Number","Making the vision concrete"),
("Let Us Rise Up and Build","Nehemiah's rallying line"),
("This Is Why We Exist","Mission restated without jargon"),
("What Would We Attempt","Faith-sized goals, honestly examined"),
("Commit With Me Today","The same-day response"))),]),

("New Year's Sunday",
"Low attendance, high leverage. The people who show up on the first Sunday of January are the ones who will carry the year.",
{"roll":"A January discipleship or generosity campaign, and the group-launch semester.",
 "give":"First-fruits commitment for the year ahead.",
 "gospel":"Fresh start preached as gospel rather than as self-improvement.",
 "act":"One word, one habit, one relationship, chosen and written down today."},
[(None, T(
("New Year, Same God","Stability when the calendar turns"),
("Forgetting What Is Behind","Paul on moving forward without denial"),
("Resolutions Fail. Repentance Works.","The difference that lasts past February"),
("One Word for the Year","A discipline simple enough to keep"),
("Numbering Our Days","Psalm 90 at the turn of the year"),
("The God of New Things","Isaiah 43 and genuine fresh starts"),
("Redeeming the Time","Stewardship of the year in front of you"),
("Fresh Start for the Failed Start","For anyone who has broken this promise before"),
("What Do You Want True Next December?","Working backward from the end"),
("Not Everyone Starts January Excited","Grace for the discouraged"),
("The Habits That Will Build You","Small practices, long obedience"),
("Clear the Deck","What to stop doing this year"),
("Where Did Last Year Go?","Honest review before any planning"),
("Choose Your Company","Who you walk with decides where you arrive"),
("Make One Change","Focus over ambition"),
("New Every Morning","Lamentations at the turn of the year"),
("The Year You Stop Waiting","Acting on what you already know"),
("Plan Like a Steward","Goals held under providence"),
("Do Not Do This Alone","Accountability from day one"),
("Begin Again","The invitation the gospel never stops offering"))),]),

("Serve Sunday",
"A churchwide serving initiative built on Better Together. Not a food drive with a sermon attached, but a Sunday where everybody serves somebody.",
{"roll":"A multi-week serving season, culminating in a citywide day and a testimony Sunday afterward.",
 "give":"Project supplies, benevolence, and the partner organizations being served.",
 "gospel":"Serving alongside someone is the lowest-barrier front door a church has.",
 "act":"Sign up for a project before you leave, and bring one person who does not attend here."},
[(None, T(
("Everybody Serves Somebody","The churchwide challenge, stated once and clearly"),
("More Than a Food Drive","Serving that actually costs something"),
("Better Together","The frame for the whole initiative"),
("He Took a Towel","Leadership according to the God who washed feet"),
("The Church Leaves the Building","Serving as public witness"),
("Whatever You Did for the Least of These","Matthew 25 preached plainly"),
("Your City Is Your Parish","Adopting a neighborhood rather than a cause"),
("One Saturday Changes a Street","Concrete and measurable"),
("Serving Is Not Volunteering","Redefining the category"),
("Faith Without Works","James, without the guilt trip"),
("Find the Need in Front of You","Proximity over program"),
("He Was Late for Something","The Good Samaritan and interruption as ministry"),
("Bring Your Family","Serving as household formation"),
("What You Do for One","Scale was never the point"),
("Serve Before You Believe","Belonging through doing"),
("Every Skill Is Usable","Monday's work applied on Saturday"),
("The Ministries That Need You","The internal call to serve"),
("Do Not Serve Alone","Teams over individuals"),
("Sign Up Before You Leave","The same-day mechanic"),
("Come Back and Tell Us","Closing the loop with testimony"))),]),

("Connection Sunday",
"A service engineered to launch groups during the weekend itself rather than hoping people follow up on Tuesday.",
{"roll":"The group semester, launched from the platform with signup happening in the room.",
 "give":"Host-home support, curriculum, and leader training.",
 "gospel":"Belonging before believing. Name it as the strategy, not the compromise.",
 "act":"Register in the service, meet your group in the lobby, first gathering this week."},
[(None, T(
("Connect Before You Leave","The same-service group launch"),
("Ten Years and Never Known","The honest problem, named from the platform"),
("From the Row to the Circle","Making the move today"),
("Nobody Grows in a Crowd","The case, made briefly"),
("Six Weeks. One Room.","The finite ask"),
("The Lobby Is the Front Door","Designing connection into the service itself"),
("Who Would Notice If You Stopped Coming?","The diagnostic question"),
("Say Yes to a Table","Lowering the barrier as far as it goes"),
("Belonging Comes First","Belong, then believe, then behave"),
("Open House This Week","The mechanic, announced from the platform"),
("Too Big to Do Alone","Reframing what size costs you"),
("Find Three People","The minimum viable community"),
("They Devoted Themselves","Acts 2 preached at the launch"),
("It Only Takes One Yes","Removing the deliberation"),
("What Is Actually Stopping You?","Naming the objections out loud"),
("Groups Are Not for Extroverts","Addressing the real fear"),
("You Are Closer Than You Think","Encouragement for the hesitant"),
("New Here? Start Here.","The guest-specific path"),
("Register Today, Meet Thursday","Urgency with an actual date"),
("The Room That Will Change Your Year","Vision for what a group does"))),]),

("Pair Up and Group Up",
"The four-week challenge. People map their relational circles with the 5 F exercise, then gather in twos or in a living room, starting with an open house.",
{"roll":"A four-week micro-group season that feeds directly into the full group semester.",
 "give":"Open-house hosting kits and starter curriculum.",
 "gospel":"The open house is the invitation. Neighbors and coworkers come to a home before they come to a building.",
 "act":"Complete the 5 F exercise in the service, name one person, host or attend an open house this week."},
[(None, T(
("Each One Reach One","The four-week challenge"),
("Pair Up for Four Weeks","The simplest possible commitment"),
("Who Is on Your List?","The 5 F exercise, completed during the service"),
("Map Your Circles","Naming the people already around you"),
("Open Your Home Once","Hosting an open house, not leading a study"),
("Two Is a Group","Removing the size requirement"),
("Four Weeks Is Not Forever","The finite frame"),
("Start With a Meal","The lowest-barrier gathering there is"),
("Everybody Knows Somebody","Removing the excuse before it forms"),
("You Do Not Have to Teach","Separating hosting from leading"),
("Andrew Brought His Brother","The biblical pattern for this exact ask"),
("The Person Sitting Next to You","Connecting inside the service"),
("Text One Person Right Now","The same-service mechanic"),
("Come to the Open House","The specific, dated invitation"),
("Four Weeks, Four Conversations","The shape of the commitment"),
("Two Are Better Than One","Ecclesiastes on the math"),
("What If It Is Awkward?","Naming the fear and moving anyway"),
("Who Discipled You?","Motivating the pay-it-forward"),
("Multiply After Four Weeks","Building the next round in from the start"),
("Say Yes Before You Leave","The same-day commitment"))),]),

("Church at Home",
"The household as the first congregation. For a snow week, a scattered season, or a deliberate strategy to move formation off the campus.",
{"roll":"A household discipleship series, or a home-based campaign running alongside weekend services.",
 "give":"Home discipleship kits, family devotionals, table resources.",
 "gospel":"Neighbors will enter a living room long before they enter a sanctuary.",
 "act":"One household practice chosen and started this week. One neighbor invited to the table this month."},
[(None, T(
("Church at Home","The household as the first congregation"),
("The Home Is the First Church","Where discipleship primarily happens"),
("They Broke Bread in Their Homes","Acts 2 and the living room"),
("As for Me and My House","Joshua's declaration, applied this week"),
("Lead Your Family in One Thing","A single achievable practice"),
("When You Sit and When You Walk","Deuteronomy 6 inside a modern house"),
("The Table Is an Altar","Meals as formation"),
("A Liturgy for Your Living Room","Practical rhythms for a household"),
("Your Home Has a Culture","Building it on purpose rather than by accident"),
("Sunday Is Not Enough","The honest math of one hour a week"),
("Teach Your Children to Pray","Simple, practical instruction"),
("What They Actually Learn From You","Modeling over instruction"),
("A Household of One","Church at home for singles"),
("Read One Chapter Together","The smallest possible start"),
("The Snow Day Church","When the building is closed"),
("Leading From a Distance","Grandparents and long-range household discipleship"),
("Bless Your Children Out Loud","The practice, taught and modeled"),
("Make Sunday Start Saturday Night","Preparing to gather"),
("Invite the Neighbors In","Home as the outreach venue"),
("Start This Week","The same-day household commitment"))),]),

("Ask Sundays",
"Twenty ways to make a clear ask without apologizing for it. Most churches ask badly, late, and only for money.",
{"roll":"Whatever campaign, capital effort, or recruitment season the ask serves.",
 "give":"The ask itself, named specifically and without euphemism.",
 "gospel":"Generosity as response to grace, never as leverage or obligation.",
 "act":"A written, dated commitment turned in before leaving."},
[(None, T(
("We Need You to Say Yes","The general ask, framed honestly"),
("Count the Cost With Me","Transparent about what it will require"),
("Give Until It Reorders Something","The sacrificial ask"),
("We Cannot Do This Without You","The congregational appeal"),
("He Made the Ask Plainly","Nehemiah, and biblical precedent for asking"),
("What Would It Take?","Naming the specific number out loud"),
("The Building Is Not the Point","Capital campaign framing"),
("Fill the Gap","A specific, named shortfall"),
("Everyone Gives Something","Participation over amount"),
("Pray First, Then Decide","The process, not the pressure"),
("Two Small Coins","Proportion over size"),
("Serve One Slot","The volunteer ask"),
("Open Your Home","The hosting ask"),
("Lead a Group","The leadership ask"),
("Bring One Person","The invitation ask"),
("Give a Year","The commitment ask"),
("Sponsor a Family","The named-outcome ask"),
("Go","The missions ask"),
("Stay and Finish","The endurance ask"),
("Here Is Exactly What We Are Asking","Clarity as a form of respect"))),]),

("Ministry Launch Sundays",
"Fifty ministries, fifty launch messages. Every ministry a church starts dies or thrives based on the Sunday that introduces it.",
{"roll":"Each launches its own ministry season, with a sign-up table and a first meeting inside two weeks.",
 "give":"Startup costs, leader training, childcare for the new ministry.",
 "gospel":"Most of these ministries reach people the weekend service never will.",
 "act":"Sign up at the table today. First gathering within fourteen days, or momentum is gone."},
[(None, T(
("You Are Not the Only One","Launching a support group ministry"),
("Fight For It, Not With Each Other","Launching a marriage ministry"),
("Ours, Yours, and God's","Launching a blended family ministry"),
("Whole, Not Waiting","Launching a singles ministry"),
("Iron Sharpens Iron","Launching a men's ministry"),
("Together, Not Alone","Launching a women's ministry"),
("Room for the Grieving","Launching a grief and loss ministry"),
("One Day, One Room, One Step","Launching a recovery ministry"),
("After the Worst Year","Launching a divorce care ministry"),
("Every Child Needs a Yes","Launching a foster and adoption ministry"),
("Everybody Belongs Here","Launching a special needs ministry"),
("It Is Okay to Not Be Okay","Launching a mental health ministry"),
("Free From What Owns You","Launching a financial stewardship ministry"),
("Between Jobs, Not Between Callings","Launching a career transition ministry"),
("Twenties Are Not a Waiting Room","Launching a young adults ministry"),
("Faith That Survives the Campus","Launching a college ministry"),
("More Than a Youth Group","Launching a student ministry"),
("The Church at Four Feet Tall","Launching a children's ministry"),
("Foundations Before Memory","Launching a preschool and early childhood ministry"),
("Nobody Trained You for This","Launching a parenting ministry"),
("When the Rules Change","Launching a parents of teens ministry"),
("The Chapter After the Kids","Launching an empty nesters ministry"),
("Finishing Strong","Launching a senior adults ministry"),
("The Ministry Nobody Sees","Launching a caregivers ministry"),
("After the Empty Chair","Launching a widows and widowers ministry"),
("Carrying It All","Launching a single parents ministry"),
("The Grief With No Funeral","Launching an infertility and loss ministry"),
("A House of Prayer","Launching a prayer ministry"),
("Go","Launching a global missions ministry"),
("Your City Is Your Parish","Launching a local outreach ministry"),
("Nobody Here Goes Without","Launching a benevolence ministry"),
("Nobody Is Too Far","Launching a prison and reentry ministry"),
("A Place to Land","Launching a housing and homelessness ministry"),
("Welcome the Stranger","Launching a refugee and immigrant ministry"),
("Monday Is Ministry","Launching a marketplace and business leaders ministry"),
("Serving Those Who Serve","Launching a military and first responder ministry"),
("Play as an Open Door","Launching a sports and recreation ministry"),
("Making Beauty for God","Launching a creative arts ministry"),
("Lead Us","Launching a worship team ministry"),
("The First Ninety Seconds","Launching a hospitality and guest services ministry"),
("You Are More Ready Than You Think","Launching a small group leader ministry"),
("Who Is Discipling You?","Launching a discipleship and mentoring ministry"),
("Brothers in the Fight","Launching a men's accountability ministry"),
("Free, and Staying Free","Launching an addiction and sobriety ministry"),
("Not an Afterthought","Launching a health and wellness ministry"),
("Couples Who Made It","Launching a marriage mentoring ministry"),
("Before You Say Yes","Launching a premarital ministry"),
("From Guest to Family","Launching a newcomer and assimilation ministry"),
("Send Us","Launching a church planting and multiplication ministry"),
("Find Your Place","Launching a volunteer and serving team ministry"))),]),
]
