# -*- coding: utf-8 -*-
def T(*p): return list(p)

# (name, explainer, experience, hinge, tracks)
CATS = [

("21-Day Challenges",
"Three weeks is the shortest span in which a person can feel a habit stop being effort. Twenty-one days is long enough to change something and short enough that a congregation will actually finish, which is why it outperforms both the seven-day sprint and the forty-day campaign for pure behavior change.",
"Give every person a physical tracker on day one &mdash; a card with twenty-one boxes, not an app. Mount a wall in the lobby where people add a mark each Sunday, so by week three the congregation can see the whole church's progress in one glance. End with the wall photographed and printed in the bulletin.",
{"roll":"Each challenge runs three weeks and lands on a Celebration Sunday where people report what happened.",
 "give":"Tracker cards, challenge guides, and whatever the challenge itself serves.",
 "gospel":"Formation preached as grace-driven response, never as spiritual performance.",
 "act":"Take the tracker, commit publicly, and name the person who will ask you about it."},
[("21 Days of Prayer", T(
("Twenty-One Days of Prayer","Launching the church's most important three weeks"),
("Teach Us to Pray","Starting exactly where the disciples started"),
("The Prayer Room Is Open","Making space for it, physically"),
("Pray First","Reordering the day around it"),
("Go Into Your Room","Matthew 6 and the private practice"),
("Pray for Your City","Three weeks of intercession aimed outward"),
("Pray for Your Family By Name","The household focus"),
("Fasting Alongside It","The pairing that intensifies everything"),
("Praying Scripture for Three Weeks","Using God's words when yours run out"),
("The Prayer List That Lasts","Building something sustainable"),
("He Prayed for Four Months","Nehemiah and endurance in intercession"),
("Ask Boldly","Removing the false humility"),
("Pray Until Something Happens","Persistence without formula"),
("The Midnight Friend","Luke 11 and shameless asking"),
("Praying Through Lament","Bringing the grief honestly"),
("Twenty-One Days of Listening","The half of prayer we skip"),
("Every Morning, Together","The church gathered daily for three weeks"),
("Praying for the Prodigal","Three weeks aimed at one person"),
("Write Down the Answers","Recording what God actually does"),
("What Changed in Twenty-One Days","The closing testimony Sunday"))),
("21 Days of Service", T(
("Twenty-One Days of Serving Somebody","The challenge, launched"),
("One Act a Day","Small, daily, and sustainable"),
("Serve Your Household First","Starting where you actually live"),
("Serve a Neighbor You Do Not Know","Proximity as mission"),
("The Towel Challenge","Three weeks of foot-washing leadership"),
("Look for the Need in Front of You","Attention as a spiritual practice"),
("Serve Someone Who Cannot Repay You","Luke 14, applied literally"),
("Twenty-One Days of Invisible Service","Nobody knows, and that is the point"),
("Give Away an Hour","Time as the harder currency"),
("Serve With Your Family","Making it a household practice"),
("Adopt a Street","Three weeks in one place"),
("Serve Someone You Disagree With","The hardest version of the challenge"),
("Interrupted on Purpose","The Good Samaritan challenge"),
("Serve Your Church","The internal call, for three weeks"),
("Twenty-One Encouragements","Words as service"),
("Feed Someone","The simplest possible act"),
("Show Up for the Grieving","Presence as the whole assignment"),
("Serve Until It Costs You","Week three and the real test"),
("Who Served You?","Gratitude built into the challenge"),
("What Twenty-One Days Did","The closing testimony Sunday"))),
("21 Days of Storytelling", T(
("Twenty-One Days of Telling Your Story","The challenge, launched"),
("Write It Down First","Days one through three"),
("Three Minutes, Out Loud","Practicing the short version"),
("Tell It to Your Family","The first and hardest audience"),
("Tell One Person a Day","The daily assignment"),
("Ask Someone for Theirs","Listening is half the practice"),
("The Story You Have Not Told","Naming what you keep leaving out"),
("He Told Me Everything I Ever Did","The Samaritan woman's entire method"),
("I Was Blind, Now I See","The version nobody can argue with"),
("Where God Showed Up This Year","The recent, ongoing testimony"),
("Record One for Your Children","Legacy as the outcome"),
("Tell It Without the Christian Words","Translating for people outside"),
("Who Discipled You","Honoring the chain you are part of"),
("Tell the Middle, Not Just the End","Unfinished stories count"),
("Twenty-One Days of Noticing","Collecting material daily"),
("Ask, Then Listen","Story as conversation rather than speech"),
("Your Scars Have a Testimony","The healed wound, spoken"),
("Post One, Send One, Speak One","Three channels, three weeks"),
("Collect Your Family's Stories","Interviewing the older generation"),
("Testimony Sunday","The closing celebration"))),
("21 Days of Family Life", T(
("Twenty-One Days of Family Life","The household challenge, launched"),
("Eat Together Every Night","The simplest habit with the deepest effect"),
("Twenty-One Days of Blessing Your Children","Words spoken out loud, daily"),
("Pray Together Before Bed","The daily rhythm"),
("Read One Chapter as a Family","Scripture at the table"),
("Put the Phones in a Basket","Attention as a form of love"),
("Twenty-One Days of No Criticism","Retraining the tone of a household"),
("Ask One Real Question a Day","Beyond how was your day"),
("Serve Somebody as a Family","Mission at household scale"),
("Twenty-One Days of Sabbath Practice","Rest as a family value"),
("Tell Your Kids Your Story","Testimony inside the home"),
("Apologize First","Modeling repentance for three weeks"),
("Twenty-One Days of Marriage Attention","Prioritizing the foundation"),
("Reclaim One Hour","Screens off at dinner"),
("Call the Grandparents","Three generations, three weeks"),
("One Specific Word, Every Day","Encouragement as a practice"),
("Make Home the Safest Room","Emotional safety as a discipline"),
("Have the Hard Conversation","The one you keep postponing"),
("Build One Family Tradition","Culture created on purpose"),
("What Changed at Home","The closing testimony Sunday"))),]),

("Celebration Sundays",
"The last weekend of any series, redesigned so the congregation arrives with something to say rather than something to hear. A church that never asks people to report what happened teaches them, without meaning to, that nothing was supposed to.",
"Announce it three weeks out and take actual signups, so people prepare rather than volunteer nervously in the moment. Cap each story at ninety seconds and coach them beforehand. Then close in the water or at the table &mdash; a baptism or a communion service is a far better ending to a series than a summary sermon.",
{"roll":"Closes one series and launches the next by naming what the church will take on together.",
 "give":"Thanking the givers by showing outcomes rather than making a new ask.",
 "gospel":"Testimony is the most persuasive preaching a guest will ever hear.",
 "act":"Sign up to tell your story, and name one person you will bring to the next series."},
[(None, T(
("Tell Us What Happened","The closing weekend of any series"),
("What Did God Do in You?","The testimony prompt, given three weeks early"),
("Bring Your Story","Preparation announced well ahead"),
("Stones of Remembrance","Building a marker for what happened here"),
("They Came Back to Say Thank You","The one leper out of ten"),
("Six Weeks Later","Measuring what actually changed"),
("Testimony Is the Best Preaching","Handing the platform over on purpose"),
("What You Did With the Devotions","Reporting on the daily work"),
("What Changed at Work","Vocational testimony"),
("What Changed at Home","Household testimony"),
("What Changed in My Walk With God","Personal testimony"),
("Our Story, Not Just Mine","Corporate celebration"),
("Open Mic, Structured and Timed","Ninety seconds each, prepared in advance"),
("Close It in the Water","Baptism as the celebration"),
("Close It at the Table","Communion as the celebration"),
("Write It on the Wall","A physical record of what God did"),
("Now Do Not Stop","Momentum past the last week"),
("Who Are You Bringing Next Time?","Multiplication built into the celebration"),
("Celebrate the Ones Who Served","Honoring leaders, hosts, and volunteers"),
("Mark This Day","Making the ending memorable on purpose"))),]),

("Challenge Sunday",
"A universal launch message for any challenge a church wants to run at seven, ten, or twenty-one days. The content changes; the psychology does not, which is why one well-built launch structure serves every challenge you will ever call.",
"Do the signing in the room. Cards in the seats, pens in the seats, everyone writes and signs during the service, then walks the card forward and drops it in a basket at the front. A commitment carried out of the building in a pocket is a commitment abandoned by Wednesday.",
{"roll":"Whatever challenge follows &mdash; 7, 10, or 21 days &mdash; ending in a Celebration Sunday.",
 "give":"Challenge guides, trackers, and the cause the challenge serves.",
 "gospel":"Obedience framed as response to grace, with explicit room for the ones who will miss days.",
 "act":"Sign the card in the service and hand it in before you leave."},
[(None, T(
("Take the Challenge","The generic launch message"),
("Seven Days Will Not Kill You","Lowering the barrier all the way down"),
("Ten Days to Change One Thing","The mid-length ask"),
("Twenty-One Days Makes It Yours","The habit-length ask"),
("Pick One Thing","Focus over ambition"),
("What Would Change If You Actually Did It?","Obedience over intention"),
("Do Not Do This Alone","Accountability built in from day one"),
("Start Today, Not Monday","Removing the delay that kills it"),
("He Took a Ten-Day Challenge","Daniel, and the biblical precedent"),
("Write It Down and Sign It","The commitment card moment"),
("You Will Want to Quit on Day Four","Naming the wall in advance"),
("Small and Daily Beats Big and Occasional","The formation argument"),
("Tell Somebody You Are Doing It","Public commitment as fuel"),
("What Are You Willing to Try?","The invitational frame"),
("The Challenge Is Not the Point","Formation is"),
("Grace for the Days You Miss","Preventing the shame spiral"),
("Take It as a Family","The household version"),
("Take It as a Group","The group version"),
("Report Back","Building the celebration in from the start"),
("Say Yes Before You Leave","The same-day commitment"))),]),

("Fasting Sundays",
"Ten messages on the discipline the modern church quietly dropped. Jesus said when you fast, not if, and most congregations have never once been taught how.",
"Break the fast together. Schedule the end of a corporate fast for a Sunday evening meal in the building, tables set, everyone eating at once. People will remember the meal for a decade, and the meal is what makes the fast make sense.",
{"roll":"A corporate fast of three, seven, or twenty-one days, ending at a shared table.",
 "give":"Redirect the cost of what is not eaten to a named benevolence or hunger need.",
 "gospel":"Emptiness as the condition in which people finally hear.",
 "act":"Choose the fast, name the length, tell one person, and put the broken-fast meal on the calendar."},
[(None, T(
("When You Fast","Jesus assumed you would"),
("Not by Bread Alone","The first temptation and the appetite underneath it"),
("Fasting Is Not a Hunger Strike","Correcting the transactional view"),
("What Are You Actually Hungry For?","Appetite as a spiritual diagnostic"),
("The Fast God Chooses","Isaiah 58, and justice as fasting"),
("Fast From More Than Food","Screens, noise, comfort, and opinion"),
("Fasting and Prayer Together","The pairing the church dropped"),
("Fasting as a Church","Corporate fasting, explained and scheduled"),
("What Surfaces When You Are Empty","Fasting as exposure"),
("Break It at the Table","Ending the fast together"))),]),

("The Challenge Hundred",
"One hundred messages engineered to become a seven or ten day challenge, each with its companion daily content named up front &mdash; a devotional, a testimony, a teaching, or a training. This is the working inventory a church draws from all year when it wants to move people rather than inform them.",
"Rotate the companion type on purpose. A week of devotionals forms differently than a week of ninety-second testimony videos from people in the congregation, and a training week &mdash; where each day asks for a skill practiced rather than a passage read &mdash; produces the highest completion rate of the three. Pick the companion to match what you want changed.",
{"roll":"Any short challenge, standalone or as the on-ramp to a longer campaign.",
 "give":"Daily content production, and the cause each challenge serves.",
 "gospel":"Each challenge is short enough that a not-yet-believing spouse or friend will do it alongside someone.",
 "act":"Choose your challenge and your companion track today, then start tomorrow morning."},
[("Spiritual Habits", T(
("Seven Days of Silence","7-day &middot; daily teaching &middot; learning to hear God in a loud life"),
("Ten Days in the Psalms","10-day &middot; daily devotional &middot; praying the emotions you have"),
("Seven Days of Praying First","7-day &middot; daily devotional &middot; reordering the morning"),
("Ten Days Without Complaining","10-day &middot; daily training &middot; retraining the reflex"),
("Seven Days of Sabbath Practice","7-day &middot; daily teaching &middot; rest as trust"),
("Ten Days of Scripture Memory","10-day &middot; daily training &middot; one verse, built in"),
("Seven Days of Solitude","7-day &middot; daily devotional &middot; alone on purpose"),
("Ten Days of Gratitude","10-day &middot; daily devotional &middot; naming it out loud"),
("Seven Days of Confession","7-day &middot; daily teaching &middot; the practice nobody does"),
("Ten Days of Early Mornings","10-day &middot; daily training &middot; the hour before everyone wakes"),
("Seven Days of Worship at Home","7-day &middot; daily devotional &middot; the living room as sanctuary"),
("Ten Days of Journaling","10-day &middot; daily training &middot; recording what God does"),
("Seven Days Off the Screen","7-day &middot; daily teaching &middot; fasting from the feed"),
("Ten Days of Listening Prayer","10-day &middot; daily devotional &middot; the half we skip"),
("Seven Days in One Gospel","7-day &middot; daily teaching &middot; reading a whole book"),
("Ten Days of Reviewing the Day","10-day &middot; daily training &middot; an ancient practice, simply taught"),
("Seven Days of Slowing Down","7-day &middot; daily devotional &middot; hurry as the enemy"),
("Ten Days of Obedience in One Thing","10-day &middot; daily testimony &middot; the thing you already know"),
("Seven Days of Saying Yes","7-day &middot; daily testimony &middot; availability as a discipline"),
("Ten Days of Practicing His Presence","10-day &middot; daily devotional &middot; God in the ordinary"))),
("Home and Relationships", T(
("Seven Days of Eating Together","7-day &middot; daily devotional &middot; the table as formation"),
("Ten Days of Blessing Your Children","10-day &middot; daily training &middot; words they keep for fifty years"),
("Seven Days of No Criticism","7-day &middot; daily training &middot; changing the household tone"),
("Ten Days of Marriage Attention","10-day &middot; daily devotional &middot; the foundation, prioritized"),
("Seven Days of Apologizing First","7-day &middot; daily teaching &middot; repair as a skill"),
("Ten Days of Praying for Your Spouse","10-day &middot; daily devotional &middot; specific and daily"),
("Seven Days of Undivided Attention","7-day &middot; daily training &middot; presence over presents"),
("Ten Days of Forgiving One Person","10-day &middot; daily teaching &middot; the slow work"),
("Seven Days of Family Prayer","7-day &middot; daily devotional &middot; the simplest household rhythm"),
("Ten Days of Honoring Your Parents","10-day &middot; daily testimony &middot; the commandment, applied"),
("Seven Days of Encouraging Your Kids","7-day &middot; daily training &middot; one specific word a day"),
("Ten Days of Reconciliation","10-day &middot; daily teaching &middot; going first"),
("Seven Days of Phones in a Basket","7-day &middot; daily training &middot; reclaiming the meal"),
("Ten Days of Listening Better","10-day &middot; daily training &middot; the underrated skill"),
("Seven Days of Serving Your Household","7-day &middot; daily devotional &middot; starting where you live"),
("Ten Days of Speaking Life","10-day &middot; daily devotional &middot; the tongue, retrained"),
("Seven Days of Hard Conversations","7-day &middot; daily teaching &middot; the one you keep postponing"),
("Ten Days of Rebuilding Trust","10-day &middot; daily teaching &middot; after it broke"),
("Seven Days of Family Worship","7-day &middot; daily devotional &middot; singing at home"),
("Ten Days of Grandparent Legacy","10-day &middot; daily testimony &middot; three generations deep"))),
("Character and Freedom", T(
("Seven Days of Telling the Truth","7-day &middot; daily teaching &middot; including the small ones"),
("Ten Days Without Anger","10-day &middot; daily training &middot; the reflex, examined"),
("Seven Days of Humility","7-day &middot; daily devotional &middot; going last on purpose"),
("Ten Days of Guarding Your Eyes","10-day &middot; daily training &middot; practical and unshaming"),
("Seven Days of Integrity in Private","7-day &middot; daily teaching &middot; when nobody is watching"),
("Ten Days Free From Comparison","10-day &middot; daily devotional &middot; putting the phone down"),
("Seven Days Without Gossip","7-day &middot; daily training &middot; harder than it sounds"),
("Ten Days of Contentment","10-day &middot; daily devotional &middot; enough as a decision"),
("Seven Days of Facing the Fear","7-day &middot; daily testimony &middot; the thing you avoid"),
("Ten Days of Staying Sober","10-day &middot; daily testimony &middot; one day at a time, together"),
("Seven Days of Patience","7-day &middot; daily training &middot; in traffic and at home"),
("Ten Days of Laying Down Control","10-day &middot; daily devotional &middot; surrender as practice"),
("Seven Days of Self-Control","7-day &middot; daily teaching &middot; the fruit nobody wants"),
("Ten Days of Healthy Boundaries","10-day &middot; daily training &middot; saying no without guilt"),
("Seven Days of Rest Without Guilt","7-day &middot; daily devotional &middot; permission, theologically"),
("Ten Days of Courage","10-day &middot; daily testimony &middot; one brave thing a day"),
("Seven Days of Owning Your Part","7-day &middot; daily teaching &middot; the end of blame"),
("Ten Days of Renewing Your Mind","10-day &middot; daily devotional &middot; what you feed it"),
("Seven Days of Caring for Your Body","7-day &middot; daily training &middot; stewardship, not vanity"),
("Ten Days of Breaking One Habit","10-day &middot; daily training &middot; specific and measurable"))),
("Generosity and Stewardship", T(
("Seven Days of Giving Something Away","7-day &middot; daily devotional &middot; one thing a day"),
("Ten Days of Honest Budgeting","10-day &middot; daily training &middot; looking at the actual numbers"),
("Seven Days of Contentment","7-day &middot; daily devotional &middot; wanting what you have"),
("Ten Days of Debt-Free Planning","10-day &middot; daily training &middot; the first real plan"),
("Seven Days of Generous Words","7-day &middot; daily devotional &middot; generosity that costs nothing"),
("Ten Days of Giving First","10-day &middot; daily teaching &middot; order of operations"),
("Seven Days of Buying Nothing","7-day &middot; daily training &middot; the fast you feel"),
("Ten Days of Financial Honesty","10-day &middot; daily testimony &middot; telling the truth about money"),
("Seven Days of Anonymous Giving","7-day &middot; daily devotional &middot; Matthew 6, literally"),
("Ten Days of Simplifying","10-day &middot; daily training &middot; less as freedom"),
("Seven Days of Giving Your Time","7-day &middot; daily devotional &middot; the harder currency"),
("Ten Days of Stewarding Your Work","10-day &middot; daily teaching &middot; Monday as ministry"),
("Seven Days of Gratitude for Provision","7-day &middot; daily devotional &middot; counting what came"),
("Ten Days of Planning Your Legacy","10-day &middot; daily teaching &middot; past your own lifetime"),
("Seven Days of Giving It Up","7-day &middot; daily testimony &middot; the thing that owns you"),
("Ten Days of Family Money Conversations","10-day &middot; daily training &middot; talking about it at home"),
("Seven Days of Investing in People","7-day &middot; daily devotional &middot; the only lasting asset"),
("Ten Days of Wise Decisions","10-day &middot; daily teaching &middot; counsel before commitment"),
("Seven Days of Open Hands","7-day &middot; daily devotional &middot; holding it all loosely"),
("Ten Days of Sowing Generously","10-day &middot; daily testimony &middot; the harvest logic"))),
("Mission and Witness", T(
("Seven Days of Praying for One Person","7-day &middot; daily devotional &middot; one name, seven mornings"),
("Ten Days of Learning Your Neighbors' Names","10-day &middot; daily training &middot; proximity as mission"),
("Seven Days of Telling Your Story","7-day &middot; daily training &middot; three minutes, practiced"),
("Ten Days of Serving Your City","10-day &middot; daily testimony &middot; showing up where you live"),
("Seven Days of Inviting Someone","7-day &middot; daily training &middot; the ask, rehearsed"),
("Ten Days of Praying for the Nations","10-day &middot; daily devotional &middot; a country a day"),
("Seven Days of Noticing the Overlooked","7-day &middot; daily devotional &middot; seeing before serving"),
("Ten Days of Hospitality","10-day &middot; daily training &middot; the door and the table"),
("Seven Days of Encouraging Strangers","7-day &middot; daily devotional &middot; one person a day"),
("Ten Days of Workplace Witness","10-day &middot; daily teaching &middot; without being strange about it"),
("Seven Days of Listening to Someone's Story","7-day &middot; daily training &middot; asking, then waiting"),
("Ten Days of Loving Your Enemy","10-day &middot; daily teaching &middot; the hardest instruction"),
("Seven Days of Practical Compassion","7-day &middot; daily devotional &middot; help that helps"),
("Ten Days of Praying for Your School","10-day &middot; daily devotional &middot; teachers, students, by name"),
("Seven Days of Being Interruptible","7-day &middot; daily devotional &middot; margin as mission"),
("Ten Days of Building One Friendship","10-day &middot; daily training &middot; slow and deliberate"),
("Seven Days of Answering Gently","7-day &middot; daily teaching &middot; 1 Peter 3 in practice"),
("Ten Days of Missional Living","10-day &middot; daily training &middot; ordinary life, on purpose"),
("Seven Days of Blessing Your Block","7-day &middot; daily testimony &middot; one street, one week"),
("Ten Days of Going","10-day &middot; daily testimony &middot; the step you have been avoiding"))),]),

("Impact Sundays",
"Twenty-five messages that report rather than ask. Most churches only talk about money when they need it, which trains a congregation to brace every time the subject comes up. An Impact Sunday reverses that reflex by showing what the last gift actually did before asking for the next one.",
"Bring the outcome into the room. Not a video &mdash; the actual person, the actual family, the teacher from the school you adopted, standing on the platform for ninety seconds. Hand every giver a card with one name and one sentence on it: this is who your giving reached this year. People do not remember a percentage. They remember a face.",
{"roll":"Sets up the next vision or generosity season by establishing credibility first.",
 "give":"No ask. That is the design. The ask comes the following month and lands harder for it.",
 "gospel":"The people served tell their own stories, which preaches better than any appeal.",
 "act":"Take the card, read the name, pray for that person this week."},
[(None, T(
("What Difference Are We Making?","The honest measurement question"),
("Count What Matters","Metrics beyond attendance and giving"),
("One Hundred Families Changed","Reporting the year in human terms"),
("Your Giving Did This","Showing the outcome instead of the need"),
("The City Noticed","External impact as witness"),
("Impact Is a Person, Not a Number","Grounding every report in one story"),
("Where Your Offering Went","Radical transparency Sunday"),
("Salt and Light in This Zip Code","Local impact framing"),
("What If We Were Not Here?","The question that clarifies everything"),
("The Ripple You Cannot See","Long-range impact"),
("From This Church to the Nations","The global report"),
("Every Number Has a Name","Humanizing the data"),
("This Is What Your Serving Did","The volunteer impact report"),
("The Church That Blessed Its City","Vision told through outcome"),
("Twelve Months of Faithfulness","The annual impact message"),
("Multiplied, Not Added","Impact through the people we sent away"),
("We Fed, We Housed, We Sat With","Naming the specific work"),
("Impact Beyond the Building","Monday through Saturday"),
("The Ones You Will Meet Later","Eternal impact, framed carefully"),
("Report and Rejoice","Impact as worship rather than marketing"),
("What Ten Dollars a Week Did","Small giving, aggregated and shown"),
("The Least of These Have Names","Matthew 25, with faces"),
("Impact Takes Time","Patience for slow fruit"),
("What We Will Do Next","Impact as the runway into vision"),
("Thank You, Church","Honoring the congregation that did it"))),]),

("Bible Reading Challenge Sundays",
"Twenty-five ways to launch a reading plan, including the ones that address why the last four attempts failed. Most reading-plan sermons assume enthusiasm; the useful ones assume a congregation that has quit before and needs a different on-ramp.",
"Hand out physical Bibles, not links &mdash; the same edition to everyone, so a congregation is literally on the same page. Put a bookmark in it at the starting chapter. Then designate one Sunday mid-plan as an amnesty week: everyone who fell behind starts again together, publicly and without embarrassment, which is the single highest-leverage thing a church can do for completion rates.",
{"roll":"A churchwide reading plan running a season, a quarter, or the full year.",
 "give":"Bibles for the congregation and for a school, prison, or partner church.",
 "gospel":"Give a Bible away to someone outside the church as part of the challenge.",
 "act":"Take the Bible, open to the first chapter before you leave the parking lot."},
[(None, T(
("Read the Bible This Year","The annual launch"),
("Start With One Gospel","The beginner's on-ramp"),
("Twenty Minutes a Day","Making the math feel achievable"),
("You Have Tried This Before","Grace for the failed attempts"),
("Read It in Community","The group reading plan"),
("What to Do When You Hit Leviticus","Naming the wall in advance"),
("A Story, Not a Rulebook","Reframing before the first page"),
("Read It Out Loud","The ancient practice, recovered"),
("Listen Instead","Audio Scripture for the commute"),
("One Chapter of Proverbs a Day","The simplest possible plan"),
("The Psalms for the Hard Year","Reading for the season you are actually in"),
("The Whole Bible in Ninety Days","The intensive challenge"),
("One Book, Thirty Times","Depth instead of breadth"),
("Memorize While You Read","Adding retention to the plan"),
("Journal What You Read","The practice that makes it stick"),
("Read It as a Family","The household plan"),
("What About the Hard Parts?","Handling difficult texts honestly"),
("Read Until It Reads You","Formation over information"),
("The Bible in a Year, Together","The churchwide campaign"),
("Study One Book Deeply","The inductive method, simply taught"),
("Read What Jesus Read","The Old Testament through his eyes"),
("Fall Behind and Keep Going","Amnesty week, preventing the quit"),
("Give Someone a Bible","Reading as an outward act"),
("What You Read Changed You","The mid-plan testimony"),
("Finish It","The end-of-year celebration"))),]),
]
