# -*- coding: utf-8 -*-
def E(t, sub): return [t, sub]
def C(n, sub, why, when, tools, addins, notes, passages, ee): 
    return {"n":n,"sub":sub,"why":why,"when":when,"tools":tools,"addins":addins,
            "notes":notes,"pas":passages,"ee":ee}

THESIS = ("A pastor faces more unchurched people at a wedding and a funeral than at any other moment in his ministry, "
 "with forty-eight hours to prepare and no library anywhere. This is the largest gap in Christian publishing and "
 "nobody has filled it.")

WHY = [
 ["The room is not hostile, it is unfamiliar","Nobody at a graveside is arguing with you. Most of them simply have no category for what is happening."],
 ["Forty-eight hours, sometimes twelve","A sermon has a week. A funeral has a phone call on Tuesday and a service on Thursday."],
 ["It is the highest-stakes preaching a pastor does","A family will remember what you said at their mother's funeral for thirty years, word for word, accurately or not."],
 ["Nobody sells help for it","Search any sermon site for a funeral for a child. You will find almost nothing, and what you find is generic."],
 ["It is repeat business a church never plans for","Weddings and funerals are how families first meet a church and how they decide whether to come back."],
]

CATS = [

C("The Wedding Homily","Eight minutes that the couple will remember",
 "Most wedding homilies are too long, too general and aimed at the couple when half the room needs them more.",
 "Any wedding. This is the default set.",
 ["Eight-minute homily builder","Ceremony run sheet","Vow options with theology notes","Officiant script with rubrics","Timing sheet for the whole service"],
 ["Printed order of service template","Couple's keepsake copy of the homily","Guest card with the marriage blessing","Anniversary follow-up letter at year one"],
 "Keep it under eight minutes. Address the couple by name at least twice, and the room at least once. The gospel goes in without an altar call.",
 ["Genesis 2:18-25","Ecclesiastes 4:9-12","1 Corinthians 13:4-8","Ephesians 5:21-33","Colossians 3:12-14"],
 [E("Covenant, Not Contract","The distinction the whole ceremony rests on"),
  E("The First Miracle Was at a Wedding","John 2, and a God who came to a party"),
  E("Love Is Patient, Read Honestly","1 Corinthians 13 rescued from the greeting card"),
  E("A Cord of Three Strands","Why two is not enough"),
  E("Leave and Cleave","The two verbs that make a household"),
  E("It Was Not Good to Be Alone","The first thing God called not good"),
  E("Submit to One Another","Ephesians 5, read from verse twenty-one"),
  E("Clothe Yourselves","Colossians 3 as a wedding text"),
  E("The Charge to the Couple","What to say that they will still remember"),
  E("For Better, For Worse","The vow nobody thinks about until later"),
  E("Two Become One","What the phrase actually means"),
  E("A House Built on Rock","Matthew 7 at a wedding"),
  E("Love as Christ Loved","The standard nobody meets and everyone needs"),
  E("The Ring and the Promise","A symbol explained for a room that does not know"),
  E("Bear With Each Other","The unglamorous verse that saves marriages"),
  E("Who Gave Their Blessing","Honouring the families in the room"),
  E("What We Are Witnessing","Explaining the witnesses' role"),
  E("Forgiveness Is the Whole Skill","The one thing to master"),
  E("Until Death Parts Us","Taking the ending seriously at the beginning"),
  E("Go in Peace","The benediction, written short")]),

C("Premarital Preparation","The work before the day",
 "Most couples get four sessions about a wedding and none about a marriage. This is the material that changes the odds.",
 "Six to twelve weeks before the wedding, four to six sessions.",
 ["Six-session premarital guide","Couple assessment with scoring","Family-of-origin worksheet","Money conversation guide","Conflict style inventory"],
 ["Couple's workbook, print-ready","Mentor couple leader notes","Homework between sessions","Six-month post-wedding check-in"],
 "Never do fewer than four sessions. If a couple will not do the work, that is information. Refer to a licensed counsellor when anything clinical appears.",
 ["Genesis 2:24","Proverbs 24:3-4","1 Corinthians 7:1-7","Ephesians 5:25-33","1 Peter 3:7"],
 [E("Why We Do This","What premarital counselling is actually for"),
  E("Your Family of Origin","What you are bringing that you cannot see"),
  E("Expectations, Named","The assumptions nobody says out loud"),
  E("How You Fight","Conflict style before there is conflict"),
  E("Money Before the Wedding","The fight underneath the fight"),
  E("Roles and Decisions","Who decides what, agreed in advance"),
  E("Sex, Honestly","Handled plainly, without evasion"),
  E("In-Laws","The relationship nobody plans for"),
  E("Children, or Not","The conversation to have before, not after"),
  E("Work and Ambition","Two careers and one household"),
  E("Faith at Home","What your household will actually practise"),
  E("Friendship","The part that has to survive everything else"),
  E("Communication Skills","Practised, not discussed"),
  E("Repair","How you come back after a bad week"),
  E("Community","Who will hold this marriage up"),
  E("The Wedding Is One Day","Keeping perspective on the event"),
  E("What Would Make This Fail","Working backward from divorce"),
  E("Blended Family Preparation","When children are already here"),
  E("Second Marriage","What is different and what is not"),
  E("Your First Year","What to expect and what to do about it")]),

C("Vows, Ceremony & Liturgy","The words and the shape of the service",
 "Most pastors improvise or reuse a ceremony they inherited. Neither serves a couple who will keep the recording forever.",
 "Any wedding. Choose the elements, then build the order.",
 ["Ceremony builder with element library","Three vow sets with theology notes","Declaration and pronouncement options","Unity symbol scripts","Full officiant script, print-ready"],
 ["Printed ceremony booklet","Rehearsal run sheet","Musician and reader cue sheet","Signing and legal checklist"],
 "Read every word aloud before the day. Know how to pronounce every name. Have a printed copy even if you never look at it.",
 ["Genesis 2:24","Ruth 1:16-17","Song of Songs 8:6-7","1 Corinthians 13","Colossians 3:14"],
 [E("The Welcome","Setting the room in ninety seconds"),
  E("Why We Are Here","The statement of purpose"),
  E("The Giving and Blessing","Honouring parents without awkwardness"),
  E("Traditional Vows","The historic words and why they endure"),
  E("Written Vows","Guidance for couples writing their own"),
  E("Modern Vows","Contemporary language that still means something"),
  E("The Exchange of Rings","The symbol, explained briefly"),
  E("Unity Candle","When it works and when it does not"),
  E("Communion at a Wedding","How to handle a mixed room"),
  E("Handfasting and Cord of Three","Symbols with real history"),
  E("Foot Washing","The most powerful and least used option"),
  E("Scripture Readings","Twelve options with a note on each"),
  E("Prayer for the Couple","Written out, three lengths"),
  E("The Declaration","The legal moment, said well"),
  E("The Pronouncement","The line everyone waits for"),
  E("The Kiss and the Presentation","Getting the ending right"),
  E("The Benediction","Sending them out"),
  E("A Very Short Ceremony","Fifteen minutes, complete"),
  E("An Outdoor Ceremony","What changes and what to prepare"),
  E("A Courthouse or Small Ceremony","Six people and a purpose")]),

C("Complicated Weddings","The ones nobody has material for",
 "Second marriages, blended families, estranged parents, a divided faith, a pregnancy, a deployment. Most weddings have at least one.",
 "When the situation is not simple, which is most of the time.",
 ["Situation triage guide","Difficult conversation scripts","Family seating and honouring plan","Modified ceremony elements","Pastoral boundary framework"],
 ["Family communication template","Children's participation guide","Blended-family blessing script","Pre-ceremony family meeting agenda"],
 "Meet the difficult family member before the day, not at the rehearsal. Decide in advance what you will and will not say from the front.",
 ["Ruth 1:16-17","Romans 15:7","Ephesians 4:32","Colossians 3:13","1 Corinthians 13:7"],
 [E("A Second Wedding","Grace and honesty at a remarriage"),
  E("When Children Are in the Room","Blending two households publicly"),
  E("The Blended Family Blessing","Words for children at a wedding"),
  E("Estranged Parents","Seating, honouring and what not to say"),
  E("A Divided Family","When half the room is not speaking"),
  E("One Believer, One Not","Handled with integrity and warmth"),
  E("Different Traditions","Two faiths, two cultures, one ceremony"),
  E("After a Divorce","Naming the past without dwelling in it"),
  E("After a Death","When a first spouse is remembered"),
  E("A Very Young Couple","Pastoral care alongside the ceremony"),
  E("An Older Couple","Second half of life, first marriage or not"),
  E("Already Living Together","How to handle it pastorally"),
  E("A Pregnancy","Celebrating without pretending"),
  E("A Deployment or Departure","Marrying under a clock"),
  E("Illness in the Family","When someone may not be there long"),
  E("A Small Budget","Dignity without expense"),
  E("A Rushed Timeline","Two weeks, done well"),
  E("Family Who Disapprove","Ministering to everyone in the room"),
  E("A Couple You Have Concerns About","When to say something and how"),
  E("When You Cannot Officiate","Declining with love and without judgement)")]),

C("After the Wedding","The first year nobody prepares for",
 "A church spends months on the wedding and disappears the week after. The first year is where marriages are actually formed.",
 "Weeks one to fifty-two after the ceremony.",
 ["First-year check-in schedule","Mentor couple pairing guide","Six-month conversation guide","Anniversary letter templates","Newlywed group curriculum"],
 ["Thirty-day follow-up card","Six-month coffee invitation","First anniversary letter from the pastor","Newlywed household devotional, 21 days"],
 "Book the six-month conversation before the wedding. Couples say yes in advance and decline afterwards.",
 ["Deuteronomy 24:5","Ecclesiastes 4:12","Ephesians 4:2-3","Colossians 3:12-17","1 Peter 4:8"],
 [E("The Week After","When the guests leave and the marriage starts"),
  E("The First Fight","Normal, and what to do with it"),
  E("Merging Two Households","Practical and emotional"),
  E("Money in Month One","The systems conversation"),
  E("In-Laws at Christmas","The first holiday negotiation"),
  E("Your Friends Now","How friendships change"),
  E("Faith at Home","Establishing one household rhythm"),
  E("The Six-Month Conversation","The check-in that catches things early"),
  E("Sex in the First Year","Expectations and reality"),
  E("Work and Time","Two calendars, one life"),
  E("When One Travels","Distance in the first year"),
  E("The First Anniversary","Marking it deliberately"),
  E("Mentor Couples","Who is walking with you"),
  E("A Newlywed Group","Six sessions for the first year"),
  E("When It Is Harder Than Expected","Permission to say so"),
  E("Getting Help Early","Counselling as maintenance, not crisis"),
  E("Building Your Traditions","Deciding rather than defaulting"),
  E("Serving Together","The habit that binds"),
  E("Children Sooner Than Planned","Adjusting the first year"),
  E("Year One Review","What worked and what to change")]),

C("The Funeral Message","The hardest twenty minutes a pastor preaches",
 "Grief, truth and hope in one message, for a room where half the people have never been in a church.",
 "Any funeral. This is the default set.",
 ["Funeral message builder","Family interview guide","Eulogy versus sermon framework","Order of service with timings","Committal words, three lengths"],
 ["Printed order of service template","Memory card for guests","Family keepsake booklet","Two-week follow-up letter"],
 "Twelve to eighteen minutes. Say the person's name often. Preach the gospel briefly and without an altar call. Never speculate about eternal destiny.",
 ["Psalm 23","John 11:25-26","John 14:1-6","Romans 8:38-39","1 Thessalonians 4:13-18"],
 [E("A Funeral for a Believer","Grief and confidence, held together"),
  E("Reading Psalm 23 Well","The most-requested text, done with care"),
  E("I Am the Resurrection","John 11 as the centre of the service"),
  E("Do Not Let Your Hearts Be Troubled","John 14 for a frightened family"),
  E("Nothing Can Separate Us","Romans 8 read slowly"),
  E("We Do Not Grieve as Those Without Hope","1 Thessalonians 4, honestly"),
  E("A Long Life Well Lived","When someone finished well"),
  E("A Life Cut Short","When they did not"),
  E("Jesus Wept","Permission to grieve, from God himself"),
  E("The Last Enemy","Naming death as an enemy, not a friend"),
  E("Where Is God in This","The question the room is asking"),
  E("What We Believe About Heaven","What Scripture actually promises"),
  E("The Body in the Ground","Talking about resurrection plainly"),
  E("A Funeral for Someone You Are Not Sure About","Honesty without false comfort"),
  E("When You Did Not Know Them","Preaching a stranger's funeral"),
  E("Eulogy Versus Sermon","Knowing which you were asked for"),
  E("The Family Wants a Story","Weaving memory into the message"),
  E("Twelve Minutes","A short funeral message, complete"),
  E("The Room Is Full of People Who Never Come","Preaching to them without ambushing them"),
  E("Go in Peace","The closing words")]),

C("Hard Deaths","The services nobody has material for",
 "A child, a suicide, an accident, a young parent, a violent death. These need different words and almost nobody has written them.",
 "When the death is not the natural end of a long life.",
 ["Triage guide by type of death","What never to say, by situation","Family meeting agenda for a hard death","Care team activation checklist","Referral list template"],
 ["Sibling and children's support card","Congregational communication template","Anniversary-of-death follow-up","Support group invitation"],
 "Never speculate. Never explain. Never say it was God's plan. Sit with the family longer than is comfortable and say less than you think you should.",
 ["Psalm 34:18","Psalm 88","Lamentations 3:19-24","Romans 8:26","Revelation 21:4"],
 [E("A Funeral for a Child","The hardest forty-eight hours of a pastor's life"),
  E("A Death by Suicide","Care, truth and no speculation"),
  E("A Sudden Death","When there was no goodbye"),
  E("A Young Parent","Speaking to children who are present"),
  E("A Violent Death","Anger in the room, named"),
  E("An Overdose","Dignity and honesty together"),
  E("A Stillbirth or Infant Loss","The grief nobody names"),
  E("A Miscarriage","A service most churches never offer"),
  E("A Long Illness","When everyone is exhausted and relieved"),
  E("Dementia","Grieving someone who left before they died"),
  E("An Accident","When it could have been avoided"),
  E("A Death Far From Home","Memorial without a body"),
  E("A Missing Person","A service with no ending"),
  E("An Estranged Family Member","When the grief is complicated"),
  E("Someone Who Left the Faith","Handled with love and integrity"),
  E("A Death in the Congregation","When the church is grieving too"),
  E("Multiple Deaths","One family, more than one loss"),
  E("A Public Death","When the news is already covering it"),
  E("What Never to Say","The sentences that do damage"),
  E("Sitting in the Silence","When there is nothing to say")]),

C("Graveside & Committal","Ten minutes in the cold",
 "Short, exposed and unforgettable. Most pastors have never been taught how to do this well.",
 "At the cemetery, before or after the service.",
 ["Committal words, three lengths","Graveside order with timings","Weather and logistics checklist","Military and fraternal honours guide","Scattering and interment scripts"],
 ["Printed committal card for the family","Graveside handout","Directions and logistics sheet","Cemetery liaison checklist"],
 "Under ten minutes, whatever the weather. Stand where the family can see you. Know who lowers the casket and when.",
 ["Genesis 3:19","Job 1:21","Psalm 90:1-2","John 11:25","1 Corinthians 15:42-44"],
 [E("Earth to Earth","The traditional committal, explained"),
  E("A Short Committal","Six minutes, complete"),
  E("A Very Short Committal","Three minutes in bad weather"),
  E("Ashes to Ashes","Cremation and committal"),
  E("Scattering Ashes","Words for an unusual place"),
  E("A Burial at Sea","Rare and worth having ready"),
  E("A Military Funeral","Honours, folding and what you say around them"),
  E("A Veteran's Committal","Working with an honour guard"),
  E("Fraternal Rites","When another group has a part"),
  E("A Child's Graveside","The hardest ten minutes there is"),
  E("A Family Plot","Words when others are already there"),
  E("An Unmarked Grave","Dignity without resources"),
  E("Winter Graveside","Cold, short and warm"),
  E("A Large Crowd Outside","Logistics and voice"),
  E("A Private Family Committal","Six people, no service"),
  E("Delayed Burial","When months have passed"),
  E("The Sound of the Soil","Whether to invite the family to participate"),
  E("The Last Words","What you say before you walk away"),
  E("Staying After","The five minutes that matter most"),
  E("Leaving Well","How to end without hurrying them")]),

C("Memorial & Celebration of Life","When the service is not a funeral",
 "Increasingly common, often months later, frequently in a venue rather than a church, and pastorally different from a funeral.",
 "Weeks or months after the death, or when there is no body.",
 ["Memorial service builder","Open-mic management guide","Slideshow and music guidance","Venue and logistics checklist","Speaker briefing template"],
 ["Printed memorial programme","Memory table and guest book plan","Speaker time-card","Family thank-you template"],
 "Manage the open microphone or it will manage you. Brief every speaker on time, and have somebody ready to close it gracefully.",
 ["Psalm 116:15","Ecclesiastes 7:2","2 Timothy 4:7","Hebrews 12:1","Revelation 14:13"],
 [E("A Celebration of Life","Joy and grief in the same room"),
  E("Months Later","When time has passed and grief has not"),
  E("A Memorial Without a Body","When there is nothing to bury"),
  E("In a Venue, Not a Church","Leading worship in a rented room"),
  E("Managing the Open Microphone","The most common way these go wrong"),
  E("Briefing the Speakers","Three minutes, one story, no lists"),
  E("The Slideshow","How to make it help rather than hurt"),
  E("Music They Loved","Handling secular music pastorally"),
  E("A Life Well Lived","Honouring without eulogising into fiction"),
  E("A Complicated Life","Honest honour for a difficult person"),
  E("Someone Outside the Faith","Ministering to the family with integrity"),
  E("A Very Large Memorial","Hundreds of people, one message"),
  E("A Very Small One","Eight people in a living room"),
  E("A Community Loss","When a town is grieving"),
  E("For a Church Member of Fifty Years","Congregational grief"),
  E("For a Staff Member","When the church has lost one of its own"),
  E("Children Present","Making room for them"),
  E("The Memory Table","Objects, photographs and story"),
  E("The Gospel, Briefly","Twelve sentences, no altar call"),
  E("Sending Everyone Home","The close that lets people leave")]),

C("After the Funeral","When everyone else stops calling",
 "The casseroles stop at two weeks. Grief runs for years. The follow-up is where a church either becomes their church or does not.",
 "Two weeks to two years after the death.",
 ["Grief follow-up schedule","Anniversary and milestone calendar","Grief group curriculum, eight sessions","Care team assignment sheet","Widow and widower support guide"],
 ["Fourteen-day follow-up letter","Three-month check-in card","First anniversary letter","Holiday grief guide for the family"],
 "Put the first anniversary in the calendar the week of the funeral. Nobody else will remember it and the family will remember that you did.",
 ["Psalm 34:18","Isaiah 61:1-3","2 Corinthians 1:3-4","1 Thessalonians 5:14","Revelation 21:4"],
 [E("Fourteen Days Later","The call that makes the difference"),
  E("When the Casseroles Stop","Naming the second wave of grief"),
  E("The First Christmas","The hardest holiday"),
  E("The First Birthday","Their birthday, without them"),
  E("The Anniversary","One year, and who remembers"),
  E("Grieving a Spouse","The particular loneliness of it"),
  E("Grieving a Child","Grief that does not follow a timeline"),
  E("Grieving a Parent","Becoming the older generation"),
  E("Children Grieving","What is normal at each age"),
  E("Complicated Grief","When to refer and to whom"),
  E("Anger at God","Making room for it"),
  E("Guilt and What-If","The questions that will not stop"),
  E("Sorting Their Things","The practical grief nobody mentions"),
  E("Returning to Church","Why some people cannot"),
  E("A Grief Group","Eight sessions, and who should run it"),
  E("Widows and Widowers","Ongoing care beyond the first year"),
  E("Remarriage After Loss","Pastoral care for a new season"),
  E("The Second Year","Often harder than the first"),
  E("When They Are Ready to Serve","Grief that becomes ministry"),
  E("Remembering Together","An All Saints or memorial Sunday")]),
]
