# Four new collections for the master library: (title, subtitle) tuples, 100 each.

FELLOWSHIP = [
("Better Together","Why we were made for each other"),
("Life Together","The beauty of biblical community"),
("You Belong","Finding your place in the family of God"),
("Never Alone","The antidote to loneliness"),
("Do Life Together","Moving from rows to relationships"),
("Known","Fully seen and fully loved"),
("One Another","Living out the New Testament commands"),
("The Family of God","Living as brothers and sisters"),
("Find Your People","Building a circle of faith"),
("Belong Here","A place for everyone"),
("Circles","Why we need each other"),
("Come to the Table","Where everyone fits"),
("Rooted in Relationship","Growing through community"),
("Real Friends","Friendships that go deeper"),
("Show Up","The power of being there"),
("Bear One Another's Burdens","Carrying each other"),
("Doing Life","Sharing faith and everyday life"),
("Connected","Building relationships that matter"),
("The Church Family","Belonging to something bigger"),
("Welcome Home","A place to belong"),
("Open Doors","Practicing radical hospitality"),
("Around the Table","Fellowship over a meal"),
("Devoted","The fellowship of the early church"),
("Koinonia","The deep sharing of life in Christ"),
("Together","Growing in community, not alone"),
("No One Walks Alone","A church where you're known"),
("Closer","From surface to depth"),
("The Gathering","Why we come together"),
("Held by Community","Strength in one another"),
("Friends for the Journey","Companions in the faith"),
("Small Groups, Big Life","Growing in circles of faith"),
("Get in a Group","Doing life in community"),
("The Welcome Table","Hospitality that includes everyone"),
("Real & Known","Authentic community that heals"),
("We Need Each Other","Made for connection, not isolation"),
("Better in Circles","Community that changes you"),
("Come Together","Uniting as the body of Christ"),
("Your Place","Where you're seen, known, and loved"),
("Side by Side","Walking together in faith"),
("The Company We Keep","Friendships that shape your faith"),
("Iron Sharpens Iron","Growing through each other"),
("Fellowship of the Broken","Grace in community"),
("All In Together","Committed to one another"),
("Gather","The rhythm of coming together"),
("The Table Is Open","Everyone's welcome here"),
("Belonging","Finding your place in the church"),
("Community That Sticks","Bonds that last"),
("Woven Together","The tapestry of the church"),
("Doing Faith Together","Growing side by side"),
("The One-Anothers","Loving as Jesus commanded"),
("Hospitality","Opening your life to others"),
("A Seat at the Table","Room for one more"),
("Companions","Walking the journey together"),
("The Fellowship","Deep community in Christ"),
("Stronger Together","A church that leans in"),
("Friendship & Faith","Growing closer to God and each other"),
("Life on Life","Discipleship through relationship"),
("Do Life With Us","An invitation to community"),
("Not Meant to Be Alone","The gift of community"),
("Bound Together","United in Christ"),
("Belonging Before Believing","A welcome for everyone"),
("The Gathered Church","Why we assemble"),
("Shared Life","Living out koinonia"),
("In It Together","Facing life as a family"),
("The Body","Every member connected"),
("Held Together","Community that carries you"),
("Come as You Are","A church for everyone"),
("Table Talk","Faith and friendship over a meal"),
("Closer Together","Deepening our bonds"),
("The Beloved Community","Living as God's family"),
("Woven In","Belonging to the body of Christ"),
("Every Member","No one on the outside"),
("Together in Christ","United by the gospel"),
("The Circle","Where faith grows in community"),
("Deep Roots, Close Friends","Growing together"),
("A Place to Belong","The gift of the church family"),
("Journey Together","Faith is not a solo trip"),
("The Shared Table","Fellowship at its best"),
("Us","The church as family"),
("All Together","United in worship and life"),
("Do Community","Living connected lives"),
("Neighbors in the Faith","Growing side by side"),
("The Family Table","Belonging in God's household"),
("Locked Arms","Standing together in Christ"),
("Faith & Friendship","Better in community"),
("Around the Fire","Warmth of Christian fellowship"),
("Come In","An open door to belonging"),
("The Warmth of Welcome","Hospitality in the church"),
("Together We Grow","Community that matures faith"),
("Not Alone in This","Bearing life together"),
("The Gathering Place","Where the church becomes family"),
("Shoulder to Shoulder","Walking together in faith"),
("Communion","Sharing life in Christ"),
("One Body","Many members, one family"),
("Belong, Grow, Serve","The journey of community"),
("The Fellowship of Believers","Life together in Christ"),
("Homegroup","Faith in the living room"),
("Deeper Together","Community that goes below the surface"),
("The Ties That Bind","What holds the church together"),
("Family","The church as the household of God"),
]

MISSIONS_EVANGELISM = [
("Go","Answering the Great Commission"),
("Sent","Living on mission where you are"),
("For the One","God's heart for the lost"),
("Everyday Evangelism","Sharing Jesus naturally"),
("Tell Someone","Sharing the hope you've found"),
("Who's Your One?","Reaching the person on your heart"),
("Bring One","The power of a simple invitation"),
("Your Story","Sharing your testimony naturally"),
("Good News","The message the world needs"),
("Love Your Neighbor","Reaching those around you"),
("Salt & Light","Living visibly different"),
("Unafraid","Courage to speak of Jesus"),
("Fishers of People","Learning to share your faith"),
("Come and See","A faith worth inviting others into"),
("Found","Helping the lost find their way home"),
("Reaching One","Impacting the world one person at a time"),
("The Great Commission","The mission Jesus gave"),
("To the Nations","Joining God's global mission"),
("For the World","God's heart for every people"),
("Sent Ones","Carrying the gospel to the world"),
("Everyone Needs Hope","Reaching a searching world"),
("Neighbors","Reaching the people next door"),
("Contagious","A faith worth catching"),
("Bold","Speaking about Jesus without fear"),
("Go & Tell","Answering the call to share"),
("The Harvest","Laborers for a ready field"),
("Reach","Extending grace to a searching world"),
("Here for Good","A lasting blessing to your city"),
("Serve the City","Blessing your community"),
("Mission Field Next Door","Reaching your neighborhood"),
("The Sent Life","Living as one commissioned"),
("Show & Tell","Living and speaking the gospel"),
("From Fear to Faithful","Finding courage to share"),
("The Simple Gospel","Sharing the good news clearly"),
("Ready to Answer","Responding to people's questions"),
("Everybody's Welcome","A church that reaches out"),
("Open Doors","Becoming a church guests love"),
("The Front Door","Reaching people far from God"),
("Praying for the Lost","Interceding for the far"),
("Compassion in Action","The gospel with skin on"),
("The Least of These","Serving Jesus by serving others"),
("Hands & Feet","Being the tangible love of Christ"),
("Do Justice","God's heart for the vulnerable"),
("Mercy in Motion","Compassion that acts"),
("Welcome the Stranger","Loving the outsider"),
("Defend the Fatherless","Caring for the vulnerable"),
("Until Everyone Hears","Reaching the unreached"),
("The Unreached","The gospel where it's never been"),
("Cross-Cultural","The gospel for every people"),
("Global Vision","A heart for the whole world"),
("Short-Term, Long Impact","Missions that matter"),
("Go Near, Go Far","Local and global mission"),
("Bring Them Home","Reaching the wandering"),
("The Rescue","Joining God's rescue mission"),
("Light in the Dark","Bringing hope to dark places"),
("The Invitation","Come and see who Jesus is"),
("Conversations That Count","Talking about faith with grace"),
("Everyday Missionary","Living sent right where you are"),
("The Gospel at Work","Representing Christ in your job"),
("Faith Out Loud","Speaking the good news boldly"),
("Reaching the Far","Loving those who feel distant from God"),
("Hope for the Hopeless","The gospel for the broken"),
("One More","Reaching one more for Christ"),
("Seek & Save","Joining Jesus in the search"),
("The Searching","Helping people find their way to God"),
("Room for You","Making space for the far"),
("Life Change","Stories of gospel transformation"),
("Come Home","An invitation back to God"),
("Witness","Living and telling the good news"),
("The Great Invitation","Come to Jesus"),
("Reach Your World","Mission in your everyday life"),
("Sowing Seeds","Faithful gospel witness"),
("Plant, Water, Grow","Trusting God with the harvest"),
("Every Tribe, Every Tongue","God's global family"),
("Send Me","Answering God's call to go"),
("Here Am I","Willing to be sent"),
("On Mission","Advancing God's kingdom together"),
("The Sending Church","Mobilizing for the mission"),
("Cross the Street, Cross the Sea","Local and global"),
("Gospel Neighbors","Reaching those around you"),
("The Bold Church","Unashamed of the gospel"),
("Everyone Gets to Play","All of us on mission"),
("Tell the Story","Sharing what Jesus has done"),
("Good News People","Confident messengers of hope"),
("The Message","The gospel the world needs"),
("Reaching the Next Door","Neighborhood mission"),
("Compassion Beyond Comfort","Serving where it costs"),
("The Heart of God for the Lost","Why we go"),
("Not Ashamed","Bold about the gospel"),
("Carry the Light","Bringing Jesus to dark places"),
("The Mission of God","Joining what He's doing"),
("Sent to Serve","Mission through compassion"),
("Love in Action","Meeting needs in Jesus' name"),
("Every Nation","God's plan for the world"),
("Bringing Heaven Near","The kingdom breaking in"),
("The Witness Life","Living and telling the gospel"),
("Reach One, Reach Many","Multiplying the mission"),
("Go Local","Mission in your own backyard"),
("The World at Our Door","Reaching the nations near us"),
("Until He Comes","Faithful mission to the end"),
]

WORSHIP = [
("The Heart of Worship","Returning to the God we adore"),
("More Than a Song","Worship as a way of life"),
("Holy Awe","Rediscovering wonder before God"),
("Worship in the Storm","Praising through the hardest days"),
("The Sacrifice of Praise","Worshiping when it's hard"),
("Living Worship","Offering all of life to God"),
("Spirit & Truth","Worship God actually desires"),
("Everyday Altars","Meeting God in the ordinary"),
("Behold Your God","Fixing your gaze on His majesty"),
("The Overflow","Worship from a grateful heart"),
("Undivided","A heart wholly devoted to God"),
("Worship as Warfare","Fighting your battles with praise"),
("Still","Encountering God in silence"),
("Magnify","Making God bigger in your eyes"),
("Come to the Altar","Meeting God in surrender"),
("Extravagant","Holding nothing back in worship"),
("Grateful","A heart tuned to thanksgiving"),
("The Weight of Glory","Encountering God's majesty"),
("Wonder","Recovering awe before an infinite God"),
("Worthy","Fixing your heart on the greatness of God"),
("Lost in Wonder","Losing yourself in God's greatness"),
("Bow Down","Choosing surrender over self"),
("The Throne Room","Seeing God as He truly is"),
("A Lifestyle of Praise","Gratitude in every circumstance"),
("Worship That Transforms","Becoming what you behold"),
("Hallelujah","Praise that lifts the soul"),
("Sing","Finding your voice in worship"),
("The Song of the Redeemed","Why we sing"),
("Praise Him","A life of continual worship"),
("Adore","Fixing our affections on God"),
("Surrender","Worship as total yielding"),
("All to You","Laying everything before God"),
("Here I Am to Worship","Coming before the King"),
("Holy Ground","Worship in the presence of God"),
("Enthroned","Making God the center of praise"),
("Lift Him High","Exalting the name of Jesus"),
("Face Down","Reverent worship before God"),
("Hands Lifted High","Surrender in worship"),
("The Worshiper's Heart","What God is looking for"),
("Worship First","Making praise your priority"),
("In Spirit and in Truth","Authentic worship"),
("Every Breath","Worshiping with all of life"),
("The Beauty of Holiness","Worshiping a holy God"),
("Awe & Wonder","Recovering reverence for God"),
("Consumed","Worship that captivates the heart"),
("Come Boldly, Bow Humbly","Worship's holy tension"),
("The Melody of Grace","Worship shaped by the gospel"),
("Songs of Deliverance","Worship through the trial"),
("Worship the King","Exalting the reign of Christ"),
("Glory to God","Giving God the honor He deserves"),
("Whole-Life Worship","Every moment for God's glory"),
("Living Sacrifice","Offering yourself in worship"),
("Fixed on Jesus","Worship that centers on Christ"),
("The Anthem","Our praise to the risen King"),
("Worship Beyond the Walls","Praise in everyday life"),
("The Sound of Heaven","Joining the worship above"),
("Unashamed Worship","Praising God without reserve"),
("When Words Fail","Worship in wordless awe"),
("The Overflowing Heart","Worship from gratitude"),
("Reverence","Worship marked by holy fear"),
("Encounter","Meeting God in worship"),
("Worship & Wonder","Awe at the greatness of God"),
("Our God Reigns","Worshiping the sovereign King"),
("Holy Is the Lord","Worshiping the thrice-holy God"),
("The Great I AM","Worshiping the eternal God"),
("Come, Now Is the Time","An invitation to worship"),
("Draw Me Near","Longing for God's presence"),
("The Presence","Worship that welcomes God near"),
("All Glory","Giving God everything He deserves"),
("Praise in the Valley","Worship through the hard"),
("Songs in the Night","Worship when it's dark"),
("Rejoice","The joy of worship"),
("Worship the Creator","Awe at the Maker of all"),
("The Gathered Song","Why we worship together"),
("One Voice","The church united in praise"),
("Heart, Soul & Strength","Wholehearted worship"),
("The Sacred Assembly","Gathering to worship God"),
("Behold the Lamb","Worship centered on the cross"),
("Crown Him","Exalting Jesus as King"),
("Holy, Holy, Holy","The song of heaven"),
("Set Apart in Praise","Worship as consecration"),
("The Wonder of You","Worship captivated by God"),
("Every Knee","All creation worshiping God"),
("Wholehearted Worship","Loving God with everything"),
("Worship Unleashed","Praise without restraint"),
("The Language of Heaven","Worship as our native tongue"),
("Come and Worship","An open invitation to praise"),
("The Beauty of God","Worship that beholds Him"),
("Give Him Praise","Honoring God in worship"),
("The Doxology","Living to glorify God"),
("Awe-Struck","Recovering wonder in worship"),
("Worship in Truth","Praise grounded in who God is"),
("The Sound of Surrender","Worship that yields all"),
("Holy Fire","Worship that burns with passion"),
("The Grateful Song","Praise born of thankfulness"),
("Worthy Is the Lamb","Worshiping the risen Christ"),
("Enter His Gates","Coming to God with thanksgiving"),
("Lift Up Your Heads","Welcoming the King of glory"),
("The Worship-Filled Life","Praise as a lifestyle"),
("All Creation Sings","Joining the worship of all things"),
]

MINISTRY_SERVICE = [
("Serve","Discovering the joy of serving others"),
("Every Member a Minister","You have a role to play"),
("Find Your Place","Serving where God made you to shine"),
("Use Your Gifts","Investing your talents for the kingdom"),
("The Towel & the Basin","Leading by serving"),
("Called to Serve","Answering God's invitation"),
("Hands & Feet","Being the tangible love of Christ"),
("Wired to Serve","Serving from your God-given design"),
("Do Your Part","Everyone playing their role"),
("Greater Is the Servant","Greatness in God's kingdom"),
("The Serving Life","A lifestyle of generosity"),
("Step Up","Answering the call to serve"),
("Faithful in the Small","Serving where no one sees"),
("Behind the Scenes","The ministry that goes unnoticed"),
("Gifted to Give","Discovering your spiritual gifts"),
("Made to Serve","Created for good works"),
("Serve the City","Blessing your community"),
("Love in Action","Faith that serves"),
("The Ministry of Presence","Being there for others"),
("All Hands","Everyone serving together"),
("Serving Where You Are","Ministry in daily life"),
("The Servant Heart","What God is looking for"),
("Give of Yourself","Serving with your whole life"),
("Volunteer","The gift of your time and hands"),
("The Dream Team","Serving together in the church"),
("Play Your Part","Every gift matters"),
("Serve First","Leading by lifting others"),
("The Least of These","Serving Jesus by serving others"),
("Compassion in Action","Meeting real needs"),
("Ministry Matters","Why your service counts"),
("Sent to Serve","Ministry through compassion"),
("The Servant King's People","Following Jesus in service"),
("Whatever It Takes","Serving without conditions"),
("Serving Sunday","Making room for others"),
("The Joy of Serving","Blessed in the giving"),
("Empowered to Serve","Strength for the work"),
("Your Gifts, God's Glory","Serving for His name"),
("Discover Your Gifts","Finding your ministry fit"),
("Faithful Servants","Doing what God asks"),
("The Serving Church","Known for love in action"),
("Together We Serve","Ministry as a team"),
("Serve & Multiply","Ministry that reproduces"),
("The Ministry of the Ordinary","Serving in small ways"),
("Roll Up Your Sleeves","Getting into the work"),
("Kingdom Work","Serving God's mission"),
("Serving the Broken","Ministering to the hurting"),
("Go Low","The path of servant leadership"),
("Called & Equipped","Ready to serve"),
("Serve Where You're Planted","Ministry right where you are"),
("The Heart of a Servant","Loving through service"),
("Every Gift Counts","No one is unnecessary"),
("Serve the One","Ministry to the person in front of you"),
("Give Your Time","The generosity of service"),
("Ministry in Motion","Faith that moves to serve"),
("The Great Servant","Following Jesus' example"),
("Serve Together","The church on mission"),
("Be the Blessing","Living to serve others"),
("Willing Hands","Ready and available to God"),
("The Volunteer Life","Serving as a lifestyle"),
("Serve Boldly","Stepping into ministry"),
("Ordinary People, Extraordinary Service","God uses you"),
("Found Faithful","Serving well in your role"),
("The Serving Spirit","A heart bent toward others"),
("Your Ministry Matters","The value of your service"),
("Serve the Least","Ministry to the overlooked"),
("Faithful with Little","Serving in the small things"),
("The Ministry of Availability","Saying yes to God"),
("Answer the Need","Serving where it hurts"),
("Do Good","Faith expressed in service"),
("Serve Like Jesus","Greatness through servanthood"),
("Called Up","Stepping into your ministry"),
("Give Back","Serving out of gratitude"),
("The Servant's Reward","Joy in giving your life"),
("Ministry for Everyone","No spectators here"),
("Hands to Serve","Being useful to God"),
("The Gift of Service","Blessing others with your time"),
("Serve the Body","Ministry within the church"),
("Poured Out","Giving your life in service"),
("The Ministry of the Towel","Humble, hidden service"),
("Willing & Ready","Available for God's work"),
("Serve with Joy","Finding gladness in giving"),
("The Serving Season","A church that serves"),
("Show Up & Serve","The gift of presence"),
("Faithful Hands","Serving God through the work"),
("Made for Ministry","Your role in the body"),
("Serve On Purpose","Ministry with intention"),
("Everyone Has a Gift","Discovering yours"),
("The Faithful Few","Serving when others won't"),
("Ministry Beyond the Building","Serving your world"),
("The Work of the People","Every member serving"),
("Serve the Mission","Ministry that advances the gospel"),
("Answer the Call","Stepping into service"),
("Generous with Your Life","Serving sacrificially"),
("The Servant's Path","Following Jesus in ministry"),
("Lift as You Serve","Blessing others through service"),
("Willing Hearts, Working Hands","Serving God together"),
("The Ministry Mindset","Living to serve"),
("Serve Faithfully","Consistency in ministry"),
("Give It All","Wholehearted service to God"),
("Whatever You Do","Serving God in everything"),
]

NEW_COLLECTIONS = {
    "Fellowship": FELLOWSHIP,
    "Missions & Evangelism": MISSIONS_EVANGELISM,
    "Worship": WORSHIP,
    "Ministry & Service": MINISTRY_SERVICE,
}

if __name__ == "__main__":
    for name, items in NEW_COLLECTIONS.items():
        print(f"{name}: {len(items)}")
