# -*- coding: utf-8 -*-
import json

# flag: 1 = title supplied by Brett's documents, 0 = drafted here to complete the category

JOURNEYS = [
 (1, "Stewardship & Purpose", "What has been entrusted to us, and what is it ultimately for?", [
  ("What's in Your Hand?", "30 Days to Discover the Purpose Behind Everything You've Been Entrusted With", 1),
  ("Owner or Steward?", "30 Days to Rethink Who Everything Actually Belongs To", 0),
  ("The Purpose of Prosperity", "30 Days to Ask What Your Family's Resources Are Ultimately For", 0),
  ("First Things First", "30 Days to Order Your Family's Priorities Before Ordering Its Assets", 0),
  ("The Stewardship Inventory", "30 Days to Take Honest Account of Time, Talent, Treasure, and Influence", 0),
  ("Beyond Accumulation", "30 Days to Move from Building Wealth to Deploying It", 0),
  ("What Were We Given For?", "30 Days to Connect Provision with Assignment", 0),
  ("The Weight of Opportunity", "30 Days to Carry Advantage with Humility and Intention", 0),
  ("Stewards of More Than Money", "30 Days to Steward Relationships, Reputation, and Time as Carefully as Capital", 0),
  ("A Life Under Assignment", "30 Days to Live as Though Everything Was Entrusted Rather Than Earned", 0),
  ("Called to Steward", "30 Days to Discover the Responsibility Hidden Inside Opportunity", 1),
  ("Purposeful Prosperity", "30 Days to Align Financial Success with a Life of Meaning", 1),
  ("The Enough Conversation", "30 Days to Decide What Is Enough for Lifestyle, Security, Inheritance, and Giving", 1),
  ("Blessed to Bless", "30 Days to Turn Abundance into Responsibility and Impact", 1),
  ("The Stewardship Life Plan", "30 Days to Bring Everything You Have and Everything You Are Under One Purpose", 1),
 ]),
 (2, "Family Values, Mission & Unity", "Who are we, what do we believe, and what holds us together?", [
  ("The Family Values Journey", "30 Days to Name the Convictions Your Family Actually Lives By", 1),
  ("The Family Mission Journey", "30 Days to Write the Statement That Guides a Generation of Decisions", 1),
  ("The Family Conversation Journey", "30 Days to Start the Conversations Your Family Has Been Avoiding", 1),
  ("What We Stand For", "30 Days to Define the Handful of Things Your Family Will Not Trade", 0),
  ("One Family, Many Homes", "30 Days to Stay Connected as Households Multiply and Scatter", 0),
  ("The Values We Inherited", "30 Days to Decide What to Carry Forward and What to Leave Behind", 0),
  ("Traditions Worth Keeping", "30 Days to Choose the Practices That Will Outlive You", 0),
  ("Naming Our Family", "30 Days to Articulate What Your Last Name Should Mean", 0),
  ("The Unity Journey", "30 Days to Repair, Strengthen, and Protect the Bonds That Hold a Family", 0),
  ("Decisions We Make Together", "30 Days to Agree on How This Family Decides", 0),
  ("Our Family Why", "30 Days to Discover the Purpose That Holds Generations Together", 1),
  ("The Family Identity Journey", "30 Days to Clarify Who We Are Beyond Our Wealth and Achievements", 1),
  ("Shared Values, Different Lives", "30 Days to Build Unity Without Requiring Every Generation to Be the Same", 1),
  ("The Family Culture Journey", "30 Days to Shape the Behaviors, Traditions, and Relationships We Want to Multiply", 1),
  ("Together on Purpose", "30 Days to Build a Shared Vision for the Years Ahead", 1),
 ]),
 (3, "Wisdom & Next-Generation Preparation", "How do we prepare people before transferring possessions?", [
  ("Wisdom Before Wealth", "30 Days to Transfer the Lessons Before You Transfer the Assets", 1),
  ("Next Generation Journey", "30 Days to Prepare the Next Generation for Wealth, Responsibility, and Purpose", 1),
  ("Prepared, Not Protected", "30 Days to Raise Capable Heirs Instead of Cautious Ones", 0),
  ("The First Job, the First Budget, the First Loss", "30 Days of Formation Through Ordinary Financial Experience", 0),
  ("Teaching Work Before Wealth", "30 Days to Build a Work Ethic That Money Cannot Buy", 0),
  ("What We Learned the Hard Way", "30 Days to Pass on Mistakes as Faithfully as Successes", 0),
  ("Raising Givers", "30 Days to Form Generosity Early Enough for It to Take", 0),
  ("The Character Conversation", "30 Days to Talk About Who They Are Becoming, Not What They Will Receive", 0),
  ("Ready for More", "30 Days to Assess Whether the Next Generation Is Prepared for Greater Responsibility", 0),
  ("From Allowance to Ownership", "30 Days to Move Children Through Every Stage of Financial Responsibility", 0),
  ("Before You Inherit", "30 Days to Build the Character, Wisdom, and Competence Wealth Requires", 1),
  ("The Next Steward Playbook", "30 Days to Prepare Young Adults for Greater Financial Responsibility", 1),
  ("Learning to Lead the Family", "30 Days to Prepare Emerging Generational Leaders", 1),
  ("Money Lessons We Wish We Learned Earlier", "30 Days of Practical Wisdom for the Next Generation", 1),
  ("Growing Into Responsibility", "30 Days to Move from Dependence to Ownership, Initiative, and Stewardship", 1),
 ]),
 (4, "Generosity & Kingdom Impact", "How do we turn resources into blessing while we are still together?", [
  ("Generous Together", "30 Days to Discover the Joy and Purpose of Giving as a Family", 1),
  ("The Family Generosity Summit", "30 Days to Prepare for the Meeting Where Your Family Decides Its Giving", 1),
  ("Why We Give", "30 Days to Understand the Motives Beneath Your Family's Generosity", 0),
  ("The First Check", "30 Days to Begin Giving Together for the First Time", 0),
  ("Giving While Living", "30 Days to Experience the Impact of Generosity in Your Lifetime", 0),
  ("The Causes That Move Us", "30 Days to Map Where Your Family's Compassion Already Points", 0),
  ("Generosity and the Business", "30 Days to Connect Enterprise Success with Intentional Giving", 0),
  ("The Donor-Advised Family", "30 Days to Use Charitable Tools with Purpose Rather Than Convenience", 0),
  ("Anonymous or Known?", "30 Days to Decide How Publicly Your Family Will Give", 0),
  ("When Giving Gets Complicated", "30 Days to Navigate Requests, Relationships, and Saying No Well", 0),
  ("The Generosity Pledge Journey", "30 Days to Decide What Generous Living Could Look Like for Your Family", 1),
  ("Giving with Wisdom", "30 Days to Combine Compassion, Discernment, Strategy, and Impact", 1),
  ("The Joy of Enough", "30 Days to Discover How Contentment Can Release Greater Generosity", 1),
  ("Giving Across Generations", "30 Days to Build a Family Culture of Generosity That Outlives the Founders", 1),
  ("Kingdom Capital", "30 Days to Explore How Wealth Can Advance Eternal Purposes", 1),
 ]),
 (5, "Legacy & Family Story", "What do we want future generations to remember and carry forward?", [
  ("Family Legacy Journey", "30 Days to Clarify the Story, Values, Faith, and Wisdom You Want to Pass On", 1),
  ("Living Legacy", "30 Days to Give, Teach, Experience, and Bless While You're Still Together", 1),
  ("The Grandparent Legacy Journey", "30 Days to Do for Grandchildren What Only Grandparents Can Do", 1),
  ("Where We Came From", "30 Days to Recover the Origins Your Children Have Never Heard", 0),
  ("The Turning Points", "30 Days to Tell the Stories of the Decisions That Changed Everything", 0),
  ("What Money Meant in Our House", "30 Days to Understand the Financial Story Behind Your Family's Habits", 0),
  ("The Blessing Journey", "30 Days to Speak Words Your Children Will Carry for Life", 0),
  ("Recording the Elders", "30 Days to Capture Voices Before They Are Gone", 0),
  ("Our Family in Ten Objects", "30 Days to Tell Your History Through What You Have Kept", 0),
  ("What Will They Say?", "30 Days to Decide Now What You Hope Is Said Later", 0),
  ("The Legacy Interview Journey", "30 Days to Capture the Stories, Decisions, and Lessons That Shaped Your Life", 1),
  ("Letters to the Future", "30 Days to Write What You Hope Future Generations Will One Day Read", 1),
  ("The Family Memory Project", "30 Days to Preserve the Stories That Money Cannot Replace", 1),
  ("The Wisdom Archive", "30 Days to Capture the Lessons Your Family Should Never Have to Learn Twice", 1),
  ("Legacy Beyond the Estate", "30 Days to Define What You Want to Leave That Cannot Be Listed on a Balance Sheet", 1),
 ]),
 (6, "Succession, Transition & Inheritance", "What happens when leadership, authority, responsibility, and assets change hands?", [
  ("The Succession Journey", "30 Days to Prepare People, Not Only Documents, for What Comes Next", 1),
  ("Preparing the Surviving Spouse", "30 Days to Make Sure the One Left Behind Is Ready to Lead", 1),
  ("What They Should Know Before We're Gone", "30 Days to Replace Surprise with Understanding", 0),
  ("Fair Is Not Always Equal", "30 Days to Think Clearly About Dividing What You Leave", 0),
  ("The Trustee Conversation", "30 Days to Choose and Prepare the People Who Will Carry Authority", 0),
  ("Documents and Intentions", "30 Days to Close the Gap Between What Is Written and What Is Meant", 0),
  ("The In-Law Question", "30 Days to Decide How Spouses of the Next Generation Are Included", 0),
  ("When to Give, When to Wait", "30 Days to Time Transfers to Readiness Rather Than the Calendar", 0),
  ("Preparing Heirs for a Liquidity Event", "30 Days to Get Ahead of a Sale, a Windfall, or a Distribution", 0),
  ("The Handoff", "30 Days to Move Authority from One Generation to the Next Without Losing Either", 0),
  ("The Inheritance Conversation", "30 Days to Discuss What Will Transfer Before the Transfer Happens", 1),
  ("Preparing for Control", "30 Days to Help Future Decision-Makers Understand Authority and Responsibility", 1),
  ("The Sibling Succession Journey", "30 Days to Prepare Brothers and Sisters for Shared Wealth and Shared Decisions", 1),
  ("When the Founder Steps Away", "30 Days to Prepare Family and Enterprise for a New Leadership Era", 1),
  ("Continuity Without Control", "30 Days to Release Leadership Without Abandoning Wisdom", 1),
 ]),
 (7, "Longevity, Retirement & Finishing Well", "If we live another 20 to 35 years, what should those years accomplish?", [
  ("Finish Well", "30 Days to Complete the Conversations, Relationships, Generosity, and Legacy That Matter Most", 1),
  ("The Longevity Journey", "30 Days to Plan for the Decades You Did Not Expect to Have", 1),
  ("The Last Third", "30 Days to Give the Final Season of Life a Clear Assignment", 0),
  ("Retiring to Something", "30 Days to Replace a Career with a Calling", 0),
  ("The Slower Yes", "30 Days to Choose What Deserves Your Remaining Time", 0),
  ("Grandparenting on Purpose", "30 Days to Make These Years Count for the Generations Behind You", 0),
  ("Simplifying Well", "30 Days to Release Possessions, Property, and Roles with Grace", 0),
  ("The Second Act", "30 Days to Consider What You Might Build, Fund, or Serve Next", 0),
  ("Mentoring in the Later Years", "30 Days to Pour Experience into People Who Need It", 0),
  ("Ready for the Last Chapter", "30 Days to Face the End with Clarity, Faith, and Peace", 0),
  ("Twenty More Years", "30 Days to Imagine What Your Next Two Decades Could Accomplish", 1),
  ("Purpose After the Paycheck", "30 Days to Build Identity and Meaning Beyond Professional Achievement", 1),
  ("The Longevity Conversation", "30 Days to Prepare Financially, Relationally, Physically, and Spiritually for Longer Life", 1),
  ("The Season of Blessing", "30 Days to Invest Your Later Years in People, Generosity, and Wisdom Transfer", 1),
  ("Lasting Fruit", "30 Days to Make the Final Chapters of Life Deeply Purposeful", 1),
 ]),
 (8, "Marriage, Family Relationships & Difficult Conversations", "How do we keep wealth from creating distance, confusion, or conflict?", [
  ("Marriage & Money", "30 Days to Align the Two People Who Decide Everything Else", 1),
  ("Ready Together", "30 Days to Make Sure Both Spouses Understand and Can Carry the Family's Financial Life", 1),
  ("The Conversation We Keep Postponing", "30 Days to Finally Say the Thing That Needs Saying", 0),
  ("Two Money Stories, One Marriage", "30 Days to Understand the Histories You Each Brought Into This", 0),
  ("When We Disagree About Giving", "30 Days to Find Unity in Generosity Without Forcing Sameness", 0),
  ("The Favored Child Question", "30 Days to Address Perceived Unfairness Before It Hardens", 0),
  ("Loving Adult Children Well", "30 Days to Support Without Controlling and Help Without Enabling", 0),
  ("The Table We Avoid", "30 Days to Rebuild Honest Communication in a Family That Has Gone Quiet", 0),
  ("Boundaries and Blessing", "30 Days to Give Generously Without Losing Yourself", 0),
  ("Repair Before Transfer", "30 Days to Address the Relationships That Wealth Will Otherwise Strain", 0),
  ("Wealth Without Wedges", "30 Days to Keep Money from Dividing the People You Love", 1),
  ("Talking About Inheritance", "30 Days to Replace Assumptions with Healthy Family Communication", 1),
  ("The Parent-Adult Child Conversation", "30 Days to Build a Mature Relationship Around Money and Responsibility", 1),
  ("Healing the Family Money Story", "30 Days to Understand How Past Financial Experiences Shape Present Relationships", 1),
  ("Grace in the Family", "30 Days to Navigate Differences, Disappointment, and Forgiveness", 1),
 ]),
 (9, "Business, Entrepreneurship & Influence", "How do families steward companies, leadership, opportunity, and influence?", [
  ("The Family Business Transition", "30 Days to Prepare the Company and the Family for a Change in Leadership", 1),
  ("The Stewardship of Influence", "30 Days to Steward the Doors Your Name Can Open", 1),
  ("Who Owns It, Who Runs It", "30 Days to Separate Ownership, Management, and Family Membership", 0),
  ("The Next Owner", "30 Days to Prepare a Family Member for Ownership Rather Than Employment", 0),
  ("Working with Family", "30 Days to Set Expectations Before They Become Grievances", 0),
  ("The Company We Built", "30 Days to Tell the Story and Name the Values Behind the Enterprise", 0),
  ("Should It Stay in the Family?", "30 Days to Answer the Question Before the Market Answers It for You", 0),
  ("Convictions at Work", "30 Days to Lead an Enterprise by Principles You Can Defend", 0),
  ("The Employee Legacy", "30 Days to Consider What the Business Owes the People Who Built It", 0),
  ("Purpose Beyond the Enterprise", "30 Days to Define Identity Apart from the Company You Created", 0),
  ("The Founder Legacy Journey", "30 Days to Decide What the Business Has Really Been For", 1),
  ("Family Business Values", "30 Days to Align Enterprise Decisions with Family Convictions", 1),
  ("Entrepreneurship Across Generations", "30 Days to Encourage Initiative Without Creating Entitlement", 1),
  ("The Business Owner's Finish-Well Journey", "30 Days to Prepare Yourself, Your Company, and Your Family for Transition", 1),
  ("Influence with Integrity", "30 Days to Steward Leadership, Networks, Reputation, and Opportunity Wisely", 1),
 ]),
 (10, "Family Governance, Annual Planning & Continuity", "How do we turn good intentions into an enduring family rhythm?", [
  ("The First Family Meeting", "30 Days to Prepare for a Conversation Your Family Has Never Had", 0),
  ("How This Family Decides", "30 Days to Agree on Who Decides What, and How", 0),
  ("The Family Constitution", "30 Days to Write the Agreements That Outlast the Founders", 0),
  ("The Family Council", "30 Days to Build a Structure That Keeps Every Generation Represented", 0),
  ("Rules for Money in This Family", "30 Days to Clarify Loans, Gifts, Support, and Expectations", 0),
  ("The Family Employment Policy", "30 Days to Decide How Family Members Join, Advance, and Exit", 0),
  ("Keeping the Record", "30 Days to Document Decisions So the Next Generation Is Not Guessing", 0),
  ("The Annual Stewardship Rhythm", "30 Days to Build a Calendar Your Family Can Actually Keep", 0),
  ("Continuity Planning", "30 Days to Prepare for the Day the Founders Are No Longer in the Room", 0),
  ("Accountability Without Control", "30 Days to Hold Each Other to Agreements Without Damaging Relationships", 0),
  ("The Annual Family Summit", "30 Days to Prepare for Your Most Important Family Conversation of the Year", 1),
  ("Our Family Rhythm", "30 Days to Build Repeatable Practices for Communication, Giving, Learning, and Decision-Making", 1),
  ("The Family Leadership Plan", "30 Days to Clarify Who Leads What as Generations Change", 1),
  ("The Stewardship Dashboard Journey", "30 Days to Measure What Matters Beyond Financial Performance", 1),
  ("Generational Continuity", "30 Days to Build Structures That Can Carry Family Purpose Forward", 1),
 ]),
 (11, "Faith, Spiritual Formation & Discipleship", "How does faith shape the way our family lives, gives, decides, and leads?", [
  ("Faithful Stewardship", "30 Days to Discover God's Perspective on Everything Entrusted to You", 1),
  ("Trusting God with Everything", "30 Days to Move from Financial Control Toward Faithful Dependence", 1),
  ("A Family of Faith", "30 Days to Strengthen Spiritual Life Across Generations", 1),
  ("Biblical Wisdom for Wealth", "30 Days to Apply Scripture to Prosperity, Responsibility, and Generosity", 1),
  ("Faith & Finances", "30 Days to Align Money Decisions with Biblical Convictions", 1),
  ("The Spiritual Legacy Journey", "30 Days to Pass Faith Along with Family Wealth", 1),
  ("Prayer & Stewardship", "30 Days to Bring Major Financial and Family Decisions Before God", 1),
  ("Obedience Over Ownership", "30 Days to Explore What Faithful Obedience Looks Like in a Life of Abundance", 1),
  ("The Family Discipleship Journey", "30 Days to Make Spiritual Formation Part of Family Legacy", 1),
  ("Kingdom-Minded Wealth", "30 Days to See Resources Through an Eternal Perspective", 1),
  ("The Faith Conversation", "30 Days to Talk Honestly About What Each Generation Believes", 1),
  ("Practicing Gratitude", "30 Days to Replace Entitlement with Thanksgiving and Perspective", 1),
  ("Contentment in a Culture of More", "30 Days to Discover the Freedom of Enough", 1),
  ("Called to Generosity", "30 Days to Explore Giving as Worship, Obedience, and Joy", 1),
  ("Faith for the Next Generation", "30 Days to Help Children Own Their Faith Rather Than Merely Inherit It", 1),
 ]),
 (12, "Life Transitions, Crisis & Resilience", "How does the family prepare for change, disruption, loss, and uncertainty?", [
  ("When Life Changes", "30 Days to Navigate Major Transition with Wisdom and Perspective", 1),
  ("The Family Resilience Journey", "30 Days to Build the Strength to Face Change Together", 1),
  ("After the Loss", "30 Days to Navigate Grief, Decisions, Family, and Stewardship After Someone Dies", 1),
  ("Suddenly Responsible", "30 Days for the Family Member Who Unexpectedly Becomes the Decision-Maker", 1),
  ("The Widow and Widower Stewardship Journey", "30 Days to Rebuild Confidence After Losing a Spouse", 1),
  ("When Health Changes Everything", "30 Days to Respond Wisely When Illness Reshapes Family Priorities", 1),
  ("Navigating a Financial Setback", "30 Days to Rebuild Perspective, Planning, and Hope", 1),
  ("Family Crisis Conversations", "30 Days to Communicate Clearly When Emotions and Stakes Are High", 1),
  ("After the Business Sale", "30 Days to Reorient Family Identity After a Major Liquidity Event", 1),
  ("Unexpected Wealth", "30 Days to Prepare for Sudden Financial Responsibility", 1),
  ("When Plans Change", "30 Days to Adapt Without Losing Purpose", 1),
  ("The Caregiver Transition", "30 Days to Prepare Family Members for New Responsibilities", 1),
  ("Rebuilding After Conflict", "30 Days to Restore Trust and Create Healthier Patterns", 1),
  ("Navigating Divorce in a Wealthy Family", "30 Days to Protect People, Relationships, and Wise Decision-Making During Transition", 1),
  ("Resilient Across Generations", "30 Days to Build Family Practices That Withstand Disruption", 1),
 ]),
 (13, "Family Health, Well-Being & Care", "How do we steward health, aging, caregiving, and quality of life alongside wealth?", [
  ("Whole Family Health", "30 Days to Align Physical, Emotional, Relational, Spiritual, and Financial Well-Being", 1),
  ("Health Is Wealth", "30 Days to Treat Vitality as a Stewardship Responsibility", 1),
  ("The Healthy Longevity Journey", "30 Days to Prepare for More Years with Greater Intention", 1),
  ("Caring for Aging Parents", "30 Days to Navigate Responsibility, Care, Finances, and Family Roles", 1),
  ("The Family Care Plan", "30 Days to Prepare Before a Health Crisis Makes Decisions Urgent", 1),
  ("The Caregiving Conversation", "30 Days to Clarify Expectations Before Care Is Needed", 1),
  ("Aging with Dignity", "30 Days to Plan for Independence, Assistance, and Family Involvement", 1),
  ("Preparing for Incapacity", "30 Days to Make Important Decisions While You Still Can", 1),
  ("The Health & Wealth Alignment Journey", "30 Days to Coordinate Financial Resources with Quality-of-Life Priorities", 1),
  ("Mental and Emotional Well-Being", "30 Days to Build Healthier Family Practices Around Stress, Success, and Responsibility", 1),
  ("Family Care Without Resentment", "30 Days to Create Fairer Expectations for Adult Children and Caregivers", 1),
  ("The Healthy Marriage in Retirement Journey", "30 Days to Rediscover Partnership in a New Life Season", 1),
  ("Living Well Longer", "30 Days to Turn Longevity into Opportunity, Not Merely Expense", 1),
  ("The End-of-Life Conversation", "30 Days to Clarify Wishes, Values, Relationships, and Family Responsibilities", 1),
  ("Quality of Life", "30 Days to Define What Living Well Means for Your Family", 1),
 ]),
 (14, "Community, Service & Social Impact", "How does the family use its resources and influence to serve beyond itself?", [
  ("A Family That Serves", "30 Days to Make Service Part of Your Family Identity", 1),
  ("Beyond Ourselves", "30 Days to Discover Where Your Family Can Make a Meaningful Difference", 1),
  ("The Community Impact Journey", "30 Days to Connect Local Needs with Family Resources and Relationships", 1),
  ("Time, Talent & Treasure", "30 Days to Expand Generosity Beyond Financial Giving", 1),
  ("Serving Together", "30 Days to Create Shared Service Experiences Across Generations", 1),
  ("The Family Impact Map", "30 Days to Identify the Causes, Communities, and Problems Your Family Cares About", 1),
  ("Influence for Good", "30 Days to Use Relationships and Reputation to Open Doors for Others", 1),
  ("Strategic Service", "30 Days to Move from Random Acts of Help to Intentional Impact", 1),
  ("The Volunteer Legacy", "30 Days to Pass a Lifestyle of Service to Children and Grandchildren", 1),
  ("Solving Problems Together", "30 Days to Turn Family Resources Toward Meaningful Challenges", 1),
  ("The Family Foundation Journey", "30 Days to Clarify Purpose, Participation, and Impact", 1),
  ("Impact Investing Conversation", "30 Days to Explore How Capital Can Express Values Alongside Financial Objectives", 1),
  ("The Local Church Impact Journey", "30 Days to Consider How Your Family Can Strengthen Ministry and Community", 1),
  ("Global Impact Family", "30 Days to Explore How Your Family Can Engage Needs Beyond Your Community", 1),
  ("A Legacy of Service", "30 Days to Become Known for What Your Family Gave, Built, and Changed", 1),
 ]),
 (15, "Advisor-Family Partnership & Financial Stewardship", "How does the family work with advisors to integrate financial wisdom with its larger purpose?", [
  ("The Family Stewardship Advisor Journey", "30 Days to Build a More Meaningful Partnership with Your Financial Advisor", 1),
  ("Beyond the Portfolio", "30 Days to Connect Financial Planning with Family, Purpose, Generosity, and Legacy", 1),
  ("The Annual Stewardship Review", "30 Days to Prepare for a More Meaningful Advisor Conversation", 1),
  ("Know Your Financial Team", "30 Days to Understand the Advisors, Roles, and Relationships Supporting Your Family", 1),
  ("The Financial Quarterback Journey", "30 Days to Coordinate Your Advisor, CPA, Attorney, and Other Specialists", 1),
  ("The Family Financial Organization Journey", "30 Days to Make Important Information Understandable and Accessible", 1),
  ("Preparing Your Spouse Financially", "30 Days to Make Sure Both Spouses Understand the Family's Financial Life", 1),
  ("The Estate Coordination Journey", "30 Days to Connect Documents, Intentions, Advisors, and Family Understanding", 1),
  ("The Tax & Stewardship Conversation", "30 Days to Explore How Taxes, Giving, and Long-Term Planning Work Together", 1),
  ("The Investment Purpose Journey", "30 Days to Connect Investment Strategy with What the Money Is Actually For", 1),
  ("The Advisor Relationship Transfer", "30 Days to Introduce the Next Generation Before They Need the Relationship", 1),
  ("Your Family Financial Playbook", "30 Days to Clarify How Your Family Makes, Manages, Gives, and Transfers Money", 1),
  ("The Family Financial Confidence Journey", "30 Days to Help Every Key Decision-Maker Understand the Financial Picture", 1),
  ("The Stewardship Team Journey", "30 Days to Build Better Collaboration Among Your Family's Professional Advisors", 1),
  ("Your Next Best Financial Conversation", "30 Days to Identify the Financial, Family, and Stewardship Questions That Matter Now", 1),
 ]),
]

TOOLS = [
 ("Family", "Top 50 Family Tools", "Help us make wise decisions and transfer more than wealth.", [
  ("A", "Discover the Family", [
   ("Family Stewardship Assessment", "Scores the family across wealth, wisdom, relationships, values and faith, generosity, succession, and legacy."),
   ("Family Stewardship Profile", "Creates the persistent master profile from which CAN personalization occurs."),
   ("Family Relationship Map", "Maps G1, G2, G3, spouses, advisors, trustees, and other influential relationships."),
   ("Couple Alignment Assessment", "Reveals where spouses agree and differ around money, children, giving, inheritance, and legacy."),
   ("What's in Your Hand? Inventory", "Inventories time, talent, treasure, relationships, influence, experiences, and opportunities."),
   ("Family Values Assessment", "Each member independently identifies values before CAN reveals overlap and differences."),
   ("Family Communication Assessment", "Measures whether important financial and family subjects are actually discussed."),
   ("Next-Generation Readiness Assessment", "Measures financial, relational, character, generosity, and leadership preparedness."),
   ("Generosity Assessment", "Helps the family understand its current giving philosophy, practices, and opportunities."),
   ("Legacy Readiness Assessment", "Determines how intentional the family has been about transferring wisdom, stories, values, and relationships."),
  ]),
  ("B", "Define What Matters", [
   ("Family Mission Builder", "Produces a concise family mission statement."),
   ("Family Values Builder", "Turns selected values into observable family behaviors."),
   ("Family Purpose Statement", "Answers what the family hopes its resources ultimately accomplish."),
   ("Family Stewardship Vision", "Creates a five to ten year picture of family flourishing and impact."),
   ("Enough Calculator & Conversation", "Helps distinguish lifestyle needs, security, inheritance, and surplus."),
   ("Family Wealth Purpose Map", "Assigns purposes to pools of capital."),
   ("Family Generosity Map", "Maps causes, ministries, geography, passions, and giving vehicles."),
   ("Family Legacy Statement", "Defines what the family hopes to pass beyond financial assets."),
   ("Family Impact Map", "Connects family resources with people and problems the family hopes to influence."),
   ("Family Stewardship Priority Map", "AI ranks issues into Now, Next, and Later."),
  ]),
  ("C", "Have the Conversations", [
   ("Couple Conversation Guide", "Structured spouse discussions before wider family conversations."),
   ("Family Conversation Cards", "Questions around wealth, values, faith, inheritance, generosity, and relationships."),
   ("Inheritance Conversation Guide", "Helps parents communicate intentions without unnecessarily disclosing every financial detail."),
   ("Next-Generation Conversation Guide", "Gives parents and adult children a structured pathway into responsibility."),
   ("Generosity Conversation Guide", "Moves giving from transactions to shared family purpose."),
   ("Family Meeting Kit", "Invitation, pre-work, agenda, exercises, facilitation, decisions, and follow-up."),
   ("Difficult Conversation Planner", "Prepares families for sensitive conversations involving conflict, inequity, addiction, entitlement, or relational strain."),
   ("Sibling Stewardship Guide", "Helps siblings prepare for shared assets and decision authority."),
   ("Grandparent Conversation Guide", "Helps grandparents intentionally transfer wisdom and story."),
   ("Family Questions We Never Asked", "A curated set of deep questions for uncovering stories, fears, hopes, mistakes, and dreams."),
  ]),
  ("D", "Transfer Wisdom & Legacy", [
   ("Wisdom Before Wealth Workbook", "Captures lessons the family wants transferred alongside assets."),
   ("Legacy Letter Builder", "Helps parents and grandparents write personal legacy letters."),
   ("Family Story Capture", "AI-guided interviews converted into written family stories."),
   ("Family Storybook Generator", "Turns stories, photos, values, and milestones into a custom book."),
   ("Family Video Legacy Kit", "Interview prompts, filming guide, questions, and production framework."),
   ("Ready to Receive Next-Gen Workbook", "Prepares heirs for increasing responsibility."),
   ("Family Wisdom Library", "Searchable archive of stories, lessons, letters, videos, and family principles."),
   ("Grandparent Legacy Journal", "Structured story and wisdom transfer for grandchildren."),
   ("Living Legacy Plan", "Identifies what the family should give, teach, experience, and communicate now."),
   ("Family Blessing & Commissioning Guide", "Helps parents intentionally affirm and commission the next generation."),
  ]),
  ("E", "Act & Continue", [
   ("Personalized 30-Day Journey", "CAN generates the family's prescribed journey from the 225-journey library."),
   ("Personalized Family Journal", "Family-specific digital and printed companion."),
   ("Family Decision Worksheet", "Integrates values, relationships, finances, professional counsel, and decision criteria."),
   ("Family Stewardship Action Plan", "Converts discussion into 30-day, 90-day, and annual commitments."),
   ("Family Stewardship Portfolio", "Persistent home for mission, values, generosity, succession, legacy, journeys, and goals."),
   ("Annual Family Stewardship Review", "Reviews family change before investment performance."),
   ("Family Impact Report", "Shows what the family accomplished beyond portfolio returns."),
   ("Recommended Specialist Roadmap", "Identifies when attorney, CPA, counselor, pastor, generosity expert, or other specialist should enter."),
   ("Next Best Journey Engine", "Recommends what the family should experience next."),
   ("Family Stewardship Roadmap", "The family's multiyear master plan tying all of the above together."),
  ]),
 ]),
 ("Advisor", "Top 50 Advisor Tools", "Help me know, engage, and serve the whole family.", [
  ("A", "Know the Family", [
   ("Advisor Family Discovery Guide", "Questions for learning the family's story beyond financial data."),
   ("Family Relationship Intelligence Brief", "AI-generated summary before each significant meeting."),
   ("Family Relationship Map, Advisor View", "Shows exactly whom the advisor knows and does not know."),
   ("Relationship Depth Score", "Measures financial, personal, family, multigenerational, and stewardship relationship depth."),
   ("Family Stewardship Opportunity Finder", "Identifies the highest-value unanswered family questions."),
   ("Client Life-Transition Monitor", "Flags retirement, marriage, inheritance, death, sale, caregiving, and other transition opportunities."),
   ("Spouse Relationship Tracker", "Prevents the non-primary spouse from remaining relationally invisible."),
   ("G2/G3 Engagement Tracker", "Measures actual relationships with heirs."),
   ("Family Professional Network Map", "Attorney, CPA, insurance, pastor, coach, trustee, and specialists."),
   ("Relationship Risk Alert", "Flags high-value households with fragile relational coverage."),
  ]),
  ("B", "Prepare Better Conversations", [
   ("AI Meeting Prep Brief", "Everything worth remembering before the meeting."),
   ("Advisor Conversation Prompt Generator", "Personalized questions based on the family's profile."),
   ("Questions Beneath the Numbers", "A master library of relational stewardship questions."),
   ("Annual Stewardship Review Guide", "Converts traditional annual reviews into whole-family conversations."),
   ("Couple Conversation Facilitation Guide", "Tells the advisor what to ask, listen for, avoid, clarify, document, and do next."),
   ("Next-Generation Meeting Guide", "Tells the advisor what to ask, listen for, avoid, clarify, document, and do next."),
   ("Generosity Conversation Guide", "Tells the advisor what to ask, listen for, avoid, clarify, document, and do next."),
   ("Succession Conversation Guide", "Tells the advisor what to ask, listen for, avoid, clarify, document, and do next."),
   ("Longevity Conversation Guide", "Tells the advisor what to ask, listen for, avoid, clarify, document, and do next."),
   ("Difficult Family Conversation Guide", "Tells the advisor what to ask, listen for, avoid, clarify, document, and do next."),
  ]),
  ("C", "Facilitate Family Experiences", [
   ("Family Meeting Builder", "AI creates the complete meeting package."),
   ("Family Meeting Facilitator Playbook", "Teaches advisors how to facilitate rather than lecture."),
   ("30-Day Journey Prescription Tool", "Chooses among the 225 journeys."),
   ("Journey Launch Kit", "Advisor introduction, invitation, family instructions, and check-ins."),
   ("Journey Completion Debrief", "Converts learning into an advisor conversation."),
   ("Family Values Workshop Kit", "Workshop format for the family values conversation."),
   ("Family Mission Workshop Kit", "Workshop format for the family mission conversation."),
   ("Generosity Family Summit Kit", "Workshop format for the family generosity summit."),
   ("Wisdom Before Wealth Workshop", "Workshop format for transferring wisdom ahead of assets."),
   ("Living Legacy Workshop", "Workshop format for giving, teaching, and blessing now."),
  ]),
  ("D", "Build Advisor Capability", [
   ("30-Day Advisor Stewardship Journey", "Forms the advisor personally and professionally."),
   ("Family Stewardship Advisor Curriculum", "Core training pathway."),
   ("Family Stewardship Advisor Certification", "Competency-based credential for the CAN methodology."),
   ("Advisor Behavior Scorecard", "Measures observable stewardship-advisor behaviors."),
   ("Advisor Self-Assessment", "Identifies skill and confidence gaps."),
   ("Advisor Role-Play Simulator", "AI practices inheritance, generosity, spouse, conflict, and next-generation conversations."),
   ("Advisor Coaching Guide", "Used by managers and coaches to develop advisors."),
   ("Stewardship Case Study Library", "Realistic family scenarios and recommended responses."),
   ("Advisor Resource Recommendation Engine", "Finds the right tool without searching a library."),
   ("Specialist Referral Decision Tree", "Clarifies when the advisor should stop and bring in another professional."),
  ]),
  ("E", "Multiply Advisor Capacity", [
   ("AI Advisor Workflow Map", "Defines automate, augment, and never delegate."),
   ("AI Personalization Engine", "Generates family-specific experiences from CAN intellectual property."),
   ("Advisor Follow-Up Generator", "Drafts personalized summaries and next steps for human review."),
   ("Family Meeting Summary Generator", "Creates a family-approved action summary rather than an indiscriminate transcript."),
   ("Advisor Relationship Dashboard", "Displays relationship depth across the advisor's book."),
   ("Top 25 Family Priority Dashboard", "Shows which relationships deserve immediate attention."),
   ("Advisor Value Story Builder", "Helps explain the difference between wealth management and family stewardship."),
   ("Advisor Client Experience Planner", "Maps the next twelve months of experiences for each priority family."),
   ("Referral Conversation Kit", "Helps satisfied families introduce other families without awkward selling."),
   ("Advisor Annual Impact Report", "Shows how the advisor served families beyond AUM and production."),
  ]),
 ]),
 ("Enterprise", "Top 25 RIA Enterprise Tools", "Help us scale this experience across advisors, offices, and acquisitions.", [
  ("A", "Culture & Advisor Formation", [
   ("Christian RIA Culture Blueprint", "Converts faith and values into purpose, client promises, advisor behaviors, team behaviors, decision principles, and non-negotiables."),
   ("30-Day Culture Journey", "Standardized formation for every employee and acquired advisor."),
   ("Culture Activation Kit", "Leadership guide, founder stories, employee and client assessments, manager tools, and culture measurements."),
   ("Enterprise Advisor Stewardship Academy", "Standardized advisor training, certification, role play, coaching, and continuing development."),
   ("Advisor Stewardship Competency Dashboard", "Shows leadership which advisors can actually deliver the promised experience."),
  ]),
  ("B", "Standardize the Family Experience", [
   ("Enterprise Client Experience Standards", "Defines what every client tier is guaranteed to receive."),
   ("Family Stewardship Journey Library", "Enterprise access to the 225-journey system."),
   ("Enterprise Personalization Engine", "Generates firm-approved, advisor-personalized, family-specific experiences."),
   ("RIA Family Experience Playbook", "Defines exactly how assessment, journey, meeting, action, and follow-up should occur."),
   ("Family Stewardship Annual Calendar", "Creates a firm-wide cadence for assessments, family reviews, journeys, meetings, and impact reporting."),
  ]),
  ("C", "Protect Relationships", [
   ("Relationship Retention Dashboard", "Enterprise view of vulnerable client relationships."),
   ("Great Relationship Transfer Score", "Measures the firm's readiness for generational wealth transition."),
   ("Multigenerational Coverage Dashboard", "Shows G1, G2, and G3 relationships across the firm."),
   ("Relationship Concentration Risk Map", "Identifies AUM dependent on one advisor, founder, spouse relationship, or generation."),
   ("Top 100 Family Risk Map", "Prioritizes the firm's most economically and relationally significant households."),
  ]),
  ("D", "M&A Integration", [
   ("Acquisition Culture Integration Kit", "Helps acquired teams adopt the new firm's culture without destroying what clients valued."),
   ("Acquired Family Relationship Audit", "Answers what relationships the firm actually inherited."),
   ("100-Day Relationship Retention Plan", "Prescribes actions immediately following an acquisition."),
   ("Founder Relationship Transfer Plan", "Systematically transfers trust from selling founder to team and enterprise."),
   ("Acquisition Relationship Dashboard", "Tracks retention, spouse engagement, next-generation engagement, journey participation, and relationship depth after closing."),
  ]),
  ("E", "Leadership Intelligence & Economics", [
   ("RIA Stewardship Intelligence Dashboard", "CEO view combining culture, advisor capability, family engagement, multigenerational coverage, and relationship risk."),
   ("Client Experience Consistency Score", "Determines whether families receive the same core experience regardless of advisor or office."),
   ("Advisor Capacity & AI Productivity Dashboard", "Measures where AI saves time and whether the recovered capacity is reinvested in relationships."),
   ("Family Impact Enterprise Report", "Aggregates non-investment outcomes: family meetings, heirs engaged, journeys completed, generosity conversations, succession milestones, and legacy work."),
   ("Relationship Equity Index", "Estimates the depth, breadth, continuity, and transferability of the firm's client relationships."),
  ]),
 ]),
]

# ---------------- build flat entry list ----------------

entries = []
cats = []
for cn, cname, cq, js in JOURNEYS:
    assert len(js) == 15, (cname, len(js))
    ids = []
    for i, (t, s, flag) in enumerate(js):
        eid = "j" + str(cn) + "-" + str(i + 1)
        entries.append({"id": eid, "kind": "journey", "n": i + 1, "t": t, "s": s, "src": flag,
                        "grp": "c" + str(cn), "grpName": cname})
        ids.append(eid)
    cats.append({"k": "c" + str(cn), "n": cn, "name": cname, "q": cq, "ids": ids})

groups = []
for gk, gname, gpromise, secs in TOOLS:
    sections = []
    total = 0
    for sk, sname, items in secs:
        ids = []
        for i, (t, d) in enumerate(items):
            eid = "t" + gk[0] + str(len(entries))
            entries.append({"id": eid, "kind": "tool", "n": total + i + 1, "t": t, "s": d, "src": 1,
                            "grp": "g" + gk, "grpName": gname})
            ids.append(eid)
        total += len(items)
        sections.append({"k": sk, "name": sname, "ids": ids})
    groups.append({"k": "g" + gk, "name": gname, "promise": gpromise, "user": gk,
                   "sections": sections, "count": total})

jcount = sum(1 for e in entries if e["kind"] == "journey")
tcount = sum(1 for e in entries if e["kind"] == "tool")
drafted = sum(1 for e in entries if e["kind"] == "journey" and e["src"] == 0)
supplied = jcount - drafted
assert jcount == 225, jcount
assert tcount == 125, tcount
assert supplied + drafted == 225

STATS = {"journeys": jcount, "tools": tcount, "drafted": drafted, "supplied": supplied,
         "cats": len(cats), "sessions": (jcount + tcount) * 4, "days": jcount * 30,
         "entries": jcount + tcount}

print("journeys", jcount, "tools", tcount, "drafted", drafted, "supplied", supplied)
print("sessions", STATS["sessions"], "days", STATS["days"])

html = open("/home/claude/template.html", encoding="utf-8").read()
html = html.replace("/*__ENTRIES__*/", json.dumps(entries, ensure_ascii=False))
html = html.replace("/*__CATS__*/", json.dumps(cats, ensure_ascii=False))
html = html.replace("/*__GROUPS__*/", json.dumps(groups, ensure_ascii=False))
html = html.replace("/*__STATS__*/", json.dumps(STATS, ensure_ascii=False))
open("/mnt/user-data/outputs/can-library-clickable.html", "w", encoding="utf-8").write(html)
print("wrote", len(html), "bytes")
