"""Disciplines 11-20: the ten new disciplines, 20 courses each."""

D2 = [
("11", "Apologetics and Worldview", "Giving a reason, with gentleness and respect",
 [("Why Apologetics", "giving a reason with gentleness"),
  ("Does God Exist", "the classic arguments in plain language"),
  ("Is the Bible Reliable", "manuscripts, canon, and archaeology"),
  ("Did the Resurrection Happen", "the historical case"),
  ("Worldview Basics", "the four questions every worldview answers")],
 [("Suffering and the Goodness of God", "the objection that actually bites"),
  ("Science and Faith", "the real relationship and the false war"),
  ("Other Religions", "understanding before responding"),
  ("Secularism and the Nones", "the dominant worldview of your neighbors"),
  ("Sexuality, Identity, and the Christian Story", "engaging with clarity and care")],
 [("Presuppositional, Classical, Evidential", "the schools compared"),
  ("The New Atheism and Its Aftermath", "where the argument has moved"),
  ("Deconstruction", "taking doubt seriously without losing the faith"),
  ("Cults and Distortions", "recognizing what departs from orthodoxy"),
  ("Public Apologetics", "writing and speaking to a skeptical room")],
 [("Hosting a Skeptics Forum", "designing a room for honest questions"),
  ("Training a Team to Answer", "reproducing the reasoning"),
  ("Apologetics With Your Own Children", "the household version"),
  ("Case Study Lab", "real conversations, transcribed and reviewed"),
  ("Capstone: An Apologetics Series", "taught, recorded, and assessed")]),

("12", "Biblical Language Literacy", "The tools track: real gain, honest limits, no bluffing",
 [("What You Gain and What You Cannot Claim", "honest limits without Greek and Hebrew"),
  ("The Greek Alphabet and Sight-Reading", "enough to follow along"),
  ("The Hebrew Alphabet and Sight-Reading", "enough to follow along"),
  ("Using an Interlinear Responsibly", "the tool's actual purpose"),
  ("Lexicons and Concordances", "how to look up a word without ruining it")],
 [("Greek Grammar for English Bible Readers", "tense, voice, mood, and why it matters"),
  ("Hebrew Poetry and Parallelism", "structure you can see in translation"),
  ("Semantic Range", "why \u201cthe Greek means\u201d is usually wrong"),
  ("Comparing Translations", "what a variant reading actually indicates"),
  ("Software Fluency", "searching, filtering, and not being fooled by results")],
 [("Textual Criticism, Plainly", "footnotes explained without anxiety"),
  ("Discourse Analysis in Translation", "following the author's structure"),
  ("Verbal Aspect and the Old Debates", "what the argument is actually about"),
  ("Idiom, Metaphor, and Cultural Distance", "translating meaning, not words"),
  ("Evaluating a Commentary's Language Claims", "reading the experts critically")],
 [("Teaching a Word Study Without Overreach", "the responsible version"),
  ("Optional Track A: First-Year Greek", "the long road, if you want it"),
  ("Optional Track B: First-Year Hebrew", "the long road, if you want it"),
  ("Coaching Others in Tool Use", "reproducing the discipline"),
  ("Capstone: A Tool-Based Exegesis", "submitted and reviewed")]),

("13", "Discipleship and Small Group Ministry", "The home discipline: how formation actually travels",
 [("What a Disciple Is", "the definition everything else depends on"),
  ("The Master Plan", "how Jesus actually made disciples"),
  ("Life on Life", "the irreducible relational core"),
  ("Starting a Group", "the first six weeks"),
  ("Facilitation", "asking, waiting, and not teaching too much")],
 [("Group Covenant and Culture", "the agreements that make depth possible"),
  ("The Difficult Group", "dominators, silence, and drift"),
  ("Care Inside the Group", "what the table can carry"),
  ("Multiplication", "why groups must birth groups"),
  ("Curriculum Selection and Adaptation", "choosing and reshaping content")],
 [("Models of Small Group Ministry", "free market, campaign, cell, and hybrid"),
  ("Assessing Group Health", "measuring formation, not attendance"),
  ("Leader Pipelines", "apprenticeship as the default"),
  ("Groups and the Whole Church", "alignment without control"),
  ("Discipleship Across Cultures and Generations", "one gospel, many tables")],
 [("Coaching Group Leaders", "the second tier of multiplication"),
  ("Designing a Discipleship Pathway", "the whole-church map"),
  ("Writing a Six-Session Study", "from idea to leader's guide"),
  ("Launching a Churchwide Campaign", "the alignment moment"),
  ("Capstone: A Discipleship System", "designed, piloted, and reviewed")]),

("14", "Marriage, Family, and Home Formation", "The household as the primary classroom",
 [("Marriage as Covenant", "the biblical shape"),
  ("Communication and Conflict", "the skills most couples never learned"),
  ("Money, Sex, and Time", "the three recurring fault lines"),
  ("Parenting as Discipleship", "the home as first classroom"),
  ("Family Worship", "simple practices that hold")],
 [("Singleness and Wholeness", "a full theology, not a waiting room"),
  ("Blended Families", "grace in complexity"),
  ("Divorce, Remarriage, and the Church", "the hard questions handled honestly"),
  ("Caring for Aging Parents", "the sandwich generation"),
  ("Family Systems Basics", "why patterns repeat")],
 [("A Theology of the Household", "from the patriarchs to the New Testament family"),
  ("Sexual Integrity and Formation", "purity, pornography, and repair"),
  ("Infertility, Loss, and Adoption", "the griefs the church often misses"),
  ("Legacy and Generational Transfer", "passing on more than assets"),
  ("Abuse in the Home", "recognizing, reporting, and protecting")],
 [("Leading a Marriage Group", "facilitation with high stakes"),
  ("Premarital and Marriage Mentoring", "training lay couples"),
  ("Designing a Family Ministry Pathway", "birth through launch"),
  ("Family Conversation Design", "writing prompts that actually get used"),
  ("Capstone: A Family Formation Plan", "built, piloted, and reviewed")]),

("15", "Worship and the Church Gathered", "Why we assemble, and what the hour is doing to us",
 [("Why We Gather", "a theology of assembly"),
  ("Elements of Worship", "word, table, song, prayer, giving, sending"),
  ("The Church Calendar", "Advent to Pentecost, and why it forms us"),
  ("Baptism and the Lord's Supper", "meaning and practice"),
  ("Planning a Service", "the shape of an hour")],
 [("Music and the Congregation", "singability, theology, and taste"),
  ("Prayer in Public", "writing and leading corporate prayer"),
  ("Scripture Read Aloud", "the neglected element"),
  ("Weddings and Funerals", "the services that carry the most weight"),
  ("Technology in Worship", "sound, screens, and the streaming question")],
 [("A History of Christian Worship", "from synagogue to sanctuary"),
  ("Sacramental Traditions Compared", "an honest map"),
  ("Liturgy and Formation", "how repetition shapes belief"),
  ("Worship and Culture", "indigenous forms and imported ones"),
  ("When Worship Becomes Performance", "diagnosing the drift")],
 [("Leading a Worship Planning Team", "collaboration across disciplines"),
  ("Writing Liturgy for Your Church", "original and rooted"),
  ("Small Group Worship", "what a living room can hold"),
  ("Seasonal Series Design", "Advent, Lent, and the churchwide moment"),
  ("Capstone: A Complete Worship Season", "planned, executed, and reviewed")]),

("16", "Christian Ethics and Cultural Engagement", "How Christians decide, under pressure",
 [("How Christians Decide", "the sources of moral authority"),
  ("The Ten Commandments", "still the framework"),
  ("Truth-Telling and Integrity", "the ethics of ordinary speech"),
  ("Work, Rest, and Vocation", "the ethics of an ordinary week"),
  ("Neighbor Love", "the ethic that reorders everything")],
 [("Life Ethics", "beginning and end of life questions"),
  ("Sexual Ethics", "the historic Christian position, taught clearly"),
  ("Wealth, Poverty, and Justice", "the Bible's most repeated ethical theme"),
  ("Race and Reconciliation", "history, Scripture, and honest repair"),
  ("Politics and the Christian", "engagement without capture")],
 [("Ethical Frameworks Compared", "virtue, duty, consequence, and narrative"),
  ("Bioethics and Technology", "fertility, gene editing, and enhancement"),
  ("War, Violence, and Peacemaking", "the historic Christian positions"),
  ("Creation Care", "dominion, stewardship, and the current debate"),
  ("Institutional Ethics", "when organizations sin")],
 [("Teaching Ethics Without Culture War", "facilitation under pressure"),
  ("Case Study Lab", "real dilemmas, reasoned through in writing"),
  ("Writing an Ethical Position Paper", "argument with charity"),
  ("Guiding a Church Through a Contested Issue", "process design"),
  ("Capstone: An Ethics Series", "taught and defended orally")]),

("17", "Church Planting and Multiplication", "From addition to multiplication",
 [("Why Plant", "the biblical and strategic case"),
  ("Assessing the Planter", "calling, capacity, and character"),
  ("Reading a Community", "demography, culture, and need"),
  ("The Core Team", "gathering the first twelve"),
  ("Models of Planting", "from house church to large launch")],
 [("Funding a Plant", "partnership, bivocational work, and sustainability"),
  ("Preview to Launch", "the first ninety days"),
  ("Systems From Day One", "groups, care, giving, and kids"),
  ("The Second Year", "where most plants stall"),
  ("Planter Care", "isolation, marriage, and burnout")],
 [("Movements in History", "how the gospel has spread rapidly"),
  ("Multiplication Math", "from addition to multiplication"),
  ("Networks and Denominations", "belonging while planting"),
  ("Urban, Rural, and Suburban Realities", "one method will not travel"),
  ("Revitalization as Planting", "replanting a dying church")],
 [("Coaching a Planter", "the supervisory role"),
  ("Becoming a Sending Church", "the mother-church playbook"),
  ("Writing a Church Plant Prospectus", "the document that raises support"),
  ("Assessing a Plant's Health", "honest metrics in the first five years"),
  ("Capstone: A Planting or Revitalization Plan", "written and reviewed")]),

("18", "Next Generation Ministry", "Birth through launch, and the years the church loses people",
 [("Why the Next Generation Leaves", "the research, honestly read"),
  ("Children's Ministry Foundations", "teaching the very young"),
  ("Youth Ministry Foundations", "adolescence and faith"),
  ("Family-Equipping Models", "partnering with parents, not replacing them"),
  ("Safety and Protection", "policy, screening, and vigilance")],
 [("Teaching Children the Whole Bible", "not only the felt-board stories"),
  ("Teenagers and Doubt", "creating room for questions"),
  ("Digital Natives", "phones, identity, and attention"),
  ("Special Needs Inclusion", "welcoming every family"),
  ("College and Launch", "the years the church loses most people")],
 [("Faith Development Theory", "how belief matures by stage"),
  ("Youth Culture Analysis", "reading a moving target"),
  ("Mental Health in Adolescence", "recognizing, responding, and referring"),
  ("Intergenerational Church", "the alternative to age segregation"),
  ("Volunteer Recruitment for Next Gen", "the hardest ask in the church")],
 [("Building a Next Gen Team", "structure and supervision"),
  ("Curriculum Design for Children", "age-appropriate depth"),
  ("Curriculum Design for Youth", "honesty and challenge"),
  ("A Birth-to-Launch Pathway", "the eighteen-year plan"),
  ("Capstone: A Next Gen Strategy", "built, piloted, and reviewed")]),

("19", "Stewardship, Generosity, and Church Finance", "The subject Jesus taught most and churches teach least",
 [("God Owns It All", "the ownership question underneath everything"),
  ("Money in the Teaching of Jesus", "his most frequent subject"),
  ("Giving", "tithe, offering, and the heart behind both"),
  ("Debt and Contentment", "the personal side of stewardship"),
  ("Talking About Money in Church", "overcoming the flinch")],
 [("Household Budgeting as Discipleship", "practice, not theory"),
  ("Generosity Pathways", "moving a congregation without pressuring it"),
  ("Church Budgeting", "priorities made visible"),
  ("Financial Controls and Integrity", "the safeguards that protect trust"),
  ("Capital Campaigns", "vision, not fundraising")],
 [("A Theology of Wealth and Poverty", "the Bible's uncomfortable range"),
  ("Planned Giving and Legacy", "estates, wills, and generational transfer"),
  ("Nonprofit Finance and Compliance", "the rules churches must know"),
  ("Business as Mission", "capital, calling, and kingdom return"),
  ("Wealth and the Soul", "pastoral care for the affluent")],
 [("Leading a Stewardship Ministry", "structure and volunteers"),
  ("Coaching a Household Toward Freedom", "the lay financial mentor"),
  ("Designing a Generosity Campaign", "the churchwide moment"),
  ("Financial Discipleship Curriculum Design", "writing the study"),
  ("Capstone: A Stewardship Strategy", "built, costed, and reviewed")]),

("20", "Digital Discernment, AI, and Media", "The formation happening while no one is teaching",
 [("Attention as a Spiritual Issue", "what the feed is forming"),
  ("A Theology of Technology", "tools, idols, and the image of God"),
  ("Social Media and the Soul", "comparison, outrage, and vanity"),
  ("Truth, Rumor, and Discernment Online", "testing what you read"),
  ("The Household Media Rule", "practices for a connected home")],
 [("Artificial Intelligence, Plainly Explained", "what it is and what it is not"),
  ("AI and Human Dignity", "the image of God under pressure"),
  ("Using AI in Ministry Responsibly", "study, writing, and the honesty line"),
  ("Digital Community", "what online can and cannot be"),
  ("Pornography and Digital Formation", "the church's hardest silence")],
 [("Media Ecology", "how mediums shape messages"),
  ("Algorithms, Formation, and Desire", "the machinery of habit"),
  ("AI Ethics and the Christian Tradition", "labor, truth, and creation"),
  ("Synthetic Media and Trust", "witness in an age of fabrication"),
  ("Digital Ministry Strategy", "presence with purpose")],
 [("Teaching Digital Discernment", "leading a group through the questions"),
  ("Writing a Church Technology and AI Policy", "clarity for staff and volunteers"),
  ("The Church as Publisher", "content, streaming, and the stewardship of attention"),
  ("Coaching Families on Media", "the lay guide role"),
  ("Capstone: A Digital Discernment Series", "taught, recorded, and assessed")]),
]
