"""Disciplines 01-10: the reconstructed original ten, each expanded 10 -> 20."""

D1 = [
("01", "Old Testament", "The story Israel told, and the God who told it",
 [("The Story Before the Story", "reading the Old Testament as one narrative"),
  ("Genesis: Beginnings", "creation, fall, covenant, and the family God chose"),
  ("Exodus and Sinai", "deliverance, law, and the God who dwells with a people"),
  ("The Land and the Judges", "Joshua, Judges, Ruth, and the cost of forgetting"),
  ("Kings, Prophets, Exile", "the rise and fall of Israel's monarchy")],
 [("The Pentateuch Up Close", "Leviticus, Numbers, and Deuteronomy for ordinary readers"),
  ("Wisdom for Real Life", "Proverbs, Job, Ecclesiastes, and the fear of the Lord"),
  ("The Psalms as a School of Prayer", "praise, lament, and the honest heart"),
  ("The Major Prophets", "Isaiah, Jeremiah, Ezekiel, and the word that will not return empty"),
  ("The Twelve", "the Minor Prophets and the anatomy of covenant faithfulness")],
 [("Covenant and Kingdom", "tracing the structural spine of the Old Testament"),
  ("Sacrifice, Temple, Priest", "the theology underneath the ritual"),
  ("Israel Among the Nations", "ancient Near Eastern context without losing the text"),
  ("The Hard Passages", "violence, holy war, and reading honestly"),
  ("Christ in the Old Testament", "typology done carefully")],
 [("Teaching a Book of the Old Testament", "a six-week series you actually build"),
  ("Preaching Narrative", "how Old Testament stories preach"),
  ("The Old Testament in the New", "how the apostles read their Bible"),
  ("A Whole-Canon Reading Plan", "designing a year in the Old Testament for a group"),
  ("Capstone: An Old Testament Book", "taught, recorded, and assessed")]),

("02", "New Testament", "One Jesus, four portraits, and the letters that formed the church",
 [("How the New Testament Came to Us", "canon, transmission, and confidence"),
  ("The World Jesus Entered", "Second Temple Judaism and Roman rule"),
  ("The Four Gospels", "one Jesus, four portraits"),
  ("Acts: The Church in Motion", "Jerusalem to Rome"),
  ("Reading the Letters", "occasion, audience, and argument")],
 [("Romans", "the gospel laid out"),
  ("The Corinthian Correspondence", "a messy church and a patient apostle"),
  ("The Prison Letters", "Ephesians, Philippians, Colossians, Philemon"),
  ("Hebrews and the General Letters", "endurance, faith, and warning"),
  ("Revelation Without Fear", "apocalyptic literature for ordinary Christians")],
 [("The Sermon on the Mount", "the ethics of the kingdom"),
  ("The Parables", "how Jesus taught and why it still unsettles"),
  ("Paul's Theology in Its Own Terms", "union with Christ, law, and Israel"),
  ("The Synoptic Question, Plainly", "what the differences do and do not mean"),
  ("Jesus and the Resurrection", "historical claim and pastoral weight")],
 [("Teaching a New Testament Letter", "building a six-week series"),
  ("Preaching the Gospels", "narrative, dialogue, and the reveal"),
  ("Expository Teaching Lab", "one passage, start to finish, with feedback"),
  ("A Year in the New Testament", "group reading plan design"),
  ("Capstone: A New Testament Book", "taught, recorded, and assessed")]),

("03", "Hermeneutics and Bible Study Method", "The skill that makes every other discipline possible",
 [("What Reading Well Requires", "the reader, the text, and the Spirit"),
  ("Genre Matters", "law, narrative, poetry, prophecy, letter, apocalypse"),
  ("Context Before Application", "the three contexts every verse sits inside"),
  ("Observation, Interpretation, Application", "the inductive method"),
  ("Common Ways We Get It Wrong", "the ten most frequent reading errors")],
 [("Word Studies Without Word Fallacies", "lexicons used honestly"),
  ("Following an Argument", "discourse, structure, and the flow of thought"),
  ("Cross-Reference Discipline", "using Scripture to interpret Scripture"),
  ("From Text to Timeless Truth", "the bridge principle"),
  ("From Truth to Today", "application that is not moralism")],
 [("The History of Interpretation", "how the church has read, and misread"),
  ("Biblical Theology as Method", "the storyline as interpretive control"),
  ("Systematic and Biblical Theology in Conversation", "keeping both honest"),
  ("Reading With the Church", "creeds, confessions, and community"),
  ("Reading Across Cultures", "what other readers see that we miss")],
 [("Building a Study Guide", "writing questions that actually open a text"),
  ("Leading Inductive Study at a Table", "facilitation as interpretation"),
  ("Assessing Someone Else's Interpretation", "the reader's rubric"),
  ("Teaching Others to Read", "reproducing the skill, not just the content"),
  ("Capstone: An Original Study Guide", "written, submitted, and reviewed")]),

("04", "Systematic Theology", "What the church believes, why it matters, and where it divides",
 [("Why Doctrine Matters", "theology as the church's memory"),
  ("Revelation and Scripture", "how God speaks and what that means"),
  ("God: One and Three", "the doctrine of the Trinity for ordinary believers"),
  ("Creation and Providence", "the world God made and still governs"),
  ("Humanity, Sin, and the Fall", "what went wrong and how deep it goes")],
 [("The Person of Christ", "fully God, fully man, one person"),
  ("The Work of Christ", "atonement, resurrection, and what was accomplished"),
  ("The Holy Spirit", "person, presence, and power"),
  ("Salvation", "grace, faith, justification, sanctification, perseverance"),
  ("The Church and the Sacraments", "what the church is and what it does")],
 [("Last Things", "death, judgment, resurrection, and the new creation"),
  ("Election and Human Freedom", "the debate, charitably mapped"),
  ("A Theology of Suffering and Evil", "the hardest doctrine"),
  ("Where Traditions Divide", "an honest map of evangelical disagreement"),
  ("Doctrine and Discipleship", "how belief forms behavior")],
 [("Teaching Doctrine to a Small Group", "making theology land"),
  ("Writing a Statement of Faith", "clarity, charity, and boundaries"),
  ("Diagnosing Bad Theology in the Room", "pastoral triage"),
  ("Catechesis for Adults", "recovering the church's oldest teaching tool"),
  ("Capstone: A Doctrinal Series", "written, taught, and defended")]),

("05", "Church History", "The communion of saints as your faculty",
 [("Why History Is Discipleship", "the dead as teachers"),
  ("The Apostolic and Persecuted Church", "the first three centuries"),
  ("Councils and Creeds", "how the church said what it believed"),
  ("The Medieval Church", "monastics, mystics, scholastics, and reform movements"),
  ("The Reformation", "the recovery and the rupture")],
 [("Puritans, Pietists, and the Awakenings", "heart religion in the modern world"),
  ("The Missionary Century", "the gospel goes global"),
  ("American Christianity", "revival, division, and civil religion"),
  ("The Twentieth Century", "fundamentalism, evangelicalism, and the global South"),
  ("The Church in the Last Fifty Years", "movements, megachurch, and decline")],
 [("Heresy and Orthodoxy", "the recurring errors and how they were answered"),
  ("The African, Asian, and Latin American Church", "history beyond the West"),
  ("Spiritual Awakening", "what revivals have had in common"),
  ("The Church and Power", "patronage, empire, and the cost of proximity"),
  ("Reading a Primary Source", "Augustine, Luther, Wesley, and others in their own words")],
 [("Teaching Church History to a Small Group", "making the dead speak"),
  ("Your Church's Own History", "researching and telling it"),
  ("Learning From Failure", "the church's worst moments, taught honestly"),
  ("Tradition and Innovation", "what to keep and what to change"),
  ("Capstone: A Historical Study", "researched, written, and presented")]),

("06", "Spiritual Formation", "How people actually change, and the practices that carry them",
 [("Formation Is Not Optional", "how people actually change"),
  ("The Practice of Prayer", "beginning, sustaining, and returning"),
  ("Scripture as Food", "meditation, memorization, and the daily habit"),
  ("Sabbath, Silence, and Solitude", "the disciplines of stopping"),
  ("Confession and Repentance", "the ordinary work of honesty")],
 [("Fasting, Simplicity, Generosity", "the disciplines of release"),
  ("Worship as a Way of Life", "the reordering of desire"),
  ("Community as Formation", "why you cannot mature alone"),
  ("Suffering as Formation", "the school no one enrolls in"),
  ("A Rule of Life", "designing a sustainable pattern")],
 [("The History of Spiritual Practice", "the desert, the cloister, the parlor"),
  ("The Anatomy of Sin Patterns", "the seven deadly sins as diagnostic"),
  ("Discernment", "testing the inner voice"),
  ("Formation Across the Lifespan", "how growth changes with age"),
  ("When Formation Stalls", "dryness, dark nights, and plateaus")],
 [("Leading a Formation Group", "facilitating depth without performance"),
  ("Spiritual Direction Basics", "asking better questions"),
  ("Designing a Formation Journey", "a forty-day arc for a church"),
  ("Guarding the Leader's Soul", "the practices leaders skip first"),
  ("Capstone: A Personal Rule of Life", "practiced, journaled, and reviewed")]),

("07", "Preaching and Teaching", "Proclamation as craft, not performance",
 [("What Preaching Is", "proclamation, not performance"),
  ("From Text to Sermon", "the exegetical path"),
  ("Structure", "the shapes a sermon can take"),
  ("Delivery", "voice, body, presence, and nerves"),
  ("The First Sermon", "preparing, preaching, and surviving the feedback")],
 [("Preaching Narrative", "story as argument"),
  ("Preaching the Epistles", "argument as story"),
  ("Preaching Poetry and Wisdom", "image, rhythm, and restraint"),
  ("Illustration", "finding, testing, and earning the analogy"),
  ("Application", "from the pulpit to Monday")],
 [("Series Design", "the arc across weeks"),
  ("Preaching When Unbelievers Are Present", "the two audiences in every room"),
  ("Hard Texts and Hard Weeks", "funerals, crises, and controversy"),
  ("The Ethics of the Pulpit", "attribution, self-disclosure, and manipulation"),
  ("Preaching in a Distracted Age", "attention, brevity, and depth")],
 [("Teaching Around a Table", "the shift from monologue to dialogue"),
  ("Coaching Another Preacher", "feedback that actually helps"),
  ("Building a Teaching Team", "reproducing communicators"),
  ("Your Preaching Portfolio", "six manuscripts, submitted and reviewed"),
  ("Capstone: A Six-Week Series", "preached, recorded, and assessed")]),

("08", "Pastoral Care and Counseling", "Presence, limits, and knowing when to hand off",
 [("The Ministry of Presence", "showing up before speaking"),
  ("Listening", "the most underrated pastoral skill"),
  ("Care and Its Limits", "what a layperson can and cannot carry"),
  ("Hospital, Hospice, and the Bedside", "care at the edges of life"),
  ("Referral", "knowing when and how to hand off")],
 [("Grief and Loss", "accompanying people through the valley"),
  ("Anxiety and Depression", "care that is both biblical and informed"),
  ("Marriage in Trouble", "first conversations and honest limits"),
  ("Addiction and Recovery", "the church's role alongside treatment"),
  ("Crisis Care", "risk, disclosure, and mandatory reporting")],
 [("Models of Christian Counseling", "the major approaches, fairly compared"),
  ("Trauma-Informed Care", "why the body remembers"),
  ("Shame and Identity", "the deepest pastoral terrain"),
  ("Confidentiality and Ethics", "the rules that protect everyone"),
  ("Caring for the Caregiver", "secondary trauma and sustainability")],
 [("Building a Care Team", "structure, training, and oversight"),
  ("Supervised Care Practicum", "real situations, real supervision"),
  ("Care in the Small Group", "what a table can hold"),
  ("Writing a Church Care Policy", "protection, clarity, and follow-through"),
  ("Capstone: A Supervised Care Portfolio", "logged, reviewed, and signed off")]),

("09", "Evangelism and Missions", "The mandate, the conversation, and the world",
 [("The Gospel in One Page", "what we are actually announcing"),
  ("Your Story and His", "testimony without formula"),
  ("Conversations, Not Presentations", "evangelism as ordinary talk"),
  ("Objections People Actually Raise", "the ten most common"),
  ("The Great Commission", "the mandate and its scope")],
 [("Hospitality as Mission", "the table as the front door"),
  ("Workplace Witness", "faithfulness where you already are"),
  ("Reaching Neighbors and Nations", "local and global as one calling"),
  ("Cross-Cultural Basics", "culture, worldview, and humility"),
  ("Short-Term Missions Done Right", "help that actually helps")],
 [("The History of Mission", "what worked and what harmed"),
  ("Contextualization", "the line between translation and compromise"),
  ("Unreached Peoples", "the data and the strategy"),
  ("Church and Agency", "how sending actually works"),
  ("Persecution and the Global Church", "solidarity and realism")],
 [("Leading an Outreach Initiative", "planning, launching, measuring"),
  ("Training Others to Share", "reproducing the skill"),
  ("Designing a Church Mission Strategy", "from calendar to conviction"),
  ("Partnership Ethics", "money, power, and dignity in mission"),
  ("Capstone: A Mission Plan", "built, costed, and reviewed")]),

("10", "Leadership and Church Administration", "The unglamorous half of ministry, taken seriously",
 [("Leadership as Stewardship", "authority under authority"),
  ("Character Before Competence", "the qualification passages"),
  ("Vision and Direction", "naming where you are going"),
  ("Teams", "recruiting, delegating, and letting go"),
  ("Meetings, Calendars, and Systems", "the work no one applauds")],
 [("Volunteers", "the engine of the local church"),
  ("Conflict", "the leader's most frequent task"),
  ("Difficult Conversations", "clarity as kindness"),
  ("Change Management", "leading people through loss"),
  ("Decision Making", "discernment in groups")],
 [("Polity and Governance", "how churches are actually structured"),
  ("Staffing and Supervision", "hiring, reviewing, releasing"),
  ("Budgets and Financial Oversight", "reading the numbers"),
  ("Legal and Risk Basics", "the exposures churches ignore"),
  ("Succession", "planning the handoff before you need it")],
 [("Leading Leaders", "the multiplication tier"),
  ("Coaching and Supervision Skills", "developing others on purpose"),
  ("Assessing Church Health", "instruments and honest metrics"),
  ("A Ministry Development Plan", "your own next three years"),
  ("Capstone: A Leadership Project", "executed, documented, and reviewed")]),
]
